### ISSUE TITLE
Error: package.json export path for ".pnpm/tslib@2.4.0/node_modules/tslib/tslib.js" not found

### ISSUE THREAD

**Issue by sb55555** [pulumi/pulumi#10009]
### What happened?

After upgrade we are not able to run `pulumi up` successfully
```
Diagnostics:
  pulumi:pulumi:Stack (app-web-app-web.dev):
    error: Error: package.json export path for ".pnpm/tslib@2.4.0/node_modules/tslib/tslib.js" not found
        at ModuleMap.get (/home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.2/node_modules/@pulumi/runtime/closure/package.ts:214:19)
        at Object.getModuleFromPath (/home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.2/node_modules/@pulumi/runtime/closure/package.ts:263:35)
        at /home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.2/node_modules/@pulumi/runtime/closure/createClosure.ts:1229:19
        at Generator.next (<anonymous>)
        at /home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.2/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.2/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:17:12)
        at captureModuleAsync (/home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.2/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:871:20)
        at /home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.2/node_modules/@pulumi/runtime/closure/createClosure.ts:931:19
        at Generator.next (<anonymous>)
 
    (node:1359) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
    (Use `node --trace-warnings ...` to show where the warning was created)
 
 
```

### Steps to reproduce

```
"@pulumi/pulumi": "~3.35.2",
```

`pulumi up`

### Expected Behavior

It's working when downgrading on this version
```
"@pulumi/pulumi": "~3.24.1",
```

### Actual Behavior

It fails after upgrading pulumi version

### Versions used

CLI          
Version      3.35.2
Go Version   go1.17.11
Go Compiler  gc

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

### Additional context
It seems related to #8893
@dixler this could be of interest

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
> ".pnpm/tslib@2.4.0/node_modules/tslib/tslib.js"

Is it supposed to be `.pnpm`?

**Comment by sb55555** [comment]
@dixler you're right we are using https://pnpm.io/ package manager to manage our project dependencies

**Comment by dixler** [comment]
@sb55555 if it worked on the previous version, I'd assume that the original path it was using would work. Do you mind checking out this version of the code and seeing if it fixes your issue. I don't have a repro locally.

https://github.com/pulumi/pulumi/pull/10023

**Comment by sb55555** [comment]
@dixler unfortunately it's not doing it

```
Diagnostics:
  pulumi:pulumi:Stack (my-api-my-api.dev):
    warning: package.json export path for ".pnpm/tslib@2.4.0/node_modules/tslib/tslib.js" not found
 
    error: Error: Error reading file '/home/nemesis/workspace/nxapp/apps/my-api/src-infra/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open '/home/nemesis/workspace/nxapp/apps/my-api/src-infra/package.json'
        at readFile (/home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.2/node_modules/@pulumi/runtime/closure/codePaths.ts:250:19)
        at computeDependenciesDirectlyFromPackageFile (/home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.2/node_modules/@pulumi/runtime/closure/codePaths.ts:229:22)
        at /home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.2/node_modules/@pulumi/runtime/closure/codePaths.ts:187:36
        at /home/nemesis/workspace/nxapp/node_modules/.pnpm/read-package-tree@5.3.1/node_modules/read-package-tree/rpt.js:162:20
```

**Comment by sb55555** [comment]
@dixler I fixed this error adding here

https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/runtime/closure/package.ts#L166

```
        const key = Object.keys(this.map).filter((k) => srcName.endsWith(k))[0];
        if (key) {
          return this.map[key]
        }
```

so that `.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js` is succesfully resolved against `tslib/tslib.js` in `this.map`

**Comment by sb55555** [comment]
A new error appears then

```
Diagnostics:
  pulumi:pulumi:Stack (my-api-my-api.dev):
    error: Error: Error reading file '/home/nemesis/workspace/nxapp/apps/my-api/src-infra/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open '/home/nemesis/workspace/nxapp/apps/my-api/src-infra/package.json'
        at readFile (/home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.3/node_modules/@pulumi/runtime/closure/codePaths.ts:250:19)
        at computeDependenciesDirectlyFromPackageFile (/home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.3/node_modules/@pulumi/runtime/closure/codePaths.ts:229:22)
        at /home/nemesis/workspace/nxapp/node_modules/.pnpm/@pulumi+pulumi@3.35.3/node_modules/@pulumi/runtime/closure/codePaths.ts:187:36
        at /home/nemesis/workspace/nxapp/node_modules/.pnpm/read-package-tree@5.3.1/node_modules/read-package-tree/rpt.js:162:20
```

im able to bypass the error forcing the path to readPackageTree to my package.json file (monorepo root)  :
https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/runtime/closure/codePaths.ts#L169
`"./../../.."` insted of `"."`.

With theses changes 

I still get a bunch of :
```
Could not include required dependency '@aws-crypto/sha1-browser' in '/home/nemesis/workspace/nxapp/node_modules/@aws-sdk/client-s3'.
Could not include required dependency '@aws-crypto/sha256-browser' in '/home/nemesis/workspace/nxapp/node_modules/@aws-sdk/client-s3'.
Could not include required dependency '@aws-crypto/sha256-js' in '/home/nemesis/workspace/nxapp/node_modules/@aws-sdk/client-s3'.
Could not include required dependency '@aws-sdk/client-sts' in '/home/nemesis/workspace/nxapp/node_modules/@aws-sdk/client-s3'.
Could not include required dependency '@aws-sdk/config-resolver' in '/home/nemesis/workspace/nxapp/node_modules/@aws-sdk/client-s3'.
Could not include required dependency '@aws-sdk/credential-provider-node' in '/home/nemesis/workspace/nxapp/node_modules/@aws-sdk/client-s3'.
Could not include required dependency '@aws-sdk/eventstream-serde-browser' in '/home/nemesis/workspace/nxapp/node_modules/@aws-sdk/client-s3'.
Could not include required dependency '@aws-sdk/eventstream-serde-config-resolver' in '/home/nemesis/workspace/nxapp/node_modules/@aws-sdk/client-s3'.
    ...
```

but overall `pulumi up` is running on the latest version !

Our monorepo/filesystem was working fine with the old version of pulumi what would you advise to make it stable again ?

Cordially

**Comment by sb55555** [comment]
Also we pushed a Lambda to AWS with this fixes, the Lambda is sent to AWS successfully but when it runs in the cloud it fails, it seems like something is not loaded right.

Here is the log, could be related
```
{
    "errorType": "Error",
    "errorMessage": "Cannot find module '.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js'\nRequire stack:\n- /var/task/__index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/__index.js",
        "/var/runtime/UserFunction.js",
        "/var/runtime/Runtime.js",
        "/var/runtime/index.js"
    ],
    "stack": [
        "Error: Cannot find module '.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js'",
        "Require stack:",
        "- /var/task/__index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/Runtime.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:746:27)",
        "    at Module.require (internal/modules/cjs/loader.js:974:19)",
        "    at require (internal/modules/cjs/helpers.js:101:18)",
        "    at /var/task/__index.js:5:21",
        "    at Runtime.__f0 [as handler] (/var/task/__index.js:20:6)",
        "    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:73:25)"
    ]
}
```

**Comment by dixler** [comment]
I'm going to try making a small reproduction.

@sb55555 do you think you could send me a tree view of the lambda deployment archive? I think it could help me get a better idea of what's getting serialized out. if it's too sensitive, I can do without.

**Comment by sb55555** [comment]
@dixler don't know where to find the deployment archive we defined the lambda like this 

```
const lambda = new aws.lambda.CallbackFunction(
  name,
  {
    runtime: 'nodejs14.x',
    callback: async (event: any, context: aws.lambda.Context) => {
      const request = event.Records[0].cf.request;

      console.log('Receiving request for', request.uri);

      if (request.uri.includes('+')) {
        const old = request.uri;
        const allPlus = /\+/g;
        request.uri = request.uri.replace(allPlus, '%2B');
        console.log(`rewriting request from ${old} to ${request.uri}`);
      }

      return request;
    },
  },
  { provider: usEast1AwsProvider },
);
```

**Comment by dixler** [comment]
> @dixler don't know where to find the deployment archive we defined the lambda like this
> 
> ```
> const lambda = new aws.lambda.CallbackFunction(
>   name,
>   {
>     runtime: 'nodejs14.x',
>     callback: async (event: any, context: aws.lambda.Context) => {
>       const request = event.Records[0].cf.request;
> 
>       console.log('Receiving request for', request.uri);
> 
>       if (request.uri.includes('+')) {
>         const old = request.uri;
>         const allPlus = /\+/g;
>         request.uri = request.uri.replace(allPlus, '%2B');
>         console.log(`rewriting request from ${old} to ${request.uri}`);
>       }
> 
>       return request;
>     },
>   },
>   { provider: usEast1AwsProvider },
> );
> ```

like downloading the lambda deployment's zip from aws lambda, unzipping it to a folder, and then running `tree` on that folder.

**Comment by sb55555** [comment]
@dixler good news we solved most of the issues of node_modules deps

following [node-linker=hoisted](https://pnpm.io/npmrc#node-linker)

in `.npmrc`
```
node-linker=hoisted
```

using pnpm in `hoisted` mode makes it compatible with pulumi as of now
```
hoisted - a flat node_modules without symlinks is created. Same as the node_modules created by npm or Yarn Classic. Legitimate reasons to use this setting:
Your tooling doesn't work well with symlinks. A React Native project will most probably only work if you use a hoisted node_modules.
Your project is deployed to a serverless hosting provider. Some serverless providers (for instance, AWS Lambda) don't support symlinks. An alternative solution for this problem is to bundle your application before deployment.
```

we still have the issue of locating the right `package.json` in the root of our monorepo, still using the bypass that we described previously

**Comment by dixler** [comment]
> @dixler good news we solved most of the issues of node_modules deps
> 
> following [node-linker=hoisted](https://pnpm.io/npmrc#node-linker)
> 
> in `.npmrc`
> 
> ```
> node-linker=hoisted
> ```
> 
> using pnpm in `hoisted` mode makes it compatible with pulumi as of now
> 
> ```
> hoisted - a flat node_modules without symlinks is created. Same as the node_modules created by npm or Yarn Classic. Legitimate reasons to use this setting:
> Your tooling doesn't work well with symlinks. A React Native project will most probably only work if you use a hoisted node_modules.
> Your project is deployed to a serverless hosting provider. Some serverless providers (for instance, AWS Lambda) don't support symlinks. An alternative solution for this problem is to bundle your application before deployment.
> ```
> 
> we still have the issue of locating the right `package.json` in the root of our monorepo, still using the bypass that we described previously

the package.json that the serialization code reading is the package.json that defines the exports for the module that it's trying to serialize.

**Comment by sb55555** [comment]
@dixler understood, as we use a monorepo, the package.json is not located within the module being serialized.
 is there a way to specify the path to our package.json on aws.lambda.CallbackFunction ?

**Comment by dixler** [comment]
there seems to be a whole host of issues with monorepos. I'm going to collect them and put them on
- #8865

**Comment by dixler** [comment]
here's a link to the aggregated issues https://github.com/pulumi/pulumi/issues/8865#issuecomment-1172930983

**Comment by sb55555** [comment]
thank you @dixler 

for now we have symlinked our root package.json and node_modules as described here
https://github.com/pulumi/pulumi/issues/2619#issuecomment-636474897

we are able to run `pulumi up` with success its finding the package.json

unfortunately it's trying to pack all of our monorepo dependencies in the lambda archive.

```
    ~ aws:lambda/function:Function: (update)
        [id=reimage-edge-lambda-dfb3c4f]
        [urn=urn:pulumi:my-api.dev::my-api::aws:lambda/function:Function::reimage-edge-lambda]
        [provider=urn:pulumi:my-api.dev::my-api::pulumi:providers:aws::us-east-1-aws-provider::9f969a5e-b657-4b98-aa01-b54182e76b05]
      ~ code                        : archive(assets:55e4a06->5667050) {
          ~ "__index.js"                                                       : asset(text:a16beb9->af48d0d) {
                    ...
                        with (__closure) {
                    return (event, context) => tslib_1.__awaiter(void 0, void 0, void 0, function* () {
                  +         const sharp = require('sharp');
                            const request = event.Records[0].cf.request;
                            console.log('Receiving request for', request.uri);
                    ...
            }
              + "node_modules/@aws-crypto/crc32"                                   : archive(file:8afb9d0) { node_modules/@aws-crypto/crc32 }
              + "node_modules/@aws-crypto/crc32c"                                  : archive(file:0536420) { node_modules/@aws-crypto/crc32c }
              + "node_modules/@aws-crypto/crc32c/node_modules/tslib"               : archive(file:8c1dc3e) { node_modules/@aws-crypto/crc32c/node_modules/tslib }
              + "node_modules/@aws-crypto/ie11-detection"                          : archive(file:0374a1b) { node_modules/@aws-crypto/ie11-detection }
              + "node_modules/@aws-crypto/sha1-browser"                            : archive(file:12e4be9) { node_modules/@aws-crypto/sha1-browser }
              + "node_modules/@aws-crypto/sha256-browser"                          : archive(file:ad69a0d) { node_modules/@aws-crypto/sha256-browser }
              + "node_modules/@aws-crypto/sha256-js"                               : archive(file:5d07a47) { node_modules/@aws-crypto/sha256-js }
              + "node_modules/@aws-crypto/supports-web-crypto"                     : archive(file:64ae811) { node_modules/@aws-crypto/supports-web-crypto }
              + "node_modules/@aws-crypto/util"                                    : archive(file:2fe140a) { node_modules/@aws-crypto/util }
              + "node_modules/@aws-sdk/abort-controller"                           : archive(file:9c71ca4) { node_modules/@aws-sdk/abort-controller }
              + "node_modules/@aws-sdk/chunked-blob-reader"                        : archive(file:34598f7) { node_modules/@aws-sdk/chunked-blob-reader }
              + "node_modules/@aws-sdk/chunked-blob-reader-native"                 : archive(file:ac780fa) { node_modules/@aws-sdk/chunked-blob-reader-native }
              + "node_modules/@aws-sdk/client-s3"                                  : archive(file:646874d) { node_modules/@aws-sdk/client-s3 }
              + "node_modules/@aws-sdk/client-sesv2"                               : archive(file:dc8f2b4) { node_modules/@aws-sdk/client-sesv2 }
              + "node_modules/@aws-sdk/client-sso"                                 : archive(file:34bf1f8) { node_modules/@aws-sdk/client-sso }
              + "node_modules/@aws-sdk/client-sts"                                 : archive(file:4de95c5) { node_modules/@aws-sdk/client-sts }
              + "node_modules/@aws-sdk/config-resolver"                            : archive(file:e825aee) { node_modules/@aws-sdk/config-resolver }
              + "node_modules/@aws-sdk/credential-provider-env"                    : archive(file:6e396d2) { node_modules/@aws-sdk/credential-provider-env }
              + "node_modules/@aws-sdk/credential-provider-imds"                   : archive(file:98399af) { node_modules/@aws-sdk/credential-provider-imds }
              + "node_modules/@aws-sdk/credential-provider-ini"                    : archive(file:a7a4ab4) { node_modules/@aws-sdk/credential-provider-ini }
...
```

here is our lambda
we should only have `sharp` as a dependency in the archive

```
const lambda = new aws.lambda.CallbackFunction(
  name,
  {
    publish: true,
    role: lambdaRole,
    architectures: ['x86_64'],
    memorySize: 128,
    timeout: 5,
    runtime: 'nodejs16.x',
    codePathOptions: {},
    callback: async (event: any, context: aws.lambda.Context) => {
      const sharp = require('sharp');

      const request = event.Records[0].cf.request;

      console.log('Receiving request for', request.uri);

      if (request.uri.includes('+')) {
        const old = request.uri;
        const allPlus = /\+/g;
        request.uri = request.uri.replace(allPlus, '%2B');
        console.log(`rewriting request from ${old} to ${request.uri}`);
      }

      return request;
    },
  },
  { provider: usEast1AwsProvider },
);
```

**Comment by ubeytdemirr** [comment]
Hey guys :) Just encountered with this issue, any update on this?

**Comment by ryankauk** [comment]
Just wanted to chime in, this issue seems directly related to pnpm all together, not just for monorepos.

**Comment by dimas-cyriaco** [comment]
I got this problem too. Not on a monorepo. A normal Nestjs repo with `pnpm`. The problematic package is `uuid` in my case.

**Comment by netra3310** [comment]
Any update on this?

**Comment by ffMathy** [comment]
I get this issue too. Would love to have this resolved.

**Comment by erin-allison** [comment]
I hacked a workaround into my project to bypass this, but when using pnpm, I run into another issue where it can resolve the packages but bundles none of them. This is due to pulumi ignoring directory symlinks, which pnpm utilizes for everything.

```diff
diff --git a/runtime/closure/package.js b/runtime/closure/package.js
index 735896c432f121f772ff42fa66c989b617aff896..916638487b079f9949b47d28e5b6b18cfbfb4263 100644
--- a/runtime/closure/package.js
+++ b/runtime/closure/package.js
@@ -190,7 +190,8 @@ class ModuleMap {
         this.wildcardMap = new WildcardMap(rules);
     }
     get(srcName) {
-        const modPath = this.wildcardMap.get(srcName);
+        const match = /node_modules\/(.+)/.exec(srcName)
+        const modPath = this.wildcardMap.get(match ? match[1] : srcName);
         if (modPath === undefined) {
             throw new Error(`package.json export path for "${srcName}" not found`);
         }
```

The offender for symlinks appears to be here: https://github.com/pulumi/pulumi/blob/4ac9a416b946f1b2bca8352afebf25f644cea30e/sdk/go/common/resource/asset.go#L848-L860

Unfortunately, since it's in go, I can't as easily patch that on the fly.

**Comment by baoduy** [comment]
I go this issue too. Hope the fix will be soon releases
