### ISSUE TITLE
pulumi new fails on AlmaLinux9 container on MacOS X host

### ISSUE THREAD

**Issue by johann-koebbe-vericity** [pulumi/pulumi#10182]
### What happened?

I'm evaluating Pulumi on AlmaLinux9 on a MacOS X 12.4 host via Podman 4.1.1. `pulumi new <projectname>` fails during `pip` and the file reference is `macosx_libfile.py`.

### Steps to reproduce

Create a new project in an AlmaLinux 9 container on MacOS X 12.4 host.

### Expected Behavior

It would work.

### Actual Behavior

It didn't work.

### Versions used

```
=> pulumi version
v3.36.0
```

### Additional context

Intallation Output:

```
=> pulumi new aws-native-python
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name: (amazonmq-rabbitmq)
project description: (A minimal AWS Python Pulumi program) Manage AmazonMQ for RabbitMQ
Created project 'amazonmq-rabbitmq'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
stack name: (dev)
Created stack 'dev'

aws-native:region: The AWS region to deploy into: (us-east-1)
Saved config

Failed to resolve python version command: fork/exec /root/projects/operations/amazonmq-rabbitmq/venv/bin/python: no such file or directory

Installing dependencies...

Creating virtual environment...
Finished creating virtual environment
Updating pip, setuptools, and wheel in virtual environment...
Requirement already satisfied: pip in ./venv/lib/python3.10/site-packages (22.0.4)
Collecting pip
  Using cached pip-22.1.2-py3-none-any.whl (2.1 MB)
Requirement already satisfied: setuptools in ./venv/lib/python3.10/site-packages (58.1.0)
Collecting setuptools
  Downloading setuptools-63.2.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 14.8 MB/s eta 0:00:00
Collecting wheel
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-22.1.2 setuptools-63.2.0 wheel-0.37.1
Finished updating
Installing dependencies in virtual environment...
Collecting pulumi<4.0.0,>=3.0.0
  Downloading pulumi-3.36.0-py2.py3-none-any.whl (165 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.3/165.3 kB 7.2 MB/s eta 0:00:00
Collecting pulumi-aws-native<1.0.0,>=0.8.0
  Downloading pulumi_aws_native-0.19.0.tar.gz (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 16.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting semver~=2.8
  Downloading semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting grpcio~=1.33
  Downloading grpcio-1.47.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 38.4 MB/s eta 0:00:00
Collecting dill~=0.3
  Downloading dill-0.3.5.1-py2.py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.8/95.8 kB 25.5 MB/s eta 0:00:00
Collecting protobuf~=4.21
  Downloading protobuf-4.21.2-cp37-abi3-manylinux2014_x86_64.whl (407 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.8/407.8 kB 41.6 MB/s eta 0:00:00
Collecting six~=1.12
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pyyaml~=5.3
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 29.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      /tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprec
ated, use license_files instead.
        warnings.warn(msg, warning_class)
      running dist_info
      creating /tmp/pip-modern-metadata-nzx7sx3f/PyYAML.egg-info
      writing /tmp/pip-modern-metadata-nzx7sx3f/PyYAML.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-nzx7sx3f/PyYAML.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-modern-metadata-nzx7sx3f/PyYAML.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-nzx7sx3f/PyYAML.egg-info/SOURCES.txt'
      skipping 'yaml/_yaml.c' Cython extension (up-to-date)
      reading manifest file '/tmp/pip-modern-metadata-nzx7sx3f/PyYAML.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-nzx7sx3f/PyYAML.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-nzx7sx3f/PyYAML-5.4.1.dist-info'
      Traceback (most recent call last):
        File "/root/projects/operations/amazonmq-rabbitmq/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/root/projects/operations/amazonmq-rabbitmq/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/projects/operations/amazonmq-rabbitmq/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for
_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/command/dist_info.py", line 42, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 303, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 859, in get_command_obj
          klass = self.get_command_class(command)
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 954, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/root/.pyenv/versions/3.10.5/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
          module = import_module(match.group('module'))
        File "/root/.pyenv/versions/3.10.5/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 26, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/tmp/pip-build-env-27ox900q/overlay/lib/python3.10/site-packages/wheel/macosx_libfile.py", line 41, in <module>
          import ctypes
        File "/root/.pyenv/versions/3.10.5/lib/python3.10/ctypes/__init__.py", line 8, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
error: installing dependencies failed; rerun manually to try again, then run 'pulumi up' to perform an initial deployment: installing dependencies via '/root/projects/opera
tions/amazonmq-rabbitmq/venv/bin/python -m pip install -r requirements.txt': exit status 1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
tried reproing this in docker on linux and was unable to. My terminal output is attached at the bottom.

I think I've seen that error message before might this help?
[stackoverflow](https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul#answer-48045929)

```
% docker run -it almalinux:9 /bin/bash
Unable to find image 'almalinux:9' locally
9: Pulling from library/almalinux
5a7a72386449: Pull complete 
Digest: sha256:0d4234391413396dfb70bfda297f23fb158cd4982be781278164a3169e1ee709
Status: Downloaded newer image for almalinux:9
(failed reverse-i-search)`p': ^C
[root@77dda298cb95 /]# ^C
(reverse-i-search)`': ^C
[root@77dda298cb95 /]# ^C
[root@77dda298cb95 /]# yum install python pulumi
AlmaLinux 9 - AppStream                                                                      3.9 MB/s | 7.0 MB     00:01    
AlmaLinux 9 - BaseOS                                                                         2.8 MB/s | 2.7 MB     00:00    
AlmaLinux 9 - Extras                                                                          28 kB/s |  12 kB     00:00    
No match for argument: pulumi
Error: Unable to find a match: pulumi
[root@77dda298cb95 /]# yum install python
Last metadata expiration check: 0:00:03 ago on Tue Jul 19 21:46:09 2022.
Dependencies resolved.
=============================================================================================================================
 Package                                   Architecture          Version                      Repository                Size
=============================================================================================================================
Installing:
 python-unversioned-command                noarch                3.9.10-2.el9                 appstream                 12 k

Transaction Summary
=============================================================================================================================
Install  1 Package

Total download size: 12 k
Installed size: 23  
Is this ok [y/N]: y
Downloading Packages:
python-unversioned-command-3.9.10-2.el9.noarch.rpm                                           141 kB/s |  12 kB     00:00    
-----------------------------------------------------------------------------------------------------------------------------
Total                                                                                         37 kB/s |  12 kB     00:00     
AlmaLinux 9 - AppStream                                                                      3.0 MB/s | 3.1 kB     00:00    
Importing GPG key 0xB86B3716:
 Userid     : "AlmaLinux OS 9 <packager@almalinux.org>"
 Fingerprint: BF18 AC28 7617 8908 D6E7 1267 D36C B86C B86B 3716
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-9
Is this ok [y/N]: y
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                     1/1 
  Installing       : python-unversioned-command-3.9.10-2.el9.noarch                                                      1/1 
  Verifying        : python-unversioned-command-3.9.10-2.el9.noarch                                                      1/1 

Installed:
  python-unversioned-command-3.9.10-2.el9.noarch                                                                             

Complete!
[root@77dda298cb95 /]# curl -fsSL https://get.pulumi.com | sh
=== Installing Pulumi v3.36.0 ===
+ Downloading https://get.pulumi.com/releases/sdk/pulumi-v3.36.0-linux-x64.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 83.7M  100 83.7M    0     0  7162k      0  0:00:11  0:00:11 --:--:-- 7256k
+ Extracting to /root/.pulumi/bin
+ Adding $HOME/.pulumi/bin to $PATH in /root/.bashrc

=== Pulumi is now installed! 🍹 ===
+ Please restart your shell or add /root/.pulumi/bin to your $PATH
+ Get started with Pulumi: https://www.pulumi.com/docs/quickstart
[root@77dda298cb95 /]# pulumi login --local
bash: pulumi: command not found
[root@77dda298cb95 /]# cd ^C
[root@77dda298cb95 /]# /root/.pulumi/bin/pulumi login --local
Logged in to 77dda298cb95 as root (file://~)
[root@77dda298cb95 /]# /root/.pulumi/bin/pulumi new aws-native-python
error: / is not empty; rerun in an empty directory, pass the path to an empty directory to --dir, or use --force
[root@77dda298cb95 /]# mkdir foobar
[root@77dda298cb95 /]# cd foobar/
[root@77dda298cb95 foobar]# /root/.pulumi/bin/pulumi new aws-native-python
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name: (foobar) 
project description: (A minimal AWS Python Pulumi program) 
Created project 'foobar'

stack name: (dev) 
Created stack 'dev'
Enter your passphrase to protect config/secrets: 
Re-enter your passphrase to confirm: 

aws-native:region: The AWS region to deploy into: (us-east-1) 
Saved config

Failed to resolve python version command: fork/exec /foobar/venv/bin/python: no such file or directory

Installing dependencies...

Creating virtual environment...
Finished creating virtual environment
Updating pip, setuptools, and wheel in virtual environment...
Requirement already satisfied: pip in ./venv/lib/python3.9/site-packages (21.2.3)
Collecting pip
  Downloading pip-22.1.2-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 1.7 MB/s 
Requirement already satisfied: setuptools in ./venv/lib/python3.9/site-packages (53.0.0)
Collecting setuptools
  Downloading setuptools-63.2.0-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 16.2 MB/s 
Collecting wheel
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 53.0.0
    Uninstalling setuptools-53.0.0:
      Successfully uninstalled setuptools-53.0.0
  Attempting uninstall: pip
    Found existing installation: pip 21.2.3
    Uninstalling pip-21.2.3:
      Successfully uninstalled pip-21.2.3
Successfully installed pip-22.1.2 setuptools-63.2.0 wheel-0.37.1
Finished updating
Installing dependencies in virtual environment...
Collecting pulumi<4.0.0,>=3.0.0
  Downloading pulumi-3.36.0-py2.py3-none-any.whl (165 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.3/165.3 kB 4.1 MB/s eta 0:00:00
Collecting pulumi-aws-native<1.0.0,>=0.8.0
  Downloading pulumi_aws_native-0.19.0.tar.gz (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 7.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pyyaml~=5.3
  Downloading PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl (630 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 630.1/630.1 kB 7.4 MB/s eta 0:00:00
Collecting six~=1.12
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting semver~=2.8
  Downloading semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting grpcio~=1.33
  Downloading grpcio-1.47.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 7.0 MB/s eta 0:00:00
Collecting protobuf~=4.21
  Downloading protobuf-4.21.2-cp37-abi3-manylinux2014_x86_64.whl (407 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.8/407.8 kB 8.2 MB/s eta 0:00:00
Collecting dill~=0.3
  Downloading dill-0.3.5.1-py2.py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.8/95.8 kB 13.3 MB/s eta 0:00:00
Collecting parver>=0.2.1
  Downloading parver-0.3.1-py2.py3-none-any.whl (14 kB)
Collecting attrs>=19.2
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 11.6 MB/s eta 0:00:00
Collecting arpeggio~=1.7
  Downloading Arpeggio-1.10.2-py2.py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.9/54.9 kB 12.7 MB/s eta 0:00:00
Building wheels for collected packages: pulumi-aws-native
  Building wheel for pulumi-aws-native (setup.py) ... done
  Created wheel for pulumi-aws-native: filename=pulumi_aws_native-0.19.0-py3-none-any.whl size=4974747 sha256=1af79a6922d879e68d3bc5a0c2bf92dc73709eba33f5dacf82c535a0a65e5356
  Stored in directory: /root/.cache/pip/wheels/ad/1f/e5/79a4dc7d5c96903d4df69620fd700923df8435e9cbabe51cef
Successfully built pulumi-aws-native
Installing collected packages: arpeggio, six, semver, pyyaml, protobuf, dill, attrs, parver, grpcio, pulumi, pulumi-aws-native
Successfully installed arpeggio-1.10.2 attrs-21.4.0 dill-0.3.5.1 grpcio-1.47.0 parver-0.3.1 protobuf-4.21.2 pulumi-3.36.0 pulumi-aws-native-0.19.0 pyyaml-5.4.1 semver-2.13.0 six-1.16.0
Finished installing dependencies
Finished installing dependencies

Your new project is ready to go! 

To perform an initial deployment, run 'pulumi up'

[root@77dda298cb95 foobar]# 
```

**Comment by johann-koebbe-vericity** [comment]
@dixler Thanks for the reply. I will try the StackOverflow idea tomorrow. The part that has me confused is the reference to macosx in the error. Does that seem normal?

**Comment by dixler** [comment]
> @dixler Thanks for the reply. I will try the StackOverflow idea tomorrow. The part that has me confused is the reference to macosx in the error. Does that seem normal?

It might be a combination of the macos host, podman, and the linux container coming together to confuse pip.

**Comment by johann-koebbe-vericity** [comment]
@dixler I decided to spin up an AlmaLinux 9 VM instead of spending time on the container. There were other limitations of working with a container that I needed to get around anyway, and this was the impetus I needed to migrate to a VM. `pulumi new aws-native-python` worked correctly on the VM. This issue can be closed. I won't be pursuing this avenue any further. Thanks a bunch for your involvement. 😃

**Comment by dixler** [comment]
> @dixler I decided to spin up an AlmaLinux 9 VM instead of spending time on the container. There were other limitations of working with a container that I needed to get around anyway, and this was the impetus I needed to migrate to a VM. `pulumi new aws-native-python` worked correctly on the VM. This issue can be closed. I won't be pursuing this avenue any further. Thanks a bunch for your involvement. smiley

np. If someone else hits this error, we can reopen it.
