### ISSUE TITLE
[sdk/python] simplify python program errors

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#10222]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We currently report 3 errors from Python programs that throw an exception. We should report only 1.

### Reproduce

To reproduce `pulumi new python` and:

```python
import pulumi

raise Exception('!')
```

```pulumi preview```

### Current Behavior

```
Previewing update (dev)

View Live: https://app.pulumi.com/t0yv0/python-err/dev/previews/e08cb126-25ea-4c38-9640-15e381ebc32d

     Type                 Name            Plan       Info
 +   pulumi:pulumi:Stack  python-err-dev  create     3 errors
 
Diagnostics:
  pulumi:pulumi:Stack (python-err-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/Users/anton/.nix-profile/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/nix/store/7q3qsarzyffcm2sjb2yhjgy0d3hzdi7y-python3-3.8.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/Users/anton/.nix-profile/bin/pulumi-language-python-exec", line 106, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/nix/store/7q3qsarzyffcm2sjb2yhjgy0d3hzdi7y-python3-3.8.8/lib/python3.8/runpy.py", line 282, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/nix/store/7q3qsarzyffcm2sjb2yhjgy0d3hzdi7y-python3-3.8.8/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 3, in <module>
        raise Exception('!')
    Exception: !
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
 ```

### Desired behavior

Same as before, but 1 error instead of 3, drop the redundant ones.

```
Previewing update (dev)

View Live: https://app.pulumi.com/t0yv0/python-err/dev/previews/e08cb126-25ea-4c38-9640-15e381ebc32d

     Type                 Name            Plan       Info
 +   pulumi:pulumi:Stack  python-err-dev  create     *1 error*
 
Diagnostics:
  pulumi:pulumi:Stack (python-err-dev):
    error: Traceback (most recent call last):
      File "/Users/anton/.nix-profile/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/nix/store/7q3qsarzyffcm2sjb2yhjgy0d3hzdi7y-python3-3.8.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/Users/anton/.nix-profile/bin/pulumi-language-python-exec", line 106, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/nix/store/7q3qsarzyffcm2sjb2yhjgy0d3hzdi7y-python3-3.8.8/lib/python3.8/runpy.py", line 282, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/nix/store/7q3qsarzyffcm2sjb2yhjgy0d3hzdi7y-python3-3.8.8/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 3, in <module>
        raise Exception('!')
    Exception: !
 ```

### Affected area/feature

Possibly Python SDK, Python language provider.

**Comment by Frassle** [comment]
cc @Zaid-Ajaj as your looking at a very similar data flow in dotnet

**Comment by t0yv0** [comment]
I have some trouble installing .NET 6 but if we can repro in .NET please 🙏 link here, nice to consider doing also.

**Comment by dixler** [comment]
context: https://github.com/pulumi/pulumi/issues/9237

**Comment by dixler** [comment]
I have an alternate proposal as python devs skim for Traceback as the leftmost non-whitespace character.

```
Previewing update (dev)

View Live: https://app.pulumi.com/t0yv0/python-err/dev/previews/e08cb126-25ea-4c38-9640-15e381ebc32d

     Type                 Name            Plan       Info
 +   pulumi:pulumi:Stack  python-err-dev  create     3 errors
 
Diagnostics:
  pulumi:pulumi:Stack (python-err-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/anton/.nix-profile/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/nix/store/7q3qsarzyffcm2sjb2yhjgy0d3hzdi7y-python3-3.8.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/Users/anton/.nix-profile/bin/pulumi-language-python-exec", line 106, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/nix/store/7q3qsarzyffcm2sjb2yhjgy0d3hzdi7y-python3-3.8.8/lib/python3.8/runpy.py", line 282, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/nix/store/7q3qsarzyffcm2sjb2yhjgy0d3hzdi7y-python3-3.8.8/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 3, in <module>
        raise Exception('!')
    Exception: !
```
