### ISSUE TITLE
Pulumi CLI fatal error when `main` incorrectly defined in `Pulumi.yaml`

### ISSUE THREAD

**Issue by nebbles** [pulumi/pulumi#10246]
### What happened?

When running `pulumi up`
```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.36.0
Go Version:       go1.18.4
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/Cellar/go/1.18.4/libexec/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x57260a0, 0x6c63090})
        /usr/local/Cellar/go/1.18.4/libexec/src/runtime/panic.go:838 +0x207
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*Context).WithCancelChannel(0x0, 0xc000059c20)
        /private/tmp/pulumi-20220714-87123-ozfc8n/sdk/go/common/resource/plugin/context.go:119 +0x38
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x6cc3838, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/engine/deployment.go:153 +0x1de
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x6cc3838, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/engine/update.go:449 +0x391
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x5e4c9c0, 0xc000af77a0}, 0xc0005112c0, {{0x6cc3838, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, ...}, ...)
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/engine/update.go:193 +0x670
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc00030bef0, {0xc00045b400, 0x39}, ...}, ...)
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/backend/httpstate/backend.go:1099 +0x95b
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc00030bef0, {0xc00045b400, 0x39}, ...}, ...)
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/backend/httpstate/backend.go:1006 +0x41f
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt({_, _}, {_, _}, {_, _}, {0xc00030bef0, {0xc00045b400, 0x39}, {0x0, ...}, ...}, ...)
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/backend/apply.go:116 +0x17a
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc00030bef0, {0xc00045b400, 0x39}, {0x0, ...}, ...}, ...)
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/backend/apply.go:210 +0x13e
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Update(_, {_, _}, {_, _}, {0xc00030bef0, {0xc00045b400, 0x39}, {0x0, 0x0, ...}, ...})
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/backend/httpstate/backend.go:889 +0xc5
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc00030bef0, {0xc00045b400, 0x39}, {0x0, 0x0, 0x0}, ...})
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/backend/stack.go:87 +0xba
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Update(_, {_, _}, {0xc00030bef0, {0xc00045b400, 0x39}, {0x0, 0x0, 0x0}, 0xc0009e9c38, ...})
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/backend/httpstate/stack.go:151 +0x88
main.newUpCmd.func1({{{0x6cc3838, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, 0x0, {0x6cc3838, ...}, ...}, ...})
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/cmd/pulumi/up.go:180 +0xd2c
main.newUpCmd.func3(0x2a?, {0x6cc3838, 0x0, 0x4201645?})
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/cmd/pulumi/up.go:456 +0x63f
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc0005f9180?, {0x6cc3838, 0x0, 0x0})
        /private/tmp/pulumi-20220714-87123-ozfc8n/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc0005f9180, {0x6cc3838, 0x0, 0x0})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005f8c80)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /private/tmp/pulumi-20220714-87123-ozfc8n/pkg/cmd/pulumi/main.go:48 +0x45
```

### Steps to reproduce

The `Pulumi.yaml` file specified a value for `main` which was no longer correct.

I had refactored the repository and there was no longer a file at the expected `main` entrypoint. Removing the `main` variable from `Pulumi.yaml` to resort back to `index.ts` as intended fixed the issue.

### Expected Behavior

If no entry point can be found as defined in the `Pulumi.yaml` configuration file, then the CLI should provide a helpful error to inform the user that there is no file.

### Actual Behavior

See error message above that was printed above when running `pulumi up`

### Versions used

```
CLI          
Version      3.36.0
Go Version   go1.18.4
Go Compiler  gc

Host     
OS       darwin
Version  10.15.7
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Pretty sure this panic was fixed this week with https://github.com/pulumi/pulumi/pull/10211, so the next release shouldn't panic here. But I'll leave this open to check that the error message that should now get returned makes sense.

**Comment by Frassle** [comment]
This now errors out with something like:
```
error: project 'main' could not be read: stat /home/fraser/projects/examplepy/testing: no such file or directory
```
