### ISSUE TITLE
AWS plugin download fails

### ISSUE THREAD

**Issue by pratikgajjar** [pulumi/pulumi#10310]
### What happened?

Pulumi keeps trying to download aws plugin and it fails every time.

### Steps to reproduce

No idea

### Expected Behavior

Pulumi should download plugin and start deployment 

### Actual Behavior

It failed

### Versions used

```
CLI
Version      3.37.2
Go Version   go1.17.12
Go Compiler  gc

Plugins
NAME    VERSION
aws     4.38.1
docker  3.2.0
nodejs  unknown

Host
OS       darwin
Version  12.4
Arch     arm64

This project is written in nodejs: executable='/nix/store/7zdpqkc149lxnakicprrw728px5gi1hk-nodejs-16.14.2/bin/node' version='v16.14.2'

Current Stack: prod

TYPE                                               URN
pulumi:pulumi:Stack                                urn:pulumi:prod::tyrion::pulumi:pulumi:Stack::tyrion-prod
awsx:ecr:Repository                                urn:pulumi:prod::tyrion::awsx:ecr:Repository::tyrion-cr
pulumi:providers:aws                               urn:pulumi:prod::tyrion::pulumi:providers:aws::default_4_15_0
awsx:x:ec2:Vpc                                     urn:pulumi:prod::tyrion::awsx:x:ec2:Vpc::default-vpc
awsx:x:ecs:Cluster                                 urn:pulumi:prod::tyrion::awsx:x:ecs:Cluster::prod-cluster
awsx:x:ecs:FargateService                          urn:pulumi:prod::tyrion::awsx:x:ecs:FargateService::tyrion-fs
awsx:x:ecs:FargateTaskDefinition                   urn:pulumi:prod::tyrion::awsx:x:ecs:FargateTaskDefinition::tyrion-fs
awsx:x:ec2:SecurityGroup                           urn:pulumi:prod::tyrion::awsx:x:ec2:SecurityGroup::tyrion-fs-0
aws:ec2/securityGroup:SecurityGroup                urn:pulumi:prod::tyrion::aws:ec2/securityGroup:SecurityGroup::tyrion-fs-0
aws:ecs/cluster:Cluster                            urn:pulumi:prod::tyrion::aws:ecs/cluster:Cluster::prod-cluster-4af2876
aws:ecr/repository:Repository                      urn:pulumi:prod::tyrion::awsx:ecr:Repository$aws:ecr/repository:Repository::tyrion-cr
aws:ec2/securityGroup:SecurityGroup                urn:pulumi:prod::tyrion::awsx:x:ecs:Cluster$aws:ec2/securityGroup:SecurityGroup::prod-cluster-0
aws:iam/role:Role                                  urn:pulumi:prod::tyrion::aws:iam/role:Role::tyrion-fs-execution
aws:ec2/vpc:Vpc                                    urn:pulumi:prod::tyrion::aws:ec2/vpc:Vpc::default-vpc
awsx:x:ec2:SecurityGroup                           urn:pulumi:prod::tyrion::awsx:x:ecs:Cluster$awsx:x:ec2:SecurityGroup::prod-cluster-0
aws:cloudwatch/logGroup:LogGroup                   urn:pulumi:prod::tyrion::awsx:x:ecs:FargateTaskDefinition$aws:cloudwatch/logGroup:LogGroup::tyrion-fs
aws:iam/role:Role                                  urn:pulumi:prod::tyrion::awsx:x:ecs:FargateTaskDefinition$aws:iam/role:Role::tyrion-fs-task
aws:ecr/lifecyclePolicy:LifecyclePolicy            urn:pulumi:prod::tyrion::awsx:ecr:Repository$aws:ecr/lifecyclePolicy:LifecyclePolicy::tyrion-cr
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:prod::tyrion::awsx:x:ecs:FargateTaskDefinition$aws:iam/rolePolicyAttachment:RolePolicyAttachment::tyrion-fs-task-0cbb1731
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:prod::tyrion::awsx:x:ecs:FargateTaskDefinition$aws:iam/rolePolicyAttachment:RolePolicyAttachment::tyrion-fs-task-b5aeb6b6
aws:ecs/taskDefinition:TaskDefinition              urn:pulumi:prod::tyrion::awsx:x:ecs:FargateTaskDefinition$aws:ecs/taskDefinition:TaskDefinition::tyrion-fs
aws:ecs/service:Service                            urn:pulumi:prod::tyrion::awsx:x:ecs:FargateService$aws:ecs/service:Service::tyrion-fs


Found no pending operations associated with prod

Backend
Name           Pratik
URL            s3://fbi-top-secret/boom
User           pratikgajjar
Organizations

Dependencies:
NAME            VERSION
@pulumi/aws     4.38.1
@pulumi/awsx    0.30.0
@pulumi/pulumi  3.37.2
@types/node     10.17.60

Pulumi locates its logs in /tmp by default
```

### Additional context

```
Downloading plugin: 78.87 MiB / 78.87 MiB [========================] 100.00% 10s
[resource plugin aws-4.15.0] installing
Downloading plugin: 97.68 MiB / 99.80 MiB [========================]  97.87% 11s
Downloading plugin: 97.66 MiB / 99.80 MiB [=========================]  97.86% 8s^C^C^C^C^C^C
Downloading plugin: 97.66 MiB / 99.80 MiB [=========================]  97.85% 7s^C^C^C^C^C^C
Downloading plugin: 97.66 MiB / 99.80 MiB [=========================]  97.86% 8s
Downloading plugin: 97.66 MiB / 99.80 MiB [=========================]  97.85% 7s
Downloading plugin: 97.66 MiB / 99.80 MiB [=========================]  97.86% 7s

================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.37.2
Go Version:       go1.17.12
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            send on closed channel

goroutine 1 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.17.12/x64/src/runtime/debug/stack.go:24 +0x88
main.panicHandler()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x48
panic({0x104586060, 0x104857dc0})
	/Users/runner/hostedtoolcache/go/1.17.12/x64/src/runtime/panic.go:1038 +0x21c
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.loadPlugin(0x1400034eb40, 0x1400197e2c0)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:249 +0xd4
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).LanguageRuntime(0x140006638f0, {0x14000caa848, 0x6})
	/Users/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:372 +0xa0
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).EnsurePlugins(0x140006638f0, {0x140014e6600, 0x4, 0x4}, 0x3)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:415 +0x208
github.com/pulumi/pulumi/pkg/v3/engine.ensurePluginsAreLoaded(0x14000c90ab0, 0x14000a56570, 0x3)
	/Users/runner/work/pulumi/pulumi/pkg/engine/plugins.go:208 +0x48
github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource({0x1048a2130, 0x14001838d80}, {{{0x105801220, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/Users/runner/work/pulumi/pulumi/pkg/engine/update.go:386 +0x90
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(0x14000893900, 0x1400002efc0, {{{0x105801220, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:161 +0x204
github.com/pulumi/pulumi/pkg/v3/engine.update(0x14000893900, 0x1400002efc0, {{{0x105801220, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/Users/runner/work/pulumi/pulumi/pkg/engine/update.go:450 +0x2f8
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x1048a66f0, 0x14001834ba0}, 0x14000893900, {{0x105801220, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, ...}, ...)
	/Users/runner/work/pulumi/pulumi/pkg/engine/update.go:193 +0x508
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).apply(0x140005ffa40, {0x1048be2c8, 0x140000581b8}, {0x103f766fd, 0x6}, {0x1048f8e08, 0x14000c53380}, {0x14000ba0a00, {0x140007a7d80, 0x2d}, ...}, ...)
	/Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:618 +0x6e4
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt({0x1048be2c8, 0x140000581b8}, {0x103f766fd, 0x6}, {0x1048f8e08, 0x14000c53380}, {0x14000ba0a00, {0x140007a7d80, 0x2d}, {0x0, ...}, ...}, ...)
	/Users/runner/work/pulumi/pulumi/pkg/backend/apply.go:116 +0xec
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({0x1048be2c8, 0x140000581b8}, {0x103f766fd, 0x6}, {0x1048f8e08, 0x14000c53380}, {0x14000ba0a00, {0x140007a7d80, 0x2d}, {0x0, ...}, ...}, ...)
	/Users/runner/work/pulumi/pulumi/pkg/backend/apply.go:210 +0xb0
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).Update(0x140005ffa40, {0x1048be2c8, 0x140000581b8}, {0x1048f8e08, 0x14000c53380}, {0x14000ba0a00, {0x140007a7d80, 0x2d}, {0x0, 0x0, ...}, ...})
	/Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:501 +0x1d0
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({0x1048be2c8, 0x140000581b8}, {0x1048f8e08, 0x14000c53380}, {0x14000ba0a00, {0x140007a7d80, 0x2d}, {0x0, 0x0, 0x0}, ...})
	/Users/runner/work/pulumi/pulumi/pkg/backend/stack.go:87 +0x88
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localStack).Update(0x14000c53380, {0x1048be2c8, 0x140000581b8}, {0x14000ba0a00, {0x140007a7d80, 0x2d}, {0x0, 0x0, 0x0}, 0x14000780e28, ...})
	/Users/runner/work/pulumi/pulumi/pkg/backend/filestate/stack.go:76 +0x68
main.newUpCmd.func1({{{0x105801220, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, 0x0, {0x105801220, ...}, ...}, ...})
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:180 +0xcb4
main.newUpCmd.func3(0x14000645180, {0x105801220, 0x0, 0x0})
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:458 +0x518
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000645180, {0x105801220, 0x0, 0x0})
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x48
github.com/spf13/cobra.(*Command).execute(0x14000645180, {0x105801220, 0x0, 0x0})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x14000214000)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x40
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Thank you for your report @pratikgajjar. I suspect #9712 may have introduced this issue, so if you need a workaround - try downgrading to 3.33.2.

I can see `^C^C^C^C^C^C` in your output - does it mean that you are trying to cancel the operation with Ctrl-C? Do you get the same panic on every Pulumi run?

**Comment by pratikgajjar** [comment]
> Do you get the same panic on every Pulumi run?
Yes, everytime

> I can see ^C^C^C^C^C^C in your output - does it mean that you are trying to cancel the operation with Ctrl-C?
Yes, I was trying to stop it since it fails everytime.

**Comment by pratikgajjar** [comment]
It works in ubuntu instance, not working in m1 pro chip macbook

**Comment by mikhailshilkov** [comment]
@pratikgajjar Thank you for your response. Could you please also post the output of a failure without Ctrl-C interruption?

**Comment by Frassle** [comment]
Also can you run `pulumi plugin install resource aws 4.38.1`?

**Comment by Frassle** [comment]
> send on closed channel

That looks like this panic'd _because_ you were cancelling. So echoing Mikhail that a log of this crashing without you trying to cancel would be very useful.

Note that we ought to improve the cancellation such that it cancels cleanly here, rather than panics but I suspect that's totally unrelated to your issues of being able to install plugins at all.

**Comment by pratikgajjar** [comment]
Hi, thank you for being patient. Here it keeps retrying. 

https://github.com/pulumi/pulumi/issues/10310#issuecomment-1207968502

```
➜  pulumi git:(fallback) ✗ pulumi plugin install resource aws 4.38.1
[resource plugin aws-4.38.1] installing
Downloading plugin: 97.67 MiB / 99.80 MiB [========================]  97.87% 50s
warning: Error downloading plugin: write /var/folders/8l/_xp4ll7n4c3dqjxrs8klhkqh0000gn/T/pulumi-plugin-tar132389514: file too large
Will retry in 80ms [1/5]
Downloading plugin: 97.67 MiB / 99.80 MiB [========================]  97.87% 53s
warning: Error downloading plugin: write /var/folders/8l/_xp4ll7n4c3dqjxrs8klhkqh0000gn/T/pulumi-plugin-tar104784105: file too large
Will retry in 160ms [2/5]
Downloading plugin: 7.91 MiB / 99.80 MiB [=>--------------------]   7.93% 00m39s
```

**Comment by pratikgajjar** [comment]
Log from `pulumi up`

```
Previewing update (prod):
Downloading plugin: 97.68 MiB / 99.80 MiB [========================]  97.87% 10s
Downloading plugin: 97.66 MiB / 99.80 MiB [========================]  97.85% 10s
Downloading plugin: 97.68 MiB / 99.80 MiB [========================]  97.87% 10s^C
Downloading plugin: 53.37 MiB / 99.80 MiB [===========>---------]  53.47% 00m05s^C
```

**Comment by Frassle** [comment]
> Hi, thank you for being patient. Here it keeps retrying.

You'll note that there's a retry counter there "Will retry in 80ms [1/5]" it will only retry 5 times before giving up.

Your actual issue is "write /var/folders/8l/_xp4ll7n4c3dqjxrs8klhkqh0000gn/T/pulumi-plugin-tar132389514: file too large"
Seem's there no space in your temp folder to download the plugin to. I'll see if we can catch write errors vs read errors separately here because we only want to retry download issues.

**Comment by pratikgajjar** [comment]
```
➜  pulumi git:(fallback) ✗ just p up
(pulumi up)
Previewing update (prod):
Downloading plugin: 97.67 MiB / 99.80 MiB [========================]  97.87% 49s
Downloading plugin: 97.66 MiB / 99.80 MiB [========================]  97.85% 48s
Downloading plugin: 97.67 MiB / 99.80 MiB [========================]  97.87% 51s
Downloading plugin: 97.66 MiB / 99.80 MiB [========================]  97.86% 49s
Downloading plugin: 97.66 MiB / 99.80 MiB [========================]  97.85% 51s
Downloading plugin: 97.66 MiB / 99.80 MiB [========================]  97.86% 44s

error: could not load plugin for aws provider 'urn:pulumi:prod::tyrion::pulumi:providers:aws::default_4_38_1': no resource plugin 'pulumi-resource-aws' found in the workspace at version v4.38.1 or on your $PATH, install the plugin using `pulumi plugin install resource aws v4.38.1`
error: Recipe `p` failed on line 18 with exit code 255
➜  pulumi git:(fallback) ✗ pulumi plugin install resource aws v4.38.1
[resource plugin aws-4.38.1] installing
Downloading plugin: 97.66 MiB / 99.80 MiB [========================]  97.86% 19s
warning: Error downloading plugin: write /var/folders/8l/_xp4ll7n4c3dqjxrs8klhkqh0000gn/T/pulumi-plugin-tar2906519192: file too large
Will retry in 80ms [1/5]
Downloading plugin: 97.66 MiB / 99.80 MiB [=========================]  97.86% 6s
warning: Error downloading plugin: write /var/folders/8l/_xp4ll7n4c3dqjxrs8klhkqh0000gn/T/pulumi-plugin-tar3318986447: file too large
Will retry in 160ms [2/5]
Downloading plugin: 97.68 MiB / 99.80 MiB [=========================]  97.87% 7s
warning: Error downloading plugin: write /var/folders/8l/_xp4ll7n4c3dqjxrs8klhkqh0000gn/T/pulumi-plugin-tar954663623: file too large
Will retry in 320ms [3/5]
Downloading plugin: 97.68 MiB / 99.80 MiB [=========================]  97.87% 7s
warning: Error downloading plugin: write /var/folders/8l/_xp4ll7n4c3dqjxrs8klhkqh0000gn/T/pulumi-plugin-tar713719867: file too large
Will retry in 640ms [4/5]
Downloading plugin: 97.66 MiB / 99.80 MiB [=========================]  97.85% 7s
warning: Error downloading plugin: write /var/folders/8l/_xp4ll7n4c3dqjxrs8klhkqh0000gn/T/pulumi-plugin-tar3755335009: file too large
Will retry in 1.28s [5/5]
Downloading plugin: 97.66 MiB / 99.80 MiB [=========================]  97.86% 8s
error: [resource plugin aws-4.38.1] downloading from : failed to download plugin: aws-4.38.1: write /var/folders/8l/_xp4ll7n4c3dqjxrs8klhkqh0000gn/T/pulumi-plugin-tar3384323738: file too large

```

I have deleted all data in tmp dir and have sufficient space in disk  263.42 GB Free space. 

Can you please help resolving file too large issue ?

**Comment by Frassle** [comment]
Quick check but can you write a 100MiB file to /var/folders/8l/_xp4ll7n4c3dqjxrs8klhkqh0000gn/T ?

**Comment by Frassle** [comment]
Splunking into the go source code it looks like "file too large" is in response to an EFBIG error from the kernel. Given it looks like its managing to write about 97MiB before failing it doesn't look like this is due to folder limits (EFBIG can be returned if a folder has too many files).
So this looks like either a really odd filesystem which has file limits of like 100MiB, or the partition is full.

For sanity as well as the above suggestion of trying to create a file in the said folder, could you run the install command with full debug logs `-v10 --logtostderr`, we can just check if there's anything odd in those.

**Comment by pratikgajjar** [comment]
Hi @Frassle 

I was able to create the file in given directory. I got the same error while doing `rustup update`. It seems I had set ulimit in my ~/.zshrc which caused this issue. -  [ref](https://www.cyberciti.biz/faq/file-size-limit-exceeded-error-under-linux-and-solution/)

It's working fine now.
