### ISSUE TITLE
Unescaped text reaching the display logic

### ISSUE THREAD

**Issue by samueldudley-xrd** [pulumi/pulumi#10351]
### What happened?

During a `pulumi up` the backend exited with a panic.

### Steps to reproduce

This forms part of our CI run that deploys and destroys infrastructure daily.  We have not encountered this error before so reproduction will likely be difficult. The following command was used when running the pulumi up: 

``` bash
PULUMI_DEBUG_COMMANDS=true pulumi up --skip-preview --yes --event-log $CI_PROJECT_DIR/events-up.json
```

The event log would likely have some useful info in it but unfortunately it was not saved due to the CI job exiting in a panic.

### Expected Behavior

`pulumi up` to work without exiting in a panic.

### Actual Behavior

The stack consists of ~3000+ resources and the panic occurred about an hour into the `pulumi up`. 

```
panic: runtime error: slice bounds out of range [818:35]
goroutine 54 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/diag/colors.colorizeText({0xc000af8a80, 0x346}, {0x1dd2175, 0x5}, 0xffffffffffffffff)
	/home/runner/work/pulumi/pulumi/sdk/go/common/diag/colors/colors.go:181 +0x3ea
github.com/pulumi/pulumi/sdk/v3/go/common/diag/colors.Colorization.Colorize({0x1dd2175, 0x0}, {0xc000af8a80, 0x0})
	/home/runner/work/pulumi/pulumi/sdk/go/common/diag/colors/diag.go:44 +0x85
github.com/pulumi/pulumi/pkg/v3/backend/display.logJSONEvent(0x437500, {{0x1dcfcaf, 0x4}, {0x1d094c0, 0xc0016d1c80}}, {{0x1dd2175, 0x5}, 0x0, 0x0, 0x0, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/display/display.go:85 +0x2de
github.com/pulumi/pulumi/pkg/v3/backend/display.startEventLogger.func1()
	/home/runner/work/pulumi/pulumi/pkg/backend/display/display.go:119 +0x219
created by github.com/pulumi/pulumi/pkg/v3/backend/display.startEventLogger
	/home/runner/work/pulumi/pulumi/pkg/backend/display/display.go:109 +0x254
```

### Versions used

Pulumi was running on a public gitlab runner using the`pulumi/pulumi-python:3.35.3` docker container and using the pulumi.com backend for stack state.

```
CLI          
Version      3.35.3
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.10.0
azure   5.12.0
okta    3.13.0
python  unknown
random  4.8.0
tls     4.6.0

Host     
OS       debian
Version  11.3
Arch     x86_64

This project is written in python: executable='/app/venv/bin/python3' version='3.9.13'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by samueldudley-xrd** [comment]
I am able to replicate this consistently, always with the same error

```
 panic: runtime error: slice bounds out of range [818:35]
goroutine 54 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/diag/colors.colorizeText({0xc006210a80, 0x346}, {0x1dd2175, 0x5}, 0xffffffffffffffff)
	/home/runner/work/pulumi/pulumi/sdk/go/common/diag/colors/colors.go:181 +0x3ea
github.com/pulumi/pulumi/sdk/v3/go/common/diag/colors.Colorization.Colorize({0x1dd2175, 0x0}, {0xc006210a80, 0x0})
	/home/runner/work/pulumi/pulumi/sdk/go/common/diag/colors/diag.go:44 +0x85
github.com/pulumi/pulumi/pkg/v3/backend/display.logJSONEvent(0x437500, {{0x1dcfcaf, 0x4}, {0x1d094c0, 0xc0062453e0}}, {{0x1dd2175, 0x5}, 0x0, 0x0, 0x0, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/display/display.go:85 +0x2de
github.com/pulumi/pulumi/pkg/v3/backend/display.startEventLogger.func1()
	/home/runner/work/pulumi/pulumi/pkg/backend/display/display.go:119 +0x219
created by github.com/pulumi/pulumi/pkg/v3/backend/display.startEventLogger
	/home/runner/work/pulumi/pulumi/pkg/backend/display/display.go:109 +0x254
```

I have a verbosity level 10 log (162MB) and the event log (84MB) which I can share on request but they dont immediately appear to show anything of use. 

I should also note that I have now tried running the pulumi up with the `--color never` argument and the result is exactly the same.

**Comment by Frassle** [comment]
I think I know what's causing this but if you could share the debug log that would help (you can mail it to me <first name>@pulumi.com)

**Comment by Frassle** [comment]
Raised https://github.com/pulumi/pulumi/pull/10354 to at least fix the panic, it won't result in backwards slices anymore. Having said that I think there's probably some bad data getting into the system that resulted in this in the first place, if this fix can make it to the release today it would be good to update and re-run your repro and see if we can work out what the bad data is.

**Comment by samueldudley-xrd** [comment]
Thanks! Having a look at the big binary blob at the bottom of the debug log (where I'm assuming the issue is occuring) it appears to be the content of a zip file that is being uploaded to a S3 bucket:

```python
    self.source_object = aws.s3.BucketObject(
            f"{spoke.alias}:{feature_name}:source-bucket:object",
            bucket=source_bucket.bucket,
            source=pulumi.FileArchive(source_path.as_posix()),
            key="source.zip",
            server_side_encryption="AES256",
            opts=spoke.resource_options(
                parent=source_bucket,
            ),
        )
```

**Comment by Frassle** [comment]
> (where I'm assuming the issue is occuring)

Yup spilling binary data to the logs is pretty suspect. I think the bit actually causing the panic probably didn't get printed to the logs (because it panicked first) but I'm hoping with #10354 we'll be able to see a log line with a stray "%}>" in it.

**Comment by Frassle** [comment]
Reopened to track where this badly formatted text is coming from.

**Comment by SamuelDudley** [comment]
Thanks @Frassle and pulumi team. I'll await the release and get back to you with a complete debug log.

**Comment by samueldudley-xrd** [comment]
Thanks @Frassle and the pulumi team for the quick turnaround. I'll await the release and get back to you with the resulting debug log.

**Comment by Frassle** [comment]
Hey @samueldudley-xrd just to let you know that [v3.38](https://github.com/pulumi/pulumi/releases/tag/v3.38.0) was released yesterday. If you update and give that a run you should be able to get some more logs (and hopefully no panics), if you could send them over to me that would help with tracking down exactly what's wrong here. Thanks.

**Comment by samueldudley-xrd** [comment]
Thanks @Frassle I was on leave last week, but will get the pulumi version update into our next sprint cycle and report back with the results.

**Comment by samueldudley-xrd** [comment]
@Frassle I have sent you an email with the v3.38 event logs attached. The zipped events are 25MB so please let me know if you don't get the file and I will share via dropbox or similar.

Taking a look at the event log I used the following regex `(%\}>)(((?!<\{%).|\n|\r)*)(%\}>)` and identified 
```
I0826 08:00:22.564599      69 eventsink.go:62] eventSink::Debug(<{%reset%}>R�^7�ammg�l�W��v�!l}%}>D�U�X\�w�H �<��ҔJ�FU�|z�
```
Which as expected is in one of those zip file binary blobs.

On another note, your panic fix worked :)

**Comment by Frassle** [comment]
> Taking a look at the event log I used the following regex [(%\}>)(((?!<\{%).|\n|\r)*)(%\}>)](https://regex101.com/r/5oM74X/1) and identified the following single line (line # 1085861):

Ah that'll do it! Thank's looks like we def have some unescaped text reaching the display logic then.
