### ISSUE TITLE
The Pulumi CLI encountered a fatal error. This is a bug!

### ISSUE THREAD

**Issue by Oyelowo** [pulumi/pulumi#10405]
### What happened?

`Pulumi up` throws the error below after downloading the latest golang version
go version:  go1.19 darwin/amd64

```sh
Please enter your desired stack name: 
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.37.2
Go Version:       go1.18.4
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            fatal: A precondition has failed for stack

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.18.4/libexec/src/runtime/debug/stack.go:24 +0x68
main.panicHandler()
        /private/tmp/pulumi-20220729-172-1xfssut/pkg/cmd/pulumi/main.go:29 +0x38
panic({0x106894dc0, 0x1400036aff0})
        /opt/homebrew/Cellar/go/1.18.4/libexec/src/runtime/panic.go:838 +0x204
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /private/tmp/pulumi-20220729-172-1xfssut/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Require(0x98?, {0x10630d62f?, 0x106894dc0?})
        /private/tmp/pulumi-20220729-172-1xfssut/sdk/go/common/util/contract/require.go:26 +0xb4
github.com/pulumi/pulumi/pkg/v3/backend/filestate.stackLockDir({0x0, 0x0})
        /private/tmp/pulumi-20220729-172-1xfssut/pkg/backend/filestate/lock.go:146 +0x40
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).checkForLock(0x14000e484e0, {0x106c6f268, 0x1400012e000}, {0x106c6a738, 0x107a9dd80})
        /private/tmp/pulumi-20220729-172-1xfssut/pkg/backend/filestate/lock.go:61 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).Lock(0x14000e484e0, {0x106c6f268, 0x1400012e000}, {0x106c6a738?, 0x107a9dd80?})
        /private/tmp/pulumi-20220729-172-1xfssut/pkg/backend/filestate/lock.go:107 +0x3c
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).CreateStack(0x14000e484e0, {0x106c6f268, 0x1400012e000}, {0x106c6a738?, 0x107a9dd80}, {0x0, 0x0?})
        /private/tmp/pulumi-20220729-172-1xfssut/pkg/backend/filestate/backend.go:305 +0x58
main.createStack({0x106c7c980, 0x14000e484e0}, {0x106c6a738, 0x107a9dd80}, {0x0, 0x0}, 0x0, {0x0, 0x0})
        /private/tmp/pulumi-20220729-172-1xfssut/pkg/cmd/pulumi/util.go:213 +0x78
main.chooseStack({0x106c7c980, 0x14000e484e0}, 0x1, {{0x10630ef3f, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        /private/tmp/pulumi-20220729-172-1xfssut/pkg/cmd/pulumi/util.go:405 +0x90c
main.requireCurrentStack(0xe8?, {{0x10630ef3f, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...}, ...)
        /private/tmp/pulumi-20220729-172-1xfssut/pkg/cmd/pulumi/util.go:296 +0xac
main.requireStack({0x0?, 0x1400024e338?}, 0xc0?, {{0x10630ef3f, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        /private/tmp/pulumi-20220729-172-1xfssut/pkg/cmd/pulumi/util.go:245 +0x278
main.newUpCmd.func1({{{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x0, 0x0, 0x0, {0x0, ...}, ...}, ...})
        /private/tmp/pulumi-20220729-172-1xfssut/pkg/cmd/pulumi/up.go:84 +0xe8
main.newUpCmd.func3(0x2a?, {0x107a9b588, 0x0, 0x1051beb74?})
        /private/tmp/pulumi-20220729-172-1xfssut/pkg/cmd/pulumi/up.go:458 +0x4ac
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000e18a00?, {0x107a9b588, 0x0, 0x0})
        /private/tmp/pulumi-20220729-172-1xfssut/sdk/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000e18a00, {0x107a9b588, 0x0, 0x0})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x14000c0ac80)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /private/tmp/pulumi-20220729-172-1xfssut/pkg/cmd/pulumi/main.go:48 +0x40

```

### Steps to reproduce

- Download new golang version
- Run `pulumi up`

Machine spec:
Macbook M1 Pro Max, 14 inch, 8TB memory, 64GB RAM, 32GHZ GPU

### Expected Behavior

- Update stack

### Actual Behavior

- `pulumi up` fails

### Versions used

```sh
CLI          
Version      3.37.2
Go Version   go1.18.4
Go Compiler  gc

Plugins
NAME                      VERSION
docker                    3.4.0
kubernetes                3.20.3
kubernetes-ingress-nginx  0.0.9
linode                    3.9.1
nodejs                    unknown
random                    4.8.1

Host     
OS       darwin
Version  12.3.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v18.7.0'

Backend        
Name           Oyelowos-MBP.wlan
URL            file://loginn
User           oyelowo
Organizations  

Dependencies:
NAME                              VERSION
@types/bcrypt                     5.0.0
@types/jest                       28.1.6
@pulumi/kubernetes                3.20.3
eslint                            8.21.0
prompt                            1.3.0
ts-node                           10.9.1
@pulumi/random                    4.8.1
eslint-plugin-n                   15.2.4
patch-package                     6.4.7
@types/ramda                      0.28.15
json-schema-to-ts                 2.5.5
ts-jest                           28.0.7
@types/shelljs                    0.8.11
@types/inquirer                   9.0.0
chalk                             5.0.1
eslint-plugin-promise             6.0.0
eslint-plugin-unicorn             43.0.2
json-to-ts                        1.7.0
@faker-js/faker                   7.4.0
eslint-plugin-unused-imports      2.0.0
inquirer                          9.1.0
@pulumi/pulumi                    3.37.2
eslint-config-standard            17.0.0
@types/lodash-es                  4.17.6
eslint-config-prettier            8.5.0
ramda                             0.28.0
shelljs                           0.8.5
cross-env                         7.0.3
zod                               3.18.0
yargs                             17.5.1
json-ts                           1.6.4
typescript                        4.7.4
@types/uuid                       8.3.4
@types/prompt                     1.1.2
json-schema-to-typescript         11.0.2
lodash-es                         4.17.21
lodash                            4.17.21
mock-stdin                        1.0.0
yaml                              2.1.1
@pulumi/kubernetes-ingress-nginx  0.0.9
cli-progress                      3.11.2
get-port                          6.1.2
@swc/jest                         0.2.22
@typescript-eslint/parser         5.33.0
eslint-plugin-import              2.26.0
@typescript-eslint/eslint-plugin  5.33.0
@swc/core                         1.2.224
@types/cli-progress               3.11.0
eslint-plugin-prettier            4.2.1
jest                              28.1.3
@pulumi/linode                    3.9.1
@types/node                       18.7.1
@types/yargs                      17.0.11
prettier                          2.7.1
@pulumi/kubernetesx               0.1.6
bcrypt                            5.0.1
find-free-port                    2.0.0
uuid                              8.3.2
@pulumi/docker                    3.4.0

Pulumi locates its logs in /var/folders/xp/xnmy9hns4mgc9kzv78jlj8g40000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Hi @Oyelowo great find! This is a legitimate bug. We looked into this today, and I'm going to generate a patch. Unfortunately, the patch won't make it into v3.38.0, but you can expect to see it soon (either in a patch release like v3.38.1 or in about two weeks with v3.39.0).

The bug doesn't have to do with Go 1.19, however! Instead, the file backend doesn't correctly validate stack names. In this case, your stack name is empty. You should have gotten an error about the empty stack name, but the file backend failed to invalidate the empty name.

As a workaround, name your stack, and you should be good to go! :) 

Thanks again for bringing this to our attention.

**Comment by Oyelowo** [comment]
Thanks @RobbieMcKinstry!
Yeah, I eventually figured that out and named my stack. Apologies for not getting back sooner. Hands were tied :)

Great job on this wonderful project!

**Comment by RobbieMcKinstry** [comment]
Thank you, friend! Much appreciated!
