### ISSUE TITLE
ESM mode not working when main is in a subdirectory 

### ISSUE THREAD

**Issue by gsuess** [pulumi/pulumi#10459]
### What happened?

These lines incorrectly assume that package.json is located the same directory as the program https://github.com/pulumi/pulumi/blob/4478bc0f695b17ec68e8d8e92a3202a038999741/sdk/nodejs/cmd/run/run.ts#L292-L293

This is not always true, because pulumi supports defining a `main` package.json or pulumi.yaml, which can refer to a different directory that the package.json is located to.

This means that you cannot use ESM mode when using a main that is not located in the same directory as your `package.json`.

### Steps to reproduce

Create a project a project that includes the following with [proper configuration for ESM as shown here](https://github.com/pulumi/pulumi/tree/6bc7b1cc67621e515c44d9dde99ab8deba4d1c08/tests/integration/nodejs/esm-ts).

Place the `index.ts` (the main entry point for pulumi into a subdirectory called `src`, so that you end up with a relative directory structure that looks like this:

```
package.json
src/index.ts
pulumi.yaml
tsconfig.json
```

Set property `main` in `pulumi.yaml` to `"src/index.ts"` (or alternatively set `main` in `package.json` to `"src/index.ts"`).

Run your project (i.e. `pulumi up`).
 

### Expected Behavior

Works fine in ESM mode. 

### Actual Behavior

When loading the `packageObject` [here](https://github.com/pulumi/pulumi/blob/4478bc0f695b17ec68e8d8e92a3202a038999741/sdk/nodejs/cmd/run/run.ts#L293), it comes back as empty object `{}`, causing it to run all the validation checks as if it was an CommonJS module.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /src/index.ts
    require() of ES modules is not supported.
    require() of /src/index.ts from /node_modules/@pulumi/pulumi/cmd/run/run.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
    Instead change the requiring code to use import(), or remove "type": "module" from /package.json.
    
        at createErrRequireEsm (/node_modules/ts-node/dist-raw/node-internal-errors.js:46:15)
        at assertScriptCanLoadAsCJSImpl (/node_modules/ts-node/dist-raw/node-internal-modules-cjs-loader.js:584:11)
        at require.extensions.<computed> (/node_modules/ts-node/src/index.ts:1610:5)
        at Object.require.extensions.<computed> [as .ts] (/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:998:32)
        at Function.Module._load (node:internal/modules/cjs/loader:839:12)
        at Module.require (node:internal/modules/cjs/loader:1022:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.<anonymous> (/node_modules/@pulumi/cmd/run/run.ts:325:14)
        at Generator.next (<anonymous>)
```

### Output of `pulumi about`

CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  12.5
Arch     arm64

This project is written in nodejs: executable='/Users/gsuess/.nvm/versions/node/v18.7.0/bin/node' version='v18.7.0'

// Truncated the rest as it should not be relevant here.

### Additional context

A workaround for this is to place the main entrypoint of pulumi in the same directory as the package.json.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by geekflyer** [comment]
ran into the same issue. Kinda confusing.
What I ended up doing is to create a symbolic link from the root package.json into the directory which contains entry point.
E.g. `ln -s ../../../../package.json package.json`

**Comment by RobbieMcKinstry** [comment]
Nice find! This feels like a bug that could bite monorepo setups. @gsuess or @geekflyer , would either of you be willing to submit a PR?

**Comment by vtereshyn** [comment]
any updates here? trying to resolve that so I can finally move my project to ESM

**Comment by RobbieMcKinstry** [comment]
@vtereshyn There's an open PR (https://github.com/pulumi/pulumi/pull/11045) with an open question. It looks like the PR has the right idea but needs more work to plumb the `package.json` file to the right place, if I'm understanding it correctly.

**Comment by RobbieMcKinstry** [comment]
We've added support for loading `package.json` above the Pulumi project root 🎉 We intend to ship a release soon; the GitHub Actions outage has limited our ability to cut a release today. It's possible this change will go live tomorrow.

**Comment by justinvp** [comment]
Unfortunately, we found the change results in an error if `main` in `package.json` references a file that doesn't exist. We're temporarily reverting the change and plan to re-introduce it soon.

**Comment by vtereshyn** [comment]
@justinvp so we can assume that this issue won't appear anymore?

**Comment by justinvp** [comment]
@vtereshyn, the issue should now be addressed.
