### ISSUE TITLE
Exception while trying to unprotect gcs dataflow resource - slice bounds out of range

### ISSUE THREAD

**Issue by remintz** [pulumi/pulumi#10497]
### What happened?

```
% pulumi state unprotect 'urn:pulumi:datamilk-dataflow-datamilk-dev::dataflow::gcp:dataflow/job:Job::datamilk_dataflow_dev'
 warning: This command will edit your stack's state directly. Confirm? Yes
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.38.0
Go Version:       go1.19
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            runtime error: slice bounds out of range [:-2]

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.19.0/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x1d68680, 0xc0008e2fd8})
        /opt/hostedtoolcache/go/1.19.0/x64/src/runtime/panic.go:884 +0x212
gopkg.in/AlecAivazis/survey%2ev1.paginate(0x50c429?, {0xc0009c3ec0?, 0xd?, 0x40d83a?}, 0x9?)
        /home/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/survey.go:254 +0xb7
gopkg.in/AlecAivazis/survey%2ev1.(*Select).Prompt(0xc001528340)
        /home/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/select.go:199 +0x125
gopkg.in/AlecAivazis/survey%2ev1.Ask({0xc000ce7730, 0x1, 0x7f7d7d3d1dd0?}, {0x1a69be0?, 0xc0016ec150}, {0x0, 0x0, 0xc001528340?})
        /home/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/survey.go:148 +0x1e4
gopkg.in/AlecAivazis/survey%2ev1.AskOne({0x22dabc0?, 0xc001528340?}, {0x1a69be0?, 0xc0016ec150?}, 0x1?, {0x0?, 0x9?, 0x1521ce9a00000100?})
        /home/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/survey.go:94 +0x8c
main.locateStackResource({{0x1e6fd54, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:113 +0x6aa
main.runStateEdit.func1({{0x1e6fd54, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:129 +0x78
main.runTotalStateEdit({0x22dc488, 0xc0000540c0}, {0x0, 0x0}, 0x1, 0xc000ce7bf0)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:175 +0x3fe
main.runStateEdit({0x22dc488?, 0xc0000540c0?}, {0x0?, 0x19?}, 0x70?, {0x7ffd69313ed0?, 0x0?}, 0x19?)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:128 +0x68
main.unprotectResource({0x22dc488?, 0xc0000540c0?}, {0x0?, 0xc00079e270?}, {0x7ffd69313ed0?, 0x0?}, 0x0?)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_unprotect.go:95 +0x4a
main.newStateUnprotectCommand.func1(0xe?, {0xc00032b6c0, 0x1, 0x605745?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_unprotect.go:59 +0xcf
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc00059a000?, {0xc00032b6c0, 0x1, 0x1})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc00059a000, {0xc00032b6a0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000438f00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
```

### Steps to reproduce

.

### Expected Behavior

.

### Actual Behavior

.

### Output of `pulumi about`

.

### Additional context

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hi, thanks for reporting this. I was looking through the code and it appears to have been addressed by
https://github.com/pulumi/pulumi/issues/10450

It will be fixed by the next release this Wednesday.

In the meantime, the workaround is downgrading to a version prior to `3.38.0`
> Looks like we have a fix - https://github.com/pulumi/pulumi/pull/10475 - this regression was introduced in 3.38.0 and will be fixed in the next release. You can downgrade Pulumi CLI to pre-3.38.0 in the meanwhile as a workaround.

**Comment by dixler** [comment]
I'm going to close this issue as duplicate.
