### ISSUE TITLE
panic when upgrading operator to v3.39.0

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#10569]
### What happened?

user reports that they upgraded operator to use pulumi v3.39.0

they have this panic output:

```
================================================================================
Pulumi Version:   v3.39.0
Go Version:       go1.19
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.0/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic(***0x1b8a520, 0x3112060***)
	/opt/hostedtoolcache/go/1.19.0/x64/src/runtime/panic.go:884 +0x212
main.filterMapPendingCreates.func1(***0x1e66ac0, 0x5***, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, ...***, ...)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/refresh.go:330 +0x2a
main.totalStateEdit(***0x22d4e68, 0xc000114000***, ***0x22e4dc0, 0xc0009717a0***, 0x1, ***0x1e66ac0, 0x5***, 0x0, 0x0, 0x0, ...***, ...)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:172 +0x2dd
main.filterMapPendingCreates(***0x22d4e68?, 0xc000114000?***, ***0x22e4dc0?, 0xc0009717a0?***, ***0x1e66ac0, 0x5***, 0x0, 0x0, 0x0, 0x0, ...***, ...)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/refresh.go:328 +0xab
main.pendingCreatesToImports(***0x22d4e68, 0xc000114000***, ***0x22e4dc0, 0xc0009717a0***, 0x1?, ***0x1e66ac0, 0x5***, 0x0, 0x0, 0x0, ...***, ...)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/refresh.go:364 +0x291
main.newRefreshCmd.func1(0x20?, ***0xc000685200?, 0xc0007efd78?, 0x604ba5?***)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/refresh.go:165 +0xadb
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc00094d180?, ***0xc0008fe620, 0x0, 0x7***)
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc00094d180, ***0xc0008fe5b0, 0x7, 0x7***)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000940280)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45


", "errorVerbose": "failed to refresh stack: exit status 1
code: 1
stdout: 
stderr: 
```

### Steps to reproduce

getting more feedback

### Expected Behavior

not panic

### Actual Behavior

panic

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Offending line: https://github.com/pulumi/pulumi/blob/e07f0f038a003e8c3a0cc6bfadaabf442e16606c/pkg/cmd/pulumi/refresh.go#L330

Apparently `snap` can be nil.
