### ISSUE TITLE
How to increase MaxListeners, and troubleshoot cause

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#10645]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
We received the following error, and would like to know the best practice for changing this setting and if there is a way to make a larger default in the code, our current way seems to be to modify: `node_modules/@pulumi/pulumi/cmd/run/index.js`; this doesn't seem like a good long term practice. 
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit

```
### Affected area/feature

pulumi cli

**Comment by justinvp** [comment]
@rshade, Would it be possible for the customer to temporarily modify their `Pulumi.yaml` file to specify the `--trace-warnings` node arg, which will tell node to print stack traces of where the warning is coming from?

In `Pulumi.yaml`, replace:

```yaml
runtime: nodejs
```

with:

```yaml
runtime:
   name: nodejs
   options:
     nodeargs: "--trace-warnings"
```

**Comment by maxemann96** [comment]
I have the same problem. Adding the trace warnings option, the following output is generated:
```
(node:25141) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at process.addListener (node:events:605:10)
    at Object.debuggablePromise (PROJECT_DIR/node_modules/@pulumi/random/node_modules/@pulumi/runtime/debuggable.ts:80:17)
    at Object.rpcKeepAlive (PROJECT_DIR/node_modules/@pulumi/random/node_modules/@pulumi/runtime/settings.ts:430:25)
    at log (PROJECT_DIR/node_modules/@pulumi/random/node_modules/@pulumi/log/index.ts:102:35)
    at Object.debug (PROJECT_DIR/node_modules/@pulumi/random/node_modules/@pulumi/log/index.ts:44:16)
    at Object.registerResource (PROJECT_DIR/node_modules/@pulumi/random/node_modules/@pulumi/runtime/resource.ts:283:9)
    at new Resource (PROJECT_DIR/node_modules/@pulumi/random/node_modules/@pulumi/resource.ts:401:13)
    at new CustomResource (PROJECT_DIR/node_modules/@pulumi/random/node_modules/@pulumi/resource.ts:780:9)
```

**Comment by maxemann96** [comment]
Output of `pulumi about`:
```
CLI          
Version      3.39.3
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.13.0
cloudflare  4.10.0
keycloak    4.10.0
kubernetes  3.21.2
nodejs      unknown
random      4.8.2

Host     
OS       darwin
Version  11.6.8
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.9.0'

Current Stack: ORGANIZATION/STACK

TYPE                                                                       URN
...Stripped...


Found no pending operations associated with ORGANIZATION/STACK

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/maxemann96
User           maxemann96
Organizations  REDACTED

Dependencies:
NAME                 VERSION
@pulumi/aws          5.13.0
@pulumi/cloudflare   4.10.0
@pulumi/keycloak     4.10.0
@pulumi/kubernetes   3.21.2
@pulumi/kubernetesx  0.1.6
@pulumi/pulumi       3.39.3
@pulumi/random       4.8.2
@types/node          14.18.28

Pulumi locates its logs in /var/folders/3p/6t2fzpvj3g7gj3jtgqm4yt080000gn/T/ by default
```

**Comment by maxemann96** [comment]
@mikhailshilkov do you need more information than the one I posted above?

**Comment by justinvp** [comment]
@maxemann96,

The warning you are getting is happening when we add a `process.on("exit")` listener inside `@pulumi/pulumi`. Currently, there are four places in `@pulumi/pulumi` where we add `process.on("exit")` listeners, which counts against the default max listener limit of 10 listeners. But that should leave 6 more listeners for `exit` before Node emits the warning.

From the stack trace you provided, I think I might know why you're seeing the warning: It looks like you have a nested copy of `@pulumi/pulumi` under `@pulumi/random/node_modules`, which would mean additional calls to `process.on("exit")` from that copy (and likely have other nested copies), adding to the listener count for this event. This can happen sometimes when multiple different versions of the same package are requested from different packages, and can't coalesce on a single top-level version that satisfies the requirements. You may be able to fix this by deleting your `package-lock.json` (backing it up, if you want), and then deleting your entire top-level `node_modules` directory, then re-running `npm install` such that only a single copy of `@pulumi/pulumi` is in the top-level `node_modules` directory, and isn't present nested under any of the other packages. If you're having a hard time avoiding the nested copies, I can help review your `package-lock.json`.

Another workaround is to change the default limit at the beginning of your Pulumi program, e.g. `process.setMaxListeners(20);` 

In terms of actual changes we could consider making to `@pulumi/pulumi`, we likely could reduce the number of listeners on `exit` from 4 to 1, to add some breathing room even in the face of multiple copies of `@pulumi/pulumi`. It may even be possible to store some global state to avoid other copies of `@pulumi/pulumi` adding additional listeners.

**Comment by maxemann96** [comment]
Thanks for your fast answer. You correct identified the issue, but the cause is a messed up multi module TypeScript project. I will fix that and then report if that fixed my issue.

**Comment by maxemann96** [comment]
I now corrected the npm setup and built my project with the npm workspaces. This fixes my issue. Thanks for your useful hints and investigation.

**Comment by pgavlin** [comment]
@rshade any idea if this is still an issue?

**Comment by rshade** [comment]
@pgavlin yes, I think this might still be a problem, although. I don't think to many  people run into it.
