### ISSUE TITLE
NodeJs Automation API can crash instead of returning error Promise

### ISSUE THREAD

**Issue by barclayadam** [pulumi/pulumi#10744]
### What happened?

When an error occurs in my Automation API program it can hard-quit (with an error code of `1`) the application instead of returning from `stack.up`.

### Steps to reproduce

Run an Automation API that has an error (as below) using `stack.up`:

````typescript
try {
    await stack.up();

    // This is not hit
} catch (e) {
    // This is not hit
    throw new Error(e.message ?? e.commandResult?.stderr ?? 'Error in Pulumi. See output');
}
````

````
configured Kubernetes cluster is unreachable: failed to parse kubeconfig data in `kubernetes:config:kubeconfig`- couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }

update failed

Error: failed to register new resource smtp-inbound-pdb [kubernetes:policy/v1beta1:PodDisruptionBudget]: Resource monitor is terminating
    at Object.registerResource (D:\Adam\Projects\Signature365\devops\node_modules\@pulumi\runtime\resource.ts:292:27)
    at new Resource (D:\Adam\Projects\Signature365\devops\node_modules\@pulumi\resource.ts:401:13)
    at new CustomResource (D:\Adam\Projects\Signature365\devops\node_modules\@pulumi\resource.ts:780:9)
    at new PodDisruptionBudget (D:\Adam\Projects\Signature365\devops\node_modules\@pulumi\policy\v1beta1\podDisruptionBudget.ts:85:9)
    at DockerDeployment.createPodDisruptionBudget (D:\Adam\Projects\Signature365\devops\bin\providers\dockerDeployment.js:63:16)
    at D:\Adam\Projects\Signature365\devops\bin\apps\smtpInbound.js:224:43
    at D:\Adam\Projects\Signature365\devops\node_modules\@pulumi\output.ts:383:31
    at Generator.next (<anonymous>)
    at D:\Adam\Projects\Signature365\devops\node_modules\@pulumi\pulumi\output.js:21:71
    at new Promise (<anonymous>)
````

### Expected Behavior

No crash, events raised of the error, and a rejected Promise to be returned with no output to the console from Pulumi itself

### Actual Behavior

Program crashes

### Output of `pulumi about`

CLI
Version      3.39.3
Go Version   go1.19.1
Go Compiler  gc

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22000 Build 22000
Arch     x86_64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/symprex
User           symprex
Organizations  symprex

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hi. Thanks for filing this. Could you put together a small repro program that causes exit to be called in your automation api program?

**Comment by barclayadam** [comment]
Hi @dixler 

The below program should reproduce this issue:

````typescript
import * as k8s from '@pulumi/kubernetes';
import { LocalWorkspace } from '@pulumi/pulumi/automation';

async function go() {
    const stack = await LocalWorkspace.createOrSelectStack({
        projectName: 'bugs',
        stackName: '10744',
        program: () => {
            new k8s.policy.v1beta1.PodDisruptionBudget('test', {
                metadata: {
                    name: 'pdb-test',
                },

                spec: {
                    minAvailable: 3,
                },
            });

            return Promise.resolve();
        },
    });

    await stack.setConfig('kubernetes:kubeconfig', { value: 'invalid' });

    await stack.up();
}

go()
    .then(() => {
        console.log('Done');
    })
    .catch(e => {
        console.error(e);
    });
````

On my machine it prints:

````
Error: failed to register new resource test [kubernetes:policy/v1beta1:PodDisruptionBudget]: Resource monitor is terminating
    at Object.registerResource (D:\Adam\Projects\Signature365\devops\node_modules\@pulumi\runtime\resource.ts:292:27)
    at new Resource (D:\Adam\Projects\Signature365\devops\node_modules\@pulumi\resource.ts:401:13)
    at new CustomResource (D:\Adam\Projects\Signature365\devops\node_modules\@pulumi\resource.ts:780:9)
    at new PodDisruptionBudget (D:\Adam\Projects\Signature365\devops\node_modules\@pulumi\policy\v1beta1\podDisruptionBudget.ts:85:9)
    at Object.program [as init] (D:\Adam\Projects\Signature365\devops\bin\index-repro.js:30:13)
    at Stack.<anonymous> (D:\Adam\Projects\Signature365\devops\node_modules\@pulumi\runtime\stack.ts:86:39)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Adam\Projects\Signature365\devops\node_modules\@pulumi\pulumi\runtime\stack.js:18:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
````

**Comment by dixler** [comment]
Hi again, sorry about that. I had been working on other stuff.

I took your code and added a try catch block for the part that had an exception and it was able to complete. I have a link to the recording.
https://asciinema.org/a/9EexdhwhsZXnSBJQPF0FHL4Yw

Can you see if upgrading the pulumi CLI or the package versions fixes your issue?

my package-lock.json has the following versions.
```
        "@pulumi/kubernetes": 
            "version": "3.21.4",
        "@pulumi/kubernetesx":
            "version": "0.1.6",
        "@pulumi/pulumi":
            "version": "3.43.1",

```

**Comment by barclayadam** [comment]
No worries.

The updated version of Pulumi has indeed fixed this issue and I now get the correct events from the automation API without the hard crash.

**Comment by barclayadam** [comment]
@dixler 

I've just hit a similar issue, not sure if it's quite the same as before, but the symptom of a hard crash is. I'm unable to reproduce this quickly right now, but the symptom is an error printed to the console (output below).

This error happens for both an up and preview command. The error (that I can only see in the Pulumi portal) is "unable to replace resource", not sure if that is relevant to the cause of this.

Are there any logs / diagnostic outputs I can get that will help to diagnose this issue?

````
Error: Resource monitor is terminating
    at Object.callErrorFromStatus (D:\Adam\Projects\Signature365\devops\node_modules\@grpc\grpc-js\src\call.ts:81:24)
    at Object.onReceiveStatus (D:\Adam\Projects\Signature365\devops\node_modules\@grpc\grpc-js\src\client.ts:338:36)
    at Object.onReceiveStatus (D:\Adam\Projects\Signature365\devops\node_modules\@grpc\grpc-js\src\client-interceptors.ts:426:34)
    at Object.onReceiveStatus (D:\Adam\Projects\Signature365\devops\node_modules\@grpc\grpc-js\src\client-interceptors.ts:389:48)
    at D:\Adam\Projects\Signature365\devops\node_modules\@grpc\grpc-js\src\call-stream.ts:276:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
````

**Comment by barclayadam** [comment]
I have upgraded CLI and npm to version 3.53.1 and still experience the above issue. Alongside the Azure Native issue referenced above I'm completely unable to manage our node pools on AKS.

The stack trace continues to be the same as before with new version:

````
D:Project\node_modules\@grpc\grpc-js\src\call.ts:81
  return Object.assign(new Error(message), status);
                       ^
Error: Resource monitor is terminating
    at Object.callErrorFromStatus (D:Project\node_modules\@grpc\grpc-js\src\call.ts:81:24)
    at Object.onReceiveStatus (D:Project\node_modules\@grpc\grpc-js\src\client.ts:338:36)
    at Object.onReceiveStatus (D:Project\node_modules\@grpc\grpc-js\src\client-interceptors.ts:426:34)
    at Object.onReceiveStatus (D:Project\node_modules\@grpc\grpc-js\src\client-interceptors.ts:389:48)
    at D:Project\node_modules\@grpc\grpc-js\src\call-stream.ts:276:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
````

The Automation events that I receive at the end of the run are below. It shows that the correct error is output as a `diagnosticEvent` (although I think I would have expected a `resOpFailedEvent` in this case), a summary is published but then a `cancelEvent` is also published, before the process terminates with an exist code of `

````json
{"sequence":418,"timestamp":1675075122,"diagnosticEvent":{"urn":"urn:pulumi:project1::stack1::custom:DataCentre$azure-native:containerservice:ManagedCluster::k8s","prefix":"error: ","message":"unable to replace resource \"urn:pulumi:project1::stack1::custom:DataCentre$azure-native:containerservice:ManagedCluster::k8s\"\nas it is currently marked for protection. To unprotect the resource, remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`\n","color":"never","severity":"error"}}
{"sequence":419,"timestamp":1675075122,"summaryEvent":{"maybeCorrupt":false,"durationSeconds":4,"resourceChanges":{"same":7,"update":3},"PolicyPacks":{}}}
{"sequence":420,"timestamp":1675075122,"diagnosticEvent":{"prefix":"debug: ","message":"RegisterResource RPC finished: resource:outbound-static-app-ip-dns[cloudflare:index/record:Record]; err: null, resp: urn:pulumi:project1::stack1::cloudflare:index/record:Record::outbound-static-app-ip-dns,5b3078ba495e52a11dff221fb897ee0d,__meta,,,{\"e2bfb730-ecaa-11e6-8f88-34363bc7c4c0\":{\"create\":30000000000,\"update\":30000000000},\"schema_version\":\"1\"},allowOverwrite,,,,false,createdOn,,,2022-02-11T13:24:22.581919Z,data,,,,,,hostname,,,example.com,id,,,,metadata,,,,,auto_added,,,false,managed_by_apps,,,false,managed_by_argo_tunnel,,,false,source,,,primary,modifiedOn,,,2022-02-11T13:24:22.581919Z,name,,,example.com,proxiable,,,,true,proxied,,,,false,ttl,,1,type,,,A,zoneId,,,12345,,\n","color":"never","severity":"debug"}}
{"sequence":421,"timestamp":1675075122,"diagnosticEvent":{"prefix":"debug: ","message":"RegisterResource RPC prepared: t=pulumi-nodejs:dynamic:Resource, name=outbound-static-app-ip-reverse-fqdn\n","color":"never","severity":"debug"}}
{"sequence":422,"timestamp":1675075122,"cancelEvent":{}}
````

**Comment by RobbieMcKinstry** [comment]
```
Error: Resource monitor is terminating
```
..should not be a user-visible error. Can you provide another sample program? Or does the old one produce this issue as well?

Assuming the program doesn't do anything crazy, this could be a regression. If we have a program that can reliably produce this fault, we should be able to `git bisect` until we find the commit that introduced it.

**Comment by barclayadam** [comment]
I have just upgraded to the latest, v3.68.0 and I still get this issue. I have not attempted to reduce to a minimum working repro. The current instance of this failing happens using Azure Native, creating an alert policy with an invalid resource group name. 

See below output from the portal:

````
Changes:
 
    Type                                  Name                               Status               Info
    pulumi:pulumi:Stack                   s365-apm-uat-deploy-global                              
+   ├─ azure-native:insights:ActionGroup  new-relic-azure-action-group       **creating failed**  
+   └─ azure-native:insights:ActionGroup  infrastructure-azure-action-group  **creating failed**  
 
Diagnostics:
  pulumi:pulumi:Stack (symprex/s365-apm/uat-deploy-global)
    error: update failed
 
  azure-native:insights:ActionGroup (infrastructure-azure-action-group)
    error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'rg' could not be found."
 
  azure-native:insights:ActionGroup (new-relic-azure-action-group)
    error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'rg' could not be found."
 
Resources:
    32 unchanged
 
Duration: 7s
````

which locally prints the "Resource monitor is terminating" error.

If it would help I could screen share with someone to help diagnose this issue locally?

**Comment by barclayadam** [comment]
Note that it's not all types of failures. For example I have a different stack that failed with a REST failure from AZure Native that was handled correctly and gave the error as expected:

````
Service returned an error. Status=400 Code="LocationNotAvailableForResourceType" Message="The provided location 'uksouth' is not available for resource type 'microsoft.insights/metricalerts'. List of available regions for the resource type is 'global,westeurope,northeurope,swedencentral,germanywestcentral'.
````

**Comment by dixler** [comment]
Taking a look at this
