### ISSUE TITLE
requireSecret triggers  YAMLException: unacceptable kind of an object to dump [object Function] for some secrets

### ISSUE THREAD

**Issue by LouisJULIEN** [pulumi/pulumi#10836]
### What happened?

I've been actively using pulumi for a few months, on different repos and with different Pulumi.\<env\>.yaml files.
Out of nowhere (and only once so far), I got the following error after adding a new secret using `pulumi config set --secret` and using it with `config.requireSecret(...)`.

```        
        XXXX started
        error: Running program '/jinko/gitops-infra/local-deployment/qa-e2e-release/deploy-app/apps/main' failed with an unhandled exception:
        YAMLException: unacceptable kind of an object to dump [object Function]
            at writeNode (/jinko/gitops-infra/local-deployment/qa-e2e-release/deploy-app/node_modules/js-yaml/lib/dumper.js:868:13)
            at writeBlockMapping (/jinko/gitops-infra/local-deployment/qa-e2e-release/deploy-app/node_modules/js-yaml/lib/dumper.js:731:10)
            at writeNode (/jinko/gitops-infra/local-deployment/qa-e2e-release/deploy-app/node_modules/js-yaml/lib/dumper.js:834:9)
            at writeBlockMapping (/jinko/gitops-infra/local-deployment/qa-e2e-release/deploy-app/node_modules/js-yaml/lib/dumper.js:731:10)
            at writeNode (/jinko/gitops-infra/local-deployment/qa-e2e-release/deploy-app/node_modules/js-yaml/lib/dumper.js:834:9)
            at writeBlockMapping (/jinko/gitops-infra/local-deployment/qa-e2e-release/deploy-app/node_modules/js-yaml/lib/dumper.js:731:10)
            at writeNode (/jinko/gitops-infra/local-deployment/qa-e2e-release/deploy-app/node_modules/js-yaml/lib/dumper.js:834:9)
            at writeBlockMapping (/jinko/gitops-infra/local-deployment/qa-e2e-release/deploy-app/node_modules/js-yaml/lib/dumper.js:731:10)
            at writeNode (/jinko/gitops-infra/local-deployment/qa-e2e-release/deploy-app/node_modules/js-yaml/lib/dumper.js:834:9)
            at writeBlockMapping (/jinko/gitops-infra/local-deployment/qa-e2e-release/deploy-app/node_modules/js-yaml/lib/dumper.js:731:10)
```

I got this error on every run. Having only the secret in the Pulumi file (= not reading it) doesn't trigger the error.    

I tried to re-encrypt the secret (same secret value, different `secret:  XXXX` result in the Pulumi.env.yaml). It got the same error.  
I managed to solve this issue by changing the `config.requireSecret(...)` to `config.require(...)`.

### Steps to reproduce

I am afraid I can't reproduce outside my production code. My guess is that I have a combination of encryption keys that ends up creating an encrypted string with parenthesis (or other) that is interpreted as a JavaScript function. As a result, this "function" that should be a string can't be converted to yaml.

### Expected Behavior

requireSecret should work whatever the encrypted value is.

### Actual Behavior

Depending on the secret value and - I guess - pulumi config passphrases, it's not always working.

### Output of `pulumi about`

```
CLI          
Version      3.33.2
Go Version   go1.17.10
Go Compiler  gc

Host     
OS       alpine
Version  3.16.0
Arch     x86_64

Backend        
Name           louis-julien
URL            s3://<MANUALLY-REDACTED>
User           root
Organizations  

Pulumi locates its logs in /tmp by default
warning: A new version of Pulumi is available. To upgrade from version '3.33.2' to '3.40.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This is a bit odd, that error looks like it's coming from "js-yaml" but the only place we use that is in automation api when calling `saveProjectSettings`. But sounds like your hitting this issue when running a program?

**Comment by LouisJULIEN** [comment]
@Frassle good point, I didn't think about it. I'll investigate our internal architecture and will let you know

**Comment by LouisJULIEN** [comment]
@Frassle You were absolutely right. Sorry for wasting your time and thanks for your help!

For anyone with the same issue: `config.require(...)` returns a `string` that can, for example, be passed to yaml by js-yaml.
However, `requireSecret(...)` returns `Output<string>`. That can't be converted to yaml as it is a function. Use `.apply(secretAsStr => {/*use secret as string here */})` on the value returned by `requireSecret` to get the string content.
