### ISSUE TITLE
CLI panic when using convert to generate Go code

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi#10875]
### What happened?

I have a simple YAML program to use AWSx (version 1.0.0-beta.10) to create a VPC and a security group in that VPC (the code can be found in https://github.com/pulumi/templates/pull/380). Attempting to use `pulumi convert` on this code causes a CLI panic.

`pulumi convert` seems to work normally (no panic or other errors) for TypeScript and Python.

### Steps to reproduce

1. Check out the code in https://github.com/pulumi/templates/pull/380.
2. Try using `pulumi convert` to generate Go code.
3. You'll get an error about being unable to find package AWSx. Comment out lines 26 and 27.
4. Repeat step 2. You'll get a panic.

### Expected Behavior

I expected `pulumi convert` to generate Go code.

### Actual Behavior

A panic occurs. Here's the output from the CLI:
```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.40.2
Go Version:       go1.19.1
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            send on closed channel

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/debug/stack.go:24 +0x64
main.panicHandler()
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/cmd/pulumi/main.go:29 +0x34
panic({0x10481b400, 0x104b0e190})
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/panic.go:884 +0x204
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.loadPlugin(0x14000cbe050?, 0x140005cdc50)
	/private/tmp/pulumi-20220926-94408-q1pnqk/sdk/go/common/resource/plugin/host.go:250 +0xb8
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).Provider(0x14000b40770, {0x14000e7841e, 0x3}, 0x14000cbe050)
	/private/tmp/pulumi-20220926-94408-q1pnqk/sdk/go/common/resource/plugin/host.go:326 +0xb8
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*pluginLoader).loadPluginSchemaBytes(0x14000e7841e?, {0x14000e7841e?, 0x14005ff7a28?}, 0x14005ff7ab8?)
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/schema/loader.go:258 +0x2c
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*pluginLoader).loadSchemaBytes(0x14000595780, {0x14000e7841e, 0x3}, 0x14000cbe050)
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/schema/loader.go:234 +0x138
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*pluginLoader).LoadPackageReference(0x14000595780, {0x14000e7841e, 0x3}, 0x14000cbe050)
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/schema/loader.go:163 +0x220
github.com/pulumi/pulumi/pkg/v3/codegen/schema.LoadPackageReference({0x104b12120, 0x14000595780}, {0x14000e7841e, 0x3}, 0x39?)
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/schema/loader.go:202 +0xc0
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindTypeSpecRef(0x140008694a0, {0x1400bc83cc0?, 0x10618c5b8?}, {{0x0, 0x0}, {0x14000e7841d, 0x39}, 0x0, 0x0, {0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/schema/bind.go:738 +0x378
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindTypeSpec(0xd?, {0x1400bc83cc0?, 0x1c00089680?}, {{0x0, 0x0}, {0x14000e7841d, 0x39}, 0x0, 0x0, {0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/schema/bind.go:871 +0xd5c
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindProperties(0x140008694a0, {0x14001849ad0, 0x2c}, 0x10415622f?, {0x14001849b00, 0x2a}, {0x140005dc000, 0x1, 0x104a7a460?}, 0x30?)
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/schema/bind.go:1045 +0x16c
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindResourceDetails(0x140008694a0, {0x14001849aa0, _}, {_, _}, {{{0x0, 0x0}, 0x1400a7ee5a0, {0x0, 0x0}, ...}, ...}, ...)
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/schema/bind.go:1340 +0x230
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindResourceDef(0x140008694a0, {0x14000e783ae, 0x15})
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/schema/bind.go:1321 +0x1d8
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindResourceTypeDef(0x140008694a0, {0x14000e783ae, 0x15})
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/schema/bind.go:702 +0x58
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).finishResources(0x140008694a0, {0x14000176000, 0xc, 0x140005cc8d0?})
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/schema/bind.go:1452 +0x274
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*PartialPackage).Definition(0x14000172dc0)
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/schema/package_reference.go:444 +0x110
github.com/pulumi/pulumi/pkg/v3/codegen/go.programPackageDefs(0xdf?)
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/go/gen_program.go:956 +0x88
github.com/pulumi/pulumi/pkg/v3/codegen/go.GenerateProgramWithOptions(0x1400244f200, {0x70?, 0x0?})
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/go/gen_program.go:66 +0x48
github.com/pulumi/pulumi/pkg/v3/codegen/go.GenerateProgram(0x14000620000?)
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/go/gen_program.go:60 +0x30
github.com/pulumi/pulumi/pkg/v3/codegen/go.GenerateProject({0x16d0d3793, 0x2d}, {{0x140000cb828, 0x3}, {{0x140000cb860, 0x4}, 0x0}, {0x0, 0x0}, 0x140002491a0, ...}, ...)
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/codegen/go/gen_program.go:142 +0x34
main.newConvertCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/cmd/pulumi/convert.go:87 +0x358
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000b26780?, {0x14000341ef0, 0x0, 0x5})
	/private/tmp/pulumi-20220926-94408-q1pnqk/sdk/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000b26780, {0x14000341ea0, 0x5, 0x5})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x14000902f00)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/private/tmp/pulumi-20220926-94408-q1pnqk/pkg/cmd/pulumi/main.go:48 +0x3c
```

### Output of `pulumi about`

```
CLI
Version      3.40.2
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME  VERSION
aws   unknown
awsx  unknown
yaml  unknown

Host
OS       darwin
Version  12.6
Arch     arm64

This project is written in yaml

Backend
Name           pulumi.com
URL            https://app.pulumi.com/scottslowe
User           scottslowe
Organizations  scottslowe

No dependencies found

Pulumi locates its logs in /var/folders/kp/nk2y9x1x13n6v6r_d1wqhztm0000gn/T/ by default
```

### Additional context

Attempting to use `pulumi convert` on YAML programs that previously worked fine to generate Go code is also generating a panic, although I am unsure if the details of the panic are similar or different.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
This problem emerges from a flaw in the design of [`Eject`](https://github.com/pulumi/pulumi-yaml/blob/a97d9ab3c54bb169199229d88983cf8b3f41ed03/pkg/pulumiyaml/codegen/eject.go#L27-L70) not accounting for how compared with how loaders are captured during bind. This leads to us closing a host, and then using that host via the `*pcl.Program` that embeds it. The solution is to pass in your own host.

I'm going to open a PR to fix the problem here, and a second PR changing the API of pulumiyaml.Eject to require passing in a loader, and thus prevent this problem occurring in the future.
