### ISSUE TITLE
[sdk/python] RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#10885]
A user reported hitting this failure in the Pulumi Python SDK:

```
error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 179, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/stack.py", line 73, in wait_for_rpcs
        await RPC_MANAGER.rpcs.pop()
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        result = await rpc
      File "/usr/local/lib/python3.9/dist-packages/pulumi/output.py", line 99, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/output.py", line 99, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/output.py", line 99, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 34 more times]
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/resource.py", line 514, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/resource.py", line 109, in prepare_resource
        explicit_urn_dependencies = await _resolve_depends_on_urns(
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/resource.py", line 852, in _resolve_depends_on_urns
        return await _expand_dependencies(all_deps, from_resource)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/resource.py", line 823, in _expand_dependencies
        await _add_dependency(urns, d, from_resource)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/resource.py", line 809, in _add_dependency
        urn = await res.urn.future()
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        result = await rpc
      File "/usr/local/lib/python3.9/dist-packages/pulumi/output.py", line 99, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/output.py", line 99, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/output.py", line 124, in get_value
        val = await self._future
      File "/usr/local/lib/python3.9/dist-packages/pulumi/output.py", line 99, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/output.py", line 99, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/output.py", line 99, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 3 more times]
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/resource.py", line 514, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/resource.py", line 109, in prepare_resource
        explicit_urn_dependencies = await _resolve_depends_on_urns(
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/resource.py", line 852, in _resolve_depends_on_urns
        return await _expand_dependencies(all_deps, from_resource)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/resource.py", line 823, in _expand_dependencies
        await _add_dependency(urns, d, from_resource)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/resource.py", line 804, in _add_dependency
        await _add_dependency(deps, child, from_resource)
      File "/usr/local/lib/python3.9/dist-packages/pulumi/runtime/resource.py", line 803, in _add_dependency
        for child in res._childResources:
    RuntimeError: Set changed size during iteration
```

**Comment by lukehoban** [comment]
It looks like these two lines could race and trigger this:

https://github.com/pulumi/pulumi/blob/2b3870d3ddcb295df8e4a9e9550b13b2d1cb3cce/sdk/python/lib/pulumi/resource.py#L896:L896

https://github.com/pulumi/pulumi/blob/2b3870d3ddcb295df8e4a9e9550b13b2d1cb3cce/sdk/python/lib/pulumi/runtime/resource.py#L803:L803

**Comment by lukehoban** [comment]
Note also that to hit this, it seems you would need to a case where a child resource was being added which could potentially happen in parallel with a dependency being taken on the component.  In this case, there is already a non-determism in what transitive dependencies will be seen, based on whether the child ends up being added before or after the dependency is computed.  This particular failure appears to be caused by it happening not before or after, but actually *during* the computation of the dependencies.  But even once fixed, the underlying non-determinism might remain in the user program.  Not exactly clear what code pattern would trigger that though.
