### ISSUE TITLE
Show progress while restoring provider packages

### ISSUE THREAD

**Issue by tonybutt** [pulumi/pulumi#11101]
### What happened?

pulumi plugin install resource eks v0.42.5                               
[resource plugin eks-0.42.5] installing
Downloading plugin: 653.81 KiB / 653.81 KiB [=======================] 100.00% 0s

### Steps to reproduce

Install latest pulumi cli. 
Attempt to install eks plugin >v0.42.2
Sits downloading forever.

### Expected Behavior

Installs and previews changes

### Actual Behavior

Hangs until canceled and stack traces on pulumi up. 
```

Downloading plugin: 653.80 KiB / 653.80 KiB [=======================] 100.00% 1s
[resource plugin eks-0.42.3] installing
 
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.43.1
Go Version:       go1.19.1
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            send on closed channel

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x1f71220, 0x2847640})
	/opt/hostedtoolcache/go/1.19.1/x64/src/runtime/panic.go:884 +0x212
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.loadPlugin(0x422205?, 0xc001687660)
	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:253 +0xbd
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).LanguageRuntime(0xc00034a0e0, {0xc000300508, 0x2})
	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:376 +0x99
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).EnsurePlugins(0xc00221d298?, {0xc00044ec80?, 0x5, 0x0?}, 0x3)
	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:419 +0x249
github.com/pulumi/pulumi/pkg/v3/engine.ensurePluginsAreLoaded(0xc0010a6b40, 0xc0016cabc0?, 0x38a4f6e?)
	/home/runner/work/pulumi/pulumi/pkg/engine/plugins.go:208 +0x179
github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource({_, _}, {{{0x38a55b0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:386 +0xa5
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x38a55b0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:161 +0x263
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x38a55b0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:451 +0x391
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x28640c0, 0xc0016b3470}, 0xc0016a96c0, {{0x38a55b0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:193 +0x670
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc000001ea0, {0xc0016cabc0, 0x2b}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:622 +0x939
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt({_, _}, {_, _}, {_, _}, {0xc000001ea0, {0xc0016cabc0, 0x2b}, {0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/apply.go:116 +0x17a
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc000001ea0, {0xc0016cabc0, 0x2b}, {0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/apply.go:218 +0x13e
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).Update(_, {_, _}, {_, _}, {0xc000001ea0, {0xc0016cabc0, 0x2b}, {0x0, 0x0, ...}, ...})
	/home/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:505 +0x285
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc000001ea0, {0xc0016cabc0, 0x2b}, {0x0, 0x0, 0x0}, ...})
	/home/runner/work/pulumi/pulumi/pkg/backend/stack.go:91 +0xba
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localStack).Update(_, {_, _}, {0xc000001ea0, {0xc0016cabc0, 0x2b}, {0x0, 0x0, 0x0}, 0xc0016e0078, ...})
	/home/runner/work/pulumi/pulumi/pkg/backend/filestate/stack.go:77 +0x88
main.newUpCmd.func1({_, _}, {{{0x38a55b0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:188 +0xe17
main.newUpCmd.func3(0x0?, {0x38a55b0, 0x0, 0x0?})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:468 +0x665
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc00067a000?, {0x38a55b0, 0x0, 0x0})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc00067a000, {0x38a55b0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004e7680)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
```

### Output of `pulumi about`

```
CLI          
Version      3.43.1
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.9.1
aws-native  0.19.0
eks         0.42.3
go          unknown
kubernetes  3.17.0

Host     
OS       debian
Version  bookworm/sid
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.19.2 linux/amd64'

Backend        
Name           pop-os
URL            s3://gamewarden-infra-state/
User           cheeks
Organizations  

Dependencies:
NAME                                        VERSION
github.com/go-git/go-git/v5                 5.4.2
github.com/pulumi/pulumi-aws-native/sdk     0.19.0
github.com/pulumi/pulumi-aws/sdk/v5         5.9.1
github.com/pulumi/pulumi-eks/sdk            0.42.3
github.com/pulumi/pulumi-kubernetes/sdk/v3  3.17.0
github.com/pulumi/pulumi/sdk/v3             3.36.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This repros with just `pulumi plugin install resource eks 0.42.3`, should make it easy enough to track down.

**Comment by Frassle** [comment]
Ah ok it doesn't download forever, but it does take a while. It's doing an "npm install" in the background, there's no feedback about that, but it looks like it should complete eventually.

This is a another one of our "hardcoded npm" bits of code, so I'll see if I can flip it out to use the language host InstallDependencies instead and get it to write progress at the same time.

**Comment by Frassle** [comment]
_sigh_ this will be really painful to fix to use the language host because the plugin code is used by a load of other tools and it would require a large rewrite to fix the import cycle that is currently required between plugin install and plugin hosting.

We could get this to just print to stdout/stderr quite easily, although that _might_ break some uses of automation api (because it tries to parse stdout for most commands). cc @justinvp if you think that would actually break anything?

**Comment by justinvp** [comment]
> if you think that would actually break anything?

It's possible that it could break something, but unlikely. Perhaps we only emit the detailed npm install output when interactive (automation API sets `--non-interactive`), otherwise, output a single line like "installing plugin dependencies (this could take a while)..." or something like that?

@danielrbradley, have we not moved EKS over to using vercel/pkg? I would expect most of our Node-based providers (and those created by users) to be using that, so this would be less of an issue going forward.

**Comment by danielrbradley** [comment]
@justinvp no we've not managed to get the time yet to implement vercel/pkg for building a native binary. It was decided that it will probably have to wait until after the 1.0 release due to more pressing issues elsewhere.

**Comment by mikhailshilkov** [comment]
I tried `pulumi plugin install resource eks v0.42.5` and it does work for me too. The panic is only related to triggering the cancellation, so I'll remove the P1 label from the issue.
