### ISSUE TITLE
CallbackFunction causes unhandled promise rejections when used in unit tests

### ISSUE THREAD

**Issue by tenwit** [pulumi/pulumi#11113]
### What happened?

When constructing even the most trivial of `aws.lambda.CallbackFunction`s in a test suite, the suite leaks a rejected promise. This causes the test runner (jest, in my case) to report that the suite has failed, even though all tests have passed.

### Steps to reproduce

I have an MCVE here: https://gist.github.com/tenwit/4931c53da217144e283d563c13433845
When the wrapper ComponentResource is not constructed (comment out line 23), everything works fine.

### Expected Behavior

The test suite should run the same whether the wrapper component resource is constructed or not.

### Actual Behavior

When the wrapper component resource is constructed, I see this error output (running with `--unhandled-rejections=strict`; it's even worse with this option omitted):
```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From callbackfunc.spec.ts.

      at ../node_modules/@pulumi/runtime/closure/createClosure.ts:417:48
      at ../node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:21:71
      at Object.<anonymous>.__awaiter (../node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:17:12)

 RUNS  ./callbackfunc.spec.ts
internal/process/promises.js:194
        triggerUncaughtException(err, true /* fromPromise */);
        ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: pf.parseFunction is not a function or its return value is not iterable".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

### Output of `pulumi about`

```
CLI          
Version      3.34.0
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME     VERSION
aws      5.17.0
command  0.5.2
datadog  4.11.0
docker   3.4.1
nodejs   unknown
random   4.8.2
tls      4.6.1

Host     
OS       debian
Version  11.3
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v16.15.1'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/paulhicks_sentify
User           paulhicks_sentify
Organizations  paulhicks_sentify, mahanatx, iqa-managed-services

Dependencies:
NAME                                      VERSION
pg                                        8.8.0
@mahana-therapeutics/pulumi-aws-accounts  1.0.5
@pulumi/aws                               5.17.0
@pulumi/awsx                              0.40.1
@pulumi/command                           0.5.2
@pulumi/datadog                           4.11.0
@pulumi/pulumi                            3.40.2
@pulumi/random                            4.8.2
@pulumi/tls                               4.6.1
@types/jest                               28.1.8
@types/node                               18.8.0
@types/pg                                 8.6.5
@typescript-eslint/eslint-plugin          5.38.1
@typescript-eslint/parser                 5.38.1
eslint                                    8.24.0
eslint-config-airbnb-base                 15.0.0
eslint-config-prettier                    8.5.0
eslint-plugin-import                      2.26.0
eslint-plugin-prettier                    4.2.1
husky                                     8.0.1
jest                                      28.1.3
jest-junit                                13.2.0
prettier                                  2.7.1
release-it                                14.14.3
rimraf                                    3.0.2
ts-jest                                   28.0.8
typescript                                4.8.4

Pulumi locates its logs in /tmp by default
```
### Additional context

It looks like this sort of thing has worked in the past? https://github.com/pulumi/pulumi-aws/issues/925
Given that this is creating a lambda that won't be deployed, I'd be okay with it doing nothing in the text context. That is, if the mixin code just detected that it's a test run and didn't create the AssetArchive and anything else that might not work great when unit testing, I'd be satisfied with that. I can adjust my tests accordingly.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @tenwit - thank you for reporting and thank you for your patience. 

I'm moving this issue over to the Pulumi engine repository, as it's an error in the nodejs SDK.

**Comment by RobbieMcKinstry** [comment]
If this is as simple as a leaked promise in the definition of the `Component` class, we should be able to find this with a linter.
