### ISSUE TITLE
Failed interface conversion

### ISSUE THREAD

**Issue by k4y3ff** [pulumi/pulumi#11149]
### What happened?

We use the [Pulumi GitHub Action](https://github.com/pulumi/actions). Yesterday, the action ran `preview` successfully; today the action ran `preview` on the same Pulumi code, which resulted in the following error message and direction to open a GitHub issue against the `pulumi/pulumi` repo.

### Steps to reproduce

```
code: -2
 stdout: 
 stderr: Command failed with exit code 1: pulumi preview --parallel 2147483647 --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --event-log /tmp/automation-logs-preview-CWUnQb/eventlog.txt --stack REDACTED --non-interactive
[resource plugin kubernetes-3.21.2] installing
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.44.0
Go Version:       go1.19.2
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            interface conversion: interface {} is map[string]interface {}, not plugin.JSONSchema

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x1fa4f60, 0xc001748b70})
	/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/panic.go:884 +0x212
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.convertConfigSchema(0xc001638a50)
	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/analyzer_plugin.go:618 +0x1c7
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*analyzer).GetAnalyzerInfo(0xc001772040)
	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/analyzer_plugin.go:295 +0x3f4
github.com/pulumi/pulumi/pkg/v3/engine.installAndLoadPolicyPlugins(0xc0014d18c0, {0x38b1670?, 0x22ab8ee?}, {0xc000967e40?, 0x3, 0xc0014d18c0?}, {0x38b1670, 0x0, 0x7f188c2175b8?}, 0xc000efcdc0)
	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:283 +0x17c
github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource({_, _}, {{{0x38b1670, 0x0, 0x0}, {0xc000967e40, 0x3, 0x4}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:406 +0x22d
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x38b1670, 0x0, 0x0}, {0xc000967e40, 0x3, 0x4}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:161 +0x263
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x38b1670, 0x0, 0x0}, {0xc000967e40, 0x3, 0x4}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:451 +0x391
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x286cfe0, 0xc0014d15f0}, 0xc001438f80, {{0x38b1670, 0x0, 0x0}, {0xc000967e40, 0x3, 0x4}, 0x7fffffff, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:193 +0x670
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc000001c20, {0xc0004cb590, 0x42}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1164 +0x972
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc000001c20, {0xc0004cb590, 0x42}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1073 +0x41f
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Preview(_, {_, _}, {_, _}, {0xc000001c20, {0xc0004cb590, 0x42}, {0x0, 0x0, ...}, ...})
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:950 +0xa7
github.com/pulumi/pulumi/pkg/v3/backend.PreviewStack({_, _}, {_, _}, {0xc000001c20, {0xc0004cb590, 0x42}, {0x0, 0x0, 0x0}, ...})
	/home/runner/work/pulumi/pulumi/pkg/backend/stack.go:86 +0xba
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Preview(_, {_, _}, {0xc000001c20, {0xc0004cb590, 0x42}, {0x0, 0x0, 0x0}, 0xc0007edb60, ...})
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:147 +0x88
main.newPreviewCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/preview.go:211 +0x1114
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000904280?, {0xc000a78820, 0x0, 0xd})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/c
```

### Expected Behavior

I expected the `preview` command to succeed.

### Actual Behavior

As described, the `pulumi preview` command failed.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
This seems to be similar to https://github.com/pulumi/pulumi/issues/11140

Pulumi v3.44.1 should fix this when the release completes.
