### ISSUE TITLE
Fatal error after upgrading to CLI version 3.44.0

### ISSUE THREAD

**Issue by lukemundy-vgw** [pulumi/pulumi#11140]
### What happened?

I upgraded my Pulumi CLI to v3.44.0 using Homebrew. Since upgrading, running `pulumi up` or `pulumi preview` results in a fatal error. Other commands appear to work ok, for example `pulumi stack select` works fine.

### Steps to reproduce

```sh
brew upgrade pulumi
pulumi up
```

### Expected Behavior

`pulumi up` or `pulumi preview` completes successfully

### Actual Behavior

The following fatal error is encountered:

```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.44.0
Go Version:       go1.19.2
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            interface conversion: interface {} is map[string]interface {}, not plugin.JSONSchema

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/debug/stack.go:24 +0x64
main.panicHandler()
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/cmd/pulumi/main.go:29 +0x34
panic({0x106333a00, 0x1400091a270})
        /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/panic.go:884 +0x204
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.convertConfigSchema(0x140013fb3b0)
        /private/tmp/pulumi-20221024-21523-11h0snq/sdk/go/common/resource/plugin/analyzer_plugin.go:618 +0x198
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*analyzer).GetAnalyzerInfo(0x1400013e980)
        /private/tmp/pulumi-20221024-21523-11h0snq/sdk/go/common/resource/plugin/analyzer_plugin.go:295 +0x328
github.com/pulumi/pulumi/pkg/v3/engine.installAndLoadPolicyPlugins(0x14000a1f0e0, {0x10f7cbc18?, 0x1076722b8?}, {0x140008d43f0?, 0x1, 0x1045264dc?}, {0x1076722b8, 0x0, 0x107ed93c8?}, 0x18?)
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/engine/update.go:283 +0xfc
github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource({_, _}, {{{0x1076722b8, 0x0, 0x0}, {0x140008d43f0, 0x1, 0x1}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/engine/update.go:406 +0x174
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x1076722b8, 0x0, 0x0}, {0x140008d43f0, 0x1, 0x1}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/engine/deployment.go:161 +0x1ac
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x1076722b8, 0x0, 0x0}, {0x140008d43f0, 0x1, 0x1}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/engine/update.go:451 +0x2ac
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x106662620, 0x14000524f30}, 0x1400013e640, {{0x1076722b8, 0x0, 0x0}, {0x140008d43f0, 0x1, 0x1}, 0x7fffffff, ...}, ...)
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/engine/update.go:193 +0x48c
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0x140000d9e00, {0x14000350880, 0x2e}, ...}, ...)
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/backend/httpstate/backend.go:1164 +0x7d8
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0x140000d9e00, {0x14000350880, 0x2e}, ...}, ...)
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/backend/httpstate/backend.go:1073 +0x2cc
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Preview(_, {_, _}, {_, _}, {0x140000d9e00, {0x14000350880, 0x2e}, {0x0, 0x0, ...}, ...})
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/backend/httpstate/backend.go:950 +0x70
github.com/pulumi/pulumi/pkg/v3/backend.PreviewStack({_, _}, {_, _}, {0x140000d9e00, {0x14000350880, 0x2e}, {0x0, 0x0, 0x0}, ...})
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/backend/stack.go:86 +0x80
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Preview(_, {_, _}, {0x140000d9e00, {0x14000350880, 0x2e}, {0x0, 0x0, 0x0}, 0x14000116630, ...})
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/backend/httpstate/stack.go:147 +0x5c
main.newPreviewCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/cmd/pulumi/preview.go:211 +0xc64
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000f28f00?, {0x1076722b8, 0x0, 0x0})
        /private/tmp/pulumi-20221024-21523-11h0snq/sdk/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000f28f00, {0x1076722b8, 0x0, 0x0})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x14000cbac80)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /private/tmp/pulumi-20221024-21523-11h0snq/pkg/cmd/pulumi/main.go:48 +0x3c

exit status 1
```

### Output of `pulumi about`

```
CLI
Version      3.44.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.16.0
nodejs  unknown

Host
OS       darwin
Version  12.3
Arch     arm64

This project is written in nodejs: executable='/Users/<REDACTED>/.nvm/versions/node/v16.17.1/bin/node' version='v16.17.1'

Current Stack: <REDACTED>

TYPE                                               URN
<REDACTED>


Found no pending operations associated with <REDACTED>

Backend
Name           pulumi.com
URL            https://app.pulumi.com/<REDACTED>
User           <REDACTED>
Organizations  <REDACTED>

Dependencies:
NAME                              VERSION
typescript                        4.5.4
@types/node                       16.11.7
@typescript-eslint/eslint-plugin  5.9.0
eslint-plugin-import              2.25.4
eslint-plugin-prettier            4.0.0
eslint                            8.6.0
eslint-config-prettier            8.3.0
prettier                          2.5.1
@pulumi/aws                       5.16.0
@pulumi/pulumi                    3.40.2
@typescript-eslint/parser         5.9.0
eslint-config-airbnb-base         15.0.0
eslint-config-airbnb-typescript   16.1.0

Pulumi locates its logs in /var/folders/5f/0m5l6g9107g99svc6r4stx6r0000gq/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by alexrocco** [comment]
We're having the exactly same issue.

**Comment by aureq** [comment]
@alexrocco do you mind adding the stack trace you had please?

**Comment by aureq** [comment]
@alexrocco and the output for `pulumi about` like Luke did please. It may be related to `arm64`.

**Comment by lukemundy-vgw** [comment]
> It may be related to `arm64`.

we're starting to see the same error in our CI environments too, which runs the pulumi-nodejs docker image on amd64

```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.44.0
Go Version:       go1.19.2
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            interface conversion: interface {} is map[string]interface {}, not plugin.JSONSchema
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x1fa4f60, 0xc000a2ce10})
	/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/panic.go:884 +0x212
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.convertConfigSchema(0xc00046f810)
	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/analyzer_plugin.go:618 +0x1c7
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*analyzer).GetAnalyzerInfo(0xc0000f61c0)
	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/analyzer_plugin.go:295 +0x3f4
github.com/pulumi/pulumi/pkg/v3/engine.installAndLoadPolicyPlugins(0xc0017e8990, {0x38b1670?, 0x22ab8ee?}, {0xc000ed49e0?, 0x1, 0xc0017e8990?}, {0x38b1670, 0x0, 0x7f3d9ccf9108?}, 0xc001bda1c0)
	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:283 +0x17c
github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource({_, _}, {{{0x38b1670, 0x0, 0x0}, {0xc000ed49e0, 0x1, 0x1}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:406 +0x22d
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x38b1670, 0x0, 0x0}, {0xc000ed49e0, 0x1, 0x1}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:161 +0x263
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x38b1670, 0x0, 0x0}, {0xc000ed49e0, 0x1, 0x1}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:451 +0x391
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x286cfe0, 0xc0017e86c0}, 0xc001955380, {{0x38b1670, 0x0, 0x0}, {0xc000ed49e0, 0x1, 0x1}, 0x7fffffff, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:193 +0x670
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc0001b1cc0, {0xc000320558, 0xa}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1164 +0x972
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc0001b1cc0, {0xc000320558, 0xa}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1073 +0x41f
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Preview(_, {_, _}, {_, _}, {0xc0001b1cc0, {0xc000320558, 0xa}, {0x0, 0x0, ...}, ...})
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:950 +0xa7
github.com/pulumi/pulumi/pkg/v3/backend.PreviewStack({_, _}, {_, _}, {0xc0001b1cc0, {0xc000320558, 0xa}, {0x0, 0x0, 0x0}, ...})
	/home/runner/work/pulumi/pulumi/pkg/backend/stack.go:86 +0xba
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Preview(_, {_, _}, {0xc0001b1cc0, {0xc000320558, 0xa}, {0x0, 0x0, 0x0}, 0xc000d4fbf0, ...})
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:147 +0x88
main.newPreviewCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/preview.go:211 +0x1114
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000c70f00?, {0xc0000f5040, 0x0, 0x5})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000c70f00, {0xc0000f4ff0, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ae4c80)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
```

**Comment by alexrocco** [comment]
@aureq Sorry, is not the exact same issue, as the architecture here is `amd64`, and also having the same issue on GitHub Actions.

```
stdout: Previewing update ():
  
   stderr: ================================================================================
  The Pulumi CLI encountered a fatal error. This is a bug!
  We would appreciate a report: https://github.com/pulumi/pulumi/issues/
  Please provide all of the below text in your report.
  ================================================================================
  Pulumi Version:   v3.44.0
  Go Version:       go1.19.2
  Go Compiler:      gc
  Architecture:     amd64
  Operating System: linux
  Panic:            interface conversion: interface {} is map[string]interface {}, not plugin.JSONSchema
  
  goroutine 1 [running]:
  runtime/debug.Stack()
  	/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/debug/stack.go:24 +0x65
  main.panicHandler()
  	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
  panic({0x1fa4f60, 0xc000e11980})
  	/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/panic.go:884 +0x212
  github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.convertConfigSchema(0xc00140ee10)
  	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/analyzer_plugin.go:618 +0x1c7
  github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*analyzer).GetAnalyzerInfo(0xc000c09240)
  	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/analyzer_plugin.go:295 +0x3f4
  github.com/pulumi/pulumi/pkg/v3/engine.installAndLoadPolicyPlugins(0xc00078d290, {0x38b1670?, 0x22ab8ee?}, {0x0?, 0xc00090de10?, 0xc00078d290?}, {0xc00081a3f0, 0x1, 0x7f60439c15b8?}, 0xc000c08d40)
  	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:325 +0x69c
  github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource({_, _}, {{{0xc00081a3f0, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
  	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:406 +0x22d
  github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0xc00081a3f0, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
  	/home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:161 +0x263
  github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0xc00081a3f0, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
  	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:451 +0x391
  github.com/pulumi/pulumi/pkg/v3/engine.Update({0x286cf80, 0xc000be45d0}, 0xc0013d3e80, {{0xc00081a3f0, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x7fffffff, ...}, ...)
  	/home/runner/work/pulumi/pulumi/pkg/engine/update.go:193 +0x670
  github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc000001d60, {0xc0000634a0, 0x46}, ...}, ...)
  	/home/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:620 +0xa34
  github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).Preview(_, {_, _}, {_, _}, {0xc000001d60, {0xc0000634a0, 0x46}, {0x0, 0x0, ...}, ...})
  	/home/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:493 +0xa7
  github.com/pulumi/pulumi/pkg/v3/backend.PreviewStack({_, _}, {_, _}, {0xc000001d60, {0xc0000634a0, 0x46}, {0x0, 0x0, 0x0}, ...})
  	/home/runner/work/pulumi/pulumi/pkg/backend/stack.go:86 +0xba
  github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localStack).Preview(_, {_, _}, {0xc000001d60, {0xc0000634a0, 0x46}, {0x0, 0x0, 0x0}, 0xc000725260, ...})
  	/home/runner/work/pulumi/pulumi/pkg/backend/filestate/stack.go:73 +0x88
  main.newPreviewCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
  	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/preview.go:211 +0x1114
  github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000be6280?, {0xc00063e120, 0x0, 0x12})
  	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
  github.com/spf13/cobra.(*Command).execute(0xc000be6280, {0xc00063e000, 0x12, 0x12})
  	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
  github.com/spf13/cobra.(*Command).ExecuteC(0xc000b24000)
  	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
  github.com/spf13/cobra.(*Command).Execute(...)
  	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
  main.main()
  	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
  
  
   err?: 
```

**Comment by Frassle** [comment]
Issue found, I'll get a release of 3.44.1 out as soon as possible with the fix for this.

**Comment by Frassle** [comment]
3.44.1 is released, should fix this panic

**Comment by lukemundy-vgw** [comment]
Yep, tried out 3.44.1 earlier this morning and its working fine now. thanks for the prompt fix.
