### ISSUE TITLE
bug in custom provider crashes CLI

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#11287]
### What happened?

I was working on pulumi-command and some sort of bug causes the CLI to panic.

Should be an easy fix?

```
+   └─ command:remote:Command   hostname                create...  error: Preview failed: error reading from server: EO
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   3.45.0-dev.0
Go Version:       go1.19
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x1f7d6c0, 0x3858c90})
	/usr/lib/go/src/runtime/panic.go:884 +0x212
github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run(0xc001910000, 0xc00169c080, {0x287e3b0, 0xc00169a420}, 0x0?, 0x1)
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/engine/deployment.go:330 +0xa7b
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x38ba948, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/engine/update.go:457 +0x4c7
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x2874d80, 0xc00056e3f0}, 0xc00169c080, {{0x38ba948, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, ...}, ...)
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/engine/update.go:193 +0x670
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc000139e00, {0xc00010f9e0, 0x49}, ...}, ...)
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:1164 +0x972
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc000139e00, {0xc00010f9e0, 0x49}, ...}, ...)
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:1073 +0x41f
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Preview(_, {_, _}, {_, _}, {0xc000139e00, {0xc00010f9e0, 0x49}, {0x0, 0x0, ...}, ...})
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:950 +0xa7
github.com/pulumi/pulumi/pkg/v3/backend.PreviewStack({_, _}, {_, _}, {0xc000139e00, {0xc00010f9e0, 0x49}, {0x0, 0x0, 0x0}, ...})
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/backend/stack.go:86 +0xba
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Preview(_, {_, _}, {0xc000139e00, {0xc00010f9e0, 0x49}, {0x0, 0x0, 0x0}, 0xc00150b1b8, ...})
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/backend/httpstate/stack.go:147 +0x88
main.newPreviewCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/preview.go:211 +0x1114
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000eae280?, {0x38ba948, 0x0, 0x0})
	/home/kdixler/go/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000eae280, {0x38ba948, 0x0, 0x0})
```

### Steps to reproduce

slack me if you need more details.

### Expected Behavior

not panic and gracefully terminate.

### Actual Behavior

panics.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Hey hey @dixler  - would you be able to provide a repro for this issue?

**Comment by dixler** [comment]
@kpitzen Yeah sure. It seems that the CLI panics without a useful error message when a provider schema is missing a version.

Not adding a version is an implementation error, but the engine should provide better feedback to the user than a panic.

The repro test case is located here.
https://github.com/pulumi/pulumi/tree/dixler/11287/version-panic-repro/tests/integration/provider-tests/version-panic

**Comment by dixler** [comment]
This was on a dirty branch. My bad.
