### ISSUE TITLE
"Invalid or unknown key" error with kubernetes-aws-yaml template

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#11304]
I was trying to use the `kubernetes-aws-yaml` template, but keep getting errors:

```
  pulumi:pulumi:Stack (aws-dev):
    Error: invocation of aws:index/getAvailabilityZones:getAvailabilityZones returned an error: could not validate provider configuration: 5 errors occurred:
    	* Invalid or unknown key
    	* Invalid or unknown key
    	* Invalid or unknown key
    	* Invalid or unknown key
    	* Invalid or unknown key
    : Error: invocation of aws:index/getAvailabilityZones:getAvailabilityZones returned an error: could not validate provider configuration: 5 errors occurred:
    	* Invalid or unknown key
    	* Invalid or unknown key
    	* Invalid or unknown key
    	* Invalid or unknown key
    	* Invalid or unknown key
        at Object.callback (/snapshot/awsx/node_modules/@pulumi/pulumi/runtime/invoke.js:141:33)
        at Object.onReceiveStatus (/snapshot/awsx/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/snapshot/awsx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/snapshot/awsx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /snapshot/awsx/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)

    error: Error: invocation of aws:index/getAvailabilityZones:getAvailabilityZones returned an error: could not validate provider configuration: 5 errors occurred:
    	* Invalid or unknown key
    	* Invalid or unknown key
    	* Invalid or unknown key
    	* Invalid or unknown key
    	* Invalid or unknown key
```

I had created this template with the `-y` flags and so accepted all the default config parameters:

```yaml
config:
  aws:desiredClusterSize: "3"
  aws:eksNodeInstanceType: t2.medium
  aws:maxClusterSize: "6"
  aws:minClusterSize: "3"
  aws:region: us-west-2
  aws:vpcNetworkCidr: 10.0.0.0/16
```

I thought the issue was that all of these, except for `aws:region`, are template config variables and should not have the `aws:` prefix. I assumed this meant the engine would attempt to configure the AWS provider with them, leading to the failure.

So I changed the config file to:

```yaml
config:
  aws:region: us-west-2
  desiredClusterSize: "3"
  eksNodeInstanceType: t2.medium
  maxClusterSize: "6"
  minClusterSize: "3"
  vpcNetworkCidr: 10.0.0.0/16
```

And yet the errors continue to persist. I'll keep debugging, but posting it here in case this is a known issue.

**Comment by squaremo** [comment]
Thanks for reporting and diagnosing this, Joe. Looks like you are not the only person to run into it: https://github.com/pulumi/pulumi/issues/3546.
