### ISSUE TITLE
 Unable to convert HCL example 

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi#11305]
### What happened?

With the latest version of 

```go
github.com/pulumi/pulumi-terraform-bridge/v3
github.com/pulumi/pulumi/sdk/v3
```

The provider I'm building is `pulumiverse/pulumi-aquasec`.

I get following output, when creating the sdks:

```bash
warning: unable to convert HCL example for Pulumi entity '#/functions/aquasec:index/getPermissionsSets:getPermissionsSets': 1 error occurred:
        * failed to convert HCL for #/functions/aquasec:index/getPermissionsSets:getPermissionsSets to csharp: panic converting HCL: runtime error: invalid memory address or nil pointer dereference

. The example will be dropped from any generated docs or SDKs.
warning: unable to convert HCL example for Pulumi entity '#/functions/aquasec:index/getRoles:getRoles': 1 error occurred:
        * failed to convert HCL for #/functions/aquasec:index/getRoles:getRoles to csharp: panic converting HCL: runtime error: invalid memory address or nil pointer dereference
```

See https://github.com/pulumiverse/pulumi-aquasec/actions/runs/3426284456/jobs/5708011242#step:11:236 for more output in the GitHub action.

### Steps to reproduce

Run the generation of the sdks in this provider -> https://github.com/pulumiverse/pulumi-aquasec

### Expected Behavior

Examples get converted from HCL to the language

### Actual Behavior

The example will be dropped from any generated docs or SDKs.

### Output of `pulumi about`

```bash
pulumi about
CLI          
Version      3.46.0
Go Version   go1.19.2
Go Compiler  gc

Host     
OS       darwin
Version  12.5
Arch     arm64
```

### Additional context

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Here's a stack trace I captured from my reproduction. Regardless of the language, all codegen reliably creates a trace like this (looked at dotnet, go, and node).

```
warning: unable to convert HCL example for Pulumi entity '#/functions/aquasec:index/getUsersSaas:getUsersSaas': 1 error occurred:
	* failed to convert HCL for #/functions/aquasec:index/getUsersSaas:getUsersSaas to go: panic converting HCL: runtime error: invalid memory address or nil pointer dereference. The stack trace from the panic is:
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).convert.func1()
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tfgen/docs.go:1189 +0xb4
panic({0x104a7dd40, 0x105d5b1b0})
	/usr/local/go/src/runtime/panic.go:884 +0x204
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.annotateObjectProperties({0x104ddb2c0?, 0x14001d46d40}, {0x104dc88a0?, 0x0?})
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/pcl/invoke.go:62 +0x148
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*binder).bindInvokeSignature(0x14001d77b00, {0x14001d69340, 0x2, 0x0?})
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/pcl/invoke.go:153 +0x808
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.GenericFunctionSignature.GetSignature(0x14001d7a390?, {0x14001d69340?, 0x6?, 0x1039de960?})
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/hcl2/model/functions.go:57 +0x44
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.(*Function).GetSignature(...)
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/hcl2/model/functions.go:82
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.(*expressionBinder).bindFunctionCallExpression(0x14001b2ba60, 0x140001fa870)
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/hcl2/model/binder_expression.go:431 +0x118
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.(*expressionBinder).bindExpression(0x14001b2ba68?, {0x104dc7770?, 0x140001fa870?})
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/hcl2/model/binder_expression.go:86 +0x2b0
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.BindExpression({0x104dc7770, 0x140001fa870}, 0x14001d7a390, {0x104dcb5a0, 0x14001d7a360}, {0x14001b2bb60, 0x1, 0x103a49e8c?})
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/hcl2/model/binder_expression.go:60 +0xbc
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.BindAttribute(0x14001be4e00, 0x0?, {0x104dcb5a0, 0x14001d7a360}, {0x14001b2bb60, 0x1, 0x1})
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/hcl2/model/attribute.go:78 +0x74
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*binder).bindLocalVariable(0x14001d77b00?, 0x14001d7a4e0)
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/pcl/binder_nodes.go:116 +0x98
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*binder).bindNode(0x104933e20?, {0x104ddbd88, 0x14001d7a4e0})
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/pcl/binder_nodes.go:59 +0x32c
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.BindProgram({0x1400045a848?, 0x1, 0x1}, {0x14001d46740, 0x6, 0x4?})
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/pcl/binder.go:156 +0xb18
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.convertTF12({0x1400045a7e8, 0x1, 0x104278a41?}, {0x1, 0x0, 0x1, 0x0, 0x0, 0x1, {0x0, ...}, ...})
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tf2pulumi/convert/tf12.go:168 +0x1528
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.internalEject({0x1, 0x0, 0x1, 0x0, 0x0, 0x1, {0x0, 0x0}, {0x104ddcbe0, 0x14001d6b110}, ...})
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tf2pulumi/convert/eject.go:145 +0x27c
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.Convert({0x1, 0x0, 0x1, 0x0, 0x0, 0x1, {0x0, 0x0}, {0x104ddcbe0, 0x14001d6b110}, ...})
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tf2pulumi/convert/convert.go:95 +0x1b4
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).convert(0x140000d8280, {0x104ddcbe0, 0x14001d6b110}, {0x10426f3fa, 0x2})
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tfgen/docs.go:1196 +0x284
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).convertHCLToString(0x140000d8280, {0x14000d31e80, 0x75}, {0x14001131280, 0x33}, {0x10426f3fa, 0x2})
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tfgen/docs.go:1224 +0x14c
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).convertHCL(0x140000d8280, {0x14000d31e80, 0x75}, {0x14001131280, 0x33}, {0x0, 0x0}, {0x14001d670d0, 0x1, 0x0?})
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tfgen/docs.go:1354 +0x920
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).convertExamples(0x140000d8280, {0x14000d371e0, 0x153}, {0x14001131280, 0x33}, 0x1)
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tfgen/docs.go:1107 +0xe64
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).convertExamplesInFunctionSpec(0x14001b2dae0?, {0x14001131280, 0x33}, {{0x14000d371e0, 0x153}, 0x0, 0x14000ad1490, {0x0, 0x0}, 0x0, ...})
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tfgen/generate_schema.go:842 +0x7c
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).convertExamplesInSchema(_, {{0x14000550070, 0x7}, {0x1042776e5, 0x7}, {0x1047e5620, 0xb}, {0x104301243, 0x43}, {0x140003d4db0, ...}, ...})
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tfgen/generate_schema.go:867 +0x500
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).Generate(0x140000d8280)
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tfgen/generate.go:783 +0x238
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.func1(0x0?, {0x14000ab0500, 0x1, 0x0?})
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tfgen/main.go:144 +0x468
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunFunc.func1(0x0?, {0x14000ab0500?, 0x0?, 0x0?})
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.44.2/go/common/util/cmdutil/exit.go:96 +0x28
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x140000f8000?, {0x14000ab0500, 0x1, 0x8})
	/Users/robbiemckinstry/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.44.2/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x140000f8000, {0x1400004e0a0, 0x8, 0x8})
	/Users/robbiemckinstry/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x140000f8000)
	/Users/robbiemckinstry/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/robbiemckinstry/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.Main({_, _}, {_, _}, {{0x104de0440, 0x1400053c420}, {0x10427802a, 0x7}, {0x0, 0x0}, ...})
	/Users/robbiemckinstry/workspace/pulumi/pulumi-terraform-bridge/pkg/tfgen/main.go:36 +0x4c
main.main()
	/Users/robbiemckinstry/workspace/pulumi/pulumi-aquasec/provider/cmd/pulumi-tfgen-aquasec/main.go:25 +0x7c
```

**Comment by RobbieMcKinstry** [comment]
Thanks for submitting this @dirien . My first PR in this area of the codebase, but I think we were just missing a guard. Hopefully its as simple as this.

**Comment by RobbieMcKinstry** [comment]
We're merging a fix for this now. I was able to locally verify correctness. Please let me know if you still encounter this issue after the next release and we can reopen. 👍🏻

**Comment by dirien** [comment]
Thanks @RobbieMcKinstry! Will let u know! 👍
