### ISSUE TITLE
Convert test failure in pulumi-terraform-bridge when upgrading pu/pu pkg to v3.47.2

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi#11452]
### What happened?

Bumping the pu/pu pkg dependency to v3.47.2 fails: https://github.com/pulumi/pulumi-terraform-bridge/actions/runs/3534186280/jobs/5930763252

```
=== RUN   TestConvert/regress_cannot_bind_expression
=== CONT  TestConvert
    convert_test.go:127: fixHcl left intact: 
                          variable "region_number" {
                            default = {
                              us-east-1 = 1
                            }
                          }
    convert_test.go:127: fixHcl left intact: 
                          variable "region_number" {
                            default = {
                              us-east-1 = 1
                            }
                          }
        
                          resource "aws_vpc" "example" {
                            cidr_block = cidrsubnet("10.0.0.0/8", 4, 2)
                          }
--- FAIL: TestConvert (4.93s)
    --- FAIL: TestConvert/regress_cannot_bind_expression (4.93s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x148770e]

goroutine 28 [running]:
testing.tRunner.func1.2({0x1fa9020, 0x38253a0})
	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1399 +0x39f
panic({0x1fa9020, 0x38253a0})
	/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/panic.go:884 +0x212
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.MapProvidersAsResources(0x0)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.47.2/codegen/pcl/utilities.go:145 +0x2e
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.GenerateProgram(0x0)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.47.2/codegen/nodejs/gen_program.go:53 +0x36
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/convert.Convert({0x1, 0x0, 0x1, 0x0, 0x0, 0x1, {0x0, 0x0}, {0x2863ee0, 0xc0006de270}, ...})
	/home/runner/work/pulumi-terraform-bridge/pulumi-terraform-bridge/pkg/tf2pulumi/convert/convert.go:105 +0xb5d
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.TestConvert.func1({0x23754e6?, 0xc0000fb6c0?})
	/home/runner/work/pulumi-terraform-bridge/pulumi-terraform-bridge/pkg/tfgen/convert_test.go:52 +0x118
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.TestConvert.func2(0x0?)
	/home/runner/work/pulumi-terraform-bridge/pulumi-terraform-bridge/pkg/tfgen/convert_test.go:93 +0x1bc
testing.tRunner(0xc0000fb6c0, 0xc0004a86b0)
	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1493 +0x35f
```

### Steps to reproduce

Run a new workflow for https://github.com/pulumi/pulumi-terraform-bridge/actions/workflows/weekly-pulumi-update.yml

### Expected Behavior

Successful upgrade

### Actual Behavior

Panic/test failure. See above.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@iwahbe Could you please take a look?

**Comment by Zaid-Ajaj** [comment]
The line where the error occurs is `nodes := make([]Node, 0, len(p.Nodes))` which can only fail when `p : *pcl.Program` is `nil` so suspecting that something went wrong when going tf to pcl without propagating error information that the binding has failed

**Comment by iwahbe** [comment]
From the stack trace, we see the error chain go
https://github.com/pulumi/pulumi/blob/35f8427aa091a315da0c2199c8a72b229e24b47b/pkg/codegen/pcl/utilities.go#L145

https://github.com/pulumi/pulumi/blob/35f8427aa091a315da0c2199c8a72b229e24b47b/pkg/codegen/nodejs/gen_program.go#L52-L53

https://github.com/pulumi/pulumi-terraform-bridge/blob/65079911289212d33b98958221df78168fbe464d/pkg/tf2pulumi/convert/convert.go#L95-L105

There should be an error check on the result of `internalEject`, but I don't see it. `program` should be nil iff that `err != nil`. I suspect adding that error check will give a much more helpful error.

**Comment by Frassle** [comment]
> There should be an error check on the result of internalEject,

Huh my bad, I rewrote that bit to use internalEject. Very surprised the linter didn't pick up that err was unchecked though? Guess we're not running linting here, or at least missing errcheck.

**Comment by Frassle** [comment]
Seems errcheck just doesn't detect this case, I think because the error is checked and returned later on in the method. 
Still merged https://github.com/pulumi/pulumi-terraform-bridge/pull/652 to add the missing check, see if that helps this.

**Comment by iwahbe** [comment]
I don't think that errorcheck will get this case. The underlying problem is a useless assignment (we assign to `err`, then re-assign to `err` without viewing the old value). That would be the `ineffassign` lint.

I assume that the `errcheck` lint only triggers if the var itself is not checker.

**Comment by thomas11** [comment]
Trying with the latest pulumi release 3.48.0, it still fails the same test with an assertion failure instead of a nil ref.

```
2022-11-29T00:33:48.2925209Z === RUN   TestConvert/regress_cannot_bind_expression
2022-11-29T00:33:48.2926019Z === CONT  TestConvert
2022-11-29T00:33:48.2928197Z     convert_test.go:127: fixHcl left intact: 
2022-11-29T00:33:48.2928791Z                           variable "region_number" {
2022-11-29T00:33:48.2929244Z                             default = {
2022-11-29T00:33:48.2929997Z                               us-east-1 = 1
2022-11-29T00:33:48.2930344Z                             }
2022-11-29T00:33:48.2930694Z                           }
2022-11-29T00:33:48.2931056Z     convert_test.go:127: fixHcl left intact: 
2022-11-29T00:33:48.2931625Z                           variable "region_number" {
2022-11-29T00:33:48.2932059Z                             default = {
2022-11-29T00:33:48.2932604Z                               us-east-1 = 1
2022-11-29T00:33:48.2932961Z                             }
2022-11-29T00:33:48.2933282Z                           }
2022-11-29T00:33:48.2933490Z         
2022-11-29T00:33:48.2934038Z                           resource "aws_vpc" "example" {
2022-11-29T00:33:48.2934878Z                             cidr_block = cidrsubnet("10.0.0.0/8", 4, 2)
2022-11-29T00:33:48.2935245Z                           }
2022-11-29T00:33:48.2935512Z     convert_test.go:61: 
2022-11-29T00:33:48.2936361Z         	Error Trace:	/home/runner/work/pulumi-terraform-bridge/pulumi-terraform-bridge/pkg/tfgen/convert_test.go:61
2022-11-29T00:33:48.2937747Z         	            				/home/runner/work/pulumi-terraform-bridge/pulumi-terraform-bridge/pkg/tfgen/convert_test.go:93
2022-11-29T00:33:48.2938250Z         	Error:      	Received unexpected error:
2022-11-29T00:33:48.2938844Z         	            	loader returned @<nil>: expected aws@<nil>
2022-11-29T00:33:48.2939190Z         	Test:       	TestConvert
2022-11-29T00:33:48.2939485Z === CONT  TestConvert/regress_cannot_bind_expression
2022-11-29T00:33:48.2940033Z     testing.go:1343: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
2022-11-29T00:33:48.2940431Z --- FAIL: TestConvert (4.26s)
2022-11-29T00:33:48.2940896Z     --- FAIL: TestConvert/regress_cannot_bind_expression (4.25s)
```

**Comment by iwahbe** [comment]
We have tightened up the contract for the loader. We require that `LoadPackage(name, version)` returns a package where `pkg.Name == name`. 

The test was failing because the loader defined [here](https://github.com/pulumi/pulumi-terraform-bridge/blob/023b36175e3af65d1ac2aac87bdc86f212907280/pkg/tfgen/loaders.go#L24-L27) returned an empty schema for `aws`.

The test runs correctly with this patch:
```patch
 pkg/tfgen/loaders.go | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/pkg/tfgen/loaders.go b/pkg/tfgen/loaders.go
index f80706c..08c609b 100644
--- a/pkg/tfgen/loaders.go
+++ b/pkg/tfgen/loaders.go
@@ -30,7 +30,10 @@ var _ schema.Loader = &loader{}
 
 func (l *loader) LoadPackage(name string, ver *semver.Version) (*schema.Package, error) {
 	if l.emptyPackages[name] {
-		return &schema.Package{}, nil
+		return &schema.Package{
+			Name:    name,
+			Version: ver,
+		}, nil
 	}
 	return l.innerLoader.LoadPackage(name, ver)
 }
```

@viveklak Could you explain the purpose of the [`emptyPackages`](https://github.com/pulumi/pulumi-terraform-bridge/blob/023b36175e3af65d1ac2aac87bdc86f212907280/pkg/tfgen/loaders.go#L26) field, I don't understand why its there.
