### ISSUE TITLE
sdk/go/aws/secretsmanager/secretVersion.go#L82-L92 are incorrectly cast.

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#11664]
### What happened?

> we're looking into upgrading to the latest provider versions currently and we've run into a potential bug caused by this:
> 
> https://github.com/pulumi/pulumi-aws/blame/master/sdk/go/aws/secretsmanager/secretVersion.go#L82-L92
>
> If I understand it correctly it was always acceptable to pass a StringOutput to a StringPtrInput. This change is breaking this, because there's now a cast to StringPtrOutput in the provider implementation. If we were to upgrade this would require us, as well as all customers potentially using this, to switch all call sites to StringPtrOutputs.

It looks like after upgrade to the 4.42.0 of upstream terrraform-provider-aws, these items were marked as secret, causing them to be incorrectly cast by the existing codegen. 

### Steps to reproduce

Here is the equivalent in a go program and it causes pulumi to panic:
```go
func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		// Create an AWS resource (S3 Bucket)
		_, err := secretsmanager.NewSecret(ctx, "my-secret", &secretsmanager.SecretArgs{
			Name:                        pulumi.String("my-secret"),
			Description:                 pulumi.String("My secret"),
			ForceOverwriteReplicaSecret: pulumi.Bool(false),
			Replicas: secretsmanager.SecretReplicaArray{
				&secretsmanager.SecretReplicaArgs{
					Region: pulumi.String("us-east-1"),
				},
			},
		})
		if err != nil {
			return err
		}

		
	      secretsmanager.NewSecretVersion(ctx, "my-secret-version", &secretsmanager.SecretVersionArgs{
				SecretId:     secret.ID(),
				SecretString: pulumi.String("my-secret-value"),
			})
		return nil
	})
}
```

### Expected Behavior

The type is cast correctly and it works.

### Actual Behavior

```
 panic: interface conversion: pulumi.Output is pulumi.StringOutput, not pulumi.StringPtrOutput
    goroutine 1 [running]:
    github.com/pulumi/pulumi-aws/sdk/v5/go/aws/secretsmanager.NewSecretVersion(0x0?, {0x105212783, 0x11}, 0x1400056c280, {0x0, 0x0, 0x0})
        /Users/dirien/go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v5@v5.23.0/go/aws/secretsmanager/secretVersion.go:86 +0x3b8
    main.main.func1(0x1400056a160?)
        /Users/dirien/trash-stacks/aws-classic-test/main.go:20 +0x124
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
Moving over to pulumi/pulumi since this is a codegen issue.
