### ISSUE TITLE
Missing required property 'function' on BucketEventSubscription

### ISSUE THREAD

**Issue by jernaumorat** [pulumi/pulumi#11717]
### What happened?

When trying to run `pulumi up`, Pulumi fails at the stack preview with:

```
error: Running program '/Users/jernaumorat/Documents/.../PROJECT-import-lookup' failed with an unhandled exception:
    Error: Missing required property 'function'
```

The failure occurs at this line: `PROJECTExportBucket.onObjectCreated("PROJECTExportHandler", PROJECTImport)`, commenting it out allows the preview and stack update to proceed as expected (although as expected it deletes the S3 event)

### Steps to reproduce

Bucket configuration:
```ts
export const PROJECTExportBucket = new aws.s3.Bucket("PROJECTExportBucket", {
    serverSideEncryptionConfiguration: {
        rule:{
            applyServerSideEncryptionByDefault: {
                sseAlgorithm: 'AES256'
            }
        }
    },
    lifecycleRules: [
        {
            enabled: true,
            expiration: {days: 30}
        }
    ]
})

PROJECTExportBucket.onObjectCreated("PROJECTExportHandler", PROJECTImport)
```

Lambda Function configuration:
```ts
const PROJECTImportExecutionRole = new aws.iam.Role('PROJECTImport-exec-role', {
    assumeRolePolicy: aws.iam.assumeRolePolicyForPrincipal({Service: 'lambda.amazonaws.com'})
});
const PROJECTImportExecutionPolicy = new aws.iam.RolePolicy('PROJECTImport-exec-policy', {
    role: PROJECTImportExecutionRole,
    policy: {
        Version: '2012-10-17',
        Statement: [
            {
                Action: ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'],
                Effect: 'Allow',
                Resource: '*'
            },
        ]
    }
});

const PROJECTImportCodeBundle = new pulumi.asset.FileArchive('./build/PROJECTImport.zip');

export const PROJECTImport = new aws.lambda.Function('PROJECTImport', {
    code: PROJECTImportCodeBundle,
    handler: 'PROJECTImport.handler',
    role: PROJECTImportExecutionRole.arn,
    runtime: 'nodejs18.x',
    environment: {
        variables: {
            TABLE_NAME: PROJECTDataTable.name,
            BUCKET_NAME: PROJECTExportBucket.bucket
        }
    }
});
```

### Expected Behavior

Stack is updated with the BucketEventSubscription.

### Actual Behavior

Stack update fails at the preview stage:

```
$ pulumi up -y                                                                                                                                                                                   <aws:Sandbox1>
Previewing update (dev)

View Live: https://app.pulumi.com/jernaumorat/PROJECT-import-lookup/dev/previews/969782be-0b63-4317-81cf-446190ba4d01

     Type                                  Name                      Plan       Info
     pulumi:pulumi:Stack                   PROJECT-import-lookup-dev             1 error
     └─ aws:s3:Bucket                      PROJECTExportBucket                   
 +      └─ aws:s3:BucketEventSubscription  PROJECTExportHandler       create     


Diagnostics:
  pulumi:pulumi:Stack (PROJECT-import-lookup-dev):
    error: Running program '/Users/jernaumorat/Documents/.../PROJECT-import-lookup' failed with an unhandled exception:
    Error: Missing required property 'function'
        at new Permission (/Users/jernaumorat/Documents/.../PROJECT-import-lookup/node_modules/@pulumi/lambda/permission.ts:280:23)
        at new BucketEventSubscription (/Users/jernaumorat/Documents/.../PROJECT-import-lookup/node_modules/@pulumi/s3/s3Mixins.ts:145:27)
        at Bucket.bucket_1.Bucket.onEvent (/Users/jernaumorat/Documents/.../PROJECT-import-lookup/node_modules/@pulumi/s3/s3Mixins.ts:275:12)
        at Bucket.bucket_1.Bucket.onObjectCreated (/Users/jernaumorat/Documents/.../PROJECT-import-lookup/node_modules/@pulumi/s3/s3Mixins.ts:258:17)
        at Object.<anonymous> (/Users/jernaumorat/Documents/.../PROJECT-import-lookup/infrastructure/PROJECTExportBucket.ts:22:20)
        at Module._compile (node:internal/modules/cjs/loader:1159:14)
        at Module.m._compile (/Users/jernaumorat/Documents/.../PROJECT-import-lookup/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/jernaumorat/Documents/.../PROJECT-import-lookup/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:1037:32)
```

### Output of `pulumi about`

```
$ pulumi about                                                                                                                                                                                   
CLI          
Version      3.50.1
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.24.0
awsx    1.0.1
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  13.0
Arch     arm64

This project is written in nodejs: executable='/Users/jernaumorat/.nvm/versions/node/v18.12.1/bin/node' version='v18.12.1'

Current Stack: jernaumorat/PROJECT/dev

TYPE                                          URN
pulumi:pulumi:Stack                           urn:pulumi:dev::PROJECT::pulumi:pulumi:Stack::PROJECT-dev
pulumi:providers:aws                          urn:pulumi:dev::PROJECT::pulumi:providers:aws::default_5_24_0
aws:iam/role:Role                             urn:pulumi:dev::PROJECT::aws:iam/role:Role::PROJECTLookup-exec-role
aws:s3/bucket:Bucket                          urn:pulumi:dev::PROJECT::aws:s3/bucket:Bucket::PROJECTExportBucket
aws:iam/role:Role                             urn:pulumi:dev::PROJECT::aws:iam/role:Role::PROJECTUploadWorkflow-exec-role
aws:iam/role:Role                             urn:pulumi:dev::PROJECT::aws:iam/role:Role::PROJECTImport-exec-role
aws:iam/rolePolicy:RolePolicy                 urn:pulumi:dev::PROJECT::aws:iam/rolePolicy:RolePolicy::PROJECTLookup-exec-policy
aws:iam/rolePolicy:RolePolicy                 urn:pulumi:dev::PROJECT::aws:iam/rolePolicy:RolePolicy::PROJECTImport-exec-policy
aws:iam/rolePolicy:RolePolicy                 urn:pulumi:dev::PROJECT::aws:iam/rolePolicy:RolePolicy::PROJECTUploadWorkflow-exec-policy
aws:dynamodb/table:Table                      urn:pulumi:dev::PROJECT::aws:dynamodb/table:Table::PROJECTDataTable
aws:lambda/function:Function                  urn:pulumi:dev::PROJECT::aws:lambda/function:Function::PROJECTLookup
aws:lambda/function:Function                  urn:pulumi:dev::PROJECT::aws:lambda/function:Function::PROJECTImport
aws:s3:BucketEventSubscription                urn:pulumi:dev::PROJECT::aws:s3/bucket:Bucket$aws:s3:BucketEventSubscription::PROJECTExportHandler
aws:transfer/workflow:Workflow                urn:pulumi:dev::PROJECT::aws:transfer/workflow:Workflow::PROJECTUploadWorkflow
aws:lambda/permission:Permission              urn:pulumi:dev::PROJECT::aws:s3/bucket:Bucket$aws:s3:BucketEventSubscription$aws:lambda/permission:Permission::PROJECTExportHandler
aws:transfer/server:Server                    urn:pulumi:dev::PROJECT::aws:transfer/server:Server::PROJECTUploadGateway
aws:transfer/user:User                        urn:pulumi:dev::PROJECT::aws:transfer/user:User::PROJECTUploadUser
aws:transfer/sshKey:SshKey                    urn:pulumi:dev::PROJECT::aws:transfer/sshKey:SshKey::PROJECTUploadUserKey
aws:s3/bucketNotification:BucketNotification  urn:pulumi:dev::PROJECT::aws:s3/bucket:Bucket$aws:s3/bucketNotification:BucketNotification::PROJECTExportHandler


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jernaumorat
User           jernaumorat
Organizations  jernaumorat

Dependencies:
NAME                       VERSION
@aws-sdk/client-dynamodb   3.236.0
@aws-sdk/client-s3         3.236.0
@aws-sdk/signature-v4-crt  3.226.0
@babel/core                7.20.5
@babel/preset-typescript   7.18.6
@pulumi/aws                5.24.0
@pulumi/awsx               1.0.1
@pulumi/pulumi             3.49.0
aws-crt                    1.15.5
babel-loader               9.1.0
cache-loader               4.1.0
csv-parse                  5.3.3
libphonenumber-js          1.10.15
@types/aws-lambda          8.10.109
@types/node                14.18.35
webpack                    5.75.0
webpack-cli                5.0.1

Pulumi locates its logs in /var/folders/ps/gnmd8rvx0rg90h8v5kvcvvkh0000gn/T/ by default
```

### Additional context

Stack had been deployed without issue yesterday. I ran a `brew update` this morning, unfortunately I'm not sure what my previous installed version was.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jernaumorat** [comment]
Thinking that this may be related to #5071, I attempted to `get` the Function resource rather than supplying it directly and discovered that `PROJECTImport` is `undefined` at the point that it's referenced by `.onObjectCreated`.

**Comment by mikhailshilkov** [comment]
Hi @jernaumorat 

I'm trying to repro this issue. Here is my entire program:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const PROJECTImportExecutionRole = new aws.iam.Role('PROJECTImport-exec-role', {
    assumeRolePolicy: aws.iam.assumeRolePolicyForPrincipal({Service: 'lambda.amazonaws.com'})
});
const PROJECTImportExecutionPolicy = new aws.iam.RolePolicy('PROJECTImport-exec-policy', {
    role: PROJECTImportExecutionRole,
    policy: {
        Version: '2012-10-17',
        Statement: [
            {
                Action: ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'],
                Effect: 'Allow',
                Resource: '*'
            },
        ]
    }
});

const PROJECTImportCodeBundle = new pulumi.asset.FileArchive('./Handler.zip');

export const PROJECTImport = new aws.lambda.Function('PROJECTImport', {
    code: PROJECTImportCodeBundle,
    handler: 'PROJECTImport.handler',
    role: PROJECTImportExecutionRole.arn,
    runtime: 'nodejs18.x',
    environment: {
    }
});

export const PROJECTExportBucket = new aws.s3.Bucket("PROJECTExportBucket", {
    serverSideEncryptionConfiguration: {
        rule:{
            applyServerSideEncryptionByDefault: {
                sseAlgorithm: 'AES256'
            }
        }
    },
    lifecycleRules: [
        {
            enabled: true,
            expiration: {days: 30}
        }
    ]
})

PROJECTExportBucket.onObjectCreated("PROJECTExportHandler", PROJECTImport);
```

However, `pulumi up` shows the preview just fine. What am I missing?

**Comment by jernaumorat** [comment]
Hi @mikhailshilkov, what wasn’t clear in my post and may be relevant is that `PROJECTImport` is imported from a sibling file. Happy holidays!

**Comment by mikhailshilkov** [comment]
Thank you for getting back to me. Alright, I changed it to two files:

`func.ts`:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const PROJECTImportCodeBundle = new pulumi.asset.FileArchive('./Handler.zip');

const PROJECTImportExecutionRole = new aws.iam.Role('PROJECTImport-exec-role', {
    assumeRolePolicy: aws.iam.assumeRolePolicyForPrincipal({Service: 'lambda.amazonaws.com'})
});

const PROJECTImportExecutionPolicy = new aws.iam.RolePolicy('PROJECTImport-exec-policy', {
    role: PROJECTImportExecutionRole,
    policy: {
        Version: '2012-10-17',
        Statement: [
            {
                Action: ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'],
                Effect: 'Allow',
                Resource: '*'
            },
        ]
    }
});

export const PROJECTImport = new aws.lambda.Function('PROJECTImport', {
    code: PROJECTImportCodeBundle,
    handler: 'PROJECTImport.handler',
    role: PROJECTImportExecutionRole.arn,
    runtime: 'nodejs18.x',
    environment: {
    }
});
```

`index.ts`:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import { PROJECTImport } from "./func";

const PROJECTExportBucket = new aws.s3.Bucket("PROJECTExportBucket", {
    serverSideEncryptionConfiguration: {
        rule:{
            applyServerSideEncryptionByDefault: {
                sseAlgorithm: 'AES256'
            }
        }
    },
    lifecycleRules: [
        {
            enabled: true,
            expiration: {days: 30}
        }
    ]
})

PROJECTExportBucket.onObjectCreated("PROJECTExportHandler", PROJECTImport);
```

The preview still shows up just fine...
