### ISSUE TITLE
.get panics with Output<string> but works with string

### ISSUE THREAD

**Issue by liamawhite** [pulumi/pulumi#11719]

**Comment by dixler** [comment]
Was able to repro this issue with the following code on the version the reporter was on

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure-native";

const resourceGroup = new azure.resources.ResourceGroup("resourceGroup");
const lbId = pulumi.secret(resourceGroup.id)

export const works = lbId.apply((id) => azure.resources.ResourceGroup.get("thing", id, undefined)) // works
export const notWorks = azure.resources.ResourceGroup.get("thingtoo", lbId, undefined) // doesn't work
```

```
Do you want to perform this update? yes
Updating (dev)

View Live: https://app.pulumi.com/kyle-pulumi-corp/azure-lb/dev/updates/27

     Type                                     Name           Status      Info
     pulumi:pulumi:Stack                      azure-lb-dev   running..   read azure-native:resources:ResourceGroup thing
 +   └─ azure-native:resources:ResourceGroup  resourceGroup  created     
panic: fatal: An assertion has failed

goroutine 295 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/home/kdixler/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
	/home/kdixler/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*provider).Read(0x1f0a228?, {0xc00032c0f0?, 0x10?}, {0x0?, 0x0?}, 0x7f9562d15cc8?, 0x7f958ca7ea68?)
	/home/kdixler/go/src/github.com/pulumi/pulumi/sdk/go/common/resource/plugin/provider_plugin.go:809 +0xb54
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*ReadStep).Apply(0xc0016d9560, 0x48?)
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/step.go:636 +0xcc
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeStep(0xc001566300, 0x0?, {0x1f0a228, 0xc0016d9560})
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:302 +0x1e2
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc001566300, 0xc000513728?, {0xc0017febf0?, 0x1, 0x0?})
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:252 +0xe5
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1()
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:414 +0xd9
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker
	/home/kdixler/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:411 +0x2b1
```

on SDK v3.86.0 it with master complains with

```
% pulumi up
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/kyle-pulumi-corp/azure-lb/dev/previews/a2455bd4-0e9e-46e4-8a8d-def6fb70b7f0

     Type                                     Name          Plan     Info
     pulumi:pulumi:Stack                      azure-lb-dev           
     └─ azure-native:resources:ResourceGroup  thingtoo               1 error


Diagnostics:
  azure-native:resources:ResourceGroup (thingtoo):
    error: Expected an ID for urn:pulumi:dev::azure-lb::azure-native:resources:ResourceGroup::thingtoo

```

**Comment by Frassle** [comment]
I think it's because `serializeProperty` is returning the JSON encoding for a secret object here, not just the string value.
It should probably be doing an output await to get the literal string from it (or unknown) and then setting the RPC requests ID field by that.

_But_ on that point I went and checked the engine support for this.
The engine doesn't actually handle unknowns for ID in a ReadResource call... 

So something doesn't line up here, I think there are three choices, and none of them are great.

1. Fix the typing information here that ID actually needs to be a prompt value (`Promise<string>`, not `Output<string>`). That's a risky breaking change for anyone using Outputs that _happen_ to resolve at the moment.
2. Fix the SDK to skip the ReadResource call when the ID is unknown. I'm not sure what the SDK should return in this case, probably just resolve every property on the resource to unknown straight away.
3. Fix the engine to allow an unknown value here (probably indicated by the empty string), where the engine would then just return nothing right away.
