### ISSUE TITLE
Pulumi complains about tsconfig when using "extends"

### ISSUE THREAD

**Issue by sam-goodwin** [pulumi/pulumi#11947]
### What happened?

`pulumi up` throws an error whenever I use `extends` in my `tsconfig.json` (which I always do). It seems to recursively validate the tsconfig extends chain but doesn't respect how tsconfig files are merged into a final config. 

### Steps to reproduce

1. Create a TypeScript Pulumi app.
2. Install `"@tsconfig/node16": "^1.0.3",`
3. Configure `tsconfig.json` with the following:
```json
{
  "extends": "@tsconfig/node16/tsconfig.json",
  // your overrides
}
```
4. run `pulumi up`

### Expected Behavior

Pulumi should only use the final merged `tsconfig.json` value and not worry about recursively validate the hierarchy.

### Actual Behavior

Even though my final `tsconfig.json` has all the correct configuration, Pulumi still believes it's misconfigured because the file i'm extending doesn't contain those same values.

```
    error: TSError: ⨯ Unable to compile TypeScript:
    ../tsconfig.base.json(10,13): error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'esnext', 'dom', 'dom.iterable', 'webworker', 'webworker.importscripts', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.asyncgenerator', 'es2018.asynciterable', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'es2019.array', 'es2019.object', 'es2019.string', 'es2019.symbol', 'es2020.bigint', 'es2020.promise', 'es2020.string', 'es2020.symbol.wellknown', 'esnext.array', 'esnext.symbol', 'esnext.asynciterable', 'esnext.intl', 'esnext.bigint'.
    ../node_modules/@tsconfig/node16/tsconfig.json(6,13): error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'esnext', 'dom', 'dom.iterable', 'webworker', 'webworker.importscripts', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.asyncgenerator', 'es2018.asynciterable', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'es2019.array', 'es2019.object', 'es2019.string', 'es2019.symbol', 'es2020.bigint', 'es2020.promise', 'es2020.string', 'es2020.symbol.wellknown', 'esnext.array', 'esnext.symbol', 'esnext.asynciterable', 'esnext.intl', 'esnext.bigint'.
    ../node_modules/@tsconfig/node16/tsconfig.json(8,15): error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'esnext'.

        at createTSError (/Users/samgoodwin/workspaces/pulumi-L2/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:261:12)
        at Object.register (/Users/samgoodwin/workspaces/pulumi-L2/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:265:42)
        at Object.run (/Users/samgoodwin/workspaces/pulumi-L2/node_modules/@pulumi/cmd/run/run.ts:219:13)
        at /Users/samgoodwin/workspaces/pulumi-L2/node_modules/@pulumi/cmd/run/index.ts:162:57
```

### Output of `pulumi about`

```
CLI
Version      3.52.0
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  13.1
Arch     arm64

This project is written in nodejs: executable='/Users/samgoodwin/.nvm/versions/node/v18.13.0/bin/node' version='v18.13.0'

Current Stack: sam-g/quickstart/dev

TYPE                         URN
pulumi:pulumi:Stack          urn:pulumi:dev::quickstart::pulumi:pulumi:Stack::quickstart-dev
pulumi:providers:aws         urn:pulumi:dev::quickstart::pulumi:providers:aws::default_5_27_0
cdk:index:Stack              urn:pulumi:dev::quickstart::cdk:index:Stack::test-stack
pulumi:providers:aws-native  urn:pulumi:dev::quickstart::pulumi:providers:aws-native::default_0_18_0
cdk:construct:LambdaStack    urn:pulumi:dev::quickstart::cdk:index:Stack$cdk:construct:LambdaStack::test-stack/test-stack
cdk:construct:Function       urn:pulumi:dev::quickstart::cdk:index:Stack$cdk:construct:LambdaStack$cdk:construct:Function::test-stack/test-stack/Foo
cdk:construct:Role           urn:pulumi:dev::quickstart::cdk:index:Stack$cdk:construct:LambdaStack$cdk:construct:Function$cdk:construct:Role::test-stack/test-stack/Foo/ServiceRole
aws-native:iam:Role          urn:pulumi:dev::quickstart::cdk:index:Stack$cdk:construct:LambdaStack$cdk:construct:Function$cdk:construct:Role$aws-native:iam:Role::FooServiceRole7A8BDD5B
aws-native:lambda:Function   urn:pulumi:dev::quickstart::cdk:index:Stack$cdk:construct:LambdaStack$cdk:construct:Function$aws-native:lambda:Function::FooDFE0DD70


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/sam-g
User           sam-g
Organizations  sam-g

Pulumi locates its logs in /var/folders/n4/xg8p19md0q97kssylnmllk3w0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by WSanders31** [comment]
It would also appear using a greater version of `ts-node` than Pulumi uses with `tsconfig` settings that don't yet exist in that old version of `ts-node`, will break in a similar fashion. 

IE. Trying to utilize ES2022 - isn't recognized by `ts-node` version 7.0.1 that Pulumi uses internally, but is recognized by future versions of ts-node (I'm using 10.9.1). 

```error: TSError: ⨯ Unable to compile TypeScript:
    error TS5023: Unknown compiler option 'ignoreDeprecations'.
    node_modules/@tsconfig/node18-strictest-esm/tsconfig.json(8,7): error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'esnext', 'dom', 'dom.iterable', 'webworker', 'webworker.importscripts', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.asyncgenerator', 'es2018.asynciterable', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'es2019.array', 'es2019.object', 'es2019.string', 'es2019.symbol', 'es2020.bigint', 'es2020.promise', 'es2020.string', 'es2020.symbol.wellknown', 'esnext.array', 'esnext.symbol', 'esnext.asynciterable', 'esnext.intl', 'esnext.bigint'.
    node_modules/@tsconfig/node18-strictest-esm/tsconfig.json(10,15): error TS6046: Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'es2020', 'esnext'.
    node_modules/@tsconfig/node18-strictest-esm/tsconfig.json(11,15): error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'esnext'.
    node_modules/@tsconfig/node18-strictest-esm/tsconfig.json(19,5): error TS5023: Unknown compiler option 'exactOptionalPropertyTypes'.
    node_modules/@tsconfig/node18-strictest-esm/tsconfig.json(21,5): error TS5023: Unknown compiler option 'noImplicitOverride'.
    node_modules/@tsconfig/node18-strictest-esm/tsconfig.json(23,5): error TS5023: Unknown compiler option 'noPropertyAccessFromIndexSignature'.
    node_modules/@tsconfig/node18-strictest-esm/tsconfig.json(24,5): error TS5023: Unknown compiler option 'noUncheckedIndexedAccess'.
```
    
 I assume this isn't expected because Pulumi docs specify that you can utilize whichever `tsconfig` settings you wish: `"You may customize this however you’d like, including the TypeScript settings that work for you"` -https://www.pulumi.com/docs/intro/languages/javascript/#3-create-tsconfigjson

**Comment by RobbieMcKinstry** [comment]
@WSanders31 not only that, but the version of TypeScript itself is locked. https://github.com/pulumi/pulumi/issues/12687 has more details here. It's something I'm working on fixing this quarter. I believe the documentation you've referenced is eliding that the version of TypeScript serves as an upper bound for what the allowable configurables in `tsconfig.json` are.

**Comment by bradleyayers** [comment]
I'm having a related issue where it seems like `extends` just isn't supported by Pulumi in `tsconfig.json` files, going by https://github.com/pulumi/pulumi/blob/b67c72149ca97bd1008e258017004894c1a9837b/sdk/nodejs/tsutils.ts#L27C29-L27C54 it looks like only the immediate `tsconfig.json` is parsed, `compileOptions` extracted, and then spread over some defaults (see https://github.com/pulumi/pulumi/blob/b67c72149ca97bd1008e258017004894c1a9837b/sdk/nodejs/cmd/run/run.ts#L272).

In my case I have a `tsconfigBase.json` that defines `"composite": true`, then in my `tsconfig.json` I define `"tsBuildInfoFile": "dist/.tsbuildinfo",`. Unfortunately with this setup, `ts-node` doesn't see the `composite: true`, so I get this error from Pulumi:

```
Previewing update (dev):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::website-infra::pulumi:pulumi:Stack::website-infra-dev]
error: Running program '/Users/brad/src/workspaces/website-infra/src/index.ts' failed with an unhandled exception:
TSError: ⨯ Unable to compile TypeScript:
error TS5069: Option 'tsBuildInfoFile' cannot be specified without specifying option 'incremental' or option 'composite'.
```

This took a little bit of digging around to figure out, perhaps a short term safe guard is to throw an error if `extends` exist, in https://github.com/pulumi/pulumi/blob/b67c72149ca97bd1008e258017004894c1a9837b/sdk/nodejs/tsutils.ts#L27C29-L27C54 and explicitly say `extends` is not supported at this time.

**Comment by justinvp** [comment]
Closing this as fixed. You can now use the latest versions of TypeScript and ts-node. See https://www.pulumi.com/blog/typescript-versions/ for more details.
