### ISSUE TITLE
Codegen panics if a provider resource is named `provider`

### ISSUE THREAD

**Issue by aq17** [pulumi/pulumi#11961]
While updating the [pulumi-databricks](https://github.com/pulumi/pulumi-databricks) upstream provider, a new resource `databricks_provider` was added. Attempting to build the sdks results in a panic due to the resource mapping conflict on the name `Provider`
```
panic: fatal: An assertion has failed: duplicate file: provider.ts

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/alexqiu/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.44.2/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x50?, {0x103d6b562?, 0x14011312a50?}, {0x14010c9d090?, 0xb?, 0xb?})
        /Users/alexqiu/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.44.2/go/common/util/contract/assert.go:33 +0xe0
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.fs.add(...)
        /Users/alexqiu/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/nodejs/gen.go:1744
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.(*modContext).gen.func2({{0x14011312850, 0x8}, {0x14011312920, 0xc}, {0x140113128f0, 0xd}, {0x0, 0x0}}, {0x14011312a30?, 0x10262b9c4?}, ...)
        /Users/alexqiu/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/nodejs/gen.go:1790 +0x20c
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.(*modContext).gen(0x14008af0700, 0x140105f7ad0)
        /Users/alexqiu/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/nodejs/gen.go:1858 +0x874
github.com/pulumi/pulumi/pkg/v3/codegen/nodejs.GeneratePackage({0x103dae9ab?, 0x14000beaea0?}, 0x140088b2780, 0x0?)
        /Users/alexqiu/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.44.2/codegen/nodejs/gen.go:2561 +0x28c
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.Language.emitSDK({_, _}, _, {{0x1049075c0, 0x14000bfe720}, {0x103d57f7d, 0xa}, {0x0, 0x0}, {0x103d57f7d, ...}, ...}, ...)
        /Users/alexqiu/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.33.0/pkg/tfgen/generate.go:121 +0x270
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).Generate(0x14000c10280)
        /Users/alexqiu/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.33.0/pkg/tfgen/generate.go:816 +0x644
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.func1(0x0?, {0x14000c073b0, 0x1, 0x0?})
        /Users/alexqiu/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.33.0/pkg/tfgen/main.go:144 +0x468
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunFunc.func1(0x0?, {0x14000c073b0?, 0x0?, 0x0?})
        /Users/alexqiu/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.44.2/go/common/util/cmdutil/exit.go:96 +0x28
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000b0db80?, {0x14000c073b0, 0x1, 0x3})
        /Users/alexqiu/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.44.2/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000b0db80, {0x140001b4010, 0x3, 0x3})
        /Users/alexqiu/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x14000b0db80)
        /Users/alexqiu/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/alexqiu/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.Main({_, _}, {_, _}, {{0x1049075c0, 0x14000bfe720}, {0x103d57f7d, 0xa}, {0x0, 0x0}, ...})
        /Users/alexqiu/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.33.0/pkg/tfgen/main.go:36 +0x4c
main.main()
        /Users/alexqiu/github.com/pulumi/pulumi-databricks/provider/cmd/pulumi-tfgen-databricks/main.go:25 +0x7c
make: *** [build_nodejs] Error 2
```

**Comment by Frassle** [comment]
Thinking the easiest way to handle this is to just not allow top level resources/functions/types to be called "Provider" given it clashes with the built in "Provider" type pulumi will emit for every SDK.
Provider types in modules should be ok (e.g. "myProvider:index:provider" error, "myProvider:somemod:provider" ok)
