### ISSUE TITLE
pulumi import -f panics if the file is missing an ID

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi#12103]
### What happened?

I ran `pulumi import -f import.json` with a file containing roughly:

```json
{
	"resources": [
		{
			"type": "someTokenType",
			"name": "someName"
		}
	]
}
```

This panicked with:

```
panic: fatal: An assertion has failed

                                     goroutine 66 [running]:
                                                            github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
                                                                                                                                        /home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
                github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
                                                                                        /home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
                                                                                                                                                                github.com/pulumi/pulumi/pkg/v3/resource/deploy.newImportDeploymentStep(0x0?, 0xc001571d10?, {0xc0015ab900?, 0x1?, 0x0?})
                                                                                        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/step.go:886 +0x319
                                                                                                                                                              github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*importer).importResources(0xc000f95948, {0x2b0a3d0, 0xc0015a3b80})
                                                                                        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/import.go:359 +0x805
                                                                                                                                                                github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).importResources(0xc0015a1e18, {0x2b0a478, 0xc00163d860}, {{0x79ed181aadb0, 0xc0003d2900}, 0x7fffffff, 0x0, 0x0, {{0x0, 0x0, ...}, ...}, ...}, ...)
                                                                                                                                                                                        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:455 +0x132
                                                                           github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute(0xc0015a1e18, {0x2b0a478?, 0xc00163d860}, {{0x79ed181aadb0, 0xc0003d2900}, 0x7fffffff, 0x0, 0x0, {{0x0, 0x0, ...}, ...}, ...}, ...)
                                                                                                /home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:144 +0xe38
                                                                                                                                                                                     github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Deployment).Execute(0xc001650160, {0x2b0a478, 0xc00163d860}, {{0x79ed181aadb0, 0xc0003d2900}, 0x7fffffff, 0x0, 0x0, {{0x0, 0x0, ...}, ...}, ...}, ...)
                                                                                                                                                                                                /home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:534 +0xd0
                                                                         github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run.func1()
                                                                                                                                                /home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:291 +0x290
                 created by github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run
                                                                                        /home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:274 +0x365
```

Note that the formatting is all over the place because the panic also left the terminal in a bad mode.

### Expected Behavior

`pulumi import` succeeds or gives me a meaningful error message.

Instead, it only prints "panic: fatal: An assertion has failed".

### Steps to reproduce

- Create a new project

- Create a file import.json with the contents:

    ```json
    {
        "resources": [
            {
                "type": "someTokenType",
                "name": "someName"
            }
        ]
    }
    ```

- Run `pulumi import -f import.json`

### Output of `pulumi about`

```
% pulumi about
CLI
Version      3.54.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME    VERSION
github  4.17.0
go      unknown

Host
OS       arch
Version
Arch     x86_64

This project is written in go: executable='/usr/bin/go' version='go version go1.20 linux/amd64'

[..]


Dependencies:
NAME                                    VERSION
github.com/pulumi/pulumi-github/sdk/v4  4.17.0
github.com/pulumi/pulumi/sdk/v3         3.51.0
```

### Additional context

The error is coming from this line. https://github.com/pulumi/pulumi/blob/8915911825ba26aea1ad4a53aa666eacff8ca7da/pkg/resource/deploy/step.go#L886

The file I supplied was obviously invalid, but that should not result in an inscrutable panic.

Perhaps as a general practice, we should replace all contract.Asserts with Assertfs so that we're forced to supply a message. (And, where possible, we should just use errors instead of contract.Assert.)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> The file I supplied was obviously invalid, but that should not result in an inscrutable panic.

Indeed we should never panic for bad user input. This should be an error.

> Perhaps as a general practice, we should replace all contract.Asserts with Assertfs so that we're forced to supply a message. 

I like that idea. Would it be easy to add a lint check that we only use Assertf?

> And, where possible, we should just use errors instead of contract.Assert.)

We should use the right tool for the job, I'm happy with asserts for things that should never happen or are programming bugs (like passing nil pointers to methods that don't expect that, or conversions failing for things we've just constructed so know they are convertible)

**Comment by jaxxstorm** [comment]
> contract.Asserts with Assertfs so that we're forced to supply a message.

I would strongly support this as an investment.

**Comment by abhinav** [comment]
> I like that idea. Would it be easy to add a lint check that we only use Assertf?

Ah I see contract.Assert is in sdk/ so we can't delete it.
Yeah, we can add a deprecated comment on it and staticcheck will start erroring out for those lines.

> We should use the right tool for the job

Agree. That might have been too general a statement based on the specific case from this PR.
Yes, panics should happen when the universe is broken, but not on invalid user input.

**Comment by abhinav** [comment]
Pulled out `Assert` deprecation discussion into its own issue: #12132
