### ISSUE TITLE
Unit testing fails against eks clusters in component resource

### ISSUE THREAD

**Issue by caboog** [pulumi/pulumi#12141]
### What happened?

Customer reports that they are unable to get a successful unit test against their EKS component resource code. All other component resource tests work as expected.  Code is in typescript and using Jest for testing.

Slack thread: https://pulumi.slack.com/archives/C04AFE25P9V/p1671583496501659
Zendesk ticket: https://pulumi.zendesk.com/agent/tickets/2233

Customer's error message:

```
 RUNS  tests/services/eks.test.ts
/Users/365546/Code/lost--ml--infrastructure/ml-service/node_modules/@pulumi/eks/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/invoke.js:135
            const resp = yield debuggable_1.debuggablePromise(new Promise((innerResolve, innerReject) => monitor.invoke(req, (err, innerResponse) => {
                                                                                                                 ^

<ref *1> TypeError: Cannot read properties of undefined (reading 'invoke')
    at /Users/365546/Code/lost--ml--infrastructure/ml-service/node_modules/@pulumi/eks/node_modules/@pulumi/aws/node_modules/@pulumi/runtime/invoke.ts:145:21
    at new Promise (<anonymous>)
    at /Users/365546/Code/lost--ml--infrastructure/ml-service/node_modules/@pulumi/eks/node_modules/@pulumi/aws/node_modules/@pulumi/runtime/invoke.ts:144:51
    at Generator.next (<anonymous>)
    at fulfilled (/Users/365546/Code/lost--ml--infrastructure/ml-service/node_modules/@pulumi/eks/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58) {
  promise: Promise { <rejected> [Circular *1] }
}
```

### Expected Behavior

Unit tests pass.

### Steps to reproduce

Component resource code: 

```
import * as eks from "@pulumi/eks";
import * as pulumi from "@pulumi/pulumi";

/**
 * IEksArgs
 * The arguments for the Sqs class constructor.
 * @interface
 * 
 * @property {string} project - The project name
 * @property {string} environment - The environment name
 * @property {string} organization - The organization name
 * @property {pulumi.Input<{[key: string]: any}>} tags
 */
interface IEksArgs {
  project: string;
  environment: string;
  organization: string;
  tags: pulumi.Input<{[key: string]: any}>;
  vpcId: pulumi.Output<any>;
  privateSubNetIds: pulumi.Output<any>;
}

/**
 * Eks
 * The EKS cluster for the ML Service to run on
 * @class
 * @param {string} name - The name of the resource
 * @param {IECRReposArgs} args - The arguments for the class constructor
 * @param {pulumi.ComponentResourceOptions} opts - The options for the class constructor
 */
export default class Eks extends pulumi.ComponentResource {
  public readonly kubeconfig: pulumi.Output<any>;
  // public readonly imageProcessQueue: pulumi.Output<string>;

  constructor(name: string, args: IEksArgs, opts?: pulumi.ComponentResourceOptions) {
    super("POur:ML:Eks", name, {}, opts);
        
    /**
     * Create the EKS cluster
     * @var {eks.Cluster} cluster - The ML Service EKS cluster
     */
    const cluster = new eks.Cluster(`${args.project}-${args.environment}-eks-cluster`, {
      clusterTags: args.tags,
      desiredCapacity: 1,
      instanceType: "t2.medium",
      maxSize: 1,
      minSize: 1,
      name: `${args.project}-${args.environment}-eks-cluster`,
      clusterSecurityGroupTags: args.tags,
      nodeSecurityGroupTags: args.tags,
      vpcId: args.vpcId,    
      subnetIds: args.privateSubNetIds,
      userMappings: [
        {
          groups: ["system:masters"],
          userArn: "arn:aws:iam::582448216311:user/zachary.hinchcliff",
          username: "zachary.hinchcliff"
        },
        {
          groups: ["system:masters"],
          userArn: "arn:aws:iam::582448216311:user/ryan.davis",
          username: "ryan.davis"
        },
        {
          groups: ["system:masters"],
          userArn: "arn:aws:iam::582448216311:user/shannon.cronin",
          username: "shannon.cronin"
        }
      ]
    }, {
      parent: this
    });

    /**
     * Get the kubeconfig for the cluster
     * @var {pulumi.Output<string>} this.kubeconfig - The kubeconfig for the cluster
     */
    this.kubeconfig = cluster.kubeconfig;
  }
}
```

Jest test file:

```
import * as pulumi from '@pulumi/pulumi';
import EKS from '../../src/services/eks';

pulumi.runtime.setMocks(
  {
    newResource: function (args: pulumi.runtime.MockResourceArgs): {
      id: string;
      state: any;
    } {
      return {
        id: args.inputs.name + '_id',
        state: {
          ...args.inputs,
        },
      };
    },
    call: function (args: pulumi.runtime.MockCallArgs) {
      return args;
    },

  },
  'project',
  'stack',
  false,
  'organization'
);


describe('EKS', () => {
  it('Creates the Proper EKS Resources', async () => {
    const project = "project";
    const environment = "test";
    const organization = "organization";
    const tags = {
      "test": "test"
    };
    const vpcId: pulumi.Output<any> = pulumi.interpolate`vpc-${project}-${environment}`;
    const privateSubNetIds: pulumi.Output<any> = pulumi.interpolate`privateSubNetIds-${project}-${environment}`;
    const eks = new EKS("test", {
      project,
      environment,
      organization,
      tags,
      vpcId,
      privateSubNetIds
    });
    expect(eks).toBeDefined();
    expect(eks.kubeconfig).toBeDefined();
  })
});
```

### Output of `pulumi about`

Not provided by the customer

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by abhinav** [comment]
The error indicates that monitor is somehow not defined, which can happen if the `setMocks` didn't "take".
From the [Unit testing docs](https://www.pulumi.com/docs/guides/testing/unit/#write-the-tests),

**Comment by abhinav** [comment]
The error indicates that monitor is somehow not defined, which can happen if the `setMocks` didn't "take".
From the [Unit testing docs](https://www.pulumi.com/docs/guides/testing/unit/#write-the-tests),
they may need to import EKS inside describe -- after the mocks have been set.


```javascript
pulumi.runtime.setMocks({
  // ...
})

describe('EKS', () => {
  let EKS: typeof import("../../src/services/eks");
  before(async function() {
    EKS = await import("../../src/services/eks");
  })

  it('Creates the Proper EKS Resources', async () => {
    const project = "project";
    // ...
```

**Comment by caboog** [comment]
Passing this over to the customer. Thanks @abhinav!

**Comment by jasonyic** [comment]
Hi @abhinav, I am running into the similar issue and `import` inside `describe` does not help. in my class,  I am creating a new `repository`, thank you for your help
```
     this.repo = new aws.ecr.Repository(name, {
        name: args.repoName,
        tags: defaultTags,
        imageTagMutability,
      }, {
        ...defaultOpts,
        deleteBeforeReplace: true,
      });
```

**Comment by t0yv0** [comment]
Thank you for this fix! It might be pertinent to something else we were running into with @corymhall in the pulumi-cdk context.
