### ISSUE TITLE
Requirement to have Pulumi code separate from main source

### ISSUE THREAD

**Issue by semiautomatix** [pulumi/pulumi#12357]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Related to: https://github.com/pulumi/templates/issues/291#issuecomment-1453121909

I have a specific use case (which I'm replicating from an AWS CDK use case) where we specifically use the main source code folder, with `index.ts` to package our project in a repository, for access from our other repositories (usually an orchestration service).

As such, we don't specifically deploy to our environment (using Pulumi) in this specific project. However, there may be a need to test the resource locally, either using `preview` or possibly deploying to a sandbox environment. 

We cannot change the `main` path in the `package.json` file as this would prevent our repository from being published. We are then also unable to use any Pulumi commands as the main folder is invalid.

```json
  "name": "@sa-retail/ret-aws-serverless",
  "version": "1.0.0",
  "description": "",
  "main": "lib/index.ts",
```

I only `pulumi up` locally and that is in a separate folder for testing or deploying for local. 

```zsh
Diagnostics:
  pulumi:pulumi:Stack (ret-aws-serverless-dev):
    error: Error: Error reading file '/workspace/ret-aws-serverless/bin/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open '/workspace/ret-aws-serverless/bin/package.json'
        at readFile (/workspace/ret-aws-serverless/node_modules/.pnpm/@pulumi+pulumi@3.55.0/node_modules/@pulumi/runtime/closure/codePaths.ts:250:19)
        at computeDependenciesDirectlyFromPackageFile (/workspace/ret-aws-serverless/node_modules/.pnpm/@pulumi+pulumi@3.55.0/node_modules/@pulumi/runtime/closure/codePaths.ts:229:22)
        at /workspace/ret-aws-serverless/node_modules/.pnpm/@pulumi+pulumi@3.55.0/node_modules/@pulumi/runtime/closure/codePaths.ts:187:36
        at /workspace/ret-aws-serverless/node_modules/.pnpm/read-package-tree@5.3.1/node_modules/read-package-tree/rpt.js:162:20
```

Pulumi.yaml

```yaml
name: ret-aws-serverless
runtime: nodejs
description: Provision AWS Serverless infrastructure for the Retail project
main: bin/
```

On the advice of @AaronFriel I have removed `bin/` from my Pulumi.yaml file.

As a stop gap, or may a permanent solution, I will convert the project to a monorepo.

### Affected area/feature

Pulumi CLI

**Comment by AaronFriel** [comment]
@semiautomatix thanks for raising this here, I'll leave the needs-triage label for the platform team to find this ticket in case they have more insight.

So I understand correctly, you have an NPM package such as `"@sa-retail/ret-aws-serverless"` and you would like to export this as both a library and use as a Pulumi program?

In situations like this, it's possible to use a folder structure like this:

```
ret-aws-serverless/
├─ node_modules/
├─ infra/
│  ├─ index.ts
│  ├─ Pulumi.yaml
├─ src/
│  ├─ index.ts
├─ package.json
```

Here I've put `Pulumi.yaml` and the program entrypoint, `index.ts`, in a subdirectory of the NPM package. That `infra/index.tx` program can still be part of the same NPM package, and therefore can import shared library code in `src`, e.g.:

```ts
// infra/index.ts
import aws from "@pulumi/aws"

import { Foo, bar, baz } from "../src" // using CommonJS imports

// can use Foo, bar, baz, exported from the Node package

new aws.s3.Bucket(...);
```

**Comment by semiautomatix** [comment]
Thanks @AaronFriel 

I'm unsure how this would work, I've updated, as per your suggestion:

```
ret-aws-serverless/
├─ node_modules/
├─ bin/
│  ├─ index.ts
│  ├─ Pulumi.yaml
├─ lib/
│  ├─ index.ts
├─ package.json
```

As we are publishing the library the main is set tot he `lib` folder in `package.json`:

```json
  "main": "lib/index.ts",
```

```typescript
// bin/index.ts

import * as pulumi from '@pulumi/pulumi';
import * as dotenv from 'dotenv'; // see https://github.com/motdotla/dotenv#how-do-i-use-dotenv-with-import
dotenv.config();
import { ServerlessApiGateway } from '../lib/';

const branchName = process.env.BRANCH_NAME ?? 'localhost';

const apiGateway = new ServerlessApiGateway(pulumi.getProject(), branchName, pulumi.getStack());

export const apiUrl = apiGateway.restApi.url;
```

Unfortunately, I'm not unable to run the `pulumi up` command from the root or `bin\` folder? What am I missing?

**Comment by semiautomatix** [comment]
Thanks for getting back to me.

> What error do you get with this approach, and what is the content of `Pulumi.yaml`?

```bash
/ret-aws-serverless/bin (main) $ pulumi up -s dev
Logging in using access token from PULUMI_ACCESS_TOKEN
Previewing update (dev)

View Live: https://app.pulumi.com/semiautomatix/ret-aws-serverless/dev/previews/40ea9037-167e-42d2-96ac-420ff1501b99

Downloading plugin aws v5.30.0: 151.80 MiB / 151.80 MiB [===========] 100.00% 7s
Downloading plugin aws-apigateway v1.0.1: 20.12 MiB / 20.12 MiB [===] 100.00% 1s
     Type                 Name                    Plan     Info
     pulumi:pulumi:Stack  ret-aws-serverless-dev           1 error; 1 message


Diagnostics:
  pulumi:pulumi:Stack (ret-aws-serverless-dev):
    error: It looks like the Pulumi SDK has not been installed. Have you run npm install or yarn install?

    error: error reading from server: EOF
```

Pulumi.yaml

```yaml
name: ret-aws-serverless
runtime: nodejs
description: Provision AWS Serverless infrastructure for the Retail project
```

Seems like it's trying to find a `package.json` file?

**Comment by semiautomatix** [comment]
> Thanks for getting back to me.
> 
> > What error do you get with this approach, and what is the content of `Pulumi.yaml`?
> 
> ```shell
> ret-aws-serverless/bin (main) $ pulumi up -s dev
> Previewing update (dev)
> 
> View Live: https://app.pulumi.com/semiautomatix/ret-aws-serverless/dev/previews/e5d4d720-27f6-41ad-8106-3dc2d9491df5
> 
>      Type                             Name                                                     Plan       Info
>  +   pulumi:pulumi:Stack              ret-aws-serverless-dev                                   create     1 error
>  +   ├─ aws:iam:Role                  ret-aws-serverless-localhost-dev-hello-handler           create     
>  +   ├─ aws:iam:RolePolicyAttachment  ret-aws-serverless-localhost-dev-hello-handler-b5aeb6b6  create     
>  +   ├─ aws:iam:RolePolicyAttachment  ret-aws-serverless-localhost-dev-hello-handler-019020e7  create     
>  +   ├─ aws:iam:RolePolicyAttachment  ret-aws-serverless-localhost-dev-hello-handler-74d12784  create     
>  +   ├─ aws:iam:RolePolicyAttachment  ret-aws-serverless-localhost-dev-hello-handler-1b4caae3  create     
>  +   ├─ aws:iam:RolePolicyAttachment  ret-aws-serverless-localhost-dev-hello-handler-7cd09230  create     
>  +   ├─ aws:iam:RolePolicyAttachment  ret-aws-serverless-localhost-dev-hello-handler-e1a3786d  create     
>  +   ├─ aws:iam:RolePolicyAttachment  ret-aws-serverless-localhost-dev-hello-handler-a1de8170  create     
>  +   ├─ aws:iam:RolePolicyAttachment  ret-aws-serverless-localhost-dev-hello-handler-6c156834  create     
>  +   └─ aws:iam:RolePolicyAttachment  ret-aws-serverless-localhost-dev-hello-handler-4aaabb8e  create     
> 
> 
> Diagnostics:
>   pulumi:pulumi:Stack (ret-aws-serverless-dev):
>     error: <ref *1> ResourceError: Error reading file '/workspace/ret-aws-serverless/bin/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open '/workspace/ret-aws-serverless/bin/package.json'
>         at readFile (/workspace/ret-aws-serverless/node_modules/.pnpm/@pulumi+pulumi@3.56.0/node_modules/@pulumi/runtime/closure/codePaths.ts:250:19)
>         at computeDependenciesDirectlyFromPackageFile (/workspace/ret-aws-serverless/node_modules/.pnpm/@pulumi+pulumi@3.56.0/node_modules/@pulumi/runtime/closure/codePaths.ts:229:22)
>         at /workspace/ret-aws-serverless/node_modules/.pnpm/@pulumi+pulumi@3.56.0/node_modules/@pulumi/runtime/closure/codePaths.ts:187:36
>         at /workspace/ret-aws-serverless/node_modules/.pnpm/read-package-tree@5.3.1/node_modules/read-package-tree/rpt.js:162:20 {
>       resource: undefined,
>       hideStack: undefined,
>       __pulumResourceError: true,
>       promise: Promise { <rejected> [Circular *1] }
>     }
> ```
> 
> Pulumi.yaml
> 
> ```yaml
> name: ret-aws-serverless
> runtime: nodejs
> description: Provision AWS Serverless infrastructure for the Retail project
> ```
> 
> Seems like it's trying to find a `package.json` file?

Ah, updating `Pulumi.yaml` seems to work:

```
name: ret-aws-serverless
runtime: nodejs
description: Provision AWS Serverless infrastructure for the Retail project
main: ../
```

**Comment by semiautomatix** [comment]
Ah, updating `Pulumi.yaml` seems to work:

```
name: ret-aws-serverless
runtime: nodejs
description: Provision AWS Serverless infrastructure for the Retail project
main: ../
```

**Comment by AaronFriel** [comment]
@RobbieMcKinstry I think this is related to #11876, it looks like there's been a regression here as this did work at one point (per comment here https://github.com/pulumi/pulumi/pull/11045#pullrequestreview-1146732123).

**Comment by semiautomatix** [comment]
> @RobbieMcKinstry I think this is related to #11876, it looks like there's been a regression here as this did work at one point (per comment here [#11045 (review)](https://github.com/pulumi/pulumi/pull/11045#pullrequestreview-1146732123)).

Appreciate the action on this.

I've managed to resolve my issue by using a `pnpm` monorepo, so it's not a blocker.
