### ISSUE TITLE
AWS_DEFAULT_REGION when you're working with both aws and another CSP (which is storing the state's files in a bucket)

### ISSUE THREAD

**Issue by idrissneumann** [pulumi/pulumi#12369]
### What happened?

Hi.

Using `AWS_DEFAULT_REGION` set with the region of another CSP than AWS is working pretty well (in our case, it's Scaleway on the region `fr-par`).

But if we need to also provision some instances or buckets on aws, Pulumi is failing with this kind of error:

```shell
[06/03/2023, 14:58:38] - 8b77be6a-dcdd-4b12-8294-f5903dc646ed - x.x.x.x - duration=0.08 "GET /v1/provider/aws/instance/eu-west-3/a/config params={} " 200 -
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/src/utils/instance.py", line 78, in create_instance
    ProviderStrategy().create_instance(instance_id, ami_image, hashed_instance_name, environment, instance_region, instance_zone, instance_type, generate_dns, root_dns_zone)
error: Resource monitor has terminated, shutting down  File "/app/src/strategies/AwsStrategy.py", line 61, in create_instance
    up_res = stack.up()

  File "/usr/local/lib/python3.9/site-packages/pulumi/automation/_stack.py", line 284, in up
    up_result = self._run_pulumi_cmd_sync(args, on_output)
  File "/usr/local/lib/python3.9/site-packages/pulumi/automation/_stack.py", line 663, in _run_pulumi_cmd_sync
    result = _run_pulumi_cmd(args, self.workspace.work_dir, envs, on_output)
  File "/usr/local/lib/python3.9/site-packages/pulumi/automation/_cmd.py", line 78, in _run_pulumi_cmd
    raise create_command_error(result)
pulumi.automation.errors.CommandError:
 code: 255
 stdout: Updating (test-aws-g9f6cy):

@ updating....
 +  pulumi:pulumi:Stack vps-test-aws-g9f6cy creating (0s)
@ updating.................
    aws:ec2:Instance test-aws-g9f6cy  error: unable to validate AWS credentials.
@ updating........
 +  pulumi:pulumi:Stack vps-test-aws-g9f6cy created
    aws:ec2:Instance test-aws-g9f6cy **failed** 1 error

Diagnostics:
  aws:ec2:Instance (test-aws-g9f6cy):
    error: unable to validate AWS credentials.
    Details: error validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.fr-par.amazonaws.com/": dial tcp: lookup sts.fr-par.amazonaws.com on 127.0.0.11:53: no such host
    Make sure you have set your AWS region, e.g. `pulumi config set aws:region us-west-2`.

Resources:
    + 1 created

Duration: 16s
```

`sts.fr-par.amazonaws.com` it's using the `fr-par` value that is used for the state bucket in Scaleway.

If we're setting the `AWS_DEFAULT_REGION` with the aws region `eu-west-3` it'll fail with this error:

```shell
error: unable to check if bucket s3://tf-pulumi-state?endpoint=s3.fr-par.scw.cloud is accessible: blob (code=Unknown): MissingRegion: could not find region configuration
```

### Expected Behavior

Here's an example of piece of code with Python:

```python
def create_bucket(self, user_email, bucket_id, hashed_bucket_name, region, bucket_type):
        def create_pulumi_program():
            object_storage = aws.s3.Bucket(resource_name=hashed_bucket_name, acl=bucket_type, hosted_zone_id=region)
        
        aws_strategy_access_key_id = os.getenv('AWS_STRATEGY_ACCESS_KEY_ID')
        aws_strategy_secret_access_key = os.getenv('AWS_STRATEGY_SECRET_ACCESS_KEY')
        aws_strategy_default_region = os.getenv('AWS_STRATEGY_DEFAULT_REGION')
        stack = auto.create_or_select_stack(stack_name=hashed_bucket_name,
                                            project_name=user_email,
                                            program=create_pulumi_program)
        
        stack.set_config("access_key_id", auto.ConfigValue(aws_strategy_access_key_id))
        stack.set_config("secret_access_key", auto.ConfigValue(aws_strategy_secret_access_key))
        stack.set_config("default_region", auto.ConfigValue(aws_strategy_default_region))
        try:
            up_res = stack.up()
            
        except Exception as e:
            log_msg("ERROR", "[AwsStrategy][create_bucket] unexpected exception : e = {}".format(e)) 
```

Let's assume `aws_strategy_default_region` has the `eu-west-3` values. It should not fail with this error:

```shell
"https://sts.fr-par.amazonaws.com/": dial tcp: lookup sts.fr-par.amazonaws.com on 127.0.0.11:53: no such host
```

### Steps to reproduce

Try to work with aws and another cloud provider. Just so you know we're already working with Pulumi mixing different cloud providers (OVH, Scaleway, Cloudflare, etc).

### Output of `pulumi about`

Inside the container:

```shell
root@dc60dc0b381f:/app# pulumi about
CLI
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.30.0
cloudflare  4.13.0
openstack   3.9.0
ovh         0.0.4
python      unknown
scaleway    1.7.0

Host
OS       debian
Version  11.6
Arch     x86_64

This project is written in python: executable='/usr/local/bin/python3' version='3.9.16
'

Backend
Name           dc60dc0b381f
URL            s3://tf-pulumi-state?endpoint=s3.fr-par.scw.cloud
User           root
Organizations

Dependencies:
NAME                         VERSION
ansicolors                   1.1.8
boto3                        1.26.85
Flask-Bcrypt                 1.0.1
Flask-Cors                   3.0.10
Flask-JWT                    0.3.2
flask-redis                  0.4.0
flask-request-id-middleware  1.1.0
flask-restx                  1.1.0
Flask-SQLAlchemy             3.0.2
lbrlabs-pulumi-ovh           0.0.4
lbrlabs-pulumi-scaleway      1.7.0
minio                        7.1.13
openstacksdk                 0.100.0
ovh                          1.0.0
pdfkit                       1.0.0
pip                          23.0.1
psycopg2                     2.9.5
psycopg2-binary              2.9.5
pulumi-aws                   5.30.0
pulumi-cloudflare            4.13.0
pulumi-openstack             3.9.0
pyotp                        2.8.0
python-dotenv                1.0.0
python-gitlab                3.13.0
sendgrid                     6.9.7
setuptools                   67.5.1
stripe                       4.2.0
wheel                        0.38.4
yubico-client                1.13.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by idrissneumann** [comment]
@justinvp The problem is : we want to create buckets on amazon S3 and keep the state stored in a bucket on Scaleway at the same time (yes we're working on a multicloud project). 

We already tried to replace the environment variable with the `aws:region` config but it seems there isn't a way for making a difference between the "aws default region" for the bucket where I want to store the state (which is not necessarily on aws) and the "aws default region" for creating other buckets with pulumi.

Thanks.

**Comment by justinvp** [comment]
Have you tried _keeping_ the envvar for the bucket where you want to store the state, but setting `aws:region` config for the stack that's creating the bucket?

**Comment by idrissneumann** [comment]
> Have you tried _keeping_ the envvar for the bucket where you want to store the state, but setting `aws:region` config for the stack that's creating the bucket?

I'll try again because it's possible that I set a wrong config. I'll let you know the result as soon as possible ([there is another issue we just got](https://github.com/lbrlabs/pulumi-ovh/issues/56)). Thanks.

**Comment by idrissneumann** [comment]
@justinvp It's solved, many thanks. I was setting the wrong config for the region before.
