### ISSUE TITLE
Failed to parse kubectl version JSON output. EKS 

### ISSUE THREAD

**Issue by Vad1mo** [pulumi/pulumi#12517]
### What happened?

I run the preview and apply operations inside a container. On my local machine, I can run in the container `pulumi preview -s 8g-sandbox` and all works. Running the same command inside the same container in CI/CD fails with this message:

**Error message:** `Failed to parse kubectl version JSON output. Received: "}"`

### Expected Behavior

I have the expectation of the executing the same commands in the same container, locally and in CI/CD has the same outcome. 

### Steps to reproduce

**My Dockerfile** where the error happens.
```Dockerfile
#
# Gitlab CI image with node, npm, python, poetry, sops, git and curl, cdk8, pulumi
#
FROM python:3.11-slim as runtime
ARG TARGETARCH
ARG SOPS_VERSION=3.7.3
ENV PATH=${PATH}:/opt/bin:/root/.pulumi/bin
WORKDIR /opt/bin/
RUN apt-get -qy update && apt-get -qy install git curl && rm -rf /var/lib/apt/lists/*
RUN curl -sSL -o sops https://github.com/mozilla/sops/releases/download/v$SOPS_VERSION/sops-v$SOPS_VERSION.linux && chmod +x sops
RUN curl -sSL -o kubectl https://dl.k8s.io/release/v1.26.3/bin/linux/$TARGETARCH/kubectl && chmod +x kubectl && ls -la
RUN curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | HELM_INSTALL_DIR=/opt/bin bash
RUN curl -fsSL https://deb.nodesource.com/setup_19.x | bash -
RUN curl -fsSL https://get.pulumi.com | bash
RUN curl -sL -o yq https://github.com/mikefarah/yq/releases/download/v4.33.1/yq_linux_$TARGETARCH && chmod +x yq
RUN apt-get -qy update && apt-get -qy install git curl nodejs jq && rm -rf /var/lib/apt/lists/*
RUN pip install poetry awscli -q
RUN npm install -g cdk8s-cli

WORKDIR /src/
```

```python
import json
import string

import requests

import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx
import pulumi_eks as eks
from pulumi import Output

from ruamel.yaml import YAML

config = pulumi.Config()
min_cluster_size: int = config.get_int("minClusterSize", 3)  # type: ignore
max_cluster_size: int = config.get_int("maxClusterSize", 9)  # type: ignore
desired_cluster_size: int = config.get_int("desiredClusterSize", 3)  # type: ignore
eks_node_instance_type = config.get("eksNodeInstanceType", "t3a.medium")
vpc_network_cidr: str = config.get("vpcNetworkCidr", "10.10.0.0/16")  # type: ignore
db_instance_count: int = config.get_int("dbInstanceCount", 1)  # type: ignore
protected: bool = config.get_bool("protect", True)  # type: ignore

yaml = YAML()

current = aws.get_caller_identity()
pulumi.export("account_id", current.account_id)
pulumi.export("region", aws.get_region().name)

eks_vpc = awsx.ec2.Vpc(
    f"cr-vpc-{pulumi.get_stack()}",
    enable_dns_hostnames=True,
    cidr_block=vpc_network_cidr,
    number_of_availability_zones=2,  # 2 AZ
    tags={
        "Stack": pulumi.get_stack(),
    },
    opts=pulumi.ResourceOptions(protect=protected),
)
pulumi.export("vpc_id", eks_vpc.vpc_id)

eks_cluster: eks.Cluster = eks.Cluster(
    f"cr-eks-{pulumi.get_stack()}",
    vpc_id=eks_vpc.vpc_id,
    create_oidc_provider=True,
    public_subnet_ids=eks_vpc.public_subnet_ids,
    private_subnet_ids=eks_vpc.private_subnet_ids,
    node_associate_public_ip_address=False,
    version="1.25",
    node_group_options=eks.ClusterNodeGroupOptionsArgs(
        instance_type=eks_node_instance_type,
        desired_capacity=3,
        min_size=min_cluster_size,
        max_size=max_cluster_size,
        bootstrap_extra_args="--use-max-pods false",
        kubelet_extra_args="--max-pods=110",
        node_root_volume_size=50,
    ),
    tags={
        "Stack": pulumi.get_stack(),
    },
    opts=pulumi.ResourceOptions(protect=protected),
)


def write_to_file(value: dict):
    value["contexts"][0]["name"] = f"aws-{pulumi.get_stack()}"
    value["current-context"] = f"aws-{pulumi.get_stack()}"
    with open(r"kubeconfig.yaml", "w") as file:
        yaml.dump(value, file)


eks_cluster.kubeconfig.apply(lambda v: write_to_file(v))
# pulumi.export("kubeconfig", eks_cluster.kubeconfig)
pulumi.export("cluster_name", eks_cluster.eks_cluster.name)

```

### Output of `pulumi about`

```
pulumi about -s 8g-sandbox
CLI          
Version      3.59.1
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.31.0
awsx        1.0.2
docker      3.6.1
eks         1.0.1
kubernetes  3.24.2
python      unknown

Host     
OS       debian
Version  11.6
Arch     x86_64

This project is written in python: executable='/src/infra/aws/.venv/bin/python3' version='3.11.2
'

Current Stack: 8g-sandbox

TYPE                                                 URN
pulumi:providers:aws                                 urn:pulumi:8g-sandbox::cr-eks::pulumi:providers:aws::default
pulumi:pulumi:Stack                                  urn:pulumi:8g-sandbox::cr-eks::pulumi:pulumi:Stack::cr-eks-8g-sandbox
pulumi:providers:awsx                                urn:pulumi:8g-sandbox::cr-eks::pulumi:providers:awsx::default_1_0_2
pulumi:providers:aws                                 urn:pulumi:8g-sandbox::cr-eks::pulumi:providers:aws::default_5_30_1
awsx:ec2:Vpc                                         urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc::cr-vpc-8g-sandbox
pulumi:providers:aws                                 urn:pulumi:8g-sandbox::cr-eks::pulumi:providers:aws::default_5_16_2
aws:iam/role:Role                                    urn:pulumi:8g-sandbox::cr-eks::aws:iam/role:Role::cr-db-enhances-monitoring-role-8g-sandbox
aws:ec2/vpc:Vpc                                      urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc::cr-vpc-8g-sandbox
aws:ec2/subnet:Subnet                                urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::cr-vpc-8g-sandbox-public-1
aws:ec2/subnet:Subnet                                urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::cr-vpc-8g-sandbox-private-2
aws:ec2/subnet:Subnet                                urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::cr-vpc-8g-sandbox-private-1
aws:ec2/subnet:Subnet                                urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::cr-vpc-8g-sandbox-public-2
aws:ec2/internetGateway:InternetGateway              urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/internetGateway:InternetGateway::cr-vpc-8g-sandbox
aws:ec2/routeTable:RouteTable                        urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::cr-vpc-8g-sandbox-public-1
aws:ec2/eip:Eip                                      urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/eip:Eip::cr-vpc-8g-sandbox-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::cr-vpc-8g-sandbox-private-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::cr-vpc-8g-sandbox-private-1
aws:ec2/eip:Eip                                      urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/eip:Eip::cr-vpc-8g-sandbox-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::cr-vpc-8g-sandbox-public-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::cr-vpc-8g-sandbox-public-1
aws:ec2/route:Route                                  urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::cr-vpc-8g-sandbox-public-1
aws:ec2/natGateway:NatGateway                        urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::cr-vpc-8g-sandbox-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::cr-vpc-8g-sandbox-private-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::cr-vpc-8g-sandbox-private-1
aws:ec2/natGateway:NatGateway                        urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::cr-vpc-8g-sandbox-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::cr-vpc-8g-sandbox-public-2
aws:ec2/route:Route                                  urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::cr-vpc-8g-sandbox-public-2
aws:ec2/route:Route                                  urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::cr-vpc-8g-sandbox-private-1
aws:ec2/route:Route                                  urn:pulumi:8g-sandbox::cr-eks::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::cr-vpc-8g-sandbox-private-2
pulumi:providers:pulumi                              urn:pulumi:8g-sandbox::cr-eks::pulumi:providers:pulumi::default
aws:rds/subnetGroup:SubnetGroup                      urn:pulumi:8g-sandbox::cr-eks::aws:rds/subnetGroup:SubnetGroup::cr_rds_private_subnet_group-8g-sandbox
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:8g-sandbox::cr-eks::aws:ec2/securityGroup:SecurityGroup::allow-pg-access-8g-sandbox
aws:ec2/vpcEndpoint:VpcEndpoint                      urn:pulumi:8g-sandbox::cr-eks::aws:ec2/vpcEndpoint:VpcEndpoint::s3-endpoint-8g-sandbox
pulumi:providers:eks                                 urn:pulumi:8g-sandbox::cr-eks::pulumi:providers:eks::default_1_0_1
aws:rds/cluster:Cluster                              urn:pulumi:8g-sandbox::cr-eks::aws:rds/cluster:Cluster::cr-db-8g-sandbox
aws:rds/clusterInstance:ClusterInstance              urn:pulumi:8g-sandbox::cr-eks::aws:rds/clusterInstance:ClusterInstance::cr-db-8g-sandbox-instance-a
eks:index:Cluster                                    urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster::cr-eks-8g-sandbox
eks:index:ServiceRole                                urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$eks:index:ServiceRole::cr-eks-8g-sandbox-instanceRole
eks:index:ServiceRole                                urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$eks:index:ServiceRole::cr-eks-8g-sandbox-eksRole
pulumi:providers:eks                                 urn:pulumi:8g-sandbox::cr-eks::pulumi:providers:eks::default
eks:index:RandomSuffix                               urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$eks:index:RandomSuffix::cr-eks-8g-sandbox-cfnStackName
aws:iam/role:Role                                    urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$eks:index:ServiceRole$aws:iam/role:Role::cr-eks-8g-sandbox-instanceRole-role
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::cr-eks-8g-sandbox-eksClusterSecurityGroup
aws:iam/role:Role                                    urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$eks:index:ServiceRole$aws:iam/role:Role::cr-eks-8g-sandbox-eksRole-role
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::cr-eks-8g-sandbox-eksClusterInternetEgressRule
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::cr-eks-8g-sandbox-instanceRole-3eb088f2
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::cr-eks-8g-sandbox-instanceRole-03516f97
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::cr-eks-8g-sandbox-instanceRole-e1b295bd
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::cr-eks-8g-sandbox-eksRole-4b490823
aws:iam/instanceProfile:InstanceProfile              urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:iam/instanceProfile:InstanceProfile::cr-eks-8g-sandbox-instanceProfile
aws:eks/cluster:Cluster                              urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:eks/cluster:Cluster::cr-eks-8g-sandbox-eksCluster
aws:iam/openIdConnectProvider:OpenIdConnectProvider  urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:iam/openIdConnectProvider:OpenIdConnectProvider::cr-eks-8g-sandbox-oidcProvider
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::cr-eks-8g-sandbox-nodeSecurityGroup
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::cr-eks-8g-sandbox-eksNodeInternetEgressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::cr-eks-8g-sandbox-eksExtApiServerClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::cr-eks-8g-sandbox-eksNodeIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::cr-eks-8g-sandbox-eksNodeClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::cr-eks-8g-sandbox-eksClusterIngressRule
pulumi:providers:kubernetes                          urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$pulumi:providers:kubernetes::cr-eks-8g-sandbox-eks-k8s
eks:index:VpcCni                                     urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$eks:index:VpcCni::cr-eks-8g-sandbox-vpc-cni
kubernetes:core/v1:ConfigMap                         urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$kubernetes:core/v1:ConfigMap::cr-eks-8g-sandbox-nodeAccess
aws:ec2/launchConfiguration:LaunchConfiguration      urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:ec2/launchConfiguration:LaunchConfiguration::cr-eks-8g-sandbox-nodeLaunchConfiguration
aws:cloudformation/stack:Stack                       urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$aws:cloudformation/stack:Stack::cr-eks-8g-sandbox-nodes
pulumi:providers:kubernetes                          urn:pulumi:8g-sandbox::cr-eks::eks:index:Cluster$pulumi:providers:kubernetes::cr-eks-8g-sandbox-provider
aws:iam/role:Role                                    urn:pulumi:8g-sandbox::cr-eks::aws:iam/role:Role::AmazonEKS_CNI_PolicyRole
aws:iam/role:Role                                    urn:pulumi:8g-sandbox::cr-eks::aws:iam/role:Role::cr-eks-alb-role-8g-sandbox
aws:iam/role:Role                                    urn:pulumi:8g-sandbox::cr-eks::aws:iam/role:Role::cr-eks-external-dns-role-8g-sandbox
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:8g-sandbox::cr-eks::aws:iam/rolePolicyAttachment:RolePolicyAttachment::rpa-AmazonEKS-CNI-Policy-8g-sandbox
aws:eks/addon:Addon                                  urn:pulumi:8g-sandbox::cr-eks::aws:eks/addon:Addon::eks-vpc-cni-8g-sandbox
aws:iam/rolePolicy:RolePolicy                        urn:pulumi:8g-sandbox::cr-eks::aws:iam/rolePolicy:RolePolicy::cr-eks-external-dns-role-policy-8g-sandbox
aws:iam/rolePolicy:RolePolicy                        urn:pulumi:8g-sandbox::cr-eks::aws:iam/rolePolicy:RolePolicy::cr-eks-alb-role-policy-8g-sandbox


Found no pending operations associated with 8g-sandbox

Backend        
Name           567036c5ba0c
URL            s3://cr-sandbox-pulumi-state-20230305
User           root
Organizations  

Dependencies:
NAME         VERSION
loguru       0.6.0
pip          23.0.1
pulumi-awsx  1.0.2
pulumi-eks   1.0.1
ruamel.yaml  0.17.21
setuptools   67.4.0
wheel        0.38.4

Pulumi locates its logs in /tmp by default


```

### Additional context

```
pulumi preview -s 8g-sandbox
Previewing update (8g-sandbox):
@ previewing update....
E0327 12:48:46.821084     146 log.go:84] GitHub rate limit exceeded, try again in 9m52.178950948s. You can set GITHUB_TOKEN to make an authenticated request with a higher rate limit.
E0327 12:48:46.821673     146 log.go:84] GitHub rate limit exceeded, try again in 9m52.178355248s. You can set GITHUB_TOKEN to make an authenticated request with a higher rate limit.
E0327 12:48:46.821166     146 log.go:84] GitHub rate limit exceeded, try again in 9m52.178851988s. You can set GITHUB_TOKEN to make an authenticated request with a higher rate limit.
E0327 12:48:46.822156     146 log.go:84] GitHub rate limit exceeded, try again in 9m52.177857687s. You can set GITHUB_TOKEN to make an authenticated request with a higher rate limit.
.[resource plugin kubernetes-3.23.0] installing
.
[resource plugin aws-5.16.2] installing
[resource plugin aws-5.30.1] installing
.
.
.
.
.
.
.
.
@ previewing update....
.
    pulumi:pulumi:Stack cr-eks-8g-sandbox running 
@ previewing update....
.
.
    awsx:ec2:Vpc cr-vpc-8g-sandbox  
@ previewing update....
    aws:iam:Role cr-db-enhances-monitoring-role-8g-sandbox  [diff: ~provider]
    aws:ec2:Vpc cr-vpc-8g-sandbox  
    aws:ec2:InternetGateway cr-vpc-8g-sandbox  
    aws:ec2:Subnet cr-vpc-8g-sandbox-private-2  
    aws:ec2:Subnet cr-vpc-8g-sandbox-private-1  
    aws:ec2:Subnet cr-vpc-8g-sandbox-public-1  
    aws:ec2:Subnet cr-vpc-8g-sandbox-public-2  
    aws:ec2:RouteTable cr-vpc-8g-sandbox-private-1  
    aws:ec2:RouteTable cr-vpc-8g-sandbox-private-2  
    aws:ec2:Eip cr-vpc-8g-sandbox-1  
    aws:ec2:RouteTable cr-vpc-8g-sandbox-public-1  
    aws:ec2:Eip cr-vpc-8g-sandbox-2  
    aws:ec2:RouteTable cr-vpc-8g-sandbox-public-2  
    aws:ec2:RouteTableAssociation cr-vpc-8g-sandbox-private-1  
    aws:ec2:RouteTableAssociation cr-vpc-8g-sandbox-private-2  
    aws:ec2:NatGateway cr-vpc-8g-sandbox-1  
    aws:ec2:RouteTableAssociation cr-vpc-8g-sandbox-public-1  
    aws:ec2:Route cr-vpc-8g-sandbox-public-1  
    aws:ec2:NatGateway cr-vpc-8g-sandbox-2  
    aws:ec2:RouteTableAssociation cr-vpc-8g-sandbox-public-2  
    aws:ec2:Route cr-vpc-8g-sandbox-public-2  
    aws:ec2:Route cr-vpc-8g-sandbox-private-1  
    aws:ec2:Route cr-vpc-8g-sandbox-private-2  
    aws:ec2:SecurityGroup allow-pg-access-8g-sandbox  [diff: ~provider]
    aws:rds:SubnetGroup cr_rds_private_subnet_group-8g-sandbox  [diff: ~provider]
@ previewing update....
    aws:ec2:VpcEndpoint s3-endpoint-8g-sandbox  [diff: ~provider]
@ previewing update....
    aws:rds:Cluster cr-db-8g-sandbox  [diff: ~provider]
    aws:rds:ClusterInstance cr-db-8g-sandbox-instance-a  [diff: ~provider]
    pulumi:pulumi:Stack cr-eks-8g-sandbox running Error: Failed to parse kubectl version JSON output. Received: : Error: Failed to parse kubectl version JSON output. Received: 
    pulumi:pulumi:Stack cr-eks-8g-sandbox running     at Object.assertCompatibleKubectlVersionExists (/snapshot/eks/bin/dependencies.js:46:15)
    pulumi:pulumi:Stack cr-eks-8g-sandbox running     at createCore (/snapshot/eks/bin/cluster.js:211:20)
    pulumi:pulumi:Stack cr-eks-8g-sandbox running     at createCluster (/snapshot/eks/bin/cluster.js:793:18)
    pulumi:pulumi:Stack cr-eks-8g-sandbox running     at new ClusterInternal (/snapshot/eks/bin/cluster.js:872:25)
    pulumi:pulumi:Stack cr-eks-8g-sandbox running     at Object.construct (/snapshot/eks/bin/cmd/provider/cluster.js:21:29)
    pulumi:pulumi:Stack cr-eks-8g-sandbox running     at Provider.construct (/snapshot/eks/bin/cmd/provider/index.js:129:100)
    pulumi:pulumi:Stack cr-eks-8g-sandbox running     at Server.<anonymous> (/snapshot/eks/node_modules/@pulumi/pulumi/provider/server.js:315:52)
    pulumi:pulumi:Stack cr-eks-8g-sandbox running     at Generator.next (<anonymous>)
    pulumi:pulumi:Stack cr-eks-8g-sandbox running     at fulfilled (/snapshot/eks/node_modules/@pulumi/pulumi/provider/server.js:18:58)
    pulumi:pulumi:Stack cr-eks-8g-sandbox running     at processTicksAndRejections (node:internal/process/task_queues:95:5)
    eks:index:Cluster cr-eks-8g-sandbox  
    pulumi:pulumi:Stack cr-eks-8g-sandbox running error: Program failed with an unhandled exception:
@ previewing update....
    pulumi:pulumi:Stack cr-eks-8g-sandbox  1 error; 11 messages
Diagnostics:
  pulumi:pulumi:Stack (cr-eks-8g-sandbox):
    Error: Failed to parse kubectl version JSON output. Received: : Error: Failed to parse kubectl version JSON output. Received:
        at Object.assertCompatibleKubectlVersionExists (/snapshot/eks/bin/dependencies.js:46:15)
        at createCore (/snapshot/eks/bin/cluster.js:211:20)
        at createCluster (/snapshot/eks/bin/cluster.js:793:18)
        at new ClusterInternal (/snapshot/eks/bin/cluster.js:872:25)
        at Object.construct (/snapshot/eks/bin/cmd/provider/cluster.js:21:29)
        at Provider.construct (/snapshot/eks/bin/cmd/provider/index.js:129:100)
        at Server.<anonymous> (/snapshot/eks/node_modules/@pulumi/pulumi/provider/server.js:315:52)
        at Generator.next (<anonymous>)
        at fulfilled (/snapshot/eks/node_modules/@pulumi/pulumi/provider/server.js:18:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/root/.pulumi/bin/pulumi-language-python-exec", line 197, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/builds/8g/sf/k8s/infra/aws/.venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 136, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/builds/8g/sf/k8s/infra/aws/.venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/builds/8g/sf/k8s/infra/aws/.venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 82, in wait_for_rpcs
        raise exn from cause
      File "/builds/8g/sf/k8s/infra/aws/.venv/lib/python3.11/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
                 ^^^^^^^^^
      File "/builds/8g/sf/k8s/infra/aws/.venv/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 921, in do_register
        resp = await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/builds/8g/sf/k8s/infra/aws/.venv/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 918, in do_rpc_call
        handle_grpc_error(exn)
      File "/builds/8g/sf/k8s/infra/aws/.venv/lib/python3.11/site-packages/pulumi/runtime/settings.py", line 273, in handle_grpc_error
        raise grpc_error_to_exception(exn)
    Exception: Failed to parse kubectl version JSON output. Received:
$ ls -la
```

here is the debug 
```
debug: exception when preparing or executing rpc: Traceback (most recent call last):
      File "/builds/8gears/saas-factory/k8s/infra/aws/.venv/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 916, in do_rpc_call
        return monitor.RegisterResource(req)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/builds/8gears/saas-factory/k8s/infra/aws/.venv/lib/python3.11/site-packages/grpc/_channel.py", line 946, in __call__
        return _end_unary_response_blocking(state, call, False, None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/builds/8gears/saas-factory/k8s/infra/aws/.venv/lib/python3.11/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
        raise _InactiveRpcError(state)
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    	status = StatusCode.UNKNOWN
    	details = "Failed to parse kubectl version JSON output. Received: "
    	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:33765 {created_time:"2023-03-27T15:38:29.097999359+00:00", grpc_status:2, grpc_message:"Failed to parse kubectl version JSON output. Received: "}"
    >
    
    During handling of the above exception, another exception occurred:
```

Kubectl
```sh
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
The connection to the server localhost:8080 was refused - did you specify the right host or port?

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Vad1mo** [comment]
I debugged the code and found the error.  It was a corrupt kubectl and a wrong pulled image. 
lesson learned, use git hashes as tags.

**Comment by justinvp** [comment]
@Vad1mo, glad you were able to find the problem!
