### ISSUE TITLE
azure native sql Go example throws error:  panic: existing registration for azure-native: 1.0.0

### ISSUE THREAD

**Issue by kevin-shelaga** [pulumi/pulumi#12535]
### What happened?

azure native sql Go example throws error https://www.pulumi.com/registry/packages/azure-native/api-docs/sql/server/

```
 panic: existing registration for azure-native: 1.0.0
    goroutine 1 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RegisterResourcePackage(...)
        /Users/REDACTED/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.51.1/go/pulumi/rpc.go:913
    github.com/pulumi/pulumi-azure-native/sdk/go/azure.init.0()
        /Users/REDACTED/go/pkg/mod/github.com/pulumi/pulumi-azure-native/sdk@v1.93.0/go/azure/init.go:33 +0x11c

    error: an unhandled error occurred: program exited with non-zero exit code: 2
```

### Expected Behavior

No errors and db server gets created

### Steps to reproduce

https://www.pulumi.com/registry/packages/azure-native/api-docs/sql/server/

### Output of `pulumi about`

```
CLI          
Version      3.59.1
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME              VERSION
azure-native      1.93.0
azure-native      1.88.1
azure-native-sdk  1.88.1
azure-native-sdk  1.88.1
azure-native-sdk  1.88.1
go                unknown

Host     
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in go: executable='/opt/homebrew/Cellar/go/1.20.2/libexec/bin/go' version='go version go1.20.2 darwin/arm64'

Current Stack: REDACTED/stg

Found no resources associated with REDACTED/stg

Found no pending operations associated with REDACTED/stg

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/REDACTED
User           REDACTED
Organizations  REDACTED

Dependencies:
NAME                                                        VERSION
github.com/pulumi/pulumi-azure-native-sdk/containerservice  1.88.1
github.com/pulumi/pulumi-azure-native-sdk/network           1.88.1
github.com/pulumi/pulumi-azure-native-sdk/resources         1.88.1
github.com/pulumi/pulumi/sdk/v3                             3.51.1
golang.org/x/crypto                                         0.7.0

Pulumi locates its logs in /var/folders/nz/r_wlktxj4gz1xvrjwht7h4580000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kevin-shelaga** [comment]
It looks like because im creating an AKS cluster and an azure sql server 2 versions of azure-native are installed on `pulumi up`

```
Downloading plugin: 42.87 MiB / 42.87 MiB [=========================] 100.00% 2s
                                                                                [resource plugin azure-native-1.88.1] installing.    -> when create azure sql server
Downloading plugin: 44.05 MiB / 44.05 MiB [=========================] 100.00% 2s
                                                                                [resource plugin azure-native-1.93.0] installing.  -> when creating aks cluster
```

**Comment by justinvp** [comment]
Since this is related to azure-native, going to transfer the issue there and someone will take a look. My guess is that yes, this is an issue due to having imports for both `github.com/pulumi/pulumi-azure-native/sdk` and `github.com/pulumi/pulumi-azure-native-sdk/resources`.
