### ISSUE TITLE
Pulumi preview: send on closed channel

### ISSUE THREAD

**Issue by Chasic** [pulumi/pulumi#12543]
### What happened?

Executed `pulumi preview`. It works on a different project but I can't say what's different between the two projects from Pulumi perspective...

Got this error:

```
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.55.0
Go Version:       go1.20
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            send on closed channel

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:24 +0x64
main.panicHandler()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x34
panic({0x106abb2c0, 0x106e45578})
        /opt/hostedtoolcache/go/1.20.0/x64/src/runtime/panic.go:884 +0x1f4
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.loadPlugin(0x0?, 0x14000457d10)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:267 +0xb4
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).LanguageRuntime(0x14000662000, {0x0, 0x0}, {0x1400061bd60, 0x36}, {0x14001010680, 0x6}, 0x0)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:391 +0x120
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).EnsurePlugins(0x14000662000, {0x14001e12820?, 0x5, 0x0?}, 0x3)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:448 +0x1a0
github.com/pulumi/pulumi/pkg/v3/engine.ensurePluginsAreLoaded(0x14000fd4140, 0x140013d07e0, 0x1400097a0a8?)
        /home/runner/work/pulumi/pulumi/pkg/engine/plugins.go:208 +0x180
github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource({_, _}, {{{0x107fffa48, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/engine/update.go:390 +0x78
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x107fffa48, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:180 +0x1b0
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x107fffa48, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/engine/update.go:455 +0x29c
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x106e64430, _}, _, {{0x107fffa48, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/engine/update.go:197 +0x480
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).apply(_, {_, _}, {_, _}, {_, _}, {0x1400134c000, {0x1400061bd60, 0x36}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:624 +0x844
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).Preview(_, {_, _}, {_, _}, {0x1400134c000, {0x1400061bd60, 0x36}, {0x0, 0x0, ...}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:497 +0x78
github.com/pulumi/pulumi/pkg/v3/backend.PreviewStack({_, _}, {_, _}, {0x1400134c000, {0x1400061bd60, 0x36}, {0x0, 0x0, 0x0}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/stack.go:90 +0x88
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localStack).Preview(_, {_, _}, {0x1400134c000, {0x1400061bd60, 0x36}, {0x0, 0x0, 0x0}, 0x140015f0048, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/filestate/stack.go:79 +0x64
main.newPreviewCmd.func1(0x0?, {0x107fffa48, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/preview.go:236 +0x121c
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000eb9500?, {0x107fffa48, 0x0, 0x0})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000eb9500, {0x107fffa48, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5ac
github.com/spf13/cobra.(*Command).ExecuteC(0x140007ecc00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x3c


```

### Expected Behavior

No error on preview

### Steps to reproduce

Run `pulumi preview`

### Output of `pulumi about`

```
CLI          
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.33.0
docker  4.1.0
python  unknown

Host     
OS       darwin
Version  13.2
Arch     arm64

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Hello @Chasic and welcome to the Pulumi community! Thanks for filing this bug. 
Could you provide me with a little more information about your program? For example, can you provide any source code we could use to reproduce the issue?
Additionally, does your program use the Automation API at all? From your bug report, it sounds like the answer is "no", but I wanted to double-check.
