### ISSUE TITLE
Firebase hosting and release issue

### ISSUE THREAD

**Issue by OpenAIMP** [pulumi/pulumi#12573]
### What happened?

trying to implement [this](https://www.pulumi.com/registry/packages/gcp/api-docs/firebase/hostingversion/) using pulumi automation-api with python

able to create the hostingsite and hostingchannel and other firebase resources

not able to create the hostingversion and hostingchannel

### Expected Behavior

should be able to create a version and release of the hosting site. 

### Steps to reproduce

trying to implement [this](https://www.pulumi.com/registry/packages/gcp/api-docs/firebase/hostingversion/)

getting below output...but [docs](https://github.com/pulumi/pulumi-gcp/blob/master/sdk/python/pulumi_gcp/firebase/hosting_version.py) says it has HostingVersion class.

    AttributeError: module 'pulumi_gcp.firebase' has no attribute 'HostingVersion'
    error: an unhandled error occurred: python inline source runtime error: module 'pulumi_gcp.firebase' has no attribute 'HostingVersion'
    Traceback (most recent call last):
      File "/home/xaimpl/.local/lib/python3.10/site-packages/pulumi/automation/_server.py", line 81, in Run
        loop.run_until_complete(run_in_stack(self.program))
      File "/home/xaimpl/anaconda3/envs/iacp/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
        return future.result()
      File "/home/xaimpl/.local/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 136, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/xaimpl/.local/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/home/xaimpl/.local/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 136, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/home/xaimpl/.local/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 159, in __init__
        func()
      File "/home/xaimpl/work/iacp/GCP/e2e_auto/24firebase.py", line 367, in pulumi_program
        basic_web_app, basic_web_app_config = fb_webapp()
      File "/home/xaimpl/work/iacp/GCP/e2e_auto/24firebase.py", line 276, in fb_webapp
        default_hosting_version = gcp.firebase.HostingVersion("defaultHostingVersion",
    AttributeError: module 'pulumi_gcp.firebase' has no attribute 'HostingVersion'

### Output of `pulumi about`

(iacp) xaimpl@ma:~/work/iacp/GCP/e2e_auto$ pulumi about
CLI          
Version      3.60.1
Go Version   go1.20.2
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/mlops
User           mlops
Organizations  mlops

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by OpenAIMP** [comment]
resolved by upgrading pulumi-gcp package
