### ISSUE TITLE
protobuf your generated code is out of date

### ISSUE THREAD

**Issue by ShedPlant** [pulumi/pulumi#12580]
### What happened?

On Python 3.9, latest versions of `pulumi`, `pulumi-aws` and `pulumi-docker`, when I try to `pulumi up` I see a crash:

```
    TypeError: Descriptors cannot not be created directly.
    If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
    If you cannot immediately regenerate your protos, some other possible workarounds are:
     1. Downgrade the protobuf package to 3.20.x or lower.
     2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
    More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

### Expected Behavior

`pulumi up` to work, as it did before in an earlier version

### Steps to reproduce

Minimal Python pulumi project:

`pyproject.toml`
```
[tool.poetry]
name = "issue-573"
version = "0.1.0"
description = "Reproduce pulumi-docker issue 573"
authors = ["expend"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
pulumi-docker = "^4.1.1"
pulumi-aws = "^5.34.0"
```

results in installed packages:
```
shed@Ori issue_573 % poetry show  
arpeggio          2.0.0  Packrat parser interpreter
attrs             22.2.0 Classes Without Boilerplate
dill              0.3.6  serialize all of python
grpcio            1.53.0 HTTP/2-based RPC framework
parver            0.4    Parse and manipulate version numbers.
protobuf          4.22.1 
pulumi            3.33.1 Pulumi's Python SDK
pulumi-aws        5.34.0 A Pulumi package for creating and managing Amazon Web Services (AWS) cloud resources.
pulumi-docker     4.1.1  A Pulumi package for interacting with Docker in Pulumi programs
pyyaml            6.0    YAML parser and emitter for Python
semver            3.0.0  Python helper for Semantic Versioning (https://semver.org)
six               1.16.0 Python 2 and 3 compatibility utilities
typing-extensions 4.5.0  Backported and Experimental Type Hints for Python 3.7+
```

`pulumi up` fails:

```
shed@Ori issue_573 % pulumi -s sandbox up
Previewing update (sandbox)

     Type                 Name                             Plan     Info
     pulumi:pulumi:Stack  pulumi-docker-issue-573-sandbox           1 error; 31 messages


Diagnostics:
  pulumi:pulumi:Stack (pulumi-docker-issue-573-sandbox):
    error: an unhandled error occurred: program exited with non-zero exit code: 1

    Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 16, in <module>
        import pulumi
      File "/Users/shed/.venvs/pulumi-docker-investigations/issue_573/lib/python3.9/site-packages/pulumi/__init__.py", line 33, in <module>
        from .config import (
      File "/Users/shed/.venvs/pulumi-docker-investigations/issue_573/lib/python3.9/site-packages/pulumi/config.py", line 22, in <module>
        from . import log
      File "/Users/shed/.venvs/pulumi-docker-investigations/issue_573/lib/python3.9/site-packages/pulumi/log.py", line 22, in <module>
        from .runtime.settings import get_engine
      File "/Users/shed/.venvs/pulumi-docker-investigations/issue_573/lib/python3.9/site-packages/pulumi/runtime/__init__.py", line 29, in <module>
        from .mocks import (
      File "/Users/shed/.venvs/pulumi-docker-investigations/issue_573/lib/python3.9/site-packages/pulumi/runtime/mocks.py", line 24, in <module>
        from . import rpc, rpc_manager
      File "/Users/shed/.venvs/pulumi-docker-investigations/issue_573/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 40, in <module>
        from . import known_types, settings
      File "/Users/shed/.venvs/pulumi-docker-investigations/issue_573/lib/python3.9/site-packages/pulumi/runtime/settings.py", line 23, in <module>
        from ..runtime.proto import engine_pb2_grpc, resource_pb2, resource_pb2_grpc
      File "/Users/shed/.venvs/pulumi-docker-investigations/issue_573/lib/python3.9/site-packages/pulumi/runtime/proto/__init__.py", line 20, in <module>
        from .analyzer_pb2 import *
      File "/Users/shed/.venvs/pulumi-docker-investigations/issue_573/lib/python3.9/site-packages/pulumi/runtime/proto/analyzer_pb2.py", line 15, in <module>
        from . import plugin_pb2 as plugin__pb2
      File "/Users/shed/.venvs/pulumi-docker-investigations/issue_573/lib/python3.9/site-packages/pulumi/runtime/proto/plugin_pb2.py", line 34, in <module>
        _descriptor.FieldDescriptor(
      File "/Users/shed/.venvs/pulumi-docker-investigations/issue_573/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 561, in __new__
        _message.Message._CheckCalledFromGeneratedFile()
    TypeError: Descriptors cannot not be created directly.
    If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
    If you cannot immediately regenerate your protos, some other possible workarounds are:
     1. Downgrade the protobuf package to 3.20.x or lower.
     2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
    More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

### Output of `pulumi about`

```
shed@Ori issue_573 % pulumi about        
CLI          
Version      3.60.1
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.34.0
docker  4.1.1
python  unknown

Host     
OS       darwin
Version  13.3
Arch     x86_64

This project is written in python: executable='/Users/shed/.venvs/pulumi-docker-investigations/issue_573/bin/python3' version='3.9.16
'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ShedPlant
User           ShedPlant

Dependencies:
NAME           VERSION
pip            22.3.1
pulumi-aws     5.34.0
pulumi-docker  4.1.1
setuptools     65.6.3
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ShedPlant** [comment]
As a workaround (or is it a full fix?):
`poetry add "pulumi^3.60"`

although I am not sure why I got an old version before

**Comment by Frassle** [comment]
```
pulumi-docker = "^4.1.1"
pulumi-aws = "^5.34.0"
```
Both of those packages just ask for `pulumi>=3.0.0,<4.0.0`. Not sure why poetry picked 3.33.1, that's pretty old (May last year).

Grabbing the latest pulumi should be a full fix of this for you. But might be that we should update the provider packages to have a higher minimum version of pulumi than just 3.0.0.

**Comment by gglissmann** [comment]
I'm seeing this same error running Python 3.10 Pulumi being incompatible with Protobuf 5.x.
```
pulumi (3.113.0) depends on protobuf (>=4.21,<5.0)
```
Is there any plan to support protobuf 5.x?

**Comment by justinvp** [comment]
> Is there any plan to support protobuf 5.x?

This was addressed with https://github.com/pulumi/pulumi/pull/19588 which shipped with [v3.190.0](https://github.com/pulumi/pulumi/releases/tag/v3.190.0).
