### ISSUE TITLE
Issue with creating AWSX resources (Vpc) with the Java SDK

### ISSUE THREAD

**Issue by rohanprabhu** [pulumi/pulumi#12604]
### What happened?

When creating a Vpc resource (from Crosswalk, under `com.pulumi.awsx.ec2.*`) pulumi reports an error related to the resource URN generation. Somewhere in the chain of validating the resource URN there is a failure within one of the Java library methods. The stacktrace is as follows:

```
java.lang.IllegalArgumentException: expected qualified type to have 1 or 2 parts, split by '\$', got 'awsx:ec2:Vpc, aws:ec2/vpc:Vpc, aws:ec2/internetGateway:InternetGateway'
        at com.pulumi.core.internal.Objects.require(Objects.java:34)
        at com.pulumi.core.internal.Objects.require(Objects.java:48)
        at com.pulumi.core.internal.Urn$QualifiedTypeName.parse(Urn.java:178)
        at com.pulumi.core.internal.Urn.parse(Urn.java:131)
        at com.pulumi.serialization.internal.Deserializer.tryDeserializeResource(Deserializer.java:365)
        at com.pulumi.serialization.internal.Deserializer.deserializeCore(Deserializer.java:103)
        at com.pulumi.serialization.internal.Deserializer.deserialize(Deserializer.java:59)
        at com.pulumi.serialization.internal.Converter.convertValue(Converter.java:81)
        at com.pulumi.core.internal.OutputCompletionSource.setValue(OutputCompletionSource.java:95)
        at com.pulumi.deployment.internal.DeploymentImpl$ReadOrRegisterResourceInternal.lambda$completeResourceAsync$0(DeploymentImpl.java:1193)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### Expected Behavior

The VPC should be created as expected with the correct subnet specs.

### Steps to reproduce

1. Create a new pulumi project using `mkdir awsx-pulumi-issue && cd awsx-pulumi-issue && pulumi new java-gradle`. Answer the questionnaire with any defaults you prefer.
2. In the generated code directory, add the following line in `app/build.gradle` under the `dependencies` section: `   implementation 'com.pulumi:awsx:1.0.2'` 
3. In the generated code, replace the contents of `app/src/main/java/myproject/App.java` with

```
package myproject;

import com.pulumi.Pulumi;
import com.pulumi.awsx.ec2.Vpc;
import com.pulumi.awsx.ec2.VpcArgs;
import com.pulumi.awsx.ec2.enums.NatGatewayStrategy;
import com.pulumi.awsx.ec2.enums.SubnetType;
import com.pulumi.awsx.ec2.inputs.NatGatewayConfigurationArgs;
import com.pulumi.awsx.ec2.inputs.SubnetSpecArgs;

public class App {
    public static void main(String[] args) {
        Pulumi.run(ctx -> {
            Vpc vpc = new Vpc(
                    "example-private-vpc",
                    VpcArgs.builder()
                            .subnetSpecs(
                                    SubnetSpecArgs.builder()
                                            .type(SubnetType.Private)
                                            .cidrMask(22)
                                            .build()
                            )
                            .natGateways(
                                    NatGatewayConfigurationArgs.builder()
                                            .strategy(NatGatewayStrategy.None)
                                            .build()
                            )
                            .build()
            );

            ctx.export("privateVpcId", vpc.vpcId());
        });
    }
}
```

The above might even be a little more elaborate than required to elaborate this issue. Even the following fails with the exact same error:

```
Pulumi.run(ctx -> {
            Vpc vpc = new Vpc(
                    "example-private-vpc"
            );

            ctx.export("privateVpcId", vpc.vpcId());
        });
```

4. In the pulumi code directory, run `pulumi up`

### Output of `pulumi about`

```
CLI          
Version      3.46.1
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME  VERSION
aws   5.16.2
awsx  1.0.2
java  unknown

Host     
OS       arch
Version  "rolling"
Arch     x86_64

This project is written in java: executable='/usr/bin/java' version='openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10)
OpenJDK 64-Bit Server VM (build 17.0.6+10, mixed mode)' java='/usr/bin/java' javac='17.0.6' maven='Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)' gradle='8.0.2'

Current Stack: awsx-pulumi-issue

Found no resources associated with awsx-pulumi-issue

Found no pending operations associated with awsx-pulumi-issue

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/rohanprabhu
User           rohanprabhu
Organizations  rohanprabhu, commandk

No dependencies found

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rohanprabhu** [comment]
Moving this to the `pulumi-java` repo [https://github.com/pulumi/pulumi-java/issues/1045], sorry for filing it here. Closing this issue
