### ISSUE TITLE
error: problem logging in: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown)

### ISSUE THREAD

**Issue by andrevagil** [pulumi/pulumi#12672]
### What happened?

In the context of Azure Pipeline, we have setup a Pipeline using Nuke for building and deployment.

The step to login the pulumi, it throwns an error. I tried already using many different permission for our Service Principal account, but still doesn't work.

PulumiLogin
[00:07:00 Debug] ArmClientId = *****
[00:07:00 Debug] ArmClientSecret = *****
[00:07:00 Debug] PulumiProjectPath = /home/vsts/work/1/dist/infrastructure
[00:07:00 Information] > "/usr/local/bin/pulumi" "login azblob://pulumi-backend"
[00:07:00 Information] @ "/home/vsts/work/1/dist/infrastructure"
[00:07:01 Error] error: problem logging in: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): ===== RESPONSE ERROR (ErrorCode=AuthorizationPermissionMismatch) =====
[00:07:01 Error] Description=This request is not authorized to perform this operation using this permission.
[00:07:01 Error] RequestId:3084af73-701e-00b7-7a65-6ef2dd000000
[00:07:01 Error] Time:2023-04-14T00:07:01.7723526Z, Details: (none)
[00:07:01 Error] 
[00:07:01 Error] Target "PulumiLogin" has thrown an exception
Nuke.Common.Tooling.ProcessException: Process 'pulumi' exited with code 255.
   > /usr/local/bin/pulumi login azblob://pulumi-backend
   @ /home/vsts/work/1/dist/infrastructure
Error output:
   error: problem logging in: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): ===== RESPONSE ERROR (ErrorCode=AuthorizationPermissionMismatch) =====
   Description=This request is not authorized to perform this operation using this permission.
   RequestId:3084af73-701e-00b7-7a65-6ef2dd000000
   Time:2023-04-14T00:07:01.7723526Z, Details: (none)
   

   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process) in /_/source/Nuke.Common/Tooling/ProcessExtensions.cs:line 39
   at Nuke.Common.Tooling.ToolExecutor.Execute(String arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Action`2 customLogger, Func`2 outputFilter) in /_/source/Nuke.Common/Tooling/ToolExecutor.cs:line 30
   at Deployment.Shared.IPulumiDeployment.<get_PulumiLogin>b__27_1() in /home/vsts/work/1/s/build/shared/IPulumiDeployment.cs:line 107
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) in /_/source/Nuke.Common/Utilities/Collections/Enumerable.ForEach.cs:line 17
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Common/Execution/BuildExecutor.cs:line 112

this is the implementation

`    Target PulumiLogin => _ => _
        .DependsOn(EnsureStateBackendIsAvailable)
        .DependsOn(PulumiInstall)
        .Triggers(PulumiLogout)
        .Executes(() =>
        {
            Pulumi($"login azblob://{AzureStateBackend.BlobContainerName}", PulumiProjectPath, PulumiEnvVars);
        });
`

### Expected Behavior

It is expected the success login

### Steps to reproduce

Setup a pulumi and nuke project that do a Pulumi Authentication in the backend

### Output of `pulumi about`

running 'dotnet build -nologo .'
Determining projects to restore...

All projects are up-to-date for restore.

***********.Shared -> C:*\src*.Shared\bin\Debug\net6.0***********.Shared.dll

***********.Infrastructure -> C:*\src*.Infrastructure\bin\Debug\net6.0***********.Infrastructure.dll

Build succeeded.
0 Warning(s)
0 Error(s)

Time Elapsed 00:00:01.06

'dotnet build -nologo .' completed successfully
CLI
Version 3.61.0
Go Version go1.20.2
Go Compiler gc

Plugins
NAME VERSION
azure 4.13.0
azure-native 1.99.1
azuread 4.3.0
dotnet unknown

Host
OS Microsoft Windows 11 Pro
Version 10.0.22621 Build 22621
Arch x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='6.0.402'

Current Stack: ***********

TYPE URN
pulumi:pulumi:Stack urn:pulumi:-dev::.Infrastructure::pulumi:pulumi:Stack::.Infrastructure--dev
pulumi:providers:azure-native urn:pulumi:-dev::.Infrastructure::pulumi:providers:azure-native::default_1_99_1
azure-native:resources:ResourceGroup urn:pulumi:-dev::.Infrastructure::azure-native:resources:ResourceGroup::rg--adpt-dev
azure-native:storage:StorageAccount urn:pulumi:-dev::.Infrastructure::azure-native:storage:StorageAccount::**
azure-native:web:AppServicePlan urn:pulumi:-dev::.Infrastructure::azure-native:web:AppServicePlan::-dev-001
azure-native:storage:BlobContainer urn:pulumi:-dev::.Infrastructure::azure-native:storage:BlobContainer::-packages
azure-native:storage:Blob urn:pulumi:-dev::.Infrastructure::azure-native:storage:Blob::******
azure-native:web:WebApp urn:pulumi:-dev::.Infrastructure::azure-native:web:WebApp::******

Found no pending operations associated with ******-dev

Backend
Name ******
URL azblob://**********
User ********
Organizations

Dependencies:
NAME VERSION
********.Pulumi.Utils 0.1.23
Pulumi.AzureAD 4.3.0
Pulumi.AzureNative 1.99.1

Pulumi locates its logs in C:\Users******\AppData\Local\Temp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by andrevagil** [comment]
I figured out what was the problem.
Storage Blob Data Contributor role assignment was missing.

this can be closed

**Comment by Maria-Espero** [comment]
Hi Can I ask where you located the missing Storage Blob Data Contributor role

**Comment by Team-Vertrieb** [comment]
> Hi Can I ask where you located the missing Storage Blob Data Contributor role

You have to set this role permission in a storage account.

Open the desired storage account
Access Control (IAM)
Add -> Add role assignment
Here you can search for the "Storage Blob Data Contributor" role and assign to the desired member

![image](https://github.com/pulumi/pulumi/assets/135048522/072a91f8-b25e-4795-a5bf-2fa289f62efb)


![image](https://github.com/pulumi/pulumi/assets/135048522/47902a1a-360c-4c13-b6aa-b168441b841f)

**Comment by kraiz** [comment]
Make sure you're account have that role. Owner permission inherited from f.e. subscription didn't work for me.
