### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by orcutt989** [pulumi/pulumi#12750]
### What happened?

================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.55.0
Go Version:       go1.19.5
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            send on closed channel

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/Cellar/go/1.19.5/libexec/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x101dfcd20, 0x10276c110})
	/usr/local/Cellar/go/1.19.5/libexec/src/runtime/panic.go:884 +0x212
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.loadPlugin(0x40?, 0xc007956910)
	/private/tmp/pulumi-20230214-4678-1s03eky/sdk/go/common/resource/plugin/host.go:267 +0xbd
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).LanguageRuntime(0xc00020c0e0, {0x0, 0x0}, {0xc0001b2b40, 0x22}, {0xc0003c7ca0, 0x6}, 0x0)
	/private/tmp/pulumi-20230214-4678-1s03eky/sdk/go/common/resource/plugin/host.go:391 +0x125
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.GetRequiredPlugins({0x1027a0808?, 0xc00020c0e0?}, {0x0?, 0x0?}, {0xc001042420, {0xc0001b2b40, 0x22}, {0x10217e46b, 0x1}}, 0x7)
	/private/tmp/pulumi-20230214-4678-1s03eky/sdk/go/common/resource/plugin/host.go:582 +0xa8
github.com/pulumi/pulumi/pkg/v3/engine.gatherPluginsFromProgram(0xc0008ed0e0, {0xc001042420, {0xc0001b2b40, 0x22}, {0x10217e46b, 0x1}})
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/engine/plugins.go:122 +0xea
github.com/pulumi/pulumi/pkg/v3/engine.installPlugins(0xc0028c6d60?, {0xc0001b2b40?, 0xc0028c6db8?}, {0x10217e46b?, 0xc0001b2b40?}, 0x22?, 0xc0008ed0e0, 0x0)
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/engine/update.go:229 +0xb9
github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource({_, _}, {{{0x103981830, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/engine/update.go:380 +0x7b
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x103981830, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/engine/deployment.go:180 +0x263
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x103981830, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/engine/update.go:455 +0x391
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x10278b630, _}, _, {{0x103981830, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, ...}, ...)
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/engine/update.go:197 +0x650
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc001042420, {0xc0001b2b40, 0x22}, ...}, ...)
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/backend/httpstate/backend.go:1183 +0x8af
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc001042420, {0xc0001b2b40, 0x22}, ...}, ...)
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/backend/httpstate/backend.go:1090 +0x43f
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc001042420, {0xc0001b2b40, 0x22}, {0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/backend/apply.go:251 +0x24d
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Update(_, {_, _}, {_, _}, {0xc001042420, {0xc0001b2b40, 0x22}, {0x0, 0x0, ...}, ...})
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/backend/httpstate/backend.go:973 +0xc5
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc001042420, {0xc0001b2b40, 0x22}, {0x0, 0x0, 0x0}, ...})
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/backend/stack.go:95 +0xba
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Update(_, {_, _}, {0xc001042420, {0xc0001b2b40, 0x22}, {0x0, 0x0, 0x0}, 0xc0000126f0, ...})
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/backend/httpstate/stack.go:157 +0x88
main.newUpCmd.func1({_, _}, {{{0x103981830, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...})
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/cmd/pulumi/up.go:176 +0x1095
main.newUpCmd.func3(0x0?, {0xc00099c660, 0x0, 0x0?})
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/cmd/pulumi/up.go:492 +0xc65
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc001055200?, {0xc00099c660, 0x0, 0x1})
	/private/tmp/pulumi-20230214-4678-1s03eky/sdk/go/common/util/cmdutil/exit.go:112 +0x4c
github.com/spf13/cobra.(*Command).execute(0xc001055200, {0xc00099c640, 0x1, 0x1})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ed0300)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/private/tmp/pulumi-20230214-4678-1s03eky/pkg/cmd/pulumi/main.go:48 +0x45

### Expected Behavior

No error

### Steps to reproduce

Pulumi up

### Output of `pulumi about`

CLI
Version      3.55.0
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.35.0
aws         5.10.0
aws         4.38.1
docker      3.1.0
eks         0.42.7
eks         0.41.2
eks         0.33.0
kubernetes  3.22.1
kubernetes  3.20.2
nodejs      unknown

Host
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.11.0'

Dependencies:
NAME                       VERSION
@pulumi/kubernetes         3.22.1
@pulumi/pulumi             3.47.1
@types/node                16.9.6
@oxheadalpha/tezos-pulumi  1.1.1
@pulumi/aws                5.35.0
@pulumi/awsx               0.40.1
@pulumi/eks                0.42.7
dotenv                     10.0.0
tezos-pulumi               2.0.0
yaml                       1.10.2

Pulumi locates its logs in /var/folders/w7/vxl3tlsj4vb7kxf0jw20_08w0000gn/T/ by default
warning: A new version of Pulumi is available. To upgrade from version '3.55.0' to '3.64.0', run
   $ brew upgrade pulumi
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

### Additional context

I figure I need to update, but I am just lazy. This error was randomly encountered and was not encountered again. I am only filing this issue because the message requested that I do.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by orcutt989** [comment]
I don't think I CTRL+C'd.

**Comment by abhinav** [comment]
That's certainly unexpected. Are you able to reproduce this?

We're aware of an issue on the relevant lines that usually manifests if you press Ctrl-C at the right time during a `pulumi up`, but it can probably also occur without pressing Ctrl-C.

**Comment by orcutt989** [comment]
No problem. I won't be able to reproduce and investigate. Like I said I only opened this issue because the measage asked me too. 😄  Feel free to close of there's not anything more that can be done.

**Comment by abhinav** [comment]
Thanks, @orcutt989.
Based on the stack trace, we think this has the same cause as https://github.com/pulumi/pulumi/issues/12371, even without the Ctrl-C.
I'll mark this as duplicate for now as we think fixing https://github.com/pulumi/pulumi/issues/12371 will also fix this.

Thanks for the issue!
