### ISSUE TITLE
CLI panic if secret is not valid UTF-8

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1280]
I used 256 random bytes as a config secret and got this crash:

```
panic: regexp: Compile("ac7b463d70da7345c5948c3be57380dd|uz\u07b6\xa1\x04\x01\x13M\x89xM\xf1\x8bo\x14X\xc5S\xf0\x19\x05\xe5_U\\]=\x1a\xc5V\x03\xb8\xe2\xa5\xcc\xf4\xd3%7\xca\xfey\xdadO\xce2x\xe4\xb0O\x14\x8a\xa6\xb8\a\x98fa\x05ٽ\x90㏋\xce-\x1eq\x92\xe8P2\\*\x9c\xe0\xf6\xb5س\r\v\x12\xce\xc8B\xc8\xd4`\x82\xee\xa15\x03\xc5\xdfv\xce\xeaǲp\xd0\a\x9eĝd\\{Kjz\x87\x8a\xb9\x8b1\xfe\xf5;\x9e\xff\xae\xbd!8\x9a\\|\x90\xfe\xd4\x01҂\xeb-\xf4\xe29\xf08\x87\xd1&O\xfc\xfb\x01\v5\xbcE\xafWwq`\aё\xab\x04\xf29\xce\xe4\x1a\x93\\\\\xea\x13\xda꙳kn\xad\x9e:\xf3\x86J\xaf\xe8\x9eb0\x95fȗ\x15\xbfؘ4\\?\\*\xb5\xad\xfb\xcd\x1bS7\\+\xba\xaa\xcc\"\xd5\xd9v\\}U\xd0\xff\\?\x9d\x8b\x97\f\xc0\xdeY\xec\x19Y\xbe\x86A\a\xe1\\];Pa\x1də\x8eIS\xb4F\xb8\x05\\.\\]\"\xaf\xb2\xd3\\*"): error parsing regexp: invalid UTF-8: `MxMXU\]=%7yOxfaٽ㏋q2\*س
B`vǲpĝd\{Kjz1;!8\|҂9O
                     5EWwq`ё\\kn:0fȗؘ4\?\*S7\+v\}U\?
                                                    YA];PaəISF\.\]"*`

goroutine 1 [running]:
regexp.MustCompile(0xc4202f7040, 0x12f, 0x12f)
        /usr/local/go/src/regexp/regexp.go:240 +0x171
github.com/pulumi/pulumi/pkg/engine.makeEventEmitter(0xc420032720, 0x1aa3080, 0xc4204e05a0, 0x0, 0x0, 0x130d65a)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/engine/events.go:151 +0x261
github.com/pulumi/pulumi/pkg/engine.Preview(0x1aa3080, 0xc4204e05a0, 0xc420466000, 0x1f82558, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/engine/preview.go:24 +0x149
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).runEngineAction(0xc42029e5a0, 0x19c8798, 0x6, 0x1aa0b00, 0xc42029fc20, 0xc4202217a0, 0xc4202ec410, 0x39, 0x1f82558, 0x0, ...)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:843 +0x4cc
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).updateStack(0xc42029e5a0, 0x19c8798, 0x6, 0x1aacce0, 0xc42014b920, 0xc4202217a0, 0xc4202ec410, 0x39, 0x0, 0x0, ...)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:761 +0x73f
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).PreviewThenPrompt(0xc42029e5a0, 0x19c8798, 0x6, 0x1aacce0, 0xc42014b920, 0xc4202217a0, 0xc4202ec410, 0x39, 0x0, 0x0, ...)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:568 +0x1a4
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).PreviewThenPromptThenExecute(0xc42029e5a0, 0x19c8798, 0x6, 0x1aa0b00, 0xc42029f230, 0xc4202217a0, 0xc4202ec410, 0x39, 0x0, 0x0, ...)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:638 +0x29a
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).Update(0xc42029e5a0, 0x1aa0b00, 0xc42029f230, 0xc4202217a0, 0xc4202ec410, 0x39, 0x0, 0x0, 0xc42029f350, 0x1f82558, ...)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:656 +0x11d
github.com/pulumi/pulumi/pkg/backend.UpdateStack(0x1aacce0, 0xc42014ad80, 0xc4202217a0, 0xc4202ec410, 0x39, 0x0, 0x0, 0xc42029f350, 0x1f82558, 0x0, ...)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/backend/stack.go:49 +0x145
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudStack).Update(0xc42014ad80, 0xc4202217a0, 0xc4202ec410, 0x39, 0x0, 0x0, 0xc42029f350, 0x1f82558, 0x0, 0x0, ...)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/stack.go:122 +0xf4
github.com/pulumi/pulumi/cmd.newUpdateCmd.func1(0xc420288000, 0x1f82558, 0x0, 0x0, 0x0, 0x0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/cmd/update.go:78 +0x3b7
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc420288000, 0x1f82558, 0x0, 0x0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:55 +0x54
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute(0xc420288000, 0x1f82558, 0x0, 0x0, 0xc420288000, 0x1f82558)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4202586c0, 0xc42027a291, 0xc42027a290, 0xc420257530)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4202586c0, 0xc4201e5f78, 0x100609c)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/main.go:14 +0x2b
```

We should not try to filter the secret if it can't be compiled as a regex.

**Comment by ellismg** [comment]
We'll use #2907 (the user reported version of this bug) to track the fix.
