### ISSUE TITLE
No error on Helm invalid credentials when using node 17 and above

### ISSUE THREAD

**Issue by matanbaruch** [pulumi/pulumi#12807]
### What happened?

Hey,
We are working with private Helm Charts repository, and providing the credentials to the Typescript code. 
When we are using Node version 16 we see an error of unauthorized when Helm repository credentials are not valid.
When we are using 17 or above we only see a generic invocation GRPC error

Example
Node 16
```
    error: Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to pull chart: looks like "https://example.com/artifactory/api/helm/eks-helm" is not a valid chart repository or cannot be reached: failed to fetch https://example.com/artifactory/api/helm/eks-helm/index.yaml : 401
        at Object.callback (/Users/matan.baruch/IdeaProjects/pulumi-infra/01_application_infra/EKS/02_services/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/matan.baruch/IdeaProjects/pulumi-infra/01_application_infra/EKS/02_services/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/matan.baruch/IdeaProjects/pulumi-infra/01_application_infra/EKS/02_services/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/matan.baruch/IdeaProjects/pulumi-infra/01_application_infra/EKS/02_services/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/matan.baruch/IdeaProjects/pulumi-infra/01_application_infra/EKS/02_services/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
```
Node >=17
```
    error: Error:
        at Object.callback (/Users/matan.baruch/IdeaProjects/pulumi-infra/01_application_infra/EKS/02_services/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/matan.baruch/IdeaProjects/pulumi-infra/01_application_infra/EKS/02_services/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/matan.baruch/IdeaProjects/pulumi-infra/01_application_infra/EKS/02_services/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/matan.baruch/IdeaProjects/pulumi-infra/01_application_infra/EKS/02_services/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/matan.baruch/IdeaProjects/pulumi-infra/01_application_infra/EKS/02_services/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

### Expected Behavior

Error will be displayed on any node version
`error: Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to pull chart: looks like "https://example.com/artifactory/api/helm/eks-helm" is not a valid chart repository or cannot be reached: failed to fetch https://example.com/artifactory/api/helm/eks-helm/index.yaml : 401`

### Steps to reproduce

1. Use private helm repo with invalid credentials 
2. Use node 17 or above
3. pulumi preview / up

### Output of `pulumi about`

CLI
Version      3.34.1
Go Version   go1.17.11
Go Compiler  gc

Host
OS       darwin
Version  13.0.1
Arch     x86_64

Does not work also on pulumi 3.52.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by matanbaruch** [comment]
Hey,
Any update regarding this?

**Comment by EronWright** [comment]
@matanbaruch I haven't been able to reproduce the issue, using the nodejs 21 and Pulumi 3.116.  Could you verify that the problem is gone? Thanks!

**Comment by matanbaruch** [comment]
I think it's resolved. Thanks

**Comment by matanbaruch** [comment]
Looks like it's still not resolved. @EronWright 
```
CLI          
Version      3.214.1
Go Version   go1.25.5
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.45.0
resource  aws         5.43.0
resource  aws         5.43.0
resource  aws         5.43.0
resource  aws         5.43.0
resource  aws         5.43.0
resource  aws         5.9.2
resource  aws         5.1.0
resource  aws         4.38.1
resource  aws         4.36.0
resource  eks         0.37.1
resource  eks         0.36.0
resource  kubernetes  4.18.0
resource  kubernetes  3.30.2
resource  kubernetes  3.21.4
resource  mysql       3.2.13
language  nodejs      3.214.1
resource  postgresql  3.16.1
resource  random      4.18.5

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/opt/hostedtoolcache/node/20.19.6/x64/bin/node' version='v20.19.6' packagemanager='npm' packagemanagerVersion='10.8.2'

Backend        
Name           runnervmvatxw
URL            s3://bucket/?region=us-west-2
User           runner
Organizations  
Token type     personal

Dependencies:
NAME                                    VERSION
@pulumi-kit/aws-secretmanager      1.0.8
@pulumi-kit/eks-deployment         3.1.4
@pulumi-kit/eks-scaledobject       1.0.5
@pulumi-kit/stackreference         2.2.1
@pulumi/aws                             4.36.0
@pulumi/pulumi                          3.27.0
@types/node                             16.11.57
@typescript-eslint/eslint-plugin        5.36.2
@pulumi-kit/eks-ingress            1.0.5
eslint-plugin-n                         15.2.5
ts-node                                 7.0.1
@pulumi-kit/x-mysql            1.3.6
@pulumi-kit/autotag                1.0.5
@pulumi-kit/eks-externalsecret     1.0.11
@pulumi-kit/utils                  3.2.2
eslint-config-standard-with-typescript  22.0.0
eslint-plugin-import                    2.26.0
@pulumi-kit/x-configmap        1.0.1
@pulumi-kit/eks-service            1.0.5
@pulumi/eks                             0.37.1
eslint-plugin-promise                   6.0.1
eslint                                  8.23.0
typescript                              4.8.2

Pulumi locates its logs in /tmp by default
```

```
Error: 
    at Object.callback (/home/runner/work/service-name/service-name/infra/node_modules/@pulumi/runtime/invoke.ts:161:33)
    at Object.onReceiveStatus (/home/runner/work/service-name/service-name/infra/node_modules/@grpc/grpc-js/src/client.ts:338:26)
    at Object.onReceiveStatus (/home/runner/work/service-name/service-name/infra/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
    at Object.onReceiveStatus (/home/runner/work/service-name/service-name/infra/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /home/runner/work/service-name/service-name/infra/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
```
