### ISSUE TITLE
Crash during `pulumi convert --from terraform`

### ISSUE THREAD

**Issue by asaf400** [pulumi/pulumi#12826]
### What happened?

When invoking `pulumi convert --from terraform --language pcl --out pulumi` on our Terraform environment root

Attaching go stack:
```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.66.0
Go Version:       go1.20.3
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.3/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x226c200, 0x3d9f3a0})
        /opt/hostedtoolcache/go/1.20.3/x64/src/runtime/panic.go:884 +0x213
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*Component).Traverse(0xc000ab5c40?, {0x2bdac10?, 0xc00240ba90?})
        /home/runner/work/pulumi/pulumi/pkg/codegen/pcl/component.go:85 +0x26
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.bindTraversalParts({0x2bbfe20?, 0xc00056ba20}, {0xc0023bb9b0?, 0x1, 0x1}, 0x0)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/traversable.go:85 +0x18b
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.(*ScopeTraversalExpression).typecheck(0xc00132f540, 0x20?, 0xbd?)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/expression.go:1913 +0x112
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.(*expressionBinder).bindScopeTraversalExpression(0xc0017aba70, 0xc000a84d80)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/binder_expression.go:627 +0x3ea
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.(*expressionBinder).bindExpression(0x7f1a1f985108?, {0x2bd1ed8?, 0xc000a84d80?})
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/binder_expression.go:98 +0x1c5
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.BindExpression({0x2bd1ed8, 0xc000a84d80}, 0xc000add7a0, {0x2bd64d8, 0xc000add740}, {0x0, 0x0, 0xc000100800?})
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/binder_expression.go:60 +0xe5
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.BindAttribute(0xc000b44fc0, 0x2?, {0x2bd64d8, 0xc000add740}, {0x0, 0x0, 0x0})
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/attribute.go:82 +0xa5
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.BindBody(0xc00056af20, {0x2bd3300, 0xc000614df8}, {0x2bd64d8?, 0xc000add740}, {0x0, 0x0, 0x0})
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/body.go:136 +0x285
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.BindBlock(0xc000abaa20, {0x2bd3300?, 0xc000614df8?}, {0x2bd64d8?, 0xc000add740?}, {0x0?, 0x1c?, 0xc0017abe40?})
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/block.go:119 +0x5e
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*binder).getPkgOpts(0xc0009eb600, 0xc00056bb80)
        /home/runner/work/pulumi/pulumi/pkg/codegen/pcl/binder_schema.go:203 +0x534
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*binder).loadReferencedPackageSchemas(0xc0009eb600, {0x2bea120?, 0xc00056bb80?})
        /home/runner/work/pulumi/pulumi/pkg/codegen/pcl/binder_schema.go:247 +0x195
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*binder).declareNodes(0x20ff440?, 0xc000ab4a00)
        /home/runner/work/pulumi/pulumi/pkg/codegen/pcl/binder.go:228 +0x2c5
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.BindProgram({0xc000b6a700?, 0x4, 0x4}, {0xc0017ac680, 0x3, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/codegen/pcl/binder.go:172 +0xb56
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.ComponentProgramBinderFromFileSystem.func1({{0xc000057dc0, 0x1d}, {0x2bbfee0, 0xc000ab57c0}, {0xc00054ca60, 0x10}, {{0xc00005e37e, 0x9}, {0x2, 0x1, ...}, ...}})
        /home/runner/work/pulumi/pulumi/pkg/codegen/pcl/binder_component.go:138 +0x5dd
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*binder).bindComponent(0xc0005a0f80, 0xc000ade160)
        /home/runner/work/pulumi/pulumi/pkg/codegen/pcl/binder_component.go:164 +0x2b8
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*binder).bindNode(0x20ff440?, {0x2be9f40, 0xc000ade160})
        /home/runner/work/pulumi/pulumi/pkg/codegen/pcl/binder_nodes.go:65 +0x671
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.BindProgram({0xc000130400?, 0x14, 0x20}, {0xc000e55530, 0x3, 0x31?})
        /home/runner/work/pulumi/pulumi/pkg/codegen/pcl/binder.go:181 +0xd56
main.pclBindProgram({0xc000057dc0, 0x1d}, {0x2bd34b8?, 0xc000ab57c0})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/convert.go:195 +0x4f4
main.runConvert.func1.1({0x2be55e0, 0xc000a895c0}, {0xc000057dc0, 0x1d}, {0x7ffd18e1aa63, 0x6}, {0x2bd34b8?, 0xc000ab57c0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/convert.go:217 +0x9e
main.runConvert({0x2bdb060, 0xc0003a9c90}, {0xc000056064, 0x16}, {0x3e05e08, 0x0, 0x0}, {0x7ffd18e1aa41, 0x9}, {0x7ffd18e1aa56, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/convert.go:344 +0x1388
main.newConvertCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/convert.go:74 +0x1f4
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000aa6600?, {0xc0009eb580, 0x0, 0x8})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4c
github.com/spf13/cobra.(*Command).execute(0xc000aa6600, {0xc0009eb500, 0x8, 0x8})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000768900)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
        ```

### Expected Behavior

.

### Steps to reproduce

.

### Output of `pulumi about`

 .

**Comment by Frassle** [comment]
Issue in the binder so moving to pu/pu.
