### ISSUE TITLE
ModuleNotFoundError Python error on Mac with homebrew

### ISSUE THREAD

**Issue by dtrailin** [pulumi/pulumi#12928]
### What happened?

I am trying to run a script which uses the pulumi python package. However when I run this script I get the following error
```
Traceback (most recent call last):
  File "[our-script]", line 548, in <module>
    main()
  File "/opt/homebrew/lib/python3.11/site-packages/loguru/_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[our-script]", line 333, in main
    result = pulumi_cloud_instance.stack.up(on_output=logger.debug)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pulumi/automation/_stack.py", line 309, in up
    up_result = self._run_pulumi_cmd_sync(args, on_output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pulumi/automation/_stack.py", line 784, in _run_pulumi_cmd_sync
    result = _run_pulumi_cmd(args, self.workspace.work_dir, envs, on_output)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pulumi/automation/_cmd.py", line 78, in _run_pulumi_cmd
    raise create_command_error(result)
pulumi.automation.errors.RuntimeError: 
 code: 255
 stdout: Updating ([org-name]/[deployment-name])

View Live: https://app.pulumi.com/[org-name]/aws/[deployment-name]/updates/39


    pulumi:pulumi:Stack aws-[deployment-name]  Traceback (most recent call last):
    pulumi:pulumi:Stack aws-[deployment-name]    File "/opt/homebrew/bin/pulumi-language-python-exec", line 16, in <module>
    pulumi:pulumi:Stack aws-[deployment-name]      import pulumi
    pulumi:pulumi:Stack aws-[deployment-name]  ModuleNotFoundError: No module named 'pulumi'
    pulumi:pulumi:Stack aws-[deployment-name]  It looks like the Pulumi SDK has not been installed. Have you run pip install?
    pulumi:pulumi:Stack aws-[deployment-name]  If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
    pulumi:pulumi:Stack aws-[deployment-name]  error: an unhandled error occurred: program exited with non-zero exit code: 1
    pulumi:pulumi:Stack aws-[deployment-name] **failed** 1 error; 6 messages

Diagnostics:
  pulumi:pulumi:Stack (aws-[deployment-name]):
    error: an unhandled error occurred: program exited with non-zero exit code: 1

    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 16, in <module>
        import pulumi
    ModuleNotFoundError: No module named 'pulumi'
    It looks like the Pulumi SDK has not been installed. Have you run pip install?
```
This is my python version:
```
which python3
/opt/homebrew/bin/python3
python3
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
Pulumi is installed in my python version. 

### Expected Behavior

I expect the script to work without errors. 

### Steps to reproduce

1. Install the following with brew:
 ``` 
 brew install pulumi
 brew install python3
```
2. Run `pip3 install pulumi`.
3. Run a script that tries to bring up a pulumi stack. 
 ```
 from pulumi import automation as pa

if __name__ == "__main__":
    stack = pa.create_or_select_stack(stack_name="test-out-pulumi",
                                               project_name='aws',
                                               work_dir=os.path.join('..', 'pulumi', 'aws'))
    stack.up()
```
 

### Output of `pulumi about`

```
% pulumi about
CLI          
Version      3.67.0
Go Version   go1.20.4
Go Compiler  gc

Host     
OS       darwin
Version  13.3.1
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/dtrailin
User           dtrailin
Organizations  dtrailin

Pulumi locates its logs in /var/folders/z1/g6rj61qj687_17jxg39kmm0h0000gq/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@dtrailin, so your actual Pulumi project lives in `../pulumi/aws`? What does the `Pulumi.yaml` file look like in that directory? Does it have a `virtualenv` specified in the runtime options? Is `pulumi` installed in that `virtualenv`?

**Comment by dtrailin** [comment]
The issue seems to be that the `venv` was created in the same directory as my `Pulumi.yaml` file which was different than where I was running my script from.

**Comment by Alex-ley-scrub** [comment]
@dtrailin I have a similar issue:
- I installed pulumi using HomeBrew as instructed on the website: `brew install pulumi/tap/pulumi`
- I have a conda environment I use for my development/repo - it's called `py312`
- I installed pulumi into the conda env and it is activated and you can see it is installed from the log below
- but when I run `pulumi up` it's almost like it is trying to use my system / HomeBrew python and not the active conda env, why?
- `deployment/src/scrub_infra/applications/backend/Pulumi.yaml` has `runtime: python` and is in my cwd

```
(py312) alex@Alexs-MacBook-Pro-297 backend % pulumi up                             
Previewing update (scrub-ai/dev)

View in Browser (Ctrl+O): https://app.pulumi.com/scrub-ai/backend/dev/previews/d40cadca-d281-4927-b57f-812197c98eb6

     Type                 Name         Plan     Info
     pulumi:pulumi:Stack  backend-dev           1 error; 6 messages

Diagnostics:
  pulumi:pulumi:Stack (backend-dev):
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 17, in <module>
        import pulumi
    ModuleNotFoundError: No module named 'pulumi'
    It looks like the Pulumi SDK has not been installed. Have you run pip install?
    If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.

    error: an unhandled error occurred: program exited with non-zero exit code: 1

    [Pulumi Copilot] Would you like help with these diagnostics?
    https://app.pulumi.com/scrub-ai/backend/dev/previews/d40cadca-d281-4927-b57f-812197c98eb6?explainFailure

Resources:

(py312) alex@Alexs-MacBook-Pro-297 backend % pwd
{some_path}/deployment/src/scrub_infra/applications/backend
(py312) alex@Alexs-MacBook-Pro-297 backend % ls
__init__.py     __main__.py     Pulumi.dev.yaml Pulumi.yaml     scaling.py
(py312) alex@Alexs-MacBook-Pro-297 backend % which python
/Users/alex/miniconda/envs/py312/bin/python
(py312) alex@Alexs-MacBook-Pro-297 backend % python -c "import pulumi; print(pulumi._version.version);"
3.163.0
(py312) alex@Alexs-MacBook-Pro-297 backend % 
```

Am I doing something dumb? Or should I  open another issue?
