### ISSUE TITLE
Automation API fails when program contains AWS provider

### ISSUE THREAD

**Issue by nebbles** [pulumi/pulumi#12942]
### What happened?

When running the Automation API with a program that contains a managed `aws.Provider`, the run fails.

This has been confirmed as working on version `3.42.0`, on version `3.43.0` it then began failing. I've tested on the latest package version `3.67.0` and it's still failing.

### Expected Behavior

I would expect to be able to configure the aws provider even when using an inline program for the Automation API.AWS

### Steps to reproduce

This simple code snippet is my reproduction:
```ts
import { LocalWorkspace } from "@pulumi/pulumi/automation";
import * as aws from "@pulumi/aws";
import { Region } from "@pulumi/aws";

const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;

async function stackUp(opt: { stackName: string }) {
    console.log("getting stack", opt.stackName);
    const stack = await LocalWorkspace.createOrSelectStack({
        projectName: "test-project",
        stackName: opt.stackName,
        program: async () => {
            const awsProvider = new aws.Provider("aws-provider", {
                accessKey: AWS_ACCESS_KEY_ID,
                secretKey: AWS_SECRET_ACCESS_KEY,
                region: Region.EUWest2,
            });
        },
    });
    console.log("stack up");
    await stack.up({ onOutput: console.log });
}

async function main() {
    await stackUp({ stackName: "stack-1" });
}
main();

```

<details>
<summary>Output when running pulumi sdk v3.42.0</summary>

```
getting stack stack-1
stack up
Updating (stack-1)


View Live: https://app.pulumi.com/mytos/test-project/stack-1/updates/5




    pulumi:pulumi:Stack test-project-stack-1 running 

 ~  pulumi:providers:aws aws-provider updating (0s) [diff: -skipGetEc2Platforms~version]

 ~  pulumi:providers:aws aws-provider updated (0.22s) [diff: -skipGetEc2Platforms~version]

    pulumi:pulumi:Stack test-project-stack-1  

Resources:
    ~ 1 updated
    1 unchanged

Duration: 1s
```

</details>

<details>
<summary>Output when running pulumi sdk v3.43.0</summary>

```
getting stack stack-1
stack up
Updating (stack-1)


View Live: https://app.pulumi.com/mytos/test-project/stack-1/updates/6




    pulumi:pulumi:Stack test-project-stack-1 running 

    pulumi:pulumi:Stack test-project-stack-1 running error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

    pulumi:pulumi:Stack test-project-stack-1 running error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

    pulumi:pulumi:Stack test-project-stack-1 **failed** 2 errors

Diagnostics:
  pulumi:pulumi:Stack (test-project-stack-1):
    error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
        at requireTestModeEnabled (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/settings.js:123:15)
        at Object.getMonitor (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/settings.js:214:13)
        at Object.registerResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/resource.js:213:32)
        at new Resource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new ProviderResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:336:9)
        at new Provider (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/provider.ts:128:9)
        at Object.program [as init] (/Users/REDACTED_PATH/infrastructure/scripts/bug-repro.ts:42:33)
        at Stack.<anonymous> (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/runtime/stack.ts:77:39)
        at Generator.next (<anonymous>)
    error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

Resources:
    1 unchanged

Duration: 1s


CommandError: code: -2
 stdout: 
 stderr: Command failed with exit code 255: pulumi up --yes --skip-preview --client=127.0.0.1:56086 --exec-kind auto.inline --stack stack-1 --non-interactive
Updating (stack-1)

View Live: https://app.pulumi.com/mytos/test-project/stack-1/updates/6


    pulumi:pulumi:Stack test-project-stack-1 running 
    pulumi:pulumi:Stack test-project-stack-1 running error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    pulumi:pulumi:Stack test-project-stack-1 running error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    pulumi:pulumi:Stack test-project-stack-1 **failed** 2 errors

Diagnostics:
  pulumi:pulumi:Stack (test-project-stack-1):
    error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
        at requireTestModeEnabled (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/settings.js:123:15)
        at Object.getMonitor (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/settings.js:214:13)
        at Object.registerResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/resource.js:213:32)
        at new Resource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new ProviderResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:336:9)
        at new Provider (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/provider.ts:128:9)
        at Object.program [as init] (/Users/REDACTED_PATH/infrastructure/scripts/bug-repro.ts:42:33)
        at Stack.<anonymous> (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/runtime/stack.ts:77:39)
        at Generator.next (<anonymous>)
    error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

Resources:
    1 unchanged

Duration: 1s

 err?: Error: Command failed with exit code 255: pulumi up --yes --skip-preview --client=127.0.0.1:56086 --exec-kind auto.inline --stack stack-1 --non-interactive
Updating (stack-1)

View Live: https://app.pulumi.com/mytos/test-project/stack-1/updates/6


    pulumi:pulumi:Stack test-project-stack-1 running 
    pulumi:pulumi:Stack test-project-stack-1 running error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    pulumi:pulumi:Stack test-project-stack-1 running error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    pulumi:pulumi:Stack test-project-stack-1 **failed** 2 errors

Diagnostics:
  pulumi:pulumi:Stack (test-project-stack-1):
    error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
        at requireTestModeEnabled (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/settings.js:123:15)
        at Object.getMonitor (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/settings.js:214:13)
        at Object.registerResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/resource.js:213:32)
        at new Resource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new ProviderResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:336:9)
        at new Provider (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/provider.ts:128:9)
        at Object.program [as init] (/Users/REDACTED_PATH/infrastructure/scripts/bug-repro.ts:42:33)
        at Stack.<anonymous> (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/runtime/stack.ts:77:39)
        at Generator.next (<anonymous>)
    error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

Resources:
    1 unchanged

Duration: 1s


    at Object.createCommandError (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/automation/errors.ts:73:21)
    at Object.<anonymous> (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/automation/cmd.ts:84:15)
    at Generator.throw (<anonymous>)
    at rejected (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/pulumi/automation/cmd.js:19:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

</details>

<details>
<summary>Output from running pulumi sdk v3.67.0</summary>

```
getting stack stack-1
stack up
Updating (stack-1)


View Live: https://app.pulumi.com/mytos/test-project/stack-1/updates/7




    pulumi:pulumi:Stack test-project-stack-1 running 

    pulumi:pulumi:Stack test-project-stack-1 running error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

    pulumi:pulumi:Stack test-project-stack-1 running error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

    pulumi:pulumi:Stack test-project-stack-1 **failed** 2 errors

Diagnostics:
  pulumi:pulumi:Stack (test-project-stack-1):
    error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
        at requireTestModeEnabled (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/settings.js:123:15)
        at Object.getMonitor (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/settings.js:214:13)
        at Object.registerResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/resource.js:213:32)
        at new Resource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new ProviderResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:336:9)
        at new Provider (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/provider.ts:128:9)
        at Object.program [as init] (/Users/REDACTED_PATH/infrastructure/scripts/bug-repro.ts:42:33)
        at Stack.<anonymous> (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/runtime/stack.ts:76:39)
        at Generator.next (<anonymous>)
    error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

Resources:
    1 unchanged

Duration: 1s


CommandError: code: -2
 stdout: 
 stderr: Command failed with exit code 255: pulumi up --yes --skip-preview --client=127.0.0.1:56214 --exec-kind auto.inline --stack stack-1 --non-interactive
Updating (stack-1)

View Live: https://app.pulumi.com/mytos/test-project/stack-1/updates/7


    pulumi:pulumi:Stack test-project-stack-1 running 
    pulumi:pulumi:Stack test-project-stack-1 running error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    pulumi:pulumi:Stack test-project-stack-1 running error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    pulumi:pulumi:Stack test-project-stack-1 **failed** 2 errors

Diagnostics:
  pulumi:pulumi:Stack (test-project-stack-1):
    error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
        at requireTestModeEnabled (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/settings.js:123:15)
        at Object.getMonitor (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/settings.js:214:13)
        at Object.registerResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/resource.js:213:32)
        at new Resource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new ProviderResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:336:9)
        at new Provider (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/provider.ts:128:9)
        at Object.program [as init] (/Users/REDACTED_PATH/infrastructure/scripts/bug-repro.ts:42:33)
        at Stack.<anonymous> (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/runtime/stack.ts:76:39)
        at Generator.next (<anonymous>)
    error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

Resources:
    1 unchanged

Duration: 1s

 err?: Error: Command failed with exit code 255: pulumi up --yes --skip-preview --client=127.0.0.1:56214 --exec-kind auto.inline --stack stack-1 --non-interactive
Updating (stack-1)

View Live: https://app.pulumi.com/mytos/test-project/stack-1/updates/7


    pulumi:pulumi:Stack test-project-stack-1 running 
    pulumi:pulumi:Stack test-project-stack-1 running error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    pulumi:pulumi:Stack test-project-stack-1 running error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    pulumi:pulumi:Stack test-project-stack-1 **failed** 2 errors

Diagnostics:
  pulumi:pulumi:Stack (test-project-stack-1):
    error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
        at requireTestModeEnabled (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/settings.js:123:15)
        at Object.getMonitor (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/settings.js:214:13)
        at Object.registerResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/runtime/resource.js:213:32)
        at new Resource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new ProviderResource (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/aws/node_modules/@pulumi/pulumi/resource.js:336:9)
        at new Provider (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/provider.ts:128:9)
        at Object.program [as init] (/Users/REDACTED_PATH/infrastructure/scripts/bug-repro.ts:42:33)
        at Stack.<anonymous> (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/runtime/stack.ts:76:39)
        at Generator.next (<anonymous>)
    error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

Resources:
    1 unchanged

Duration: 1s


    at Object.createCommandError (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/automation/errors.ts:78:11)
    at Object.<anonymous> (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/automation/cmd.ts:79:15)
    at Generator.throw (<anonymous>)
    at rejected (/Users/REDACTED_PATH/infrastructure/node_modules/@pulumi/pulumi/automation/cmd.js:19:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

</details>

### Output of `pulumi about`

```
CLI          
Version      3.67.0
Go Version   go1.20.4
Go Compiler  gc

Host     
OS       darwin
Version  10.15.7
Arch     x86_64
```

### Additional context

This relates to #10325 since its the exact same reproduction. Instead of the second stack update hanging however (in that issue) now even one single stack update fails with the presence of the `aws.Provider`.

I'm hoping if this issue can be resolved, then it will also resolve #10325 since #5449 apparently has fixed parallel updates which is pretty handy (but it also corresponds with which version this bug reproduction starts failing!).

This bug is a blocker from us being able to update beyond v3.42.0 because now our Automation API script doesn't work.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by nebbles** [comment]
FYI @AaronFriel (from #10325 where this issue now supersedes that one, and because https://github.com/pulumi/pulumi/pull/10568 may have introduced this)

**Comment by abhinav** [comment]
Thanks for the report, @nebbles. I was unable to reproduce this despite numerous attempts.
Just for confirmation, what version of `@pulumi/pulumi` do you have in your package.json?
I have a suspicion that the version of your Node SDK is too old.
The error message does not appear to be part of the Pulumi codebase right now—it was removed in August 2022 in #10400.
Would you mind checking which version is being used, and try to upgrade, if possible?
