### ISSUE TITLE
Error: 14 UNAVAILABLE: No connection established while deploying a stack

### ISSUE THREAD

**Issue by WiinyB** [pulumi/pulumi#12970]
### What happened?

Hi,

I was trying to deploy a k8s deployment which had a volume who's link to a k8s secret. The volume configuration that I provided was empty which caused the stack.up() to fail (expected). But, the error Error: 14 UNAVAILABLE: No connection established occur on top of the one returned by the stack.up() function and I'm unable to catch this error. 

The second error seems to be thrown within a async call which make it uncatchable.

### Expected Behavior

Only one error should be thrown, the one that details the stack deployment.
Or at least, the second error should be catchable.

### Steps to reproduce

Run the following stack deployment.

```
const auto = require("@pulumi/pulumi/automation");
const k8s = require("@pulumi/kubernetes");

const args = process.argv.slice(2);
let destroy = false;
if (args.length > 0 && args[0]) {
    destroy = args[0] === "destroy";
}

const run = async () => {
    // This is our pulumi program in "inline function" form
    const pulumiProgram = async () => {
        // Creating k8s deployment
        const deployment =  new k8s.apps.v1.Deployment(
            'helloworld-deployment',
            {
                spec: {
                    replicas: 1,
                    selector: {
                        matchLabels: {
                            app: "helloworld",
                        },
                    },
                    template: {
                        spec: {
                            restartPolicy: "Always",
                            containers: [
                                {
                                    name: 'mycontainer',
                                    image: "nginx"
                                },
                            ],
                            volumes: [
                            {
                                name: "myvolume",
                                secret: {
                                    secretName: "",
                                },
                            },
                            ],
                        },
                    },
                },
            }
        );

        return {
            deploymentId: deployment.id
        }
    };

    // Create our stack 
    const args = {
        stackName: "dev",
        projectName: "inlineNode",
        program: pulumiProgram
    };

    // create (or select if one already exists) a stack that uses our inline program
    const stack = await auto.LocalWorkspace.createOrSelectStack(args);

    console.info("successfully initialized stack");
    console.info("config set");
    console.info("refreshing stack...");
    await stack.refresh({ onOutput: console.info });
    console.info("refresh complete");

    if (destroy) {
        console.info("destroying stack...");
        await stack.destroy({ onOutput: console.info });
        console.info("stack destroy complete");
        process.exit(0);
    }

    console.info("updating stack...");
    const upRes = await stack.up({ onOutput: console.info });
    console.info(`update summary: \n${JSON.stringify(upRes.summary.resourceChanges, null, 4)}`);
};

run().catch(err => console.log(err));
```

The catch block will be able to catch the deployment failure error but shouldn't be able to catch this error.
```
<ref *1> Error: 14 UNAVAILABLE: No connection established
    at callErrorFromStatus (/home/root/repo/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/home/root/repo/node_modules/@grpc/grpc-js/src/client.ts:356:55)
    at Object.onReceiveStatus (/home/root/repo/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
    at Object.onReceiveStatus (/home/root/repo/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
    at /home/root/repo/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/home/root/repo/node_modules/@grpc/grpc-js/src/client.ts:326:30)
    at ServiceClientImpl.registerResourceOutputs (/home/root/repo/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at /home/root/repo/node_modules/@pulumi/runtime/resource.ts:847:34
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/root/repo/node_modules/@pulumi/runtime/resource.ts:846:37)
    at Generator.next (<anonymous>)
    at fulfilled (/home/root/repo/node_modules/@pulumi/pulumi/runtime/resource.js:18:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  promise: Promise {
    <rejected> [Circular *1],
    [Symbol(async_id_symbol)]: 2202,
    [Symbol(trigger_async_id_symbol)]: 526,
    [Symbol(kResourceStore)]: LocalStore {
      settings: [Object],
      config: [Object],
      stackResource: [Stack],
      leakCandidates: Set(0) {}
    }
  }
}
```

### Output of `pulumi about`

CLI          
Version      3.57.1
Go Version   go1.20.1
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Backend        
Name           mydesktop
URL            file://~
User           root
Organizations  

### Additional context

This is a major issue, the error make our api crash completly.

Thanks in advance!

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hi, we are looking to improve the error handling experience around automation API and appreciate this feedback.
