### ISSUE TITLE
panic in `pulumi convert` for a go program

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#13199]
Looks like there was a panic on the other side of an RPC boundary trying to convert the following YAML into go: https://github.com/pulumi/pulumi-auto-deploy/blob/main/examples/yaml/Pulumi.yaml

Conversion of the same program succeeded for node, python, and csharp.

```
$ pulumi convert --generate-only --out ../go --language go    
Converting from yaml...
Converting to go...
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105584734]

goroutine 37 [running]:

github.com/pulumi/pulumi/pkg/v3/codegen/go.GenerateProject({0x140000b0148, 0x5}, {{0x140002d9400, 0x10}, {{0x1055a31f4, 0x2}, 0x0}, {0x0, 0x0}, 0x14000409690, ...}, ...)

        /home/runner/work/pulumi/pulumi/pkg/codegen/go/gen_program.go:554 +0x6d4

main.(*goLanguageHost).GenerateProject(0x1400019e3c0, {0x10490bf1c?, 0x40?}, 0x1400060c240)

        /home/runner/work/pulumi/pulumi/sdk/go/pulumi-language-go/main.go:855 +0x360

github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_GenerateProject_Handler.func1({0x105fe6f10, 0x140007a74a0}, {0x105e99a00?, 0x1400060c240})

        /home/runner/work/pulumi/pulumi/sdk/proto/go/language_grpc.pb.go:429 +0x74

github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x105fe6f10, 0x140007a6420}, {0x105e99a00, 0x1400060c240}, 0x140003182c0, 0x140000b2ba0)

        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x308

github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_GenerateProject_Handler({0x105f21e60?, 0x1400019e3c0}, {0x105fe6f10, 0x140007a6420}, 0x14000144150, 0x14000488940)

        /home/runner/work/pulumi/pulumi/sdk/proto/go/language_grpc.pb.go:431 +0x138

google.golang.org/grpc.(*Server).processUnaryRPC(0x1400046c3c0, {0x105fefc00, 0x140006831e0}, 0x140004019e0, 0x14000424ed0, 0x106e48ab0, 0x0)

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1337 +0xc90

google.golang.org/grpc.(*Server).handleStream(0x1400046c3c0, {0x105fefc00, 0x140006831e0}, 0x140004019e0, 0x0)

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1714 +0x82c

google.golang.org/grpc.(*Server).serveStreams.func1.1()

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:959 +0x84

created by google.golang.org/grpc.(*Server).serveStreams.func1

        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:957 +0x16c

error: could not generate output program: error reading from server: EOF
```

**Comment by EvanBoyle** [comment]
Looks like the panic might be here:

https://github.com/pulumi/pulumi/blob/master/pkg/codegen/go/gen_program.go#L554

For context, I haven't published the MLC I'm developing yet but have installed it locally. Perhaps the version is nil as a result?

**Comment by EvanBoyle** [comment]
Looks like the reason I hit this is because the boilerplate repo was not correctly configured to link in the version:

https://github.com/pulumi/pulumi-provider-boilerplate/issues/61

**Comment by Zaid-Ajaj** [comment]
Trying to convert the YAML program to go using Pulumi v3.72.2 and `auto-deploy` v0.0.4 succeeds without panicking. It does generate incorrect aliasing for the module but that is tackled in #13212. I guess the underlying problem is that `go` program-gen expects `version` to be set 🤔

**Comment by EvanBoyle** [comment]
@Zaid-Ajaj `auto-deploy` v0.0.4 has a fix that properly sets the version.

Even if we don't change the go codegen to be resilient against missing version, should we at least add a null guard before accessing properties on the version? Should we return a well formatted error message that indicates something is wrong with the provider binary? 

My understanding was that we have a zero tolerance policy on panics, so seems like we would at least want to fix that.
