### ISSUE TITLE
Recursion error when calling identitystore.get_group_output(...)

### ISSUE THREAD

**Issue by ollaw** [pulumi/pulumi#13291]
### What happened?

Was trying to retrieve Group ID from identity store with the following snippet

```python
from pulumi_aws import identitystore

#  ...
#  ...
#  ... 

# Issue is related to get_group_output call, but I wrap it in a loop since it's how we bumped into this 
# and seems it's repeating the call multiple times which causes the troubles, since caching the responses
# fixes the problem.
for name in ["a","b","c" ... ]:
  identitystore.get_group_output(
    identity_store_id=identity_store,
    alternate_identifier=identitystore.GetGroupAlternateIdentifierArgs(
    unique_attribute=identitystore.GetGroupAlternateIdentifierUniqueAttributeArgs(
        attribute_path="DisplayName",
        attribute_value=name,
      )
    ),
  ).group_id
```

This code crashes during a `preview` (stack trace shown below) indicating a problem related to max level of recursion reached. 
**As said in the comment, seems like the problem is due to the fact that this function is called multiple times (even with same `name`. We were able to mitigate that adding a simple dictionary as a simple cache avoiding retrieving ID of Groups we already know.** 

Below the stack trace, there's a lot of output repeated and i tried to trim it. If needed I can post the entire one.
```
  error: Program failed with an unhandled exception:
  Traceback (most recent call last):
    File "/__t/pulumi/3.73.0/x64/pulumi-language-python-exec", line 197, in <module>
      loop.run_until_complete(coro)
    File "/opt/bitnami/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
      return future.result()
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
      await run_pulumi_func(lambda: Stack(func))
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
      await wait_for_rpcs()
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 73, in wait_for_rpcs
      await RPC_MANAGER.rpcs.pop()
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
      result = await rpc
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/output.py", line 99, in is_value_known
      return await is_known and not contains_unknowns(await future)
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/output.py", line 99, in is_value_known
      return await is_known and not contains_unknowns(await future)
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/output.py", line 99, in is_value_known
      return await is_known and not contains_unknowns(await future)
    [Previous line repeated 5 more times]


    
    ### [ REPEATED A LOT OF TIMES ]
    
    
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
      result = await rpc
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/output.py", line 99, in is_value_known
      return await is_known and not contains_unknowns(await future)
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/output.py", line 99, in is_value_known
      return await is_known and not contains_unknowns(await future)
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/output.py", line 99, in is_value_known
      return await is_known and not contains_unknowns(await future)
    [Previous line repeated 5 more times]
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 514, in do_register
      resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 124, in prepare_resource
      serialized_props = await rpc.serialize_properties(
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 207, in serialize_properties
      result = await serialize_property(
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 378, in serialize_property
      value = await serialize_property(
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 361, in serialize_property
      future_return = await asyncio.ensure_future(awaitable)


    ### [ REPEATED A LOT OF TIMES ]
    

      
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/output.py", line 124, in get_value
      val = await self._future
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/output.py", line 124, in get_value
      val = await self._future
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/output.py", line 124, in get_value
      val = await self._future
    [Previous line repeated 27 more times]
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/output.py", line 170, in run
      value = await self._future
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/output.py", line 195, in run
      transformed: Input[U] = func(value)
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi_aws/_utilities.py", line 243, in <lambda>
      }).apply(lambda resolved_args: func(*resolved_args['args'],
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi_aws/identitystore/get_group.py", line 145, in get_group
      __ret__ = pulumi.runtime.invoke('aws:identitystore/getGroup:getGroup', __args__, opts=opts, typ=GetGroupResult).value
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/invoke.py", line 142, in invoke
      invoke_result, invoke_error = _sync_await(asyncio.ensure_future(do_rpc()))
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/sync_await.py", line 87, in _sync_await
      return fut.result()
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/invoke.py", line 132, in do_rpc
      resp, exn = await RPC_MANAGER.do_rpc("invoke", do_invoke)()
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/runtime/rpc_manager.py", line 63, in rpc_wrapper
      log.debug(f"beginning rpc {name}")
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/log.py", line 45, in debug
      _log(engine, engine_pb2.DEBUG, msg, resource, stream_id, ephemeral)
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/pulumi/log.py", line 144, in _log
      engine.Log(req)
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 944, in __call__
      state, call, = self._blocking(request, timeout, metadata, credentials,
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 921, in _blocking
      state, operations, deadline, rendezvous = self._prepare(
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 907, in _prepare
      state = _RPCState(_UNARY_UNARY_INITIAL_DUE, None, None, None, None)
    File "/__w/core-infra/core-infra/root/pulumi/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 98, in __init__
      self.condition = threading.Condition()
    File "/opt/bitnami/python/lib/python3.9/threading.py", line 230, in __init__
      lock = RLock()
    File "/opt/bitnami/python/lib/python3.9/threading.py", line 93, in RLock
      return _CRLock(*args, **kwargs)
  RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Expected Behavior

Retrieve correctly all the Groups IDs.

### Steps to reproduce

That may be quite hard to reproduce, for both the nature of issue itself and the fact that seemed a bit flaky (bumped into this from GHA, some my colleagues were able to reproduce it locally, but not me). Using Poetry we at least had the same Python and dependencies version. 

The code above should be enough to reproduce it, as already mention wrap that call into a loop (eventually making calls also with same parameters) because that's how we bumped into that.

### Output of `pulumi about`

Currently don't have those information since personally I was unable to reproduce it, but I can look for it if needed.

### Additional context

`pulumi_aws == 5.41.0`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Thanks for filing this. We'll see what we can do. In the mean-time, you could potentially set your max recursion depth higher in your program, but this may not be a satisfactory answer.

**Comment by ollaw** [comment]
@dixler Yep, thanks. Doubling it solved the problem but we've been able to solve this just by caching the results and so limiting the calls.

I've opened the issue just to point out and help someone else 😄
