### ISSUE TITLE
bug: Typescript Promise leak detected with top level `async` function and `ComponentResource`

### ISSUE THREAD

**Issue by tmeckel** [pulumi/pulumi#13307]
### What happened?

Pulumi stops processing a `preview` when trying to create and reference a CompoentResource in a top-level `async` function.

**Command used:** `pulumi pre -r --diff`

**Reference:** https://www.pulumi.com/docs/languages-sdks/javascript/#entrypoint

```
Previewing update (default):
+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:default::async-components::pulumi:pulumi:Stack::async-components-default]
    + pkg:index:KeyVault: (create)
        [urn=urn:pulumi:default::async-components::pkg:index:KeyVault::keyvault]
    + azure:core/resourceGroup:ResourceGroup: (create)
        [urn=urn:pulumi:default::async-components::azure:core/resourceGroup:ResourceGroup::resource-group]
        [provider=urn:pulumi:default::async-components::pulumi:providers:azure::default_5_44_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        location  : "northeurope"
        name      : "rg-test-asnyc-components"
        + random:index/randomId:RandomId: (create)
            [urn=urn:pulumi:default::async-components::pkg:index:KeyVault$random:index/randomId:RandomId::random-id]
            [provider=urn:pulumi:default::async-components::pulumi:providers:random::default_4_13_2::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
            byteLength: 8
            keepers   : {
                keep: "keyvault"
            }
        + azure:keyvault/keyVault:KeyVault: (create)
            [urn=urn:pulumi:default::async-components::pkg:index:KeyVault$azure:keyvault/keyVault:KeyVault::keyvault]
            [provider=urn:pulumi:default::async-components::pulumi:providers:azure::default_5_44_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
            enableRbacAuthorization   : true
            enabledForDiskEncryption  : true
            location                  : "northeurope"
            name                      : output<string>
            publicNetworkAccessEnabled: true
            purgeProtectionEnabled    : false
            resourceGroupName         : "rg-test-asnyc-components"
            skuName                   : "standard"
            softDeleteRetentionDays   : 7
            tenantId                  : "eaf84f79-6028-44c2-8482-cc9668e6c88a"
    --outputs:--
    out: {
        @isPulumiResource: true
        keyVault         : {
            @isPulumiResource           : true
            accessPolicies              : output<string>
            contacts                    : output<string>
            enableRbacAuthorization     : true
            enabledForDeployment        : output<string>
            enabledForDiskEncryption    : true
            enabledForTemplateDeployment: output<string>
            id                          : output<string>
            location                    : "northeurope"
            name                        : output<string>
            networkAcls                 : output<string>
            publicNetworkAccessEnabled  : true
            purgeProtectionEnabled      : false
            resourceGroupName           : "rg-test-asnyc-components"
            skuName                     : "standard"
            softDeleteRetentionDays     : 7
            tags                        : output<string>
            tenantId                    : "eaf84f79-6028-44c2-8482-cc9668e6c88a"
            urn                         : "urn:pulumi:default::async-components::pkg:index:KeyVault$azure:keyvault/keyVault:KeyVault::keyvault"
            vaultUri                    : output<string>
        }
        urn              : "urn:pulumi:default::async-components::pkg:index:KeyVault::keyvault"
    }
        + azure:authorization/assignment:Assignment: (create)
            [urn=urn:pulumi:default::async-components::pkg:index:KeyVault$azure:authorization/assignment:Assignment::kv-admin-0]
            [provider=urn:pulumi:default::async-components::pulumi:providers:azure::default_5_44_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
            principalId       : "21e8e9a5-cc18-4450-aa35-2b86b93c9107"
            roleDefinitionName: "Key Vault Administrator"
            scope             : output<string>
Promise leak detected:

CONTEXT(206): rpcKeepAlive
STACK_TRACE:
Error: 
    at Object.debuggablePromise (/work/node_modules/@pulumi/runtime/debuggable.ts:74:75)
    at Object.rpcKeepAlive (/work/node_modules/@pulumi/runtime/settings.ts:404:25)
    at /work/node_modules/@pulumi/runtime/resource.ts:574:30
    at Generator.next (<anonymous>)
    at /work/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/work/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
    at prepareResource (/work/node_modules/@pulumi/pulumi/runtime/resource.js:409:12)
    at Object.registerResource (/work/node_modules/@pulumi/runtime/resource.ts:394:24)
    at new Resource (/work/node_modules/@pulumi/resource.ts:423:13)
Promise leak detected:

CONTEXT(207): resolveURN(resource:password[random:index/randomPassword:RandomPassword])

...
``` 

### Expected Behavior

Pulumi successfully performs a `preview`.

### Steps to reproduce

Sample program

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure"
import * as random from '@pulumi/random'

interface KeyVaultArgs {
    resourceGroupName: pulumi.Input<string>,
    location: pulumi.Input<string>
    tenantId: pulumi.Input<string>
    administrators: pulumi.Input<string>[]
}

class KeyVault extends pulumi.ComponentResource {
    private keyVault: azure.keyvault.KeyVault

    constructor(name: string, args: KeyVaultArgs, opts?: pulumi.ComponentResourceOptions) {
        super("pkg:index:KeyVault", name, {}, opts)

        if (!args.administrators?.length) {
            throw new Error("The list of administrators cannot be empty")
        }

        const rndId = new random.RandomId("random-id", {
            byteLength: 8,
            keepers: {
                "keep": name
            }
        }, {
            parent: this
        })

        this.keyVault = new azure.keyvault.KeyVault("keyvault", {
            name: pulumi.interpolate`kv${rndId.hex}`,
            location: args.location,
            resourceGroupName: args.resourceGroupName,
            enabledForDiskEncryption: true,
            tenantId: args.tenantId,
            softDeleteRetentionDays: 7,
            purgeProtectionEnabled: false,
            skuName: "standard",
            enableRbacAuthorization: true,
        }, {
            parent: this
        });

        args.administrators.forEach((principalId, idx) => {
            const roleAssignment = new azure.authorization.Assignment(`kv-admin-${idx}`, {
                principalId: principalId,
                scope: this.keyVault.id,
                roleDefinitionName: "Key Vault Administrator"
            }, {
                parent: this
            })
        })

        this.registerOutputs({
            keyVault: this.keyVault
        })
    }

    get instance(): azure.keyvault.KeyVault {
        return this.keyVault
    }
}

// Create an async wrapper, so that we can use async/await pattern
export = async () => {

    const current = await azure.core.getClientConfig()
    const resourceGroup = new azure.core.ResourceGroup("resource-group", {
        name: "rg-test-asnyc-components",
        location: "northeurope"
    });

    const keyVault = new KeyVault("keyvault", {
        location: resourceGroup.location,
        resourceGroupName: resourceGroup.name,
        tenantId: current.tenantId,
        administrators: [
            current.objectId
        ]
    })

    const password = new random.RandomPassword("password", {
        length: 32,
        keepers: {
            "keeper": keyVault.urn
        }
    })

    const kvSecret = new azure.keyvault.Secret("password-secret", {
        keyVaultId: keyVault.instance.id,
        value: password.result,
        name: "password"
    }, {
        parent: keyVault
    })

} // async-wrapper
```

### Output of `pulumi about`

```
CLI          
Version      3.72.2
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
azure   5.44.1
nodejs  unknown
random  4.13.2

Host     
OS       debian
Version  11.7
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.16.0'

Backend        
Name           7ce2cd941b2a
URL            file://.stacks
User           root
Organizations  

Dependencies:
NAME            VERSION
@pulumi/azure   5.44.1
@pulumi/pulumi  3.73.0
@pulumi/random  4.13.2
@types/node     16.18.37
eslint          8.43.0
typescript      5.1.5
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Hi @tmeckel. It looks like the problem is unrelated to top level `async` and `ComponentResource`...

The source of the error is this resource definition:

```typescript
    const kvSecret = new azure.keyvault.Secret("password-secret", {
        keyVaultId: keyVault.instance.id,
        value: password.result,
        name: "password"
    }, {
        parent: keyVault
    })
```

Specifically the `parent: keyVault`. You're adding a child to the component outside of the component, which often can lead to cyclical dependencies and/or promise leaks. You could workaround by not setting a parent, or setting the parent to `parent: keyVault.instance.id` instead.

Hope this helps!

---

Unrelated to the error, I also wanted to mention that you don't strictly need the top level async function in this example. An alternative would be to wrap the result of the `azure.core.getClientConfig()` call as an `pulumi.output`:

```typescript
const current = pulumi.output(azure.core.getClientConfig())
const resourceGroup = new azure.core.ResourceGroup("resource-group", {
    name: "rg-test-asnyc-components",
    location: "northeurope"
});

const keyVault = new KeyVault("keyvault", {
    location: resourceGroup.location,
    resourceGroupName: resourceGroup.name,
    tenantId: current.tenantId,
    administrators: [
        current.objectId
    ]
})

...
```

**Comment by tmeckel** [comment]
@justinvp sorry for the late response and thank you for your valuable answer. Especially for the nice hint using `pulumi.output` instead of an `async` wrapper.

Only for my understanding: adding a `ComponentResource` as a parent to another resource (or `ComponentResource`) will lead to described error in Javascript/NodeJS. But why is it that so harmful? And why is it okay, to use the `id` of  a member of the `ComponentResource`? 

Would a `parent: keyVault.instance`, i.e. a reference to the complete provider resource (`azure.keyvault.KeyVault`) work as well? If that's the case, I wonder what makes a `ComponentResource` so "special" that it can't be used as a parent resource of another resource and if this might be a bug in the implementation of the `ComponentResource` itself.
