### ISSUE TITLE
Panic when Alias is malformed

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#13490]
### What happened?

Alias was malformed and it caused a panic. 
```
@ previewing update....panic: runtime error: index out of range [3] with length 3

goroutine 90 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/resource.URN.Name({0xc002c79970?, 0xa8?})
	/workspace/sdk/go/common/resource/urn.go:122 +0x65
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).generateAliases(0xc000236fc0, 0xc004722780)
	/workspace/pkg/resource/deploy/step_generator.go:433 +0x30a
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).generateSteps(0xc000236fc0, {0x7fffd0510a28, 0xc002888f30})
	/workspace/pkg/resource/deploy/step_generator.go:460 +0xfb
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).GenerateSteps(0xc000236fc0, {0x7fffd0510a28?, 0xc002888f30?})
	/workspace/pkg/resource/deploy/step_generator.go:258 +0x46
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).handleSingleEvent(0xc0027fb1d0, {0x29b4d40?, 0xc002888f30})
	/workspace/pkg/resource/deploy/deployment_executor.go:399 +0xdd
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute.func3(0xc001ff2960, 0xc0027fb1d0, 0xc00212bed0, {{0x7fffd0ddef58, 0xc001ed72c0}, 0x7fffffff, 0x0, 0x0, {{0x3b784f0, 0x0, ...}, ...}, ...}, ...)
	/workspace/pkg/resource/deploy/deployment_executor.go:250 +0x21e
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute(0xc0027fb1d0, {0x29ced30?, 0xc001fffa70}, {{0x7fffd0ddef58, 0xc001ed72c0}, 0x7fffffff, 0x0, 0x0, {{0x3b784f0, 0x0, ...}, ...}, ...}, ...)
	/workspace/pkg/resource/deploy/deployment_executor.go:266 +0x839
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Deployment).Execute(0xc000cf0fd0, {0x29ced30, 0xc001fffa70}, {{0x7fffd0ddef58, 0xc001ed72c0}, 0x7fffffff, 0x0, 0x0, {{0x3b784f0, 0x0, ...}, ...}, ...}, ...)
	/workspace/pkg/resource/deploy/deployment.go:564 +0xd0
github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run.func1()
	/workspace/pkg/engine/deployment.go:298 +0x214
created by github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run
	/workspace/pkg/engine/deployment.go:283 +0x365
```

### Expected Behavior

It should not panic, but throw a helpful error message.

### Steps to reproduce

Set an fstring alias to the wrong number of items. 
pulumi preview

### Output of `pulumi about`

will add later

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
We should return an error for invalid URNs for aliases, rather than panicking.
