### ISSUE TITLE
await aws.s3.getBucket throws TypeError: Cannot read properties of undefined (reading 'invoke')

### ISSUE THREAD

**Issue by admintoystack** [pulumi/pulumi#13505]
### What happened?

Im trying to get the bucket using the await method, it throws the error cannot read properties of undefined (reading 'Inovoke').

This the code
```
import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';


 const bucketName = "test-bucket";

  const getBucketDetails = async () => {

    try {
        const response = await aws.s3.getBucket({bucket: bucketName});

        return response

    } catch (error) {

      console.log(error);

        pulumi.log.error(Failed to get bucket details: ${error});

        pulumi.log.error(error.stack!); // Log the stack trace

        throw error;
    }
};
let getData = getBucketDetails()
const bucketNameOutput = getData;
console.log(bucketNameOutput) 
```

Throws the error like this 

```error: [runtime] Failed to get bucket details: TypeError: Cannot read properties of undefined (reading 'invoke')
error: [runtime] TypeError: Cannot read properties of undefined (reading 'invoke')
    at /opt/clients/node_modules/@pulumi/runtime/invoke.ts:158:25
    at new Promise (<anonymous>)
    at /opt/clients//node_modules/@pulumi/runtime/invoke.ts:157:13
    at Generator.next (<anonymous>)
    at fulfilled (/opt/clients/toystack/toy_stack_backend/toystack-core-backend/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected Behavior

It was supposed to get the bucket details but it is not 

`"@pulumi/aws": "^5.0.0", 
  "@pulumi/awsx": "^1.0.0",
  "@pulumi/eks": "^1.0.1",
  "@pulumi/pulumi": "^3.0.0",
`

### Steps to reproduce

I have pasted the code above

### Output of `pulumi about`

There is no pulumi about in my root of the project

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I'm not able to repro that error. Running your code as is just prints that `bucketNameOutput` is a promise object. Fixing it up to wait for that works as expected.

**Comment by Frassle** [comment]
Oh wait, I can repro. You ran this program directly via node, without the pulumi engine attached. We should make this error message better, but this isn't expected to work. 
Run your program using the `pulumi` command, see https://www.pulumi.com/docs/clouds/aws/get-started/begin/ for a getting started guide.

**Comment by Frassle** [comment]
> should it still not be possible, since the programmatic approach is supported via the Automation API?

Yup but only if you're calling this from within a program function inside Automation API. You need an engine context running for this method to work.

**Comment by justinvp** [comment]
This can also happen when there are multiple copies of `@pulumi/pulumi`. See #17074 and #18057.

Using this issue to track:

1. Seeing if there's a way we can make `getMonitor()` work even in the face of multiple copies of `@pulumi/pulumi`
2. Aside from that, at a minimum we should provide a better error message when the result of `getMonitor()` is `undefined`, which can happen when there are multiple copies of the SDK or if you try to run the program directly rather than via `pulumi up` or inline automation API.
