### ISSUE TITLE
Automation: remove stack error

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi#13547]
### What happened?

Hi,
I would like to use the pulumi automation API to remove a stack.

Consider the following:

```python
from pulumi import automation as auto

workspace = auto.LocalWorkspace(
    work_dir="/tmp",
    secrets_provider="gcpkms://projects/...",
    project_settings=auto.ProjectSettings(
        name="cloudrun",
        runtime="python",
        backend=auto.ProjectBackend(url="gs://<bucket>"),
    ),
)
stack = auto.select_stack(
    stack_name="stack_name",
    work_dir=workspace.work_dir,
)

stack.destroy(on_output=print)
```

I get the following output:

```console
Destroying (stack_name):

Resources:

Duration: 1s

The resources in the stack have been deleted, but the history and configuration associated with the stack are still maintained.
If you want to remove the stack completely, run `pulumi stack rm stack_name`.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/pulumi/automation/_stack.py", line 577, in destroy
    summary = self.info(show_secrets and not self._remote)
  File "/usr/local/lib/python3.10/site-packages/pulumi/automation/_stack.py", line 744, in info
    history = self.history(page_size=1, show_secrets=show_secrets)
  File "/usr/local/lib/python3.10/site-packages/pulumi/automation/_stack.py", line 710, in history
    result = self._run_pulumi_cmd_sync(args)
  File "/usr/local/lib/python3.10/site-packages/pulumi/automation/_stack.py", line 789, in _run_pulumi_cmd_sync
    result = _run_pulumi_cmd(args, self.workspace.work_dir, envs, on_output)
  File "/usr/local/lib/python3.10/site-packages/pulumi/automation/_cmd.py", line 78, in _run_pulumi_cmd
    raise create_command_error(result)
pulumi.automation.errors.CommandError: 
 code: 255
 stdout: 
 stderr: error: decrypting secrets: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables
```

The resources are correctly removed but it errors right after.

### Expected Behavior

Stack is delete without any error.

### Steps to reproduce

`python script.py`

### Output of `pulumi about`

```
CLI          
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME        VERSION
gcp         6.59.0
kubernetes  3.30.2
python      unknown

Host     
OS       debian
Version  12.0
Arch     x86_64

This project is written in python: executable='/usr/local/bin/python3' version='3.10.12
'

Current Stack: organization/cloudrun/py_backend-model-cache-bbd2cee

Found no resources associated with py_backend-model-cache-bbd2cee

Found no pending operations associated with py_backend-model-cache-bbd2cee

Backend        
Name           35da13947ce9
URL            gs://prmx-stage-pulumi-platform
User           root
Organizations  

Dependencies:
NAME               VERSION
pip                23.0.1
pulumi-gcp         6.59.0
pulumi-kubernetes  3.30.2
setuptools         65.5.1
wheel              0.40.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi there @yellowhat 👋 thanks a lot for opening this issue. It looks like it is specific to using google KMS as a secret provider in the program. From the error we see that the stack has been destroyed but the program still fails with secrets not being decrypted 🤔 looks weird for sure. We will have a look into this promptly and come back to you with our findings

**Comment by yellowhat** [comment]
Hi,
do you need any other information from my side?

**Comment by yellowhat** [comment]
Hi, any news?

**Comment by lunaris** [comment]
Hi @yellowhat; sorry that this issue appears to have gone stale. The issue you are encountering is due to a feature of the automation API where, after performing an operation (here `destroy`), the SDK will fetch information about the operation to present back (e.g. the changed resources, etc.). This will ask for the stack's history, which if the stack contains secrets, will by default require the ability to decrypt those secrets. I think the error you are seeing is because your automation program is not running with that ability (e.g. the appropriate AWS and KMS credentials).

I believe you can pass `show_secrets=False` to the `destroy` method to work around this, or you could furnish your automation API program with the relevant credentials. Let me know if this helps/whether or not this is still an issue for you 🙏
