### ISSUE TITLE
Panic occurring when changing config and running update with refresh

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#13558]
### What happened?

Got this error:

```
pulumi:pulumi:Stack (update-refresh-dev):
    panic: send on closed channel
    goroutine 64 [running]:
    main.(*nodeLanguageHost).Run.func4()
        /home/runner/work/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/main.go:544 +0xa5
    created by main.(*nodeLanguageHost).Run
        /home/runner/work/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/main.go:541 +0x5ea

    error: error reading from server: EOF
```

### Expected Behavior

A refresh of the resources and then an update.

### Steps to reproduce

1. Clone this repo: https://github.com/pierskarsenbarg/update-refresh
2. Run `pulumi up`
3. Run this: `pulumi config set pwLength 20` (or set it to be a different number from the one that's already in `Pulumi.dev.yaml`
4. Run `pulumi up --refresh`

### Output of `pulumi about`

```
CLI          
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown
random  4.13.2

Host     
OS       darwin
Version  13.4.1
Arch     x86_64

This project is written in nodejs: executable='/Users/piers/.nvm/versions/node/v18.12.1/bin/node' version='v18.12.1'

Current Stack: pierskarsenbarg/update-refresh/dev

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:dev::update-refresh::pulumi:pulumi:Stack::update-refresh-dev
pulumi:providers:random                     urn:pulumi:dev::update-refresh::pulumi:providers:random::default_4_13_2
random:index/randomPassword:RandomPassword  urn:pulumi:dev::update-refresh::random:index/randomPassword:RandomPassword::pw


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/pierskarsenbarg
User           pierskarsenbarg
Organizations  pierskarsenbarg, karsenbarg, team-ce, demo

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.76.0
@pulumi/random  4.13.2
@types/node     16.18.38

Pulumi locates its logs in /var/folders/69/3w1gr05s2pq36wn49bhyknym0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
@pierskarsenbarg could you repro this consistently? It seems to work ok for me.

` panic: send on closed channel` looks like a race bug to me, so might be this is intermittent.

**Comment by pierskarsenbarg** [comment]
I've seen it once since I filed this, but only once and I've had it been successful every other time.
