### ISSUE TITLE
Panic when updating Pulumi CLI to v3.76.1

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#13634]
### What happened?

Customer experienced a panic after upgrading to Pulumi CLI v3.76.1:

```
aws:ec2:VpcEndpoint (secretsManagerVPCEdpoint):

    error: error reading from server: EOF

  pulumi:pulumi:Stack (<customer-stack-name>):

    warning: provider config warning: skip_metadata_api_check: the use of values other than "true" and "false" is deprecated and will be removed in a future version of the provider

    error: update failed

    panic: interface conversion: interface {} is nil, not map[string]interface {}

    goroutine 83 [running]:
    github.com/hashicorp/go-cty/cty.Value.GetAttr({{{0x111302230?, 0x140083ce808?}}, {0x0?, 0x0?}}, {0x10d424969, 0x8})
       [/home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:711](mailto:/home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:711) +0x268
    github.com/hashicorp/terraform-provider-aws/internal/provider.tagsInterceptor.run({0x14000685700?, 0x1111e5078?, 0x1111e5070?}, {0x111300ac8, 0x14008417170}, {0x11130eb20, 0x14001085900}, {0x11117d5a0?, 0x14002b04750?}, 0x1, ...)
       /home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/provider/intercept.go:250 +0xea4
    github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0x11117d5a0?, 0x14002b04750?})
       /home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/provider/intercept.go:100 +0x114
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x111300a58?, {0x111300a58?, 0x140000b6080?}, 0xd?, {0x11117d5a0?, 0x14002b04750?})
       [/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230710100801-03a71d0fca3d/helper/schema/resource.go:767](mailto:/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230710100801-03a71d0fca3d/helper/schema/resource.go:767) +0x64
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400119fdc0, {0x111300a58, 0x140000b6080}, 0x1400607a4e0, 0x14001085400, {0x11117d5a0, 0x14002b04750})
       [/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230710100801-03a71d0fca3d/helper/schema/resource.go:879](mailto:/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230710100801-03a71d0fca3d/helper/schema/resource.go:879) +0x6b0
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0x140008cc2a0?, {0x14000638a30?, 0x140083d3670?, 0x0?}}, {0x10d467442, 0x10}, {0x111302700?, 0x140082c9ea8}, {0x11130f888?, 0x14001085400})
       [/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.54.1/pkg/tfshim/sdk-v2/provider.go:100](mailto:/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.54.1/pkg/tfshim/sdk-v2/provider.go:100) +0x160
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Update(0x14003f4a580, {0x111300ac8?, 0x140082e3ce0?}, 0x14007f69a70)
       [/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.54.1/pkg/tfbridge/provider.go:929](mailto:/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.54.1/pkg/tfbridge/provider.go:929) +0x688
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Update.func1({0x111327390?, 0x14003f4a580?})
       [/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.6/muxer.go:356](mailto:/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.6/muxer.go:356) +0x3c
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.resourceMethod[...](0x14001729860?, 0x1400820d778, 0x1400820d758?)
       [/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.6/muxer.go:303](mailto:/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.6/muxer.go:303) +0xc4
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Update(0x1400820d7b8?, {0x111300ac8?, 0x140082e3ce0?}, 0x10ef4d440?)
       [/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.6/muxer.go:355](mailto:/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.6/muxer.go:355) +0x5c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1({0x111300ac8, 0x140082e3ce0}, {0x110dea180?, 0x14007f69a70})
       [/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.75.0/proto/go/provider_grpc.pb.go:609](mailto:/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.75.0/proto/go/provider_grpc.pb.go:609) +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x111300ac8, 0x140082e34d0}, {0x110dea180, 0x14007f69a70}, 0x140082dd8c0, 0x140082c99e0)
       [/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57](mailto:/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57) +0x308
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler({0x111008900?, 0x14001729860}, {0x111300ac8, 0x140082e34d0}, 0x140082cfb90, 0x14003f0e6c0)
       [/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.75.0/proto/go/provider_grpc.pb.go:611](mailto:/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.75.0/proto/go/provider_grpc.pb.go:611) +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140000b23c0, {0x1113107e0, 0x140036a21a0}, 0x140082ed680, 0x140058d6690, 0x1197c23f0, 0x0)
       [/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:1337](mailto:/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:1337) +0xc90
    google.golang.org/grpc.(*Server).handleStream(0x140000b23c0, {0x1113107e0, 0x140036a21a0}, 0x140082ed680, 0x0)
       [/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:1714](mailto:/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:1714) +0x82c
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
       [/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:959](mailto:/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:959) +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
       [/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:957](mailto:/home/runner/go/pkg/mod/google.golang.org/grpc@v1.56.1/server.go:957) +0x16c
```

### Expected Behavior

No panic.

### Steps to reproduce

Requested from customer.

### Output of `pulumi about`

Requested from customer. Will update when provided.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
That stacktrace looks like a pulumi-aws issue rather than the CLI?

**Comment by ringods** [comment]
@Frassle customer responded with `pulumi about` (updated above). They are using AWS 6.0.0-alpha.5+8163083e
