### ISSUE TITLE
Panic on SIGINT shortly after `pulumi up`

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#13667]
### What happened?

Also known as "ctrl-c" or "cmd-c", a SIGINT sent shortly after process start resulted in a panic being thrown:

```
$ pulumi up
Previewing update (corp)

View in Browser (Ctrl+O): https://app.pulumi.com/pulumi/pulumi-ai-app-infra/corp/previews/d6843c91-9bba-4a8a-9a84-cc425d4f7c15



================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.76.0
Go Version:       go1.20.6
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            send on closed channel

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.6/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler(0xc0016c3f47)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:35 +0x47
panic({0x200fd00, 0x28de370})
        /opt/hostedtoolcache/go/1.20.6/x64/src/runtime/panic.go:884 +0x213
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.loadPlugin(0xc0016c09f8?, 0xc000199090)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:268 +0xbd
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).LanguageRuntime(0xc0000d1b80, {0x0, 0x0}, {0xc000318870, 0x3c}, {0xc000c965b0, 0x6}, 0xc001702e70)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:408 +0x125
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.GetRequiredPlugins({0x290d4e0?, 0xc0000d1b80?}, {0x0?, 0x3a22e20?}, {0xc000db02c0, {0xc000318870, 0x3c}, {0x28d4628, 0x1}}, 0x7)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:577 +0xa8
github.com/pulumi/pulumi/pkg/v3/engine.gatherPluginsFromProgram(0xc000893900, {0xc000db02c0, {0xc000318870, 0x3c}, {0x28d4628, 0x1}})
        /home/runner/work/pulumi/pulumi/pkg/engine/plugins.go:123 +0xea
github.com/pulumi/pulumi/pkg/v3/engine.installPlugins(0x4198b1?, {0xc000318870?, 0xc0016c0c90?}, {0x28d4628?, 0xc0014a6000?}, 0x18?, 0xc000893900, 0x0)
        /home/runner/work/pulumi/pulumi/pkg/engine/update.go:227 +0xb9
github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource({_, _}, {{{0x3a23510, 0x0, 0x0}, {0xc000922420, 0x1, 0x1}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/engine/update.go:378 +0x85
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x3a23510, 0x0, 0x0}, {0xc000922420, 0x1, 0x1}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:189 +0x38f
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x3a23510, 0x0, 0x0}, {0xc000922420, 0x1, 0x1}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/engine/update.go:454 +0x391
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x28fbc90, 0xc0015a4900}, 0xc000dab980, {{0x3a23510, 0x0, 0x0}, {0xc000922420, 0x1, 0x1}, 0x7fffffff, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/engine/update.go:194 +0x690
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc000db02c0, {0xc000318870, 0x3c}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1220 +0x8ef
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc000db02c0, {0xc000318870, 0x3c}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1136 +0x5ab
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt({_, _}, {_, _}, {_, _}, {0xc000db02c0, {0xc000318870, 0x3c}, {0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/apply.go:116 +0x17a
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc000db02c0, {0xc000318870, 0x3c}, {0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/apply.go:248 +0x13e
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Update(_, {_, _}, {_, _}, {0xc000db02c0, {0xc000318870, 0x3c}, {0x0, 0x0, ...}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:989 +0xc5
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc000db02c0, {0xc000318870, 0x3c}, {0x0, 0x0, 0x0}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/stack.go:94 +0xba
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Update(_, {_, _}, {0xc000db02c0, {0xc000318870, 0x3c}, {0x0, 0x0, 0x0}, 0xc000bc15c0, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:168 +0x88
main.newUpCmd.func1({_, _}, {{{0x3a23510, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:170 +0x10f5
main.newUpCmd.func3(0x0?, {0x3a23510, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:491 +0xc73
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000c8b500?, {0x3a23510, 0x0, 0x0})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4c
github.com/spf13/cobra.(*Command).execute(0xc000c8b500, {0x3a23510, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc00081ec00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:56 +0x65
```

### Expected Behavior

No panic.

### Steps to reproduce

This is a bit hard to reproduce, but the stack trace and error is a send on closed channel, pointing to the channel send here:

https://github.com/pulumi/pulumi/blob/0d92abc9ede438ff2d728e5d7fabf1a69f018e77/sdk/go/common/resource/plugin/host.go#L264-L277

We likely want some synchronization primitives here, as we want to wait for any outstanding plugin loads to complete before closing the plugin host:

https://github.com/pulumi/pulumi/blob/0d92abc9ede438ff2d728e5d7fabf1a69f018e77/sdk/go/common/resource/plugin/host.go#L521-L547

And here, as if we are in a "closing" state we want to short-circuit these goroutines to skip all pending loads.

https://github.com/pulumi/pulumi/blob/0d92abc9ede438ff2d728e5d7fabf1a69f018e77/sdk/go/common/resource/plugin/host.go#L148-L161

### Output of `pulumi about`

```
CLI          
Version      3.76.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.42.0
aws-native  0.70.0
docker      4.3.0
nodejs      unknown
random      4.13.2

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

... omitting the resource URNs

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/friel-pulumi-corp
User           friel-pulumi-corp
Organizations  friel-pulumi-corp, pulumi

Dependencies:
NAME                VERSION
@pulumi/random      4.13.2
@types/node         16.18.38
ts-node             10.9.1
@pulumi/aws-native  0.70.0
@pulumi/aws         5.42.0
@pulumi/docker      4.3.0
@pulumi/pulumi      3.74.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Looks like a duplicate of #12371.
