### ISSUE TITLE
Can't create lambda when package.json lives in parent directory

### ISSUE THREAD

**Issue by jesseduffield** [pulumi/pulumi#13764]
### What happened?

I'm updating my pulumi repo to have a single package.json at the root and it's worked fine everywhere except when dealing with inline lambdas.

### Expected Behavior

`pulumi up` works fine

### Steps to reproduce

Folder structure:
```
package.json
package-lock.json
node_modules/
repro/
  index.ts
  Pulumi.yaml
  Pulumi.production.yaml
  tsconfig.json
```

package.json:
```json
{
    "name": "repro",
    "devDependencies": {
        "@types/aws-sdk": "^2.7.0",
        "@types/node": "^10.17.60"
    },
    "dependencies": {
        "@pulumi/aws": "^5.42.0"
    }
}
```

index.ts:
```ts
import * as aws from '@pulumi/aws'

const lambdaFunction = new aws.lambda.CallbackFunction('my-callback', {
  callback: async (_) => {
    return "foo"
  },
  runtime: 'nodejs16.x',
})
```

tsconfig.json:
```json
{
    "compilerOptions": {
        "strict": true,
        "outDir": "bin",
        "target": "es2016",
        "module": "commonjs",
        "moduleResolution": "node",
    },
    "files": [
        "index.ts"
    ]
}
```

Error upon running `pulumi up`:
```
Previewing update (production)

View in Browser (Ctrl+O): https://app.pulumi.com/Activepipe/repro/production/previews/6a8bf1c8-91dc-4fb1-88f5-9954f9f46e5f

     Type                 Name              Plan       Info
 +   pulumi:pulumi:Stack  repro-production  create     1 error


Diagnostics:
  pulumi:pulumi:Stack (repro-production):
    error: Running program '/Users/jesse/repos/pulumi-lambda-repro/documentdb-repro/' failed with an unhandled exception:
    Error: Cannot find module './wafregional'
    Require stack:
    - /Users/jesse/repos/pulumi-lambda-repro/documentdb-repro/node_modules/@pulumi/aws/index.js
    - /Users/jesse/repos/pulumi-lambda-repro/documentdb-repro/index.ts
    - /Users/jesse/repos/pulumi-lambda-repro/node_modules/@pulumi/pulumi/cmd/run/run.js
    - /Users/jesse/repos/pulumi-lambda-repro/node_modules/@pulumi/pulumi/cmd/run/index.js
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
        at Function.Module._load (node:internal/modules/cjs/loader:778:27)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.<anonymous> (/Users/jesse/repos/pulumi-lambda-repro/documentdb-repro/node_modules/@pulumi/index.ts:288:1)
        at Module._compile (node:internal/modules/cjs/loader:1105:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/Users/jesse/repos/pulumi-lambda-repro/documentdb-repro/node_modules/@pulumi/aws/index.js',
        '/Users/jesse/repos/pulumi-lambda-repro/documentdb-repro/index.ts',
        '/Users/jesse/repos/pulumi-lambda-repro/node_modules/@pulumi/pulumi/cmd/run/run.js',
        '/Users/jesse/repos/pulumi-lambda-repro/node_modules/@pulumi/pulumi/cmd/run/index.js'
      ]
    }
```

### Output of `pulumi about`

▶ pulumi about
CLI
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
nodejs  unknown

Host
OS       darwin
Version  12.5.1
Arch     x86_64

This project is written in nodejs: executable='/Users/jesse/.nvm/versions/node/v16.15.1/bin/node' version='v16.15.1'

Current Stack: Activepipe/repro/production

Found no resources associated with production

Found no pending operations associated with production

Backend
Name           pulumi.com
URL            https://app.pulumi.com/Activepipe
User           Activepipe
Organizations  Activepipe

Dependencies:
NAME            VERSION
@pulumi/aws     5.42.0
@types/aws-sdk  2.7.0
@types/node     10.17.60

Pulumi locates its logs in /var/folders/d_/3fryg6d934l7jxttrz1z21bh0000gn/T/ by default

### Additional context

Symlinking package.json, package-lock.json and node_modules doesn't help.

If I move package.json/package-lock.json into the same folder as `index.ts` and `npm i` it works fine, but my goal is to have a single package.json defined at the root of the repo for all pulumi projects to use.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi @jesseduffield I am able to reproduce the issue locally, here is the error message I am getting
```
Diagnostics:
  pulumi:pulumi:Stack (inlinelambda-dev):
    error: Error: Error reading file '/Users/zaid/projects/inlinelambda/repro/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open '/Users/zaid/projects/inlinelambda/repro/package.json'
        at readFile (/Users/zaid/projects/inlinelambda/node_modules/@pulumi/runtime/closure/codePaths.ts:256:19)
        at computeDependenciesDirectlyFromPackageFile (/Users/zaid/projects/inlinelambda/node_modules/@pulumi/runtime/closure/codePaths.ts:235:22)
        at /Users/zaid/projects/inlinelambda/node_modules/@pulumi/runtime/closure/codePaths.ts:193:36
        at /Users/zaid/projects/inlinelambda/node_modules/read-package-tree/rpt.js:162:20
```
I think we need to lookup package.json recursively from the current working directory up the parent directories. Assigned the issue to myself and looking into it now.

**Comment by lukehoban** [comment]
Is this the same issue as tracked in https://github.com/pulumi/pulumi/issues/7168?
