### ISSUE TITLE
cannot iterate over a value of type union(cty.NullVal(cty.DynamicPseudoType), map(dynamic)); 

### ISSUE THREAD

**Issue by AaronSaikovski** [pulumi/pulumi#13854]
### What happened?

pulumi convert --from terraform --language python --out pulumi

### Expected Behavior

converted output

### Steps to reproduce

pulumi convert --from terraform --language python --out pulumi

### Output of `pulumi about`

Converting from terraform...
Converting to python...
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.79.0
Go Version:       go1.21.0
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            fatal: An assertion has failed: error typechecking expression: locals.role_definitions.pp:26,45-74: cannot iterate over a value of type union(cty.NullVal(cty.DynamicPseudoType), map(dynamic)); 

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/debug/stack.go:24 +0x64
main.panicHandler(0x1400199feff)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:35 +0x44
panic({0x1065eb720?, 0x14000d108c0?})
        /opt/hostedtoolcache/go/1.21.0/x64/src/runtime/panic.go:914 +0x218
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x50?, {0x105e45452?, 0x1?}, {0x1400199df78?, 0x1400199df48?, 0x105bdf888?})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:35 +0xe0
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*observeContext).PostVisit(0x14001914c00, {0x106af7268?, 0x140019d2de0})
        /home/runner/work/pulumi/pulumi/pkg/codegen/pcl/rewrite_apply.go:560 +0xb8
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*applyRewriter).postVisit(0x14000a27d00, {0x106af7268?, 0x140019d2de0?})
        /home/runner/work/pulumi/pulumi/pkg/codegen/pcl/rewrite_apply.go:237 +0x38
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitIndex(0x140019d2de0, 0x140019d2de0?, 0x1400199e988)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:172 +0x1fc
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x106af7268?, 0x140019d2de0?}, 0x14000a27d00?, 0x1400199e988)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:325 +0x158
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitIndex(0x140019d2ea0, 0x140019d2ea0?, 0x1400199e988)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:167 +0xdc
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x106af7268?, 0x140019d2ea0?}, 0x0?, 0x1400199e988)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:325 +0x158
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitRelativeTraversal(0x140019defa0, 0x140019defa0?, 0x1400199e988)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:196 +0x40
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x106af72e8?, 0x140019defa0?}, 0x14000a0f230?, 0x1400199e988)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:331 +0x1c4
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitExpressions({0x140019d1a00, 0x4, 0x4}, 0x105bffc68?, 0x14001914c00?)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:273 +0xac
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitTemplate(0x140019f6780, 0x140019f6780?, 0x1400199e988)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:223 +0x48
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x106af6b68?, 0x140019f6780?}, 0x20?, 0x1400199e988)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:337 +0x230
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitObjectCons(0x140019f67c0, 0x140019f67c0?, 0x1400199e988)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:183 +0x168
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x106af6be8?, 0x140019f67c0?}, 0x1400199e818?, 0x1400199e988)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:329 +0x1a0
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.visitFor(0x140019f87e0, 0x140019f87e0?, 0x1400199e988)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:137 +0x194
github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model.VisitExpression({0x106af71e8?, 0x140019f87e0?}, 0x0?, 0x1400199e988)
        /home/runner/work/pulumi/pulumi/pkg/codegen/hcl2/model/visitor.go:321 +0x110
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.RewriteApplies({0x106af71e8?, 0x140019f87e0}, {0x106ac8620?, 0x1064590d8}, 0x0)
        /home/runner/work/pulumi/pulumi/pkg/codegen/pcl/rewrite_apply.go:659 +0x164
github.com/pulumi/pulumi/pkg/v3/codegen/python.(*generator).lowerExpression(0x14001a85980, {0x106af71e8?, 0x140019f87e0?}, {0x106af6e68, 0x140019fa440})
        /home/runner/work/pulumi/pulumi/pkg/codegen/python/gen_program_expressions.go:31 +0x54
github.com/pulumi/pulumi/pkg/v3/codegen/python.(*generator).genLocalVariable(0x14001a85980, {0x106ac7208, 0x14001a90300}, 0x140018a8300)
        /home/runner/work/pulumi/pulumi/pkg/codegen/python/gen_program.go:1079 +0x84
github.com/pulumi/pulumi/pkg/v3/codegen/python.(*generator).genNode(0x14001a85980?, {0x106ac7208?, 0x14001a90300?}, {0x106af63a8?, 0x140018a8300?})
        /home/runner/work/pulumi/pulumi/pkg/codegen/python/gen_program.go:560 +0x84
github.com/pulumi/pulumi/pkg/v3/codegen/python.GenerateProgram(0x1066b3dc0?)
        /home/runner/work/pulumi/pulumi/pkg/codegen/python/gen_program.go:70 +0x128
github.com/pulumi/pulumi/pkg/v3/codegen/python.GenerateProject({0x16b78b2e0, 0x6}, {{0x14000058110, 0xa}, {{0x0, 0x0}, 0x0}, {0x0, 0x0}, 0x0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/codegen/python/gen_program.go:304 +0x34
main.runConvert.func2({0x16b78b2e0?, 0x10477274c?}, {{0x14000058110, 0xa}, {{0x0, 0x0}, 0x0}, {0x0, 0x0}, 0x0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/convert.go:247 +0x44
main.runConvert.generatorWrapper.func7({0x1400137a000, 0x49}, {0x16b78b2e0, 0x6}, 0x140008406e0, {0x106ad6688, 0x14000a260c0}, 0x0)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/convert.go:206 +0x2ac
main.runConvert({0x106ae3e48, 0x140009f8860}, {0x140000580c4, 0x56}, {0x107ce6e00, 0x0, 0x0}, {0x16b78b2be, 0x9}, {0x16b78b2d3, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/convert.go:433 +0x1994
main.newConvertCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/convert.go:75 +0x17c
main.newConvertCmd.RunResultFunc.func2(0x14000a0aa00?, {0x140009e4d20, 0x0, 0x6})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x34
github.com/spf13/cobra.(*Command).execute(0x140009ff800, {0x140009e4cc0, 0x6, 0x6})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x14001035200)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:56 +0x54

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This is old, and me and codex can't trigger a repro here, so I'm going to optimistically close this that we likely fixed it already.
