### ISSUE TITLE
[sdk/python] `aws.lambda_.Function` `code` argument does not gracefully handle `code=pulumi.AssetArchive({"index.py": pulumi.StringAsset("")})`

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#13878]
### What happened?

I have the following program:

```python
import json
import pulumi
import pulumi_aws as aws


lambda_role = aws.iam.Role(
    "lambda-role",
    assume_role_policy=json.dumps(
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": "sts:AssumeRole",
                    "Principal": {"Service": "lambda.amazonaws.com"},
                    "Effect": "Allow",
                    "Sid": "",
                }
            ],
        }
    ),
)

policy_attachment = aws.iam.RolePolicyAttachment(
    "execution",
    role=lambda_role.name,
    policy_arn="arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
)

aws.lambda_.Function(
    "SleepLambda",
    code=pulumi.AssetArchive({"index.py": pulumi.StringAsset("")}), # offending line
    #code=pulumi.AssetArchive({"index.py": pulumi.StringAsset("this fixes this")}),
    handler="index.lambda_handler",
    role=lambda_role.arn,
    runtime="python3.8",
)
```

error message:

```
Diagnostics:
  pulumi:pulumi:Stack (py-hang-dyna-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/kdixler/.pulumi-dev/bin/pulumi-language-python-exec", line 197, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 137, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 121, in wait_for_rpcs
        raise exception
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
                 ^^^^^^^^^
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 1029, in do_register
        rpc.resolve_outputs(
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 1104, in resolve_outputs
        for key, value in deserialize_properties(outputs).items():
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 637, in deserialize_properties
        value = deserialize_property(v, keep_unknowns)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 769, in deserialize_property
        props = deserialize_properties(value, keep_unknowns)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 606, in deserialize_properties
        return AssetArchive(deserialize_property(props_struct["assets"]))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 769, in deserialize_property
        props = deserialize_properties(value, keep_unknowns)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 637, in deserialize_properties
        value = deserialize_property(v, keep_unknowns)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 769, in deserialize_property
        props = deserialize_properties(value, keep_unknowns)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/kdixler/Programs/py-hang-dyna/venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 600, in deserialize_properties
        raise AssertionError(
    AssertionError: Invalid asset encountered when unmarshalling resource property

```

### Expected Behavior

Pulumi should either
- be able to upload a lambda with empty files.
- error when files are empty.

### Steps to reproduce

See program.

### Output of `pulumi about`

```
% pulumi about
CLI          
Version      3.80.0-dev.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.0.3
python  unknown

Host     
OS       debian
Version  12.1
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.11.2
'

Current Stack: kyle-pulumi-corp/py-hang-dyna/dev

TYPE                                               URN
pulumi:pulumi:Stack                                urn:pulumi:dev::py-hang-dyna::pulumi:pulumi:Stack::py-hang-dyna-dev
pulumi:providers:aws                               urn:pulumi:dev::py-hang-dyna::pulumi:providers:aws::default_6_0_3
aws:iam/role:Role                                  urn:pulumi:dev::py-hang-dyna::aws:iam/role:Role::lambda-role
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::py-hang-dyna::aws:iam/rolePolicyAttachment:RolePolicyAttachment::execution
aws:lambda/function:Function                       urn:pulumi:dev::py-hang-dyna::aws:lambda/function:Function::SleepLambda


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/kyle-pulumi-corp
User           kyle-pulumi-corp
Organizations  kyle-pulumi-corp, kd-test2, kd-test1, pulumi

Dependencies:
NAME        VERSION
boto3       1.28.39
pip         23.2.1
pulumi-aws  6.0.3
setuptools  68.1.2
wheel       0.41.2

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Maybe related https://github.com/pulumi/pulumi/issues/6254
