### ISSUE TITLE
Automation API: calling createOrSelectStack after selecting another stack requires PULUMI_CONFIG_PASSPHRASE when using s3 secrets provider

### ISSUE THREAD

**Issue by DominicRoyStang** [pulumi/pulumi#14003]
### What happened?

I have a project that uses an s3 backend with aws kms secrets provider. I'm using the automation API `LocalWorkspace.createOrSelectStack` after selecting another stack first (to get its outputs). The first time I run the program, the stack gets created, but throws an error about a missing PULUMI_CONFIG_PASSPHRASE.

>Command failed with exit code 255: pulumi stack init dev-job --non-interactive\nerror: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables
>Created stack 'dev-job'
>at makeError (/Users/dom/Programming/[REDACTED:project_name]/pulumi/node_modules/execa/lib/error.js:60:11)\n    at handlePromise (/Users/dom/Programming/[REDACTED:project_name]/pulumi/node_modules/execa/index.js:118:26)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Workarounds/situations where the error does not occur:

- The pulumi program does not use a passphrase, but the error disappears if I set the variable with `export PULUMI_CONFIG_PASSPHRASE=whatever`. I would expect the program to work even without the variable being set.

- If I don't select another stack first, the error doesn't occur, and the program is able to continue without raising the error

### Example

Pulumi.dev.yaml
```yaml
secretsprovider: awskms://alias/[REDACTED:aws_kms_key_alias]
encryptedkey: [REDACTED]
config:
  aws:defaultTags:
    tags:
      tag1: "REDACTED"
  aws:region: us-east-1

```

job.ts
```typescript
import { LocalWorkspace } from '@pulumi/pulumi/automation/localWorkspace.js'

const projectName = 'blackline-bot' // same as in Pulumi.yaml
const sourceStackName = 'dev'
const stackName = `${sourceStackName}-job`

const workspace = await LocalWorkspace.create({ workDir: '.' })
const environmentSettings = await workspace.stackSettings(sourceStackName)

const sourceStack = await LocalWorkspace.selectStack({
    projectName,
    stackName: sourceStackName,
    program: async () => {},
}, {
    workDir: '.',
    secretsProvider: environmentSettings.secretsProvider,
    stackSettings: { [sourceStackName]: environmentSettings },
})

const stack = await LocalWorkspace.createOrSelectStack({
    projectName,
    stackName,
    program: async () => {},
}, {
    workDir: '.',
    secretsProvider: environmentSettings.secretsProvider,
    stackSettings: { [stackName]: environmentSettings },
})
console.log(`Created/selected stack ${stack.name} (this line does not get reached)`)
```

Execute with `yarn run build && node dist/job.js up`

### Output of `pulumi about`

CLI          
Version      3.83.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.1.0
aws         5.42.0
docker      4.4.1
kubernetes  4.2.0
nodejs      unknown

Host     
OS       darwin
Version  13.5.2
Arch     arm64

This project is written in nodejs: executable='/Users/dom/.asdf/shims/node' version='v18.16.1'

Current Stack: organization/[REDACTED:project_name]/[REDACTED:stack_name]

TYPE                                       URN
[REDACTED]

Found no pending operations associated with [REDACTED:stack_name]

Backend        
Name          <REDACTED>
URL            s3://[REDACTED:bucket_name]/[REDACTED:object]
User           dom
Organizations  

Pulumi locates its logs in /var/folders/0f/spy7dccj3dq73_tx646_68g40000gp/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: failed to run "/Users/dom/.asdf/shims/yarn list --json": exit status 1

### Additional context

My use case for this is that I create a new "sub-stack" that inherits configuration from the regular `dev` stack. I have to select the `dev` stack first to get its outputs, which are then used as inputs for the pulumi program "sub-stack" (`dev-job`).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by DominicRoyStang** [comment]
Possibly related issues:
- https://github.com/pulumi/pulumi/issues/11591
- https://github.com/pulumi/automation-api-examples/issues/4#issuecomment-1282128462
