### ISSUE TITLE
Python SDK generator continues to fail with incorrectCase

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#14274]
### What happened?

When upgrading pulumi-aws to bridge v3.62.0 that pulls in Pulumi v3.89.0, an integration test started failing with:

``` 
  Diagnostics:
    pulumi:pulumi:Stack (codebuild-project-py-p-it-runner-codebuild--e6f6c90e):
      error: Program failed with an unhandled exception:
      Traceback (most recent call last):
        File "/tmp/p-it-runner-codebuild--e6f6c90e-3217781259/./__main__.py", line 61, in <module>
          prebuild_project = codebuild.Project(
        File "/home/runner/work/pulumi-aws/pulumi-aws/sdk/python/bin/pulumi_aws/codebuild/project.py", line 1469, in __init__
          __self__._internal_init(resource_name, *args, **kwargs)
        File "/home/runner/work/pulumi-aws/pulumi-aws/sdk/python/bin/pulumi_aws/codebuild/project.py", line 1535, in _internal_init
          ProjectEnvironmentArgs._configure(_setter, **environment)
      TypeError: _configure() missing 1 required positional argument: 'compute_type'
 
```

You can see the example code in https://github.com/pulumi/pulumi-aws/blob/upgrade-pulumi-terraform-bridge-to-v3.62.0/examples/codebuild-project-py/__main__.py#L69

I suspect this can be worked around by replacing         

```
"computeType": "BUILD_GENERAL1_SMALL"
```

with

```
"compute_type": "BUILD_GENERAL1_SMALL"
```

or some such in case of AWS, but I wanted to flag as it may have broader impact.

### Example

See https://github.com/pulumi/pulumi-aws/blob/upgrade-pulumi-terraform-bridge-to-v3.62.0/examples/codebuild-project-py/__main__.py#L69

### Output of `pulumi about`

N/A

### Additional context

It is possible that https://github.com/pulumi/pulumi/issues/14151 is either not fixed or not fixed for second-level properties. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
The failing test: https://github.com/pulumi/pulumi-aws/blob/upgrade-pulumi-terraform-bridge-to-v3.62.0/examples/codebuild-project-py/__main__.py#L69

```python
prebuild_project = codebuild.Project(
    resource_name="sample",
    name="sample",
    build_timeout=30,  # In minutes
    artifacts={
        "type": "NO_ARTIFACTS",
    },
    environment={
        "computeType": "BUILD_GENERAL1_SMALL",
        "image": "aws/codebuild/amazonlinux2-x86_64-standard:3.0",
        "imagePullCredentialsType": "CODEBUILD",
        "type": "LINUX_CONTAINER",
        "privilegedMode": True,  # Required to use docker
    },
```

Here's what the `_configure` method for the `ProjectEnvironmentArgs` class looks like with v3.89.0 codegen:

```python
    @staticmethod
    def _configure(
             _setter: Callable[[Any, Any], None],
             compute_type: pulumi.Input[str],
             image: pulumi.Input[str],
             type: pulumi.Input[str],
             certificate: Optional[pulumi.Input[str]] = None,
             environment_variables: Optional[pulumi.Input[Sequence[pulumi.Input['ProjectEnvironmentEnvironmentVariableArgs']]]] = None,
             image_pull_credentials_type: Optional[pulumi.Input[str]] = None,
             privileged_mode: Optional[pulumi.Input[bool]] = None,
             registry_credential: Optional[pulumi.Input['ProjectEnvironmentRegistryCredentialArgs']] = None,
             opts: Optional[pulumi.ResourceOptions]=None,
             **kwargs):
        if 'computeType' in kwargs:
            compute_type = kwargs['computeType']
        if 'environmentVariables' in kwargs:
            environment_variables = kwargs['environmentVariables']
        if 'imagePullCredentialsType' in kwargs:
            image_pull_credentials_type = kwargs['imagePullCredentialsType']
        if 'privilegedMode' in kwargs:
            privileged_mode = kwargs['privilegedMode']
        if 'registryCredential' in kwargs:
            registry_credential = kwargs['registryCredential']

        ...
```

The problem is `compute_type` is a required positional argument, but in this case it's being passed as `computeType`.

We should fix `_configure` to not have any required positional args (in this case `compute_type`, `image`, and `type`).

**Comment by t0yv0** [comment]
How's it going here 🙏
