### ISSUE TITLE
Unable to implement method on a resource, call fails with "fatal: Missing <engine> addres"

### ISSUE THREAD

**Issue by david-driscoll** [pulumi/pulumi#14282]
### What happened?

I'm currently building a nodejs provider for onepassword and I'm currently unable to get the `call` method to happen.  Before it gets called, an error comes back `fatal: Missing <engine> address`  (my best guess is it's this one here https://github.com/pulumi/pulumi/blob/2dfea8fd59eddb8f4c7e0ec1ceac712e34585bff/sdk/nodejs/provider/server.ts#L489-L494)  I don't really know why it's failing, as by this point the provider has already created a few resources.

I've added a global function, that can be used instead of the resource method, but it would be great to have the resource method as well, because it makes the api very convenient!

### Example

My example code is: https://github.com/david-driscoll/pulumi-onepassword/blob/56c9e758a0e8c8a5bebd4bcfab8afe626862ddb2/examples/simple/index.ts#L134C1-L139C7

### Output of `pulumi about`

CLI          
Version      3.89.0
Go Version   go1.21.1
Go Compiler  gc

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/david-driscoll
User           david-driscoll
Organizations  david-driscoll
Token type     personal

Pulumi locates its logs in /tmp by default

### Additional context

The full error text is:

```
Error: fatal: Missing <engine> address: Error: fatal: Missing <engine> address
        at configureRuntime (/home/david/Development/pulumi-onepassword/provider/cmd/pulumi-resource-one-password-native/node_modules/@pulumi/provider/server.ts:493:15)
        at Server.<anonymous> (/home/david/Development/pulumi-onepassword/provider/cmd/pulumi-resource-one-password-native/node_modules/@pulumi/provider/server.ts:399:13)
        at Generator.next (<anonymous>)
        at /home/david/Development/pulumi-onepassword/provider/cmd/pulumi-resource-one-password-native/node_modules/@pulumi/pulumi/provider/server.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/home/david/Development/pulumi-onepassword/provider/cmd/pulumi-resource-one-password-native/node_modules/@pulumi/pulumi/provider/server.js:17:12)
        at Server.callImpl (/home/david/Development/pulumi-onepassword/provider/cmd/pulumi-resource-one-password-native/node_modules/@pulumi/pulumi/provider/server.js:356:16)
        at /home/david/Development/pulumi-onepassword/provider/cmd/pulumi-resource-one-password-native/node_modules/@pulumi/provider/server.ts:371:61
        at processTicksAndRejections (node:internal/process/task_queues:95:5)

    error: Error: call of one-password-native:index:LoginItem/attachment returned an error: fatal: Missing <engine> address
        at Object.callback (/home/david/Development/pulumi-onepassword/sdk/nodejs/node_modules/@pulumi/runtime/invoke.ts:301:45)
        at Object.onReceiveStatus (/home/david/Development/pulumi-onepassword/sdk/nodejs/node_modules/@grpc/grpc-js/src/client.ts:360:26)
        at Object.onReceiveStatus (/home/david/Development/pulumi-onepassword/sdk/nodejs/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
        at Object.onReceiveStatus (/home/david/Development/pulumi-onepassword/sdk/nodejs/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
        at /home/david/Development/pulumi-onepassword/sdk/nodejs/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@david-driscoll, I was able to get this working by modifying this script: https://github.com/david-driscoll/pulumi-onepassword/blob/56c9e758a0e8c8a5bebd4bcfab8afe626862ddb2/provider/cmd/pulumi-resource-onepassword/pulumi-resource-onepassword

It needs the `$@` to pass along the engine address arg.

```diff
 #!/bin/bash
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-node $SCRIPT_DIR/bin/index.js
+node $SCRIPT_DIR/bin/index.js $@
```

**Comment by justinvp** [comment]
@david-driscoll, closing this as it doesn't appear to be a bug in Pulumi.
