### ISSUE TITLE
Flaky CI builds

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#14292]
I've noticed the CI builds fail after PRs are added to the merge queue multiple times now.  It seems to affect mostly the windows CI build.  It's probably worth spending some time looking into what's going on there, since the CI for the merge queue already takes a while to complete, and having that flaky isn't great.

 ```
=== FAIL: . TestPackageGetSchema (re-run 1) (2.77s)
    environment.go:97: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\test-env2966114542
    smoke_test.go:243: Running command pulumi plugin ls
    smoke_test.go:249: Running command pulumi package get-schema random
    smoke_test.go:226: Running command pulumi plugin rm resource random --all --yes
    smoke_test.go:254: Running command pulumi package get-schema random@4.13.0
    smoke_test.go:258: Running command pulumi package get-schema random
    smoke_test.go:270: Running command pulumi package get-schema C:\a\pulumi\pulumi\home\plugins\resource-random-v4.13.0\pulumi-resource-random
    smoke_test.go:270: Run Error: exit status 0xffffffff
    smoke_test.go:270: STDOUT: 
    smoke_test.go:270: STDERR: error: could not find file C:\a\pulumi\pulumi\home\plugins\resource-random-v4.13.0\pulumi-resource-random
    smoke_test.go:270: Ran command pulumi args [package get-schema C:\a\pulumi\pulumi\home\plugins\resource-random-v4.13.0\pulumi-resource-random] and expected success. Instead got failure.

DONE 2 runs, 139 tests, 6 skipped, 2 failures in 653.049s
Traceback (most recent call last):
  File "C:\a\pulumi\pulumi\scripts\go-test.py", line 99, in <module>
    sp.check_call(args, shell=False)
  File "C:\hostedtoolcache\windows\Python\3.11.5\x64\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gotestsum', '--jsonfile', 'C:\\a\\pulumi\\pulumi\\test-results\\405ad520-d702-468d-b1f6-5625307fff5d.json', '--rerun-fails=1', '--packages', 'github.com/pulumi/pulumi/tests/integration/policy github.com/pulumi/pulumi/tests github.com/pulumi/pulumi/tests/examples', '--', '-count=1', '-cover', '-tags=all xplatform_acceptance', '-timeout', '1h', '-parallel=1', '-shuffle=off', '-p=1', '-race=false', '-coverprofile=C:\\a\\pulumi\\pulumi\\tests/go-test-05a35677.cov', '-coverpkg=github.com/pulumi/pulumi/pkg/v3/...,github.com/pulumi/pulumi/sdk/v3/...,github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3/...,github.com/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/v3/...,github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/v3/...']' returned non-zero exit status 1.
mingw32-make: *** [Makefile:140: gotestsum/tests] Error 1
::warning Failed after 3 attempts
```

**Comment by Frassle** [comment]
Oh that's a super interesting log text, I haven't seen this before but it looks like we're installing the provider and then failing to find it.
