### ISSUE TITLE
Pulumi 3.92.0 Throws error in `pulumi_kubernetes/helm/v3/helm.py", line 602` on upgrade.

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#14508]
### What happened?

I upgraded my library from 3.91.0 to 3.92.0 and it threw a new error. Pulumi up succeeds with pulumi 3.91.0.

```
Diagnostics:
  pulumi:pulumi:Stack (cluster-ephemeral):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 1063, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs or {}, {})
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 209, in serialize_properties
        result = await serialize_property(
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 452, in serialize_property
        value = await serialize_property(
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 435, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/output.py", line 128, in get_value
        val = await self._future
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/output.py", line 174, in run
        value = await self._future
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/output.py", line 211, in run
        return await transformed.future(with_unknowns=True)
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/output.py", line 128, in get_value
        val = await self._future
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/output.py", line 174, in run
        value = await self._future
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/output.py", line 199, in run
        transformed: Input[U] = func(value)
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi_kubernetes/helm/v3/helm.py", line 602, in invoke_helm_template
        return inv.value['result'] if inv is not None and inv.value is not None else []
    KeyError: 'result'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 197, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 137, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in wait_for_rpcs
        raise exn from cause
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 75, in wait_for_rpcs
        await rpc_manager.rpcs.pop()
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 1063, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs or {}, {})
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 209, in serialize_properties
        result = await serialize_property(
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 452, in serialize_property
        value = await serialize_property(
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 435, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/output.py", line 128, in get_value
        val = await self._future
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/output.py", line 174, in run
        value = await self._future
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/output.py", line 211, in run
        return await transformed.future(with_unknowns=True)
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/output.py", line 128, in get_value
        val = await self._future
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/output.py", line 174, in run
        value = await self._future
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi/output.py", line 199, in run
        transformed: Input[U] = func(value)
      File "/workspace/examples/cluster/venv-Linux/lib/python3.8/site-packages/pulumi_kubernetes/helm/v3/helm.py", line 602, in invoke_helm_template
        return inv.value['result'] if inv is not None and inv.value is not None else []
    KeyError: 'result'

```

### Example

Working on a repro, and gathering more info

### Output of `pulumi about`

pulumi about
CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.6.0
cloudinit   1.3.0
command     0.8.2
datadog     4.17.1
kubernetes  3.30.2
python      unknown
random      4.13.0
tls         4.10.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Looks like it's due to https://github.com/pulumi/pulumi/pull/14470, which fixed https://github.com/pulumi/pulumi/issues/13985.

**Comment by justinvp** [comment]
There were two approaches to addressing #13985:

1. Gracefully handle the possible `None` from invoke in the generated provider SDKs
2. Not returning `None` in the first place from the core SDK

#14470 went with (B) as it aligned the core Python SDK behavior with the Node.js and Go SDKs, and it wasn't going to impact invokes from generated provider SDKs.

However, it looks like `v3/helm.py` is not using the generated provider SDK to call the invoke. Instead, it has some hand-rolled code for calling an invoke which depends on the old behavior of an empty result returning `None` rather than an empty dict.

---

I see two options for addressing this issue:

1. Revert #14470 and instead fix #13985 by changing Python sdkgen to gracefully handle `None`.
2. Fix custom invokes in `pulumi-kubernetes` to handle empty dicts from invoke calls.

(1) is more involved but seems best as it makes the Python SDK behave the same as it did before, even though it means the Python SDK will behave differently from the Node.js and Go SDKs. Reverting ensures anyone else doing custom invokes and expecting `None` for an empty result will continue to work as before (this _should_ be exceedingly rare, but as we've seen there's at least one case of it being done). We'll have to fix #13985 by making the Python sdkgen gracefully handle `None`, which is a bit unfortunate, as it will add more code/complexity to the generated provider SDKs, but is necessary to fix that issue and maintain the prior behavior in the core SDK.

(2) is tempting as it's a more localized fix to make `pulumi-kubernetes` custom invoke code resilient to empty dicts, but  something else out there may be calling invoke in a custom way like this which may also be impacted in the same way, which is why (1) is preferable.

**Comment by justinvp** [comment]
So I went back and reviewed the entire history here... Interestingly, the original implementation of `invoke.py` actually did return an empty dict for empty results:

https://github.com/pulumi/pulumi/blob/828d59665e7942148ac7067907a5e52328a4c4e8/sdk/python/lib/pulumi/runtime/invoke.py#L65-L69

The behavior [changed](https://github.com/pulumi/pulumi/commit/7c5ec6815ef522f9a25b70c05aa5852abf7b7a0a#diff-79c3d17f133bdccf8462df7f09be6f46c90999bce8b4110c97e9cdd8f6e6138bL126-R129) (regressed) in #6504 which first shipped in [v2.24.0](https://github.com/pulumi/pulumi/releases/tag/v2.24.0):

```diff
-            return rpc.translate_output_properties(deserialized, lambda prop: prop, typ) if typ else deserialized
-        return {}
+            return rpc.translate_output_properties(deserialized, lambda prop: prop, typ) if typ else deserialized, None
+        return None, None
```

My guess is this was unintentional. That `return None, None` should have been `return {}, None`, but alas.

#14470 changed us back to returning empty dict, the original behavior prior to this change in v2.24.0, which is also consistent with the Node.js and Go SDKs (haven't checked the other SDKs).

**Comment by rshade** [comment]
I feel like making all of the sdk's uniform is the best long term path.

**Comment by justinvp** [comment]
We'll address this in two ways:

1. https://github.com/pulumi/pulumi-kubernetes/pull/2665: Fix the hand-rolled invoke code in the Kubernetes Python SDK to be resilient to getting either None or an empty dict for empty results. Basically, by applying the same change as a907bddce8da5141992c2c9946e2f6be3fe9f79a to Helm and YAML.
2. https://github.com/pulumi/pulumi/pull/14535: We'll add a fix in the core pulumi SDK that makes it return `None` when there are empty results and the invoke is for one of the affected kubernetes functions.
