### ISSUE TITLE
`pulumi up` panics when there's a secret in `Pulumi.yaml`

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#14521]
### What happened?

While investigating https://github.com/pulumi/pulumi-yaml/issues/518, I tried to put a secret into the config in the `Pulumi.yaml` for testing.  This resulted in a panic that seems to be unrelated to said issue.  I bisected it down to 6756c12fd031f787908795977291d6b063ca5eb3.  Before this, adding a secret there would also not work, however it would result in an error message instead of a panic.

### Example

```
name: pulumi-yaml-secret
runtime: yaml
description: A minimal Pulumi YAML program
config:
  password:
    type: string
    value:
      secure: AAABAF.... (replace this with a real secret)
outputs:
  my-secret: ${password}

```

Results in:

```
$ pulumi up
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/v-thomas-pulumi-corp/pulumi-yaml-secret/dev/previews/b30e2cd1-28f7-4abd-9ba6-f8d544d121c2




================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   3.87.1-dev.0
Go Version:       go1.20.8
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            attempt to decrypt value

goroutine 1 [running]:
runtime/debug.Stack()
	/nix/store/23wrmhyfnwjxc9cvy3lab9xj551ic53c-go-1.20.8/share/go/src/runtime/debug/stack.go:24 +0x65
main.panicHandler(0xc001a0ff47)
	/home/tgummerer/work/pulumi/3.78.0/pkg/cmd/pulumi/main.go:35 +0x47
panic({0x2044700, 0x2b12730})
	/nix/store/23wrmhyfnwjxc9cvy3lab9xj551ic53c-go-1.20.8/share/go/src/runtime/panic.go:884 +0x213
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.panicCrypter.DecryptValue(...)
	/home/tgummerer/work/pulumi/3.78.0/sdk/go/common/resource/config/crypt.go:107
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.object.decrypt({{0x2044700?, 0xc000650ac0?}, 0x0?}, {0x2b3dee0, 0xc000058108}, {0x0?, 0x0, 0x0}, {0x7f5e28413418, 0x3de7250})
	/home/tgummerer/work/pulumi/3.78.0/sdk/go/common/resource/config/object.go:93 +0xe2
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.object.Decrypt(...)
	/home/tgummerer/work/pulumi/3.78.0/sdk/go/common/resource/config/object.go:78
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.Value.Value({{0xc000fd2050?, 0xc000ff7170?}, 0x90?, 0x0?}, {0x7f5e28413418?, 0x3de7250})
	/home/tgummerer/work/pulumi/3.78.0/sdk/go/common/resource/config/value.go:55 +0xc5
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.Map.Decrypt(0xc000fd6de0?, {0x7f5e28413418, 0x3de7250})
	/home/tgummerer/work/pulumi/3.78.0/sdk/go/common/resource/config/map.go:33 +0xf5
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x3de7250, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/tgummerer/work/pulumi/3.78.0/pkg/engine/deployment.go:176 +0x1ac
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x3de7250, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/tgummerer/work/pulumi/3.78.0/pkg/engine/update.go:454 +0x391
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x2b38770, 0xc000ff7200}, 0xc000da27c0, {{0x3de7250, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, ...}, ...)
	/home/tgummerer/work/pulumi/3.78.0/pkg/engine/update.go:194 +0x4f0
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc000c70210, {0xc00005e740, 0x27}, ...}, ...)
	/home/tgummerer/work/pulumi/3.78.0/pkg/backend/httpstate/backend.go:1271 +0x84f
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc000c70210, {0xc00005e740, 0x27}, ...}, ...)
	/home/tgummerer/work/pulumi/3.78.0/pkg/backend/httpstate/backend.go:1194 +0x568
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt({_, _}, {_, _}, {_, _}, {0xc000c70210, {0xc00005e740, 0x27}, {0x0, ...}, ...}, ...)
	/home/tgummerer/work/pulumi/3.78.0/pkg/backend/apply.go:116 +0x17a
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc000c70210, {0xc00005e740, 0x27}, {0x0, ...}, ...}, ...)
	/home/tgummerer/work/pulumi/3.78.0/pkg/backend/apply.go:247 +0x13e
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Update(_, {_, _}, {_, _}, {0xc000c70210, {0xc00005e740, 0x27}, {0x0, 0x0, ...}, ...})
	/home/tgummerer/work/pulumi/3.78.0/pkg/backend/httpstate/backend.go:1020 +0xc5
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc000c70210, {0xc00005e740, 0x27}, {0x0, 0x0, 0x0}, ...})
	/home/tgummerer/work/pulumi/3.78.0/pkg/backend/stack.go:94 +0xba
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Update(_, {_, _}, {0xc000c70210, {0xc00005e740, 0x27}, {0x0, 0x0, 0x0}, 0xc00044c750, ...})
	/home/tgummerer/work/pulumi/3.78.0/pkg/backend/httpstate/stack.go:168 +0x88
main.newUpCmd.func1({_, _}, {{{0x3de7250, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/home/tgummerer/work/pulumi/3.78.0/pkg/cmd/pulumi/up.go:171 +0xd55
main.newUpCmd.func3(0x0?, {0x3de7250, 0x0, 0x0?})
	/home/tgummerer/work/pulumi/3.78.0/pkg/cmd/pulumi/up.go:492 +0xb93
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000c47800?, {0x3de7250, 0x0, 0x0})
	/home/tgummerer/work/pulumi/3.78.0/sdk/go/common/util/cmdutil/exit.go:115 +0x3e
github.com/spf13/cobra.(*Command).execute(0xc000c47800, {0x3de7250, 0x0, 0x0})
	/home/tgummerer/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000406c00)
	/home/tgummerer/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/tgummerer/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/home/tgummerer/work/pulumi/3.78.0/pkg/cmd/pulumi/main.go:56 +0x65
```

### Output of `pulumi about`

```
$ pulumi about  
CLI          
Version      3.87.1-dev.0
Go Version   go1.20.8
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host     
OS       debian
Version  12.2
Arch     x86_64

This project is written in yaml

Current Stack: v-thomas-pulumi-corp/pulumi-yaml-secret/dev

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:dev::pulumi-yaml-secret::pulumi:pulumi:Stack::pulumi-yaml-secret-dev


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/v-thomas-pulumi-corp
User           v-thomas-pulumi-corp
Organizations  v-thomas-pulumi-corp, tgummerer-test, demo, pulumi-test, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /tmp by default
```

Not sure why the version for `pulumi-yaml` says unknown, but it's version 1.3.0.

### Additional context

/cc @pgavlin 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by EvanBoyle** [comment]
@pgavlin @justinvp if this is indeed fixed as Pat suggested, can we close this out?

**Comment by pgavlin** [comment]
This is fixed.
