### ISSUE TITLE
User reports child resource's parent is missing during targeted update.

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#14531]
### What happened?

A user in community slack reports the following issue when using pulumi `v3.90.0`

```
I am unable to destroy the stack that was created with what I believe is a bug.
Now I am stuck doing a stack surgery...
I started with targeting SSM parameters because they have no dependencies (apart form a ComponentResource)
pulumi up --target '**ssm**'
everything as expected
Previewing update (myOrg/staging)

View in Browser (Ctrl+O): https://app.pulumi.com/myOrg/myProject-backend/staging/previews/<redacted>

     Type                                     Name                                            Plan       Info
 +   pulumi:pulumi:Stack                      myProject-backend-staging                         create     2 messages
 +   ├─ pulumi:providers:aws                  myProject-backend-staging-eu-central-1            create     
 +   ├─ pulumi:providers:aws                  myProject-backend-staging-us-east-1               create     
     └─ myOrg:infrastructure:aws:app-backend  myProject-backend-staging-component                          
 +      ├─ aws:ssm:Parameter                  myProject-backend-staging-app-user-password       create     
 +      ├─ aws:ssm:Parameter                  myProject-backend-staging-migrator-user-password  create     
 +      └─ aws:ssm:Parameter                  myProject-backend-staging-db-endpoint             create     


Do you want to perform this update? yes
but then during the up phase something went wrong and pulumi tried to deploy a CloudFront resource that wasn't in the preview.
Updating (myOrg/staging)

View in Browser (Ctrl+O): https://app.pulumi.com/myOrg/myProject-backend/staging/updates/1

     Type                                                  Name                                            Status                       Info
 +   pulumi:pulumi:Stack                                   myProject-backend-staging                         **creating failed (3s)**     2 errors; 2 messages
 +   ├─ pulumi:providers:aws                               myProject-backend-staging-us-east-1               created (0.22s)              
 +   ├─ pulumi:providers:aws                               myProject-backend-staging-eu-central-1            created (0.46s)              
     └─ myOrg:infrastructure:aws:app-backend               myProject-backend-staging-component                                            
 +      ├─ aws:ssm:Parameter                               myProject-backend-staging-migrator-user-password  **creating failed (1s)**     1 error
 +      ├─ aws:ssm:Parameter                               myProject-backend-staging-app-user-password       **creating failed (1s)**     1 error
        └─ myOrg:infrastructure:aws:cloudfront:CloudFront  myProject-backend-staging-cf                      **failed**                   1 error
the whole operation resulted in error and most importantly missing the component resource myOrg:infrastructure:aws:app-backend in the state
Diagnostics:
  pulumi:pulumi:Stack (myProject-backend-staging):
    Deploying image: 294336126331.dkr.ecr.eu-central-1.amazonaws.com/myProject:08279aac3466f40f38db91017ac92fcd6c048b8d
    error: update failed
    error: Error: invocation of aws:route53/getZone:getZone returned an error: error reading from server: read tcp 127.0.0.1:52645->127.0.0.1:52643: use of closed network connection
        at Object.callback (/Users/user/work/myOrg/takeables/myProject/infrastructure/node_modules/.pnpm/@pulumi+pulumi@3.91.1/node_modules/@pulumi/runtime/invoke.ts:172:37)
        at Object.onReceiveStatus (/Users/user/work/myOrg/takeables/myProject/infrastructure/node_modules/.pnpm/@grpc+grpc-js@1.9.9/node_modules/@grpc/grpc-js/src/client.ts:360:26)
        at Object.onReceiveStatus (/Users/user/work/myOrg/takeables/myProject/infrastructure/node_modules/.pnpm/@grpc+grpc-js@1.9.9/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
        at Object.onReceiveStatus (/Users/user/work/myOrg/takeables/myProject/infrastructure/node_modules/.pnpm/@grpc+grpc-js@1.9.9/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
        at /Users/user/work/myOrg/takeables/myProject/infrastructure/node_modules/.pnpm/@grpc+grpc-js@1.9.9/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)

    Using provided image

  aws:ssm:Parameter (myProject-backend-staging-app-user-password):
    error: post-step event returned an error: failed to verify snapshot: child resource urn:pulumi:staging::myProject-backend::myOrg:infrastructure:aws:app-backend$aws:ssm/parameter:Parameter::myProject-backend-staging-migrator-user-password refers to missing parent urn:pulumi:staging::myProject-backend::myOrg:infrastructure:aws:app-backend::myProject-backend-staging-component

  myOrg:infrastructure:aws:cloudfront:CloudFront (myProject-backend-staging-cf):
    error: resource complete event returned an error: failed to verify snapshot: child resource urn:pulumi:staging::myProject-backend::myOrg:infrastructure:aws:app-backend$aws:ssm/parameter:Parameter::myProject-backend-staging-migrator-user-password refers to missing parent urn:pulumi:staging::myProject-backend::myOrg:infrastructure:aws:app-backend::myProject-backend-staging-component

  aws:ssm:Parameter (myProject-backend-staging-migrator-user-password):
    error: post-step event returned an error: failed to verify snapshot: child resource urn:pulumi:staging::myProject-backend::myOrg:infrastructure:aws:app-backend$aws:ssm/parameter:Parameter::myProject-backend-staging-migrator-user-password refers to missing parent urn:pulumi:staging::myProject-backend::myOrg:infrastructure:aws:app-backend::myProject-backend-staging-component

Resources:
    + 5 created
    14 unchanged

Duration: 10s
now I cannot run even pulumi destroy due to pre-step error pre-step event returned an error: failed t ...
I was only able to destroy the resources after I manually removed the missing parent property from the stack.
As I did not dare to create the parent component manually, since "sourcePosition" was added to the state. I am now really afraid that this may have a huge impact on my next work which relies on stack surgery a lot (edited) 
```

### Example

see above

### Output of `pulumi about`

pulumi CLI v3.90.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
```
     Type                                     Name                                            Plan       Info
 +   pulumi:pulumi:Stack                      myProject-backend-staging                         create     2 messages
 +   ├─ pulumi:providers:aws                  myProject-backend-staging-eu-central-1            create     
 +   ├─ pulumi:providers:aws                  myProject-backend-staging-us-east-1               create     
     └─ myOrg:infrastructure:aws:app-backend  myProject-backend-staging-component                          
 +      ├─ aws:ssm:Parameter                  myProject-backend-staging-app-user-password       create     
 +      ├─ aws:ssm:Parameter                  myProject-backend-staging-migrator-user-password  create     
 +      └─ aws:ssm:Parameter                  myProject-backend-staging-db-endpoint             create     
```

That does not look like a targeted preview. Clearly something amiss here because of the snapshot verification issues but I haven't been able to repro this exact issue.

I have however found a more general issue that if you did try to run `up --target ssm` to create everything we should have been rejecting that deployment much earlier because the ssm resource has a dependency (parent) on a skipped create resource. I'll get a PR raised for that, and I think that probably means the issue here would be unhittable as well.
