### ISSUE TITLE
Pulumi preview: Panic: reflect: call of reflect.Value.Type on zero Value

### ISSUE THREAD

**Issue by jooooel** [pulumi/pulumi#14558]
### What happened?

Trying to run `pulumi preview`, getting the following output

```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.93.0
Go Version:       go1.21.4
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/debug/stack.go:24 +0x64
main.panicHandler(0x14000425eff)
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/cmd/pulumi/main.go:35 +0x44
panic({0x102854a00?, 0x14006268060?})
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/panic.go:914 +0x218
gopkg.in/yaml%2ev3.handleErr(0x140004221e0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:294 +0x80
panic({0x102854a00?, 0x14006268060?})
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/panic.go:914 +0x218
reflect.Value.typeSlow({0x0?, 0x0?, 0x14001bcb800?})
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/reflect/value.go:2634 +0x134
reflect.Value.Type(...)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/reflect/value.go:2629
gopkg.in/yaml%2ev3.(*decoder).unmarshal(0x140013773b0, 0x1400626f680, {0x0?, 0x0?, 0x129b8b990?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:492 +0x110
gopkg.in/yaml%2ev3.(*Decoder).Decode(0x14000422288, {0x0, 0x0})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:131 +0x1d8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).decodeValue.func1()
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/display/object_diff.go:1245 +0x314
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).decodeValue(0x1027704e0?, {0x14000db8400, 0xb7f})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/display/object_diff.go:1258 +0x4c
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPrimitivePropertyValue(0x1400626cf30, {{0x1027704e0, 0x140064f8e30}})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/display/object_diff.go:830 +0x1e4
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x1400626cf30, {{0x1027704e0, 0x140064f8e30}})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/display/object_diff.go:565 +0x890
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printDelete(0x1027704e0?, {{0x1027704e0?, 0x140064f8e30?}}, 0x14000422af8)
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/display/object_diff.go:863 +0xd4
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValueDiff(0x1028812e0?, 0x14000422af8, {{{0x1027704e0, 0x140064f8e30}}, {{0x1027704e0, 0x1042956e0}}, 0x0, 0x0})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/display/object_diff.go:796 +0x3fc
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectPropertyDiff(0x1400626ced0, {0x14005c9a884, 0x7}, 0x7, {0x1400626cdb0?, 0x1400626cde0?, 0x1400626ce10?, 0x1400626ce40?})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/display/object_diff.go:726 +0x160
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectDiff(0x1400626ced0, {0x1400626cdb0, 0x1400626cde0, 0x1400626ce10, 0x1400626ce40}, {0x0?, 0x0, 0x14005ecd6a0?})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/display/object_diff.go:715 +0x28c
github.com/pulumi/pulumi/pkg/v3/backend/display.PrintObjectDiff(0x1400626cd80, {0x1400626cdb0?, 0x1400626cde0?, 0x1400626ce10?, 0x1400626ce40?}, {0x0, 0x0, 0x0}, 0x1, 0x2, ...)
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/display/object_diff.go:689 +0x138
github.com/pulumi/pulumi/pkg/v3/backend/display.renderDiff({_, _}, {{0x101e223ff, 0x12}, {0x14006234180, 0x7b}, {0x14004e7f620, 0x2a}, 0x14005f4f5f0, 0x14005f4f680, ...}, ...)
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/display/diff.go:391 +0x1c4
github.com/pulumi/pulumi/pkg/v3/backend/display.renderDiffResourcePreEvent({{{0x101e223ff, 0x12}, {0x14006234180, 0x7b}, {0x14004e7f620, 0x2a}, 0x14005f4f5f0, 0x14005f4f680, 0x14005f4f710, {0x1400688c000, ...}, ...}, ...}, ...)
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/display/diff.go:419 +0x2bc
github.com/pulumi/pulumi/pkg/v3/backend/display.RenderDiffEvent({{0x101dfbd35?, 0x1027704e0?}, {0x102a38e60?, 0x14005f517c0?}}, 0x1029d0be0?, {{0x101dcc5de, 0x6}, 0x0, 0x0, 0x0, ...})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/display/diff.go:120 +0x3c4
github.com/pulumi/pulumi/pkg/v3/backend.createDiff({0x14000580000?, 0x14000423dc8?}, {0x14005bac000, 0x7a, 0x100691db0?}, {{0x101dcc5de, 0x6}, 0x0, 0x0, 0x0, ...})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/apply.go:322 +0x14c
github.com/pulumi/pulumi/pkg/v3/backend.confirmBeforeUpdating({_, _}, {_, _}, {_, _, _}, _, {{{0x104292280, 0x0, ...}, ...}, ...})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/apply.go:224 +0x4fc
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt({_, _}, {_, _}, {_, _}, {0x14001cba210, {0x14001ba7c70, 0x5f}, {0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/apply.go:161 +0x488
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0x14001cba210, {0x14001ba7c70, 0x5f}, {0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/apply.go:247 +0xbc
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).Update(_, {_, _}, {_, _}, {0x14001cba210, {0x14001ba7c70, 0x5f}, {0x0, 0x0, ...}, ...})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/filestate/backend.go:910 +0x16c
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0x14001cba210, {0x14001ba7c70, 0x5f}, {0x0, 0x0, 0x0}, ...})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/stack.go:94 +0x88
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localStack).Update(_, {_, _}, {0x14001cba210, {0x14001ba7c70, 0x5f}, {0x0, 0x0, 0x0}, 0x14002401e30, ...})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/backend/filestate/stack.go:89 +0x64
main.newUpCmd.func1({_, _}, {{{0x104292280, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/cmd/pulumi/up.go:182 +0xac4
main.newUpCmd.func3(0x0?, {0x104292280, 0x0, 0x0?})
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/cmd/pulumi/up.go:513 +0x7cc
main.newUpCmd.RunResultFunc.func4(0x14001a6ca00?, {0x104292280, 0x0, 0x0})
	/private/tmp/pulumi-20231110-3852-199s6j9/sdk/go/common/util/cmdutil/exit.go:115 +0x34
github.com/spf13/cobra.(*Command).execute(0x14001a70300, {0x104292280, 0x0, 0x0})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x14001294900)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/private/tmp/pulumi-20231110-3852-199s6j9/pkg/cmd/pulumi/main.go:56 +0x54
```

### Example

Not sure how to reproduce this bug actually... But I think it's related to trying to diff a `github:index:RepositoryFile` resource.

### Output of `pulumi about`

```
CLI
Version      3.93.0
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME          VERSION
akamai        6.3.1
azure-native  2.16.0
azure-native  2.12.0
azure-native  2.12.0
azure-native  2.12.0
azure-native  2.11.0
azure-native  2.10.0
azure-native  2.10.0
azure-native  2.10.0
azure-native  2.10.0
github        5.21.0
go            unknown
random        4.13.2

Host
OS       darwin
Version  13.5.2
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.21.3 darwin/arm64'

Dependencies:
NAME                                                                                  VERSION
github.com/Azure/azure-sdk-for-go/sdk/azidentity                                      1.0.0
github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/authorization/armauthorization  1.0.0
github.com/MakeNowJust/heredoc                                                        1.0.0
github.com/pulumi/pulumi-akamai/sdk/v6                                                6.3.1
github.com/pulumi/pulumi-azure-native-sdk/authorization/v2                            2.10.0
github.com/pulumi/pulumi-azure-native-sdk/containerservice/v2                         2.12.0
github.com/pulumi/pulumi-azure-native-sdk/documentdb/v2                               2.10.0
github.com/pulumi/pulumi-azure-native-sdk/managedidentity/v2                          2.12.0
github.com/pulumi/pulumi-azure-native-sdk/network/v2                                  2.10.0
github.com/pulumi/pulumi-azure-native-sdk/resources/v2                                2.10.0
github.com/pulumi/pulumi-azure-native-sdk/servicebus/v2                               2.12.0
github.com/pulumi/pulumi-azure-native-sdk/storage/v2                                  2.11.0
github.com/pulumi/pulumi-github/sdk/v5                                                5.21.0
github.com/pulumi/pulumi-random/sdk/v4                                                4.13.2
github.com/pulumi/pulumi/sdk/v3                                                       3.92.0
github.com/stretchr/testify                                                           1.8.4

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jooooel** [comment]
I realized why I got the error, but not what's causing it.

I had an older version of GitHub CLI, so when I ran this locally, `LookupRepositoryFile` in the GitHub provider would return a `LookupFileRepositoryResult` with all the properties set to their zero values (empty strings etc).
