### ISSUE TITLE
`pulumi stack change-secrets-provider default` - panics when trying to replace passphrase

### ISSUE THREAD

**Issue by blaargh** [pulumi/pulumi#14570]
### What happened?

When tyring to change the secrets provider of the stack to default, a panic occurs. The stack was imported from a local backend (S3) into the Cloud version (Self-hosted)

`Panic:            fatal: A failure has occurred: unexpected plaintext of type <nil>`

Stacktrace:

```
Migrating old configuration and state to new secrets provider
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.94.0
Go Version:       go1.21.4
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            fatal: A failure has occurred: unexpected plaintext of type <nil>

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/debug/stack.go:24 +0x64
main.panicHandler(0x14001abfeff)
	/private/tmp/pulumi-20231114-4101-1han7fp/pkg/cmd/pulumi/main.go:35 +0x44
panic({0x1033985a0?, 0x14001e83fb0?})
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/panic.go:914 +0x218
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20231114-4101-1han7fp/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf({0x102a861ce?, 0x100d04c80?}, {0x14001abf348?, 0x100cfcbc8?, 0x4?})
	/private/tmp/pulumi-20231114-4101-1han7fp/sdk/go/common/util/contract/fail.go:32 +0xbc
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.Plaintext.encrypt({{0x0?, 0x0?}, 0xb8?}, {0x10390df38?, 0x104eba280?}, {0x14001b5d1a0?, 0x0?, 0x14001ea6750?}, {0x1038e7be0?, 0x14001ea63f0?})
	/private/tmp/pulumi-20231114-4101-1han7fp/sdk/go/common/resource/config/plaintext.go:156 +0x388
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.Plaintext.encrypt({{0x1034ab280?, 0x14001ea6720?}, 0xb8?}, {0x10390df38, 0x104eba280}, {0x14001e83f70?, 0x1, 0x1}, {0x1038e7be0, 0x14001ea63f0})
	/private/tmp/pulumi-20231114-4101-1han7fp/sdk/go/common/resource/config/plaintext.go:148 +0x49c
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.Plaintext.encrypt({{0x1034ab280?, 0x14001ea66f0?}, 0x20?}, {0x10390df38, 0x104eba280}, {0x0?, 0x0, 0x0}, {0x1038e7be0, 0x14001ea63f0})
	/private/tmp/pulumi-20231114-4101-1han7fp/sdk/go/common/resource/config/plaintext.go:148 +0x49c
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.Plaintext.Encrypt({{0x1034ab280?, 0x14001ea66f0?}, 0xc0?}, {0x10390df38?, 0x104eba280?}, {0x1038e7be0?, 0x14001ea63f0?})
	/private/tmp/pulumi-20231114-4101-1han7fp/sdk/go/common/resource/config/plaintext.go:110 +0x48
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.Value.Copy({{0x14001b65600?, 0x100cfd00c?}, 0xf0?, 0x63?}, {0x12c7cb458, 0x104eba280}, {0x1038e7be0, 0x14001ea63f0})
	/private/tmp/pulumi-20231114-4101-1han7fp/sdk/go/common/resource/config/value.go:91 +0xa4
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.Map.Copy(0x14001b6f890?, {0x12c7cb458, 0x104eba280}, {0x1038e7be0, 0x14001ea63f0})
	/private/tmp/pulumi-20231114-4101-1han7fp/sdk/go/common/resource/config/map.go:45 +0xc4
main.migrateOldConfigAndCheckpointToNewSecretsProvider({0x10390dde8, 0x104eba280}, 0x102adecd7?, {0x1039255f0, 0x14000c7ca10}, 0x14001e21020, {0x12c7cb458, 0x104eba280})
	/private/tmp/pulumi-20231114-4101-1han7fp/pkg/cmd/pulumi/stack_change_secrets_provider.go:165 +0xc4
main.(*stackChangeSecretsProviderCmd).Run(0x14001b83880, {0x10390dde8, 0x104eba280}, {0x14001bc5e40, 0x1, 0x0?})
	/private/tmp/pulumi-20231114-4101-1han7fp/pkg/cmd/pulumi/stack_change_secrets_provider.go:135 +0x340
main.newStackChangeSecretsProviderCmd.func1(0x0?, {0x14001bc5e40, 0x1, 0x1})
	/private/tmp/pulumi-20231114-4101-1han7fp/pkg/cmd/pulumi/stack_change_secrets_provider.go:67 +0x4c
main.newStackChangeSecretsProviderCmd.RunFunc.func2(0x0?, {0x14001bc5e40?, 0x0?, 0x0?})
	/private/tmp/pulumi-20231114-4101-1han7fp/sdk/go/common/util/cmdutil/exit.go:99 +0x28
main.newStackChangeSecretsProviderCmd.RunFunc.RunResultFunc.func5(0x14001c72200?, {0x14001bc5e40, 0x1, 0x1})
	/private/tmp/pulumi-20231114-4101-1han7fp/sdk/go/common/util/cmdutil/exit.go:115 +0x34
github.com/spf13/cobra.(*Command).execute(0x14001bd5800, {0x14001bc5e10, 0x1, 0x1})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x14001342900)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/private/tmp/pulumi-20231114-4101-1han7fp/pkg/cmd/pulumi/main.go:56 +0x54
```

### Example

1. Initialize a stack with a local backend
2. Set passphrase
3. Export Stack
4. Import Stack in Cloud backend
5. `pulumi stack change-secrets-provider default`

### Output of `pulumi about`

CLI          
Version      3.94.0
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME  VERSION
aws   6.0.2
go    unknown

Host     
OS       darwin
Version  14.1.1
Arch     arm64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.21.4 darwin/amd64'

Current Stack: <stackName>

Found no resources associated with <stackName>

Found no pending operations associated with <stackName

Backend        
Name           https://api-url.io
URL            
User           <username>
Organizations  <organizations>
Token type     personal

Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-aws/sdk/v6  6.0.2
github.com/pulumi/pulumi/sdk/v3      3.79.0
gopkg.in/yaml.v2                     2.4.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
Thanks for the report!  I believe we have a fix for this in progress already in https://github.com/pulumi/pulumi/pull/14562/files/6d3e963784acc7200d9482932f2eb80918e1ebf6#diff-eeb776a4baf6103db61841a29fcf7e6604756b3442669a7ee85537c9a6b05920R155-R156.

Note that even after that fix `change-secrets-provider` will not work as there's most likely an invalid (empty) secret somewhere in your stack that will need to be fixed.  Look out for something like

```
  dev:password:
    secure: null
```

in your `Pulumi.<stack>.yaml`, where the secure value is `null` or empty or similar.

**Comment by blaargh** [comment]
Thank you! Glad it's already fixed. My stack yaml is actually pretty small. All I have left in regards to secrets is the `encryptionSalt` with the respective value. Executing `change-secrets-provider` (even when panicking) would remove this line.

**Comment by tgummerer** [comment]
I'm going to close this since https://github.com/pulumi/pulumi/pull/14562 was merged, so we should no longer panic here.

**Comment by blaargh** [comment]
Thanks! I was able to change the secrets provider without issues after updating to the newest release :)
