### ISSUE TITLE
Getting a panic after upgrading from `3.88.1` to `3.94.1`

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#14598]
### What happened?

Hi

just upgraded from Pulumi version 3.88.1 to 3.94.1, and am now seeing the following error when trying to preview some stacks:

```
panic: fatal: A failure has occurred: unknown event type 'policy-load'
```

The word `policy-load` appears to be related to changes introduced in https://github.com/pulumi/pulumi/pull/14493

Here is the full panic when running `pulumi preview`.

```
panic: fatal: A failure has occurred: unknown event type 'policy-load'

goroutine 31 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20231116-4266-1mxjdrm/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf({0x1044977fd?, 0xb?}, {0x14000cb15d0?, 0x10272e024?, 0x107144a68?})
	/private/tmp/pulumi-20231116-4266-1mxjdrm/sdk/go/common/util/contract/fail.go:32 +0xbc
github.com/pulumi/pulumi/pkg/v3/backend/display.RenderDiffEvent({{0x10444b37c?, 0x14000caaaf8?}, {0x104f08e20?, 0x1068f2260?}}, 0x14001d47100?, {{0x104424256, 0x5}, 0x0, 0x0, 0x0, ...})
	/private/tmp/pulumi-20231116-4266-1mxjdrm/pkg/backend/display/diff.go:129 +0x728
github.com/pulumi/pulumi/pkg/v3/backend/display.ShowDiffEvents({0x1400148e750, 0x11}, 0x14001dab020, 0x14001dab080, {{0x104424256, 0x5}, 0x0, 0x0, 0x0, 0x0, ...})
	/private/tmp/pulumi-20231116-4266-1mxjdrm/pkg/backend/display/diff.go:85 +0x4a8
github.com/pulumi/pulumi/pkg/v3/backend/display.ShowEvents({0x1400148e750, 0x11}, {0x10442d95b, 0x7}, {{0x14001bd0c80?, 0x7?}}, {0x14001bd0f90, 0x10}, {0x14001dfe000, 0x61}, ...)
	/private/tmp/pulumi-20231116-4266-1mxjdrm/pkg/backend/display/display.go:87 +0x1f8
created by github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudUpdate).RecordAndDisplayEvents in goroutine 15
	/private/tmp/pulumi-20231116-4266-1mxjdrm/pkg/backend/httpstate/state.go:131 +0x290

```

### Example

Running `pulumi preview` on multiple stacks seems to trigger this problem.

### Output of `pulumi about`

```
CLI          
Version      3.94.1
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  14.0
Arch     arm64

This project is written in nodejs: executable='/Users/redacted/.nvm/versions/node/v18.17.0/bin/node' version='v18.17.0'

Current Stack: xxxxxxxxxx/date-eks-cluster/dev

TYPE                                                        URN
pulumi:pulumi:Stack                                         urn:pulumi:dev::date-eks-cluster::pulumi:pulumi:Stack::date-eks-cluster-dev
pulumi:providers:aws                                        urn:pulumi:dev::date-eks-cluster::pulumi:providers:aws::default_5_42_0
vpc                                                         urn:pulumi:dev::date-eks-cluster::vpc::us-east-1-dev-date
aws:ec2/vpc:Vpc                                             urn:pulumi:dev::date-eks-cluster::vpc$aws:ec2/vpc:Vpc::us-east-1-dev-date
aws:ec2/routeTable:RouteTable                               urn:pulumi:dev::date-eks-cluster::vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable::us-east-1-dev-date-private-us-east-1a
aws:ec2/subnet:Subnet                                       urn:pulumi:dev::date-eks-cluster::vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::us-east-1-dev-date-private-us-east-1f
[... // content removed //...]
kubernetes:helm.sh/v3:Release                               urn:pulumi:dev::date-eks-cluster::k8s-datadog$kubernetes:helm.sh/v3:Release::datadog


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/xxxxxxxxxxx
User           xxxxxxxxxxx
Organizations  xxxxxxxxxxx, xxxxxxxxxxx
Token type     personal

Pulumi locates its logs in /var/folders/7m/bwx6v5vs4nd006n02xmpsl680000gq/T/ by default

```

### Additional context

If needed, we have a stack state as a json.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
My kingdom for type safe discriminate unions :(
