### ISSUE TITLE
panic: sync/atomic: store of inconsistently typed value into Value

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#14611]
### What happened?

```
panic: sync/atomic: store of inconsistently typed value into Value


  aws:kms:Key (key-701):
    error: 1 error occurred:
        * No valid credential sources found: Please see https://registry.terraform.io/providers/hashicorp/aws
    for more information about providing credentials.

    Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, access disabled to EC2 IMDS via client option, or "AWS_EC2_METADATA_DISABLED" environment variable

  aws:kms:Key (key-382):
    error: 1 error occurred:
        * No valid credential sources found: Please see https://registry.terraform.io/providers/hashicorp/aws
    for more information about providing credentials.

    Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, access disabled to EC2 IMDS via client option, or "AWS_EC2_METADATA_DISABLED" environment variable

  aws:kms:Key (key-536):
    error: 1 error occurred:
        * No valid credential sources found: Please see https://registry.terraform.io/providers/hashicorp/aws
    for more information about providing credentials.

    Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, access disabled to EC2 IMDS via client option, or "AWS_EC2_METADATA_DISABLED" environment variable

Resources:

Duration: 5m35s

panic: sync/atomic: store of inconsistently typed value into Value

goroutine 2934 [running]:
sync/atomic.(*Value).Store(0xc0037ecfe8, {0x32b3520, 0xc002ad00c0})
        /opt/hostedtoolcache/go/1.21.3/x64/src/sync/atomic/value.go:78 +0xd5
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).cancelDueToError(0xc0037ecf00, {0x3e8b4c0?, 0xc002ad00c0?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:308 +0x37
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc0037ecf00, 0x0?, {0xc003a1b960?, 0x1, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:290 +0x245
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1()
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:490 +0xc8
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker in goroutine 2239
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:487 +0x2a5
panic: sync/atomic: store of inconsistently typed value into Value

goroutine 2762 [running]:
sync/atomic.(*Value).Store(0xc0037ecfe8, {0x32b3520, 0xc0057c6000})
        /opt/hostedtoolcache/go/1.21.3/x64/src/sync/atomic/value.go:78 +0xd5
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).cancelDueToError(0xc0037ecf00, {0x3e8b4c0?, 0xc0057c6000?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:308 +0x37
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc0037ecf00, 0x0?, {0xc004f9e640?, 0x1, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:290 +0x245
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1()
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:490 +0xc8
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker in goroutine 2239
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:487 +0x2a5
```

### Example

```python

"""An AWS Python Pulumi program"""

import pulumi
import pulumi_aws as aws

prov = aws.Provider('prov',
                    region='us-east-1',
                    skip_credentials_validation=False,
                    skip_region_validation=True,
                    skip_metadata_api_check=True,
                    opts=pulumi.ResourceOptions(version='6.8.0'))


me = aws.get_caller_identity(opts=pulumi.InvokeOptions(provider=prov))

var = {'s3_bucket_name': 'mybucket'}

example_policy_document = aws.iam.get_policy_document(statements=[
    aws.iam.GetPolicyDocumentStatementArgs(
        sid="1",
        actions=[
            "s3:ListAllMyBuckets",
            "s3:GetBucketLocation",
        ],
        resources=["arn:aws:s3:::*"],
    ),
    aws.iam.GetPolicyDocumentStatementArgs(
        actions=["s3:ListBucket"],
        resources=[f"arn:aws:s3:::mybucket"],
        conditions=[aws.iam.GetPolicyDocumentStatementConditionArgs(
            test="StringLike",
            variable="s3:prefix",
            values=[
                "",
                "home/",
                "home/&{aws:username}/",
            ],
        )],
    ),
    aws.iam.GetPolicyDocumentStatementArgs(
        actions=["s3:*"],
        resources=[
            f"arn:aws:s3:::{var['s3_bucket_name']}/home/&{{aws:username}}",
            f"arn:aws:s3:::{var['s3_bucket_name']}/home/&{{aws:username}}/*",
        ],
    )
], opts=pulumi.InvokeOptions(provider=prov))


for i in range(0, 1000):
    aws.kms.Key(f"key-{i}",
                deletion_window_in_days=7,
                description=f"KMS key {i}")


pulumi.export('me', me)
pulumi.export('doc', example_policy_document)
```

### Output of `pulumi about`

Version      3.92.0
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
python  unknown

Host
OS       darwin
Version  14.0
Arch     x86_64

This project is written in python: executable='/Users/t0yv0/bin/python3' version='3.10.13'

Current Stack: t0yv0/repro-aws-lbriggs/dev

TYPE                  URN
pulumi:pulumi:Stack   urn:pulumi:dev::repro-aws-lbriggs::pulumi:pulumi:Stack::repro-aws-lbriggs-dev
pulumi:providers:aws  urn:pulumi:dev::repro-aws-lbriggs::pulumi:providers:aws::prov
pulumi:providers:aws  urn:pulumi:dev::repro-aws-lbriggs::pulumi:providers:aws::default_6_8_0
aws:kms/key:Key       urn:pulumi:dev::repro-aws-lbriggs::aws:kms/key:Key::key-1
aws:kms/key:Key       urn:pulumi:dev::repro-aws-lbriggs::aws:kms/key:Key::key-997
aws:kms/key:Key       urn:pulumi:dev::repro-aws-lbriggs::aws:kms/key:Key::key-998
aws:kms/key:Key       urn:pulumi:dev::repro-aws-lbriggs::aws:kms/key:Key::key-999

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi
Token type     personal

Dependencies:
NAME        VERSION
pip         23.3.1
pulumi-aws  5.42.0
setuptools  68.2.2
wheel       0.41.3

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default

When interrupting `pulumi destroy` of 1000 KMS keys and hitting Ctrl+C a few times I go the following panic.

### Additional context

Perform pulumi destroy of 1000 buckets and interrupt it with Ctrl+C Ctrl+C.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
We only ever store `error`s in this value, but evidently different specific implementations of that. 
I've got a fix to just remove the `sync.Value` and use our new promise type instead which can handle this.
