### ISSUE TITLE
Stability issues with `pulumi convert` block deploying it in provider builds

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#14718]
### What happened?

I have been trying to isolate non-deterministic behavior of pulumi convert in `make tfgen` in pulumi azuread. Generally it looks like something around plugin acquisition is unstable. This unstable behavior makes it very hard to work with in provider builds, and I'd like to fix the issue before proceeding with deployment.

I've been able to isolate a script  that behaves as follows. The results are different each time, including a panic.

```
t0yv0@Antons-MacBook-Pro> bash repro.sh                                                                                                                                                                                          ~/code/pulumi-azuread/repro
MD5 (azuread.json) = 3dd58ed67af0aef966bfc291584c9d36
MD5 (examples.json) = a643fa1043ca9ab1204ecb5a5221d163
Converting from terraform...
Converting to pcl...
MD5 (/dev/fd/63) = e8a06e6643b47a8d2ac823978aab9c93
t0yv0@Antons-MacBook-Pro> bash repro.sh                                                                                                                                                                                          ~/code/pulumi-azuread/repro
MD5 (azuread.json) = 3dd58ed67af0aef966bfc291584c9d36
MD5 (examples.json) = a643fa1043ca9ab1204ecb5a5221d163
Converting from terraform...
Converting to pcl...
MD5 (/dev/fd/63) = 16a1f442e4ee564a50522c47ef2c379b
t0yv0@Antons-MacBook-Pro> bash repro.sh                                                                                                                                                                                          ~/code/pulumi-azuread/repro
MD5 (azuread.json) = 3dd58ed67af0aef966bfc291584c9d36
MD5 (examples.json) = a643fa1043ca9ab1204ecb5a5221d163
Converting from terraform...
panic: runtime error: index out of range [0] with length 0

goroutine 252 [running]:
github.com/pulumi/pulumi/pkg/v3/codegen/convert.(*pluginMapper).GetMapping(0xc001599400, {0x37388de?, 0x34ed260?}, {0xc00295a640, 0x6}, {0xc00295a646, 0x6})
        /home/runner/work/pulumi/pulumi/pkg/codegen/convert/plugin_mapper.go:347 +0x105b
github.com/pulumi/pulumi/pkg/v3/codegen/convert.(*mapperServer).GetMapping(0xc0015061e0, {0x3eb1e50, 0xc002885020}, 0xc001592c80)
        /home/runner/work/pulumi/pulumi/pkg/codegen/convert/mapper_server.go:42 +0x14f
github.com/pulumi/pulumi/sdk/v3/proto/go/codegen._Mapper_GetMapping_Handler.func1({0x3eb1e50, 0xc002885020}, {0x3484de0?, 0xc001592c80})
        /home/runner/work/pulumi/pulumi/sdk/proto/go/codegen/mapper_grpc.pb.go:88 +0x72
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x3eb1e50, 0xc002884fc0}, {0x3484de0, 0xc001592c80}, 0xc002932ee0, 0xc0029638d8)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3d0
github.com/pulumi/pulumi/sdk/v3/proto/go/codegen._Mapper_GetMapping_Handler({0x32b7d20?, 0xc0015061e0}, {0x3eb1e50, 0xc002884fc0}, 0xc000a56850, 0xc001506220)
        /home/runner/work/pulumi/pulumi/sdk/proto/go/codegen/mapper_grpc.pb.go:90 +0x135
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001a88000, {0x3ec27e0, 0xc0001029c0}, 0xc00255bb00, 0xc0015f2db0, 0x543e130, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.1/server.go:1358 +0xe15
google.golang.org/grpc.(*Server).handleStream(0xc001a88000, {0x3ec27e0, 0xc0001029c0}, 0xc00255bb00, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.1/server.go:1735 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.1/server.go:970 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 32
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.1/server.go:981 +0x145
```

This translates to some weird diffs in examples.

```
- import com.pulumi.random.uuid;
+ import com.pulumi.random.RandomUuid;

- example_administrator = random.index.Uuid("example_administrator")
+ example_administrator = random.RandomUuid("example_administrator")
```

I also sporadically get a warning:

```
[2] t0yv0@Antons-MacBook-Pro> bash repro.sh                                                                                                                                                                                      ~/code/pulumi-azuread/repro
MD5 (azuread.json) = 3dd58ed67af0aef966bfc291584c9d36
MD5 (examples.json) = a643fa1043ca9ab1204ecb5a5221d163
Converting from terraform...
warning: resource plugin time is expected to have version >=4.14.0, but has 0.0.16; the wrong version may be on your path, or this may be a bug in the plugin
Converting to pcl...
MD5 (/dev/fd/63) = d486afcf238cca283885fff57b495d35
```

repro.sh is as follows:

```bash

#!/usr/bin/env bash

set -euo pipefail

md5 azuread.json
md5 examples.json

export GITHUB_TOKEN="$(gh auth token)"
export PULUMI_DISABLE_AUTOMATIC_PLUGIN_ACQUISITION=true

pulumi convert --from terraform --language pcl --out ./out --generate-only --mappings azuread.json -- --convert-examples examples.json

md5 <(jq . --sort-keys out/examples.json)
```

### Example

https://gist.github.com/t0yv0/87805fe96709912a37c4cfd85d0c129f 

### Output of `pulumi about`

```$ pulumi version
v3.92.0

$ pulumi plugin ls
NAME       KIND       VERSION  SIZE    INSTALLED       LAST USED
azure      resource   5.52.0   404 MB  1 hour ago      1 hour ago
random     resource   4.14.0   37 MB   1 hour ago      1 hour ago
std        resource   1.4.0    26 MB   1 hour ago      1 hour ago
terraform  converter  1.0.11   45 MB   1 hour ago      1 hour ago
time       resource   0.0.16   38 MB   36 minutes ago  36 minutes ago
time       resource   0.0.15   35 MB   1 hour ago      1 hour ago

TOTAL plugin cache size: 584 MB
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
```
bash repro.sh                                                                                                                                                  ~/tmp/2023/12/gist-azuread-convert/87805fe96709912a37c4cfd85d0c129f
MD5 (azuread.json) = 3dd58ed67af0aef966bfc291584c9d36
MD5 (examples.json) = a643fa1043ca9ab1204ecb5a5221d163
Converting from terraform...
Converting to pcl...
MD5 (/dev/fd/63) = 035f8e6c396f541a3709263a4c54e996
t0yv0@Antons-MacBook-Pro> bash repro.sh                                                                                                                                                  ~/tmp/2023/12/gist-azuread-convert/87805fe96709912a37c4cfd85d0c129f
MD5 (azuread.json) = 3dd58ed67af0aef966bfc291584c9d36
MD5 (examples.json) = a643fa1043ca9ab1204ecb5a5221d163
Converting from terraform...
Converting to pcl...
MD5 (/dev/fd/63) = 035f8e6c396f541a3709263a4c54e996
t0yv0@Antons-MacBook-Pro> bash repro.sh                                                                                                                                                  ~/tmp/2023/12/gist-azuread-convert/87805fe96709912a37c4cfd85d0c129f
MD5 (azuread.json) = 3dd58ed67af0aef966bfc291584c9d36
MD5 (examples.json) = a643fa1043ca9ab1204ecb5a5221d163
Converting from terraform...
Converting to pcl...
MD5 (/dev/fd/63) = 035f8e6c396f541a3709263a4c54e996
t0yv0@Antons-MacBook-Pro> bash repro.sh                                                                                                                                                  ~/tmp/2023/12/gist-azuread-convert/87805fe96709912a37c4cfd85d0c129f
MD5 (azuread.json) = 3dd58ed67af0aef966bfc291584c9d36
MD5 (examples.json) = a643fa1043ca9ab1204ecb5a5221d163
Converting from terraform...
Converting to pcl...
MD5 (/dev/fd/63) = 035f8e6c396f541a3709263a4c54e996
```

**Comment by t0yv0** [comment]
This looks pretty solid on v3.97.0. Thank you!
