### ISSUE TITLE
Panic importing a stack that was exported from another backend

### ISSUE THREAD

**Issue by alexcaraffi** [pulumi/pulumi#14761]
### What happened?

I have deployed a stack on my AWS account while I was logged into Pulumi Cloud (I can see the state of the stack in my online dashboard). I exported the stack output with the command `pulumi stack export --file pulumiStackStatus` and here everything it's ok. Then i logged out, I logged in using a S3 bucket, I create a new stack and then I run the command `pulumi stack import --file pulumiStackStatus` and i got the error:

```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.95.0
Go Version:       go1.21.4
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            attempt to decrypt value

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/debug/stack.go:24 +0x64
main.panicHandler(0x14001e1feff)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:35 +0x44
panic({0x10682dd80?, 0x106d808a0?})
        /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x218
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.panicCrypter.DecryptValue(...)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/crypt.go:107
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializePropertyValue({0x10693d5a0?, 0x14001372210?}, {0x12fcb0118?, 0x10835a820?}, {0x12fcb0140, 0x10835a820})
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:623 +0x7fc
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeProperties(0x0?, {0x12fcb0118, 0x10835a820}, {0x12fcb0140, 0x10835a820})
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:548 +0xac
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeResource({{0x14000dcab40, 0x3c}, 0x1, 0x0, {0x14001edb1e8, 0x15}, {0x14000db1290, 0xf}, 0x140013721b0, 0x14001372240, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:503 +0x4c
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeDeploymentV3({0x106dad608, 0x10835a820}, {{{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:276 +0x2e0
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeUntypedDeployment({0x106dad608, 0x10835a820}, 0x1400132a480?, {0x106d86a20, 0x10835a820})
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:210 +0xa8
main.newStackImportCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/stack_import.go:82 +0x198
main.newStackImportCmd.RunFunc.func2(0x0?, {0x14001c5e360?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x28
main.newStackImportCmd.RunFunc.RunResultFunc.func5(0x14000254e00?, {0x14001c5e360, 0x0, 0x2})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:115 +0x34
github.com/spf13/cobra.(*Command).execute(0x140017f5b00, {0x14001c5e340, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x14001d9c000)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:56 +0x54
```

### Example

```
pulumi stack export --file pulumiStackStatus
pulumi logout
pulumi login s3://pulumi-global-address-space-script-status
pulumi stack init nuovo
pulumi stack select nuovo
pulumi stack import --file pulumiStackStatus.json
```

### Output of `pulumi about`

```
CLI          
Version      3.95.0
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  14.1.2
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v20.5.1'

Backend        
Name           Air-di-Alex.homenet.telecomitalia.it
URL            s3://pulumi-global-address-space-script-status/pulumiStackStatus.json
User           alexcaraffi
Organizations  
Token type     personal

Pulumi locates its logs in /var/folders/wv/243bqwkj0jdcb9hct_2s2h900000gn/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: failed to run "/opt/homebrew/bin/npm ls --json --depth=0": exit status 1
warning: Failed to get information about the current stack: No current snapshot

```

### Additional context

Here is the error:

```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.95.0
Go Version:       go1.21.4
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            attempt to decrypt value

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/debug/stack.go:24 +0x64
main.panicHandler(0x14001b5beff)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:35 +0x44
panic({0x10741dd80?, 0x1079708a0?})
        /opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x218
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.panicCrypter.DecryptValue(...)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/crypt.go:107
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializePropertyValue({0x10752d5a0?, 0x14001ce12f0?}, {0x110b142a0?, 0x108f4a820?}, {0x110b142c8, 0x108f4a820})
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:623 +0x7fc
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeProperties(0x0?, {0x110b142a0, 0x108f4a820}, {0x110b142c8, 0x108f4a820})
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:548 +0xac
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeResource({{0x140016ec780, 0x3c}, 0x1, 0x0, {0x14001ad6e40, 0x15}, {0x14001ceb400, 0xf}, 0x14001ce1290, 0x14001ce1320, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:503 +0x4c
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeDeploymentV3({0x10799d608, 0x108f4a820}, {{{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:276 +0x2e0
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeUntypedDeployment({0x10799d608, 0x108f4a820}, 0x140014c0480?, {0x107976a20, 0x108f4a820})
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:210 +0xa8
main.newStackImportCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/stack_import.go:82 +0x198
main.newStackImportCmd.RunFunc.func2(0x0?, {0x14001459200?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x28
main.newStackImportCmd.RunFunc.RunResultFunc.func5(0x14001558a00?, {0x14001459200, 0x0, 0x2})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:115 +0x34
github.com/spf13/cobra.(*Command).execute(0x14001517200, {0x140014591e0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x14000241b00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:56 +0x54
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
@alexcaraffi I'm looking into a similar issue (#15547), and I'm a bit puzzled how we ended up in this state in the first place.  If you still have this stack around, I'd be really interested in the output of 

```
pulumi stack export | jq .version
pulumi stack export | jq .deployment.secrets_providers
```

(feel free to redact any sensitive values here).  

I'm also curious if there is any ciphertext in the state (I assume it would have to be), so the output of 
```
pulumi stack export | grep ciphertext | wc -l
```
would be helpful as well.

**Comment by tgummerer** [comment]
I'm going to close this out, since the panic has been fixed (it will now error out, because we still don't know how to construct a proper secret manager in this situation).  Feel free to reopen this with the information requested above if this is still an issue for you.
