### ISSUE TITLE
enabling tracing with python policy packs breaks

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#14816]
### What happened?

I had some policy packs (one written in python) enabled on a project, and wanted to try running `pulumi preview` with tracing enabled.  This resulted in an error, saying the policy pack could not be read.

### Example

Set up tracing with jaeger as described in [this guide](https://www.pulumi.com/docs/support/troubleshooting/#tracing).  Then run `pulumi preview` with a policy pack.  e.g.

```
pulumi preview --policy-pack ~/test/policy-test/python-starter --tracing http://localhost:9411/api/v1/spans       
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/v-thomas-pulumi-corp/pulumi-test-yaml/dev/previews/9c25f0d3-a256-4a00-a505-7bacd0b2cc08

Loading policy packs...

     Type                 Name                  Plan     Info
     pulumi:pulumi:Stack  pulumi-test-yaml-dev           7 messages

Diagnostics:
  pulumi:pulumi:Stack (pulumi-test-yaml-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/tgummerer/test/policy-test/python-starter/venv/lib/python3.11/site-packages/pulumi/policy/__main__.py", line 61, in main
        runpy.run_path(program, run_name="__main__")
      File "<frozen runpy>", line 290, in run_path
      File "<frozen runpy>", line 254, in _get_code_from_file
    FileNotFoundError: [Errno 2] No such file or directory: '/home/tgummerer/test/policy-test/python-starter/http:/localhost:9411/api/v1/spans'

error: policy pack "/home/tgummerer/test/policy-test/python-starter" failed to start: could not read plugin [/home/tgummerer/go/bin/pulumi-analyzer-policy-python] stdout: EOF
```

### Output of `pulumi about`

```
CLI          
Version      3.96.3-dev.0
Go Version   go1.20.8
Go Compiler  gc

Plugins
NAME  VERSION
aws   unknown
yaml  unknown

Host     
OS       debian
Version  12.2
Arch     x86_64

This project is written in yaml

Current Stack: v-thomas-pulumi-corp/pulumi-test-yaml/dev

TYPE                  URN
pulumi:pulumi:Stack   urn:pulumi:dev::pulumi-test-yaml::pulumi:pulumi:Stack::pulumi-test-yaml-dev
pulumi:providers:aws  urn:pulumi:dev::pulumi-test-yaml::pulumi:providers:aws::default
aws:s3/bucket:Bucket  urn:pulumi:dev::pulumi-test-yaml::aws:s3/bucket:Bucket::my-bucket


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/v-thomas-pulumi-corp
User           v-thomas-pulumi-corp
Organizations  v-thomas-pulumi-corp, demo, tgummerer-test, pulumi-test, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Cc @ringods, I think you've reported this before as well?

**Comment by ringods** [comment]
Yes, duplicate of #11092 I think.

**Comment by tgummerer** [comment]
Oh whoops, my search foo left me down.  I'm closing this out then, thank you!
