### ISSUE TITLE
nodejs rpc tests frequently flaky with 14 UNAVAILABLE

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#14841]
The nodejs rpc tests seem to fail quite frequently with an error similar to this:

```
  1) rpc
       run test: exported_function (***
     Error: 14 UNAVAILABLE: No connection established. Last error: null
The Pulumi runtime detected that 12 promises were still active
at the time that the process exited. There are a few ways that this can occur:
  * Not using `await` or `.then` on a Promise returned from a Pulumi API
  * Introducing a cyclic dependency between two Pulumi Resources
  * A bug in the Pulumi Runtime

Leaving promises active is probably not what you want. If you are unsure about
why you are seeing this message, re-run your program with the `PULUMI_DEBUG_PROMISE_LEAKS`
environment variable. The Pulumi runtime will then print out additional
debug information about the leaked promises.
      at callErrorFromStatus (bin/node_modules/@grpc/grpc-js/src/call.ts:82:17)
      at Object.onReceiveStatus (bin/node_modules/@grpc/grpc-js/src/client.ts:360:55)
      at Object.onReceiveStatus (bin/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
      at Object.onReceiveStatus (bin/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
      at /home/runner/work/pulumi/pulumi/sdk/nodejs/bin/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24
      at processTicksAndRejections (node:internal/process/task_queues:77:11)
  for call at
      at ServiceClientImpl.makeUnaryRequest (bin/node_modules/@grpc/grpc-js/src/client.ts:325:42)
      at ServiceClientImpl.run (bin/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
      at /home/runner/work/pulumi/pulumi/sdk/nodejs/tests/runtime/langhost/run.spec.ts:130:35
      at new Promise (<anonymous>)
      at mockRun (tests/runtime/langhost/run.spec.ts:130:35)
      at /home/runner/work/pulumi/pulumi/sdk/nodejs/tests/runtime/langhost/run.spec.ts:124:8
      at Generator.next (<anonymous>)
      at fulfilled (bin/tests/runtime/langhost/run.spec.js:15:808)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This does not seem specific to any specific test, in the set of `./tests/runtime/langhost/run.spec.ts` tests.  

I'm guessing it's a race when starting up the grpc server, but haven't dug into it more yet.

**Comment by tgummerer** [comment]
I'm gonna reopen this, as it's still happening even after #14843 was merged.

**Comment by tgummerer** [comment]
Another example: https://github.com/pulumi/pulumi/actions/runs/7283721891/job/19848100906

**Comment by joneteus** [comment]
I see same error occasionally in our Pulumi project CI. I tried to pin `grpc-js` to a newer version (1.9.12) and it seems to fix the issue.
