### ISSUE TITLE
Passing a file to `FileArchive` causes engine panic

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#1493]
I did the following:

```
const lambda = new aws.lambda.Function("myfunction", {
    code: new pulumi.asset.FileArchive("./app.js"), // point to file, not directory
    role: role.arn,
    handler: "app.handler",
    runtime: aws.lambda.NodeJS8d10Runtime,
});
```

Output:

```
$ pulumi update
Previewing update of stack 'pulumi-serverless-dev'
Previewing changes:

     Type                              Name                                     Plan       Info
 +   pulumi:pulumi:Stack               pulumi-serverless-pulumi-serverless-dev  create
 +   ├─ aws-serverless:apigateway:API  myapi                                    create
 +   ├─ aws:iam:Role                   mylambda-role                            create
 +   ├─ aws:dynamodb:Table             counterTable                             create
 +   └─ aws:iam:RolePolicyAttachment   mylambda-access                          create
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x11e83a2]

goroutine 215 [running]:
github.com/pulumi/pulumi/pkg/util/contract.IgnoreClose(0x0, 0x0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/ignore.go:33 +0x22
panic(0x194d360, 0x2027720)
        /Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/panic.go:491 +0x283
github.com/pulumi/pulumi/pkg/resource.addNextFileToTar(0x0, 0x0, 0xc42051d680, 0x0, 0x0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/asset.go:900 +0x52
github.com/pulumi/pulumi/pkg/resource.(*Archive).archiveTar(0xc4205379f0, 0x2588270, 0xc4200a7680, 0x0, 0x0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/asset.go:932 +0x11f
github.com/pulumi/pulumi/pkg/resource.(*Archive).Archive(0xc4205379f0, 0x1, 0x2588270, 0xc4200a7680, 0xc4200a7680, 0x0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/asset.go:886 +0x24c
github.com/pulumi/pulumi/pkg/resource.(*Archive).EnsureHash(0xc4205379f0, 0x0, 0x0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/asset.go:1019 +0x114
github.com/pulumi/pulumi/pkg/resource/plugin.UnmarshalPropertyValue(0xc420553d50, 0xc420448730, 0x49, 0x100000100, 0xc420083e98, 0xc4200bad40, 0x2)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/plugin/rpc.go:287 +0x5f1
github.com/pulumi/pulumi/pkg/resource/plugin.UnmarshalProperties(0xc4207401a0, 0xc420448730, 0x49, 0x100000100, 0x1, 0xc420553eb0, 0x0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/plugin/rpc.go:200 +0x27c
github.com/pulumi/pulumi/pkg/resource/deploy.(*resmon).RegisterResource(0xc4200baf80, 0x1fd7c80, 0xc4206a6c60, 0xc42027f0e0, 0xc4200baf80, 0x1, 0x1)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/source_eval.go:357 +0x3d1
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_RegisterResource_Handler.func1(0x1fd7c80, 0xc4206a6c60, 0x1a064e0, 0xc42027f0e0, 0x1fd7c80, 0xc4206a6c60, 0x1fdd2e0,0x205f8c0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:368 +0x86
github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1fd7c80, 0xc4206a6c60, 0x1a064e0, 0xc42027f0e0, 0xc4205494c0, 0xc4205494e0, 0x0, 0x0, 0x1fc8ac0, 0xc420047050)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_RegisterResource_Handler(0x19b35a0, 0xc4200baf80, 0x1fd7c80, 0xc4206a6bd0, 0xc42019cd20, 0xc420549140, 0x0, 0x0, 0x0, 0x0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:370 +0x16d
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4204629a0, 0x1fdb480, 0xc42050d680, 0xc420433680, 0xc42041e4b0, 0x202fc90, 0x0, 0x0, 0x0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:923 +0x92d
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4204629a0, 0x1fdb480, 0xc42050d680, 0xc420433680, 0x0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:1148 +0x1528
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420282270, 0xc4204629a0, 0x1fdb480, 0xc42050d680, 0xc420433680)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:635 +0xa1
```

**Comment by mikhailshilkov** [comment]
I got the same trying to package `jar` file for Java lambda. What's the right way to do so?

**Comment by pgavlin** [comment]
I think you'll need to use an `AssetArchive`:
```js
let javaLambda = new aws.lambda.Function("aws-java", {
    code: new pulumi.asset.AssetArchive({
        "lambda-java-example-1.0-SNAPSHOT.jar": new pulumi.asset.AssetFile("./java/target/lambda-java-example-1.0-SNAPSHOT.jar"),
    }),
});
```

Do you still have the exact stack trace you saw?

**Comment by mikhailshilkov** [comment]
`AssetArchive` + `FileAsset` won't work as it will put jar inside zip, and that's not how AWs expects it.

Here is the stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x5d6bb9]

goroutine 163 [running]:
github.com/pulumi/pulumi/pkg/util/contract.IgnoreClose(0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/util/contract/ignore.go:33 +0x29
panic(0xd2b860, 0x1414240)
        C:/go/src/runtime/panic.go:505 +0x237
github.com/pulumi/pulumi/pkg/resource.addNextFileToTar(0x0, 0x0, 0xc04244aa80, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/asset.go:901 +0x4c
github.com/pulumi/pulumi/pkg/resource.(*Archive).archiveTar(0xc042635860, 0x6b94100, 0xc0423afd00, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/asset.go:933 +0x187
github.com/pulumi/pulumi/pkg/resource.(*Archive).Archive(0xc042635860, 0x1, 0x6b94100, 0xc0423afd00, 0xc0423afd00, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/asset.go:887 +0x23c
github.com/pulumi/pulumi/pkg/resource.(*Archive).EnsureHash(0xc042635860, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/asset.go:1033 +0xfe
github.com/pulumi/pulumi/pkg/resource/plugin.UnmarshalPropertyValue(0xc0425112a0, 0xc04263a780, 0x51, 0x100000100, 0xc042426e58, 0xc042336600, 0x4)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/plugin/rpc.go:287 +0x555
github.com/pulumi/pulumi/pkg/resource/plugin.UnmarshalProperties(0xc04250c148, 0xc04263a780, 0x51, 0x100000100, 0x1, 0xc042511420, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/plugin/rpc.go:200 +0x251
github.com/pulumi/pulumi/pkg/resource/deploy.(*resmon).RegisterResource(0xc04205ec80, 0xf3e940, 0xc0425b5950, 0xc0426326c0, 0xc04205ec80, 0x1, 0x1)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/source_eval.go:357 +0x367
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_RegisterResource_Handler.func1(0xf3e940, 0xc0425b5950, 0xde7ee0, 0xc0426326c0, 0xf3e940, 0xc0425b5950, 0xf45c20, 0x144c340)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:367 +0x8d
github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0xf3e940, 0xc0425b5950, 0xde7ee0, 0xc0426326c0, 0xc042002ea0, 0xc042002ec0, 0x0, 0x0, 0xf31b20, 0xc04206cfb0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x310
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_RegisterResource_Handler(0xd93760, 0xc04205ec80, 0xf3e940, 0xc0425b5830, 0xc0420f2d20,0xc042340140, 0x0, 0x0, 0x4, 0xc04200c770)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:369 +0x16e
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0421ba420, 0xf429e0, 0xc04242fc80, 0xc04227a3c0, 0xc042680ae0, 0x141c8b0, 0x0, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:923 +0x890
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0421ba420, 0xf429e0, 0xc04242fc80, 0xc04227a3c0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:1148 +0x131f
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc04223f3d0, 0xc0421ba420, 0xf429e0, 0xc04242fc80, 0xc04227a3c0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:637 +0xa6
created by github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:635 +0xa8
```

**Comment by mikhailshilkov** [comment]
AWS accepts a zip file with jar inside lib folder, so this is the workaround I'm using now:
```
    code: new pulumi.asset.AssetArchive({
        "lib/lambda-java-example-1.0-SNAPSHOT.jar": new pulumi.asset.FileAsset("./java/target/lambda-java-example-1.0-SNAPSHOT.jar"),
    }),
```
