### ISSUE TITLE
Automation API program hangs when an exception is thrown from an `apply` and the resulting output is used as input to a resource, and then an output of that resource is used as an input to another resource

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#14980]
The following program effectively "hangs" when run through automation api. There's an output that throws, which is used as an input to another resource (`fn`), and when an output of that resource is used as an input of another resource.

### `index.ts`

```typescript
import { InlineProgramArgs, LocalWorkspace } from "@pulumi/pulumi/automation";
import * as pulumi from "@pulumi/pulumi";
import * as random from "@pulumi/random";

const process = require('process');

const args = process.argv.slice(2);
let destroy = false;
if (args.length > 0 && args[0]) {
    destroy = args[0] === "destroy";
}

const run = async () => {
    const pulumiProgram = async () => {
        const thing = pulumi.output("foo").apply(async (domain) => {
            throw new Error("hi");
        });

        const fn = new random.RandomString("fn", {
            length: 8,
            keepers: {
                foo: thing,
            }
        });

        new random.RandomString("fn2", {
            length: 8,
            keepers: {
                foo: fn.result,
            }
        });

        return ({});
    };

    const args: InlineProgramArgs = {
        stackName: "dev",
        projectName: "autoapplyerr",
        program: pulumiProgram
    };

    const stack = await LocalWorkspace.createOrSelectStack(args);

    console.info("successfully initialized stack");

    if (destroy) {
        console.info("destroying stack...");
        await stack.destroy({ onOutput: console.info });
        console.info("stack destroy complete");
        process.exit(0);
    }

    console.info("updating stack...");
    const upRes = await stack.up({ onOutput: console.info });
    console.log(`update summary: \n${JSON.stringify(upRes.summary.resourceChanges, null, 4)}`);
    console.log(`website url: ${upRes.outputs.websiteUrl.value}`);
};

run().catch(err => console.log(err));
```

### `package.json`

```json
{
    "name": "inline_program",
    "version": "1.0.0",
    "main": "./bin/index.js",
    "dependencies": {
        "@pulumi/pulumi": "^3.0.0",
        "@pulumi/random": "^4.15.0",
        "@types/node": "^14.11.7"
    },
    "scripts": {
        "build": "tsc",
        "start": "tsc && node ./bin/index.js"
    }
}
```

### `tsconfig.json`

```json
{
    "compilerOptions": {
        "outDir": "bin",
        "target": "es2016",
        "module": "commonjs",
        "moduleResolution": "node",
        "declaration": true,
        "sourceMap": true,
    },
}
```

Run `npm install` to install deps.

Then run `npm run start`, which outputs:

```
$ npm run start

> inline_program@1.0.0 start
> tsc && node ./bin/index.js

successfully initialized stack
updating stack...
Updating (dev)


View Live: url




    pulumi:pulumi:Stack autoapplyerr-dev running

    pulumi:pulumi:Stack autoapplyerr-dev running error: Unhandled exception: Error: hi

@ Updating....
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
```

You have to hit `CTRL+C` and then run `pulumi cancel` to cancel the update.

The expectation is that this wouldn't hang and execution of the update would stop.

If you comment out the last resource, e.g.:

```typescript
        // new random.RandomString("fn2", {
        //     length: 8,
        //     keepers: {
        //         foo: fn.result,
        //     }
        // });
```

And run `npm run start`, it does not hang and fails as expected:

```
$ npm run start

> inline_program@1.0.0 start
> tsc && node ./bin/index.js

successfully initialized stack
updating stack...
Updating (dev)


View Live: url




    pulumi:pulumi:Stack autoapplyerr-dev running

    pulumi:pulumi:Stack autoapplyerr-dev running error: Unhandled exception: Error: hi

    pulumi:pulumi:Stack autoapplyerr-dev running error: One or more errors occurred

    pulumi:pulumi:Stack autoapplyerr-dev **failed** 2 errors
Diagnostics:
  pulumi:pulumi:Stack (autoapplyerr-dev):
    error: Unhandled exception: Error: hi
        at /Users/user/Documents/2023/12/20/autoapplyerr/index.ts:16:19
        at Generator.next (<anonymous>)
        at /Users/user/Documents/2023/12/20/autoapplyerr/bin/index.js:8:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/user/Documents/2023/12/20/autoapplyerr/bin/index.js:4:12)
        at /Users/user/Documents/2023/12/20/autoapplyerr/index.ts:15:67
        at /Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/output.ts:398:31
        at Generator.next (<anonymous>)
        at /Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
    error: One or more errors occurred

Resources:
    1 unchanged

Duration: 1s


CommandError: code: -2
 stdout:
 stderr: Command failed with exit code 255: pulumi up --yes --skip-preview --client=127.0.0.1:59140 --exec-kind auto.inline --stack dev --non-interactive
Updating (dev)

View Live: url


    pulumi:pulumi:Stack autoapplyerr-dev running
    pulumi:pulumi:Stack autoapplyerr-dev running error: Unhandled exception: Error: hi
    pulumi:pulumi:Stack autoapplyerr-dev running error: One or more errors occurred
    pulumi:pulumi:Stack autoapplyerr-dev **failed** 2 errors
Diagnostics:
  pulumi:pulumi:Stack (autoapplyerr-dev):
    error: Unhandled exception: Error: hi
        at /Users/user/Documents/2023/12/20/autoapplyerr/index.ts:16:19
        at Generator.next (<anonymous>)
        at /Users/user/Documents/2023/12/20/autoapplyerr/bin/index.js:8:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/user/Documents/2023/12/20/autoapplyerr/bin/index.js:4:12)
        at /Users/user/Documents/2023/12/20/autoapplyerr/index.ts:15:67
        at /Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/output.ts:398:31
        at Generator.next (<anonymous>)
        at /Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
    error: One or more errors occurred

Resources:
    1 unchanged

Duration: 1s

 err?: Error: Command failed with exit code 255: pulumi up --yes --skip-preview --client=127.0.0.1:59140 --exec-kind auto.inline --stack dev --non-interactive
Updating (dev)

View Live: url


    pulumi:pulumi:Stack autoapplyerr-dev running
    pulumi:pulumi:Stack autoapplyerr-dev running error: Unhandled exception: Error: hi
    pulumi:pulumi:Stack autoapplyerr-dev running error: One or more errors occurred
    pulumi:pulumi:Stack autoapplyerr-dev **failed** 2 errors
Diagnostics:
  pulumi:pulumi:Stack (autoapplyerr-dev):
    error: Unhandled exception: Error: hi
        at /Users/user/Documents/2023/12/20/autoapplyerr/index.ts:16:19
        at Generator.next (<anonymous>)
        at /Users/user/Documents/2023/12/20/autoapplyerr/bin/index.js:8:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/user/Documents/2023/12/20/autoapplyerr/bin/index.js:4:12)
        at /Users/user/Documents/2023/12/20/autoapplyerr/index.ts:15:67
        at /Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/output.ts:398:31
        at Generator.next (<anonymous>)
        at /Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
    error: One or more errors occurred

Resources:
    1 unchanged

Duration: 1s


    at Object.createCommandError (/Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/automation/errors.ts:78:11)
    at Object.<anonymous> (/Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/automation/cmd.ts:79:15)
    at Generator.throw (<anonymous>)
    at rejected (/Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/pulumi/automation/cmd.js:19:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  commandResult: CommandResult {
    stdout: '',
    stderr: 'Command failed with exit code 255: pulumi up --yes --skip-preview --client=127.0.0.1:59140 --exec-kind auto.inline --stack dev --non-interactive\n' +
      'Updating (dev)\n' +
      '\n' +
      'View Live: https://app.pulumi.com/user-pulumi-corp/autoapplyerr/dev/updates/7\n' +
      '\n' +
      '\n' +
      '    pulumi:pulumi:Stack autoapplyerr-dev running \n' +
      '    pulumi:pulumi:Stack autoapplyerr-dev running error: Unhandled exception: Error: hi\n' +
      '    pulumi:pulumi:Stack autoapplyerr-dev running error: One or more errors occurred\n' +
      '    pulumi:pulumi:Stack autoapplyerr-dev **failed** 2 errors\n' +
      'Diagnostics:\n' +
      '  pulumi:pulumi:Stack (autoapplyerr-dev):\n' +
      '    error: Unhandled exception: Error: hi\n' +
      '        at /Users/user/Documents/2023/12/20/autoapplyerr/index.ts:16:19\n' +
      '        at Generator.next (<anonymous>)\n' +
      '        at /Users/user/Documents/2023/12/20/autoapplyerr/bin/index.js:8:71\n' +
      '        at new Promise (<anonymous>)\n' +
      '        at __awaiter (/Users/user/Documents/2023/12/20/autoapplyerr/bin/index.js:4:12)\n' +
      '        at /Users/user/Documents/2023/12/20/autoapplyerr/index.ts:15:67\n' +
      '        at /Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/output.ts:398:31\n' +
      '        at Generator.next (<anonymous>)\n' +
      '        at /Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/pulumi/output.js:21:71\n' +
      '        at new Promise (<anonymous>)\n' +
      '    error: One or more errors occurred\n' +
      '\n' +
      'Resources:\n' +
      '    1 unchanged\n' +
      '\n' +
      'Duration: 1s\n',
    code: -2,
    err: Error: Command failed with exit code 255: pulumi up --yes --skip-preview --client=127.0.0.1:59140 --exec-kind auto.inline --stack dev --non-interactive
    Updating (dev)

    View Live: url


        pulumi:pulumi:Stack autoapplyerr-dev running
        pulumi:pulumi:Stack autoapplyerr-dev running error: Unhandled exception: Error: hi
        pulumi:pulumi:Stack autoapplyerr-dev running error: One or more errors occurred
        pulumi:pulumi:Stack autoapplyerr-dev **failed** 2 errors
    Diagnostics:
      pulumi:pulumi:Stack (autoapplyerr-dev):
        error: Unhandled exception: Error: hi
            at /Users/user/Documents/2023/12/20/autoapplyerr/index.ts:16:19
            at Generator.next (<anonymous>)
            at /Users/user/Documents/2023/12/20/autoapplyerr/bin/index.js:8:71
            at new Promise (<anonymous>)
            at __awaiter (/Users/user/Documents/2023/12/20/autoapplyerr/bin/index.js:4:12)
            at /Users/user/Documents/2023/12/20/autoapplyerr/index.ts:15:67
            at /Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/output.ts:398:31
            at Generator.next (<anonymous>)
            at /Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/pulumi/output.js:21:71
            at new Promise (<anonymous>)
        error: One or more errors occurred

    Resources:
        1 unchanged

    Duration: 1s

        at makeError (/Users/user/Documents/2023/12/20/autoapplyerr/node_modules/execa/lib/error.js:60:11)
        at handlePromise (/Users/user/Documents/2023/12/20/autoapplyerr/node_modules/execa/index.js:118:26)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      shortMessage: 'Command failed with exit code 255: pulumi up --yes --skip-preview --client=127.0.0.1:59140 --exec-kind auto.inline --stack dev --non-interactive',
      command: 'pulumi up --yes --skip-preview --client=127.0.0.1:59140 --exec-kind auto.inline --stack dev --non-interactive',
      escapedCommand: 'pulumi up --yes --skip-preview "--client=127.0.0.1:59140" --exec-kind auto.inline --stack dev --non-interactive',
      exitCode: 255,
      signal: undefined,
      signalDescription: undefined,
      stdout: 'Updating (dev)\n' +
        '\n' +
        'View Live: url\n' +
        '\n' +
        '\n' +
        '    pulumi:pulumi:Stack autoapplyerr-dev running \n' +
        '    pulumi:pulumi:Stack autoapplyerr-dev running error: Unhandled exception: Error: hi\n' +
        '    pulumi:pulumi:Stack autoapplyerr-dev running error: One or more errors occurred\n' +
        '    pulumi:pulumi:Stack autoapplyerr-dev **failed** 2 errors\n' +
        'Diagnostics:\n' +
        '  pulumi:pulumi:Stack (autoapplyerr-dev):\n' +
        '    error: Unhandled exception: Error: hi\n' +
        '        at /Users/user/Documents/2023/12/20/autoapplyerr/index.ts:16:19\n' +
        '        at Generator.next (<anonymous>)\n' +
        '        at /Users/user/Documents/2023/12/20/autoapplyerr/bin/index.js:8:71\n' +
        '        at new Promise (<anonymous>)\n' +
        '        at __awaiter (/Users/user/Documents/2023/12/20/autoapplyerr/bin/index.js:4:12)\n' +
        '        at /Users/user/Documents/2023/12/20/autoapplyerr/index.ts:15:67\n' +
        '        at /Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/output.ts:398:31\n' +
        '        at Generator.next (<anonymous>)\n' +
        '        at /Users/user/Documents/2023/12/20/autoapplyerr/node_modules/@pulumi/pulumi/output.js:21:71\n' +
        '        at new Promise (<anonymous>)\n' +
        '    error: One or more errors occurred\n' +
        '\n' +
        'Resources:\n' +
        '    1 unchanged\n' +
        '\n' +
        'Duration: 1s\n',
      stderr: '',
      failed: true,
      timedOut: false,
      isCanceled: false,
      killed: false
    }
  }
}
```

Note that this doesn't happen running the Pulumi program outside of Automation API. Running the original program as a regular Pulumi program from the CLI errors as expected.

**Comment by julienp** [comment]
I have been debugging this a bit, and from what I see we're stuck in the call to `await settings.disconnect()` here https://github.com/pulumi/pulumi/blob/24e15ea6df0cc1fa52aa0417de3dc8e0db173fc3/sdk/nodejs/automation/server.ts#L96

This is waiting for RPC calls to complete.

I added some counters to track [rpcKeepAlive](https://github.com/pulumi/pulumi/blob/24e15ea6df0cc1fa52aa0417de3dc8e0db173fc3/sdk/nodejs/runtime/settings.ts#L458) acquire/releases and there is no release of the keep alive for the call to [prepareResource](https://github.com/pulumi/pulumi/blob/24e15ea6df0cc1fa52aa0417de3dc8e0db173fc3/sdk/nodejs/runtime/resource.ts#L622) with label `resource:fn2[random:index/randomString:RandomString]`
