### ISSUE TITLE
Pulumi preview panic when using with flag "--import-file"

### ISSUE THREAD

**Issue by andy-nix** [pulumi/pulumi#15002]
### What happened?

When using Pulumi CLI with flag `--import-file` it fails with following error

```
 panic: runtime error: index out of range [0] with length 0
 
 goroutine 66 [running]:
 main.newPreviewCmd.func1.buildImportFile.func1()
 	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/preview.go:91 +0x140a
 github.com/pulumi/pulumi/sdk/v3/go/common/promise.Run[...].func1()
 	/home/runner/work/pulumi/pulumi/sdk/go/common/promise/promise.go:150 +0x2c
 created by github.com/pulumi/pulumi/sdk/v3/go/common/promise.Run[...] in goroutine 1
 	/home/runner/work/pulumi/pulumi/sdk/go/common/promise/promise.go:149 +0x90
```

### Example

I can't provide exact code on which preview command fails, but in general it should create following resources with following names in state:

```
Current stack resources (17):
    TYPE                                                                                  NAME
    pulumi:pulumi:Stack                                                                   baz-core-bar-sandbox
    ├─ pulumi:providers:aws                                                               core
    ├─ pulumi:providers:aws                                                               bar-sandbox
    ├─ foo:baz-core:CoreGlobal                                                            bar-sandbox
    │  └─ foo:baz-module:MongoGlobal                                                      bar-sandbox
    │     ├─ foo:baz-module:MongoNetwork                                                  bar-sandbox
    │     │  ├─ mongodbatlas:index/projectIpAccessList:ProjectIpAccessList                whitelist-xx.xx.xx.xx/xx
    │     │  ├─ aws:ec2/securityGroup:SecurityGroup                                       bar-sandbox
    │     │  ├─ aws:ec2/vpcEndpoint:VpcEndpoint                                           bar-sandbox
    │     │  ├─ mongodbatlas:index/privateLinkEndpoint:PrivateLinkEndpoint                bar-sandbox
    │     │  └─ mongodbatlas:index/privateLinkEndpointService:PrivateLinkEndpointService  bar-sandbox
    │     ├─ mongodbatlas:index/auditing:Auditing                                         bar-sandbox
    │     ├─ mongodbatlas:index/project:Project                                           bar-sandbox
    │     ├─ mongodbatlas:index/cluster:Cluster                                           bar-sandbox
    │     └─ mongodbatlas:index/cloudBackupSchedule:CloudBackupSchedule                   bar-sandbox
    ├─ pulumi:providers:mongodbatlas                                                      default
    └─ pulumi:providers:mongodbatlas                                                      default_3_11_2
```

### Output of `pulumi about`

```
CLI          
Version      3.99.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME           VERSION
aws            5.43.0
mongodbatlas   3.11.2
null           0.0.1
pulumiservice  0.10.1
python         unknown
random         4.15.0

Host     
OS       arch
Version  "rolling"
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.11.6'

Current Stack: organization/baz-core/bar-sandbox

Found no resources associated with bar-sandbox

Found no pending operations associated with bar-sandbox

Backend        
Name           xiotto
URL            s3://<hidden>-pulumi-states?region=eu-central-1&awssdk=v2
User           andy
Organizations  
Token type     personal

Dependencies:
NAME      VERSION
coverage  7.3.4
baz-core  0.1.0
pip       23.3.1
wheel     0.41.3

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Happy Holidays. Thanks for filing this issue. I've taken some time to reproduce the error you're facing. This is definitely a bug in the import file generation. It stems from different resources sharing the same name.

I'm putting together a fix, but you can work around this by making the resource names unique (if possible).
