### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by JCzz** [pulumi/pulumi#15033]
### What happened?

Just trying to wrap my head around how to create a stack for local multipass vm. Very new to Pulumi I did the following, to play around with stacks:

```
pulumi login --local
pulumi new go \
  --description "Creates a multipass vm" \
  --name pulumi-cloud-init \
  --stack dev
pulumi stack ls --all
pulumi state delete -s organization/pulumi-cloud-init/dev
```

### Example

```
pulumi state delete -s organization/pulumi-cloud-init/dev
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.99.0
Go Version:       go1.21.5
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/debug/stack.go:24 +0x64
main.panicHandler(0x14001a3feff)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:35 +0x44
panic({0x10563a880?, 0x106f65a20?})
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x218
main.getURNFromState({0x105a72498?, 0x106ff2b00?}, {0x16cf7718f?, 0x22?}, 0x14001a3fbd8?, {0x104be9744, 0x1d})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:230 +0xfc
main.newStateDeleteCommand.func1(0x0?, {0x14001d60ce0, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_delete.go:64 +0xd0
main.newStateDeleteCommand.RunFunc.func2(0x0?, {0x14001d60ce0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x28
main.newStateDeleteCommand.RunFunc.RunResultFunc.func5(0x14001d7c700?, {0x14001d60ce0, 0x0, 0x2})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:115 +0x34
github.com/spf13/cobra.(*Command).execute(0x14001d80300, {0x14001d60cc0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x654
github.com/spf13/cobra.(*Command).ExecuteC(0x1400194c900)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:56 +0x54
```

### Output of `pulumi about`

```
CLI          
Version      3.99.0
Go Version   go1.21.5
Go Compiler  gc

Host     
OS       darwin
Version  14.2.1
Arch     arm64

Backend        
Name           <me>-MBP.localdomain
URL            file://~
User          <me>
Organizations  
Token type     personal

Pulumi locates its logs in /var/folders/ws/r3lmtqdj03d3jn5l3v3t_s3w0000gn/T/ by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /Users/<me>/appsyouwear/git/github.com/appsyouwear/gazelle/stack/core/automation/pulumi/cloudinit/proj01). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from /Users/<me>/appsyouwear/git/github.com/appsyouwear/gazelle/stack/core/automation/pulumi/cloudinit/proj01). If you have not created a project yet, use `pulumi new` to do so: no project file found
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening this issue @JCzz and sorry for the trouble! I can reproduce the panic with the steps you provided.

I'm guessing you were trying to delete the stack, in which case, you'll want to use the following command:

```
pulumi stack rm organization/pulumi-cloud-init/dev
```

The `pulumi state *` commands are for more advanced scenarios around editing Pulumi's state. For example, `pulumi state delete` is for removing a particular resource from the state.

In any case, we'll definitely fix this not to panic. The problem is happening because the stack is new and doesn't have any state yet since `pulumi up` hasn't been run yet.

---

The problem is here:

https://github.com/pulumi/pulumi/blob/e1377aece3b9008391f9d42810388f7541567a5f/pkg/cmd/pulumi/state.go#L216-L230

On line 225 we call `s.Snapshot` to get the snapshot, but this returns a `nil` snapshot. We then try to dereference the `nil` pointer on line 230 and panic.

**Comment by JCzz** [comment]
Ahh, thanks @justinvp good guessing ;-) Well, no go "panic" is always good.

**Comment by Frassle** [comment]
Re-opening to track that we'll get this panic fixed.
