### ISSUE TITLE
Duplicated resource leading to assert from `computeDeletes`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1503]
I'm not sure how I got in this state - but I think it was related to having a "pending delete" resource in my stack.  However I did get here though, it appears there is some issue handling this state which seemingly should have been okay.  I am then able to get into very strange states like in the final step below.

```
luke:~/go/src/github.com/pulumi/pulumi-azure/examples/aks (master *)
$ pulumi update
Previewing update of stack 'lukehoban'
Previewing changes:

     Type                                         Name           Plan          Info
 *   pulumi:pulumi:Stack                          aks-lukehoban  no change
 +-  ├─ azure:core:ResourceGroup                  aks            replace       changes: ~ location,name
 +   └─ azure:containerservice:KubernetesCluster  kubernetes     create
panic: fatal: An assertion has failed

goroutine 133 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(0x1a825e6, 0x17)
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xf3
github.com/pulumi/pulumi/pkg/util/contract.Assert(0x1942200)
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26 +0x49
github.com/pulumi/pulumi/pkg/resource/deploy.(*PlanIterator).computeDeletes(0xc42062e180, 0x0, 0x0, 0x0)
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_apply.go:612 +0x1bc
github.com/pulumi/pulumi/pkg/resource/deploy.(*PlanIterator).Next(0xc42062e180, 0x1fdcd80, 0xc4202f30e0, 0x1, 0x0)
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_apply.go:218 +0x172
github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk.func1(0xc42062e180, 0xc420425240, 0xc42074d380, 0xc4204252f0, 0xc420324000, 0xc420013740, 0xc4201d6c01)
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/engine/plan.go:235 +0x146
created by github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/engine/plan.go:209 +0x211

luke:~/go/src/github.com/pulumi/pulumi-azure/examples/aks (master *)
$ pulumi stack
Current stack is lukehoban:
    Owner: lukehoban
    Last updated: 8 minutes ago (2018-06-13 21:10:15.355215 -0700 PDT)
    Pulumi version: v0.12.4-dev-1528417585-g1a7d3481
    Plugin nodejs [language] version: 0.12.4-dev-1528417585-g1a7d3481
    Plugin azure [resource] version: 0.12.3-dev-1527808623-g1d30a5a

Current stack resources (3):
    TYPE                                             NAME
    pulumi:pulumi:Stack                              aks-lukehoban
    azure:core/resourceGroup:ResourceGroup           aks
    azure:core/resourceGroup:ResourceGroup           aks

Current stack outputs (0):
    No output values currently in this stack

More information at: https://app.pulumi.com/lukehoban/lukehoban

Use `pulumi stack select` to change stack; `pulumi stack ls` lists known ones

luke:~/go/src/github.com/pulumi/pulumi-azure/examples/aks (master *)
$ pulumi destroy
Previewing destroy of stack 'lukehoban'
Previewing changes:

     Type                 Name           Plan       Info
 -   pulumi:pulumi:Stack  aks-lukehoban  delete

info: 1 change previewed:
    - 1 resource to delete

Do you want to perform this destroy? yes
Destroying stack 'lukehoban'
Performing changes:

     Type                 Name           Status                  Info
 -   pulumi:pulumi:Stack  aks-lukehoban  **deleting failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack: aks-lukehoban
    error: post-step event returned an error: failed to save snapshot: after mutation of snapshot: child resource urn:pulumi:lukehoban::aks::azure:core/resourceGroup:ResourceGroup::aks refers to missing parent urn:pulumi:lukehoban::aks::pulumi:pulumi:Stack::aks-lukehoban

info: 1 change performed:
    - 1 resource deleted
Update duration: 47.6623647s

Permalink: https://app.pulumi.com/lukehoban/lukehoban/updates/12
error: post-step event returned an error: failed to save snapshot: after mutation of snapshot: child resource urn:pulumi:lukehoban::aks::azure:core/resourceGroup:ResourceGroup::aks refers to missing parent urn:pulumi:lukehoban::aks::pulumi:pulumi:Stack::aks-lukehoban

luke:~/go/src/github.com/pulumi/pulumi-azure/examples/aks (master *)
$ pulumi stack
Current stack is lukehoban:
    Owner: lukehoban
    Last updated: 17 seconds ago (2018-06-13 21:19:22.66257 -0700 PDT)
    Pulumi version: v0.14.1-dev-1528827785-g9ccd0771
    Plugin azure [resource] version: 0.14.1-dev-1528848608-gc0d6ba2-dirty

Current stack resources (1):
    TYPE                                             NAME
    azure:core/resourceGroup:ResourceGroup           aks

More information at: https://app.pulumi.com/lukehoban/lukehoban

Use `pulumi stack select` to change stack; `pulumi stack ls` lists known ones

luke:~/go/src/github.com/pulumi/pulumi-azure/examples/aks (master *)
$ yarn build
yarn run v1.3.2
warning package.json: License should be a valid SPDX license expression
$ tsc
pulumi update
✨  Done in 2.06s.

luke:~/go/src/github.com/pulumi/pulumi-azure/examples/aks (master *)
$ pulumi update
Previewing update of stack 'lukehoban'
Previewing changes:

     Type                                         Name           Plan        Info
 +   pulumi:pulumi:Stack                          aks-lukehoban  create
 +-  ├─ azure:core:ResourceGroup                  aks            replace     changes: ~ location,name
 +   └─ azure:containerservice:KubernetesCluster  kubernetes     create

info: 3 changes previewed:
    + 2 resources to create
    +-1 resource to replace

Do you want to perform this update? yes
Updating stack 'lukehoban'
Permalink: https://app.pulumi.com/lukehoban/lukehoban/updates/13
error: failed to load language plugin nodejs: failed to perform plugin load callback: failed to save snapshot: after mutation of snapshot: child resource urn:pulumi:lukehoban::aks::azure:co
re/resourceGroup:ResourceGroup::aks refers to missing parent urn:pulumi:lukehoban::aks::pulumi:pulumi:Stack::aks-lukehoban
```

**Comment by swgillespie** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/1644.
