### ISSUE TITLE
Need better error messages for python when property values are the wrong type.

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#15156]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When an incorrect type is specified for a python program one gets output like this:
```
pulumi:pulumi:Stack (aks-cluster-sc-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/pulumiGuy/.pulumi/bin/pulumi-language-python-exec", line 197, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
        return future.result()
      File "/builds/goo/devsecops/pulumi/azure/aks-cluster/aks-cluster-sc/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 137, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/builds/goo/devsecops/pulumi/azure/aks-cluster/aks-cluster-sc/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/builds/goo/devsecops/pulumi/azure/aks-cluster/aks-cluster-sc/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 121, in wait_for_rpcs
        raise exception
      File "/builds/goo/devsecops/pulumi/azure/aks-cluster/aks-cluster-sc/venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
      File "/builds/goo/devsecops/pulumi/azure/aks-cluster/aks-cluster-sc/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 872, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/builds/goo/devsecops/pulumi/azure/aks-cluster/aks-cluster-sc/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 176, in prepare_resource
        serialized_props = await rpc.serialize_properties(
      File "/builds/goo/devsecops/pulumi/azure/aks-cluster/aks-cluster-sc/venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 213, in serialize_properties
        result = await serialize_property(
      File "/builds/goo/devsecops/pulumi/azure/aks-cluster/aks-cluster-sc/venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 576, in serialize_property
        raise ValueError(f"unexpected input of type {type(value).__name__}")
    ValueError: unexpected input of type method
```
It can be extremely difficult to locate the issue.

Generating error messages that point to the specific property or similar is needed.

**Comment by kvthr** [comment]
Hey @Frassle, can I work on this issue?

**Comment by Frassle** [comment]
I don't think anyone else is, so sure.
