### ISSUE TITLE
 Pulumi CLI crashed

### ISSUE THREAD

**Issue by liron-l** [pulumi/pulumi#15159]
### What happened?

 Pulumi CLI encountered a fatal error

### Example

```
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/debug/stack.go:24 +0x64
main.panicHandler(0x4001fbfeff)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:35 +0x44
panic({0x1eb38e0?, 0x3f59210?})
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x218
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.GetPulumiHomeDir()
	/home/runner/work/pulumi/pulumi/sdk/go/common/workspace/paths.go:257 +0x90
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.getCredsFilePath()
	/home/runner/work/pulumi/pulumi/sdk/go/common/workspace/creds.go:151 +0x34
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.GetStoredCredentials()
	/home/runner/work/pulumi/pulumi/sdk/go/common/workspace/creds.go:208 +0x24
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.GetCurrentCloudURL(0x4001c71340)
	/home/runner/work/pulumi/pulumi/sdk/go/common/workspace/creds.go:183 +0x68
main.currentBackend({0x2ab7420, 0x3fe6120}, 0x0?, {{0x22ac029, 0x5}, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/util.go:166 +0x48
main.requireStack({0x2ab7420, 0x3fe6120}, {0xfffffc8851e0, 0x2c}, 0x1, {{0x22ac029, 0x5}, 0x0, 0x0, 0x0, ...})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/util.go:323 +0xbc
main.newStackHistoryCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/stack_history.go:44 +0xd0
main.newStackHistoryCmd.RunFunc.func2(0x0?, {0x40007a3200?, 0x0?, 0x0?})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x28
main.newStackHistoryCmd.RunFunc.RunResultFunc.func3(0x4001c01000?, {0x40007a3200, 0x0, 0x9})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:115 +0x34
github.com/spf13/cobra.(*Command).execute(0x40007bc300, {0x40007a3170, 0x9, 0x9})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x654
github.com/spf13/cobra.(*Command).ExecuteC(0x40007aa000)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:56 +0x54
```

### Output of `pulumi about`

Pulumi Version:   v3.101.0
Go Version:       go1.21.5
Go Compiler:      gc
Architecture:     arm64
Operating System: linux

### Additional context
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.

Pulumi Version:   v3.101.0
Go Version:       go1.21.5
Go Compiler:      gc
Architecture:     arm64
Operating System: linux
Panic:            runtime error: invalid memory address or nil pointer dereference
```
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/debug/stack.go:24 +0x64
main.panicHandler(0x4001fbfeff)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:35 +0x44
panic({0x1eb38e0?, 0x3f59210?})
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x218
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.GetPulumiHomeDir()
	/home/runner/work/pulumi/pulumi/sdk/go/common/workspace/paths.go:257 +0x90
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.getCredsFilePath()
	/home/runner/work/pulumi/pulumi/sdk/go/common/workspace/creds.go:151 +0x34
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.GetStoredCredentials()
	/home/runner/work/pulumi/pulumi/sdk/go/common/workspace/creds.go:208 +0x24
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.GetCurrentCloudURL(0x4001c71340)
	/home/runner/work/pulumi/pulumi/sdk/go/common/workspace/creds.go:183 +0x68
main.currentBackend({0x2ab7420, 0x3fe6120}, 0x0?, {{0x22ac029, 0x5}, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/util.go:166 +0x48
main.requireStack({0x2ab7420, 0x3fe6120}, {0xfffffc8851e0, 0x2c}, 0x1, {{0x22ac029, 0x5}, 0x0, 0x0, 0x0, ...})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/util.go:323 +0xbc
main.newStackHistoryCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/stack_history.go:44 +0xd0
main.newStackHistoryCmd.RunFunc.func2(0x0?, {0x40007a3200?, 0x0?, 0x0?})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x28
main.newStackHistoryCmd.RunFunc.RunResultFunc.func3(0x4001c01000?, {0x40007a3200, 0x0, 0x9})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:115 +0x34
github.com/spf13/cobra.(*Command).execute(0x40007bc300, {0x40007a3170, 0x9, 0x9})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x654
github.com/spf13/cobra.(*Command).ExecuteC(0x40007aa000)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:56 +0x54
```

**Comment by Frassle** [comment]
It looks like this is due to the user not having a home directory. I think this will always be an error case, but we could make this return a useful error telling the user this and pointing out the PULUMI_HOME envvar to fix it.
