### ISSUE TITLE
Deleted Cluster Lingering in Pulumi State

### ISSUE THREAD

**Issue by h0evans** [pulumi/pulumi#15166]
### What happened?

Long story but I tried to upgrade AWS EKS to 1.25 k8s version and needed to revert back and thus delete and create a new EKS cluster. Now when I run any of my pulumi scripts, I'm getting a message stating that 'it can't reach the deleted cluster and if it's deleted you can remove it from the pulumi state'. When I try to remove that provider via URN, I run into the issue described below.

### Example

```
[~/src/infra/infra-platform/apps/ingress] $ pulumi state delete urn:pulumi:testing-ingress::ingress::pulumi:providers:kubernetes::kubeconfig
 warning: This command will edit your stack's state directly. Confirm? Yes
 Multiple resources with the given URN exist, please select the one to edit: "b36b2f22-8aaa-4d49-b1c4-d0475c4be6e2" (Pending Deletion)
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.101.1
Go Version:       go1.21.6
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            fatal: error An assertion has failed: state edit produced an invalid snapshot. source error: resource urn:pulumi:testing-ingress::ingress::kubernetes:networking.k8s.io/v1:Ingress::testing-ingress-grpc refers to unknown provider urn:pulumi:testing-ingress::ingress::pulumi:providers:kubernetes::kubeconfig::b36b2f22-8aaa-4d49-b1c4-d0475c4be6e2

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.21.6/libexec/src/runtime/debug/stack.go:24 +0x64
main.panicHandler(0x14001fbfeff)
        /private/tmp/pulumi-20240110-4441-84n58x/pkg/cmd/pulumi/main.go:35 +0x44
panic({0x104f9be60?, 0x14000a10d20?})
        /opt/homebrew/Cellar/go/1.21.6/libexec/src/runtime/panic.go:914 +0x218
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /private/tmp/pulumi-20240110-4441-84n58x/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.AssertNoErrorf({0x1054e9f78, 0x14000a10cf0}, {0x1046b05fa?, 0x0?}, {0x0?, 0x0?, 0x0?})
        /private/tmp/pulumi-20240110-4441-84n58x/sdk/go/common/util/contract/assert.go:51 +0x10c
main.totalStateEdit({0x105510c38, 0x106aaea40}, {0x105527db0, 0x14002026300}, 0x1, {{0x1045fea57, 0x6}, 0x0, 0x0, 0x0, ...}, ...)
        /private/tmp/pulumi-20240110-4441-84n58x/pkg/cmd/pulumi/state.go:181 +0x2a4
main.runTotalStateEdit({0x105510c38, 0x106aaea40}, {0x0, 0x0}, 0xd8?, 0x0?)
        /private/tmp/pulumi-20240110-4441-84n58x/pkg/cmd/pulumi/state.go:146 +0xf4
main.runStateEdit(...)
        /private/tmp/pulumi-20240110-4441-84n58x/pkg/cmd/pulumi/state.go:123
main.newStateDeleteCommand.func1(0x0?, {0x140020840a0, 0x1, 0x0?})
        /private/tmp/pulumi-20240110-4441-84n58x/pkg/cmd/pulumi/state_delete.go:75 +0x150
main.newStateDeleteCommand.RunFunc.func2(0x0?, {0x140020840a0?, 0x0?, 0x0?})
        /private/tmp/pulumi-20240110-4441-84n58x/sdk/go/common/util/cmdutil/exit.go:99 +0x28
main.newStateDeleteCommand.RunFunc.RunResultFunc.func5(0x14001f3cf00?, {0x140020840a0, 0x1, 0x1})
        /private/tmp/pulumi-20240110-4441-84n58x/sdk/go/common/util/cmdutil/exit.go:115 +0x34
github.com/spf13/cobra.(*Command).execute(0x14001f46300, {0x14002084070, 0x1, 0x1})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x654
github.com/spf13/cobra.(*Command).ExecuteC(0x14001d56900)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /private/tmp/pulumi-20240110-4441-84n58x/pkg/cmd/pulumi/main.go:56 +0x54
```

### Output of `pulumi about`

```
CLI          
Version      3.101.1
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.41.0
awsx        1.0.2
docker      3.6.1
kubernetes  3.29.0
nodejs      unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/opt/node/bin/node' version='v20.7.0'

Current Stack: testing-ingress

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:testing-ingress::ingress::pulumi:pulumi:Stack::ingress-testing-ingress
pulumi:providers:pulumi                              urn:pulumi:testing-ingress::ingress::pulumi:providers:pulumi::default
pulumi:pulumi:StackReference                         urn:pulumi:testing-ingress::ingress::pulumi:pulumi:StackReference::testing-infrastructure
pulumi:providers:aws                                 urn:pulumi:testing-ingress::ingress::pulumi:providers:aws::default_5_41_0
aws:acm/certificate:Certificate                      urn:pulumi:testing-ingress::ingress::aws:acm/certificate:Certificate::app-wildcard-cert
pulumi:providers:kubernetes                          urn:pulumi:testing-ingress::ingress::pulumi:providers:kubernetes::kubeconfig
aws:route53/record:Record                            urn:pulumi:testing-ingress::ingress::aws:route53/record:Record::app-cert-validation-record
aws:acm/certificateValidation:CertificateValidation  urn:pulumi:testing-ingress::ingress::aws:acm/certificateValidation:CertificateValidation::app-cert-validation
kubernetes:networking.k8s.io/v1:Ingress              urn:pulumi:testing-ingress::ingress::kubernetes:networking.k8s.io/v1:Ingress::testing-ingress-grpc
kubernetes:networking.k8s.io/v1:Ingress              urn:pulumi:testing-ingress::ingress::kubernetes:networking.k8s.io/v1:Ingress::testing-ingress
aws:route53/record:Record                            urn:pulumi:testing-ingress::ingress::aws:route53/record:Record::app-wildcard
pulumi:providers:kubernetes                          urn:pulumi:testing-ingress::ingress::pulumi:providers:kubernetes::kubeconfig
kubernetes:networking.k8s.io/v1:Ingress              urn:pulumi:testing-ingress::ingress::kubernetes:networking.k8s.io/v1:Ingress::testing-ingress-grpc
kubernetes:networking.k8s.io/v1:Ingress              urn:pulumi:testing-ingress::ingress::kubernetes:networking.k8s.io/v1:Ingress::testing-ingress


Found no pending operations associated with testing-ingress

Backend        
Name           D7YQ2D72FC
URL            s3://testing-infra-state-8e07ac8
User           harrison.evans
Organizations  
Token type     personal

Pulumi locates its logs in /var/folders/cm/4ll7dptx6qz78283p_sj1c440000gr/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: failed to run "/opt/homebrew/bin/npm ls --json --depth=0": exit status 1
```

### Additional context

received this text from within the command.

```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.101.1
Go Version:       go1.21.6
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            fatal: error An assertion has failed: state edit produced an invalid snapshot. source error: resource urn:pulumi:testing-ingress::ingress::kubernetes:networking.k8s.io/v1:Ingress::testing-ingress-grpc refers to unknown provider urn:pulumi:testing-ingress::ingress::pulumi:providers:kubernetes::kubeconfig::b36b2f22-8aaa-4d49-b1c4-d0475c4be6e2
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
You might have success doing this state delete manually by exporting the state json, deleting the resource with that urn and then importing that (see the `pulumi stack export` and `import` commands).

But that's very much a workaround, this _should_ work.

**Comment by h0evans** [comment]
Thanks that worked as a work around!

From: Fraser Waters ***@***.***>
Date: Wednesday, January 17, 2024 at 7:53 AM
To: pulumi/pulumi ***@***.***>
Cc: Harrison Evans ***@***.***>, Author ***@***.***>
Subject: [External Origin] Re: [pulumi/pulumi] Deleted Cluster Lingering in Pulumi State (Issue #15166)

You might have success doing this state delete manually by exporting the state json, deleting the resource with that urn and then importing that (see the pulumi stack export and import commands).

But that's very much a workaround, this should work.

**Comment by craig-pyrra** [comment]
Just jumping in to add that I have the same issue. I deleted an EKS cluster and created a new one. A dependant project is now failing to `update` or `destroy` because it's trying to act on the deleted cluster. Editing the state of that project fails with the same error as in the bug report above.
