### ISSUE TITLE
`TestDeterminePulumiPackages/non-empty` is failing in CI

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#15192]
For example: https://github.com/pulumi/pulumi/actions/runs/7590486447/job/20677128176?pr=15191#step:38:145

```
=== FAIL: . TestDeterminePulumiPackages/non-empty (9.66s)
    main_test.go:149: 
Traceback (most recent call last):
  File "/home/runner/work/pulumi/pulumi/scripts/go-test.py", line 99, in <module>
    sp.check_call(args, shell=False)
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gotestsum', '--jsonfile', '/home/runner/work/pulumi/pulumi/test-results/439b935b-12cd-44fb-be3e-47f936f9d6ed.json', '--rerun-fails=1', '--packages', 'github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/v3', '--', '-count=1', '-cover', '-tags=all', '-timeout', '1h', '-parallel=8', '-shuffle=off', '-p=2', '-race=true', '-coverprofile=/home/runner/work/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/go-test-7434371f.cov', '-coverpkg=github.com/pulumi/pulumi/pkg/v3/...,github.com/pulumi/pulumi/sdk/v3/...,github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3/...,github.com/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/v3/...,github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/v3/...']' returned non-zero exit status 1.
        	Error Trace:	/home/runner/work/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/main_test.go:149
        	Error:      	Not equal: 
        	            	expected: "pulumi-random"
        	            	actual  : "pulumi_random"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-pulumi-random
        	            	+pulumi_random
        	Test:       	TestDeterminePulumiPackages/non-empty
```

This appears to be related to the `pulumi-random` [v4.15.1 release](https://github.com/pulumi/pulumi-random/releases/tag/v4.15.1) from 1/19 at 9:08 AM PT.

There seems to be a discrepancy now when installing `pulumi-random`. Previous versions reported the package name as `pulumi-random`, but now it's being reported by pip as `pulumi_random`.

## pulumi-random v4.15.0

```
python -m pip install pulumi-random==4.15.0
python -m pip list -v --format json
```

```json
{
    "name": "pulumi-random",
    "version": "4.15.0",
    "location": "/Users/user/test/venv/lib/python3.9/site-packages",
    "installer": "pip"
}
```

## pulumi-random v4.15.1

```
python -m pip install pulumi-random==4.15.1
python -m pip list -v --format json
```

```json
{
    "name": "pulumi_random",
    "version": "4.15.1",
    "location": "/Users/user/test/venv/lib/python3.9/site-packages",
    "installer": "pip"
}
```

This is likely going to cause problems with the Python language host's `GetRequiredPlugins` plugin detection.

Nothing obvious is jumping out from a cursory look at the diff between the two versions: https://github.com/pulumi/pulumi-random/compare/v4.15.0...v4.15.1

Will need to investigate what's going on.

**Comment by justinvp** [comment]
I downloaded the .tar.gz for [4.15.0](https://pypi.org/project/pulumi-random/4.15.0/#files) and [4.15.1](https://pypi.org/project/pulumi-random/4.15.1/#files) and compared the contents.

`PKG-INFO` and `pyproject.toml` are the same other than the version.

However, `pulumi_random.egg-info/PKG-INFO` have the different names:

<img width="1374" alt="Screenshot 2024-01-19 at 10 49 14 PM" src="https://github.com/pulumi/pulumi/assets/710598/5a2cc30f-c8d0-4088-95f9-496c70915d2c">

**Comment by justinvp** [comment]
Looks like it's due to https://github.com/pypa/setuptools/pull/4159

**Comment by justinvp** [comment]
OK, so plugin detection still works with this change. We used to get back `pulumi-random` for the package name from pip, and then we'd look for a `pulumi-plugin.json` inside the reported location. In doing so, we replace dashes with underscores, because the directory of the package is named with underscore.

https://github.com/pulumi/pulumi/blob/8bcef51fb8a781fcb9b9b630b4cc96fecc859640/sdk/python/cmd/pulumi-language-python/main.go#L393-L398

I think we can just update the `TestDeterminePulumiPackages/non-empty` test to expect `pulumi_random` now.

**Comment by justinvp** [comment]
We might want to consider updating the following:

https://github.com/pulumi/pulumi/blob/8bcef51fb8a781fcb9b9b630b4cc96fecc859640/sdk/python/cmd/pulumi-language-python/main.go#L379-L386

And:

https://github.com/pulumi/pulumi/blob/8bcef51fb8a781fcb9b9b630b4cc96fecc859640/sdk/python/cmd/pulumi-language-python/main.go#L474-L476

If we can't find a `pulumi-plugin.json` file, we fallback to saying it's a plugin if the name of the package is prefixed with `pulumi-`. We might want to consider updating this to also check for `pulumi_`.

However, all that said, this is largely for very old packages that don't have `pulumi-plugin.json`. Now all python packages should be including a `pulumi-plugin.json` for some time. Any new package being published that will have this name change would likely be using more recent SDKgen that includes the `pulumi-plugin.json`, so this likely isn't a problem we need to be concerned about.
