### ISSUE TITLE
integration TestAutomaticVenvCreation/AbsolutePathWithMain is flaky

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#15238]
```
=== FAIL: integration TestAutomaticVenvCreation/AbsolutePathWithMain (18.02s)
    environment.go:97: Created new test environment:  /tmp/test-env1645492430
    integration_python_acceptance_test.go:259: venvPath = /tmp/test-env1645492430/absvenv (IsAbs = true)
    integration_python_acceptance_test.go:280: Wrote Pulumi.yaml:
        name: pulumi-python-venv
        description: A simple Python Pulumi program that needs a venv to run.
        runtime:
          name: python
          options:
            virtualenv: >-
              /tmp/test-env1645492430/absvenv
        main: infra
        
    environment.go:216: Running command pulumi login --cloud-url file:///tmp/test-env1645492430
    environment.go:216: Running command pulumi stack init teststack
    environment.go:216: Running command pulumi preview
    integration_python_acceptance_test.go:290: Run Error: exit status 255
    integration_python_acceptance_test.go:290: STDOUT: Previewing update (teststack):
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Creating virtual environment...
        @ previewing update.........
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Finished creating virtual environment
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Updating pip, setuptools, and wheel in virtual environment...
        @ previewing update....
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Requirement already satisfied: pip in /tmp/test-env1645492430/absvenv/lib/python3.8/site-packages (23.0.1)
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Collecting pip
            pulumi:pulumi:Stack pulumi-python-venv-teststack    Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Requirement already satisfied: setuptools in /tmp/test-env1645492430/absvenv/lib/python3.8/site-packages (56.0.0)
        @ previewing update....
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Collecting setuptools
            pulumi:pulumi:Stack pulumi-python-venv-teststack    Using cached setuptools-69.0.3-py3-none-any.whl (819 kB)
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Collecting wheel
            pulumi:pulumi:Stack pulumi-python-venv-teststack    Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Installing collected packages: wheel, setuptools, pip
            pulumi:pulumi:Stack pulumi-python-venv-teststack    Attempting uninstall: setuptools
        @ previewing update....
            pulumi:pulumi:Stack pulumi-python-venv-teststack      Found existing installation: setuptools 56.0.0
            pulumi:pulumi:Stack pulumi-python-venv-teststack      Uninstalling setuptools-56.0.0:
            pulumi:pulumi:Stack pulumi-python-venv-teststack        Successfully uninstalled setuptools-56.0.0
        @ previewing update....
            pulumi:pulumi:Stack pulumi-python-venv-teststack    Attempting uninstall: pip
            pulumi:pulumi:Stack pulumi-python-venv-teststack      Found existing installation: pip 23.0.1
            pulumi:pulumi:Stack pulumi-python-venv-teststack      Uninstalling pip-23.0.1:
            pulumi:pulumi:Stack pulumi-python-venv-teststack        Successfully uninstalled pip-23.0.1
        @ previewing update.....
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Successfully installed pip-23.3.2 setuptools-69.0.3 wheel-0.42.0
        @ previewing update....
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Finished updating
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Installing dependencies in virtual environment...
        @ previewing update....
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Finished installing dependencies
        @ previewing update.....
        
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Traceback (most recent call last):
            pulumi:pulumi:Stack pulumi-python-venv-teststack    File "/home/runner/work/pulumi/pulumi/bin/pulumi-language-python-exec", line 16, in <module>
            pulumi:pulumi:Stack pulumi-python-venv-teststack      import pulumi
            pulumi:pulumi:Stack pulumi-python-venv-teststack  ModuleNotFoundError: No module named 'pulumi'
            pulumi:pulumi:Stack pulumi-python-venv-teststack  It looks like the Pulumi SDK has not been installed. Have you run pip install?
            pulumi:pulumi:Stack pulumi-python-venv-teststack  If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
            pulumi:pulumi:Stack pulumi-python-venv-teststack  error: an unhandled error occurred: program exited with non-zero exit code: 1
            pulumi:pulumi:Stack pulumi-python-venv-teststack  1 error; 6 messages
        Diagnostics:
          pulumi:pulumi:Stack (pulumi-python-venv-teststack):
            Traceback (most recent call last):
              File "/home/runner/work/pulumi/pulumi/bin/pulumi-language-python-exec", line 16, in <module>
                import pulumi
            ModuleNotFoundError: No module named 'pulumi'
            It looks like the Pulumi SDK has not been installed. Have you run pip install?
            If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
        
            error: an unhandled error occurred: program exited with non-zero exit code: 1
        
        
    integration_python_acceptance_test.go:290: STDERR: 
    integration_python_acceptance_test.go:290: Ran command pulumi args [preview] and expected success. Instead got failure.

=== FAIL: integration TestAutomaticVenvCreation/RelativePathWithMain (18.99s)
    environment.go:97: Created new test environment:  /tmp/test-env3515876479
    integration_python_acceptance_test.go:259: venvPath = venv (IsAbs = false)
    integration_python_acceptance_test.go:280: Wrote Pulumi.yaml:
        name: pulumi-python-venv
        description: A simple Python Pulumi program that needs a venv to run.
        runtime:
          name: python
          options:
            virtualenv: >-
              venv
        main: infra
        
    environment.go:216: Running command pulumi login --cloud-url file:///tmp/test-env3515876479
    environment.go:216: Running command pulumi stack init teststack
    environment.go:216: Running command pulumi preview
    integration_python_acceptance_test.go:290: Run Error: exit status 255
    integration_python_acceptance_test.go:290: STDOUT: Previewing update (teststack):
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Creating virtual environment...
        @ previewing update.........
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Finished creating virtual environment
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Updating pip, setuptools, and wheel in virtual environment...
        @ previewing update....
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Requirement already satisfied: pip in /tmp/test-env3515876479/venv/lib/python3.8/site-packages (23.0.1)
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Collecting pip
            pulumi:pulumi:Stack pulumi-python-venv-teststack    Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Requirement already satisfied: setuptools in /tmp/test-env3515876479/venv/lib/python3.8/site-packages (56.0.0)
        @ previewing update....
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Collecting setuptools
            pulumi:pulumi:Stack pulumi-python-venv-teststack    Using cached setuptools-69.0.3-py3-none-any.whl (819 kB)
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Collecting wheel
            pulumi:pulumi:Stack pulumi-python-venv-teststack    Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
        @ previewing update....
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Installing collected packages: wheel, setuptools, pip
            pulumi:pulumi:Stack pulumi-python-venv-teststack    Attempting uninstall: setuptools
            pulumi:pulumi:Stack pulumi-python-venv-teststack      Found existing installation: setuptools 56.0.0
            pulumi:pulumi:Stack pulumi-python-venv-teststack      Uninstalling setuptools-56.0.0:
            pulumi:pulumi:Stack pulumi-python-venv-teststack        Successfully uninstalled setuptools-56.0.0
        @ previewing update....
            pulumi:pulumi:Stack pulumi-python-venv-teststack    Attempting uninstall: pip
            pulumi:pulumi:Stack pulumi-python-venv-teststack      Found existing installation: pip 23.0.1
            pulumi:pulumi:Stack pulumi-python-venv-teststack      Uninstalling pip-23.0.1:
            pulumi:pulumi:Stack pulumi-python-venv-teststack        Successfully uninstalled pip-23.0.1
        @ previewing update.....
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Successfully installed pip-23.3.2 setuptools-69.0.3 wheel-0.42.0
        @ previewing update....
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Finished updating
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Installing dependencies in virtual environment...
        @ previewing update.....
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Finished installing dependencies
        @ previewing update....
        
            pulumi:pulumi:Stack pulumi-python-venv-teststack  Traceback (most recent call last):
            pulumi:pulumi:Stack pulumi-python-venv-teststack    File "/home/runner/work/pulumi/pulumi/bin/pulumi-language-python-exec", line 16, in <module>
            pulumi:pulumi:Stack pulumi-python-venv-teststack      import pulumi
            pulumi:pulumi:Stack pulumi-python-venv-teststack  ModuleNotFoundError: No module named 'pulumi'
            pulumi:pulumi:Stack pulumi-python-venv-teststack  It looks like the Pulumi SDK has not been installed. Have you run pip install?
            pulumi:pulumi:Stack pulumi-python-venv-teststack  If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
            pulumi:pulumi:Stack pulumi-python-venv-teststack  error: an unhandled error occurred: program exited with non-zero exit code: 1
            pulumi:pulumi:Stack pulumi-python-venv-teststack  1 error; 6 messages
        Diagnostics:
          pulumi:pulumi:Stack (pulumi-python-venv-teststack):
            Traceback (most recent call last):
              File "/home/runner/work/pulumi/pulumi/bin/pulumi-language-python-exec", line 16, in <module>
                import pulumi
            ModuleNotFoundError: No module named 'pulumi'
            It looks like the Pulumi SDK has not been installed. Have you run pip install?
            If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
        
            error: an unhandled error occurred: program exited with non-zero exit code: 1
        
        
    integration_python_acceptance_test.go:290: STDERR: 
    integration_python_acceptance_test.go:290: Ran command pulumi args [preview] and expected success. Instead got failure.

=== FAIL: integration TestAutomaticVenvCreation (0.00s)
```

From https://github.com/pulumi/pulumi/actions/runs/7638225936/job/20809022315.  Keeping a few tests together here, since they all seem to have the same cause.

**Comment by tgummerer** [comment]
I remember trying to look at this, but I don't remember the outcome tbh.  According to [codecov test reports](https://app.codecov.io/gh/pulumi/pulumi/tests/master?term=TestAutomaticVenvCreation&historicalTrend=INTERVAL_30_DAY) it didn't fail in the last 30 days though, so I'm going to close this out.
