### ISSUE TITLE
"LocalWorkspace        runs through the stack lifecycle with multiple inline programs in parallel" is flaky

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#15239]
```
  1) LocalWorkspace
       runs through the stack lifecycle with multiple inline programs in parallel:
     CommandError: code: -2
 stdout: 
 stderr: Command failed with exit code 255: pulumi preview --exec-agent pulumi/pulumi/test --client=127.0.0.1:44727 --exec-kind auto.inline --event-log /tmp/automation-logs-preview-tb5Yu5/eventlog.txt --stack moolumi/inline_node/int_testb7a5b07a-d906-40b0-ad95-b5cf1cfc6639 --non-interactive
Previewing update (moolumi/int_testb7a5b07a-d906-40b0-ad95-b5cf1cfc6639)

View Live: https://app.pulumi.com/moolumi/inline_node/int_testb7a5b07a-d906-40b0-ad95-b5cf1cfc6639/previews/fdd909dc-4fb9-419b-ad5c-ccca4aee6668


    pulumi:pulumi:Stack inline_node-int_testb7a5b07a-d906-40b0-ad95-b5cf1cfc6639  error: One or more errors occurred
    pulumi:pulumi:Stack inline_node-int_testb7a5b07a-d906-40b0-ad95-b5cf1cfc6639  1 error
Diagnostics:
  pulumi:pulumi:Stack (inline_node-int_testb7a5b07a-d906-40b0-ad95-b5cf1cfc6639):
    error: One or more errors occurred


 err?: Error: Command failed with exit code 255: pulumi preview --exec-agent pulumi/pulumi/test --client=127.0.0.1:44727 --exec-kind auto.inline --event-log /tmp/automation-logs-preview-tb5Yu5/eventlog.txt --stack moolumi/inline_node/int_testb7a5b07a-d906-40b0-ad95-b5cf1cfc6639 --non-interactive
Previewing update (moolumi/int_testb7a5b07a-d906-40b0-ad95-b5cf1cfc6639)

View Live: https://app.pulumi.com/moolumi/inline_node/int_testb7a5b07a-d906-40b0-ad95-b5cf1cfc6639/previews/fdd909dc-4fb9-419b-ad5c-ccca4aee6668


    pulumi:pulumi:Stack inline_node-int_testb7a5b07a-d906-40b0-ad95-b5cf1cfc6639  error: One or more errors occurred
    pulumi:pulumi:Stack inline_node-int_testb7a5b07a-d906-40b0-ad95-b5cf1cfc6639  1 error
Diagnostics:
  pulumi:pulumi:Stack (inline_node-int_testb7a5b07a-d906-40b0-ad95-b5cf1cfc6639):
    error: One or more errors occurred



      at Object.createCommandError (automation/errors.ts:23:53)
      at /home/runner/work/pulumi/pulumi/sdk/nodejs/bin/automation/cmd.js:31:2256
      at Generator.throw (<anonymous>)
      at rejected (bin/automation/cmd.js:15:1011)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)



error Command failed with exit code 1.
```

From https://github.com/pulumi/pulumi/actions/runs/7633303481/job/20795449170

**Comment by tgummerer** [comment]
Adding a note here that @oskarwilliams was seeing the same issue in an automation API program they were running, so this isn't just a test issue.

**Comment by tgummerer** [comment]
I believe this has been fixed by https://github.com/pulumi/pulumi/commit/248d8d10c6d0870a8812d47e91ae6111c079df82.  Using https://github.com/pulumi/pulumi/pull/15656, we can see the error message, which matches what we were expecting to fix there: `One or more errors occurred: 14 UNAVAILABLE: No connection established. Last error: null`

@oskarwilliams could you confirm the pulumi version you were using where you were seeing these errors?  I believe it would have to be 3.103.x or earlier?

**Comment by oskarwilliams** [comment]
The version we were using was 3.103.1 yep, I am just testing now that we see it working with the updated package version (we are now using 3.109)
