### ISSUE TITLE
integration TestConstructComponentConfigureProviderPython is flaky

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#15240]
```
=== FAIL: integration TestConstructComponentConfigureProviderPython (82.07s)
    io.go:432: + set -euo pipefail
    io.go:432: + DONEFILE=.done
    io.go:432: ++ git rev-parse HEAD:./
    io.go:432: + EXPECTED_HASH=49c728ddf88a9e2e54f2c3b12774c4bee13ad097
    io.go:432: + BUILD=false
    io.go:432: + '[' -f .done ']'
    io.go:432: + echo 'Setup not marked done'
    io.go:432: Setup not marked done
    io.go:432: + BUILD=true
    io.go:432: ++ git status --porcelain .
    io.go:432: + output=
    io.go:432: + '[' -z '' ']'
    io.go:432: + echo 'Directory is clean'
    io.go:432: Directory is clean
    io.go:432: + true
    io.go:432: + setup_nodejs
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent ']'
    io.go:432: + setup_python
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent-python ']'
    io.go:432: + i=0
    io.go:432: + for step in setup_nodejs setup_python
    io.go:432: + builds[$***i***]=120
    io.go:432: + echo 'Started setup_nodejs with PID 120'
    io.go:432: Started setup_nodejs with PID 120
    io.go:432: + i=1
    io.go:432: + for step in setup_nodejs setup_python
    io.go:432: + setup_nodejs
    io.go:432: + builds[$***i***]=121
    io.go:432: + echo 'Started setup_python with PID 121'
    io.go:432: Started setup_python with PID 121
    io.go:432: + i=2
    io.go:432: + for build_pid in "$***builds[@]***"
    io.go:432: + echo 'Waiting for 120'
    io.go:432: Waiting for 120
    io.go:432: + wait 120
    io.go:432: + setup_python
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent ']'
    io.go:432: 
    io.go:432: real	0m0.013s
    io.go:432: user	0m0.015s
    io.go:432: sys	0m0.000s
    io.go:432: + for build_pid in "$***builds[@]***"
    io.go:432: + echo 'Waiting for 121'
    io.go:432: Waiting for 121
    io.go:432: + wait 121
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent-python ']'
    io.go:432: 
    io.go:432: real	0m0.017s
    io.go:432: user	0m0.000s
    io.go:432: sys	0m0.015s
    io.go:432: + echo 49c728ddf88a9e2e54f2c3b12774c4bee13ad097
    program.go:1906: sample: construct_component_configure_provider\python
    program.go:1911: pulumi: D:\a\pulumi\pulumi\bin\pulumi.exe
    command.go:34: **** Invoke 'C:\hostedtoolcache\windows\Python\3.11.7\x64\python.exe -m venv venv' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\python-venv.20240124-140004.9b651.log
    command.go:34: **** Invoke 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\venv\Scripts\python.exe -m pip install -r requirements.txt' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
Traceback (most recent call last):
  File "D:\a\pulumi\pulumi\scripts\go-test.py", line 99, in <module>
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\virtualenv-pip-install.20240124-140028.95b90.log
    command.go:34: **** Invoke 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\venv\Scripts\python.exe -m pip install -e D:\a\pulumi\pulumi\sdk\python\env\src' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\virtualenv-pip-install-package.20240124-140033.1982a.log
    command.go:34: **** Invoke 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\venv\Scripts\python.exe -m pip install -e D:\a\pulumi\pulumi\pkg\codegen\testing\test\testdata\methods-return-plain-resource\python' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\virtualenv-pip-install-package.20240124-140037.e83d4.log
    program.go:2056: projdir: C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557
    program.go:1321: Initializing project (dir C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557; stack p-it-fv-az1388--python-f9683ea7)
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe login' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\pulumi-login.20240124-140038.ee6ec.log
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe stack init moolumi/p-it-fv-az1388--python-f9683ea7' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\pulumi-stack-init.20240124-140038.07791.log
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe config set-all --plaintext proxy=FromEnv' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:106: Command completed without output
    program.go:1488: Performing primary preview and update
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe preview --non-interactive --diff' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\pulumi-preview-initial.20240124-140045.221c9.log
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe up --non-interactive --yes --skip-preview --event-log C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-events.json' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\pulumi-update-initial.20240124-140053.34c2e.log
    program.go:1498: Roundtripping checkpoint via stack export and stack import
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe stack export --file stack.json' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:106: Command completed without output
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe stack import --file stack.json' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:83: Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe stack import --file stack.json' failed: exit status 0xffffffff
error: constructing deployment for upload: serializing resources: failed to encrypt secret value: [404] Not Found: Stack 'p-it-fv-az1388--python-f9683ea7' not found

    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\pulumi-stack-import.20240124-140054.dc37b.log
    program.go:1446: Destroying stack
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557'
    command.go:83: Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview' failed: exit status 0xffffffff
Destroying (moolumi/p-it-fv-az1388--python-f9683ea7)

error: could not deserialize deployment: [404] Not Found: Stack 'p-it-fv-az1388--python-f9683ea7' not found

    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1388--python-f9683ea7-3829266557\command-output\pulumi-destroy.20240124-140055.39407.log
    program.go:1256: 
        	Error Trace:	D:/a/pulumi/pulumi/pkg/testing/integration/program.go:1256
        	            				D:/a/pulumi/pulumi/pkg/testing/integration/program.go:1267
        	Error:      	Received unexpected error:
        	            	[D:\a\pulumi\pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview] did not succeed after 1 tries
        	Test:       	TestConstructComponentConfigureProviderPython
    program.go:841: 
        	Error Trace:	D:/a/pulumi/pulumi/pkg/testing/integration/program.go:841
        	            				D:/a/pulumi/pulumi/tests/integration/integration_python_acceptance_test.go:239
        	Error:      	Received unexpected error:
        	            	running test preview, update, and edits: empty preview + update: exit status 0xffffffff
        	Test:       	TestConstructComponentConfigureProviderPython

DONE 5 tests, 1 failure in 120.930s
    sp.check_call(args, shell=False)
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gotestsum', '--jsonfile', 'D:\\a\\pulumi\\pulumi\\test-results\\f6382d3c-d203-49f0-8096-caf3e34d2f8c.json', '--packages', 'github.com/pulumi/pulumi/tests/integration', '--', '-count=1', '-cover', '-tags=all xplatform_acceptance', '-timeout', '1h', '-parallel=4', '-shuffle=off', '-p=1', '-race=false', '-run', '^(TestParentRename_issue13179|TestJSONOutput|TestConstructComponentConfigureProviderPython|TestEmptyNodeJS|TestRotatePassphrase)$', '-coverprofile=D:/a/pulumi/pulumi/coverage/go-test-75bf57d8.cov', '-coverpkg=github.com/pulumi/pulumi/pkg/v3/...,github.com/pulumi/pulumi/sdk/v3/...,github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3/...,github.com/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/v3/...,github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/v3/...']' returned non-zero exit status 1.
make: *** [Makefile:140: gotestsum/tests/integration] Error 1
::warning Retrying command
cd tests/integration && python 'D:/a/pulumi/pulumi/scripts/go-test.py' -count=1 -cover -tags="all xplatform_acceptance" -timeout 1h -parallel=2 -shuffle=off -p=1 -race=false  $***OPTS*** $***PKGS***
warning: no packages being tested depend on matches for pattern github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3/...
warning: no packages being tested depend on matches for pattern github.com/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/v3/...
warning: no packages being tested depend on matches for pattern github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/v3/...
heartbeat
Running: gotestsum --jsonfile D:\a\pulumi\pulumi\test-results\af055029-eb4d-49c5-a772-9a183f8c4f47.json --packages github.com/pulumi/pulumi/tests/integration -- -count=1 -cover -tags=all xplatform_acceptance -timeout 1h -parallel=2 -shuffle=off -p=1 -race=false -run ^(TestParentRename_issue13179|TestJSONOutput|TestConstructComponentConfigureProviderPython|TestEmptyNodeJS|TestRotatePassphrase)$ -coverprofile=D:/a/pulumi/pulumi/coverage/go-test-08c7e61f.cov -coverpkg=github.com/pulumi/pulumi/pkg/v3/...,github.com/pulumi/pulumi/sdk/v3/...,github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3/...,github.com/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/v3/...,github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/v3/...
heartbeat
heartbeat
✖  integration (26.921s) (coverage: 5.4% of statements in github.com/pulumi/pulumi/pkg/v3/..., github.com/pulumi/pulumi/sdk/v3/..., github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3/..., github.com/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/v3/..., github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/v3/...)
```

From https://github.com/pulumi/pulumi/actions/runs/7640630391/job/20817655285

**Comment by tgummerer** [comment]
This just flaked again:

```
```
=== FAIL: integration TestConstructComponentConfigureProviderPython (41.74s)
    io.go:432: + set -euo pipefail
    io.go:432: + DONEFILE=.done
    io.go:432: ++ git rev-parse HEAD:./
    io.go:432: + EXPECTED_HASH=c29ab0c8a2bb8a2947f9fbc4e0d52b8b59858250
    io.go:432: + BUILD=false
    io.go:432: + '[' -f .done ']'
    io.go:432: + echo 'Setup not marked done'
    io.go:432: Setup not marked done
    io.go:432: + BUILD=true
    io.go:432: ++ git status --porcelain .
    io.go:432: + output=
    io.go:432: + '[' -z '' ']'
    io.go:432: + echo 'Directory is clean'
    io.go:432: Directory is clean
    io.go:432: + true
    io.go:432: + setup_nodejs
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent ']'
    io.go:432: + setup_python
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent-python ']'
    io.go:432: + i=0
    io.go:432: + for step in setup_nodejs setup_python
    io.go:432: + builds[$***i***]=288
    io.go:432: + echo 'Started setup_nodejs with PID 288'
    io.go:432: Started setup_nodejs with PID 288
    io.go:432: + i=1
    io.go:432: + for step in setup_nodejs setup_python
    io.go:432: + setup_nodejs
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent ']'
Traceback (most recent call last):
  File "D:\a\pulumi\pulumi\scripts\go-test.py", line 99, in <module>
    io.go:432: + builds[$***i***]=290
    io.go:432: + echo 'Started setup_python with PID 290'
    io.go:432: Started setup_python with PID 290
    io.go:432: + i=2
    io.go:432: + for build_pid in "$***builds[@]***"
    io.go:432: + echo 'Waiting for 288'
    io.go:432: Waiting for 288
    io.go:432: + wait 288
    io.go:432: 
    io.go:432: real	0m0.013s
    io.go:432: user	0m0.015s
    io.go:432: sys	0m0.000s
    io.go:432: + setup_python
    io.go:432: + for build_pid in "$***builds[@]***"
    io.go:432: + echo 'Waiting for 290'
    io.go:432: Waiting for 290
    io.go:432: + wait 290
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent-python ']'
    io.go:432: 
    io.go:432: real	0m0.011s
    io.go:432: user	0m0.000s
    io.go:432: sys	0m0.015s
    io.go:432: + echo c29ab0c8a2bb8a2947f9fbc4e0d52b8b59858250
    program.go:1925: sample: construct_component_configure_provider\python
    program.go:1930: pulumi: D:\a\pulumi\pulumi\bin\pulumi.exe
    command.go:34: **** Invoke 'C:\hostedtoolcache\windows\Python\3.12.1\x64\python.exe -m venv venv' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916\command-output\python-venv.20240207-185516.7c63d.log
    command.go:34: **** Invoke 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916\venv\Scripts\python.exe -m pip install -r requirements.txt' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916\command-output\virtualenv-pip-install.20240207-185523.ad0a1.log
    command.go:34: **** Invoke 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916\venv\Scripts\python.exe -m pip install -e D:\a\pulumi\pulumi\sdk\python\env\src' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916\command-output\virtualenv-pip-install-package.20240207-185529.b35a6.log
    command.go:34: **** Invoke 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916\venv\Scripts\python.exe -m pip install -e D:\a\pulumi\pulumi\pkg\codegen\testing\test\testdata\methods-return-plain-resource\python' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916\command-output\virtualenv-pip-install-package.20240207-185536.72086.log
    program.go:2075: projdir: C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916
    program.go:1326: Initializing project (dir C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916; stack p-it-fv-az1258--python-0202ec77)
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe login' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916\command-output\pulumi-login.20240207-185536.3d428.log
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe stack init moolumi/p-it-fv-az1258--python-0202ec77' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916\command-output\pulumi-stack-init.20240207-185537.eb8b8.log
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe config set-all --plaintext proxy=FromEnv' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916'
    command.go:106: Command completed without output
    program.go:1493: Performing primary preview and update
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe preview --non-interactive --diff' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916'
    command.go:83: Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe preview --non-interactive --diff' failed: exit status 0xffffffff
Previewing update (moolumi/p-it-fv-az1258--python-0202ec77)

View Live: https://app.pulumi.com/moolumi/construct_component_configure_provider/p-it-fv-az1258--python-0202ec77/previews/81686c58-3250-488c-a6f9-c2da8f791076

+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:p-it-fv-az1258--python-0202ec77::construct_component_configure_provider::pulumi:pulumi:Stack::construct_component_configure_provider-p-it-fv-az1258--python-0202ec77]
error: no resource plugin 'pulumi-resource-tls' found in the workspace at version v4.10.0 or on your $PATH
Resources:
    + 1 to create

    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916\command-output\pulumi-preview-initial.20240207-185544.028a9.log
    program.go:1451: Destroying stack
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916\command-output\pulumi-destroy.20240207-185545.a6bb6.log
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe stack rm --yes' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916'
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az1258--python-0202ec77-824354916\command-output\pulumi-stack-rm.20240207-185545.76bf1.log
    program.go:846: 
        	Error Trace:	D:/a/pulumi/pulumi/pkg/testing/integration/program.go:846
        	            				D:/a/pulumi/pulumi/tests/integration/integration_python_acceptance_test.go:239
        	Error:      	Received unexpected error:
        	            	running test preview, update, and edits: initial failure: [D:\a\pulumi\pulumi\bin\pulumi.exe preview --non-interactive --diff] did not succeed after 1 tries
        	Test:       	TestConstructComponentConfigureProviderPython
```

**Comment by justinvp** [comment]
This test is now consistently failing on macOS:

https://github.com/pulumi/pulumi/actions/runs/7908712209/job/21588589686#step:38:214

```
=== FAIL: integration TestConstructComponentConfigureProviderPython (174.27s)
    io.go:432: + set -euo pipefail
    io.go:432: + DONEFILE=.done
    io.go:432: ++ git rev-parse HEAD:./
    io.go:432: + EXPECTED_HASH=236859ec8f83be4c605dfc131ed8bfc521a25884
    io.go:432: + BUILD=false
    io.go:432: + '[' -f .done ']'
    io.go:432: + echo 'Setup not marked done'
    io.go:432: Setup not marked done
    io.go:432: + BUILD=true
    io.go:432: ++ git status --porcelain .
    io.go:432: + output=
    io.go:432: + '[' -z '' ']'
    io.go:432: + echo 'Directory is clean'
    io.go:432: Directory is clean
    io.go:432: + true
    io.go:432: + setup_nodejs
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent ']'
    io.go:432: + setup_python
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent-python ']'
    io.go:432: + i=0
    io.go:432: + for step in setup_nodejs setup_python
    io.go:432: + builds[$***i***]=4311
    io.go:432: + echo 'Started setup_nodejs with PID 4311'
    io.go:432: Started setup_nodejs with PID 4311
    io.go:432: + i=1
    io.go:432: + for step in setup_nodejs setup_python
    io.go:432: + builds[$***i***]=4312
    io.go:432: + echo 'Started setup_python with PID 4312'
    io.go:432: Started setup_python with PID 4312
    io.go:432: + i=2
    io.go:432: + for build_pid in '"$***builds[@]***"'
    io.go:432: + echo 'Waiting for 4311'
    io.go:432: Waiting for 4311
    io.go:432: + wait 4311
    io.go:432: + setup_nodejs
    io.go:432: + setup_python
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent ']'
    io.go:432: 
    io.go:432: real	0m0.028s
    io.go:432: user	0m0.000s
    io.go:432: sys	0m0.001s
    io.go:432: + set -euo pipefail
    io.go:432: + '[' -d testcomponent-python ']'
    io.go:432: + for build_pid in '"$***builds[@]***"'
    io.go:432: + echo 'Waiting for 4312'
    io.go:432: Waiting for 4312
    io.go:432: + wait 4312
    io.go:432: 
    io.go:432: real	0m0.023s
    io.go:432: user	0m0.000s
    io.go:432: sys	0m0.001s
    io.go:432: + echo 236859ec8f83be4c605dfc131ed8bfc521a25884
    program.go:1925: sample: construct_component_configure_provider/python
    program.go:1930: pulumi: /Users/runner/work/pulumi/pulumi/bin/pulumi
    command.go:34: **** Invoke '/Users/runner/hostedtoolcache/Python/3.12.1/x64/bin/python3 -m venv venv' in '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939'
    command.go:106: Command completed without output
    command.go:34: **** Invoke '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939/venv/bin/python -m pip install -r requirements.txt' in '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939'
    command.go:103: Wrote output to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939/command-output/virtualenv-pip-install.20240214-234133.ab419.log
    command.go:34: **** Invoke '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939/venv/bin/python -m pip install -e /Users/runner/work/pulumi/pulumi/sdk/python/env/src' in '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939'
    command.go:103: Wrote output to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939/command-output/virtualenv-pip-install-package.20240214-234235.bed33.log
    command.go:34: **** Invoke '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939/venv/bin/python -m pip install -e /Users/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/methods-return-plain-resource/python' in '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939'
    command.go:103: Wrote output to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939/command-output/virtualenv-pip-install-package.20240214-234256.e0aa6.log
    program.go:2075: projdir: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939
    program.go:1326: Initializing project (dir /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939; stack p-it-mac-170795-python-dff5ef4b)
    command.go:34: **** Invoke '/Users/runner/work/pulumi/pulumi/bin/pulumi login' in '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939'
    command.go:103: Wrote output to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939/command-output/pulumi-login.20240214-234257.40832.log
    command.go:34: **** Invoke '/Users/runner/work/pulumi/pulumi/bin/pulumi stack init moolumi/p-it-mac-170795-python-dff5ef4b' in '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939'
    command.go:103: Wrote output to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939/command-output/pulumi-stack-init.20240214-234257.68c79.log
    command.go:34: **** Invoke '/Users/runner/work/pulumi/pulumi/bin/pulumi config set-all --plaintext proxy=FromEnv' in '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939'
    command.go:106: Command completed without output
    program.go:1493: Performing primary preview and update
    command.go:34: **** Invoke '/Users/runner/work/pulumi/pulumi/bin/pulumi preview --non-interactive --diff' in '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939'
    command.go:83: Invoke '/Users/runner/work/pulumi/pulumi/bin/pulumi preview --non-interactive --diff' failed: exit status 255
Previewing update (moolumi/p-it-mac-170795-python-dff5ef4b)

View Live: https://app.pulumi.com/moolumi/construct_component_configure_provider/p-it-mac-170795-python-dff5ef4b/previews/3a606a11-1e78-4a1e-bb5b-130e98358082

+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:p-it-mac-170795-python-dff5ef4b::construct_component_configure_provider::pulumi:pulumi:Stack::construct_component_configure_provider-p-it-mac-170795-python-dff5ef4b]
go: downloading github.com/pulumi/pulumi-tls/sdk/v4 v4.10.0

    + metaprovider:index:Configurer: (create)
        [urn=urn:pulumi:p-it-mac-170795-python-dff5ef4b::construct_component_configure_provider::metaprovider:index:Configurer::configurer]
error: no resource plugin 'pulumi-resource-tls' found in the workspace at version v4.10.0 or on your $PATH
Resources:
    + 2 to create

    command.go:103: Wrote output to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939/command-output/pulumi-preview-initial.20240214-234314.68ae3.log
    program.go:1451: Destroying stack
    command.go:34: **** Invoke '/Users/runner/work/pulumi/pulumi/bin/pulumi destroy --non-interactive --yes --skip-preview' in '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939'
    command.go:103: Wrote output to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939/command-output/pulumi-destroy.20240214-234316.e8a15.log
    command.go:34: **** Invoke '/Users/runner/work/pulumi/pulumi/bin/pulumi stack rm --yes' in '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939'
    command.go:103: Wrote output to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/p-it-mac-170795-python-dff5ef4b-1036260939/command-output/pulumi-stack-rm.20240214-234317.71836.log
    program.go:846: 
        	Error Trace:	/Users/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:846
        	            				/Users/runner/work/pulumi/pulumi/tests/integration/integration_python_acceptance_test.go:239
        	Error:      	Received unexpected error:
        	            	running test preview, update, and edits: initial failure: [/Users/runner/work/pulumi/pulumi/bin/pulumi preview --non-interactive --diff] did not succeed after 1 tries
        	Test:       	TestConstructComponentConfigureProviderPython
```

It's blocking the v3.106.0 release

**Comment by justinvp** [comment]
I've temporarily skipped this test on macOS to unblock the release. This issue tracks addressing the underlying problem and unskipping.

**Comment by tgummerer** [comment]
From the `os.Rename` docs: "Even within the same directory, on non-Unix platforms Rename is not an atomic operation."

For programtests we do a `pulumi login` for every test with the same directory.  I wonder if the issue here is a race condition where we try to do an operation in a program test, and at the same time a `pulumi login` in a different one.  Since `pulumi login` then uses `os.Rename`, which isn't an atomic operation on Windows, that could result in `error: could not deserialize deployment: [404] Not Found: Stack 'p-it-fv-az1388--python-f9683ea7' not found`.  It's hard to prove this out though.
