### ISSUE TITLE
Go: ReadResource doesn't work

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1530]
I get a panic when I try to use `get` in Go:

```
$ pulumi update
Previewing update of stack 'get-go'
Previewing changes:

     Type                 Name           Plan       Info
 +   pulumi:pulumi:Stack  get-go-get-go  create
panic: fatal: An assertion has failed

goroutine 65 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(0x1a21951, 0x17)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xe9
github.com/pulumi/pulumi/pkg/util/contract.Assert(0xc420715100)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26 +0x49
github.com/pulumi/pulumi/pkg/resource/plugin.(*provider).Read(0xc420568960, 0xc42003afa0, 0x4b, 0x0, 0x0, 0xc4204d8510, 0x0, 0xc420362330, 0x28)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/resource/plugin/provider_plugin.go:293 +0x5a
github.com/pulumi/pulumi/pkg/resource/deploy.(*resmon).ReadResource(0xc420256780, 0x1af6be0, 0xc420454900, 0xc420568460, 0xc420256780, 0x1, 0x1)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/source_eval.go:326 +0x5e4
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_ReadResource_Handler.func1(0x1af6be0, 0xc420454900, 0x198d1a0, 0xc420568460, 0x1af6be0, 0xc420454900, 0x1afdc40, 0x1fedaf0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:350 +0x86
github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1af6be0, 0xc420454900, 0x198d1a0, 0xc420568460, 0xc4205acb00, 0xc4205acb20, 0x0, 0x0, 0x1ae9b40, 0xc42007b0c0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x309
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_ReadResource_Handler(0x1951420, 0xc420256780, 0x1af6be0, 0xc420454810, 0xc4200e9570, 0xc42059c3e0, 0x0, 0x0, 0x7073656c6c696777, 0x72732f6f672f6569)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:352 +0x167
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc42067a160, 0x1afaac0, 0xc4204c2f00, 0xc4203bd400, 0xc420335530, 0x1fbec58, 0x0, 0x0, 0x0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:923 +0x889
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42067a160, 0x1afaac0, 0xc4204c2f00, 0xc4203bd400, 0x0)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:1148 +0x1318
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4205b0420, 0xc42067a160, 0x1afaac0, 0xc4204c2f00, 0xc4203bd400)
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/swgillespie/go/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:635 +0xa1
```

**Comment by swgillespie** [comment]
Go support is out of scope for M21.

**Comment by EvanBoyle** [comment]
[This test ](https://github.com/pulumi/pulumi/commit/55310b2ac25ccb770ba27557e2e3282b4dac5516)should theoretically hit this issue, but it passes. 

This may have been fixed elsewhere. Closing out for now. Will re-open if we get a repro.

**Comment by EvanBoyle** [comment]
Discovered the issue through some digging during my work propagating parent resources through resource operations.
