### ISSUE TITLE
`pulumi state edit` panics

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#15345]
### What happened?

I was trying to use `pulumi state edit` to view my stack state in my editor. It did not work. 😢 

### Example

This is a minimal repro, but I believe that this occurs for all stacks.

```bash
mkdir repro && cd repro
pulumi new yaml # Run through stack creation
pulumi state edit # 💣 
```

### Output of `pulumi about`

```
CLI          
Version      3.104.1-dev.0
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME  VERSION
aws   unknown
yaml  unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in yaml

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ian-pulumi-corp
User           ian-pulumi-corp
Organizations  ian-pulumi-corp, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default
```

### Additional context

The stack trace looks like this:

```
𝛌 pu state edit
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   3.104.1-dev.0
Go Version:       go1.21.6
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/runtime/debug/stack.go:24 +0x64
main.panicHandler(0x14000de5eff)
	/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:35 +0x44
panic({0x1034c5180?, 0x104db5fb0?})
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/runtime/panic.go:914 +0x218
github.com/opentracing/opentracing-go.SpanFromContext({0x0?, 0x0?})
	/Users/ianwahbe/go/pkg/mod/github.com/opentracing/opentracing-go@v1.2.0/gocontext.go:27 +0x20
github.com/opentracing/opentracing-go.StartSpanFromContextWithTracer({0x0, 0x0}, {0x1038fc900, 0x104e42460}, {0x102a06226, 0x15}, {0x0, 0x0, 0x0})
	/Users/ianwahbe/go/pkg/mod/github.com/opentracing/opentracing-go@v1.2.0/gocontext.go:60 +0x44
github.com/opentracing/opentracing-go.StartSpanFromContext(...)
	/Users/ianwahbe/go/pkg/mod/github.com/opentracing/opentracing-go@v1.2.0/gocontext.go:49
github.com/pulumi/pulumi/pkg/v3/backend/httpstate/client.(*Client).ExportStackDeployment(0x14001edc3f0, {0x0?, 0x0?}, {{0x14001eecf78, 0x6}, {0x14001eecff8, 0x3}, {{0x14001eecf83, 0x3}}}, 0x0)
	/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/backend/httpstate/client/client.go:550 +0x98
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).exportDeployment(0x14001e25770, {0x0, 0x0}, {0x1039003a8?, 0x14000de5a00?}, 0x1026b6900?)
	/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:1561 +0xb8
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getSnapshot(0x104e42460?, {0x0, 0x0}, {0x1038d9a20, 0x104e42460}, {0x1039003a8?, 0x14000de5a00?})
	/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/backend/httpstate/state.go:217 +0x40
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Snapshot(0x14001e5bf10, {0x0, 0x0}, {0x1038d9a20, 0x104e42460})
	/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/backend/httpstate/stack.go:145 +0xb0
main.(*stateEditCmd).Run(0x14001e2d300, {0x103916f70, 0x14001e5bf10})
	/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state_edit.go:134 +0xe4
main.newStateEditCommand.func1(0x14001e84f00, {0x0?, 0x0?, 0x0?})
	/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state_edit.go:65 +0xb8
main.newStateEditCommand.RunResultFunc.func2(0x14001ebb200?, {0x104e42460, 0x0, 0x0})
	/Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:115 +0x34
github.com/spf13/cobra.(*Command).execute(0x14001e84f00, {0x104e42460, 0x0, 0x0})
	/Users/ianwahbe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x654
github.com/spf13/cobra.(*Command).ExecuteC(0x14001bdb800)
	/Users/ianwahbe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ianwahbe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:56 +0x54
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
@iwahbe did this used to work? I moved some context code the other day, so just a little concerned that maybe that broke the tracing setup here.

**Comment by iwahbe** [comment]
This used to work.

**Comment by Frassle** [comment]
Thank for confirming. I'll take a look.

**Comment by Frassle** [comment]
Found it, we removed a context field at https://github.com/pulumi/pulumi/pull/15312/files#diff-23d8fe86d0e387f31e0286f6f45a3b86f4cb899cc1e5948511da08dc227b92d5L41 but didn't pass it as a method arg instead. Looks to be the only case in that PR where we made that mistake. I'll get a fix in soon.
