### ISSUE TITLE
Go codegen panics for type `Map<Array<string>>`

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#15478]
Version: 3.105.0

## Stack trace

```
Generating go...
panic: fatal: An assertion has failed: tok: string

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.105.0/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0xd2?, {0x105973813?, 0x105f00b18?}, {0x14006c9f5a8?, 0x0?, 0x1?})
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.105.0/go/common/util/contract/assert.go:35 +0xe0
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*pkgContext).tokenToType(0x140020c4d80, {0x1059712d2, 0x6})
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/codegen/go/gen.go:213 +0x9c
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*pkgContext).nestedTypeToType(0x1401486ff10?, {0x1063871f8?, 0x106f45038?})
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/codegen/go/gen.go:3398 +0x168
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*pkgContext).nestedTypeToType(0x14006c9f6f8?, {0x106387108?, 0x1401484e0c0?})
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/codegen/go/gen.go:3390 +0x98
github.com/pulumi/pulumi/pkg/v3/codegen/go.(*pkgContext).collectNestedCollectionTypes(0x140020c4d80, 0x14006c9f910, {0x1063870e0?, 0x140148f93e0?})
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/codegen/go/gen.go:3315 +0x13c
github.com/pulumi/pulumi/pkg/v3/codegen/go.generateTypes({0x106379c88, 0x1400b1b0060}, 0x140020c4d80, {0x1400c6740c0, 0x6, 0x8}, {0x1400689c000, 0x2d, 0x0?}, 0x0)
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/codegen/go/gen.go:4883 +0x1fc
github.com/pulumi/pulumi/pkg/v3/codegen/go.GeneratePackage({0x105994dd5, 0x18}, 0x1401398ad80)
        /Users/dan/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.105.0/codegen/go/gen.go:4797 +0x2388
main.generate(0x105978c81?, {0x16b5834d0, 0x2})
        /Users/dan/Dev/pulumi-aws-native/provider/cmd/pulumi-gen-aws-native/main.go:298 +0x94
main.emitPackage(0x140112077a0?, {0x16b5834d0, 0x2}, {0x14014607c38, 0x6})
        /Users/dan/Dev/pulumi-aws-native/provider/cmd/pulumi-gen-aws-native/main.go:313 +0x94
main.main()
        /Users/dan/Dev/pulumi-aws-native/provider/cmd/pulumi-gen-aws-native/main.go:93 +0x658
make: *** [local_generate] Error 2
```

## Type definition to repro:

```json
{
    "types": {
        "aws-native:inspectorv2:CisScanConfigurationCisTargets": {
            "properties": {
                "accountIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "targetResourceTags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "type": "object",
            "required": [
                "accountIds"
            ]
        }
    }
}
```

**Comment by danielrbradley** [comment]
This appears to be the offending piece of code: https://github.com/pulumi/pulumi/blob/14e78f559808e59fec11941f16bb6f45ee058a06/pkg/codegen/go/gen.go#L3298-L3302

It only checks if the type within the array is primative, but not if it's a collection of primatives. It assumes that any non-primative item type must be a named type and not a nested collection.

This pattern is also repeated for handling MapType too just below.

**Comment by Frassle** [comment]
Ah right so the issue is we need to generate new "primitive" types for these nested structures because we now need things like `pulumi.StringArrayArrayOutput`.

I'm am very inclined to say this should be deferred till generics and we can do this sensibly. Can aws work around this limitation, or do we really need to generate types like `pulumi.StringArrayArrayArrayOutput`?

**Comment by Frassle** [comment]
That was my plan, trying to track down the same repro that aws was hitting. I think the repro I got was a larger type than what aws had so the error fix I had would have still panic'd for aws.

**Comment by Zaid-Ajaj** [comment]
While looking into this again, I am unable to reproduce any panic for nested arrays or maps in go. `Map<Array<string>>` even compiles just fine. 

Combinations with deep nesting such as `Map<Array<Array<string>>>` or `Array<Array<Array<string>>>` don't compile because of the missing types in the code Pulumi SDK such as `pulumi.StringArrayArrayArray(Input|Output)` but they generate code nonetheless
