### ISSUE TITLE
Test failure: TypeError: LRU is not a constructor

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#15528]
A couple PRs (https://github.com/pulumi/pulumi/pull/15495 and https://github.com/pulumi/pulumi/pull/15488) failed to merge with the same error during codegen/nodejs tests:

https://github.com/pulumi/pulumi/actions/runs/8071461724/job/22051387749#step:38:267

```
=== FAIL: codegen/nodejs TestGeneratePackageTwo/output-funcs/nodejs/test (74.21s)
    gen_test.go:148: Found yarn commands in ../testing/test/testdata/output-funcs/nodejs: [_mocha acorn esparse esvalidate flat he js-yaml mkdirp mocha node-which proto-loader-gen-types resolve rimraf semver ts-node ts-node-cwd ts-node-esm ts-node-script ts-node-transpile-only ts-script tsc tsserver]
    command.go:34: **** Invoke '/opt/hostedtoolcache/node/21.6.2/x64/bin/yarn run mocha --require ts-node/register tests/**/*.spec.ts' in '/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs'
    command.go:83: Invoke '/opt/hostedtoolcache/node/21.6.2/x64/bin/yarn run mocha --require ts-node/register tests/**/*.spec.ts' failed: exit status 1
    command.go:106: Command completed without output
    helpers.go:352: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/helpers.go:352
        	            				/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/helpers.go:328
        	            				/home/runner/work/pulumi/pulumi/pkg/codegen/nodejs/gen_test.go:87
        	            				/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/sdk_driver.go:605
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestGeneratePackageTwo/output-funcs/nodejs/test
    helpers.go:356: stdout: yarn run v1.22.21
        $ /home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/.bin/mocha --require ts-node/register 'tests/**/*.spec.ts'
        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    helpers.go:359: stderr: warning package.json: No license field
        warning Waiting for the other yarn instance to finish (36318)
        warning Waiting for the other yarn instance to finish (36250)
        warning Waiting for the other yarn instance to finish (36361)
        warning Waiting for the other yarn instance to finish (36378)
        warning Waiting for the other yarn instance to finish (36472)
        
        TypeError: LRU is not a constructor
            at Object.<anonymous> (/home/runner/work/pulumi/pulumi/sdk/nodejs/bin/node_modules/hosted-git-info/index.js:6:15)
            at Module._compile (node:internal/modules/cjs/loader:1378:14)
            at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
            at Object.require.extensions.<computed> [as .js] (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/ts-node/src/index.ts:1608:43)
            at Module.load (node:internal/modules/cjs/loader:1212:32)
            at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
            at Module.require (node:internal/modules/cjs/loader:1237:19)
            at require (node:internal/modules/helpers:176:18)
            at Object.<anonymous> (/home/runner/work/pulumi/pulumi/sdk/nodejs/bin/node_modules/normalize-package-data/lib/fixer.js:4:21)
            at Module._compile (node:internal/modules/cjs/loader:1378:14)
            at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
            at Object.require.extensions.<computed> [as .js] (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/ts-node/src/index.ts:1608:43)
            at Module.load (node:internal/modules/cjs/loader:1212:32)
            at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
            at Module.require (node:internal/modules/cjs/loader:1237:19)
            at require (node:internal/modules/helpers:176:18)
            at Object.<anonymous> (/home/runner/work/pulumi/pulumi/sdk/nodejs/bin/node_modules/normalize-package-data/lib/normalize.js:3:13)
            at Module._compile (node:internal/modules/cjs/loader:1378:14)
            at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
            at Object.require.extensions.<computed> [as .js] (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/ts-node/src/index.ts:1608:43)
            at Module.load (node:internal/modules/cjs/loader:1212:32)
            at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
            at Module.require (node:internal/modules/cjs/loader:1237:19)
            at require (node:internal/modules/helpers:176:18)
            at Object.<anonymous> (/home/runner/work/pulumi/pulumi/sdk/nodejs/runtime/closure/codePaths.ts:17:1)
            at Module._compile (node:internal/modules/cjs/loader:1378:14)
            at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
            at Object.require.extensions.<computed> [as .js] (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/ts-node/src/index.ts:1608:43)
            at Module.load (node:internal/modules/cjs/loader:1212:32)
            at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
            at Module.require (node:internal/modules/cjs/loader:1237:19)
            at require (node:internal/modules/helpers:176:18)
            at Object.<anonymous> (/home/runner/work/pulumi/pulumi/sdk/nodejs/runtime/index.ts:22:1)
            at Module._compile (node:internal/modules/cjs/loader:1378:14)
            at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
            at Object.require.extensions.<computed> [as .js] (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/ts-node/src/index.ts:1608:43)
            at Module.load (node:internal/modules/cjs/loader:1212:32)
            at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
            at Module.require (node:internal/modules/cjs/loader:1237:19)
            at require (node:internal/modules/helpers:176:18)
            at Object.<anonymous> (/home/runner/work/pulumi/pulumi/sdk/nodejs/index.ts:34:1)
            at Module._compile (node:internal/modules/cjs/loader:1378:14)
            at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
            at Object.require.extensions.<computed> [as .js] (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/ts-node/src/index.ts:1608:43)
            at Module.load (node:internal/modules/cjs/loader:1212:32)
            at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
            at Module.require (node:internal/modules/cjs/loader:1237:19)
            at require (node:internal/modules/helpers:176:18)
            at Object.<anonymous> (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/tests/codegen.spec.ts:17:1)
            at Module._compile (node:internal/modules/cjs/loader:1378:14)
            at Module.m._compile (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/ts-node/src/index.ts:1618:23)
            at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
            at Object.require.extensions.<computed> [as .ts] (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/ts-node/src/index.ts:1621:12)
            at Module.load (node:internal/modules/cjs/loader:1212:32)
            at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
            at Module.require (node:internal/modules/cjs/loader:1237:19)
            at require (node:internal/modules/helpers:176:18)
            at Object.exports.requireOrImport (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/mocha/lib/nodejs/esm-utils.js:53:16)
            at async Object.exports.loadFilesAsync (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
            at async singleRun (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/mocha/lib/cli/run-helpers.js:125:3)
            at async Object.exports.handler (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/output-funcs/nodejs/node_modules/mocha/lib/cli/run.js:370:5)
        error Command failed with exit code 1.
```

https://github.com/pulumi/pulumi/actions/runs/8070873897/job/22049389099#step:38:349

```
=== FAIL: codegen/nodejs TestGeneratePackageOne/simple-resource-schema/nodejs/test (72.94s)
    gen_test.go:148: Found yarn commands in ../testing/test/testdata/simple-resource-schema/nodejs: [_mocha acorn esparse esvalidate flat he js-yaml mkdirp mocha node-which proto-loader-gen-types resolve rimraf semver ts-node ts-node-cwd ts-node-esm ts-node-script ts-node-transpile-only ts-script tsc tsserver]
            at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
            at Object.require.extensions.<computed> [as .js] (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/node_modules/ts-node/src/index.ts:1608:43)
            at Module.load (node:internal/modules/cjs/loader:1212:32)
            at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
            at Module.require (node:internal/modules/cjs/loader:1237:19)
            at require (node:internal/modules/helpers:176:18)
            at Object.<anonymous> (/home/runner/work/pulumi/pulumi/sdk/nodejs/runtime/index.ts:22:1)
            at Module._compile (node:internal/modules/cjs/loader:1378:14)
            at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
            at Object.require.extensions.<computed> [as .js] (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/node_modules/ts-node/src/index.ts:1608:43)
            at Module.load (node:internal/modules/cjs/loader:1212:32)
            at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
            at Module.require (node:internal/modules/cjs/loader:1237:19)
            at require (node:internal/modules/helpers:176:18)
            at Object.<anonymous> (/home/runner/work/pulumi/pulumi/sdk/nodejs/index.ts:34:1)
            at Module._compile (node:internal/modules/cjs/loader:1378:14)
            at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
            at Object.require.extensions.<computed> [as .js] (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/node_modules/ts-node/src/index.ts:1608:43)
            at Module.load (node:internal/modules/cjs/loader:1212:32)
            at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
            at Module.require (node:internal/modules/cjs/loader:1237:19)
            at require (node:internal/modules/helpers:176:18)
Traceback (most recent call last):
  File "/home/runner/work/pulumi/pulumi/scripts/go-test.py", line 99, in <module>
    sp.check_call(args, shell=False)
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/subprocess.py", line 413, in check_call
            at Object.<anonymous> (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/tests/codegen.spec.ts:15:1)
            at Module._compile (node:internal/modules/cjs/loader:1378:14)
            at Module.m._compile (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/node_modules/ts-node/src/index.ts:1618:23)
            at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
            at Object.require.extensions.<computed> [as .ts] (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/node_modules/ts-node/src/index.ts:1621:12)
            at Module.load (node:internal/modules/cjs/loader:1212:32)
            at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
            at Module.require (node:internal/modules/cjs/loader:1237:19)
            at require (node:internal/modules/helpers:176:18)
            at Object.exports.requireOrImport (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/node_modules/mocha/lib/nodejs/esm-utils.js:53:16)
            at async Object.exports.loadFilesAsync (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
            at async singleRun (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/node_modules/mocha/lib/cli/run-helpers.js:125:3)
            at async Object.exports.handler (/home/runner/work/pulumi/pulumi/pkg/codegen/testing/test/testdata/simple-resource-schema/nodejs/node_modules/mocha/lib/cli/run.js:370:5)
        error Command failed with exit code 1.
```

Not sure if this is a test issue or product issue.

**Comment by t0yv0** [comment]
@EronWright brought up that some provider tests may be implicated here, please let us know if we can assist in any way.
