### ISSUE TITLE
Panic seen when Pulumi Preview is called on the cli

### ISSUE THREAD

**Issue by prramineni** [pulumi/pulumi#15547]
**What happened?**
Using pulumi open source community edition. 
When calling pulumi preview, before creating gke cluster, we are seeing a panic. The stack trace is as below.
Could someone take a look from pulumi's end?

```
Pulumi Version:   v3.75.0
Go Version:       go1.20.5
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            attempt to decrypt value

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler(0xc00158ff47)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:35 +0x47
panic({0x1ef13c0, 0x28d4610})
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:884 +0x213
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.panicCrypter.DecryptValue(...)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/crypt.go:143
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializePropertyValue({0x1fd7fa0?, 0xc0014bb530?}, {0x7ff804618628?, 0x3a19450?}, {0x7ff8045d5e58, 0x3a19450})
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:611 +0x8ee
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeProperties(0xc0002d41e0?, {0x7ff804618628, 0x3a19450}, {0x7ff8045d5e58, 0x3a19450})
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:536 +0xeb
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializePropertyValue({0x1fd7fa0?, 0xc0014bb4d0?}, {0x7ff804618628?, 0x3a19450?}, {0x7ff8045d5e58, 0x3a19450})
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:572 +0x205
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeProperties(0x256?, {0x7ff804618628, 0x3a19450}, {0x7ff8045d5e58, 0x3a19450})
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:536 +0xeb
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeResource({{0xc0005fe3f0, 0x62}, 0x1, 0x0, {0xc000b0a000, 0x50}, {0xc000b10200, 0x1d}, 0xc0014baed0, 0xc0014bb1d0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:495 +0xa5
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeDeploymentV3({0x28f7060, 0xc00005e060}, {{{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:264 +0x3a7
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeUntypedDeployment({0x28f7060, 0xc00005e060}, 0xc0005b3bc0, {0x28ddba0, 0x3a18d60})
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:198 +0x45f
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getSnapshot(0x58?, {0x28f7060, 0xc00005e060}, {0x28ddba0, 0x3a18d60}, {0x28f89c0?, 0xc000636e40?})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:221 +0x66
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getTarget(0xc0008d0fc0?, {0x28f7060, 0xc00005e060}, {0x28ddba0, 0x3a18d60}, {0x28f89c0, 0xc000636e40}, 0xc00092a750, {0x7ff804618628, 0x3a19450})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:237 +0x10b
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).newUpdate(_, {_, _}, {_, _}, {0xc000c100b0, {0xc0002562d0, 0x19}, {0x0, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:195 +0x21f
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc000c100b0, {0xc0002562d0, 0x19}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1162 +0x133
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc000c100b0, {0xc0002562d0, 0x19}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1136 +0x5ab
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Preview(_, {_, _}, {_, _}, {0xc000c100b0, {0xc0002562d0, 0x19}, {0x0, 0x0, ...}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:982 +0xa7
github.com/pulumi/pulumi/pkg/v3/backend.PreviewStack({_, _}, {_, _}, {0xc000c100b0, {0xc0002562d0, 0x19}, {0x0, 0x0, 0x0}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/stack.go:90 +0xba
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Preview(_, {_, _}, {0xc000c100b0, {0xc0002562d0, 0x19}, {0x0, 0x0, 0x0}, 0xc000011e00, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:162 +0x88
main.newPreviewCmd.func1(0x0?, {0xc000a5f7a0, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/preview.go:227 +0x18d7
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000b83800?, {0xc000a5f7a0, 0x0, 0x7})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4c
github.com/spf13/cobra.(*Command).execute(0xc000b83800, {0xc000a5f730, 0x7, 0x7})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc00016ac00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:56 +0x65
```

**Comment by tgummerer** [comment]
I notice you are using a somewhat older version of pulumi, any chance you could try with the latest version?  Not sure that's going to help though, since this seems relatively similar to https://github.com/pulumi/pulumi/issues/14761, which is also still open.

I'm also curious what your config looks like, do you have any secrets stored there, and if so what secret manager are you using?

**Comment by tgummerer** [comment]
I'm going to close this out, since the panic has been fixed (it will now error out, because we still don't know how to construct a proper secret manager in this situation). Feel free to reopen this with the information requested above if this is still an issue for you.  In addition the information requested in a similar issue (https://github.com/pulumi/pulumi/issues/14761#issuecomment-1978494433) would be super helpful!
