### ISSUE TITLE
integration/transforms TestNodejsTransforms/nodejs/simple is flaky

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#15639]
```
=== Failed
=== FAIL: integration/transforms TestNodejsTransforms/nodejs/simple (27.28s)
    program.go:1935: sample: nodejs/simple
    program.go:1940: pulumi: /home/runner/work/pulumi/pulumi/bin/pulumi
    program.go:1086: acquired yarn install lock
    command.go:46: **** Invoke '/opt/hostedtoolcache/node/21.7.0/x64/bin/yarn install' in '/tmp/p-it-fv-az888-2-simple-a0709b74-4119690147'
    command.go:118: Wrote output to /tmp/p-it-fv-az888-2-simple-a0709b74-4119690147/command-output/yarn-install.20240308-144427.f5599.log
    program.go:1112: released yarn install lock
    program.go:1086: acquired yarn install lock
    command.go:46: **** Invoke '/opt/hostedtoolcache/node/21.7.0/x64/bin/yarn link @pulumi/pulumi' in '/tmp/p-it-fv-az888-2-simple-a0709b74-4119690147'
    command.go:118: Wrote output to /tmp/p-it-fv-az888-2-simple-a0709b74-4119690147/command-output/yarn-link.20240308-144427.5da14.log
    program.go:1112: released yarn install lock
    program.go:2085: projdir: /tmp/p-it-fv-az888-2-simple-a0709b74-4119690147
    program.go:1336: Initializing project (dir /tmp/p-it-fv-az888-2-simple-a0709b74-4119690147; stack p-it-fv-az888-2-simple-a0709b74)
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi login --cloud-url file:///tmp/TestNodejsTransformsnodejssimple2650469499/001' in '/tmp/p-it-fv-az888-2-simple-a0709b74-4119690147'
    command.go:118: Wrote output to /tmp/p-it-fv-az888-2-simple-a0709b74-4119690147/command-output/pulumi-login.20240308-144427.7f96e.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack init p-it-fv-az888-2-simple-a0709b74' in '/tmp/p-it-fv-az888-2-simple-a0709b74-4119690147'
    command.go:118: Wrote output to /tmp/p-it-fv-az888-2-simple-a0709b74-4119690147/command-output/pulumi-stack-init.20240308-144428.186ae.log
    program.go:1503: Performing primary preview and update
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi up --non-interactive --yes --skip-preview --event-log /tmp/p-it-fv-az888-2-simple-a0709b74-events.json' in '/tmp/p-it-fv-az888-2-simple-a0709b74-4119690147'
    command.go:118: Wrote output to /tmp/p-it-fv-az888-2-simple-a0709b74-4119690147/command-output/pulumi-update-initial.20240308-144450.27a7b.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack export --file /tmp/p-it-fv-az888-2-simple-a0709b742859658456/stack.json' in '/tmp/p-it-fv-az888-2-simple-a0709b74-4119690147'
    command.go:121: Command completed without output
    program.go:1879: Performing extra runtime validation.
    transforms_test.go:48: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/integration/transforms/transforms_test.go:48
        	            				/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:1880
        	            				/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:1533
        	Error:      	Expected value not to be nil.
        	Test:       	TestNodejsTransforms/nodejs/simple
    program.go:1461: Destroying stack
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi destroy --non-interactive --yes --skip-preview' in '/tmp/p-it-fv-az888-2-simple-a0709b74-4119690147'
    command.go:118: Wrote output to /tmp/p-it-fv-az888-2-simple-a0709b74-4119690147/command-output/pulumi-destroy.20240308-144453.54d7a.log
    program.go:1477: Test failed, retaining stack 'p-it-fv-az888-2-simple-a0709b74'

=== FAIL: integration/transforms TestNodejsTransforms (27.28s)
panic: interface conversion: interface *** is nil, not string [recovered]
	panic: interface conversion: interface *** is nil, not string

goroutine 12 [running]:
testing.tRunner.func1.2(***0x23aeac0, 0xc00080ee70***)
	/opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:1631 +0x3f7
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:1634 +0x6b6
panic(***0x23aeac0?, 0xc00080ee70?***)
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/panic.go:770 +0x132
github.com/pulumi/pulumi/tests/integration/transforms.Validator(_, ***0xc000a014c0, 0x1f***, 0xc000848000, ***0xc000022000, 0x85***, 0x0, 0x0, ***0x0, 0x0***, ...***, ...***)
	/home/runner/work/pulumi/pulumi/tests/integration/transforms/transforms_test.go:49 +0xb37
github.com/pulumi/pulumi/pkg/v3/testing/integration.(*ProgramTester).performExtraRuntimeValidation(0xc000000b40, 0x26fe928, ***0xc000959260, 0x2f***)
	/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:1880 +0x10f5
github.com/pulumi/pulumi/pkg/v3/testing/integration.(*ProgramTester).TestPreviewUpdateAndEdits(0xc000000b40)
	/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:1533 +0x686
github.com/pulumi/pulumi/pkg/v3/testing/integration.(*ProgramTester).TestLifeCycleInitAndDestroy(0xc000000b40)
	/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:1281 +0x766
github.com/pulumi/pulumi/pkg/v3/testing/integration.ProgramTest(0xc000593380, 0xc000668588)
	/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:850 +0x9c
github.com/pulumi/pulumi/tests/integration/transforms.TestNodejsTransforms.func1(0xc000593380)
	/home/runner/work/pulumi/pulumi/tests/integration/transforms/transforms_nodejs_test.go:20 +0x345
testing.tRunner(0xc000593380, 0xc00015fc98)
	/opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:1689 +0x21f
created by testing.(*T).Run in goroutine 10
	/opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:1742 +0x826

=== FAIL: integration/transforms TestGoTransformations (unknown)
    program.go:1935: sample: go/simple
    program.go:1940: pulumi: /home/runner/work/pulumi/pulumi/bin/pulumi
    command.go:46: **** Invoke '/opt/hostedtoolcache/go/1.22.0/x64/bin/go mod edit -replace github.com/pulumi/pulumi/sdk/v3=/home/runner/work/pulumi/pulumi/sdk' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:121: Command completed without output
    command.go:46: **** Invoke '/opt/hostedtoolcache/go/1.22.0/x64/bin/go mod tidy' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:118: Wrote output to /home/runner/go/src/stackName-1709909065824755627-324/command-output/go-mod-tidy.20240308-144429.70bd9.log
    program.go:2085: projdir: /home/runner/go/src/stackName-1709909065824755627-324
    program.go:1336: Initializing project (dir /home/runner/go/src/stackName-1709909065824755627-324; stack p-it-fv-az888-2-simple-54e0c042)
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi login --cloud-url file:///tmp/TestGoTransformationsgosimple2273207198/001' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:118: Wrote output to /home/runner/go/src/stackName-1709909065824755627-324/command-output/pulumi-login.20240308-144429.1cd82.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack init p-it-fv-az888-2-simple-54e0c042' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:118: Wrote output to /home/runner/go/src/stackName-1709909065824755627-324/command-output/pulumi-stack-init.20240308-144429.a3978.log
    program.go:1503: Performing primary preview and update
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi up --non-interactive --yes --skip-preview --event-log /tmp/p-it-fv-az888-2-simple-54e0c042-events.json' in '/home/runner/go/src/stackName-1709909065824755627-324'
    sp.check_call(args, shell=False)
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/subprocess.py", line 413, in check_call
    command.go:118: Wrote output to /home/runner/go/src/stackName-1709909065824755627-324/command-output/pulumi-update-initial.20240308-144450.f5580.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack export --file /tmp/p-it-fv-az888-2-simple-54e0c042774528985/stack.json' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:121: Command completed without output
    program.go:1879: Performing extra runtime validation.
    program.go:1881: Extra runtime validation complete.
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi refresh --non-interactive --yes --skip-preview --expect-no-changes' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:118: Wrote output to /home/runner/go/src/stackName-1709909065824755627-324/command-output/pulumi-refresh.20240308-144452.801f0.log
    program.go:1461: Destroying stack
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi destroy --non-interactive --yes --skip-preview' in '/home/runner/go/src/stackName-1709909065824755627-324'

=== FAIL: integration/transforms TestGoTransformations/go/simple (unknown)
    program.go:1935: sample: go/simple
    program.go:1940: pulumi: /home/runner/work/pulumi/pulumi/bin/pulumi
    command.go:46: **** Invoke '/opt/hostedtoolcache/go/1.22.0/x64/bin/go mod edit -replace github.com/pulumi/pulumi/sdk/v3=/home/runner/work/pulumi/pulumi/sdk' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:121: Command completed without output
    command.go:46: **** Invoke '/opt/hostedtoolcache/go/1.22.0/x64/bin/go mod tidy' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:118: Wrote output to /home/runner/go/src/stackName-1709909065824755627-324/command-output/go-mod-tidy.20240308-144429.70bd9.log
    program.go:2085: projdir: /home/runner/go/src/stackName-1709909065824755627-324
    program.go:1336: Initializing project (dir /home/runner/go/src/stackName-1709909065824755627-324; stack p-it-fv-az888-2-simple-54e0c042)
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi login --cloud-url file:///tmp/TestGoTransformationsgosimple2273207198/001' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:118: Wrote output to /home/runner/go/src/stackName-1709909065824755627-324/command-output/pulumi-login.20240308-144429.1cd82.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack init p-it-fv-az888-2-simple-54e0c042' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:118: Wrote output to /home/runner/go/src/stackName-1709909065824755627-324/command-output/pulumi-stack-init.20240308-144429.a3978.log
    program.go:1503: Performing primary preview and update
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi up --non-interactive --yes --skip-preview --event-log /tmp/p-it-fv-az888-2-simple-54e0c042-events.json' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:118: Wrote output to /home/runner/go/src/stackName-1709909065824755627-324/command-output/pulumi-update-initial.20240308-144450.f5580.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack export --file /tmp/p-it-fv-az888-2-simple-54e0c042774528985/stack.json' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:121: Command completed without output
    program.go:1879: Performing extra runtime validation.
    program.go:1881: Extra runtime validation complete.
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi refresh --non-interactive --yes --skip-preview --expect-no-changes' in '/home/runner/go/src/stackName-1709909065824755627-324'
    command.go:118: Wrote output to /home/runner/go/src/stackName-1709909065824755627-324/command-output/pulumi-refresh.20240308-144452.801f0.log
    program.go:1461: Destroying stack
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi destroy --non-interactive --yes --skip-preview' in '/home/runner/go/src/stackName-1709909065824755627-324'
```

From: https://github.com/pulumi/pulumi/actions/runs/8204803585/job/22440485130?pr=15562

@Frassle this looks like a test introduced with transforms, any idea what could be happening here?

**Comment by Frassle** [comment]
huh I'll have a look

**Comment by tgummerer** [comment]
We hit the issue here again, this time with a slightly better error message:

```
=== FAIL: integration/transforms TestNodejsSimpleTransforms (78.00s)
    program.go:1946: sample: nodejs/simple
    program.go:1951: pulumi: /home/runner/work/pulumi/pulumi/bin/pulumi
    program.go:1086: acquired yarn install lock
    command.go:46: **** Invoke '/opt/hostedtoolcache/node/21.7.3/x64/bin/yarn install' in '/tmp/p-it-fv-az775-2-simple-44f365fb-882904913'
    command.go:118: Wrote output to /tmp/p-it-fv-az775-2-simple-44f365fb-882904913/command-output/yarn-install.20240515-085818.c2452.log
    program.go:1112: released yarn install lock
    program.go:1086: acquired yarn install lock
    command.go:46: **** Invoke '/opt/hostedtoolcache/node/21.7.3/x64/bin/yarn link @pulumi/pulumi' in '/tmp/p-it-fv-az775-2-simple-44f365fb-882904913'
    command.go:118: Wrote output to /tmp/p-it-fv-az775-2-simple-44f365fb-882904913/command-output/yarn-link.20240515-085819.a9c19.log
    program.go:1112: released yarn install lock
    program.go:2096: projdir: /tmp/p-it-fv-az775-2-simple-44f365fb-882904913
    program.go:1336: Initializing project (dir /tmp/p-it-fv-az775-2-simple-44f365fb-882904913; stack p-it-fv-az775-2-simple-44f365fb)
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi login --cloud-url file:///tmp/TestNodejsSimpleTransforms1577615724/001' in '/tmp/p-it-fv-az775-2-simple-44f365fb-882904913'
    command.go:118: Wrote output to /tmp/p-it-fv-az775-2-simple-44f365fb-882904913/command-output/pulumi-login.20240515-085823.21f85.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack init p-it-fv-az775-2-simple-44f365fb' in '/tmp/p-it-fv-az775-2-simple-44f365fb-882904913'
    command.go:118: Wrote output to /tmp/p-it-fv-az775-2-simple-44f365fb-882904913/command-output/pulumi-stack-init.20240515-085839.aea6a.log
    program.go:1503: Performing primary preview and update
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi up --non-interactive --yes --skip-preview --event-log /tmp/p-it-fv-az775-2-simple-44f365fb-events.json' in '/tmp/p-it-fv-az775-2-simple-44f365fb-882904913'
    command.go:118: Wrote output to /tmp/p-it-fv-az775-2-simple-44f365fb-882904913/command-output/pulumi-update-initial.20240515-085908.3e4dc.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack export --file /tmp/p-it-fv-az775-2-simple-44f365fb737581135/stack.json' in '/tmp/p-it-fv-az775-2-simple-44f365fb-882904913'
    command.go:121: Command completed without output
    program.go:1890: Performing extra runtime validation.
    transforms_test.go:52: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/integration/transforms/transforms_test.go:52
        	            				/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:1891
        	            				/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:1533
        	Error:      	Expected value not to be nil.
        	Test:       	TestNodejsSimpleTransforms
    transforms_test.go:53: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/integration/transforms/transforms_test.go:53
        	            				/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:1891
        	            				/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:1533
        	Error:      	Not equal: 
        	            	expected: string("stackDefault")
        	            	actual  : <nil>(<nil>)
        	Test:       	TestNodejsSimpleTransforms
    transforms_test.go:60: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/tests/integration/transforms/transforms_test.go:60
        	            				/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:1891
        	            				/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:1533
        	Error:      	[]resource.PropertyKey(nil) does not contain "result"
        	Test:       	TestNodejsSimpleTransforms
    program.go:1892: Extra runtime validation complete.
    program.go:1220: Canceling further steps due to test failure
    program.go:1461: Destroying stack
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi destroy --non-interactive --yes --skip-preview' in '/tmp/p-it-fv-az775-2-simple-44f365fb-882904913'
    command.go:118: Wrote output to /tmp/p-it-fv-az775-2-simple-44f365fb-882904913/command-output/pulumi-destroy.20240515-085935.68b25.log
    program.go:1477: Test failed, retaining stack 'p-it-fv-az775-2-simple-44f365fb'
```

from: https://github.com/pulumi/pulumi/actions/runs/9092563159/job/24989923686

**Comment by tgummerer** [comment]
Turns out this is an actual race, and not just a flaky test, so I'm marking it as such.
