### ISSUE TITLE
Pulumi versions after v3.108.1 sometimes crashes/panics when using `--target`

### ISSUE THREAD

**Issue by aucampia** [pulumi/pulumi#15704]
### What happened?

When `poetry run pulumi --cwd infrastructure/pulumi --stack "beta" preview  --target 'urn:pulumi:beta::Kron::nomad:index/job:Job::kron-backend'  --target-dependents --diff` with v3.111.0 Pulumi crashes/panics.

### Example

```console
$ poetry run pulumi --cwd infrastructure/pulumi --stack "beta" preview  --target 'urn:pulumi:beta::Kron::nomad:index/job:Job::kron-backend'  --target-dependents --diff
Previewing update (beta):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:beta::Kron::pulumi:pulumi:Stack::Kron-beta]
    ~ nomad:index/job:Job: (update)
        [id=beta-kron-backend]
        [urn=urn:pulumi:beta::Kron::nomad:index/job:Job::kron-backend]
        [provider: urn:pulumi:beta::Kron::pulumi:providers:nomad::default_2_1_0::1be6fc28-6c5b-4f77-b191-533c222dace3 => urn:pulumi:beta::Kron::pulumi:providers:nomad::default_2_2_0::output<string>]
      ~ jobspec: 
            ...
              priority = 40
              meta {
          -     image_tag = "30727bf9"
          +     image_tag = "1d4f3cd9"
                env_flavour = "beta"
          +     mark = 0000
              }
              reschedule {
            ...
@ previewing update...|panic: fatal: An assertion has failed: provider missing from step generator providers map

goroutine 100 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x0?, {0x2b89058?, 0xc001e3d420?}, {0x0?, 0x0?, 0xc001ee16b8?})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:35 +0xe8
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).getProviderResource(0xc00054d100, {0x2b3013d?, 0xc001ee1880?}, {0xc001e3d420?, 0x28c3520?})
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1739 +0xa5
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).AnalyzeResources.func1({0xc0021b6dc0, 0x3b}, 0xc000f72140)
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1998 +0x445
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).AnalyzeResources.(*resourceMap).mapRange.func2({0x290cf20?, 0xc003719700?}, {0x26cd180?, 0xc000f72140?})
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:244 +0x4d
sync.(*Map).Range(0xc001583080?, 0xc001ee1bb8)
	/opt/hostedtoolcache/go/1.22.1/x64/src/sync/map.go:477 +0x1f8
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*resourceMap).mapRange(...)
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:243
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).AnalyzeResources(0xc00054d100)
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1974 +0xba
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute(0xc001549608, {0x3437e20, 0xc00238ee40}, {{0x7fd3185d9998, 0xc001bd07e0}, 0x40, 0x0, 0x0, {{0xc002002ae0, 0x1, ...}, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:316 +0x8a9
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Deployment).Execute(...)
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:578
github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run.func1()
	/home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:323 +0x290
created by github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run in goroutine 1
	/home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:308 +0x27d
```

### Output of `pulumi about`

```
$ poetry run pulumi --cwd infrastructure/pulumi --stack "beta" about
CLI          
Version      3.111.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.68.0
azure-native  2.32.0
azuread       5.47.2
command       0.9.2
consul        3.11.1
gcp           7.13.0
nomad         2.2.0
python        unknown
tailscale     0.15.0

Host     
OS       fedora
Version  39
Arch     x86_64

This project is written in python: executable='/home/iwana/.cache/pypoetry/virtualenvs/kron-Ba8vgTu5-py3.12/bin/python3' version='3.12.2'

Current Stack: organization/Kron/beta

TYPE                                                  URN
pulumi:pulumi:Stack                                   urn:pulumi:beta::Kron::pulumi:pulumi:Stack::Kron-beta
pkg:index:AzureComponent                              urn:pulumi:beta::Kron::pkg:index:AzureComponent::default
pkg:index:GCPComponent                                urn:pulumi:beta::Kron::pkg:index:GCPComponent::default
pulumi:providers:nomad                                urn:pulumi:beta::Kron::pulumi:providers:nomad::default_2_1_0
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::dbt
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::cash-reconciliation-snapshot
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::export-wolf
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::email-tracking
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::fas-archive
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::kron-web
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::kronponents
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::logs-archive
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::metabase
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::minio-offsite-backup
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::main-proxy
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::metrics
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::postgres-backup
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::postgres
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::postgres-export-scrubbed-db
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::postgres-upgrade
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::minio
pulumi:providers:consul                               urn:pulumi:beta::Kron::pulumi:providers:consul::default_3_11_1
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::kron-backend
consul:index/configEntry:ConfigEntry                  urn:pulumi:beta::Kron::consul:index/configEntry:ConfigEntry::beta-kron-backend-queue-readonly-failover
consul:index/configEntry:ConfigEntry                  urn:pulumi:beta::Kron::consul:index/configEntry:ConfigEntry::beta-kron-backend-queue
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::ss-scan
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::sslscan
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::redis-commander
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::redis-backup
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::postgres-import-scrubbed-db
pulumi:providers:gcp                                  urn:pulumi:beta::Kron::pulumi:providers:gcp::default_7_13_0
gcp:projects/service:Service                          urn:pulumi:beta::Kron::pkg:index:GCPComponent$gcp:projects/service:Service::compute
gcp:projects/service:Service                          urn:pulumi:beta::Kron::pkg:index:GCPComponent$gcp:projects/service:Service::cloudasset
gcp:projects/service:Service                          urn:pulumi:beta::Kron::pkg:index:GCPComponent$gcp:projects/service:Service::serviceusage
gcp:storage/bucket:Bucket                             urn:pulumi:beta::Kron::pkg:index:GCPComponent$gcp:storage/bucket:Bucket::documents
pulumi:providers:azure-native                         urn:pulumi:beta::Kron::pulumi:providers:azure-native::default_2_32_0
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::herman.schistad@kron.no-READER-subscription
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::jedrzej.nowacki@kron.no-READER-subscription
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::per.gunnar.paulsen@kron.no-READER-subscription
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::iwan.armand.aucamp@kron.no-READER-subscription
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::hallvard.nygard@kron.no-READER-subscription
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::piotr.janiszewski@kron.no-READER-subscription
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::jostein.bo.floystad@kron.no-READER-subscription
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::knut.saua@kron.no-READER-subscription
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::emil.haugberg.van.veen@kron.no-READER-subscription
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::andreas.drivenes@kron.no-READER-subscription
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::henrik.molnes@kron.no-READER-subscription
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::sofian.gharsallah@kron.no-READER-subscription
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:authorization:RoleAssignment::joar.kosberg@kron.no-READER-subscription
gcp:storage/bucketIAMBinding:BucketIAMBinding         urn:pulumi:beta::Kron::pkg:index:GCPComponent$gcp:storage/bucket:Bucket$gcp:storage/bucketIAMBinding:BucketIAMBinding::documents-roles/storage.legacyBucketReader
gcp:projects/service:Service                          urn:pulumi:beta::Kron::pkg:index:GCPComponent$gcp:projects/service:Service::cloudresourcemanager
azure-native:resources:ResourceGroup                  urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup::pulumi
azure-native:resources:ResourceGroup                  urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup::kron-main
nomad:index/job:Job                                   urn:pulumi:beta::Kron::nomad:index/job:Job::redis
gcp:projects/service:Service                          urn:pulumi:beta::Kron::pkg:index:GCPComponent$gcp:projects/service:Service::iam
azure-native:storage:StorageAccount                   urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount::pulumi
azure-native:storage:StorageAccount                   urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount::signicat
azure-native:storage:StorageAccount                   urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount::documents
gcp:projects/iAMBinding:IAMBinding                    urn:pulumi:beta::Kron::pkg:index:GCPComponent$gcp:projects/iAMBinding:IAMBinding::kron-backend-viewers
gcp:serviceaccount/account:Account                    urn:pulumi:beta::Kron::pkg:index:GCPComponent$gcp:serviceaccount/account:Account::kron-backend
azure-native:storage:BlobContainer                    urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer::pulumi-main
azure-native:storage:BlobServiceProperties            urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobServiceProperties::signicat-default
azure-native:storage:BlobServiceProperties            urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobServiceProperties::documents-default
gcp:storage/bucketIAMBinding:BucketIAMBinding         urn:pulumi:beta::Kron::gcp:storage/bucketIAMBinding:BucketIAMBinding::documents-storage.objectAdmin
gcp:serviceaccount/key:Key                            urn:pulumi:beta::Kron::pkg:index:GCPComponent$gcp:serviceaccount/account:Account$gcp:serviceaccount/key:Key::kron-backend
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::iwan.armand.aucamp@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::herman.schistad@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::jedrzej.nowacki@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::per.gunnar.paulsen@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::hallvard.nygard@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::jostein.bo.floystad@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::emil.haugberg.van.veen@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::andreas.drivenes@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::joar.kosberg@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::sofian.gharsallah@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::henrik.molnes@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::knut.saua@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:authorization:RoleAssignment             urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobContainer$azure-native:authorization:RoleAssignment::piotr.janiszewski@kron.no-STORAGE_BLOB_DATA_CONTRIBUTOR-bc-pulumi-main
azure-native:storage:BlobContainer                    urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobServiceProperties$azure-native:storage:BlobContainer::signicat-main
azure-native:storage:BlobContainer                    urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobServiceProperties$azure-native:storage:BlobContainer::documents-main
azure-native:storage:BlobContainerImmutabilityPolicy  urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobServiceProperties$azure-native:storage:BlobContainer$azure-native:storage:BlobContainerImmutabilityPolicy::signicat-main-default
azure-native:storage:BlobContainerImmutabilityPolicy  urn:pulumi:beta::Kron::pkg:index:AzureComponent$azure-native:resources:ResourceGroup$azure-native:storage:StorageAccount$azure-native:storage:BlobServiceProperties$azure-native:storage:BlobContainer$azure-native:storage:BlobContainerImmutabilityPolicy::documents-main-default
pulumi:providers:azure-native                         urn:pulumi:beta::Kron::pulumi:providers:azure-native::default_2_30_0
pulumi:providers:gcp                                  urn:pulumi:beta::Kron::pulumi:providers:gcp::default_7_12_0
pulumi:providers:azure-native                         urn:pulumi:beta::Kron::pulumi:providers:azure-native::default_2_29_0
pulumi:providers:nomad                                urn:pulumi:beta::Kron::pulumi:providers:nomad::default_2_0_0
pulumi:providers:azure-native                         urn:pulumi:beta::Kron::pulumi:providers:azure-native::default_2_27_0


Found no pending operations associated with beta

Backend        
Name           iwana-202305.pc.kron.no
URL            azblob://a-pulumi-main?storage_account=1e659733apulumi
User           iwana
Organizations  
Token type     personal

Dependencies:
NAME                              VERSION
aioboto3                          12.3.0
azure-mgmt-storage                21.1.0
boto3                             1.34.34
Brotli                            1.0.9
datamodel-code-generator          0.25.4
dbt-postgres                      1.7.9
deptry                            0.12.0
fakeredis                         2.21.2
freezegun                         1.4.0
google-api-python-client          2.122.0
google-cloud-storage              2.15.0
hiredis                           2.2.3
httpx                             0.27.0
ipython                           8.22.1
kron                              0.0.0
lupa                              2.0
msgpack                           1.0.5
mypy                              1.9.0
openpyxl                          3.1.2
pip                               23.3.1
pre-commit                        3.6.2
pulumi_azure                      5.68.0
pulumi_azure_native               2.32.0
pulumi_azuread                    5.47.2
pulumi-command                    0.9.2
pulumi_consul                     3.11.1
pulumi_gcp                        7.13.0
pulumi_nomad                      2.2.0
pulumi_tailscale                  0.15.0
pytest-aiohttp                    1.0.5
pytest-cov                        4.1.0
pytest-mock                       3.12.0
pytest-repeat                     0.9.3
pytest-socket                     0.7.0
pytest-tornado                    0.8.1
pytest-watch                      4.2.0
pytest-xdist                      3.5.0
python-dotenv                     1.0.0
ruff                              0.3.2
safety                            3.0.1
sqlfluff-templater-dbt            2.3.5
types-aioboto3                    12.3.0
types-aiobotocore-cloudformation  2.11.1
types-aiobotocore-dynamodb        2.11.1
types-aiobotocore-ec2             2.11.1
types-aiobotocore-lambda          2.11.1
types-aiobotocore-rds             2.11.1
types-aiobotocore-s3              2.12.1
types-aiobotocore-sqs             2.11.1
types-cachetools                  5.3.0.7
types-emoji                       2.1.0.3
types-freezegun                   1.1.10
types-python-dateutil             2.8.19.20240311
types-PyYAML                      6.0.12.20240311
types-redis                       4.6.0.20240311
types-requests                    2.31.0.6
zopfli                            0.2.2

Pulumi locates its logs in /tmp by default
```

### Additional context

The crash does not happen if I don't use `--target` or if I switch to `v3.108.1` 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aucampia** [comment]
The problem also does not happen unless there is a change in the provider version, when I switched back to `pulumi-nomad` v2.1.0 the crash/panic went away.

**Comment by Frassle** [comment]
Got a test that repro's this, not tracked down a fix yet.
