### ISSUE TITLE
ResourceReference outputs are sometimes not useable with the Pulumi SDK

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi#15788]
### What happened?

I hit upon a problem with how the Pulumi Go SDK unmarshals output property values. In the case of a resource reference being unmarshaled as `any`, e.g. into an element of an `ArrayOutput`, one doesn't get a pointer to the `Resource`, one gets a copy of the underlying struct. On the other hand, a resource reference that is unmarshaled to a concrete type like `*corev1.ConfigMap` may work as expected. The problem occurs with dynamic output types like arrays.

See [this code](https://github.com/pulumi/pulumi/blob/41e38c9a27eadf4fe412f101e3dd9ea4331425c9/sdk/go/pulumi/rpc.go#L757-L762) for more details.

### Example

For example, the elements of the `Resources` property of `ConfigGroup` cannot be used as `pulumi.Resource` or even as `*corev1.ConfigMap`.

```go
example, err := yamlv2.NewConfigGroup(ctx, "example", &yamlv2.ConfigGroupArgs{
	Objs: pulumi.Array{
		pulumi.Map{
			"apiVersion": pulumi.String("v1"),
			"kind":       pulumi.String("ConfigMap"),
			"metadata": pulumi.Map{
				"name": pulumi.String("my-map"),
			},
		},
	},
})
_ = example.Resources.Index(pulumi.Int(0)).ApplyT(func(r any) error {
	res := r.(pulumi.Resource) // <-- PANIC: r is not a pulumi.Resource
	ctx.Log.Info("Hello World", &pulumi.LogArgs{Resource: res})

	configMap := r.(*corev1.ConfigMap) // <-- PANIC: r is a corev1.ConfigMap not a *corev1.ConfigMap
	ctx.Export("configMapUid", configMap.Metadata.Uid())
	return nil
})
```

The `Resources` output property is defined as a simple `ArrayOutput`:
```go
type ConfigGroup struct {
	pulumi.ResourceState

	// Resources created by the ConfigGroup.
	Resources pulumi.ArrayOutput `pulumi:"resources"`
}
```

At the RPC level, the `resources` output is an an array of property values, with each value being a `ResourceReference`.

### Output of `pulumi about`

```
CLI          
Version      3.108.1
Go Version   go1.22.0
Go Compiler  gc

Host     
OS       darwin
Version  13.5.1
Arch     arm64

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already). 

```[tasklist]
### Blocked Issues
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1173
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1108
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/907
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1174
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/3057
```

**Comment by EronWright** [comment]
I observe that the dotnet SDK has a similar problem and returns the raw resource reference.

**Comment by justinvp** [comment]
> `configMap := r.(*corev1.ConfigMap) // <-- PANIC: r is a corev1.ConfigMap not a *corev1.ConfigMap`

When the resource reference is deserialized, it should be turned into `*corev1.ConfigMap` via https://github.com/pulumi/pulumi-kubernetes/blob/a15641e45ef72f2be6ef15a2527e3f014598adfb/sdk/go/kubernetes/core/v1/init.go#L29

I wonder if `Index` or `ApplyT` has something to do with what you're seeing inside the apply.

**Comment by EronWright** [comment]
@justinvp I believe that the reference is indeed turned into a `*corev1.ConfigMap` by `unmarshalResourceReference` (which calls the above-mentioned `Construct` function. Note that it returns a `pulumi.Resource` as expected.
```go
func unmarshalResourceReference(ctx *Context, ref resource.ResourceReference) (Resource, error)
```
I believe the [caller](https://github.com/pulumi/pulumi/blob/41e38c9a27eadf4fe412f101e3dd9ea4331425c9/sdk/go/pulumi/rpc.go#L794-L802) (`unmarshalOutput`) is where the issue lies.  There's a block [here](https://github.com/pulumi/pulumi/blob/41e38c9a27eadf4fe412f101e3dd9ea4331425c9/sdk/go/pulumi/rpc.go#L757-L762) that ensures that a pointer is returned, only if the destination type is a pointer.  In our case, the destination type is `any` (because we're unmarshaling to an ArrayOutput).

I'm a bit curious as to why the `v.IsArchive()` and `v.IsAsset()` cases are coded differently.

Introducing a `ResourceArrayOutput` seems like a good alternative solution.

**Comment by EronWright** [comment]
I observe that the Java SDK has problems with working with resource references. I tried to install a Helm chart that includes CRDs, and see a problem that suggests a mishandling of the resource references.

```plain
    java.lang.IllegalArgumentException: Couldn't instantiate class 'com.pulumi.kubernetes.apiextensions.v1.CustomResourceDefinition' using constructor: 'public com.pulumi.kubernetes.apiextensions.v1.CustomResourceDefinition(java.lang.String,com.pulumi.kubernetes.apiextensions.v1.CustomResourceDefinitionArgs,com.pulumi.resources.CustomResourceOptions)', for resource type: 'kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition'
        at com.pulumi.serialization.internal.ResourcePackages.tryConstruct(ResourcePackages.java:234)
        at com.pulumi.serialization.internal.Deserializer.tryDeserializeResource(Deserializer.java:367)
        at com.pulumi.serialization.internal.Deserializer.deserializeCore(Deserializer.java:103)
        at com.pulumi.serialization.internal.Deserializer.deserialize(Deserializer.java:59)
        at com.pulumi.serialization.internal.Deserializer.lambda$deserializeList$8(Deserializer.java:150)
        at com.pulumi.serialization.internal.Deserializer.lambda$deserializeOneOf$10(Deserializer.java:223)
        at com.pulumi.serialization.internal.Deserializer.deserializeCore(Deserializer.java:109)
        at com.pulumi.serialization.internal.Deserializer.deserializeOneOf(Deserializer.java:221)
        at com.pulumi.serialization.internal.Deserializer.deserializeList(Deserializer.java:143)
        at com.pulumi.serialization.internal.Deserializer.lambda$deserialize$6(Deserializer.java:75)
        at com.pulumi.serialization.internal.Deserializer.deserializeCore(Deserializer.java:109)
        at com.pulumi.serialization.internal.Deserializer.deserialize(Deserializer.java:59)
        at com.pulumi.serialization.internal.Converter.convertValue(Converter.java:81)
        at com.pulumi.core.internal.OutputCompletionSource.setValue(OutputCompletionSource.java:95)
        at com.pulumi.deployment.internal.DeploymentImpl$ReadOrRegisterResourceInternal.lambda$completeResourceAsync$0(DeploymentImpl.java:1187)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by EronWright** [comment]
While the Go SDK was fixed to not crash, I'm not sure whether the broader issue was fully addressed across all the SDKs to ensure that resource references are actually useable, e.g.
- able to send and receive resource references with high-fidelity
- resources references work as expected as stack outputs
