### ISSUE TITLE
Improve python error messages to include more information about what's failing

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#15869]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

User came forward and passed on this error message:

```
  error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/*username*/code/******-db/******-platform/pulumi/satellites/venv/lib/python3.12/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
                 ^^^^^^^^^
      File "/home/*username*/code/******-db/******-platform/pulumi/satellites/venv/lib/python3.12/site-packages/pulumi/runtime/resource.py", line 909, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/*username*/code/******-db/******-platform/pulumi/satellites/venv/lib/python3.12/site-packages/pulumi/runtime/resource.py", line 196, in prepare_resource
        serialized_props = await rpc.serialize_properties(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/*username*/code/******-db/******-platform/pulumi/satellites/venv/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 215, in serialize_properties
        result = await serialize_property(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/*username*/code/******-db/******-platform/pulumi/satellites/venv/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 578, in serialize_property
        raise ValueError(f"unexpected input of type {type(value).__name__}")
    ValueError: unexpected input of type property
   
    The above exception was the direct cause of the following exception:
   
    Traceback (most recent call last):
      File "/home/*username*/.pulumi/bin/pulumi-language-python-exec", line 191, in <module>
        loop.run_until_complete(coro)
      File "/home/linuxbrew/.linuxbrew/Cellar/python@3.12/3.12.2_1/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/home/*username*/code/******-db/******-platform/pulumi/satellites/venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 153, in run_in_stack
        await run_pulumi_func(run)
      File "/home/*username*/code/******-db/******-platform/pulumi/satellites/venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 61, in run_pulumi_func
        await wait_for_rpcs()
      File "/home/*username*/code/******-db/******-platform/pulumi/satellites/venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 94, in wait_for_rpcs
        raise exn from cause
      File "/home/*username*/code/******-db/******-platform/pulumi/satellites/venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 86, in wait_for_rpcs
        await rpc_manager.rpcs.pop()
    ValueError: unexpected input of type property
```

The error message doesn't contain any information about what resource, input name or even the line number in the Pulumi project that might be causing the error message. Can we improve the error message to include something to help debugging easier (without attaching a debugger)?

**Comment by kvthr** [comment]
Hey @pierskarsenbarg I would like work on this issue,
