### ISSUE TITLE
pulumi_awsx python package dependency on setuptools.pkg_resources

### ISSUE THREAD

**Issue by daroczig** [pulumi/pulumi#15927]
### What happened?

Trying to use the `pulumi_awsx` Python package without `setuptools` installed raises the below exception:

```
Diagnostics:
    pulumi:pulumi:Stack (spare-cores-dev):
      error: Program failed with an unhandled exception:
      Traceback (most recent call last):
        File "/home/runner/work/sc-infra/sc-infra/dev/spare-cores/__main__.py", line 4, in <module>
          import pulumi_awsx as awsx
        File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/pulumi_awsx/__init__.py", line 5, in <module>
          from . import _utilities
        File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/pulumi_awsx/_utilities.py", line 10, in <module>
          import pkg_resources
      ModuleNotFoundError: No module named 'pkg_resources'
```

### Example

1. Install `pulumi_awsx` without `setuptools` (that is not a dependency)
2. Try to use it

### Output of `pulumi about`

```
CLI          
Version      3.111.1
Go Version   go1.22.1
Go Compiler  gc

Host     
OS       arch
Version  "rolling"
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations  
Token type     personal
```

### Additional context

Same issue as in #12414 but for `awsx` this time instead of `aws`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening the issue @daroczig! Looks like awsx needs to upgrade to a more recent version of pulumi's codegen libraries for its generated SDK. Moving this issue to the awsx repo for further triage.
