### ISSUE TITLE
Cannot pass a Provider Resource reference to a node-implemented ComponentResource

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#15926]
### What happened?

Working with @rquitales on  https://github.com/pulumi/pulumi-eks/pull/1121 we cannot seem to get the creationRoleProvider option to work across the MLC boundary. The impact here is that creationRoleProvider option is only supported in Node (in-proc not MLC) and is not supported in Go, Java, Python, Java.

Definition is:

```
                "creationRoleProvider": {
                    "$ref": "#/types/eks:index:CreationRoleProvider",
                    "plain": true,
                    "description": "The IAM Role Provider used to create \u0026 authenticate against the EKS cluster. This role is given `[system:masters]` permission in K8S, See: https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html"
                },
```

With the type def:

```
        "eks:index:CreationRoleProvider": {
            "description": "Contains the AWS Role and Provider necessary to override the `[system:master]` entity ARN. This is an optional argument used when creating `Cluster`. Read more: https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html",
            "properties": {
                "provider": {
                    "$ref": "/aws/v6.5.0/schema.json#/provider",
                    "plain": true
                },
                "role": {
                    "$ref": "/aws/v6.5.0/schema.json#/resources/aws:iam%2Frole:Role",
                    "plain": true
                }
            },
            "type": "object",
            "required": [
                "role",
                "provider"
            ]
        },
```

Extract from gRPC log:

```
{
  "method": "/pulumirpc.ResourceProvider/Construct",
  "request": {
    "project": "eks-python",
    "stack": "dev",
    "type": "eks:index:Cluster",
    "name": "eks-cluster",
    "parent": "urn:pulumi:dev::eks-python::pulumi:pulumi:Stack::eks-python-dev",
    "inputs": {
      "creationRoleProvider": {
        "provider": {
          "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
          "id": "74dadd48-1575-45ff-98e3-8a74b708b1f0",
          "urn": "urn:pulumi:dev::eks-python::pulumi:providers:aws::aws-prov"
        },
        "role": "arn:aws:iam::123456789012:role/eks-creation-role"
      },
```

The Node code does not seem to do anything too strange but pass this reference after it's deserialized by the plumbing to a ResourceOptoin to create another resource, which then fails with:

```
   TypeError: provider.getPackage is not a function: TypeError: provider.getPackage is not a function
        at convertToProvidersMap (/snapshot/eks/node_modules/@pulumi/pulumi/resource.js:334:25)
        at new Resource (/snapshot/eks/node_modules/@pulumi/pulumi/resource.js:205:133)
        at new CustomResource (/snapshot/eks/node_modules/@pulumi/pulumi/resource.js:400:9)
        at new Cluster (/snapshot/eks/node_modules/@pulumi/aws/eks/cluster.js:200:9)
        at createCore (/snapshot/eks/bin/cluster.js:331:24)
        at createCluster (/snapshot/eks/bin/cluster.js:827:18)
        at new ClusterInternal (/snapshot/eks/bin/cluster.js:906:25)
        at Object.construct (/snapshot/eks/bin/cmd/provider/cluster.js:21:29)
        at Provider.construct (/snapshot/eks/bin/cmd/provider/index.js:131:24)
        at Server.<anonymous> (/snapshot/eks/node_modules/@pulumi/pulumi/provider/server.js:315:52)
```

### Example

See above.

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Also tried: updating Node SDK Pulumi reference to latest in the provider. Still persists.

**Comment by justinvp** [comment]
@t0yv0, @rquitales, do you have an example program handy?

**Comment by rquitales** [comment]
> @t0yv0, @rquitales, do you have an example program handy?

Here's a GitHub gist with a Python repro, and the grpc debug log.
 https://gist.github.com/rquitales/76c042c26ea142ebe88201289641dc9a
