### ISSUE TITLE
Since 3.112.0 getting `IndexError: list index out of range` in `pulumi up`

### ISSUE THREAD

**Issue by nexeck** [pulumi/pulumi#15952]
### What happened?

Calling pulumi up isn't working since 3.112.0. 3.111.1 is working fine.

3.113.0 has the same error in those projects.

pulumi refresh works without problems on those projects

The following error is happening in some of our pulumi projects:

```
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 191, in <module>
        loop.run_until_complete(coro)
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/Users/REDACTED*/.venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 132, in run_in_stack
        await run_pulumi_func(run)
      File "/Users/REDACTED/.venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 53, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/REDACTED/.venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 109, in wait_for_rpcs
        await task
    IndexError: list index out of range

```

### Example

I don't know why this is happening in 4 of our 8 pulumi projects. The Code is not public, and can't be provided.

If needed i can provide the redacted version of pulumi about for the other failing projects, too.

### Output of `pulumi about`

```
CLI
Version      3.112.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME          VERSION
aws           6.30.0
azure         5.71.0
azure-native  2.37.0
azuread       5.47.2
databricks    1.35.0
github        6.2.0
python        unknown

Host
OS       darwin
Version  14.4
Arch     arm64

This project is written in python: executable='/Users/REDACTED/.venv/bin/python3' version='3.12.2'

Current Stack: organization/REDACTED/dev

TYPE                                                              URN
pulumi:pulumi:Stack                                               urn:pulumi:dev::REDACTED::pulumi:pulumi:Stack::REDACTED
pulumi:providers:azure-native                                     urn:pulumi:dev::REDACTED::pulumi:providers:azure-native::REDACTED
pulumi:providers:azure-native                                     urn:pulumi:dev::REDACTED::pulumi:providers:azure-native::REDACTED
azure-native:resources:ResourceGroup                              urn:pulumi:dev::REDACTED::azure-native:resources:ResourceGroup::REDACTED
azure-native:resources:ResourceGroup                              urn:pulumi:dev::REDACTED::azure-native:resources:ResourceGroup::REDACTED
azure-native:resources:ResourceGroup                              urn:pulumi:dev::REDACTED::azure-native:resources:ResourceGroup::REDACTED
azure-native:databricks:AccessConnector                           urn:pulumi:dev::REDACTED::azure-native:databricks:AccessConnector::REDACTED
azure-native:operationalinsights:Workspace                        urn:pulumi:dev::REDACTED::azure-native:operationalinsights:Workspace::REDACTED
azure-native:network:NetworkSecurityGroup                         urn:pulumi:dev::REDACTED::azure-native:network:NetworkSecurityGroup::REDACTED
azure-native:network:Subnet                                       urn:pulumi:dev::REDACTED::azure-native:network:Subnet::REDACTED
azure-native:network:Subnet                                       urn:pulumi:dev::REDACTED::azure-native:network:Subnet::REDACTED
azure-native:databricks:Workspace                                 urn:pulumi:dev::REDACTED::azure-native:databricks:Workspace::REDACTED
azure-native:storage:StorageAccount                               urn:pulumi:dev::REDACTED::azure-native:storage:StorageAccount::REDACTED
azure-native:storage:StorageAccount                               urn:pulumi:dev::REDACTED::azure-native:storage:StorageAccount::REDACTED
azure-native:storage:StorageAccount                               urn:pulumi:dev::REDACTED::azure-native:storage:StorageAccount::REDACTED
azure-native:storage:StorageAccount                               urn:pulumi:dev::REDACTED::azure-native:storage:StorageAccount::REDACTED
pulumi:providers:databricks                                       urn:pulumi:dev::REDACTED::pulumi:providers:databricks::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:insights:DiagnosticSetting                           urn:pulumi:dev::REDACTED::azure-native:insights:DiagnosticSetting::REDACTED
azure-native:authorization:RoleAssignment                         urn:pulumi:dev::REDACTED::azure-native:authorization:RoleAssignment::REDACTED
azure-native:authorization:RoleAssignment                         urn:pulumi:dev::REDACTED::azure-native:authorization:RoleAssignment::REDACTED
azure-native:authorization:RoleAssignment                         urn:pulumi:dev::REDACTED::azure-native:authorization:RoleAssignment::REDACTED
azure-native:authorization:RoleAssignment                         urn:pulumi:dev::REDACTED::azure-native:authorization:RoleAssignment::REDACTED
azure-native:authorization:RoleAssignment                         urn:pulumi:dev::REDACTED::azure-native:authorization:RoleAssignment::REDACTED
azure-native:authorization:RoleAssignment                         urn:pulumi:dev::REDACTED::azure-native:authorization:RoleAssignment::REDACTED
azure-native:storage:BlobContainer                                urn:pulumi:dev::REDACTED::azure-native:storage:BlobContainer::REDACTED
azure-native:authorization:RoleAssignment                         urn:pulumi:dev::REDACTED::azure-native:authorization:RoleAssignment::REDACTED
azure-native:authorization:RoleAssignment                         urn:pulumi:dev::REDACTED::azure-native:authorization:RoleAssignment::REDACTED
azure-native:storage:BlobContainer                                urn:pulumi:dev::REDACTED::azure-native:storage:BlobContainer::REDACTED
azure-native:storage:BlobContainer                                urn:pulumi:dev::REDACTED::azure-native:storage:BlobContainer::REDACTED
azure-native:storage:BlobContainer                                urn:pulumi:dev::REDACTED::azure-native:storage:BlobContainer::REDACTED
databricks:index/workspaceConf:WorkspaceConf                      urn:pulumi:dev::REDACTED::databricks:index/workspaceConf:WorkspaceConf::REDACTED
databricks:index/globalInitScript:GlobalInitScript                urn:pulumi:dev::REDACTED::databricks:index/globalInitScript:GlobalInitScript::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/sqlEndpoint:SqlEndpoint                          urn:pulumi:dev::REDACTED::databricks:index/sqlEndpoint:SqlEndpoint::REDACTED
databricks:index/clusterPolicy:ClusterPolicy                      urn:pulumi:dev::REDACTED::databricks:index/clusterPolicy:ClusterPolicy::REDACTED
databricks:index/clusterPolicy:ClusterPolicy                      urn:pulumi:dev::REDACTED::databricks:index/clusterPolicy:ClusterPolicy::REDACTED
databricks:index/permissionAssignment:PermissionAssignment        urn:pulumi:dev::REDACTED::databricks:index/permissionAssignment:PermissionAssignment::REDACTED
databricks:index/permissionAssignment:PermissionAssignment        urn:pulumi:dev::REDACTED::databricks:index/permissionAssignment:PermissionAssignment::REDACTED
databricks:index/clusterPolicy:ClusterPolicy                      urn:pulumi:dev::REDACTED::databricks:index/clusterPolicy:ClusterPolicy::REDACTED
databricks:index/sqlEndpoint:SqlEndpoint                          urn:pulumi:dev::REDACTED::databricks:index/sqlEndpoint:SqlEndpoint::REDACTED
databricks:index/permissionAssignment:PermissionAssignment        urn:pulumi:dev::REDACTED::databricks:index/permissionAssignment:PermissionAssignment::REDACTED
databricks:index/clusterPolicy:ClusterPolicy                      urn:pulumi:dev::REDACTED::databricks:index/clusterPolicy:ClusterPolicy::REDACTED
databricks:index/clusterPolicy:ClusterPolicy                      urn:pulumi:dev::REDACTED::databricks:index/clusterPolicy:ClusterPolicy::REDACTED
databricks:index/clusterPolicy:ClusterPolicy                      urn:pulumi:dev::REDACTED::databricks:index/clusterPolicy:ClusterPolicy::REDACTED
databricks:index/sqlEndpoint:SqlEndpoint                          urn:pulumi:dev::REDACTED::databricks:index/sqlEndpoint:SqlEndpoint::REDACTED
azure-native:authorization:ManagementLockByScope                  urn:pulumi:dev::REDACTED::azure-native:authorization:ManagementLockByScope::REDACTED
azure-native:authorization:ManagementLockByScope                  urn:pulumi:dev::REDACTED::azure-native:authorization:ManagementLockByScope::REDACTED
azure-native:authorization:ManagementLockByScope                  urn:pulumi:dev::REDACTED::azure-native:authorization:ManagementLockByScope::REDACTED
azure-native:authorization:ManagementLockByScope                  urn:pulumi:dev::REDACTED::azure-native:authorization:ManagementLockByScope::REDACTED
databricks:index/externalLocation:ExternalLocation                urn:pulumi:dev::REDACTED::databricks:index/externalLocation:ExternalLocation::REDACTED
databricks:index/externalLocation:ExternalLocation                urn:pulumi:dev::REDACTED::databricks:index/externalLocation:ExternalLocation::REDACTED
databricks:index/externalLocation:ExternalLocation                urn:pulumi:dev::REDACTED::databricks:index/externalLocation:ExternalLocation::REDACTED
databricks:index/externalLocation:ExternalLocation                urn:pulumi:dev::REDACTED::databricks:index/externalLocation:ExternalLocation::REDACTED
databricks:index/directory:Directory                              urn:pulumi:dev::REDACTED::databricks:index/directory:Directory::REDACTED
databricks:index/entitlements:Entitlements                        urn:pulumi:dev::REDACTED::databricks:index/entitlements:Entitlements::REDACTED
databricks:index/entitlements:Entitlements                        urn:pulumi:dev::REDACTED::databricks:index/entitlements:Entitlements::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/entitlements:Entitlements                        urn:pulumi:dev::REDACTED::databricks:index/entitlements:Entitlements::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/catalog:Catalog                                  urn:pulumi:dev::REDACTED::databricks:index/catalog:Catalog::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/catalog:Catalog                                  urn:pulumi:dev::REDACTED::databricks:index/catalog:Catalog::REDACTED
databricks:index/catalog:Catalog                                  urn:pulumi:dev::REDACTED::databricks:index/catalog:Catalog::REDACTED
databricks:index/catalog:Catalog                                  urn:pulumi:dev::REDACTED::databricks:index/catalog:Catalog::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/schema:Schema                                    urn:pulumi:dev::REDACTED::databricks:index/schema:Schema::REDACTED
databricks:index/schema:Schema                                    urn:pulumi:dev::REDACTED::databricks:index/schema:Schema::REDACTED
databricks:index/schema:Schema                                    urn:pulumi:dev::REDACTED::databricks:index/schema:Schema::REDACTED
databricks:index/grants:Grants                                    urn:pulumi:dev::REDACTED::databricks:index/grants:Grants::REDACTED
databricks:index/catalogWorkspaceBinding:CatalogWorkspaceBinding  urn:pulumi:dev::REDACTED::databricks:index/catalogWorkspaceBinding:CatalogWorkspaceBinding::REDACTED
databricks:index/grants:Grants                                    urn:pulumi:dev::REDACTED::databricks:index/grants:Grants::REDACTED
databricks:index/schema:Schema                                    urn:pulumi:dev::REDACTED::databricks:index/schema:Schema::REDACTED
databricks:index/grants:Grants                                    urn:pulumi:dev::REDACTED::databricks:index/grants:Grants::REDACTED
databricks:index/schema:Schema                                    urn:pulumi:dev::REDACTED::databricks:index/schema:Schema::REDACTED
databricks:index/directory:Directory                              urn:pulumi:dev::REDACTED::databricks:index/directory:Directory::REDACTED
databricks:index/grants:Grants                                    urn:pulumi:dev::REDACTED::databricks:index/grants:Grants::REDACTED
databricks:index/schema:Schema                                    urn:pulumi:dev::REDACTED::databricks:index/schema:Schema::REDACTED
databricks:index/schema:Schema                                    urn:pulumi:dev::REDACTED::databricks:index/schema:Schema::REDACTED
databricks:index/directory:Directory                              urn:pulumi:dev::REDACTED::databricks:index/directory:Directory::REDACTED
databricks:index/directory:Directory                              urn:pulumi:dev::REDACTED::databricks:index/directory:Directory::REDACTED
databricks:index/catalogWorkspaceBinding:CatalogWorkspaceBinding  urn:pulumi:dev::REDACTED::databricks:index/catalogWorkspaceBinding:CatalogWorkspaceBinding::REDACTED
databricks:index/directory:Directory                              urn:pulumi:dev::REDACTED::databricks:index/directory:Directory::REDACTED
databricks:index/catalogWorkspaceBinding:CatalogWorkspaceBinding  urn:pulumi:dev::REDACTED::databricks:index/catalogWorkspaceBinding:CatalogWorkspaceBinding::REDACTED
databricks:index/catalogWorkspaceBinding:CatalogWorkspaceBinding  urn:pulumi:dev::REDACTED::databricks:index/catalogWorkspaceBinding:CatalogWorkspaceBinding::REDACTED
databricks:index/grants:Grants                                    urn:pulumi:dev::REDACTED::databricks:index/grants:Grants::REDACTED
databricks:index/grants:Grants                                    urn:pulumi:dev::REDACTED::databricks:index/grants:Grants::REDACTED
databricks:index/grants:Grants                                    urn:pulumi:dev::REDACTED::databricks:index/grants:Grants::REDACTED
databricks:index/grants:Grants                                    urn:pulumi:dev::REDACTED::databricks:index/grants:Grants::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/grants:Grants                                    urn:pulumi:dev::REDACTED::databricks:index/grants:Grants::REDACTED
databricks:index/grants:Grants                                    urn:pulumi:dev::REDACTED::databricks:index/grants:Grants::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED
databricks:index/grants:Grants                                    urn:pulumi:dev::REDACTED::databricks:index/grants:Grants::REDACTED
databricks:index/permissions:Permissions                          urn:pulumi:dev::REDACTED::databricks:index/permissions:Permissions::REDACTED


Found no pending operations associated with dev

Backend
Name           REDACTED
URL            REDACTED
User           REDACTED
Organizations
Token type     personal

Dependencies:
NAME            VERSION
black           24.4.0
boto3           1.34.84
REDACTED  0.1.0
Faker           24.8.0
locust          2.25.0
pip             23.3.1
pytest          8.1.1
python-ulid     2.4.0.post0

Pulumi locates its logs in /var/folders/c6/r0qc_tl17pj7xsl4y1gyxqdw0000gp/T/ by default

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> Calling pulumi up isn't working since 3.112.0. 3.111.1 is working fine.

Is this changing the version of the pulumi python library or the CLI or both? Does it work on 3.112 CLI if you use 3.111.1 of the python library? Likewise how about 3.111.1 CLI with 3.112 python library?

**Comment by nexeck** [comment]
Not sure if it helps, thats with --debug (Python lib & CLI 3.113.0)

```
debug: waiting for quiescence; 8874 outputs outstanding
    debug: waiting for quiescence; 8873 outputs outstanding
    debug: waiting for quiescence; 8872 outputs outstanding
    debug: waiting for quiescence; 8871 outputs outstanding
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 191, in <module>
        loop.run_until_complete(coro)
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/Users/REDACTED/.venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 132, in run_in_stack
        await run_pulumi_func(run)
      File "/Users/REDACTED/.venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 53, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/REDACTED/.venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 109, in wait_for_rpcs
        await task
    IndexError: list index out of range

```

**Comment by Frassle** [comment]
Ok thanks that narrows it down to an issue with the library not the CLI. I have a suspicion to what change could have caused this.

**Comment by Frassle** [comment]
So https://github.com/pulumi/pulumi/pull/15744/files changed how we wait for outputs and async tasks. I think this may have had the effect that an exception your code was throwing that used to be ignored/missed is now detected.

Worth taking a look at https://docs.python.org/3/library/asyncio-dev.html and running your program on 3.111.1 with debugging turned on to see if it picks up any uncaught exceptions.

**Comment by nexeck** [comment]
Thanks for the quick support

The following code caused the issue:

```
import time

import pulumi


async def wait_for_eventual_consistency(args: list) -> bool:
    resource_id = args[0]
    duration = 5 if args[1] is None else int(args[1])

    if not pulumi.runtime.is_dry_run():
        pulumi.log.info(
            f"Waiting {duration} seconds for eventual consistency for resource {resource_id}"
        )

        time.sleep(duration)
    return True
```

```
pulumi.Output.all(account.id).apply(pkg.wait_for_eventual_consistency)
```

With this error:

```
        duration = 5 if args[1] is None else int(args[1])
                        ~~~~^^^
    IndexError: list index out of range
```
