### ISSUE TITLE
xRegisterStackTransform causes an error if there is no stack outputs

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#15973]
### What happened?

While attempting to use xRegisterStackTransform I encountered the following error when I don't have a stack output set.
```
Diagnostics:
  pulumi:pulumi:Stack (awsx-ts-dev):
    error: failed to register stack transform: Error: 1 CANCELLED: Call cancelled
    error: Error: Channel has been shut down
        at InternalChannel.createCall (/Users/zbuchheit/work/tmp/awsx-ts/node_modules/@grpc/grpc-js/src/internal-channel.ts:835:13)
        at ChannelImplementation.createCall (/Users/zbuchheit/work/tmp/awsx-ts/node_modules/@grpc/grpc-js/src/channel.ts:166:33)
        at getCall (/Users/zbuchheit/work/tmp/awsx-ts/node_modules/@grpc/grpc-js/src/client-interceptors.ts:349:24)
        at getBottomInterceptingCall (/Users/zbuchheit/work/tmp/awsx-ts/node_modules/@grpc/grpc-js/src/client-interceptors.ts:480:16)
        at /Users/zbuchheit/work/tmp/awsx-ts/node_modules/@grpc/grpc-js/src/client-interceptors.ts:574:7
        at getInterceptingCall (/Users/zbuchheit/work/tmp/awsx-ts/node_modules/@grpc/grpc-js/src/client-interceptors.ts:576:10)
        at ServiceClientImpl.makeUnaryRequest (/Users/zbuchheit/work/tmp/awsx-ts/node_modules/@grpc/grpc-js/src/client.ts:312:64)
        at ServiceClientImpl.registerResource (/Users/zbuchheit/work/tmp/awsx-ts/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
        at /Users/zbuchheit/work/tmp/awsx-ts/node_modules/@pulumi/runtime/resource.ts:545:41
        at new Promise (<anonymous>)
```

### Repro Code
```ts
import * as pulumi from "@pulumi/pulumi";
import * as awsx from "@pulumi/awsx";

pulumi.runtime.xRegisterStackTransform(args => {
    if (args.type === "awsx:ec2:Vpc") {
    console.log(args.name, args.type, args.props)
    }
    return undefined;
})

const vpc = new awsx.ec2.Vpc("vpc", {
    natGateways: {
        strategy: "None"
    },
});

// export const subnet = vpc.vpc.urn; //Uncomment to fix the issue
```

### Repro Steps

1. Run `pulumi up`

### Output of `pulumi about`

```
CLI          
Version      3.113.0
Go Version   go1.22.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.31.0
awsx    2.7.0
docker  4.5.3
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/zbuchheit/.nvm/versions/node/v18.17.1/bin/node' version='v18.17.1'

Current Stack: zbuchheit-pulumi-corp/awsx-ts/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/zbuchheit-pulumi-corp
User           zbuchheit-pulumi-corp
Organizations  zbuchheit-pulumi-corp
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.113.0
@types/node     18.19.31
typescript      5.4.5
@pulumi/aws     6.31.0
@pulumi/awsx    2.7.0

Pulumi locates its logs in /var/folders/lh/l71cdh810xb33t0jc7qmt5_80000gn/T/ by default

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Similar to https://github.com/pulumi/pulumi/issues/15984 looks like this is something specific about component providers. We already have tests for normal resources and stack transforms without outputs that work fine.

**Comment by Frassle** [comment]
Ah nope got a repro with just a single normal custom resource, it's just intermittent.
