### ISSUE TITLE
fatal: An assertion has failed: Expected to find parent node

### ISSUE THREAD

**Issue by ctolkien** [pulumi/pulumi#1600]
```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================




Pulumi Version:   v0.14.2
Go Version:       go1.10
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            fatal: An assertion has failed: Expected to find parent node 'urn:pulumi:pulumi-test-dev::Soda-Digital/pulumi-test::pulumi:pulumi:Stack::Soda-Digital/pulumi-test-pulumi-test-dev' in checkpoint tree nodes

goroutine 1 [running]:
runtime/debug.Stack(0xc04245b3a0, 0xcc94e0, 0xc04239ea70)
        C:/go/src/runtime/debug/stack.go:24 +0xae
main.panicHandler()
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/main.go:30 +0x78
panic(0xcc94e0, 0xc04239ea70)
        C:/go/src/runtime/panic.go:505 +0x237
github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc04247c0d0, 0xc4)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xf0
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xd90e00, 0xe85a67, 0x3a, 0xc04245b630, 0x1, 0x1)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x12d
github.com/pulumi/pulumi/pkg/operations.makeResourceTreeMap(0xc0420040b8, 0x1, 0x1, 0x0, 0xffffffffffffffff)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/operations/resources.go:76 +0x48a
github.com/pulumi/pulumi/pkg/operations.NewResourceTree(0xc0420040b8, 0x1, 0x1, 0xc0423851a0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/operations/resources.go:44 +0x46
github.com/pulumi/pulumi/pkg/backend/local.GetLogsForTarget(0xc042385110, 0xc042466320, 0x0, 0x0, 0xc0422ac870, 0xc042385110, 0x0, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/local/backend.go:348 +0xb7
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).GetLogs(0xc0422f8b70, 0xf3e8c0, 0xc042086078, 0xf38b40, 0xc0422ac870, 0xc042466320, 0x0, 0x0, 0x5d, 0x80, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:1124 +0x191
github.com/pulumi/pulumi/pkg/backend.GetStackLogs(0xf3e8c0, 0xc042086078, 0xf45520, 0xc0420b4180, 0xc042466320, 0x0, 0x0, 0x2, 0x2, 0x5d, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/stack.go:104 +0xdc
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudStack).GetLogs(0xc0420b4180, 0xf3e8c0, 0xc042086078, 0xc042466320, 0x0, 0x0, 0x0, 0x0, 0x3e, 0x3, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/stack.go:144 +0x80
github.com/pulumi/pulumi/cmd.newLogsCmd.func1(0xc04222fb00, 0x144c340, 0x0, 0x0, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/cmd/logs.go:76 +0x6f5
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc04222fb00, 0x144c340, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:92 +0x61
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute(0xc04222fb00, 0x144c340, 0x0, 0x0, 0xc04222fb00, 0x144c340)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:702 +0x2cd
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc04222e480, 0xc0423f8b79, 0xc0423f8b78, 0xc042408190)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:783 +0x2eb
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute(0xc04222e480, 0xe98970, 0x404083)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:736 +0x32
main.main()
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/main.go:49 +0x52
```

**Comment by ellismg** [comment]
Thanks for opening this, @ctolkien.  Do you have any more details as to what was going on here when `pulumi logs` gave you this error?  Did you happen to change the project name by editing `Pulumi.yaml` between when you deployed the stack and when you tried to view its logs?

**Comment by ctolkien** [comment]
Hi,

I managed to get my stacks into a "bad state", Possibly via #1597, but I don't really have much more to go on. I was trying out various means of updating a stack and they were all failing (due to the Azure endpoint throwing a 400, one of the options objects I was passing in wasn't as it expected).

No edits were performed to Pulumi.yaml however.

**Comment by swgillespie** [comment]
Moving this out to 0.18, this is a crash in `pulumi logs`.

**Comment by swgillespie** [comment]
This bug is quite old and many things have changed. Closing this out unless we can get a newer repro.
