### ISSUE TITLE
Python panic when `config.get()` used when it should be  `config.get_object()`

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#16045]
### What happened?

* Program gets a list of subnets from config but accidentally used `config.get()` instead of `config.get_object()`
* `pulumi preview` throws a panic for the ecs.service resource that references the subnets.

### Example

Example code is based on customer-provided code which I do not want to share publicly.
Contact me for a link to code.

### Output of `pulumi about`

CLI          
Version      3.113.3
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.32.0
resource  docker  4.5.3
language  python  unknown

Host     
OS       darwin
Version  13.6.6
Arch     x86_64

This project is written in python: executable='/Users/mitch/Downloads/wmg-panic-5070/customer-engineering/customer-support/5070/venv/bin/python3' version='3.10.11'

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME           VERSION
pip            23.0.1
pulumi_aws     6.32.0
pulumi_docker  4.5.3
setuptools     65.5.0

### Additional context

Correcting the code to use `get_object()` (and a fix in the code where subnets are referenced) fixes the problem.
But finding the root-cause was hard given the panic output instead of a more prescriptive the error message.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
This is unrelated to config. Looks like the panic is coming from the bridge. Here's a minimal repro:

```python
import pulumi_aws as aws

ecs_subnets = '["first","second"]'
# ecs_subnets = ["first", "second"]

security_group = aws.ec2.SecurityGroup("security-group",)

service = aws.ecs.Service("service",
    network_configuration=aws.ecs.ServiceNetworkConfigurationArgs(
        security_groups=[security_group.id],
        subnets=ecs_subnets,
    ),
)
```

Running `pulumi preview` yields:

```
$ pulumi preview
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/...

     Type                      Name            Plan       Info
 +   pulumi:pulumi:Stack       ecsrepro-dev    create     1 error; 42 messages
 +   ├─ aws:ec2:SecurityGroup  security-group  create
 +   └─ aws:ecs:Service        service         create     1 error

Diagnostics:
  aws:ecs:Service (service):
    error: Preview failed: error reading from server: EOF

  pulumi:pulumi:Stack (ecsrepro-dev):
    panic: value has no attribute of that name
    goroutine 101 [running]:
    github.com/zclconf/go-cty/cty.Value.GetAttr({{{0x116fd8880?, 0x14003d404e0?}}, {0x114eb23a0?, 0x14003eb6120?}}, {0x111e024ab, 0x21})
    	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.3/cty/value_ops.go:808 +0x270
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2/internal/tf/plans/objchange.proposedNewAttributes(0x14003ead3e0, {{{0x116fd8880?, 0x14003d40410?}}, {0x114eb23a0?, 0x14003eadf20?}}, {{{0x116fd8880?, 0x14003d404e0?}}, {0x114eb23a0?, 0x14003eb6120?}})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfshim/sdk-v2/internal/tf/plans/objchange/objchange.go:289 +0x170
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2/internal/tf/plans/objchange.proposedNew(0x14003ead3b0, {{{0x116fd8880?, 0x14003d40410?}}, {0x114eb23a0?, 0x14003eadf20?}}, {{{0x116fd8880?, 0x14003d404e0?}}, {0x114eb23a0?, 0x14003eb6120?}})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfshim/sdk-v2/internal/tf/plans/objchange/objchange.go:89 +0xe0
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2/internal/tf/plans/objchange.ProposedNew(0x116fd8688?, {{{0x116fd8880?, 0x14003d40410?}}, {0x114eb23a0?, 0x14003eadf20?}}, {{{0x116fd8880?, 0x14003d404e0?}}, {0x114eb23a0?, 0x14003eb6120?}})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfshim/sdk-v2/internal/tf/plans/objchange/objchange.go:46 +0xec
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.proposedNew(0x14003e9e2d0?, {{{0x116fd8688?, 0x14003a06288?}}, {0x114eb23a0?, 0x14003e9fd10?}}, {{{0x116fd8688?, 0x14003a06118?}}, {0x114eb23a0?, 0x14003e96600?}})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfshim/sdk-v2/proposed_new.go:34 +0x104
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.simpleDiffViaPlanState({0x116fd8228, 0x14003e70780}, 0x0?, 0x0?, {{{0x116fd8688?, 0x14003a06118?}}, {0x114eb23a0?, 0x14003e96600?}}, {0x116d7a740, 0x1400212ea90})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfshim/sdk-v2/provider_diff.go:176 +0xac
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.simpleDiff({0x114eb5220?, {0x14003a11ea0?, 0x111cd11f3?, 0xf?}}, {0x116fd8228, 0x14003e70780}, 0x111c91fc7?, 0x8?, 0x14001695b30?, 0x1212f3ab0?, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfshim/sdk-v2/provider_diff.go:125 +0x638
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0x14000701c80?, {0x1400208d210?, 0x14003d0f298?, 0x1047b68b4?}}, {0x116fd8228, 0x14003e70780}, {0x111cd11f3, 0xf}, {0x0?, 0x0}, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfshim/sdk-v2/provider_diff.go:75 +0x294
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.(*providerWithPlanResourceChangeDispatch).Diff(0x14002250570, {0x116fd8228, 0x14003e70780}, {0x111cd11f3, 0xf}, {0x0, 0x0}, {0x116e104a0, 0x14003a11ea0}, {0x0?, ...})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfshim/sdk-v2/provider2.go:691 +0xfc
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0x14001895980, {0x116fd8228?, 0x14003e70390?}, 0x1400391b540)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.80.0/pkg/tfbridge/provider.go:1048 +0x598
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Create.func1({0x117053800?, 0x14001895980?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:375 +0x3c
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.resourceMethod[...](0x14003865260?, 0x14003d0f6c8, 0x14003d0f6a8?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:334 +0xc4
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Create(0x14003d0f708?, {0x116fd8228?, 0x14003e70390?}, 0x114483680?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:374 +0x5c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x116fd8228, 0x14003e70390}, {0x116514b80?, 0x1400391b540})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.112.0/proto/go/provider_grpc.pb.go:593 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x116fd8228, 0x14003e70270}, {0x116514b80, 0x1400391b540}, 0x14003e68100, 0x14003dc3bd8)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x116ba2360?, 0x14003865260}, {0x116fd8228, 0x14003e70270}, 0x14003907880, 0x14003e0e160)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.112.0/proto/go/provider_grpc.pb.go:595 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x14003caa000, {0x116fd8228, 0x14003e701e0}, {0x11701cf00, 0x14003752680}, 0x14003dccd80, 0x140038ec360, 0x12129c720, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1386 +0xba0
    google.golang.org/grpc.(*Server).handleStream(0x14003caa000, {0x11701cf00, 0x14003752680}, 0x14003dccd80)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1797 +0xc70
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1027 +0x8c
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 31
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1038 +0x150

    error: preview failed
```

Uncommenting the commented line to make `ecs_subnets` a list of strings rather than a string allows the preview to succeed without panicking:

```
$ pulumi preview
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/...

     Type                      Name            Plan
 +   pulumi:pulumi:Stack       ecsrepro-dev    create
 +   ├─ aws:ec2:SecurityGroup  security-group  create
 +   └─ aws:ecs:Service        service         create

Resources:
    + 3 to create
```

Interestingly, if I don't set `security_groups` or set it to a prompt string array, I don't get a panic, but get the expected error:

```python
import pulumi_aws as aws

ecs_subnets = '["first","second"]'
# ecs_subnets = ["first", "second"]

# security_group = aws.ec2.SecurityGroup("security-group",)

service = aws.ecs.Service("service",
    network_configuration=aws.ecs.ServiceNetworkConfigurationArgs(
        # security_groups=[security_group.id],
        subnets=ecs_subnets,
    ),
)
```

```
$ pulumi preview
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/...

     Type                 Name          Plan       Info
 +   pulumi:pulumi:Stack  ecsrepro-dev  create
     └─ aws:ecs:Service   service                  1 error

Diagnostics:
  aws:ecs:Service (service):
    error: aws:ecs/service:Service resource 'service' has a problem: Attribute must be a list. Examine values at 'service.networkConfiguration.subnets'.
```

Transferring to the aws repo for further triage.
