### ISSUE TITLE
Pulumi automation does not understand 'output-change'

### ISSUE THREAD

**Issue by Phil1972** [pulumi/pulumi#16126]
### What happened?

I am trying to preview a stack with the newest CLI 3.115.0 and for resources that change, the preview shows 'output-change' instead of the proper verb I guess and that crashes the automation module.

![image](https://github.com/pulumi/pulumi/assets/40364427/4b30e42c-1830-446b-856e-32e52aee162e)

### Example

See report above

and the automation fails with this:
`System.InvalidOperationException: 'output-change' is not valid Pulumi.Automation.OperationType
   at Pulumi.Automation.Serialization.OperationTypeConverter.Convert(String input)
   at Pulumi.Automation.Serialization.Json.ResourceChangesJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at Pulumi.Automation.Serialization.Json.MapToModelJsonConverter`2.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at Pulumi.Automation.Events.EventLogWatcher.ReadEventsOnce()
   at Pulumi.Automation.Events.EventLogWatcher.ReadEventsOnce()
   at Pulumi.Automation.Events.EventLogWatcher.PollForEvents(CancellationToken externalCancellationToken)
   at Pulumi.Automation.Events.EventLogWatcher.AwaitPollingTask()
   at Pulumi.Automation.Events.EventLogWatcher.Stop()
   at Pulumi.Automation.Commands.LocalPulumiCommand.RunAsync(IList`1 args, String workingDir, IDictionary`2 additionalEnv, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)
   at Pulumi.Automation.Workspace.RunStackCommandAsync(String stackName, IList`1 args, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.RunCommandAsync(IList`1 args, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.PreviewAsync(PreviewOptions options, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.PreviewAsync(PreviewOptions options, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Program.Preview(WorkspaceStack stack, Int32 attempt) in /home/vsts/work/1/s/src/Infra.Automation/Program.cs:line 230`

### Output of `pulumi about`

```
CLI
Version      3.115.0
Go Version   go1.22.2
Go Compiler  gc
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
This looks like a regression due to https://github.com/pulumi/pulumi/pull/15903

Before that, we wouldn't show an `output-change`/`output-changed` in the summary.

## v3.114.0

```
$ pulumi up
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/...

     Type                       Name        Plan
 +   pulumi:pulumi:Stack        rndtst-dev  create
 +   └─ random:index:RandomPet  username    create

Outputs:
    name: output<string>

Resources:
    + 2 to create

Do you want to perform this update? yes
Updating (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/...

     Type                       Name        Status
 +   pulumi:pulumi:Stack        rndtst-dev  created (0.70s)
 +   └─ random:index:RandomPet  username    created (0.12s)

Outputs:
    name: "equipped-civet"

Resources:
    + 2 created

Duration: 1s
```

## v3.115.1

```
$ pulumi up
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/...

     Type                       Name        Plan
 +   pulumi:pulumi:Stack        rndtst-dev  create
 +   └─ random:index:RandomPet  username    create

Outputs:
    name: output<string>

Resources:
    + 2 to create
    ~ 1 to output-change
    3 changes

Do you want to perform this update? yes
Updating (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/...

     Type                       Name        Status
 +   pulumi:pulumi:Stack        rndtst-dev  created (1s)
 +   └─ random:index:RandomPet  username    created (0.13s)

Outputs:
    name: "sharing-robin"

Resources:
    + 2 created
    ~ 1 output-changed
    3 changes

Duration: 2s
```

@PollRobots, can we elide `output-change` from the output?
