### ISSUE TITLE
panic: fatal: An assertion has failed: ignoreErrors and ContinueOnError are mutually exclusive

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#16177]
A user reports "this is what I receive when adding --continue-on-error option (pulumi v3.115.2)".

```
Updating (github)

View Live: https://app.pulumi.com/portx/testcu-github/github/updates/213

@ Updating......

panic: fatal: An assertion has failed: ignoreErrors and ContinueOnError are mutually exclusive

goroutine 132 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x1?, {0x2c0107d?, 0xc001f8f888?}, {0x0?, 0xc000101610?, 0xc000101008?})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:35 +0xe8
github.com/pulumi/pulumi/pkg/v3/resource/deploy.newStepExecutor({0x34c8c18, 0xc002406aa0}, 0xc002466290, 0xc00242e210, {{0x7e7897bdb558, 0xc0023c2140}, 0x40, 0x1, 0x0, {{0x4bae900, ...}, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:572 +0x7b
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).refresh(0xc0022179e0, {0x34c8be0, 0xc001e447e0}, {{0x7e7897bdb558, 0xc0023c2140}, 0x40, 0x1, 0x0, {{0x4bae900, 0x0, ...}, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:563 +0x4d5
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute(0xc0022179e0, {0x34c8be0, 0xc001e447e0}, {{0x7e7897bdb558, 0xc0023c2140}, 0x40, 0x1, 0x0, {{0x4bae900, 0x0, ...}, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:154 +0x230
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Deployment).Execute(...)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:558
github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run.func1()
        /home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:310 +0x290
created by github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run in goroutine 1
        /home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:295 +0x21d
```

**Comment by lukehoban** [comment]
This appears to be triggered via `pulumi up --refresh`.
