### ISSUE TITLE
Pulumi update fails with panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Phil1972** [pulumi/pulumi#16258]
### What happened?

While running an update on one of our stack, pulumi crashes with the following:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf421b7]

goroutine 128 [running]:
github.com/pulumi/pulumi/pkg/v3/resource/graph.markAsDependency({0xc002279440?, 0xc006153798?}, 0xc006153798, 0xc006153858)
	/home/runner/work/pulumi/pulumi/pkg/resource/graph/dependency_graph.go:282 +0x77
github.com/pulumi/pulumi/pkg/v3/resource/graph.(*DependencyGraph).TransitiveDependenciesOf(0xc002397b60, 0xc000d551e0)
	/home/runner/work/pulumi/pulumi/pkg/resource/graph/dependency_graph.go:255 +0x1e9
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).performDeletes(0xc002397cb0, {0x34cd438, 0xc003ea1ae0}, {{0x4bb5940?, 0xc0022b2f00?, 0x1?}, 0xc0022b2f00?})
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:409 +0x66d
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute.func3(0xc00442a5a0, 0xc002397cb0, 0xc00592ae60, {{0x7f91a54303e8, 0xc0017ee0f0}, 0x8, 0x0, 0x0, {{0x4bb5940, 0x0, ...}, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:239 +0x425
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute(0xc002397cb0, {0x34cd400, 0xc002397c20}, {{0x7f91a54303e8, 0xc0017ee0f0}, 0x8, 0x0, 0x0, {{0x4bb5940, 0x0, ...}, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:271 +0x579
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Deployment).Execute(...)
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:558
github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run.func1()
	/home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:310 +0x290
created by github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run in goroutine 1
	/home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:295 +0x21d


   at Pulumi.Automation.Commands.LocalPulumiCommand.RunAsyncInner(IList`1 args, String workingDir, IDictionary`2 additionalEnv, Action`1 onStandardOutput, Action`1 onStandardError, EventLogFile eventLogFile, CancellationToken cancellationToken)
   at Pulumi.Automation.Commands.LocalPulumiCommand.RunAsync(IList`1 args, String workingDir, IDictionary`2 additionalEnv, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)
   at Pulumi.Automation.Workspace.RunStackCommandAsync(String stackName, IList`1 args, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.RunCommandAsync(IList`1 args, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.UpAsync(UpOptions options, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.UpAsync(UpOptions options, CancellationToken cancellationToken)
```

of course we are stuck at the moment.  Hopefully someone has already seen this.  I will add more info as I try different scenarios.

NOTES:
- Preview and refresh operations work fine.

Edits:
- Tried different CLI versions(3.115.1), same problem
- Nugets for pulumi components are up-to-date
- Only does it for one of our stack, other similar stacks are fine (in different azure regions)

Edits2:
- I removed the ContinueOnError flag and resolved the conflicts prior to running the update, and it went through.  So I assume there is something wrong when using the ContinueOnError while there are conflicts that causes this problem.  As I mentioned, this issue did not reproduce in our other stacks which had similar conflicting problems.  The problems were the renaming of some role assignments causing errors of the sort:

> error: autorest/azure: Service returned an error. Status=<nil> Code="RoleAssignmentExists" Message="The role assignment already exists."

This is always a challenge for us as pulumi is not 'smart' enough when dealing with those in azure.  I understand it is not trivial to fix but it would require the role assignment with the same scope/principalId to be deleted BEFORE trying to create or replace the others.
 
### Example

Pulumi update -c Continue-on-error

### Output of `pulumi about`

```
CLI
Version      3.115.0
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure         5.78.0
resource  azure-native  2.42.1
resource  azuread       5.50.0
resource  azuredevops   3.1.1
resource  confluent     0.2.2
language  dotnet        unknown
resource  kafka         3.7.4
resource  kubernetes    4.12.0

...

Dependencies:
NAME                                            VERSION
Azure.Identity                                  1.11.3
Azure.Security.KeyVault.Secrets                 4.6.0
KubernetesClient                                14.0.2
Microsoft.Extensions.Localization.Abstractions  8.0.5
Pulumi                                          3.63.1
Pulumi.Azure                                    5.78.0
Pulumi.AzureAD                                  5.50.0
Pulumi.AzureNative                              2.42.1
Pulumi.Confluent                                0.2.2
Pulumi.Kafka                                    3.7.4
Pulumi.Kubernetes                               4.12.0
System.IO.Abstractions                          21.0.2
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
Thanks for reporting this issue. We'll take a look.
