### ISSUE TITLE
Panic during preview

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi#1630]
I encountered this panic while previewing a rather large stack. I will try to make a minimal reproduction to attach to this issue, but in the meantime, here is the backtrace:

```
panic: fatal: An assertion has failed

goroutine 746 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(0x1a82c24, 0x17)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xf3
github.com/pulumi/pulumi/pkg/util/contract.Assert(0x27c8600)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26 +0x49
github.com/pulumi/pulumi/pkg/resource/plugin.(*provider).Read(0xc420080690, 0xc4203c6700, 0x76, 0x0, 0x0, 0xc4207b2270, 0x0, 0xc4204226c0, 0x2d)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/plugin/provider_plugin.go:293 +0x5e
github.com/pulumi/pulumi/pkg/resource/deploy.(*resmon).ReadResource(0xc4204189c0, 0x1fdbc80, 0xc4207b21e0, 0xc4207be000, 0xc4204189c0, 0x1, 0x1)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/source_eval.go:326 +0x615
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_ReadResource_Handler.func1(0x1fdbc80, 0xc4207b21e0, 0x19f1d00, 0xc4207be000, 0x1fdbc80, 0xc4207b21e0, 0x1fe12e0, 0x20638c8)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:349 +0x86
github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1fdbc80, 0xc4207b21e0, 0x19f1d00, 0xc4207be000, 0xc4202202a0, 0xc420220340, 0x0, 0x0, 0x1fccac0, 0xc42003f050)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_ReadResource_Handler(0x19b6520, 0xc4204189c0, 0x1fdbc80, 0xc4207b2000, 0xc42019a070, 0xc4204f8740, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:351 +0x16d
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4204ce580, 0x1fdf480, 0xc42061d080, 0xc4207c97c0, 0xc4204154d0, 0x2033c78, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:923 +0x92d
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4204ce580, 0x1fdf480, 0xc42061d080, 0xc4207c97c0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:1148 +0x1528
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420535990, 0xc4204ce580, 0x1fdf480, 0xc42061d080, 0xc4207c97c0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:635 +0xa1
```

**Comment by jen20** [comment]
This is using the Node runtime. Annoyingly, trying to make a minimal reproduction of it failed so far. I can give it another shot if it will be useful.

**Comment by swgillespie** [comment]
That would be helpful, if you don't mind!

**Comment by joeduffy** [comment]
I guess we don't have a solid repro for this, so I'll reluctantly close out. @jen20 if you believe this might still be an issue, please feel free to reopen, and we can spend some time trying to create a repro.
