### ISSUE TITLE
RecursionError: maximum recursion depth exceeded during pulumi up

### ISSUE THREAD

**Issue by piotr-bzdyl-vertexinc** [pulumi/pulumi#16328]
### What happened?

Recently we get `RecursionError` being thrown from Pulumi programs using Python. It seems it's related to #11887 and [now we should have more information for troubleshooting](https://github.com/pulumi/pulumi/issues/11887#issuecomment-1397756160).

Example errors (they seem to differ between occurrences):

<details>

<summary>Error 1</summary>

```
error: Program failed with an unhandled exception:
Traceback (most recent call last):
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 872, in do_register
    resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 230, in prepare_resource
    urns = await _expand_dependencies(deps, from_resource=res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 311, in _expand_dependencies
    await _add_dependency(urns, d, from_resource)
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/rpc.py", line 297, in _add_dependency
    urn = await res.urn.future()
                ^^^^^^^^^^^^^^^^
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/output.py", line 132, in future
    return asyncio.ensure_future(get_value())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/tasks.py", line 659, in ensure_future
    return _ensure_future(coro_or_future, loop=loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/tasks.py", line 680, in _ensure_future
    return loop.create_task(coro_or_future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 437, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 766, in call_soon
    handle = self._call_soon(callback, args, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 782, in _call_soon
    handle = events.Handle(callback, args, self, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/events.py", line 44, in __init__
    if self._loop.get_debug():
       ^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/tokenize.py", line 398, in open
    encoding, lines = detect_encoding(buffer.readline)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/tokenize.py", line 367, in detect_encoding
    first = read_or_stop()
            ^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/tokenize.py", line 325, in read_or_stop
    return readline()
           ^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
    result = await rpc
             ^^^^^^^^^
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 986, in do_register
    f"exception when preparing or executing rpc: {traceback.format_exc()}"
                                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/traceback.py", line 184, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/traceback.py", line 139, in format_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/traceback.py", line 728, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/traceback.py", line 433, in _extract_from_extended_frame_gen
    f.line
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/traceback.py", line 318, in line
    self._line = linecache.getline(self.filename, self.lineno)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/tokenize.py", line 404, in open
    buffer.close()
RecursionError: maximum recursion depth exceeded while calling a Python object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/pulumi/3.101.1/x64/pulumi-language-python-exec", line 197, in <module>
    loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 137, in run_in_stack
    await run_pulumi_func(lambda: Stack(func))
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
    await wait_for_rpcs()
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 83, in wait_for_rpcs
    raise exn from cause
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 75, in wait_for_rpcs
    await rpc_manager.rpcs.pop()
RecursionError: maximum recursion depth exceeded while calling a Python object
```
</details>

<details>

<summary>Error 2</summary>

```
error: Program failed with an unhandled exception:
Traceback (most recent call last):
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 1009, in do_register
    log.debug(f"resource registration successful: ty={ty}, urn={resp.urn}")
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/log.py", line 45, in debug
    _log(engine, engine_pb2.DEBUG, msg, resource, stream_id, ephemeral)
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/log.py", line 144, in _log
    engine.Log(req)
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/grpc/_channel.py", line 1028, in __call__
    state, call, = self._blocking(request, timeout, metadata, credentials,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/grpc/_channel.py", line 1005, in _blocking
    state, operations, deadline, rendezvous = self._prepare(
                                              ^^^^^^^^^^^^^^
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/grpc/_channel.py", line 984, in _prepare
    state = _RPCState(_UNARY_UNARY_INITIAL_DUE, None, None, None, None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/grpc/_channel.py", line 124, in __init__
    self.condition = threading.Condition()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/threading.py", line 245, in __init__
    lock = RLock()
           ^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/threading.py", line 101, in RLock
    return _CRLock(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
    result = await rpc
             ^^^^^^^^^
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/resource.py", line 1040, in do_register
    log.debug(f"exception after executing rpc: {traceback.format_exc()}")
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/traceback.py", line 184, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/traceback.py", line 139, in format_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/traceback.py", line 728, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/traceback.py", line 433, in _extract_from_extended_frame_gen
    f.line
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/traceback.py", line 318, in line
    self._line = linecache.getline(self.filename, self.lineno)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/tokenize.py", line 396, in open
    buffer = _builtin_open(filename, 'rb')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/pulumi/3.101.1/x64/pulumi-language-python-exec", line 197, in <module>
    loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 137, in run_in_stack
    await run_pulumi_func(lambda: Stack(func))
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
    await wait_for_rpcs()
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 83, in wait_for_rpcs
    raise exn from cause
  File "/runner/_work/my-project/my-project/venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 75, in wait_for_rpcs
    await rpc_manager.rpcs.pop()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

</details>

### Example

I cannot share the code and I'm not how to recreate it in a simple way. Our pulumi program manages ~3000 resources (using pulumi-github and pulumi-aws providers). We are using pulumi service for managing state.

### Output of `pulumi about`

I don't have the exact output from pulumi about as it's being run in our CI process.

Pulumi version: 3.101.1
Python version: 3.11
requirements.txt:
```
pulumi==3.101.1
pulumi-aws==6.37.0
pulumi-github==5.25.0
pulumi-terraform==5.6.7
pulumi-tls==4.6.1
pydantic>=2.4.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
I see `_add_dependency` in the first error, which is something we do call recursively. That could be where we're hitting the limit, in which case we could look into making it iterative rather than recursive. We also use recursion elsewhere, when serializing and deserializing

@piotr-bzdyl-vertexinc, would you be able to share the output of `pulumi stack` (anonymized, if needed)? I'm interested to see the tree of the resources. Are you using Components? Do you have a lot of nested children?

In the meantime, you may be able to workaround this by increasing Python's recursion limit at the start of the program, e.g.:

```python
import sys

sys.setrecursionlimit(10**6)
```

**Comment by piotr-bzdyl-vertexinc** [comment]
> I see `_add_dependency` in the first error, which is something we do call recursively. That could be where we're hitting the limit, in which case we could look into making it iterative rather than recursive. We also use recursion elsewhere, when serializing and deserializing
> 
> @piotr-bzdyl-vertexinc, would you be able to share the output of `pulumi stack` (anonymized, if needed)? I'm interested to see the tree of the resources. Are you using Components? Do you have a lot of nested children?
> 
> In the meantime, you may be able to workaround this by increasing Python's recursion limit at the start of the program, e.g.:
> 
> ```python
> import sys
> 
> sys.setrecursionlimit(10**6)
> ```

Hi @justinvp. Yes, we use components and we do have nested children (I would say they can have 3-4 levels of nesting).

Would it be possible to contact you directly via email to provide the coordinates of our Pulumi stack in the Pulumi service so that you can inspect it?

**Comment by tgummerer** [comment]
@piotr-bzdyl-vertexinc yes we can grab a stack from the pulumi service with your permission. @justinvp is on PTO, but if you'd rather send it by email you can send it to me (v-thomas@pulumi.com).

Did increasing the recursion limit help with the issue at all?

**Comment by piotr-bzdyl-vertexinc** [comment]
> @piotr-bzdyl-vertexinc yes we can grab a stack from the pulumi service with your permission. @justinvp is on PTO, but if you'd rather send it by email you can send it to me ([v-thomas@pulumi.com](mailto:v-thomas@pulumi.com)).

Thanks! I will send you the coordinates to our problematic stack.


> Did increasing the recursion limit help with the issue at all?

I didn't have time to test it yet, sorry.
