### ISSUE TITLE
Mac hello world example update issue

### ISSUE THREAD

**Issue by boynux** [pulumi/pulumi#1634]
Trying to run hello world example from tutorial, after creating the project, `pulumi update` fails with this error message:

`error: failed to discover plugin requirements: re-statting file moby/bundles/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/binary-daemon/dockerd: stat moby/bundles/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/binary-daemon/dockerd: too many levels of symbolic links`

Os: Mac
Docker: 18.03.1-ce
Pulumi: 18.03.1-ce

**Comment by boynux** [comment]
I deleted everything and recreated the project, that error is gone now, but now I get this error:

` +   pulumi:pulumi:Stack            hello-pulumi-hello-pulumi-dev  create..   2 errors. error: TypeError: script.locationFromPosition is not a function`

**Comment by boynux** [comment]
Stack trace:

```
error: TypeError: script.locationFromPosition is not a function
        at Object.getFunctionLine (/Users/marab/working/hello-pulumi/node_modules/@pulumi/pulumi/runtime/closure/v8.js:114:29)
        at createFunctionInfo (/Users/marab/working/hello-pulumi/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:157:21)
        at Object.<anonymous> (/Users/marab/working/hello-pulumi/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:93:26)
        at Generator.next (<anonymous>)
        at /Users/marab/working/hello-pulumi/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:20:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/marab/working/hello-pulumi/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:16:12)
        at Object.createFunctionInfoAsync (/Users/marab/working/hello-pulumi/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:56:12)
        at Object.<anonymous> (/Users/marab/working/hello-pulumi/node_modules/@pulumi/pulumi/runtime/closure/serializeClosure.js:49:44)
        at Generator.next (<anonymous>)
```

**Comment by lukehoban** [comment]
This looks related, but slightly different, to https://github.com/pulumi/pulumi/issues/1478.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Any idea what is up with the script.locationFromPosition issue? Is this a Node version issue, perhaps?

Yes.  I believe so.  I think this is: https://github.com/pulumi/pulumi/issues/1502 which is duped against https://github.com/pulumi/pulumi/issues/1270

Note: from talking to @swgillespie, we don't think this should be hard to make work.  So if we just address the issue with ```locationFromPosition``` we'll likely just be able to work on node v10.  I can try to get that working this week.

**Comment by joeduffy** [comment]
That would be wonderful. The "download latest" link, which I assume many people will click on (myself included), now points to v10.

Please do close as a dupe if truly a dupe.

Thanks!

**Comment by boynux** [comment]
Node version: v10.6.0
