### ISSUE TITLE
unknown provider urn:pulumi:spain::gv-nodes::pulumi:providers:azure-native::default_2_42_1

### ISSUE THREAD

**Issue by germansak** [pulumi/pulumi#16366]
### What happened?

Can no longer deploy after upgrading Pulumi

### Example

```
> pulumi up

Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):

Previewing update (spain):

error: snapshot integrity failure; refusing to use it: resource urn:pulumi:spain::gv-nodes::azure-native:network:PrivateEndpoint::es01-testalertacorreos-privep-blob refers to unknown provider urn:pulumi:spain::gv-nodes::pulumi:providers:azure-native::default_2_42_1::dab295e9-b71a-433e-90a4-ae7903a0eecb
```

### Output of `pulumi about`

```
CLI
Version      3.119.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.45.0
resource  azuread       5.47.0
language  dotnet        unknown
resource  random        4.15.1

Host
OS       Microsoft Windows Server 2022 Datacenter Azure Edition
Version  10.0.20348 Build 20348
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='8.0.300'

Backend
Name           pulumi
URL            file://~
User           pulumi\admintooling
Organizations
Token type     personal

Dependencies:
NAME                VERSION
Pulumi              3.64.0
Pulumi.AzureAD      5.47.0
Pulumi.AzureNative  2.45.0

Pulumi locates its logs in C:\Users\ADMINT~1\AppData\Local\Temp\2 by default
```

### Additional context

Similar to https://github.com/pulumi/pulumi/issues/15831, but the ```pulumi up``` command is always executed manually from the same vm and we don't use --targets or Github Actions

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by germansak** [comment]
Hi, first of all, thanks for the quick response.

 I tried with ```--disabled-integrity-checking``` and at first it started to work and do the update, but then it gives the error again
``` error: could not load provider for resource urn:pulumi:spain::gv-nodes::azure-native:network:PrivateEndpoint::es01-auditusuario-privep-blob: could not find provider urn:pulumi:spain::gv-nodes::pulumi:providers:azure-native::default_2_42_1::dab295e9-b71a-433e-90a4-ae7903a0eecb```

**Comment by germansak** [comment]
This is what shows when I type ```pulumi logs```

```
pulumi logs --disable-integrity-checking
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your passphrase to unlock config/secrets
Collecting logs for stack spain since 2024-06-11T14:40:24.000-03:00.

================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.119.0
Go Version:       go1.22.3
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            fatal: An assertion has failed: Expected to find provider node 'urn:pulumi:spain::gv-nodes::pulumi:providers:azure-native::default_2_42_1' in checkpoint tree nodes

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/debug/stack.go:24 +0x5e
main.panicHandler(0xc000ad7f17)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:35 +0x45
panic({0x2df8f20?, 0xc005231030?})
        /opt/hostedtoolcache/go/1.22.3/x64/src/runtime/panic.go:770 +0x132
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0xb0?, {0x346e0ce?, 0xc003145ab0?}, {0xc000ad72e8?, 0xc000ad72e8?, 0xc0051a96e0?})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:35 +0xe8
github.com/pulumi/pulumi/pkg/v3/operations.makeResourceTreeMap({0xc003840008, 0x789, 0x5664a60?})
        /home/runner/work/pulumi/pulumi/pkg/operations/resources.go:88 +0x54d
github.com/pulumi/pulumi/pkg/v3/operations.NewResourceTree(...)
        /home/runner/work/pulumi/pulumi/pkg/operations/resources.go:48
github.com/pulumi/pulumi/pkg/v3/backend/diy.GetLogsForTarget(0xc00518c5c0, {0xc000ae72d8?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/backend.go:1276 +0xcb
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).GetLogs(0xc0021d6360, {0x3ef1848, 0x5664a60}, {0x3ec9d20, 0x5664a60}, {0x3f0d008?, 0xc000ae7008?}, {{{0x0, 0x0}, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/backend.go:1259 +0xec
github.com/pulumi/pulumi/pkg/v3/backend.GetStackLogs({0x3ef1848, 0x5664a60}, {0x3ec9d20, 0x5664a60}, {0x3f0d008, 0xc000ae7008}, {{{0x0, 0x0}, 0x0, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/stack.go:132 +0x115
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).GetLogs(0x5664a60?, {0x3ef1848?, 0x5664a60?}, {0x3ec9d20?, 0x5664a60?}, {{{0x0, 0x0}, 0x0, 0x0, {{{...}, ...}, ...}}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/stack.go:114 +0xb7
main.newLogsCmd.func1(0x0?, {0x0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/logs.go:127 +0x7c7
main.newLogsCmd.RunFunc.func2(0x0?, {0xc0021691f0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x1c
main.newLogsCmd.RunFunc.RunResultFunc.func3(0xc00219f508, {0xc0021691f0, 0x0, 0x1})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:115 +0x38
github.com/spf13/cobra.(*Command).execute(0xc00219f508, {0xc0021691d0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003c3508)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:56 +0x58
```

**Comment by germansak** [comment]
Yes, it starts to analyze changes and stops with the error

![image](https://github.com/pulumi/pulumi/assets/702172/460f5e08-d6e5-4bb3-84d8-cb71c76b38c1)

there are more changes to apply, so it seems it stops in the middle of the process

**Comment by Frassle** [comment]
OK I suspect an old version of the CLI has got this stack into a bad state. You'll probably need to fix the snapshot state manually. If you export the state with `pulumi stack export` you should be able to find the two resource blocks that correspond to the resources in that error message (`urn:pulumi:spain::gv-nodes::azure-native:network:PrivateEndpoint::es01-testalertacorreos-privep-blob` and `urn:pulumi:spain::gv-nodes::pulumi:providers:azure-native::default_2_42_1::dab295e9-b71a-433e-90a4-ae7903a0eecb`). You need to edit the file so that the provider resource is above the PrivateEndpoint resource and then re-import it (`pulumi stack import`). I'd hope after that a normal `up` will be ok.

**Comment by germansak** [comment]
The exported json is about 200k lines. It seems that the resource default_2_42_1::dab295e9-b71a-433e-90a4-ae7903a0eecb is never defined (at least doing a search). It is referenced as a provider about 100 times, but there's no definition for the resource.
On the resources definition (99 times) it appears like this:
```
 "provider": "urn:pulumi:spain::gv-nodes::pulumi:providers:azure-native::default_2_42_1::dab295e9-b71a-433e-90a4-ae7903a0eecb",
```

the closest definition that I've found is this
```
 {
                "urn": "urn:pulumi:spain::gv-nodes::pulumi:providers:azure-native::default_2_45_0",
                "custom": true,
                "id": "d96c7c2c-e973-4dd9-9563-9bf1155ce87d",
                "type": "pulumi:providers:azure-native",
                "inputs": {
                    "location": "FranceCentral",
                    "version": "2.45.0"
                },
                "outputs": {
                    "location": "FranceCentral",
                    "version": "2.45.0"
                },
                "created": "2024-06-10T19:33:50.2039576Z",
                "modified": "2024-06-10T19:33:50.2039576Z"
            },
```

If this resource is what should be referenced and not default_2_42_1, I could do a replace with the correct value, and that should work. Am I right?

**Comment by Frassle** [comment]
> If this resource is what should be referenced and not default_2_42_1, I could do a replace with the correct value, and that should work. Am I right?

No, do not search&replace. That is the right resource, and the references are correct. Providers are referred to via their URN _and_ their ID. Just move that resource block up so it's higher than anything referring to it, then try `pulumi up`.

**Comment by germansak** [comment]
But there is no resource definition for _urn:pulumi:spain::gv-nodes::pulumi:providers:azure-native::default_2_42_1_, only references from other resources via the _provider_ property

**Comment by germansak** [comment]
I've found this definition
```
{
                    "urn": "urn:pulumi:spain::gv-nodes::pulumi:providers:azure-native::default_2_42_1",
                    "custom": true,
                    "id": "dab295e9-b71a-433e-90a4-ae7903a0eecb",
                    "type": "pulumi:providers:azure-native",
                    "inputs": {
                        "location": "FranceCentral",
                        "version": "2.42.1"
                    },
                    "outputs": {
                        "location": "FranceCentral",
                        "version": "2.42.1"
                    },
                    "created": "2024-05-27T18:41:20.7165789Z",
                    "modified": "2024-05-27T18:41:20.7165789Z"
                },
```
in a backup file from june 7, in _\.pulumi\backups\gv-nodes\spain_. 
It's located at the same lines than the definition of _default_2_45_0_ as if default_2_45_0 had replaced default_2_41_1

**Comment by Frassle** [comment]
Should work to copy that into your state file as is. I suspect this corruption was caused by `--target` bugs we have since fixed.

**Comment by germansak** [comment]
It worked! I copied the resource definition from the backup to the exported json. Then I imported the file to the stack and pulumi up ran with no errors.
Thank you @Frassle for all your help!
Closing
