### ISSUE TITLE
pulumi up crashes with `SemVer is not a constructor`

### ISSUE THREAD

**Issue by DanielSchiavini** [pulumi/pulumi#16377]
### What happened?

When I try to run `pulumi up` it crashes with an error (see below)

### Example

```
$ pulumi up
Previewing update (staging)

View in Browser (Ctrl+O): https://app.pulumi.com/DanielSchiavini/estamap-services/staging/previews/a67839fd-968c-4ba7-a576-f26eb2a3189f

     Type                 Name                      Plan     Info
     pulumi:pulumi:Stack  estamap-services-staging           1 error; 15 messages

Diagnostics:
  pulumi:pulumi:Stack (estamap-services-staging):
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

    /home/schiavini/estamap/estamap-services/tools/infra/node_modules/@pulumi/pulumi/node_modules/semver/classes/comparator.js:51
          this.semver = new SemVer(m[2], this.options.loose)
                        ^
    TypeError: SemVer is not a constructor
        at Comparator.parse (/home/schiavini/estamap/estamap-services/tools/infra/node_modules/@pulumi/pulumi/node_modules/semver/classes/comparator.js:51:21)
        at new Comparator (/home/schiavini/estamap/estamap-services/tools/infra/node_modules/@pulumi/pulumi/node_modules/semver/classes/comparator.js:23:10)
        at Object.<anonymous> (/home/schiavini/estamap/estamap-services/tools/infra/node_modules/@pulumi/pulumi/node_modules/semver/ranges/subset.js:71:39)
        at Module._compile (node:internal/modules/cjs/loader:1376:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
        at Module.load (node:internal/modules/cjs/loader:1207:32)
        at Module._load (node:internal/modules/cjs/loader:1023:12)
        at Module.require (node:internal/modules/cjs/loader:1235:19)
        at require (node:internal/modules/helpers:176:18)
        at Object.<anonymous> (/home/schiavini/estamap/estamap-services/tools/infra/node_modules/@pulumi/pulumi/node_modules/semver/index.js:42:16)
    Node.js v20.10.0
```

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.119.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/schiavini/.nvm/versions/node/v20.10.0/bin/node' version='v20.10.0'

Current Stack: DanielSchiavini/estamap-services/staging

TYPE                                                           URN
omitted for privacy/security reasons

Found no pending operations associated with staging

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/DanielSchiavini
User           DanielSchiavini
Organizations  DanielSchiavini
Token type     personal

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either yarn.lock or package-lock.json
```

note: the dependencies are in the parent folder
```
  "devDependencies": {
    "@types/node": "^20",
    "typescript": "5.4.5"
  },
  "dependencies": {
    "@pulumi/aws": "^6.39.0",
    "@pulumi/awsx": "^2.11.0",
    "@pulumi/github": "^6.2.1",
    "@pulumi/mongodbatlas": "^3.15.2",
    "@pulumi/pulumi": "^3.119.0",
    "@pulumi/random": "^4.16.2",
    "reflect-metadata": "^0.2.2"
  }
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by DanielSchiavini** [comment]
nb just ran a dependency upgrade, [pulumi-aws@v6.39.1](https://github.com/pulumi/pulumi-aws/releases/tag/v6.39.1) doesn't fix the issue

**Comment by tgummerer** [comment]
This seems really odd, the error seems to come from the `semver` package, and having a quick look at that nothing seems to have changed recently in this callpath :thinking:

It almost smells like the dependency has broken in some odd way.  Would you be willing to give just re-installing all the dependencies (e.g. through `npm ci`) a try and see if that helps?

Also did the issue start recently in an existing project, or is this a new project?

**Comment by DanielSchiavini** [comment]
Seems like an NPM issue. The problem was fixed after deleting `node_modules` and reinstalling.
