### ISSUE TITLE
Diagnostics is not fully exposing reference/stack

### ISSUE THREAD

**Issue by spe888** [pulumi/pulumi#16413]
### What happened?

Doing a usual `pulumi up` with a error sometimes does not return referenced diagnostics information, because the stack/ref is not fully exposed. As shown in the example it only returns `<ref *1> Error: an instanceProfile is required ...` with no stack information to the relevant problem in the own code (e.g. file, linenumber). 

### Example

```
Diagnostics:
  pulumi:pulumi:Stack (some-stack-name):
    error: Running program '/Users/username/Projects/aws-kubernetes-migration2/' failed with an unhandled exception:
    <ref *1> Error: an instanceProfile is required
        at /Users/username/Projects/aws-kubernetes-migration2/node_modules/@pulumi/nodegroup.ts:574:19
        at /Users/username/Projects/aws-kubernetes-migration2/node_modules/@pulumi/output.ts:402:31
        at Generator.next (<anonymous>)
        at /Users/username/Projects/aws-kubernetes-migration2/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/username/Projects/aws-kubernetes-migration2/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/Users/username/Projects/aws-kubernetes-migration2/node_modules/@pulumi/pulumi/output.js:244:12)
        at /Users/username/Projects/aws-kubernetes-migration2/node_modules/@pulumi/output.ts:316:13
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      promise: Promise { <rejected> [Circular *1] }
    }
```

### Output of `pulumi about`

```
CLI
Version      3.120.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.40.0
resource  awsx        2.12.1
resource  docker      4.5.4
resource  docker      3.6.1
resource  eks         2.7.1
resource  kubernetes  4.13.1
language  nodejs      unknown

Host
OS       darwin
Version  14.4
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v20.14.0'

Current Stack: *******/*******-eks-testmigration/aws-eks-prod (redacted)

Found no resources associated with *******/aws-eks-prod (redacted)

Found no pending operations associated with *******/aws-eks-prod (redacted)

Backend
Name           pulumi.com
URL            https://app.pulumi.com/***
User           *** (redacted)
Organizations  ***, ******* (redacted)
Token type     personal

Dependencies:
NAME            VERSION
@types/node     18.19.34
typescript      5.4.5
@pulumi/awsx    2.12.1
@pulumi/eks     2.7.1
@pulumi/pulumi  3.120.0

Pulumi locates its logs in /var/folders/_b/z_g0y6l918dcrn46sgknmrrw0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
Thanks for the report!  This is definitely an area we can improve.  I'm going to tag it as an enhancement request for internal tracking though, since it works as expected, but we could improve the error message here.
