### ISSUE TITLE
`TestResourceRefsGetResourceGo` is flaky

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#16536]
```
=== FAIL: integration TestResourceRefsGetResourceGo (50.75s)
    program.go:1950: sample: resource_refs_get_resource/go
    program.go:1955: pulumi: /home/runner/work/pulumi/pulumi/bin/pulumi
    command.go:46: **** Invoke '/opt/hostedtoolcache/go/1.22.4/x64/bin/go mod edit -replace github.com/pulumi/pulumi/sdk/v3=/home/runner/work/pulumi/pulumi/sdk' in '/home/runner/go/src/stackName-1719819668228914633-342180'
    command.go:121: Command completed without output
    command.go:46: **** Invoke '/opt/hostedtoolcache/go/1.22.4/x64/bin/go mod tidy' in '/home/runner/go/src/stackName-1719819668228914633-342180'
    command.go:118: Wrote output to /home/runner/go/src/stackName-1719819668228914633-342180/command-output/go-mod-tidy.20240701-074108.9cc26.log
Traceback (most recent call last):
  File "/home/runner/work/pulumi/pulumi/scripts/go-test.py", line 104, in <module>
    raise e
  File "/home/runner/work/pulumi/pulumi/scripts/go-test.py", line 100, in <module>
    sp.check_call(args, shell=False)
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/subprocess.py", line 413, in check_call
    program.go:2100: projdir: /home/runner/go/src/stackName-1719819668228914633-342180
    program.go:1340: Initializing project (dir /home/runner/go/src/stackName-1719819668228914633-342180; stack p-it-fv-az569-6-go-378e7d46)
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi login --cloud-url file:///tmp/TestResourceRefsGetResourceGo2760595364/001' in '/home/runner/go/src/stackName-1719819668228914633-342180'
    command.go:118: Wrote output to /home/runner/go/src/stackName-1719819668228914633-342180/command-output/pulumi-login.20240701-074112.29cc9.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack init p-it-fv-az569-6-go-378e7d46' in '/home/runner/go/src/stackName-1719819668228914633-342180'
    command.go:118: Wrote output to /home/runner/go/src/stackName-1719819668228914633-342180/command-output/pulumi-stack-init.20240701-074126.1d32b.log
    program.go:1507: Performing primary preview and update
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi up --non-interactive --yes --skip-preview --event-log /tmp/p-it-fv-az569-6-go-378e7d46-events.json' in '/home/runner/go/src/stackName-1719819668228914633-342180'
    command.go:98: Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi up --non-interactive --yes --skip-preview --event-log /tmp/p-it-fv-az569-6-go-378e7d46-events.json' failed: exit status 255
Updating (p-it-fv-az569-6-go-378e7d46):

@ updating.......
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) 
 +  test:index:Container mycontainer creating (0s) 
 +  test:index:Child mychild creating (0s) 
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) panic: runtime error: invalid memory address or nil pointer dereference
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc31e5f]
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) goroutine 1 [running]:
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) main.main.func1(0xc000517a70)
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) 	/home/runner/go/src/stackName-1719819668228914633-342180/main.go:128 +0x3bf
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc000517a70, 0xede870)
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) 	/home/runner/work/pulumi/pulumi/sdk/go/pulumi/run.go:122 +0x1a4
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) github.com/pulumi/pulumi/sdk/v3/go/pulumi.runErrInner(0xede870, 0xedee20, ***0x0, 0x0, 0xc0004b04f0?***)
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) 	/home/runner/work/pulumi/pulumi/sdk/go/pulumi/run.go:98 +0x2a5
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) github.com/pulumi/pulumi/sdk/v3/go/pulumi.Run(0xe72737?, ***0x0?, 0xe73041?, 0x5?***)
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) 	/home/runner/work/pulumi/pulumi/sdk/go/pulumi/run.go:50 +0x28
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) main.main()
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) 	/home/runner/go/src/stackName-1719819668228914633-342180/main.go:99 +0x158
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 creating (0s) error: an unhandled error occurred: program exited with non-zero exit code: 2
 +  pulumi:pulumi:Stack resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46 **creating failed** 1 error; 13 messages
Diagnostics:
  pulumi:pulumi:Stack (resource_refs_get_resource_go-p-it-fv-az569-6-go-378e7d46):
    error: an unhandled error occurred: program exited with non-zero exit code: 2

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc31e5f]
    goroutine 1 [running]:
    main.main.func1(0xc000517a70)
    	/home/runner/go/src/stackName-1719819668228914633-342180/main.go:128 +0x3bf
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc000517a70, 0xede870)
    	/home/runner/work/pulumi/pulumi/sdk/go/pulumi/run.go:122 +0x1a4
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.runErrInner(0xede870, 0xedee20, ***0x0, 0x0, 0xc0004b04f0?***)
    	/home/runner/work/pulumi/pulumi/sdk/go/pulumi/run.go:98 +0x2a5
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.Run(0xe72737?, ***0x0?, 0xe73041?, 0x5?***)
    	/home/runner/work/pulumi/pulumi/sdk/go/pulumi/run.go:50 +0x28
    main.main()
    	/home/runner/go/src/stackName-1719819668228914633-342180/main.go:99 +0x158

Resources:
    + 3 created

Duration: 5s
```

From: https://github.com/pulumi/pulumi/actions/runs/9739975364/job/26876483720?pr=16527

**Comment by Frassle** [comment]
Got a slightly different stack trace:

```
panic: expected message "hello world!" not equal to actual message ""
    goroutine 45 [running]:
    main.main.func1.1(***0xc000171230?, 0x2?, 0x0?***)
    	/home/runner/go/src/stackName-1721331326864178436-827910/main.go:138 +0x16e
    reflect.Value.call(***0xcf58e0?, 0xee06b8?, 0x30?***, ***0xe744e7, 0x4***, ***0xc000600bd0, 0x1, 0xc000526878?***)
    	/opt/hostedtoolcache/go/1.22.5/x64/src/reflect/value.go:596 +0xca6
    reflect.Value.Call(***0xcf58e0?, 0xee06b8?, 0x101000000000000?***, ***0xc000600bd0?, 0x0?, 0x3?***)
    	/opt/hostedtoolcache/go/1.22.5/x64/src/reflect/value.go:380 +0xb9
    github.com/pulumi/pulumi/sdk/v3/go/internal.(*applier).Call(0xc000529940, ***0xfcf570, 0x17480c0***, ***0xca67a0?, 0xc0004bc570?, 0x0?***)
    	/home/runner/work/pulumi/pulumi/sdk/go/internal/types.go:510 +0x22d
    github.com/pulumi/pulumi/sdk/v3/go/internal.(*OutputState).applyTWithApplier.func1()
    	/home/runner/work/pulumi/pulumi/sdk/go/internal/types.go:622 +0x16a
    created by github.com/pulumi/pulumi/sdk/v3/go/internal.(*OutputState).applyTWithApplier in goroutine 1
    	/home/runner/work/pulumi/pulumi/sdk/go/internal/types.go:609 +0x265
```

**Comment by tgummerer** [comment]
I just realized the NodeJS version of this test is flaky as well (https://github.com/pulumi/pulumi/issues/11677), probably for the same reasons.

The problem here is that `RegisterResourceOutputs` is run in a Goroutine/async in NodeJS. This means the registration of the resource output might not complete before we try to access the child resource.  But because of how resource registration works, we might already have registered a nil value for that field.  Thus the `UnsafeAwait`/`pulumi.All` don't wait any longer, because the `RegisterResourceOutputs` might not even have started at this point. 

This can easily be reproduced using the following diff:
```diff
diff --git a/sdk/go/pulumi/context.go b/sdk/go/pulumi/context.go
index e4a75dd7b8..f15b276e5b 100644
--- a/sdk/go/pulumi/context.go
+++ b/sdk/go/pulumi/context.go
@@ -29,6 +29,7 @@ import (
        "sort"
        "strings"
        "sync"
+       "time"
 
        multierror "github.com/hashicorp/go-multierror"
        "github.com/pulumi/pulumi/sdk/v3/go/common/resource"
@@ -2191,6 +2195,7 @@ func (ctx *Context) RegisterResourceOutputs(resource Resource, outs Map) error {
        }
 
        go func() {
+               time.Sleep(5 * time.Second)
                // No matter the outcome, make sure all promises are resolved and that we've signaled completion of this RPC.
                var err error
                defer func() {
```
