### ISSUE TITLE
Copies of Output values via `deepcopy` cause panics

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi#16634]
This works:

```go
sshConnNoDialLimit := remote.ConnectionArgs{
	Host:           publicIp.IpAddress.Elem(),
	User:           pulumi.String("pulumi"),
	PrivateKey:     privateKey.PrivateKeyOpenssh,
	DialErrorLimit: pulumi.IntPtr(-1),
}

poll, err := remote.NewCommand(ctx, "poll", &remote.CommandArgs{
	Connection: sshConnNoDialLimit,
	Create:     pulumi.String("echo 'Connection established'"),
}, pulumi.Timeouts(&pulumi.CustomTimeouts{Create: "10m"}), pulumi.DependsOn([]pulumi.Resource{vm}))
```

This panics. Same as above, but the connection object is a deep copy of another one (using `github.com/pulumi/pulumi/sdk/v3/go/common/util/deepcopy`).

```go
sshConn := remote.ConnectionArgs{
	Host:       publicIp.IpAddress.Elem(),
	User:       pulumi.String("pulumi"),
	PrivateKey: privateKey.PrivateKeyOpenssh,
}

sshConnNoDialLimit := deepcopy.Copy(sshConn).(remote.ConnectionArgs)
sshConnNoDialLimit.DialErrorLimit = pulumi.IntPtr(10)

poll, err := remote.NewCommand(ctx, "poll", &remote.CommandArgs{
	Connection: sshConnNoDialLimit,
	Create:     pulumi.String("echo 'Connection established'"),
}, pulumi.Timeouts(&pulumi.CustomTimeouts{Create: "10m"}), pulumi.DependsOn([]pulumi.Resource{vm}))
```

Panic:
```
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100d88794]
    goroutine 874 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/internal.(*OutputState).awaitOnce(0x1400067b500, {0x10220f520, 0x103c88240})
    	/Users/tkappler/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.122.0/go/internal/types.go:269 +0x54
    github.com/pulumi/pulumi/sdk/v3/go/internal.(*OutputState).awaitWithOptions(0x14000169701?, {0x10220f520, 0x103c88240}, 0x1)
    	/Users/tkappler/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.122.0/go/internal/types.go:292 +0x7c
    github.com/pulumi/pulumi/sdk/v3/go/internal.(*OutputState).await(0x103bfd9b0?, {0x10220f520?, 0x103c88240?})
    	/Users/tkappler/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.122.0/go/internal/types.go:283 +0x28
    github.com/pulumi/pulumi/sdk/v3/go/internal.awaitInputs({0x10220f520, 0x103c88240}, {0x101d70c40?, 0x1400035ec00?, 0x0?}, {0x101a9f320, 0x14000676430, 0x198})
    	/Users/tkappler/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.122.0/go/internal/types.go:850 +0x1940
    github.com/pulumi/pulumi/sdk/v3/go/internal.awaitInputs({0x10220f520, 0x103c88240}, {0x101efb500?, 0x1400035ebe0?, 0x99?}, {0x101e80de0, 0x14000676420, 0x199})
    	/Users/tkappler/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.122.0/go/internal/types.go:938 +0xbdc
    github.com/pulumi/pulumi/sdk/v3/go/internal.toOutputTWithContext.func3()
    	/Users/tkappler/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.122.0/go/internal/types.go:1037 +0xcc
    created by github.com/pulumi/pulumi/sdk/v3/go/internal.toOutputTWithContext in goroutine 1
    	/Users/tkappler/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.122.0/go/internal/types.go:1029 +0x2b8
```

The problem is most likely that `sshConn` contains Outputs, which are probably not deep-copied correctly.

If we cannot fix this, we should see if we can fail in a better way here that communicates the actual problem to the user.

**Comment by justinvp** [comment]
I'm not sure we intended `deepcopy` to be able to work with Outputs and really be used by users in this way.

If it's an easy fix, then we could consider it. Otherwise, we could consider special casing to provide a better error message. The signature doesn't provide a way to return an error, but we could panic with a better message.

Special casing Outputs (if indeed it is the root cause) is slightly unsatisfying, though. The intention for this appears to be a general deepcopy utility, not something Pulumi-specific.
