### ISSUE TITLE
Error when logging from stack transformation

### ISSUE THREAD

**Issue by tlinhart** [pulumi/pulumi#16654]
### What happened?

I'm trying to log a message from within the stack transformation function. I'm supplying the `resource` argument to associate the message with a concrete resource being transformed which should be possible according to the [documentation](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/functions/log.warn.html). However, when using `pulumi preview` it ends with an error. When I omit the `resource` and leave only the error message, it works.

### Example

Here's the sample Pulumi program:

```
"use strict";
const pulumi = require("@pulumi/pulumi");
const aws = require("@pulumi/aws");

pulumi.runtime.registerStackTransformation((args) => {
  pulumi.log.warn("dummy", args.resource);
  return undefined;
});

const bucket = new aws.s3.BucketV2("mybucket");
```

Here's the error from console:

```
Previewing update (dev):
     Type                 Name         Plan       Info
 +   pulumi:pulumi:Stack  test-js-dev  create     1 error

Diagnostics:
  pulumi:pulumi:Stack (test-js-dev):
    error: Running program '/home/pasmen/tmp/index.js' failed with an unhandled exception:
    TypeError: Cannot read properties of undefined (reading 'promise')
        at log (/home/pasmen/tmp/node_modules/@pulumi/log/index.ts:103:48)
        at Object.warn (/home/pasmen/tmp/node_modules/@pulumi/log/index.ts:70:16)
        at /home/pasmen/tmp/index.js:6:14
        at new Resource (/home/pasmen/tmp/node_modules/@pulumi/resource.ts:410:26)
        at new CustomResource (/home/pasmen/tmp/node_modules/@pulumi/resource.ts:976:9)
        at new BucketV2 (/home/pasmen/tmp/node_modules/@pulumi/s3/bucketV2.ts:295:9)
        at Object.<anonymous> (/home/pasmen/tmp/index.js:10:16)
        at Module._compile (node:internal/modules/cjs/loader:1369:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
        at Module.load (node:internal/modules/cjs/loader:1206:32)
```

### Output of `pulumi about`

```
CLI          
Version      3.124.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.44.0
resource  docker  4.5.4
resource  docker  3.6.1
language  nodejs  unknown

Host     
OS       ubuntu
Version  24.04
Arch     x86_64

This project is written in nodejs: executable='/home/pasmen/.nvm/versions/node/v20.12.2/bin/node' version='v20.12.2'

Backend        
Name           nyx
URL            file:///home/pasmen/tmp/state
User           pasmen
Organizations  
Token type     personal

Dependencies:
NAME             VERSION
@pulumi/aws      6.44.0
@pulumi/pulumi   3.124.0

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current snapshot
```

### Additional context

It works well in Python.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening the issue.

I haven't dug deep into this yet, but I suspect the problem is that the transformation is running in the Resource's constructor before the `urn` property has been initialized. Even if we changed the constructor to initialize `urn` before running the transformations, this may result in a deadlock: we'd be waiting for the URN to be resolved to log the message, but it never will since the constructor is waiting for the URN. Would have to try it out.

I suspect the best "fix" would be to update the log methods to not wait on the `urn` if it is `undefined`, with the caveat that the log message won't end up being associated with the resource.

In the meantime, I'd avoid passing the resource from a transformation.

**Comment by tlinhart** [comment]
@justinvp thanks for initial investigation, for now I'll remove the `resource` when logging.
