### ISSUE TITLE
Unable to unit-test failing outputs in Node

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#16665]
### What happened?

It would be nice to be able to write tests against logic that uses `Output<T>` with expected exceptions inside. There apparently is a handy combinator `(x: Output<T>).promise(): Promise<T>` but I could not find a way to write a Jest test, with either `async` or a promise-returning test that could catch and assert on the exception, per https://jestjs.io/docs/asynchronous documentation.

There possibly is some issue with making sure that `promise()` turns an exceptionally terminating `Output` into an exceptionally terminating `Promise`.

### Example

Given this Jest test:

```
    it("try-catching", () => {
        const myPromise = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve("foo");
            }, 300);
        });

        return output(myPromise).apply(x => {
            return Promise.reject(new Error("OOPS"));
            // throw new Error("OOPS");
        }).promise().catch(e => {
            console.log(e);
        });
    });
```

Get this output:

```
 RUNS  ./authenticationMode.test.ts
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: OOPS
    at /Users/anton/code/pulumi-eks/nodejs/eks/authenticationMode.test.ts:47:29
    at /Users/anton/code/pulumi-eks/nodejs/eks/node_modules/@pulumi/output.ts:398:31
    at Generator.next (<anonymous>)
    at /Users/anton/code/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:21:71
    at new Promise (<anonymous>)
    at Object.<anonymous>.__awaiter (/Users/anton/code/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:17:12)
    at applyHelperAsync (/Users/anton/code/pulumi-eks/nodejs/eks/node_modules/@pulumi/pulumi/output.js:239:12)
    at /Users/anton/code/pulumi-eks/nodejs/eks/node_modules/@pulumi/output.ts:310:13
```

### Output of `pulumi about`

Pulumi Node SDK 3.80.0

### Additional context

The context is testing some validation logic in pulumi-eks, the provider written in Node, that uses Exceptions to express input validation failures.  https://github.com/pulumi/pulumi-eks/pull/1227

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
I took a cursory look, but didn't see any obvious ways to do it besides what you tried.
