### ISSUE TITLE
Strange Runtime Error with pulumi azure native

### ISSUE THREAD

**Issue by baoduy** [pulumi/pulumi#16714]
### What happened?

I got a stranger error as below
```
   error: Running program '/com.docker.devenvironments.code/01-az-shared/index.ts' failed with an unhandled exception:
    <ref *1> TypeError: c.g is not a function
        at Function.N.setWrapperField (/com.docker.devenvironments.code/01-az-shared/node_modules/google-protobuf/google-protobuf.js:91:66)
        at proto.pulumirpc.RegisterResourceOutputsRequest.setOutputs (/com.docker.devenvironments.code/01-az-shared/node_modules/@pulumi/pulumi/proto/resource_pb.js:3831:23)
        at Object.<anonymous> (/com.docker.devenvironments.code/01-az-shared/node_modules/@pulumi/runtime/resource.ts:1082:21)
        at Generator.next (<anonymous>)
        at fulfilled (/com.docker.devenvironments.code/01-az-shared/node_modules/@pulumi/pulumi/runtime/resource.js:18:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      promise: Promise { <rejected> [Circular *1] }
    }
 ```

### Example

this error happened when run any pulumi project with below version

```
"@pulumi/azure-native": "^2.50.1",
"@pulumi/pulumi": "^3.124.0"
```

### Output of `pulumi about`

CLI          
Version      3.121.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME                           VERSION
resource  azure-native                   2.50.1
language  nodejs                         unknown

Host     
OS       debian
Version  12.5
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v20.13.1'

Current Stack: transwap/az-shared-ts/uk-prd

TYPE                                                  URN
pulumi:pulumi:Stack                                   urn:pulumi:uk-prd::az-shared-ts::pulumi:pulumi:Stack::az-shared-ts-uk-prd
pulumi:providers:azure-native                         urn:pulumi:uk-prd::az-shared-ts::pulumi:providers:azure-native::default_2_50_1
azure-native:resources:ResourceGroup                  urn:pulumi:uk-prd::az-shared-ts::azure-native:resources:ResourceGroup::uk-prd-shared-gb-grp-transwap
azure-native:operationalinsights:Workspace            urn:pulumi:uk-prd::az-shared-ts::azure-native:operationalinsights:Workspace::uk-prd-shared-gb-logs-wp
azure-native:signalrservice:SignalR                   urn:pulumi:uk-prd::az-shared-ts::azure-native:signalrservice:SignalR::uk-prd-shared-gb-sigr
azure-native:storage:StorageAccount                   urn:pulumi:uk-prd::az-shared-ts::azure-native:storage:StorageAccount::ukprdsharedgblogstranswa
pulumi:providers:pulumi-nodejs                        urn:pulumi:uk-prd::az-shared-ts::pulumi:providers:pulumi-nodejs::default
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:uk-cf-tunnel
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultCerts:uk-identity-server-cert
pulumi:providers:azuread                              urn:pulumi:uk-prd::az-shared-ts::pulumi:providers:azuread::default_5_53_2
azuread:index/group:Group                             urn:pulumi:uk-prd::az-shared-ts::azuread:index/group:Group::TRANSWAP ROL PRD AZURE ADMIN
azuread:index/group:Group                             urn:pulumi:uk-prd::az-shared-ts::azuread:index/group:Group::TRANSWAP ROL PRD AZURE CONTRIBUTOR
azuread:index/group:Group                             urn:pulumi:uk-prd::az-shared-ts::azuread:index/group:Group::TRANSWAP ROL PRD AZURE READONLY
azure-native:managedidentity:UserAssignedIdentity     urn:pulumi:uk-prd::az-shared-ts::azure-native:managedidentity:UserAssignedIdentity::uk-prd-shared-gb-acc-auto-mid
azure-native:authorization:ManagementLockByScope      urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:ManagementLockByScope::uk-prd-shared-gb-grp-transwap
azure-native:cache:Redis                              urn:pulumi:uk-prd::az-shared-ts::azure-native:cache:Redis::uk-prd-shared-gb-rds
azure-native:insights:Component                       urn:pulumi:uk-prd::az-shared-ts::azure-native:insights:Component::uk-prd-shared-gb-logs-isg
azure-native:storage:ManagementPolicy                 urn:pulumi:uk-prd::az-shared-ts::azure-native:storage:ManagementPolicy::ukprdsharedgblogstranswa-mnp
azure-native:authorization:ManagementLockByScope      urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:ManagementLockByScope::ukprdsharedgblogstranswa
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:envroles-admin-object-id
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:envroles-admin-display-name
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-admin-KeyVaultAdministrator-KeyVaultAdministrator
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-admin-KeyVaultDataAccessAdministrator-KeyVaultDataAccessAdministrator
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-admin-Owner-Owner
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:envroles-contributor-object-id
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-contributor-KeyVaultCertificatesOfficer-KeyVaultCertificatesOfficer
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-contributor-Contributor-Contributor
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:envroles-contributor-display-name
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-contributor-KeyVaultSecretsOfficer-KeyVaultSecretsOfficer
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-contributor-KeyVaultContributor-KeyVaultContributor
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-contributor-KeyVaultCryptoOfficer-KeyVaultCryptoOfficer
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-readonly-KeyVaultCryptoServiceEncryptionUser-KeyVaultCryptoServiceEncryptionUser
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-readonly-Reader-Reader
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:envroles-readonly-display-name
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:envroles-readonly-object-id
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-readonly-KeyVaultReader-KeyVaultReader
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-readonly-KeyVaultCryptoUser-KeyVaultCryptoUser
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-readonly-KeyVaultCertificateUser-KeyVaultCertificateUser
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-readonly-KeyVaultSecretsUser-KeyVaultSecretsUser
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-grp-transwap-readonly-KeyVaultCryptoServiceReleaseUser-KeyVaultCryptoServiceReleaseUser
azure-native:automation:AutomationAccount             urn:pulumi:uk-prd::az-shared-ts::azure-native:automation:AutomationAccount::uk-prd-shared-gb-acc-auto
azure-native:insights:ComponentCurrentBillingFeature  urn:pulumi:uk-prd::az-shared-ts::azure-native:insights:ComponentCurrentBillingFeature::uk-prd-shared-gb-logs-isg-CurrentBillingFeature
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:uk-prd-shared-gb-logs-isg
azuread:index/groupMember:GroupMember                 urn:pulumi:uk-prd::az-shared-ts::azuread:index/groupMember:GroupMember::ukprdsharedgblogstranswa
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:ukprdsharedgblogstranswa-key-primary
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:ukprdsharedgblogstranswa-conn-primary
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:ukprdsharedgblogstranswa-conn-secondary
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:ukprdsharedgblogstranswa-key-secondary
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-acc-auto-Contributor
azure-native:authorization:RoleAssignment             urn:pulumi:uk-prd::az-shared-ts::azure-native:authorization:RoleAssignment::uk-prd-shared-gb-acc-auto-mid-Contributor
azure-native:network:PrivateEndpoint                  urn:pulumi:uk-prd::az-shared-ts::azure-native:network:PrivateEndpoint::uk-prd-shared-gb-sigr-pre-0
azure-native:keyvault:Vault                           urn:pulumi:uk-prd::az-shared-ts::azure-native:keyvault:Vault::uk-prd-shared-transwap-g
azure-native:network:PrivateEndpoint                  urn:pulumi:uk-prd::az-shared-ts::azure-native:network:PrivateEndpoint::uk-prd-shared-gb-rds-pre-0
azure-native:network:PrivateZone                      urn:pulumi:uk-prd::az-shared-ts::azure-native:network:PrivateZone::uk-prd-shared-gb-sigr.privatelink.service.signalr.net
azure-native:network:PrivateZone                      urn:pulumi:uk-prd::az-shared-ts::azure-native:network:PrivateZone::uk-prd-shared-gb-rds.privatelink.redis.cache.windows.net
azure-native:network:VirtualNetworkLink               urn:pulumi:uk-prd::az-shared-ts::azure-native:network:VirtualNetworkLink::uk-prd-shared-gb-sigr-0-1-link
azure-native:network:VirtualNetworkLink               urn:pulumi:uk-prd::az-shared-ts::azure-native:network:VirtualNetworkLink::uk-prd-shared-gb-sigr-0-2-link
azure-native:network:PrivateRecordSet                 urn:pulumi:uk-prd::az-shared-ts::azure-native:network:PrivateRecordSet::uk-prd-shared-gb-sigr.privatelink.service.signalr.net-Root-0-ARecord
azure-native:network:VirtualNetworkLink               urn:pulumi:uk-prd::az-shared-ts::azure-native:network:VirtualNetworkLink::uk-prd-shared-gb-sigr-0-0-link
azure-native:network:VirtualNetworkLink               urn:pulumi:uk-prd::az-shared-ts::azure-native:network:VirtualNetworkLink::uk-prd-shared-gb-rds-0-1-link
azure-native:network:PrivateRecordSet                 urn:pulumi:uk-prd::az-shared-ts::azure-native:network:PrivateRecordSet::uk-prd-shared-gb-rds.privatelink.redis.cache.windows.net-Root-0-ARecord
azure-native:network:VirtualNetworkLink               urn:pulumi:uk-prd::az-shared-ts::azure-native:network:VirtualNetworkLink::uk-prd-shared-gb-rds-0-0-link
azure-native:network:VirtualNetworkLink               urn:pulumi:uk-prd::az-shared-ts::azure-native:network:VirtualNetworkLink::uk-prd-shared-gb-rds-0-2-link
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:uk-prd-shared-gb-rds-primary-key
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:uk-prd-shared-gb-rds-primary-connection
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:uk-prd-shared-gb-rds-secondary-connection
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:uk-prd-shared-gb-rds-secondary-key
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:uk-prd-shared-gb-sigr-host
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:uk-prd-shared-gb-sigr-secondaryConnection
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:uk-prd-shared-gb-sigr-primaryKey
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:uk-prd-shared-gb-sigr-primaryConnection
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:uk-prd-shared-gb-sigr-secondaryKey
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:shared-gb-logs-wp-key-secondary
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:shared-gb-logs-wp-key-primary
pulumi-nodejs:dynamic:Resource                        urn:pulumi:uk-prd::az-shared-ts::pulumi-nodejs:dynamic:Resource::csp:VaultSecrets:uk-prd-shared-gb-logs-wp-Id
pulumi:providers:azure-native                         urn:pulumi:uk-prd::az-shared-ts::pulumi:providers:azure-native::default_2_49_1
pulumi:providers:azuread                              urn:pulumi:uk-prd::az-shared-ts::pulumi:providers:azuread::default_5_53_1

Found no pending operations associated with uk-prd

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/transwap
User           transwap
Organizations  transwap
Token type     personal

Dependencies:
NAME                               VERSION
@types/node                        20.12.12
ts-node                            10.9.2
@azure/identity                    4.4.0
@drunk-pulumi/azure-providers      0.0.30
@drunk-pulumi/azure                0.0.1
@microsoft/microsoft-graph-client  3.0.7
@pulumi/azure-native               2.50.1
@pulumi/pulumi                     3.124.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Related: https://github.com/pulumi/pulumi/issues/16693

This appears to be due to different google-protobuf dependencies being pulled in. eks team fixed it for their tests by just updating the version of google-protobuf they were using. You may be able to do similar.

**Comment by ps-mattstuart** [comment]
We're experiencing this as well. We're using ESXI native plugin but it's not related to that as far as I can tell. Forcing an install of 3.21.2 and cleaning the version out of the pulumi node_modules sub install which was 3.21.4 seems to work.

**Comment by vedantrathore** [comment]
Running into the same issue, tried both 3.21.2 and 3.21.4 and its not working, any help here would be appreciated.

**Comment by vedantrathore** [comment]
Any update on this ?

**Comment by Frassle** [comment]
Nothing beyond the original workaround, which is updating google-protobuf to latest seems to fix it. If that doesn't work for you let us know so we can investigate more.

**Comment by ExploHash** [comment]
I also have this problem with kubernetes and updating to the latest version of protobuf didn't work. Reverting to an earlier pulumi version worked though

**Comment by bengouss** [comment]
> We're experiencing this as well. We're using ESXI native plugin but it's not related to that as far as I can tell. Forcing an install of 3.21.2 and cleaning the version out of the pulumi node_modules sub install which was 3.21.4 seems to work.

This worked for me 🙏 Seem to be happening after a big dependabot upgrade

**Comment by baoduy** [comment]
Since the issue also fixed on the latest version so I close the ticket.

**Comment by alamothe** [comment]
Can't believe I'm paying for this junk when we need to downgrade protobuf by hand to make it work. 

When do you plan to update `@pulumi/gcp` and `@pulumi/kubernetes`? Currently, if all three have the latest versions there is protobuf mismatch and it crashes with the above error.
