### ISSUE TITLE
Error with Scaleway Provider in Pulumi: UNKNOWN:Error received from peer

### ISSUE THREAD

**Issue by Med-hedi-bra** [pulumi/pulumi#16815]
### What happened?

I’m experiencing an issue when using the Scaleway provider in Pulumi. The **stack.up()** function executes and creates resources on Scaleway, but I receive an error and the return value, which includes the IP address, is not being returned correctly.

``` 
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (0s)
@ updating.....
 +  scaleway:index:InstanceIp publicIp creating (0s)
@ updating....
 +  scaleway:index:InstanceIp publicIp created (1s)
 +  scaleway:index:InstanceServer test3-inov-y6678o creating (0s)
@ updating.....................
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) panic: runtime error: invalid memory address or nil pointer dereference
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x12c4e37]
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) goroutine 64 [running]:
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) github.com/scaleway/terraform-provider-scaleway/v2/scaleway.resourceScalewayInstanceServerRead({0x1ac09f0, 0xc000d1c420}, 0xc000ac4d00, {0x13f1420, 0xc000b73f70})
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway/v2@v2.10.0/scaleway/resource_instance_server.go:532 +0x4f7
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) github.com/scaleway/terraform-provider-scaleway/v2/scaleway.resourceScalewayInstanceServerCreate({0x1ac09f0, 0xc000d1c420}, 0x7fc230765108?, {0x13f1420?, 0xc000b73f70?})
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway/v2@v2.10.0/scaleway/resource_instance_server.go:500 +0x2225
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000162a80, {0x1ac09b8, 0xc000046108}, 0xd?, {0x13f1420, 0xc000b73f70})
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:712 +0x12e
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000162a80, {0x1ac09b8, 0xc000046108}, 0x0, 0xc000ac4b80, {0x13f1420, 0xc000b73f70})
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:842 +0xa85
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0x167df3b?}, {0x169af5c, 0x18}, {0x0?, 0x0}, {0x1ac7558?, 0xc000ac4b80})
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.40.0/pkg/tfshim/sdk-v2/provider.go:122 +0x19b
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0xc00055ef00, {0x1ac0a28?, 0xc000d0d560?}, 0xc00093f400)
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.40.0/pkg/tfbridge/provider.go:895 +0x643
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x1ac0a28, 0xc000d0d560}, {0x15b9f20?, 0xc00093f400})
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.55.0/proto/go/provider_grpc.pb.go:573 +0x78
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1ac0a28, 0xc000d0d440}, {0x15b9f20, 0xc00093f400}, 0xc000341620, 0xc000d10888)
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x1645480?, 0xc00055ef00}, {0x1ac0a28, 0xc000d0d440}, 0xc0006fa1c0, 0xc000403680)
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.55.0/proto/go/provider_grpc.pb.go:575 +0x138
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006c41e0, {0x1ac79e0, 0xc00039e1a0}, 0xc0001647e0, 0xc0008300f0, 0x2612000, 0x0)
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) google.golang.org/grpc.(*Server).handleStream(0xc0006c41e0, {0x1ac79e0, 0xc00039e1a0}, 0xc0001647e0, 0x0)
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) google.golang.org/grpc.(*Server).serveStreams.func1.2()
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965 +0x98
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) created by google.golang.org/grpc.(*Server).serveStreams.func1
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (20s) 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:963 +0x28a
 +  scaleway:index:InstanceServer test3-inov-y6678o creating (17s) error: error reading from server: EOF
 +  scaleway:index:InstanceServer test3-inov-y6678o **creating failed** error: error reading from server: EOF
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o creating (21s) error: update failed
 +  pulumi:pulumi:Stack inovdrop-back-test3-inov-y6678o **creating failed** 1 error; 29 messages


debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-07-26T09:54:26.374087936+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:41563: Failed to connect to remote host: Connection refused"}"
Diagnostics:
  scaleway:index:InstanceServer (test3-inov-y6678o):
    error: error reading from server: EOF

  pulumi:pulumi:Stack (inovdrop-back-test3-inov-y6678o):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x12c4e37]
    goroutine 64 [running]:
    github.com/scaleway/terraform-provider-scaleway/v2/scaleway.resourceScalewayInstanceServerRead({0x1ac09f0, 0xc000d1c420}, 0xc000ac4d00, {0x13f1420, 0xc000b73f70})
    	/home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway/v2@v2.10.0/scaleway/resource_instance_server.go:532 +0x4f7
    github.com/scaleway/terraform-provider-scaleway/v2/scaleway.resourceScalewayInstanceServerCreate({0x1ac09f0, 0xc000d1c420}, 0x7fc230765108?, {0x13f1420?, 0xc000b73f70?})
    	/home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway/v2@v2.10.0/scaleway/resource_instance_server.go:500 +0x2225
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000162a80, {0x1ac09b8, 0xc000046108}, 0xd?, {0x13f1420, 0xc000b73f70})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:712 +0x12e
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000162a80, {0x1ac09b8, 0xc000046108}, 0x0, 0xc000ac4b80, {0x13f1420, 0xc000b73f70})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:842 +0xa85
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0x167df3b?}, {0x169af5c, 0x18}, {0x0?, 0x0}, {0x1ac7558?, 0xc000ac4b80})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.40.0/pkg/tfshim/sdk-v2/provider.go:122 +0x19b
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0xc00055ef00, {0x1ac0a28?, 0xc000d0d560?}, 0xc00093f400)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.40.0/pkg/tfbridge/provider.go:895 +0x643
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x1ac0a28, 0xc000d0d560}, {0x15b9f20?, 0xc00093f400})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.55.0/proto/go/provider_grpc.pb.go:573 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1ac0a28, 0xc000d0d440}, {0x15b9f20, 0xc00093f400}, 0xc000341620, 0xc000d10888)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x1645480?, 0xc00055ef00}, {0x1ac0a28, 0xc000d0d440}, 0xc0006fa1c0, 0xc000403680)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.55.0/proto/go/provider_grpc.pb.go:575 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006c41e0, {0x1ac79e0, 0xc00039e1a0}, 0xc0001647e0, 0xc0008300f0, 0x2612000, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
    google.golang.org/grpc.(*Server).handleStream(0xc0006c41e0, {0x1ac79e0, 0xc00039e1a0}, 0xc0001647e0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

    error: update failed

Resources:
    + 2 created
```

Expected Behavior
The resources should be created, and the IP address should be returned without errors.

Actual Behavior
The resources are created, but an error occurs, and the IP address is not returned correctly.

### Example

- Run `pulumi up` with the following configuration:
(Include details of your Pulumi stack and Scaleway configuration)

- Observe the error logs and failure.

### Output of `pulumi about`

CLI          
Version      3.126.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  python  unknown

Host     
OS       debian
Version  11.10
Arch     x86_64

This project is written in python: executable='/app/venv/bin/python' version='3.9.16'

Backend        
Name           4de98fe949d6
URL            s3://cwcloud-pulumi-state?endpoint=s3.fr-par.scw.cloud
User           root
Organizations  
Token type     personal

Dependencies:
NAME        VERSION
pip         22.0.4
setuptools  71.1.0
wheel       0.43.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This is either a bridge bug or a bug in the scaleway provider. I'll move this to the bridge repo for them to have a quick check if it looks like a bridge bug.
