### ISSUE TITLE
Assert on duplicate URN

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1682]
```
const aws = require("@pulumi/aws");
let b = new aws.s3.Bucket("foo", {
    bucket: "luke123aaaa232132122",
});

let b2 = new aws.s3.Bucket("foo", {
    bucket: "luke123aaaa232132",
});
```

```
$ pulumi update
Previewing update of stack 'ademo-dev'
Previewing changes:

     Type                 Name             Plan          Info
 *   pulumi:pulumi:Stack  ademo-ademo-dev  no change
 +-  └─ aws:s3:Bucket     foo              replace..     changes: ~ bucket
panic: fatal: An assertion has failed

goroutine 118 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(0x1ab55e2, 0x17)
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xf3
github.com/pulumi/pulumi/pkg/util/contract.Assert(0x191c500)
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26 +0x49
github.com/pulumi/pulumi/pkg/resource/deploy.NewCreateReplacementStep(0xc420324360, 0x4d40140, 0xc4202c76e0, 0xc4201cd290, 0xc420624120, 0xc4203dad60, 0x1, 0x1, 0x1,0x0, ...)
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/step.go:118 +0x91
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepGenerator).GenerateSteps(0xc4205522d0, 0x4d40140, 0xc4202c76e0, 0x4d40140, 0xc4202c76e0, 0xc42032a701, 0xc4203641c0, 0x36)
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_generator.go:269 +0x13d7
github.com/pulumi/pulumi/pkg/resource/deploy.(*PlanIterator).Next(0xc4202f5a40, 0x2034fc0, 0xc420297840, 0x1, 0x0)
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_apply.go:182 +0x2e0
github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk.func1(0xc4202f5a40, 0xc4204402e0, 0xc4203001e0, 0xc4204403a0, 0xc4202ac9f0, 0xc4204661f8, 0xc4200ce310, 0xc420180c01)
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/engine/plan.go:253 +0x19e
created by github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk
        /Users/luke/go/src/github.com/pulumi/pulumi/pkg/engine/plan.go:212 +0x221
```

**Comment by swgillespie** [comment]
Yikes - I know we used to raise a diagnostic for this but it must have regressed.

**Comment by swgillespie** [comment]
I can't repro the assert failure but I can repro some bad behavior. I'll turn this into a test.
