### ISSUE TITLE
`pulumi state move` fatal error

### ISSUE THREAD

**Issue by PhilBroderickCrezco** [pulumi/pulumi#16835]
### What happened?

I'm trying out the new `pulumi state move` command to move some resources from one project to another, but ran into a fatal error.

### Example

Source program:

```csharp
using System.Collections.Generic;
using Pulumi.AzureNative.Resources;
using Deployment = Pulumi.Deployment;

return await Deployment.RunAsync(() =>
{
    var resourceGroup = new ResourceGroup("resource-group", new ResourceGroupArgs
    {
        ResourceGroupName = "pulumi-move-rsg"
    });

    // Export outputs here
    return new Dictionary<string, object?>
    {
        ["name"] = resourceGroup.Name
    };
});
```

Run `pulumi state move urn:pulumi:dev::PulumiMove.Source::azure-native:resources:ResourceGroup::resource-group` and immediately get error.

### Output of `pulumi about`

```
Pulumi Version:   v3.127.0
Go Version:       go1.22.5
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            attempt to encrypt value

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.5/x64/src/runtime/debug/stack.go:24 +0x5e
main.panicHandler(0xc002943f27)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:34 +0x45
panic({0x2d53fe0?, 0x3e3b720?})
        /opt/hostedtoolcache/go/1.22.5/x64/src/runtime/panic.go:770 +0x132
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.panicCrypter.EncryptValue(...)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/crypt.go:103
github.com/pulumi/pulumi/pkg/v3/resource/stack.SerializePropertyValue({0x3e6ab68, 0x5614880}, {{0x2cd7440?, 0xc0016925d0?}}, {0x1d27b583928, 0x5614880}, 0x0)
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:478 +0x5eb
github.com/pulumi/pulumi/pkg/v3/resource/stack.SerializeProperties({0x3e6ab68, 0x5614880}, 0xc002619680, {0x1d27b583928, 0x5614880}, 0x0)
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:386 +0xdd
github.com/pulumi/pulumi/pkg/v3/resource/stack.SerializeResource({_, _}, _, {_, _}, _)
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:325 +0x1f4
github.com/pulumi/pulumi/pkg/v3/resource/stack.SerializeDeployment({0x3e6ab68, 0x5614880}, 0xc001be1dd0, 0x0)
        /home/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:125 +0x2e5
main.saveSnapshot({0x3e6ab68, 0x5614880}, {0x3e861e8, 0xc0004d0000}, 0xc001be1dd0, 0x0)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/stack_import.go:150 +0x5d6
main.(*stateMoveCmd).Run(0xc00125dbc0, {0x3e6ab68, 0x5614880}, {0x3e861e8, 0xc000495340}, {0x3e861e8, 0xc0004d0000}, {0xc0012e4930, 0x1, 0x3}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_move.go:370 +0x25e5
main.newStateMoveCommand.func1(0x0?, {0xc0012e4930, 0x1, 0x3})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_move.go:89 +0x265
main.newStateMoveCommand.RunFunc.func2(0x0?, {0xc0012e4930?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x1c
main.newStateMoveCommand.RunFunc.RunResultFunc.func5(0xc0012a9808, {0xc0012e4930, 0x1, 0x3})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:115 +0x38
github.com/spf13/cobra.(*Command).execute(0xc0012a9808, {0xc0012e48d0, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc00202cc08)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x58
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
Thanks for the report!  I'll look into it.

**Comment by tgummerer** [comment]
@PhilBroderickCrezco Looking into this, this happens when trying to move a resource that has secrets to a stack where no secrets manager is initialized.  https://github.com/pulumi/pulumi/pull/16844 will fix this, but if you want to use the command in the meantime you can make sure the stack you are moving the resources to has a secrets manager set up.

You can do that by using `pulumi stack --stack <stack-name> change-secrets-provider default`.

**Comment by PhilBroderickCrezco** [comment]
> [@PhilBroderickCrezco](https://github.com/PhilBroderickCrezco) Looking into this, this happens when trying to move a resource that has secrets to a stack where no secrets manager is initialized. [#16844](https://github.com/pulumi/pulumi/pull/16844) will fix this, but if you want to use the command in the meantime you can make sure the stack you are moving the resources to has a secrets manager set up.
> 
> You can do that by using `pulumi stack --stack <stack-name> change-secrets-provider default`.

Awesome, thanks for getting onto this so quickly @tgummerer. I've confirmed the workaround you suggested does work, so that unblocks me for now, but look forward to the proper fix 🙌
