### ISSUE TITLE
Python codegen panics when a resource is called `provider`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#17034]
### What happened?

When given a schema such as the one below, `pulumi package gen-sdk schema.json --language python` panics:

```console
$ pulumi package gen-sdk schema.json --language python
panic: fatal: An assertion has failed: duplicate file: pulumi_databricks/provider.py

goroutine 82 [running]:

github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)

        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23

github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0xc0?, {0x1033e95ec?, 0x14000500fc0?}, {0x1400094e7f0?, 0x103b93300?, 0x3?})

        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:35 +0xe0

github.com/pulumi/pulumi/pkg/v3/codegen.Fs.Add(...)

        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/utilities.go:180

github.com/pulumi/pulumi/pkg/v3/codegen/python.(*modContext).gen.func1({0x14000b8ce70, 0xb}, {0x140001d7300, 0x11c9})

        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/python/gen.go:594 +0x1f8

github.com/pulumi/pulumi/pkg/v3/codegen/python.(*modContext).gen(0x140006c0900, 0x140008f98c0)

        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/python/gen.go:677 +0x990

github.com/pulumi/pulumi/pkg/v3/codegen/python.GeneratePackage({0x1033f0be9, 0x16}, 0x14000764680, 0x0)

        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/pkg/codegen/python/gen.go:3209 +0x3f0

main.(*pythonLanguageHost).GeneratePackage(0x14000b5a4c0, {0x103e7ee00?, 0x40?}, 0x14000d2a620)

        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/python/cmd/pulumi-language-python/main.go:1256 +0x374

github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_GeneratePackage_Handler.func1({0x103f06da8?, 0x14000aa3440?}, {0x103e35ca0?, 0x14000d2a620?})

        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/proto/go/language_grpc.pb.go:497 +0xd0

github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x103f06da8, 0x14000d03bc0}, {0x103e35ca0, 0x14000d2a620}, 0x14000d04400, 0x1400084e720)

        /Users/ianwahbe/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e4

github.com/pulumi/pulumi/sdk/v3/proto/go._LanguageRuntime_GeneratePackage_Handler({0x103e7ee00, 0x14000b5a4c0}, {0x103f06da8, 0x14000d03bc0}, 0x14000822400, 0x14000b52380)

        /Users/ianwahbe/go/src/github.com/pulumi/pulumi/sdk/proto/go/language_grpc.pb.go:499 +0x148

google.golang.org/grpc.(*Server).processUnaryRPC(0x14000d0e200, {0x103f06da8, 0x14000d03b00}, {0x103f10000, 0x140008a5200}, 0x140007d2000, 0x14000b63620, 0x104c06600, 0x0)

        /Users/ianwahbe/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xb58

google.golang.org/grpc.(*Server).handleStream(0x14000d0e200, {0x103f10000, 0x140008a5200}, 0x140007d2000)

        /Users/ianwahbe/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0xb20

google.golang.org/grpc.(*Server).serveStreams.func2.1()

        /Users/ianwahbe/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8c

created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 68

        /Users/ianwahbe/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x13c

error: error reading from server: EOF
```

```json
{
  "name": "databricks",
  "version": "1.50.0",
  "description": "A Pulumi provider dynamically bridged from databricks.",
  "attribution": "This Pulumi package is based on the [`databricks` Terraform Provider](https://github.com/terraform-providers/terraform-provider-databricks).",
  "publisher": "Pulumi",
  "meta": {
    "moduleFormat": "(.*)(?:/[^/]*)"
  },
  "language": {
    "csharp": {
      "compatibility": "tfbridge20",
      "liftSingleValueMethodReturns": true,
      "respectSchemaVersion": true
    },
    "go": {
      "importBasePath": "github.com/pulumi/pulumi-databricks/sdk/go/databricks",
      "liftSingleValueMethodReturns": true,
      "generateExtraInputTypes": true,
      "respectSchemaVersion": true
    },
    "java": {
      "basePackage": "",
      "buildFiles": "",
      "gradleNexusPublishPluginVersion": "",
      "gradleTest": ""
    },
    "nodejs": {
      "packageDescription": "A Pulumi provider dynamically bridged from databricks.",
      "readme": "\u003e This provider is a derived work of the [Terraform Provider](https://github.com/terraform-providers/terraform-provider-databricks)\n\u003e distributed under [MPL 2.0](https://www.mozilla.org/en-US/MPL/2.0/). If you encounter a bug or missing feature,\n\u003e first check the [`pulumi-databricks` repo](/issues); however, if that doesn't turn up anything,\n\u003e please consult the source [`terraform-provider-databricks` repo](https://github.com/terraform-providers/terraform-provider-databricks/issues).",
      "compatibility": "tfbridge20",
      "disableUnionOutputTypes": true,
      "liftSingleValueMethodReturns": true,
      "respectSchemaVersion": true
    },
    "python": {
      "readme": "\u003e This provider is a derived work of the [Terraform Provider](https://github.com/terraform-providers/terraform-provider-databricks)\n\u003e distributed under [MPL 2.0](https://www.mozilla.org/en-US/MPL/2.0/). If you encounter a bug or missing feature,\n\u003e first check the [`pulumi-databricks` repo](/issues); however, if that doesn't turn up anything,\n\u003e please consult the source [`terraform-provider-databricks` repo](https://github.com/terraform-providers/terraform-provider-databricks/issues).",
      "compatibility": "tfbridge20",
      "respectSchemaVersion": true,
      "pyproject": {
        "enabled": true
      }
    }
  },
  "provider": {
    "description": "The provider type for the databricks package. By default, resources use package-wide configuration\nsettings, however an explicit `Provider` instance may be created and passed during resource\nconstruction to achieve fine-grained programmatic control over provider settings. See the\n[documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.\n"
  },
  "resources": {
    "databricks:index/provider:Provider": {
      "properties": {
        "authenticationType": {
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "authenticationType"
      ],
      "inputProperties": {
        "authenticationType": {
          "type": "string"
        }
      },
      "requiredInputs": [
        "authenticationType"
      ]
    }
  }
}
```

### Example

See https://github.com/pulumi/pulumi-terraform-provider/issues/14 for an example.

### Output of `pulumi about`

```
CLI          
Version      3.129.1-dev.0
Go Version   go1.22.4
Go Compiler  gc

Host     
OS       darwin
Version  14.5
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ian-pulumi-corp
User           ian-pulumi-corp
Organizations  ian-pulumi-corp, pulumi
Token type     personal

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default
```

### Additional context

Pulumi should reject the schema as invalid, or at minimum python code generation should error with an actionable message. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
> Pulumi should reject the schema as invalid

I'm curious how the other languages behave. Do they also panic or error? If some other languages "work," without erroring/panicing we may have to start with a warning rather than a hard error during schema validation, to avoid breaking someone who may depend on this working for the language(s) they care about.

Agree at a minimum we could have Python error rather than panic.

**Comment by iwahbe** [comment]
When using `pulumi package gen-sdk --language <LANG>`, I get:

- dotnet: `Panic:            fatal: An assertion has failed: duplicate file: Provider.cs`
- nodejs: `panic: fatal: An assertion has failed: duplicate file: provider.ts`
- python: `panic: fatal: An assertion has failed: duplicate file: pulumi_databricks/provider.py`
- go:     `panic: fatal: An assertion has failed: duplicate file: databricks/provider.go`
- java:   `Panic:            fatal: An assertion has failed: duplicate file: src/main/java/com/pulumi/databricks/Provider.java`


I think we can safely make this a schema error. 

It is a breaking change for Pulumi YAML, but I don't think we have substantial use of YAML only providers.

**Comment by beanscg** [comment]
Bean Labs took a public-source pass on this issue.

The narrowest useful next step looks like: schema/name collision repro

Public evidence checked:
- pkg/codegen/
- sdk/python/
- tests/

A good acceptance check would be a small regression or smoke test that fails before the change and passes after it.

No PR opened from this pass.
