### ISSUE TITLE
Resource refers to missing resource which is set to use `delete_before_replace=True`

### ISSUE THREAD

**Issue by jeevanions** [pulumi/pulumi#17073]
### What happened?

```
Pulumi Version:    v3.130.0
Go Version:        go1.22.6
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin
Command:           pulumi state delete urn:pulumi:sandbox::infra::azure-native:containerinstance:ContainerGroup::openfgaseed-container-group --force
Error:             resource urn:pulumi:sandbox::infra::command:local:Command::initSqlCommand's dependency urn:pulumi:sandbox::infra::azure-native:containerinstance:ContainerGroup::openfgaseed-container-group refers to missing resource

We delete the Container group before creating new one using `delete_before_replace=True` parameter. Often the resource that is dependent on this resource goes into a state that this resource doesnt exist anymore(may be caught up between delete and create.
```

### Example

1. Create command local and azurenative container Group resource with a dependency. 

### Output of `pulumi about`

```
Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.6/x64/src/runtime/debug/stack.go:24 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x10207a376?, 0x65?}, {0x14002c9f678?, 0x65?, 0x40?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:313 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x14001f34630)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:217 +0xd9c
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getSnapshot(0x140022ca870, {0x1032758c8, 0x104978d80}, {0x10324d720, 0x104978d80}, 0x1400229bb80)
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:180 +0xf4
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Snapshot(0x14002296570, {0x1032758c8, 0x104978d80}, {0x10324d720, 0x104978d80})
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/stack.go:62 +0x84
main.totalStateEdit({0x1032758c8, 0x104978d80}, {0x103290318, 0x14002296570}, 0x1, {{0x101f9588f, 0x6}, 0x0, 0x0, 0x0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:153 +0x6c
main.runTotalStateEdit({0x1032758c8, 0x104978d80}, {0x0, 0x0}, 0x1, 0x140023bfb60)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:147 +0xf4
main.runStateEdit(...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:124
main.newStateDeleteCommand.func1(0x0?, {0x140021411c0?, 0x1?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_delete.go:75 +0x164
main.newStateDeleteCommand.runCmdFunc.func2(0x0?, {0x140021411c0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:31 +0x28
main.newStateDeleteCommand.runCmdFunc.RunFunc.func5(0x1400216e308, {0x140021411c0, 0x1, 0x2})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x38
github.com/spf13/cobra.(*Command).execute(0x1400216e308, {0x140021411a0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x14001ed6908)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x54
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jeevanions** [comment]
There is no way to recover form this unless we open the stat json file and remove the dependencies than upload the json to remote state store.

**Comment by justinvp** [comment]
Possibly a dupe or similar of https://github.com/pulumi/pulumi/issues/17070?

**Comment by Frassle** [comment]
```
Command:           pulumi state delete urn:pulumi:sandbox::infra::azure-native:containerinstance:ContainerGroup::openfgaseed-container-group --force
```

I'm assuming the initial command that caused an issue was _not_ `pulumi state delete`. Can you share what update initially triggered an issue with the state?
