### ISSUE TITLE
The Pulumi CLI encountered a snapshot integrity error

### ISSUE THREAD

**Issue by jeevanions** [pulumi/pulumi#17070]
### What happened?

================================================================================
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:    v3.130.0
Go Version:        go1.22.6
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin
Command:           pulumi state delete urn:pulumi:sandbox::infra::azure-native:network:RecordSet::frontend-cname --force
Error:             resource urn:pulumi:sandbox::infra::azure-native:web:StaticSiteCustomDomain::staticSiteCustomDomain's dependency urn:pulumi:sandbox::infra::azure-native:network:RecordSet::frontend-cname refers to missing resource

### Example

-

### Output of `pulumi about`

Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.6/x64/src/runtime/debug/stack.go:24 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x102e6e376?, 0x49?}, {0x14002d1f678?, 0x49?, 0x40?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:313 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x14000f0e630)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:217 +0xd9c
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getSnapshot(0x140005abef0, {0x1040698c8, 0x10576cd80}, {0x104041720, 0x10576cd80}, 0x14001f2c980)
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:180 +0xf4
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Snapshot(0x14000f824b0, {0x1040698c8, 0x10576cd80}, {0x104041720, 0x10576cd80})
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/stack.go:62 +0x84
main.totalStateEdit({0x1040698c8, 0x10576cd80}, {0x104084318, 0x14000f824b0}, 0x1, {{0x102d8988f, 0x6}, 0x0, 0x0, 0x0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:153 +0x6c
main.runTotalStateEdit({0x1040698c8, 0x10576cd80}, {0x0, 0x0}, 0x1, 0x1400213fb60)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:147 +0xf4
main.runStateEdit(...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:124
main.newStateDeleteCommand.func1(0x0?, {0x14000c643a0?, 0x1?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_delete.go:75 +0x164
main.newStateDeleteCommand.runCmdFunc.func2(0x0?, {0x14000c643a0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:31 +0x28
main.newStateDeleteCommand.runCmdFunc.RunFunc.func5(0x140005b0308, {0x14000c643a0, 0x1, 0x2})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x38
github.com/spf13/cobra.(*Command).execute(0x140005b0308, {0x14000c64380, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x14000a07508)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x54

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening the issue @jeevanions and sorry for the trouble. Did the error first happen when running some other command, before running the `pulumi state delete` command? If so, what command and what happened in the update?

**Comment by lunaris** [comment]
Note: this is technically a duplicate of #16916, since this was the first issue raised with this root cause (and consequently is the only issue bearing a regression label).
