### ISSUE TITLE
Test flakes in integration test using resource `getResource` invoke

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#17095]
This test failed in CI, though it concerningly looks similar like a regression or defect.

https://github.com/pulumi/pulumi/blob/df7b3e802766fffc0388d18926227fe02f82db06/tests/integration/integration_go_test.go#L956-L968

https://github.com/pulumi/pulumi/blob/df7b3e802766fffc0388d18926227fe02f82db06/tests/integration/resource_refs_get_resource/go/main.go#L171-L188

Panic in CI (https://github.com/pulumi/pulumi/actions/runs/10605622250/job/29394973013?pr=17084#step:36:190):

```
Diagnostics:
  pulumi:pulumi:Stack (resource_refs_get_resource_go-p-it-fv-az1426--go-566573f2):
    panic: expected message "hello world!" not equal to actual message ""
    goroutine 58 [running]:
    main.main.func1.1(***0xc0000bf620?, 0x2?, 0x0?***)
    	/home/runner/go/src/stackName-1724886544225458069-241426/main.go:181 +0x16e
    reflect.Value.call(***0xcf7a20?, 0xee3260?, 0x30?***, ***0xe77027, 0x4***, ***0xc0000bf920, 0x1, 0xc0000bf920?***)
    	/opt/hostedtoolcache/go/1.22.6/x64/src/reflect/value.go:596 +0xca6
    reflect.Value.Call(***0xcf7a20?, 0xee3260?, 0x101000000000000?***, ***0xc0000bf920?, 0x0?, 0x3?***)
    	/opt/hostedtoolcache/go/1.22.6/x64/src/reflect/value.go:380 +0xb9
    github.com/pulumi/pulumi/sdk/v3/go/internal.(*applier).Call(0xc000522700, ***0xfd22d0, 0x174c1c0***, ***0xca8960?, 0xc000012750?, 0x0?***)
    	/home/runner/work/pulumi/pulumi/sdk/go/internal/types.go:510 +0x22d
    github.com/pulumi/pulumi/sdk/v3/go/internal.(*OutputState).applyTWithApplier.func1()
    	/home/runner/work/pulumi/pulumi/sdk/go/internal/types.go:622 +0x16a
    created by github.com/pulumi/pulumi/sdk/v3/go/internal.(*OutputState).applyTWithApplier in goroutine 1
    	/home/runner/work/pulumi/pulumi/sdk/go/internal/types.go:609 +0x265
```

**Comment by justinvp** [comment]
Looks like #16897 didn't fully address the flakiness.
