### ISSUE TITLE
Pulumi panic when plugins.providers.path ends with extra slash

### ISSUE THREAD

**Issue by zhangyoufu** [pulumi/pulumi#17130]
### What happened?

```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.130.0
Go Version:       go1.22.6
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            fatal: An assertion has failed: plugin executable (/Users/user/Project/pulumi-alicloud/bin/pulumi-resource-alicloud) is not inside plugin directory (/Users/user/Project/pulumi-alicloud/bin/)

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go@1.22/1.22.6/libexec/src/runtime/debug/stack.go:24 +0x64
main.panicHandler(0x14001fbff1f)
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/cmd/pulumi/main.go:34 +0x44
panic({0x105722200?, 0x14001b59070?})
	/opt/homebrew/Cellar/go@1.22/1.22.6/libexec/src/runtime/panic.go:770 +0x124
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20240823-4941-susvfh/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0xf0?, {0x104aefc5f?, 0x104a0f854?}, {0x14001fbdc78?, 0x14001198dac?, 0x8?})
	/private/tmp/pulumi-20240823-4941-susvfh/sdk/go/common/util/contract/assert.go:35 +0xe0
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.GetPluginPath({0x105ceee50?, 0x1400090bb18?}, {0x104a0f854?, 0x14001fbde70?}, {0x14001198dac?, 0x8?}, 0x0?, {0x140020ffc80?, 0x0?, 0x0?})
	/private/tmp/pulumi-20240823-4941-susvfh/sdk/go/common/workspace/plugins.go:1765 +0x10c
github.com/pulumi/pulumi/pkg/v3/engine.ensurePluginsAreInstalled({0x105ce2c08, 0x14001c544b0}, {0x105ceee50, 0x1400090bb18}, 0x14001b50db0, {0x140020ffc80, 0x1, 0x1})
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/engine/plugins.go:201 +0x2b8
github.com/pulumi/pulumi/pkg/v3/engine.installPlugins({0x105ce2c08, 0x14001c544b0}, 0x10?, {0x14000d3f740?, 0x10?}, {0x105545f38?, 0x140014a2300?}, 0x140020ffbc0, 0x14000feb540, 0x0)
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/engine/update.go:272 +0x158
github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource({0x105ce2c08, 0x14001c544b0}, {0x0?, 0x105ceee50?}, 0x1400149b440, 0x140020d28f0, {0x14000d3f740, 0x23}, {0x105545f38, 0x1}, ...)
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/engine/update.go:441 +0x70
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(0x140020ffc00, 0x14000782680, {0x105ceedb0, 0x14000782700}, 0x1400149b440)
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/engine/deployment.go:210 +0x304
github.com/pulumi/pulumi/pkg/v3/engine.update(0x140020ffc00, 0x14000782680, 0x1400149b440)
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/engine/update.go:511 +0x168
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x105cdf360, 0x140014898c0}, 0x140020ffc00, {{0x1074049c0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x20, ...}, ...)
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/engine/update.go:215 +0x3d4
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).apply(_, {_, _}, {_, _}, {_, _}, {0x140020d28f0, {0x14000d3f740, 0x23}, ...}, ...)
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/backend/diy/backend.go:1110 +0x878
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).Preview(_, {_, _}, {_, _}, {0x140020d28f0, {0x14000d3f740, 0x23}, {0x0, 0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/backend/diy/backend.go:931 +0x78
github.com/pulumi/pulumi/pkg/v3/backend.PreviewStack({_, _}, {_, _}, {0x140020d28f0, {0x14000d3f740, 0x23}, {0x0, 0x0, 0x0}, ...}, ...)
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/backend/stack.go:91 +0x88
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Preview(_, {_, _}, {0x140020d28f0, {0x14000d3f740, 0x23}, {0x0, 0x0, 0x0}, 0x140007d2798, ...}, ...)
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/backend/diy/stack.go:85 +0x68
main.newPreviewCmd.func1(0x14000a22608, {0x1074049c0, 0x0, 0x0?})
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/cmd/pulumi/preview.go:456 +0x1014
main.newPreviewCmd.runCmdFunc.func2(0x0?, {0x1074049c0?, 0x0?, 0x0?})
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/cmd/pulumi/errors.go:31 +0x28
main.newPreviewCmd.runCmdFunc.RunFunc.func5(0x14000a22608, {0x1074049c0, 0x0, 0x0})
	/private/tmp/pulumi-20240823-4941-susvfh/sdk/go/common/util/cmdutil/exit.go:99 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000a22608, {0x1074049c0, 0x0, 0x0})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x14001c8f208)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/private/tmp/pulumi-20240823-4941-susvfh/pkg/cmd/pulumi/main.go:55 +0x54
```

### Example

`Pulumi.yaml`:
```
plugins:
  providers:
    - name: alicloud
      path: /Users/user/Project/pulumi-alicloud/bin/
```

related code: https://github.com/pulumi/pulumi/blob/7ab5fad61e5cd2df7bcc19183dd4488d99b727ef/sdk/go/common/workspace/plugins.go#L1765-L1766

workaround: remove the final `/` from path

### Output of `pulumi about`

```
CLI
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  alicloud    3.0.0-alpha.0+dev
resource  cloudflare  5.36.0
language  python      unknown

Host
OS       darwin
Version  14.6.1
Arch     arm64

...
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening the issue, @zhangyoufu. @tgummerer, can you take a look?

**Comment by Frassle** [comment]
I think this just needs a path clean on https://github.com/pulumi/pulumi/blob/7ab5fad61e5cd2df7bcc19183dd4488d99b727ef/sdk/go/common/workspace/plugins.go#L1846
