### ISSUE TITLE
Allowed to delete a resource from stack that had dependencies

### ISSUE THREAD

**Issue by joedyndale** [pulumi/pulumi#17157]
### What happened?

Got the following error in my deployment pipeline, along with a request to file a ticket here about it. It happened because I manually deleted a resource from the stack, which I probably shouldn't have been allowed to.

```
Error:             resource urn:pulumi:dev::identity-service-v2::azure-native:keyvault:Secret::kv-CommandQueue-Name's dependency urn:pulumi:dev::identity-service-v2::azure-native:servicebus:Queue::CommandQueue refers to missing resource

Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x2d16148?, 0x50?}, {0xc00213d4b0?, 0x50?, 0x40?})
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:313 +0x34
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0xc001c0b3b0)
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:217 +0x127f
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getSnapshot(0x10002[37](https://github.com/elkjopnordic/identity-service-v2/actions/runs/10702120091/job/29669592505#step:4:38)9380?, {0x37b10a8, 0x4f0c020}, {0x37891e0, 0x4f0c020}, {0x37b15c0?, 0xc0022d7e00?})
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:229 +0x85
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getTarget(0xc0022db130, {0x37b10a8, 0x4f0c020}, {0x37891e0, 0x4f0c020}, {0x37b15c0, 0xc0022d7e00}, 0xc001631b00, {0x7fe01c4526f0, 0x4f0c020})
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:245 +0x106
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).newUpdate(_, {_, _}, {_, _}, {0xc0023242c0, {0xc001a335c0, 0x4b}, {0x0, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:196 +0x207
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc0023242c0, {0xc001a335c0, 0x4b}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1354 +0x11a
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc0023242c0, {0xc001a335c0, 0x4b}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1328 +0x52a
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc0023242c0, {0xc001a335c0, 0x4b}, {0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/apply.go:272 +0x22d
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Update(_, {_, _}, {_, _}, {0xc0023242c0, {0xc001a335c0, 0x4b}, {0x0, 0x0, ...}, ...})
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1103 +0xb8
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc0023242c0, {0xc001a335c0, 0x4b}, {0x0, 0x0, 0x0}, ...})
	/home/runner/work/pulumi/pulumi/pkg/backend/stack.go:96 +0x9e
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Update(_, {_, _}, {0xc0023242c0, {0xc001a335c0, 0x4b}, {0x0, 0x0, 0x0}, 0xc001608fd8, ...})
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:179 +0x6a
main.newUpCmd.func1({_, _}, {{{0x4f0c020, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x8, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:187 +0xead
main.newUpCmd.func3(0xc0020c2908, {0xc00204[39](https://github.com/elkjopnordic/identity-service-v2/actions/runs/10702120091/job/29669592505#step:4:40)80, 0x0, 0x0?})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:531 +0xc2e
main.newUpCmd.runCmdFunc.func4(0x0?, {0xc002043980?, 0x0?, 0x0?})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:31 +0x1c
main.newUpCmd.runCmdFunc.RunFunc.func7(0xc0020c2908, {0xc002043980, 0x0, 0x4})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x3b
github.com/spf13/cobra.(*Command).execute(0xc0020c2908, {0xc0020439[40](https://github.com/elkjopnordic/identity-service-v2/actions/runs/10702120091/job/29669592505#step:4:41), 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc001c31b08)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x58
```

### Example

Create an Azure ServiceBus queue, and store its name in a KeyVault secret. Manually delete the queue resource from the stack.

### Output of `pulumi about`

```
Pulumi Version:    v3.130.0
Go Version:        go1.22.6
Go Compiler:       gc
Architecture:      amd64
Operating System:  linux
Command:           pulumi up -y -s elkjopnordic/dev --skip-preview
```

### Additional context

This occurred when running in a GitHub Workflow, but it obviously also occurs when running locally on my own machine. I'm now unable to run the full deployment or even delete the things that are now missing a dependency.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
> Manually delete the queue resource from the stack

@joedyndale, how did you manually delete the resource?

**Comment by justinvp** [comment]
@joedyndale, did you run `pulumi state delete` to do this or something else?

**Comment by Frassle** [comment]
> Manually delete the queue resource from the stack.

I've checked over `state delete` and I can't repro this. It correctly errors if you try and delete a resource that another depends on. 

If this was from manually deleting by editing the state file then this isn't really a bug, but more caveat utilitor. If you edit the JSON by hand it's on you to get it right. Although maybe we should make "state import" reject invalid snapshots unless --force or something is given.

**Comment by Frassle** [comment]
@joedyndale, bumping Justins question, but how exactly did you manually delete the resource?

**Comment by joeduffy** [comment]
> Although maybe we should make "state import" reject invalid snapshots unless --force or something is given.


I know it’s largely orthogonal to the issue being discussed, however, I do think this would be a nice guardrail to add!

**Comment by Frassle** [comment]
> I know it’s largely orthogonal to the issue being discussed, however, I do think this would be a nice guardrail to add!

Just went to check this again, and thankfully we already have this guardrail in place. Exactly as described, it will error by default but you can pass `--force` to import anyway.

**Comment by justinvp** [comment]
Closing since we haven't heard back. Happy to re-open, if needed.
