### ISSUE TITLE
Python SDK: AssertionError: Unexpected type. Expected 'list' got 'typing.Union[typing.Sequence..

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#17181]
### What happened?

Unable to provision DynamoDB tables in aws-native with keySchema in Python. The SDK fails to send the data to the engine fails with:

```
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/anton/bin/pulumi-language-python-exec", line 192, in <module>
        loop.run_until_complete(coro)
      File "/nix/store/ak3zf631ws2rwsl5qq0x3v7j18h0c2jj-python3-3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
        return future.result()
      File "/Users/anton/Library/Mobile Documents/com~apple~CloudDocs/pulumi-bugs/aws-native-846/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 142, in run_in_stack
        await run_pulumi_func(run)
      File "/Users/anton/Library/Mobile Documents/com~apple~CloudDocs/pulumi-bugs/aws-native-846/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 56, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/anton/Library/Mobile Documents/com~apple~CloudDocs/pulumi-bugs/aws-native-846/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 118, in wait_for_rpcs
        await task
      File "/Users/anton/Library/Mobile Documents/com~apple~CloudDocs/pulumi-bugs/aws-native-846/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 935, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/Users/anton/Library/Mobile Documents/com~apple~CloudDocs/pulumi-bugs/aws-native-846/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 197, in prepare_resource
        serialized_props = await rpc.serialize_properties(
      File "/Users/anton/Library/Mobile Documents/com~apple~CloudDocs/pulumi-bugs/aws-native-846/venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 216, in serialize_properties
        result = await serialize_property(
      File "/Users/anton/Library/Mobile Documents/com~apple~CloudDocs/pulumi-bugs/aws-native-846/venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 368, in serialize_property
        element_type = _get_list_element_type(typ)
      File "/Users/anton/Library/Mobile Documents/com~apple~CloudDocs/pulumi-bugs/aws-native-846/venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 168, in _get_list_element_type
        raise AssertionError(f"Unexpected type. Expected 'list' got '{typ}'")
    AssertionError: Unexpected type. Expected 'list' got 'typing.Union[typing.Sequence[typing.Union[pulumi_aws_native.dynamodb._inputs.TableKeySchemaArgs, typing.Awaitable[pulumi_aws_native.dynamodb._inputs.TableKeySchemaArgs], pulumi.output.Output[NoneType]]], typing.Any, typing.Awaitable[typing.Union[typing.Sequence[typing.Union[pulumi_aws_native.dynamodb._inputs.TableKeySchemaArgs, typing.Awaitable[pulumi_aws_native.dynamodb._inputs.TableKeySchemaArgs], pulumi.output.Output[NoneType]]], typing.Any]], pulumi.output.Output[NoneType]]'
```

The relevant schema bit is:

```
                "keySchema": {
                    "oneOf": [
                        {
                            "type": "array",
                            "items": {
                                "$ref": "#/types/aws-native:dynamodb:TableKeySchema"
                            }
                        },
                        {
                            "$ref": "pulumi.json#/Any"
                        }
                    ],
                    "description": "Specifies the attributes that make up the primary key for the table. The attributes in the ``KeySchema`` property must also be defined in the ``AttributeDefinitions`` property."
                },

```

Python generated as:

```
@pulumi.input_type
class TableArgs:
    def __init__(__self__, *,
                 key_schema: pulumi.Input[Union[Sequence[pulumi.Input['TableKeySchemaArgs']], Any]],
```

### Example

```python

"""An AWS Python Pulumi program"""

import pulumi
import pulumi_aws_native as aws_native

aws_native.dynamodb.Table(
       "table_id",
       table_name="example",
       billing_mode="PROVISIONED",
       opts=pulumi.ResourceOptions(protect=True),
       attribute_definitions=[
           aws_native.dynamodb.TableAttributeDefinitionArgs(
               attribute_name="PrimaryKey",
               attribute_type="S",
            )
        ],
        provisioned_throughput=aws_native.dynamodb.TableProvisionedThroughputArgs(
            read_capacity_units=100,
            write_capacity_units=1,
        ),
        key_schema=[
            {
                "attribute_name": "PrimaryKey",
                "key_type": "HASH",
            },
        ],
)

```

### Output of `pulumi about`

```
CLI          
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.50.1
resource  aws-native  0.121.0
language  python      unknown

Host     
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in python: executable='/Users/anton/Library/Mobile Documents/com~apple~CloudDocs/pulumi-bugs/aws-native-846/venv/bin/python' version='3.10.13'

Current Stack: anton-pulumi-corp/aws-native-846/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/anton-pulumi-corp
User           anton-pulumi-corp
Organizations  anton-pulumi-corp, moolumi, demo, pulumi
Token type     personal

Dependencies:
NAME               VERSION
pip                24.2
pulumi_aws         6.50.1
pulumi_aws_native  0.121.0
setuptools         74.1.2
wheel              0.44.0

Pulumi locates its logs in /var/folders/gd/3ncjb1lj5ljgk8xl5ssn_gvc0000gn/T/com.apple.shortcuts.mac-helper// by default

```

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks. I'll take a closer look. I suspect `_get_list_element_type` isn't able to correctly determine the element type due to the `Union`. Should be a relatively quick fix.
