### ISSUE TITLE
TestNewPythonConvertRequirementsTxt is flaky on windows

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#17183]
```
=== FAIL: integration TestNewPythonConvertRequirementsTxt (10.23s)
    environment.go:103: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\test-env3651034804
    environment.go:223: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/test-env3651034804
    environment.go:223: Running command pulumi new python --force --non-interactive --yes --name test_project --description A python test using poetry as toolchain --stack test --runtime-options toolchain=poetry
    integration_python_acceptance_test.go:527: Run Error: exit status 0xffffffff
    integration_python_acceptance_test.go:527: STDOUT: Created project 'test_project'
        
        Created stack 'test'
        
        Installing dependencies...
        
        Updating dependencies
        Resolving dependencies...
        
        Package operations: 7 installs, 0 updates, 0 removals
        
          - Installing dill (0.3.8)
          - Installing grpcio (1.60.2)
          - Installing protobuf (4.25.4)
          - Installing pyyaml (6.0.2)
          - Installing semver (2.13.0)
          - Installing six (1.16.0)
        
          PermissionError
        
          [WinError 5] Access is denied: 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\28\\4e\\98\\453ce8b870e4cfe9358088414f85245d6eb340e295a8c57ee760ca773b\\tmp3a5wnzg6' -> 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\28\\4e\\98\\453ce8b870e4cfe9358088414f85245d6eb340e295a8c57ee760ca773b\\dill-0.3.8-py3-none-any.whl'
        
          at C:\Program Files (x86)\pipx\venvs\poetry\lib\site-packages\requests\utils.py:312 in atomic_open
               308|     tmp_descriptor, tmp_name = tempfile.mkstemp(dir=os.path.dirname(filename))
               309|     try:
               310|         with os.fdopen(tmp_descriptor, "wb") as tmp_handler:
               311|             yield tmp_handler
            >  312|         os.replace(tmp_name, filename)
               313|     except BaseException:
               314|         os.remove(tmp_name)
               315|         raise
               316| 
        
        The following error occurred when trying to handle this error:
        
        
          PermissionError
        
          [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\28\\4e\\98\\453ce8b870e4cfe9358088414f85245d6eb340e295a8c57ee760ca773b\\dill-0.3.8-py3-none-any.whl'
        
          at C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\pathlib.py:1354 in unlink
              1350|         Remove this file or link.
              1351|         If the path is a directory, use rmdir() instead.
              1352|         """
              1353|         try:
            > 1354|             self._accessor.unlink(self)
              1355|         except FileNotFoundError:
              1356|             if not missing_ok:
              1357|                 raise
              1358| 
        
        Cannot install dill.
        
        
          PermissionError
        
          [WinError 5] Access is denied: 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\36\\20\\14\\641a24d267d75de08dc2038dbbde3d028ba45f1934e7068368dbe8b1dd\\tmp7qt4ij93' -> 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\36\\20\\14\\641a24d267d75de08dc2038dbbde3d028ba45f1934e7068368dbe8b1dd\\protobuf-4.25.4-cp39-cp39-win_amd64.whl'
        
          at C:\Program Files (x86)\pipx\venvs\poetry\lib\site-packages\requests\utils.py:312 in atomic_open
               308|     tmp_descriptor, tmp_name = tempfile.mkstemp(dir=os.path.dirname(filename))
               309|     try:
               310|         with os.fdopen(tmp_descriptor, "wb") as tmp_handler:
               311|             yield tmp_handler
            >  312|         os.replace(tmp_name, filename)
               313|     except BaseException:
               314|         os.remove(tmp_name)
               315|         raise
               316| 
        
        The following error occurred when trying to handle this error:
        
        
          PermissionError
        
          [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\36\\20\\14\\641a24d267d75de08dc2038dbbde3d028ba45f1934e7068368dbe8b1dd\\protobuf-4.25.4-cp39-cp39-win_amd64.whl'
        
          at C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\pathlib.py:1354 in unlink
              1350|         Remove this file or link.
              1351|         If the path is a directory, use rmdir() instead.
              1352|         """
              1353|         try:
            > 1354|             self._accessor.unlink(self)
              1355|         except FileNotFoundError:
              1356|             if not missing_ok:
              1357|                 raise
              1358| 
        
        Cannot install protobuf.
        
    integration_python_acceptance_test.go:527: STDERR: Creating virtualenv non-package-mode in C:\Users\RUNNER~1\AppData\Local\Temp\test-env3651034804\.venv
        error: installing dependencies failed: exit status 1
        Run `pulumi install` to complete the installation.
    integration_python_acceptance_test.go:527: Ran command pulumi args [new python --force --non-interactive --yes --name test_project --description A python test using poetry as toolchain --stack test --runtime-options toolchain=poetry] and expected success. Instead got failure.

=== FAIL: integration TestAutomaticVenvCreationPoetry (10.37s)
Traceback (most recent call last):
  File "D:\a\pulumi\pulumi\scripts\go-test.py", line 104, in <module>
    raise e
  File "D:\a\pulumi\pulumi\scripts\go-test.py", line 100, in <module>
    sp.check_call(args, shell=False)
  File "C:\hostedtoolcache\windows\Python\3.12.5\x64\Lib\subprocess.py", line 413, in check_call
    environment.go:103: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\test-env1942999696
    environment.go:223: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/test-env1942999696
    environment.go:223: Running command pulumi stack init teststack
    environment.go:223: Running command pulumi preview
    integration_python_acceptance_test.go:337: Run Error: exit status 0xffffffff
    integration_python_acceptance_test.go:337: STDOUT: Previewing update (teststack):
        @ previewing update......
            pulumi:pulumi:Stack pulumi-python-poetry-teststack  error: Creating virtualenv pulumi-python-poetry in C:\Users\RUNNER~1\AppData\Local\Temp\test-env1942999696\.venv
        @ previewing update.....
            pulumi:pulumi:Stack pulumi-python-poetry-teststack  Updating dependencies
            pulumi:pulumi:Stack pulumi-python-poetry-teststack  Resolving dependencies...
        @ previewing update.....
            pulumi:pulumi:Stack pulumi-python-poetry-teststack  
            pulumi:pulumi:Stack pulumi-python-poetry-teststack  Package operations: 7 installs, 0 updates, 0 removals
            pulumi:pulumi:Stack pulumi-python-poetry-teststack    - Installing dill (0.3.8)
            pulumi:pulumi:Stack pulumi-python-poetry-teststack    - Installing grpcio (1.60.2)
            pulumi:pulumi:Stack pulumi-python-poetry-teststack    - Installing protobuf (4.25.4)
            pulumi:pulumi:Stack pulumi-python-poetry-teststack    - Installing pyyaml (6.0.2)
            pulumi:pulumi:Stack pulumi-python-poetry-teststack    - Installing semver (2.13.0)
            pulumi:pulumi:Stack pulumi-python-poetry-teststack    - Installing six (1.16.0)
            pulumi:pulumi:Stack pulumi-python-poetry-teststack  
            pulumi:pulumi:Stack pulumi-python-poetry-teststack    PermissionError
        @ previewing update....
            pulumi:pulumi:Stack pulumi-python-poetry-teststack         308|     tmp_descriptor, tmp_name = tempfile.mkstemp(dir=os.path.dirname(filename))
            pulumi:pulumi:Stack pulumi-python-poetry-teststack         309|     try:
            pulumi:pulumi:Stack pulumi-python-poetry-teststack        1350|         Remove this file or link.
            pulumi:pulumi:Stack pulumi-python-poetry-teststack        1351|         If the path is a directory, use rmdir() instead.
            pulumi:pulumi:Stack pulumi-python-poetry-teststack  
            pulumi:pulumi:Stack pulumi-python-poetry-teststack         308|     tmp_descriptor, tmp_name = tempfile.mkstemp(dir=os.path.dirname(filename))
            pulumi:pulumi:Stack pulumi-python-poetry-teststack         309|     try:
            pulumi:pulumi:Stack pulumi-python-poetry-teststack        1350|         Remove this file or link.
            pulumi:pulumi:Stack pulumi-python-poetry-teststack        1351|         If the path is a directory, use rmdir() instead.
            pulumi:pulumi:Stack pulumi-python-poetry-teststack  
            pulumi:pulumi:Stack pulumi-python-poetry-teststack    PermissionError
            pulumi:pulumi:Stack pulumi-python-poetry-teststack         308|     tmp_descriptor, tmp_name = tempfile.mkstemp(dir=os.path.dirname(filename))
            pulumi:pulumi:Stack pulumi-python-poetry-teststack         309|     try:
            pulumi:pulumi:Stack pulumi-python-poetry-teststack    [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\runneradmin\\AppData\\Local\\pypoetry\\Cache\\artifacts\\6a\\7a\\66\\d746c06868d6a05ab881b93ece592eb6a42be46bcc069fb4ae51d716c1\\grpcio-1.60.2-cp39-cp39-win_amd64.whl'
            pulumi:pulumi:Stack pulumi-python-poetry-teststack        1350|         Remove this file or link.
            pulumi:pulumi:Stack pulumi-python-poetry-teststack        1351|         If the path is a directory, use rmdir() instead.
            pulumi:pulumi:Stack pulumi-python-poetry-teststack  
    integration_python_acceptance_test.go:337: STDERR: error: failed to discover plugin requirements: exit status 1
    integration_python_acceptance_test.go:337: Ran command pulumi args [preview] and expected success. Instead got failure.
```

from https://github.com/pulumi/pulumi/actions/runs/10721771194/attempts/1?pr=17102.

**Comment by tgummerer** [comment]
I believe this was fixed in https://github.com/pulumi/pulumi/pull/17337, but I didn't get the `Fixes:` line correct in the PR description.  Closing this out.
