### ISSUE TITLE
[sdk/nodejs] Output returning invokes seem to be broken in some cases

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#17379]
To repro, in an empty directory run the following:
1. `mkdir azurerepro && cd azurerepro`
2. `pulumi new azure-typescript`
3. `pulumi preview`

```
$ pulumi preview
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/...

     Type                                     Name              Plan       Info
 +   pulumi:pulumi:Stack                      azurereltest-dev  create     1 error
 +   ├─ azure-native:resources:ResourceGroup  resourceGroup     create
 +   └─ azure-native:storage:StorageAccount   sa                create

Diagnostics:
  pulumi:pulumi:Stack (azurereltest-dev):
    error: Running program '/Users/user/Documents/azurerepro/index.ts' failed with an unhandled exception:
    <ref *1> Error: invocation of azure-native:storage:listStorageAccountKeys returned an error: request failed /subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/{resourceGroupName}/providers/Microsoft.Storage/storageAccounts/{accountName}/listKeys: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group '{resourceGroupName}' could not be found."
        at Object.callback (/Users/justin/Documents/azurerepro/node_modules/@pulumi/azure-native/node_modules/@pulumi/runtime/invoke.ts:261:37)
        at Object.onReceiveStatus (/Users/justin/Documents/azurerepro/node_modules/@grpc/grpc-js/src/client.ts:360:26)
        at Object.onReceiveStatus (/Users/justin/Documents/azurerepro/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
        at Object.onReceiveStatus (/Users/justin/Documents/azurerepro/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
        at /Users/justin/Documents/azurerepro/node_modules/@grpc/grpc-js/src/resolving-call.ts:163:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11) {
      promise: Promise { <rejected> [Circular *1] }
    }
```

If I specify the following versions in `package.json` it works:

```json
"@pulumi/azure-native": "2.62.0",
"@pulumi/pulumi": "3.132.0"
```

But these versions are broken, including the latest dev release from the most recent commit in master:

```json
"@pulumi/azure-native": "2.63.0",
"@pulumi/pulumi": "3.133.0"
```

```json
"@pulumi/azure-native": "2.63.0",
"@pulumi/pulumi": "3.134.0"
```

```json
"@pulumi/azure-native": "2.63.0",
"@pulumi/pulumi": "3.134.2-alpha.xdacad14"
```

Note that version [v2.63.0](https://github.com/pulumi/pulumi-azure-native/releases/tag/v2.63.0) of Azure Native was released yesterday and depends on the latest Node.js sdkgen that uses the new `pulumi.runtime.invokeOutput`.

See failing test here: https://github.com/pulumi/templates/actions/runs/11042205684/job/30674073549#step:21:958

Related to:
- https://github.com/pulumi/pulumi/pull/17237
- https://github.com/pulumi/pulumi/pull/17353

**Comment by justinvp** [comment]
False alarm.

https://github.com/pulumi/pulumi/pull/17353 does indeed address this problem.

The reason I wasn’t seeing the fix working was because when installing these packages:

```json
"@pulumi/azure-native": "2.63.0",
"@pulumi/pulumi": "3.134.2-alpha.xdacad14"
```

`@pulumi/azure-native` `2.63.0` depends on `@pulumi/pulumi` `^3.0.0`.

When running `npm install`, `npm` installs `@pulumi/pulumi` `3.134.0` inside a nested `node_modules` directory (`node_modules/@pulumi/azure-native/node_modules/@pulumi/pulumi`). `3.134.0` doesn't have the fix. It wasn’t actually using the dev version of the package (at `node_modules/@pulumi/pulumi`) that has the fix.

If I force it to via `overrides` in `package.json`:

```json
    "dependencies": {
        "@pulumi/azure-native": "2.63.0",
        "@pulumi/pulumi": "3.134.2-alpha.xdacad14"
    },
    "overrides": {
        "@pulumi/pulumi": "3.134.2-alpha.xdacad14"
    }
```

Then it works.
