### ISSUE TITLE
Request message serialization failure: b.Va is not a function

### ISSUE THREAD

**Issue by notquiteasplanned** [pulumi/pulumi#17421]
### What happened?

I'm trying to use both resources available through various providers as well as my own component resources together, but whenever I try to do a `pulumi preview` or `pulumi up` I get the following error:

```sh
Diagnostics:
  pulumi:pulumi:Stack (infra-test-dev):
    error: Running program '~/pulumi-b-va-not-a-function/infra/index.ts' failed with an unhandled exception:
    <ref *1> Error: failed to register new resource echo [command:local:Command]: 13 INTERNAL: Request message serialization failure: b.Va is not a function
        at Object.registerResource (~/pulumi-b-va-not-a-function/infra/node_modules/@pulumi/runtime/resource.ts:444:27)
        at new Resource (~/pulumi-b-va-not-a-function/infra/node_modules/@pulumi/resource.ts:507:13)
        at new CustomResource (~/pulumi-b-va-not-a-function/infra/node_modules/@pulumi/resource.ts:962:9)
        at new Command (~/pulumi-b-va-not-a-function/infra/node_modules/@pulumi/local/command.ts:317:9)
        at file://~/pulumi-b-va-not-a-function/infra/index.ts:5:13
        at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
        at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26) {
      promise: Promise { <rejected> [Circular *1] }
    }
```

What's really strange is if I comment out either the provider resource _or_ my component resource, the commands succeed, it's only when they're both uncommented that I get this error.

### Example

I've created a repo with a minimal reproduction sample: https://github.com/notquiteasplanned/pulumi-b-va-not-a-function

The code where I originally hit this error was much more complex, but I was able to simplify it down to reproduce with just instances of the [`Command`](https://www.pulumi.com/registry/packages/command/) provider.

### Output of `pulumi about`

```
$ pulumi about
CLI
Version      3.134.1
Go Version   go1.23.1
Go Compiler  gc

Plugins
NAME     VERSION
command  1.0.1
command  1.0.1
nodejs   unknown

Host
OS       darwin
Version  14.7
Arch     arm64

This project is written in nodejs: executable='~/.local/share/mise/installs/node/22/bin/node' version='v22.9.0'

Backend
Name           <MY_DEVICE>.local
URL            azblob://backend?storage_account=<MY_STORAGE_ACCOUNT>
User           <MY_USER>
Organizations
Token type     personal

Dependencies:
NAME                     VERSION
ts-node                  10.9.2
typescript               5.4.5
@internal/local-command
@pulumi/command          1.0.1
@pulumi/pulumi           3.134.1
@types/node              18.19.33

Pulumi locates its logs in /var/folders/cz/j76nb6bn7_d8zpph0zvssx940000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

This seems to have come up a couple times on Slack, but none of the suggestions worked for me.

Ref:

- https://archive.pulumi.com/t/23037496/hello-has-anyone-had-success-with-using-custom-component-res
- https://archive.pulumi.com/t/22785832/topic

**Comment by Frassle** [comment]
I think this is because of a mismatch between google-protobuf versions. Seen a similar case in https://github.com/pulumi/pulumi/issues/16714.

Try making sure both the component library and the infra library are locked to using _exactly_ the same version of google-protobuf for now. We'll try to work out why messages are seemingly being sent to the wrong library version when multiple copies are present.

**Comment by notquiteasplanned** [comment]
Thanks for the tip! Tested by `rm -rf node_modules package-lock.json && npm install` to make sure both the component and resource dependencies resolve to the same versions and I'm not getting the error any more.

I had a look at the specific version differences in the `package-lock.json` files and found the following:

| package | resolved component version | resolved infra version |
| --- | --- | --- |
| **@grpc/grpc-js** | **1.11.3** | **1.10.8** |
| @jridgewell/sourcemap-codec | 1.5.0 | 1.4.15 |
| @npmcli/arborist | 7.5.4 | 7.5.2 |
| @npmcli/git | 5.0.8 | 5.0.7 |
| @npmcli/package-json | 5.2.1 | 5.1.0 |
| @npmcli/redact | 2.0.1 | 2.0.0 |
| @types/node | 22.5.5 | 22.7.4 |
| acorn | 8.12.1 | 8.11.3 |
| acorn-walk | 8.3.4 | 8.3.2 |
| ansi-regex | 6.1.0 | 6.0.1 |
| cacache | 18.0.4 | 18.0.3 |
| fdir | 6.3.0 | 6.1.1 |
| foreground-child | 3.3.0 | 3.1.1 |
| glob | 10.4.5 | 10.4.1 |
| **google-protobuf** | **3.21.4** | **3.21.2** |
| https-proxy-agent | 7.0.5 | 7.0.4 |
| is-core-module | 2.15.1 | 2.13.1 |
| jackspeak | 3.4.3 | 3.1.2 |
| lru-cache | 10.4.3 | 10.2.2 |
| minimatch | 9.0.5 | 9.0.4 |
| node-gyp | 10.2.0 | 10.1.0 |
| normalize-package-data | 6.0.2 | 6.0.1 |
| npm-package-arg | 11.0.3 | 11.0.2 |
| npm-pick-manifest | 9.1.0 | 9.0.1 |
| npm-registry-fetch | 17.1.0 | 17.0.1 |
| postcss-selector-parser | 6.1.2 | 6.1.0 |
| promise-call-limit | 3.0.2 | 3.0.1 |
| **protobufjs** | **7.4.0** | **7.3.0** |
| pump | 3.0.2 | 3.0.0 |
| semver | 7.6.3 | 7.6.2 |
| socks-proxy-agent | 8.0.4 | 8.0.3 |
| spdx-license-ids | 3.0.20 | 3.0.18 |
| yocto-queue | 1.1.1 | 1.0.0 |

I'd thought upgrading pulumi to latest would have updated the dependencies as well, but it looks like because they're all defined as caret ranges and so are "compatible" `npm` didn't bother to re-resolve them.

It would be really great to handle multiple instances of different library versions, or if matching versions is actually required it might be worth a more specific version range on the relevant dependencies for the NodeJS SDK.

**Comment by rcarcasses** [comment]
I can confirm that rolling back to `google-protobuf@v3.21.2` and ensure this is the only version installed by making use of the `"resolutions"` field in my main `package.json` solves the issue.

**Comment by newman-dani** [comment]
Any solution here?

**Comment by Frassle** [comment]
Updating the repro program on this ticket to the latest version of pulumi seems to work. N.B. I only updated the package.json in the infra folder, I left the component package on the old version of pulumi.

If anyone can repro this issue on a modern pulumi version do let us know.
