### ISSUE TITLE
Output returning invokes aren't short-circuiting when passed unknown inputs

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#17459]
Minimal repro:

```
mkdir azureinvoke && cd azureinvoke
pulumi new azure-python
```

Replace the content of `__main__.py` with the following:

```python
import pulumi
from pulumi_azure_native import storage
from pulumi_azure_native import resources

resource_group = resources.ResourceGroup("resource_group")

storage_account = storage.StorageAccount(
    "sa",
    resource_group_name=resource_group.name,
    sku={
        "name": storage.SkuName.STANDARD_LRS,
    },
    kind=storage.Kind.STORAGE_V2,
)

sas = storage.list_storage_account_service_sas_output(
    account_name=storage_account.name,
    resource_group_name=resource_group.name)
```

Run `pulumi preview`:

```
$ pulumi preview
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/...

     Type                                     Name             Plan       Info
 +   pulumi:pulumi:Stack                      azureinvoke-dev  create     1 error
 +   ├─ azure-native:resources:ResourceGroup  resource_group   create
 +   └─ azure-native:storage:StorageAccount   sa               create

Diagnostics:
  pulumi:pulumi:Stack (azureinvoke-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/user/.pulumi-dev/bin/pulumi-language-python-exec", line 192, in <module>
        loop.run_until_complete(coro)
      File "/Users/user/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
        return future.result()
      File "/Users/user/Documents/2024/10/02/azureinvoke/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 142, in run_in_stack
        await run_pulumi_func(run)
      File "/Users/user/Documents/2024/10/02/azureinvoke/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 56, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/user/Documents/2024/10/02/azureinvoke/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 118, in wait_for_rpcs
        await task
      File "/Users/user/Documents/2024/10/02/azureinvoke/venv/lib/python3.10/site-packages/pulumi/runtime/invoke.py", line 149, in do_invoke_output
        invoke_result = await _invoke(
      File "/Users/user/Documents/2024/10/02/azureinvoke/venv/lib/python3.10/site-packages/pulumi/runtime/invoke.py", line 306, in wait_for_fut
        return await asyncio.ensure_future(do_rpc())
      File "/Users/user/Documents/2024/10/02/azureinvoke/venv/lib/python3.10/site-packages/pulumi/runtime/invoke.py", line 302, in do_rpc
        raise error
    Exception: invoke of azure-native:storage:listStorageAccountServiceSAS failed: invocation of azure-native:storage:listStorageAccountServiceSAS returned an error: request failed /subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/{resourceGroupName}/providers/Microsoft.Storage/storageAccounts/{accountName}/ListServiceSas: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group '{resourceGroupName}' could not be found."
```

This was using `pulumi` 3.135.0 and `pulumi-azure-native` 2.64.2.

Now switch to an older version of the `pulumi-azure-native` package that does not contain the recent sdkgen changes (https://github.com/pulumi/pulumi/pull/17349):

```
source venv/bin/activate
pip uninstall pulumi-azure-native
pip install pulumi-azure-native==2.63.0
```

Re-running `pulumi preview` succeeds:

```
$ pulumi preview
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/...

     Type                                     Name             Plan
 +   pulumi:pulumi:Stack                      azureinvoke-dev  create
 +   ├─ azure-native:resources:ResourceGroup  resource_group   create
 +   └─ azure-native:storage:StorageAccount   sa               create

Resources:
    + 3 to create
```

**Comment by justinvp** [comment]
There's a test in examples failing: https://github.com/pulumi/examples/actions/runs/11147927160/job/30983403606#step:4:213

And a customer hitting it: https://github.com/pulumi/pulumi-azure-native/issues/3617

**Comment by justinvp** [comment]
Looks like the problem is due to `keep_output_values=True`:

https://github.com/pulumi/pulumi/blob/1e39fa9d0a3a351c338327e05a8b8a2973f4a38d/sdk/python/lib/pulumi/runtime/invoke.py#L226

When that is set to `False`, things work as expected.
