### ISSUE TITLE
TypeError when calling getSchemaRegistryClusterOutput

### ISSUE THREAD

**Issue by williamsbdev** [pulumi/pulumi#17518]
### Describe what happened

We call the function `getSchemaRegistryClusterOutput` in our Pulumi program and when we do so, it throws a TypeError. We started experiencing this issue with the upgrade to 2.4.0 and I verified it's also still broken in 2.5.0.

### Sample program

```
import * as cc from '@pulumi/confluentcloud';

main();

async function main() {
  const confluentEnvironment = new cc.Environment('test', {
    displayName: 'test',
  });

  const schemaRegistryCluster = cc.getSchemaRegistryClusterOutput({
    environment: {
      id: confluentEnvironment.id,
    },
  });
}
```

### Log output

```
Previewing update (kafka):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:kafka::kafka::pulumi:pulumi:Stack::kafka-kafka]
error: Running program '/Users/brandon.williams/kafka/' failed with an unhandled exception:
TypeError: pulumi.runtime.invokeOutput is not a function
    at Object.getSchemaRegistryClusterOutput (/Users/brandon.williams/kafka/node_modules/@pulumi/getSchemaRegistryCluster.ts:161:27)
    at /Users/brandon.williams/kafka/index.ts:60:42
    at Generator.next (<anonymous>)
    at fulfilled (/Users/brandon.williams/kafka/index.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Affected Resource(s)

`getSchemaRegistryClusterOutput` -> data source/function

### Output of `pulumi about`

```
CLI
Version      3.135.1
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME            VERSION
resource  aws             6.54.2
resource  confluentcloud  2.5.0
resource  kafka           3.8.0
language  nodejs          3.135.1-dev.0
resource  random          4.16.6

Host
OS       darwin
Version  14.7
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v21.6.1'

Backend
Name           mm-williamsb2
URL            s3://rs-pulumi-state-bucket
User           brandon.williams
Organizations
Token type     personal

Dependencies:
NAME                    VERSION
@pulumi/aws             6.54.2
@pulumi/confluentcloud  2.5.0
@pulumi/kafka           3.8.0
@pulumi/pulumi          3.135.1
@pulumi/random          4.16.6
@types/jest             29.5.13
@types/node             22.7.4
gts                     5.3.1
jest                    29.7.0
ts-jest                 29.2.5
typescript              5.6.2

Pulumi locates its logs in /var/folders/kl/shdhdl253wvbgy5jh9q76ybw0000gq/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

Thank you in advance for the help in identifying and fixing this issue!

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@williamsbdev Can you try again with `@pulumi/pulumi` set to `3.136.0`?

**Comment by johnnybenson** [comment]
Still seeing this is `3.136.1`

```sh
    TypeError: pulumi.runtime.invokeOutput is not a function
        at Object.getRouteTablesOutput (./node_modules/@pulumi/ec2/getRouteTables.ts:125:27)
```

**Comment by justinvp** [comment]
@johnnybenson, you have 3.136.1 of the `@pulumi/pulumi` npm package installed?

I just tried running `pulumi new aws-typescript` and replaced `index.ts` with:

```typescript
import * as aws from "@pulumi/aws";

const rts = aws.ec2.getRouteTablesOutput();
```

And it ran without issue. From `pulumi about`:

```
Dependencies:
NAME            VERSION
@pulumi/awsx    2.16.1
@pulumi/pulumi  3.136.1
@types/node     18.19.55
typescript      5.6.3
@pulumi/aws     6.55.0
```

**Comment by williamsbdev** [comment]
As of today (10/25/2024), I am running with Pulumi `3.137.0` and I am seeing the issue has been fixed!

Thank you for your help in resolving this issue.
