### ISSUE TITLE
Cannot expose resources retrieved with `.get` across MLC component boundaries

### ISSUE THREAD

**Issue by flostadler** [pulumi/pulumi#17515]
### What happened?

In https://github.com/pulumi/pulumi-eks we wanted to expose a resource retrieved with `.get` as an output of an MLC (`Component A`).
This worked, but another component (`Component B`) takes `Component A` as an input. The `construct` call for `Component B` started to fail after doing this with an error message about not finding the resource retrieved with `.get`:
```
Error: failed to register new resource al-2023-mng [eks:index:ManagedNodeGroup]: 2 UNKNOWN: invocation of pulumi:pulumi:getResource returned an error: unknown resource urn:pulumi:p-it-florians-m-skip-defau-54544e4b::skip-default-security-groups::eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::skip-default-sg-mng-eksClusterSecurityGroup
    at Object.registerResource (/Users/flo/development/pulumi-eks/sdk/nodejs/node_modules/@pulumi/runtime/resource.ts:509:27)
    at new Resource (/Users/flo/development/pulumi-eks/sdk/nodejs/node_modules/@pulumi/resource.ts:556:13)
    at new ComponentResource (/Users/flo/development/pulumi-eks/sdk/nodejs/node_modules/@pulumi/resource.ts:1228:9)
    at new ManagedNodeGroup (/Users/flo/development/pulumi-eks/sdk/nodejs/managedNodeGroup.ts:75:9)
```

I was able to reproduce this with a minimal MLC provider: https://github.com/flostadler/pulumi-get-function-across-mlc-repro (also includes GRPC logs). The same thing does not happen when using regular components, so it seems to be related to MLCs.

### Example

https://github.com/flostadler/pulumi-get-function-across-mlc-repro

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jdavredbeard** [comment]
I was able to reproduce this error in a slightly different but related situation:

If you have a role deployed:

```
import * as eks from "@pulumi/eks";
import * as aws from "@pulumi/aws"

export const role = aws.iam.Role.get("role", "<role-name>") 

const cluster = new eks.Cluster("cluster", {
    serviceRole: role,
});
```

Error:
``` pulumi:pulumi:Stack (pulumi-17515-dev):
    error: eks:index:Cluster resource 'cluster' has a problem: invocation of pulumi:pulumi:getResource returned an error: unknown resource urn:pulumi:dev::pulumi-17515::aws:iam/role:Role::role
    error: Error: invocation of pulumi:pulumi:getResource returned an error: unknown resource urn:pulumi:dev::pulumi-17515::aws:iam/role:Role::role
        at Object.callback (/snapshot/eks/node_modules/@pulumi/pulumi/runtime/resource.js:100:36)
        at Object.onReceiveStatus (/snapshot/eks/node_modules/@grpc/grpc-js/src/client.ts:360:26)
        at Object.onReceiveStatus (/snapshot/eks/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
        at Object.onReceiveStatus (/snapshot/eks/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
        at /snapshot/eks/node_modules/@grpc/grpc-js/src/resolving-call.ts:163:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)

    Error: invocation of pulumi:pulumi:getResource returned an error: unknown resource urn:pulumi:dev::pulumi-17515::aws:iam/role:Role::role: Error: invocation of pulumi:pulumi:getResource returned an error: unknown resource urn:pulumi:dev::pulumi-17515::aws:iam/role:Role::role
        at Object.callback (/snapshot/eks/node_modules/@pulumi/pulumi/runtime/resource.js:100:36)
        at Object.onReceiveStatus (/snapshot/eks/node_modules/@grpc/grpc-js/src/client.ts:360:26)
        at Object.onReceiveStatus (/snapshot/eks/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
        at Object.onReceiveStatus (/snapshot/eks/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
        at /snapshot/eks/node_modules/@grpc/grpc-js/src/resolving-call.ts:163:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)```

about:
```CLI          
Version      3.138.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.59.0
resource  eks         3.0.1
resource  kubernetes  4.18.3
language  nodejs      unknown

Host     
OS       darwin
Version  14.4
Arch     arm64

This project is written in nodejs: executable='/Users/jdavenport/.nvm/versions/node/v18.20.4/bin/node' version='v18.20.4'

Current Stack: organization/pulumi-17515/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           jdavenports-MacBook-Pro.local
URL            <url>
User           jdavenport
Organizations  
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/aws     6.59.0
@pulumi/eks     3.0.1
@pulumi/pulumi  3.138.0
@types/node     18.19.64
typescript      5.6.3

Pulumi locates its logs in /var/folders/68/1bv_wkxd4fgf81z7l3r37yy40000gn/T/ by default
```

**Comment by EvgeniiIakubov** [comment]
I got the same error too
