### ISSUE TITLE
Python - create a resource_name from the properties of the another resources.

### ISSUE THREAD

**Issue by denists1984** [pulumi/pulumi#17527]
Hi All

Having an issue when trying to dynamically assemble(concatenate) resource_name from another resources properties when running `pulumi preview` for the newly created stack that suppose to create VPC(subnets/RTs, ets) on AWS.

The [expected type](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/functions/concat.html) of the :
`nat_gtw_eip_name = pulumi.Output.concat("nat-gtw-eip", "-", vpc_ref.id)`
 is :
`nat_gtw_eip_name type: <class 'pulumi.output.Output'>`

In order to get a string the pulumi AI suggests to use the `.apply` method.
Processing the `nat_gtw_eip_name` through the`.apply` method into a variable `eip_name` didn't  work:

code sample
```
nat_gtw_eip_name = pulumi.Output.concat("nat-gtw-eip", "-", vpc_ref.id)

eip_name = nat_gtw_eip_name.apply(lambda name: print(f"{name}" or "blah"))

print('eip_name type: ', type(eip_name))

pulumi.export('eip_name_pulumi_export', eip_name)

nat_gtw_eip = ec2.Eip(eip_name,
                             domain=vpc_ref.id,
                             tags=Helper().create_resource_tags(nat_gtw_eip_name, self.conf))
```

The print type `eip_name` (from the code sample above) returns:
```
eip_name type:  <class 'pulumi.output.Output'>
```

The pulumi export `eip_name`(from the code sample above) returns:
```
eip_name_pulumi_export   : output<string>
```

 and the `TypeError` for the resource_name:
```  
error: Program failed with an unhandled exception:
Traceback (most recent call last):
  File "/cloud-pulumi/aws-resources/vpc/__main__.py", line 16, in <module>
    main()
  File "/cloud-pulumi/aws-resources/vpc/__main__.py", line 12, in main
    CreateVpc().runner()
  File "/cloud-pulumi/aws-resources/vpc/create_vpc.py", line 229, in runner
    nat_gtw_eip_ref = self.create_nat_gtw_elastic_ip(vpc_ref)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cloud-pulumi/aws-resources/vpc/create_vpc.py", line 130, in create_nat_gtw_elastic_ip
    nat_gtw_eip = ec2.Eip(eip_name,
                  ^^^^^^^^^^^^^^^^^
  File "/cloud-pulumi/.venv/lib/python3.12/site-packages/pulumi_aws/ec2/eip.py", line 795, in __init__
    __self__._internal_init(resource_name, *args, **kwargs)
  File "/cloud-pulumi/.venv/lib/python3.12/site-packages/pulumi_aws/ec2/eip.py", line 840, in _internal_init
    super(Eip, __self__).__init__(
  File "/cloud-pulumi/.venv/lib/python3.12/site-packages/pulumi/resource.py", line 1139, in __init__
    Resource.__init__(
  File "/cloud-pulumi/.venv/lib/python3.12/site-packages/pulumi/resource.py", line 873, in __init__
    raise TypeError("Expected resource name to be a string")
TypeError: Expected resource name to be a string
```

I have tried to convert the `resouce_name` attribute in to a string during the `ec2.Eip` call  :
```
nat_gtw_eip_name = pulumi.Output.concat("nat-gtw-eip", "-", vpc_ref.id)

eip_name = nat_gtw_eip_name.apply(lambda name: print(f"{name}" or "blah"))

nat_gtw_eip = ec2.Eip(str(eip_name),
                     domain=vpc_ref.id,
                     tags=Helper().create_resource_tags(nat_gtw_eip_name, self.conf))
```

then the error message was just converted into a string as a resource_name and applied to the resource URN :
```
urn : "urn:pulumi:cie-1::vpc::aws:ec2/eip:Eip::Calling __str__ on an Output[T] is not supported.\n\nTo get the value of an Output[T] as an Output[str] consider:\n1. o.apply(lambda v: f\"prefix{v}suffix\")\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\nThis function may throw in a future version of Pulumi
```

Also i have tried to use  the `.apply` method as a resource_name parameters when calling the  `ec2.Eip`:
```
nat_gtw_eip_name = pulumi.Output.concat("nat-gtw-eip", "-", vpc_ref.id)

nat_gtw_eip = ec2.Eip(nat_gtw_eip_name.apply(lambda name: print(f"{name}" or "blah")),
                     domain=vpc_ref.id,
                     tags=Helper().create_resource_tags(nat_gtw_eip_name, self.conf))
```

And still getting the TypeError:
```
error: Program failed with an unhandled exception:
Traceback (most recent call last):
  File "/cloud-pulumi/aws-resources/vpc/__main__.py", line 16, in <module>
    main()
  File "/cloud-pulumi/aws-resources/vpc/__main__.py", line 12, in main
    CreateVpc().runner()
  File "/cloud-pulumi/aws-resources/vpc/create_vpc.py", line 223, in runner
    nat_gtw_eip_ref = self.create_nat_gtw_elastic_ip(vpc_ref)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cloud-pulumi/aws-resources/vpc/create_vpc.py", line 124, in create_nat_gtw_elastic_ip
    nat_gtw_eip = ec2.Eip(nat_gtw_eip_name.apply(lambda name: print(f"{name}" or "blah")),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cloud-pulumi/.venv/lib/python3.12/site-packages/pulumi_aws/ec2/eip.py", line 795, in __init__
    __self__._internal_init(resource_name, *args, **kwargs)
  File "/cloud-pulumi/.venv/lib/python3.12/site-packages/pulumi_aws/ec2/eip.py", line 840, in _internal_init
    super(Eip, __self__).__init__(
  File "/cloud-pulumi/.venv/lib/python3.12/site-packages/pulumi/resource.py", line 1139, in __init__
    Resource.__init__(
  File "/cloud-pulumi/.venv/lib/python3.12/site-packages/pulumi/resource.py", line 873, in __init__
    raise TypeError("Expected resource name to be a string")
TypeError: Expected resource name to be a string
```

Pulumi version: v3.135.1
Language : Python
Execution: `pulumi preview` locally on macos
Stack status: newly created
Pulumi AI related questions:
1. string concatenate of vpc.id and subnet.id
2. Expected type 'str', got 'Output[str]' instead
3. still getting the "TypeError: Expected resource name to be a string"

**Comment by justinvp** [comment]
> Having an issue when trying to dynamically assemble(concatenate) resource_name from another resources properties

`resource_name` must be a plain string. You can't create it based on other resource output properties that are typed as `Output[T]`. However, you can use another resource's `name` property, which is also a plain string.

```python
nat_gtw_eip_name = f"nat-gtw-eip-{vpc_ref.name}" # assuming `vpc_ref` is a resource
```

**Comment by denists1984** [comment]
Thank you @justinvp , it worked with the `_name`.

```
nat_gtw_eip_name = f"nat-gtw-eip-{vpc_ref.name}"
                                          ^^^^^^^^^^^^
AttributeError: 'Vpc' object has no attribute 'name'. Did you mean: '_name'?
```

In a meanwhile was trying to access the VPC tags when i assumed the Tag will be a Key,Value of strings.
Wich seems like now the case as well.

Do you have a plans to introduce method/plugin that will convert any resource property to a string ?
That would be very helpful to introduce unique names for the resources based on their usage and belonging (for example: "public-subnet-1-VPC-12345" or "eip-instance-id").

**Comment by lunaris** [comment]
Closing this as I think it's by-design. To respond to the follow-up question (which seems to have gone stale; apologies) -- I don't believe we will ever have the ability to convert an arbitrary property to a string. Properties are generally `Output`s as you mention, and since an `Output` is "eventual" (that is, it won't necessarily be known immediately -- only when the resource it belongs to has been fully created/updated/realised), it's not in general possible to convert it to a "plain" (always available) `str`. Hope that makes sense 🙏
