### ISSUE TITLE
The Pulumi CLI encountered a snapshot integrity error

### ISSUE THREAD

**Issue by phutm** [pulumi/pulumi#17554]
### What happened?
```
[2024:10:15 09:37:47] fail: Scloud Unhandled exception:  Pulumi.Automation.Commands.Exceptions.CommandException: code: -1 stdout:  stderr: error: The Pulumi CLI encountered a snapshot integrity error. This is a bug!

================================================================================
We would appreciate a report: https://github.com/pulumi/pulumi/issues/

NOTE: This error occurred while reading a snaphot. This error was introduced by
a previous operation when it wrote the snapshot. If you have details about that
operation, please include them in your report as well.

Please provide all of the text below in your report.
================================================================================

**Stack Trace:**

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.23.2/x64/src/runtime/debug/stack.go:26 +0x5e
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x3542f1f?, 0x86?}, {0xc0026e5888?, 0x86?, 0x40?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:611 +0x34
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0xc0021825a0)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:497 +0x1053
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getSnapshot(0x5328fc0?, {0x3c554a8, 0x5328fc0}, {0x3c30da0, 0x5328fc0}, {0x3c55a00?, 0xc001fbf990?})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:229 +0xa5
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Snapshot(0xc00218cb60, {0x3c554a8, 0x5328fc0}, {0x3c30da0, 0x5328fc0})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:151 +0xdb
main.(*stackOutputCmd).Run(0xc0009b5a90, {0x3c554a8, 0x5328fc0}, {0xc001ff4e40, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/stack_output.go:127 +0x3a3
main.newStackOutputCmd.func1(0x0?, {0xc001ff4e40?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/stack_output.go:51 +0x3c
main.newStackOutputCmd.runCmdFunc.func2(0x0?, {0xc001ff4e40?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:45 +0x1c
main.newStackOutputCmd.runCmdFunc.RunFunc.func5(0xc002010008, {0xc001ff4e40, 0x0, 0x4})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x3b
github.com/spf13/cobra.(*Command).execute(0xc002010008, {0xc001ff4e00, 0x4, 0x4})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0xc0011d9b08)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x4e
```

### Example

We have an automation api program that doing some Pulumi operations. 
```
at Pulumi.Automation.Commands.LocalPulumiCommand.RunAsyncInner(IList`1 args, String workingDir, IDictionary`2 additionalEnv, Action`1 onStandardOutput, Action`1 onStandardError, EventLogFile eventLogFile, CancellationToken cancellationToken)    at Pulumi.Automation.Commands.LocalPulumiCommand.RunAsync(IList`1 args, String workingDir, IDictionary`2 additionalEnv, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)    at Pulumi.Automation.LocalWorkspace.GetStackOutputsAsync(String stackName, CancellationToken cancellationToken)
```
### Output of `pulumi about`
```
Pulumi Version:    v3.136.1
Go Version:        go1.23.2
Go Compiler:       gc
Architecture:      amd64
Operating System:  windows
Command:           pulumi stack output --json --stack sinequacloud/eaus-02-dev.phu0.p0 --non-interactive
Error:             snapshot integrity failure; refusing to use it: resource urn:pulumi:eaus-02-dev.phu0.p0::sinequa-grid::Sinequa:CustomGrid$sinequa:Node$azure-native:network:NetworkInterface::phu0-p0-n1-nic's dependency urn:pulumi:eaus-02-dev.phu0.p0::sinequa-grid::Sinequa:CustomGrid$azure-native:network:LoadBalancerBackendAddressPool::phu0-p0-ilb-beap comes after it
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Hi @phutm, thanks for opening the issue and sorry for the trouble!

Do you have any more details on the previous operation that was performed? That will help us track down what caused the problem.

To fix your stack, we recently shipped a new `pulumi state repair` command that you could try running.

**Comment by phutm** [comment]
Hi Justin,

It is quite hard to get that detail since it is a development stack and
it’s been a few weeks from when the last update was done.

Usually, we do pulumi refresh and then pulumi up in our automation api and
it only happens with 2 of my stacks.

Regards,
Phu Tran

**Comment by lunaris** [comment]
Discussed with the customer and we think this could be an older version. They are happy to close this as no reproduction for now so doing so.
