### ISSUE TITLE
Simplest example of pulumi automation is complaining about "no Pulumi.yaml project file"

### ISSUE THREAD

**Issue by alfred-stokespace** [pulumi/pulumi#17572]
### What happened?

I have an existing project that is functioning fine and uses the same APIs. So, call me confused when I tried creating a super simple new TS project using the same API and I get the following error...

```
 pulumi:pulumi:Stack (mgmt-reports):
    error: CommandError: code: -2
     stdout:
     stderr: Command failed with exit code 255: pulumi stack ls --json --non-interactive
    error: could not detect current project: no Pulumi.yaml project file found (searching upwards from /tmp/automation-BsFzlp). If you have not created a project yet, use `pulumi new` to do so: no project file found
     err?: Error: Command failed with exit code 255: pulumi stack ls --json --non-interactive
    error: could not detect current project: no Pulumi.yaml project file found (searching upwards from /tmp/automation-BsFzlp). If you have not created a project yet, use `pulumi new` to do so: no project file found

        at Object.createCommandError (/depot/pulumi/mgmt/node_modules/@pulumi/automation/errors.ts:82:17)
        at /depot/pulumi/mgmt/node_modules/@pulumi/automation/cmd.ts:225:15
        at Generator.throw (<anonymous>)
        at rejected (/depot/pulumi/mgmt/node_modules/@pulumi/pulumi/automation/cmd.js:19:65)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Example

```
/depot/pulumi-auto$ p new
 Would you like to create a project from a template or using a Pulumi AI prompt? template
Please choose a template (219 total):
 typescript                         A minimal TypeScript Pulumi program
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

Project name (pulumi-auto):
Project description (A minimal TypeScript Pulumi program):
Created project 'pulumi-auto'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
Stack name (dev):
Created stack 'dev'

The package manager to use for installing dependencies npm
Installing dependencies...


added 294 packages, and audited 295 packages in 8s

43 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Finished installing dependencies

Your new project is ready to go!

To perform an initial deployment, run `pulumi up`
```

I then put the following code into index.ts
```
import * as pulumi from "@pulumi/pulumi";
import {LocalWorkspace} from "@pulumi/pulumi/automation";


const wkspc = LocalWorkspace.create({});

wkspc.then(w => {
    w.listStacks().then(stacks => {
        stacks.forEach(stack => {
            pulumi.log.info(`Looking at stack ${stack.name}`)            
        })
    })
})
```

and I get ...

```
Diagnostics:
  pulumi:pulumi:Stack (pulumi-auto-dev):
    error: CommandError: code: -2
     stdout:
     stderr: Command failed with exit code 255: pulumi stack ls --json --non-interactive
    error: could not detect current project: no Pulumi.yaml project file found (searching upwards from /tmp/automation-vdpLQf). If you have not created a project yet, use `pulumi new` to do so: no project file found
     err?: Error: Command failed with exit code 255: pulumi stack ls --json --non-interactive
    error: could not detect current project: no Pulumi.yaml project file found (searching upwards from /tmp/automation-vdpLQf). If you have not created a project yet, use `pulumi new` to do so: no project file found

        at Object.createCommandError (/depot/pulumi-auto/node_modules/@pulumi/automation/errors.ts:82:17)
        at /depot/pulumi-auto/node_modules/@pulumi/automation/cmd.ts:225:15
        at Generator.throw (<anonymous>)
        at rejected (/depot/pulumi-auto/node_modules/@pulumi/pulumi/automation/cmd.js:19:65)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Output of `pulumi about`

```
CLI
Version      3.136.1
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/REDACTED/.nvm/versions/node/v18.20.1/bin/node' version='v18.20.1'

Current Stack: REDACTED/pulumi-auto/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/REDACTED
User           REDACTED
Organizations  REDACTED
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.136.1
@types/node     18.19.56
typescript      5.6.3

Pulumi locates its logs in /tmp by default
```

### Additional context

What's odd is that I have a working project that is able to run the same code just fine.

the working project has this package.json
```
{
    "name": "dns",
    "devDependencies": {
        "@types/node": "^18"
    },
    "dependencies": {
        "@pulumi/aws": "^5",
        "@pulumi/awsx": "^0.40.0",
        "@pulumi/pulumi": "^3"
    }
}
```
I have the same code from the example and I get what I expect from the log line, lots and lots of stacks printed out.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@alfred-stokespace, I think you're missing specifying the working directory that contains the `Pulumi.yaml` file, e.g. 

```typescript
const wkspc = LocalWorkspace.create({ workDir: "." });
```

**Comment by alfred-stokespace** [comment]
Yes, that does indeed change things.  thank you @justinvp 

Before we/I close this issue I think there is more here than just me not reading the docs. It would seem this api for LocalWorkspace is lacking a "pit of success".  The doc https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi.Automation/Pulumi.Automation.LocalWorkspace.html#Pulumi_Automation_LocalWorkspace_WorkDir doesn't give advance warning about the significance of this argument
```
export interface LocalWorkspaceOptions {
    /**
     * The directory to run Pulumi commands and read settings (`Pulumi.yaml` and
     * `Pulumi.<stack>.yaml`).
     */
    workDir?: string;
```
It is optional... perhaps I should put two and two together and realized that the error message was mentioning the Pulumi.yaml file.
  
I get that it probably has to be optional in order for other use cases to be possible, still not a pit-of-success. 

When I used Pulumi AI to generate some code it gave the following...
```
    // Create or select an existing stack
    const stack = await LocalWorkspace.createOrSelectStack({
        stackName: "dev",
        projectName: "my-project",
        program: pulumiProgram,
    });
```
So, when I subtracted the things I didn't want, I was left with...

```
    // Create or select an existing stack
    const stack = await LocalWorkspace.createOrSelectStack({});
```
Which as you pointed out doesn't work.

Seems like a simple thing to check for.  ie. if LocalWorkspaceOptions has no defined attributes an error message that explains more would be super helpful. 

What's also puzzling is comparing how my other project is succeeding....
it was doing `const wkspc = LocalWorkspace.create({projectSettings: {name: projectName, runtime: "nodejs"}});`

So clearly there is no need in that case for `workDir` since that allowed the `listStacks` code to iterate through all the stacks that fit criteria. 

What I was really after with my attempt to do `LocalWorkspace.createOrSelectStack({});`, was -- "how do I iterate through all stacks in my org by using the pulumiservice package?"

I can see now that even with `workDir` populated with "." I don't get any stacks back  with listStacks function.

Oh well, I ended up moving on and just using the REST API anyways. 

Was pulumiservice package intended for my use case in the first place?
