### ISSUE TITLE
Error in Python SDK when running `stack.up`

### ISSUE THREAD

**Issue by fubuloubu** [pulumi/pulumi#17588]
### What happened?

Still trying to debug if there is a local problem with my setup, but at the very least this seems like a bug that should be caught and raised in a more graceful way (which would help me debug)

### Example

```
Traceback (most recent call last):
  File "site-packages/silverback_cluster_infra/__init__.py", line 234, in blocking_up
    result = stack.up(on_event=on_event, on_output=on_output)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/pulumi/automation/_stack.py", line 374, in up
    up_result = self._run_pulumi_cmd_sync(args, on_output)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/pulumi/automation/_stack.py", line 990, in _run_pulumi_cmd_sync
    result = self.workspace.pulumi_command.run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/pulumi/automation/_cmd.py", line 238, in run
    raise create_command_error(result)
pulumi.automation.errors.InlineSourceRuntimeError:
 code: 255
 stdout: Updating (test-490dca):
@ updating.......
    pulumi:pulumi:Stack fubuloubu-test-490dca running error: python inline source runtime error: 'Loop' object has no attribute '_ready'
    pulumi:pulumi:Stack fubuloubu-test-490dca running error: an unhandled error occurred: python inline source runtime error: 'Loop' object has no attribute '_ready'
    pulumi:pulumi:Stack fubuloubu-test-490dca **failed** 2 errors
Diagnostics:
  pulumi:pulumi:Stack (fubuloubu-test-490dca):
    error: python inline source runtime error: 'Loop' object has no attribute '_ready'
        Traceback (most recent call last):
      File "site-packages/pulumi/automation/_server.py", line 80, in run
        loop.run_until_complete(run_in_stack(self.program))
      File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
      File "site-packages/pulumi/runtime/stack.py", line 142, in run_in_stack
        await run_pulumi_func(run)
      File "site-packages/pulumi/runtime/stack.py", line 54, in run_pulumi_func
        func()
      File "site-packages/pulumi/runtime/stack.py", line 139, in run
        Stack(func)
      File "site-packages/pulumi/runtime/stack.py", line 168, in __init__
        awaitable = func()
                    ^^^^^^
      File "site-packages/silverback_cluster_infra/cluster/main.py", line 31, in build_cluster_stack
        context = get_context()
                  ^^^^^^^^^^^^^
      File "site-packages/silverback_cluster_infra/cluster/context.py", line 46, in get_context
        caller=get_caller_identity(),
               ^^^^^^^^^^^^^^^^^^^^^
      File "site-packages/pulumi_aws/get_caller_identity.py", line 112, in get_caller_identity
        __ret__ = pulumi.runtime.invoke('aws:index/getCallerIdentity:getCallerIdentity', __args__, opts=opts, typ=GetCallerIdentityResult).value
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "site-packages/pulumi/runtime/invoke.py", line 121, in invoke
        return _sync_await(awaitableInvokeResult)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "site-packages/pulumi/runtime/sync_await.py", line 49, in _sync_await
        ntodo = len(loop._ready)  # type: ignore
                    ^^^^^^^^^^^
    AttributeError: 'Loop' object has no attribute '_ready'
    error: an unhandled error occurred: python inline source runtime error: 'Loop' object has no attribute '_ready'
    Traceback (most recent call last):
      File "site-packages/pulumi/automation/_server.py", line 80, in run
        loop.run_until_complete(run_in_stack(self.program))
      File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
      File "site-packages/pulumi/runtime/stack.py", line 142, in run_in_stack
        await run_pulumi_func(run)
      File "site-packages/pulumi/runtime/stack.py", line 54, in run_pulumi_func
        func()
      File "site-packages/pulumi/runtime/stack.py", line 139, in run
        Stack(func)
      File "site-packages/pulumi/runtime/stack.py", line 168, in __init__
        awaitable = func()
                    ^^^^^^
      File "site-packages/silverback_cluster_infra/cluster/main.py", line 31, in build_cluster_stack
        context = get_context()
                  ^^^^^^^^^^^^^
      File "site-packages/silverback_cluster_infra/cluster/context.py", line 46, in get_context
        caller=get_caller_identity(),
               ^^^^^^^^^^^^^^^^^^^^^
      File "site-packages/pulumi_aws/get_caller_identity.py", line 112, in get_caller_identity
        __ret__ = pulumi.runtime.invoke('aws:index/getCallerIdentity:getCallerIdentity', __args__, opts=opts, typ=GetCallerIdentityResult).value
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "site-packages/pulumi/runtime/invoke.py", line 121, in invoke
              return _sync_await(awaitableInvokeResult)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "site-packages/pulumi/runtime/sync_await.py", line 49, in _sync_await
        ntodo = len(loop._ready)  # type: ignore
                    ^^^^^^^^^^^
    AttributeError: 'Loop' object has no attribute '_ready'
    error: an unhandled error occurred: python inline source runtime error: 'Loop' object has no attribute '_ready'
    Traceback (most recent call last):
      File "site-packages/pulumi/automation/_server.py", line 80, in run
        loop.run_until_complete(run_in_stack(self.program))
      File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
      File "site-packages/pulumi/runtime/stack.py", line 142, in run_in_stack
        await run_pulumi_func(run)
      File "site-packages/pulumi/runtime/stack.py", line 54, in run_pulumi_func
        func()
      File "site-packages/pulumi/runtime/stack.py", line 139, in run
        Stack(func)
      File "site-packages/pulumi/runtime/stack.py", line 168, in __init__
        awaitable = func()
                    ^^^^^^
      File "site-packages/silverback_cluster_infra/cluster/main.py", line 31, in build_cluster_stack
        context = get_context()
                  ^^^^^^^^^^^^^
      File "site-packages/silverback_cluster_infra/cluster/context.py", line 46, in get_context
        caller=get_caller_identity(),
               ^^^^^^^^^^^^^^^^^^^^^
      File "site-packages/pulumi_aws/get_caller_identity.py", line 112, in get_caller_identity
        __ret__ = pulumi.runtime.invoke('aws:index/getCallerIdentity:getCallerIdentity', __args__, opts=opts, typ=GetCallerIdentityResult).value
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "site-packages/pulumi/runtime/invoke.py", line 121, in invoke
        return _sync_await(awaitableInvokeResult)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "site-packages/pulumi/runtime/sync_await.py", line 49, in _sync_await
        ntodo = len(loop._ready)  # type: ignore
                    ^^^^^^^^^^^
    AttributeError: 'Loop' object has no attribute '_ready'
Resources:
    1 unchanged
Duration: 5s
 stderr:
```

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.136.1
Go Version   go1.23.2
Go Compiler  gc

Host     
OS       fedora
Version  40
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/fubuloubu
User           fubuloubu
Organizations  fubuloubu, ApeWorX
Token type     personal

Dependencies:
NAME                      VERSION
mypy                      1.12.1
pip                       24.2
ruff                      0.6.9
setuptools-scm            8.1.0
silverback_cluster_infra  0.2.1

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

Link to affected code
https://github.com/pulumi/pulumi/blob/fd07f42c6116ea9685b24ca35ba5832994196fc5/sdk/python/lib/pulumi/runtime/sync_await.py#L41-L49

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@fubuloubu, what version of python are you using?

**Comment by fubuloubu** [comment]
> @fubuloubu, what version of python are you using?

3.11

**Comment by justinvp** [comment]
This looks suspicious:

```
File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
```

Is https://github.com/MagicStack/uvloop being used?

**Comment by fubuloubu** [comment]
> This looks suspicious:
> 
> ```
> File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
> ```
> 
> Is https://github.com/MagicStack/uvloop being used?

We are using pulumi to deploy stuff behind a FastAPI service (inside of a Background Task) using uvicorn, which I believe uses uvloop to run the service

**Comment by fubuloubu** [comment]
@justinvp were you able to reproduce? this is blocking me, so I can help find a MWE if needed

**Comment by justinvp** [comment]
I haven't repro'd it yet, but it's almost certainly due to the use of uvloop over the standard asyncio loop, since we are calling some internals on the asyncio loop.

We'll look into whether we can support running with uvloop.

It looks like there's a uvicorn setting to use the asyncio loop: https://www.uvicorn.org/settings/#implementation

> `--loop <str>` - Set the event loop implementation. The uvloop implementation provides greater performance, but is not compatible with Windows or PyPy. **Options:** _'auto'_, _'asyncio'_, _'uvloop'_. **Default:** _'auto'_.

Wondering if that could be used to workaround in the meantime.
