### ISSUE TITLE
Alias plus deletedWith leads to Snapshot Integrity Error

### ISSUE THREAD

**Issue by fritz-k** [pulumi/pulumi#17614]
### What happened?

Moving resources to another `ComponentResource` via an `Alias` leads to a corrupted state if one of these resources is the target of a `deletedWith`.

In my case the resource containing the `deletedWith` is being moved as well, not sure if this issue is also triggered if that resource isn't being moved.

### Initial program

The initial program
```python
"""A dummy Pulumi program"""

import pulumi
from pulumi_command import local


class OriginalParent(pulumi.ComponentResource):
    def __init__(self) -> None:
        super().__init__("component:original", "test", None, None)

        mkdir = local.Command(
            "mkdir",
            create="mkdir dir1",
            opts=pulumi.ResourceOptions(
                parent=self,
            ),
        )

        write_dir = local.Command(
            "write_dir",
            create="touch dir1/file2",
            opts=pulumi.ResourceOptions(
                parent=self,
                deleted_with=mkdir,
            ),
        )


class NewParent(pulumi.ComponentResource):
    def __init__(self, old_parent: pulumi.ComponentResource) -> None:
        super().__init__("component:moved", "test", None, None)


original_parent = OriginalParent()
new_parent = NewParent(original_parent)
```
correctly creates the resources:
```bash
Previewing update (tst_local):

 +  pulumi:pulumi:Stack tst_local-tst_local create 
 +  component:original test create 
 +  component:moved test create 
 +  command:local:Command mkdir create 
 +  command:local:Command write_dir create 
 +  pulumi:pulumi:Stack tst_local-tst_local create 
Resources:
    + 5 to create

Updating (tst_local):

 +  pulumi:pulumi:Stack tst_local-tst_local creating (0s) 
 +  component:original test creating (0s) 
 +  component:moved test creating (0s) 
 +  command:local:Command mkdir creating (0s) 
 +  command:local:Command mkdir created (0.02s) 
 +  command:local:Command write_dir creating (0s) 
 +  command:local:Command write_dir created (0.02s) 
 +  pulumi:pulumi:Stack tst_local-tst_local created (0.11s) 
 +  component:original test created 
 +  component:moved test created 
Resources:
    + 5 created

Duration: 1s
```

### Move both resources via `Alias`
Adjusting the code to move resources to another `ComponentResource`
```python
"""A dummy Pulumi program"""

import pulumi
from pulumi_command import local


class OriginalParent(pulumi.ComponentResource):
    def __init__(self) -> None:
        super().__init__("component:original", "test", None, None)


class NewParent(pulumi.ComponentResource):
    def __init__(self, old_parent: pulumi.ComponentResource) -> None:
        super().__init__("component:moved", "test", None, None)

        mkdir = local.Command(
            "mkdir",
            create="mkdir dir1",
            opts=pulumi.ResourceOptions(
                parent=self,
                aliases=[pulumi.Alias(parent=old_parent)],
            ),
        )

        write_dir = local.Command(
            "write_dir",
            create="touch dir1/file2",
            opts=pulumi.ResourceOptions(
                parent=self,
                deleted_with=mkdir,
                aliases=[pulumi.Alias(parent=old_parent)],
            ),
        )


original_parent = OriginalParent()
new_parent = NewParent(original_parent)
```
shows a proper preview (moving via `Alias` doesn't show up in `preview` in general),
```bash
Previewing update (tst_local):

    pulumi:pulumi:Stack tst_local-tst_local  
Resources:
    5 unchanged
```
but the `up` fails with a snapshot integrity error
```bash
Previewing update (tst_local):

    pulumi:pulumi:Stack tst_local-tst_local  
Resources:
    5 unchanged

Updating (tst_local):

    command:local:Command mkdir **failed** error: post-step event returned an error: failed to save snapshot: .pulumi/stacks/tst_local/tst_local.json: snapshot integrity failure; it was already written, but is invalid (backup available at .pulumi/stacks/tst_local/tst_local.json.bak): resource urn:pulumi:tst_local::tst_local::component:original$command:local:Command::write_dir is specified as being deleted with urn:pulumi:tst_local::tst_local::component:original$command:local:Command::mkdir, which is missing
    pulumi:pulumi:Stack tst_local-tst_local running error: update failed
    pulumi:pulumi:Stack tst_local-tst_local **failed** 1 error
Diagnostics:
  pulumi:pulumi:Stack (tst_local-tst_local):
    error: update failed

  command:local:Command (mkdir):
    error: post-step event returned an error: failed to save snapshot: .pulumi/stacks/tst_local/tst_local.json: snapshot integrity failure; it was already written, but is invalid (backup available at .pulumi/stacks/tst_local/tst_local.json.bak): resource urn:pulumi:tst_local::tst_local::component:original$command:local:Command::write_dir is specified as being deleted with urn:pulumi:tst_local::tst_local::component:original$command:local:Command::mkdir, which is missing

Resources:
    4 unchanged

Duration: 1s

error: The Pulumi CLI encountered a snapshot integrity error. This is a bug!

================================================================================
We would appreciate a report: https://github.com/pulumi/pulumi/issues/

Please provide all of the text below in your report.
================================================================================
Pulumi Version:    v3.137.0
Go Version:        go1.23.2
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin
Command:           pulumi up --yes
Error:             writing snapshot: failed to save snapshot: .pulumi/stacks/tst_local/tst_local.json: snapshot integrity failure; it was already written, but is invalid (backup available at .pulumi/stacks/tst_local/tst_local.json.bak): resource urn:pulumi:tst_local::tst_local::component:original$command:local:Command::write_dir is specified as being deleted with urn:pulumi:tst_local::tst_local::component:original$command:local:Command::mkdir, which is missing

Stack Trace:

goroutine 302 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.23.2/libexec/src/runtime/debug/stack.go:26 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x104ae6b43?, 0x50?}, {0x14001ecbd48?, 0x50?, 0x40?})
        /private/tmp/pulumi-20241017-5200-awxgm2/pkg/resource/deploy/snapshot.go:611 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x140027201e0)
        /private/tmp/pulumi-20241017-5200-awxgm2/pkg/resource/deploy/snapshot.go:536 +0xba4
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).saveStack(0x140013b27e0, {0x1058b2748, 0x106ed9c80}, 0x14001680140, 0x140027201e0)
        /private/tmp/pulumi-20241017-5200-awxgm2/pkg/backend/diy/state.go:315 +0x108
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diySnapshotPersister).Save(0x14002720140?, 0x140028223f0?)
        /private/tmp/pulumi-20241017-5200-awxgm2/pkg/backend/diy/snapshot.go:35 +0x38
github.com/pulumi/pulumi/pkg/v3/backend.(*SnapshotManager).saveSnapshot(0x140021c5b00)
        /private/tmp/pulumi-20241017-5200-awxgm2/pkg/backend/snapshot.go:680 +0x84
github.com/pulumi/pulumi/pkg/v3/backend.(*SnapshotManager).defaultServiceLoop(0x140021c5b00, 0x1400233f730, 0x1400233f810)
        /private/tmp/pulumi-20241017-5200-awxgm2/pkg/backend/snapshot.go:718 +0x114
created by github.com/pulumi/pulumi/pkg/v3/backend.NewSnapshotManager in goroutine 1
        /private/tmp/pulumi-20241017-5200-awxgm2/pkg/backend/snapshot.go:769 +0x228
```

At this point the `urn` of the first resource has changed in state, while the second one remains with the old `urn` and `deletedWith`, which can't be resolved anymore.

### Output of `pulumi about`

CLI          
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.49.1
resource  azuread       5.53.1
resource  command       1.0.0
language  python        3.137.0
resource  random        4.16.3

Host     
OS       darwin
Version  14.7
Arch     arm64

This project is written in python: executable='/Users/user/dev/pulumi_tests/.direnv/python-3.11/bin/python3' version='3.11.7'

Backend        
Name           LOCAL
URL            file://~
User           user
Organizations  
Token type     personal

Dependencies:
NAME                 VERSION
pip                  23.2.1
pulumi_azure_native  2.49.1
pulumi_azuread       5.53.1
pulumi_command       1.0.0
pulumi_random        4.16.3
setuptools           65.5.0

Pulumi locates its logs in /var/folders/sk/pszdtqpd27scfxbkpy52zl1c0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for the repro, @fritz-k! Looks like we're not correctly handling aliases and deletedWith.
