### ISSUE TITLE
The Pulumi CLI encountered a snapshot integrity error

### ISSUE THREAD

**Issue by hramezani** [pulumi/pulumi#17615]
### What happened?

I got the following error when I ran the `pulumi preview`:

```
Please provide all of the text below in your report.
================================================================================
Pulumi Version:    v3.137.0
Go Version:        go1.23.2
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin
Command:           pulumi preview
Error:             could not deserialize deployment: snapshot integrity failure; refusing to use it: resource urn:pulumi:foo::bar::gcp:organizations/project:Project::project-name refers to unknown provider urn:pulumi:foo::bar::pulumi:providers:gcp::default_7_32_0::<uuid>

Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.23.2/x64/src/runtime/debug/stack.go:26 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x104d840af?, 0x1400368df98?}, {0x1400368dfb8?, 0x4b?, 0x40?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:611 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x14001d05e00)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:455 +0x3b8
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getSnapshot(0x70?, {0x105b89208, 0x107191fc0}, {0x105b64920, 0x107191fc0}, {0x105b89760?, 0x14001facd80?})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:235 +0x74
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getTarget(0x14001eded20, {0x105b89208, 0x107191fc0}, {0x105b64920, 0x107191fc0}, {0x105b89760, 0x14001facd80}, 0x14001f84f60, {0x105b75198, 0x14001f852f0})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:255 +0xa4
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).newUpdate(_, {_, _}, {_, _}, {0x14001f36580, {0x140020210e0, 0x3f}, {0x0, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:202 +0x1c0
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0x14001f36580, {0x140020210e0, 0x3f}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1381 +0xf0
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0x14001f36580, {0x140020210e0, 0x3f}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1355 +0x3e4
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Preview(_, {_, _}, {_, _}, {0x14001f36580, {0x140020210e0, 0x3f}, {0x0, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1101 +0x70
github.com/pulumi/pulumi/pkg/v3/backend.PreviewStack({_, _}, {_, _}, {0x14001f36580, {0x140020210e0, 0x3f}, {0x0, 0x0, 0x0}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/stack.go:92 +0x80
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Preview(_, {_, _}, {0x14001f36580, {0x140020210e0, 0x3f}, {0x0, 0x0, 0x0}, 0x14001ecbdd0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:173 +0x60
main.newPreviewCmd.func1(0x14001f35b08, {0x107191fc0, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/preview.go:466 +0x1108
main.newPreviewCmd.runCmdFunc.func2(0x0?, {0x107191fc0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:45 +0x28
main.newPreviewCmd.runCmdFunc.RunFunc.func5(0x14001f35b08, {0x107191fc0, 0x0, 0x0})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x38
github.com/spf13/cobra.(*Command).execute(0x14001f35b08, {0x107191fc0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x81c
github.com/spf13/cobra.(*Command).ExecuteC(0x14001ca8608)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x50
```

### Example

run `pulumi preview`

### Output of `pulumi about`

```
CLI          
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  cloudflare     5.34.0
resource  gcp            7.32.0
resource  google-native  0.32.0
resource  kubernetes     4.15.0
language  nodejs         unknown
resource  random         4.16.3
resource  tls            5.0.4

Host     
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v22.10.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/hasan-pydantic
User           hasan-pydantic
Organizations  hasan-pydantic, pydantic
Token type     personal

Dependencies:
NAME                              VERSION
@pulumi/google-native             0.32.0
@types/node                       20.14.11
eslint-plugin-simple-import-sort  12.1.1
eslint                            8.56.0
@pulumi/cloudflare                5.34.0
@pulumi/pulumi                    3.124.0
eslint-config-prettier            9.1.0
eslint-config-standard            17.1.0
prettier                          3.3.3
typescript                        5.5.3
@pulumi/kubernetes                4.15.0
@typescript-eslint/parser         7.16.1
@pulumi/gcp                       7.32.0
@pulumi/tls                       5.0.4
@typescript-eslint/eslint-plugin  7.16.1
@pulumi/random                    4.16.3

Pulumi locates its logs in /var/folders/y2/pvtpkxhn0g700nhccl2p1zvh0000gn/T/ by default
warning: Failed to get information about the current stack: snapshot integrity failure; refusing to use it: resource urn:pulumi:foo::bar::gcp:organizations/project:Project::project-name refers to unknown provider urn:pulumi:foo::bar::pulumi:providers:gcp::default_7_32_0::<uuid>
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hramezani** [comment]
got fixed by `pulumi state repair`
