### ISSUE TITLE
Provide a more helpful error message when failing to decrypt secrets

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1763]
When users copy secrets from one stack to another, this currently triggers an error because the encryption is done on a per-stack basis.

The error message is not good/helpful:

```
fatal: [500] Internal Server Error
Internal error: cipher: message authentication failed
```

We should provide a better error here (and link to Troubleshooting docs if necessary).

**Comment by jarshwah** [comment]
Just incase it helps someone with their google-fu in future, I'll attach the stacktrace that I ran into.

```
Pulumi Version:   v0.14.3
Go Version:       go1.9
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: [500] Internal Server Error

goroutine 1 [running]:
runtime/debug.Stack(0xc4201b4dd0, 0x191afa0, 0xc420556280)
        /Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/debug/stack.go:24 +0xa7
main.panicHandler()
        /Users/travis/gopath/src/github.com/pulumi/pulumi/main.go:30 +0x71
panic(0x191afa0, 0xc420556280)
        /Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/panic.go:491 +0x283
github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc420528240, 0x1b)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xf3
github.com/pulumi/pulumi/pkg/util/contract.AssertNoError(0x2020bc0, 0xc4204662c0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:40 +0x58
github.com/pulumi/pulumi/pkg/engine.makeEventEmitter(0xc4203f4e40, 0x202c140, 0xc4200f0a00, 0x6)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/events.go:148 +0x197
github.com/pulumi/pulumi/pkg/engine.Update(0x202c140, 0xc4200f0a00, 0xc4201f0690, 0x20b8308, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, ...)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/update.go:66 +0x197
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).runEngineAction(0xc42032e870, 0x202fd00, 0xc42008e008, 0x1aa3ed2, 0x7, 0x202ac80, 0xc42032fdd0, 0xc4200f0600, 0xc42044d800, 0x2f, ...)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:986 +0xaa9
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).updateStack(0xc42032e870, 0x202fd00, 0xc42008e008, 0x1aa3ed2, 0x7, 0x2034c80, 0xc4200a1bc0, 0xc4200f0600, 0xc42044d800, 0x2f, ...)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:895 +0x80b
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).PreviewThenPrompt(0xc42032e870, 0x202fd00, 0xc42008e008, 0x1aa3ed2, 0x7, 0x2034c80, 0xc4200a1bc0, 0xc4200f0600, 0xc42044d800, 0x2f, ...)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:689 +0x391
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).PreviewThenPromptThenExecute(0xc42032e870, 0x202fd00, 0xc42008e008, 0x1aa3ed2, 0x7, 0x202ac80, 0xc42032f350, 0xc4200f0600, 0xc42044d800, 0x2f, ...)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:775 +0x1e7
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).Preview(0xc42032e870, 0x202fd00, 0xc42008e008, 0x202ac80, 0xc42032f350, 0xc4200f0600,0xc42044d800, 0x2f, 0x0, 0x0, ...)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:787 +0x124
github.com/pulumi/pulumi/pkg/backend.PreviewStack(0x202fd00, 0xc42008e008, 0x2034c80, 0xc4200a10e0, 0xc4200f0600, 0xc42044d800, 0x2f, 0x0, 0x0, 0xc42032f470, ...)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/stack.go:71 +0x163
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudStack).Preview(0xc4200a10e0, 0x202fd00, 0xc42008e008, 0xc4200f0600, 0xc42044d800, 0x2f, 0x0, 0x0, 0xc42032f470, 0x20b8308, ...)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/cloud/stack.go:125 +0x101
github.com/pulumi/pulumi/cmd.newPreviewCmd.func1(0xc420315200, 0x20b8308, 0x0, 0x0, 0x0, 0x0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/cmd/preview.go:91 +0x39f
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc420315200, 0x20b8308, 0x0, 0x0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:92 +0x5a
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute(0xc420315200, 0x20b8308, 0x0, 0x0, 0xc420315200, 0x20b8308)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420216d80, 0xc4202e7fc0, 0xc4202ee800, 0xc4202ee840)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420216d80, 0x1ae2098, 0xc420080058)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
        /Users/travis/gopath/src/github.com/pulumi/pulumi/main.go:49 +0x4b
```

**Comment by joeduffy** [comment]
Oh, that's doubly bad, I didn't realize we are panicking. We should never assert on something that could get triggered by an HTTP response code.
