### ISSUE TITLE
[pulumi-java] storageClasses - java.lang.NullPointerException: expected parameter 'provisioner' to be non-null

### ISSUE THREAD

**Issue by vvatlin** [pulumi/pulumi#17641]
### What happened?

Hello.  I'm trying to create EKS cluster with this configuration 

```
new Cluster(name, ClusterArgs.builder()
            .name(name)
            .desiredCapacity(2)
            .vpcId(vpc.vpcId())
            .createOidcProvider(true)
            .enableConfigMapMutable(true)
            .instanceType("t3.medium")
            .nodeRootVolumeSize(50)
            .nodeRootVolumeEncrypted(true)
            .storageClasses(
                Map.of("gp3", StorageClassArgs.builder()
                    .type("gp3")
                    .allowVolumeExpansion(true)
                    .default_(true)
                    .reclaimPolicy("Retain")
                    .volumeBindingMode("WaitForFirstConsumer")
                    .build()
                )
            )
            .publicSubnetIds(vpc.publicSubnetIds())
            .privateSubnetIds(vpc.privateSubnetIds())
            .build()

```

And I got this error:
```
Diagnostics:
  pulumi:pulumi:Stack (project1-prod):
    error: Running program [PID: 29217](/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /opt/homebrew/Cellar/maven/3.9.9/libexec/boot/plexus-classworlds-2.8.0.jar -Dclassworlds.conf=/opt/homebrew/Cellar/maven/3.9.9/libexec/bin/m2.conf -Dmaven.home=/opt/homebrew/Cellar/maven/3.9.9/libexec -Dlibrary.jansi.path=/opt/homebrew/Cellar/maven/3.9.9/libexec/lib/jansi-native -Dmaven.multiModuleProjectDirectory=/Users/user1/job/git/advcash/pulumi org.codehaus.plexus.classworlds.launcher.Launcher -Dorg.slf4j.simpleLogger.defaultLogLevel=warn --no-transfer-progress compile exec:java) failed with an unhandled exception:
    java.lang.IllegalArgumentException: Couldn't instantiate class 'com.pulumi.kubernetes.storage.v1.StorageClass' using constructor: 'public com.pulumi.kubernetes.storage.v1.StorageClass(java.lang.String,com.pulumi.kubernetes.storage.v1.StorageClassArgs,com.pulumi.resources.CustomResourceOptions)', for resource type: 'kubernetes:storage.k8s.io/v1:StorageClass'
        at com.pulumi.serialization.internal.ResourcePackages.tryConstruct(ResourcePackages.java:248)
        at com.pulumi.serialization.internal.Deserializer.tryDeserializeResource(Deserializer.java:367)
        at com.pulumi.serialization.internal.Deserializer.deserializeCore(Deserializer.java:103)
        at com.pulumi.serialization.internal.Deserializer.deserialize(Deserializer.java:59)
        at com.pulumi.serialization.internal.Deserializer.lambda$deserializeStruct$9(Deserializer.java:194)
        at com.pulumi.serialization.internal.Deserializer.lambda$deserializeOneOf$10(Deserializer.java:223)
        at com.pulumi.serialization.internal.Deserializer.deserializeCore(Deserializer.java:109)
        at com.pulumi.serialization.internal.Deserializer.deserializeOneOf(Deserializer.java:221)
        at com.pulumi.serialization.internal.Deserializer.deserializeStruct(Deserializer.java:176)
        at com.pulumi.serialization.internal.Deserializer.lambda$deserialize$6(Deserializer.java:72)
        at com.pulumi.serialization.internal.Deserializer.deserializeCore(Deserializer.java:109)
        at com.pulumi.serialization.internal.Deserializer.deserialize(Deserializer.java:59)
        at com.pulumi.serialization.internal.Deserializer.lambda$deserializeStruct$9(Deserializer.java:194)
        at com.pulumi.serialization.internal.Deserializer.lambda$deserializeOneOf$10(Deserializer.java:223)
        at com.pulumi.serialization.internal.Deserializer.deserializeCore(Deserializer.java:109)
        at com.pulumi.serialization.internal.Deserializer.deserializeOneOf(Deserializer.java:221)
        at com.pulumi.serialization.internal.Deserializer.deserializeStruct(Deserializer.java:176)
        at com.pulumi.serialization.internal.Deserializer.lambda$deserialize$6(Deserializer.java:72)
        at com.pulumi.serialization.internal.Deserializer.deserializeCore(Deserializer.java:109)
        at com.pulumi.serialization.internal.Deserializer.deserialize(Deserializer.java:59)
        at com.pulumi.serialization.internal.Converter.convertValue(Converter.java:81)
        at com.pulumi.core.internal.OutputCompletionSource.setValue(OutputCompletionSource.java:95)
        at com.pulumi.deployment.internal.DeploymentImpl$ReadOrRegisterResourceInternal.lambda$completeResourceAsync$1(DeploymentImpl.java:1258)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:690)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:527)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189)
    Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
        at com.pulumi.serialization.internal.ResourcePackages.tryConstruct(ResourcePackages.java:245)
        ... 28 more
    Caused by: java.lang.NullPointerException: expected parameter 'provisioner' to be non-null
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at com.pulumi.kubernetes.storage.v1.StorageClassArgs$Builder.build(StorageClassArgs.java:440)
        at com.pulumi.kubernetes.storage.v1.StorageClass.makeArgs(StorageClass.java:204)
        at com.pulumi.kubernetes.storage.v1.StorageClass.<init>(StorageClass.java:192)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        ... 31 more
    error: an unhandled error occurred: '/opt/homebrew/bin/mvn /opt/homebrew/bin/mvn -Dorg.slf4j.simpleLogger.defaultLogLevel=warn --no-transfer-progress compile exec:java' exited with non-zero exit code: 32

```

All packages and software - latest versions.

### Example

```
new Cluster(name, ClusterArgs.builder()
            .name(name)
            .desiredCapacity(2)
            .vpcId(vpc.vpcId())
            .createOidcProvider(true)
            .enableConfigMapMutable(true)
            .instanceType("t3.medium")
            .nodeRootVolumeSize(50)
            .nodeRootVolumeEncrypted(true)
            .storageClasses(
                Map.of("gp3", StorageClassArgs.builder()
                    .type("gp3")
                    .allowVolumeExpansion(true)
                    .default_(true)
                    .reclaimPolicy("Retain")
                    .volumeBindingMode("WaitForFirstConsumer")
                    .build()
                )
            )
            .publicSubnetIds(vpc.publicSubnetIds())
            .privateSubnetIds(vpc.privateSubnetIds())
            .build()
```

### Output of `pulumi about`

```
pulumi about
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):  
Enter your passphrase to unlock config/secrets
CLI          
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.57.0-alpha.1730217437
resource  awsx        2.17.0-alpha.1729879547
resource  docker      4.5.1
resource  eks         3.1.0-alpha.1730149020
language  java        unknown
resource  kubernetes  4.4.0

Host     
OS       darwin
Version  15.1
Arch     arm64

This project is written in java: executable='/usr/bin/java' version='openjdk 21.0.5 2024-10-15 LTS
OpenJDK Runtime Environment Corretto-21.0.5.11.1 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.5.11.1 (build 21.0.5+11-LTS, mixed mode, sharing)' maven='Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)' java='/usr/bin/java' javac='21.0.5'

Current Stack: organization/project1/prod

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:prod::project1::pulumi:pulumi:Stack::project1-prod
pulumi:providers:awsx                                urn:pulumi:prod::project1::pulumi:providers:awsx::default_2_17_0_alpha_1729879547
awsx:ec2:Vpc                                         urn:pulumi:prod::project1::awsx:ec2:Vpc::project1
pulumi:providers:aws                                 urn:pulumi:prod::project1::pulumi:providers:aws::default_6_47_0
aws:ec2/vpc:Vpc                                      urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc::project1
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-databases-3
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-intra-2
aws:ec2/internetGateway:InternetGateway              urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/internetGateway:InternetGateway::project1
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-caches-3
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-intra-3
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-caches-2
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-databases-2
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-intra-1
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-databases-1
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-caches-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-databases-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-intra-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-caches-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-intra-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-caches-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-intra-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-databases-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-databases-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-databases-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-caches-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-intra-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-caches-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-intra-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-caches-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-intra-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-databases-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-databases-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-caches-1
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-public-1
aws:ec2/eip:Eip                                      urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/eip:Eip::project1-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-public-1
aws:ec2/natGateway:NatGateway                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::project1-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-public-1
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-public-1
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-caches-1
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-databases-3
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-intra-3
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-caches-3
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-databases-2
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-databases-1
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-intra-2
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-caches-2
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-intra-1
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-private-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-private-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-private-1
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-private-1
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-private-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-private-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-private-2
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-private-2
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-private-3
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-public-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-private-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-public-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-private-3
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-private-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-public-2
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-public-2
aws:ec2/subnet:Subnet                                urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::project1-public-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::project1-public-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::project1-public-3
aws:ec2/route:Route                                  urn:pulumi:prod::project1::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::project1-public-3
pulumi:providers:pulumi                              urn:pulumi:prod::project1::pulumi:providers:pulumi::default
pulumi:providers:eks                                 urn:pulumi:prod::project1::pulumi:providers:eks::default_3_1_0_alpha_1730149020
eks:index:Cluster                                    urn:pulumi:prod::project1::eks:index:Cluster::project1
eks:index:ServiceRole                                urn:pulumi:prod::project1::eks:index:Cluster$eks:index:ServiceRole::project1-instanceRole
pulumi:providers:aws                                 urn:pulumi:prod::project1::pulumi:providers:aws::default_6_45_0
eks:index:ServiceRole                                urn:pulumi:prod::project1::eks:index:Cluster$eks:index:ServiceRole::project1-eksRole
aws:iam/role:Role                                    urn:pulumi:prod::project1::eks:index:Cluster$eks:index:ServiceRole$aws:iam/role:Role::project1-eksRole-role
aws:iam/role:Role                                    urn:pulumi:prod::project1::eks:index:Cluster$eks:index:ServiceRole$aws:iam/role:Role::project1-instanceRole-role
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:prod::project1::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::project1-eksRole-4b490823
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:prod::project1::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::project1-instanceRole-3eb088f2
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:prod::project1::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::project1-instanceRole-e1b295bd
aws:iam/rolePolicyAttachment:RolePolicyAttachment    urn:pulumi:prod::project1::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::project1-instanceRole-03516f97
aws:iam/instanceProfile:InstanceProfile              urn:pulumi:prod::project1::eks:index:Cluster$aws:iam/instanceProfile:InstanceProfile::project1-instanceProfile
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:prod::project1::eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::project1-eksClusterSecurityGroup
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:prod::project1::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::project1-eksClusterInternetEgressRule
aws:eks/cluster:Cluster                              urn:pulumi:prod::project1::eks:index:Cluster$aws:eks/cluster:Cluster::project1-eksCluster
pulumi:providers:kubernetes                          urn:pulumi:prod::project1::eks:index:Cluster$pulumi:providers:kubernetes::project1-eks-k8s
aws:iam/openIdConnectProvider:OpenIdConnectProvider  urn:pulumi:prod::project1::eks:index:Cluster$aws:iam/openIdConnectProvider:OpenIdConnectProvider::project1-oidcProvider
kubernetes:core/v1:ConfigMap                         urn:pulumi:prod::project1::eks:index:Cluster$kubernetes:core/v1:ConfigMap::project1-nodeAccess
eks:index:VpcCniAddon                                urn:pulumi:prod::project1::eks:index:Cluster$eks:index:VpcCniAddon::project1-vpc-cni
kubernetes:storage.k8s.io/v1:StorageClass            urn:pulumi:prod::project1::eks:index:Cluster$kubernetes:storage.k8s.io/v1:StorageClass::project1-gp3
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:prod::project1::eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::project1-nodeSecurityGroup
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:prod::project1::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::project1-eksClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:prod::project1::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::project1-eksNodeInternetEgressRule
aws:ec2/launchTemplate:LaunchTemplate                urn:pulumi:prod::project1::eks:index:Cluster$aws:ec2/launchTemplate:LaunchTemplate::project1-launchTemplate
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:prod::project1::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::project1-eksExtApiServerClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:prod::project1::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::project1-eksNodeClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule          urn:pulumi:prod::project1::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::project1-eksNodeIngressRule
aws:eks/addon:Addon                                  urn:pulumi:prod::project1::eks:index:Cluster$aws:eks/addon:Addon::project1-kube-proxy
aws:eks/addon:Addon                                  urn:pulumi:prod::project1::eks:index:Cluster$eks:index:VpcCniAddon$aws:eks/addon:Addon::project1-vpc-cni
aws:autoscaling/group:Group                          urn:pulumi:prod::project1::eks:index:Cluster$aws:autoscaling/group:Group::project1
aws:eks/addon:Addon                                  urn:pulumi:prod::project1::eks:index:Cluster$aws:eks/addon:Addon::project1-coredns


Found no pending operations associated with prod

Backend        
Name           MBP.Home
URL            file://~
User           user1
Organizations  
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/mp/g7_53xrn6ggbyp4fm_pwfg6m0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for the issue, @vvatlin, sorry for the trouble and delay getting back to you!

It looks like this was fixed in https://github.com/pulumi/pulumi-kubernetes/pull/3119 and shipped in v4.16.0 of pulumi-kubernetes. However, the EKS library is depending on v4.4.0:

https://github.com/pulumi/pulumi-eks/blob/00353a9d5579be4e1b7c227af7753663b6b36a32/provider/cmd/pulumi-resource-eks/schema.json#L32

We'll need to upgrade our EKS SDK to depend on a more recent version of the kubernetes SDK.

I'm going to transfer this issue to https://github.com/pulumi/pulumi-eks and someone will take a look soon.
