### ISSUE TITLE
import existed resources failed by dynamic resource provider

### ISSUE THREAD

**Issue by tangr** [pulumi/pulumi#17698]
## Hello!

I wrote custom resource by dynamic resource provider, everything works fine except import existed resource.
How could I import existed resource?

```typescript
import * as pulumi from "@pulumi/pulumi";
import { ApolloItem } from "./providers/apolloItem";

const existingItem = new ApolloItem(
  "item-tmptest-open-api-test3",
  {},
  {
    import: "PRO:superadmin:open-api-test3:application:content",
  }
);

```

and ApolloItem definition:

```typescript
export class ApolloItem extends pulumi.dynamic.Resource {
  constructor(name: string, props: any, opts?: pulumi.CustomResourceOptions) {
    super(
      new ApolloItemProvider(),
      name,
      props,
      opts,
      "apolloconfig",
      "ApolloItem"
    );
  }
}
```

### Affected area

```
% pulumi up
Previewing update (test):
     Type                                              Name                         Plan       Info
 +   pulumi:pulumi:Stack                               apolloconfig-itfs-test       create     1 error; 11 messages
 =   └─ pulumi-nodejs:dynamic/apolloconfig:ApolloItem  item-tmptest-open-api-test3  import     1 error

Diagnostics:
  pulumi:pulumi:Stack (apolloconfig-itfs-test):
    Error: code must be a string, not undefined: Error: code must be a string, not undefined
        at requireFromString (/Users/admin/test/node_modules/require-from-string/index.js:19:9)
        at getProvider (/Users/admin/test/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:70:20)
        at Object.<anonymous> (/Users/admin/test/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:231:30)
        at Generator.next (<anonymous>)
        at /Users/admin/test/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/admin/test/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:17:12)
        at Object.readRPC [as read] (/Users/admin/test/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:225:12)
        at Object.onReceiveHalfClose (/Users/admin/test/node_modules/@grpc/grpc-js/build/src/server.js:1425:25)
        at BaseServerInterceptingCall.maybePushNextMessage (/Users/admin/test/node_modules/@grpc/grpc-js/build/src/server-interceptors.js:569:31)

    error: preview failed

  pulumi-nodejs:dynamic/apolloconfig:ApolloItem (item-tmptest-open-api-test3):
    error: Preview failed: code must be a string, not undefined


```

```
% pulumi about
CLI
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  3.137.0-dev.0

Host
OS       darwin
Version  14.1.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.16.0'

Backend
Organizations
Token type     personal

Dependencies:
NAME            VERSION
@types/axios    0.14.4
@types/node     8.10.66
axios           1.7.7
@pulumi/pulumi  3.137.0


warning: Failed to get information about the current stack: No current stack
```

**Comment by justinvp** [comment]
Hi @tangr. Unfortunately, this is a known limitation of dynamic providers. We're currently tracking this at https://github.com/pulumi/pulumi/issues/16175. Feel free to upvote it. Therefore, I'm going to close this as a duplicate.
