### ISSUE TITLE
Wrapping a Promise<T> in a `pulumi.output` then running apply() hits `Maximum call stack exceeded` error

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#17778]
### What happened?

When using automation api and inline programs, there is an attempt to wrap a function that returns a promise in `pulumi.output` to avoid having to add await all over the place. The following program is an example:

```typescript
import axios from "axios";
import * as pulumi from "@pulumi/pulumi";
import { LocalWorkspace } from "@pulumi/pulumi/automation";

const pulumiProgram = async () => {
  const response = pulumi.output(axios.get("https://google.com"));
  response.apply((r) => {
    pulumi.log.info(`${r.status}`);
  });
};

(async () => {
  const stack = await LocalWorkspace.createOrSelectStack({
    program: pulumiProgram,
    projectName: "test-async-apply",
    stackName: "dev",
  });

  await stack.up({ onOutput: console.log });
})();
```

When this is run, the following error is shown:

```
❯ npm run start

> async-output-apply@1.0.0 start
> ./node_modules/ts-node/dist/bin.js index.ts

Updating (dev)


View Live: https://app.pulumi.com/pierskarsenbarg/test-async-apply/dev/updates/6




    pulumi:pulumi:Stack test-async-apply-dev
Resources:
    1 unchanged

Duration: 1s


RangeError: Maximum call stack size exceeded
    at outputRec (/Users/piers/go/src/github.com/pierskarsenbarg/scratchpad/async-output-apply/node_modules/@pulumi/output.ts:482:19)
    at outputRec (/Users/piers/go/src/github.com/pierskarsenbarg/scratchpad/async-output-apply/node_modules/@pulumi/output.ts:549:24)
    at outputRec (/Users/piers/go/src/github.com/pierskarsenbarg/scratchpad/async-output-apply/node_modules/@pulumi/output.ts:549:24)
    at outputRec (/Users/piers/go/src/github.com/pierskarsenbarg/scratchpad/async-output-apply/node_modules/@pulumi/output.ts:549:24)
    at outputRec (/Users/piers/go/src/github.com/pierskarsenbarg/scratchpad/async-output-apply/node_modules/@pulumi/output.ts:524:24)
    at outputRec (/Users/piers/go/src/github.com/pierskarsenbarg/scratchpad/async-output-apply/node_modules/@pulumi/output.ts:549:24)
    at outputRec (/Users/piers/go/src/github.com/pierskarsenbarg/scratchpad/async-output-apply/node_modules/@pulumi/output.ts:549:24)
    at outputRec (/Users/piers/go/src/github.com/pierskarsenbarg/scratchpad/async-output-apply/node_modules/@pulumi/output.ts:549:24)
    at outputRec (/Users/piers/go/src/github.com/pierskarsenbarg/scratchpad/async-output-apply/node_modules/@pulumi/output.ts:549:24)
    at outputRec (/Users/piers/go/src/github.com/pierskarsenbarg/scratchpad/async-output-apply/node_modules/@pulumi/output.ts:549:24)
```

If I run the same without automation API:

```typescript
import * as pulumi from "@pulumi/pulumi";
import axios from "axios";

const response = pulumi.output(axios.get("https://google.com/"));

response.apply((r) => pulumi.log.info(`${r.status}`));
```

I get the same error message. I've uploaded verbose logs here: https://gist.github.com/pierskarsenbarg/22cd407a8854adb7c2c3d71218f70cbe

### Example

1. Clone repo: `git clone https://github.com/pierskarsenbarg/async-output-apply-bug`
2. Install dependencies: `npm i`
3. Run: `npm run start`

### Output of `pulumi about`

automation api but here's the package.json with fixed package versions: https://github.com/pierskarsenbarg/async-output-apply-bug/blob/main/package.json

output from Pulumi about anyway:

```
❯ pulumi about
CLI
Version      3.138.0
Go Version   go1.23.2
Go Compiler  gc
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pierskarsenbarg** [comment]
I thought this might be an automation API thing, but it seems it won't work in non-automation API programs as well:

```typescript
import * as pulumi from "@pulumi/pulumi";
import axios from "axios";

const response = pulumi.output(axios.get("https://google.com"));

response.apply((r) => pulumi.log.info(`${r.status}`));
```

**Comment by pierskarsenbarg** [comment]
Further update to this: if I remove the `apply()` line:

```typescript
import * as pulumi from "@pulumi/pulumi";
import axios from "axios";

const response = pulumi.output(axios.get("https://google.com/"));
```

I still get the error

**Comment by pierskarsenbarg** [comment]
This looks like it might be an axios thing.

If I do the following:

```typescript
import * as pulumi from "@pulumi/pulumi";

interface myInterface {
  name: string;
  value: string;
}

const myPromise = async (): Promise<myInterface> => {
  return new Promise<myInterface>((resolve) => {
    resolve({
      name: "Piers",
      value: "ten",
    });
  });
};

const response = pulumi.output(myPromise());
response.apply((x) => pulumi.log.info(x.value));
```

I get `ten` written out as expected. 

So it _does_ work with standard promises.
