### ISSUE TITLE
The Pulumi CLI encountered a snapshot integrity error.

### ISSUE THREAD

**Issue by olly-writes-code** [pulumi/pulumi#17775]
### What happened?

Running `pulumi preview -s prod` I get 

```
error: The Pulumi CLI encountered a snapshot integrity error. This is a bug!

We would appreciate a report: https://github.com/pulumi/pulumi/issues/

NOTE: This error occurred while reading a snaphot. This error was introduced by
a previous operation when it wrote the snapshot. If you have details about that
operation, please include them in your report as well.

Please provide all of the text below in your report.
```

### Example

I don't have these but the request is to upload the output

### Output of `pulumi about`

```
Previewing update (prod)

error: The Pulumi CLI encountered a snapshot integrity error. This is a bug!

================================================================================
We would appreciate a report: https://github.com/pulumi/pulumi/issues/

NOTE: This error occurred while reading a snaphot. This error was introduced by
a previous operation when it wrote the snapshot. If you have details about that
operation, please include them in your report as well.

Please provide all of the text below in your report.
================================================================================
Go Version:        go1.23.2
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin

Pulumi Version:    v3.138.0
Command:           pulumi preview -s prod
Error:             could not deserialize deployment: snapshot integrity failure; refusing to use it: resource urn:pulumi:prod::engineering::aws:ec2/eipAssociation:EipAssociation::ollys-data_processing-machine-eip-assoc's dependency urn:pulumi:prod::engineering::aws:ec2/instance:Instance::ollys-data_processing-machine refers to missing resource

Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/debug/stack.go:26 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x10415814c?, 0x56?}, {0x14001ebdf88?, 0x56?, 0x40?})
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:617 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x14001f53cc0)
	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:507 +0xcd4
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getSnapshot(0x70?, {0x104f44728, 0x10656e040}, {0x104f1fd40, 0x10656e040}, {0x104f44c40?, 0x14001f9e6c0?})
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:235 +0x74
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getTarget(0x14001f80690, {0x104f44728, 0x10656e040}, {0x104f1fd40, 0x10656e040}, {0x104f44c40, 0x14001f9e6c0}, 0x14001f46720, {0x14dfb04d8, 0x10656e040})
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:255 +0xa4
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).newUpdate(_, {_, _}, {_, _}, {0x14000277970, {0x1400081bb00, 0x4e}, {0x0, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:202 +0x1c0
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0x14000277970, {0x1400081bb00, 0x4e}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1386 +0xf0
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0x14000277970, {0x1400081bb00, 0x4e}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1360 +0x434
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Preview(_, {_, _}, {_, _}, {0x14000277970, {0x1400081bb00, 0x4e}, {0x0, 0x0, ...}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1102 +0x70
github.com/pulumi/pulumi/pkg/v3/backend.PreviewStack({_, _}, {_, _}, {0x14000277970, {0x1400081bb00, 0x4e}, {0x0, 0x0, 0x0}, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/stack.go:92 +0x80
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Preview(_, {_, _}, {0x14000277970, {0x1400081bb00, 0x4e}, {0x0, 0x0, 0x0}, 0x140001a1458, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:173 +0x60
main.newPreviewCmd.func1(0x14001ecfb08, {0x14001ef6480, 0x0, 0x0?})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/preview.go:466 +0x1108
main.newPreviewCmd.runCmdFunc.func2(0x0?, {0x14001ef6480?, 0x0?, 0x0?})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:45 +0x28
main.newPreviewCmd.runCmdFunc.RunFunc.func5(0x14001ecfb08, {0x14001ef6480, 0x0, 0x2})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x38
github.com/spf13/cobra.(*Command).execute(0x14001ecfb08, {0x14001ef6460, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x81c
github.com/spf13/cobra.(*Command).ExecuteC(0x14001904608)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x50

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by olly-writes-code** [comment]
noting that ` pulumi refresh -s prod` also doesn't work, returning the same error

**Comment by olly-writes-code** [comment]
I think what happened here is that a pulumi up command errored (due to a different process) midway through performing an ec2 replacement with `opts=pulumi.ResourceOptions(delete_before_replace=True)`. 

Any advice for getting out of this situation without destroying the whole stack?

**Comment by olly-writes-code** [comment]
Fixed! I ran `pulumi up -s prod --disable-integrity-checking` to ignore the integrity check. Everything ran okay and the stack is all good now!

**Comment by Frassle** [comment]
We've fixed some issues with delete_before_replace recently (e.g. https://github.com/pulumi/pulumi/pull/17146), and given the error message doesn't include the command that caused it we can tell the corrupt snapshot was written by and older CLI version. I'm minded to say it's likely we've already fixed this specific issue.
