### ISSUE TITLE
Error: Cannot find module './trace'

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#17823]
```
=== FAIL: integration TestConstructComponentConfigureProviderNode (255.05s)
    io.go:431: + set -euo pipefail
    io.go:431: + DONEFILE=.done
    io.go:431: ++ git rev-parse HEAD:./
    io.go:431: + EXPECTED_HASH=89660b502ffe86f8922c10b01b046971e4201e9d
    io.go:431: + BUILD=false
    io.go:431: + '[' -f .done ']'
    io.go:431: ++ head .done
    io.go:431: + '[' 89660b502ffe86f8922c10b01b046971e4201e9d = 89660b502ffe86f8922c10b01b046971e4201e9d ']'
    io.go:431: + echo 'Setup marked complete'
    io.go:431: Setup marked complete
    io.go:431: ++ git status --porcelain .
    io.go:431: + output=
    io.go:431: + '[' -z '' ']'
    io.go:431: + echo 'Directory is clean'
    io.go:431: Directory is clean
    io.go:431: + false
    io.go:431: + echo 'Setup already done, directory is clean. Success!'
    io.go:431: Setup already done, directory is clean. Success!
    io.go:431: + exit 0
    integration_nodejs_acceptance_test.go:174: yarn run tsc # precompile @pulumi/metaprovider
    integration_nodejs_acceptance_test.go:180: yarn link # prelink @pulumi/metaprovider
    program.go:1959: sample: construct_component_configure_provider/nodejs
    program.go:1964: pulumi: /home/runner/work/pulumi/pulumi/bin/pulumi
    program.go:1095: acquired yarn install lock
    command.go:46: **** Invoke '/opt/hostedtoolcache/node/18.20.4/x64/bin/yarn install' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:118: Wrote output to /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326/command-output/yarn-install.20241121-054639.c0aa4.log
    program.go:1121: released yarn install lock
    program.go:1095: acquired yarn install lock
    command.go:46: **** Invoke '/opt/hostedtoolcache/node/18.20.4/x64/bin/yarn link @pulumi/pulumi' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:118: Wrote output to /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326/command-output/yarn-link.20241121-054640.70b69.log
    program.go:1121: released yarn install lock
    program.go:1095: acquired yarn install lock
    command.go:46: **** Invoke '/opt/hostedtoolcache/node/18.20.4/x64/bin/yarn link @pulumi/metaprovider' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:118: Wrote output to /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326/command-output/yarn-link.20241121-054726.a4e6c.log
    program.go:1121: released yarn install lock
    program.go:2116: projdir: /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326
    program.go:1349: Initializing project (dir /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326; stack p-it-fv-az1986--nodejs-f8ea463b)
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi login --cloud-url file:///tmp/TestConstructComponentConfigureProviderNode984788358/001' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:118: Wrote output to /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326/command-output/pulumi-login.20241121-054728.2b6fa.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack init p-it-fv-az1986--nodejs-f8ea463b' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:118: Wrote output to /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326/command-output/pulumi-stack-init.20241121-054737.b29ae.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi config set-all --plaintext proxy=FromEnv' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:121: Command completed without output
    program.go:1516: Performing primary preview and update
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi preview --non-interactive --diff' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:118: Wrote output to /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326/command-output/pulumi-preview-initial.20241121-054759.e1203.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi up --non-interactive --yes --skip-preview --event-log /tmp/p-it-fv-az1986--nodejs-f8ea463b-events.json' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:118: Wrote output to /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326/command-output/pulumi-update-initial.20241121-054813.199f2.log
    program.go:1526: Roundtripping checkpoint via stack export and stack import
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack export --file stack.json' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:121: Command completed without output
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack import --file stack.json' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:118: Wrote output to /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326/command-output/pulumi-stack-import.20241121-054824.ffa7f.log
    program.go:1538: Performing empty preview and update(no changes expected)
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi preview --non-interactive --diff' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:98: Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi preview --non-interactive --diff' failed: exit status 255
Previewing update (p-it-fv-az1986--nodejs-f8ea463b):
error: Error: Cannot find module './trace'
Require stack:
- /home/runner/work/pulumi/pulumi/sdk/nodejs/bin/node_modules/@opentelemetry/semantic-conventions/build/src/index.js
- /home/runner/work/pulumi/pulumi/sdk/nodejs/bin/cmd/run/tracing.js
- /home/runner/work/pulumi/pulumi/sdk/nodejs/bin/cmd/run/run.js
- /home/runner/work/pulumi/pulumi/sdk/nodejs/bin/cmd/run/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/runner/work/pulumi/pulumi/sdk/nodejs/bin/node_modules/@opentelemetry/semantic-conventions/build/src/index.js:33:14)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
Resources:

    command.go:118: Wrote output to /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326/command-output/pulumi-preview-empty.20241121-054833.379a6.log
    program.go:1474: Destroying stack
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi destroy --non-interactive --yes --skip-preview' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:118: Wrote output to /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326/command-output/pulumi-destroy.20241121-054845.ee012.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack rm --yes' in '/tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326'
    command.go:118: Wrote output to /tmp/p-it-fv-az1986--nodejs-f8ea463b-30239326/command-output/pulumi-stack-rm.20241121-054851.9af40.log
    program.go:857: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/pkg/testing/integration/program.go:857
        	            				/home/runner/work/pulumi/pulumi/tests/integration/integration_nodejs_acceptance_test.go:195
        	Error:      	Received unexpected error:
        	            	running test preview, update, and edits: empty preview: [/home/runner/work/pulumi/pulumi/bin/pulumi preview --non-interactive --diff] did not succeed after 1 tries
        	Test:       	TestConstructComponentConfigureProviderNode
```

See https://github.com/pulumi/pulumi/actions/runs/11947260224/job/33303120445

**Comment by justinvp** [comment]
Hit again https://github.com/pulumi/pulumi/actions/runs/13464165789/job/37626452298?pr=18681#step:40:175

```
=== FAIL: integration TestNodeJSReservedIdentifierShadowing (43.06s)
    program.go:1977: sample: dynamic/nodejs-reserved-identifier-shadowing
    program.go:1982: pulumi: /home/runner/work/pulumi/pulumi/bin/pulumi
    program.go:1107: acquired yarn install lock
    command.go:46: **** Invoke '/opt/hostedtoolcache/node/23.8.0/x64/bin/yarn install' in '/tmp/p-it-fv-az770-3-nodejs-res-5a7e1225-3318481098'
    command.go:118: Wrote output to /tmp/p-it-fv-az770-3-nodejs-res-5a7e1225-3318481098/command-output/yarn-install.20250221-200717.b5ef4.log
    program.go:1133: released yarn install lock
    program.go:1107: acquired yarn install lock
    command.go:46: **** Invoke '/opt/hostedtoolcache/node/23.8.0/x64/bin/yarn link @pulumi/pulumi' in '/tmp/p-it-fv-az770-3-nodejs-res-5a7e1225-3318481098'
    command.go:118: Wrote output to /tmp/p-it-fv-az770-3-nodejs-res-5a7e1225-3318481098/command-output/yarn-link.20250221-200718.ec581.log
    program.go:1133: released yarn install lock
    program.go:2134: projdir: /tmp/p-it-fv-az770-3-nodejs-res-5a7e1225-3318481098
    program.go:1364: Initializing project (dir /tmp/p-it-fv-az770-3-nodejs-res-5a7e1225-3318481098; stack p-it-fv-az770-3-nodejs-res-5a7e1225)
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi login --cloud-url file:///tmp/TestNodeJSReservedIdentifierShadowing910282807/001' in '/tmp/p-it-fv-az770-3-nodejs-res-5a7e1225-3318481098'
    command.go:118: Wrote output to /tmp/p-it-fv-az770-3-nodejs-res-5a7e1225-3318481098/command-output/pulumi-login.20250221-200722.83de6.log
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi stack init p-it-fv-az770-3-nodejs-res-5a7e1225' in '/tmp/p-it-fv-az770-3-nodejs-res-5a7e1225-3318481098'
    command.go:118: Wrote output to /tmp/p-it-fv-az770-3-nodejs-res-5a7e1225-3318481098/command-output/pulumi-stack-init.20250221-200730.48160.log
    program.go:1531: Performing primary preview and update
    command.go:46: **** Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi preview --non-interactive --diff' in '/tmp/p-it-fv-az770-3-nodejs-res-5a7e1225-3318481098'
    command.go:98: Invoke '/home/runner/work/pulumi/pulumi/bin/pulumi preview --non-interactive --diff' failed: exit status 255
Previewing update (p-it-fv-az770-3-nodejs-res-5a7e1225):
error: Error: Cannot find module './trace'
Require stack:
- /home/runner/work/pulumi/pulumi/sdk/nodejs/bin/node_modules/@opentelemetry/semantic-conventions/build/src/index.js
- /home/runner/work/pulumi/pulumi/sdk/nodejs/bin/cmd/run/tracing.js
- /home/runner/work/pulumi/pulumi/sdk/nodejs/bin/cmd/run/run.js
- /home/runner/work/pulumi/pulumi/sdk/nodejs/bin/cmd/run/index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1405:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1061:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1066:22)
    at Function._load (node:internal/modules/cjs/loader:1215:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1491:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/home/runner/work/pulumi/pulumi/sdk/nodejs/bin/node_modules/@opentelemetry/semantic-conventions/src/index.ts:23:1)
```
