### ISSUE TITLE
`pulumi stack ls` crashes in migrate.UpToCheckpointV2

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1788]
Not clear what is unique about the folder I'm in where this crashes.  It does not repro in most other places on my machine.

```
$ pulumi stack ls
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v0.15.0
Go Version:       go1.9.2
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack(0xc42077f178, 0x19b2ba0, 0x212b800)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
main.panicHandler()
	/Users/luke/go/src/github.com/pulumi/pulumi/main.go:30 +0x71
panic(0x19b2ba0, 0x212b800)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/pulumi/pulumi/pkg/apitype/migrate.UpToCheckpointV2(0xc42027f660, 0x14, 0x0, 0x0, 0xc42030f2c0, 0x0, 0x0, 0x109ee03)
	/Users/luke/go/src/github.com/pulumi/pulumi/pkg/apitype/migrate/checkpoint.go:31 +0x1c6
github.com/pulumi/pulumi/pkg/resource/stack.UnmarshalVersionedCheckpointToLatestCheckpoint(0xc420cc0000, 0x57, 0x257, 0x57, 0x257, 0x0)
	/Users/luke/go/src/github.com/pulumi/pulumi/pkg/resource/stack/checkpoint.go:58 +0x2e2
github.com/pulumi/pulumi/pkg/backend/local.(*localBackend).getCheckpoint(0xc420207d40, 0xc42047d71b, 0x14, 0xc420812540, 0x34, 0x0)
	/Users/luke/go/src/github.com/pulumi/pulumi/pkg/backend/local/state.go:146 +0xa9
github.com/pulumi/pulumi/pkg/backend/local.(*localBackend).getStack(0xc420207d40, 0xc42047d71b, 0x14, 0x5, 0xc4200902c8, 0xc42030f201, 0x1, 0x2, 0x0)
	/Users/luke/go/src/github.com/pulumi/pulumi/pkg/backend/local/state.go:116 +0xa2
github.com/pulumi/pulumi/pkg/backend/local.(*localBackend).getLocalStacks(0xc420207d40, 0x28, 0xc4200c8c00, 0xc42001da40, 0x0, 0x0)
	/Users/luke/go/src/github.com/pulumi/pulumi/pkg/backend/local/backend.go:433 +0x1f6
github.com/pulumi/pulumi/pkg/backend/local.(*localBackend).ListStacks(0xc420207d40, 0x2086fc0, 0xc4200160a0, 0xc4201fb290, 0xc42077fae0, 0xc420216780, 0x0, 0x0, 0x0)
	/Users/luke/go/src/github.com/pulumi/pulumi/pkg/backend/local/backend.go:156 +0x40
github.com/pulumi/pulumi/cmd.newStackLsCmd.func1(0xc420784b40, 0x21641e8, 0x0, 0x0, 0x0, 0x0)
	/Users/luke/go/src/github.com/pulumi/pulumi/cmd/stack_ls.go:81 +0x269
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc420784b40, 0x21641e8, 0x0, 0x0)
	/Users/luke/go/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:92 +0x5a
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute(0xc420784b40, 0x21641e8, 0x0, 0x0, 0xc420784b40, 0x21641e8)
	/Users/luke/go/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42008e480, 0xc420327d98, 0xc420049430, 0xc4200496b0)
	/Users/luke/go/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42008e480, 0x1b209e8, 0xc4200200b8)
	/Users/luke/go/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/Users/luke/go/src/github.com/pulumi/pulumi/main.go:49 +0x4b
```

Note that `pulumi stack` itself does work:

```
$ pulumi stack
Current stack is jens-dev:
    Managed by Lukes-MacBook-Pro.local
    Last updated: 5 days ago (2018-08-13 14:22:03.821878 -0700 PDT)
    Pulumi version: v0.15.1-dev-1534037607-gda616ecc
    Plugin nodejs [language] version: 0.15.1-dev-1534037607-gda616ecc
    Plugin aws [resource] version: 0.14.6-dev-1533615635-g36bed34-dirty

Current stack resources (14):
    TYPE                                             NAME
    pulumi:providers:aws                             default
    pulumi:pulumi:Stack                              jens-jens-dev
    aws-infra:network:Network                        network
    aws:ec2/eip:Eip                                  network-nat-1
    aws:ec2/eip:Eip                                  network-nat-0
    aws:ec2/vpc:Vpc                                  network
    aws:ec2/subnet:Subnet                            network-1
    aws:ec2/subnet:Subnet                            network-0
    aws:ec2/internetGateway:InternetGateway          network
    aws:ec2/subnet:Subnet                            network-nat-0
    aws:ec2/subnet:Subnet                            network-nat-1
    aws:ec2/routeTable:RouteTable                    network
    aws:ec2/routeTableAssociation:RouteTableAssociation network-nat-1
    aws:ec2/routeTableAssociation:RouteTableAssociation network-nat-0

Current stack outputs (0):
    No output values currently in this stack

Use `pulumi stack select` to change stack; `pulumi stack ls` lists known ones
```

**Comment by lukehoban** [comment]
I hit this in another folder, for a project I haven't updated in >1 month.  In that folder every command I try leads to the same/similar crash: `pulumi stack`, `pulumi stack ls`, `pulumi up`, etc.

**Comment by swgillespie** [comment]
> Not clear what is unique about the folder I'm in where this crashes.

The likely explanation is that the folder that you're in has a stack that has never been deployed. I'll have a fix for this shortly.
