### ISSUE TITLE
`up` assertion failure: pkg/resource/deploy/step.go:66

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1790]
I had a bunch of Kubernetes deployment timeouts, which led to my stack being wedged with "this resource failed to initialize" warnings. The recommended way to deal with them is to run `refresh`, which I dutifully did. After doing so, anytime I try to run `up` or `destroy`, the CLI crashes:

```
λ pulumi up
Previewing update of stack 'k8s-guestbook-dev'
Previewing changes:

     Type                 Name                             Plan          Info
 *   pulumi:pulumi:Stack  k8s-guestbook-k8s-guestbook-dev  no change
panic: fatal: An assertion has failed

goroutine 95 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(0x1af0799, 0x17)
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xf3
github.com/pulumi/pulumi/pkg/util/contract.Assert(0x1951500)
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26 +0x49
github.com/pulumi/pulumi/pkg/resource/deploy.NewSameStep(0xc4200b2f00, 0x253d570, 0xc420df7840, 0xc420438c80, 0xc420f02280, 0xc4208d15f0, 0xc420f04120)
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/resource/deploy/step.go:66 +0x6a
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepGenerator).GenerateSteps(0xc4203156e0, 0x253d570, 0xc420df7840, 0x253d570, 0xc420df7840, 0x1, 0x0, 0xc420ba5f00)
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_generator.go:391 +0x1d04
github.com/pulumi/pulumi/pkg/resource/deploy.(*PlanExecutor).handleSingleEvent(0xc4201fddd0, 0x2077200, 0xc420df7840)
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:208 +0x111
github.com/pulumi/pulumi/pkg/resource/deploy.(*PlanExecutor).Execute(0xc4201fddd0, 0xc420838780, 0xc4200b2f00)
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:142 +0xd1
github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk.func1(0x2085f80, 0xc420838780, 0xc420f10580, 0x2082400, 0xc420f10600, 0xa, 0x207e401, 0x207e480, 0xc420838880, 0xc420ddab90, ...)
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/engine/plan.go:213 +0xa7
created by github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/engine/plan.go:211 +0x246
```

The crashing assert is https://github.com/pulumi/pulumi/blob/bee8bb8a78f356c115763bdf0f23d2f83e8c2094/pkg/resource/deploy/step.go#L66

This repros both at current HEAD and in the v0.15.0 release.

Below is the full checkpoint. I will keep this stack alive in case it helps during debugging.

```
{
    "version": 2,
    "deployment": {
        "manifest": {
            "time": "2018-08-19T12:25:00.885571-04:00",
            "magic": "26df1232971091c82f1416be8c68a826272efac2c0a3f4b4417bd1c98a925619",
            "version": "v0.15.1-dev-1534221790-gd83774ca",
            "plugins": [
                {
                    "name": "kubernetes",
                    "path": "/Users/joeduffy/.pulumi/plugins/resource-kubernetes-v0.15.1/pulumi-resource-kubernetes",
                    "type": "resource",
                    "version": "0.15.1"
                }
            ]
        },
        "resources": [
            {
                "urn": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:pulumi:Stack::k8s-guestbook-k8s-guestbook-dev",
                "custom": false,
                "type": "pulumi:pulumi:Stack",
                "dependencies": [],
                "initErrors": null
            },
            {
                "urn": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:providers:kubernetes::default",
                "custom": true,
                "id": "5ac66c65-f113-423b-a894-81bcc8dc2a43",
                "type": "pulumi:providers:kubernetes",
                "inputs": {
                    "version": "0.15.1"
                },
                "dependencies": null,
                "initErrors": null
            },
            {
                "urn": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::kubernetes:core/v1:Service::redis-slave",
                "custom": true,
                "id": "default.redis-slave",
                "type": "kubernetes:core/v1:Service",
                "inputs": {
                    "apiVersion": "v1",
                    "kind": "Service",
                    "metadata": {
                        "labels": {
                            "app": "redis",
                            "role": "slave",
                            "tier": "backend"
                        },
                        "name": "redis-slave"
                    },
                    "spec": {
                        "ports": [
                            {
                                "port": 6379,
                                "targetPort": 6379
                            }
                        ],
                        "selector": {
                            "app": "redis",
                            "role": "slave",
                            "tier": "backend"
                        }
                    }
                },
                "outputs": {
                    "__inputs": {
                        "apiVersion": "v1",
                        "kind": "Service",
                        "metadata": {
                            "labels": {
                                "app": "redis",
                                "role": "slave",
                                "tier": "backend"
                            },
                            "name": "redis-slave"
                        },
                        "spec": {
                            "ports": [
                                {
                                    "port": 6379,
                                    "targetPort": 6379
                                }
                            ],
                            "selector": {
                                "app": "redis",
                                "role": "slave",
                                "tier": "backend"
                            }
                        }
                    },
                    "apiVersion": "v1",
                    "kind": "Service",
                    "metadata": {
                        "creationTimestamp": "2018-08-19T15:52:24Z",
                        "labels": {
                            "app": "redis",
                            "role": "slave",
                            "tier": "backend"
                        },
                        "name": "redis-slave",
                        "namespace": "default",
                        "resourceVersion": "798",
                        "selfLink": "/api/v1/namespaces/default/services/redis-slave",
                        "uid": "ddbdf0c3-a3c7-11e8-838c-025000000001"
                    },
                    "spec": {
                        "clusterIP": "10.98.36.196",
                        "ports": [
                            {
                                "port": 6379,
                                "protocol": "TCP",
                                "targetPort": 6379
                            }
                        ],
                        "selector": {
                            "app": "redis",
                            "role": "slave",
                            "tier": "backend"
                        },
                        "sessionAffinity": "None",
                        "type": "ClusterIP"
                    },
                    "status": {
                        "loadBalancer": {}
                    }
                },
                "parent": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:pulumi:Stack::k8s-guestbook-k8s-guestbook-dev",
                "dependencies": [],
                "initErrors": [],
                "provider": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:providers:kubernetes::default::5ac66c65-f113-423b-a894-81bcc8dc2a43"
            },
            {
                "urn": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::kubernetes:core/v1:Service::frontend",
                "custom": true,
                "id": "default.frontend",
                "type": "kubernetes:core/v1:Service",
                "inputs": {
                    "apiVersion": "v1",
                    "kind": "Service",
                    "metadata": {
                        "labels": {
                            "app": "guestbook",
                            "tier": "frontend"
                        },
                        "name": "frontend"
                    },
                    "spec": {
                        "ports": [
                            {
                                "port": 80
                            }
                        ],
                        "selector": {
                            "app": "guestbook",
                            "tier": "frontend"
                        },
                        "type": "NodePort"
                    }
                },
                "outputs": {
                    "__inputs": {
                        "apiVersion": "v1",
                        "kind": "Service",
                        "metadata": {
                            "labels": {
                                "app": "guestbook",
                                "tier": "frontend"
                            },
                            "name": "frontend"
                        },
                        "spec": {
                            "ports": [
                                {
                                    "port": 80
                                }
                            ],
                            "selector": {
                                "app": "guestbook",
                                "tier": "frontend"
                            },
                            "type": "NodePort"
                        }
                    },
                    "apiVersion": "v1",
                    "kind": "Service",
                    "metadata": {
                        "creationTimestamp": "2018-08-19T15:52:24Z",
                        "labels": {
                            "app": "guestbook",
                            "tier": "frontend"
                        },
                        "name": "frontend",
                        "namespace": "default",
                        "resourceVersion": "795",
                        "selfLink": "/api/v1/namespaces/default/services/frontend",
                        "uid": "ddab701a-a3c7-11e8-838c-025000000001"
                    },
                    "spec": {
                        "clusterIP": "10.106.219.105",
                        "externalTrafficPolicy": "Cluster",
                        "ports": [
                            {
                                "nodePort": 32314,
                                "port": 80,
                                "protocol": "TCP",
                                "targetPort": 80
                            }
                        ],
                        "selector": {
                            "app": "guestbook",
                            "tier": "frontend"
                        },
                        "sessionAffinity": "None",
                        "type": "NodePort"
                    },
                    "status": {
                        "loadBalancer": {
                            "ingress": [
                                {
                                    "hostname": "localhost"
                                }
                            ]
                        }
                    }
                },
                "parent": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:pulumi:Stack::k8s-guestbook-k8s-guestbook-dev",
                "dependencies": [],
                "initErrors": [],
                "provider": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:providers:kubernetes::default::5ac66c65-f113-423b-a894-81bcc8dc2a43"
            },
            {
                "urn": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::kubernetes:core/v1:Service::redis-master",
                "custom": true,
                "id": "default.redis-master",
                "type": "kubernetes:core/v1:Service",
                "inputs": {
                    "apiVersion": "v1",
                    "kind": "Service",
                    "metadata": {
                        "labels": {
                            "app": "redis",
                            "role": "master",
                            "tier": "backend"
                        },
                        "name": "redis-master"
                    },
                    "spec": {
                        "ports": [
                            {
                                "port": 6379,
                                "targetPort": 6379
                            }
                        ],
                        "selector": {
                            "app": "redis",
                            "role": "master",
                            "tier": "backend"
                        }
                    }
                },
                "outputs": {
                    "__inputs": {
                        "apiVersion": "v1",
                        "kind": "Service",
                        "metadata": {
                            "labels": {
                                "app": "redis",
                                "role": "master",
                                "tier": "backend"
                            },
                            "name": "redis-master"
                        },
                        "spec": {
                            "ports": [
                                {
                                    "port": 6379,
                                    "targetPort": 6379
                                }
                            ],
                            "selector": {
                                "app": "redis",
                                "role": "master",
                                "tier": "backend"
                            }
                        }
                    },
                    "apiVersion": "v1",
                    "kind": "Service",
                    "metadata": {
                        "creationTimestamp": "2018-08-19T15:52:24Z",
                        "labels": {
                            "app": "redis",
                            "role": "master",
                            "tier": "backend"
                        },
                        "name": "redis-master",
                        "namespace": "default",
                        "resourceVersion": "788",
                        "selfLink": "/api/v1/namespaces/default/services/redis-master",
                        "uid": "dd99a78e-a3c7-11e8-838c-025000000001"
                    },
                    "spec": {
                        "clusterIP": "10.100.22.170",
                        "ports": [
                            {
                                "port": 6379,
                                "protocol": "TCP",
                                "targetPort": 6379
                            }
                        ],
                        "selector": {
                            "app": "redis",
                            "role": "master",
                            "tier": "backend"
                        },
                        "sessionAffinity": "None",
                        "type": "ClusterIP"
                    },
                    "status": {
                        "loadBalancer": {}
                    }
                },
                "parent": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:pulumi:Stack::k8s-guestbook-k8s-guestbook-dev",
                "dependencies": [],
                "initErrors": [],
                "provider": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:providers:kubernetes::default::5ac66c65-f113-423b-a894-81bcc8dc2a43"
            },
            {
                "urn": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::kubernetes:apps/v1:Deployment::redis-master",
                "custom": true,
                "id": "default.redis-master",
                "type": "kubernetes:apps/v1:Deployment",
                "inputs": {
                    "apiVersion": "apps/v1",
                    "kind": "Deployment",
                    "metadata": {
                        "name": "redis-master"
                    },
                    "spec": {
                        "replicas": 1,
                        "selector": {
                            "matchLabels": {
                                "app": "redis",
                                "role": "master",
                                "tier": "backend"
                            }
                        },
                        "template": {
                            "metadata": {
                                "labels": {
                                    "app": "redis",
                                    "role": "master",
                                    "tier": "backend"
                                }
                            },
                            "spec": {
                                "containers": [
                                    {
                                        "image": "k8s.gcr.io/redis:e2e",
                                        "name": "master",
                                        "ports": [
                                            {
                                                "containerPort": 6379
                                            }
                                        ],
                                        "resources": {
                                            "requests": {
                                                "cpu": "100m",
                                                "memory": "100Mi"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    }
                },
                "outputs": {
                    "__inputs": {
                        "apiVersion": "apps/v1",
                        "kind": "Deployment",
                        "metadata": {
                            "name": "redis-master"
                        },
                        "spec": {
                            "replicas": 1,
                            "selector": {
                                "matchLabels": {
                                    "app": "redis",
                                    "role": "master",
                                    "tier": "backend"
                                }
                            },
                            "template": {
                                "metadata": {
                                    "labels": {
                                        "app": "redis",
                                        "role": "master",
                                        "tier": "backend"
                                    }
                                },
                                "spec": {
                                    "containers": [
                                        {
                                            "image": "k8s.gcr.io/redis:e2e",
                                            "name": "master",
                                            "ports": [
                                                {
                                                    "containerPort": 6379
                                                }
                                            ],
                                            "resources": {
                                                "requests": {
                                                    "cpu": "100m",
                                                    "memory": "100Mi"
                                                }
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "apiVersion": "apps/v1",
                    "kind": "Deployment",
                    "metadata": {
                        "annotations": {
                            "deployment.kubernetes.io/revision": "1"
                        },
                        "creationTimestamp": "2018-08-19T15:52:25Z",
                        "generation": 1,
                        "name": "redis-master",
                        "namespace": "default",
                        "resourceVersion": "1186",
                        "selfLink": "/apis/apps/v1/namespaces/default/deployments/redis-master",
                        "uid": "dde7e77d-a3c7-11e8-838c-025000000001"
                    },
                    "spec": {
                        "progressDeadlineSeconds": 600,
                        "replicas": 1,
                        "revisionHistoryLimit": 10,
                        "selector": {
                            "matchLabels": {
                                "app": "redis",
                                "role": "master",
                                "tier": "backend"
                            }
                        },
                        "strategy": {
                            "rollingUpdate": {
                                "maxSurge": "25%",
                                "maxUnavailable": "25%"
                            },
                            "type": "RollingUpdate"
                        },
                        "template": {
                            "metadata": {
                                "labels": {
                                    "app": "redis",
                                    "role": "master",
                                    "tier": "backend"
                                }
                            },
                            "spec": {
                                "containers": [
                                    {
                                        "image": "k8s.gcr.io/redis:e2e",
                                        "imagePullPolicy": "IfNotPresent",
                                        "name": "master",
                                        "ports": [
                                            {
                                                "containerPort": 6379,
                                                "protocol": "TCP"
                                            }
                                        ],
                                        "resources": {
                                            "requests": {
                                                "cpu": "100m",
                                                "memory": "100Mi"
                                            }
                                        },
                                        "terminationMessagePath": "/dev/termination-log",
                                        "terminationMessagePolicy": "File"
                                    }
                                ],
                                "dnsPolicy": "ClusterFirst",
                                "restartPolicy": "Always",
                                "schedulerName": "default-scheduler",
                                "securityContext": {},
                                "terminationGracePeriodSeconds": 30
                            }
                        }
                    },
                    "status": {
                        "availableReplicas": 1,
                        "conditions": [
                            {
                                "lastTransitionTime": "2018-08-19T15:57:10Z",
                                "lastUpdateTime": "2018-08-19T15:57:10Z",
                                "message": "Deployment has minimum availability.",
                                "reason": "MinimumReplicasAvailable",
                                "status": "True",
                                "type": "Available"
                            },
                            {
                                "lastTransitionTime": "2018-08-19T15:52:25Z",
                                "lastUpdateTime": "2018-08-19T15:57:10Z",
                                "message": "ReplicaSet \"redis-master-55db5f7567\" has successfully progressed.",
                                "reason": "NewReplicaSetAvailable",
                                "status": "True",
                                "type": "Progressing"
                            }
                        ],
                        "observedGeneration": 1,
                        "readyReplicas": 1,
                        "replicas": 1,
                        "updatedReplicas": 1
                    }
                },
                "parent": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:pulumi:Stack::k8s-guestbook-k8s-guestbook-dev",
                "dependencies": [],
                "initErrors": [],
                "provider": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:providers:kubernetes::default::5ac66c65-f113-423b-a894-81bcc8dc2a43"
            },
            {
                "urn": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::kubernetes:apps/v1:Deployment::redis-slave",
                "custom": true,
                "id": "default.redis-slave",
                "type": "kubernetes:apps/v1:Deployment",
                "inputs": {
                    "apiVersion": "apps/v1",
                    "kind": "Deployment",
                    "metadata": {
                        "name": "redis-slave"
                    },
                    "spec": {
                        "replicas": 1,
                        "selector": {
                            "matchLabels": {
                                "app": "redis",
                                "role": "slave",
                                "tier": "backend"
                            }
                        },
                        "template": {
                            "metadata": {
                                "labels": {
                                    "app": "redis",
                                    "role": "slave",
                                    "tier": "backend"
                                }
                            },
                            "spec": {
                                "containers": [
                                    {
                                        "env": [
                                            {
                                                "name": "GET_HOSTS_FROM",
                                                "value": "dns"
                                            }
                                        ],
                                        "image": "gcr.io/google_samples/gb-redisslave:v1",
                                        "name": "slave",
                                        "ports": [
                                            {
                                                "containerPort": 6379
                                            }
                                        ],
                                        "resources": {
                                            "requests": {
                                                "cpu": "100m",
                                                "memory": "100Mi"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    }
                },
                "outputs": {
                    "__inputs": {
                        "apiVersion": "apps/v1",
                        "kind": "Deployment",
                        "metadata": {
                            "name": "redis-slave"
                        },
                        "spec": {
                            "replicas": 1,
                            "selector": {
                                "matchLabels": {
                                    "app": "redis",
                                    "role": "slave",
                                    "tier": "backend"
                                }
                            },
                            "template": {
                                "metadata": {
                                    "labels": {
                                        "app": "redis",
                                        "role": "slave",
                                        "tier": "backend"
                                    }
                                },
                                "spec": {
                                    "containers": [
                                        {
                                            "env": [
                                                {
                                                    "name": "GET_HOSTS_FROM",
                                                    "value": "dns"
                                                }
                                            ],
                                            "image": "gcr.io/google_samples/gb-redisslave:v1",
                                            "name": "slave",
                                            "ports": [
                                                {
                                                    "containerPort": 6379
                                                }
                                            ],
                                            "resources": {
                                                "requests": {
                                                    "cpu": "100m",
                                                    "memory": "100Mi"
                                                }
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "apiVersion": "apps/v1",
                    "kind": "Deployment",
                    "metadata": {
                        "annotations": {
                            "deployment.kubernetes.io/revision": "1"
                        },
                        "creationTimestamp": "2018-08-19T15:52:25Z",
                        "generation": 1,
                        "name": "redis-slave",
                        "namespace": "default",
                        "resourceVersion": "945",
                        "selfLink": "/apis/apps/v1/namespaces/default/deployments/redis-slave",
                        "uid": "ddd6b9c9-a3c7-11e8-838c-025000000001"
                    },
                    "spec": {
                        "progressDeadlineSeconds": 600,
                        "replicas": 1,
                        "revisionHistoryLimit": 10,
                        "selector": {
                            "matchLabels": {
                                "app": "redis",
                                "role": "slave",
                                "tier": "backend"
                            }
                        },
                        "strategy": {
                            "rollingUpdate": {
                                "maxSurge": "25%",
                                "maxUnavailable": "25%"
                            },
                            "type": "RollingUpdate"
                        },
                        "template": {
                            "metadata": {
                                "labels": {
                                    "app": "redis",
                                    "role": "slave",
                                    "tier": "backend"
                                }
                            },
                            "spec": {
                                "containers": [
                                    {
                                        "env": [
                                            {
                                                "name": "GET_HOSTS_FROM",
                                                "value": "dns"
                                            }
                                        ],
                                        "image": "gcr.io/google_samples/gb-redisslave:v1",
                                        "imagePullPolicy": "IfNotPresent",
                                        "name": "slave",
                                        "ports": [
                                            {
                                                "containerPort": 6379,
                                                "protocol": "TCP"
                                            }
                                        ],
                                        "resources": {
                                            "requests": {
                                                "cpu": "100m",
                                                "memory": "100Mi"
                                            }
                                        },
                                        "terminationMessagePath": "/dev/termination-log",
                                        "terminationMessagePolicy": "File"
                                    }
                                ],
                                "dnsPolicy": "ClusterFirst",
                                "restartPolicy": "Always",
                                "schedulerName": "default-scheduler",
                                "securityContext": {},
                                "terminationGracePeriodSeconds": 30
                            }
                        }
                    },
                    "status": {
                        "availableReplicas": 1,
                        "conditions": [
                            {
                                "lastTransitionTime": "2018-08-19T15:53:38Z",
                                "lastUpdateTime": "2018-08-19T15:53:38Z",
                                "message": "Deployment has minimum availability.",
                                "reason": "MinimumReplicasAvailable",
                                "status": "True",
                                "type": "Available"
                            },
                            {
                                "lastTransitionTime": "2018-08-19T15:52:25Z",
                                "lastUpdateTime": "2018-08-19T15:53:38Z",
                                "message": "ReplicaSet \"redis-slave-584c66c5b5\" has successfully progressed.",
                                "reason": "NewReplicaSetAvailable",
                                "status": "True",
                                "type": "Progressing"
                            }
                        ],
                        "observedGeneration": 1,
                        "readyReplicas": 1,
                        "replicas": 1,
                        "updatedReplicas": 1
                    }
                },
                "parent": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:pulumi:Stack::k8s-guestbook-k8s-guestbook-dev",
                "dependencies": [],
                "initErrors": [],
                "provider": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:providers:kubernetes::default::5ac66c65-f113-423b-a894-81bcc8dc2a43"
            },
            {
                "urn": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::kubernetes:apps/v1:Deployment::frontend",
                "custom": true,
                "type": "kubernetes:apps/v1:Deployment",
                "inputs": {
                    "apiVersion": "apps/v1",
                    "kind": "Deployment",
                    "metadata": {
                        "name": "frontend"
                    },
                    "spec": {
                        "replicas": 3,
                        "selector": {
                            "matchLabels": {
                                "app": "guestbook",
                                "tier": "frontend"
                            }
                        },
                        "template": {
                            "metadata": {
                                "labels": {
                                    "app": "guestbook",
                                    "tier": "frontend"
                                }
                            },
                            "spec": {
                                "containers": [
                                    {
                                        "env": [
                                            {
                                                "name": "GET_HOSTS_FROM",
                                                "value": "dns"
                                            }
                                        ],
                                        "image": "gcr.io/google-samples/gb-frontend:v4",
                                        "name": "php-redis",
                                        "ports": [
                                            {
                                                "containerPort": 80
                                            }
                                        ],
                                        "resources": {
                                            "requests": {
                                                "cpu": "100m",
                                                "memory": "100Mi"
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    }
                },
                "outputs": {
                    "__inputs": {
                        "apiVersion": "apps/v1",
                        "kind": "Deployment",
                        "metadata": {
                            "name": "frontend"
                        },
                        "spec": {
                            "replicas": 3,
                            "selector": {
                                "matchLabels": {
                                    "app": "guestbook",
                                    "tier": "frontend"
                                }
                            },
                            "template": {
                                "metadata": {
                                    "labels": {
                                        "app": "guestbook",
                                        "tier": "frontend"
                                    }
                                },
                                "spec": {
                                    "containers": [
                                        {
                                            "env": [
                                                {
                                                    "name": "GET_HOSTS_FROM",
                                                    "value": "dns"
                                                }
                                            ],
                                            "image": "gcr.io/google-samples/gb-frontend:v4",
                                            "name": "php-redis",
                                            "ports": [
                                                {
                                                    "containerPort": 80
                                                }
                                            ],
                                            "resources": {
                                                "requests": {
                                                    "cpu": "100m",
                                                    "memory": "100Mi"
                                                }
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "apiVersion": "apps/v1",
                    "kind": "Deployment",
                    "metadata": {
                        "annotations": {
                            "deployment.kubernetes.io/revision": "1"
                        },
                        "creationTimestamp": "2018-08-19T15:52:25Z",
                        "generation": 1,
                        "name": "frontend",
                        "namespace": "default",
                        "resourceVersion": "1480",
                        "selfLink": "/apis/apps/v1/namespaces/default/deployments/frontend",
                        "uid": "de3e9aff-a3c7-11e8-838c-025000000001"
                    },
                    "spec": {
                        "progressDeadlineSeconds": 600,
                        "replicas": 3,
                        "revisionHistoryLimit": 10,
                        "selector": {
                            "matchLabels": {
                                "app": "guestbook",
                                "tier": "frontend"
                            }
                        },
                        "strategy": {
                            "rollingUpdate": {
                                "maxSurge": "25%",
                                "maxUnavailable": "25%"
                            },
                            "type": "RollingUpdate"
                        },
                        "template": {
                            "metadata": {
                                "labels": {
                                    "app": "guestbook",
                                    "tier": "frontend"
                                }
                            },
                            "spec": {
                                "containers": [
                                    {
                                        "env": [
                                            {
                                                "name": "GET_HOSTS_FROM",
                                                "value": "dns"
                                            }
                                        ],
                                        "image": "gcr.io/google-samples/gb-frontend:v4",
                                        "imagePullPolicy": "IfNotPresent",
                                        "name": "php-redis",
                                        "ports": [
                                            {
                                                "containerPort": 80,
                                                "protocol": "TCP"
                                            }
                                        ],
                                        "resources": {
                                            "requests": {
                                                "cpu": "100m",
                                                "memory": "100Mi"
                                            }
                                        },
                                        "terminationMessagePath": "/dev/termination-log",
                                        "terminationMessagePolicy": "File"
                                    }
                                ],
                                "dnsPolicy": "ClusterFirst",
                                "restartPolicy": "Always",
                                "schedulerName": "default-scheduler",
                                "securityContext": {},
                                "terminationGracePeriodSeconds": 30
                            }
                        }
                    },
                    "status": {
                        "availableReplicas": 3,
                        "conditions": [
                            {
                                "lastTransitionTime": "2018-08-19T16:01:18Z",
                                "lastUpdateTime": "2018-08-19T16:01:18Z",
                                "message": "Deployment has minimum availability.",
                                "reason": "MinimumReplicasAvailable",
                                "status": "True",
                                "type": "Available"
                            },
                            {
                                "lastTransitionTime": "2018-08-19T15:52:25Z",
                                "lastUpdateTime": "2018-08-19T16:01:18Z",
                                "message": "ReplicaSet \"frontend-5c548f4769\" has successfully progressed.",
                                "reason": "NewReplicaSetAvailable",
                                "status": "True",
                                "type": "Progressing"
                            }
                        ],
                        "observedGeneration": 1,
                        "readyReplicas": 3,
                        "replicas": 3,
                        "updatedReplicas": 3
                    }
                },
                "parent": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:pulumi:Stack::k8s-guestbook-k8s-guestbook-dev",
                "dependencies": [],
                "initErrors": [],
                "provider": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::pulumi:providers:kubernetes::default::5ac66c65-f113-423b-a894-81bcc8dc2a43"
            }
        ]
    }
}
```

**Comment by joeduffy** [comment]
The problem was this resource:

```
            {
                "urn": "urn:pulumi:k8s-guestbook-dev::k8s-guestbook::kubernetes:apps/v1:Deployment::frontend",
                "custom": true,
                "type": "kubernetes:apps/v1:Deployment",
                "inputs": {
                    "apiVersion": "apps/v1",
                    "kind": "Deployment",
                    "metadata": {
                        "name": "frontend"
                    },
```

Notice that it is missing an ID. I manually gave it one, which I gather should have been

```
                "id": "default.frontend",
```

and all is well again.

I have no idea how this resource lost its ID. If I had to guess, since the `refresh` succeeded -- implying it used to have an ID -- the Kubernetes provider is dropping the ID on `Read` somehow. So, @hausdorff, this might end up being yours. In either case, however, the engine probably ought to be defensive against ill-behaved providers, and use a dynamic failure rather than assert here.

**Comment by lukehoban** [comment]
Hit this as well today during live stream - you can watch the results here: https://youtu.be/u0aSHhfUnMc?t=34m17s

**Comment by hausdorff** [comment]
I think there is an 80% probability this is something bad happening in the Kubernetes provider. We should never exit without returning an ID. If we do, it's either a control flow bug or a `panic`, and I think the latter is more likely.

I'll take a look.

**Comment by hausdorff** [comment]
Ok I've sat down to look at this and I believe this is no longer an issue. Let's close it for now.
