### ISSUE TITLE
[sdk/nodejs] Using a Provider function as part of a static member on a class will cause an RPC provider to fail to start

### ISSUE THREAD

**Issue by Makeshift** [pulumi/pulumi#18013]
### What happened?

I'm currently attempting to adapt some component resources into a fully-fledged Pulumi provider, so they can be used in languages other than TS, and I came across this edge case. 

The following component works fine in a TS-based Pulumi program:

```ts
import * as pulumi from '@pulumi/pulumi'
import * as aws from '@pulumi/aws'

export class MyComponent extends pulumi.ComponentResource {
  static test = aws.iam.getPolicyDocument({})
}
```

However, if you try and wrap that component into a provider and then try to start the RPC server with `await pulumi.provider.main(new Provider(...))`, it will throw this error:

```
error: [runtime] TypeError: Cannot read properties of undefined (reading 'invoke')
    at /home/connor/echobox/repos/pulumi-provider-echobox/node_modules/@pulumi/runtime/invoke.ts:271:25
    at new Promise (<anonymous>)
    at /home/connor/echobox/repos/pulumi-provider-echobox/node_modules/@pulumi/runtime/invoke.ts:270:13
    at Generator.next (<anonymous>)
    at fulfilled (/home/connor/echobox/repos/pulumi-provider-echobox/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
```

Note that the RPC server will throw that error _on startup_, ie immediately after starting. It will still output a port so you can try and interact with it, but it'll just throw the same error again when you do.

### Example

See above

### Output of `pulumi about`

```
CLI
Version      3.138.0
Go Version   go1.23.2
Go Compiler  gc

Host
OS       ubuntu
Version  24.04
Arch     x86_64
```

### Additional context

Presumably, because it's a `static` member, it tries to resolve it as soon as the interpreter comes across it, which in the case of an RPC provider is long before it's able to start making invoke requests to other providers, hence the failed invoke.

It makes sense why this doesn't work, but because it happens _during interpretation_ I found it quite hard to debug and find, and the thrown error message didn't help much. I was very confused as to why just importing a module that contained this (not even using or exposing anything from it!) was causing my provider to suddenly stop starting properly.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for the issue @Makeshift. I suspect we can improve the error in such cases so it's more obvious where the problem is.
