### ISSUE TITLE
`TypeError: Cannot convert object to primitive value` hides all errors in pulumi program

### ISSUE THREAD

**Issue by rulatir** [pulumi/pulumi#18068]
### What happened?

Figuring out problems with one's pulumi code is a nightmare because all we ever see is this:

```
error: Running program '/path/to/project/index.ts' failed with an unhandled exception:
TypeError: Cannot convert object to primitive value
    at process.uncaughtHandler (/path/to/project/node_modules/.pnpm/@pulumi+pulumi@3.134.1_typescript@5.6.2/node_modules/@pulumi/cmd/run/run.ts:309:65)
    at process.emit (node:events:532:35)
    at emitUnhandledRejection (node:internal/process/promises:250:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Actual errors thrown by our code, or typescript compilation errors, are completely hidden by this error, which is identical in every case. But it is definitely correlated with errors in Pulumi program: I've run into it routinely when introducing syntax errors by accident. Unfortunately it's not just about syntax errors, i.e. something that the IDE would warn me about anyway.

### Example

In order to create a reproducible example, I would first need a basic understanding of what's wrong. This issue prevents me from gathering that understanding. It's an unknown unknown.

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.142.0
Go Version   go1.23.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.54.1
resource  aws     6.39.0
resource  awsx    2.16.0
resource  awsx    2.11.0
resource  docker  4.5.6
resource  docker  4.5.4
resource  docker  3.6.1
resource  docker  3.6.1
language  nodejs  unknown

Host     
OS       arch
Version  "rolling"
Arch     x86_64

This project is written in nodejs: executable='/home/rulatir/projects/zaffre/internment/nave/store/installed/node-modern/bin/node' version='v22.2.0'

[stack-related info omitted]

Dependencies:
NAME               VERSION
@types/express     4.17.17
@types/lodash      4.14.196
aws-sdk            2.1632.0
pnpm               7.26.0
sitemap-generator  8.5.1
yaml               2.4.2

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rulatir** [comment]
I am aware of [this comment](https://github.com/pulumi/docs/issues/9466#issuecomment-2429480495). Switching to `tsx` does not resolve the issue for me.

**Comment by julienp** [comment]
Thanks for reporting the issue, that is super frustrating to debug!

It looks to me like something is throwing something that does not have a toString method, which causes our error handler to throw this very unhelpful message.

We will fix the error handler to handle this case more gracefully, and that should then reveal the actual error cause.

**Comment by scythargon** [comment]
Hello, guys! I'm still encountering the same error a year later in latest pulumi (automation) `3.153.1` in NodeJS `20.18.1`.

```
error: [runtime] Unhandled exception: TypeError: Cannot convert object to primitive value
    at process.<anonymous> (/Users/argon/code/04-gitlab-api/fargate/node_modules/@pulumi/automation/server.ts:164:60)
    at process.emit (node:events:518:28)
    at process.emit (node:domain:489:12)
    at process.emit.sharedData.processEmitHook.installedValue (/Users/argon/code/04-gitlab-api/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
    at processEmit [as emit] (/Users/argon/code/04-gitlab-api/fargate/node_modules/execa/node_modules/signal-exit/index.js:199:34)
    at emitUnhandledRejection (node:internal/process/promises:250:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
TypeError: Cannot convert object to primitive value
    at LanguageServer.<anonymous> (/Users/argon/code/04-gitlab-api/fargate/node_modules/@pulumi/automation/server.ts:129:81)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/argon/code/04-gitlab-api/fargate/node_modules/@pulumi/pulumi/automation/server.js:18:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
```

my dependencies:

```
yarn list --pattern "@pulumi|@aws-sdk"                                                                                                                                                        
yarn list v1.22.22
├─ @aws-sdk/client-cloudwatch-logs@3.758.0
├─ @aws-sdk/client-ecs@3.758.0
├─ @aws-sdk/client-sso@3.758.0
├─ @aws-sdk/core@3.758.0
├─ @aws-sdk/credential-provider-env@3.758.0
├─ @aws-sdk/credential-provider-http@3.758.0
├─ @aws-sdk/credential-provider-ini@3.758.0
├─ @aws-sdk/credential-provider-node@3.758.0
├─ @aws-sdk/credential-provider-process@3.758.0
├─ @aws-sdk/credential-provider-sso@3.758.0
├─ @aws-sdk/credential-provider-web-identity@3.758.0
├─ @aws-sdk/middleware-host-header@3.734.0
├─ @aws-sdk/middleware-logger@3.734.0
├─ @aws-sdk/middleware-recursion-detection@3.734.0
├─ @aws-sdk/middleware-user-agent@3.758.0
├─ @aws-sdk/nested-clients@3.758.0
├─ @aws-sdk/region-config-resolver@3.734.0
├─ @aws-sdk/token-providers@3.758.0
├─ @aws-sdk/types@3.734.0
├─ @aws-sdk/util-endpoints@3.743.0
├─ @aws-sdk/util-locate-window@3.723.0
├─ @aws-sdk/util-user-agent-browser@3.734.0
├─ @aws-sdk/util-user-agent-node@3.758.0
├─ @pulumi/aws-native@0.105.0
├─ @pulumi/aws@6.70.1
├─ @pulumi/awsx@2.21.0
├─ @pulumi/docker-build@0.0.8
├─ @pulumi/docker@4.6.1
├─ @pulumi/pulumi@3.153.1
├─ @pulumi/query@0.3.0
└─ @pulumi/random@4.18.0
✨  Done in 0.17s.
```
