### ISSUE TITLE
Setting `PULUMI_DEBUG_PROVIDERS` to connect to a local provider server breaks nested providers used within it

### ISSUE THREAD

**Issue by Makeshift** [pulumi/pulumi#18112]
### What happened?

I'm creating a component provider which sources most of its resources from the AWS provider. As part of developing/debugging my component provider, I occasionally run it directly and then use `PULUMI_DEBUG_PROVIDERS=<provider>:<port>` to attach to it.

My provider has a resource that invokes the AWS provider as part of its constructor, something along the lines of:

```ts
export class Repository extends pulumi.ComponentResource {
  constructor(name: string, args: RepositoryOpts, opts?: pulumi.ComponentResourceOptions) {
    super('echobox:ecr:repository', name, args, opts)

    const accountId = aws.getCallerIdentityOutput({}, { parent: this }).accountId
  }
}
```

I have the following simple YAML project to test out the provider with:

```yaml
name: servicename-example
runtime: yaml
resources:
  my-ecr-repo:
    type: echobox:ecr:repository
    properties:
      tags:
        foobar: baz

```

Attempting to deploy it like so: `PULUMI_DEBUG_PROVIDERS="echobox:55665" pulumi up`

I receive the following error:
```
Diagnostics:
  pulumi:pulumi:Stack (servicename-example-dev):
    error: echobox:ecr:repository resource 'my-ecr-repo' has a problem: Cannot read properties of undefined (reading 'invoke')
    error: TypeError: Cannot read properties of undefined (reading 'invoke')
        at /home/connor/echobox/repos/infrastructure-common-sdk/node_modules/@pulumi/aws/node_modules/@pulumi/runtime/invoke.ts:261:25
        at new Promise (<anonymous>)
        at /home/connor/echobox/repos/infrastructure-common-sdk/node_modules/@pulumi/aws/node_modules/@pulumi/runtime/invoke.ts:260:13
        at Generator.next (<anonymous>)
        at fulfilled (/home/connor/echobox/repos/pulumi-provider-echobox/dist/provider.cjs:371389:28)
        at processTicksAndRejections (node:internal/process/task_queues:105:5)
    error: TypeError: Cannot read properties of undefined (reading 'invoke')
        at /home/connor/echobox/repos/infrastructure-common-sdk/node_modules/@pulumi/aws/node_modules/@pulumi/runtime/invoke.ts:261:25
        at new Promise (<anonymous>)
        at /home/connor/echobox/repos/infrastructure-common-sdk/node_modules/@pulumi/aws/node_modules/@pulumi/runtime/invoke.ts:260:13
        at Generator.next (<anonymous>)
        at fulfilled (/home/connor/echobox/repos/pulumi-provider-echobox/dist/provider.cjs:371389:28)
        at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

### Example

Pretty much the best I can do is the above. If needed I can potentially put together a reproduction repo, but I think it's possible I've just misunderstood something.

### Output of `pulumi about`

```
CLI
Version      3.144.1
Go Version   go1.23.4
Go Compiler  gc

Plugins
KIND      NAME     VERSION
resource  echobox  unknown
language  yaml     1.13.0

Host
OS       ubuntu
Version  24.04
Arch     x86_64

This project is written in yaml

Current Stack: echobox/servicename-example/dev

TYPE                                       URN
pulumi:pulumi:Stack                        urn:pulumi:dev::servicename-example::pulumi:pulumi:Stack::servicename-example-dev
pulumi:providers:echobox                   urn:pulumi:dev::servicename-example::pulumi:providers:echobox::default
ebx:component:repository/my-ecr-repo       urn:pulumi:dev::servicename-example::ebx:component:repository/my-ecr-repo::my-ecr-repo
pulumi:providers:aws                       urn:pulumi:dev::servicename-example::pulumi:providers:aws::default_6_65_0
aws:ecr/repository:Repository              urn:pulumi:dev::servicename-example::ebx:component:repository/my-ecr-repo$aws:ecr/repository:Repository::my-ecr-repo
aws:ecr/repositoryPolicy:RepositoryPolicy  urn:pulumi:dev::servicename-example::ebx:component:repository/my-ecr-repo$aws:ecr/repositoryPolicy:RepositoryPolicy::my-ecr-repo-repositoryPolicy
aws:ecr/lifecyclePolicy:LifecyclePolicy    urn:pulumi:dev::servicename-example::ebx:component:repository/my-ecr-repo$aws:ecr/lifecyclePolicy:LifecyclePolicy::my-ecr-repo-lifecyclePolicy


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/Makeshift
User           Makeshift
Organizations  Makeshift, echobox
Token type     personal

Dependencies:
NAME     VERSION
echobox
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Makeshift** [comment]
I suspect that this _might_ be due to a race condition causing the wrong error to bubble up. It might be that my provider is actually crashing/throwing an error at some point, which then causes Pulumi to start shutting down providers, so the queued invoke then fails.

I'm not sure this is actually the case, but it sort of feels that way. I'll see if I can find some debug logs that show it.
