### ISSUE TITLE
An assertion has failed: Module member token 'A:B' missing module member delimiter

### ISSUE THREAD

**Issue by protometa** [pulumi/pulumi#1820]
I have some custom `ComponentResource`s in my stack (e.g. `gummi:GitLabRunner`). After upgrading to `0.15.0` I get the following on `pulumi up`:

```
Previewing update of stack 'aws-dev'
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v0.15.0
Go Version:       go1.9
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: An assertion has failed: Module member token 'gummi:GitLabRunner' missing module member delimiter

goroutine 1 [running]:
runtime/debug.Stack(0xc4203861b0, 0x1950360, 0xc4210d4290)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/debug/stack.go:24 +0xa7
main.panicHandler()
	/Users/travis/gopath/src/github.com/pulumi/pulumi/main.go:30 +0x71
panic(0x1950360, 0xc4210d4290)
	/Users/travis/.gimme/versions/go1.9.darwin.amd64/src/runtime/panic.go:491 +0x283
github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc421100070, 0x61)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xf3
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0x19e0e00, 0x1b0bc7b, 0x38, 0xc4203863c0, 0x1, 0x1)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x13d
github.com/pulumi/pulumi/pkg/tokens.ModuleMember.Module(0xc420014c55, 0x12, 0x1adaf5f, 0x1)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/tokens/tokens.go:204 +0xd4
github.com/pulumi/pulumi/pkg/tokens.Type.Module(0xc420014c55, 0x12, 0x1, 0x1)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/tokens/tokens.go:268 +0xa9
github.com/pulumi/pulumi/pkg/resource/deploy/providers.IsProviderType(0xc420014c55, 0x12, 0xc420014c55)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/providers/reference.go:37 +0x39
github.com/pulumi/pulumi/pkg/resource/deploy.addDefaultProviders(0xc420b67aa0, 0x20895c0, 0xc4208b4320, 0xc420b6c080, 0x8, 0xc4210d8320)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan.go:114 +0x32e
github.com/pulumi/pulumi/pkg/resource/deploy.NewPlan(0xc420222800, 0xc420b67aa0, 0xc420b6c080, 0x20895c0, 0xc4208b4320, 0x0, 0x0, 0x0, 0x1, 0xc420b74000, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan.go:180 +0xa9
github.com/pulumi/pulumi/pkg/engine.plan(0xc420b67b90, 0xc4208a2f00, 0x21651e8, 0x0, 0x0, 0xa, 0x0, 0x0, 0x0, 0x1b1e510, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/plan.go:153 +0x627
github.com/pulumi/pulumi/pkg/engine.update(0xc420b67b90, 0xc4208a2f00, 0x21651e8, 0x0, 0x0, 0xa, 0x0, 0x0, 0x0, 0x1b1e510, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/update.go:129 +0xa0
github.com/pulumi/pulumi/pkg/engine.Update(0x2084380, 0xc420b6c100, 0xc420b67b90, 0x21651e8, 0x0, 0x0, 0xa, 0x0, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/update.go:81 +0x2a2
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).runEngineAction(0xc4202b9aa0, 0x2087fc0, 0xc420082008, 0x1adebad, 0x6, 0x2082ec0, 0xc42051e420, 0xc420207560, 0xc420579c40, 0x29, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:956 +0x93a
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).updateStack(0xc4202b9aa0, 0x2087fc0, 0xc420082008, 0x1adebad, 0x6, 0x208d080, 0xc42082c7d0, 0xc420207560, 0xc420579c40, 0x29, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:874 +0x420
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).PreviewThenPrompt(0xc4202b9aa0, 0x2087fc0, 0xc420082008, 0x1adebad, 0x6, 0x208d080, 0xc42082c7d0, 0xc420207560, 0xc420579c40, 0x29, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:655 +0x393
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).PreviewThenPromptThenExecute(0xc4202b9aa0, 0x2087fc0, 0xc420082008, 0x1adebad, 0x6, 0x2082ec0, 0xc420d71290, 0xc420207560, 0xc420579c40, 0x29, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:734 +0x18c
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).Update(0xc4202b9aa0, 0x2087fc0, 0xc420082008, 0x2082ec0, 0xc420d71290, 0xc420207560, 0xc420579c40, 0x29, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:767 +0x124
github.com/pulumi/pulumi/pkg/backend.UpdateStack(0x2087fc0, 0xc420082008, 0x208d080, 0xc42082c0f0, 0xc420207560, 0xc420579c40, 0x29, 0x0, 0x0, 0xc420d713b0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/stack.go:77 +0x163
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudStack).Update(0xc42082c0f0, 0x2087fc0, 0xc420082008, 0xc420207560, 0xc420579c40, 0x29, 0x0, 0x0, 0xc420d713b0, 0x21651e8, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/cloud/stack.go:120 +0x101
github.com/pulumi/pulumi/cmd.newUpCmd.func1(0x21651e8, 0x0, 0x0, 0xa, 0x0, 0x0, 0x0, 0x1added5, 0x6, 0x100000000, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/cmd/up.go:78 +0x2f3
github.com/pulumi/pulumi/cmd.newUpCmd.func3(0xc4200118c0, 0x21651e8, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/cmd/up.go:277 +0x319
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc4200118c0, 0x21651e8, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:92 +0x5a
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200118c0, 0x21651e8, 0x0, 0x0, 0xc4200118c0, 0x21651e8)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200786c0, 0xc4204dbd68, 0xc4200775c0, 0xc420077700)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200786c0, 0x1b1fab8, 0xc420074058)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/Users/travis/gopath/src/github.com/pulumi/pulumi/main.go:49 +0x4b
```

Output of `npm ls | grep pulumi`:

```
├─┬ @pulumi/aws@0.15.0
│ ├── @pulumi/pulumi@0.15.0 deduped
├─┬ @pulumi/kubernetes@0.15.0
│ ├── @pulumi/pulumi@0.15.0 deduped
├─┬ @pulumi/pulumi@0.15.0
```

**Comment by swgillespie** [comment]
Thanks for the report - the engine requires that these resource types have a specific format but it looks like we don't enforce it anywhere.

**Comment by protometa** [comment]
Is the expected format `*:*:*`? I edited my stack to change these from `gummi:GitLabRunner` to `gummi:component:GitLabRunner`. It gets a bit further but still ultimately fails with a similar error:

```
Previewing update of stack 'aws-dev'
Previewing changes:

     Type                 Name                     Plan          Info
 *   pulumi:pulumi:Stack  gummicube-infra-aws-dev  no change
panic: fatal: An assertion has failed: Module member token 'gummi:GitLabRunner' missing module member delimiter

goroutine 118 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc4201f8cb0, 0x61)
	/private/tmp/pulumi-20180816-55386-whrdjz/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xe9
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0x1975900, 0x1aa61fe, 0x38, 0xc4209a68c0, 0x1, 0x1)
	/private/tmp/pulumi-20180816-55386-whrdjz/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x126
github.com/pulumi/pulumi/pkg/tokens.ModuleMember.Module(0xc42003f925, 0x12, 0x1520f00, 0xc42003f925)
	/private/tmp/pulumi-20180816-55386-whrdjz/src/github.com/pulumi/pulumi/pkg/tokens/tokens.go:204 +0xca
github.com/pulumi/pulumi/pkg/tokens.Type.Module(0xc42003f925, 0x12, 0x1, 0x1)
	/private/tmp/pulumi-20180816-55386-whrdjz/src/github.com/pulumi/pulumi/pkg/tokens/tokens.go:268 +0x8d
github.com/pulumi/pulumi/pkg/resource/deploy/providers.IsProviderType(0xc42003f925, 0x12, 0xc42003f925)
	/private/tmp/pulumi-20180816-55386-whrdjz/src/github.com/pulumi/pulumi/pkg/resource/deploy/providers/reference.go:37 +0x39
github.com/pulumi/pulumi/pkg/engine.isDefaultProviderStep(0x1b6ace0, 0xc420f26be0, 0xc42003f900)
	/private/tmp/pulumi-20180816-55386-whrdjz/src/github.com/pulumi/pulumi/pkg/engine/plan.go:367 +0x6f
github.com/pulumi/pulumi/pkg/engine.(*planActions).OnResourceStepPre(0xc42107e280, 0x1b6ace0, 0xc420f26be0, 0xc4209a6b90, 0x100fc39, 0x19621a0, 0x68ec40)
	/private/tmp/pulumi-20180816-55386-whrdjz/src/github.com/pulumi/pulumi/pkg/engine/plan.go:286 +0x5d0
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).executeStep(0xc4202af290, 0x1, 0x1b6ace0, 0xc420f26be0, 0x11d06f1, 0xc420f6ff58)
	/private/tmp/pulumi-20180816-55386-whrdjz/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:197 +0xbcf
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).executeChain(0xc4202af290, 0x1, 0xc4208aea30, 0x1, 0x1)
	/private/tmp/pulumi-20180816-55386-whrdjz/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:157 +0xe8
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).worker(0xc4202af290, 0x1)
	/private/tmp/pulumi-20180816-55386-whrdjz/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:279 +0x13a
created by github.com/pulumi/pulumi/pkg/resource/deploy.newStepExecutor
	/private/tmp/pulumi-20180816-55386-whrdjz/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:302 +0x195
```

Is there some way to migrate?

**Comment by protometa** [comment]
nvm I hadn't saved all open files from my sublime replace command heh. Changing to `*.*.*` format in stack and code worked.

**Comment by swgillespie** [comment]
> nvm I hadn't saved all open files from my sublime replace command heh. Changing to *:*:* format in stack and code worked.

Awesome!

**Comment by swgillespie** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/1904.

**Comment by lukehoban** [comment]
The fix in #1904 only applied to `CustomResource`s, not `ComponentResource`s.  Since this and #1880 were about `ComponentResource`, re-opening this so we continue to track the issue here.

**Comment by cnunciato** [comment]
I hit this today with `v1.0.0` and a `ComponentResource`. Here's a program program that repros:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

class MyComponent extends pulumi.ComponentResource {

    constructor(name: string) {
        super("myapp:MyComponent", name);

        aws.cloudwatch.onSchedule("schedule", "rate(1 minute)", event => {
            console.log(event);
        });
    }
}

const myComp = new MyComponent("comp");
```

```
$ pulumi up --yes --skip-preview && pulumi logs
...
Collecting logs for stack dev since 2019-09-10T15:11:56.000-07:00.

panic: fatal: An assertion has failed: Module member token 'myapp:MyComponent' missing module member delimiter
```

**Comment by joeduffy** [comment]
This no longer panics, and we seem to accept the looser format now. If we want to ensure the `*:*:*` format, we'll need to implement #4695, but at this point, the engine seems to accept the format in @cnunciato's repro above without panic/error.
