### ISSUE TITLE
Flaky test: 018.logging

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1835]
```
  1) rpc run test: logging (pwd=undefined,prog=/home/travis/gopath/src/github.com/pulumi/pulumi/sdk/nodejs/bin/tests/runtime/langhost/cases/018.logging):
      AssertionError [ERR_ASSERTION]: Expected an error of ""; got "Program exited with non-zero exit code: 1"
      + expected - actual
      -Program exited with non-zero exit code: 1
      
      at Object.<anonymous> (bin/tests/runtime/langhost/run.spec.js:565:24)
      at Generator.next (<anonymous>)
      at fulfilled (bin/tests/runtime/langhost/run.spec.js:17:58)
      at <anonymous>
```

Not sure what the issue is yet.

**Comment by swgillespie** [comment]
Closing this because I think the issue might be fixed - if it persists, we can re-open the issue.
