### ISSUE TITLE
Failing test: 005.resource_thens

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#1862]
https://travis-ci.com/pulumi/pulumi/jobs/143280222

```
 1) rpc run test: resource_thens (pwd=undefined,prog=/home/travis/gopath/src/github.com/pulumi/pulumi/sdk/nodejs/bin/tests/runtime/langhost/cases/005.resource_thens):
      AssertionError [ERR_ASSERTION]: Expected an error of ""; got "Program exited with non-zero exit code: 1"
      + expected - actual
      -Program exited with non-zero exit code: 1
      
      at Object.<anonymous> (bin/tests/runtime/langhost/run.spec.js:565:24)
      at Generator.next (<anonymous>)
      at fulfilled (bin/tests/runtime/langhost/run.spec.js:17:58)
      at <anonymous>
```

@swgillespie assigning to you as it looks similar to #1835

**Comment by justinvp** [comment]
Another similar failure:

https://travis-ci.com/pulumi/pulumi/jobs/143705051

```
  1) rpc run test: ten_complex_resources (pwd=undefined,prog=/home/travis/gopath/src/github.com/pulumi/pulumi/sdk/nodejs/bin/tests/runtime/langhost/cases/004.ten_complex_resources):
      AssertionError [ERR_ASSERTION]: Expected an error of ""; got "Program exited with non-zero exit code: 1"
      + expected - actual
      -Program exited with non-zero exit code: 1
      
      at Object.<anonymous> (bin/tests/runtime/langhost/run.spec.js:584:24)
      at Generator.next (<anonymous>)
      at fulfilled (bin/tests/runtime/langhost/run.spec.js:17:58)
      at <anonymous>
```

**Comment by swgillespie** [comment]
I'm reasonably sure this is the same as https://github.com/pulumi/pulumi/issues/1835, closing as a dupe.
