### ISSUE TITLE
Module member token 'foo:Bar' missing module member delimiter

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#1880]
I've been adding my own component 

```
export class HttpFunction extends pulumi.ComponentResource {
    constructor(name: string, handler: AzureFunctionHandler, options?: pulumi.ResourceOptions) {
        super("azure:HttpFunction", name, {}, options);
```

and it worked fine in `0.14`. Now I upgraded to `0.15` and started getting errors

```
Pulumi Version:   v0.15.0
Go Version:       go1.10
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            fatal: An assertion has failed: Module member token 'azure:HttpFunction' missing module member delimiter

goroutine 1 [running]:
runtime/debug.Stack(0xc042776330, 0xd24b00, 0xc042e38870)
        C:/go/src/runtime/debug/stack.go:24 +0xae
main.panicHandler()
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/main.go:30 +0x78
panic(0xd24b00, 0xc042e38870)
        C:/go/src/runtime/panic.go:505 +0x237
github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc0420344d0, 0x61)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xf0
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xdb8100, 0xeee522, 0x38, 0xc042776538, 0x1, 0x1)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x12d
github.com/pulumi/pulumi/pkg/tokens.ModuleMember.Module(0xc042e00228, 0x12, 0x939100, 0xc042e00228)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/tokens/tokens.go:204 +0xd1
github.com/pulumi/pulumi/pkg/tokens.Type.Module(0xc042e00228, 0x12, 0x1, 0x1)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/tokens/tokens.go:268 +0x94
github.com/pulumi/pulumi/pkg/resource/deploy/providers.IsProviderType(0xc042e00228, 0x12, 0xc042e00228)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/providers/reference.go:37 +0x40
github.com/pulumi/pulumi/pkg/resource/deploy.addDefaultProviders(0xc042e30f00, 0xfaea60, 0xc042e23680, 0xc0420f6e80, 0x8
, 0xc0420db1d0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan.go:114 +0x2de
github.com/pulumi/pulumi/pkg/resource/deploy.NewPlan(0xc04223ea80, 0xc042e30f00, 0xc0420f6e80, 0xfaea60, 0xc042e23680, 0
x0, 0x0, 0x0, 0x1, 0xc042077a40, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan.go:180 +0xaa
github.com/pulumi/pulumi/pkg/engine.plan(0xc042e30ff0, 0xc042e235e0, 0x0, 0x0, 0x0, 0xa, 0x0, 0x0, 0x0, 0xf01208, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/engine/plan.go:153 +0x577
github.com/pulumi/pulumi/pkg/engine.update(0xc042e30ff0, 0xc042e235e0, 0x0, 0x0, 0x0, 0xa, 0x0, 0x0, 0x0, 0xf01208, ...)

        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/engine/update.go:129 +0x9a
github.com/pulumi/pulumi/pkg/engine.Refresh(0xfa97e0, 0xc0420f6f00, 0xc042e30ff0, 0x0, 0x0, 0x0, 0xa, 0x0, 0x0, 0x0, ...
)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/engine/refresh.go:37 +0x29b
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).runEngineAction(0xc042267200, 0xfad0a0, 0xc042084090, 0xebf6e
1, 0x7, 0xfa7220, 0xc0423d2900, 0xc0422bc090, 0xc04202b1d0, 0x28, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:958 +0x9eb
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).updateStack(0xc042267200, 0xfad0a0, 0xc042084090, 0xebf6e1, 0
x7, 0xfb5200, 0xc0420db040, 0xc0422bc090, 0xc04202b1d0, 0x28, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:874 +0x402
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).PreviewThenPrompt(0xc042267200, 0xfad0a0, 0xc042084090, 0xebf
6e1, 0x7, 0xfb5200, 0xc0420db040, 0xc0422bc090, 0xc04202b1d0, 0x28, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:655 +0x377
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).PreviewThenPromptThenExecute(0xc042267200, 0xfad0a0, 0xc04208
4090, 0xebf6e1, 0x7, 0xfa7220, 0xc042608690, 0xc0422bc090, 0xc04202b1d0, 0x28, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:734 +0x193
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).Refresh(0xc042267200, 0xfad0a0, 0xc042084090, 0xfa7220, 0xc04
2608690, 0xc0422bc090, 0xc04202b1d0, 0x28, 0x0, 0x0, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:773 +0x12b
github.com/pulumi/pulumi/pkg/backend.RefreshStack(0xfad0a0, 0xc042084090, 0xfb5200, 0xc0423a8c30, 0xc0422bc090, 0xc04202
b1d0, 0x28, 0x0, 0x0, 0xc042608780, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/stack.go:83 +0x16a
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudStack).Refresh(0xc0423a8c30, 0xfad0a0, 0xc042084090, 0xc0422bc090, 0xc
04202b1d0, 0x28, 0x0, 0x0, 0xc042608780, 0x0, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/stack.go:125 +0x108
github.com/pulumi/pulumi/cmd.newRefreshCmd.func1(0xc042499440, 0x1548700, 0x0, 0x0, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/cmd/refresh.go:99 +0x4eb
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc042499440, 0x1548700, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:92 +0x61
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute(0xc042499440, 0x1548700, 0x0, 0x0, 0xc04249944
0, 0x1548700)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:702 +0x2cd
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc04212e000, 0xc0426f9c90, 0xc042079670, 0xc
042079770)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:783 +0x2eb
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute(0xc04212e000, 0xf028b0, 0x404083)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:736 +0x32
main.main()
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/main.go:49 +0x52
```

Why is that?

**Comment by lukehoban** [comment]
This is the same as .  There is a requirement currently that Pulumi types be in the format `A:B:C` (three parts), but this is not correctly enforced early - and currently leads to asserts at other layers.  We expect to both fix the assert as well as loosen the requirement.

**Comment by mikhailshilkov** [comment]
@lukehoban  Are the examples like https://github.com/pulumi/examples/blob/master/azure-ts-functions/azureFunction.ts#L59 wrong then?

**Comment by swgillespie** [comment]
@mikhailshilkov Very possible. I'm fixing this bug so I'll do a run-through of those examples today.
