### ISSUE TITLE
Panic using `pulumi.asset.FileArchive` with `aws.lambda.Function`

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi#1953]
An issue was reported in the community chat by @joaoasrosa where the following code resulted in a panic when running `pulumi up`:

```ts
    const lambda = new aws.lambda.Function("lambda", {
        description: "Dummy API Endpoint",
        runtime: aws.lambda.DotnetCore2d1Runtime,
        code: new pulumi.asset.FileArchive("./artifacts/Lambda.zip"),
        timeout: 5,
        handler: "Lambda::Lambda.Function::Handler",
        role: role.arn,
        tags: {
            environment: stackConfig.require("environment")
        }
    });
```

```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11ebc72]

goroutine 242 [running]:
github.com/pulumi/pulumi/pkg/util/contract.IgnoreClose(0x0, 0x0)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/pkg/util/contract/ignore.go:33 +0x22
panic(0x197cd20, 0x2331150)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/pulumi/pulumi/pkg/resource.addNextFileToTar(0x0, 0x0, 0xc000ba2700, 0xc000f6ef70, 0x0, 0x0)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/pkg/resource/asset.go:900 +0x45
github.com/pulumi/pulumi/pkg/resource.(*Archive).archiveTar(0xc00087d360, 0x5fc2148, 0xc000fcc100, 0x0, 0x0)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/pkg/resource/asset.go:941 +0x1f9
github.com/pulumi/pulumi/pkg/resource.(*Archive).Archive(0xc00087d360, 0x1, 0x5fc2148, 0xc000fcc100, 0xc000fcc100, 0x0)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/pkg/resource/asset.go:886 +0x21c
github.com/pulumi/pulumi/pkg/resource.(*Archive).EnsureHash(0xc00087d360, 0x0, 0x0)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/pkg/resource/asset.go:1050 +0xfa
github.com/pulumi/pulumi/pkg/resource/plugin.UnmarshalPropertyValue(0xc0011d1aa0, 0xc00115c600, 0x5e, 0x100000100, 0xc0011e4228, 0xc000127100, 0x4)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/pkg/resource/plugin/rpc.go:287 +0x568
github.com/pulumi/pulumi/pkg/resource/plugin.UnmarshalProperties(0xc0011d1a70, 0xc00115c600, 0x5e, 0x100000100, 0x1, 0xc000bf1f30, 0x0)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/pkg/resource/plugin/rpc.go:200 +0x244
github.com/pulumi/pulumi/pkg/resource/deploy.(*resmon).RegisterResource(0xc0000a2240, 0x1bdd7c0, 0xc0011d1da0, 0xc001202000, 0xc0000a2240, 0x1, 0x1)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/pkg/resource/deploy/source_eval.go:608 +0x2fb
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_RegisterResource_Handler.func1(0x1bdd7c0, 0xc0011d1da0, 0x1a64220, 0xc001202000, 0x1bdd7c0, 0xc0011d1da0, 0x1be5da0, 0x2369028)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:507 +0x86
github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1bdd7c0, 0xc0011d1da0, 0x1a64220, 0xc001202000, 0xc0008b7fa0, 0xc0008b7fc0, 0x0, 0x0, 0x1bd03e0, 0xc00015aa80)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x300
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_RegisterResource_Handler(0x1a18be0, 0xc0000a2240, 0x1bdd7c0, 0xc0011d1a40, 0xc00029de30, 0xc0008661e0, 0x0, 0x0, 0xffffffffffffffff, 0x1017450)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:509 +0x158
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000b886e0, 0x1be2320, 0xc000f42300, 0xc001087b80, 0xc000b8a960, 0x2339930, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:923 +0x7b0
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000b886e0, 0x1be2320, 0xc000f42300, 0xc001087b80, 0x0)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:1148 +0x1308
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00039cc30, 0xc000b886e0, 0x1be2320, 0xc000f42300, 0xc001087b80)
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/private/tmp/pulumi-20180912-70519-12fwdqn/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:635 +0xa1
```

**Comment by lukehoban** [comment]
This looks like the same issue we closed in https://github.com/pulumi/pulumi/issues/1493, but looks like there was feedback that the issue was not fixed there.  Leaving this one open to investigate.

**Comment by joaoasrosa** [comment]
As discussed in the community channel, more info:
Pulumi version:
```
Joaos-MacBook-Pro:~ joaorosa$ pulumi version
v0.15.2
```
And packages in the project:
```
{
    "name": "lambda-project",
    "main": "index.js",
    "dependencies": {
        "@pulumi/aws": "^0.15.1",
        "@pulumi/aws-serverless": "^0.15.1",
        "@pulumi/cloud-aws": "^0.15.1",
        "@pulumi/pulumi": "^0.15.2"
    }
}
```
