### ISSUE TITLE
isKnown is incorrectly propagated when `apply` returns an Output

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1972]
We have hit a case in `@pulumi/cloud` where an `apply` callback sees an `undefined` value during preview for a property which is not known.  This should never happen - the apply callback should not run at all.

The root cause appears to be a bug in `Output#apply` where we pass `isKnown` through on the outer `Output`, without coalescing any information about whether the inner `Output` returned from the transformation is known.  

https://github.com/pulumi/pulumi/blob/3b1ddea2e78efc4faea01dfb90b975a00c4abd1e/sdk/nodejs/resource.ts#L386-L406

We can repro this by deploying the following program, and then changing `nginx` to `other` and re-deploying.  The preview then fails with the error below

```typescript
let service = new cloud.Service("basic-web", {
    containers: {
        nginx: {
            build: "./app",
            memory: 256,
            ports: [{port: 8080}]
        },
    },
    replicas: 2
});
```

```
  pulumi:pulumi:Stack: kenny-kenny-dev
    error: Running program '/Users/luke/dd/pulumidemos/kenny' failed with an unhandled exception:

    error: TypeError: Cannot read property 'environment' of undefined
        at pulumi.all.apply (/Users/luke/dd/pulumidemos/kenny/node_modules/@pulumi/service.ts:437:24)
        at Output.<anonymous> (/Users/luke/dd/pulumidemos/kenny/node_modules/@pulumi/pulumi/resource.js:236:43)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/luke/dd/pulumidemos/kenny/node_modules/@pulumi/pulumi/resource.js:17:58)
        at <anonymous>

    error: Running program '/Users/luke/dd/pulumidemos/kenny' failed with an unhandled exception:

    error: TypeError: Cannot read property 'environment' of undefined
        at pulumi.all.apply (/Users/luke/dd/pulumidemos/kenny/node_modules/@pulumi/service.ts:437:24)
        at Output.<anonymous> (/Users/luke/dd/pulumidemos/kenny/node_modules/@pulumi/pulumi/resource.js:236:43)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/luke/dd/pulumidemos/kenny/node_modules/@pulumi/pulumi/resource.js:17:58)
        at <anonymous>

    error: Running program '/Users/luke/dd/pulumidemos/kenny' failed with an unhandled exception:

    error: TypeError: Cannot read property 'environment' of undefined
        at pulumi.all.apply (/Users/luke/dd/pulumidemos/kenny/node_modules/@pulumi/service.ts:437:24)
        at Output.<anonymous> (/Users/luke/dd/pulumidemos/kenny/node_modules/@pulumi/pulumi/resource.js:236:43)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/luke/dd/pulumidemos/kenny/node_modules/@pulumi/pulumi/resource.js:17:58)
        at <anonymous>

    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by lukehoban** [comment]
PR with proposed fix at https://github.com/pulumi/pulumi/pull/1974.
