### ISSUE TITLE
AssetArchive of FileAssets causes a panic()

### ISSUE THREAD

**Issue by yapith-suplari** [pulumi/pulumi#1995]
Possibly related to this open issue: https://github.com/pulumi/pulumi/issues/280
**pulumi version:** v0.15.2
**flavor:** python

**src snippet:**
```
fn_lambda = lambda_.Function(fn_name,
                                     role=lambda_role.arn,
                                     runtime='python3.6',
                                     handler='lambda_handler',
                                     code=pulumi.AssetArchive({
                                         '.': pulumi.FileAsset('file1.py')
```
**repro steps:**
pulumi update

**additional info:**
when it panics, the current `pulumi update` is stuck and requires a `pulumi cancel`

**other reference:**
from `pulumi/asset.py`, AssetArchive is advertised to take named assets:
```
@known_types.asset_archive
class AssetArchive(Archive):
    """
    An AssetArchive is an archive created from an in-memory collection of named assets or other archives.
    """
    def __init__(self, assets):
        if not isinstance(assets, dict):
            raise TypeError("AssetArchive assets must be a dictionary")
        for k, v in assets.items():
            if not isinstance(v, Asset) and not isinstance(v, Archive):
                raise TypeError("AssetArchive assets must contain only Assets or Archives")
        self.assets = assets
```

**stacktrace:**
```
panic: interface conversion: interface {} is *resource.Asset, not *resource.Archive

goroutine 658 [running]:
github.com/pulumi/pulumi/pkg/engine.printAssetsDiff(0xc4202b0000, 0xc420921290, 0xc420921680, 0xef4000, 0x3, 0xc420550000)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/diff.go:717 +0xeb4
github.com/pulumi/pulumi/pkg/engine.printArchiveDiff(0xc4202b0000, 0xc4205570e8, 0xc42058d9a0, 0xc42058da90, 0xc4208b9300, 0x2, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/diff.go:642 +0x719
github.com/pulumi/pulumi/pkg/engine.printPropertyValueDiff(0xc4202b0000, 0xc4205570e8, 0xebfca0, 0xc42058d9a0, 0xebfca0, 0xc42058da90, 0x0, 0x0, 0xc420985500, 0x2, ...)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/diff.go:537 +0x670
github.com/pulumi/pulumi/pkg/engine.printObjectPropertyDiff(0xc4202b0000, 0xc420c5cdf4, 0x4, 0xa, 0xc4209854a0, 0xc4209854d0, 0xc420985500, 0xc420985530, 0xc4208c8c00, 0x2, ...)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/diff.go:485 +0x2f5
github.com/pulumi/pulumi/pkg/engine.printObjectDiff(0xc4202b0000, 0xc4209854a0, 0xc4209854d0, 0xc420985500, 0xc420985530, 0xe46b00, 0x2, 0xc4202b0000)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/diff.go:470 +0x131
github.com/pulumi/pulumi/pkg/engine.printOldNewDiffs(0xc4202b0000, 0xc4209211d0, 0xc420921650, 0xe1cc00, 0x2, 0xee5376, 0x6, 0xd50000)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/diff.go:451 +0x9f
github.com/pulumi/pulumi/pkg/engine.GetResourcePropertiesDetails(0xee5376, 0x6, 0xc4207b7360, 0x47, 0xc420c6b140, 0x1c, 0xc420a3cb40, 0xc420a3cbd0, 0xc420a3cc60, 0x0, ...)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/diff.go:197 +0x1b3
github.com/pulumi/pulumi/pkg/backend/display.renderResourcePreEvent(0xee5376, 0x6, 0xc4207b7360, 0x47, 0xc420c6b140, 0x1c, 0xc420a3cb40, 0xc420a3cbd0, 0xc420a3cc60, 0x0, ...)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/display.go:274 +0x2ac
github.com/pulumi/pulumi/pkg/backend/display.RenderDiffEvent(0xee5376, 0x6, 0xeeb26e, 0xc, 0xe251a0, 0xc4208b8300, 0xc420557aa8, 0xee2091, 0x3, 0x100000000, ...)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/display.go:123 +0x608
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudUpdate).recordEvent(0xc420497100, 0xee5376, 0x6, 0xeeb26e, 0xc, 0xe251a0, 0xc4208b8300, 0xc420557aa8, 0xee2091, 0x3, ...)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/state.go:161 +0x2c9
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudUpdate).RecordAndDisplayEvents(0xc420497100, 0xee6fe1, 0x8, 0xee5376, 0x6, 0xc4210bdc80, 0xc4210bdce0, 0xee46b0, 0x6, 0x100000000)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/state.go:190 +0x2c1
created by github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).runEngineAction
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:765 +0x372
```

**Comment by joeduffy** [comment]
@yapith-suplari, just FYI, this fix is available in version 0.15.4 of the CLI (https://pulumi.io/reference/changelog.html#v154). If you install via the instructions at https://pulumi.io/quickstart/install.html, you'll get the latest.
