### ISSUE TITLE
lambda_.Function() environments dict with all caps unknown keys throws exception

### ISSUE THREAD

**Issue by yapith-suplari** [pulumi/pulumi#2025]
Update: I realized it was a pebkac on my part right after I created the ticket. The problem turns out is minor and low pri, but I'm keeping this issue open anyway to track the go exception thrown.

pulumi version: v0.15.4

**repro steps:**
pulumi update with the following snippet:
```
fn_lambda = lambda_.Function(fn_name,
                                     role=lambda_role.arn,
                                     runtime='python3.6',
                                     handler='env.{}_handler'.format(fn_name),
                                     code=pulumi.AssetArchive({
                                         '.': pulumi.FileArchive(zipfile.ZipFile('/tmp/test.zip')
                                     }),
                                     environment={'TEST_CAPS': 1234}
```
it reports as unknown key properly with `test_caps`.

**stacktrace:**

```
info: panic: fatal: An assertion has failed: Unexpected duplicate underscore: r_e_p__i_n_s_t__a_r_n
    goroutine 93 [running]:
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc42001f1d0, 0x4f)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xf3
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.Assertf(0x28a1a00, 0x32d4e82, 0x23, 0xc42082aa40, 0x1, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x13d
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.TerraformToPulumiName(0xc420e3d5e0, 0x15, 0x0, 0x0, 0x52ccdc0, 0xc42082ac58)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/names.go:74 +0x3a6
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.getInfoFromTerraformName(0xc420e3d5e0, 0x15, 0xc42066c3f0, 0x0, 0xc420611d00, 0x10, 0x10, 0xc42082abb8, 0x412147)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:730 +0x15d
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformOutputs(0xc420611d70, 0xc42066c3f0, 0x0, 0xc42082b518, 0xc420c68300, 0x98)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:396 +0x12f
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformOutput(0x2bc16a0, 0xc4206118c0, 0xc420278000, 0x0, 0xc42082b518, 0xc420a45900, 0x0, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:510 +0xadb
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformOutput(0x284fe20, 0xc420e3bb00, 0xc420278000, 0x0, 0xc42082b518, 0xc4208dbe00, 0xb, 0xc420278000)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:479 +0x3a3
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformOutputs(0xc4206115c0, 0xc42066c390, 0xc420578990, 0xc42082b518, 0x0, 0xc4204eaa88)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:400 +0x1bb
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Check(0xc420562a50, 0x5220460, 0xc42058b1d0, 0xc42059cdc0, 0xc420562a50, 0x1, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:360 +0xc0d
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler.func1(0x5220460, 0xc42058b1d0, 0x3114700, 0xc42059cdc0, 0x5220460, 0xc42058b1d0, 0x5226060, 0x52cb6b8)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1193 +0x86
    github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x5220460, 0xc42058b1d0, 0x3114700, 0xc42059cdc0, 0xc420e3b0a0, 0xc420e3b0c0, 0x0, 0x0, 0x520ef20, 0xc42025bcb0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Check_Handler(0x31cff60, 0xc420562a50, 0x5220460, 0xc420510bd0, 0xc4204e2d20, 0xc4204e7220, 0x0, 0x0, 0xc420811a90, 0x47f574)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1195 +0x16d
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200a6000, 0x5224800, 0xc4200a4000, 0xc4207cc300, 0xc420073860, 0x529f0b0, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:826 +0xab4
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200a6000, 0x5224800, 0xc4200a4000, 0xc4207cc300, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:1023 +0x1528
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4204d6010, 0xc4200a6000, 0x5224800, 0xc4200a4000, 0xc4207cc300)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:572 +0x9f
    created by github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:570 +0xa1
```

**Comment by yapith-suplari** [comment]
I closed the ticket when I was not using the API correctly, then reopened it so we could track the unexpected go exception.

**Comment by lukehoban** [comment]
Thanks @yapith-suplari. We’ll take a look at the exception.

**Comment by swgillespie** [comment]
Self-contained repro:

```python
import pulumi
from pulumi_aws import lambda_

fn_name = "foo"
fn_lambda = lambda_.Function(fn_name,
                                     role="foobar",
                                     runtime='python3.6',
                                     handler='env.{}_handler'.format(fn_name),
                                     code=pulumi.AssetArchive({
                                         '.': pulumi.FileAsset('requirements.txt')
                                     }),
                                     environment={'TEST_CAPS': 1234})
```

**Comment by swgillespie** [comment]
Closing in favor of https://github.com/pulumi/pulumi-terraform/issues/263
