### ISSUE TITLE
Duplicate resource URNs leads to assertions

### ISSUE THREAD

**Issue by brandonbloom** [pulumi/pulumi#2030]
```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v0.15.4
Go Version:       go1.11
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: An assertion has failed

goroutine 1 [running]:
runtime/debug.Stack(0xc000386708, 0x1917e80, 0xc000fe0970)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/debug/stack.go:24 +0xa7
main.panicHandler()
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/main.go:30 +0x71
panic(0x1917e80, 0xc000fe0970)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/pulumi/pulumi/pkg/util/contract.failfast(0x1ab3570, 0x17)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xe9
github.com/pulumi/pulumi/pkg/util/contract.Assert(0x1958200)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26 +0x49
github.com/pulumi/pulumi/pkg/resource/deploy.NewPlan(0xc0000da500, 0xc000ef55c0, 0xc000b4ec00, 0x1bde840, 0xc000c90380, 0x0, 0x0, 0x0, 0x1, 0xc000eb0660, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan.go:199 +0x16f
github.com/pulumi/pulumi/pkg/engine.plan(0xc000ef56b0, 0xc000c81ae0, 0x236b028, 0x0, 0x0, 0xa, 0x0, 0x0, 0x0, 0x1ae4620, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/engine/plan.go:153 +0x444
github.com/pulumi/pulumi/pkg/engine.update(0xc000ef56b0, 0xc000c81ae0, 0x236b028, 0x0, 0x0, 0xa, 0x0, 0x0, 0x0, 0x1ae4620, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/engine/update.go:133 +0xa3
github.com/pulumi/pulumi/pkg/engine.Update(0x1bdab00, 0xc000b4ec80, 0xc000ef56b0, 0x236b028, 0x0, 0x0, 0xa, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/engine/update.go:84 +0x327
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).runEngineAction(0xc0002a5920, 0x1bde4c0, 0xc000034070, 0x1aa2999, 0x6, 0x1bd8540, 0xc000b7c300, 0xc000256360, 0xc000c7c080, 0x2b, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:802 +0x91e
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).apply(0xc0002a5920, 0x1bde4c0, 0xc000034070, 0x1aa2999, 0x6, 0x1be64a0, 0xc0000e61e0, 0xc000256360, 0xc000c7c080, 0x2b, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:724 +0x3d0
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).apply-fm(0x1bde4c0, 0xc000034070, 0x1aa2999, 0x6, 0x1be64a0, 0xc0000e61e0, 0xc000256360, 0xc000c7c080, 0x2b, 0x0, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:617 +0xe5
github.com/pulumi/pulumi/pkg/backend.PreviewThenPrompt(0x1bde4c0, 0xc000034070, 0x1aa2999, 0x6, 0x1be64a0, 0xc0000e61e0, 0xc000256360, 0xc000c7c080, 0x2b, 0x0, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/backend/apply.go:101 +0x2ca
github.com/pulumi/pulumi/pkg/backend.PreviewThenPromptThenExecute(0x1bde4c0, 0xc000034070, 0x1aa2999, 0x6, 0x1be64a0, 0xc0000e61e0, 0xc000256360, 0xc000c7c080, 0x2b, 0x0, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/backend/apply.go:183 +0xbe
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).Update(0xc0002a5920, 0x1bde4c0, 0xc000034070, 0x1bd8540, 0xc000d022d0, 0xc000256360, 0xc000c7c080, 0x2b, 0x0, 0x0, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:617 +0x15d
github.com/pulumi/pulumi/pkg/backend.UpdateStack(0x1bde4c0, 0xc000034070, 0x1be64a0, 0xc0002502d0, 0xc000256360, 0xc000c7c080, 0x2b, 0x0, 0x0, 0xc000d023f0, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/backend/stack.go:71 +0xf5
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudStack).Update(0xc0002502d0, 0x1bde4c0, 0xc000034070, 0xc000256360, 0xc000c7c080, 0x2b, 0x0, 0x0, 0xc000d023f0, 0x236b028, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/backend/httpstate/stack.go:123 +0x93
github.com/pulumi/pulumi/cmd.newUpCmd.func1(0x236b028, 0x0, 0x0, 0xa, 0x0, 0x0, 0x0, 0x1aa1ca3, 0x6, 0x100000000, ...)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/cmd/up.go:98 +0x3b5
github.com/pulumi/pulumi/cmd.newUpCmd.func3(0xc0000b5440, 0x236b028, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/cmd/up.go:300 +0x309
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc0000b5440, 0x236b028, 0x0, 0x0)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:92 +0x5a
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute(0xc0000b5440, 0x236b028, 0x0, 0x0, 0xc0000b5440, 0x236b028)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:702 +0x2d3
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b4240, 0xc0005fbb08, 0xc00006d600, 0xc00006d7e0)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000b4240, 0x1ae5be0, 0xc000387f88)
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/private/tmp/pulumi-20180929-13534-106pg2m/src/github.com/pulumi/pulumi/main.go:49 +0x4b
```

**Comment by brandonbloom** [comment]
Some more context: I removed a `"delete": true,` from my snapshot file.

**Comment by brandonbloom** [comment]
Seems to be caused by having a duplicate resource in the snapshot file after a botched hand-edit.

**Comment by joeduffy** [comment]
We should probably do an audit and change all data validation assertions to proper errors. At the start, I think we assumed nobody would be editing checkpoints by hand, in which case assertions might have made sense (to validate invariants we were supposed to uphold), but now that people are responsible for this, we should fail gracefully.

**Comment by brandonbloom** [comment]
FWIW, I'd love to avoid editing snapshots by hand. Some more command-line tools for correcting mistakes and recovering from errors would be greatly appreciated.

**Comment by joeduffy** [comment]
Absolutely, agree 100% -- thankfully, @swgillespie has got you covered, he has a new `state` command in the works: https://github.com/pulumi/pulumi/pull/2024. Just a start, but I'd expect us to start integrating commands for various scenarios we encounter, so hand editing becomes a thing of the past!

**Comment by lukehoban** [comment]
@brandonbloom Definitely. We’re working on https://github.com/pulumi/pulumi/issues/1909 now which should address the most common needs to edit the checkpoint. F there’s additional scenarios you’ve hit that aren’t yet covered there, add a note on that issue.
