### ISSUE TITLE
Dependencies occasionally fail to install when `pulumi new` is used

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi#2157]
Occasionally when I run `pulumi new`, `npm` fails to install dependencies (usually gRPC). Invariably if I run `npm install` in the directory immediately after this failure, installation succeeds.

A log of one such failure (ignore the typo in the project name!):

```shell
$ pulumi new aws-typescript --yes
Created project 'assumeroel'.
Created stack 'assumeroel-dev'
Installing dependencies...

> grpc@1.16.0 install /private/tmp/assumeroel/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.16.0 and node@8.12.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.16.0 and node@8.12.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error bad download
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
rm: ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw: No such file or directory
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
gyp  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
 ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/James/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/James/.nvm/versions/node/v8.12.0/bin/node" "/Users/James/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/private/tmp/assumeroel/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/private/tmp/assumeroel/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /private/tmp/assumeroel/node_modules/grpc
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/James/.nvm/versions/node/v8.12.0/bin/node /Users/James/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/private/tmp/assumeroel/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/private/tmp/assumeroel/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/tmp/assumeroel/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/Users/James/.nvm/versions/node/v8.12.0/bin/node" "/private/tmp/assumeroel/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /private/tmp/assumeroel/node_modules/grpc
node-pre-gyp ERR! node -v v8.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/Users/James/.nvm/versions/node/v8.12.0/bin/node /Users/James/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/private/tmp/assumeroel/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/private/tmp/assumeroel/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown --napi_version=3 --node_abi_napi=napi' (1)
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
../deps/grpc/src/core/lib/backoff/backoff.cc:25:10: fatal error: 'src/core/lib/gpr/useful.h' file not found
#include "src/core/lib/gpr/useful.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/James/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/James/.nvm/versions/node/v8.12.0/bin/node" "/Users/James/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/private/tmp/assumeroel/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/private/tmp/assumeroel/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /private/tmp/assumeroel/node_modules/grpc
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN assumeroel@ No description
npm WARN assumeroel@ No repository field.
npm WARN assumeroel@ No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.16.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.16.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/James/.npm/_logs/2018-11-01T14_39_11_438Z-debug.log
error: installing dependencies; rerun 'npm install' manually to try again: exit status 1
```

**Comment by lukehoban** [comment]
Which OS are you on?  This looks like perhaps https://github.com/grpc/grpc/issues/15288?  

I suspect the only real solution here will be to avoid the constantly problematic grpc dependency if/when https://github.com/grpc/grpc-node/blob/master/packages/grpc-js-core/README.md becomes a real option.

**Comment by ellismg** [comment]
In this case, it would appear that there was some intermittent issue in downloading the prebuilt binaries (which should exist for node 8.12.0):

```
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.16.0 and node@8.12.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.16.0 and node@8.12.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error bad download
```

At that point `node-pre-gyp` decides that it will just build the binary from source, but it looks like it spawned two processes to do so and they bashed up against one another.  It's possible that's because of https://github.com/mapbox/node-pre-gyp/issues/426, but I can't be 100% certain, since different node versions also behave differently in these cases now.  In these cases, you can pass, `--build-from-source` to npm install to just have it not try to download a prebuilt binary and just build from the get go.  I've seen comments that helps ameliorate some of these issues. 

I assume on a future `npm install` it just downloads the binary successfully and everything goes along on its way.

I don't think there's really anything we can be doing here, short of moving to the pure JS.

**Comment by lukehoban** [comment]
Opened https://github.com/pulumi/pulumi/issues/2218 to track moving to a pure JS implementation.  

Given @ellismg's analysis I'm not sure there's anything more we ourselves can do here - so I'll close this out as a dupe for now.
