### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2170]
A user hit the following:

```
Logging in using access token from PULUMI_ACCESS_TOKEN
Previewing update (XXXXXX/XXXXXXXX-XXXXXX):
panic: send on closed channel

goroutine 105 [running]:
github.com/pulumi/pulumi/pkg/engine.diagEvent(0xc421034a50, 0xc42147e7e0, 0xc420ecc5e0, 0x1d, 0xc420ea2440, 0x40, 0xef15d8, 0x5, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/events.go:425 +0x207
github.com/pulumi/pulumi/pkg/engine.(*eventEmitter).diagDebugEvent(0xc421034a50, 0xc42147e7e0, 0xc420ecc5e0, 0x1d, 0xc420ea2440, 0x40, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/events.go:440 +0x81
github.com/pulumi/pulumi/pkg/engine.(*eventSink).Debugf(0xc421034a50, 0xc42147e7e0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/eventsink.go:65 +0x16e
github.com/pulumi/pulumi/pkg/engine.(*eventSink).Logf(0xc421034a50, 0xef15d8, 0x5, 0xc42147e7e0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/eventsink.go:44 +0x12f
github.com/pulumi/pulumi/pkg/resource/plugin.(*defaultHost).Log(0xc420c0ee00, 0xef15d8, 0x5, 0x0, 0x0, 0xc420909920, 0x29, 0x7fb400000000)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/plugin/host.go:160 +0xd8
github.com/pulumi/pulumi/pkg/resource/plugin.(*hostServer).Log(0xc421033400, 0x16bba60, 0xc42147e7b0, 0xc4206f8aa0, 0xc421033400, 0x1, 0x1)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/plugin/host_server.go:101 +0x126
github.com/pulumi/pulumi/sdk/proto/go._Engine_Log_Handler.func1(0x16bba60, 0xc42147e7b0, 0xe96920, 0xc4206f8aa0, 0x16bba60, 0xc42147e7b0, 0x16c1000, 0x17838e0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/sdk/proto/go/engine.pb.go:370 +0x86
github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x16bba60, 0xc42147e7b0, 0xe96920, 0xc4206f8aa0, 0xc4208e35a0, 0xc4208e35c0, 0x0, 0x0, 0x16ac5a0, 0xc4201608e0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x326
github.com/pulumi/pulumi/sdk/proto/go._Engine_Log_Handler(0xe1b860, 0xc421033400, 0x16bba60, 0xc42147e750, 0xc4200d11f0, 0xc42102bac0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/sdk/proto/go/engine.pb.go:372 +0x16d
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420f10580, 0x16bf1a0, 0xc420503500, 0xc4200df2c0, 0xc42102f590, 0x169cfe0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:923 +0x92d
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420f10580, 0x16bf1a0, 0xc420503500, 0xc4200df2c0, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:1148 +0x1528
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420f6f120, 0xc420f10580, 0x16bf1a0, 0xc420503500, 0xc4200df2c0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:635 +0xa1
Exited with code 2
```

**Comment by lukehoban** [comment]
User reported that this was happening consistently.  But that:

> looks like removing the yarn lock file and repulling the latest providers fixes it

**Comment by lukehoban** [comment]
And another tip:

> I had it set to `0.16.1` in my packages file. after setting `pulumi/pulumi` to `latest` is when the bug happened

**Comment by lukehoban** [comment]
Marking as a P1. 

@geekflyer Does the suggestion above to "looks like removing the yarn lock file and repulling the latest providers fixes it" fix things for you?  If so, what changes does that make to your lock file?  The only thing I can imagine is that perhaps two side-by-side different versions of `@pulumi/pulumi` get merged into one which fixes it?

**Comment by geekflyer** [comment]
nope that doesn't help (fyi we use npm instead of yarn, but deleting the package-lock.json doesn't help either).
