### ISSUE TITLE
Python: exceptions during property serialization can cause deadlocks

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#2189]
This includes exceptions during `apply` or in coroutines awaited during property serialization.

This can be confirmed by running Pulumi with debug logging on (`-d`) and observing a message like this in the logs:

```
    debug: RPC failed with exception:
    debug: Traceback (most recent call last):
      File "/Users/swgillespie/.local/share/virtualenvs/aws-py-stepfunctions-pmkRkyJw/lib/python3.6/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        await rpc_function(*args, **kwargs)
      File "/Users/swgillespie/.local/share/virtualenvs/aws-py-stepfunctions-pmkRkyJw/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 114, in do_register
        resolver = await prepare_resource(res, ty, props, opts)
      File "/Users/swgillespie/.local/share/virtualenvs/aws-py-stepfunctions-pmkRkyJw/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 47, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, implicit_dependencies, res.translate_input_property)
      File "/Users/swgillespie/.local/share/virtualenvs/aws-py-stepfunctions-pmkRkyJw/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 54, in serialize_properties
        result = await serialize_property(v, deps, transform)
      File "/Users/swgillespie/.local/share/virtualenvs/aws-py-stepfunctions-pmkRkyJw/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 141, in serialize_property
        value = await serialize_property(value.future(), deps, transform)
      File "/Users/swgillespie/.local/share/virtualenvs/aws-py-stepfunctions-pmkRkyJw/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 131, in serialize_property
        future_return = await asyncio.ensure_future(value)
      File "/Users/swgillespie/.local/share/virtualenvs/aws-py-stepfunctions-pmkRkyJw/lib/python3.6/site-packages/pulumi/output.py", line 132, in run
        transformed: Input[U] = func(value)
      File "./__main__.py", line 28, in <lambda>
        }""".format(arn))
```

followed by a deadlock.

I'm thinking the correct thing to do here is to likely abort RPCs waiting to begin if a previous RPC failed to launch due to a fatal exception.

**Comment by pgavlin** [comment]
What is the root cause of the deadlock (i.e. why does the exception cause us to deadlock)?

**Comment by swgillespie** [comment]
> What is the root cause of the deadlock (i.e. why does the exception cause us to deadlock)?

We [keep track of the number of outstanding RPCs](https://github.com/pulumi/pulumi/blob/c63c43b3a9faceac389196e0c43de897533bdb55/sdk/python/lib/pulumi/runtime/rpc_manager.py#L63-L65) in order to avoid exiting prematurely. We only exit when [the number of oustanding RPCs becomes zero](https://github.com/pulumi/pulumi/blob/c63c43b3a9faceac389196e0c43de897533bdb55/sdk/python/lib/pulumi/runtime/stack.py#L49-L50). `register_resource` [increments the RPC count before waiting for its input properties to resolve](https://github.com/pulumi/pulumi/blob/c63c43b3a9faceac389196e0c43de897533bdb55/sdk/python/lib/pulumi/runtime/resource.py#L114).

What happens is that, if one resource fails to do an RPC because an `apply` throws, it'll exit its RPC without ever resolving any of its output properties. If there's another resource that is waiting for the first resource's outputs to resolve, it will wait forever because the properties will never be resolved. Furthermore, we'll never exit, because the second resource will only decrement the RPC count when it returns from its infinite wait.

Node fires the [`unhandledRejection`](https://github.com/pulumi/pulumi/blob/c63c43b3a9faceac389196e0c43de897533bdb55/sdk/nodejs/cmd/run/run.ts#L199) event whenever this happens. Python has no such thing, so we can't hook it the same way that we do in Node. However, I am not sure yet why Node does not have this problem.
