### ISSUE TITLE
pulumi up panics

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#2276]
I ran `pulumi up` directly after `pulumi stack init`:

```
panic: fatal: An assertion has failed

goroutine 104 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(0x1abcd20, 0x17)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xe9
github.com/pulumi/pulumi/pkg/util/contract.Assert(0x13a7f00)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26 +0x49
github.com/pulumi/pulumi/pkg/resource/deploy.(*defaultProviders).getDefaultProviderRef(0xc00032d800, 0xc000e9f100, 0x6, 0x6, 0x2, 0xc0000c8000, 0x45, 0x0, 0x0)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/source_eval.go:331 +0x51
github.com/pulumi/pulumi/pkg/resource/deploy.(*resmon).RegisterResource(0xc000ba6480, 0x1be9c60, 0xc000f821e0, 0xc000f84000, 0xc000ba6480, 0x1, 0x1)
	/Users/alex/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/source_eval.go:596 +0x1336
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_RegisterResource_Handler.func1(0x1be9c60, 0xc000f821e0, 0x1a6e660, 0xc000f84000, 0x1be9c60, 0xc000f821e0, 0x1bf2360, 0x23771a8)
	/Users/alex/go/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:507 +0x86
github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1be9c60, 0xc000f821e0, 0x1a6e660, 0xc000f84000, 0xc000602180, 0xc0006021a0, 0x0, 0x0, 0x1bdc6e0, 0xc000148ff0)
	/Users/alex/go/src/github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x300
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_RegisterResource_Handler(0x1a229e0, 0xc000ba6480, 0x1be9c60, 0xc000f82000, 0xc00028e000, 0xc0005d6060, 0x0, 0x0, 0x0, 0x1017450)
	/Users/alex/go/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:509 +0x158
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e1e40, 0x1bee700, 0xc000525080, 0xc000ecf7c0, 0xc000b80cc0, 0x2347a50, 0x0, 0x0, 0x0)
	/Users/alex/go/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:923 +0x7b0
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000e1e40, 0x1bee700, 0xc000525080, 0xc000ecf7c0, 0x0)
	/Users/alex/go/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:1148 +0x1308
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0005f2500, 0xc0000e1e40, 0x1bee700, 0xc000525080, 0xc000ecf7c0)
	/Users/alex/go/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:637 +0x9f
created by github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/alex/go/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:635 +0xa1
```

**Comment by pgavlin** [comment]
This happens when using `pulumi.StackReference` with a CLI prior to 0.16.6. Upgrading to the 0.16.6 CLI fixes this issue.

**Comment by hausdorff** [comment]
This did fix the issue.

**Comment by hausdorff** [comment]
@pgavlin @joeduffy @lukehoban still, seems like we should not be panicking with older clients?

**Comment by pgavlin** [comment]
> seems like we should not be panicking with older clients?

We could move `pulumi.StackReference`'s type token (`pulumi:pulumi:StackReference`) into a different package, but I don't think that we want to do that: as it stands, it seems like it's in the right place. IMO it's fine to require upgrading to a 0.16.6 CLI in order to use this type.

**Comment by lukehoban** [comment]
Very much agree with @hausdorff that we should not panic in cases like this. We need to make sure we can version changes like this so that we report reasonable and actionable errors.  If we have to it’s fone to require a newer CLI, but only if users have some reasonable way of discovering that requirement. It is *very* easy to pick up a new package, and much less clear that a new CLI is needed. 

It may be the ship has already sailed on this specific case - but we should think hard about how to make changes like this in the future in a way that versions better.

**Comment by pgavlin** [comment]
> Very much agree with @hausdorff that we should not panic in cases like this. We need to make sure we can version changes like this so that we report reasonable and actionable errors

I don’t think there’s any disagreement on these points. In this case I simply didn’t account for the fact that downlevel CLIs would assert in this scenario.

> It may be the ship has already sailed on this specific case - but we should think hard about how to make changes like this in the future in a way that versions better.

I agree.

**Comment by adaniline-traderev** [comment]
I have the same issue, but only with pulumi refresh or pulumi destroy, pulumi up works
```
panic: fatal: An assertion has failed

goroutine 70 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
        /private/tmp/pulumi-20190408-49771-s2tk45/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assert(...)
        /private/tmp/pulumi-20190408-49771-s2tk45/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/resource/plugin.(*provider).Read(0xc000100780, 0xc001068840, 0x38, 0x0, 0x0, 0xc00104fbf0, 0xc00104fc20, 0x7fffffff, 0x100, 0x0, ...)
        /private/tmp/pulumi-20190408-49771-s2tk45/src/github.com/pulumi/pulumi/pkg/resource/plugin/provider_plugin.go:388 +0x108c
github.com/pulumi/pulumi/pkg/resource/deploy.(*RefreshStep).Apply(0xc00039e540, 0x1, 0x1bcd08a, 0x23, 0xc0009d7e50, 0x3)
        /private/tmp/pulumi-20190408-49771-s2tk45/src/github.com/pulumi/pulumi/pkg/resource/deploy/step.go:663 +0x120
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).executeStep(0xc000ac0b40, 0x7, 0x1d7f500, 0xc00039e540, 0x0, 0x0)
        /private/tmp/pulumi-20190408-49771-s2tk45/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:270 +0x211
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).executeChain(0xc000ac0b40, 0x7, 0xc0005d8000, 0x1, 0x1)
        /private/tmp/pulumi-20190408-49771-s2tk45/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:220 +0xe0
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).worker.func1(0xc000ac0b40, 0x7, 0xc0005d8000, 0x1, 0x1, 0xc000770000)
        /private/tmp/pulumi-20190408-49771-s2tk45/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:360 +0xc5
created by github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).worker
        /private/tmp/pulumi-20190408-49771-s2tk45/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:357 +0x2c2
```
```
    Pulumi version: v0.17.5
    Plugin nodejs [language] version: 0.17.5
    Plugin aws [resource] version: 0.18.0
    Plugin kubernetes [resource] version: 0.22.0
```

**Comment by catmeme** [comment]
This also happens when you use a StackReference output from another stack but the output doesn't exist yet.

e.g.

```
const stackReference = new pulumi.StackReference("organization/shared-infra/production");

const apigatewayLogRoleId = stackReference.getOutputValue("apigatewayLogRoleId");

const apigatewayLogRole = aws.iam.Role.get("apigateway-log-role", apigatewayLogRoleId);
```

If `organization/shared-infra/production` doesn't have the output `apigatewayLogRoleId` yet, a panic occurs.

**Comment by joeduffy** [comment]
I was unable to repro any of these: running up/refresh/destroy on a `pulumi/pulumi` project worked fine, `new` seems to guard against this naming now-a-days, and using `StackReference` to read an output that doesn't yet exist fails gracefully.

If this is still a problem, please reopen, but I believe this is a non-issue now.
