### ISSUE TITLE
Error when `parent: undefined` is inscrutible

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#2292]
If you create a resource with `{parent: undefined}`, you get something like this:

```
  pulumi:pulumi:Stack (infrastructure-pulumi-infra-dev):
    error: Running program '/Users/alex/src/pulumi/kubernetes-the-prod-way/gcp/infrastructure' failed with an unhandled exception:
    error: TypeError: Cannot read property 'promise' of undefined
        at log (/Users/alex/src/pulumi/kubernetes-the-prod-way/gcp/infrastructure/node_modules/@pulumi/pulumi/log/index.js:97:24)
        at Object.error (/Users/alex/src/pulumi/kubernetes-the-prod-way/gcp/infrastructure/node_modules/@pulumi/pulumi/log/index.js:85:16)
        at process.uncaughtHandler (/Users/alex/src/pulumi/kubernetes-the-prod-way/gcp/infrastructure/node_modules/@pulumi/pulumi/cmd/run/run.js:165:17)
        at process.emit (events.js:182:13)
        at process.emit (/Users/alex/src/pulumi/kubernetes-the-prod-way/gcp/infrastructure/node_modules/ts-node/node_modules/source-map-support/source-map-support.js:461:21)
        at process.emit (/Users/alex/src/pulumi/kubernetes-the-prod-way/gcp/infrastructure/node_modules/source-map-support/source-map-support.js:439:21)
        at emitPromiseRejectionWarnings (internal/process/promises.js:105:20)
        at process._tickCallback (internal/process/next_tick.js:69:34)
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

error: an error occurred while advancing the preview
```

**Comment by swgillespie** [comment]
This issue no longer repros - we probably fixed it some time in the past few months.
