### ISSUE TITLE
Need better error if not providing a project name to `pulumi.Config` ctor

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#2330]
This only repros when running the integration tests in the `pulumi/pulumi` repo, so perhaps this isn't an actual bug. But the following code:

```
// No value passed to pulumi.Config()
const config = new pulumi.Config();
const iterations = config.getNumber("count") || 1000;
```

Leads to this error at runtime, which was confusing until I started digging through the source code. Ideally we would throw a more meaningful error higher up the stack.

```
[                        ee_perf ] Diagnostics:
[                        ee_perf ]   pulumi:pulumi:Stack (ee-perf-p-it-chris-pulu-ee_perf-5a05058b):
[                        ee_perf ]     error: Running program '/private/var/folders/xt/gznxgjrs7wx09j3b9crz75qr0000gn/T/p-it-chris-pulu-ee_perf-5a05058b-681642898' failed with an unhandled exception:
[                        ee_perf ]     error: TypeError: Cannot read property 'endsWith' of undefined
[                        ee_perf ]         at new Config (/Users/chris/pulumi-root/node_modules/@pulumi/pulumi/config.js:31:18)
[                        ee_perf ]         at Object.<anonymous> (/private/var/folders/xt/gznxgjrs7wx09j3b9crz75qr0000gn/T/p-it-chris-pulu-ee_perf-5a05058b-681642898/index.js:6:16)
[                        ee_perf ]         at Module._compile (module.js:652:30)
[                        ee_perf ]         at Object.Module._extensions..js (module.js:663:10)
[                        ee_perf ]         at Module.load (module.js:565:32)
[                        ee_perf ]         at tryModuleLoad (module.js:505:12)
[                        ee_perf ]         at Function.Module._load (module.js:497:3)
[                        ee_perf ]         at Module.require (module.js:596:17)
[                        ee_perf ]         at require (internal/module.js:11:18)
[                        ee_perf ]         at runtime.runInPulumiStack (/Users/chris/pul
```

**Comment by ellismg** [comment]
This is very strange.

Do you have a full repo here?  We use the zero argument version in some other tests without issue, and looking at the implementation I struggle to see how we could end up with undefined here.

**Comment by chrsmith** [comment]
I'll take a closer look. Like I said, it could be related to how the tests are ran (and maybe that specific one).
