### ISSUE TITLE
Python SDK causes intermittent build failures

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#2365]
For example: https://travis-ci.com/pulumi/pulumi-kubernetes/builds/97625054#L8526

There are many more like this, though.

**Comment by hausdorff** [comment]
Apparently if you re-run a job it will blow away the old log. Here's what it looks like when it fails in other places:

```
[ tes/examples/python/smoke-test ]     Adding pulumi-kubernetes [unknown version] to easy-install.pth file
[ tes/examples/python/smoke-test ]     /home/travis/.local/share/virtualenvs/p-it-travis-job-smoke-test-e516ddda-570884-RBsdW_IF/lib/python3.6/site-packages/setuptools/command/easy_install.py:1662: UserWarning: Unbuilt egg for pulumi-kubernetes [unknown version] (/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/sdk/python/bin)
[ tes/examples/python/smoke-test ]       Environment.add(self, dist)
[ tes/examples/python/smoke-test ]     /home/travis/.local/share/virtualenvs/p-it-travis-job-smoke-test-e516ddda-570884-RBsdW_IF/lib/python3.6/site-packages/setuptools/command/easy_install.py:728: UserWarning: Unbuilt egg for pulumi-kubernetes [unknown version] (/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/sdk/python/bin)
[ tes/examples/python/smoke-test ]       self.package_index.add(dist)
[ tes/examples/python/smoke-test ]     /home/travis/.local/share/virtualenvs/p-it-travis-job-smoke-test-e516ddda-570884-RBsdW_IF/lib/python3.6/site-packages/setuptools/command/easy_install.py:731: UserWarning: Unbuilt egg for pulumi-kubernetes [unknown version] (/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/sdk/python/bin)
[ tes/examples/python/smoke-test ]       self.local_index.add(dist)
[ tes/examples/python/smoke-test ]     Traceback (most recent call last):
[ tes/examples/python/smoke-test ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-smoke-test-e516ddda-570884-RBsdW_IF/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2584, in version
[ tes/examples/python/smoke-test ]         return self._version
[ tes/examples/python/smoke-test ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-smoke-test-e516ddda-570884-RBsdW_IF/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2691, in __getattr__
[ tes/examples/python/smoke-test ]         raise AttributeError(attr)
[ tes/examples/python/smoke-test ]     AttributeError: _version
[ tes/examples/python/smoke-test ]     
[ tes/examples/python/smoke-test ]     During handling of the above exception, another exception occurred:
[ tes/examples/python/smoke-test ]     
[ tes/examples/python/smoke-test ]     Traceback (most recent call last):
[ tes/examples/python/smoke-test ]       File "<string>", line 1, in <module>
[ tes/examples/python/smoke-test ]       File "/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/sdk/python/bin/setup.py", line 31, in <module>
[ tes/examples/python/smoke-test ]         zip_safe=False)
[ tes/examples/python/smoke-test ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-smoke-test-e516ddda-570884-RBsdW_IF/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
[ tes/examples/python/smoke-test ]         return distutils.core.setup(**attrs)
[ tes/examples/python/smoke-test ]       File "/opt/python/3.6.3/lib/python3.6/distutils/core.py", line 148, in setup
[ tes/examples/python/smoke-test ]         dist.run_commands()
[ tes/examples/python/smoke-test ]       File "/opt/python/3.6.3/lib/python3.6/distutils/dist.py", line 955, in run_commands
[ tes/examples/python/smoke-test ]         self.run_command(cmd)
[ tes/examples/python/smoke-test ]       File "/opt/python/3.6.3/lib/python3.6/distutils/dist.py", line 974, in run_command
[ tes/examples/python/smoke-test ]         cmd_obj.run()
[ tes/examples/python/smoke-test ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-smoke-test-e516ddda-570884-RBsdW_IF/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
[ tes/examples/python/smoke-test ]         self.install_for_development()
[ tes/examples/python/smoke-test ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-smoke-test-e516ddda-570884-RBsdW_IF/lib/python3.6/site-packages/setuptools/command/develop.py", line 154, in install_for_development
[ tes/examples/python/smoke-test ]         self.process_distribution(None, self.dist, not self.no_deps)
[ tes/examples/python/smoke-test ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-smoke-test-e516ddda-570884-RBsdW_IF/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 734, in process_distribution
[ tes/examples/python/smoke-test ]         log.info(self.installation_report(requirement, dist, *info))
[ tes/examples/python/smoke-test ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-smoke-test-e516ddda-570884-RBsdW_IF/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1108, in installation_report
[ tes/examples/python/smoke-test ]         version = dist.version
[ tes/examples/python/smoke-test ]       File "/home/travis/.local/share/virtualenvs/p-it-travis-job-smoke-test-e516ddda-570884-RBsdW_IF/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2589, in version
[ tes/examples/python/smoke-test ]         raise ValueError(tmpl % self.PKG_INFO, self)
[ tes/examples/python/smoke-test ]     ValueError: ("Missing 'Version:' header and/or PKG-INFO file", pulumi-kubernetes [unknown version] (/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/sdk/python/bin))
[ tes/examples/python/smoke-test ]     
[ tes/examples/python/smoke-test ]     ----------------------------------------
[ tes/examples/python/smoke-test ] 
[ tes/examples/python/smoke-test ] Error:  An error occurred while installing -e /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/sdk/python/bin!
[ tes/examples/python/smoke-test ] Command "/home/travis/.local/share/virtualenvs/p-it-travis-job-smoke-test-e516ddda-570884-RBsdW_IF/bin/python3.6 -c "import setuptools, tokenize;__file__='/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/sdk/python/bin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/sdk/python/bin/
[ tes/examples/python/smoke-test ] 
[ tes/examples/python/smoke-test ] 
[ tes/examples/python/smoke-test ] Wrote output to /tmp/p-it-travis-job-smoke-test-e516ddda-570884315/command-output/pipenv-install-package.20190117-010503.12fe2.log
--- FAIL: TestSmoke (32.84s)
	Error Trace:	program.go:446
			python_test.go:52
	Error:      	Received unexpected error:
	            	exit status 1
	            	Failed to prepare /tmp/p-it-travis-job-smoke-test-e516ddda-570884315
	            	github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/pkg/testing/integration.(*programTester).copyTestToTemporaryDirectory
	            		/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/pkg/testing/integration/program.go:1086
	            	github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/pkg/testing/integration.(*programTester).testLifeCycleInitAndDestroy
	            		/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/pkg/testing/integration/program.go:610
	            	github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/pkg/testing/integration.ProgramTest
	            		/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/pkg/testing/integration/program.go:445
	            	github.com/pulumi/pulumi-kubernetes/examples/python.TestSmoke
	            		/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/examples/python/python_test.go:52
	            	testing.tRunner
	            		/home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:827
	            	runtime.goexit
	            		/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/asm_amd64.s:1333
	            	copying test to temp dir
	            	github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/pkg/testing/integration.(*programTester).testLifeCycleInitAndDestroy
	            		/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/pkg/testing/integration/program.go:612
	            	github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/pkg/testing/integration.ProgramTest
	            		/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/vendor/github.com/pulumi/pulumi/pkg/testing/integration/program.go:445
	            	github.com/pulumi/pulumi-kubernetes/examples/python.TestSmoke
	            		/home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/examples/python/python_test.go:52
	            	testing.tRunner
	            		/home/travis/.gimme/versions/go1.11.linux.amd64/src/testing/testing.go:827
	            	runtime.goexit
	            		/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/asm_amd64.s:1333
```
