### ISSUE TITLE
Calling 'registerOutputs' twice leads to a crash.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#2394]
This happened to me due a coding bug in a ComponentResource hierarchy.  I accidently had both a base-class and a derived-class **both** call `.registerOutputs`.  This is certainly a bug in the hierarchy.  However, we should still not crash the engine, and should instead report some reasonable error to the user.

The crash stack is:

```go
panic: fatal: An assertion has failed: cannot complete a resource 'urn:pulumi:cyservtest::containers-fargate::awsinfra:x:ecs:FargateService::fargate-cached-nginx' whose registration isn't pending

goroutine 82 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc00361c000, 0xb5)
	/home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xe9
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xe03400, 0xef704e, 0x40, 0xc001709b48, 0x1, 0x1)
	/home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x126
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).ExecuteRegisterResourceOutputs(0xc000616500, 0x7fa1d0b17770, 0xc000d09420)
	/home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:153 +0x16b
github.com/pulumi/pulumi/pkg/resource/deploy.(*planExecutor).handleSingleEvent(0xc000d2f360, 0xff84e0, 0xc000d09420, 0xc001709cd8)
	/home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:217 +0x2ea
github.com/pulumi/pulumi/pkg/resource/deploy.(*planExecutor).Execute.func3(0xc000cdd0e0, 0xc000d2f360, 0xc000c5fc00, 0x10054a0, 0xc0005f1640, 0x10054a0, 0xc0005f1500, 0x10000, 0x1, 0xc000616500)
	/home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:171 +0x280
github.com/pulumi/pulumi/pkg/resource/deploy.(*planExecutor).Execute(0xc000d2f360, 0x10054a0, 0xc0005f1500, 0x1001a20, 0xc000602870, 0x7fffffff, 0x10000, 0xc0005d3201, 0x0, 0x0)
	/home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:187 +0x4c4
github.com/pulumi/pulumi/pkg/resource/deploy.(*Plan).Execute(0xc00171b3e0, 0x10054a0, 0xc0005f1500, 0x1001a20, 0xc000602870, 0x7fffffff, 0x10000, 0xc000da5001, 0x1000, 0x1000)
	/home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan.go:295 +0x87
github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk.func1(0x1001a20, 0xc000602870, 0xc0006027e0, 0x10054a0, 0xc0005f1500, 0x1, 0xc000c5fb80, 0xc000cdc9c0)
	/home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/engine/plan.go:216 +0xc9
created by github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk
	/home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/engine/plan.go:208 +0x114
```

**Comment by joeduffy** [comment]
By the way, this doesn't appear to repro in the Node.js runtime anymore, thanks to this change: https://github.com/pulumi/pulumi/commit/342b80b7683356b022cb266a362c42ec4bd27f23#diff-2324dd338afb732d58bf71af19ec789fb841a80e03d9d659bd05cb411e7f30d3R826-R828.

It does, however, repro in other languages. For example, Python. The runtime itself should guard against this:

```python
import pulumi

class C(pulumi.ComponentResource):
    def __init__(self, name):
        super(C, self).__init__('c:index:C', name)
        self.register_outputs({ 'x': 'y' })
        self.register_outputs({ 'x': 'y' })
        self.register_outputs({ 'x': 'y' })
        self.register_outputs({ 'x': 'y' })

c = C('foo')

pulumi.export('CCC', c)

```

**Comment by danielbraun89** [comment]
Almost 4 years later and this is still an issue in python. calling register_output crash with a  _non-descriptive error_:
`panic: fatal: An assertion has failed: cannot complete a resource X whose registration isn't pending`

**Comment by Frassle** [comment]
This issue was just tracking that this used to panic and crash the engine, and the fix was to handle it as an error case. So what you've posted is what is expected.

If you have a use case for wanting to call register_outputs twice and have that work (presumably overwriting?) you should raise a new issue to track that.
