### ISSUE TITLE
Fatal error in pulumi 0.16.12

### ISSUE THREAD

**Issue by pbzdyl** [pulumi/pulumi#2395]
I just upgraded to v0.16.12 (via brew upgrade) and now I get:

```
$ pulumi up
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v0.16.12
Go Version:       go1.11.5
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: An assertion has failed

goroutine 1 [running]:
runtime/debug.Stack(0xc0004ab478, 0x1934fe0, 0xc0003a0140)
	/usr/local/Cellar/go/1.11.5/libexec/src/runtime/debug/stack.go:24 +0xa7
main.panicHandler()
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/main.go:30 +0x71
panic(0x1934fe0, 0xc0003a0140)
	/usr/local/Cellar/go/1.11.5/libexec/src/runtime/panic.go:513 +0x1b9
github.com/pulumi/pulumi/pkg/util/contract.failfast(0x1ad4545, 0x17)
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xe9
github.com/pulumi/pulumi/pkg/util/contract.Assert(0x0)
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26 +0x49
github.com/pulumi/pulumi/pkg/backend/httpstate.cloudStackSummary.Name(0xc000928230, 0x6, 0x0, 0x0, 0xc00094b2a0, 0x14, 0xc000928238, 0xc000928250, 0xc00034ee40, 0xc000928250, ...)
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/pkg/backend/httpstate/stack.go:170 +0x33
github.com/pulumi/pulumi/cmd.chooseStack(0x1c0fb00, 0xc00034ee40, 0x1c0fb01, 0x1ac2af3, 0x6, 0x10000000000, 0x1, 0x0, 0x0, 0x10, ...)
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/cmd/util.go:195 +0x14f
github.com/pulumi/pulumi/cmd.requireCurrentStack(0x1, 0x1ac2af3, 0x6, 0x10000000000, 0x1, 0x8, 0x324a568, 0xc0003f9a00, 0xc0004ab918)
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/cmd/util.go:165 +0x112
github.com/pulumi/pulumi/cmd.requireStack(0x0, 0x0, 0x102bf01, 0x1ac2af3, 0x6, 0x10000000000, 0xc0004ab901, 0xc0004ab970, 0x10778c8, 0x23a0620, ...)
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/cmd/util.go:114 +0x4a3
github.com/pulumi/pulumi/cmd.newUpCmd.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1ac2af3, 0x6, 0x10000000000, ...)
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/cmd/up.go:66 +0xc3
github.com/pulumi/pulumi/cmd.newUpCmd.func3(0xc0000d4b40, 0x23a0288, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/cmd/up.go:306 +0x31c
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc0000d4b40, 0x23a0288, 0x0, 0x0)
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:92 +0x5a
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute(0xc0000d4b40, 0x23a0288, 0x0, 0x0, 0xc0000d4b40, 0x23a0288)
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:702 +0x2d3
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d46c0, 0xc0003ad6e8, 0xc0000b1290, 0xc0000b1390)
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000d46c0, 0x1b09010, 0xc0004abf88)
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/private/tmp/pulumi-20190128-43226-2e095d/src/github.com/pulumi/pulumi/main.go:49 +0x4b
```

**Comment by chrsmith** [comment]
The assert that was triggered:
https://github.com/pulumi/pulumi/blob/master/pkg/backend/httpstate/stack.go#L170

```
func (css cloudStackSummary) Name() backend.StackReference {
	contract.Assert(css.summary.ProjectName != "")

	return cloudBackendReference{
		owner:   css.summary.OrgName,
		project: css.summary.ProjectName,
		name:    tokens.QName(css.summary.StackName),
		b:       css.b,
	}
}
```

**Comment by ellismg** [comment]
Hi, @pbzdyl,

I believe this issue should now be resolved, the was an issue with the backend service that impacted `v0.16.12`, but a fix how now been deployed to production.

Could you please try your update again and let me know if you are still running into issues?  You shouldn't need to make any changes on your end.

**Comment by pbzdyl** [comment]
Hi @ellismg. It helped a bit :) Now I'm getting:

```
pulumi up
Previewing update (<redacted>-services-dev):

     Type                             Name                                   Plan     Info
     pulumi:pulumi:Stack              <redacted>-services-<redacted>-services-dev           
 >-  └─ pulumi:pulumi:StackReference  <redacted>-infra-dev                      read     1 error
 
Diagnostics:
  pulumi:pulumi:StackReference (<redacted>-infra-dev):
    error: Preview failed: unknown stack "<redacted>-infra-dev"
 
error: an error occurred while advancing the preview
```

**Comment by ellismg** [comment]
@pbzdyl Thanks!

I believe this problem is due to some recent changes we've made (starting with `v0.16.12`) to include the project as part of a stack's identity (so you can have duplicate stack names across projects and don't need to have long stack names like `your-long-project-name-dev`.

Because of this, if you are reaching across pulumi projects with a stack reference, you now need to include the project that the other stack is in.

I assume your stack reference looks something like this:

```
const infra = new pulumi.StackReference(`our-organization/redacted-infra-dev`);
```

You will (unfortunately) need to change this to look like the following:

```
const infra = new pulumi.StackReference(`our-organization/other-project-name/redacted-infra-dev`);
```

If you're using Pulumi outside of shared organization (i.e. just in your personal account) and your stack reference looks like this:

```
const infra = new pulumi.StackReference(`redacted-infra-dev`);
```

Then for now you'll need to change it to include your pulumi username as well as the project

```
const infra = new pulumi.StackReference(`ellismg/other-project-name/redacted-infra-dev`);
```

Can you try this out and see if you make progress?

Note that this behavior differs by CLI version (it is a component of the CLI that interprets the string passed to the StackReference object), so if you are using Pulumi in a team setting, you'll want everyone to use `0.16.12` (Including updating CI systems, and the like).

Sorry for all the trouble here and thanks for blazing the trail with the newest CLI.  Hopefully this small amount of pain will be offset by not having to have such long stack names going forward (and we'll be adding a `pulumi stack rename` command shortly, if you want to shorten stuff).

**Comment by pbzdyl** [comment]
Hi @ellismg. Yes, changing the argument to `StackReference` constructor did the trick. Thanks!
