### ISSUE TITLE
Stack reference throws an error during `pulumi up`

### ISSUE THREAD

**Issue by eshamay** [pulumi/pulumi#2407]
As of 1/29 running `pulumi up` on a stack with a reference began failing with the error below. The stack certainly exists and I can `pulumi stack` to see the output from it.

Any ideas on how to proceed?

```
$ pulumi --non-interactive up
Previewing update (tableau/eks-cluster-cd-test):

 +  pulumi:pulumi:Stack eks-cluster-eks-cluster-cd-test create 
 +  kubernetes:helm.sh:Chart splunk-forwarder create 
 +  eks:index:Cluster eks-cluster-cd-test-eks-cluster create 
 >- pulumi:pulumi:StackReference tableau/mustang-aws-iam-sandbox read 
 +  eks:index:ServiceRole eks-cluster-cd-test-eks-cluster-instanceRole create 
 >- pulumi:pulumi:StackReference tableau/mustang-aws-iam-sandbox read error: Preview failed: unknown stack "tableau/mustang-aws-iam-sandbox"
 +  pulumi:pulumi:Stack eks-cluster-eks-cluster-cd-test create Error: invocation of aws:index/getRegion:getRegion returned an error: transport is closing
 +  pulumi:pulumi:Stack eks-cluster-eks-cluster-cd-test create     at monitor.invoke (/builds/service-delivery-platform/mustang/sdp-mustang-terraform/pulumi/eks-cluster/node_modules/@pulumi/pulumi/runtime/invoke.js:73:33)
 +  pulumi:pulumi:Stack eks-cluster-eks-cluster-cd-test create     at Object.onReceiveStatus (/builds/service-delivery-platform/mustang/sdp-mustang-terraform/pulumi/eks-cluster/node_modules/grpc/src/client_interceptors.js:1205:9)
 +  pulumi:pulumi:Stack eks-cluster-eks-cluster-cd-test create     at InterceptingListener._callNext (/builds/service-delivery-platform/mustang/sdp-mustang-terraform/pulumi/eks-cluster/node_modules/grpc/src/client_interceptors.js:568:42)
 +  pulumi:pulumi:Stack eks-cluster-eks-cluster-cd-test create     at InterceptingListener.onReceiveStatus (/builds/service-delivery-platform/mustang/sdp-mustang-terraform/pulumi/eks-cluster/node_modules/grpc/src/client_interceptors.js:618:8)
 +  pulumi:pulumi:Stack eks-cluster-eks-cluster-cd-test create     at callback (/builds/service-delivery-platform/mustang/sdp-mustang-terraform/pulumi/eks-cluster/node_modules/grpc/src/client_interceptors.js:845:24)
 >- pulumi:pulumi:StackReference tableau/mustang-aws-iam-sandbox read 1 error
 
Diagnostics:
  pulumi:pulumi:Stack (eks-cluster-eks-cluster-cd-test):
    Error: invocation of aws:index/getRegion:getRegion returned an error: transport is closing
        at monitor.invoke (/builds/service-delivery-platform/mustang/sdp-mustang-terraform/pulumi/eks-cluster/node_modules/@pulumi/pulumi/runtime/invoke.js:73:33)
        at Object.onReceiveStatus (/builds/service-delivery-platform/mustang/sdp-mustang-terraform/pulumi/eks-cluster/node_modules/grpc/src/client_interceptors.js:1205:9)
        at InterceptingListener._callNext (/builds/service-delivery-platform/mustang/sdp-mustang-terraform/pulumi/eks-cluster/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.onReceiveStatus (/builds/service-delivery-platform/mustang/sdp-mustang-terraform/pulumi/eks-cluster/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/builds/service-delivery-platform/mustang/sdp-mustang-terraform/pulumi/eks-cluster/node_modules/grpc/src/client_interceptors.js:845:24)

  pulumi:pulumi:StackReference (tableau/mustang-aws-iam-sandbox):
    error: Preview failed: unknown stack "tableau/mustang-aws-iam-sandbox"
```

**Comment by eshamay** [comment]
This doesn't repro when run without the `--non-interactive` flag. It repros consistently over the past two days when run as above.

**Comment by eshamay** [comment]
This looks to be addressed by this: https://github.com/pulumi/pulumi/issues/2395#issuecomment-458352016

**Comment by pgavlin** [comment]
cc @ellismg
