### ISSUE TITLE
Using `gcp.config.project` inside serialized closure fails

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2623]
When I attempt to use `gcp.config.project` inside a serialized closure (for Google Cloud Functions) with `CallbackFunction` - I see:

```
Error: Cannot find module '@pulumi/gcp/index.js'
                                                                        at Function.Module._resolveFilename (module.js:548:15)
                                                                        at Function.Module._load (module.js:475:25)
                                                                        at Module.require (module.js:597:17)
                                                                        at require (internal/module.js:11:18)
                                                                        at /srv/index.js:22:102
                                                                        at __f0 (/srv/index.js:35:6)
                                                                        at /worker/worker.js:825:24
                                                                        at <anonymous>
                                                                        at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

It's unfortunate that:
1. This doesn't work as written.
2. The error isn't presented early - at least at deployment time.

**Comment by lukehoban** [comment]
This still repros.  I expect it's because the `gcp.config.project` property (and all similar properties on config objects) are getter:

```ts
Object.defineProperty(exports, "profile", {
    get() {
        return __config.get("profile");
    },
    enumerable: true,
});
```

FWIW - here's an example of what the generated code looks like that triggers this error at function runtime:

```js
exports.handler = __f0;
const aws = require("@pulumi/aws/index.js");

function __f0(__0, __1) {
  return (function() {
    with({ this: undefined, arguments: undefined }) {

return async (ev, ctx) => {
        return {
            statusCode: 200,
            body: aws.config.region,
        };
    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}
```
