### ISSUE TITLE
Pulumi CLI fatal error 0.17.5 on rename stack

### ISSUE THREAD

**Issue by OliverCulleyDeLange** [pulumi/pulumi#2654]
This happened when i was renaming a stack. 
Prior to this action, i had exported a stack from my Pulumi cloud account to a file, logged out of Pulumi cloud, and logged into a file in my working directory, then imported the stack. After this, i tried to rename, where the error happened. 

```
ocd$ pulumi stack rename dev
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v0.17.5
Go Version:       go1.11
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack(0xc000473810, 0x19f5d40, 0x243ae60)
        /Users/travis/.gimme/versions/go1.11.darwin.amd64/src/runtime/debug/stack.go:24 +0xa7
main.panicHandler()
        /Users/travis/gopath/src/github.com/pulumi/pulumi/main.go:30 +0x71
panic(0x19f5d40, 0x243ae60)
        /Users/travis/.gimme/versions/go1.11.darwin.amd64/src/runtime/panic.go:513 +0x1b9
github.com/pulumi/pulumi/pkg/resource/edit.RenameStack(0x0, 0x7ffeefbff7f4, 0x3, 0x0, 0x1c74100)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/edit/operations.go:143 +0xa1
github.com/pulumi/pulumi/pkg/backend/filestate.(*localBackend).RenameStack(0xc0003e6330, 0x1c80c20, 0xc0000b6008, 0x1c79c20, 0xc000153bb0, 0x7ffeefbff7f4, 0x3, 0x7ffeefbff7f4, 0x3)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/filestate/backend.go:235 +0x13c
github.com/pulumi/pulumi/pkg/backend.RenameStack(0x1c80c20, 0xc0000b6008, 0x1c89a40, 0xc00023e140, 0x7ffeefbff7f4, 0x3, 0x1988260, 0xc000153ec0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/stack.go:72 +0xbc
github.com/pulumi/pulumi/pkg/backend/filestate.(*localStack).Rename(0xc00023e140, 0x1c80c20, 0xc0000b6008, 0x7ffeefbff7f4, 0x3, 0x0, 0xc000473c01)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/filestate/stack.go:69 +0x5f
github.com/pulumi/pulumi/cmd.newStackRenameCmd.func1(0xc000465b00, 0xc000153a20, 0x1, 0x1, 0xe, 0xd)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/cmd/stack_rename.go:65 +0x1d8
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc000465b00, 0xc000153a20, 0x1, 0x1, 0x0, 0x0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:95 +0x51
github.com/pulumi/pulumi/pkg/util/cmdutil.RunResultFunc.func1(0xc000465b00, 0xc000153a20, 0x1, 0x1)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:111 +0x60
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute(0xc000465b00, 0xc0001539a0, 0x1, 0x1, 0xc000465b00, 0xc0001539a0)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:702 +0x2d3
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d26c0, 0xc000357738, 0xc0000ad200, 0xc0000ad300)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000d26c0, 0x1b7d140, 0xc000473f88)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
        /Users/travis/gopath/src/github.com/pulumi/pulumi/main.go:49 +0x4b

```

**Comment by ellismg** [comment]
Hi @OliverCulleyDeLange 

Quick question.  For the stack you exported from the Pulumi service, where there resources in the stack?  Looking at the backtrace it seems like this failed because our data structure which represents the cloud deployment was `nil`, and we aren't guarding against that.  So that bug can easily be fixed.

But I am more concerned that the exporting from the cloud and importing to the local backend process didn't actually work correctly, leaving you with something in a bad state (by losing track of all your existing resources).

**Comment by OliverCulleyDeLange** [comment]
@ellismg I think there were resources in the stack as the export was a large file. 
I got into a bit of a twist with my stacks so can't be certain but I think the import did work.. 

I will try and reproduce the scenario and report back

**Comment by CrystalMethod** [comment]
I can confirm the above error if I choose the same name as the current stack. A look at the help showed me, that the expected argument is the new stack name: ``pulumi stack rename **<new-stack-name>**`` ...
