### ISSUE TITLE
Serialisation failure when lambda uses library with native Map

### ISSUE THREAD

**Issue by mnbbrown** [pulumi/pulumi#2704]
I'm having an issue with using inversifyjs in a lambda. It looks like the serialisation step is serialising an internal inversify class that uses native Map under the hood.

I've created a repo to reproduce the issue: https://github.com/mnbbrown/pulumi-native-map 

I realise that native function support is a known limitation (https://github.com/pulumi/docs/blob/master/reference/serializing-functions.md) but does that limitation also apply to libraries that use native functions?

**Comment by ellismg** [comment]
> I realise that native function support is a known limitation (https://github.com/pulumi/docs/blob/master/reference/serializing-functions.md) but does that limitation also apply to libraries that use native functions?

This can happen.  When pulumi captures an object, it does so "by value" which means serializing it's entire hierarchy, and the hierarchy of any thing it transitively references, which can end up bottoming out on native methods.

Surprisingly, I was unable to reproduce your exact issue with the sample program you shared, on both node 8 and node 12.  Unfortunately, I had a much worse experience.  While I was able to deploy your application, when I tried to hit the published route, I ran into this crazy error:

```
Collecting logs for stack dev since 2019-05-06T14:28:10.000-07:00.

 2019-05-06T15:27:56.037-07:00[           hello-worlda552609d] TypeError: Method Map.prototype.has called on incompatible receiver #<Map>
    at Map.has (<anonymous>)
    at __Lookup.<anonymous> (/var/task/__index.js:861:26)
    at __Lookup.__f35 [as hasKey] (/var/task/__index.js:865:34)
    at getBindings (/var/task/node_modules/inversify/lib/planning/planner.js:123:27)
    at _getActiveBindings (/var/task/node_modules/inversify/lib/planning/planner.js:30:20)
    at _createSubRequests (/var/task/node_modules/inversify/lib/planning/planner.js:85:26)
    at Object.plan (/var/task/node_modules/inversify/lib/planning/planner.js:136:9)
    at /var/task/__index.js:734:37
    at __Container.<anonymous> (/var/task/__index.js:718:44)
    at __Container.__f28 [as _get] (/var/task/__index.js:724:34)
[matell@matell pulumi-native-map]$ 
```

You can see here that much of the Container object from inversify is actually defined in __index.js itself, which is an artifact of our serialization logic.  I think the recommendation here would be to construct the IoC container and populate it "on the inside" of your lambda handler, instead of "on the outside" as part of the deployment program. If you move to using the `@pulumi/awsx` package to define your API, then you can use the `callbackFactory` stuff (see [comments here](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/lambda/lambdaMixins.ts#L208-L219)) to allow you to construct the IoC container and inject things into it when your lambda first boots, such that you don't need to do that per request the lambda handles.

**Comment by mnbbrown** [comment]
I also ended up with the `Method Map.prototype.has called on incompatible receiver #<Map>` error. 

The serialisation turns `new Map()` into `Object.create(global.Map.prototype)` which seem to be different things - one creates an `internal slot` - the other doesn.t (see https://www.reddit.com/r/javascript/comments/6k3ps1/babel_6_mysterious_return_super_from_the/)

I refactored so the Container logic was on the "inside" of the serialisation logic. It worked 👍but I came across another issue. It now throws `Missing required @injectable annotation in: __f9` - it would seem the serialisation logic doesn't support annotations :(

**Comment by ellismg** [comment]
> I refactored so the Container logic was on the "inside" of the serialisation logic. It worked +1but I came across another issue. It now throws Missing required @injectable annotation in: __f9 - it would seem the serialisation logic doesn't support annotations :(

@CyrusNajmabadi Do you think keeping these annotations around is something we could do?

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Do you think keeping these annotations around is something we could do?

Interesting question!  I'll have to read up on how injections actually work in JS, they're in the 'very new' category for me.

**Comment by agentd00nut** [comment]
If you've stumbled on this ticket from googling the serialization error and can't find any good examples of how to use the callbackfactory to step around this issue the video from pulumi here

https://www.pulumi.com/resources/getting-started-gcp-serverless-graphql/

at around 8 minutes shows an example.

If your library doesn't have a built in "createHandler" method like `lambda-api` then you can do something like this...

simple_lambda.ts

```
import { APIGatewayEvent, Context } from 'aws-lambda';
import createAPI, {API} from 'lambda-api'

export const cb_fact = function(){
    let api = createAPI();

    api.get('/test', async (req,res)=>{
        return {"hello":"world"};
    });
    return async (event: APIGatewayEvent, context: Context) => {
        return await api.run(event, context)
    }
}
```



Then build the lambda like this...
```
import {lambda} from "@pulumi/aws";
lambda.CallbackFunction(name,{
    callbackFactory:require('./simple_lambda').cb_fact ,
    role: your_roll_here,
})
```

**Comment by AlexBuitrago** [comment]
Did someone found the solution for the Inversifyjs library in Pulumi?

![image](https://user-images.githubusercontent.com/6596384/120908262-4ef2ca00-c636-11eb-9cc9-2ba036872357.png)

**Comment by SimoneGianni** [comment]
I've been fighting with this error for a while, actually using typescript-ioc, which is again an ioc library. 

I'm new to Pulumi but I think there are a few problems here:
1. Pulumi is wrongly serializing the maps. Just replacing (manually, from the AWS console) `Object.create(globals.Map.prototype)` with a simple `new Map()` works. While Object.create is the correct way to reconstitute an object in a serialization context, simply not all objects can be serialized and deserialized that way, Map needs a custom serialization.
2. Pulumi is wrongly serializing any static things. We can debate wether this is a mistake or not. For example, it may be right in serializing the ioc "context" in case I decide to initialize there some values upfront, so Pulumi correctly tries to serialize them and recostitute them on the other side. In my case however, since I was going to setup the ioc container in the lambda itself, this was useless .. which bings us to point number 3.
3. Pulumi does not offer (or at least I have not found) a way to customize/trim/control the serialization. Actually there are some settings, like CodePathOptions, which however only let you control the node_modules things and not actual instances/classes/fields. there is a SerializeFunctionArgs::serialize method, that may help us guide the serialization, but can't find any way to configure/override/customize it. The only place where this function is used, it is declared as () => true, so it's not being used even internally. 
4. When decorators come into play, it is even worse. Decorators will add phantom getters or setters that refer to static things all the time. This is what most of these libraries do, like in aspect programming they intercept the pointcut to implement new behaviours (for example, @Inject in any ioc library). These are references we cannot control, this is something we cannot offset into a factory method so that they run only on the other side. It will be Pulumi itself trying to serialize things that will trigger these getters and make the static stuff alive anyway.

**Comment by SimoneGianni** [comment]
I briefly found some hope, cause buried in Pulumi code there is a check for a `doNotCapture` boolean. But still it does not work as it should.

Stuff (classes, functions etc..) with doNotCapture=true should .. well, not be captured. And it does not in fact capture them, the problem is how it replaces them.

Package typescript-ioc that I use has a class IoCContainer with a lot of static methods called by decorators, so it is captured by Pulumi.

This means that all the used functions are "moved" y Pulumi, and the content of the fields as well, with the dreaded Object.create(global.Map.prototype) problem, main symptom of this ticket. 

So I add in my index.ts:
```
(IoCContainer as any)["doNotCapture"] = true;
```

Now magically, the functions and the fields are not moved anymore. Great? no, not really. Still Pulumi moves "the class", meaning that it does lot leave the original import from my code, but instead replaces it with:

```
function __f19() {
  return (function() {
    with({ message: "Function 'IoCContainer' cannot be called at runtime. It can only be used at deployment time..." }) {
return () => { throw new Error(message); };
    }
  }).apply(undefined, undefined).apply(this, arguments);
}
```

And it passes this __f19 thing everywhere the original class was used:
```
function __f18(__0, __1) {
  return (function() {
    with({ IoCContainer: __f19 }) {
```

Removing (again manually from the AWS console) this "__f19" and instead using the original import, works perfectly:

```
function __f18(__0, __1) {
  return (function() {
    with({ IoCContainer: require("typescript-ioc/dist/container/container.js").IoCContainer }) {
```

So, "doNotCapture" does not mean "leave it as it is", but rather "make me unusable".

**Comment by kay-is** [comment]
Had a similar issue, solved it by not using class members in my provider.

Instead of doing it like this:

```
class P {
  #x 
  constructor() {
    this.#x = new SomeSdk()
  } 
  async create(...) {
    const a = this.#x.doSomething()
  }
}
```

I did it like that:

```
class P {
  async create(...) {
    const a = new SomeSdk().doSomething()
  }
}
```
