### ISSUE TITLE
Error when using `additional_secret_outputs`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2782]
When I set `additional_secret_outputs = ["status"]` for a `k8s.core.v1.Pod`, I get the error below.  

Looking at the code in https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/rpc.py#L226, it appears this failure can definitely happen - though I'm not sure exactly what that code is trying to do.

```
[ ests/examples/python/yaml-test ]   pulumi:pulumi:Stack (yaml-test-p-it-lukes-mbpc-yaml-test-7c0d6c62):
[ ests/examples/python/yaml-test ]     error: Program failed with an unhandled exception:
[ ests/examples/python/yaml-test ]     error: Traceback (most recent call last):
[ ests/examples/python/yaml-test ]       File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
[ ests/examples/python/yaml-test ]         loop.run_until_complete(coro)
[ ests/examples/python/yaml-test ]       File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
[ ests/examples/python/yaml-test ]         return future.result()
[ ests/examples/python/yaml-test ]       File "/Users/luke/.local/share/virtualenvs/p-it-lukes-mbpc-yaml-test-7c0d6c62-0623230-QDqjETIE/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 38, in run_in_stack
[ ests/examples/python/yaml-test ]         await RPC_MANAGER.unhandled_exeception()
[ ests/examples/python/yaml-test ]       File "/Users/luke/.local/share/virtualenvs/p-it-lukes-mbpc-yaml-test-7c0d6c62-0623230-QDqjETIE/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
[ ests/examples/python/yaml-test ]         result = await rpc_function(*args, **kwargs)
[ ests/examples/python/yaml-test ]       File "/Users/luke/.local/share/virtualenvs/p-it-lukes-mbpc-yaml-test-7c0d6c62-0623230-QDqjETIE/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 246, in do_register
[ ests/examples/python/yaml-test ]         await rpc.resolve_outputs(res, props, resp.object, resolvers)
[ ests/examples/python/yaml-test ]       File "/Users/luke/.local/share/virtualenvs/p-it-lukes-mbpc-yaml-test-7c0d6c62-0623230-QDqjETIE/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 331, in resolve_outputs
[ ests/examples/python/yaml-test ]         for key, value in deserialize_properties(outputs).items():
[ ests/examples/python/yaml-test ]       File "/Users/luke/.local/share/virtualenvs/p-it-lukes-mbpc-yaml-test-7c0d6c62-0623230-QDqjETIE/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 226, in deserialize_properties
[ ests/examples/python/yaml-test ]         value: output
[ ests/examples/python/yaml-test ]     TypeError: unhashable type: 'dict'
[ ests/examples/python/yaml-test ]     error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by lukehoban** [comment]
Ahh - the issue is this:

```
        return {
            _special_sig_key: _special_secret_sig,
            value: output
        }
```

should be this:

```
        return {
            _special_sig_key: _special_secret_sig,
            "value": output
        }
```

**Comment by lukehoban** [comment]
@jen20 hit what looks like a similar/related issue.  His led to the following stack trace, but looking at the code, it seems the main way this could get triggered is as a result of the same core bug noted above.

```
I0625 16:48:12.502192   58173 eventsink.go:60] Traceback (most recent call last):
  File "/Users/James/.local/share/virtualenvs/kube-cluster--sxGNHds/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
    result = await rpc_function(*args, **kwargs)
  File "/Users/James/.local/share/virtualenvs/kube-cluster--sxGNHds/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 358, in do_register
    await rpc.resolve_outputs(res, props, resp.object, resolvers)
  File "/Users/James/.local/share/virtualenvs/kube-cluster--sxGNHds/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 331, in resolve_outputs
    for key, value in deserialize_properties(outputs).items():
  File "/Users/James/.local/share/virtualenvs/kube-cluster--sxGNHds/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 219, in deserialize_properties
    value = value["value"]
KeyError: 'value'
I0625 16:48:12.502212   58173 eventsink.go:63] eventSink::Debug(<{%reset%}>Traceback (most recent call last):
  File "/Users/James/.local/share/virtualenvs/kube-cluster--sxGNHds/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
    result = await rpc_function(*args, **kwargs)
  File "/Users/James/.local/share/virtualenvs/kube-cluster--sxGNHds/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 358, in do_register
    await rpc.resolve_outputs(res, props, resp.object, resolvers)
  File "/Users/James/.local/share/virtualenvs/kube-cluster--sxGNHds/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 331, in resolve_outputs
    for key, value in deserialize_properties(outputs).items():
  File "/Users/James/.local/share/virtualenvs/kube-cluster--sxGNHds/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 219, in deserialize_properties
    value = value["value"]
KeyError: 'value'
```

**Comment by jen20** [comment]
I'll try this fix locally and send a PR if it fixes it.
