### ISSUE TITLE
Assert in `mustWrite`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2804]
A user reports hitting the following assert:

```
 ~   └─ gcp:container:Cluster         gke                     updated     [diff: ~addonsConfig]
panic: fatal: An assertion has failed

goroutine 535 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
	/private/tmp/pulumi-20190604-14204-2zvez6/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assert(...)
	/private/tmp/pulumi-20190604-14204-2zvez6/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/backend.(*sameSnapshotMutation).mustWrite(0xc000010470, 0xc000a6a9a0, 0xc0006607e0, 0xc0003e1f60)
	/private/tmp/pulumi-20190604-14204-2zvez6/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:192 +0x3f4
github.com/pulumi/pulumi/pkg/backend.(*sameSnapshotMutation).End.func1(0xc0003e1f60)
	/private/tmp/pulumi-20190604-14204-2zvez6/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:237 +0xd0
github.com/pulumi/pulumi/pkg/backend.NewSnapshotManager.func1(0xc0019f18c0, 0xc001a21600, 0xc0019f1920, 0xc0019f1980)
	/private/tmp/pulumi-20190604-14204-2zvez6/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:564 +0x108
created by github.com/pulumi/pulumi/pkg/backend.NewSnapshotManager
	/private/tmp/pulumi-20190604-14204-2zvez6/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:554 +0x150
```

**Comment by lukehoban** [comment]
The assert is:

https://github.com/pulumi/pulumi/blob/fdc4c64789dc6e293f3404433908a702131d37ed/pkg/backend/snapshot.go#L192

**Comment by lukehoban** [comment]
@pat is this related to https://github.com/pulumi/pulumi/pull/2767 perhaps?

**Comment by nesl247** [comment]
Maybe as `[provider: urn:pulumi:production::kubernetes::pulumi:providers:gcp::default::d98feb7d-8406-4882-b99e-6592f7f75c73 => urn:pulumi:production::kubernetes::pulumi:providers:gcp::default_0_18_7::output<string>]` was part of the changeset.
