### ISSUE TITLE
Crash with replace of an 'aliased' resource.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#2826]
Note: you'll need the latest pulumi and pulumi-aws packages.

I had a stack with an sns topic and a subscription created off of it.  They also included an explicit provider i.e.:

```ts
const provider = new aws.Provider("custom", { region: "us-west-2" });

const topic = new aws.sns.Topic("sites-to-process-topic", /*args:*/ undefined, { provider });
const subscription = topic.onEvent("for-each-url", async (event) => {
}, /*args:*/ undefined, { providers: { aws: provider } });
```

I created my stack from this.  I then deleted the provider, moving to code like this:

```ts
const topic = new aws.sns.Topic("sites-to-process-topic");
const subscription = topic.onEvent("for-each-url", async (event) => {
});
```

Updating my stack showed a reasonable preview.  However, the actual apply crashed with this error:

```
panic: fatal: An assertion has failed: two resources ('urn:pulumi:cydash::dashboard::aws:sns/topic:Topic$aws:sns:TopicEventSubscription$aws:iam/role:Role::for-each-url' and 'urn:pulumi:cydash::dashboard::aws:sns/topic:Topic$aws:sns:TopicEventSubscription$aws:iam/role:Role::for-each-url') aliased to the same: 'urn:pulumi:cydash::dashboard::aws:sns:TopicEventSubscription$aws:iam/role:Role::for-each-url'

goroutine 3613 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
        /home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc001116200, 0x138928c, 0x37, 0xc001e45ce0, 0x3, 0x3)
        /home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x198
github.com/pulumi/pulumi/pkg/resource/deploy.(*Snapshot).NormalizeURNReferences(0xc0012d2ea0)
        /home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/resource/deploy/snapshot.go:109 +0x6ac
github.com/pulumi/pulumi/pkg/backend.(*SnapshotManager).saveSnapshot(0xc00031e300, 0xc001e45f30, 0x2)
        /home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:527 +0x42
github.com/pulumi/pulumi/pkg/backend.NewSnapshotManager.func1(0xc001117320, 0xc00031e300, 0xc001117380, 0xc001117440)
        /home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:570 +0x12e
created by github.com/pulumi/pulumi/pkg/backend.NewSnapshotManager
        /home/cyrusn/go/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:559 +0x150
```

**Comment by CyrusNajmabadi** [comment]
Tagging @lukehoban @pgavlin

**Comment by lukehoban** [comment]
I believe this was fixed with https://github.com/pulumi/pulumi/pull/2864.
