### ISSUE TITLE
RuntimeError: cannot reuse already awaited coroutine

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2940]
The following code:

```
import pulumi
from pulumi_aws import s3, ec2, iam

async def get_profile():
    instance_profile = await iam.get_instance_profile(name="webServerProfile-ad563fb")
    return instance_profile.name

async def get_policy(): 
    policy = await iam.get_policy(arn="arn:aws:iam::aws:policy/AdministratorAccess")
    return policy.name

iam.RolePolicyAttachment(role=get_profile(),resource_name="policy_test",policy_arn=get_policy())
```

Leads to:

```
Diagnostics:
  pulumi:pulumi:Stack (awsimport-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
      File "/Users/luke/.local/share/virtualenvs/awsimport-NvZwckuT/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 38, in run_in_stack
        await RPC_MANAGER.unhandled_exeception()
      File "/Users/luke/.local/share/virtualenvs/awsimport-NvZwckuT/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        result = await rpc_function(*args, **kwargs)
      File "/Users/luke/.local/share/virtualenvs/awsimport-NvZwckuT/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 358, in do_register
        await rpc.resolve_outputs(res, props, resp.object, resolvers)
      File "/Users/luke/.local/share/virtualenvs/awsimport-NvZwckuT/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 344, in resolve_outputs
        input_prop = await serialize_property(value, [])
      File "/Users/luke/.local/share/virtualenvs/awsimport-NvZwckuT/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 135, in serialize_property
        future_return = await asyncio.ensure_future(value)
    RuntimeError: cannot reuse already awaited coroutine
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by astronouth7303** [comment]
Yup, happens pretty much any time you use a bare coroutine in Python.

My work around is #2901's `FauxOutput`/`@outputish`.

**Comment by pgavlin** [comment]
@astronouth7303 we were just discussing this. It seems that changing data sources from coroutines to synchronous functions that return plain values and removing support for raw awaitables throughout most of the public API (i.e. requiring that all inputs are either prompt values or Outputs and allowing a user to create an Output from an awaitable) would vastly decrease the likelihood of this happening. Does that sound reasonable?

**Comment by astronouth7303** [comment]
Part of me isn't happy because async is _so cool_ and you're basically cutting it out.

On the flip side, having the primary user-exposed stuff being sync will simplify pretty much everything for, like, 95% of users.
