### ISSUE TITLE
Poor error message using PaC with older SDK

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#2968]
If you are using PAC and the Pulumi program is using an older version of the `@pulumi/pulumi` Node package (e.g. `16.0.0`) then you get a somewhat confusing error message.

I suspect this has to do with the minimum version of the package's runtime not matching what the Pulumi program is requesting. Is there some super-complicated NPM package versioning issue going on here? e.g. if the PAC package is built on `@pulumi/pulumi` version X and the Pulumi program is running against version Y, we would expect that to cause odd failures from time to time. Right?

Is there a way to insulate ourselves from this somehow? e.g. load a different `@pulumi/pulumi` package specific for the PAC package?

```
Diagnostics:
  pulumi:pulumi:Stack (resources-pac-test):
    internal/modules/cjs/loader.js:628
        throw err;
        ^
    Error: Cannot find module '@pulumi/pulumi/cmd/run-policy-pack'
    Require stack:
    - /Users/chris/go/src/github.com/pulumi/pulumi-service/examples/resources/[eval]
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
        at Function.resolve (internal/modules/cjs/helpers.js:21:19)
        at [eval]:1:21
        at Script.runInThisContext (vm.js:123:20)
        at Object.runInThisContext (vm.js:313:38)
        at Object.<anonymous> ([eval]-wrapper:9:26)
        at Module._compile (internal/modules/cjs/loader.js:776:30)
        at evalScript (internal/process/execution.js:80:25)
        at internal/main/eval_string.js:23:3 {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/Users/chris/go/src/github.com/pulumi/pulumi-service/examples/resources/[eval]'
      ]
    }
 
Permalink: https://app.pulumi.com/chrsmith/resources/pac-test/updates/2
error: could not read plugin [/Users/chris/pulumi-root/bin/pulumi-analyzer] stdout: EOF
```

**Comment by chrsmith** [comment]
This bit me again, a second time 😬 . Probably worth improving the error diagnostic for this.

The specific way to fix this is to update the Pulumi SDK referenced **in the stack's `package.json`**.
