### ISSUE TITLE
Cannot create a VPC using both numberOfAvailabilityZones and numberOfNatGateways

### ISSUE THREAD

**Issue by darinpope** [pulumi/pulumi#2978]
pulumi version == v0.17.25
node --version == v12.6.0
macOS 10.12.6

When trying to create a VPC based on the examples:

```
import * as awsx from '@pulumi/awsx';

const vpc = new awsx.ec2.Vpc('dpope-scratch', {
    numberOfAvailabilityZones: "all",
    numberOfNatGateways: 1,
});
```
or

```
import * as awsx from '@pulumi/awsx';

const vpc = new awsx.ec2.Vpc('dpope-scratch', {
    numberOfAvailabilityZones: 3,
    numberOfNatGateways: 1,
});
```
I receive the following error:

```
Previewing update (stage):

     Type                 Name                     Plan       Info
 +   pulumi:pulumi:Stack  dpzyz-stage  create     1 error; 1 message
 +   └─ awsx:x:ec2:Vpc    dpope-scratch            create
 +      └─ aws:ec2:Vpc    dpope-scratch            create

Diagnostics:
  pulumi:pulumi:Stack (dpzyz-stage):
    (node:56067) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

    error: Running program '/Users/dpope/dpzyz-proj/dpzyz' failed with an unhandled exception:
    TypeError: Cannot read property 'name' of undefined
        at ComputedLocationTopology.create (/Users/dpope/dpzyz-proj/dpzyz/node_modules/@pulumi/ec2/vpcTopology.ts:149:66)
        at Object.create (/Users/dpope/dpzyz-proj/dpzyz/node_modules/@pulumi/ec2/vpcTopology.ts:56:21)
        at Vpc.partition (/Users/dpope/dpzyz-proj/dpzyz/node_modules/@pulumi/ec2/vpc.ts:103:62)
        at new Vpc (/Users/dpope/dpzyz-proj/dpzyz/node_modules/@pulumi/ec2/vpc.ts:86:18)
        at Object.<anonymous> (/Users/dpope/dpzyz-proj/dpzyz/index.ts:4:13)
        at Module._compile (internal/modules/cjs/loader.js:776:30)
        at Module.m._compile (/Users/dpope/dpzyz-proj/dpzyz/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/dpope/dpzyz-proj/dpzyz/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:643:32)
```

If I test with either one by themselves, it works as expected. The problem is when I combine both numberOfAvailabilityZones and numberOfNatGateways.

**Comment by darinpope** [comment]
..and I just realized that I should have probably put this in pulumi-awx
