### ISSUE TITLE
Automatically generated function bundles don't like `yarn link`

### ISSUE THREAD

**Issue by eropple** [pulumi/pulumi#2980]
I'm working on shared infra for our company/for eventual open-source release and one of the things I've realized is that Pulumi has trouble with `yarn link`. I can't share the code right now but what I've discovered is that creating a `CallbackFunction` in a linked package fails with an odd error:

```
  pulumi:pulumi:Stack (data-api-v2-deploy-dev.data-api-v2):
    error: Running program 'consumer-dir' failed with an unhandled exception:
    TypeError: Cannot read property 'apply' of undefined
        at new ELKTransport (linked-dir/src/orchestration/elk-transport/index.ts:116:45)
        at consumer-dir/index.ts:60:28
        at Generator.next (<anonymous>)
        at fulfilled (consumer-dir/index.ts:4:58)
    error: Running program 'consumer-dir' failed with an unhandled exception:
    Error: failed to register new resource elk-shipper-lambda-lambda [aws:lambda/function:Function]: 2 UNKNOWN: failed to compute asset hash: asset path 'node_modules/@hydrow-infra/pulumi-tools' is a directory; try using an archive
        at Object.registerResource (linked-dir/node_modules/@pulumi/pulumi/runtime/resource.js:112:27)
        at new Resource (linked-dir/node_modules/@pulumi/pulumi/resource.js:172:24)
        at new CustomResource (linked-dir/node_modules/@pulumi/pulumi/resource.js:270:9)
        at new Function (linked-dir/node_modules/@pulumi/lambda/function.ts:221:9)
        at new CallbackFunction (linked-dir/node_modules/@pulumi/lambda/lambdaMixins.ts:325:9)
        at new NotifyingCallbackFunction (linked-dir/src/orchestration/notifying-callback.ts:71:24)
        at new ELKTransport (linked-dir/src/orchestration/elk-transport/index.ts:95:32)
        at consumer-dir/index.ts:60:28
        at Generator.next (<anonymous>)
        at fulfilled (consumer-dir/index.ts:4:58)

    Could not include required dependency '@pulumi/aws' in 'consumer-dir'.
    Could not include required dependency '@pulumi/pulumi' in 'consumer-dir'.
    Could not include required dependency '@pulumi/terraform' in 'consumer-dir'.
    Could not include required dependency 'lodash' in 'consumer-dir'.
    Could not include required dependency 'runtypes' in 'consumer-dir'.
    Could not include required dependency 'utility-types' in 'consumer-dir'.
```

My guess is that whatever's walking the tree either 1) doesn't understand symlinks, or 2) is looking in the wrong place (possibly just an insufficient place) for the `node_modules` referenced by the hoisted code.

**Comment by lukehoban** [comment]
Can you share any details on the shape of your project or a small independent repro?  It will be slightly hard to investigate this without more details.

**Comment by eropple** [comment]
I don't have time at the moment to repro, though I might next week.

The entire `aws.lambda.CallbackFunction` is being created and returned via a function in `linked-dir`, including the code that it's using as its `callbackFactory`.

**Comment by arthur-caillaud** [comment]
```
pulumi:pulumi:Stack (aws-architecture-dev):
    error: Running program '/.../deploy.ts' failed with an unhandled exception:
    Error: failed to register new resource lambdas28ff37ff [aws:lambda/function:Function]: 2 UNKNOWN: failed to compute asset hash: asset path 'node_modules/@outmind/core' is a directory; try using an archive
        at Object.registerResource (/.../node_modules/@pulumi/pulumi/runtime/resource.js:114:27)
        at new Resource (/.../node_modules/@pulumi/pulumi/resource.js:204:24)
        at new CustomResource (/.../node_modules/@pulumi/pulumi/resource.js:295:9)
        at new Function (/.../node_modules/@pulumi/lambda/function.ts:233:9)
        at new CallbackFunction (/.../node_modules/@pulumi/lambda/lambdaMixins.ts:325:9)
        at Object.createFunctionFromEventHandler (/.../node_modules/@pulumi/lambda/lambdaMixins.ts:244:16)
        at addEventHandlerRouteToSwaggerSpec (/.../node_modules/@pulumi/apigateway/api.ts:822:31)
        at createSwaggerSpec (/.../node_modules/@pulumi/apigateway/api.ts:736:13)
        at new API (/.../node_modules/@pulumi/apigateway/api.ts:531:28)
        at Object.<anonymous> (/.../deploy.ts:5:13)
```

The `@outmind/*` packages are our company modules that are imported by the `pulumi up` script (`deploy.ts`) and that are managed through `yarn workspaces`. They are symlinks to the actual modules. I have been looking in other issues and I think this problem is linked with the issues #2661 and #3013.

A support with `yarn workspaces` is greatly welcomed for large projects and monorepos.

**Comment by EvanBoyle** [comment]
I just ran into something similar. I had a project that had jest as a dev-dep. It looks like it had this package simlinked in a few places: https://www.npmjs.com/package/acorn

```
error: Running program '/Users/evanboyle/code/react_example' failed with an unhandled exception:
    Error: failed to register new resource hello1b023375 [aws:lambda/function:Function]: 2 UNKNOWN: failed to compute archive hash: stat node_modules/espree/node_modules/acorn-jsx/node_modules/.bin/acorn: no such file or directory
        at Object.registerResource (/Users/evanboyle/code/react_example/node_modules/@pulumi/pulumi/runtime/resource.js:114:27)
        at new Resource (/Users/evanboyle/code/react_example/node_modules/@pulumi/pulumi/resource.js:204:24)
        at new CustomResource (/Users/evanboyle/code/react_example/node_modules/@pulumi/pulumi/resource.js:295:9)
        at new Function (/Users/evanboyle/code/react_example/node_modules/@pulumi/lambda/function.ts:233:9)
        at new CallbackFunction (/Users/evanboyle/code/react_example/node_modules/@pulumi/lambda/lambdaMixins.ts:333:9)
        at Object.createFunctionFromEventHandler (/Users/evanboyle/code/react_example/node_modules/@pulumi/lambda/lambdaMixins.ts:244:16)
        at addEventHandlerRouteToSwaggerSpec (/Users/evanboyle/code/react_example/node_modules/@pulumi/apigateway/api.ts:826:31)
        at createSwaggerSpec (/Users/evanboyle/code/react_example/node_modules/@pulumi/apigateway/api.ts:740:13)
        at new API (/Users/evanboyle/code/react_example/node_modules/@pulumi/apigateway/api.ts:531:28)
        at Object.<anonymous> (/Users/evanboyle/code/react_example/index.js:8:18)
```

the solution for me was to do a dep only install:

```sh
rm -r ./node_modules && npm install --production
```

**Comment by EvanBoyle** [comment]
It would actually be pretty helpful here if our closure serialization could filter out anything in the dev dependencies section of the package.json.
