### ISSUE TITLE
Creating an Asset with improperly typed properties panics

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3016]
If I create an `Asset` with poorly typed properties, as in

```typescript
const b = new aws.s3.Bucket("x");
new aws.s3.BucketObject("a", {
    bucket: b,
    source: new pulumi.asset.StringAsset(new Buffer("bad") as any),
});
```

Pulumi panics with `interface conversion: interface {} is map[string]interface {}, not string`:

```
Updating (dev):

     Type                               Name             Status      Info
     pulumi:pulumi:Stack                s3-encypted-dev  running.    (node:92106) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues.
 +   └─ pulumi-nodejs:dynamic:Resource  my-datakey       created
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 208 [running]:
github.com/pulumi/pulumi/pkg/resource.DeserializeAsset(0xc0016806c0, 0x1f8ab4f, 0x20, 0x1, 0xc0010a0e08)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/asset.go:255 +0x459
github.com/pulumi/pulumi/pkg/resource/plugin.UnmarshalPropertyValue(0xc001093770, 0xc0001545a0, 0x48, 0x10100000100, 0xc00101da90, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/plugin/rpc.go:290 +0x93e
github.com/pulumi/pulumi/pkg/resource/plugin.UnmarshalProperties(0xc0010936e0, 0xc0001545a0, 0x48, 0x10100000100, 0x2, 0xc0008b5de0, 0x1)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/plugin/rpc.go:211 +0x25f
github.com/pulumi/pulumi/pkg/resource/deploy.(*resmon).RegisterResource(0xc000afd5e0, 0x21f6e60, 0xc001093c20, 0xc00109c120, 0xc000afd5e0, 0x1daf401, 0xc00109a600)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/source_eval.go:717 +0x410
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_RegisterResource_Handler.func1(0x21f6e60, 0xc001093c20, 0x1f3b540, 0xc00109c120, 0x1f05500, 0x2d4e9a0, 0x21f6e60, 0xc001093c20)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:823 +0x86
github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x21f6e60, 0xc0010936b0, 0x1f3b540, 0xc00109c120, 0xc0005d3040, 0xc0005d3060, 0x0, 0x0, 0x21d1ba0, 0xc0001d6c00)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x350
github.com/pulumi/pulumi/sdk/proto/go._ResourceMonitor_RegisterResource_Handler(0x1ebe4e0, 0xc000afd5e0, 0x21f6e60, 0xc0010936b0, 0xc00108a7d0, 0xc000233ac0, 0x21f6e60, 0xc0010936b0, 0xc00133ea80, 0x347)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/sdk/proto/go/resource.pb.go:825 +0x158
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003a7e00, 0x2206800, 0xc000560780, 0xc001081300, 0xc0010bb0b0, 0x2d1e8e8, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:972 +0x4b5
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0003a7e00, 0x2206800, 0xc000560780, 0xc001081300, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:1252 +0xda6
github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0009e9e40, 0xc0003a7e00, 0x2206800, 0xc000560780, 0xc001081300)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:691 +0x9f
created by github.com/pulumi/pulumi/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/google.golang.org/grpc/server.go:689 +0xa1
```

**Comment by lukehoban** [comment]
The title says the opposite - but the panic is the same as https://github.com/pulumi/pulumi/issues/2836.

**Comment by joeduffy** [comment]
My understanding of what was happening here was wrong. What was actually happening is the `StringAsset`'s property ended up being a `Buffer`, not a `string`, which apparently somehow gets marshaled as a `map[string]interface{}`. Adjusting the title accordingly.
