### ISSUE TITLE
AsyncIO Loop error

### ISSUE THREAD

**Issue by astronouth7303** [pulumi/pulumi#3038]
After upgrading to v0.17.28, https://github.com/dingbots/castle fails to preview, with the following trace:

```
Previewing update (dev):

     Type                     Name        Plan       Info
     pulumi:pulumi:Stack      castle-dev             3 errors; 42 messages
 ~   └─ pulumi:providers:aws  us-east-2   update     [diff: -profile]
 
Diagnostics:
  pulumi:pulumi:Stack (castle-dev):
    Processing /home/astraluma/src/awsgi
    Collecting boto3-extensions==0.12.2 (from -r /tmp/tmpf49ws7hd (line 3))
    Collecting boto3==1.9.197 (from -r /tmp/tmpf49ws7hd (line 4))
      Using cached https://files.pythonhosted.org/packages/df/2a/e77374950632d42b36d62a74ec15e56dc1ffabab15be6fc18395d9136b6d/boto3-1.9.197-py2.py3-none-any.whl
    Collecting botocore==1.12.197 (from -r /tmp/tmpf49ws7hd (line 5))
      Using cached https://files.pythonhosted.org/packages/7e/3e/ba5f2c7f1ca24c128401efd364c9a5231f411ec83328659c9a0321d82d45/botocore-1.12.197-py2.py3-none-any.whl
    Collecting click==7.0 (from -r /tmp/tmpf49ws7hd (line 6))
      Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
    Collecting docutils==0.14 (from -r /tmp/tmpf49ws7hd (line 7))
 
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/astraluma/.local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 566, in run_until_complete
        self.run_forever()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
        self._run_once()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 1756, in _run_once
        handle = self._ready.popleft()
    IndexError: pop from an empty deque
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
 
    exception calling callback for <Future at 0x7f20d0962d90 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 728, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
    exception calling callback for <Future at 0x7f20d3a00e90 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 728, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
    exception calling callback for <Future at 0x7f20d091de50 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 728, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
```

`git bisect` pins the blame on 63eb7abb5949e562b20bf9fe43bac1868e730774 aka #3019.

I suspect the triggering code is https://github.com/dingbots/deplumi/blob/master/deplumi/builders/pipenv.py but i have no confirmation on that yet.

I'm still working to produce a reduced test case. Trivial ones don't reproduce the bug.

**Comment by astronouth7303** [comment]
Test case:

```
import pulumi
import pulumi_aws

pulumi_aws.s3.Bucket('bucket')


async def test():
    zone = await pulumi_aws.route53.get_zone(name='dingbots.dev')
    return zone.arn

pulumi.export('zone', test())
```

**Comment by astronouth7303** [comment]
Ok, my reproduction is:

```
import asyncio
import pulumi_aws

asyncio.create_task(pulumi_aws.iam.get_policy('arn:aws:iam::aws:policy/AdministratorAccess'))
asyncio.create_task(pulumi_aws.iam.get_policy('arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'))
```

I think this will work as long as you have a functioning AWS setup (you've logged in to awscli and configured a region in awscli or pulumi)

**Comment by astronouth7303** [comment]
As far as I can tell, you need 2 `get*()` calls and create tasks out of them.

**Comment by pgavlin** [comment]
Okay, I can imagine how that might be a problem: both of these tasks will attempt to run the event loop simultaneously. I'll look into this.

**Comment by pgavlin** [comment]
To be more precise, one task may try to run the other when pumping the event loop. The other task will then attempt the same. While this seems like it could work, I can also imagine that it may be an issue.

**Comment by pgavlin** [comment]
I can confirm that this reproduces the `IndexError: pop from an empty deque` error.

**Comment by astronouth7303** [comment]
Maybe it'd be better to explicitly build a version of the event loop for reentrancy so it can track that data? I'm having trouble visualizing that against the now-dual nature (sync and async) of `invoke()`?

**Comment by pgavlin** [comment]
Interestingly enough, that repro only appears to happen when using an older AWS SDK with a newer Pulumi SDK. The following code works as expected after manually editing the older AWS SDK to the newer, non-coroutine-style of code we now generate:

```
asyncio.ensure_future(pulumi_aws.iam.get_policy('arn:aws:iam::aws:policy/AdministratorAccess'))
asyncio.ensure_future(pulumi_aws.iam.get_policy('arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'))
```

I imagine that the behavior reported in this issue is still possible if a user-written coroutine awaits the result of an invoke. Checking that now.

**Comment by pgavlin** [comment]
Confirmed: the code below also produces the `pop from an empty deque` error.

```
async def get_policy(policy):
    return await pulumi_aws.iam.get_policy(policy)

asyncio.ensure_future(get_policy('arn:aws:iam::aws:policy/AdministratorAccess'))
asyncio.ensure_future(get_policy('arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'))
```
