### ISSUE TITLE
Allow passing configuration/arguments to underlying runtime engine

### ISSUE THREAD

**Issue by jonjitsu** [pulumi/pulumi#3061]
I'm using  pulumi with typescript and mocha for testing. I added a paths configuration to my tsconfig.json like so:

```
{
    "compilerOptions": {
       ...
        "baseUrl": ".",
        "paths": {
            "@jonjitsu/*": ["src/*"]
        }
    }
    ...
}
```

in my mocha tests I access my code like so:
```
import * as foo from '@jonjitsu/foo'
```

run my mocha tests with ts-mocha:
```
    ts-mocha \
        --paths 'src/**/*.ts' \
        -p tsconfig.json \
        'tests/unit/**/*.test.ts' "$@"
```

And everything works fine.

In my pulumi program if I try to access my code with the above namespaced import `import * as foo from '@jonjitsu/foo'` I get the `Error: Cannot find module '@jonjitsu/foo` typescript error. It doesn't seem to respect the paths tsconfig.json values.

Playing around with ts-node I got the same error until I tried `ts-node -r tsconfig-paths/register index.ts` and then I got the normal must be run with pulumi CLI error.

It would be nice to somehow pass arguments/configuration to the underlying runtime engine (in this case nodejs/typescript).

**Comment by lukehoban** [comment]
> Playing around with ts-node I got the same error until I tried ts-node -r tsconfig-paths/register index.ts and then I got the normal must be run with pulumi CLI error.

Should we be including `tsconfig-paths/register` by default?  I'm not sure the implications of that.

**Comment by jonjitsu** [comment]
> Should we be including tsconfig-paths/register by default? I'm not sure the implications of that.
That would be useful but I'm not sure if that would break existing systems out there. 

Maybe a good start would be to extend the Pulumi.yaml runtime configuration to allow passing arguments and even overriding these hardcoded values: https://github.com/pulumi/pulumi/blob/70bc0436ed165ec1fbebdda33e033e71e1ae5aa7/sdk/nodejs/cmd/run/run.ts#L154-L160

**Comment by masterada** [comment]
any update on this?

**Comment by yohanb** [comment]
Bump!  This is a great feature to clean up imports.

**Comment by Sytten** [comment]
Is there an alternative, I also want to use this feature.

**Comment by yohanb** [comment]
@Sytten you can use [module-alias](https://www.npmjs.com/package/module-alias) as a "polyfill" for this.

**Comment by Sytten** [comment]
Bumping the thread since there was no progress

**Comment by tmehlinger** [comment]
I would also like this. Just an option to `ts-node -r tsconfig-paths/register` would be a great start.

**Comment by darrensmithwtc** [comment]
> @Sytten you can use [module-alias](https://www.npmjs.com/package/module-alias) as a "polyfill" for this.

Hi @yohanb - I don't suppose you have any examples for this?

My setup is a NX mono-repo style configuration and I'm struggling to get the module-aliases working.

I have a root workspace level;

./package.json
./ts-config.base.json

Then folders for each app;

./apps/
./apps/pulumi-app/
./apps/pulumi-app/tsconfig.json
./apps/pulumi-app/Pulumi.yaml
./apps/pulumi-app/Pulumi.dev.yaml
./apps/pulumi-app/src/index.ts
./apps/pulumi-app/src/package.json -> SYMLINK = ../../../package.json
./apps/pulumi-app/src/node_modules-> SYMLINK = ../../../node_modules

The SYMLINKs enable me to include inline serialized functions without any issues.

./libs/
./libs/pulumi/
./libs/pulumi/helpers/
./libs/pulumi/helpers/tsconfig.json { extends the root project tsconfig.base.json }
./libs/pulumi/helpers/src/
./libs/pulumi/helpers/src/index.ts  { exports the interesting things out the lib folder }
./libs/pulumi/helpers/src/lib/myFunc.ts

In the root tsconfig.base.json, it has the path statements in. i.e.

    "paths": {
      "@workspace/pulumi/helpers": ["libs/pulumi/helpers/src/index.ts"],
      }

So in my apps/pulumi-app/src/index.ts - I can import { myFunc } from "@workspace/pulumi/helpers" without any TS errors.

Which obviously doesn't work currently, however if i go down the ../../../../ style route for every library and not use the paths at all, it works perfectly, just a little verbose ;-)

So I installed module-aliases and tried adding the package.json route, i.e.

"_moduleAliases": {
      "@workspace/pulumi/helpers": "libs/pulumi/helpers/src/index.ts"
}

config to my root package.json and tried to:

  import 'module-alias/register';

as the first line of the pulumi-app index.ts, but pulumi still can't find the module.

I then tried manually adding the entries;

import 'module-alias/register';
const moduleAlias = require('module-alias');
moduleAlias.addAlias('@workspace/pulumi/helpers',__dirname+'../libs/pulumi/helpers/src/index.ts');

Still to no avail.

Finally i decided to try using the automation library and not use the pulumi binary.  Same issue.

` 
     'Diagnostics:\n' +
      '  pulumi:pulumi:Stack (pulumi-app):\n' +
      "    error: Running program 'D:\\code\\workspace\\apps\\pulumi-app\\src\\index.ts' failed with an unhandled exception:\n" +
      '    TSError: ⨯ Unable to compile TypeScript:\n' +
      "    index.ts(10,31): error TS2307: Cannot find module '@workspace/pulumi/helpers'.\n" +
      '    \n' +
      '        at createTSError (D:\\code\\workspace\\node_modules\\@pulumi\\pulumi\\node_modules\\ts-node\\src\\index.ts:261:12)\n' +
      '        at getOutput (D:\\code\\workspace\\node_modules\\@pulumi\\pulumi\\node_modules\\ts-node\\src\\index.ts:367:40)\n' +
      '        at Object.compile (D:\\code\\workspace\\node_modules\\@pulumi\\pulumi\\node_modules\\ts-node\\src\\index.ts:558:11)\n' +
      '        at Module.m._compile (D:\\code\\workspace\\node_modules\\@pulumi\\pulumi\\node_modules\\ts-node\\src\\index.ts:439:43)\n' +
      '        at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n' +
      '        at Object.require.extensions.<computed> [as .ts] (D:\\code\\workspace\\node_modules\\@pulumi\\pulumi\\node_modules\\ts-node\\src\\index.ts:442:12)\n' +
      '        at Module.load (internal/modules/cjs/loader.js:928:32)\n' +
      '        at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n' +
      '        at Module.require (internal/modules/cjs/loader.js:952:19)\n' +
      '        at require (internal/modules/cjs/helpers.js:88:18)\n' +
      `
Any thoughts?

As a side note, I've been experimenting with some NX generators and executors so I can now scaffold out Pulumi programs and add stacks and do stuff like; `nx run pulumi-app:up:dev` to fire off the automation api to launch the stack etc.

Many Thanks

Darren Smith

**Comment by nesl247** [comment]
There seem to be about 4 different issues all related to pulumi overriding `compilerOptions`:

https://github.com/pulumi/pulumi/issues/2673
https://github.com/pulumi/pulumi/issues/3061 (this one)
https://github.com/pulumi/pulumi/issues/4829
https://github.com/pulumi/templates/issues/116

It would be great if this could be fixed.

**Comment by plmercereau** [comment]
You may try to add the following code on top of your main typescript file e.g. `index.ts`:
```ts
/* eslint-disable @typescript-eslint/no-var-requires */
const tsConfig = require("./tsconfig.json")
const tsConfigPaths = require("tsconfig-paths")
 tsConfigPaths.register({
  baseUrl: './',
  paths: tsConfig.compilerOptions.paths
})
```

**Comment by darrensmithwtc** [comment]
> You may want to try to add the following code on top of your main typescript file e.g. `index.ts`:
> 
> ```ts
> /* eslint-disable @typescript-eslint/no-var-requires */
> const tsConfig = require("./tsconfig.json")
> const tsConfigPaths = require("tsconfig-paths")
>  tsConfigPaths.register({
>   baseUrl: './',
>   paths: tsConfig.compilerOptions.paths
> })
> ```

Thank You @plmercereau! :), Had time to look today and by making a few changes to the repo it's now working.....

./apps/
./apps/pulumi-app/
./apps/pulumi-app/tsconfig.json
./apps/pulumi-app/Pulumi.yaml
./apps/pulumi-app/Pulumi.dev.yaml
./apps/pulumi-app/index.ts                                                                  <-- I had to drop the entrypoint to the root, not src/
./apps/pulumi-app/package.json -> SYMLINK = ../../package.json      <-- same with the
./apps/pulumi-app/node_modules-> SYMLINK = ../../node_modules  <-- symlinks a directory back

As the tsconfig.json inherits the base properties in the root of the repo, I took the approach of using the loadConfig method on the tsconfig-paths library, so my whole snippet was;

`
import { register, loadConfig } from "tsconfig-paths";
const config = loadConfig('.');
if (config.resultType === 'failed') {
    console.log('Could not load tsconfig to map paths, aborting.');
    process.exit(1);
}

register({
  baseUrl: config.absoluteBaseUrl,
  paths: config.paths
});
`
and voilla! I can now do my path based imports, so I can simply do stuff like;

`import { xyzHelper } from '@workspace/pulumi/helpers' ` 

and use it directly in multiple Pulumi programs if needed and benefit from NX's dep graph system for knowing which projects need their stacks updated.

**Comment by duro** [comment]
Bumping this again. While I see that some changes were pushed to no longer override certain compilerOptions, this still does not allow for usage of the "paths" option. When I add that to my tsConfig, I still get errors:

`Cannot find module '@my-project/cloud-components'`

**Comment by Badabum** [comment]
@darrensmithwtc can you share your `tsconfig` for pulumi project and the `tsconfig.base` if you're referencing it?

**Comment by mckinnsb** [comment]
going to bump this again, using `paths` in a Pulumi project is a real hassle right now

**Comment by Yu-Jack** [comment]
I share how I use `tsconfig` `paths` with multiple services in one repo and different folders. Here is a simple demo repo https://github.com/Yu-Jack/pulumi-arc.

Because you need to run the `pulumi` command with `index.ts`, so you should put the `tsconfig` with it. 

```
├── README.md
├── package-lock.json
├── package.json
├── service_a
│   ├── Pulumi.dev.yaml
│   ├── Pulumi.yaml
│   ├── index.ts
│   ├── lib
│   │   └── a.ts
│   └── tsconfig.json
├── service_b
│   ├── Pulumi.dev.yaml
│   ├── Pulumi.yaml
│   ├── index.ts
│   ├── lib
│   │   └── b.ts
│   └── tsconfig.json
└── shared_lib
    └── log.ts
```

Then if you have shared libs,  you should define it in `tsconfig` like this.

```
"paths": {
    "@shared_lib/*": ["../shared_lib/*"],
    "@lib/*": ["./lib/*"]
}
```

**Comment by DavidArmendariz** [comment]
Any updates on this?

**Comment by dougludlow** [comment]
The version of ts-node that pulumi depends on will need to be updated, since the current version `[v7.0.1](https://github.com/pulumi/pulumi/blob/1ce55299c3ada0787fd5f1e0251777116ecca7ca/sdk/nodejs/package.json#L25)` doesn't support the `require` parameter.

**Comment by dougludlow** [comment]
Here's a possible workaround if you are using nx and yarn. 

For some context, we place our pulumi project files in an `infrastructure` folder beside the `src` folder of an nx project. So our project structure roughly resembles something like this:

```
|-- apps
|   |-- project1
|   |   |-- src
|   |   |-- infrastructure
|   |   |   |-- index.ts
|   |   |   |-- Pulumi.yaml
|   |   |-- project.json
|   |   |-- tsconfig.json
|-- libs
|   |-- lib1
|   |   |-- src
|   |   |   |-- index.ts
|-- nx.json
|-- package.json
|-- ts-config.base.json
|-- workspace.json
```

The `tsconfig.base.json` defines the `paths` roughly like this:

```json
{
    "compilerOptions": {
        // ...
        "paths": {
            "@my-workspace/lib1": ["libs/lib1/src/index.ts"]
        }
    }
}
```

1. Install the latest `ts-node` (`v10.8.0` at the time of this writing) and `tsconfig-paths`.

   ```bash
   yarn add --dev ts-node@10.8.0 tsconfig-paths
   ```
2. Update the `package.json` to use yarn's resolutions to force pulumi to use the version of ts-node you just installed:
   **`./package.json`**
   ```json
   {
        //...
        "resolutions": {
            "ts-node": "10.8.0"
        }
   }
   ```
3. Add the following script to the root of your project to allow `tsconfig-paths` to register the baseUrl and paths. I've put mine in a `scripts` directory.
   **`./scripts/tsconfig-paths.js`**
   ```js
   // this is needed until https://github.com/pulumi/pulumi/issues/3061 is resolved
   const { loadConfig, register } = require('tsconfig-paths');
   const minimist = require('minimist');
   
   const isPulumiCommand = process.argv[1]?.includes('pulumi') ?? false;
   if (!isPulumiCommand) {
       return;
   }
   
   const argv = minimist(process.argv.slice(2), { string: ['pwd'] });
   const tsConfig = loadConfig(argv.pwd);
   if (tsConfig.resultType === 'failed') {
       console.log('Could not load tsconfig to map paths, aborting.');
       process.exit(1);
   }
   
   register({
       baseUrl: tsConfig.absoluteBaseUrl,
       paths: tsConfig.paths,
   });
   ```
4. Update your base tsConfig to tell `ts-node` to use the script:
   **`./tsconfig.base.json`**
   ```json
   {
       // ...
       "ts-node": {
           "require": ["./scripts/tsconfig-paths"]
       }
   }
   ```
5. Add a `tsconfig.json` to the pulumi project with the following content:
   ```json
   {
       "extends": "../../tsconfig.json"
   }
   ```
6. Run `pulumi` and it will resolve the import from the lib without issue.

**Comment by Fydon** [comment]
Thank you dougludlow.

I have all my files like the following, where all my code files under `src` except the index.ts that Pulumi read.

```
|-- src
|    |-- foo
|    |    |-- bar.ts
|    |-- some-file.ts
|-- index.ts
|-- package.json
|-- Pulumi.yaml
|-- tsconfig.json
```
dougludlow's solution worked until I needed to use top level await. During the Pulumi runtime I received an error like the following:

```
error: Running program 'c:\some\path' failed with an unhandled exception:
    Error: Cannot find package 'src' imported from c:\some\path\src\foo\bar.ts
```

I eventually got it working using [imports in packages.json](https://nodejs.org/api/packages.html#packages_imports) and adding `#` to the start of all my absolute paths.

package.json:
```
{
    "imports": {
        "#src/*": {
            "default": "./src/*"
        }
    },
    ...
}
```

bar.ts:
```
import { someObject } from '#src/some-file.ts'

...
```

If someone is able to get this working without imports and with top level await, please let me know.

**Comment by samox73** [comment]
I am curious why Pulumi does not load and use the `tsconfig.json`. Since a `pulumi new` generates the file, I find it very confusing and misleading that the options supplied in it are not actually used. Is there another way to load `baseUrl` and `paths` from the `tsconfig.json` without the workaround @Yu-Jack shared? In a micro-project architecture with 20+ projects this solution does not scale well.

**Comment by coopbri** [comment]
Aside from the nested `tsconfig`/module path aliasing solution already described above, another solution (if you can fit it into your architecture) is to use inline programs with the automation API (specifically inline programs, since the path aliasing is shared in-memory/in-process). Of course, the solution people described above works for local programs 👍 It could be further automated with tooling, such as [Turborepo](https://turborepo.org/), etc.

In the case of the automation API specifically, it might be cool to have a solution where the original executing program can be composed with custom code around it. For example:

```ts
 await stack.up({
      program: (fn) => { // <-- `fn` is added here, not part of current API
        // execute custom code before local program here, such as TS path registration
        
        // execute original function
        fn();

        // execute custom code after local program here
      },
    });
```

Currently, `program` expects a `PulumiFn`, which does not carry this context with it. In other words, replace (or overload) the return signature of `program` from `PulumiFn` to `(originalProgram: PulumiFn) => PulumiFn`.

I have no idea if that is feasible, it's just a pattern I naturally went to try while testing this. I understand this might conflict in the underlying architecture (especially considering inline programs, which use `program` by nature).

Another approach could be to have a pre-hook function that is executed in the local program process, which could be passed as a separate parameter (e.g. called `before`), and possibly a symmetrical post-hook function (`after`).

**Comment by wmodden** [comment]
I'm getting a similar error when using pulumi on a monorepo (`turborepo`).

Whenever I import an internal package on my pulumi iac code (`import { environments } from '@fanzi/common'`) I get the following error

```
error: Running program '/Users/william/Documents/fanzihq/iac/infrastructure/web/src/index.ts' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    index.ts(3,74): error TS2307: Cannot find module '@fanzi/common' or its corresponding type declarations.
      There are types at '/Users/william/Documents/fanzihq/iac/node_modules/@fanzi/common/src/constants.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.
```

But If I use relative paths (`import { environments } from '../../../../../src/constants'`), it works as expected.

**Comment by ashish111333** [comment]
@wmodden  is this a language specific problem  or its true for all pulumi sdks ??

**Comment by iwahbe** [comment]
Pulumi should load the `tsconfig.json` file & https://github.com/pulumi/pulumi/pull/8655 allowed passing args to the underlying node process: https://www.pulumi.com/docs/iac/concepts/projects/project-file/#runtime-options.
