### ISSUE TITLE
Panic on update - Should not have seen an older plugin

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi#3068]
```
Pulumi Version:   v0.17.28
Go Version:       go1.12.7
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: A failure has occurred: Should not have seen an older plugin if sorting is correct!

goroutine 1 [running]:
runtime/debug.Stack(0xc000801e40, 0x1f35900, 0xc000982480)
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/main.go:30 +0x6e
panic(0x1f35900, 0xc000982480)
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:522 +0x1b5
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Failf(0x223261a, 0x3b, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/util/contract/fail.go:30 +0x182
github.com/pulumi/pulumi/pkg/engine.computeDefaultProviderPlugins(0xc0010eba10, 0xc000f6c360, 0x0)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/engine/plugins.go:254 +0x88c
github.com/pulumi/pulumi/pkg/engine.installPlugins(0xc000614b80, 0xc000f8ae80, 0x25, 0x21e8685, 0x1, 0xc0010eb620, 0xc0004b8410, 0x0, 0x0, 0x25, ...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/engine/update.go:154 +0x16d
github.com/pulumi/pulumi/pkg/engine.newUpdateSource(0x24ac460, 0xc0008a4ba0, 0x315bd70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/engine/update.go:183 +0x80
github.com/pulumi/pulumi/pkg/engine.plan(0xc0010bc080, 0xc000240ce0, 0x315bd70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/engine/plan.go:132 +0x294
github.com/pulumi/pulumi/pkg/engine.update(0xc0010bc080, 0xc000240ce0, 0x315bd70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/engine/update.go:216 +0x96
github.com/pulumi/pulumi/pkg/engine.Update(0x24b6d60, 0xc0010f3440, 0xc0010bc080, 0x315bd70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, ...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/engine/update.go:105 +0x420
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).runEngineAction(0xc00045d980, 0x24c3820, 0xc0000f2000, 0x21ec8f8, 0x6, 0x24ac420, 0xc000130540, 0xc000614b80, 0xc000f8ae80, 0x25, ...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:847 +0xa25
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).apply(0xc00045d980, 0x24c3820, 0xc0000f2000, 0x21ec8f8, 0x6, 0x24df640, 0xc0001e6000, 0xc000614b80, 0xc000f8ae80, 0x25, ...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:726 +0x285
github.com/pulumi/pulumi/pkg/backend.PreviewThenPromptThenExecute(0x24c3820, 0xc0000f2000, 0x21ec8f8, 0x6, 0x24df640, 0xc0001e6000, 0xc000614b80, 0xc000f8ae80, 0x25, 0xc000601a60, ...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/backend/apply.go:208 +0xdd
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).Update(0xc00045d980, 0x24c3820, 0xc0000f2000, 0x24ac420, 0xc0010e8180, 0xc000614b80, 0xc000f8ae80, 0x25, 0xc000601a60, 0x315bd70, ...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:600 +0x1ca
github.com/pulumi/pulumi/pkg/backend.UpdateStack(0x24c3820, 0xc0000f2000, 0x24df640, 0xc0003321c0, 0xc000614b80, 0xc000f8ae80, 0x25, 0xc000601a60, 0x315bd70, 0x0, ...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/backend/stack.go:86 +0xf8
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudStack).Update(0xc0003321c0, 0x24c3820, 0xc0000f2000, 0xc000614b80, 0xc000f8ae80, 0x25, 0xc000601a60, 0x315bd70, 0x0, 0x0, ...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/backend/httpstate/stack.go:146 +0x96
github.com/pulumi/pulumi/cmd.newUpCmd.func1(0x315bd70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/cmd/up.go:114 +0x713
github.com/pulumi/pulumi/cmd.newUpCmd.func3(0xc0001b4a00, 0xc0001c7480, 0x0, 0x1, 0x0, 0x0)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/cmd/up.go:345 +0x35b
github.com/pulumi/pulumi/pkg/util/cmdutil.RunResultFunc.func1(0xc0001b4a00, 0xc0001c7480, 0x0, 0x1)
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc0001b4a00, 0xc0001c7450, 0x1, 0x1, 0xc0001b4a00, 0xc0001c7450)
	/private/tmp/pulumi-20190805-61331-sfwbvz/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b4500, 0x2254180, 0x0, 0x0)
	/private/tmp/pulumi-20190805-61331-sfwbvz/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/pulumi-20190805-61331-sfwbvz/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/private/tmp/pulumi-20190805-61331-sfwbvz/src/github.com/pulumi/pulumi/main.go:49 +0x4c
```

**Comment by lblackstone** [comment]
Not sure if it's related, but I encountered this error right after I caused a panic in the k8s provider. I ended up destroying the resources in the stack and then recreating them, at which point it showed the panic in the k8s provider rather than the reported panic here.

**Comment by stack72** [comment]
@lblackstone can you suggest some steps of what you did up until this happened?

**Comment by lblackstone** [comment]
@stack72 I had accidentally introduced a panic in the await logic for one the resources in the k8s provider. The next time I ran an update, I saw the reported panic, and no mention of the underlying panic in the k8s provider.

**Comment by pgavlin** [comment]
Closing this out as we haven't been able to reproduce this. We did add additional logging to make the issue clearer if we ever see this again.
