### ISSUE TITLE
Need StackReference tests that use /older/ CLIs with /newer/ SDKs.

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3127]
With `1.0.0-beta.3` many/most uses of StackReference throw.

```
Diagnostics:
  pulumi:pulumi:Stack (ff-data-import-lambda-dev):
    error: Running program '/builds/factsfirst/ff-data-import-lambda' failed with an unhandled exception:
    TypeError: Cannot read property 'outputs' of undefined
        at /builds/factsfirst/ff-data-import-lambda/node_modules/@pulumi/pulumi/stackReference.js:117:31
        at Generator.next (<anonymous>)
        at fulfilled (/builds/factsfirst/ff-data-import-lambda/node_modules/@pulumi/pulumi/stackReference.js:17:58)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:189:7)
        at Function.module.exports.loopWhile (/builds/factsfirst/ff-data-import-lambda/node_modules/deasync/index.js:70:11)
        at Object.promiseResult (/builds/factsfirst/ff-data-import-lambda/node_modules/@pulumi/pulumi/utils.js:80:13)
        at StackReference.getOutputSync (/builds/factsfirst/ff-data-import-lambda/node_modules/@pulumi/pulumi/stackReference.js:86:34)
        at Object.<anonymous> (/builds/factsfirst/ff-data-import-lambda/index.js:14:19)
        at Module._compile (module.js:653:30)
```

See https://pulumi-community.slack.com/archives/C84L4E3N1/p1566434791458700.

This appears to be the issue https://github.com/pulumi/pulumi/compare/lukehoban/fixstackreference.  But we also need to add test coverage around this.

**Comment by ellismg** [comment]
`1.0.0-beta.4` has been released and has the fix for this.  The testing hole here was using the current SDK with an older CLI.  Lowering the priority as this now just tracks trying to get test coverage here.

**Comment by lukehoban** [comment]
Closing this one out - as we addressed the original bug here.

I've opened https://github.com/pulumi/pulumi/issues/3137 on the test coverage for new+old CLI+pkgs more generally,
