### ISSUE TITLE
Inscrutable error message accessing member with `Output.py`

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#3158]
This error happened to me once, and it subsequently went away—I'm sorry I don't have more details. From the stack trace, I'm gathering that somehow we subscripted an `Output` that happened to be `None` (_e.g._, `output_of_null["foo"]`) and it exploded.

The error message seems like it could have been more helpful here, perhaps telling me what `v` was, at least.

```
  pulumi:pulumi:Stack (istio-test-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/opt/pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 41, in run_in_stack
        await RPC_MANAGER.unhandled_exeception()
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        result = await rpc_function(*args, **kwargs)
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 414, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 67, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 159, in serialize_property
        value = await serialize_property(value.future(), deps, input_transformer)
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 147, in serialize_property
        future_return = await asyncio.ensure_future(value)
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/output.py", line 149, in run
        value = await self._future
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/output.py", line 149, in run
        value = await self._future
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/output.py", line 149, in run
        value = await self._future
      [Previous line repeated 3 more times]
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/output.py", line 161, in run
        transformed: Input[U] = func(value)
      File "/Users/alex/.local/share/virtualenvs/app-DGyeJ8l9/lib/python3.7/site-packages/pulumi/output.py", line 217, in <lambda>
        return self.apply(lambda v: v[key])
    TypeError: 'NoneType' object is not subscriptable
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by mikhailshilkov** [comment]
This doesn't look actionable, so I'll go ahead and close
