### ISSUE TITLE
Exceptions in Windows are not propagated to stdout

### ISSUE THREAD

**Issue by 4c74356b41** [pulumi/pulumi#3192]
Code with exception on windows:
```
    error: Program failed with an unhandled exception:
    error: NoneType: None
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```
same code with exception on linux:

```
  pulumi:pulumi:Stack (aks-testing):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
      File "/usr/local/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/usr/local/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 37, in run_in_stack
        Stack(func)
      File "/usr/local/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 96, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/local/lib/python3.6/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 94, in <module>
        "vmSize": cluster_vm_size_mapper[aks_name],
    KeyError: 'testing-aks'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

this happens with any code I've tried. windows 10, python 3.6.8, pulumi 1.0 (but the same happened with 0.16.x and 0.17.x)

**Comment by mikhailshilkov** [comment]
@4c74356b41 I'm sorry for such a long response time, but I've finally tried to reproduce the issue.

I tried a basic program like 

```python
import pulumi

def crash(s):
  print('Hello')
  boom(s)

pulumi.export('connection_string', crash('hello'))
```

Running `pulumi up` on Windows yields

```
pulumi:pulumi:Stack (azure-play-python-dev):
 error: Program failed with an unhandled exception:
 error: Traceback (most recent call last):
 File "C:\Users\shilk\.pulumi\bin\pulumi-language-python-exec", line 85, in <module>
 loop.run_until_complete(coro)
 File "C:\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
 return future.result()
 File "C:\Python36\lib\asyncio\tasks.py", line 180, in _step
 result = coro.send(None)
 File "C:\Python36\lib\site-packages\pulumi\runtime\stack.py", line 37, in run_in_stack
 Stack(func)
 File "C:\Python36\lib\site-packages\pulumi\runtime\stack.py", line 95, in __init__
 func()
 File "C:\Users\shilk\.pulumi\bin\pulumi-language-python-exec", line 84, in <lambda>
 coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
 File "C:\Python36\lib\runpy.py", line 280, in run_path
 run_name, mod_spec, pkg_name).copy()
 File "C:\Python36\lib\runpy.py", line 85, in _run_code
 exec(code, run_globals)
 File ".\__main__.py", line 9, in <module>
 pulumi.export('connection_string', crash('hello'))
 File ".\__main__.py", line 6, in crash
 boom(s)
 NameError: name 'boom' is not defined
 error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

and on a Mac:

```
 pulumi:pulumi:Stack (azure-py-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
        return future.result()
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 38, in run_in_stack
        Stack(func)
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 96, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 7, in <module>
        pulumi.export('connection_string', crash('hello'))
      File "./__main__.py", line 5, in crash
        boom(s)
    NameError: name 'boom' is not defined
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

which look very similar to me.

May I ask you to try again with a current version (I'm on Pulumi 1.9.1) and report back a simple repro code if you find one? Thank a ton!

**Comment by 4c74356b41** [comment]
sorry, dont have window + python anywhere right now, you can probably close this for now, I'll test some time later and get back to you if it doesn't work
