### ISSUE TITLE
`pulumi version` panic SIGSEGV

### ISSUE THREAD

**Issue by zhangyoufu** [pulumi/pulumi#3199]
`pulumi version` crash for fresh installation on macOS

```
$ rm -rf ~/.pulumi
$ pulumi version
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x3f0338 pc=0x7fff9a8284dd]
```

<details><summary>click for full stack trace</summary>

```
runtime stack:
runtime.throw(0x221dbfd, 0x2a)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/signal_unix.go:374 +0x4a9

goroutine 38 [syscall]:
runtime.cgocall(0x10020d0, 0xc000529470, 0xc0003661b8)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/cgocall.go:128 +0x5b fp=0xc000529440 sp=0xc000529408 pc=0x1004e7b
crypto/x509._Cfunc_FetchPEMRoots(0xc0003661b0, 0xc0003661b8, 0xc000340b00, 0x0)
	_cgo_gotypes.go:110 +0x4d fp=0xc000529470 sp=0xc000529440 pc=0x127909d
crypto/x509.loadSystemRoots.func1(0xc0003661b0, 0xc0003661b8, 0x20300000000000)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/crypto/x509/root_cgo_darwin.go:281 +0x12d fp=0xc0005294b0 sp=0xc000529470 pc=0x127d1bd
crypto/x509.loadSystemRoots(0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/crypto/x509/root_cgo_darwin.go:281 +0xec fp=0xc000529580 sp=0xc0005294b0 pc=0x127920c
crypto/x509.initSystemRoots()
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/crypto/x509/root.go:21 +0x26 fp=0xc0005295a8 sp=0xc000529580 pc=0x126bc36
sync.(*Once).Do(0x3217e30, 0x224b6f8)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/sync/once.go:44 +0xb3 fp=0xc0005295d8 sp=0xc0005295a8 pc=0x1073063
crypto/x509.systemRootsPool(...)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/crypto/x509/root.go:16
crypto/x509.(*Certificate).Verify(0xc0000f0580, 0xc0000c4200, 0xe, 0xc00027e180, 0x0, 0xbf554ec08d565650, 0x32cda738, 0x31fab60, 0x0, 0x0, ...)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/crypto/x509/verify.go:744 +0x6b8 fp=0xc0005296f0 sp=0xc0005295d8 pc=0x126ff78
crypto/tls.(*Conn).verifyServerCertificate(0xc0003d1880, 0xc00009f740, 0x4, 0x4, 0x12dd, 0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/crypto/tls/handshake_client.go:838 +0x26a fp=0xc000529888 sp=0xc0005296f0 pc=0x12a235a
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc000529dc8, 0xc00037c0e0, 0x62)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/crypto/tls/handshake_client.go:454 +0x1872 fp=0xc000529bc0 sp=0xc000529888 pc=0x12a04c2
crypto/tls.(*clientHandshakeState).handshake(0xc000529dc8, 0xc0004d4480, 0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/crypto/tls/handshake_client.go:399 +0x3fb fp=0xc000529cc8 sp=0xc000529bc0 pc=0x129e87b
crypto/tls.(*Conn).clientHandshake(0xc0003d1880, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/crypto/tls/handshake_client.go:208 +0x2cd fp=0xc000529f38 sp=0xc000529cc8 pc=0x129cecd
crypto/tls.(*Conn).Handshake(0xc0003d1880, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/crypto/tls/conn.go:1343 +0xef fp=0xc000529f78 sp=0xc000529f38 pc=0x129b4ef
net/http.(*persistConn).addTLS.func2(0x0, 0xc0003d1880, 0xc000150000, 0xc0000c80c0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/transport.go:1190 +0x42 fp=0xc000529fc0 sp=0xc000529f78 pc=0x1370832
runtime.goexit()
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000529fc8 sp=0xc000529fc0 pc=0x105d451
created by net/http.(*persistConn).addTLS
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/transport.go:1186 +0x1ab

goroutine 1 [select]:
net/http.(*Transport).getConn(0x31e7020, 0xc000427620, 0x0, 0xc0000f6090, 0x5, 0xc0000c4200, 0x12, 0x0, 0x0, 0x0, ...)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/transport.go:1020 +0x63d
net/http.(*Transport).roundTrip(0x31e7020, 0xc00053ae00, 0x10, 0xc0000cf270, 0xc00052cac0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/transport.go:467 +0x76e
net/http.(*Transport).RoundTrip(0x31e7020, 0xc00053ae00, 0x31e7020, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc00053ae00, 0x2494f20, 0x31e7020, 0x0, 0x0, 0x0, 0xc0000101b0, 0x31f7c00, 0x1, 0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/client.go:250 +0x202
net/http.(*Client).send(0x31fa840, 0xc00053ae00, 0x0, 0x0, 0x0, 0xc0000101b0, 0x0, 0x1, 0x1)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/client.go:174 +0xfb
net/http.(*Client).do(0x31fa840, 0xc00053ae00, 0x0, 0x0, 0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/client.go:641 +0x279
net/http.(*Client).Do(...)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/client.go:509
github.com/pulumi/pulumi/pkg/util/httputil.DoWithRetry.func2(0x0, 0x8f0d180, 0x20ca760, 0x374e498, 0xc00052cf88, 0x20, 0x20)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/httputil/http.go:49 +0x58
github.com/pulumi/pulumi/pkg/util/retry.Until(0x24bfbe0, 0xc0000d4000, 0xc0004b6940, 0x0, 0x0, 0x0, 0x13a6ed9, 0x100b71b, 0x10, 0x1f2b1c0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/retry/until.go:74 +0xcf
github.com/pulumi/pulumi/pkg/util/httputil.DoWithRetry(0xc00053ae00, 0x31fa840, 0xc0000cf230, 0xf, 0xc0000ec0d0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/httputil/http.go:38 +0xea
github.com/pulumi/pulumi/pkg/backend/httpstate/client.pulumiAPICall(0x24bfbe0, 0xc0000d4000, 0x24cddc0, 0xc000427020, 0x21fd3d5, 0x16, 0x21e3b49, 0x3, 0x21f2f9b, 0x10, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/client/api.go:201 +0xebe
github.com/pulumi/pulumi/pkg/backend/httpstate/client.pulumiRESTCall(0x24bfbe0, 0xc0000d4000, 0x24cddc0, 0xc000427020, 0x21fd3d5, 0x16, 0x21e3b49, 0x3, 0x21f2f9b, 0x10, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/client/api.go:276 +0x180
github.com/pulumi/pulumi/pkg/backend/httpstate/client.(*Client).restCall(...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/client/client.go:68
github.com/pulumi/pulumi/pkg/backend/httpstate/client.(*Client).GetCLIVersionInfo(0xc00052d750, 0x24bfbe0, 0xc0000d4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/client/client.go:152 +0x188
github.com/pulumi/pulumi/cmd.getCLIVersionInfo(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/cmd/pulumi.go:228 +0x354
github.com/pulumi/pulumi/cmd.checkForUpdate()
	/Users/travis/gopath/src/github.com/pulumi/pulumi/cmd/pulumi.go:209 +0x1e4
github.com/pulumi/pulumi/cmd.NewPulumiCmd.func1(0xc0004b9680, 0x3217d90, 0x0, 0x0, 0xc0000cf160, 0xc000234780)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/cmd/pulumi.go:116 +0x1da
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc0004b9680, 0x3217d90, 0x0, 0x0, 0xc00052dd60, 0x1162024)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:96 +0x51
github.com/pulumi/pulumi/pkg/util/cmdutil.RunResultFunc.func1(0xc0004b9680, 0x3217d90, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:112 +0x6b
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004b9680, 0x3217d90, 0x0, 0x0, 0xc0004b9680, 0x3217d90)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:746 +0x221
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000119900, 0x224e0c8, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:852 +0x2c0
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/Users/travis/gopath/src/github.com/pulumi/pulumi/main.go:49 +0x4c

goroutine 18 [chan receive]:
github.com/pulumi/pulumi/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x31faf00)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by github.com/pulumi/pulumi/vendor/github.com/golang/glog.init.0
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/golang/glog/glog.go:410 +0x272

goroutine 34 [syscall]:
os/signal.signal_recv(0x0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/os/signal/signal_unix.go:29 +0x41

goroutine 20 [select]:
github.com/pulumi/pulumi/vendor/go.opencensus.io/stats/view.(*worker).start(0xc0001121e0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by github.com/pulumi/pulumi/vendor/go.opencensus.io/stats/view.init.0
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

goroutine 23 [chan receive]:
net/http.(*persistConn).addTLS(0xc0004d4360, 0xc0000c4200, 0xe, 0x0, 0xc0000c420f, 0x3)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/transport.go:1196 +0x1d4
net/http.(*Transport).dialConn(0x31e7020, 0x24bfc60, 0xc000427290, 0x0, 0xc0000f6090, 0x5, 0xc0000c4200, 0x12, 0x0, 0x0, ...)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/transport.go:1269 +0x1cba
net/http.(*Transport).getConn.func4(0x31e7020, 0x24bfc60, 0xc000427290, 0xc0004276b0, 0xc0000d65a0)
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/transport.go:1015 +0xa6
created by net/http.(*Transport).getConn
	/Users/travis/.gimme/versions/go1.12.darwin.amd64/src/net/http/transport.go:1014 +0x455
```
</details>

This panic persists until cached version information is available.

```
$ pulumi version
fatal error: unexpected signal during runtime execution
...
$ pulumi version
fatal error: unexpected signal during runtime execution
...
$ pulumi version
fatal error: unexpected signal during runtime execution
...
$ pulumi version
v1.0.0
$ cat .pulumi/.cachedVersionInfo
{"latestVersion":"1.0.0","oldestWithoutWarning":"1.0.0"}
```

**Comment by zhangyoufu** [comment]
This issue is resolved at https://github.com/golang/go/issues/28092#issuecomment-494501224.
And backported to golang 1.12.6. @pulumi Please upgrade your CI toolchain.
