### ISSUE TITLE
Panic on almost every pulumi operation after upgrading to 1.1.0

### ISSUE THREAD

**Issue by igorshapiro** [pulumi/pulumi#3231]
The following is the error:

```
     pulumi:pulumi:Stack  pubsub-service-pubsub-staging-shared           debug: Setting AWS metadata API timeout to 100ms

panic: fatal: An assertion has failed

goroutine 187 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
        /private/tmp/pulumi-20190913-17277-15zhmar/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assert(...)
        /private/tmp/pulumi-20190913-17277-15zhmar/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/resource/deploy.NewDeleteStep(0xc0010d0f00, 0xc001234d00, 0xc001128850, 0x68)
        /private/tmp/pulumi-20190913-17277-15zhmar/src/github.com/pulumi/pulumi/pkg/resource/deploy/step.go:238 +0x261
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepGenerator).GenerateDeletes(0xc0005e25a0, 0xc0014bfc00, 0x2, 0x0)
        /private/tmp/pulumi-20190913-17277-15zhmar/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_generator.go:551 +0x77d
github.com/pulumi/pulumi/pkg/resource/deploy.(*planExecutor).Execute.func3(0xc0015d98c0, 0xc000239be0, 0xc0006e58f0, 0x24c7aa0, 0xc0010c3f40, 0x24c7aa0, 0xc0010c3f00, 0x10000, 0x1, 0xc000761400)
        /private/tmp/pulumi-20190913-17277-15zhmar/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:155 +0x3d5
github.com/pulumi/pulumi/pkg/resource/deploy.(*planExecutor).Execute(0xc000239be0, 0x24c7aa0, 0xc0010c3f00, 0x24c7ea0, 0xc000af8000, 0x7fffffff, 0x10000, 0x1, 0x0, 0x0)
        /private/tmp/pulumi-20190913-17277-15zhmar/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan_executor.go:192 +0x511
github.com/pulumi/pulumi/pkg/resource/deploy.(*Plan).Execute(...)
        /private/tmp/pulumi-20190913-17277-15zhmar/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan.go:330
github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk.func1(0x24c7ea0, 0xc000af8000, 0xc001568160, 0x24c7aa0, 0xc0010c3f00, 0x20e5401, 0xc0006e58e0, 0xc0015d96e0)
        /private/tmp/pulumi-20190913-17277-15zhmar/src/github.com/pulumi/pulumi/pkg/engine/plan.go:182 +0x13b
created by github.com/pulumi/pulumi/pkg/engine.(*planResult).Walk
        /private/tmp/pulumi-20190913-17277-15zhmar/src/github.com/pulumi/pulumi/pkg/engine/plan.go:173 +0x1
```

**Comment by lukehoban** [comment]
From offline discussions with @igorshapiro, it looks like this resource exists in the checkpoint, which we believe is what is triggering the assertion:

```
   {
                "urn": "urn:pulumi:pubsub-staging-us-east-1-shared::pubsub-service::aws:ec2/securityGroup:SecurityGroup::defaultWorkerNode",
                "custom": true,
                "type": "aws:ec2/securityGroup:SecurityGroup",
                "parent": "urn:pulumi:pubsub-staging-us-east-1-shared::pubsub-service::pulumi:pulumi:Stack::pubsub-service-pubsub-staging-us-east-1-shared",
                "external": true,
                "provider": "urn:pulumi:pubsub-staging-us-east-1-shared::pubsub-service::pulumi:providers:aws::default_0_18_27::f080e605-2455-4b40-b27e-2c9208521928",
                "customTimeouts": {
                    "Create": 0,
                    "Update": 0,
                    "Delete": 0
                }
            },
```

**Comment by pgavlin** [comment]
Looking into this. The assertion that is firing is intended to validate that all non-component resources have a non-empty ID, as we treat an empty ID as indicating that a physical resource does not exist.

**Comment by pgavlin** [comment]
@igorshapiro can you share any additional details about your stack and Pulumi program? It looks like this resource is being read by a `.get`--is that the case?

**Comment by lukehoban** [comment]
@igorshapiro noted in Community Slack:

---
Seems I found the issue. It was:

```ts
    const nodeSecurityGroup = aws.ec2.SecurityGroup.get(
      'defaultWorkerNode',
      someStackReference.outputs.workerSecurityGroupId
    )
```

The stack outputs didn’t have workerSecurityGroupId set.

I think there should be an easier way to debug these. Panic and crash seems like inadequate here

**Comment by lukehoban** [comment]
> Panic and crash seems like inadequate here

Definitely a bug that it is possible to hit these asserts.  This should fail much earlier.  

Also, these asserts (and honestly all others), should include more info to make any future debugging related to these invariants easier.

**Comment by pgavlin** [comment]
We made the following change in August that was intended to fail read steps that return missing resources: https://github.com/pulumi/pulumi/pull/3123

Notably, it does not ensure that the ID is non-empty. I'll have to look at the specific results we get from the provider when a security group is missing.
