### ISSUE TITLE
Pulumi not able to connect to Kubernetes cluster

### ISSUE THREAD

**Issue by pasmon** [pulumi/pulumi#3274]
Pulumi is not able to connect to a bare-metal Kubernetes cluster, kubectl, helm, k9s and ktail all work just fine.
Check attached file for traceback.

[pulumi_kubernetes_connect_issue_traceback.txt](https://github.com/pulumi/pulumi/files/3662276/pulumi_kubernetes_connect_issue_traceback.txt)

Company uses a proxy, but this proxy should not be used for internal communications - after I "unset http_proxy" and "unset https_proxy" Pulumi worked. Pulumi should work without these tricks just like kubectl does?

Pulumi version: 1.2.0

**Comment by pgavlin** [comment]
It looks like this is a failure to communicate between the Pulumi CLI and the plugins it launches to manage resources rather than a failure to talk to the k8s server. I know we've had problems with proxies in the past... It sounds like yours are configured using the `http_proxy` and `https_proxy` envvars--is that right?

**Comment by pasmon** [comment]
I guess so, since I have HTTP_PROXY, HTTPS_PROXY, FTP_PROXY and NO_PROXY (and their lowercase variants) set and unsetting the http* ones got Pulumi connection working.

**Comment by pgavlin** [comment]
What do your `NO_PROXY` envvars look like? We've seen issues with the gRPC library failing to parse `NO_PROXY` if it contains whitespace: https://github.com/pulumi/pulumi/issues/2651

**Comment by aureq** [comment]
Hi @pgavlin,

So I *have been* experiencing the same issue, but I've made progress. Here is some extra information that might help other people.

Below is the error I'm experiencing. It's in clear text to allow search engines to index the content.

1 - Error message.
```python
Previewing update (<redacted>)

View Live: https://app.pulumi.com/aureq/<redacted>

     Type                 Name                        Plan     Info
     pulumi:pulumi:Stack  <redacted>           1 error; 66 messages
 
Diagnostics:
  pulumi:pulumi:Stack (<redacted>):
    Traceback (most recent call last):
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 35, in run_pulumi_func
        func()
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 100, in __init__
        super(Stack, self).__init__('pulumi:pulumi:Stack', name, None, None)
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/resource.py", line 870, in __init__
        Resource.__init__(self, t, name, False, props, opts, remote, False)
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/resource.py", line 742, in __init__
        register_resource(self, t, name, custom, remote, DependencyResource, props, opts)
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 351, in register_resource
        log.debug(f"registering resource: ty={ty}, name={name}, custom={custom}, remote={remote}")
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/log.py", line 40, in debug
        _log(engine, engine_pb2.DEBUG, msg, resource, stream_id, ephemeral)
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/log.py", line 113, in _log
        engine.Log(req)
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/grpc/_channel.py", line 923, in __call__
        return _end_unary_response_blocking(state, call, False, None)
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
        raise _InactiveRpcError(state)
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1607142679.847280280","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1607142679.847277234","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
    >
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/root/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 37, in run_pulumi_func
        log.debug("Waiting for outstanding RPCs to complete")
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/log.py", line 40, in debug
        _log(engine, engine_pb2.DEBUG, msg, resource, stream_id, ephemeral)
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/log.py", line 113, in _log
        engine.Log(req)
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/grpc/_channel.py", line 923, in __call__
        return _end_unary_response_blocking(state, call, False, None)
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
        raise _InactiveRpcError(state)
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1607142679.847601847","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1607142679.847277234","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
    >
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/root/.pulumi/bin/pulumi-language-python-exec", line 90, in <module>
        pulumi.log.error("Program failed with an unhandled exception:")
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/log.py", line 88, in error
        _log(engine, engine_pb2.ERROR, msg, resource, stream_id, ephemeral)
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/pulumi/log.py", line 113, in _log
        engine.Log(req)
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/grpc/_channel.py", line 923, in __call__
        return _end_unary_response_blocking(state, call, False, None)
      File "/root/work/pulumi/quickstart/venv/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
        raise _InactiveRpcError(state)
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1607142679.847832155","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1607142679.847277234","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
    >
 
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

2 - Environment

I run a develoment environment in k8s (k3s specifically) and have a HTTP/HTTPS proxy to access the internet.
I'm running Python 3.8.5 and the pulumi CLI is v2.15.1.

3a - Diagnosis

I looked into my proxy (squid-cache) and noticed the CLI had no issues connecting to `api.pulumi.com` but it complained about accessing `127.0.0.1`.

```
2020-12-05 15:31:20	3366 192.168.2.203 TCP_TUNNEL/200 8300 CONNECT api.pulumi.com:443 - HIER_DIRECT/52.41.162.80 -
2020-12-05 15:31:19	0 192.168.2.203 NONE/000 0 NONE error:transaction-end-before-headers - HIER_NONE/- -
2020-12-05 15:31:19 1 192.168.2.203 NONE/503 0 NONE 127.0.0.1:33481 - HIER_NONE/- -
2020-12-05 15:31:19	0 192.168.2.203 NONE/200 0 CONNECT 127.0.0.1:33481 - HIER_NONE/- -
```

I had to update the `no_proxy` (`NO_PROXY` seems to be ignored).
 
```bash
export no_proxy="127.0.0.1,localhost,localhost.localdomain,*.cluster.local,*.svc"
```
 
I'm guessing the code opens a back channel to allow the server side service to connect to the local CI (via gRPC and the so called subchannels).
 
 
3b - Diagnosis
 
Running `pulumi up` progressed further this time.
 
```
Previewing update (<redacted>)

View Live: https://app.pulumi.com/aureq/<redacted>

     Type                 Name                        Plan       Info
 +   pulumi:pulumi:Stack  quickstart-<redacted>  create     
     └─ aws:s3:Bucket     my-bucket                              1 error
 
Diagnostics:
  aws:s3:Bucket (my-bucket):
    error: 1 error occurred:
        * error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
    
    Please see https://registry.terraform.io/providers/hashicorp/aws
    for more information about providing credentials.
    
    Error: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```        

Again looking at the proxy logs, I noticed my local dev environment tried to access (through the proxy) an EC2 metadata server (aka 169.254.169.254).

```
2020-12-05 15:45:18	996 192.168.2.203 TCP_MISS_ABORTED/000 0 GET http://169.254.169.254/latest/meta-data/iam/security-credentials/ - HIER_DIRECT/169.254.169.254 -
```

I guess I could have avoided this error by setting my AWS credentials correctly in the first place. I'm reporting for completeness.


4 - Solution

After setting my AWS credentials correctly and setting `no_proxy` correctly everything seems to be fine.

```bash
export no_proxy="169.254.169.254,127.0.0.1,localhost,localhost.localdomain,*.cluster.local,*.svc"
```

Maybe something worth adding to the doc.

Cheers

**Comment by aureq** [comment]
As a side note to my comment above, Man-in-the-Middle proxies are probably not a good idea since it may break the port forward to allow the connection back to the local development environment.

**Comment by lblackstone** [comment]
It looks like this issue was related to user config, and hasn't had any update in quite some time. Closing this out.
