### ISSUE TITLE
`pulumi.secret` seems to cause exception in `resource.ts`

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#3277]
I have this code:

```typescript
const appName = "nginx";
const appLabels = { app: pulumi.secret(appName) };
const nginx = new k8s.apps.v1beta1.Deployment(appName, {
    spec: {
        selector: { matchLabels: appLabels },
        replicas: 1,
        template: {
            metadata: { labels: appLabels },
            spec: { containers: [{ name: appName, image: "nginx:1.15-alpine" }] },
        },
    },
});
```

Running `pulumi up` results in the following:

```
    error: Running program '/Users/alex/src/pulumi/examples/kubernetes-ts-exposed-deployment' failed with an unhandled exception:
    Error: Unexpected struct type.
        at Function.proto.google.protobuf.Value.fromJavaScript (/Users/alex/src/pulumi/examples/kubernetes-ts-exposed-deployment/node_modules/google-protobuf/google/protobuf/struct_pb.js:846:13)
        at Function.proto.google.protobuf.Struct.fromJavaScript (/Users/alex/src/pulumi/examples/kubernetes-ts-exposed-deployment/node_modules/google-protobuf/google/protobuf/struct_pb.js:912:51)
        at Function.proto.google.protobuf.Value.fromJavaScript (/Users/alex/src/pulumi/examples/kubernetes-ts-exposed-deployment/node_modules/google-protobuf/google/protobuf/struct_pb.js:842:55)
        at Function.proto.google.protobuf.Struct.fromJavaScript (/Users/alex/src/pulumi/examples/kubernetes-ts-exposed-deployment/node_modules/google-protobuf/google/protobuf/struct_pb.js:912:51)
        at Object.<anonymous> (/Users/alex/src/pulumi/examples/kubernetes-ts-exposed-deployment/node_modules/@pulumi/pulumi/runtime/resource.js:409:43)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/alex/src/pulumi/examples/kubernetes-ts-exposed-deployment/node_modules/@pulumi/pulumi/runtime/resource.js:17:58)
```

This code does not seem obviously wrong to me, so I'm guessing this is an issue? I'm not an expert on Pulumi's secrets model.

**Comment by hausdorff** [comment]
This is happening in `registerResourceOutputs`:

```typescript
export function registerResourceOutputs(res: Resource, outputs: Inputs | Promise<Inputs> | Output<Inputs>) {
    // Now run the operation. Note that we explicitly do not serialize output registration with
    // respect to other resource operations, as outputs may depend on properties of other resources
    // that will not resolve until later turns. This would create a circular promise chain that can
    // never resolve.
    const opLabel = `monitor.registerResourceOutputs(...)`;
    runAsyncResourceOp(opLabel, async () => {
        // The registration could very well still be taking place, so we will need to wait for its URN.
        // Additionally, the output properties might have come from other resources, so we must await those too.
        const urn = await res.urn.promise();
        const resolved = await serializeProperties(opLabel, { outputs });
        const outputsObj = gstruct.Struct.fromJavaScript(resolved.outputs);
```

I don't know how this code works, but I can look into it if we need to.

**Comment by lukehoban** [comment]
I cannot repro this.

Are you using recent versions of everything involved?
