### ISSUE TITLE
Unit testing support not working during preview

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#3429]
The unit testing support described in https://www.pulumi.com/blog/unit-testing-infrastructure-in-nodejs-and-mocha/ no longer works. 

Note: the tests do run successfully during the `update` but fail during the `preview`. The tests can be skipped during the `preview` by checking `pulumi.runtime.isDryRun()`.

#### Code
```ts
import * as eks from "@pulumi/eks";
import { runTests } from "./tests";

// Create a basic EKS cluster.
export const cluster = new eks.Cluster("my-cluster", {
    desiredCapacity: 2,
    minSize: 1,
    maxSize: 2,
    storageClasses: "gp2",
    deployDashboard: false,
    version: "1.13",
});

runTests();
```
#### Test Code 
```ts
import * as aws from "@pulumi/aws";
import { expect } from "chai";
import * as pulumi from "@pulumi/pulumi";
import { promise } from "./";
import { cluster } from "../";

describe("#Amazon EKS Cluster", () => {
    it("Should use an approved Kubernetes version", async () => {
        const version = await promise(cluster.eksCluster.version);
        expect(version).to.equal("1.13");
    });
});
```
#### Output
```
% pulumi preview
Previewing update (dev):

     Type                 Name                     Plan       Info
 +   pulumi:pulumi:Stack  pulumi-testing-blog-dev  create...  Running Mocha Tests: 
...
 +      └─ pulumi:providers:kubernetes             my-cluster-provider                           create

Diagnostics:
  pulumi:pulumi:Stack (pulumi-testing-blog-dev):
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

    Running Mocha Tests: /Users/clstokes/cc/pulumi/pulumi-testing-blog/tests/eks.spec.ts
      #Amazon EKS Cluster
        1) Should use an approved Kubernetes version
      0 passing (10s)
      1 failing
      1) #Amazon EKS Cluster
           Should use an approved Kubernetes version:
         AssertionError: expected undefined to equal '1.13'
          at /Users/clstokes/cc/pulumi/pulumi-testing-blog/tests/eks.spec.ts:10:28
          at Generator.next (<anonymous>)
          at fulfilled (tests/eks.spec.ts:5:58)

Permalink: https://app.pulumi.com/clstokes/pulumi-testing-blog/dev/previews/596ea4d2-af2a-4a79-8451-f8a3a5e20f33
```

#### Versions
```
% npm ls | grep 'pulumi'
aws-typescript@ /Users/clstokes/cc/pulumi/pulumi-testing-blog
├─┬ @pulumi/aws@1.7.0
│ ├── @pulumi/pulumi@1.4.0 deduped
├─┬ @pulumi/awsx@0.18.12
│ ├── @pulumi/aws@1.7.0 deduped
│ ├─┬ @pulumi/docker@0.17.4
│ │ ├── @pulumi/pulumi@1.4.0 deduped
│ ├── @pulumi/pulumi@1.4.0 deduped
├─┬ @pulumi/eks@0.18.14
│ ├── @pulumi/aws@1.7.0 deduped
│ ├─┬ @pulumi/kubernetes@1.2.3
│ │ ├── @pulumi/pulumi@1.4.0 deduped
│ ├── @pulumi/pulumi@1.4.0 deduped
├─┬ @pulumi/pulumi@1.4.0
│ ├── @pulumi/query@0.3.0
% pulumi version
v1.4.0
```

**Comment by mikhailshilkov** [comment]
Closing this one as we changed our unit testing approach
