### ISSUE TITLE
Panic during pulumi logs

### ISSUE THREAD

**Issue by ekrengel** [pulumi/pulumi#3432]
I was trying to run `pulumi logs` and the CLI paniced. 

```
Collecting logs for stack erin-dev since 2019-10-31T15:20:24.000-07:00.

panic: fatal: An assertion has failed: Module member token 'platypull:slacklambdas' missing module member delimiter

goroutine 85 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
	/private/tmp/pulumi-20191024-22371-1uz83xt/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc000fb9500, 0x22f4964, 0x38, 0xc0005acc30, 0x1, 0x1)
	/private/tmp/pulumi-20191024-22371-1uz83xt/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x198
github.com/pulumi/pulumi/pkg/tokens.ModuleMember.Module(0xc000fb9540, 0x16, 0x0, 0x18)
	/private/tmp/pulumi-20191024-22371-1uz83xt/src/github.com/pulumi/pulumi/pkg/tokens/tokens.go:192 +0xd7
github.com/pulumi/pulumi/pkg/tokens.ModuleMember.Package(0xc000fb9540, 0x16, 0x22ab68f, 0x1)
	/private/tmp/pulumi-20191024-22371-1uz83xt/src/github.com/pulumi/pulumi/pkg/tokens/tokens.go:187 +0x35
github.com/pulumi/pulumi/pkg/tokens.Type.Package(0xc000fb9540, 0x16, 0xc0010e64f8, 0x100e398)
	/private/tmp/pulumi-20191024-22371-1uz83xt/src/github.com/pulumi/pulumi/pkg/tokens/tokens.go:227 +0x83
github.com/pulumi/pulumi/pkg/operations.(*resourceOperations).getOperationsProvider(0xc000e33550, 0x0, 0x1, 0x0, 0x0)
	/private/tmp/pulumi-20191024-22371-1uz83xt/src/github.com/pulumi/pulumi/pkg/operations/resources.go:252 +0x63
github.com/pulumi/pulumi/pkg/operations.(*resourceOperations).GetLogs(0xc000e33550, 0xc000e64b00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20191024-22371-1uz83xt/src/github.com/pulumi/pulumi/pkg/operations/resources.go:147 +0xb50
github.com/pulumi/pulumi/pkg/operations.(*resourceOperations).GetLogs.func1(0xc000e33550, 0xc0009c7960, 0xc000e22a20, 0xc000e22a80)
	/private/tmp/pulumi-20191024-22371-1uz83xt/src/github.com/pulumi/pulumi/pkg/operations/resources.go:175 +0x5f
created by github.com/pulumi/pulumi/pkg/operations.(*resourceOperations).GetLogs
	/private/tmp/pulumi-20191024-22371-1uz83xt/src/github.com/pulumi/pulumi/pkg/operations/resources.go:174 +0x1b8
```

**Comment by lukehoban** [comment]
Related (or possibly ultimately the same): https://github.com/pulumi/pulumi/issues/1820
