### ISSUE TITLE
Panic when two resources exist with the same name

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi#3445]
```
❯ pulumi up -s LinioIT/development --yes --skip-preview
Updating (LinioIT/development):

     Type                         Name                 Status       Info
     pulumi:pulumi:Stack          blobber-development  running..    read pulumi:pulumi:StackReference LinioIT/vpc/development
 +   └─ gcp:sql:DatabaseInstance  blobber              creating...
panic: fatal: An assertion has failed: Two resources ('urn:pulumi:development::blobber::gcp:sql/databaseInstance:DatabaseInstance::blobber' and 'urn:pulumi:development::blobber::gcp:sql/databaseInstance:DatabaseInstance::bookmarks') aliased to the same: 'urn:pulumi:development::blobber::gcp:sql/databaseInstance:DatabaseInstance::blobber'

goroutine 41 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
	/private/tmp/pulumi-20191102-90695-7ouf4f/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc000f6ea00, 0x2304110, 0x37, 0xc000d6fce0, 0x3, 0x3)
	/private/tmp/pulumi-20191102-90695-7ouf4f/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x198
github.com/pulumi/pulumi/pkg/resource/deploy.(*Snapshot).NormalizeURNReferences(0xc0003ea7e0)
	/private/tmp/pulumi-20191102-90695-7ouf4f/src/github.com/pulumi/pulumi/pkg/resource/deploy/snapshot.go:112 +0x6cb
github.com/pulumi/pulumi/pkg/backend.(*SnapshotManager).saveSnapshot(0xc0006d6b00, 0xc000d6ff30, 0x2)
	/private/tmp/pulumi-20191102-90695-7ouf4f/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:565 +0x42
github.com/pulumi/pulumi/pkg/backend.NewSnapshotManager.func1(0xc000f6f020, 0xc0006d6b00, 0xc000f6f080, 0xc000f6f0e0)
	/private/tmp/pulumi-20191102-90695-7ouf4f/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:608 +0x12e
created by github.com/pulumi/pulumi/pkg/backend.NewSnapshotManager
	/private/tmp/pulumi-20191102-90695-7ouf4f/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:597 +0x150
```

This happened by an unusual circumstance, but it still shouldn't panic.

**Comment by pgavlin** [comment]
Thanks for the report--agree that this definitely should not panic.
