### ISSUE TITLE
Node tests hanging and timing out in Node v12.13.0

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#3484]
```sh
rpc run test: provider_invokes (pwd=undefined,prog=/usr/local/src/pulumi/sdk/nodejs/bin/tests/runtime/langhost/cases/060.provider_invokes):
Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)

rpc run test: provider_in_parent_invokes (pwd=undefined,prog=/usr/local/src/pulumi/sdk/nodejs/bin/tests/runtime/langhost/cases/061.provider_in_parent_invokes):
Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)
```

I ran into this during setup and currently have these tests commented out. Has also been encountered in https://github.com/pulumi/pulumi/issues/3464#issuecomment-552058982. I believe @CyrusNajmabadi  has more context on the root cause here.

**Comment by pgavlin** [comment]
@CyrusNajmabadi is it simply the case that these tests are hanging due to deasync?
