### ISSUE TITLE
Importing using custom NodeJS providers fails

### ISSUE THREAD

**Issue by hermanbanken** [pulumi/pulumi#3550]
# `pulumi.dynamic.Resource` with `import` CustomResourceOption

![import](https://gist.githubusercontent.com/hermanbanken/708b9b2f8c013d50ca4afd319cd05487/raw/41f8193299bea3d74930a9a67fdccd216b071007/failure.png)

I'm not 100% sure that this is expected to work, but since the pulumi/kubernetes provider is giving us issues I wanted to write a custom provider that just runs `kubectl apply` with the given specs. I wanted to add an `import` statement in order to load the current state of the resource using `kubectl get` and noticed that if I add `import` as a CustomResourceOption the `pulumi up` task fails.

To investigate I created a minimal sample project that just uses a fake FileResource.

Sample project: https://gist.github.com/hermanbanken/708b9b2f8c013d50ca4afd319cd05487

---

```bash
-> % pulumi up
Previewing update (test):

     Type                               Name            Plan       Info
     pulumi:pulumi:Stack                file-test-test             1 error; 10 messages
 =   └─ pulumi-nodejs:dynamic:Resource  existing.txt    import     1 error

Diagnostics:
  pulumi:pulumi:Stack (file-test-test):
    error: preview failed

    Error: code must be a string, not undefined: Error: code must be a string, not undefined
        at requireFromString (/pulumi-custom-provider-test/node_modules/require-from-string/index.js:19:9)
        at getProvider (/pulumi-custom-provider-test/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:39:12)
        at Object.<anonymous> (/pulumi-custom-provider-test/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:188:30)
        at Generator.next (<anonymous>)
        at /pulumi-custom-provider-test/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/pulumi-custom-provider-test/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:17:12)
        at Object.readRPC [as read] (/pulumi-custom-provider-test/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:182:12)
        at /pulumi-custom-provider-test/node_modules/grpc/src/server.js:590:13

  pulumi-nodejs:dynamic:Resource (existing.txt):
    error: Preview failed: code must be a string, not undefined

```

**Comment by pgavlin** [comment]
import is not supportable using the current implementation of dynamic providers. We have plans to change the implementation such that this scenario is supportable--I can't find an existing issue, so we'll use this issue to track.

**Comment by hermanbanken** [comment]
Ok. Thanks for the answer. Would have been nice if that would have been mentioned as an error by itself, but I get that it didn't because there are plans to replace them.

**Comment by Lepozepo** [comment]
+1! Support for `import` in dynamic providers would be great

**Comment by project0** [comment]
I just felt into the same trap, it would be nice to have at least a proper error message instead of obscure exceptions
