### ISSUE TITLE
Preview with --policy-pack arg is broken in 1.6.0

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#3564]
When running an up or preview with `--policy-pack=<path>` Pulumi fails with a `no such file or directory` error. This was working correctly (AFAIK) in versions prior to 1.6.0.

Note in the error below the path is not correct. It seems that the provided `<path>` argument is getting appended twice.

#### Error
```
aws-ts-webserver % pulumi preview --policy-pack=policies
Previewing update (demo):

     Type                 Name                        Plan     Info
     pulumi:pulumi:Stack  demo-aws-ts-webserver-demo           1 error; 13 messages

Diagnostics:
  pulumi:pulumi:Stack (demo-aws-ts-webserver-demo):
    We failed to locate the entry point for your program: /Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/policies/policies
    error: [runtime] Running program '/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/policies/policies' failed with an unhandled exception:
        Error: ENOENT: no such file or directory, lstat '/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/policies/policies'
        at Object.lstatSync (fs.js:845:3)
        at throwOrPrintModuleLoadError (/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/node_modules/@pulumi/pulumi/cmd/run-policy-pack/run.js:70:21)
        at reportModuleLoadFailure (/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/node_modules/@pulumi/pulumi/cmd/run-policy-pack/run.js:38:5)
        at runProgram (/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/node_modules/@pulumi/pulumi/cmd/run-policy-pack/run.js:214:17)
        at Object.run (/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/node_modules/@pulumi/pulumi/cmd/run-policy-pack/run.js:221:85)
        at v8Hooks.isInitializedAsync.then (/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/node_modules/@pulumi/pulumi/cmd/run-policy-pack/index.js:95:42)
        at process._tickCallback (internal/process/next_tick.js:68:7)
        at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
        at startup (internal/bootstrap/node.js:283:19)
        at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

    error: policy pack "/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/policies" failed to start: could not read plugin [/usr/local/bin/pulumi-analyzer-policy] stdout: EOF

Permalink: https://app.pulumi.com/clstokes/demo-aws-ts-webserver/demo/previews/e652049e-5e2b-4209-984d-b250bfa0bf8d
aws-ts-webserver %
```

**Comment by justinvp** [comment]
@clstokes, could you provide the `package.json` for both the Pulumi program and Policy Pack, along with the lock files?

**Comment by clstokes** [comment]
@justinvp https://gist.github.com/clstokes/ac5837ff5b0e9511943c0e2f699c60cd

**Comment by clstokes** [comment]
Confirmed that downgrading to v1.5.2 works.

**Comment by justinvp** [comment]
I've reproduced the issue and know what the problem is (and why our tests didn't catch it).

In the meantime, with v1.6.0, you can workaround by specifying a full path to the policy pack, e.g.:

```
pulumi preview --policy-pack=/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/policies
```

Our tests didn't catch it, because we always pass a full rooted path to `--policy-pack`. Along with the fix, I'll add a regression test that also passes a relative path to `--policy-pack`.
