### ISSUE TITLE
Python: Can't catch exceptions from invokes ("data sources")

### ISSUE THREAD

**Issue by geekofalltrades** [pulumi/pulumi#3611]
This looks like #2908 again, but that issue is closed, so I'm opening a new one.

I'm using pulumi 1.6.0 with pulumi-aws version 1.11.0.

I'm trying to use `get_volume` for disaster recovery to see if a previously dynamically-allocated volume exists so I can reattach it. Here's some sample code:

```python
try:
    backups_volume = ebs.get_volume(
        filters=[
            {
                "Name": "tag:KubernetesCluster",
                "Values": [config.require("cluster.name")],
            },
            {
                "Name": "tag:kubernetes.io/created-for/pvc/namespace",
                "Values": [base_namespace.metadata["name"]],
            },
            {
                "Name": "tag:kubernetes.io/created-for/pvc/name",
                "Values": ["backups"],
            },
        ]
    )
except:
    pass
```

This is resulting in this:

```
Diagnostics:
  pulumi:pulumi:Stack (mine):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/me/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/home/me/projects/pulumi/pulumi-project/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 72, in run_in_stack
        raise RPC_MANAGER.unhandled_exception.with_traceback(RPC_MANAGER.exception_traceback)
      File "/home/me/projects/pulumi/pulumi-project/venv/lib/python3.6/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc_function(*args, **kwargs)
      File "/home/me/projects/pulumi/pulumi-project/venv/lib/python3.6/site-packages/pulumi/runtime/invoke.py", line 157, in do_invoke
        resp = await asyncio.get_event_loop().run_in_executor(None, do_invoke)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/me/projects/pulumi/pulumi-project/venv/lib/python3.6/site-packages/pulumi/runtime/invoke.py", line 155, in do_invoke
        raise Exception(details)
    Exception: invocation of aws:ebs/getVolume:getVolume returned an error: invoking aws:ebs/getVolume:getVolume: Your query returned no results. Please change your search criteria and try again.
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

My try/except failed to catch this exception.

#2908 claims to have fixed this in August, but maybe not for all resource types?

Also looks similar to #3364 .

**Comment by pgavlin** [comment]
Interesting. I wonder if this is a bad interaction with the code we use to allow these functions to be called synchronously. Thanks for the report!

**Comment by clstokes** [comment]
Related - https://github.com/pulumi/pulumi/issues/3364.

**Comment by joeduffy** [comment]
@lukehoban @justinvp This seemed like a fairly simple thing to fix, so I gave it a go. Did I miss something fundamental about why this one's so difficult? It seems to work -- but I may have busted things in the process? https://github.com/pulumi/pulumi/commit/b114a763fa43660fbd2e37d493fda5e4c16c6480

**Comment by justinvp** [comment]
> This seemed like a fairly simple thing to fix, so I gave it a go.

I haven't had a chance to look closely yet, but looks promising! Will review in more detail soon.
