### ISSUE TITLE
`pulumi up` led to broken state

### ISSUE THREAD

**Issue by samscott89** [pulumi/pulumi#3626]
We were having successful deploys through CI/CD, when we simultaneously (a) made a broken change and (b) added `--skip-preview` to the CI `pulumi up` step.

After the CI failed with:

```
error: Running program '/github/workspace/pulumi/infra' failed with an unhandled exception:
TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.getImageNameAndTag (/github/workspace/pulumi/infra/node_modules/@pulumi/utils.ts:25:37)
    at /github/workspace/pulumi/infra/node_modules/@pulumi/docker.ts:188:43
    at Generator.next (<anonymous>)
    at /github/workspace/pulumi/infra/node_modules/@pulumi/docker/docker.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/github/workspace/pulumi/infra/node_modules/@pulumi/docker/docker.js:17:12)
    at buildAndPushImageWorkerAsync (/github/workspace/pulumi/infra/node_modules/@pulumi/docker/docker.js:100:12)
    at Object.<anonymous> (/github/workspace/pulumi/infra/node_modules/@pulumi/docker.ts:165:34)
    at Generator.next (<anonymous>)
    at /github/workspace/pulumi/infra/node_modules/@pulumi/docker/docker.js:21:71
```

We then ended up with a broken state. In particular, it had created a new ECR repository resource in the state file, without actually creating one, so it didnt have an ID.

Due to this, every pulumi operation on the state would then throw an assertion error, since the `id` was missing.

We manually fixed this by locating the resource without an ID that wasnt (a) an awsx resource, or alias of one, and (b) wasnt a customer resource. This left just the one option which we manually deleted using export/import and everything seems okay.

**Comment by samscott89** [comment]
In addition, this is somewhat reproducible, in that running the same CI again after applying the mitigations led to the broken outcome again.

**Comment by samscott89** [comment]
Final note: removing the `--skip-preview` gets it working again somehow.

**Comment by leezen** [comment]
Are you still seeing this and if so, could you please provide a repro?

**Comment by leezen** [comment]
Closing due to inactivity. If you have additional details to add, I'll be happy to re-open.
