### ISSUE TITLE
Crash in runtime/resource.ts when creating resources inside `apply` 

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3645]
The following example leads to an exception in core Pulumi:

```
  pulumi:pulumi:Stack (cert-demo-cert-demo):
    TypeError: Cannot read property 'concat' of undefined
        at C:\Users\Justin\Source\cert-demo\node_modules\@pulumi\pulumi\runtime\resource.js:356:29
        at Generator.next (<anonymous>)
        at fulfilled (C:\Users\Justin\Source\cert-demo\node_modules\@pulumi\pulumi\runtime\resource.js:18:58)
```

When setting `SHOW_BUG` to true the issue repros:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
const SHOW_BUG = true
const apex = process.env.APEX_DOMAIN || "example.com"
const cert = new aws.acm.Certificate("cert", {
  domainName: `v.${apex}`,
  subjectAlternativeNames: [`vv.${apex}`, `vvv.${apex}`],
  validationMethod: "DNS",
});
const zone = aws.route53.getZone({
  name: apex,
  privateZone: false,
});
if(SHOW_BUG) {
  const domains = cert.domainValidationOptions.apply((opts) => 
    opts.map((opt) => 
      new aws.route53.Record(opt.resourceRecordName, {
        name: opt.resourceRecordName,
        records: [opt.resourceRecordValue],
        ttl: 60,
        type: opt.resourceRecordType,
        zoneId: zone.id,
      }, { dependsOn: cert })
    )
  )
  new aws.acm.CertificateValidation(`cert-${apex}`, { 
    certificateArn: cert.arn,
    validationRecordFqdns: domains.apply((doms) => doms.map((dom) => dom.fqdn))
  }, { dependsOn: domains })
}
else {
  let domains: Array<aws.route53.Record> = []
  for(let i = 0; i < 3; i++) {
    domains.push(new aws.route53.Record(`val-${i}`, {
      name: cert.domainValidationOptions[i].resourceRecordName,
      records: [cert.domainValidationOptions[i].resourceRecordValue],
      ttl: 60,
      type: cert.domainValidationOptions[i].resourceRecordType,
      zoneId: zone.id,
    }, { dependsOn: cert }))
  }
  new aws.acm.CertificateValidation(`cert-${apex}`, { 
    certificateArn: cert.arn,
    validationRecordFqdns: domains.map((dom) => dom.fqdn)
  }, { dependsOn: domains })
}
```

The code where this is thrown looks like it should not be possible to have `undefined` be the result of `dos.promise()`, so seems like there is some bug here:
https://github.com/pulumi/pulumi/blame/83a2fc2442428db52a16ce78d305372ae5d9e5db/sdk/nodejs/runtime/resource.ts#L449-L453

**Comment by Fryuni** [comment]
Use case that got me here:
```typescript
{
        parent: project,
        dependsOn: [
            managementCredentials,
            managementIAM,
            projectService(project.projectId, 'cloudresourcemanager.googleapis.com'),
        ],
}
```

The function `projectService` creates a singleton for the pair projectId and service allowing to define which APIs needs to be enabled at every resource without creating multiple `Service` resources or defining a `enabledServices` file.
