### ISSUE TITLE
Panic when importing a stack 

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi#3654]
Version: pulumi 1.6.1

Today, I tried to move from a **pulumi backend "A"** to a **pulumi backend "B"** with `pulumi stack export` and `pulumi stack import` (see below for detailed process):
```bash
pulumi login "A"
pulumi stack export
pulumi logout
pulumi login "B"
pulumi stack init
pulumi stack import
```

During this operation, I don't rename neither the stack nor the project.

When I tried to import to **pulumi backend "B"**, I got this error ❌: 

> error: could not deserialize deployment: decrypting secret value: [404] Not Found: Stack 'dev' not found

I didn't understand why, and tried with a newly created stack with a single resource and it works well.

So I tried to **login to a local file** to retry the import and got this error ❌: 
> error: could not deserialize deployment: constructing secrets manager of type "service": could not find access token for https://api.pulumi.com, have you logged in?

This seems due to state `secrets_providers` :
```json
"secrets_providers": {
            "type": "service",
            "state": {
                "url": "https://api.pulumi.com",
                "owner": "XXX",
                "project": "XXX",
                "stack": "dev"
            }
        },
```

I removed the `secrets_providers` from state and got the **PANIC** ❌: 
(I verify with the newly created stack, and without the `secrets_providers` I was able to import the state)

Detail of panic:
```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v1.6.1
Go Version:       go1.13.4
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            attempt to decrypt value

goroutine 1 [running]:
runtime/debug.Stack(0xc0004c6758, 0x4fd8520, 0x555e1a0)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/main.go:30 +0x6e
panic(0x4fd8520, 0x555e1a0)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
github.com/pulumi/pulumi/pkg/resource/config.panicCrypter.DecryptValue(...)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/pkg/resource/config/crypt.go:123
github.com/pulumi/pulumi/pkg/resource/stack.DeserializePropertyValue(0x50525e0, 0xc000433320, 0xae04770, 0x612a008, 0xc00052fb88, 0xc0005387f0, 0x0, 0x0)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:490 +0x40d
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeProperties(0xc0004332f0, 0xae04770, 0x612a008, 0xc0004c6cf8, 0x43ea38e, 0xc0003a2dc0)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:428 +0xe6
github.com/pulumi/pulumi/pkg/resource/stack.DeserializePropertyValue(0x50525e0, 0xc0004332f0, 0xae04770, 0x612a008, 0x6e, 0xc0004a5a40, 0x1, 0x0)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:461 +0x25a
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeProperties(0xc0004332c0, 0xae04770, 0x612a008, 0x4fd8520, 0xc000531650, 0x4fbb5e0)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:428 +0xe6
github.com/pulumi/pulumi/pkg/resource/stack.DeserializePropertyValue(0x50525e0, 0xc0004332c0, 0xae04770, 0x612a008, 0xa829800, 0x400, 0xa9fffff, 0xc0004c6e40)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:461 +0x25a
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeProperties(0xc000433290, 0xae04770, 0x612a008, 0xc00030acc0, 0x0, 0x0)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:428 +0xe6
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeResource(0xc0000444b0, 0x49, 0x0, 0x0, 0x0, 0xc000306b40, 0x13, 0x0, 0xc000433290, 0x0, ...)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:405 +0xa5
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeDeploymentV3(0x38e5cdd0, 0xed5846f4f, 0x0, 0xc000046fc0, 0x40, 0xc000453b18, 0x6, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:229 +0x421
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeUntypedDeployment(0xc0003d2dc0, 0x558cf20, 0x6129c60, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:175 +0x186
github.com/pulumi/pulumi/cmd.newStackImportCmd.func1(0xc000182000, 0xc0000cbbc0, 0x0, 0x2, 0x11, 0x11)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/cmd/stack_import.go:78 +0x231
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc000182000, 0xc0000cbbc0, 0x0, 0x2, 0x0, 0x0)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:96 +0x51
github.com/pulumi/pulumi/pkg/util/cmdutil.RunResultFunc.func1(0xc000182000, 0xc0000cbbc0, 0x0, 0x2)
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000182000, 0xc0000cbb20, 0x2, 0x2, 0xc000182000, 0xc0000cbb20)
	/private/tmp/pulumi-20191127-55098-lml7a3/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000df900, 0x0, 0x0, 0x52b7712)
	/private/tmp/pulumi-20191127-55098-lml7a3/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/pulumi-20191127-55098-lml7a3/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/private/tmp/pulumi-20191127-55098-lml7a3/src/github.com/pulumi/pulumi/main.go:49 +0x63
```

Beyond the error, my use case is to move a stack from a backend to another, and I didn't figure out how to do that.

**Comment by boillodmanuel** [comment]
I was able to reproduce it with a very simple stack:

```ts
import * as pulumi from "@pulumi/pulumi";

export const aSecret = pulumi.secret("mySecret")
```

As soon a secret is exported in the state, we have this error.

**Comment by leezen** [comment]
This particular issue is now resolved given the issue described above is an issue with changing secrets providers from one stack to another, which pulumi now supports via `change-secrets-provider`
