### ISSUE TITLE
Panic on `pulumi up`

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi#3685]
I hit this this morning after running `pulumi -C infra up --yes --skip-preview` in a Make target:

```
pulumi -C infra up --yes --skip-preview
Updating (dev):

     Type                    Name                  Status       Info
     pulumi:pulumi:Stack     pulumi-in-action-dev  running...   
 ~   ├─ aws:s3:BucketObject  /pdf/00/00.pdf        updating     [diff: ~source]
 ~   └─ aws:s3:BucketObject  /pdf/01/01.pdf        updating     [diff: ~source]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x43f4f6d]

goroutine 104 [running]:
encoding/json.(*encodeState).marshal.func1(0xc0004a3b48)
        /usr/local/Cellar/go/1.13.4/libexec/src/encoding/json/encode.go:305 +0x9a
panic(0x508c340, 0x60ecd40)
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
encoding/json.(*encodeState).string(0xc00017a2a0, 0x0, 0xe, 0x1)
        /usr/local/Cellar/go/1.13.4/libexec/src/encoding/json/encode.go:895 +0x5d
encoding/json.stringEncoder(0xc00017a2a0, 0x5047ea0, 0xc00079d018, 0x198, 0x100)
        /usr/local/Cellar/go/1.13.4/libexec/src/encoding/json/encode.go:610 +0xd9
encoding/json.structEncoder.encode(0xc000176600, 0x12, 0x21, 0xc000f95110, 0xc00017a2a0, 0x52856a0, 0xc00079d000, 0x199, 0x100)
        /usr/local/Cellar/go/1.13.4/libexec/src/encoding/json/encode.go:664 +0x306
encoding/json.structEncoder.encode(0xc000fbaea0, 0x2, 0x2, 0xc000f951d0, 0xc00017a2a0, 0x51112e0, 0xc00079d000, 0x199, 0x100)
        /usr/local/Cellar/go/1.13.4/libexec/src/encoding/json/encode.go:664 +0x306
encoding/json.arrayEncoder.encode(0xc000f95200, 0xc00017a2a0, 0x4fb43a0, 0xc0003d47c0, 0x197, 0x100)
        /usr/local/Cellar/go/1.13.4/libexec/src/encoding/json/encode.go:791 +0xd6
encoding/json.sliceEncoder.encode(0xc000faeba0, 0xc00017a2a0, 0x4fb43a0, 0xc0003d47c0, 0x197, 0x100)
        /usr/local/Cellar/go/1.13.4/libexec/src/encoding/json/encode.go:765 +0x8f
encoding/json.structEncoder.encode(0xc000fbc6c0, 0x4, 0x4, 0xc000f95230, 0xc00017a2a0, 0x5192540, 0xc0003d4750, 0x199, 0x43f0100)
        /usr/local/Cellar/go/1.13.4/libexec/src/encoding/json/encode.go:664 +0x306
encoding/json.ptrEncoder.encode(0xc0011c3740, 0xc00017a2a0, 0x4f87320, 0xc0003d4750, 0x16, 0x4f80100)
        /usr/local/Cellar/go/1.13.4/libexec/src/encoding/json/encode.go:810 +0xb1
encoding/json.(*encodeState).reflectValue(0xc00017a2a0, 0x4f87320, 0xc0003d4750, 0x16, 0x100)
        /usr/local/Cellar/go/1.13.4/libexec/src/encoding/json/encode.go:337 +0x82
encoding/json.(*encodeState).marshal(0xc00017a2a0, 0x4f87320, 0xc0003d4750, 0xc0004a0100, 0x0, 0x0)
        /usr/local/Cellar/go/1.13.4/libexec/src/encoding/json/encode.go:309 +0x10b
encoding/json.Marshal(0x4f87320, 0xc0003d4750, 0xc000fcca50, 0x4b, 0x0, 0xc000fd2a40, 0x1)
        /usr/local/Cellar/go/1.13.4/libexec/src/encoding/json/encode.go:161 +0x52
github.com/pulumi/pulumi/pkg/backend/httpstate/client.(*Client).PatchUpdateCheckpoint(0xc0005bf940, 0x55b8160, 0xc0000dc008, 0xc000fb61c0, 0x9, 0xc000f5cc80, 0x10, 0xc000fb61c9, 0x3, 0x52b73ca, ...)
        /private/tmp/pulumi-20191216-89384-1t4r2yw/src/github.com/pulumi/pulumi/pkg/backend/httpstate/client/client.go:628 +0x4f
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudSnapshotPersister).Save(0xc000fd0280, 0xc0003d46c0, 0x0, 0xc0004a3ee0)
        /private/tmp/pulumi-20191216-89384-1t4r2yw/src/github.com/pulumi/pulumi/pkg/backend/httpstate/snapshot.go:50 +0x223
github.com/pulumi/pulumi/pkg/backend.(*SnapshotManager).saveSnapshot(0xc000fd0300, 0xc0004a3f30, 0x2)
        /private/tmp/pulumi-20191216-89384-1t4r2yw/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:579 +0x75
github.com/pulumi/pulumi/pkg/backend.NewSnapshotManager.func1(0xc0010ee4e0, 0xc000fd0300, 0xc0010ee540, 0xc0010ee5a0)
        /private/tmp/pulumi-20191216-89384-1t4r2yw/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:621 +0x12e
created by github.com/pulumi/pulumi/pkg/backend.NewSnapshotManager
        /private/tmp/pulumi-20191216-89384-1t4r2yw/src/github.com/pulumi/pulumi/pkg/backend/snapshot.go:610 +0x150
make: *** [deploy] Error 2
```

macOS Mojave 10.14.6

```
pulumi version
v1.7.1
```

**Comment by lukehoban** [comment]
@cnunciato If you downgrade to `1.7.0` (or `1.6.1`) does this work without issue?
