### ISSUE TITLE
Serialization failure exporting an `[OutputType]` class as a stack export in .NET

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3690]
I get this:

 System.InvalidOperationException: Pulumi.Kubernetes.Types.Outputs.Rbac.V1.Subject is not a supported argument type.
        monitor.registerResourceOutputs(...).subjects.id[0]
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Serialization.Serializer.SerializeListAsync(String ctx, IList list)

When trying to return to add the last line (`subjects`) below:
             return new Dictionary<string, object>{
                { "namespacePhase", ns.Status.Apply(status => status.Phase) },
                { "revisionData", revision.Data },
                { "subjects", binding.Subjects },
            };

The type of that property is:

Output<System.Collections.Immutable.ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Rbac.V1.Subject>> RoleBinding.Subjects

It appears that the serialization we do for `registerResourceOutputs` and/or stack exports is not correctly supporting `OutputType` classes.

**Comment by CyrusNajmabadi** [comment]
Need info from Luke what we want the semantics ot be here.  Totally possible to support this.  But there are some open design questions.  First, as Outputs, these are just normal .Net objects.  So it's an open question how we would actually serialize these in RegisterResourceOutput.  Let's look at an example: 

```c#
    [OutputType]
    public sealed class Subject
    {
      public readonly string ApiGroup;
      public readonly string Kind;
      public readonly string Name;
      public readonly string Namespace;

      [OutputConstructor]
      private Subject(
          string @apiGroup,
          string @kind,
          string @name,
          string @namespace)
      {
          this.ApiGroup = @apiGroup;
          this.Kind = @kind;
          this.Name = @name;
          this.Namespace = @namespace;
      }
    }
  }
```

Because it's an OutputType, we know it will just have fields and a constructor.  So we could just walk the fields to produce the result.  That will give us the names `ApiGroup` and whatnot.  

However, tehse are not the same names teh engine gave us.  Specifically, the object originally traveled from the engine to the SDK using names like `"apiGroup"` (which you can see in the constructor).

It should be easy to support either form here.  TBH, it's not clear what is right/expected.  As these are public types with public fields, it makese sense to me to keep the field names.  However, it's also just serializing out an engine value that internally uses different names...

Any feelings here @lukehoban ?

**Comment by lukehoban** [comment]
For the use-case origianlly called out - I think it might be reasonable to treat this as "by design".

However, for registering resource outputs, which may be required as part of https://github.com/pulumi/pulumi/pull/3711 for example (and is already technically possible to want to do with the existing resource model), it does seem we'll need the ability to pass `Output`s of PONOs into `RegisterResourceOutputs` in a relatively sane way.

It may be we can put this off for now, and just reject anything that is not explicitly handled by serialization as inputs to `RegisterResourceOutputs`.  But it feels like we'll have to address this in some form at some point.

**Comment by Rookian** [comment]
It would be nice to use simple POCO classes for `Output`s. Using dictionaries is a bit cumbersome. 
What I would like to have is something like an artificat in form of a POCO class after `pulumi up` run. I could pass this over to a deployment process and deserialize it back into my deployment process reusing the same POCO class. 

What do you think?

**Comment by RehanSaeed** [comment]
From what I've understood, using a class with `[OutputType]` as an `[Output]` from my stack is not supported. Can I also suggest that C# 9 record classes also be supported? I initially had tried and failed to use one of those. Protobuf has full support for them.

The error I got while trying to use `[OutputType]`:

```
System.InvalidOperationException: Ummati.Infrastructure.ContainerAppOutput is not a supported argument type.
        monitor.registerResourceOutputs(...).ContainerApps.id[0]
       at async Task<object> Pulumi.Serialization.Serializer.SerializeAsync(string ctx, object prop, bool keepResources, bool keepOutputValues)
       at async Task<ImmutableArray<object>> Pulumi.Serialization.Serializer.SerializeListAsync(string ctx, IList list, bool keepResources, bool keepOutputValues)
       at async Task<object> Pulumi.Serialization.Serializer.SerializeAsync(string ctx, object prop, bool keepResources, bool keepOutputValues) x 2
       at async Task<RawSerializationResult> Pulumi.Deployment.SerializeFilteredPropertiesRawAsync(string label, IDictionary<string, object> args, Predicate<string> acceptKey, bool keepResources, bool keepOutputValues)
       at async Task<SerializationResult> Pulumi.Deployment.SerializeFilteredPropertiesAsync(string label, IDictionary<string, object> args, Predicate<string> acceptKey, bool keepResources, bool keepOutputValues)
       at async Task<Struct> Pulumi.Deployment.SerializeAllPropertiesAsync(string label, IDictionary<string, object> args, bool keepResources, bool keepOutputValues)
       at async Task Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output<IDictionary<string, object>> outputs)
```

Here is my type:

```cs
[OutputType]
public class ContainerAppOutput
{
    [OutputConstructor]
    public ContainerAppOutput(string location, string fqdn, string url)
    {
        this.Location = location;
        this.Fqdn = fqdn;
        this.Url = url;
    }

    public string Location { get; }
    public string Fqdn { get; }
    public string Url { get; }
}
```

Here is my usage:

```cs
var containerAppOutputs = new List<Output<ContainerAppOutput>>();
foreach (var location in Configuration.Locations)
{
    var containerApp = GetContainerApp();
    var containerAppOutput = containerApp.Configuration
        .Apply(x => x!.Ingress)
        .Apply(x => new ContainerAppOutput(location, x!.Fqdn, $"https://{x!.Fqdn}"));
    containerAppOutputs.Add(containerAppOutput);
}
this.ContainerApps = Output.All(containerAppOutputs);

[Output]
public Output<ImmutableArray<ContainerAppOutput>> ContainerApps { get; private set; }
```
