### ISSUE TITLE
Expected diff to not require deletion or replacement during Update

### ISSUE THREAD

**Issue by RichardWLaub** [pulumi/pulumi#3712]
After updating subnets on managed node in the [pulumi-eks](https://github.com/pulumi/pulumi-eks) package I run into this error:

```
Diagnostics:
  pulumi:pulumi:Stack (aws-arcus-kitchensink-alpha):
    Running Mocha Tests: /Users/richard.laub/Documents/aws-arcus-kitchensink/src/tests/Buckets.spec.ts,/Users/richard.laub/Documents/aws-arcus-kitchensink/src/tests/SvcRoles.spec.ts,/Users/richard.laub/Documents/aws-arcus-kitchensink/src/tests/types.ts
      # BUCKETS
        # Deployment tests
          ✓ Should successfully retrieve correct quantity of buckets
      # ROLE
        ✓ Should successfully retrieve the created roles
      2 passing (120ms)
    error: Running program '/Users/richard.laub/Documents/aws-arcus-kitchensink/src/index.ts' failed with an unhandled exception:
    AssertionError: expected [Function: testFn] to not throw an error but 'Error: Invoke of \'aws:iam/getRole:getRole\' failed: rpc error: code = Unknown desc = invocation of aws:iam/getRole:getRole returned an error: transport is closing ()' was thrown
        at /Users/richard.laub/Documents/aws-arcus-kitchensink/src/tests/SvcRoles.spec.ts:39:40
        at Array.map (<anonymous>)
        at /Users/richard.laub/Documents/aws-arcus-kitchensink/src/tests/SvcRoles.spec.ts:32:42
        at /Users/richard.laub/Documents/aws-arcus-kitchensink/node_modules/@pulumi/pulumi/output.js:220:35
        at Generator.next (<anonymous>)
        at /Users/richard.laub/Documents/aws-arcus-kitchensink/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/richard.laub/Documents/aws-arcus-kitchensink/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/Users/richard.laub/Documents/aws-arcus-kitchensink/node_modules/@pulumi/pulumi/output.js:199:12)
        at /Users/richard.laub/Documents/aws-arcus-kitchensink/node_modules/@pulumi/pulumi/output.js:179:65
    panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update of urn:pulumi:alpha::aws-arcus-kitchensink::arcus:cluster$eks:index:Cluster$aws:eks/nodeGroup:NodeGroup::monitoring
    goroutine 524 [running]:
    github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.6.0/pkg/util/contract/failfast.go:23
    github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc000824d00, 0x623d46d, 0x48, 0xc0009f3668, 0x1, 0x1)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.6.0/pkg/util/contract/assert.go:33 +0x197
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.(*Provider).Update(0xc00057f080, 0x6aa1ea0, 0xc000b31b00, 0xc0001368c0, 0xc00057f080, 0x56d2601, 0xc000c040c0)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.5.2/pkg/tfbridge/provider.go:805 +0x81d
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler.func1(0x6aa1ea0, 0xc000b31b00, 0x5fb4fa0, 0xc0001368c0, 0x5facc60, 0x99dda70, 0x6aa1ea0, 0xc000b31b00)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.6.0/sdk/proto/go/provider.pb.go:1651 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x6aa1ea0, 0xc000b30e40, 0x5fb4fa0, 0xc0001368c0, 0xc000cbc6a0, 0xc000cbc6c0, 0x0, 0x0, 0x6a00300, 0xc000406ba0)
        /home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20171105060200-01f8541d5372/go/otgrpc/server.go:61 +0x36e
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler(0x60548c0, 0xc00057f080, 0x6aa1ea0, 0xc000b30e40, 0xc001164600, 0xc0004cd500, 0x6aa1ea0, 0xc000b30e40, 0xc000c00000, 0x675)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.6.0/sdk/proto/go/provider.pb.go:1653 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000da160, 0x6ac5720, 0xc00057f500, 0xc000134d00, 0xc0007efe00, 0x99af7e0, 0x0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995 +0x460
    google.golang.org/grpc.(*Server).handleStream(0xc0000da160, 0x6ac5720, 0xc00057f500, 0xc000134d00, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275 +0xd97
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004ebee0, 0xc0000da160, 0x6ac5720, 0xc00057f500, 0xc000134d00)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710 +0xbb
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:708 +0xa1
  aws:eks:NodeGroup (monitoring):
    error: transport is closing
  aws:iam:RolePolicy (mb-arcus-app-identity-sandbox-policy):
    error: all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:61561: connect: connection refused"
  aws:eks:NodeGroup (default):
    error: all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:61561: connect: connection refused"
```

I tried multiple `pulumi up`s with both cli version 1.7.1 and 1.8.1.

Seems related to https://github.com/pulumi/pulumi/issues/2914

**Comment by lukehoban** [comment]
@RichardWLaub Do you have any more details that could help with a repro?  I've spent some time looking into this - but can't identify anything I would expect to lead to this.  

The issue in #2914 was fixed, so although the symptom here is similar, it's likely not the same root cause.

If you could run with `pulumi up --logtostderr -v=9 2> out.txt` it might be helpful to see those logs to understand what diff Pulumi thought it needed to make.

Also - does this repro consistently?  Has it always, or did it start with a particular code change?

**Comment by lukehoban** [comment]
Going to close out for now - but @RichardWLaub if you are still seeing this please do let me know so we can get more details to investigate further.
