### ISSUE TITLE
[feat] Deno TypeScript runtime support

### ISSUE THREAD

**Issue by brandonkal** [pulumi/pulumi#3838]
I'm going to throw this one out there because it is a natural fit for configuration code.

Pros:
- No package manager. Let's face it. It's annoying to download a bunch of modules just to "Hello World" a Pulumi Program. For simple things, one will just reach for YAML instead. Because Deno uses standard HTTPS imports you can just run a file and forget about packages.
- You can run via URL. `deno https://example.com/a-pulumi-program.ts` could be the Pulumi equivalent of `kubectl apply -f https://example.com/some-manifest.yaml`
- Easier to lock down (i.e. a Deno program cannot read environment variables by default so config is more hermetic). It is still an option though if the user specifies.
- Simple to support.

To support Deno Pulumi would need to
- Generate TypeScript code that includes the file extension in the imports.
- Ensure TypeScript code doesn't access modules variable and other legacy CJS things.
- Distribute code on a nice HTTP endpoint or let raw.githubusercontent.com perform that function. So an import could be
```ts
import * as pulumi from 'https://pulumi.com/pulumi@1.4.5/mod.ts'
```
- The pulumi CLI would handle installing plugin binaries as there is no postinstall scripts like npm.

**Comment by pgavlin** [comment]
cc @lukehoban

**Comment by gabemeola** [comment]
This would be great, and more easily allow for mixing matching languages (say Java for the server and Typescript for Pulumi infra) without needing to pull in the whole NodeJS ecosystem.  
I think https://github.com/pulumi/pulumi/issues/3901 might solve this a bit better.

**Comment by Graham-Beer** [comment]
Wanted to add my support for Deno as well. Much more light weight that NodeJS and makes use of the new Javascript features under the hood where NodeJS doesn't. Built in support for TypeScript as well is a much added bonus.

**Comment by brandonkal** [comment]
Closing as I no longer use Pulumi

**Comment by leezen** [comment]
Re-opening as the issue is still something the community wants.

**Comment by pecigonzalo** [comment]
I think Deno greatly lowers the barrier to entry for TS as you dont have to bring all the "noise" of the JS/TS ecosystem.

**Comment by nuvanti** [comment]
We are a Deno shop, it'd be great if you could add Deno support.

**Comment by rafaribe** [comment]
What's the current state on this? Any progress?

**Comment by gaui** [comment]
Would love this!

**Comment by algoflows** [comment]
The waited has been so long that the thumbs have gone down from 40 to 7 🥲

**Comment by 06kellyjac** [comment]
The original is at 42 👍

**Comment by ProdigySim** [comment]
Has anyone tried to use this with one of the [deno-friendly CDNs described in their docs](https://deno.land/manual@v1.21.1/node/cdns#esmsh)?

**Comment by pecigonzalo** [comment]
I've tried a while ago, and it did not work for me unfortunately.

**Comment by RobbieMcKinstry** [comment]
I've tried them recently too, and with little success.

**Comment by RobbieMcKinstry** [comment]
I think this is a really interesting issue. In my mind, the use case is pretty compelling. Deno is (arguably) less finicky than Node. I suspect it'd be a lot easier to distribute and manage than the Node runtime. I'm still coming up to speed on the Pulumi execution model; I'm keeping this issue in the back of my head while ramping up.

**Comment by CanRau** [comment]
Love to be able to just add a dependency via a URL instead of needing to go to the terminal install and then go back to what I was doing

Also publishing reusable code is so much nicer, no need for a registry just GitHub or some accessible URL, done 👍

**Comment by denizdogan** [comment]
[Deno 1.25](https://deno.com/blog/v1.25) makes it slightly easier to import modules directly from NPM, but even with that, I'm not sure how one would add a new "runtime" to Pulumi to use Deno instead of Node.js.

**Comment by RobbieMcKinstry** [comment]
Pulumi uses a supervisor process we call "the language host" to boot a gPRC served called "the language runtime". The language host, which is a [program written in Go](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/cmd/pulumi-language-nodejs/main.go) could, in theory, choose between a Deno and a NodeJS runtime. I believe we do this currently with Java, choosing between Maven, Gradle, etc. I believe there's prior art.

**Comment by RobbieMcKinstry** [comment]
Now that Deno supports (in beta) interoperability with NPM packages, I think Deno would be able to use the existing Node packages.
The Deno team is supposedly offering enterprise office hours for collaborators working on ecosystem improvements. If this is ever scheduled, that's probably a good first step before any code is written.

**Comment by pecigonzalo** [comment]
Deno NPM is out of beta. I think one of the core questions I have is how to indicate to `pulumi up` to use the Deno runtime. That way we can try and hook it up.

**Comment by RobbieMcKinstry** [comment]
@pecigonzalo Right now the architecture looks like this:
1. The pulumi engine launches a subprocess for the Language Host (a Go binary), which is responsible for initializing the Node process which actually executes user code. [This is the Language Host](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/cmd/pulumi-language-nodejs/main.go).

2. The Language Host launches the Language Runtime, a Node program that wraps and executes the user code. [This line](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/cmd/pulumi-language-nodejs/main.go#L65) specifies the Node module to launch. You'd need to edit `locateModule`([here](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/cmd/pulumi-language-nodejs/main.go#L145)) and other helper functions which use Node to inform the runtime.

3. Inside the language host, Node is used pretty heavily as well. Here's the link to the [language host](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/cmd/run/index.ts) entrypoint, but most of the logic is in [`run.ts`](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/cmd/run/run.ts). [Here's an example](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/cmd/run/run.ts#L68) of a helper that might need to be tweaked.

One great improvement we could make is to put all uses of Node and NPM behind an interface so we could swap it out with an alternative (like Deno, for instance, or PNP).

**Comment by danielrbradley** [comment]
The biggest piece of work to support this would be reworking the core nodejs SDK. This utilizes various parts of nodejs's internal runtime for aspects like closure serialization. 

The options I can see are:
1. Have separate SDKs for nodejs and deno
   - Create a fork of pulumi/pulumi's nodejs SDK for deno with closure serialization removed
   - Generate a dedicated deno SDK for each provider based on the new pu/pu SDK
2. Refactor closure serialization out from the core pulumi/pulumi nodejs SDK
   - Create a separate package for closure serialization (e.g. `@pulumi/nodejs`)
   - Make the core nodejs SDK a portable JS library (no nodejs dependency)
   - Providers which integrate with closure serialization directly (e.g. aws) moves this functionality into an extension package (e.g. `@pulumi/aws-nodejs`)

**Comment by runlevel5** [comment]
Deno now supports many NPM packages, for example `aws-sdk`, it would help the porting effort I believe.

**Comment by algoflows** [comment]
Is this still planned, what's the current status looking like? We're going deep into Deno now and hope to build a Pulumi provider for the Deno deploy service. We are also starting our startup on Deno and would love to keep a unified Deno TS only codebase with Pulumi written in Deno.

**Comment by guy-borderless** [comment]
> Is this still planned, what's the current status looking like? We're going deep into Deno now and hope to build a Pulumi provider for the Deno deploy service. We are also starting our startup on Deno and would love to keep a unified Deno TS only codebase with Pulumi written in Deno. 

I would also appreciate an update, my ts services are all deno

**Comment by omarcresp** [comment]
bumping this, with the new release of deno 2 would be amazing to have pulumi supporting it

**Comment by butadpj** [comment]
I'm getting issues related to gRPC/node:http2 when using Pulumi's Automation API on Deno's runtime. `stack.preview()` and `stack.up()` works fine on Node.js runtime tho. So, I'm really excited for Pulumi to have Deno's runtime supported

**Comment by Makeshift** [comment]
With the recent release of Deno 2, and the continuing hell of dealing with package managers in Node, I've definitely found myself pining for a non-Nodejs runtime. 

It would be significantly easier for my developers to adopt using my TS-based infrastructure if they didn't have to wrangle with the complexities of node package management.

**Comment by runlevel5** [comment]
I think Pulumi is waiting for more upward trend in Deno adoption before making decision to spend more resources in support it.

**Comment by Kinrany** [comment]
Even if Deno somehow died right this moment, the advantages of describing infrastructure in a typed language with no build step are so great that it should be worth it anyway. This is a fantastic combination, one of the two projects should just buy the other.

**Comment by mrchantey** [comment]
Im confused, Deno 2 [has node compat](https://docs.deno.com/runtime/reference/migration_guide/#:~:text=Deno%202%20is%20backwards%20compatible,all%2Din%2Done%20toolchain.). Is there something pulumi is doing that deno 2 doesnt yet support?

**Comment by runlevel5** [comment]
> Im confused, Deno 2 [has node compat](https://docs.deno.com/runtime/reference/migration_guide/#:~:text=Deno%202%20is%20backwards%20compatible,all%2Din%2Done%20toolchain.). Is there something pulumi is doing that deno 2 doesnt yet support?

I guess it all comes down to how much commitment that pulumi want to invest in supporting Deno and NodeJS at the same time

**Comment by Kinrany** [comment]
What's the minimum viable level of effort here? Something that could be released behind some experimental flag?

**Comment by RobbieMcKinstry** [comment]
@Kinrany I suspect part of the lift is handling closure serialization. If that's elided, then one would need to update the [language host](https://www.pulumi.com/docs/iac/concepts/how-pulumi-works/#language-hosts) and implement the language runtime. That might be all it takes to get core ready. 

But additionally, making sure all of the providers are Deno-compatible might be troublesome. I don't really know what would go into that, but given that Deno is supposedly able to transparently work with NPM modules, it might be a no-op.

**Comment by Kinrany** [comment]
Deno has equivalents of Node APIs for compatibility too. The NPM package `@pulumi/pulumi` is the library that's doing serialization by using Node's v8 APIs, right? So forking it and trying to compile it with Deno and replacing Node stuff with Deno's compat should be a good first step.

**Comment by Kinrany** [comment]
And if the differences are small enough and can be contained in a runtime abstraction, perhaps it'll be possible to keep it all in a single codebase.

**Comment by attrove-wolfe** [comment]
I find myself also desperate for this.

**Comment by fry69** [comment]
This would be great!

Bun as a package manager is a great first step, but Deno would make the TypeScript environment incredibly clean.

Deno is almost a drop-in replacement for Node.js by now. Very few breaking points remain, none of them should matter for Pulumi or provider implementations IMHO.

**Comment by Xylenox** [comment]
Currently trying to use deno with the automation API, seems like https://github.com/denoland/deno/issues/23714 is the biggest blocker right now.

**Comment by julienp** [comment]
I had another look at this, and using GRPC as a client works, we can create a resource from a TypeScript program that's running in Deno. However, GRPC as a server does not work yet. This blocks features like transforms, hooks or component plugins, which run a server from within the SDK.

I believe this work tracked in the upstream Deno issue mentioned above https://github.com/denoland/deno/issues/23714

**Comment by bai-jie** [comment]
Deno 2.7.8 may already fixed the GRPC issue.

**Comment by julienp** [comment]
Edit: oops, I accidentally ran an old version of deno when testing this, and this particular test now works

<s>Still running into issues with grpc-js:</s>
```typescript
import grpc from "npm:@grpc/grpc-js@1.14.3";

const server = new grpc.Server();
server.bindAsync(
  "127.0.0.1:0",
  grpc.ServerCredentials.createInsecure(),
  (err, port) => {
    if (err) {
      console.error("server bind failed:", err.message);
      process.exit(1);
    }

    const client = new grpc.Client(
      `127.0.0.1:${port}`,
      grpc.credentials.createInsecure()
    );
    client.waitForReady(Date.now() + 5000, (err) => {
      if (err) {
        console.error("error:", err.details || err.message);
        process.exit(1);
      }
      console.log("connected to gRPC server");
      client.close();
      server.forceShutdown();
    });
  }
);
```

```
% deno run --allow-all index.ts
>>> Error in Http2Server Error [ERR_HTTP2_SOCKET_UNBOUND]: The socket has been disconnected from the Http2Session
    at Object.get (node:http2:89:19)
    at Http2Server.<anonymous> (file:///Users/julien/Library/Caches/deno/npm/registry.npmjs.org/@grpc/grpc-js/1.14.3/build/src/server.js:1193:148)
    at Http2Server.emit (ext:deno_node/_events.mjs:436:20)
    at Http2Server.<anonymous> (node:http2:1210:14)
    at Http2Server.emit (ext:deno_node/_events.mjs:436:20)
    at TCP._onconnection (node:net:1309:8)
    at TCP.#accept (ext:deno_node/internal_binding/tcp_wrap.ts:363:12)
    at eventLoopTick (ext:core/01_core.js:187:7) {
  code: "ERR_HTTP2_SOCKET_UNBOUND",
  name: "Error"
}

```

**Comment by Kinrany** [comment]
(Not blocked then?)

**Comment by vinayaggarwal-softway** [comment]
Yes

> Edit: oops, I accidentally ran an old version of deno when testing this, and this particular test now works
> 
> Still running into issues with grpc-js:
> 
> import grpc from "npm:@grpc/grpc-js@1.14.3";
> 
> const server = new grpc.Server();
> server.bindAsync(
>   "127.0.0.1:0",
>   grpc.ServerCredentials.createInsecure(),
>   (err, port) => {
>     if (err) {
>       console.error("server bind failed:", err.message);
>       process.exit(1);
>     }
> 
>     const client = new grpc.Client(
>       `127.0.0.1:${port}`,
>       grpc.credentials.createInsecure()
>     );
>     client.waitForReady(Date.now() + 5000, (err) => {
>       if (err) {
>         console.error("error:", err.details || err.message);
>         process.exit(1);
>       }
>       console.log("connected to gRPC server");
>       client.close();
>       server.forceShutdown();
>     });
>   }
> );
> ```
> % deno run --allow-all index.ts
> >>> Error in Http2Server Error [ERR_HTTP2_SOCKET_UNBOUND]: The socket has been disconnected from the Http2Session
>     at Object.get (node:http2:89:19)
>     at Http2Server.<anonymous> (file:///Users/julien/Library/Caches/deno/npm/registry.npmjs.org/@grpc/grpc-js/1.14.3/build/src/server.js:1193:148)
>     at Http2Server.emit (ext:deno_node/_events.mjs:436:20)
>     at Http2Server.<anonymous> (node:http2:1210:14)
>     at Http2Server.emit (ext:deno_node/_events.mjs:436:20)
>     at TCP._onconnection (node:net:1309:8)
>     at TCP.#accept (ext:deno_node/internal_binding/tcp_wrap.ts:363:12)
>     at eventLoopTick (ext:core/01_core.js:187:7) {
>   code: "ERR_HTTP2_SOCKET_UNBOUND",
>   name: "Error"
> }
> ```

Yes this example works on deno 2.7.12
