### ISSUE TITLE
runtime.listResourceOutputs broken in node.js SDK

### ISSUE THREAD

**Issue by squarebracket** [pulumi/pulumi#3905]
With the latest packages, `runtime.listResourceOutputs` fails with a protobuf deserialization error:

```
    AssertionError: Failure: Decoder hit an error
        at new goog.asserts.AssertionError (/home/chuck/le-codes/asp-pulumi/node_modules/google-protobuf/google-protobuf.js:81:876)
        at Object.goog.asserts.fail (/home/chuck/le-codes/asp-pulumi/node_modules/google-protobuf/google-protobuf.js:84:89)
        at jspb.BinaryReader.nextField (/home/chuck/le-codes/asp-pulumi/node_modules/google-protobuf/google-protobuf.js:375:123)
        at proto.google.protobuf.Struct.deserializeBinaryFromReader (/home/chuck/le-codes/pulumi-library/node_modules/google-protobuf/google/protobuf/struct_pb.js:146:17)
        at jspb.BinaryReader.readMessage (/home/chuck/le-codes/asp-pulumi/node_modules/google-protobuf/google-protobuf.js:384:329)
        at proto.google.protobuf.Value.deserializeBinaryFromReader (/home/chuck/le-codes/pulumi-library/node_modules/google-protobuf/google/protobuf/struct_pb.js:338:14)
        at jspb.BinaryReader.readMessage (/home/chuck/le-codes/pulumi-library/node_modules/google-protobuf/google-protobuf.js:384:329)
        at Function.jspb.Map.deserializeBinary (/home/chuck/le-codes/pulumi-library/node_modules/google-protobuf/google-protobuf.js:411:202)
        at /home/chuck/le-codes/pulumi-library/node_modules/google-protobuf/google/protobuf/struct_pb.js:155:18
        at jspb.BinaryReader.readMessage (/home/chuck/le-codes/asp-pulumi/node_modules/google-protobuf/google-protobuf.js:384:329)
    error: transport is closing
 
    panic: send on closed channel
    goroutine 135 [running]:
    main.(*nodeLanguageHost).Run.func4(0xc0001b84e0, 0xc0001b8540)
        /home/travis/gopath/src/github.com/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/main.go:446 +0xc4
    created by main.(*nodeLanguageHost).Run
        /home/travis/gopath/src/github.com/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/main.go:443 +0x3e4
```

pulumi version v1.10.1

```
npm ls | grep pulumi
asp@ /home/chuck/le-codes/asp-pulumi
├─┬ @pulumi/aws@1.21.0
│ ├── @pulumi/pulumi@1.10.1 deduped
├─┬ @pulumi/digitalocean@1.6.0
│ ├── @pulumi/pulumi@1.10.1 deduped
├─┬ @pulumi/eks@0.18.19
│ ├── @pulumi/aws@1.21.0 deduped
│ ├── @pulumi/kubernetes@1.5.1 deduped
│ ├── @pulumi/pulumi@1.10.1 deduped
├─┬ @pulumi/kubernetes@1.5.1
│ ├── @pulumi/pulumi@1.10.1 deduped
├─┬ @pulumi/kubernetesx@0.1.2
│ ├─┬ @pulumi/kubernetes@1.4.5
│ │ ├── @pulumi/pulumi@1.9.1 deduped
│ └─┬ @pulumi/pulumi@1.9.1
│   ├── @pulumi/query@0.3.0 deduped
├─┬ @pulumi/pulumi@1.10.1
│ ├── @pulumi/query@0.3.0
├─┬ @pulumi/random@1.5.0
│ └── @pulumi/pulumi@1.10.1 deduped
├─┬ UNMET DEPENDENCY @vantrix/pulumi-library@0.1.6
│ ├── @pulumi/aws@1.21.0 deduped
│ ├─┬ UNMET DEPENDENCY @pulumi/digitalocean@1.6.0
│ │ ├── @pulumi/pulumi@1.10.1 deduped
│ ├─┬ UNMET DEPENDENCY @pulumi/kubernetes@1.5.1
│ │ ├── @pulumi/pulumi@1.10.1 deduped
│ ├── @pulumi/pulumi@1.10.1 deduped
```

**Comment by leezen** [comment]
Do you mind providing a small repro program? I wasn't able to reproduce this behavior with a simple program that creates one bucket and then calls listResourceOutputs.

**Comment by squarebracket** [comment]
What versions were you using?

**Comment by squarebracket** [comment]
You're right -- it seems that small programs don't suffer from this problem. But at some point, it starts happening.

I just hit the problem on another program. I've had it there since I started programming to see when it would happen. Unfortunately, it seems to only happen when trying to create an actual resource; I never hit the error when previewing the resources. I can give you the stack/update if you want to investigate.

I've noticed, in the stack where I just got the error, the following:
```
at Object.<anonymous> (/home/chuck/le-codes/asp-pulumi-front/index.ts:238:45)
```
However, this doesn't correspond to `index.ts:238:45`. I'm guessing this is because it's actually using a compiled-down js file, but it's not using the source-mapped line/column. Is there a way to see the actual js file that it's using so that I can track down the offending resource?

**Comment by leezen** [comment]
I'd be happy to take a look at the stack/program. Can you find me on the [community Slack](https://slack.pulumi.com) and we can exchange files that way?

Regarding the line correspondence -- I don't think I've run into that before, so not sure what that's about.

**Comment by leezen** [comment]
This appears to be an issue with synchronous invokes, which has been problematic in the past (see https://github.com/pulumi/pulumi/issues/3528). You can try running this with async invokes, which worked for me (`pulumi config set pulumi:noSyncCalls true`)

**Comment by mikhailshilkov** [comment]
I believe this has been fixed a long time ago, closing
