### ISSUE TITLE
Assertion failure on stack import when pending_operations list contains an empty object

### ISSUE THREAD

**Issue by smena** [pulumi/pulumi#3921]
Pulumi CLI stack traces with `fatal: An assertion has failed: type was empty` when importing state that has been modified with "pending_operations" set to a list containing an empty object.

**Expected result**
Stack imports successfully

**Steps to reproduce**
1. Create a resource and kill the CLI before the operation completes.
2. Export the state with `pulumi stack export` and modify "pending_operations" in the resulting file:
```
        "pending_operations": [{}]
```
3. Attempt to. run `pulumi stack import`

**Resolution**
Remove "pending_operations" entirely or setting it to an empty list.

**Stack trace**
```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v1.10.1
Go Version:       go1.13.7
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: An assertion has failed: type was empty

goroutine 1 [running]:
runtime/debug.Stack(0xc0004b8be8, 0x4fe0940, 0xc0003acb60)
	/usr/local/Cellar/go/1.13.7/libexec/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
	/private/tmp/pulumi-20200207-86636-xtcwe5/src/github.com/pulumi/pulumi/main.go:30 +0x6e
panic(0x4fe0940, 0xc0003acb60)
	/usr/local/Cellar/go/1.13.7/libexec/src/runtime/panic.go:679 +0x1b2
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
	/private/tmp/pulumi-20200207-86636-xtcwe5/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0x0, 0x52cb596, 0xe, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20200207-86636-xtcwe5/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x197
github.com/pulumi/pulumi/pkg/resource.NewState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0003a4c90, 0xc0003a4d50, 0x0, ...)
	/private/tmp/pulumi-20200207-86636-xtcwe5/src/github.com/pulumi/pulumi/pkg/resource/resource_state.go:54 +0x58
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeResource(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200207-86636-xtcwe5/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:410 +0x296
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeOperation(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200207-86636-xtcwe5/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:417 +0x83
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeDeploymentV3(0x19018510, 0xed5d6879c, 0x611d040, 0xc000f50300, 0x40, 0xc000fae050, 0x7, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200207-86636-xtcwe5/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:238 +0x59f
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeUntypedDeployment(0xc000b89960, 0x55983e0, 0x6139c80, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20200207-86636-xtcwe5/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:175 +0x186
github.com/pulumi/pulumi/cmd.newStackImportCmd.func1(0xc000129b80, 0xc00057d0c0, 0x0, 0x4, 0x11, 0x11)
	/private/tmp/pulumi-20200207-86636-xtcwe5/src/github.com/pulumi/pulumi/cmd/stack_import.go:78 +0x231
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc000129b80, 0xc00057d0c0, 0x0, 0x4, 0x0, 0x0)
	/private/tmp/pulumi-20200207-86636-xtcwe5/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:96 +0x51
github.com/pulumi/pulumi/pkg/util/cmdutil.RunResultFunc.func1(0xc000129b80, 0xc00057d0c0, 0x0, 0x4)
	/private/tmp/pulumi-20200207-86636-xtcwe5/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000129b80, 0xc00057d000, 0x4, 0x4, 0xc000129b80, 0xc00057d000)
	/private/tmp/pulumi-20200207-86636-xtcwe5/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d5900, 0x0, 0x0, 0x52c0f5d)
	/private/tmp/pulumi-20200207-86636-xtcwe5/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/pulumi-20200207-86636-xtcwe5/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/private/tmp/pulumi-20200207-86636-xtcwe5/src/github.com/pulumi/pulumi/main.go:49 +0x63
```

**Comment by mikhailshilkov** [comment]
It will work if one specifies `"pending_operations": []` (an emtry array). I don't think we need to support an empty object literal there, so I'll close the issue as won't do.
