### ISSUE TITLE
Panic in display logic when interactive mode is (incorrectly?) inferred in CI

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3935]
A user reported that they are seeing the panic below when they run in CI unless they explicitly pass `--non-interactive`.  We should in this case be detecting we are in a non-interactive environment and disabling the progress display by default - but it appears this detection is not working correctly.

```
panic: fatal: An assertion has failed: action must be non empty
goroutine 32 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0x0, 0x16d97be, 0x18, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x197
github.com/pulumi/pulumi/pkg/backend/display.makeActionProgress(0x2659b50, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:60 +0xe8
github.com/pulumi/pulumi/pkg/backend/display.(*ProgressDisplay).refreshColumns(0xc001238000, 0x2659b50, 0x1, 0xc0012cc230, 0x5, 0x5, 0xc0012c2d80, 0x5, 0x5)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:373 +0x10d
github.com/pulumi/pulumi/pkg/backend/display.(*ProgressDisplay).refreshAllRowsIfInTerminal(0xc001238000)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:591 +0x36e
github.com/pulumi/pulumi/pkg/backend/display.(*ProgressDisplay).processNormalEvent(0xc001238000, 0x16c72e0, 0xc, 0x1559ec0, 0xc000aba640)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:966 +0x45a
github.com/pulumi/pulumi/pkg/backend/display.(*ProgressDisplay).processEvents(0xc001238000, 0xc000108050, 0xc000041020)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:1033 +0x13d
github.com/pulumi/pulumi/pkg/backend/display.ShowProgressEvents.func1(0xc001238000, 0xc000108050, 0xc000041020, 0xc000394000)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:277 +0x3f
created by github.com/pulumi/pulumi/pkg/backend/display.ShowProgressEvents
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:276 +0x44b
```

**Comment by lukehoban** [comment]
I believe the issue here is that the code below is inferring a terminal width of `0`, but is also inferring that the terminal *is* interactive.  Ideally we would detect that this is not truly interactive, but we have [many heuristics already for that](https://github.com/pulumi/pulumi/blob/f6402882c2c1b6ef691d41aca7d06503ca7cfffa/pkg/util/cmdutil/console.go#L46-L51), and without knowing more about the CI system, its hard to be sure what if anything it is doing to indicate it is not interactive.  

We could potentially fix this by either:
* Setting a minimum width (and height?) in the code below (to avoid the panic, but still would render awkwardly by default), or 
* Using a 0-width terminal as indication that it is "non-interactive" (not clear this is always "correct"?)

https://github.com/pulumi/pulumi/blob/f6402882c2c1b6ef691d41aca7d06503ca7cfffa/pkg/backend/display/progress.go#L274-L277
