### ISSUE TITLE
Pulumi.ResourceException: The system cannot find the file specified - Helm Chart - .NET SDK

### ISSUE THREAD

**Issue by sfmskywalker** [pulumi/pulumi#4006]
When I try to apply a Helm chart like so:

```csharp
// Test Helm.
var chart = new Pulumi.Kubernetes.Helm.V2.Chart("nginx", new ChartArgs
{
    Namespace = "default",
    Chart = "nginx-ingress",
    Version = "1.24.4",
    FetchOptions = new ChartFetchArgs
    {
        Repo = "https://kubernetes-charts.storage.googleapis.com/"
    },
}, new ComponentResourceOptions
{
    Provider = k8sProvider
});
```
, I get the following error:

```
Diagnostics:
  kubernetes:helm.sh:Chart (nginx):
    error: Pulumi.ResourceException: The system cannot find the file specified.
       at Pulumi.Kubernetes.Helm.ChartBase.<>c__DisplayClass0_0.<.ctor>b__1(ValueTuple`2 values)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

My fork of the samples repo contains a repro:

https://github.com/sfmskywalker/examples/commit/63b5af0d29baa219eb067ed57a872845879dcc23

**Comment by sfmskywalker** [comment]
Interestingly enough, I get a different error when I start a brand new Pulumi project and add a Chart:

```
Diagnostics:
  pulumi:pulumi:Stack (helm-test-dev):
    error: Running program 'C:\Projects\Tests\Helm\bin\Debug\netcoreapp3.1\helm-test.dll' failed with an unhandled exception:
    System.InvalidOperationException: dictionary contains invalid type System.Object. Allowed types are:
        String, Boolean, Int32, Double,
        Nullable<...>, ImmutableArray<...> and ImmutableDictionary<string, ...> or
        a class explicitly marked with the [OutputTypeAttribute].
       at Pulumi.Serialization.Converter.CheckTargetType(String context, Type targetType, HashSet`1 seenTypes)
       at Pulumi.Serialization.Converter.CheckTargetType(String context, Type targetType, HashSet`1 seenTypes)
       at Pulumi.DictionaryResourceArgs..ctor(ImmutableDictionary`2 dictionary)
       at Pulumi.Kubernetes.KubernetesResource..ctor(String type, String name, ImmutableDictionary`2 dictionary, CustomResourceOptions options)
       at Pulumi.Kubernetes.Rbac.V1Beta1.ClusterRole..ctor(String name, ImmutableDictionary`2 dictionary, CustomResourceOptions options)
       at Pulumi.Kubernetes.Yaml.Parser.<>c__DisplayClass3_0.<ParseYamlObject>b__159(String id)
       at Pulumi.Output`1.<>c__DisplayClass12_0`1.<Apply>b__0(T t)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.AllHelperAsync(ImmutableArray`1 inputs)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.<TupleHelperAsync>g__GetData|20_0[T1,T2,T3,T4,T5,T6,T7,T8,X](Input`1 input)
       at Pulumi.Output`1.TupleHelperAsync[T1,T2,T3,T4,T5,T6,T7,T8](Input`1 item1, Input`1 item2, Input`1 item3, Input`1 item4, Input`1 item5, Input`1 item6, Input`1 item7, Input`1 item8)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

Project with repro: https://github.com/sfmskywalker/pulumi-helm-issue-repro

**Comment by mikhailshilkov** [comment]
@sfmskywalker Thanks for reporting this and the repro! I was able to reproduce your second error and fix it, so I got that Helm chart working locally

```
Previewing update (dev):
     Type                                                           Name                                         Plan       
     pulumi:pulumi:Stack                                            aks-cs-yaml-dev                                         
 +   ├─ kubernetes:helm.sh:Chart                                    nginx                                        create     
 +   │  ├─ kubernetes:core:ServiceAccount                           default/nginx-nginx-ingress                  create     
 +   │  ├─ kubernetes:core:ServiceAccount                           default/nginx-nginx-ingress-backend          create     
 +   │  ├─ kubernetes:rbac.authorization.k8s.io:ClusterRoleBinding  nginx-nginx-ingress                          create     
 +   │  ├─ kubernetes:rbac.authorization.k8s.io:RoleBinding         default/nginx-nginx-ingress                  create     
 +   │  ├─ kubernetes:rbac.authorization.k8s.io:ClusterRole         nginx-nginx-ingress                          create     
 +   │  ├─ kubernetes:core:Service                                  default/nginx-nginx-ingress-controller       create     
 +   │  ├─ kubernetes:core:Service                                  default/nginx-nginx-ingress-default-backend  create     
 +   │  ├─ kubernetes:rbac.authorization.k8s.io:Role                default/nginx-nginx-ingress                  create     
 +   │  ├─ kubernetes:apps:Deployment                               default/nginx-nginx-ingress-default-backend  create     
 +   │  └─ kubernetes:apps:Deployment                               default/nginx-nginx-ingress-controller       create
```

Watch for a release after #4023 is merged.

**Comment by sfmskywalker** [comment]
Sweet! :)

**Comment by mitchellmaler** [comment]
@mikhailshilkov 

I am getting the same error using Pulumi version v1.12.1 on MacOS and Kubernetes Plugin 1.6.0-alpha.1583869930+g9c001ff9.

```c#
var rancherHelmRelease = new Pulumi.Kubernetes.Helm.V3.Chart("rancher",
new ChartArgs
{
    Chart = "rancher",
    Version = args.RancherVersion,
    Namespace = cattleSystemNamespace.Metadata.Apply(x => x.Name),
    Values =
    {
        {"ingress.tls.source", "external"},
        {"tls", "external"},
        {"hostname", args.RancherDns},
        {"debug", args.RancherEnableDebug},
        {"replicas", 3}
    },
    FetchOptions = new ChartFetchArgs
    {
        Repo = "https://releases.rancher.com/server-charts/stable"
    }
},
new ComponentResourceOptions
{
    Provider = kubernetesProvider
});
```

```
error: Running program '/repos/pulumi-projects/rancher-server-cluster/bin/Debug/netcoreapp3.1/rancher-server-cluster.dll' failed with an unhandled exception:
    System.InvalidOperationException: dictionary contains invalid type System.Object. Allowed types are:
        String, Boolean, Int32, Double,
        Nullable<...>, ImmutableArray<...> and ImmutableDictionary<string, ...> or
        a class explicitly marked with the [OutputTypeAttribute].
       at Pulumi.Serialization.Converter.CheckTargetType(String context, Type targetType, HashSet`1 seenTypes)
       at Pulumi.Serialization.Converter.CheckTargetType(String context, Type targetType, HashSet`1 seenTypes)
       at Pulumi.DictionaryResourceArgs..ctor(ImmutableDictionary`2 dictionary)
       at Pulumi.Kubernetes.KubernetesResource..ctor(String type, String name, ImmutableDictionary`2 dictionary, CustomResourceOptions options)
       at Pulumi.Kubernetes.Rbac.V1.ClusterRoleBinding..ctor(String name, ImmutableDictionary`2 dictionary, CustomResourceOptions options)
       at Pulumi.Kubernetes.Yaml.Parser.<>c__DisplayClass3_0.<ParseYamlObject>b__144(String id)
       at Pulumi.Output`1.<>c__DisplayClass12_0`1.<Apply>b__0(T t)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.AllHelperAsync(ImmutableArray`1 inputs)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.<TupleHelperAsync>g__GetData|20_0[T1,T2,T3,T4,T5,T6,T7,T8,X](Input`1 input)
       at Pulumi.Output`1.TupleHelperAsync[T1,T2,T3,T4,T5,T6,T7,T8](Input`1 item1, Input`1 item2, Input`1 item3, Input`1 item4, Input`1 item5, Input`1 item6, Input`1 item7, Input`1 item8)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

**Comment by mikhailshilkov** [comment]
@mitchellmaler You are correct, you'd have to wait until https://github.com/pulumi/pulumi-kubernetes/pull/1030 is merged. We'll hopefully do that today U.S. day time. Sorry for the inconvenience.

**Comment by mitchellmaler** [comment]
@mikhailshilkov Okay good to hear!

**Comment by pkartner** [comment]
I'm still getting this error with pulumi 2.1.

**Comment by mikhailshilkov** [comment]
@pkartner Which version of `Pulumi.Kubernetes` and which Helm chart are you using?

**Comment by pkartner** [comment]
@mikhailshilkov Thanks for your response. I'm using Pulumi.Kubernetes 2.0.0 and trying to deploy stable/traefik.
