### ISSUE TITLE
Unable to Run Sharp in AWS Lambda

### ISSUE THREAD

**Issue by hwangar** [pulumi/pulumi#4073]
With latest versions of the libraries, from an env MacoOS/node@12:

```
    "@pulumi/aws": "^1.26.0",
    "@pulumi/cloud-aws": "^0.18.2",
    "@pulumi/pulumi": "^1.12.1",
    "sharp": "^0.25.1"
```

I couldn't make pulumi work with sharp library:

normal install pushes darwin libraries => it deploys but sharp is not working

...and following the solution at https://github.com/pulumi/pulumi/issues/2077: 

rm -rf node_modules/sharp;docker run -v $PWD:/var/task lambci/lambda:build-nodejs12.x npm install sharp

I got:
```
    error: Running program '/Users/juanarics/Projects/_tests/pulumi-aws-sharp' failed with an unhandled exception:
    Error: 'linux-x64' binaries cannot be used on the 'darwin-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.
        at Object.hasVendoredLibvips (/Users/juanarics/Projects/_tests/pulumi-aws-sharp/node_modules/sharp/lib/libvips.js:68:13)
        at Object.<anonymous> (/Users/juanarics/Projects/_tests/pulumi-aws-sharp/node_modules/sharp/lib/constructor.js:7:22)
        at Module._compile (internal/modules/cjs/loader.js:1158:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
        at Module.load (internal/modules/cjs/loader.js:1002:32)
        at Function.Module._load (internal/modules/cjs/loader.js:901:14)
        at Module.require (internal/modules/cjs/loader.js:1044:19)
        at require (internal/modules/cjs/helpers.js:77:18)
        at Object.<anonymous> (/Users/juanarics/Projects/_tests/pulumi-aws-sharp/node_modules/sharp/lib/index.js:3:15)
        at Module._compile (internal/modules/cjs/loader.js:1158:30)
```

**Comment by mikesurowiec** [comment]
For anyone who stumbles on this, the solution I found was to get a version of sharp installed locally that lambda can use ([more details here](https://sharp.pixelplumbing.com/install#aws-lambda)).
```sh
$ rm -rf node_modules/sharp && SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux sharp
```
And then only require sharp inside of the pulumi magic function.
```ts
import * as aws from '@pulumi/aws';

const myBucket = new aws.s3.Bucket('my-bucket');
myBucket.onObjectCreated('imageHandler', (e) => {
    const sharp = require('sharp'); // use require to import sharp here!
});
```
Not importing it at the top of the file allows pulumi to successfully run the infrastructure changes and push the lambda code up.
