### ISSUE TITLE
Possible mock resource ordering problem

### ISSUE THREAD

**Issue by hexmoose** [pulumi/pulumi#4097]
We're working to move over to the new mock resource feature that was added in https://github.com/pulumi/pulumi/pull/3738, and we've encountered what appears to be an ordering problem. When the order of operations is swapped (see the final test example), the test hangs indefinitely. Here's an example test suite that can be run with mocha:

```typescript
import * as assert from "assert";
import * as aws from "@pulumi/aws";
import * as pulumi from "@pulumi/pulumi";

pulumi.runtime.setMocks({
    newResource: function(resourceType, name, inputs) {
        const defaultState = {
            arn: `${name}-arn`,
            name: name,
            ...inputs,
        };
        console.log("newResource: type =>", resourceType);
        console.log("newResource: name =>", name);
        console.log("newResource: inputs =>", inputs);
        console.log("newResource: defaultState =>", defaultState);
        return { id: "", state: defaultState };
    },

    call: function(token, args) {
        console.log("call: token =>", token);
        console.log("call: args =>", args);
        return {
            accountId: "012345678910",
        };
    },
});

const bucket = new aws.s3.Bucket("my-bucket");

describe("example", function() {
    it("is working test", function(done) {
        pulumi
            .all([bucket.arn, aws.getCallerIdentity().accountId])
            .apply(([arn, accountId]) => {
                try {
                    assert.equal(arn, "my-bucket-arn");
                    assert.equal(accountId, "012345678910");
                    done();
                } catch (e) {
                    done(e);
                }
            });
    });
    it("is another working test", async function() {
        const accountId = aws.getCallerIdentity().accountId;
        const arn = await (bucket.arn as any).promise();

        assert.equal(arn, "my-bucket-arn");
        assert.equal(accountId, "012345678910");
    });
    it("is a test that times out and hangs", async function() {
        const arn = await (bucket.arn as any).promise();
        const accountId = aws.getCallerIdentity().accountId;

        assert.equal(arn, "my-bucket-arn");
        assert.equal(accountId, "012345678910");
    });
});
```

Sample output:

```
newResource: type => aws:s3/bucket:Bucket
newResource: name => my-bucket
newResource: inputs => {}
newResource: defaultState => { arn: 'my-bucket-arn', name: 'my-bucket' }
  example
call: token => aws:index/getCallerIdentity:getCallerIdentity
call: args => {}
    ✓ is working test
call: token => aws:index/getCallerIdentity:getCallerIdentity
call: args => {}
    ✓ is another working test
    1) is a test that times out and hangs


  2 passing (19s)
  1 failing

  1) example
       is a test that times out and hangs:
     Error: Timeout of 18000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (test/example.spec.ts)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
      at Object.run (<anonymous>)
      at Function.module.exports.loopWhile (node_modules/deasync/index.js:71:23)
      at Object.promiseResult (node_modules/@pulumi/pulumi/utils.js:86:13)
      at invokeFallbackToAsync (node_modules/@pulumi/pulumi/runtime/invoke.js:145:18)
      at invokeSync (node_modules/@pulumi/pulumi/runtime/invoke.js:99:16)
      at Object.invoke (node_modules/@pulumi/pulumi/runtime/invoke.js:84:24)
      at Object.getCallerIdentity (node_modules/@pulumi/getCallerIdentity.ts:36:70)
      at Context.<anonymous> (test/example.spec.ts:59:35)
      at Generator.next (<anonymous>)
      at fulfilled (test/example.spec.ts:5:58)

^C⏎
```

Is the mock getting overridden or removed somewhere? This is running on @pulumi/pulumi 1.12.1 and pulumi/aws 1.26.0. Thanks for looking into this!

**Comment by lukehoban** [comment]
I expect this is due to hangs when using "synchronous invokes" on newer Node.js versions.  This is being fixed in https://github.com/pulumi/pulumi/issues/3528, and a significant breaking change to remove the ability to use synchronous invokes is [part of 2.0](https://github.com/pulumi/pulumi/issues/3751)  to ensure this problem no longer occurs at all in Pulumi.

In the meantime, you will want to replace:

```ts
const accountId  = aws.getCallerIdentity().accountId
```

with:

```ts
const accountId  = (await aws.getCallerIdentity({ async: true})).accountId;
```

**Comment by hexmoose** [comment]
Thanks! Yes, that fixes it for me. I appreciate the quick response. Looking forward to 2.0. 👍
