### ISSUE TITLE
Panic when using Policy with `--json` flag

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#4124]
If I have a Policy pack enabled and run `pulumi preview --json`, Pulumi panics.

```
aws-ts-webserver % pulumi preview -s prod --json
panic: fatal: A failure has occurred: unknown event type 'policy-violation'

goroutine 84 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
        /private/tmp/pulumi-20200319-81049-s4yim0/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Failf(0x52ba634, 0x17, 0xc00111d8c0, 0x1, 0x1)
        /private/tmp/pulumi-20200319-81049-s4yim0/src/github.com/pulumi/pulumi/pkg/util/contract/fail.go:30 +0x181
github.com/pulumi/pulumi/pkg/backend/display.ShowJSONEvents(0xc000970420, 0x11, 0x52a24bf, 0x7, 0xc000694180, 0xc0006941e0, 0x52a028e, 0x6, 0x1000000000000, 0x0, ...)
        /private/tmp/pulumi-20200319-81049-s4yim0/src/github.com/pulumi/pulumi/pkg/backend/display/json.go:190 +0x485
github.com/pulumi/pulumi/pkg/backend/display.ShowEvents(0xc000970420, 0x11, 0x52a24bf, 0x7, 0xc0003b94c0, 0x4, 0xc00014ef40, 0x15, 0xc000694180, 0xc0006941e0, ...)
        /private/tmp/pulumi-20200319-81049-s4yim0/src/github.com/pulumi/pulumi/pkg/backend/display/display.go:47 +0x3bb
created by github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudUpdate).RecordAndDisplayEvents
        /private/tmp/pulumi-20200319-81049-s4yim0/src/github.com/pulumi/pulumi/pkg/backend/httpstate/state.go:205 +0x21a
aws-ts-webserver % 
```

**Comment by joeduffy** [comment]
Related to this, @lukehoban pointed out he's not sure if we would have serialized policy violations as diagnostics, or not. (I'm guessing the answer is "no" given the above.) Probably worth thinking about whether to add an entirely new section to the output, a peer to diagnostics, much like the display. This way we can give folks even more metadata about the violation than just an error message.

**Comment by lukehoban** [comment]
We fixed almost the exact same issue for the "watch" event display in https://github.com/pulumi/pulumi/pull/5569 - the fix for this should be the same thing but for the "json" event display.
