### ISSUE TITLE
Error: Cannot call '.get' during update or preview.

### ISSUE THREAD

**Issue by muhajirdev** [pulumi/pulumi#4313]
Here's my code

```javascript
const aws = require('@pulumi/aws')
const awsx = require('@pulumi/awsx')

const cluster = new awsx.ecs.Cluster('bitstream-cluster', {
  cluster: aws.ecs.Cluster.get('bitstream-builder'),
})

const image = awsx.ecs.Image.fromPath('bistream-builder', './Dockerfile')
```

Here's the full error
```
❯ pulumi up
Previewing update (dev):
     Type                                          Name                                Plan       Info
     pulumi:pulumi:Stack                           test-dev                                       1 error
 +   ├─ awsx:x:ec2:Vpc                             default-vpc-9ed95fe6                create     
 +   │  ├─ awsx:x:ec2:Subnet                       default-vpc-9ed95fe6-public-0       create     
 +   │  └─ awsx:x:ec2:Subnet                       default-vpc-9ed95fe6-public-1       create     
 +   ├─ awsx:x:ecs:Cluster                         bitstream-cluster                   create     
 +   │  └─ awsx:x:ec2:SecurityGroup                bitstream-cluster                   create     
 +   │     ├─ awsx:x:ec2:IngressSecurityGroupRule  bitstream-cluster-containers        create     
 +   │     │  └─ aws:ec2:SecurityGroupRule         bitstream-cluster-containers        create     
 +   │     ├─ awsx:x:ec2:EgressSecurityGroupRule   bitstream-cluster-egress            create     
 +   │     │  └─ aws:ec2:SecurityGroupRule         bitstream-cluster-egress            create     
 +   │     ├─ awsx:x:ec2:IngressSecurityGroupRule  bitstream-cluster-ssh               create     
 +   │     │  └─ aws:ec2:SecurityGroupRule         bitstream-cluster-ssh               create     
 +   │     └─ aws:ec2:SecurityGroup                bitstream-cluster                   create     
 +   ├─ aws:ecs:Cluster                            bitstream-builder                   create     
 +   └─ awsx:x:ecs:EC2TaskDefinition               build-bitstream                     create     
 +      ├─ aws:cloudwatch:LogGroup                 build-bitstream                     create     
 +      ├─ aws:iam:Role                            build-bitstream-task                create     
 +      ├─ aws:iam:Role                            build-bitstream-execution           create     
 +      ├─ aws:iam:RolePolicyAttachment            build-bitstream-execution-9a42f520  create     
 +      ├─ aws:ecs:TaskDefinition                  build-bitstream                     create     
 +      ├─ aws:iam:RolePolicyAttachment            build-bitstream-task-fd1a00e5       create     
 +      └─ aws:iam:RolePolicyAttachment            build-bitstream-task-32be53a2       create     
 
Diagnostics:
  pulumi:pulumi:Stack (test-dev):
    error: Running program '/Users/muhammadmuhajir/dev/muhajirdev/pulumi/test' failed with an unhandled exception:
    Error: Cannot call '.get' during update or preview.
    To manipulate the value of this Output, use '.apply' instead.
        at Proxy.get (/Users/muhammadmuhajir/dev/muhajirdev/pulumi/test/node_modules/@pulumi/pulumi/output.js:172:15)
        at EC2TaskDefinition.run (/Users/muhammadmuhajir/dev/muhajirdev/pulumi/test/node_modules/@pulumi/ecs/taskDefinition.ts:226:39)
        at Object.<anonymous> (/Users/muhammadmuhajir/dev/muhajirdev/pulumi/test/index.js:25:11)
        at Module._compile (internal/modules/cjs/loader.js:1158:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
        at Module.load (internal/modules/cjs/loader.js:1002:32)
        at Function.Module._load (internal/modules/cjs/loader.js:901:14)
        at Module.require (internal/modules/cjs/loader.js:1044:19)
        at require (internal/modules/cjs/helpers.js:77:18)
        at Object.<anonymous> (/Users/muhammadmuhajir/dev/muhajirdev/pulumi/test/node_modules/@pulumi/pulumi/cmd/run/run.js:214:31)
 
Outputs:
  - bucketName: "my-bucket-b209d4e"
  - serversIp : [
  -     [0]: "34.219.161.90"
    ]

```

I follow the documentation here https://www.pulumi.com/docs/guides/crosswalk/aws/ecs/

**Comment by lukehoban** [comment]
The usage of `get` that the error message is reporting looks like it is not the one from the code snippet you pasted. 

Do you have a call to .run in your code for a task definition?  What does that code look like?

And specifically what is at:

```

at Object.<anonymous> (/Users/muhammadmuhajir/dev/muhajirdev/pulumi/test/index.js:25:11)

```
