### ISSUE TITLE
Properties getters are executed during closure serialization

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#4368]
Our Node.js runtime seems to actually execute custom properties getters during closure serialization. This is problematic because the constructor has not yet run and so invariants that the properties assume to be held aren't true (to be honest, it's not even clear to me what `this` refers to).

For instance, this program fails to serialize:

```typescript
import * as aws from "@pulumi/aws";

class Foo {
    public readonly x: number;
    constructor(x: number) {
        this.x = x;
    }
    public get bar(): string {
        return this.x.toString(); // <-- this throws an error
    }
}

aws.cloudwatch.onSchedule(
    "timer",
    "cron(0 9 * * ? *)",
    async (ev) => {
        const f = new Foo(42);
        console.log(`TIMER[${new Date()}]: ${f.bar}`);
    },
);
```

The error is:

```
    TypeError: Cannot read property 'toString' of undefined
        at Object.get bar [as bar] (/Users/joeduffy/temp/closer/index.ts:9:23)
        at /Users/joeduffy/temp/closer/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:1082:19
        at Generator.next (<anonymous>)
        at /Users/joeduffy/temp/closer/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/joeduffy/temp/closer/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:17:12)
        at getOwnPropertyAsync (/Users/joeduffy/temp/closer/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:1081:12)
        at /Users/joeduffy/temp/closer/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:712:40
        at Generator.next (<anonymous>)
        at fulfilled (/Users/joeduffy/temp/closer/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:18:58)
```

Should we be doing something special with properties that have custom getters?

**Comment by lukehoban** [comment]
This doesn't repro for me.  It works and emits:

```js
exports.handler = __f0;

var __f1_prototype = {};
Object.defineProperty(__f1_prototype, "constructor", { configurable: true, writable: true, value: __f1 });
Object.defineProperty(__f1_prototype, "bar", { configurable: true, get: __f2 });
Object.defineProperty(__f1, "prototype", { value: __f1_prototype });

function __f1(__0) {
  return (function() {
    with({ this: undefined, arguments: undefined }) {

return function /*constructor*/(x) {
        this.x = x;
    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f2() {
  return (function() {
    with({ this: undefined, arguments: undefined }) {

return function /*bar*/() {
        return this.x.toString(); // <-- this throws an error
    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f0(__0) {
  return (function() {
    with({ Foo: __f1, this: undefined, arguments: undefined }) {

return async (ev) => {
    const f = new Foo(42);
    console.log(`TIMER[${new Date()}]: ${f.bar}`);
};

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

```
