### ISSUE TITLE
Python tests fail on exports

### ISSUE THREAD

**Issue by cmclaughlin** [pulumi/pulumi#4478]
Not sure if this is a Pulumi bug or just lack of documentation...?

I'm following this tutorial: https://www.pulumi.com/docs/guides/testing/unit/
But adding `pulumi.export` to the stack causes the tests to fail hard.

Is there a solution for this?

```
(.venv) cmclaughlin-local@cm in /tmp
$ git clone https://github.com/pulumi/examples.git
Cloning into 'examples'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (70/70), done.
Receiving objects: 100% (8466/8466), 9.34 MiB | 71.00 KiB/s, done.
remote: Total 8466 (delta 26), reused 37 (delta 14), pack-reused 8380
Resolving deltas: 100% (5094/5094), done.

(.venv) cmclaughlin-local@cm in /tmp
$ cd examples/testing-unit-py/

(.venv) cmclaughlin-local@cm in /tmp/examples/testing-unit-py
on master
$ echo "pulumi.export('hello', 'world')" >> infra.py

(.venv) cmclaughlin-local@cm in /tmp/examples/testing-unit-py
on master
$ python -m unittest
E
======================================================================
ERROR: test_ec2 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_ec2
Traceback (most recent call last):
  File "/Users/cmclaughlin-local/.pyenv/versions/3.7.4/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/cmclaughlin-local/.pyenv/versions/3.7.4/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/private/tmp/examples/testing-unit-py/test_ec2.py", line 13, in <module>
    import infra
  File "/private/tmp/examples/testing-unit-py/infra.py", line 20, in <module>
    pulumi.export('hello', 'world')
  File "/Users/cmclaughlin-local/repos/shopstyle/pulumi/stacks/pypy/.venv/lib/python3.7/site-packages/pulumi-2.1.0a1587474541-py3.7.egg/pulumi/resource.py", line 884, in export
    raise Exception("Failed to export output. Root resource is not an instance of 'Stack'")
Exception: Failed to export output. Root resource is not an instance of 'Stack'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by clstokes** [comment]
This error still occurs with the latest versions of `pulumi` and `pulumi-aws`.

Code to reproduce (based on @cmclaughlin steps) - https://gist.github.com/a6ea8084292f223c42aa38624d24bd18. Note the `pulumi.export()` in `infra.py`.

```
(venv) testing-unit-py % pip list
Package    Version
---------- -------
Arpeggio   1.9.2
attrs      19.3.0
dill       0.3.1.1
grpcio     1.29.0
parver     0.3.0
pip        20.1
protobuf   3.12.0
pulumi     2.2.1
pulumi-aws 2.4.0
semver     2.10.1
setuptools 46.4.0
six        1.14.0
wheel      0.34.2
(venv) testing-unit-py % python -m unittest
E
======================================================================
ERROR: test_ec2 (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_ec2
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/clstokes/go/src/github.com/pulumi/examples/testing-unit-py/test_ec2.py", line 13, in <module>
    import infra
  File "/Users/clstokes/go/src/github.com/pulumi/examples/testing-unit-py/infra.py", line 20, in <module>
    pulumi.export('hello', 'world')
  File "/Users/clstokes/go/src/github.com/pulumi/examples/testing-unit-py/venv/lib/python3.7/site-packages/pulumi/resource.py", line 884, in export
    raise Exception("Failed to export output. Root resource is not an instance of 'Stack'")
Exception: Failed to export output. Root resource is not an instance of 'Stack'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
(venv) testing-unit-py %
```
