### ISSUE TITLE
Fatal Error encoutered when running pulumi up

### ISSUE THREAD

**Issue by jimsorock** [pulumi/pulumi#4519]
```
Pulumi Version:   v2.0.0
Go Version:       go1.14.2
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: index out of range [-1]

goroutine 1 [running]:
runtime/debug.Stack(0xc0006b4280, 0x5272e60, 0xc00092e020)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
	/private/tmp/pulumi-20200416-24195-7o2f34/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x6e
panic(0x5272e60, 0xc00092e020)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
gopkg.in/AlecAivazis/survey%2ev1.(*Select).OnChange(0xc000a10ea0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x631aee8, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200416-24195-7o2f34/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/select.go:154 +0x6ad
gopkg.in/AlecAivazis/survey%2ev1.(*Select).Prompt(0xc000a10ea0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20200416-24195-7o2f34/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/select.go:234 +0x3b4
gopkg.in/AlecAivazis/survey%2ev1.Ask(0xc0006b4970, 0x1, 0x1, 0x502f300, 0xc001342630, 0x0, 0x0, 0x0, 0xc000010018, 0xc00181e998)
	/private/tmp/pulumi-20200416-24195-7o2f34/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/survey.go:148 +0x187
gopkg.in/AlecAivazis/survey%2ev1.AskOne(0x56ff960, 0xc000a10ea0, 0x502f300, 0xc001342630, 0x0, 0x0, 0x0, 0x0, 0x42, 0x0)
	/private/tmp/pulumi-20200416-24195-7o2f34/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/survey.go:94 +0xeb
github.com/pulumi/pulumi/pkg/v2/backend.confirmBeforeUpdating(0x5353f23, 0x6, 0x5721fc0, 0xc00065e480, 0xc000700400, 0x1e, 0x20, 0x631aee8, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200416-24195-7o2f34/src/github.com/pulumi/pulumi/pkg/backend/apply.go:168 +0x43c
github.com/pulumi/pulumi/pkg/v2/backend.PreviewThenPrompt(0x5708a20, 0xc000040078, 0x5353f23, 0x6, 0x5721fc0, 0xc00065e480, 0xc00065e580, 0xc00060e480, 0x32, 0xc000b70300, ...)
	/private/tmp/pulumi-20200416-24195-7o2f34/src/github.com/pulumi/pulumi/pkg/backend/apply.go:127 +0x24d
github.com/pulumi/pulumi/pkg/v2/backend.PreviewThenPromptThenExecute(0x5708a20, 0xc000040078, 0x5353f23, 0x6, 0x5721fc0, 0xc00065e480, 0xc00065e580, 0xc00060e480, 0x32, 0xc000b70300, ...)
	/private/tmp/pulumi-20200416-24195-7o2f34/src/github.com/pulumi/pulumi/pkg/backend/apply.go:199 +0x1ac
github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudBackend).Update(0xc0003025d0, 0x5708a20, 0xc000040078, 0x5721fc0, 0xc00065e480, 0xc00065e580, 0xc00060e480, 0x32, 0xc000b70300, 0x631aee8, ...)
	/private/tmp/pulumi-20200416-24195-7o2f34/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:819 +0xe6
github.com/pulumi/pulumi/pkg/v2/backend.UpdateStack(0x5708a20, 0xc000040078, 0x5721fc0, 0xc00065e480, 0xc00065e580, 0xc00060e480, 0x32, 0xc000b70300, 0x631aee8, 0x0, ...)
	/private/tmp/pulumi-20200416-24195-7o2f34/src/github.com/pulumi/pulumi/pkg/backend/stack.go:82 +0xc4
github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudStack).Update(0xc00065e480, 0x5708a20, 0xc000040078, 0xc00065e580, 0xc00060e480, 0x32, 0xc000b70300, 0x631aee8, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200416-24195-7o2f34/src/github.com/pulumi/pulumi/pkg/backend/httpstate/stack.go:148 +0x96
main.newUpCmd.func1(0x631aee8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, 0x631aee8, 0x0, ...)
	/private/tmp/pulumi-20200416-24195-7o2f34/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/up.go:133 +0xb0d
main.newUpCmd.func3(0xc000227340, 0x631aee8, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20200416-24195-7o2f34/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/up.go:370 +0x4ba
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc000227340, 0x631aee8, 0x0, 0x0)
	/private/tmp/pulumi-20200416-24195-7o2f34/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000227340, 0x631aee8, 0x0, 0x0, 0xc000227340, 0x631aee8)
	/private/tmp/pulumi-20200416-24195-7o2f34/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000226580, 0x15, 0x0, 0x0)
	/private/tmp/pulumi-20200416-24195-7o2f34/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/pulumi-20200416-24195-7o2f34/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
main.main()
	/private/tmp/pulumi-20200416-24195-7o2f34/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x4d
```

**Comment by stack72** [comment]
Hi @jimsorock 

Apologies you are getting this error. Can you you describe the setup you are using or some code or steps to recreate this?

Thank

Paul

**Comment by jimsorock** [comment]
```

**Comment by stack72** [comment]
Hi @jimsorock 

I'm so sorry for the lack of response on this issue :/ we've not had any further reports of this

I'm going to close this out

If this issue returns, please let me know and I can reopen it

Apologies again and thanks for letting us know

Paul
