### ISSUE TITLE
RecordSet - transport is closing

### ISSUE THREAD

**Issue by prkstaff** [pulumi/pulumi#4526]
### Problem description
Code works fine untill I try to create a RecordSet.

```
from pulumi_gcp.dns import RecordSet

dns = RecordSet("dns-api-renatoprado-com", managed_zone="renatoprado", rrdatas=["127.0.0.1"], 
                opts=ResourceOptions(provider=k8s_provider), type="A", name="api.renatoprado.com", ttl=float(300))
```
I am using this as guide: https://www.pulumi.com/docs/reference/pkg/gcp/dns/recordset/

### Errors & Logs

```
Diagnostics:
  pulumi:pulumi:Stack (jeitto-provision-dev):
    panic: fatal: An assertion has failed: Kubernetes GVK is: "urn:pulumi:dev::jeitto-provision::gcp:dns/recordSet:RecordSet::dns-api-renatoprado-com"
    goroutine 25 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0xc000df2100, 0x19785d3, 0x15, 0xc000e03438, 0x1, 0x1)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.0/go/common/util/contract/assert.go:33 +0x197
    github.com/pulumi/pulumi-kubernetes/provider/v2/pkg/provider.(*kubeProvider).gvkFromURN(0xc00038e000, 0xc000df21e0, 0x56, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3a22646572697571, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/provider/pkg/provider/provider.go:1933 +0x13e
    github.com/pulumi/pulumi-kubernetes/provider/v2/pkg/provider.(*kubeProvider).Check(0xc00038e000, 0x1bf9860, 0xc000e51110, 0xc000dd3280, 0xc00038e000, 0x1753201, 0xc000dd3300)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/provider/pkg/provider/provider.go:979 +0x92c
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Check_Handler.func1(0x1bf9860, 0xc000e51110, 0x1883840, 0xc000dd3280, 0x18b0bc0, 0x28bea50, 0x1bf9860, 0xc000e51110)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.0/proto/go/provider.pb.go:1848 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x1bf9860, 0xc000e50f30, 0x1883840, 0xc000dd3280, 0xc000def5c0, 0xc000def5e0, 0x0, 0x0, 0x1bb5760, 0xc000294270)
        /home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f9
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Check_Handler(0x18f5b60, 0xc00038e000, 0x1bf9860, 0xc000e50f30, 0xc000e4cd80, 0xc000224420, 0x1bf9860, 0xc000e50f30, 0xc001c17420, 0xd4)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.0/proto/go/provider.pb.go:1850 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00014bba0, 0x1c18080, 0xc00022d080, 0xc000df0100, 0xc00035bf20, 0x2889d98, 0x0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1082 +0x4fd
    google.golang.org/grpc.(*Server).handleStream(0xc00014bba0, 0x1c18080, 0xc00022d080, 0xc000df0100, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1405 +0xd23
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00054c170, 0xc00014bba0, 0x1c18080, 0xc00022d080, 0xc000df0100)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:746 +0xbb
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:744 +0xa1

  gcp:dns:RecordSet (dns-api-renatoprado-com):
    error: transport is closing

```

#### Pulumi
v2.0.0
#### Pip freeze

> Arpeggio==1.9.2
> attrs==19.3.0
> certifi==2020.4.5.1
> chardet==3.0.4
> dill==0.3.1.1
> grpcio==1.28.1
> idna==2.8
> parver==0.3.0
> pkg-resources==0.0.0
> protobuf==3.11.3
> pulumi==2.0.0
> pulumi-gcp==3.1.0
> pulumi-kubernetes==2.0.0
> pulumi-random==2.0.0
> requests==2.21.0
> semver==2.9.1
> six==1.14.0
> urllib3==1.24.3

**Comment by leezen** [comment]
It seems odd that the kubernetes provider panics on this, but it also looks odd that you're trying to use the gcp dns resource with the kubernetes provider?

**Comment by leezen** [comment]
Thanks -- I'll close this issue assuming you have things working. I created a new issue to track returning better error messages.
