### ISSUE TITLE
Pulumi.Tests.Mocks.MocksTests.TestCustom failing in master

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#4545]
```
4665A total of 1 test files matched the specified pattern.
4666[xUnit.net 00:00:01.66]     Pulumi.Tests.Mocks.MocksTests.TestCustom [FAIL]
4667  X Pulumi.Tests.Mocks.MocksTests.TestCustom [4ms]
4668  Error Message:
4669   System.NotSupportedException : Multiple executions of TestAsync must run serially. Please configure your unit test suite to run tests one-by-one.
4670  Stack Trace:
4671     at Pulumi.Deployment.TestAsync[TStack](IMocks mocks, TestOptions options) in /Users/travis/gopath/src/github.com/pulumi/pulumi/sdk/dotnet/Pulumi/Deployment/Deployment_Run.cs:line 127
4672   at Pulumi.Tests.Mocks.MocksTests.TestCustom() in /Users/travis/gopath/src/github.com/pulumi/pulumi/sdk/dotnet/Pulumi.Tests/Mocks/MocksTests.cs:line 33
4673--- End of stack trace from previous location where exception was thrown ---
4674
4675Test Run Failed.
4676Total tests: 86
4677     Passed: 85
4678     Failed: 1
4679 Total time: 3.6855 Seconds
```

**Comment by justinvp** [comment]
Still seeing this in master.
