### ISSUE TITLE
Please make IDeployment and Deployment.Instance public so that anyone can write unit-tests

### ISSUE THREAD

**Issue by StefH** [pulumi/pulumi#4555]
This file is used as test-base for all tests:
https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi.Tests/PulumiTest.cs
``` c#
private static async Task Run(Func<Task> func, bool dryRun)
        {
            var mock = new Mock<IDeployment>(MockBehavior.Strict);
            mock.Setup(d => d.IsDryRun).Returns(dryRun);

            Deployment.Instance = new DeploymentInstance(mock.Object);
            await func().ConfigureAwait(false);
            Deployment.Instance = null!;
        }
```

But I cannot use this in my own tests...
![image](https://user-images.githubusercontent.com/249938/80908615-974c0400-8d21-11ea-9a75-e8e070ca66b7.png)

@mikhailshilkov can you please make `IDeployment` and `Deployment.Instance` public ?

**Comment by mikhailshilkov** [comment]
@StefH There is a `TestAsync` method for you to write unit tests.

Have a look at our [Unit Testing guide](https://www.pulumi.com/docs/guides/testing/unit/) and [Unit Testing in C# example](https://www.pulumi.com/docs/guides/testing/unit/). I'm curious if that solves your needs.

**Comment by StefH** [comment]
1] It seems that if I want to test a ComponentResource, I need to create a new Stack for each test ?

2] And when trying to create a Blob in a test-stack, I get this exception:
```
System.InvalidOperationException: Unsupported value when converting to protobuf: Pulumi.FileAsset
   at Pulumi.Serialization.Serializer.CreateValue(Object value)
   at Pulumi.Serialization.Serializer.CreateStruct(ImmutableDictionary`2 serializedDictionary)
   at Pulumi.Testing.MockMonitor.SerializeAsync(Object o)
   at Pulumi.Testing.MockMonitor.RegisterResourceAsync(Resource resource, RegisterResourceRequest request)
   at Pulumi.Deployment.RegisterResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options)
   at Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options)
   at Pulumi.Deployment.CompleteResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
   at Pulumi.Output`1.GetValueAsync()
   at Pulumi.Deployment.Logger.TryGetResourceUrnAsync(Resource resource)
   at Pulumi.Deployment.Runner.WhileRunningAsync()
   at Pulumi.Deployment.TestAsync[TStack](IMocks mocks, TestOptions options)
   at 
```

**Comment by mikhailshilkov** [comment]
1. Yes. We don't have a way to run an isolated component resource, currently.
2. Doesn't sound right... Could you make a separate issue to track?

**Comment by StefH** [comment]
Should I add a new issue in this project?
Or pulumi-azure?

**Comment by mikhailshilkov** [comment]
This repo: it's probably not specific to Azure. Thank you!

**Comment by StefH** [comment]
@mikhailshilkov & @justinvp 
Issue created : https://github.com/pulumi/pulumi/issues/4558
