### ISSUE TITLE
Integration test of Pulumi program does not pick up the currently active stack configuration from the yaml file

### ISSUE THREAD

**Issue by hemantgs** [pulumi/pulumi#4560]
I have the following pulumi pogram with `dev` stack :
```

"use strict";
const pulumi = require("@pulumi/pulumi");
const pulumiAws = require("@pulumi/aws");
const config = new pulumi.Config("modules");
const s3Config = config.getObject("s3");
const bucket = new pulumiAws.s3.Bucket(s3Config["name"]);
module.exports = { bucketId: s3Config["name"] };
```
And the stack config file : `Pulumi.dev.yaml`
```
config:
  aws:region: us-west-2
  modules:s3:
    name: test
```
This is the integration test 
```
package pulumi
import (
	"os"
	"path"
	"testing"
	"github.com/pulumi/pulumi/pkg/testing/integration"
)
func TestExamples(t *testing.T) {
	awsRegion := os.Getenv("AWS_REGION")
	if awsRegion == "" {
		awsRegion = "us-west-2"
	}
	cwd, _ := os.Getwd()
	integration.ProgramTest(t, &integration.ProgramTestOptions{
		Quick:       true,
		SkipRefresh: true,
		Dir:         path.Join(cwd, "..", "..", "resources"),
		Config: map[string]string{
			"aws:region": awsRegion,
		},
		UpdateCommandlineFlags: []string{"--non-interactive", "--yes"},
		StackName:              "dev",
	})
}                         
```
I am using s3 as pulumi backend , 
When I run this test , it times out with the below message 
```
Still running command '/usr/local/bin/pulumi stack init dev' (/var/folders/2l/gws8tbdx51jcm5tb63w_gcd4_dzl53/T/dev-924744879)...
panic: test timed out after 10m0s
goroutine 54 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1460 +0xdf
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x44
goroutine 1 [chan receive, 10 minutes]:
testing.tRunner.func1(0xc000248b40)
	/usr/local/go/src/testing/testing.go:957 +0x238
testing.tRunner(0xc000248b40, 0xc0006bfe10)
	/usr/local/go/src/testing/testing.go:996 +0x10b
testing.runTests(0xc00071f880, 0x5c86300, 0x1, 0x1, 0x0)
	/usr/local/go/src/testing/testing.go:1283 +0x2a7
testing.(*M).Run(0xc000736d00, 0x0)
	/usr/local/go/src/testing/testing.go:1200 +0x15f
main.main()
	_testmain.go:44 +0x135
goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x5c9f9c0)
	/Users/hooman/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/Users/hooman/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x26f
goroutine 20 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000234820)
	/Users/hooman/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/Users/hooman/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x57
goroutine 8 [chan receive, 10 minutes]:
github.com/rjeczalik/notify.(*recursiveTree).dispatch(0xc00072f400)
	/Users/hooman/go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_recursive.go:125 +0xc4
created by github.com/rjeczalik/notify.newRecursiveTree
	/Users/hooman/go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/tree_recursive.go:119 +0x132
goroutine 9 [syscall, 10 minutes, locked to thread]:
github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
	_cgo_gotypes.go:232 +0x41
github.com/rjeczalik/notify.init.1.func1()
	/Users/hooman/go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/watcher_fsevents_cgo.go:72 +0x3c
created by github.com/rjeczalik/notify.init.1
	/Users/hooman/go/pkg/mod/github.com/rjeczalik/notify@v0.9.2/watcher_fsevents_cgo.go:63 +0x4e
goroutine 10 [syscall, 5 minutes]:
syscall.syscall6(0x4082900, 0x15b2, 0xc000a71354, 0x0, 0xc0003fa5a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/sys_darwin.go:74 +0x2e
syscall.wait4(0x15b2, 0xc000a71354, 0x0, 0xc0003fa5a0, 0x90, 0x4fc1700, 0x1)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:44 +0x87
syscall.Wait4(0x15b2, 0xc000a713a4, 0x0, 0xc0003fa5a0, 0x203000, 0x0, 0xc000a71438)
	/usr/local/go/src/syscall/syscall_bsd.go:129 +0x51
os.(*Process).wait(0xc000584270, 0x5050308, 0x5050310, 0x5050300)
	/usr/local/go/src/os/exec_unix.go:38 +0x7b
os.(*Process).Wait(...)
	/usr/local/go/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc000972160, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:502 +0x60
os/exec.(*Cmd).Run(0xc000972160, 0xc00027faa0, 0x0)
	/usr/local/go/src/os/exec/exec.go:340 +0x5c
os/exec.(*Cmd).CombinedOutput(0xc000972160, 0x13, 0x0, 0x0, 0x28, 0xc0004f0500)
	/usr/local/go/src/os/exec/exec.go:562 +0x91
github.com/pulumi/pulumi/pkg/v2/testing/integration.RunCommand(0xc000248c60, 0x5001a85, 0x11, 0xc00004c040, 0x4, 0x4, 0xc0007247d0, 0x42, 0xc000298200, 0x0, ...)
	/Users/hooman/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.0.0/testing/integration/command.go:73 +0xdff
github.com/pulumi/pulumi/pkg/v2/testing/integration.(*ProgramTester).runCommand(...)
	/Users/hooman/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.0.0/testing/integration/program.go:717
github.com/pulumi/pulumi/pkg/v2/testing/integration.(*ProgramTester).runPulumiCommand.func1(0x0, 0x8f0d180, 0x3, 0xc000a719c8, 0x4c9f4d7, 0x4d85160, 0xc00004c050)
	/Users/hooman/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.0.0/testing/integration/program.go:760 +0xb0
github.com/pulumi/pulumi/sdk/v2/go/common/util/retry.Until(0x530ab40, 0xc000210008, 0xc000a71aa0, 0x0, 0x0, 0x0, 0x4, 0x0, 0x0, 0x1, ...)
	/Users/hooman/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.0/go/common/util/retry/until.go:74 +0xcf
github.com/pulumi/pulumi/pkg/v2/testing/integration.(*ProgramTester).runPulumiCommand(0xc0005ea5a0, 0x5001a85, 0x11, 0xc000a71c90, 0x3, 0x3, 0xc0007247d0, 0x42, 0x0, 0x0, ...)
	/Users/hooman/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.0.0/testing/integration/program.go:758 +0x25c
github.com/pulumi/pulumi/pkg/v2/testing/integration.(*ProgramTester).TestLifeCycleInitialize(0xc0005ea5a0, 0xc0007247d0, 0x42)
	/Users/hooman/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.0.0/testing/integration/program.go:1005 +0x4d6
github.com/pulumi/pulumi/pkg/v2/testing/integration.(*ProgramTester).TestLifeCycleInitAndDestroy(0xc0005ea5a0, 0x0, 0x0)
	/Users/hooman/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.0.0/testing/integration/program.go:904 +0xf0
github.com/pulumi/pulumi/pkg/v2/testing/integration.ProgramTest(0xc000248c60, 0xc000298200)
	/Users/hooman/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.0.0/testing/integration/program.go:603 +0x5f
pulumi/integration_tests.TestExamples(0xc000248c60)
	/Users/hooman/infra/resources/tests/integration_test.go:19 +0x1cb
testing.tRunner(0xc000248c60, 0x5050348)
	/usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x357
goroutine 11 [chan receive, 10 minutes]:
testing.runTests.func1.1(0xc000248b40)
	/usr/local/go/src/testing/testing.go:1290 +0x3b
created by testing.runTests.func1
	/usr/local/go/src/testing/testing.go:1290 +0xac
goroutine 52 [sleep]:
time.Sleep(0x1bf08eb000)
	/usr/local/go/src/runtime/time.go:198 +0xba
github.com/pulumi/pulumi/pkg/v2/testing/integration.RunCommand.func2(0xc0005f204a, 0xc000298200, 0xc0005840f0, 0x28, 0xc0007247d0, 0x42)
	/Users/hooman/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.0.0/testing/integration/command.go:42 +0x42
created by github.com/pulumi/pulumi/pkg/v2/testing/integration.RunCommand
	/Users/hooman/go/pkg/mod/github.com/pulumi/pulumi/pkg/v2@v2.0.0/testing/integration/command.go:40 +0x234
goroutine 53 [IO wait]:
internal/poll.runtime_pollWait(0x6759e38, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0001a02b8, 0x72, 0x301, 0x32c, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001a02a0, 0xc0005c2ad4, 0x32c, 0x32c, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x201
os.(*File).read(...)
	/usr/local/go/src/os/file_unix.go:263
os.(*File).Read(0xc000010028, 0xc0005c2ad4, 0x32c, 0x32c, 0x1c, 0x0, 0x0)
	/usr/local/go/src/os/file.go:116 +0x71
bytes.(*Buffer).ReadFrom(0xc00027faa0, 0x52e88a0, 0xc000010028, 0xe68a4c0, 0xc00027faa0, 0x1)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
io.copyBuffer(0x52e52a0, 0xc00027faa0, 0x52e88a0, 0xc000010028, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:391 +0x2fc
io.Copy(...)
	/usr/local/go/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:310 +0x63
os/exec.(*Cmd).Start.func1(0xc000972160, 0xc00049a200)
	/usr/local/go/src/os/exec/exec.go:436 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:435 +0x608
exit status 2
FAIL	pulumi/integration_tests	601.530s
```
Additional note : Without the StackName prop in the test , pulumi creates a new stack , which obviously will not have the configuration the program requires and that fails too.

Expected : Integration test should pick the dev.yaml config to test the program ,
Actual : Test times out after 600s

**Comment by leezen** [comment]
With `StackName` the framework is still going to attempt to create a new stack with that name. You cannot pass in the set of configuration values to the integration testing framework via a pre-existing stack. This is by design. Part of the integration test is to create a stack and eventually destroy (and remove) it. Generally, these tests aren't meant to be stateful in any way.

Instead, you'll want to do this via the `Config` parameter for the test.

**Comment by hemantgs** [comment]
@leezen Thanks for clearing that up , how would one pass objects/nested objects as part of the Config parameter ? as it takes a Map of strings only .. an example would be of help

**Comment by leezen** [comment]
You can use `OrderedConfig` which is `[]ConfigValue`
```
type ConfigValue struct {
	// The config key to pass to `pulumi config`.
	Key string
	// The config value to pass to `pulumi config`.
	Value string
	// Secret indicates that the `--secret` flag should be specified when calling `pulumi config`.
	Secret bool
	// Path indicates that the `--path` flag should be specified when calling `pulumi config`.
	Path bool
}
```

And so you would set `Path` to `true` and have the `Key` be a path-based key per https://www.pulumi.com/docs/intro/concepts/config/#structured-configuration

It's a bit awkward, so if you wanted an alternative mechanism, we'd be happy to review a PR for modifying the way the framework itself works.

**Comment by hemantgs** [comment]
@leezen Yeah []ConfigValue is way too much work , 
But for the benefit of others @mikhailshilkov mentioned in slack that nested objects can be Stringified and sent as `Config :map[string] string`, with a bit of tinkering it works, 
A bit more documentation around these points would do a lot of good
Thanks guys
