### ISSUE TITLE
Fatal error on update command.

### ISSUE THREAD

**Issue by jpmckearin** [pulumi/pulumi#4565]
I ran `pulumi update`, the preview generated, and the CLI bombed after `Do you want to perform this update?` without actually presenting the options. See details below.

```
Pulumi Version:   v2.1.0
Go Version:       go1.14.2
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: index out of range [-1]

goroutine 1 [running]:
runtime/debug.Stack(0xc001de2280, 0x5273be0, 0xc002990820)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
	/private/tmp/pulumi-20200429-927-1lpixm7/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x6e
panic(0x5273be0, 0xc002990820)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
gopkg.in/AlecAivazis/survey%2ev1.(*Select).OnChange(0xc0014ba820, 0x0, 0x0, 0x0, 0x0, 0x10, 0x631bf08, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200429-927-1lpixm7/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/select.go:154 +0x6ad
gopkg.in/AlecAivazis/survey%2ev1.(*Select).Prompt(0xc0014ba820, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20200429-927-1lpixm7/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/select.go:234 +0x3b4
gopkg.in/AlecAivazis/survey%2ev1.Ask(0xc001de2970, 0x1, 0x1, 0x5030020, 0xc000a7dcc0, 0x0, 0x0, 0x0, 0xc000010018, 0xc001de2998)
	/private/tmp/pulumi-20200429-927-1lpixm7/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/survey.go:148 +0x187
gopkg.in/AlecAivazis/survey%2ev1.AskOne(0x57009a0, 0xc0014ba820, 0x5030020, 0xc000a7dcc0, 0x0, 0x0, 0x0, 0x0, 0x42, 0x0)
	/private/tmp/pulumi-20200429-927-1lpixm7/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/survey.go:94 +0xeb
github.com/pulumi/pulumi/pkg/v2/backend.confirmBeforeUpdating(0x5354da3, 0x6, 0x5723040, 0xc0005e8c80, 0xc0019d8000, 0x189, 0x200, 0x631bf08, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200429-927-1lpixm7/src/github.com/pulumi/pulumi/pkg/backend/apply.go:168 +0x43c
github.com/pulumi/pulumi/pkg/v2/backend.PreviewThenPrompt(0x5709aa0, 0xc0000440a0, 0x5354da3, 0x6, 0x5723040, 0xc0005e8c80, 0xc0005e8d00, 0xc000ab5140, 0x2e, 0xc000ab9020, ...)
	/private/tmp/pulumi-20200429-927-1lpixm7/src/github.com/pulumi/pulumi/pkg/backend/apply.go:127 +0x24d
github.com/pulumi/pulumi/pkg/v2/backend.PreviewThenPromptThenExecute(0x5709aa0, 0xc0000440a0, 0x5354da3, 0x6, 0x5723040, 0xc0005e8c80, 0xc0005e8d00, 0xc000ab5140, 0x2e, 0xc000ab9020, ...)
	/private/tmp/pulumi-20200429-927-1lpixm7/src/github.com/pulumi/pulumi/pkg/backend/apply.go:199 +0x1ac
github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudBackend).Update(0xc0004a4db0, 0x5709aa0, 0xc0000440a0, 0x5723040, 0xc0005e8c80, 0xc0005e8d00, 0xc000ab5140, 0x2e, 0xc000ab9020, 0x631bf08, ...)
	/private/tmp/pulumi-20200429-927-1lpixm7/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:812 +0xe6
github.com/pulumi/pulumi/pkg/v2/backend.UpdateStack(0x5709aa0, 0xc0000440a0, 0x5723040, 0xc0005e8c80, 0xc0005e8d00, 0xc000ab5140, 0x2e, 0xc000ab9020, 0x631bf08, 0x0, ...)
	/private/tmp/pulumi-20200429-927-1lpixm7/src/github.com/pulumi/pulumi/pkg/backend/stack.go:82 +0xc4
github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudStack).Update(0xc0005e8c80, 0x5709aa0, 0xc0000440a0, 0xc0005e8d00, 0xc000ab5140, 0x2e, 0xc000ab9020, 0x631bf08, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200429-927-1lpixm7/src/github.com/pulumi/pulumi/pkg/backend/httpstate/stack.go:148 +0x96
main.newUpCmd.func1(0x631bf08, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, 0x631bf08, 0x0, ...)
	/private/tmp/pulumi-20200429-927-1lpixm7/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/up.go:133 +0xb0d
main.newUpCmd.func3(0xc000245b80, 0x631bf08, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20200429-927-1lpixm7/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/up.go:370 +0x4ba
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc000245b80, 0x631bf08, 0x0, 0x0)
	/private/tmp/pulumi-20200429-927-1lpixm7/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000245b80, 0x631bf08, 0x0, 0x0, 0xc000245b80, 0x631bf08)
	/private/tmp/pulumi-20200429-927-1lpixm7/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000244580, 0x15, 0x0, 0x0)
	/private/tmp/pulumi-20200429-927-1lpixm7/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/pulumi-20200429-927-1lpixm7/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
main.main()
	/private/tmp/pulumi-20200429-927-1lpixm7/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x4d
```

**Comment by leezen** [comment]
Was your command run purely as `pulumi update` with no other flags?

**Comment by JabbarFagan** [comment]
I received a similar (same?) fatal error last night. I'll file a report per Pulumi request.

**Comment by stack72** [comment]
Hi @jpmckearin 

My apologies for us not getting back to this specific issue earlier. We upgraded the library that presents our yes / no / details survey in Pulumi v2.5.0 and thus fixed this specific panic

Paul
