### ISSUE TITLE
pulumi stack delete a S3 bucket fails

### ISSUE THREAD

**Issue by AmirMoniri** [pulumi/pulumi#4750]
**What I did**
Basically, I tried to execute the following command within my bash:
`pulumi state delete s3-BUCKET_NAME`

Keep in mind that I used the full name of my AWS S3 bucket.

**Detailed error message:**
```
Pulumi Version:   v2.3.0
Go Version:       go1.14.3
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: A precondition has failed for snap

goroutine 1 [running]:
runtime/debug.Stack(0xc0005bf4d8, 0x506f9e0, 0xc000188f30)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
	/private/tmp/pulumi-20200601-1681-dmhv4k/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x6e
panic(0x506f9e0, 0xc000188f30)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:969 +0x166
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20200601-1681-dmhv4k/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Require(0x0, 0x5360d94, 0x4)
	/private/tmp/pulumi-20200601-1681-dmhv4k/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/require.go:26 +0x13c
github.com/pulumi/pulumi/pkg/v2/resource/edit.LocateResource(0x0, 0x7ffeefbffbf4, 0x2f, 0x505d8e0, 0xc000692cac, 0x181)
	/private/tmp/pulumi-20200601-1681-dmhv4k/src/github.com/pulumi/pulumi/pkg/resource/edit/operations.go:84 +0x4a
main.locateStackResource(0x536294c, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeefbffbf4, ...)
	/private/tmp/pulumi-20200601-1681-dmhv4k/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state.go:59 +0x5d
main.runStateEdit.func1(0x536294c, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200601-1681-dmhv4k/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state.go:118 +0x81
main.runTotalStateEdit(0x0, 0x0, 0xc0005bfb01, 0xc0005bfba0, 0x4f4c491, 0x0)
	/private/tmp/pulumi-20200601-1681-dmhv4k/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state.go:164 +0x254
main.runStateEdit(0x0, 0x0, 0xc000180501, 0x7ffeefbffbf4, 0x2f, 0xc0005bfc88, 0xc00018a290, 0xc00016d500)
	/private/tmp/pulumi-20200601-1681-dmhv4k/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state.go:117 +0x89
main.newStateDeleteCommand.func1(0xc000616580, 0xc00007b3f0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/pulumi-20200601-1681-dmhv4k/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state_delete.go:58 +0xc0
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc000616580, 0xc00007b3f0, 0x1, 0x1)
	/private/tmp/pulumi-20200601-1681-dmhv4k/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000616580, 0xc00007b3c0, 0x1, 0x1, 0xc000616580, 0xc00007b3c0)
	/private/tmp/pulumi-20200601-1681-dmhv4k/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000224580, 0x15, 0x0, 0x0)
	/private/tmp/pulumi-20200601-1681-dmhv4k/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/pulumi-20200601-1681-dmhv4k/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/private/tmp/pulumi-20200601-1681-dmhv4k/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x4d
```

**Comment by leezen** [comment]
I wouldn't expect it to fail like that, but `pulumi state delete` expects the URN of the resource. If you pass that in, does this succeed?

**Comment by AmirMoniri** [comment]
I went to the AWS management console, copied the s3 buckets name and passed it in.
After that, the above error occurs.

When I create a new bucket and then execute `pulumi state delete` it says
`error: No such resource "s3-..." exists in the current state`

But maybe I'm doing something wrong here?

**Comment by leezen** [comment]
Yes, as I mentioned, you need to pass in the URN and not the bucket name. You can get the URNs of the resources in your stack by executing `pulumi stack -u`
