### ISSUE TITLE
CLI crash

### ISSUE THREAD

**Issue by gwatts** [pulumi/pulumi#4859]
Had a crash while running `pulumi up` while waiting for the prompt to appear; only happened the once so far; think i hit some keyboard input while it was running prior to the prompt appearing.

```
Resources:
    ~ 1 to update
    54 unchanged

Do you want to perform this update? did  [Use arrows to move, enter to select, type to filter]
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v2.4.0
Go Version:       go1.14.3
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: index out of range [-1]

goroutine 1 [running]:
runtime/debug.Stack(0xc001a78278, 0x5287940, 0xc0007aaf00)
        /usr/local/Cellar/go/1.14.3/libexec/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
        /private/tmp/pulumi-20200610-52205-1g5l7pb/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x6e
panic(0x5287940, 0xc0007aaf00)
        /usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:969 +0x166
gopkg.in/AlecAivazis/survey%2ev1.(*Select).OnChange(0xc0024f41a0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x6336fe8, 0x0, 0x0, 0x0, ...)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/select.go:154 +0x6ad
gopkg.in/AlecAivazis/survey%2ev1.(*Select).Prompt(0xc0024f41a0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/select.go:234 +0x3b4
gopkg.in/AlecAivazis/survey%2ev1.Ask(0xc001a78968, 0x1, 0x1, 0x503f8a0, 0xc0004afbe0, 0x0, 0x0, 0x0, 0xc000196008, 0xc001a78990)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/survey.go:148 +0x187
gopkg.in/AlecAivazis/survey%2ev1.AskOne(0x5718f80, 0xc0024f41a0, 0x503f8a0, 0xc0004afbe0, 0x0, 0x0, 0x0, 0x0, 0x42, 0x0)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/survey.go:94 +0xeb
github.com/pulumi/pulumi/pkg/v2/backend.confirmBeforeUpdating(0x5365790, 0x6, 0x573b7e0, 0xc00015e080, 0xc001b00000, 0x7b, 0x80, 0x6336fe8, 0x0, 0x0, ...)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/src/github.com/pulumi/pulumi/pkg/backend/apply.go:168 +0x43c
github.com/pulumi/pulumi/pkg/v2/backend.PreviewThenPrompt(0x5722040, 0xc00019c008, 0x5365790, 0x6, 0x573b7e0, 0xc00015e080, 0xc00015e100, 0xc00113a5a0, 0x35, 0xc0011322a0, ...)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/src/github.com/pulumi/pulumi/pkg/backend/apply.go:127 +0x24d
github.com/pulumi/pulumi/pkg/v2/backend.PreviewThenPromptThenExecute(0x5722040, 0xc00019c008, 0x5365790, 0x6, 0x573b7e0, 0xc00015e080, 0xc00015e100, 0xc00113a5a0, 0x35, 0xc0011322a0, ...)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/src/github.com/pulumi/pulumi/pkg/backend/apply.go:199 +0x1ac
github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudBackend).Update(0xc0006d4600, 0x5722040, 0xc00019c008, 0x573b7e0, 0xc00015e080, 0xc00015e100, 0xc00113a5a0, 0x35, 0xc0011322a0, 0x6336fe8, ...)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:812 +0xe6
github.com/pulumi/pulumi/pkg/v2/backend.UpdateStack(0x5722040, 0xc00019c008, 0x573b7e0, 0xc00015e080, 0xc00015e100, 0xc00113a5a0, 0x35, 0xc0011322a0, 0x6336fe8, 0x0, ...)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/src/github.com/pulumi/pulumi/pkg/backend/stack.go:82 +0xc4
github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudStack).Update(0xc00015e080, 0x5722040, 0xc00019c008, 0xc00015e100, 0xc00113a5a0, 0x35, 0xc0011322a0, 0x6336fe8, 0x0, 0x0, ...)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/src/github.com/pulumi/pulumi/pkg/backend/httpstate/stack.go:148 +0x96
main.newUpCmd.func1(0x6336fe8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, 0x6336fe8, 0x0, ...)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/up.go:133 +0xb0d
main.newUpCmd.func3(0xc000335340, 0x6336fe8, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/up.go:372 +0x4e1
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc000335340, 0x6336fe8, 0x0, 0x0)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000335340, 0x6336fe8, 0x0, 0x0, 0xc000335340, 0x6336fe8)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000334dc0, 0x15, 0x0, 0x0)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /private/tmp/pulumi-20200610-52205-1g5l7pb/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /private/tmp/pulumi-20200610-52205-1g5l7pb/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x4d

```

**Comment by stack72** [comment]
Closing this out as this was actually fixed in #4808 and released in v2.5.0

Sorry we didn't close this before!
