### ISSUE TITLE
Vanilla Python program fails with error from grpcio library

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#4881]
### What did you do?

The problem happens when creating a vanilla Python program:

```
$ mkdir emptypytest && cd emptypytest
$ pulumi new python

...

Successfully installed dill-0.3.2 grpcio-1.30.0 protobuf-3.12.2 pulumi-2.4.0 six-1.15.0
Finished installing dependencies

Your new project is ready to go! ✨

To perform an initial deployment, run 'pulumi up'
```

### What did you expect to see?

```
$ pulumi up

Previewing update (dev):
     Type                 Name             Plan       
 +   pulumi:pulumi:Stack  emptypytest-dev  create     
 
Resources:
    + 1 to create
```

### What did you see instead?

```
$ pulumi up

Previewing update (dev):
     Type                 Name             Plan       Info
 +   pulumi:pulumi:Stack  emptypytest-dev  create     8 messages
 
Diagnostics:
  pulumi:pulumi:Stack (emptypytest-dev):
    Exception ignored in: <function _ChannelCallState.__del__ at 0x1062d8290>
    Traceback (most recent call last):
      File "/Users/user/Desktop/emptypytest/venv/lib/python3.7/site-packages/grpc/_channel.py", line 1126, in __del__
    AttributeError: 'NoneType' object has no attribute 'cancelled'
    Exception ignored in: <function _ChannelCallState.__del__ at 0x1062d8290>
    Traceback (most recent call last):
      File "/Users/user/Desktop/emptypytest/venv/lib/python3.7/site-packages/grpc/_channel.py", line 1126, in __del__
    AttributeError: 'NoneType' object has no attribute 'cancelled'
```

After downgrading and pinning to grpcio 1.29.0, the error no longer happens:

```
$ venv/bin/pip uninstall grpcio
$ venv/bin/pip install grpcio==1.29.0
$ pulumi up

Previewing update (dev):
     Type                 Name             Plan       
 +   pulumi:pulumi:Stack  emptypytest-dev  create     
 
Resources:
    + 1 to create
```

**Comment by justinvp** [comment]
Opened https://github.com/grpc/grpc/issues/23290
