### ISSUE TITLE
asyncio/base_events.py", line 475, in _check_closed raise RuntimeError('Event loop is closed')

### ISSUE THREAD

**Issue by a5a5a9** [pulumi/pulumi#4917]
ypeError: __init__() got an unexpected keyword argument 'status'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
 
    exception calling callback for <Future at 0x7feedb7d9490 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 728, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
    exception calling callback for <Future at 0x7feed9d267d0 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 728, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
    exception calling callback for <Future at 0x7feed9b2b650 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 728, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
    exception calling callback for <Future at 0x7feed9d5c490 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 728, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
    exception calling callback for <Future at 0x7feed9d26890 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 728, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
    exception calling callback for <Future at 0x7feed9d5cc90 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 728, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
    exception calling callback for <Future at 0x7feed9d5cad0 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 728, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
    exception calling callback for <Future at 0x7feed984c490 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 728, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
    exception calling callback for <Future at 0x7feed98e6d50 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
      File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 728, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed

**Comment by leezen** [comment]
It'd be helpful if you could please provide more details on what you were doing that caused this error? Could you please share the code you executed and what pulumi command you ran? Also, what does your `requirements.txt` look like? Thanks!

**Comment by a5a5a9** [comment]
I installed a different version of grpcio
