### ISSUE TITLE
pulimi up fails with "Error retrieving running Azure CLI: Unable to encode the output with cp1252 encoding"

### ISSUE THREAD

**Issue by henriksen** [pulumi/pulumi#4951]
When running `pulumi up` I get the following error
```
  pulumi:pulumi:Stack (website):
    error: preview failed
    error: Running program 'C:\dev\website\pulumi' failed with an unhandled exception:
    Error: invocation of azure:appinsights/getInsights:getInsights returned an error: Error building account: Error getting authenticated object ID: Error parsing json result from the Azure CLI: Error retrieving running Azure CLI: Unable to encode the output with cp1252 encoding. Unsupported characters are discarded.
        at C:\dev\website\pulumi\node_modules\@pulumi\pulumi\runtime\invoke.js:136:33
        at Http2CallStream.<anonymous> (C:\dev\website\pulumi\node_modules\@grpc\grpc-js\src\client.ts:155:9)
        at Http2CallStream.emit (events.js:327:22)
        at C:\dev\website\pulumi\node_modules\@grpc\grpc-js\src\call-stream.ts:186:14
        at processTicksAndRejections (internal/process/task_queues.js:79:11)

  azure:core:ResourceGroup (dev):
    error: Preview failed: Error building account: Error getting authenticated object ID: Error parsing json result from the Azure CLI: Error retrieving running Azure CLI: Unable to encode the output with cp1252 encoding. Unsupported characters are discarded.
```
Last one repeated for every resource. 

Trying things from #4342 does not help. 

Changing the code page does not help
```
> chcp
Active code page: 850

> chcp 65001
Active code page: 65001
```

Setting my region to US does not work:
![image](https://user-images.githubusercontent.com/121837/86246075-b55fa480-bbaa-11ea-8240-ab73c7480aa9.png)

Display language is set to English (United States):
![image](https://user-images.githubusercontent.com/121837/86357424-1a300300-bc6e-11ea-8843-dd4990e161e7.png)

```
> Get-WinSystemLocale

LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)
```

`az account get-access-token` works fine and gives me a token. No non-ascii chars in the `get-access-token` response or in the decoded token.

Versions:
```
> pulumi version
v2.5.0

> az --version
azure-cli                          2.6.0 *

command-modules-nspkg              2.0.3
core                               2.6.0 *
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\henriksen\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

> systeminfo

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363
```

**Comment by gergo512** [comment]
I just spent a few hours trying to get it to work... and I found this: [https://github.com/terraform-providers/terraform-provider-azurerm/issues/5694#issuecomment-585949039](url); in the root directory there should be a directory called `.azure` - I removed it, restarted my computer, did a fresh `az login` and now I don't get this error when executing e.g. `terraform plan`.

**Comment by gergo512** [comment]
This helped me: [https://github.com/terraform-providers/terraform-provider-azurerm/issues/5694#issuecomment-585949039](url); delete the `.azure` directory in the root directory, then retry.

**Comment by skurik** [comment]
@henriksen Were you able to work around this?

**Comment by marius-klimantavicius** [comment]
Not OP but deleting `.azure` does not help (I am on Windows 10). 

I could only make it work if I generated a service account and used that for credentials.
Might be related to https://github.com/Azure/azure-cli/issues/14426 (which is not fixed and seems to be closed as a windows issue but it does provide more possible workarounds).

**Comment by skurik** [comment]
Yeah, ended up doing the same. Using service principal works.

**Comment by henriksen** [comment]
@skurik No, I still have that problem on Windows. I'm now using Pulumi via WSL. Not ideal, but at least it works. 

From looking at Azure/azure-cli#14426, I went though my service principals and found a few that had a Unicode value, including the Pulumi App Console:

![image](https://user-images.githubusercontent.com/121837/99086315-a1e92f00-25c9-11eb-945e-4ef17a014bc6.png)

**Comment by marius-klimantavicius** [comment]
One more work-around: disable all warnings from Azure CLI by:
`az config set core.only_show_errors=true`
A better workaround probably would be to use `--only-show-errors` in the provider.
