### ISSUE TITLE
Python: AttributeError: 'list' object has no attribute '_transformations'

### ISSUE THREAD

**Issue by asnowfix** [pulumi/pulumi#4966]
### Description

When trying to setup a parent/child relationships between 2 Azure objects (namely put a dependency from an ARecord onto its hosting PrivateDNSZone), it seems like Pulumi examins the parent object w/o checking wether attributes exist at first (JavaScript type of falsy-checking), which causes Python to crash:

### Environment

* Pulumi 2.5.0 downloaded manually from https://www.pulumi.com/docs/get-started/install/versions/
* macOS Mojave 10.14.6

### Source Code

```python
    forwarderZone = ".".join([resource_group.tags["dns-zone"] if "dns-zone" in resource_group.tags else "ns", forwardingZone])

    zone = privatedns.Zone(env,
        name=                   forwarderZone,
        resource_group_name=    resource_group.name,
       # BUG: Non-working attempt to work-around the issue
        # opts=                   ResourceOptions(transformations=[]),
    )


    # Register the load-balander IP's
    # https://www.pulumi.com/docs/reference/pkg/azure/privatedns/arecord/
    arecord = privatedns.ARecord(env + "-forwarder",
        records=                configForwarder['network']['ip'],
        resource_group_name=    resource_group.name,
        ttl=                    300,
        zone_name=              forwarderZone,
        name=                   "forwarder",
        # https://www.pulumi.com/docs/intro/concepts/programming-model/#resourceoptions
        # BUG: ResourceOptions(parent) checks for parent._transformations
        # BUG: w/o checking its existing first (JavaScript-like)
        # opts=                   ResourceOptions(parent=[zone])
    )
```

### Full backtrace

```
Previewing update (hdns-netadm):
     Type                      Name              Plan        Info
     pulumi:pulumi:Stack       hdns-hdns-netadm              3 errors; 2 messages
 +-  └─ azure:privatedns:Zone  hdns-netadm       replace     [diff: ~name]
 
Diagnostics:
  pulumi:pulumi:Stack (hdns-hdns-netadm):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/Users/fkowalski/pulumi-v2.5.0/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
        return future.result()
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 81, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 34, in run_pulumi_func
        func()
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 81, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 104, in __init__
        func()
      File "/Users/fkowalski/pulumi-v2.5.0/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 8, in <module>
        getattr(imported_module,'iacRun')()
      File "./hdns.py", line 494, in iacRun
        opts=                   ResourceOptions(depends_on=[zone], parent=[zone])
      File "/usr/local/lib/python3.7/site-packages/pulumi_azure/privatedns/a_record.py", line 102, in __init__
        opts)
      File "/usr/local/lib/python3.7/site-packages/pulumi/resource.py", line 803, in __init__
        Resource.__init__(self, t, name, True, props, opts)
      File "/usr/local/lib/python3.7/site-packages/pulumi/resource.py", line 629, in __init__
        parent_transformations = (parent._transformations or []) if parent is not None else []
    AttributeError: 'list' object has no attribute '_transformations'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
 
    forwardingZone=netadm.westeurope.azr.amadeus.net
    forwarderZone=ns.netadm.westeurope.azr.amadeus.net
 ```

**Comment by asnowfix** [comment]
BTW, I am trying to put in place that parent/child relationship because the ARecords to not have an ID (which would by a pulumi.Output) to state their dependency on their hosting PrivateDNS Zone.  However, there is still a dependency, as it is not possible to update a Private DNS Zone without flushing its records.

Main error: 

```
Original Error: autorest/azure: Service returned an error. Status=<nil> Code="CannotDeleteResource" Message="Can not delete resource before nested resources are deleted."
```

...and note that -- despite this error -- Pulumi considers execution as successful, although the underlying provider (Azure) considers the operation unsuccessful. This behaviour is in itself a bug, I presume.

## Full Log

```
Previewing update (hdns-netadm):
     Type                                        Name                   Plan        Info
     pulumi:pulumi:Stack                         hdns-hdns-netadm                   2 messages
 +-  ├─ azure:privatedns:Zone                    hdns-netadm            replace     [diff: ~name]
 ~   ├─ azure:privatedns:ARecord                 hdns-netadm-forwarder  update      [diff: ~zoneName]
 +-  ├─ azure:privatedns:ZoneVirtualNetworkLink  hdns-netadm            replace     [diff: ~privateDnsZoneName]
 ~   └─ azure:compute:Extension                  hdns-netadm            update      [diff: ~protectedSettings]
 
Diagnostics:
  pulumi:pulumi:Stack (hdns-hdns-netadm):
    forwardingZone=netadm.westeurope.azr.example.net
    forwarderZone=ns.netadm.westeurope.azr.example.net
 
Outputs:
  ~ zone: "netad.westeurope.azr.example.net" => "netadm.westeurope.azr.example.net"


Updating (hdns-netadm):
     Type                        Name              Status                   Info
     pulumi:pulumi:Stack         hdns-hdns-netadm  **failed**               1 error
 +-  ├─ azure:privatedns:Zone    hdns-netadm       **replacing failed**     1 error
 ~   └─ azure:compute:Extension  hdns-netadm       updated                  [diff: ~protectedSettings]
 
Diagnostics:
  pulumi:pulumi:Stack (hdns-hdns-netadm):
    error: update failed
 
  azure:privatedns:Zone (hdns-netadm):
    error: deleting urn:pulumi:hdns-netadm::hdns::azure:privatedns/zone:Zone::hdns-netadm: error deleting Private DNS Zone netadm.westeurope.azr.amadeus.net (resource group rg-dns): privatedns.PrivateZonesClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="CannotDeleteResource" Message="Can not delete resource before nested resources are deleted."
 
Outputs:
    ip  : [
        [0]: "10.48.130.62"
    ]
  ~ zone: "netad.westeurope.azr.example.net" => "netadm.westeurope.azr.example.net"

Resources:
    ~ 1 updated
    11 unchanged

Duration: 1m15s
```

**Comment by komalali** [comment]
@asnowfix The original error that this issue is opened for is because `parent` expects a resource, i.e. `ResourceOptions(parent=zone)`, while you have provided a list of (1) resources i.e. `ResourceOptions(parent=[zone])`

**Comment by komalali** [comment]
> ...and note that -- despite this error -- Pulumi considers execution as successful

Can you explain what you mean by this? From the log it looks to me that pulumi does not consider this execution successful (because it returns an error and fails to update the stack).

**Comment by komalali** [comment]
I'm going to close this issue out since we haven't heard back but please feel free to reopen if your issue isn't resolved.
