### ISSUE TITLE
[PANIC] Pulumi v2.6.0 on destroy panics

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#4986]
On upgrading from v2.5.0 to v2.6.0 of Pulumi, the CLI panics when trying to destroy any resources:

```
▶ pulumi destroy
Previewing destroy (dev):
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4c245bb]

goroutine 25 [running]:
github.com/pulumi/pulumi/pkg/v2/backend/display.(*resourceRowData).ColorizedColumns(0xc0009460e0, 0xc0012c5650, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/rows.go:289 +0x6b
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).getOrCreateTreeNode(0xc0000f8f20, 0xc0012c5638, 0x0, 0x0, 0x5740920, 0xc0009460e0, 0xc0012c5650, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:425 +0x96
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).getOrCreateTreeNode(0xc0000f8f20, 0xc0012c5638, 0xc0009100f0, 0x49, 0x5740920, 0xc000946000, 0xc0012c5650, 0x1)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:450 +0x407
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).generateTreeNodes(0xc0000f8f20, 0xc000921200, 0x10, 0xc00092e420)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:469 +0x21f
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).refreshAllRowsIfInTerminal(0xc0000f8f20)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:580 +0x6f
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).processNormalEvent(0xc0000f8f20, 0x536c85c, 0xc, 0x51f91c0, 0xc0009dd980)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:1085 +0x448
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).processEvents(0xc0000f8f20, 0xc000618050, 0xc00010b020)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:1153 +0x136
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowProgressEvents.func1(0xc0000f8f20, 0xc000618050, 0xc00010b020, 0xc0000ff7a0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:286 +0x3f
created by github.com/pulumi/pulumi/pkg/v2/backend/display.ShowProgressEvents
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:285 +0x415
```

**Comment by cybermaggedon** [comment]
Seeing the same stack trace...
```
[user@localhost evs-pulumi2]$ pulumi up
Previewing update (soc00):
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1026d7b]

goroutine 22 [running]:
github.com/pulumi/pulumi/pkg/v2/backend/display.(*resourceRowData).ColorizedColumns(0xc00157e1c0, 0xc001a61650, 0x0, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/rows.go:289 +0x6b
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).getOrCreateTreeNode(0xc00142c000, 0xc001a61638, 0x0, 0x0, 0x1b3d7a0, 0xc00157e1c0, 0xc001a61650, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:425 +0x96
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).getOrCreateTreeNode(0xc00142c000, 0xc001a61638, 0xc000672a80, 0x40, 0x1b3d7a0, 0xc00157e0e0, 0xc001a61650, 0x1)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:450 +0x407
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).generateTreeNodes(0xc00142c000, 0xc000672a80, 0x40, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:469 +0x21f
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).refreshAllRowsIfInTerminal(0xc00142c000)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:580 +0x6f
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).processNormalEvent(0xc00142c000, 0x175f613, 0x4, 0x16b3fe0, 0xc001a94720)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:1085 +0x448
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).processEvents(0xc00142c000, 0xc0005c4000, 0xc000249200)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:1153 +0x136
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowProgressEvents.func1(0xc00142c000, 0xc0005c4000, 0xc000249200, 0xc00018e5a0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:286 +0x3f
created by github.com/pulumi/pulumi/pkg/v2/backend/display.ShowProgressEvents
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:285 +0x415
```
In this case, it was due to delete and re-create some resource as a result of a name change.  Works fine with 2.5.0.

**Comment by fracek** [comment]
I have the same issue running `pulumi refresh`

```
$ pulumi refresh --yes -p 3
Previewing refresh (snip):
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1026d7b]

goroutine 90 [running]:
github.com/pulumi/pulumi/pkg/v2/backend/display.(*resourceRowData).ColorizedColumns(0xc0008715e0, 0xc0013c9650, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/rows.go:289 +0x6b
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).getOrCreateTreeNode(0xc00069a6e0, 0xc0013c9638, 0x0, 0x0, 0x1b3d7a0, 0xc0008715e0, 0xc0013c9650, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:425 +0x96
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).getOrCreateTreeNode(0xc00069a6e0, 0xc0013c9638, 0xc0005bc070, 0x64, 0x1b3d7a0, 0xc000871420, 0xc0013c9650, 0x1)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:450 +0x407
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).generateTreeNodes(0xc00069a6e0, 0xc001a7c7e0, 0x10, 0xc001abe1a0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:469 +0x21f
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).refreshAllRowsIfInTerminal(0xc00069a6e0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:580 +0x6f
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).processNormalEvent(0xc00069a6e0, 0x176a397, 0xc, 0x15f6e40, 0xc001a92280)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:1085 +0x448
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).processEvents(0xc00069a6e0, 0xc000a804b0, 0xc0005fe3c0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:1153 +0x136
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowProgressEvents.func1(0xc00069a6e0, 0xc000a804b0, 0xc0005fe3c0, 0xc00010f320)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:286 +0x3f
created by github.com/pulumi/pulumi/pkg/v2/backend/display.ShowProgressEvents
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:285 +0x415
```

**Comment by stack72** [comment]
We have merged the code that fixes the panic - we will start the release of v2.6.1 shortly to mitigate this problem

Apologies for this 

Paul
