### ISSUE TITLE
GRPC connection between node and pulumi drops unexpectedly

### ISSUE THREAD

**Issue by mleclercq** [pulumi/pulumi#5093]
I have an intermittent error running `pulumi up` or `pulumi preview` since a few days where pulumi exits in the middle of the preview or update somewhat randomly with the following error message:

```
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
 
    The Pulumi runtime detected that <SOME VARYING NUMBER> promises were still active
    at the time that the process exited. There are a few ways that this can occur:
      * Not using `await` or `.then` on a Promise returned from a Pulumi API
      * Introducing a cyclic dependency between two Pulumi Resources
      * A bug in the Pulumi Runtime
    Leaving promises active is probably not what you want. If you are unsure about
    why you are seeing this message, re-run your program with the `PULUMI_DEBUG_PROMISE_LEAKS`
    environment variable. The Pulumi runtime will then print out additional
    debug information about the leaked promises.
```

After investigation, it seems that the GRPC connection from node to pulumi was dropped causing the following code to call `process.exit(0)`:

https://github.com/pulumi/pulumi/blob/06fa515bf796a8def6e0e2b1d8a204f1a7b7922d/sdk/nodejs/runtime/resource.ts#L227

Just before the `process.exit(0)`, I added: 

```
  console.log(`Calling process.exit(0): t=${t}, name=${name}, custom=${custom}\`, label, err);
```

It gives the following output:

```
    Calling process.exit(0): t=gcp:serviceAccount/key:Key, name=maintenance, custom=true resource:maintenance[gcp:serviceAccount/key:Key] Error: 14 UNAVAILABLE: Connection dropped
        at Object.callErrorFromStatus (/Users/matthieu/frisson/infra/node_modules/@grpc/grpc-js/src/call.ts:79:24)
        at Http2CallStream.<anonymous> (/Users/matthieu/frisson/infra/node_modules/@grpc/grpc-js/src/client.ts:155:18)
        at Http2CallStream.emit (events.js:327:22)
        at Http2CallStream.EventEmitter.emit (domain.js:482:12)
        at /Users/matthieu/frisson/infra/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14
        at processTicksAndRejections (internal/process/task_queues.js:79:11) {
      code: 14,
      details: 'Connection dropped',
      metadata: Metadata { internalRepr: Map {}, options: {} }
    }
```

The debug logs do not show any obvious error explaining why the connection is dropped.

Regarding the particular resource on which the error is reported (note that it's not always the same resource), the debug log contains:

```
...
I0802 20:08:29.705713   40314 rpc.go:225] Unmarshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: serviceAccountId={...}
I0802 20:08:29.705738   40314 source_eval.go:837] ResourceMonitor.RegisterResource received: t=gcp:serviceAccount/key:Key, name=maintenance, custom=true, #props=1, parent=urn:pulumi:staging::infra::automat:ns-maintenance::maintenance, protect=false, provider=urn:pulumi:staging::infra::pulumi:providers:gcp::default_3_16_0::26b1b640-4dec-4588-861c-349c76f3a6f9, deps=[urn:pulumi:staging::infra::pulumi:pulumi:StackReference::automat-ai/pulumi-vault/main], deleteBeforeReplace=<nil>, ignoreChanges=[], aliases=[], customTimeouts={0 0 0}
...
I0802 20:08:29.709585   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: id=...
I0802 20:08:29.709599   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: keyAlgorithm=...
I0802 20:08:29.709611   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: name=...
I0802 20:08:29.709642   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: privateKey=...
I0802 20:08:29.709722   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: 4dabf18193072939515e22adb298388d=...
I0802 20:08:29.709736   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: value=...
I0802 20:08:29.709759   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: privateKeyType=...
I0802 20:08:29.709771   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: publicKey=...
I0802 20:08:29.709787   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: publicKeyType=...
I0802 20:08:29.709798   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: serviceAccountId=...
I0802 20:08:29.709809   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: validAfter=...
I0802 20:08:29.709821   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(gcp:serviceAccount/key:Key,maintenance)]: validBefore=...

...
I0802 20:08:29.852425   40314 source_eval.go:879] ResourceMonitor.RegisterResource operation finished: t=aws:route53/record:Record, urn=urn:pulumi:staging::infra::automat:AppCluster$aws:route53/record:Record::app-cluster-wildcard-domain, #outs=8
I0802 20:08:29.852434   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:route53/record:Record,app-cluster-wildcard-domain)]: ...
I0802 20:08:29.852442   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:route53/record:Record,app-cluster-wildcard-domain)]: ...
I0802 20:08:29.852448   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:route53/record:Record,app-cluster-wildcard-domain)]: ...
I0802 20:08:29.852455   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:route53/record:Record,app-cluster-wildcard-domain)]: ...
I0802 20:08:29.852461   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:route53/record:Record,app-cluster-wildcard-domain)]: ...
I0802 20:08:29.852469   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:route53/record:Record,app-cluster-wildcard-domain)]: ...
I0802 20:08:29.852476   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:route53/record:Record,app-cluster-wildcard-domain)]: ...
I0802 20:08:29.852483   40314 rpc.go:71] Marshaling property for RPC[ResourceMonitor.RegisterResource(aws:route53/record:Record,app-cluster-wildcard-domain)]: ...
I0802 20:08:29.877313   40314 eventsink.go:78] eventSink::Infoerr(<{%reset%}>The Pulumi runtime detected that 4363 promises were still active<{%reset%}>)
I0802 20:08:29.877352   40314 eventsink.go:70] eventSink::Info(<{%reset%}>Calling process.exit(0): t=gcp:serviceAccount/key:Key, name=maintenance, custom=true resource:maintenance[gcp:serviceAccount/key:Key] Error: 14 UNAVAILABLE: Connection dropped<{%reset%}>)
I0802 20:08:29.877384   40314 eventsink.go:70] eventSink::Info(<{%reset%}>    at Object.callErrorFromStatus (/Users/matthieu/frisson/infra/node_modules/@grpc/grpc-js/src/call.ts:79:24)<{%reset%}>)
I0802 20:08:29.877404   40314 eventsink.go:70] eventSink::Info(<{%reset%}>    at Http2CallStream.<anonymous> (/Users/matthieu/frisson/infra/node_modules/@grpc/grpc-js/src/client.ts:155:18)<{%reset%}>)
I0802 20:08:29.877361   40314 eventsink.go:78] eventSink::Infoerr(<{%reset%}>at the time that the process exited. There are a few ways that this can occur:<{%reset%}>)
I0802 20:08:29.877422   40314 eventsink.go:70] eventSink::Info(<{%reset%}>    at Http2CallStream.emit (events.js:327:22)<{%reset%}>)
I0802 20:08:29.877433   40314 eventsink.go:78] eventSink::Infoerr(<{%reset%}>  * Not using `await` or `.then` on a Promise returned from a Pulumi API<{%reset%}>)
I0802 20:08:29.877462   40314 eventsink.go:78] eventSink::Infoerr(<{%reset%}>  * Introducing a cyclic dependency between two Pulumi Resources<{%reset%}>)
I0802 20:08:29.877479   40314 eventsink.go:78] eventSink::Infoerr(<{%reset%}>  * A bug in the Pulumi Runtime<{%reset%}>)
I0802 20:08:29.877501   40314 eventsink.go:78] eventSink::Infoerr(<{%reset%}>Leaving promises active is probably not what you want. If you are unsure about<{%reset%}>)
I0802 20:08:29.877519   40314 eventsink.go:78] eventSink::Infoerr(<{%reset%}>why you are seeing this message, re-run your program with the `PULUMI_DEBUG_PROMISE_LEAKS`<{%reset%}>)
I0802 20:08:29.877535   40314 eventsink.go:78] eventSink::Infoerr(<{%reset%}>environment variable. The Pulumi runtime will then print out additional<{%reset%}>)
I0802 20:08:29.877553   40314 eventsink.go:78] eventSink::Infoerr(<{%reset%}>debug information about the leaked promises.<{%reset%}>)
I0802 20:08:29.877443   40314 eventsink.go:70] eventSink::Info(<{%reset%}>    at Http2CallStream.EventEmitter.emit (domain.js:482:12)<{%reset%}>)
I0802 20:08:29.877581   40314 eventsink.go:70] eventSink::Info(<{%reset%}>    at /Users/matthieu/frisson/infra/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14<{%reset%}>)
I0802 20:08:29.877602   40314 eventsink.go:70] eventSink::Info(<{%reset%}>    at processTicksAndRejections (internal/process/task_queues.js:79:11) {<{%reset%}>)
I0802 20:08:29.877616   40314 eventsink.go:70] eventSink::Info(<{%reset%}>  code: 14,<{%reset%}>)
I0802 20:08:29.877632   40314 eventsink.go:70] eventSink::Info(<{%reset%}>  details: 'Connection dropped',<{%reset%}>)
I0802 20:08:29.877645   40314 eventsink.go:70] eventSink::Info(<{%reset%}>  metadata: Metadata { internalRepr: Map {}, options: {} }<{%reset%}>)
I0802 20:08:29.877659   40314 eventsink.go:70] eventSink::Info(<{%reset%}>}<{%reset%}>)

...


I0802 20:08:30.219268   40314 provider_plugin.go:466] Provider[aws, 0xc005829980].Configure() failed: err=transport is closing
I0802 20:08:30.224089   40314 ignore.go:44] Explicitly ignoring and discarding error: rpc error: code = Canceled desc = grpc: the client connection is closing
I0802 20:08:30.224180   40314 host.go:451] Error closing 'nodejs' language plugin during shutdown; ignoring: 1 error occurred:
	* operation not permitted
```

**Comment by leezen** [comment]
What version of node and pulumi are you using? Could you also please provide the `package.json` and lock file for your program?

**Comment by mleclercq** [comment]
I'm running with pulumi 2.7.1 and node 12.18.2.

Here are the package.json and package-lock.json:

- `package.json` of the stack: https://gist.github.com/mleclercq/ee4af9a34efffa289337f083cb50a1ac
- `package-lock.json` of the stack: https://gist.github.com/mleclercq/41522d4973e8d70c4b07354876bbad2b
- `package.json` of the shared lib the stack uses: https://gist.github.com/mleclercq/8c6e1c37377c1c40b88d46f2e0a8f929

These are pretty bigs... and that may be part of our problem.

I've noticed yesterday that it looks like I get the error more often when my computer is more loaded with other background works.

**Comment by leezen** [comment]
Sorry for not following up sooner. Are you still seeing this and does it correlate with higher load on the machine?

**Comment by Lepozepo** [comment]
I'm running my stack on all of the latest versions and I'm seeing 14 Connection Dropped errors very often and randomly across services XD but if I try multiple times it eventually works

**Comment by danielrbradley** [comment]
I've also had this issue intermittently when deploying to Azure - with the terraform based resources. I've seen the error appear on multiple types of resources - CDN Endpoint, Key Vault Access Policies and others.

Interestingly I only see these errors when deploying using my Azure Pipeline - it doesn't normally occur if I deploy from my local development machine.

**Comment by Lepozepo** [comment]
I seem to run into this error more often when I place constructs under functions in JS:

```
index.js
import buildStuff from 'buildStuff';
const stuff = buildStuff();
```

```
import * as aws from 'pulumi/aws';

export default function buildStuff() {
  return {
    one: new aws.Construct(),
    two: new aws.Construct2(),
  }
}
```

And also if I forget to set the `parent` flag in custom constructs. Especially on `Route53` related constructs. Maybe these issues stem from some sort of dependency tracking happening behind the scenes between constructs and their outputs?

**Comment by EvanBoyle** [comment]
@Lepozepo What do you mean by `Construct`? Is this the same as `Componenet`? 

Are you by any chance making use of dynamic providers as well?

**Comment by Lepozepo** [comment]
@EvanBoyle sorry for the delay, yup, I mean something like `aws.ec2.Instance` so I suppose that would be a [resource](https://www.pulumi.com/docs/intro/concepts/resources/). I am using dynamic providers for a couple of things but haven't had issues with those. I recently upgraded pulumi and the issue wore off despite me putting resources inside of functions that aren't themselves another resource (so the latest patches have improved that in a big way on the AWS route53 resources). What continued to break my deployments may have been my forgetting to put some of them under a `parent` OR forgetting to put them in `registerOutputs` I can't say for certain which of the 2 mistakes fixed my pipeline but ensuring both seems to have gotten everything in order since I am no longer having these issues.

**Comment by justinvp** [comment]
Closing this as stale. We haven't seen any recent reports of this in years. If you're running into this, please open a new issue.
