### ISSUE TITLE
Panic:  runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ASaiun** [pulumi/pulumi#5131]
this bug again?

````
================================================================================
Pulumi Version:   v2.8.1
Go Version:       go1.14.3
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack(0xc0016af2c8, 0x1590f00, 0x277fb90)
        C:/go/src/runtime/debug/stack.go:24 +0xa4
main.panicHandler()
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x75
panic(0x1590f00, 0x277fb90)
        C:/go/src/runtime/panic.go:969 +0x174
github.com/pulumi/pulumi/sdk/v2/go/common/util/executable.FindExecutable(0x17cb21c, 0x2, 0x0, 0x0, 0x0, 0x1)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/go/common/util/executable/executable.go:38 +0x65c
main.goInstallDependencies(0xc0006bc819, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/new.go:647 +0xd5
main.installDependencies(0xc0000ed580, 0xc000c45f20, 0x22, 0x0, 0xc0006f1f80)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/new.go:577 +0x1dc
main.runNew(0x27d0ec0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000380f0, 0x4, 0x10000, 0x0, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/new.go:275 +0xc2e
main.newNewCmd.func1(0xc00027edc0, 0xc0001030c0, 0x0, 0x2, 0x16, 0x16)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/new.go:357 +0xc6
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunFunc.func1(0xc00027edc0, 0xc0001030c0, 0x0, 0x2, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:96 +0x58
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc00027edc0, 0xc0001030c0, 0x0, 0x2)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x72
github.com/spf13/cobra.(*Command).execute(0xc00027edc0, 0xc0001030a0, 0x2, 0x2, 0xc00027edc0, 0xc0001030a0)
        C:/Users/appveyor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2a4
github.com/spf13/cobra.(*Command).ExecuteC(0xc00027e580, 0x15, 0x0, 0x0)
        C:/Users/appveyor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/appveyor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x54


````

**Comment by stack72** [comment]
Hi @ASaiun 

I'm not sure what you mean by "this bug again?" - can you help me try and recreate the issue by giving me some steps that you took

Thanks

Paul

**Comment by ASaiun** [comment]
Hi, @stack72 
I just pulumi new a project, this my steps 
```
D:\golang\src\IAC-Demo\pulumi>pulumi new --dir test2-go
Please choose a template: kubernetes-go              A minimal Kubernetes Go Pulumi program
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name: (test2-go) test-2
project description: (A minimal Kubernetes Go Pulumi program) test-2
Created project 'test-2'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
stack name: (dev)
Created stack 'dev'

Installing dependencies...

================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v2.8.1
Go Version:       go1.14.3
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack(0xc0011df2c8, 0x1590f00, 0x277fb90)
        C:/go/src/runtime/debug/stack.go:24 +0xa4
main.panicHandler()
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x75
panic(0x1590f00, 0x277fb90)
        C:/go/src/runtime/panic.go:969 +0x174
github.com/pulumi/pulumi/sdk/v2/go/common/util/executable.FindExecutable(0x17cb21c, 0x2, 0x0, 0x0, 0x0, 0x1)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/go/common/util/executable/executable.go:38 +0x65c
main.goInstallDependencies(0xc000bcea81, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/new.go:647 +0xd5
main.installDependencies(0xc0009b8800, 0xc000b77d40, 0x26, 0x0, 0xc00079e420)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/new.go:577 +0x1dc
main.runNew(0x27d0ec0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000a0098, 0x8, 0x10000, 0x0, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/new.go:275 +0xc2e
main.newNewCmd.func1(0xc00023edc0, 0xc00043b4a0, 0x0, 0x2, 0x16, 0x16)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/new.go:357 +0xc6
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunFunc.func1(0xc00023edc0, 0xc00043b4a0, 0x0, 0x2, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:96 +0x58
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc00023edc0, 0xc00043b4a0, 0x0, 0x2)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x72
github.com/spf13/cobra.(*Command).execute(0xc00023edc0, 0xc00043b480, 0x2, 0x2, 0xc00023edc0, 0xc00043b480)
        C:/Users/appveyor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2a4
github.com/spf13/cobra.(*Command).ExecuteC(0xc00023e580, 0x15, 0x0, 0x0)
        C:/Users/appveyor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/appveyor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x54
```

but, I think I find the reason, this prompt message come out when I move the go runtime path.  pulumi cant not find it ?
and then I uninstall go and install go again for new version. but  pulumi still  cant not update go version again. as you can see, 
pulumi will still use the old version :   "Go Version:       go1.14.3"
```
PS C:\Users\jiasi> go version
go version go1.14.7 windows/amd64
```

what can I do to update the go version for pulumi using?

**Comment by lukehoban** [comment]
The line of code that’s triggering this does appear to be missing an error check. It’s not immediately clear why this isn’t a problem more often:

https://github.com/pulumi/pulumi/blob/master/sdk/go/common/util/executable/executable.go#L38

**Comment by ASaiun** [comment]
I find a way to fix it.
set GO111MODULE=auto 
and it work for me 
```
PS D:\golang\src\IAC-Demo\pulumi\vsphere\vsphereDemo> go env -w GO111MODULE=auto
PS D:\golang\src\IAC-Demo\pulumi\vsphere\vsphereDemo>
PS D:\golang\src\IAC-Demo\pulumi\vsphere\vsphereDemo>
PS D:\golang\src\IAC-Demo\pulumi\vsphere\vsphereDemo> pulumi up
Previewing update (vsphereDemo):
[resource plugin vsphere-2.6.1] installing
Downloading plugin: 22.05 MiB / 22.05 MiB [========================] 100.00% 17s
Moving plugin... done.
     Type                 Name                     Plan                                                                                                                                                                                       +   pulumi:pulumi:Stack  vsphereDemo-vsphereDemo  create                                                                                                                                                                                    
Resources:
    + 1 to create

Do you want to perform this update? yes
Updating (vsphereDemo):
     Type                 Name                     Status                                                                                                                                                                                     +   pulumi:pulumi:Stack  vsphereDemo-vsphereDemo  created                                                                                                                                                                                   
Resources:
    + 1 created

Duration: 22s

Permalink: https://app.pulumi.com/ASaiun/vsphereDemo/vsphereDemo/updates/1
warning: A new version of Pulumi is available. To upgrade from version '2.8.1' to '2.8.2', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
PS D:\golang\src\IAC-Demo\pulumi\vsphere\vsphereDemo>

```
