### ISSUE TITLE
Pulumi logs/watch assertion failed

### ISSUE THREAD

**Issue by adsanz** [pulumi/pulumi#5160]
A newly created project without the deployed stack gives the error:

```
  % pulumi logs                                                                                                         !395
Collecting logs for stack beta since 2020-08-11T13:01:27.000+02:00.

================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v2.8.2
Go Version:       go1.14.7
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            fatal: An assertion has failed

goroutine 1 [running]:
runtime/debug.Stack(0xc0007d3420, 0x1476a80, 0xc000255920)
        /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x6e
panic(0x1476a80, 0xc000255920)
        /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/runtime/panic.go:969 +0x166
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assert(...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v2/backend/filestate.GetLogsForTarget(0xc000671c20, 0xc000548ee0, 0x0, 0x0, 0x7f016406a498, 0x2937318, 0xc000671c20, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/filestate/backend.go:631 +0x28a
github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).GetLogs(0xc0000a4190, 0x1b27820, 0xc00003e0e0, 0x1b40ca0, 0xc000670c60, 0xc000671b00, 0x7f016406a498, 0x2937318, 0xc000548ee0, 0x0, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/filestate/backend.go:625 +0xf3
github.com/pulumi/pulumi/pkg/v2/backend.GetStackLogs(0x1b27820, 0xc00003e0e0, 0x1b40ca0, 0xc000670c60, 0xc000671b00, 0x7f016406a498, 0x2937318, 0xc000548ee0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/stack.go:109 +0xdf
github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localStack).GetLogs(0xc000670c60, 0x1b27820, 0xc00003e0e0, 0xc000671b00, 0x7f016406a498, 0x2937318, 0xc000548ee0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/filestate/stack.go:89 +0xa6
main.newLogsCmd.func1(0xc000831340, 0x2937318, 0x0, 0x0, 0x11, 0x11)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/logs.go:95 +0x434
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunFunc.func1(0xc000831340, 0x2937318, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:96 +0x51
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc000831340, 0x2937318, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000831340, 0x2937318, 0x0, 0x0, 0xc000831340, 0x2937318)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000244dc0, 0x15, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x4d
```

I'm guessing it might be because the stack is not deployed yet, but it could be nice to have a message error instead.

**Comment by lukehoban** [comment]
Looks like the same issue as https://github.com/pulumi/pulumi/issues/5112, which has a fix in PR at https://github.com/pulumi/pulumi/pull/5503.  Will close this one to track these together.
