### ISSUE TITLE
[codegen/python] Error when specifying nested Provider inputs using classes

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5212]
Provider inputs are handled a bit differently than standard resource inputs in that they are first serialized to JSON. We're not correctly handling this for the new input classes.

Attempting to do something like:

```python
provider = aws.Provider(
    'privileged',
    assume_role=aws.ProviderAssumeRoleArgs(
        role_arn=role_to_assume_arn,
        session_name='PulumiSession',
        external_id='PulumiApplication',
    ),
    region=aws_config.require('region')
)
```

Will result in the following `TypeError: Object of type ProviderAssumeRoleArgs is not JSON serializable`

<details>
  <summary>Full stack trace</summary>
  
```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/opt/pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 435, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 71, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 176, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 162, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/output.py", line 152, in run
        is_known = await self._is_known
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 23 more times]
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 320, in do_register
        resolver = await prepare_resource(res, ty, custom, props, opts)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 106, in prepare_resource
        provider_urn = await provider.urn.future()
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 18 more times]
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 320, in do_register
        resolver = await prepare_resource(res, ty, custom, props, opts)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 86, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 71, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 176, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 162, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/Users/justin/go/src/github.com/pulumi/examples/aws-py-assume-role/assume-role/venv/lib/python3.8/site-packages/pulumi/output.py", line 175, in run
        transformed: Input[U] = func(value)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
        return _default_encoder.encode(obj)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
        raise TypeError(f'Object of type {o.__class__.__name__} '
    TypeError: Object of type ProviderAssumeRoleArgs is not JSON serializable
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```
</details>

The workaround in the meantime is to continue passing this information as dict:

```python
provider = aws.Provider(
    'privileged',
    assume_role={
        'role_arn': role_to_assume_arn,
        'session_name': 'PulumiSession',
        'externalId': 'PulumiApplication',
    },
    region=aws_config.require('region')
)
```

**Comment by justinvp** [comment]
This has been addressed in the SDK and provider codegen, and will roll out as new versions of providers are released.
