### ISSUE TITLE
Python SDK: Error during preview when setting tags on AWS resources

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5250]
A couple users have reported this issue. Here's a simple repro:

```python
from pulumi_aws import ec2
vpc = ec2.Vpc(
    'eks-vpc',
    cidr_block='10.100.0.0/16',
    instance_tenancy='default',
    enable_dns_hostnames=True,
    enable_dns_support=True,
    tags={
        'Name' : 'pulumi-eks-vpc'
    }
)
```

This results in an error during preview:

```
$ pulumi up
Previewing update (test):
     Type                 Name             Plan       Info
 +   pulumi:pulumi:Stack  kubernetes-test  create     3 errors; 37 messages
 +   └─ aws:ec2:Vpc       eks-vpc-2        create
Diagnostics:
  pulumi:pulumi:Stack (kubernetes-test):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/Users/<redacted>/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/<redacted>/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/Users/<redacted>/venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/<redacted>/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 427, in do_register
        await rpc.resolve_outputs(res, resolver.serialized_props, resp.object, resolvers)
      File "/Users/<redacted>/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 487, in resolve_outputs
        translated_value = translate_output_properties(value, res.translate_output_property, types.get(key))
      File "/Users/<redacted>/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 434, in translate_output_properties
        return {
      File "/Users/<redacted>/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 436, in <dictcomp>
        translate_output_properties(v, output_transformer, get_type(k))
      File "/Users/<redacted>/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 451, in translate_output_properties
        raise AssertionError(f"Unexpected type. Expected 'list' got '{typ}'")
    AssertionError: Unexpected type. Expected 'list' got '<class 'str'>'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

The problem is the value coming back from the engine for this property is `{'Name': 'pulumi-eks-vpc', '__defaults': []}` and the type is specified as `Mapping[str, str]`, so our type check fails for `'__defaults'` because it's value is a `list` not a string.

We should be filtering out all keys that start with `__` like we do for other languages like [.NET](https://github.com/pulumi/pulumi/pull/3560) and [Go](https://github.com/pulumi/pulumi/pull/3996). We weren't previously filtering these out for Python, but now that we're checking the types, we'll need to.

Until a fix is available, users can workaround this by pinning to previous versions of the `pulumi` and `pulumi-aws` Python packages:

 - `pulumi` v2.8.2
 - `pulumi_aws` v3.1.0

**Comment by justinvp** [comment]
The fix has been released in version `2.9.2` of the `pulumi` package, which will work with `pulumi-aws` version `3.2.1`.
