### ISSUE TITLE
[codegen/nodejs] New Resource constructor overload breaks PaC type inference

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5252]
These policies used to work:

```typescript
import * as k8s from "@pulumi/kubernetes";
import { PolicyPack, validateResourceOfType } from "@pulumi/policy";
​
// tslint:disable-next-line: no-unused-expression
new PolicyPack("k8s", {
    policies: [
        {
            name: "replica-count",
            description: "Consider more replicas for high-availability.",
            enforcementLevel: "advisory",
            validateResource: validateResourceOfType(k8s.apps.v1.Deployment, (resource, _, reportViolation) => {
                if (resource.spec!.replicas! <= 1) {
                    reportViolation("Replica count should be greater than 1.");
                }
            }),
        },
        {
            name: "non-secure-http",
            description: "External services should expose via HTTPS.",
            enforcementLevel: "advisory",
            validateResource: validateResourceOfType(k8s.core.v1.Service, (resource, _, reportViolation) => {
                resource.spec!.ports?.forEach(specPort => {
                    if (specPort.port !== 443) {
                        reportViolation(`Service port [${specPort.port}] should be exposed via 443.`);
                    }
                });
            }),
        },
        {
            name: "pin-image-versions",
            description: "Images should be pinned to a specific version",
            enforcementLevel: "mandatory",
            validateResource: validateResourceOfType(k8s.apps.v1.Deployment, (resource, _, reportViolation) => {
                resource.spec!.template!.spec!.containers.forEach(it => {
                    if (it?.image?.endsWith(":latest")) {
                        reportViolation("Image version should not be 'latest'.");
                    }
                });
            }),
        },
    ],
```

But now when the policy pack references `@pulumi/kubernetes` version 2.5.0, the following errors occur during `pulumi up`:

```
    error: [runtime] Running program '/Users/clstokes/.pulumi/policies/demo/pulumi-analyzer-k8s-v0.1.20200825-5' failed with an unhandled exception:
        TSError: ⨯ Unable to compile TypeScript:
    index.ts(12,30): error TS2339: Property 'spec' does not exist on type 'never'.
    index.ts(22,26): error TS2339: Property 'spec' does not exist on type 'never'.
    index.ts(34,26): error TS2339: Property 'spec' does not exist on type 'never'.
        at createTSError (/Users/clstokes/.pulumi/policies/demo/pulumi-analyzer-k8s-v0.1.20200825-5/node_modules/ts-node/src/index.ts:261:12)
        at getOutput (/Users/clstokes/.pulumi/policies/demo/pulumi-analyzer-k8s-v0.1.20200825-5/node_modules/ts-node/src/index.ts:367:40)
...
```

The errors are due to a new constructor overload being added to the K8s resources in v2.5.0, from the codegen change in https://github.com/pulumi/pulumi/pull/4991:

```diff
diff --git a/sdk/nodejs/apps/v1/Deployment.ts b/sdk/nodejs/apps/v1/Deployment.ts
index 627419fb..e29cd74f 100644
--- a/sdk/nodejs/apps/v1/Deployment.ts
+++ b/sdk/nodejs/apps/v1/Deployment.ts
@@ -86,13 +86,18 @@ export class Deployment extends pulumi.CustomResource {
      * @param args The arguments to use to populate this resource's properties.
      * @param opts A bag of options that control this resource's behavior.
      */
-    constructor(name: string, args?: DeploymentArgs, opts?: pulumi.CustomResourceOptions) {
+    constructor(name: string, args?: DeploymentArgs, opts?: pulumi.CustomResourceOptions)
+    constructor(name: string, state: undefined, opts: pulumi.CustomResourceOptions)
+    constructor(name: string, argsOrState?: DeploymentArgs, opts?: pulumi.CustomResourceOptions) {
         let inputs: pulumi.Inputs = {};
-        inputs["apiVersion"] = "apps/v1";
-        inputs["kind"] = "Deployment";
-        inputs["metadata"] = args ? args.metadata : undefined;
-        inputs["spec"] = args ? args.spec : undefined;
-        inputs["status"] = undefined /*out*/;
+        if (!(opts && opts.id)) {
+            const args = argsOrState as DeploymentArgs | undefined;
+            inputs["apiVersion"] = "apps/v1";
+            inputs["kind"] = "Deployment";
+            inputs["metadata"] = args ? args.metadata : undefined;
+            inputs["spec"] = args ? args.spec : undefined;
+            inputs["status"] = undefined /*out*/;
+        }
         if (!opts) {
             opts = {}
         }
```

The extra `constructor(name: string, state: undefined, opts: pulumi.CustomResourceOptions)` overload has broken the type inference used in PaC's [`validateResourceOfType`](https://github.com/pulumi/pulumi-policy/blob/ae2a9155e264c43b3980de71efa574f62d771198/sdk/nodejs/policy/policy.ts#L374-L386), which infers the type of `TArgs` based on the signature of the specified Resource's constructor -- which used to work for all our custom resources.

It may be possible to update `validateResourceOfType` to take this extra constructor overload into account, but I am wondering why it's needed in the first place.

**Comment by justinvp** [comment]
In the meantime, the workaround is to pin the policy pack dependency on an earlier version of `@pulumi/kubernetes` package.

```json
"@pulumi/kubernetes": "2.4.0"
```

**Comment by justinvp** [comment]
@pgavlin, do you recall why the following new constructor overload was necessary to emit?

https://github.com/pulumi/pulumi/blob/493136d2f079011b2c8c3e49ce4b13d73fb1d76a/pkg/codegen/nodejs/gen.go#L496

I actually don't think we should be emitting it, as it exposes the `state` arg in the public signature of the constructor, which should be an implementation detail, IMO (used by `get`).

The way function overloads work in TS is that only the overloads are part of the overload list, the actual implementation function at the end isn't included in the list of overloads.

In this case, the following are the two public constructor overloads:

```typescript
constructor(name: string, args?: DeploymentArgs, opts?: pulumi.CustomResourceOptions)
constructor(name: string, state: undefined, opts: pulumi.CustomResourceOptions)
```

And the last one with the implementation is not (per https://www.typescriptlang.org/docs/handbook/functions.html#overloads):

```typescript
constructor(name: string, argsOrState?: DeploymentArgs, opts?: pulumi.CustomResourceOptions)
```

It's unclear to me why `constructor(name: string, state: undefined, opts: pulumi.CustomResourceOptions)` needs to be one of the public overloads.

**Comment by pgavlin** [comment]
> It's unclear to me why `constructor(name: string, state: undefined, opts: pulumi.CustomResourceOptions)` needs to be one of the public overloads.

I _think_ that I needed to add this because I couldn't get codegen for types with no state inputs and some required inputs working otherwise. IIRC, this doesn't compile:

```typescript
constructor(name: string, args: DeploymentArgs, opts?: pulumi.CustomResourceOptions)
constructor(name: string, argsOrState?: DeploymentArgs, opts?: pulumi.CustomResourceOptions)
```

I'd have to revert the changes and try with an appropriate provider to be certain.

**Comment by pgavlin** [comment]
Yeah, here's the concrete issue: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIE8CS5rycgbwChlTkYB7CgLmRAFcBbAI2gG4Szm4oB+WgM5gooAOYcAvkSIIANnAEC06AMLzFhTqQAO9ZrOAJkQuGEPJREMAAoAlLQxqFS4mTfIoV+lBB0IAd2UnRWt6EAATCBhQCHCAGmRheghbDjcpLWQEChAhKHoEMAooa2AHLBxYRAgEyzB+ZGYqWQg4EFtM7NykwuLShoxsSCqkWqsGpooWtttNTKkJIA

So it's not the constructor definitions that don't compile, it's the `get` method, which has no appropriate constructor that can be easily called. Perphaps could change the `undefined` constructor to take an `any` as a simple fix?

**Comment by pgavlin** [comment]
(it's annoying that the version of the constructor used for `get` has to be public at all, tbh)

**Comment by pgavlin** [comment]
Indeed, it looks like adding `any` to that constructor does work: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIE8CS5rycgbwChlTkYB7CgLmRAFcBbAI2gG4Szm4oB+WgM5gooAOYcAvkSIIANnAEC06AMLzFhTqQAO9ZrOAJkQuGEPJREMAAoAlLQxqFS4mTfIoV+lBB0IAd2UnRWt6EAATCBhQCHCAGmRheghbDjcpLWQEChAhKHoEMAooa2AHLBxYRAgEyzB+ZGYqWQg4EFtM7NykwuLS2jb0WqsGpooWto63LryCopLgBoxsSCr8AB9kQeH62jGJ9s1MqQkgA

**Comment by justinvp** [comment]
Could we just give up some type safety to keep the public API clean? https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIE8CS5rycgbwChlTkYB7CgLmRAFcBbAI2gG4Szm4oB+WgM5gooAOYcAvkSIIANnAEC06AMLzFhTqQAO9ZrOAJkQuGEPJREMAAoAlLQxqFS4mTfIoV+lBB0IAd2RrR3UlBWQ4EHRba3oQABMIGFAIeIAaZGF6CFsONyktZAQKECEoegQwCihrYAcsHFhECAzLMH5kZipZCEjbTXcyYtKKHoA6WQpRWtzCqQKQ5zG2uzYgA

**Comment by pgavlin** [comment]
Yes, that seems reasonable to me.

**Comment by justinvp** [comment]
Fixed by https://github.com/pulumi/pulumi-kubernetes/pull/1286
