### ISSUE TITLE
Large multi-cluster stack resource exhaustion

### ISSUE THREAD

**Issue by barclayadam** [pulumi/pulumi#5287]
I have a large (ish) stack that is desigend to deploy to multiple Kubernetes clusters (currently 4, 2 Azure geographies x 2 regions, would be expanded).

I have all 4 clusters and the associated services in a single stack (a method to create all resources in a loop, once per region, in essence).

I'm hitting some odd behaviour that I do not fully understand. I'm not sure if these are related, something underlying about the same of deployment or not so I'm putting them here and can split if necessary

**Duplicate resource display**

The output is showing the same resource multiple times, even one only one should exist per region. For example:

```
 +   ├─ kubernetes:yaml:ConfigFile                                                 usw-usw-cert-manager                                  created
 +   ├─ kubernetes:yaml:ConfigFile                                                 usw-usw-cert-manager                                  created
 +   ├─ kubernetes:yaml:ConfigFile                                                 usw-usw-cert-manager                                  created
 +   ├─ kubernetes:yaml:ConfigFile                                                 usw-usw-cert-manager                                  created
 +   ├─ kubernetes:yaml:ConfigFile                                                 usw-usw-cert-manager                                  created
 +   ├─ kubernetes:yaml:ConfigFile                                                 ukw-ukw-cert-manager                                  created
 +   ├─ kubernetes:yaml:ConfigFile                                                 ukw-ukw-cert-manager                                  created
 +   │  ├─ kubernetes:core:ServiceAccount                                          ukw-cert-manager/cert-manager-cainjector              created
 +   │  ├─ kubernetes:core:ServiceAccount                                          ukw-cert-manager/cert-manager-cainjector              created
 +   │  ├─ kubernetes:core:ServiceAccount                                          ukw-cert-manager/cert-manager-cainjector                created
 +   │  ├─ kubernetes:core:Namespace                                               ukw-cert-manager                                        created
 +   │  ├─ kubernetes:core:Namespace                                               ukw-cert-manager                                        created
```

You can see multiple `kubernetes:yaml:ConfigFile` resources with the same name. In reality only 4 of those should exist for different regions (i.e. 'usw-usw-cert-manager', 'usc-usc-cert-manager', 'uks-uks-cert-manager' and 'ukw-ukw-cert-manager'). I therefore have no real idea what Pulumi _really_ is doing here.

**Resource exhaustion**

The deployment runs for a while until failing with a lot of errors like:

```
    Error: failed to register new resource ukw-clusterissuers.cert-manager.io [kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition]: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted
        at Object.registerResource (D:\Adam\Projects\Signature365\azure\node_modules\@pulumi\pulumi\runtime\resource.js:115:27)
        at new Resource (D:\Adam\Projects\Signature365\azure\node_modules\@pulumi\pulumi\resource.js:204:24)
        at new CustomResource (D:\Adam\Projects\Signature365\azure\node_modules\@pulumi\pulumi\resource.js:295:9)
        at new CustomResourceDefinition (D:\Adam\Projects\Signature365\azure\node_modules\@pulumi\apiextensions\v1\customResourceDefinition.ts:91:9)
        at id.apply.id (D:\Adam\Projects\Signature365\azure\node_modules\@pulumi\yaml\yaml.ts:2866:27)
        at D:\Adam\Projects\Signature365\azure\node_modules\@pulumi\pulumi\output.js:249:35
        at Generator.next (<anonymous>)
        at D:\Adam\Projects\Signature365\azure\node_modules\@pulumi\pulumi\output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (D:\Adam\Projects\Signature365\azure\node_modules\@pulumi\pulumi\output.js:17:12)
```

I'm not sure _what_ bandwidth is being exhausted here, is it Azure, AKS, something local or perhaps the Pulumi service itself?

## Expected Behavior

I can deploy large multi-cluster scripts without issues.

## Current Behavior

The deployments fail, leaving an inconsistent state in some cases where operations _have_ completed in K8S.

## Steps to Reproduce
I do not have a small reproducable script for this.

## Context (Environment)
OS: Windows 10
Pulumi version: v2.9.2
Packages:

```
  "devDependencies": {
    "@pulumi/azure": "^3.19.0",
    "@pulumi/azuread": "^2.5.1",
    "@pulumi/cloudflare": "^2.5.0",
    "@pulumi/docker": "^2.3.0",
    "@pulumi/kubernetes": "^2.5.1",
    "@pulumi/kubernetesx": "^0.1.3",
    "@pulumi/pulumi": "^2.9.2",
    "@pulumi/random": "^2.3.1",
    "@pulumi/tls": "^2.3.0",
  },
```

**Comment by barclayadam** [comment]
If I run the same script multiple times then resources that failed in a previous iteration _can_ start to be created in subsequent runs, but never all of them in one go.

The long-term fix for me may be to split out how I split the script, to do a region at a time + a "global" one, but that feels like quite an explosion of stacks. 

I've followed some of the examples from the Pulumi site so have 6 different projects doing different parts of the system. I'd have 6*(regions+1) stacks for each environment. For us, that would mean 72 different stacks, which feels too many

**Comment by leezen** [comment]
That `RESOURCE_EXHAUSTED` is coming from the grpc call to the engine

Any chance you could share some of the code for how you're creating the resources in that loop?

It would also be helpful to see your verbose logs: https://www.pulumi.com/docs/troubleshooting/

**Comment by barclayadam** [comment]
Sure, I've cut down on some of the noise in the below. Hopefully it gives an idea of what the code looks like. I've continued to try to track down the issue so do not have a detailed log yet but will work to get one tomorrow on another run-through. As a rough guide, I believe the script expands out into >300 resources (because the charts and yaml file expand into quite a number of individual resources).

````ts
// Utility that will loop through all configured regions (4 in this case) and await the result of
// the callback. `out` is an object that is populated with outputs, separated per region
await env.forRegions<ClusterServicesRegionExports>(async (out, r) => {
    // Utility to grab a region-specific stack output
    const infraStack = r.requireStackOutput(InfraRegionExports);
    const clusterCfg = r.requireStackOutput(ClusterRegionExports);

    const provider = new k8s.Provider(r.pulumiName('aks'), {
        kubeconfig: clusterCfg.kubeconfigAdmin,
    });

    // Bind the AD admin group (see config.adGroupAdmins) to the cluster-admin role.
    new k8s.rbac.v1.ClusterRoleBinding(r.pulumiName('role-binding-admins'), {
        ...
    }, {
        provider
    });

    /*************
     * NAMESPACES
     *************/

    function namespace(name: string) {
        return new k8s.core.v1.Namespace(
            r.pulumiName(name),
            {
                metadata: {name: name},
            },
            { provider });
    }


    const appsNamespace = namespace('apps');
    out.appsNamespaceName = appsNamespace.metadata.name;

    /****************
     * CERT MANAGER
     * https://cert-manager.io/
     ****************/

    // Lets Encrypt
    const letsencryptEmail = env.config.require('letsencryptEmail');

    // Cloudflare
    const cloudflareSolverEmail = env.config.require('cloudflareSolverEmail');
    const cloudflareSolverToken = env.config.requireSecret('cloudflareSolverApiToken');

    const certManagerRelease = new k8s.yaml.ConfigFile(
        r.pulumiName('cert-manager'),
        {
            file: './cert-manager-1.0.0.yaml',
            resourcePrefix: r.shortName
        },
        {provider});

    const cloudflareSolverSecret = new kx.Secret(
        r.pulumiName('cloudflare-solver-secrets'),
        {
            metadata: {
                name: 'cloudflare-solver-secrets',
                namespace: appsNamespace.metadata.name,
            },

            stringData: {
                'api-token': cloudflareSolverToken,
            },
        },
        {provider},
    );

    const appsCertIssuerName = 'letsencrypt-apps-issuer';

    new k8s.apiextensions.CustomResource(r.pulumiName('apps-cert-issuer'), {
        apiVersion: 'cert-manager.io/v1',
        kind: 'Issuer',
        metadata: {
            name: appsCertIssuerName,
            namespace: appsNamespace.metadata.name,
        },
        spec: {
            ...
        },
    }, {
        provider,
        dependsOn: [certManagerRelease],
    });

    out.appsCertIssuerName = appsCertIssuerName;

    /*************
     * INGRESS / AMBASSADOR
     * https://www.getambassador.io/
     *************/

    const ambassadorNamespace = new k8s.core.v1.Namespace(
        r.pulumiName('ambassador'),
        {
            metadata: {name: 'ambassador'},
        },
        {
            provider,
        });

    const ambassadorRelease = new k8s.helm.v3.Chart(r.pulumiName('ambassador'),
        {
            namespace: ambassadorNamespace.metadata.name,
            resourcePrefix: r.shortName,
            chart: 'ambassador',
            fetchOpts: {
                repo: 'https://getambassador.io',
            },
            values: {
                ...
            },
            transformations: [
                (obj: any) => {
                    if (obj.metadata) {
                        obj.metadata.namespace = ambassadorNamespace.metadata.name;
                    }
                },
            ],
        },
        {provider});

    new k8s.apiextensions.CustomResource(r.pulumiName(`ambassador-module`), {
        apiVersion: 'getambassador.io/v2',
        kind: 'Module',
        metadata: {
            name: 'ambassador',
        },
        spec: {
            config: {
                // Trust CF "proxy"
                'xff_num_trusted_hops': 1,
            },
        },
    }, {
        provider,
        parent: ambassadorRelease,
    });

    /****************
     * Azure Active Directory Pod Identity
     * https://github.com/Azure/aad-pod-identity
     ****************/

    new k8s.yaml.ConfigFile(
        r.pulumiName('aad-pod-identity'),
        {
            file: './aad-pod-identity-1.6.2.yaml',
            resourcePrefix: r.shortName,
        },
        {provider});

    new k8s.yaml.ConfigFile(
        r.pulumiName('aad-pod-identity-mic-exception'),
        {
            file: './aad-pod-identity-mic-exception.yaml',
            resourcePrefix: r.shortName,
        },
        {provider});

    /****************
     * KURED - Scheduled reboot management
     * https://github.com/weaveworks/kured
     ****************/

    const kuredNamespace = new k8s.core.v1.Namespace(
        r.pulumiName('kured'),
        {
            metadata: {name: 'kured'},
        },
        {
            provider,
        });

    new k8s.helm.v2.Chart(r.pulumiName('kured'),
        {
            namespace: kuredNamespace.metadata.name,
            resourcePrefix: r.shortName,
            chart: 'kured',
            fetchOpts: {
                repo: 'https://weaveworks.github.io/kured',
            },
            version: '2.1.1', // kubernetes 1.16/1.17/1.18, Kured v1.4.5
        },
        {provider});
});


````

**Comment by barclayadam** [comment]
I have run the program again with verbose logging. It's a 758MB log file, 59MB zipped if you are interested, or is there anything in particular I could extract perhaps?

**Comment by barclayadam** [comment]
Further to this, the deletion of the stack resources takes a _very_ long time, which suggests a bottleneck somewhere in the node/go SDK. 

412 deletions took 1h 4m. Most of those resources are simple deletions from the K8S clusters, a process that with an individual cluster can take no more than 5-10 minutes.

**Comment by barclayadam** [comment]
A further update... I've been trying to get this to work by sequencing the updates. I'm doing this with a custom, empty resource, `Region`, that I have as the parent of all resources within that region. Each region has a `dependsOn` to a "previous" one. This _does_ mean in some of the other stacks that updates happen in sequence.

In the one stack that I'm trying to get working the problem *still* happens. In fact I've got in a situation now where running `pulumi up` after a previous update does almost nothing and has the following output:

````
     Type                 Name                         Plan     Info
     pulumi:pulumi:Stack  cluster-services-uat           1 error

Diagnostics:
  pulumi:pulumi:Stack (cluster-services-uat):
    error: Running program 'D:\proj\\azure\04-cluster-services' failed with an unhandled exception:
    Error: failed to register new resource usw-issuers.cert-manager.io [kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition]: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted
        at Object.registerResource (D:\proj\\azure\node_modules\@pulumi\pulumi\runtime\resource.js:115:27)
        at new Resource (D:\proj\\azure\node_modules\@pulumi\pulumi\resource.js:204:24)
        at new CustomResource (D:\proj\\azure\node_modules\@pulumi\pulumi\resource.js:295:9)
        at new CustomResourceDefinition (D:\proj\\azure\node_modules\@pulumi\apiextensions\v1\customResourceDefinition.ts:91:9)
        at id.apply.id (D:\proj\\azure\node_modules\@pulumi\yaml\yaml.ts:2866:27)
        at D:\proj\\azure\node_modules\@pulumi\pulumi\output.js:249:35
        at Generator.next (<anonymous>)
        at D:\proj\\azure\node_modules\@pulumi\pulumi\output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (D:\proj\\azure\node_modules\@pulumi\pulumi\output.js:17:12)

````

I'm not sure how to progress this forward.

**Comment by leezen** [comment]
Thanks for the additional debug information. @lblackstone any chance you've seen anything like this w/ the k8s provider regarding the grpc bandwidth consumption?

**Comment by lblackstone** [comment]
That stack is quite a bit bigger than most of the ones I've tried, and we have seen problems in the past with gRPC and large resources. https://github.com/pulumi/pulumi-kubernetes/issues/963

Helm and YAML support do involve passing large data structures back and forth across gRPC, so it seems like that could be the culprit since these resource updates are likely to run in parallel.

**Comment by coryrjohnson** [comment]
Any updates here on when this may get prioritized? This really hurts the ability to use Pulumi for us, we are running into this pretty often with our larger stacks.

**Comment by yz89122** [comment]
Is it because of registering a large output at somewhere? (probably the `/index.ts`)

I've encounter this issue today. After a few trying, I find out the cause of mine is because I'm exporting the entire resource tree using the `export` keyword in typescript in the entrypoint, which is `index.ts`. And I guess that cause a large single gRPC request that result in `RESOURCE_EXHAUSTED` error. In my case, after removing it, the error does not appear anymore.

I'm not sure is the case is the same as yours, but I fixed mine after remove the implicit output.

In my case, each JS module be like

`xxx/index.ts`

```ts
import * as resourceSet1 from './resource_set_1';
import * as resourceSet2 from './resource_set_2';

export { resourceSet1, resourceSet2 };
```

In the entrypoint of my program, which is `/index.ts`, is exporting all the resource

```ts
import * as xxx from './xxx';
import * as yyy from './yyy';

export { xxx, yyy }; // I guess this is the cause of the `RESOURCE_EXHAUSTED`
```

To fix it, which is to change `/index.ts`, just don't export the resource tree.

```ts
import './xxx';
import './yyy';
```
