### ISSUE TITLE
dotnet binary option for self-contained executables

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi#5334]
I noticed the binary option only works with a `dll`, despite the build generating an `exe`:
```yml
name: aws
runtime:
  name: dotnet
  options:
    binary: Aws.exe
description: AWS infrastructure
config: ..
```
Fails with the following error:
```sh
user@b8b9b2241208:/app/Aws$ p up
Previewing update (pharos/alpha)

View Live: https://app.pulumi.com/pharos/aws/alpha/previews/e85b6b48-b096-4857-9700-30d8a29da561

     Type                 Name       Plan     Info
     pulumi:pulumi:Stack  aws-alpha           1 error; 5 messages

Diagnostics:
  pulumi:pulumi:Stack (aws-alpha):
    Error:
      An assembly specified in the application dependencies manifest (Aws.deps.json) has already been found but with a different file extension:
        package: 'Aws', version: '0.0.0.0'
        path: 'Aws.dll'
        previously found assembly: '/app/Aws/Aws.exe'

    error: an unhandled error occurred: Program exited with non-zero exit code: 140
```
I’ll probably want to switch to a trimmed single file `exe` when dotnet 5.0 lands! 😉 

Another problem is that pulumi plugins are not automatically acquired, so given the following project dependencies:
```xml
<ItemGroup>
  <PackageReference Include="Pulumi" Version="2.10.0" />
  <PackageReference Include="Pulumi.Aws" Version="3.2.1" />
  <PackageReference Include="Pulumi.Kubernetes" Version="2.6.0" />
  <PackageReference Include="Pulumi.Tls" Version="2.3.0" />
</ItemGroup>
```
I have to run the following inside the container for the binary to work:
```sh
pulumi plugin install resource aws v3.2.1
pulumi plugin install resource kubernetes v2.6.0
pulumi plugin install resource tls v2.3.0
```

**Comment by gitfool** [comment]
FWIW, I've settled on the following workarounds for now...

Use a `Pulumi.yaml` on Windows with binary options commented out:
```yml
name: aws
description: AWS infrastructure
runtime:
  name: dotnet
#   options:
#     binary: Aws.dll
config: ..
```
Uncommented during Docker build stage. Also, parse any `Pulumi.*` package references in `csproj` files to preinstall plugins:
```Dockerfile
FROM pulumi-docker as builder

ARG configuration=Release

COPY --chown=user:user . .

RUN find -path "**/bin/$configuration/Pulumi.yaml" \
        | xargs --verbose -r -I {} sed -i -e 's/^# //' {} 2>&1 \
    && sed -n -E 's/\s+<PackageReference\s+Include="Pulumi\.([^"]+)"\s+Version="([^"]+)"\s+\/>\r?/\L\1 v\2/p' **/*.csproj | sort | uniq \
        | xargs --verbose -r -I {} bash -c 'pulumi plugin install resource {}' 2>&1

FROM pulumi-docker

ARG configuration=Release

COPY --chown=user:user --from=builder /home/user/Pulumi.*.yaml ./
COPY --chown=user:user --from=builder /home/user/Aws/bin/$configuration/ ./Aws/
COPY --chown=user:user --from=builder /home/user/Kubernetes/bin/$configuration/ ./Kubernetes/
COPY --chown=user:user --from=builder /home/user/.pulumi ./.pulumi
```
Note:
* `pulumi-docker` is a custom image
* `user` is a non-root "[user](https://tron.fandom.com/wiki/User)" 😉

**Comment by gitfool** [comment]
Hit another issue after re-targeting [.NET 5.0 RC1](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-1) and publishing a single file executable to Ubuntu 20.04 _without_ dotnet installed:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <PublishSingleFile>true</PublishSingleFile>
    <!-- <PublishTrimmed>true</PublishTrimmed> -->
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <!-- <TrimMode>Link</TrimMode> -->
    <!-- <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract> -->
  </PropertyGroup>
</Project>
```
```sh
user@93eaf4e66a3a:~$ dotnet --info
bash: dotnet: command not found

user@93eaf4e66a3a:~$ ll Aws/
total 125188
drwxr-xr-x 2 user user     4096 Sep 15 09:03 ./
drwxr-xr-x 1 user user     4096 Sep 15 09:03 ../
-rwxr-xr-x 1 user user     3374 Sep 11 04:21 AlbIngressPolicy.json*
-rwxr-xr-x 1 user user 79859509 Sep 15 09:02 Aws*
-rwxr-xr-x 1 user user    17912 Sep 15 09:02 Aws.pdb*
-rwxr-xr-x 1 user user    17072 Sep 15 09:02 Library.pdb*
-rwxr-xr-x 1 user user      104 Sep 15 09:02 Pulumi.yaml*
-rwxr-xr-x 1 user user 26419208 Sep 24  2019 libgrpc_csharp_ext.x64.so*
-rwxr-xr-x 1 user user 21845068 Sep 24  2019 libgrpc_csharp_ext.x86.so*

user@93eaf4e66a3a:~$ ./Aws/Aws
Unhandled exception. System.InvalidOperationException: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
   at Pulumi.Deployment..ctor()
   at Pulumi.Deployment.CreateRunner()
   at Pulumi.Deployment.RunAsync[TStack]()
   at Pharos.Gemini.Program.Main()
   at Pharos.Gemini.Program.<Main>()
Aborted

user@93eaf4e66a3a:~$ pulumi up --cwd=Aws --stack=pharos/alpha
Logging in using access token from PULUMI_ACCESS_TOKEN
Previewing update (pharos/alpha)

View Live: https://app.pulumi.com/pharos/aws/alpha/previews/a1a55962-48f4-4eb3-8ed7-1a3a57db8d6e

     Type                 Name       Plan     Info
     pulumi:pulumi:Stack  aws-alpha           1 message

Diagnostics:
  pulumi:pulumi:Stack (aws-alpha):
    error: could not find `dotnet` on the $PATH: exec: "dotnet": executable file not found in $PATH

error: failed to load language plugin dotnet: could not read plugin [/usr/local/bin/pulumi-language-dotnet] stdout: EOF
```
Note: `Aws` above is a [self-contained](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained) executable that does not need the dotnet sdk or runtime to be installed:
* `dotnet` is not installed as shown by `dotnet --info`
* `./Aws/Aws` runs; albeit with the expected Pulumi engine error
* `pulumi up` fails unexpectedly since it still requires `dotnet` for some reason 😕

**Comment by gitfool** [comment]
I did another test with the dotnet _runtime_ installed, but it's worse than I thought, it actually expects the dotnet _sdk_ to be installed:
```sh
user@5ca8ecd0e492:~$ pulumi up --cwd=Aws --stack=pharos/alpha
Logging in using access token from PULUMI_ACCESS_TOKEN
Previewing update (pharos/alpha)

View Live: https://app.pulumi.com/pharos/aws/alpha/previews/05e3a3f5-5fa1-46f6-bb42-2816b8074c9d

     Type                 Name       Plan     Info
     pulumi:pulumi:Stack  aws-alpha           1 error; 8 messages

Diagnostics:
  pulumi:pulumi:Stack (aws-alpha):
    Could not execute because the application was not found or a compatible .NET SDK is not installed.
    Possible reasons for this include:
      * You intended to execute a .NET program:
          The application 'Aws' does not exist.
      * You intended to execute a .NET SDK command:
          It was not possible to find any installed .NET SDKs.
          Install a .NET SDK from:
            https://aka.ms/dotnet-download

    error: an unhandled error occurred: Program exited with non-zero exit code: 145
```
🙄

**Comment by gitfool** [comment]
Nope, _still_ doesn't work after installing the dotnet sdk:
```sh
user@5ca8ecd0e492:~$ curl -fsSL https://dot.net/v1/dotnet-install.sh | bash -s -- --channel release/5.0.1xx
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
dotnet_install: Warning: Unable to locate liblttng. Probable prerequisite missing; install libcurl.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20454.5/dotnet-sdk-5.0.100-rc.1.20454.5-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20454.5/dotnet-sdk-5.0.100-rc.1.20454.5-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/home/user/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.

user@5ca8ecd0e492:~$ export PATH=$HOME/.dotnet:$PATH

user@5ca8ecd0e492:~$ pulumi up --cwd=Aws --stack=pharos/alpha
Previewing update (pharos/alpha)

View Live: https://app.pulumi.com/pharos/aws/alpha/previews/bdae1793-d765-4075-a335-3f71ec90fc5e

     Type                 Name       Plan     Info
     pulumi:pulumi:Stack  aws-alpha           1 error; 5 messages

Diagnostics:
  pulumi:pulumi:Stack (aws-alpha):
    Could not execute because the specified command or file was not found.
    Possible reasons for this include:
      * You misspelled a built-in dotnet command.
      * You intended to execute a .NET program, but dotnet-Aws does not exist.
      * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```
😞

**Comment by mikhailshilkov** [comment]
> Another problem is that pulumi plugins are not automatically acquired, so given the following project dependencies

This is currently [expected](https://github.com/pulumi/pulumi/blob/1803eb29781795460900ac3bfc597dadfe84129f/sdk/dotnet/cmd/pulumi-language-dotnet/main.go#L132). We use [`dotnet list package`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package) to list the dependencies but it requires a project file.

**Comment by mikhailshilkov** [comment]
@gitfool Does the logic in this PR look correct to you in regards to self-contained executables? https://github.com/pulumi/pulumi/pull/5519

**Comment by gitfool** [comment]
@mikhailshilkov LGTM. Any chance of a binary option in the pulumi cli as well? 😛

**Comment by gitfool** [comment]
>This is currently expected. We use dotnet list package to list the dependencies but it requires a project file.

Could you point me at the source? (I'll update my Dockerfile to run the equivalent commands so there are no surprises; presumably it's parsing transitive pulumi resource dependencies too.)

**Comment by mikhailshilkov** [comment]
> Any chance of a binary option in the pulumi cli as well? 

Not right now :) Do you want to open a separate issue focused on that or keep this one open?

> Could you point me at the source?

https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/cmd/pulumi-language-dotnet/main.go#L198

**Comment by gitfool** [comment]
I don't mind, would you prefer a new issue focused on the cli option?

One thought re the binary executable; hopefully it will no longer try to [find `dotnet`](https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/cmd/pulumi-language-dotnet/main.go#L65) in the path as it won't exist for self-contained executables...

**Comment by gitfool** [comment]
FWIW, I updated my `Dockerfile` to preinstall plugins using `dotnet list package` (the same as [DeterminePulumiPackages](https://github.com/pulumi/pulumi/blob/2b67c6ea81d09bf88d2b575995e786a8eb4a21c2/sdk/dotnet/cmd/pulumi-language-dotnet/main.go#L198)):
```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:5.0.100-rc.1-focal as builder

ARG configuration=Release

WORKDIR /src

RUN curl -fsSL https://get.pulumi.com | bash 2>&1 \
    && mv ~/.pulumi/bin/* /usr/local/bin \
    && rm -rf ~/.pulumi

COPY . .

RUN dotnet list package --include-transitive \
        | awk '/> Pulumi\./ { printf("%s v%s\n", tolower(substr($2, 8)), $NF) }' | sort | uniq \
        | xargs --verbose -r -I {} bash -c 'pulumi plugin install resource {}' 2>&1 \
    && find -path "**/bin/$configuration/Pulumi.yaml" \
        | xargs --verbose -r -I {} sed -i -e 's/^# //' {} 2>&1

FROM pulumi-docker

ARG configuration=Release

COPY --chown=user:user --from=builder /root/.pulumi /home/user/.pulumi
COPY --chown=user:user --from=builder /src/Pulumi.*.yaml ./
COPY --chown=user:user --from=builder /src/Aws/bin/$configuration Aws
COPY --chown=user:user --from=builder /src/Kubernetes/bin/$configuration Kubernetes
```

**Comment by mikhailshilkov** [comment]
> would you prefer a new issue focused on the cli option?

Yes, sounds great.

> hopefully it will no longer try to find dotnet in the path as it won't exist for self-contained executables...

That's a great point! I'll make sure it won't.

**Comment by gitfool** [comment]
FYI, unfortunately I'm now hitting upstream issue https://github.com/grpc/grpc/issues/24266 which is blocking this from working:
```
user@87057cec4f2e:~/Aws$ pulumi up
Previewing update (pharos/alpha)

View Live: https://app.pulumi.com/pharos/aws/alpha/previews/185b1178-99d6-4402-8031-e4798079c290

     Type                 Name       Plan     Info
     pulumi:pulumi:Stack  aws-alpha           1 error; 17 messages

Diagnostics:
  pulumi:pulumi:Stack (aws-alpha):
    Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
       at System.IO.Path.Combine(String path1, String path2)
       at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
       at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
       at Grpc.Core.Internal.NativeExtension..ctor()
       at Grpc.Core.Internal.NativeExtension.Get()
       at Grpc.Core.Internal.NativeMethods.Get()
       at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
       at Grpc.Core.GrpcEnvironment..ctor()
       at Grpc.Core.GrpcEnvironment.AddRef()
       at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
       at Pulumi.GrpcEngine..ctor(String engine)
       at Pulumi.Deployment..ctor()
       at Pulumi.Deployment.CreateRunner()
       at Pulumi.Deployment.RunAsync[TStack]()
       at Pharos.Gemini.Program.Main()
       at Pharos.Gemini.Program.<Main>()

    error: an unhandled error occurred: Program exited with non-zero exit code: -1
```
