### ISSUE TITLE
 TypeError: Cannot convert undefined or null to object at zMixins.ts:265:41

### ISSUE THREAD

**Issue by cowwoc** [pulumi/pulumi#5346]
Version 2.10.0

Repro steps:

Run the sample code at the top of https://www.pulumi.com/blog/simple-serverless-programming-with-google-cloud-functions-and-pulumi/:

```
import * as gcp from "@pulumi/gcp";

let greeting = new gcp.cloudfunctions.HttpCallbackFunction("greeting", (req, res) => {
    // Change this code to fit your needs!
    res.send(`Greetings from ${req.body.name || 'Google Cloud Functions'}!`);
});

export let url = greeting.httpsTriggerUrl;
```

Exception thrown:

    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
        at C:\Users\Gili\Documents\project\deploy\node_modules\@pulumi\cloudfunctions\zMixins.ts:265:41
        at C:\Users\Gili\Documents\project\deploy\node_modules\read-package-json\read-json.js:111:5
        at C:\Users\Gili\Documents\project\deploy\node_modules\read-package-json\read-json.js:431:5
        at checkBinReferences_ (C:\Users\Gili\Documents\project\deploy\node_modules\read-package-json\read-json.js:386:45)
        at final (C:\Users\Gili\Documents\project\deploy\node_modules\read-package-json\read-json.js:429:3)
        at then (C:\Users\Gili\Documents\project\deploy\node_modules\read-package-json\read-json.js:156:5)
        at ReadFileContext.callback (C:\Users\Gili\Documents\project\deploy\node_modules\read-package-json\read-json.js:345:20)
        at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:264:13)
```

**Comment by cowwoc** [comment]
For some reason, wiping out `node_modules` and re-running `npm install` resolved the problem. Closing.

**Comment by flokle** [comment]
We ran into the same issue. If you take a look into zMixins at the line described within your error message you will find 
`const dependencies = Object.keys(packageJson.dependencies)`

(e.g. https://github.com/pulumi/pulumi-gcp/blob/v6.54.0/sdk/nodejs/cloudfunctions/zMixins.ts#L273)

We only had devDependencies in our package.json. Add an empty dependencies: {}-object and the error is gone.
