### ISSUE TITLE
Stack state in Azure blob storage - connection and socket timeout

### ISSUE THREAD

**Issue by jakubneubauer** [pulumi/pulumi#5350]
We run pulumi with stack state saved in azure blob storage.
Time to time we get error like this:
pulumi:pulumi:StackReference 14 UNAVAILABLE: Connection dropped

I guess that there was some network slowness. I would like to have configurable connection and socket timeout for accessing the azure blob storage. It seems that the current values are not reliable.

**Comment by jakubneubauer** [comment]
@leezen please, this is not enhancement. We encounter errors which cause "pulumi up" failure.
I cannot share production code. But it looks like the problem is in the resolvement of the stack reference, which we use in our program.

**Comment by jakubneubauer** [comment]
Here is an full example output from my colleague who encountered the problem too:

```
# pulumi preview
Previewing update (icloudtest5-bob):available. To upgrade from version '2.6.1' to '2.10.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
     Type                                   Name                             Plan       Info                                                                                                                                                                                        pulumi:pulumi:Stack                    icloudtest5-bob-icloudtest5-bob             1 error; 6 messages                                                                                                                                                                         └─ azure:core:ResourceGroup            bob-resource-group                          [diff: ~provider]                                                                                                                                                                              └─ piq-cxm:azure:privateLinkSubnet  icbob5-pl                                                                                                                                                                                                                           +         └─ piq-core:azure:privateLink    icbob5-sb-pl                     create                                                                                                                                                                                                    └─ piq-cxm:azure:privateLinkSubnet  icbob5-pl
Diagnostics:─ piq-core:azure:privateLink    icbob5-sb-pl                     create
  pulumi:pulumi:Stack (icloudtest5-bob-icloudtest5-bob):
    Reading service def in /current/projects/inspire-cloud-test/icloudtest5-bob/charts/docgen/config.json
    Reading service def in /current/projects/inspire-cloud-test/icloudtest5-bob/charts/icm/config.json
    Reading service def in /current/projects/inspire-cloud-test/icloudtest5-bob/charts/correspondence-contentauthor/config.jsonsources" to true.
    Reading service def in /current/projects/inspire-cloud-test/icloudtest5-bob/charts/default-pod-settings/config.json
    Reading service def in /current/projects/inspire-cloud-test/icloudtest5-bob/charts/storage-account/config.json
    Reading service def in /current/projects/inspire-cloud-test/icloudtest5-bob/charts/front-office/config.jsonthor/config.json
    error: Running program '/current/projects/inspire-cloud-test/icloudtest5-bob' failed with an unhandled exception:on
    Error: failed to read resource #aks-test5 'aks-stack-reference' [pulumi:pulumi:StackReference]: 14 UNAVAILABLE: Connection dropped
        at Object.readResource (/current/projects/inspire-cloud-test/icloudtest5-bob/node_modules/@pulumi/pulumi/runtime/resource.js:50:27)
        at new Resource (/current/projects/inspire-cloud-test/icloudtest5-bob/node_modules/@pulumi/pulumi/resource.js:197:24)
        at new CustomResource (/current/projects/inspire-cloud-test/icloudtest5-bob/node_modules/@pulumi/pulumi/resource.js:295:9)pped
        at new StackReference (/current/projects/inspire-cloud-test/icloudtest5-bob/node_modules/@pulumi/pulumi/stackReference.js:44:9):27)
        at new ProjectReferenceBase (/current/projects/inspire-cloud-test/icloudtest5-bob/node_modules/piq-core/src/utils/projectReferenceBase.js:8:27)
        at new StackReference (/current/projects/inspire-cloud-test/icloudtest5-bob/node_modules/piq-core/src/reference/aksReference.js:7:9)
        at new FullAksStackReference (/current/projects/inspire-cloud-test/icloudtest5-bob/node_modules/piq-core/src/reference/aksReference.js:13:1)
        at Object.<anonymous> (/current/projects/inspire-cloud-test/icloudtest5-bob/index.ts:14:22)les/piq-core/src/utils/projectReferenceBase.js:8:27)
        at Module._compile (internal/modules/cjs/loader.js:1138:30)/icloudtest5-bob/node_modules/piq-core/src/reference/aksReference.js:7:9)
        at Module.m._compile (/current/projects/inspire-cloud-test/icloudtest5-bob/node_modules/ts-node/src/index.ts:439:23)ce/aksReference.js:13:1)
        at Object.<anonymous> (/current/projects/inspire-cloud-test/icloudtest5-bob/index.ts:14:22)
        at Module._compile (internal/modules/cjs/loader.js:1138:30)
warning: A new version of Pulumi is available. To upgrade from version '2.6.1' to '2.10.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

BTW, upgrade to 2.10.0 does not help.

**Comment by leezen** [comment]
@jakubneubauer I marked this as an enhancement because today, the way that Azure storage-backed state is handled is via the gocloud library (https://gocloud.dev/) which doesn't expose a way to control the timeout to the blob store. Marking it as an enhancement doesn't mean this issue doesn't matter or won't be considered, it's purely a triage mechanism to help understand what an issue represents in terms of net new work vs. fixing a bug, etc.

**Comment by jakubneubauer** [comment]
HI, any progress?
