### ISSUE TITLE
[Automation API] Support parallel execution of nodejs inline programs

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#5449]
The Pulumi nodejs runtime implementation uses quite a bit of global state: https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/runtime/settings.ts#L188

We'll need to refactor all usage of global state out of the node SDK to allow Automation API to execute concurrent programs on different stacks that use the inline/hosted execution model.

One consequence of this is that multiple versions of pulumi can cause problems due to conflicting module level global state. Automation API users should pin to a single version of pulumi/pulumi via yarn `resolutions`: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by EvanBoyle** [comment]
To be clear for nodejs users, the Automation API allows one concurrent update per node process for the time being. If you want to run multiple updates in parallel, they will need to be in separate node processes.

**Comment by georgeportillo** [comment]
> pulumi/pulumi

pulumi/pulumi or @ pulumi/pulumi ?

**Comment by AMKamel** [comment]
I think the issue still exists, can you tell me what is wrong with follow cod to trigger the issue when using `yarn test`
errors
```
    Program run without the Pulumi engine available; re-run using the `pulumi` CLI

      100 |     const utility = new Utility()
      101 |     const virtualminDomainCommand =
    > 102 |       pulumi.all([args])
          |                        ^
      103 |         .apply(([args]) => {
      104 |             const playbookCreateFile = path.resolve(__dirname, `playbooks/create.yaml`)
      105 |             const playbookDeleteFile = path.resolve(__dirname, `playbooks/delete.yaml`)

      at requireTestModeEnabled (../../../node_modules/@pulumi/command/node_modules/@pulumi/runtime/settings.ts:153:15)
      at Object.getMonitor (../../../node_modules/@pulumi/command/node_modules/@pulumi/runtime/settings.ts:255:13)
      at Object.registerResource (../../../node_modules/@pulumi/command/node_modules/@pulumi/runtime/resource.ts:288:21)
      at new Resource (../../../node_modules/@pulumi/command/node_modules/@pulumi/resource.ts:393:13)
      at new CustomResource (../../../node_modules/@pulumi/command/node_modules/@pulumi/resource.ts:772:9)
      at new Command (../../../node_modules/@pulumi/local/command.ts:143:9)
      at new VirtualminDomain (index.ts:102:24)
      at Object.pulumiProgram [as init] (index.test.ts:12:30)
      at Stack.<anonymous> (../../../node_modules/@pulumi/runtime/stack.ts:77:39)
      at fulfilled (../../../node_modules/@pulumi/pulumi/runtime/stack.js:18:58)

  ● Test suite failed to run

    Detected multiple versions of '@pulumi/pulumi' in use in an inline automation api program.
    Use the yarn 'resolutions' field to pin to a single version: https://github.com/pulumi/pulumi/issues/5449.

      at runSxSCheck (../../../node_modules/@pulumi/runtime/settings.ts:542:15)
      at Object.getMonitor (../../../node_modules/@pulumi/runtime/settings.ts:222:5)
      at Object.<anonymous> (../../../node_modules/@pulumi/runtime/resource.ts:773:25)
      at fulfilled (../../../node_modules/@pulumi/pulumi/runtime/resource.js:18:58)

  ● Test suite failed to run

    Detected multiple versions of '@pulumi/pulumi' in use in an inline automation api program.
    Use the yarn 'resolutions' field to pin to a single version: https://github.com/pulumi/pulumi/issues/5449.

      at runSxSCheck (../../../node_modules/@pulumi/runtime/settings.ts:542:15)
      at Object.getMonitor (../../../node_modules/@pulumi/runtime/settings.ts:222:5)
      at Object.<anonymous> (../../../node_modules/@pulumi/runtime/resource.ts:773:25)
      at fulfilled (../../../node_modules/@pulumi/pulumi/runtime/resource.js:18:58)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        17.573 s, estimated 19 s
Ran all test suites.
```
[virtualmin-domain.zip](https://github.com/pulumi/pulumi/files/9795324/virtualmin-domain.zip)

**Comment by Moshemo** [comment]
> To be clear for nodejs users, the Automation API allows one concurrent update per node process for the time being. If you want to run multiple updates in parallel, they will need to be in separate node processes.

Does this still relevant ? 
Am I able to run nodeJS app in parallel with out separate node processes today ?

**Comment by Frassle** [comment]
It's not still relevant, automation API should correctly run updates in parallel now.
