### ISSUE TITLE
Dynamic providers fail to load when used from multi-lang components

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5455]
For example, consider a component written in TypeScript that uses a dynamic provider, and a Python program that uses the component. The Python program will fail during `pulumi up` with:

```
    internal/modules/cjs/loader.js:638
        throw err;
        ^
    Error: Cannot find module '@pulumi/pulumi/cmd/dynamic-provider'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
        at Function.resolve (internal/modules/cjs/helpers.js:33:19)
        at [eval]:1:21
        at Script.runInThisContext (vm.js:122:20)
        at Object.runInThisContext (vm.js:329:38)
        at Object.<anonymous> ([eval]-wrapper:6:22)
        at Module._compile (internal/modules/cjs/loader.js:778:30)
        at evalScript (internal/bootstrap/node.js:590:27)
        at startup (internal/bootstrap/node.js:265:9)
        at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

The problem is due to the `pwd` used when launching the `pulumi-resource-pulumi-nodejs` plugin: it is currently being set to the dir of the Pulumi program.

In the case of our example, the Pulumi program is written in Python and doesn’t have a `node_modules,` so when `pulumi-resource-pulumi-nodejs` is run (which is just a bash script), it can’t find the `@pulumi/pulumi/cmd/dynamic-provider` script its looking for:

https://github.com/pulumi/pulumi/blob/6e0163b248d0fb3d6db61de6c963fb89625e3c8f/sdk/nodejs/dist/pulumi-resource-pulumi-nodejs#L1-L5

If the `pwd` is hardcoded to be the dir of the component (which has a `node_modules`), everything works as expected.

We’ll need to flow the `pwd` through somehow such that if `pulumi-resource-pulumi-nodejs` is being launched due to use from a component, it uses the `pwd` of the component, rather than the `pwd` of the program.

**Comment by justinvp** [comment]
While we definitely want to make sure dynamic providers work with multi-language components, we could consider working around this in the short-term for EKS by changing the dynamic providers in EKS to be custom resources implemented via the new provider plugin (would need to ensure the eks resource plugin is installed as part of depending on `@pulumi/eks`).

**Comment by delitescere** [comment]
This _also_ is an issue with non-relative imports in TypeScript files and relying on the `paths` in `tsconfig.json` (resulting in compile-time "cannot find module" errors, and _also_ for any nodejs lambdas that import modules from parent directories (resulting in run-time errors about unable to load tslib).

The workaround is to perform the following from the same directory as `rootDir` in `tsconfig.json` / the directory with `node_modules` / the top-level directory of your project:

```shell
NODE_PATH=$PWD pulumi up
```

**Comment by delitescere** [comment]
**NB: This also works (and is probably better than my previous comment, above)**

For each non-relative import (i.e. for every "paths" entry in `tsconfig.json`), simply create a "[workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces)" entry in `package.json`. You don't need to create a `package.json` in each corresponding directory.

For example, assume `index.ts` is the entry point for my Pulumi program, `infra` is the directory holding all the TypeScript definitions of resources using the Pulumi SDK, and `backend` is the runtime NodeJS Lambda code. This lets me keep things separate so I can manage and test runtime app concerns separately to Pulumi infrastructure concerns. However, the "API Gateway" resource references the Lambda code. Given that Lambda code is in a non-child directory, the `tsconfig.json` "paths" allows TypeScript and tooling to find that code, but not ts-node which Pulumi uses to compile it and the code isn't packaged properly (or found at runtime) when API Gateway executes the Lambda. So, the `package.json` "workspaces" does the extra job, without the blunt hammer of `NODE_PATH` when Pulumi is compiling and packaging the code.

```shell
.
├── package.json
├── tsconfig.json
├── Pulumi.prod.yaml
├── Pulumi.yaml
├── index.ts
├── backend
│   ├── contact
│   │   └── lambda.ts
├── infra
│   ├── contact
│   │   ├── apigw.ts
```

`infra/contact/apigw.ts`:
```typescript
import {ContactLambda} from 'backend/contact/lambda';
import * as cloud from '@pulumi/cloud';
...
export class ContactApi {
...
    cloud.API.post('/contact', ContactApi.createContact);
...
  static async createContact(req: cloud.Request, res: cloud.Response) {
    await new ContactLambda('contact').createContact(req, res);
  }
}
```

`tsconfig.json`:
```json
{
  "compilerOptions": {
...
    "baseUrl": "./",
    "paths": {
      "backend/*": [
        "backend/*"
      ],
...
}
```

`package.json`:
```json
...
  "workspaces": [
    "backend"
  ],
...
```

**Comment by EvanBoyle** [comment]
Automation API side of things was tracked and fixed in https://github.com/pulumi/pulumi/issues/5578

**Comment by EvanBoyle** [comment]
We unintentionally made this worse when we added single binary node providers. Now, there is no node_modules folder in the plugin directory. We could add it back, but that's another 90MB which sort of defeats the purpose of the original change. 

https://github.com/pulumi/pulumi-component-provider-ts-boilerplate/pull/6
