### ISSUE TITLE
pulumi preview fails with --policy-pack and --json

### ISSUE THREAD

**Issue by thewizarodofoz** [pulumi/pulumi#5505]
`pulumi preview` fails with these options: `--policy-pack <policypack-path> --json`

## Expected Behavior

run preview and write results as json

## Current Behavior

error:
```bash
$ pulumi preview --policy-pack policypack --json
panic: fatal: A failure has occurred: unknown event type 'policy-violation'

goroutine 52 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /private/tmp/pulumi-20200921-51897-11yu5ss/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Failf(0x54c4f77, 0x17, 0xc00072f8a0, 0x1, 0x1)
        /private/tmp/pulumi-20200921-51897-11yu5ss/sdk/go/common/util/contract/fail.go:30 +0x18d
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowJSONEvents(0xc0013be100, 0x11, 0x54ab8c1, 0x7, 0xc00156c600, 0xc00156c660, 0x54a956c, 0x6, 0x100000000000000, 0x0, ...)
        /private/tmp/pulumi-20200921-51897-11yu5ss/pkg/backend/display/json.go:191 +0x1e7
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowEvents(0xc0013be100, 0x11, 0x54ab8c1, 0x7, 0xc000612038, 0x4, 0xc0010b9950, 0xa, 0xc00156c600, 0xc00156c660, ...)
        /private/tmp/pulumi-20200921-51897-11yu5ss/pkg/backend/display/display.go:47 +0x3d6
created by github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).apply
        /private/tmp/pulumi-20200921-51897-11yu5ss/pkg/backend/filestate/backend.go:470 +0x325
error Command failed with exit code 2.

```

## Steps to Reproduce

1. create a policy pack in <policypack-path>
2. run `pulumi preview --policy-pack <policypack-path> --json`

**Comment by stack72** [comment]
Hi @thewizarodofoz 

This is closed via https://github.com/pulumi/pulumi/pull/5569 and https://github.com/pulumi/pulumi/pull/5610

These fixes are available in v2.12.2

Paul
