### ISSUE TITLE
Re-opening 5295: Serialization fails when testing - mock

### ISSUE THREAD

**Issue by edmondo1984** [pulumi/pulumi#5597]
When trying to provide a mock instance for testing, the test fails but after the assertion. has been run

```
@pulumi.runtime.test
def test_ephemeral_project():
    project_name = "my-project-name"
    root_project_name = "root-project-name"
    organization_name = "root-organization-name"
    args = ProjectArgs(project_name, root_project_name, organization_name)
    project = Project("name", args)

    def test_properties(args):
        new_project_id = args[0]
        assert new_project_id == project_name
        import pdb
        pdb.set_trace()

    Output.all(project.new_project_id).apply(test_properties)


```

```

s = None

    def _bytes_from_decode_data(s):
        if isinstance(s, str):
            try:
                return s.encode('ascii')
            except UnicodeEncodeError:
                raise ValueError('string argument should contain only ASCII characters')
        if isinstance(s, bytes_types):
            return s
        try:
            return memoryview(s).tobytes()
        except TypeError:
            raise TypeError("argument should be a bytes-like object or ASCII "
>                           "string, not %r" % s.__class__.__name__) from None
E           TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

../../../../../../.pyenv/versions/3.7.3/lib/python3.7/base64.py:46: TypeError
---------------------------------------------------------------------------------------------- Captured log call -----------------------------------------------------------------------------------------------
ERROR    asyncio:base_events.py:1608 Task exception was never retrieved
future: <Task finished coro=<Output.apply.<locals>.run() done, defined at /Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi/output.py:148> exception=Exit('Quitting debugger')>
Traceback (most recent call last):
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi/output.py", line 175, in run
    transformed: Input[U] = func(value)
  File "/Users/edmondoporcu1/Development/personal/unopac/my-project/git_submodules/pulumi-utils/tests/projects/test_ephemeral_project.py", line 33, in test_properties
    pdb.set_trace()
  File "/Users/edmondoporcu1/.pyenv/versions/3.7.3/lib/python3.7/bdb.py", line 92, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/Users/edmondoporcu1/.pyenv/versions/3.7.3/lib/python3.7/bdb.py", line 151, in dispatch_return
    self.user_return(frame, arg)
  File "/Users/edmondoporcu1/.pyenv/versions/3.7.3/lib/python3.7/pdb.py", line 293, in user_return
    self.interaction(frame, None)
  File "/Users/edmondoporcu1/.pyenv/versions/3.7.3/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Users/edmondoporcu1/.pyenv/versions/3.7.3/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Users/edmondoporcu1/.pyenv/versions/3.7.3/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/edmondoporcu1/.pyenv/versions/3.7.3/lib/python3.7/pdb.py", line 418, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/Users/edmondoporcu1/.pyenv/versions/3.7.3/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/_pytest/debugging.py", line 195, in do_quit
    outcomes.exit("Quitting debugger")
  File "/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/_pytest/outcomes.py", line 119, in exit
    raise Exit(msg, returncode)
_pytest.outcomes.Exit: Quitting debugger
=============================================================================================== warnings summary ===============================================================================================
/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/parver/_version.py:116
  /Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/parver/_version.py:116: DeprecationWarning: The usage of `cmp` is deprecated and will be removed on or after 2021-06-01.  Please use `eq` and `order` instead.
    @attr.s(frozen=True, repr=False, cmp=False)

/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/compute/autoscalar.py:15
  /Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/compute/autoscalar.py:15: DeprecationWarning: gcp.compute.Autoscalar has been deprecated in favor of gcp.compute.Autoscaler
    warnings.warn("gcp.compute.Autoscalar has been deprecated in favor of gcp.compute.Autoscaler", DeprecationWarning)

/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/compute/autoscalar.py:19
  /Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/compute/autoscalar.py:19: DeprecationWarning: gcp.compute.Autoscalar has been deprecated in favor of gcp.compute.Autoscaler
    warnings.warn("gcp.compute.Autoscalar has been deprecated in favor of gcp.compute.Autoscaler", DeprecationWarning)

/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/compute/manged_ssl_certificate.py:15
  /Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/compute/manged_ssl_certificate.py:15: DeprecationWarning: gcp.compute.MangedSslCertificate has been deprecated in favor of gcp.compute.ManagedSslCertificate
    warnings.warn("gcp.compute.MangedSslCertificate has been deprecated in favor of gcp.compute.ManagedSslCertificate", DeprecationWarning)

/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/compute/manged_ssl_certificate.py:19
  /Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/compute/manged_ssl_certificate.py:19: DeprecationWarning: gcp.compute.MangedSslCertificate has been deprecated in favor of gcp.compute.ManagedSslCertificate
    warnings.warn("gcp.compute.MangedSslCertificate has been deprecated in favor of gcp.compute.ManagedSslCertificate", DeprecationWarning)

/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/kms/registry.py:15
  /Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/kms/registry.py:15: DeprecationWarning: gcp.kms.Registry has been deprecated in favor of gcp.iot.Registry
    warnings.warn("gcp.kms.Registry has been deprecated in favor of gcp.iot.Registry", DeprecationWarning)

/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/kms/registry.py:19
  /Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/kms/registry.py:19: DeprecationWarning: gcp.kms.Registry has been deprecated in favor of gcp.iot.Registry
    warnings.warn("gcp.kms.Registry has been deprecated in favor of gcp.iot.Registry", DeprecationWarning)

/Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/monitoring/get_secret_version.py:17
  /Users/edmondoporcu1/Library/Caches/pypoetry/virtualenvs/my-project-y7f3eZBB-py3.7/lib/python3.7/site-packages/pulumi_gcp/monitoring/get_secret_version.py:17: DeprecationWarning: gcp.monitoring.getSecretVersion has been deprecated in favor of gcp.secretmanager.getSecretVersion
    warnings.warn("gcp.monitoring.getSecretVersion has been deprecated in favor of gcp.secretmanager.getSecretVersion", DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================================================================================== short test summary info ============================================================================================
FAILED tests/projects/test_ephemeral_project.py::test_ephemeral_project - TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

```

**Comment by leezen** [comment]
I'm a bit confused by what you're asking here, but given the title, I'll re-open #5295, close this and let's try to continue the conversation there.
