### ISSUE TITLE
`panic: interface conversion: interface {} is string, not int` - when using `awsx.lb.ApplicationListener` with `awsx.ecs.FargateService`

### ISSUE THREAD

**Issue by tyronedougherty** [pulumi/pulumi#5633]
Hi there!

Running the following piece of [sample code from the docs](https://www.pulumi.com/docs/guides/crosswalk/aws/ecs/#creating-a-load-balanced-ecs-service) throws an error:

```
// Create a load balancer on port 80 and spin up two instances of Nginx.
const lb = new awsx.lb.ApplicationListener("nginx", { port: 80 });
const nginx = new awsx.ecs.FargateService("nginx", {
  taskDefinitionArgs: {
    containers: {
      nginx: {
        image: "nginx",
        memory: 128,
        portMappings: [ lb ],
      },
    },
  },
  desiredCount: 2,
});
```

The error is:

```
panic: interface conversion: interface {} is string, not int
    goroutine 305 [running]:
    github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEcsLoadBalancerHash(0x616b8a0, 0xc0021ace40, 0xc0021a2cf0)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-aws@v1.38.1-0.20201023104507-9632e543c200/aws/resource_aws_ecs_service.go:1169 +0x47f
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0xc0021a2ce0, 0x616b8a0, 0xc0021ace40, 0x1f6fe87, 0xc0021a2b40)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:251 +0x3d
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc0021a2ce0, 0x616b8a0, 0xc0021ace40, 0x0, 0x616b8a0, 0xc0021ace40)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:231 +0x83
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).Add(...)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:75
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.(*diffFieldReader).readSet(0xc0021a2b40, 0xc0021a1d60, 0x1, 0x1, 0xc000f66640, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.11.1-0.20201020163502-64cff1e50894/pkg/tfshim/sdk-v2/diff_reader.go:430 +0x3c5
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.(*diffFieldReader).ReadField(0xc0021a2b40, 0xc0021a1d60, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.11.1-0.20201020163502-64cff1e50894/pkg/tfshim/sdk-v2/diff_reader.go:54 +0x2c7
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.v2InstanceState.Object.func1(0xc0020c8ff0, 0xd, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.11.1-0.20201020163502-64cff1e50894/pkg/tfshim/sdk-v2/instance_state.go:73 +0x185
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.v2InstanceState.Object(0xc000496d20, 0xc0020fda20, 0x7bc9a00, 0xc000f60210, 0x100cb68, 0xc001bcd620, 0x1009fe8)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.11.1-0.20201020163502-64cff1e50894/pkg/tfshim/sdk-v2/instance_state.go:90 +0x3f9
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformResult(0x7be6dc0, 0xc0015e60a0, 0x7bae1a0, 0xc0021a1b70, 0x7bc9a00, 0xc000f60210, 0xc00160a0c0, 0xc0020ff620, 0x1, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.11.1-0.20201020163502-64cff1e50894/pkg/tfbridge/schema.go:594 +0x224
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Create(0xc000d07880, 0x7bad060, 0xc0020ff4a0, 0xc0020d14f0, 0xc000d07880, 0x6282a01, 0xc002194100)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.11.1-0.20201020163502-64cff1e50894/pkg/tfbridge/provider.go:819 +0x97c
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Create_Handler.func1(0x7bad060, 0xc0020ff4a0, 0x6d2e000, 0xc0020d14f0, 0x6d87fc0, 0xbef1038, 0x7bad060, 0xc0020ff4a0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.12.0/proto/go/provider.pb.go:2244 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x7bad060, 0xc0020ff350, 0x6d2e000, 0xc0020d14f0, 0xc0020fd4a0, 0xc0020fd4c0, 0x0, 0x0, 0x7ae5580, 0xc0002bc130)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2eb
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Create_Handler(0x6e7bda0, 0xc000d07880, 0x7bad060, 0xc0020ff350, 0xc0020eb320, 0xc0015e0b60, 0x7bad060, 0xc0020ff350, 0xc002190400, 0x396)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.12.0/proto/go/provider.pb.go:2246 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000d076c0, 0x7bd3840, 0xc0016cc000, 0xc0020a6900, 0xc001678300, 0xbeb2cc8, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
    google.golang.org/grpc.(*Server).handleStream(0xc000d076c0, 0x7bd3840, 0xc0016cc000, 0xc0020a6900, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001640ac0, 0xc000d076c0, 0x7bd3840, 0xc0016cc000, 0xc0020a6900)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x204
 
    error: preview failed

```

Got any ideas how to resolve, or does this require a pull request and new release to fix?

Thanks! 😄

**Comment by njbmartin** [comment]
Have you tried downgrading Pulumi to 2.11.2? I've run into issues with 2.12.x and AWS. #5634

**Comment by tyronedougherty** [comment]
Darn - I was going to try downgrading but it looks like they've gotten rid of the older versions from homebrew! 😢 

Only version is latest:

```
$> brew list --versions pulumi
pulumi 2.12.1
```

Seems like a separate issue that needs to be resolved - I've opened #5635 for that too.

**Comment by leezen** [comment]
Related symptom: https://github.com/pulumi/pulumi-aws/issues/1188

But let's track the broader issue here.

**Comment by leezen** [comment]
As mentioned in pulumi-aws#1188:
> It seems this is somehow related to the recently released preview functionality. We'll continue to investigate. In the meantime, as mentioned above, downgrading is one path forward. Alternatively, you can also set the environment variable PULUMI_DISABLE_PROVIDER_PREVIEW=1 (or true) with pulumi CLI 2.12.x and should be able to proceed.

**Comment by LeslieOA** [comment]
FYI: I'm still experiencing this issue with Pulumi `v2.14.0`.
@leezen's solution works for the meantime.

Code:  
```
const sslCertValidationRecord = new aws.route53.Record(`ssl-cert-validation-record`, {
	zoneId: apiDnsZone.zoneId,
	name: sslCert.domainValidationOptions[0].resourceRecordName,
	type: sslCert.domainValidationOptions[0].resourceRecordType,
	records: [ sslCert.domainValidationOptions[0].resourceRecordValue],
	ttl: 10 * 60, // 10mins
});
```

Error:  
```
error: aws:route53/record:Record resource 'ssl-cert-validation-record' has a problem: Required attribute is not set
error: aws:route53/record:Record resource 'ssl-cert-validation-record' has a problem: Required attribute is not set
```

**Comment by lukehoban** [comment]
> FYI: I'm still experiencing this issue with Pulumi v2.14.0.

@LeslieOA Just to make sure - this was fixed in the `@pulumi/aws` package.  Did you update your version of that package?

**Comment by LeslieOA** [comment]
> > FYI: I'm still experiencing this issue with Pulumi v2.14.0.
> 
> @LeslieOA Just to make sure - this was fixed in the `@pulumi/aws` package. Did you update your version of that package?

Heya @lukehoban. 
Just updated the package to `^3.14.0`: exact same issue. My `package.json` previously had `^3.0.0`.

leezen's suggestion helped, but then I [encountered the same issue as this user](https://github.com/pulumi/pulumi/issues/5813#issuecomment-731862883):

```
  aws:acm:CertificateValidation (sslCertValidationIssued):
    error: 1 error occurred:
        * Error describing created certificate: Expected certificate to be issued but was in state PENDING_VALIDATION
```

**Comment by maganuk** [comment]
@lukehoban tried this with all the versions back to 3.9.0 - all of them throw the error

     aws:route53:Record (example-cert-validation-record-0):
        error: aws:route53/record:Record resource 'example-cert-validation-record-0' has a problem: Required attribute is not set
        error: aws:route53/record:Record resource 'example-cert-validation-record-0' has a problem: Required attribute is not set

3.8.0 is working fine. The npm module `pulumi-acm-dns-validated-cert` can be used to validate the issue. 

Example code (Using the npm module): 

    const cert = new acmCert.ACMCert('example-cert', {
      subject: 'www.sceptor.io',
      zoneId: route53
    });

**Comment by lukehoban** [comment]
Reopening - as we are still seeing folks hit variants of this issue.
