### ISSUE TITLE
Pulumi stack ls error

### ISSUE THREAD

**Issue by unaiwillr** [pulumi/pulumi#5658]
Listing pulumi stacks (with `pulumi stack ls`) created a one off error. I am connecting to an S3 backend. The next time I issued pulumi stack ls no error occured.

## Expected Behavior
Stacks should be listed

## Current Behavior
The following error occured:
```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v2.12.1
Go Version:       go1.15.2
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            fatal: An assertion has failed: localBackend GetStack returned non-localStack

goroutine 1 [running]:
runtime/debug.Stack(0xc00055d8b0, 0x1953dc0, 0xc001bb45f0)
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/debug/stack.go:24 +0x9f
main.panicHandler()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x73
panic(0x1953dc0, 0xc001bb45f0)
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/panic.go:969 +0x175
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0xc000119100, 0x1cf97d1, 0x2d, 0x0, 0x0, 0x0)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:33 +0x1a5
github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).ListStacks(0xc0001191d0, 0x1ff6c20, 0xc0000440e0, 0x0, 0xc00024cff0, 0x0, 0x0, 0x0, 0x201ddc0, 0xc0001191d0, ...)
	/Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:330 +0x16f
main.newStackLsCmd.func1(0xc0006a4840, 0x2c0a220, 0x0, 0x0, 0x11, 0x11)
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/stack_ls.go:105 +0x24f
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunFunc.func1(0xc0006a4840, 0x2c0a220, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:96 +0x51
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc0006a4840, 0x2c0a220, 0x0, 0x0)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc0006a4840, 0x2c0a220, 0x0, 0x0, 0xc0006a4840, 0x2c0a220)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000866840, 0x15, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x4d
```

## Steps to Reproduce
Entering `pulumi stack ls` with an S3 backend. Only occurred as soon as I set environment variables in my new terminal session. Same terminal session, entered the same command again gave expected behavior. First and only time seeing this error occur after a lot of use. Unsure how to always reproduce this error, but hopefully this bug report helps.

## Context (Environment)
S3 backend, new terminal session, error only occurred once and behaved as expected in the same terminal session after re-executing the command. On Ubuntu 20.04 with Pulumi version `v2.12.1`. Did not break my workflow, just trying to help identify a (seemingly rare) issue.

Commands executed before `pulumi stack ls` (`source .env.dev`) contents:
```bash
#!/bin/bash
export AWS_PROFILE=<aws profile>
export AWS_REGION=<aws region>
export PULUMI_CONFIG_PASSPHRASE=<config passphrase>
pulumi login --cloud-url s3://<bucket name>
source venv/bin/activate
```

With the following pip dependencies installed:
```
pulumi>=2.0.0,<3.0.0
pulumi-aws>=2.0.0,<3.0.0
pulumi-kubernetes>=2.0.0,<3.0.0
jinja2
pyyaml
```

**Comment by morganatkins24** [comment]
Just encountered the same error while using the Pulumi Docker container, also while using the S3 Cloud backend

Container version: v2.23.1 (pulumi/pulumi@sha256:790b8932c376)

Error message
```================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v2.23.1
Go Version:       go1.16.2
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            fatal: An assertion has failed: localBackend GetStack returned non-localStack
goroutine 1 [running]:
runtime/debug.Stack(0xc0006fb888, 0x19b7280, 0xc000a365f0)
	/Users/runner/hostedtoolcache/go/1.16.2/x64/src/runtime/debug/stack.go:24 +0x9f
main.panicHandler()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x76
panic(0x19b7280, 0xc000a365f0)
	/Users/runner/hostedtoolcache/go/1.16.2/x64/src/runtime/panic.go:965 +0x1b9
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0xc00007ec00, 0x1d657aa, 0x2d, 0x0, 0x0, 0x0)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:33 +0x1a5
github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).ListStacks(0xc00007ec00, 0x209ac08, 0xc00004a0c0, 0x0, 0xc00065a320, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:348 +0x165
main.newStackLsCmd.func1(0xc00040f080, 0x2cc91a8, 0x0, 0x0, 0xc0006a4500, 0xc00069d830)
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/stack_ls.go:105 +0x276
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunFunc.func1(0xc00040f080, 0x2cc91a8, 0x0, 0x0, 0xc000947d30, 0x0)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:96 +0x51
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc00040f080, 0x2cc91a8, 0x0, 0x0)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc00040f080, 0x2cc91a8, 0x0, 0x0, 0xc00040f080, 0x2cc91a8)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000bf340, 0xc0000482a0, 0xc000064748, 0x2c9ac60)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x4d
```

Pip Modules:
* pyyaml 5.3.1
* pulumi 2.23.1
* pulumi-aws 3.34.1
* jinja2 2.11.3

**Comment by lukehoban** [comment]
I believe this could happen previously is one of the stacks was not found.  This assert was removed, and the code should now either work or fail with a useful error message in these cases as of https://github.com/pulumi/pulumi/pull/7660.
