### ISSUE TITLE
Cannot run Pulumi with python runtime

### ISSUE THREAD

**Issue by huydinhle** [pulumi/pulumi#5660]
Pulumi up output, it was working fine the day before. I tested on both pulumi 2.12.0 and 2.12.1
```  pulumi:pulumi:Stack (IAM-integration):
    Traceback (most recent call last):
      File "/Users/huyle/bin/pulumi-language-python-exec", line 14, in <module>
        import pulumi
      File "/Users/huyle/src/bitbucket.org/picktrace/pulumi/infrastructure/iam/venv/lib/python3.9/site-packages/pulumi/__init__.py", line 33, in <module>
        from .config import (
      File "/Users/huyle/src/bitbucket.org/picktrace/pulumi/infrastructure/iam/venv/lib/python3.9/site-packages/pulumi/config.py", line 22, in <module>
        from .output import Output
      File "/Users/huyle/src/bitbucket.org/picktrace/pulumi/infrastructure/iam/venv/lib/python3.9/site-packages/pulumi/output.py", line 32, in <module>
        from . import runtime
      File "/Users/huyle/src/bitbucket.org/picktrace/pulumi/infrastructure/iam/venv/lib/python3.9/site-packages/pulumi/runtime/__init__.py", line 44, in <module>
        from .invoke import (
      File "/Users/huyle/src/bitbucket.org/picktrace/pulumi/infrastructure/iam/venv/lib/python3.9/site-packages/pulumi/runtime/invoke.py", line 43, in <module>
        from google.protobuf.pyext._message import SetAllowOversizeProtos  # pylint: disable-msg=E0611
    ModuleNotFoundError: No module named 'google.protobuf.pyext._message'
    It looks like the Pulumi SDK has not been installed. Have you run pip install?
    If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.

    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by stack72** [comment]
Hi @huydinhle 

Sorry that this has happened - this is because there is an open issue to support Python 3.9 for Pulumi

I am going to close this issue as #5662 is going to be the place we track that work

Thanks

Paul
