### ISSUE TITLE
Unittest and get_subscription()

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi#5671]
Hi,
seems that the function `azure.core.get_subscription()` does not work with `unittest`.
I managed to replicated the issue using these files:
- `vm.py`
```python
import pulumi_azure as azure
SUBSCRIPTION=azure.core.get_subscription()
```
- `test.py`
```python
import pulumi

class PulumiMocks(pulumi.runtime.Mocks):
    def new_resource(self, type_, name, inputs, provider, id_):
        return [name + '_id', inputs]
    def call(self, token, args, provider):
        return {}

pulumi.runtime.set_mocks(PulumiMocks())
import vm
```

```sh
$ python3 -m unittest test
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.8/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/lib/python3.8/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/usr/lib/python3.8/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.8/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/vasco/error/test.py", line 14, in <module>
    import vm
  File "/home/vasco/error/vm.py", line 3, in <module>
    SUBSCRIPTION=azure.core.get_subscription().id
  File "/usr/local/lib/python3.8/dist-packages/pulumi_azure/core/get_subscription.py", line 156, in get_subscription
    display_name=__ret__.display_name,
```

Any ideas?

Thanks

**Comment by yellowhat** [comment]
Are there any update on this?

Thanks

**Comment by komalali** [comment]
Hey @yellowhat unfortunately I haven't had the time to look into this more deeply. It looks like the traceback you posted isn't complete, and I'm not exactly sure what your test is trying to test. It looks like you're importing your `vm` module at the end of the `test.py` file. Can you provide some more information about what the purpose is there?

**Comment by yellowhat** [comment]
So this is just an example to replicate the bug.
The `SUBSCRIPTION=azure.core.get_subscription()` is part of a real deployment where I need the Subscription id, for example defining the scope of a RoleDefinition.

As I would like to use Pulumi Mocks for unit testing, I suppose that mock should substitute the real function `get_subscription()` attributes with dummy ones:
- azure.core.get_subscription().id: 00000000-0000-0000-0000-000000000000
- azure.core.get_subscription().display_name: "subscription"

Does this make sense?

Thanks

**Comment by komalali** [comment]
Yup, that makes sense thanks for filling in the details. So you actually have to mock out your function (i.e. `azure.core.get_subscription()`) yourself. Since `get_subscription` is a function, you'd have to use the `call()` method in your Mocks class. If you were mocking a resource (like `azure.storage.Blob`) you would use the `new_resource` method of `Mocks`

Specifically, for this case, your mock should look like:

```python
class PulumiMocks(pulumi.runtime.Mocks):
    def new_resource(self, type_, name, inputs, provider, id_):
        return [name + '_id', inputs]
    def call(self, token, args, provider):
		if token == "azure:core/getSubscription:getSubscription":
        	return {
				"id": "00000000-0000-0000-0000-000000000000",
				"display_name": "subscription"
			}
		else:
			return {}
```
