### ISSUE TITLE
Exception: cannot unmarshal output properties: unrecognized signature

### ISSUE THREAD

**Issue by pavankumarkatakam** [pulumi/pulumi#5697]
Getting some GRPC related error, when using the stack reference using backend as S3.
## Expected Behavior
Able to use Stack reference in python while using the backed as S3, im using the same backend for two projects
## Current Behavior
Getting error while preview and up commands, when used backend S3 and StackReference

## Context (Environment)
Pulumi: v2.12.1
pulumi-kubernetes: 2.6.3

## Trace Logs:
```
Diagnostics:
  pulumi:pulumi:Stack (infra5-networking-networking.dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/administrator/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/storage/work/gitlab/infra5/networking/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/storage/work/gitlab/infra5/networking/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/home/storage/work/gitlab/infra5/networking/venv/lib/python3.6/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/storage/work/gitlab/infra5/networking/venv/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 475, in do_register_resource_outputs
        await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/storage/work/gitlab/infra5/networking/venv/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 473, in do_rpc_call
        raise Exception(details)
    Exception: cannot unmarshal output properties: unrecognized signature '5cf8f73096256a8f31e491e813e4eb8e' in property map
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
 

```

**Comment by pavankumarkatakam** [comment]
I installed pulumi v2.13.1 but still getting the same error
```
Diagnostics:
  pulumi:pulumi:Stack (infra5-networking-networking.dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/administrator/.pulumi/bin/pulumi-language-python-exec", line 95, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/storage/work/gitlab/infra5/networking/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/storage/work/gitlab/infra5/networking/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/home/storage/work/gitlab/infra5/networking/venv/lib/python3.6/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/home/storage/work/gitlab/infra5/networking/venv/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 475, in do_register_resource_outputs
        await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/storage/work/gitlab/infra5/networking/venv/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 473, in do_rpc_call
        raise Exception(details)
    Exception: cannot unmarshal output properties: malformed resource reference: id not a string
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
 

```

**Comment by leezen** [comment]
Sorry about that -- there was another issue we also discovered related to this. You'll want to bump both the package version and CLI to version 2.13.2.

**Comment by pavankumarkatakam** [comment]
Yesh, working with pulumi version 2.13.2. Thanks.
