### ISSUE TITLE
Import code-gen for Python ResourceOptions is incorrect

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#5750]
The code emitted for imported Python resources is incorrect, because `ResourceOptions` is not qualified.

## Expected Behavior

The code emitted should be correct.

## Current Behavior

If I import any resource with Python, the generated code is wrong and won't run as-is.

## Steps to Reproduce

Import a resource. Since they will be protected, any resource will do.

For example, an EC2 instance: `pulumi import aws:ec2/instance:Instance webServer i-0d11b6aaae8fc7f8`.

This yields the following import code:

```python
import pulumi
import pulumi_aws as aws

web_server = aws.ec2.Instance("webServer",
    ami="ami-0947d2ba12ee1ff75",
    get_password_data=False,
    instance_type="t2.micro",
    source_dest_check=True,
    opts=ResourceOptions(protect=True))
```

Notice the use of `ResourceOptions`, which resides in the `pulumi` module, is not qualified. If you use this code as-is, it will fail with an error, `NameError: name 'ResourceOptions' is not defined`.

The code should instead be

```python
import pulumi
import pulumi_aws as aws

web_server = aws.ec2.Instance("webServer",
    ami="ami-0947d2ba12ee1ff75",
    get_password_data=False,
    instance_type="t2.micro",
    source_dest_check=True,
    opts=pulumi.ResourceOptions(protect=True))
```

## Context (Environment)

This happens with Pulumi v2.13.2.

**Comment by jdoss** [comment]
This seems to be an issue again in 

```
$ pulumi version
v3.30.0
```
I was trying to `ignore_changes=['boot_disk']`:

```
create_instance = gcp.compute.Instance(
    f'{server}-{server_id}',
    opts=ResourceOptions(ignore_changes=['boot_disk']),
    machine_type=server_data['server_type'],
    allow_stopping_for_update=True,
    zone=server_zone,
    tags=server_data['server_tags'],
    can_ip_forward=True,

    ***snip***
```

and it barfed out this:

```
Diagnostics:
  pulumi:pulumi:Stack (internal):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/user/.pulumi/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib64/python3.10/asyncio/base_events.py", line 646, in run_until_complete
        return future.result()
      File "/home/user/src/project/internal/venv/lib64/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/user/src/project/internal/venv/lib64/python3.10/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/home/user/src/project/internal/venv/lib64/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/home/user/src/project/internal/venv/lib64/python3.10/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/home/user/.pulumi/bin/pulumi-language-python-exec", line 106, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/lib64/python3.10/runpy.py", line 286, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/home/user/src/project/internal/./__main__.py", line 23, in <module>
        instances = create_instances(config_data, network, region)
      File "/home/user/src/project/internal/./instances.py", line 301, in create_instances
        opts=ResourceOptions(ignore_changes=['boot_disk'])
    NameError: name 'ResourceOptions' is not defined
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Updating to `opts=pulumi.ResourceOptions(ignore_changes=['boot_disk']), fixed the issue.
