### ISSUE TITLE
panic: interface conversion: interface {} is string, not bool goroutine 211 [running] on cli v2.13.2 in aws

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi#5770]
## Expected Behavior
`pulumi up` should have a working `preview` when on version: `v2.13.2` in aws.
language: typescript
aws sdk:
```
{
    "name": "service-repro",
    "devDependencies": {
        "@types/node": "^10.0.0"
    },
    "dependencies": {
        "@pulumi/aws": "^3.0.0",
        "@pulumi/awsx": "^0.22.0",
        "@pulumi/pulumi": "^2.0.0"
    }
}
```
language: typescript
 
## Current Behavior

`pulumi up` does this:
```
 panic: interface conversion: interface {} is string, not bool
    goroutine 211 [running]:
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.SerializeValueForHash(0xc001b78ef0, 0x5b8e640, 0x78f4630, 0xc000ff4b40)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/serialize.go:18 +0x965
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.SerializeResourceForHash(0xc001b78ef0, 0x61f0b20, 0xc001ceb2f0, 0xc000fdda20)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/serialize.go:115 +0x36e
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.HashResource.func1(0x61f0b20, 0xc001ceb2f0, 0xc001ccfd10)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:32 +0x68
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0xc001ccfd00, 0x61f0b20, 0xc001ceb2f0, 0x1f728d7, 0xc001ccfce0)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:251 +0x3d
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc001ccfd00, 0x61f0b20, 0xc001ceb2f0, 0x0, 0x61f0b20, 0xc001ceb2f0)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:231 +0x83
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).Add(...)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:75
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.(*diffFieldReader).readSet(0xc001ccfce0, 0xc001ce7f10, 0x1, 0x1, 0xc000ff4c80, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfshim/sdk-v2/diff_reader.go:424 +0x3d9
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.(*diffFieldReader).ReadField(0xc001ccfce0, 0xc001ce7f10, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00008a400, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfshim/sdk-v2/diff_reader.go:54 +0x2c7
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.v2InstanceState.Object.func1(0xc001c90ba0, 0x10, 0xc001b79450, 0xc000a7e528)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfshim/sdk-v2/instance_state.go:73 +0x185
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.v2InstanceState.Object(0xc0004bc850, 0xc001cce9a0, 0x7c78020, 0xc000fc5aa0, 0x100cb68, 0xc001b79620, 0x1009fe8)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfshim/sdk-v2/instance_state.go:90 +0x3f9
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformResult(0x7c954e0, 0xc0015e6690, 0x7c5c4e0, 0xc001ce7f00, 0x7c78020, 0xc000fc5aa0, 0xc00163b020, 0xc001cd6300, 0x1, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfbridge/schema.go:594 +0x224
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Create(0xc00000a5a0, 0x7c5b3a0, 0xc001cd60f0, 0xc001cb2820, 0xc00000a5a0, 0x6309901, 0xc001cc7d40)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfbridge/provider.go:819 +0x97c
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Create_Handler.func1(0x7c5b3a0, 0xc001cd60f0, 0x6dc40a0, 0xc001cb2820, 0x6e1e2c0, 0xc00acb8, 0x7c5b3a0, 0xc001cd60f0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.12.0/proto/go/provider.pb.go:2244 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x7c5b3a0, 0xc001cbbf20, 0x6dc40a0, 0xc001cb2820, 0xc001cce460, 0xc001cce480, 0x0, 0x0, 0x7b92620, 0xc000800780)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2eb
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Create_Handler(0x6f13820, 0xc00000a5a0, 0x7c5b3a0, 0xc001cbbf20, 0xc001cc4ae0, 0xc0015f93a0, 0x7c5b3a0, 0xc001cbbf20, 0xc001760800, 0x3d0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.12.0/proto/go/provider.pb.go:2246 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000b296c0, 0x7c81ec0, 0xc000e64300, 0xc001720d00, 0xc0016c7560, 0xbfcc908, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
    google.golang.org/grpc.(*Server).handleStream(0xc000b296c0, 0x7c81ec0, 0xc000e64300, 0xc001720d00, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000e4e060, 0xc000b296c0, 0x7c81ec0, 0xc000e64300, 0xc001720d00)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x204
 
  aws:ec2:LaunchConfiguration (autoscaling):
    error: Preview failed: transport is closing
```

## Steps to Reproduce

Steps # 1-4.  I did with pulumi version `v2.13.2`
1.  git clone: git@github.com:eordano/autosg-repro.git
1.  `cd autosg-repro/infra`
1. `pulumi stack init dev`
1. `npm install -y`
1.  `pulumi up -y` ( This will create the vpc successfully.)  
1.  `pulumi stack`      (Grab the stack reference from `pulumi stack`)
1.  `cd ../service/`
1. `pulumi stack init dev`
1. `npm install -y`
1.  update StackReference in  https://github.com/eordano/autosg-repro/blob/main/service/index.ts#L5 from:
`shaht/infra-repro/dev` TO:  `YOURORGID/infra-repro/dev`
1.  `pulumi version` shows this: `v2.13.2`
1.  `pulumi up`   Panic will happen on preview.
1. `pulumi up` with version:  `v2.11.2` works for `preview`. There is no panic

## Context (Environment)

This impacts users using typescript with pulumi in AWS.

**Comment by stack72** [comment]
what version of pulumi-aws @tusharshahrs?

**Comment by tusharshahrs** [comment]
@stack72 
package.json.lock shows:
```
        "@pulumi/aws": {
            "version": "3.12.2",
```

```
        "@pulumi/awsx": {
            "version": "0.22.0",v
```

**Comment by michael-golden** [comment]
This issue also occurs with version 2.14.0.

**Comment by komalali** [comment]
@tusharshahrs does step 13 still panic on `up` after the `preview`?

**Comment by michael-golden** [comment]
> @tusharshahrs does step 13 still panic on `up` after the `preview`?

I can confirm that it does.

**Comment by komalali** [comment]
Thanks @michael-golden! I'm fairly confident this is https://github.com/pulumi/pulumi-terraform-bridge/issues/296, which is a work in progress. Hoping to have a fix for it soon.

**Comment by tusharshahrs** [comment]
@komalali ,
Yes, I can still reproduce it.
$ `pulumi version`
v2.14.0
~/eordano/autosg-repro/service (main)$ `pulumi up`
Previewing update (dev)

View Live: https://app.pulumi.com/.../service-repro/dev/previews/976adff4-6c81-4ba7-80db-80737e10f030
```
     Type                                                        Name                  Plan       Info
 +   pulumi:pulumi:Stack                                         service-repro-dev     create     1 error; 40 messages
o:22 ├─ awsx:x:ec2:Vpc                                           my-vpc-ref            create
 +   └─ awsx:x:ecs:Cluster                                       mycluster             create
 +      ├─ awsx:x:ec2:SecurityGroup                              mycluster             create
 +      │  ├─ awsx:x:ec2:IngressSecurityGroupRule                mycluster-containers  create
 +      │  │  └─ aws:ec2:SecurityGroupRule                       mycluster-containers  create
 +      │  ├─ awsx:x:ec2:IngressSecurityGroupRule                mycluster-ssh         create
 +      │  │  └─ aws:ec2:SecurityGroupRule                       mycluster-ssh         create
 +      │  ├─ awsx:x:ec2:EgressSecurityGroupRule                 mycluster-egress      create
 +      │  │  └─ aws:ec2:SecurityGroupRule                       mycluster-egress      create
 +      │  └─ aws:ec2:SecurityGroup                              mycluster             create
 +      ├─ awsx:x:autoscaling:AutoScalingGroup                   autoscaling           create
 +      │  └─ awsx:x:autoscaling:AutoScalingLaunchConfiguration  autoscaling           create
 +      │     ├─ aws:s3:Bucket                                   autoscaling           create
 +      │     ├─ aws:iam:Role                                    autoscaling           create
 +      │     ├─ aws:iam:RolePolicyAttachment                    autoscaling-efc8f10d  create
 +      │     ├─ aws:iam:RolePolicyAttachment                    autoscaling-5e4162cd  create
 +      │     ├─ aws:iam:InstanceProfile                         autoscaling           create
 +      │     └─ aws:ec2:LaunchConfiguration                     autoscaling           create     1 error
 +      └─ aws:ecs:Cluster                                       mycluster             create

Diagnostics:
  pulumi:pulumi:Stack (service-repro-dev):
    error: preview failed

    panic: interface conversion: interface {} is string, not bool
    goroutine 191 [running]:
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.SerializeValueForHash(0xc001a5eef0, 0x5b8e640, 0x78f4630, 0xc000ff5540)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/serialize.go:18 +0x965
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.SerializeResourceForHash(0xc001a5eef0, 0x61f0b20, 0xc001d40a20, 0xc000fdda20)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/serialize.go:115 +0x36e
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.HashResource.func1(0x61f0b20, 0xc001d40a20, 0xc001d32ab0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:32 +0x68
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0xc001d32aa0, 0x61f0b20, 0xc001d40a20, 0x1f728d7, 0xc001d32a80)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:251 +0x3d
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc001d32aa0, 0x61f0b20, 0xc001d40a20, 0x0, 0x61f0b20, 0xc001d40a20)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:231 +0x83
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).Add(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:75
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.(*diffFieldReader).readSet(0xc001d32a80, 0xc001d44620, 0x1, 0x1, 0xc000ff5680, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfshim/sdk-v2/diff_reader.go:424 +0x3d9
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.(*diffFieldReader).ReadField(0xc001d32a80, 0xc001d44620, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000584400, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfshim/sdk-v2/diff_reader.go:54 +0x2c7
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.v2InstanceState.Object.func1(0xc000431590, 0x10, 0xc001a5f450, 0xc000a7a2f8)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfshim/sdk-v2/instance_state.go:73 +0x185
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.v2InstanceState.Object(0xc000338a10, 0xc001d0f740, 0x7c78020, 0xc000fc3ce0, 0x100cb68, 0xc001a5f620, 0x1009fe8)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfshim/sdk-v2/instance_state.go:90 +0x3f9
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformResult(0x7c954e0, 0xc0015bc0f0, 0x7c5c4e0, 0xc001d44610, 0x7c78020, 0xc000fc3ce0, 0xc0015d8c30, 0xc001d0da10, 0x1, 0x0, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfbridge/schema.go:594 +0x224
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Create(0xc00012a3c0, 0x7c5b3a0, 0xc001d0d800, 0xc001d18190, 0xc00012a3c0, 0x6309901, 0xc001d15080)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.12.1/pkg/tfbridge/provider.go:819 +0x97c
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Create_Handler.func1(0x7c5b3a0, 0xc001d0d800, 0x6dc40a0, 0xc001d18190, 0x6e1e2c0, 0xc00acb8, 0x7c5b3a0, 0xc001d0d800)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.12.0/proto/go/provider.pb.go:2244 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x7c5b3a0, 0xc001d0d650, 0x6dc40a0, 0xc001d18190, 0xc001d0f200, 0xc001d0f220, 0x0, 0x0, 0x7b92620, 0xc0002b4130)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2eb
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Create_Handler(0x6f13820, 0xc00012a3c0, 0x7c5b3a0, 0xc001d0d650, 0xc00036b9e0, 0xc00159efe0, 0x7c5b3a0, 0xc001d0d650, 0xc001d1a400, 0x3d0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.12.0/proto/go/provider.pb.go:2246 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008f36c0, 0x7c81ec0, 0xc0011ee300, 0xc0016ccf00, 0xc00164f170, 0xbfcc908, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
    google.golang.org/grpc.(*Server).handleStream(0xc0008f36c0, 0x7c81ec0, 0xc0011ee300, 0xc0016ccf00, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0011bc050, 0xc0008f36c0, 0x7c81ec0, 0xc0011ee300, 0xc0016ccf00)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x204

  aws:ec2:LaunchConfiguration (autoscaling):
    error: Preview failed: transport is closing

```
