### ISSUE TITLE
[sdk/python] Passing an Output via an args class to configure a provider results in error

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5780]
A customer reported an error configuring a provider when an `Output` is passed in an args class:

```python
import pulumi
import pulumi_aws as aws

key = pulumi.Output.from_input("key")

provider = aws.Provider("test",
    ignore_tags=aws.ProviderIgnoreTagsArgs(keys=[key]))
```

Results in:

```
$ pulumi preview

...

Diagnostics:
  pulumi:pulumi:Stack (prog-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/opt/pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/output.py", line 88, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 18 more times]
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 327, in do_register
        resolver = await prepare_resource(res, ty, custom, props, opts)
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 86, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 75, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 197, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 183, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/output.py", line 175, in run
        transformed: Input[U] = func(value)
      File "/Users/user/prog/venv/lib/python3.8/site-packages/pulumi/runtime/_json.py", line 45, in to_json
        return json.dumps(serializable_obj)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
        return _default_encoder.encode(obj)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
        raise TypeError(f'Object of type {o.__class__.__name__} '
    TypeError: Object of type Output is not JSON serializable
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

A workaround is to pass the output via a dictionary, rather than via the args class:

```python
import pulumi
import pulumi_aws as aws

key = pulumi.Output.from_input("key")

provider = aws.Provider("test",
    ignore_tags={"keys": [key]})
```

**Comment by pgavlin** [comment]
This is probably a bug in the Python SDK generator (and perhaps other SDK generators). In order to support legacy providers--providers that only read the `map<string>` parameter to `Configure`--the generated SDKs JSON-serialize all provider inputs that are not primitive values. I'm guessing that we just need to change the codegen to do a `pulumi.to_output(foo).apply(JSON.serialize)`.

**Comment by pgavlin** [comment]
It does look like we generate the expected code here: https://github.com/pulumi/pulumi/blob/master/pkg/codegen/python/gen.go#L1016-L1021

So this is going to require some more investigation.

**Comment by justinvp** [comment]
The generated code looks like: `pulumi.Output.from_input(foo).apply(pulumi.runtime.to_json)`.

`Output.from_input` deeply unwraps nested output values in dicts and lists, but doesn't currently do that for the more recently added "input types" (i.e. XxxArgs classes).

I think we want to fix `Output.from_input` to do that. Basically in the implementation of `from_input` have a check for `if _types.is_input_type(type(val)):` and then do a similar transformation that is done for dicts: passing all the class instance attributes to `Output.all` as a list of lists, and then recreating the class instance in the `apply`.
