### ISSUE TITLE
pulumi up fails with pulumi/dotnet:2.14.0 image and .net 5

### ISSUE THREAD

**Issue by AliBazzi** [pulumi/pulumi#5785]
## Expected Behavior
`pulumi up` to work while using `pulumi/dotnet:latest` image (2.14.0)

## Current Behavior
Fail with the following exception

```
pulumi:pulumi:Stack xxx  Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libdl.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl.so: cannot open shared object file: No such file or directory
--
  | pulumi:pulumi:Stack xxx     at Grpc.Core.Internal.UnmanagedLibrary.Linux.dlopen(String filename, Int32 flags)
  | pulumi:pulumi:Stack xxx     at Grpc.Core.Internal.UnmanagedLibrary.LoadLibraryPosix(Func`3 dlopenFunc, Func`1 dlerrorFunc, String libraryPath, String& errorMsg)
  | pulumi:pulumi:Stack xxx     at Grpc.Core.Internal.UnmanagedLibrary.PlatformSpecificLoadLibrary(String libraryPath, String& errorMsg)
  | pulumi:pulumi:Stack xxx     at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
  | pulumi:pulumi:Stack xxx     at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
  | pulumi:pulumi:Stack xxx     at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
  | pulumi:pulumi:Stack xxx     at Grpc.Core.Internal.NativeExtension..ctor()
  | pulumi:pulumi:Stack xxx     at Grpc.Core.Internal.NativeExtension.Get()
  | pulumi:pulumi:Stack xxx     at Grpc.Core.Internal.NativeMethods.Get()
  | pulumi:pulumi:Stack xxx     at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
  | pulumi:pulumi:Stack xxx     at Grpc.Core.GrpcEnvironment..ctor()
  | pulumi:pulumi:Stack xxx     at Grpc.Core.GrpcEnvironment.AddRef()
  | pulumi:pulumi:Stack xxx     at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
  | pulumi:pulumi:Stack xxx     at Pulumi.GrpcEngine..ctor(String engine)
  | pulumi:pulumi:Stack xxx     at Pulumi.Deployment..ctor()
  | pulumi:pulumi:Stack xxx     at Pulumi.Deployment.CreateRunner()
  | pulumi:pulumi:Stack xxx     at Pulumi.Deployment.RunAsync[TStack]()
  | pulumi:pulumi:Stack xxx     at xxx.Program.Main() in /workdir/xxx/Program.cs:line 8
  | pulumi:pulumi:Stack xxx     at xxx.Program.<Main>()
  | pulumi:pulumi:Stack xxx  error: an unhandled error occurred: Program exited with non-zero exit code: 134
  | pulumi:pulumi:Stack xxx **failed** 1 error; 20 messages


```

## Steps to Reproduce
create .net project with pulumi that targets .net 5, and use `pulumi/dotnet:2.14.0` image to do `pulumi up`

**Comment by gitfool** [comment]
See https://github.com/grpc/grpc/issues/24153. The fix has been merged but not released yet. Use the workaround.

**Comment by AliBazzi** [comment]
Thanks for referencing the issue @gitfool

**Comment by AliBazzi** [comment]
it's working in version `2.15.x`
