### ISSUE TITLE
azure.network.get_subnet throws AttributeError when used in unittest

### ISSUE THREAD

**Issue by thomas-b-jackson** [pulumi/pulumi#5846]
See repro steps

## Expected Behavior
running `python -m unittest test_subnet` passes

## Current Behavior
running `python -m unittest test_subnet` fails with the following error:

```
(venv) (docker-desktop:default)LOGIC-1019: /home/tomj/go/vm/azure-py > python -m unittest test_subnet
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.6/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/usr/lib/python3.6/unittest/main.py", line 148, in createTests
    self.module)
  File "/usr/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/tomj/go/vm/azure-py/test_subnet.py", line 13, in <module>
    import infra
  File "/home/tomj/go/vm/azure-py/infra.py", line 6, in <module>
    virtual_network_name="npeccpdevwu2RgGolduckVPC")
  File "/home/tomj/go/vm/azure-py/venv/lib/python3.6/site-packages/pulumi_azure/network/get_subnet.py", line 191, in get_subnet
    address_prefix=__ret__.address_prefix,
AttributeError: 'dict' object has no attribute 'address_prefix'
```

## Steps to Reproduce
1. setup 3 files per context
1. substitute valid values in infra.py
1. run: 
   `pulumi up`
1. choose `yes`
1. output contains a valid subnet id
1. run: 
   `source venv/bin/activate`
1. run:
    `python -m unittest test_subnet`

## Context (Environment)

infra.py as:
```
import pulumi
import pulumi_azure as azure

subnet_network = azure.network.get_subnet(name="clusternodes",
    resource_group_name="npeccpdevwu2RgGolduck",
    virtual_network_name="npeccpdevwu2RgGolduckVPC")
```

__main.py__ as:
```
import pulumi

import infra

pulumi.export('subnet_network', infra.subnet_network)
```

test_subnet.py as:
```
import unittest
import pulumi

class MyMocks(pulumi.runtime.Mocks):
    def new_resource(self, type_, name, inputs, provider, id_):
        return [name + '_id', inputs]
    def call(self, token, args, provider):
        return {}

pulumi.runtime.set_mocks(MyMocks())

# Now actually import the code that creates resources, and then test it.
import infra

class TestingWithMocks(unittest.TestCase):
    @pulumi.runtime.test
    def test_subnet_id(self):
        def check_id(args):
            subnet = args
            self.assertIsNotNull(subnet.id)

        print(infra.server)
        return pulumi.Output.all(infra.subnet).apply(check_id)
```

**Comment by mikhailshilkov** [comment]
I believe you need to implement this mock function to return "real" outputs of the function `get_subnet`:

```
def call(self, token, args, provider):
        return {} # this shouldn't be empty
```

Apologies for not coming back to you earlier. As this issue is 1.5 years old, I'll go ahead and close it.
