### ISSUE TITLE
Crash when running pulumi up

### ISSUE THREAD

**Issue by deevus** [pulumi/pulumi#5873]
When trying to run `pulumi up` I'm getting a crash. It's hard to say what is causing it because it's a pretty cryptic error message. 

## Expected Behavior

Stack should be created

## Current Behavior

Pulumi crashes

## Steps to Reproduce

1. `pulumi up`

## Context (Environment)

The stack is targeting AWS:

- ECS Fargate
- RDS Aurora MySQL
- ElastiCache

Exception:
```
panic: fatal: An assertion has failed
goroutine 49346 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assert(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/sdk/v2/go/common/resource/plugin.(*provider).Read(0xc0007a1260, 0xc001e93880, 0x65, 0x0, 0x0, 0x0, 0xc001652270, 0xe9b18d, 0x7fc200000004, 0xc001a49800, ...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/provider_plugin.go:763 +0x1037
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*ReadStep).Apply(0xc0016522d0, 0x0, 0x1cf17e0, 0x23, 0xc00054de40, 0x3)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step.go:620 +0x105
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).executeStep(0xc000734400, 0x60, 0x201a480, 0xc0016522d0, 0x5, 0x0)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:271 +0x209
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).executeChain(0xc000734400, 0x60, 0xc001f74260, 0x1, 0x1)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:221 +0xef
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).worker.func1(0xc000734400, 0x60, 0xc001f74260, 0x1, 0x1, 0xc0017f4360)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:371 +0xc5
created by github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).worker
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:368 +0x2e7
error Command failed with exit code 2.
```

This is a closed source project so if you need more information I can communicate via Slack, email etc.

**Comment by deevus** [comment]
I stopped the update and exported/imported the stack. It gave the following warning:

```
warning: removing pending operation 'reading' on 'urn:pulumi:dev::stackName::aws:elasticache/replicationGroup:ReplicationGroup::cache-cluster-dev' from snapshot
```
I was creating an elasticache instance, and getting the replication group so that I could output the reader and writer endpoints in the case where there are multiple cache nodes. 

```ts
  const replicationGroup = aws.elasticache.ReplicationGroup.get(
    cacheClusterName,
    cluster.replicationGroupId
  );
```

I just realised that `cacheClusterName` is not unique. Would that cause a crash?

**Comment by deevus** [comment]
> I just realised that cacheClusterName is not unique. Would that cause a crash?

That wasn't it. I made sure that it was unique and had the same crash.

**Comment by deevus** [comment]
Removing the above `ReplicationGroup.get` call fixes the issue. But it is weird that it would cause pulumi to crash.

**Comment by leezen** [comment]
The failing assert checks that the ID is not empty. Could you please share the code that feeds into how `cluster.replicationGroupId` is instantiated?

**Comment by deevus** [comment]
I'm creating an RDS instance. It just occurred to me that it may not have a `ReplicationGroup`? 

```ts
  const rds = new aws.rds.Instance('rds', {
    engine: 'mysql',
    engineVersion: '5.7',
    username,
    password,
    port: port.apply((port) => Number(port ?? 3306)),
    dbSubnetGroupName: subnetGroup.name,
    vpcSecurityGroupIds: [vpc.vpc.apply((vpc) => vpc.defaultSecurityGroupId)],
    publiclyAccessible: false,
    instanceClass: 'db.t3.small',
    allocatedStorage: 10,
    finalSnapshotIdentifier: paramCase(
      `${pulumi.getStack()}-${getAppVersion()}-final-snapshot`
    ),
    name: database,
    skipFinalSnapshot: pulumi.getStack() !== 'production',
  });
```

In any case, it would be helpful to improve the error message.

**Comment by deevus** [comment]
```ts
  const subnetGroup = new aws.elasticache.SubnetGroup(
    `cache-subnet-group-${pulumi.getStack()}`,
    {
      subnetIds: vpc.privateSubnetIds,
    }
  );

  const cluster = new aws.elasticache.Cluster(cacheClusterName, {
    engine: 'redis',
    engineVersion: '3.2.10',
    nodeType: 'cache.t3.small',
    numCacheNodes: 1,
    securityGroupIds: [vpc.vpc.defaultSecurityGroupId],
    subnetGroupName: subnetGroup.name,
  });

  const replicationGroup = aws.elasticache.ReplicationGroup.get(
    cacheClusterName,
    cluster.replicationGroupId
  );
```

**Comment by leezen** [comment]
I believe if you don't provide `replicationGroupId` to the cluster as an argument, it won't belong to a replication group (and the output value of `cluster.replicationGroupId` will be empty). The error could definitely be more helpful. I'll close this issue and create a new one to track improving the experience.
