### ISSUE TITLE
Javascript serializer is stripping off too much

### ISSUE THREAD

**Issue by andreujuanc** [pulumi/pulumi#5898]
Hi, 

I have a Typescript project in which I'm experimenting, and I'm having some issues with `reflect-metadata`

I'm using AWSX and creating EventHandlerRoute with a callback.
The code is being analyzed and stripped down to a point that it breaks execution.
**If refect-metadata is not supported with awsx callbacks then we can close this.**

For example, consider the following annotated typescript class:

```typescript
@Model({
  tableName: 'PROFILE_TABLE_NAME'
})
export class Profile {
  @PartitionKey()
  userId: string
  fullName: string
  dateOfBirth: string
  hashedPIN?: string
  profilePictureBase64?: string

  constructor(userId: string, fullName: string, dateOfBirth: string) {
    this.userId = userId
    this.fullName = fullName
    this.dateOfBirth = dateOfBirth
  }
}
```

Compiles down to 
```javascript
var Profile = /** @class */ (function () {
    function Profile(userId, fullName, dateOfBirth) {
        this.userId = userId;
        this.fullName = fullName;
        this.dateOfBirth = dateOfBirth;
    }
    __decorate([
        dynamo_easy_1.PartitionKey(),
        __metadata("design:type", String)
    ], Profile.prototype, "userId");
    Profile = __decorate([
        dynamo_easy_1.Model({
            tableName: 'PROFILE_TABLE_NAME'
        }),
        __metadata("design:paramtypes", [String, String, String])
    ], Profile);
    return Profile;
}());
exports.Profile = Profile;
```

And it's being deployed as:
```javscript
function __Profile(__0, __1, __2) {
  return (function() {
    with({ Profile: __Profile }) {

return function /*Profile*/(userId, fullName, dateOfBirth) {
        this.userId = userId;
        this.fullName = fullName;
        this.dateOfBirth = dateOfBirth;
    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}
```

## Expected Behavior
Closures should be respected.

## Current Behavior
Metadata is being removed from the objects

## Context (Environment)
I was just trying a library that helps with dynamo queries, and it needs reflect metadata to work 😭

**Comment by leezen** [comment]
I'm curious if you're importing that module within the function closure or outside of it?

**Comment by andreujuanc** [comment]
Outside, I did `import { Profile } from './profile'` 
I can try to do a small demo with a `require('./profile') ` inside the function closure. But I'm not sure it's going to work.
Another idea I had was to "publish" it all as an npm package, so it's included as a dependency in node_modules. 

I will try importing the module within the closure and get back to you, but this will make it a bit brittle, cos forgetting to do this does not throw on build or deploy time, but on runtime.

**Comment by semiautomatix** [comment]
Attempt to use IoC of dependency injection in AWS Lambdas is resulting in the "reflect-metadata" imports being stripped from the code. The polyfill and therefore the code fails to run.

I'm switching to Serverless in interim.

```
2022-07-21T10:03:57.988Z	79cc5d5d-06e7-47d7-a111-8200d3c1e441	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "tsyringe requires a reflect polyfill. Please add 'import \"reflect-metadata\"' to the top of your entry point.",
    "stack": [
        "Error: tsyringe requires a reflect polyfill. Please add 'import \"reflect-metadata\"' to the top of your entry point.",
        "    at Object.<anonymous> (/var/task/node_modules/tsyringe/dist/cjs/index.js:5:11)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at /var/task/__index.js:27:24",
        "    at Runtime.__f0 [as handler] (/var/task/__index.js:49:6)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

**Comment by semiautomatix** [comment]
Original TypeScript:

```
import "reflect-metadata";
import { Context, APIGatewayProxyResult, APIGatewayEvent } from 'aws-lambda';
import { container } from "tsyringe";
import { TagService } from "../services/TagService";

export const tagsPostHandler = async (event: APIGatewayEvent, context: Context): Promise<APIGatewayProxyResult> => {
    // TODO check for JSON
    try {
        if (!event.body) {
            return {
                statusCode: 400,
                body: 'Bad Request: no body.'
            }        
        }
        const { imageId, tag } = JSON.parse(event.body);
        if (!imageId) {
            return {
                statusCode: 400,
                body: 'Bad Request: imageId is required.'
            }
        } 
        if (!tag) {
            return {
                statusCode: 400,
                body: 'Bad Request: tag is required.'
            }
        } 
        const tagService = container.resolve(TagService);
        await tagService.addImageTag(imageId, tag);
        return {
            statusCode: 200,
            body: "OK",
        };
    } catch (e) {
        return {
            statusCode: 500,
            body: JSON.stringify(e)
        }
    }
};
```

Lambda JavaScript

```
exports.handler = __f0;

var __TagService_1 = {TagService: __f1};

function __f1(__0) {
  return (function() {
    with({  }) {

return function /*constructor*/(tagRepository) {
        this.tagRepository = tagRepository;
        this.addImageTag = async (imageId, tag) => {
            await this.tagRepository.putItem(imageId, tag);
        };
        this.getImageTags = async (imageId) => {
            const { Items } = await this.tagRepository.getItems(imageId);
            return (Items !== null && Items !== void 0 ? Items : []);
        };
        //
    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f0(__0, __1) {
  return (function() {
    with({ tsyringe_1: require("tsyringe/dist/cjs/index.js"), TagService_1: __TagService_1 }) {

return async (event, context) => {
    // TODO check for JSON
    try {
        if (!event.body) {
            return {
                statusCode: 400,
                body: 'Bad Request: no body.'
            };
        }
        const { imageId, tag } = JSON.parse(event.body);
        if (!imageId) {
            return {
                statusCode: 400,
                body: 'Bad Request: imageId is required.'
            };
        }
        if (!tag) {
            return {
                statusCode: 400,
                body: 'Bad Request: tag is required.'
            };
        }
        const tagService = tsyringe_1.container.resolve(TagService_1.TagService);
        await tagService.addImageTag(imageId, tag);
        return {
            statusCode: 200,
            body: "OK",
        };
    }
    catch (e) {
        return {
            statusCode: 500,
            body: JSON.stringify(e)
        };
    }
};

    }
  }).apply(undefined, undefined).apply(this, arguments);
}
```

**Comment by diogoviannaaraujo** [comment]
Any updates on how to use the "reflect-metadata" polyfill with pulumi serialization? I'm trying to use TypeORM with callback function and believe the problem is the same

**Comment by semiautomatix** [comment]
I'm using "reflect-metadata" in my `pulumi.dynamic.ResourceProvider` and it's failing.

Looks like I have little choice, if I want to keep using polyfills, but to go elsewhere :disappointed:
