### ISSUE TITLE
Panic with pulumi up when using refresh

### ISSUE THREAD

**Issue by mastoj** [pulumi/pulumi#5946]
Sorry for not a precise issue, but I don't have time.

I experienced this issue today with my pulumi script:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0xeaa730]

goroutine 99 [running]:
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepGenerator).AnalyzeResources.func1(0xc001728270, 0xc6, 0xc0013f6240, 0xc0006b1790)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1301 +0x130
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*resourceMap).mapRange.func1(0x1b305a0, 0xc000bced70, 0x190a5e0, 0xc0013f6240, 0x1)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:126 +0x6b
sync.(*Map).Range(0xc0000a0f00, 0xc000673810)
	/Users/runner/hostedtoolcache/go/1.15.6/x64/src/sync/map.go:345 +0x1d9
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*resourceMap).mapRange(0xc0000a0f00, 0xc000673970)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:125 +0x55
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepGenerator).AnalyzeResources(0xc0014a17a0, 0x2c1fd80, 0x0)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1289 +0xac
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).Execute(0xc0005eaea0, 0x20075a0, 0xc00172ef90, 0x7f9838b98118, 0xc0007e5180, 0x7fffffff, 0x1, 0x2c1fd80, 0x0, 0x0, ...)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:277 +0xae6
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*Deployment).Execute(...)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:383
github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run.func1(0x2011fe0, 0xc0007e5180, 0xc0005f83c0, 0x20075a0, 0xc00172ef90, 0xc00172ef01, 0xc00059aa60, 0xc00004f4a0)
	/Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:251 +0x267
created by github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run
	/Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:237 +0x306
Finished (TagStatus.Failed) 'DeployInfra' in 00:00:12.3009585


```

It only happens when I do `up` with `-r`. Removing `-r` and deploy works again. Not sure what is going on.

I'm using the 2.15.6 version of pulumi.

**Comment by mastoj** [comment]
A potential thing could be a password that we changed name on the resource, maybe that is causing the nil?

**Comment by mastoj** [comment]
I have a little bit more time now explaining when I think this happened, even though most of it is in the above description and text.

We added a `RandomPassword` resource to our stack. We then realized that the name of the resource was slighly wrong we change it. Doing a `pulumi up -r` now began to failing with the error above. Not sure why I decided to drop the `-r`, but I think looked like it was failing during refresh so I thought I would just drop it. So my guess is that it is `RandomPassword` together with refresh that doesn't play so nice... but that is just a wild guess.

**Comment by m4dc4p** [comment]
I'm seeing a panic as well (running pulumi 2.15.6). This started happening somewhere between Dec 9 (2.15.3) and Dec 11 (2.15.5). 

I'm seeing this in AWS' CodeBuild/CodePipeline environment. The update runs on their "aws/codebuild/standard:4.0" image (version 4.0-20.03.13)

I'm not doing anything with `RandomPassword` or changing the name of resource during the update. 

Running the CI job again generally fixes the problem. Interestingly, the second run does far fewer changes than the first (so clearly pulumi does change the state of resources during the first run).

Here is a stack trace from the most recent failure:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0xeaa730]

goroutine 129 [running]:
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepGenerator).AnalyzeResources.func1(0xc0015a4a20, 0x52, 0xc00014afc0, 0xc0021e5380)
    /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1301 +0x130
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*resourceMap).mapRange.func1(0x1b305a0, 0xc000884750, 0x190a5e0, 0xc00014afc0, 0x1)
    /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:126 +0x6b
sync.(*Map).Range(0xc001982630, 0xc000661810)
    /Users/runner/hostedtoolcache/go/1.15.6/x64/src/sync/map.go:345 +0x1d9
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*resourceMap).mapRange(0xc001982630, 0xc000661970)
    /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:125 +0x55
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepGenerator).AnalyzeResources(0xc001cd9440, 0x2c1fd80, 0x0)
    /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1289 +0xac
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).Execute(0xc0007d7640, 0x20075a0, 0xc0007cb890, 0x7f47045c6c80, 0xc0015109a0, 0x7fffffff, 0x1, 0x2c1fd80, 0x0, 0x0, ...)
    /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:277 +0xae6
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*Deployment).Execute(...)
    /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:383
github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run.func1(0x2012040, 0xc0015109a0, 0xc0011bea00, 0x20075a0, 0xc0007cb890, 0xc0007cb800, 0xc000b82f90, 0xc0007ccea0)
    /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:251 +0x267
created by github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run
    /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:237 +0x306
```

Here is a stack trace from a failure on 2.15.5:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0xeaa730]

goroutine 110 [running]:
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepGenerator).AnalyzeResources.func1(0xc000093a40, 0x52, 0xc002687440, 0xc0006b0410)
    /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1301 +0x130
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*resourceMap).mapRange.func1(0x1b305a0, 0xc00268f4b0, 0x190a5e0, 0xc002687440, 0x1)
    /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:126 +0x6b
sync.(*Map).Range(0xc001771bf0, 0xc003055810)
    /Users/runner/hostedtoolcache/go/1.15.6/x64/src/sync/map.go:345 +0x1d9
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*resourceMap).mapRange(0xc001771bf0, 0xc003055970)
    /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:125 +0x55
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepGenerator).AnalyzeResources(0xc002030b40, 0x2c1fd80, 0x0)
    /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1289 +0xac
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).Execute(0xc0019ac0e0, 0x20075a0, 0xc0019809f0, 0x7fc2e5b56b28, 0xc000a269a0, 0x7fffffff, 0x1, 0x2c1fd80, 0x0, 0x0, ...)
    /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:277 +0xae6
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*Deployment).Execute(...)
    /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:383
github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run.func1(0x2012040, 0xc000a269a0, 0xc0018e63c0, 0x20075a0, 0xc0019809f0, 0xc001980900, 0xc0019a99c0, 0xc00198a300)
    /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:251 +0x267
created by github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run
    /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:237 +0x306
```

**Comment by phewitt** [comment]
I am also seeing this error. this is a typescript project. 
```
$ pulumi version
v2.15.6
```
package.json dependencies.
```
                "@pulumi/aws": "2.13.1",
                "@pulumi/datadog": "2.13.0",
                "@pulumi/docker": "2.5.0",
                "@pulumi/eks": "0.19.5",
                "@pulumi/kubernetes": "2.7.4",
                "@pulumi/kubernetesx": "0.1.3",
                "@pulumi/pulumi": "2.15.6",

```

Panic:
```
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0xeaa730]
goroutine 109 [running]:
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepGenerator).AnalyzeResources.func1(0xc0018302a0, 0x53, 0xc00352b200, 0xc003526340)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1301 +0x130
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*resourceMap).mapRange.func1(0x1b305a0, 0xc002185860, 0x190a5e0, 0xc00352b200, 0x1)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:126 +0x6b
sync.(*Map).Range(0xc0017a0de0, 0xc0036af810)
        /Users/runner/hostedtoolcache/go/1.15.6/x64/src/sync/map.go:345 +0x1d9
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*resourceMap).mapRange(0xc0017a0de0, 0xc0036af970)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:125 +0x55
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepGenerator).AnalyzeResources(0xc002f9f680, 0x2c1fd80, 0x0)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1289 +0xac
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).Execute(0xc00160bdc0, 0x20075a0, 0xc000eeb2c0, 0x7f6d074c0c80, 0xc000740500, 0x7fffffff, 0x1, 0x0, 0x0, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:277 +0xae6
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*Deployment).Execute(...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:383
github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run.func1(0x2011fe0, 0xc000740500, 0xc000ef2280, 0x20075a0, 0xc000eeb2c0, 0xc000eeb201, 0xc000ee5700, 0xc0018318c0)
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:251 +0x267
created by github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:237 +0x306
        ```
        
       this does seem to be new behavior (past week) on a stack that has run no problem before.

**Comment by m4dc4p** [comment]
I ran `pulumi destroy --refresh` on my Windows (❗) machine (with 2.15.6) and saw a similar error. Running `pulumi refresh` and then `pulumi destroy` separately let me move forward.

Stack trace I received is below:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x98 pc=0x130a0fa]

goroutine 108 [running]:
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepGenerator).AnalyzeResources.func1(0xc000bc6460, 0x6a, 0xc001e67d40, 0xc0019b3200)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1301 +0x13a
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*resourceMap).mapRange.func1(0x1fd8a60, 0xc001f240b0, 0x1db0e80, 0xc001e67d40, 0x1)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/resource/deploy/deployment.go:126 +0x72
sync.(*Map).Range(0xc000b6f440, 0xc000a4b810)
        C:/hostedtoolcache/windows/go/1.15.6/x64/src/sync/map.go:345 +0x1d9
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*resourceMap).mapRange(0xc000b6f440, 0xc000a4b970)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/resource/deploy/deployment.go:125 +0x5c
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepGenerator).AnalyzeResources(0xc002636c60, 0x0, 0x0)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1289 +0xbb
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).Execute(0xc0005fc680, 0x24b7e20, 0xc0006cf4d0, 0x276b7661058, 0xc0008fb900, 0x7fffffff, 0x1, 0x0, 0x0, 0x0, ...)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:277 +0xae6
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*Deployment).Execute(...)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/resource/deploy/deployment.go:383
github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run.func1(0x24c2e00, 0xc0008fb900, 0xc0008fa8c0, 0x24b7e20, 0xc0006cf4d0, 0xc0006cf401, 0xc0006362f0, 0xc000646c00)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/engine/deployment.go:251 +0x287
created by github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/engine/deployment.go:237 +0x314
```

**Comment by lblackstone** [comment]
I was able to reproduce the issue and found the problem. The following steps will cause the issue:

1. Run the following program with `pulumi up`
```ts
import * as random from "@pulumi/random";

new random.RandomPassword("test", {
    length: 8,
});
```

2. Change the resource name to `test2`
3. Run `pulumi up -r`

The following line is retrieving the wrong map entry: https://github.com/pulumi/pulumi/blob/860ea4dc847e15231a01629f1f335a6c8a11e9b4/pkg/resource/deploy/step_generator.go#L1290

Here, `urn` will have the following suffix `::random:index/randomPassword:RandomPassword::test`, when the actual map entry has `::random:index/randomPassword:RandomPassword::test2`.

I'm working to track down the reason for this now.
