### ISSUE TITLE
Can't use nested inputs for Helm Values

### ISSUE THREAD

**Issue by kralikba** [pulumi/pulumi#5961]
## Expected Behavior
Given an `InputList<string> ipRanges`,

```
new LocalChartArgs()
{
    Namespace = "whatever",
    Values = new InputMap<object>()
    {
        { "controller", new InputMap<object>() {
                { "replicaCount", 1 },
                { "service", new InputMap<object>() {
                        { "loadBalancerSourceRanges", ipRanges }
                }}
        }}
    }
}
```

is a valid argument to the constructor of Pulumi.Kubernetes.Helm.V3.Chart

## Current Behavior
The program throws an exception: 
```
  kubernetes:helm.sh/v3:Chart (haproxy-ingress-main):
    error: Pulumi.ResourceException: A Pulumi.InputMap`1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] cannot be synchronously enumerated. Use GetAsyncEnumerator instead. Path: $.Values.
       at Pulumi.Kubernetes.Helm.V3.Chart.<>c__DisplayClass0_0.<.ctor>b__1(ValueTuple`2 values)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey, Boolean keepResources)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args, Boolean keepResources)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

## Context (Environment)
In C# 9.0, using Pulumi 2.15.6 and Pulumi.Kubernetes/2.7.4, I'm trying to programmatically set the `controller.service.loadBalancerSource` value for a Helm chart to a list of strings that I get from outputs of other components of the stack.

**Comment by kralikba** [comment]
If I use Dictionaries instead of InputMaps, the inner value, the InputList causes the problem directly:

```
  kubernetes:helm.sh/v3:Chart (haproxy-ingress-nop):
    error: Pulumi.ResourceException: A Pulumi.InputList`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] cannot be synchronously enumerated. Use GetAsyncEnumerator instead. The unsupported member type is located on type 'System.Object'. Path: $.Values.
       at Pulumi.Kubernetes.Helm.V3.Chart.<>c__DisplayClass0_0.<.ctor>b__1(ValueTuple`2 values)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey, Boolean keepResources)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args, Boolean keepResources)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

**Comment by lblackstone** [comment]
@mikhailshilkov Any thoughts here?

**Comment by mikhailshilkov** [comment]
Can you use normal dictionaries in place of inner `InputMap`'s?

**Comment by mikhailshilkov** [comment]
Ah, sorry, the curlpit is the `InputList`. You likely need to use `Apply` on it.

**Comment by mikhailshilkov** [comment]
The following assignment works for me:

```
Values = ipRanges.ToOutput().Apply(ranges => new Dictionary<string, object>
{
    ["controller"] = new Dictionary<string, object>
    {
        ["replicaCount"] = 1,
        ["service"] = new Dictionary<string, object>
        {
            ["loadBalancerSourceRanges"] = ranges
        }
    }
})
```

The error message is definitely unfortunate but it's hard to enforce proper structure on untyped `Values`. Given that we now recommend using `Release` instead of `Chart`, and a working solution is available, I'll go ahead and close this issue.

**Comment by wclr** [comment]
@mikhailshilkov 
> Given that we now recommend using Release instead of Chart

Given that in `k8s.helm.v4` there is no `Release`, so it is not "recommended" now?

**Comment by EronWright** [comment]
@wclr sorry for the confusion, the `Release` resource is still recommended and `v3` is the latest.  To explain, the `Chart` resource received a major upgrade (to `v4`) earlier this year, with some breaking changes.  The `Release` resource was unaffected.
