### ISSUE TITLE
Failed to generate YAML for specified Helm chart

### ISSUE THREAD

**Issue by aaronhayes** [pulumi/pulumi#5972]
Getting this error when trying to update my stack - occurs on `pulumi up` and `pulumi preview` . I'm not sure if it's a pulumi related issue - I posted in the Slack channel asking for help - but thought having it here helps others. Any advice is much appreciated as I can no longer update my stack! 

Things to note:
1. This was working yesterday. 
2. I haven't changed any of the stack code.
3. The only things that have changed are pulumi versions and packages. See my issue from [yesterday](https://github.com/pulumi/pulumi/issues/5955) 

```
error: Running program '/Users/…/myproject' failed with an unhandled exception: 
Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to load chart from temp directory: stat /var/folders/pm/ftb5j1d51_gbr3cdxfpl1v4r0000gn/T/helm179799543/nginx-ingress: no such file or directory
unhandled rejection: CONTEXT(516): Invoking function: tok=kubernetes:helm:template asynchronously
```

This is the code for my helm chart which i think is the culprit.

```
const certManager = new k8s.helm.v3.Chart(
  `cert-manager`,
  {
    chart: `cert-manager`,
    version: `v0.15.1`,
    fetchOpts: {
      repo: 'https://charts.jetstack.io'
    },
    namespace: `cert-manager`,
    values: {
      ingressShim: {
        defaultIssuerName: certClusterIssuerName,
        defaultIssuerKind: 'ClusterIssuer'
      }
    }
  },
  {
    dependsOn: [certNamespace, crds],
    provider: cluster.provider
  }
);
```
## Expected Behavior

Preview Succesful

## Current Behavior

Preview Errors

## Steps to Reproduce

1.
2.
3.
4.

**Comment by leezen** [comment]
I'm having trouble reproducing this. The error suggests perhaps some kind of disk issue potentially? Have you verified that you're able to retrieve the chart and that you can write to paths in that temp directory path? Are you able to reproduce this reliably and if so, how?

**Comment by aaronhayes** [comment]
Thanks @leezen , 

1. How would I go about verifying I can retrieve the chart? 

2. I don't even know where that temp path is? Is that on my cluster/nodes or local machine? My kubernetes cluster is deployed on AWS. I'm assuming it's my local machine as `/var/folders/pm/ftb5j1d51_gbr3cdxfpl1v4r0000gn/T` exists. but there's no helm folders there. **This is most likely the root issue**. I just need to work out why the chart isn't being downloaded there.
 
2. Yes I can reliability reproduce this on my stack using `pulumi up` or `pulumi preview`. I wouldn't know where to begin to try and isolate this to provide instructions/sample apps. 

As I said it only started happening yesterday.

This is the full stack trace given:

```
    Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to load chart from temp directory: stat /var/folders/pm/ftb5j1d51_gbr3cdxfpl1v4r0000gn/T/helm194639850/nginx-ingress: no such file or directory
        at /Users/projects/infra/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/runtime/invoke.js:138:33
        at Http2CallStream.<anonymous> (/Users/projects/infra/node_modules/@grpc/grpc-js/src/client.ts:155:9)
        at Http2CallStream.emit (node:events:341:22)
        at Http2CallStream.EventEmitter.emit (node:domain:467:12)
        at /Users/aaron/projects/liftly/infra/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14
        at processTicksAndRejections (node:internal/process/task_queues:75:11)

```

**Comment by leezen** [comment]
Correct, that path should exist locally. What happens under the hood in the provider is that it retrieves the chart and runs the template method (see https://github.com/pulumi/pulumi-kubernetes/blob/e54be7d7e1953c8e2929edef2b113018f1a9b441/provider/pkg/provider/invoke_helm_template.go#L67). It looks like the error is happening on https://github.com/pulumi/pulumi-kubernetes/blob/e54be7d7e1953c8e2929edef2b113018f1a9b441/provider/pkg/provider/invoke_helm_template.go#L218 which is why I was asking about your local disk setup (e.g. could that partition be full?)
