### ISSUE TITLE
Helm chart stopped deploying - The system cannot find the file specified

### ISSUE THREAD

**Issue by barclayadam** [pulumi/pulumi#5981]
One of my stacks has recently stopped working without any changes to the code, due to an error during the execution of a helm chart (which has not changed in terms of values specified, nor the version).

## Expected Behavior
The helm chart is detected as not changed, no errors occur.

## Current Behavior
Pulumi outputs the following:

````
    error: Error: Command failed: helm template C:\Users\barcl\AppData\Local\Temp\tmp-40228M92B2AG7CIlI\deprecation --name-template kube-state-metrics --values C:\Users\barcl\AppData\Local\Temp\tmp-40228M92B2AG7CIlI\deprecation\values.yaml --values C:\Users\barcl\AppData\Local\Temp\tmp-40228eL5MEkDuu74E.yaml  --namespace apm --include-crds
    Error: open C:\Users\barcl\AppData\Local\Temp\tmp-40228M92B2AG7CIlI\deprecation\values.yaml: The system cannot find the file specified.
    error: an unhandled error occurred: One or more errors occurred
````

from the chart defined as:

````typescript
new k8s.helm.v2.Chart('kube-state-metrics',
    {
        namespace: 'apm',
        chart: 'kube-state-metrics',
        version: '2.4.1',
        fetchOpts: {
            repo: 'https://kubernetes-charts.storage.googleapis.com',
        },
        values: {
            'nodeSelector': {
                'kubernetes.io/os': 'linux',
            },

            'prometheusScrape': false,

            'collectors': {
                'cronjobs': false,
            },
        },
    },
    {
        // Root has kubernetes provider defined
        parent: root,
    });
````

## Context (Environment)
Pulumi version 2.15.4 + 2.15.6 on Windows and Ubuntu respectively
Using Automation API, with "workspace" defined as the current working directory (i.e. overrides the use of the temporary folder)
Pulumi dependencies:
````json
  "devDependencies": {
    "@pulumi/azure": "^3.33.2",
    "@pulumi/azure-nextgen": "^0.2.8",
    "@pulumi/azuread": "^3.0.1",
    "@pulumi/cloudflare": "^2.9.0",
    "@pulumi/docker": "^2.5.0",
    "@pulumi/kubernetes": "^2.7.4",
    "@pulumi/kubernetesx": "^0.1.3",
    "@pulumi/pulumi": "^2.15.4",
    "@pulumi/random": "^2.4.4",
    "@pulumi/tls": "^2.4.2",
  },
````

**Comment by barclayadam** [comment]
As a test I wanted to see how v3 would work, but I get the same error in a different format:

````
    error: Unhandled exception: Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to load chart from temp directory: CreateFile C:\Users\barcl\AppData\Local\Temp\helm290366175\kube-state-metrics: The system cannot find the file specified.
        at D:\Proj\\azure\node_modules\@pulumi\pulumi\runtime\invoke.js:138:33
        at Http2CallStream.<anonymous> (D:\Proj\\azure\node_modules\@grpc\grpc-js\src\client.ts:155:9)
        at Http2CallStream.emit (events.js:326:22)
        at D:\Proj\\azure\node_modules\@grpc\grpc-js\src\call-stream.ts:186:14
        at processTicksAndRejections (internal/process/task_queues.js:75:11)
    error: an unhandled error occurred: One or more errors occurred

````
