### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by bennettp123** [pulumi/pulumi#5993]
When I run `pulumi up` I get the following error:

```
Previewing update (news-shared.branch-deploys):

    pulumi:pulumi:Stack news-shared-news-shared.branch-deploys running 
fatal error: concurrent map read and map write
    swm:security-groups:SecurityGroups news-shared-branch-deploys-securitygroups  

goroutine 316 [running]:
runtime.throw(0x1cf15da, 0x21)
	/Users/runner/hostedtoolcache/go/1.15.6/x64/src/runtime/panic.go:1116 +0x72 fp=0xc001e75c70 sp=0xc001e75c40 pc=0x436912
runtime.mapaccess2_faststr(0x1a05860, 0xc001c8f410, 0xc0018222a0, 0x62, 0xc0018995c0, 0x0)
	/Users/runner/hostedtoolcache/go/1.15.6/x64/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc001e75ce0 sp=0xc001e75c70 pc=0x414225
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).executeStep(0xc001e2c500, 0x6, 0x201ebe0, 0xc0018995c0, 0xc001737a00, 0x0)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:296 +0x3aa fp=0xc001e75e80 sp=0xc001e75ce0 pc=0xe9ad6a
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).executeChain(0xc001e2c500, 0x6, 0xc00035bd50, 0x1, 0x1)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:221 +0xef fp=0xc001e75f50 sp=0xc001e75e80 pc=0xe9a50f
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).worker.func1(0xc001e2c500, 0x6, 0xc00035bd50, 0x1, 0x1, 0xc001f1e420)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:377 +0xc5 fp=0xc001e75fb0 sp=0xc001e75f50 pc=0xea9d45
runtime.goexit()
	/Users/runner/hostedtoolcache/go/1.15.6/x64/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc001e75fb8 sp=0xc001e75fb0 pc=0x46ee21
created by github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).worker
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:374 +0x2e7

<output truncated>
```

Full output, including goroutine stack dumps: https://gist.github.com/bennettp123/9313b65d7d223b94c9cf868d10ce61c2

## Expected Behavior

Command runs without error

## Current Behavior

See description.

## Steps to Reproduce

See description. It fails at random times during the `pulumi up`, during preview or apply phase.

## Context (Environment)

We're running pulumi non-interactively as a GitHub Action. Command: `pulumi up --yes --non-interactive`

Build server details:

Pulumi version: v2.16.0
SDK: js/ts
Arch: x64
OS: Amazon Linux 2

Providers:
* "@pulumi/aws": "^3.19.3",
* "@pulumi/awsx": "^0.22.0",
* "@pulumi/pulumi": "^2.15.6",
* "@pulumi/random": "^2.4.4",

**Comment by lukehoban** [comment]
This appears to have been introduced by https://github.com/pulumi/pulumi/pull/5980.

**Comment by mgranderath** [comment]
We are using the pulumi docker container and I can confirm that this was introduced in v2.16.0. The previous version v2.15.6 seems to be working.

**Comment by Abukamel** [comment]
I have got to encounter an issue similar to this today
```
Diagnostics:
  command:remote:Command (create-domain):
    error: transport is closing
 
  pulumi:pulumi:Stack (wordpress-dev):
    fatal error: concurrent map writes
    fatal error: concurrent map writes
    goroutine 67 [running]:
    runtime.throw(0xe1ae40, 0x15)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/panic.go:1117 +0x72 fp=0xc00046af38 sp=0xc00046af08 pc=0x436bd2
    runtime.mapdelete(0xcda700, 0xc000318d50, 0xc00046afb0)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/map.go:793 +0x43b fp=0xc00046af98 sp=0xc00046af38 pc=0x4102db
    github.com/pulumi/pulumi-command/provider/pkg/provider.(*commandProvider).removeContext(0xc000318d80, 0xf23160, 0xc000508340)
    	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/provider.go:373 +0x59 fp=0xc00046afd0 sp=0xc00046af98 pc=0xc0bb39
    github.com/pulumi/pulumi-command/provider/pkg/provider.(*commandProvider).Create(0xc000318d80, 0xf23208, 0xc000422840, 0xc0000981e0, 0x0, 0xf127a0, 0xc000098a00)
    	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/provider.go:216 +0xd33 fp=0xc00046b880 sp=0xc00046afd0 pc=0xc0a273
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1(0xf23208, 0xc000422840, 0xdae460, 0xc0000981e0, 0xdbcc40, 0x1472400, 0xf23208, 0xc000422840)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/proto/go/provider.pb.go:2602 +0x89 fp=0xc00046b8c8 sp=0xc00046b880 pc=0xba6729
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0xf23208, 0xc000422750, 0xdae460, 0xc0000981e0, 0xc0001240a0, 0xc0005040f0, 0x0, 0x0, 0xf10ae0, 0xc00007f6f0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x308 fp=0xc00046bb40 sp=0xc00046b8c8 pc=0xbaa1e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler(0xdcfc20, 0xc000318d80, 0xf23208, 0xc000422750, 0xc00004c3c0, 0xc000031920, 0xf23208, 0xc000422750, 0xc00045a000, 0xe7b)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/proto/go/provider.pb.go:2604 +0x150 fp=0xc00046bbb0 sp=0xc00046bb40 pc=0xba0fb0
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032b880, 0xf2b578, 0xc00018e180, 0xc0000e0000, 0xc000318e10, 0x14354a0, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b fp=0xc00046be50 sp=0xc00046bbb0 pc=0xb741cb
    google.golang.org/grpc.(*Server).handleStream(0xc00032b880, 0xf2b578, 0xc00018e180, 0xc0000e0000, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c fp=0xc00046bf68 sp=0xc00046be50 pc=0xb7838c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0001b6020, 0xc00032b880, 0xf2b578, 0xc00018e180, 0xc0000e0000)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xab fp=0xc00046bfb8 sp=0xc00046bf68 pc=0xb863cb
    runtime.goexit()
    	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00046bfc0 sp=0xc00046bfb8 pc=0x46c5e1
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
    goroutine 1 [chan receive, 3 minutes]:
    github.com/pulumi/pulumi/pkg/v3/resource/provider.Main(0xe0f807, 0x7, 0xc00029ff20, 0xc00003a1e0, 0xc000070748)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.19.0/resource/provider/main.go:73 +0x48c
    github.com/pulumi/pulumi-command/provider/pkg/provider.Serve(0xe0f807, 0x7, 0xefe4f8, 0x6)
    	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/serve.go:26 +0x85
    main.main()
    	/home/runner/work/pulumi-command/pulumi-command/provider/cmd/pulumi-resource-command/main.go:25 +0x51
    goroutine 6 [chan receive]:
    github.com/golang/glog.(*loggingT).flushDaemon(0x14438c0)
    	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
    created by github.com/golang/glog.init.0
    	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x274
    goroutine 7 [select, 3 minutes]:
    google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000266ec0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/balancer_conn_wrappers.go:69 +0xac
    created by google.golang.org/grpc.newCCBalancerWrapper
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/balancer_conn_wrappers.go:60 +0x172
    goroutine 8 [chan receive, 3 minutes]:
    google.golang.org/grpc.(*addrConn).resetTransport(0xc0003b8840)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/clientconn.go:1213 +0x465
    created by google.golang.org/grpc.(*addrConn).connect
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/clientconn.go:843 +0x12a
    goroutine 9 [IO wait, 3 minutes]:
    internal/poll.runtime_pollWait(0x7ff3598f9da0, 0x72, 0x0)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/netpoll.go:227 +0x55
    internal/poll.(*pollDesc).wait(0xc000224698, 0x72, 0x0, 0x0, 0xe0f694)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
    internal/poll.(*pollDesc).waitRead(...)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:92
    internal/poll.(*FD).Accept(0xc000224680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_unix.go:401 +0x212
    net.(*netFD).accept(0xc000224680, 0x37e11d600, 0x0, 0x0)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/net/fd_unix.go:172 +0x45
    net.(*TCPListener).accept(0xc00000d3e0, 0xc00009ee40, 0xc00009ee48, 0x18)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/net/tcpsock_posix.go:139 +0x32
    net.(*TCPListener).Accept(0xc00000d3e0, 0xe4bfc0, 0xc00032b880, 0xf2ac38, 0xc000186008)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/net/tcpsock.go:261 +0x65
    google.golang.org/grpc.(*Server).Serve(0xc00032b880, 0xf21700, 0xc00000d3e0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:739 +0x27f
    github.com/pulumi/pulumi/sdk/v3/go/common/util/rpcutil.Serve.func2(0xc00032b880, 0xf21700, 0xc00000d3e0, 0xc00003acc0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/rpcutil/serve.go:92 +0x49
    created by github.com/pulumi/pulumi/sdk/v3/go/common/util/rpcutil.Serve
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/common/util/rpcutil/serve.go:91 +0x4cf
    goroutine 18 [IO wait, 3 minutes]:
    internal/poll.runtime_pollWait(0x7ff3598f9cb8, 0x72, 0xffffffffffffffff)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/netpoll.go:227 +0x55
    internal/poll.(*pollDesc).wait(0xc000136118, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
    internal/poll.(*pollDesc).waitRead(...)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:92
    internal/poll.(*FD).Read(0xc000136100, 0xc000138000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_unix.go:166 +0x1d5
    net.(*netFD).Read(0xc000136100, 0xc000138000, 0x8000, 0x8000, 0xb0503e, 0x800010601, 0x0)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/net/fd_posix.go:55 +0x4f
    net.(*conn).Read(0xc000130008, 0xc000138000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/net/net.go:183 +0x91
    bufio.(*Reader).Read(0xc000126180, 0xc000150040, 0x9, 0x9, 0x14, 0x7ff3805c65b8, 0x18)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/bufio/bufio.go:227 +0x222
    io.ReadAtLeast(0xf106c0, 0xc000126180, 0xc000150040, 0x9, 0x9, 0x9, 0x0, 0xc00009fdd0, 0x458713)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/io/io.go:328 +0x87
    io.ReadFull(...)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/io/io.go:347
    golang.org/x/net/http2.readFrameHeader(0xc000150040, 0x9, 0x9, 0xf106c0, 0xc000126180, 0x0, 0xc000000000, 0xb0966e, 0xc0918d740fcb532d)
    	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20211112202133-69e39bad7dc2/http2/frame.go:237 +0x89
    golang.org/x/net/http2.(*Framer).ReadFrame(0xc000150000, 0xc00003e390, 0xc00003e390, 0x0, 0x0)
    	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20211112202133-69e39bad7dc2/http2/frame.go:498 +0xa5
    google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc000154000)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/http2_client.go:1334 +0x185
    created by google.golang.org/grpc/internal/transport.newHTTP2Client
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/http2_client.go:345 +0x1011
    goroutine 19 [select, 3 minutes]:
    google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc00012e0a0, 0x1, 0x0, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/controlbuf.go:395 +0xff
    google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc000126300, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/controlbuf.go:515 +0x1dd
    google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc000154000)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/http2_client.go:391 +0x7b
    created by google.golang.org/grpc/internal/transport.newHTTP2Client
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/http2_client.go:389 +0x11e7
    goroutine 34 [select]:
    google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0001840a0, 0x1, 0x0, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/controlbuf.go:395 +0xff
    google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc000180120, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/controlbuf.go:515 +0x1dd
    google.golang.org/grpc/internal/transport.newHTTP2Server.func2(0xc00018e180)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/http2_server.go:292 +0xd7
    created by google.golang.org/grpc/internal/transport.newHTTP2Server
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/http2_server.go:289 +0x1110
    goroutine 35 [select, 3 minutes]:
    google.golang.org/grpc/internal/transport.(*http2Server).keepalive(0xc00018e180)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/http2_server.go:994 +0x237
    created by google.golang.org/grpc/internal/transport.newHTTP2Server
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/http2_server.go:300 +0x1135
    goroutine 36 [IO wait]:
    internal/poll.runtime_pollWait(0x7ff3598f9bd0, 0x72, 0xffffffffffffffff)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/netpoll.go:227 +0x55
    internal/poll.(*pollDesc).wait(0xc00018a018, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
    internal/poll.(*pollDesc).waitRead(...)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:92
    internal/poll.(*FD).Read(0xc00018a000, 0xc00019a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_unix.go:166 +0x1d5
    net.(*netFD).Read(0xc00018a000, 0xc00019a000, 0x8000, 0x8000, 0xb0503e, 0x800010601, 0x0)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/net/fd_posix.go:55 +0x4f
    net.(*conn).Read(0xc000186008, 0xc00019a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/net/net.go:183 +0x91
    bufio.(*Reader).Read(0xc0001800c0, 0xc0001b2040, 0x9, 0x9, 0x14, 0x0, 0x0)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/bufio/bufio.go:227 +0x222
    io.ReadAtLeast(0xf106c0, 0xc0001800c0, 0xc0001b2040, 0x9, 0x9, 0x9, 0x1d15f, 0xc00010dd78, 0xb0966e)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/io/io.go:328 +0x87
    io.ReadFull(...)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/io/io.go:347
    golang.org/x/net/http2.readFrameHeader(0xc0001b2040, 0x9, 0x9, 0xf106c0, 0xc0001800c0, 0x0, 0x7070e0900000000, 0xf18eb8, 0xc00003e378)
    	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20211112202133-69e39bad7dc2/http2/frame.go:237 +0x89
    golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001b2000, 0xc00003e378, 0x14437a0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/golang.org/x/net@v0.0.0-20211112202133-69e39bad7dc2/http2/frame.go:498 +0xa5
    google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0xc00018e180, 0xc00018c180, 0xe4c000)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/internal/transport/http2_server.go:474 +0x9b
    google.golang.org/grpc.(*Server).serveStreams(0xc00032b880, 0xf2b578, 0xc00018e180)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:862 +0x103
    google.golang.org/grpc.(*Server).handleRawConn.func1(0xc00032b880, 0xf2b578, 0xc00018e180)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:821 +0x3f
    created by google.golang.org/grpc.(*Server).handleRawConn
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:820 +0x525
    goroutine 68 [running]:
    	goroutine running on other thread; stack unavailable
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
    goroutine 68 [running]:
    runtime.throw(0xe1ae40, 0x15)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/panic.go:1117 +0x72 fp=0xc000466f38 sp=0xc000466f08 pc=0x436bd2
    runtime.mapdelete(0xcda700, 0xc000318d50, 0xc000466fb0)
    	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/map.go:793 +0x43b fp=0xc000466f98 sp=0xc000466f38 pc=0x4102db
    github.com/pulumi/pulumi-command/provider/pkg/provider.(*commandProvider).removeContext(0xc000318d80, 0xf23160, 0xc000508a00)
    	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/provider.go:373 +0x59 fp=0xc000466fd0 sp=0xc000466f98 pc=0xc0bb39
    github.com/pulumi/pulumi-command/provider/pkg/provider.(*commandProvider).Create(0xc000318d80, 0xf23208, 0xc000422db0, 0xc0000982d0, 0x0, 0xf127a0, 0xc00050e820)
    	/home/runner/work/pulumi-command/pulumi-command/provider/pkg/provider/provider.go:216 +0xd33 fp=0xc000467880 sp=0xc000466fd0 pc=0xc0a273
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1(0xf23208, 0xc000422db0, 0xdae460, 0xc0000982d0, 0xdbcc40, 0x1472400, 0xf23208, 0xc000422db0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/proto/go/provider.pb.go:2602 +0x89 fp=0xc0004678c8 sp=0xc000467880 pc=0xba6729
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0xf23208, 0xc000422c60, 0xdae460, 0xc0000982d0, 0xc0001245c0, 0xc000504288, 0x0, 0x0, 0xf10ae0, 0xc00007f6f0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x308 fp=0xc000467b40 sp=0xc0004678c8 pc=0xbaa1e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler(0xdcfc20, 0xc000318d80, 0xf23208, 0xc000422c60, 0xc00004c9c0, 0xc000031920, 0xf23208, 0xc000422c60, 0xc00045b000, 0xfd6)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/proto/go/provider.pb.go:2604 +0x150 fp=0xc000467bb0 sp=0xc000467b40 pc=0xba0fb0
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032b880, 0xf2b578, 0xc00018e180, 0xc0000e0ea0, 0xc000318e10, 0x14354a0, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b fp=0xc000467e50 sp=0xc000467bb0 pc=0xb741cb
    google.golang.org/grpc.(*Server).handleStream(0xc00032b880, 0xf2b578, 0xc00018e180, 0xc0000e0ea0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c fp=0xc000467f68 sp=0xc000467e50 pc=0xb7838c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0001b6020, 0xc00032b880, 0xf2b578, 0xc00018e180, 0xc0000e0ea0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xab fp=0xc000467fb8 sp=0xc000467f68 pc=0xb863cb
    runtime.goexit()
    	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000467fc0 sp=0xc000467fb8 pc=0x46c5e1
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
 
    error: update failed
 
  command:remote:Command (create-acme-ssl):
    error: transport is closing
 
Resources:
    + 18 created
    26 unchanged

Duration: 4m18s
```

**Comment by Frassle** [comment]
@Abukamel that stacktrace is from the command provider. I've opened https://github.com/pulumi/pulumi-command/issues/54 to track it.
