### ISSUE TITLE
[Automation API] Improve the experience for unhandled promise rejections for nodejs inline programs

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#6057]
Here's a minimal repro for an error we're seeing:

```ts
const run = async () => {
    // This is our pulumi program in "inline function" form
    const pulumiProgram = async () => {
        //Promise.reject(new Error("rejected promise"))
        const engineVersion = gcp.container.getEngineVersions().then((v) => v.latestMasterVersion);
        return {
            engv: engineVersion
        };
    };

    // Create our stack 
    const args: InlineProgramArgs = {
        stackName: "dev1",
        projectName: "inlineNode",
        program: pulumiProgram
    };

    // create (or select if one already exists) a stack that uses our inline program
    const stack = await LocalWorkspace.createOrSelectStack(args);

    console.info("updating stack...");
    try {
        const upRes = await stack.up({ onOutput: console.info });
        console.log(`update summary: \n${JSON.stringify(upRes.summary.resourceChanges, null, 4)}`);
    }
    catch (e){
        console.log(e)
        process.exit(1)
    }
};

run().catch(err => {
    console.log("there was an error")
    console.log(err)
    console.log("error logged")
});
```

Which results in:

```
Evans-MBP:inlineProgram-ts evanboyle$ yarn start
yarn run v1.22.10
$ tsc && node ./bin/index.js
updating stack...
Updating (dev1)


View Live: https://app.pulumi.com/EvanBoyle/inlineNode/dev1/updates/23




resetting options
{
  project: 'inlineNode',
  stack: 'dev1',
  parallel: 2147483647,
  engineAddr: '127.0.0.1:51858',
  monitorAddr: '127.0.0.1:51860',
  dryRun: false
}
    pulumi:pulumi:Stack inlineNode-dev1 running 

    pulumi:pulumi:Stack inlineNode-dev1 running error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

    pulumi:pulumi:Stack inlineNode-dev1 running error: an unhandled error occurred: Program run without the Pulumi engine available; re-run using the `pulumi` CLI

    pulumi:pulumi:Stack inlineNode-dev1 **failed** 2 errors
 
Diagnostics:
  pulumi:pulumi:Stack (inlineNode-dev1):
    error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
        at requireTestModeEnabled (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/settings.js:124:15)
        at Object.getMonitor (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/settings.js:206:13)
        at /Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/invoke.js:123:40
        at Generator.next (<anonymous>)
        at fulfilled (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
    error: an unhandled error occurred: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
 
Resources:
    1 unchanged

Duration: 1s


CommandError: code: 255
 stdout: Updating (dev1)

View Live: https://app.pulumi.com/EvanBoyle/inlineNode/dev1/updates/23


    pulumi:pulumi:Stack inlineNode-dev1 running 
    pulumi:pulumi:Stack inlineNode-dev1 running error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    pulumi:pulumi:Stack inlineNode-dev1 running error: an unhandled error occurred: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    pulumi:pulumi:Stack inlineNode-dev1 **failed** 2 errors
 
Diagnostics:
  pulumi:pulumi:Stack (inlineNode-dev1):
    error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
        at requireTestModeEnabled (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/settings.js:124:15)
        at Object.getMonitor (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/settings.js:206:13)
        at /Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/invoke.js:123:40
        at Generator.next (<anonymous>)
        at fulfilled (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
    error: an unhandled error occurred: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
 
Resources:
    1 unchanged

Duration: 1s


 stderr: 
 err?: 

    at Object.createCommandError (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/pulumi/x/automation/errors.js:71:17)
    at ChildProcess.<anonymous> (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/pulumi/x/automation/cmd.js:63:40)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  commandResult: CommandResult {
    stdout: 'Updating (dev1)\n' +
      '\n' +
      'View Live: https://app.pulumi.com/EvanBoyle/inlineNode/dev1/updates/23\n' +
      '\n' +
      '\n' +
      '    pulumi:pulumi:Stack inlineNode-dev1 running \n' +
      '    pulumi:pulumi:Stack inlineNode-dev1 running error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI\n' +
      '    pulumi:pulumi:Stack inlineNode-dev1 running error: an unhandled error occurred: Program run without the Pulumi engine available; re-run using the `pulumi` CLI\n' +
      '    pulumi:pulumi:Stack inlineNode-dev1 **failed** 2 errors\n' +
      ' \n' +
      'Diagnostics:\n' +
      '  pulumi:pulumi:Stack (inlineNode-dev1):\n' +
      '    error: Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI\n' +
      '        at requireTestModeEnabled (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/settings.js:124:15)\n' +
      '        at Object.getMonitor (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/settings.js:206:13)\n' +
      '        at /Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/invoke.js:123:40\n' +
      '        at Generator.next (<anonymous>)\n' +
      '        at fulfilled (/Users/evanboyle/go/src/github.com/pulumi/automation-api-examples/nodejs/inlineProgram-ts/node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)\n' +
      '        at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
      '    error: an unhandled error occurred: Program run without the Pulumi engine available; re-run using the `pulumi` CLI\n' +
      ' \n' +
      'Resources:\n' +
      '    1 unchanged\n' +
      '\n' +
      'Duration: 1s\n' +
      '\n',
    stderr: '',
    code: 255,
    err: undefined
  }
}
error Command failed with exit code 1.
```

**Comment by EvanBoyle** [comment]
So invokes are promises, and failed invokes that don't have a `.catch` result in unhandled promise rejections. 

Here's a standard pulumi program:

```ts
import * as gcp from "@pulumi/gcp"

const engineVersion = gcp.container.getEngineVersions().then((v) => v.latestMasterVersion);
export const engv= engineVersion;
```

without setting the project this failed with an unhandled promise rejection:

```
 unhandled rejection: CONTEXT(457): Invoking function: tok=gcp:container/getEngineVersions:getEngineVersions asynchronously
    STACK_TRACE:
    Error:
        at Object.debuggablePromise (/Users/evanboyle/garbage/nodeerr/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at /Users/evanboyle/garbage/nodeerr/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45
        at Generator.next (<anonymous>)
        at fulfilled (/Users/evanboyle/garbage/nodeerr/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
    unhandled rejection: CONTEXT(457): Invoking function: tok=gcp:container/getEngineVersions:getEngineVersions asynchronously
    STACK_TRACE:
    Error:
        at Object.debuggablePromise (/Users/evanboyle/garbage/nodeerr/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at /Users/evanboyle/garbage/nodeerr/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45
        at Generator.next (<anonymous>)
        at fulfilled (/Users/evanboyle/garbage/nodeerr/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
    unhandled rejection: CONTEXT(457): Invoking function: tok=gcp:container/getEngineVersions:getEngineVersions asynchronously
    STACK_TRACE:
    Error:
        at Object.debuggablePromise (/Users/evanboyle/garbage/nodeerr/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
        at /Users/evanboyle/garbage/nodeerr/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45
        at Generator.next (<anonymous>)
        at fulfilled (/Users/evanboyle/garbage/nodeerr/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
 
    error: Running program '/Users/evanboyle/garbage/nodeerr' failed with an unhandled exception:
    Error: invocation of gcp:container/getEngineVersions:getEngineVersions returned an error: invoking gcp:container/getEngineVersions:getEngineVersions: 1 error occurred:
    	* project: required field is not set
    
    
        at /Users/evanboyle/garbage/nodeerr/node_modules/@pulumi/pulumi/runtime/invoke.js:139:33
        at Http2CallStream.<anonymous> (/Users/evanboyle/garbage/nodeerr/node_modules/@grpc/grpc-js/src/client.ts:155:9)
        at Http2CallStream.emit (events.js:327:22)
        at /Users/evanboyle/garbage/nodeerr/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14
        at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

I need to confirm whether or not this is the expected behavior.

**Comment by EvanBoyle** [comment]
Fix has been released in https://www.npmjs.com/package/@pulumi/pulumi
