### ISSUE TITLE
Wrong keyword argument name in Python usage example for Amazon Lex Intent

### ISSUE THREAD

**Issue by tlinhart** [pulumi/pulumi#6141]
File: [docs/reference/pkg/aws/lex/intent.md](https://www.pulumi.com/docs/reference/pkg/aws/lex/intent/)

The relevant part of the Python example reads:
```
           ...
            value_elicitation_prompt=aws.lex.IntentSlotValueElicitationPromptArgs(
                max_attempts=2,
                message=[{
                    "content": "What type of flowers would you like to order?",
                    "content_type": "PlainText",
                }],
            ),
           ...
```

When running `pulumi up` I receive an error:
```
Diagnostics:
  pulumi:pulumi:Stack (aws-lex-chatbot-aws-lex-chatbot-prod):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/pasmen/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/home/pasmen/tmp/pulumi-aws-lex-chatbot/infra/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/pasmen/tmp/pulumi-aws-lex-chatbot/infra/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 35, in run_pulumi_func
        func()
      File "/home/pasmen/tmp/pulumi-aws-lex-chatbot/infra/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 83, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/home/pasmen/tmp/pulumi-aws-lex-chatbot/infra/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 106, in __init__
        func()
      File "/home/pasmen/.pulumi/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/lib/python3.6/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 43, in <module>
        'content_type': 'PlainText'
    TypeError: __init__() got an unexpected keyword argument 'message'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

The keyword argument for `aws.lex.IntentSlotValueElicitationPromptArgs` should read `messages` instead of `message`. The documentation below is correct about this.

**Comment by emiliza** [comment]
Sounds like an artifact of https://github.com/pulumi/pulumi-terraform-bridge/issues/4

**Comment by pgavlin** [comment]
This has been fixed.
