### ISSUE TITLE
[Automation API] Crosswalk API Gateway Fails

### ISSUE THREAD

**Issue by johnstonbl01** [pulumi/pulumi#6162]
Hey! 👋 
When creating an AWS API Gateway using the automation API and the Pulumi Crosswalk library, the provisioning process fails. This behavior _does not_ occur when attempting to run the same code outside of the automation API.

## Expected Behavior

The automation API should be able to create an AWS API Gateway using the Pulumi Crosswalk (`@pulumi/awsx`) library.

## Current Behavior

While running the script, I get this error:

```
CommandError: code: 255
 stdout: Updating (my-company/development-blake-api-gateway)

View Live: https://app.pulumi.com/my-company/my-company-foundations-kafka/development-blake-api-gateway/updates/2


 +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway creating
 +  aws:apigateway:x:API hello-world creating
 +  aws:iam:Role hello-world1923ec7f creating
 +  aws:iam:Role hello-world1923ec7f created
 +  aws:lambda:Function hello-world1923ec7f creating
 +  aws:iam:RolePolicyAttachment hello-world1923ec7f-32be53a2 creating
 +  aws:iam:RolePolicyAttachment hello-world1923ec7f-32be53a2 created
 +  aws:lambda:Function hello-world1923ec7f created
 +  aws:apigateway:RestApi hello-world creating
 +  aws:apigateway:RestApi hello-world creating error: 1 error occurred:
 +  aws:apigateway:RestApi hello-world **creating failed** error: 1 error occurred:
 +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway creating error: update failed
 +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway **creating failed** 1 error

Diagnostics:
  pulumi:pulumi:Stack (my-company-foundations-kafka-development-blake-api-gateway):
    error: update failed

  aws:apigateway:RestApi (hello-world):
    error: 1 error occurred:
        * creating urn:pulumi:development-blake-api-gateway::my-company-foundations-kafka::aws:apigateway:x:API$aws:apigateway/restApi:RestApi::hello-world: 1 error occurred:
        * error creating API Gateway specification: BadRequestException: Errors found during import:
        Unable to put integration on 'GET' for resource at path '/health': Invalid ARN specified in the request

Resources:
    + 5 created

Duration: 22s


 stderr:
 err?:

    at Object.createCommandError (/Users/blake/dev/my-company/my-company-foundations-kafka/node_modules/@pulumi/pulumi/x/automation/errors.js:71:17)
    at ChildProcess.<anonymous> (/Users/blake/dev/my-company/my-company-foundations-kafka/node_modules/@pulumi/pulumi/x/automation/cmd.js:63:40)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) {
  commandResult: CommandResult {
    stdout: 'Updating (my-company/development-blake-api-gateway)\n' +
      '\n' +
      'View Live: https://app.pulumi.com/my-company/my-company-foundations-kafka/development-blake-api-gateway/updates/2\n' +
      '\n' +
      '\n' +
      ' +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway creating \n' +
      ' +  aws:apigateway:x:API hello-world creating \n' +
      ' +  aws:iam:Role hello-world1923ec7f creating \n' +
      ' +  aws:iam:Role hello-world1923ec7f created \n' +
      ' +  aws:lambda:Function hello-world1923ec7f creating \n' +
      ' +  aws:iam:RolePolicyAttachment hello-world1923ec7f-32be53a2 creating \n' +
      ' +  aws:iam:RolePolicyAttachment hello-world1923ec7f-32be53a2 created \n' +
      ' +  aws:lambda:Function hello-world1923ec7f created \n' +
      ' +  aws:apigateway:RestApi hello-world creating \n' +
      ' +  aws:apigateway:RestApi hello-world creating error: 1 error occurred:\n' +
      ' +  aws:apigateway:RestApi hello-world **creating failed** error: 1 error occurred:\n' +
      ' +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway creating error: update failed\n' +
      ' +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway **creating failed** 1 error\n' +
      ' \n' +
      'Diagnostics:\n' +
      '  pulumi:pulumi:Stack (my-company-foundations-kafka-development-blake-api-gateway):\n' +
      '    error: update failed\n' +
      ' \n' +
      '  aws:apigateway:RestApi (hello-world):\n' +
      '    error: 1 error occurred:\n' +
      '    \t* creating urn:pulumi:development-blake-api-gateway::my-company-foundations-kafka::aws:apigateway:x:API$aws:apigateway/restApi:RestApi::hello-world: 1 error occurred:\n' +
      '    \t* error creating API Gateway specification: BadRequestException: Errors found during import:\n' +
      "    \tUnable to put integration on 'GET' for resource at path '/health': Invalid ARN specified in the request\n" +
      ' \n' +
      'Resources:\n' +
      '    + 5 created\n' +
      '\n' +
      'Duration: 22s\n' +
      '\n',
    stderr: '',
    code: 255,
    err: undefined
  }
}
```

After this fails, occasionally a `pulumi destroy` would also fail. I couldn't recreate the error this morning, figured I'd document it just in case it's helpful in any way. After looking into the error a bit more, it seemed like one of the updates would get stuck in the pending state, and I'd have to:

- `pulumi stack export >> stack.json`
- Remove the pending operation
- Manually delete the API Gateway via the AWS CLI
- `pulumi stack import --file stack.json`
- `pulumi refresh`
- `pulumi destroy`

## Steps to Reproduce

Here's a code sample that fails:

```ts
import { LocalWorkspace } from '@pulumi/pulumi/x/automation';
import * as awsx from '@pulumi/awsx';

async function createInfra(): Promise<{
  endpointUrl: string;
}> {
  const pulumiProgram = async () => {
    const endpoint = new awsx.apigateway.API('hello-world', {
      routes: [
        {
          path: '/health',
          method: 'GET',
          eventHandler: async () => {
            return {
              statusCode: 200,
              body: 'Hello world'
            };
          }
        }
      ]
    });

    return {
      endpointUrl: endpoint.url
    };
  };

  const args = {
    stackName: 'my-company/development-blake-api-gateway',
    projectName: 'my-company-foundations-kafka',
    program: pulumiProgram
  };

  const stack = await LocalWorkspace.createOrSelectStack(args);
  await stack.workspace.installPlugin('aws', 'v3.6.1');
  await stack.setConfig('aws:region', { value: 'us-east-2' });
  await stack.refresh({ onOutput: console.info });

  await stack.up({ onOutput: console.info });
  const stackOutputs = await stack.outputs();

  return {
    endpointUrl: stackOutputs.endpointUrl.value
  };
}

createInfra().catch((err) => console.error(err));
```

I'm running the above using a command like: `npx ts-node file.ts`

## Context (Environment)

We have been using the automation API as a way to stand up infra for integration tests. As of now, we're unable to do this with an API Gateway using the Pulumi Crosswalk library.

Environment details:
- `@pulumi/aws` v3.23.0
- `@pulumi/awsx` v0.22.0
- `@pulumi/pulumi` v2.17.1
- `typescript` v4.1.3
- macOS Catalina v10.15.17

*Update*
After chatting in Slack with @pierskarsenbarg, he suggested switching to using a `LocalProgram` ([example](https://github.com/pulumi/automation-api-examples/tree/main/nodejs/localProgram-tsnode-mochatests)) instead of an `InlineProgram`. Doing this, we were able to get the API Gateway up and running. However, we would still like to use the `InlineProgram` in the future for similar scenarios if possible.

**Comment by EvanBoyle** [comment]
I believe the issue you're seeing here is related to working directory and closure serialization of the javascript function: https://github.com/pulumi/pulumi/issues/5578

Can you try the workaround listed here: https://github.com/pulumi/pulumi/issues/5578#issuecomment-709628863

**Comment by johnstonbl01** [comment]
@EvanBoyle We'll give that a try - thanks!

**Comment by johnstonbl01** [comment]
@EvanBoyle I've tried adding the `workDir` to the stack args like this:

```ts
  const args = {
    stackName: 'my-company/development-blake-api-gateway',
    projectName: 'my-company-foundations-kafka',
    program: pulumiProgram,
    workDir: '.'
  };
```

I still get the same error. Here's the full output:

```
12:47:16 blake pulumi-api-gateway npx ts-node index.ts
Refreshing (my-company/development-blake-api-gateway)


View Live: https://app.pulumi.com/my-company/my-company-foundations-kafka/development-blake-api-gateway/updates/28





Resources:

Duration: 1s


Updating (my-company/development-blake-api-gateway)


View Live: https://app.pulumi.com/my-company/my-company-foundations-kafka/development-blake-api-gateway/updates/29




 +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway creating

 +  aws:apigateway:x:API hello-world creating

 +  aws:iam:Role hello-world1923ec7f creating

 +  aws:iam:Role hello-world1923ec7f created

 +  aws:lambda:Function hello-world1923ec7f creating
 +  aws:iam:RolePolicyAttachment hello-world1923ec7f-32be53a2 creating

 +  aws:iam:RolePolicyAttachment hello-world1923ec7f-32be53a2 created

 +  aws:lambda:Function hello-world1923ec7f created

 +  aws:apigateway:RestApi hello-world creating

 +  aws:apigateway:RestApi hello-world creating error: 1 error occurred:

 +  aws:apigateway:RestApi hello-world **creating failed** error: 1 error occurred:

 +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway creating error: update failed

 +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway **creating failed** 1 error

Diagnostics:
  aws:apigateway:RestApi (hello-world):
    error: 1 error occurred:
    	* creating urn:pulumi:development-blake-api-gateway::my-company-foundations-kafka::aws:apigateway:x:API$aws:apigateway/restApi:RestApi::hello-world: 1 error occurred:
    	* error creating API Gateway specification: BadRequestException: Errors found during import:
    	Unable to put integration on 'GET' for resource at path '/health': Invalid ARN specified in the request

  pulumi:pulumi:Stack (my-company-foundations-kafka-development-blake-api-gateway):
    error: update failed

Resources:
    + 5 created

Duration: 21s


CommandError: code: 255
 stdout: Updating (my-company/development-blake-api-gateway)

View Live: https://app.pulumi.com/my-company/my-company-foundations-kafka/development-blake-api-gateway/updates/29


 +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway creating
 +  aws:apigateway:x:API hello-world creating
 +  aws:iam:Role hello-world1923ec7f creating
 +  aws:iam:Role hello-world1923ec7f created
 +  aws:lambda:Function hello-world1923ec7f creating
 +  aws:iam:RolePolicyAttachment hello-world1923ec7f-32be53a2 creating
 +  aws:iam:RolePolicyAttachment hello-world1923ec7f-32be53a2 created
 +  aws:lambda:Function hello-world1923ec7f created
 +  aws:apigateway:RestApi hello-world creating
 +  aws:apigateway:RestApi hello-world creating error: 1 error occurred:
 +  aws:apigateway:RestApi hello-world **creating failed** error: 1 error occurred:
 +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway creating error: update failed
 +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway **creating failed** 1 error

Diagnostics:
  aws:apigateway:RestApi (hello-world):
    error: 1 error occurred:
    	* creating urn:pulumi:development-blake-api-gateway::my-company-foundations-kafka::aws:apigateway:x:API$aws:apigateway/restApi:RestApi::hello-world: 1 error occurred:
    	* error creating API Gateway specification: BadRequestException: Errors found during import:
    	Unable to put integration on 'GET' for resource at path '/health': Invalid ARN specified in the request

  pulumi:pulumi:Stack (my-company-foundations-kafka-development-blake-api-gateway):
    error: update failed

Resources:
    + 5 created

Duration: 21s


 stderr: warning: A new version of Pulumi is available. To upgrade from version '2.17.2' to '2.18.0', run
   $ brew upgrade pulumi
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

 err?:

    at Object.createCommandError (/Users/blake/dev/my-company/pulumi-api-gateway/node_modules/@pulumi/pulumi/x/automation/errors.js:71:17)
    at ChildProcess.<anonymous> (/Users/blake/dev/my-company/pulumi-api-gateway/node_modules/@pulumi/pulumi/x/automation/cmd.js:63:40)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) {
  commandResult: CommandResult {
    stdout: 'Updating (my-company/development-blake-api-gateway)\n' +
      '\n' +
      'View Live: https://app.pulumi.com/my-company/my-company-foundations-kafka/development-blake-api-gateway/updates/29\n' +
      '\n' +
      '\n' +
      ' +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway creating \n' +
      ' +  aws:apigateway:x:API hello-world creating \n' +
      ' +  aws:iam:Role hello-world1923ec7f creating \n' +
      ' +  aws:iam:Role hello-world1923ec7f created \n' +
      ' +  aws:lambda:Function hello-world1923ec7f creating \n' +
      ' +  aws:iam:RolePolicyAttachment hello-world1923ec7f-32be53a2 creating \n' +
      ' +  aws:iam:RolePolicyAttachment hello-world1923ec7f-32be53a2 created \n' +
      ' +  aws:lambda:Function hello-world1923ec7f created \n' +
      ' +  aws:apigateway:RestApi hello-world creating \n' +
      ' +  aws:apigateway:RestApi hello-world creating error: 1 error occurred:\n' +
      ' +  aws:apigateway:RestApi hello-world **creating failed** error: 1 error occurred:\n' +
      ' +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway creating error: update failed\n' +
      ' +  pulumi:pulumi:Stack my-company-foundations-kafka-development-blake-api-gateway **creating failed** 1 error\n' +
      ' \n' +
      'Diagnostics:\n' +
      '  aws:apigateway:RestApi (hello-world):\n' +
      '    error: 1 error occurred:\n' +
      '    \t* creating urn:pulumi:development-blake-api-gateway::my-company-foundations-kafka::aws:apigateway:x:API$aws:apigateway/restApi:RestApi::hello-world: 1 error occurred:\n' +
      '    \t* error creating API Gateway specification: BadRequestException: Errors found during import:\n' +
      "    \tUnable to put integration on 'GET' for resource at path '/health': Invalid ARN specified in the request\n" +
      ' \n' +
      '  pulumi:pulumi:Stack (my-company-foundations-kafka-development-blake-api-gateway):\n' +
      '    error: update failed\n' +
      ' \n' +
      'Resources:\n' +
      '    + 5 created\n' +
      '\n' +
      'Duration: 21s\n' +
      '\n',
    stderr: "warning: A new version of Pulumi is available. To upgrade from version '2.17.2' to '2.18.0', run \n" +
      '   $ brew upgrade pulumi\n' +
      'or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.\n',
    code: 255,
    err: undefined
  }
}
```

**Comment by johnstonbl01** [comment]
Here is an example of the `pulumi destroy` error that we're occasionally running into when we get the above error:

```
     Type                             Name                                                            Status                  Info
     pulumi:pulumi:Stack              my-company-services-dilithium-development-integration-api-gateway  **failed**              1 error
 -   └─ aws:iam:RolePolicyAttachment  hello-world1923ec7f-32be53a2                                    **deleting failed**     1 error
Diagnostics:
  aws:iam:RolePolicyAttachment (hello-world1923ec7f-32be53a2):
    error: pre-step event returned an error: failed to verify snapshot: resource urn:pulumi:development-integration-api-gateway::my-company-services-dilithium::aws:apigateway:x:API$aws:apigateway/restApi:RestApi::hello-world dependency  refers to missing resource
  pulumi:pulumi:Stack (my-company-services-dilithium-development-integration-api-gateway):
    error: update failed
```

When this error occurs, we've got to go through the steps mentioned in the issue to fix it and allow the destroy to proceed. Not sure if this is helpful, but wanted to mention it now that we've seen it again.

**Comment by EvanBoyle** [comment]
Fixed via https://github.com/pulumi/pulumi/pull/6743 see comment here for more details: https://github.com/pulumi/pulumi/issues/5578#issuecomment-817013936
