### ISSUE TITLE
pulumi up fails with TypeError: __init__() got an unexpected keyword argument 'status'

### ISSUE THREAD

**Issue by rgeraskin** [pulumi/pulumi#6188]
Can't deploy helm chart `cert-manager` with values `"installCRDs": True`

## Current Behavior
pulumi up fails with `TypeError: __init__() got an unexpected keyword argument 'status'`

## Steps to Reproduce
```
from pulumi_kubernetes.helm.v3 import Chart, ChartOpts, FetchOpts

cert_manager = Chart(
    "cert-manager",
    ChartOpts(chart="cert-manager",
              version="v1.1.0",
              fetch_opts=FetchOpts(repo="https://charts.jetstack.io"),
              values={"installCRDs": True}),
)
```
1. pulumi up

```
❯ pulumi up                                                                                                                                                                    at 02:25:59 
Previewing update (dev)

View Live: ...

     Type                                                                             Name                                    Plan       Info
 +   pulumi:pulumi:Stack                                                              umbrella2-dev                           create     3 errors
 +   └─ kubernetes:helm.sh/v3:Chart                                                   cert-manager                            create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        cert-manager-cainjector                 create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        cert-manager-controller-issuers         create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        cert-manager-controller-clusterissuers  create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        cert-manager-controller-challenges      create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        cert-manager-controller-certificates    create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        cert-manager-view                       create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 cert-manager-cainjector                 create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        cert-manager-controller-ingress-shim    create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        cert-manager-edit                       create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        cert-manager-controller-orders          create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 cert-manager-controller-certificates    create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 cert-manager-controller-issuers         create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 cert-manager-controller-clusterissuers  create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 cert-manager-controller-challenges      create
 +      ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 cert-manager-controller-orders          create
 +      ├─ kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration  cert-manager-webhook                    create
 +      ├─ kubernetes:admissionregistration.k8s.io/v1:MutatingWebhookConfiguration    cert-manager-webhook                    create
 +      └─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 cert-manager-controller-ingress-shim    create

Diagnostics:
  pulumi:pulumi:Stack (umbrella2-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 504, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 79, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 200, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 186, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/output.py", line 185, in run
        return await transformed.future(with_unknowns=True)
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/output.py", line 185, in run
        return await transformed.future(with_unknowns=True)
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/output.py", line 154, in run
        value = await self._future
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/output.py", line 351, in gather_futures
        return await asyncio.gather(*value_futures)
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/output.py", line 113, in get_value
        val = await self._future
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/output.py", line 154, in run
        value = await self._future
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi/output.py", line 175, in run
        transformed: Input[U] = func(value)
      File "/mnt/d/Projects/other/pulumi/umbrella/venv/lib/python3.9/site-packages/pulumi_kubernetes/yaml.py", line 519, in <lambda>
        CustomResourceDefinition(f"{x}", opts, **obj)))]
    TypeError: __init__() got an unexpected keyword argument 'status'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

❯ pulumi version
v2.18.2

**Comment by lukehoban** [comment]
This looks like the same issue tracked in https://github.com/pulumi/pulumi-kubernetes/issues/800.
