### ISSUE TITLE
previewing or updating an AWS EKS ManagedNodeGroup hit an assertion failure

### ISSUE THREAD

**Issue by sunbing81** [pulumi/pulumi#6227]
After creating an eks.ManagedNodeGroup, any modification of the spec causes `pulumi preview` panic:

```
An assertion has failed: Expected diff to not require deletion or replacement during Update of urn:pulumi:master::eks-cluster-development::eks:index:ManagedNodeGroup$aws:eks/nodeGroup:NodeGroup::cluster-eksCluster-76b9986_ng0
```

## Steps to Reproduce

1. create a managed node group (`new eks.ManagedNodeGroup`)
2. change any config (not necessarily, because a dynamic input causes the panic too), e.g. `scalingConfig.maxSize`, `launchTemplate.version` , `instanceTypes`, etc.
3. run `pulumi preview` or `pulumi up`
4. panic

## Context (Environment)

Package Versions:
@pulumi/aws: 3.26.1
@pulumi/awsx: 0.24.0
@pulumi/eks: 0.22.0
@pulumi/pulumi: 2.19.0

A node group can be created successfully by `pulumi up` with
```typescript
new eks.ManagedNodeGroup(`${cluster_name}_ng0`, {
	tags: common_tags,
	cluster: cluster,
	nodeRole: eks_instance_role.role,

	/* aws.eks.NodeGroupArgs */
	// lanuch template: aws will create a new template based on the source template
	launchTemplate: {
		id: lt.id,
		version: lt.defaultVersion.apply((v: any) => v as string)
	},
	// node parameters
	amiType: 'AL2_x86_64',
	remoteAccess: {
		/* aws.eks.NodeGroupRemoteAccess */
	},
	// auto scaling
	capacityType: 'ON_DEMAND',
	instanceTypes: [ 't3a.small' ],
	subnetIds: infra.getOutput('vpcPrivateSubnetIds'),
	scalingConfig: {
		/* aws.eks.NodeGroupScalingConfig */
		desiredSize: 2,
		minSize: 1,
		maxSize: 2
	}
});
```

But after that, re-running `pulumi preview --diff` simply throw with
```
         ~ aws:eks/nodeGroup:NodeGroup: (update)
            [id=cluster-eksCluster-76b9986:cluster-eksCluster-76b9986_ng0-065953c]
            [urn=urn:pulumi:master::eks-cluster-evelopment::eks:index:ManagedNodeGroup$aws:eks/nodeGroup:NodeGroup::cluster-eksCluster-76b9986_ng0]
            [provider=urn:pulumi:master::eks-cluster-development::pulumi:providers:aws::default_3_26_1::14e46c11-c695-44d0-90b3-fae92bebc42a]
          ~ launchTemplate: {
              ~ version: "1" => output<string>
            }
panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update of urn:pulumi:master::eks-cluster-development::eks:index:ManagedNodeGroup$aws:eks/nodeGroup:NodeGroup::cluster-eksCluster-76b9986_ng0
```

If we change the value ` lt.defaultVersion.apply((v: any) => v as string)` to `'1'`, everything is just fine; while any other value (e.g. `'2'`) doesn't work (the same assertion failure) again.

Furthermore, changing any other arguments (tested with capacityType, instanceTypes, scalingConfig, and tags) causes panic.

**Comment by sunbing81** [comment]
Detailed trace:

```
        ~ aws:eks/nodeGroup:NodeGroup: (update)
            [id=cluster-eksCluster-76b9986:cluster-eksCluster-76b9986_ng0-065953c]
            [urn=urn:pulumi:master::eks-cluster-development::eks:index:ManagedNodeGroup$aws:eks/nodeGroup:NodeGroup::cluster-eksCluster-76b9986_ng0]
            [provider=urn:pulumi:master::eks-cluster-development::pulumi:providers:aws::default_3_26_1::14e46c11-c695-44d0-90b3-fae92bebc42a]
          ~ launchTemplate: {
              ~ version: "1" => output<string>
            }
panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update of urn:pulumi:master::eks-cluster-development::eks:index:ManagedNodeGroup$aws:eks/nodeGroup:NodeGroup::cluster-eksCluster-76b9986_ng0

goroutine 104 [running]:

github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)

	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.18.1-0.20210121021731-8f7dfbb5ae22/go/common/util/contract/failfast.go:23

github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0xc00015b400, 0x6e6dc63, 0x48, 0xc001921778, 0x1, 0x1)

	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.18.1-0.20210121021731-8f7dfbb5ae22/go/common/util/contract/assert.go:33 +0x1a5

github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Update(0xc00000a5a0, 0x7863d80, 0xc00310e8a0, 0xc002a1f480, 0xc00000a5a0, 0x5f48e01, 0xc00311cfc0)

	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.18.1/pkg/tfbridge/provider.go:970 +0x8e5

github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler.func1(0x7863d80, 0xc00310e8a0, 0x6b5dee0, 0xc002a1f480, 0x6b1f440, 0xba8a200, 0x7863d80, 0xc00310e8a0)

	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.18.1-0.20210121021731-8f7dfbb5ae22/proto/go/provider.pb.go:2305 +0x8b

github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x7863d80, 0xc002ce0c60, 0x6b5dee0, 0xc002a1f480, 0xc002bf7660, 0xc002bf7680, 0x0, 0x0, 0x7792540, 0xc00039ad20)

	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f6

github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler(0x6c238c0, 0xc00000a5a0, 0x7863d80, 0xc002ce0c60, 0xc002c96de0, 0xc0017ee2c0, 0x7863d80, 0xc002ce0c60, 0xc002cec000, 0x942)

	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.18.1-0.20210121021731-8f7dfbb5ae22/proto/go/provider.pb.go:2307 +0x150

google.golang.org/grpc.(*Server).processUnaryRPC(0xc000e84c40, 0x7889ce0, 0xc001882000, 0xc000dd3c00, 0xc00182e0c0, 0xba457f8, 0x0, 0x0, 0x0)

	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x522

google.golang.org/grpc.(*Server).handleStream(0xc000e84c40, 0x7889ce0, 0xc001882000, 0xc000dd3c00, 0x0)

	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05

google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0017e4710, 0xc000e84c40, 0x7889ce0, 0xc001882000, 0xc000dd3c00)

	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xa5

created by google.golang.org/grpc.(*Server).serveStreams.func1

	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Resources:
    ~ 5 to update
    27 unchanged
Error: invocation of kubernetes:helm:template returned an error: transport is closing

    at /data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/invoke.js:139:33

    at Http2CallStream.<anonymous> (/data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@grpc/grpc-js/src/client.ts:155:9)

    at Http2CallStream.emit (node:events:388:22)

    at /data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14

    at processTicksAndRejections (node:internal/process/task_queues:75:11)

unhandled rejection: CONTEXT(1786): Invoking function: tok=kubernetes:helm:template asynchronously

STACK_TRACE:

Error: 

    at Object.debuggablePromise (/data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)

    at /data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45

    at Generator.next (<anonymous>)

    at fulfilled (/data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)

    at processTicksAndRejections (node:internal/process/task_queues:93:5)

Error: invocation of kubernetes:helm:template returned an error: transport is closing

    at /data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/invoke.js:139:33

    at Http2CallStream.<anonymous> (/data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@grpc/grpc-js/src/client.ts:155:9)

    at Http2CallStream.emit (node:events:388:22)

    at /data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14

    at processTicksAndRejections (node:internal/process/task_queues:75:11)

Error: invocation of kubernetes:helm:template returned an error: transport is closing

    at /data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/invoke.js:139:33

    at Http2CallStream.<anonymous> (/data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@grpc/grpc-js/src/client.ts:155:9)

    at Http2CallStream.emit (node:events:388:22)

    at /data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14

    at processTicksAndRejections (node:internal/process/task_queues:75:11)

Error: invocation of kubernetes:helm:template returned an error: transport is closing

    at /data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/invoke.js:139:33

    at Http2CallStream.<anonymous> (/data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@grpc/grpc-js/src/client.ts:155:9)

    at Http2CallStream.emit (node:events:388:22)

    at /data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@grpc/grpc-js/src/call-stream.ts:186:14

    at processTicksAndRejections (node:internal/process/task_queues:75:11)

unhandled rejection: CONTEXT(1786): Invoking function: tok=kubernetes:helm:template asynchronously

STACK_TRACE:

Error: 

    at Object.debuggablePromise (/data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)

    at /data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45

    at Generator.next (<anonymous>)

    at fulfilled (/data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)

    at processTicksAndRejections (node:internal/process/task_queues:93:5)

unhandled rejection: CONTEXT(1786): Invoking function: tok=kubernetes:helm:template asynchronously

STACK_TRACE:

Error: 

    at Object.debuggablePromise (/data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)

    at /data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45

    at Generator.next (<anonymous>)

    at fulfilled (/data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)

    at processTicksAndRejections (node:internal/process/task_queues:93:5)

unhandled rejection: CONTEXT(1786): Invoking function: tok=kubernetes:helm:template asynchronously

STACK_TRACE:

Error: 

    at Object.debuggablePromise (/data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)

    at /data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/invoke.js:126:45

    at Generator.next (<anonymous>)

    at fulfilled (/data/repositories/org/works/qmrz/infrastructure/aws/shared-resources-and-services/pulumi/qmrz/eks-cluster-development/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)

    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by emiliza** [comment]
Took a quick look, and can confirm- this is still an issue with the latest 3.9.0, I have a simple repro [here](https://gist.github.com/emiliza/a2b69242fc3e38c16cb22b68cc5e4ec6)

**Comment by emiliza** [comment]
Looks to be a bug within the terraform bridge
