### ISSUE TITLE
Symbol.prototype [ @@toPrimitive ] TypeError when deploying cloud function with GraphQL sdk

### ISSUE THREAD

**Issue by Frenkz** [pulumi/pulumi#6229]
Hi, I am trying to get a cloud function to run on GCP with an auto-generated GraphQL SDK from https://graphql-code-generator.com/. See: https://github.com/Frenkz/pulumi-test

When I deploy it with Pulumi I receive the error below. 
This is the generated code for the cloud function: https://gist.github.com/Frenkz/73efc927c8b48758447801082dd81979#file-gistfile1-txt-L196

Does anyone have some suggestions how to make this work? Thanks!

```
Diagnostics:
  gcp:cloudfunctions:Function (test-topic-triggered):
    error: 1 error occurred:
        * creating urn:pulumi:test::ts::gcp:pubsub/topic:Topic$gcp:cloudfunctions:CallbackFunction$gcp:cloudfunctions/function:Function::test-topic-triggered: 1 error occurred:
        * Error waiting for Creating CloudFunctions Function: Error code 3, message: Function failed on loading user code. This is likely due to a bug in the user code. Error message: Code in file index.js can't be loaded.
    Is there a syntax error in your code?
    Detailed stack trace: TypeError: Symbol.prototype [ @@toPrimitive ] requires that 'this' be a Symbol
        at Symbol.[Symbol.toPrimitive] (<anonymous>)
        at Object.<anonymous> (/srv/index.js:196:76)
        at Module._compile (module.js:653:30)
        at Object.Module._extensions..js (module.js:664:10)
        at Module.load (module.js:566:32)
        at tryModuleLoad (module.js:506:12)
        at Function.Module._load (module.js:498:3)
        at Module.require (module.js:597:17)
        at require (internal/module.js:11:18)
        at getUserFunction (/worker/worker.js:442:24). Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.

  pulumi:pulumi:Stack (ts-test):
    error: update failed

Outputs:
    topics: [
        [0]: "test.topic-ad2309c"
    ]

Resources:
    + 5 created
```

I've also tried using webpack: https://github.com/Frenkz/pulumi-test/tree/webpack

This results in a different problem which I also couldn't find any information on.

```
Diagnostics:
  pulumi:pulumi:Stack (ts-test):
    (node:16044) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    Error: Cannot find module 'assert'
        at r (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure sync:2:10)
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:1006:25
        at Generator.next (<anonymous>)
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:21:71
        at new Promise (<anonymous>)
        at n (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:17:12)
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:993:16
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:989:26
        at Generator.next (<anonymous>)
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:21:71
    Error: Cannot find module 'assert'
        at r (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure sync:2:10)
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:1006:25
        at Generator.next (<anonymous>)
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:21:71
        at new Promise (<anonymous>)
        at n (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:17:12)
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:993:16
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:989:26
        at Generator.next (<anonymous>)
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:21:71
    (node:16044) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)

    error: Running program 'E:\ubersaas\pulumi-test' failed with an unhandled exception:
    Error: Cannot find module 'assert'
        at r (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure sync:2:10)
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:1006:25
        at Generator.next (<anonymous>)
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:21:71
        at new Promise (<anonymous>)
        at n (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:17:12)
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:993:16
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:989:26
        at Generator.next (<anonymous>)
        at E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:21:71

    unhandled rejection: CONTEXT(637): resource:test.topic.triggered[gcp:storage/bucketObject:BucketObject]
    STACK_TRACE:
    Error
        at Object.t.debuggablePromise (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\debuggable.js:69:5)
        at Object.t.registerResource (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\resource.js:219:18)
        at new d (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\resource.js:206:50)
        at new _ (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\resource.js:305:46)
        at new o (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\gcp\storage\bucketObject.js:85:9)
        at new u (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\gcp\cloudfunctions\zMixins.js:68:29)
        at o.n.Topic.onMessagePublished (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\gcp\pubsub\zMixins.js:11:12)
        at Object.<anonymous> (E:\ubersaas\pulumi-test\bin\webpack:\src\TestTopic.ts:14:11)
        at r (E:\ubersaas\pulumi-test\bin\webpack:\webpack\bootstrap:9:5)
        at Object.<anonymous> (E:\ubersaas\pulumi-test\bin\webpack:\index.ts:1:1)
    unhandled rejection: CONTEXT(637): resource:test.topic.triggered[gcp:storage/bucketObject:BucketObject]
    STACK_TRACE:
    Error
        at Object.t.debuggablePromise (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\debuggable.js:69:5)
        at Object.t.registerResource (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\runtime\resource.js:219:18)
        at new d (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\resource.js:206:50)
        at new _ (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\pulumi\resource.js:305:46)
        at new o (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\gcp\storage\bucketObject.js:85:9)
        at new u (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\gcp\cloudfunctions\zMixins.js:68:29)
        at o.n.Topic.onMessagePublished (E:\ubersaas\pulumi-test\bin\webpack:\node_modules\@pulumi\gcp\pubsub\zMixins.js:11:12)
        at Object.<anonymous> (E:\ubersaas\pulumi-test\bin\webpack:\src\TestTopic.ts:14:11)
        at r (E:\ubersaas\pulumi-test\bin\webpack:\webpack\bootstrap:9:5)
        at Object.<anonymous> (E:\ubersaas\pulumi-test\bin\webpack:\index.ts:1:1)

Outputs:
  - topics: [
  -     [0]: "test.topic-ad2309c"
    ]
```

**Comment by camjackson** [comment]
I'm getting this same error in a similar situation. I've created a lambda function using `apollo-server-graphql`, and am trying to deploy it using `awsx.apigateway.API`. Here's my code:

```ts
// lambda.ts
import { ApolloServer } from 'apollo-server-lambda';
import { typeDefs, resolvers } from './graphql';

export function createHandler() {
  return new ApolloServer({ typeDefs, resolvers }).createHandler();
}

// infra.ts
import * as aws from '@pulumi/aws';
import * as awsx from '@pulumi/awsx';
import { createHandler } from './lambda';

const eventHandler = new aws.lambda.CallbackFunction('my-callback', {
  callbackFactory: createHandler as any,
});

const endpoint = new awsx.apigateway.API('my-api', {
  routes: [{ path: '/', method: 'ANY' as any, eventHandler }],
});

export const url = endpoint.url;
```

The lambda creates successfully, but when I invoke it I get this:

```
{
    "errorType": "TypeError",
    "errorMessage": "Symbol.prototype [ @@toPrimitive ] requires that 'this' be a Symbol",
    "stack": [
        "TypeError: Symbol.prototype [ @@toPrimitive ] requires that 'this' be a Symbol",
        "    at Symbol.[Symbol.toPrimitive] (<anonymous>)",
        "    at Object.<anonymous> (/var/task/__index.js:97:68)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:75:12)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)"
    ]
}
```

Here's the snippet of `__index.js` pointed to by the stack trace (the final line is where the error happens):

```js
var __graphql_1_typeDefs_loc_proto = {};
__Location.prototype = __graphql_1_typeDefs_loc_proto;
Object.defineProperty(__graphql_1_typeDefs_loc_proto, "constructor", { configurable: true, writable: true, value: __Location });
__graphql_1_typeDefs_loc_proto.toJSON = __toJSON;
__graphql_1_typeDefs_loc_proto.inspect = __toJSON;
var __graphql_1_typeDefs_loc_proto_sym = Object.create(global.Symbol.prototype);
__graphql_1_typeDefs_loc_proto[__graphql_1_typeDefs_loc_proto_sym] = __toJSON;
```

I can reproduce this error in a node.js repl by reducing it down to:

```js
obj = {};
sym = Object.create(global.Symbol.prototype);
obj[sym] = 1; // Uncaught TypeError: Symbol.prototype [ @@toPrimitive ] requires that 'this' be a Symbol
```

I'm unsure yet whether this is being caused by apollo-server-lambda, pulumi, a combination, or something else. But this is what I know so far.

**Comment by camjackson** [comment]
This may also be because in my real codebase, the infra code and the graphql code are in different yarn workspaces. I think pulumi's automatic function serialisation is struggling with that. I'll probably have to fall back to compiling + packaging the code as a separate pre-step rather than using the `callbackFactory` approach.

**Comment by KaoruDev** [comment]
I came across this error while writing a Dynamic Resource Provider. I'm using [`graphql-request`](https://github.com/prisma-labs/graphql-request)

**Comment by KaoruDev** [comment]
I narrowed down the issue to [`graphql-tag`](https://github.com/apollographql/graphql-tag). I was able to get around this issue by configuring my `@graphql-codegen/typescript-graphql-request` plugin to use a different `gql` function.

My `codegen.yml` looks like:

```yaml
overwrite: true
schema: "schema.graphql"
documents:
  - "src/graphql/**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-graphql-request"
    config:
      gqlImport: "graphql-request#gql"
```

[`@graphql-codegen/typescript-graphql-request` plugin docs](https://www.graphql-code-generator.com/plugins/typescript-graphql-request)

**Comment by AMKamel** [comment]
I have this error using dynamic provider with `true-myth` library
```bash
  pulumi:pulumi:Stack (wordpress-dev):
    TypeError: Symbol.prototype [ @@toPrimitive ] requires that 'this' be a Symbol: TypeError: Symbol.prototype [ @@toPrimitive ] requires that 'this' be a Symbol
        at Symbol.[Symbol.toPrimitive] (<anonymous>)
        at Object.<anonymous> (<anonymous>:64:21)
        at Module._compile (node:internal/modules/cjs/loader:1099:14)
        at requireFromString (/home/abukamel/codebases/work/iac/pulumi/programs/wordpress/node_modules/require-from-string/index.js:28:4)
        at getProvider (/home/abukamel/codebases/work/iac/pulumi/programs/wordpress/node_modules/@pulumi/cmd/dynamic-provider/index.ts:66:20)
        at Object.<anonymous> (/home/abukamel/codebases/work/iac/pulumi/programs/wordpress/node_modules/@pulumi/cmd/dynamic-provider/index.ts:116:26)
        at Generator.next (<anonymous>)
        at /home/abukamel/codebases/work/iac/pulumi/programs/wordpress/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/home/abukamel/codebases/work/iac/pulumi/programs/wordpress/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:17:12)
 
  pulumi-nodejs:dynamic:Resource (zadgroup-dev-pulumiwp.zadapps.info-uptimerobot-monitor):
    error: Symbol.prototype [ @@toPrimitive ] requires that 'this' be a Symbol
```

The code works normally if it was not used directly without pulumi.

```typescript
export const getOrCreateMonitor = async (fqdn: string): Promise<Result<Monitor, string>> => {
    await checkApiKey()
    const currentMonitor = await getMonitor(fqdn)
    if (currentMonitor.isOk) {
        return currentMonitor
    }
    const alertContacts = await getAlertContacts()
    if (alertContacts.isErr) {
        return err(alertContacts.error)
    }
    const formattedAlertContacts = alertContacts.value.map((alertContact: AlertContact) => `${alertContact.id}_5_0`)
    const requestData =
        qs.stringify({
            ...sharedRequestData,
            type: '1',
            alert_contacts: formattedAlertContacts.join('-'),
            friendly_name: fqdn,
            url: `https://${fqdn}`
        })
    const response = await axios.post(newMonitorUrl, requestData, sharedRequestConfig)
    if (response.data.stat != 'ok') {
        return err(response.data.error.message)
    }
    const newMonitor: Monitor = response.data.monitor
    return ok(newMonitor)
}
```

**Comment by thantos** [comment]
Ran into this issue too. The root cause is that Pulumi sees the symbol as a normal, "complex" object, grabs its prototype, and creates the symbol using said prototype rather than properly creating a new symbol.

Start:
```ts
const symbol = Symbol("@aws-cdk/core.DependableTrait");
table[symbol] = {};
```

Seralized:
```js
var __database_resource_table_sym = Object.create(global.Symbol.prototype);
var __0_database_resource_table_sym = {};
__database_resource_table[__database_resource_table_sym] = __0_database_resource_table_sym;
```

Unfortunately, symbols don't seem to work when created using the prototype as the `toPrimive` method fails 

```ts
"Symbol.prototype [ @@toPrimitive ] requires that 'this' be a Symbol"
```

Pulumi also loses the description on the symbol.

Making some changes to the internal library, this works

https://github.com/pulumi/pulumi/blob/b31c5b136c6e6626c6b5bac8b2b8a777135586bb/sdk/nodejs/runtime/closure/createClosure.ts#L1038-L1044

```ts
        if (!object.proto && !object.sym) {
            const proto = Object.getPrototypeOf(obj);
            if(proto === Symbol.prototype) { // Also treat symbol as a special case
                object.sym = obj; // added a new info object to maintain the symbol
            }
            else if (proto !== Object.prototype) {
                object.proto = await getOrCreateEntryAsync(
                    proto, undefined, context, serialize, logInfo);
            }
        }
```

https://github.com/pulumi/pulumi/blob/b31c5b136c6e6626c6b5bac8b2b8a777135586bb/sdk/nodejs/runtime/closure/serializeClosure.ts#L340-L343

```ts
            if (obj.proto) {
                const protoVar = envEntryToString(obj.proto, `${varName}_proto`);
                environmentText += `var ${envVar} = Object.create(${protoVar});\n`;
            } else if(obj.sym) { // output the symbol
                // @ts-ignore
                environmentText += `var ${envVar} = Symbol("${obj.sym.description}");\n`;
            }
```

**Comment by andreujuanc** [comment]
I just encountered this issue.
Can be "fixed" by making the output be:
```diff
-var __sym = Object.create(global.Symbol.prototype);
+var __sym = global.Symbol;
```

Hopefully we can get a quick fix on the nodejs closure library. :)

**Comment by iam-yan** [comment]
@andreujuanc 

I am struggling with issue as well.
May I ask how I can efficiently "retouch" the output with the "fix" you shared?

**Comment by JoeHartzell** [comment]
I have also just encountered this using `@grpc/grpc-js` while trying to make a dynamic resource provider. My workaround is to use dynamic imports. My guess is that would also work for the `graphql-request` folks. 

```
class MyProvider {
  async create(inputs) {
    const { MyGrpcClient } = await import('./path/to/service_grpc_pb')
  }
}
```

**Comment by thehenrymcintosh** [comment]
Also having this issue, thank you so much for the fix @AMKamel, and would be great to see a fix implemented in Pulumi. 

> I narrowed down the issue to [`graphql-tag`](https://github.com/apollographql/graphql-tag). I was able to get around this issue by configuring my `@graphql-codegen/typescript-graphql-request` plugin to use a different `gql` function.
> 
> My `codegen.yml` looks like:
> 
> overwrite: true
> schema: "schema.graphql"
> documents:
>   - "src/graphql/**/*.graphql"
> generates:
>   src/generated/graphql.ts:
>     plugins:
>       - "typescript"
>       - "typescript-operations"
>       - "typescript-graphql-request"
>     config:
>       gqlImport: "graphql-request#gql"
> [`@graphql-codegen/typescript-graphql-request` plugin docs](https://www.graphql-code-generator.com/plugins/typescript-graphql-request)
