### ISSUE TITLE
Dynamic Provider resolving inputs too early.

### ISSUE THREAD

**Issue by liamawhite** [pulumi/pulumi#6239]
I have a component resource that groups aurora with various support resources. The dynamic provider basically creates a Kube job that runs SQL against the created cluster (it has to be like this because Aurora isn't reachable from where Pulumi is run).

As part of this the dynamic resource is passed details about the cluster, but when I run pulumi up the underlying RDS cluster is still undefined at the point the dynamic resource is handled.

## Expected Behavior
The cluster should not be undefined.

## Current Behavior
```
pulumi:pulumi:Stack (operations-infra.operations.aws):
    TypeError: Cannot read property 'endpoint' of undefined
        at ComponentResource.get hostname [as hostname] (/Users/liam/dev/src/github.com/tetrateio/tetrate/xxx/lib/aws/aurora/postgres.ts:52:63)
        at /Users/liam/dev/src/github.com/tetrateio/tetrate/cloud/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:1086:19
        at Generator.next (<anonymous>)
        at /Users/liam/dev/src/github.com/tetrateio/tetrate/cloud/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/liam/dev/src/github.com/tetrateio/tetrate/cloud/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:17:12)
        at getOwnPropertyAsync (/Users/liam/dev/src/github.com/tetrateio/tetrate/cloud/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:1085:12)
        at /Users/liam/dev/src/github.com/tetrateio/tetrate/cloud/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:716:40
        at Generator.next (<anonymous>)
        at fulfilled (/Users/liam/dev/src/github.com/tetrateio/tetrate/cloud/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:18:58)
```

[full stack trace](https://gist.github.com/liamawhite/bec78ee5cab9fa0c04e043e9adf4f48f)

## Code
https://gist.github.com/liamawhite/66c7cac3d3b82ada42c453b51113b400

**Comment by EvanBoyle** [comment]
@liamawhite the behavior you're seeing may be related to not calling `registerOutputs` and `initialize`: https://github.com/pulumi/pulumi/issues/2653

Does this still happen if you implement the component resource's `initialize` method and call `registerOutputs` (with the cluster) from within that method? https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/resource.ts#L858-L860

An example of this pattern can be found here: https://github.com/pulumi/pulumi-awsx/blob/333b1ff0d649e3f19187c2e8edc292dd6c131fbd/nodejs/awsx/ec2/vpc.ts#L282-L298

**Comment by liamawhite** [comment]
Will give this a go when I have some time 🙂.
