### ISSUE TITLE
Panic passing empty string to pulumi.asset.FileArchive for Lambda code property

### ISSUE THREAD

**Issue by rofr** [pulumi/pulumi#6254]
When running pulumi preview with an empty string passed to the FileArchive() constructor, the program crashes and dumps a stack trace to the terminal. The offending code:

```typescript
const dotNetApplicationPublishFolder = "";
const myFunction = new aws.lambda.Function("myFunction", {
    role : role.arn,
    handler : "MyApi::MyApi.LambdaEntryPoint::FunctionHandlerAsync",
    runtime : aws.lambda.DotnetCore3d1Runtime,
    code: new pulumi.asset.AssetArchive({
        ".": new pulumi.asset.FileArchive(dotNetApplicationPublishFolder),
    })
});
```
A related issue: #1953

## Expected Behavior
Display an error such as "Invalid path" as opposed to crashing hard.

## Current Behavior
```
panic: fatal: An assertion has failed: cannot read an archive that has no contents

goroutine 867 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0x0, 0x591393f, 0x2b, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/util/contract/assert.go:33 +0x1a5
github.com/pulumi/pulumi/sdk/v2/go/common/resource.(*Archive).Open(0xc001723590, 0x203000, 0x4011fd0, 0xc00173fa80, 0xc000d19d48)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/resource/asset.go:678 +0x65
github.com/pulumi/pulumi/sdk/v2/go/common/resource.(*Archive).archiveTar(0xc001723590, 0x10a89998, 0xc001712a00, 0x0, 0x0)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/resource/asset.go:994 +0x66
github.com/pulumi/pulumi/sdk/v2/go/common/resource.(*Archive).Archive(0xc001723590, 0x1, 0x10a89998, 0xc001712a00, 0xc001712a00, 0x0)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/resource/asset.go:949 +0x251
github.com/pulumi/pulumi/sdk/v2/go/common/resource.(*Archive).EnsureHash(0xc001723590, 0x0, 0x0)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/resource/asset.go:1113 +0x173
github.com/pulumi/pulumi/sdk/v2/go/common/resource/plugin.UnmarshalPropertyValue(0xc0018902c0, 0xc000499540, 0x50, 0x100010100000100, 0x0, 0xc00173f9a0, 0x0, 0x1)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/resource/plugin/rpc.go:352 +0x8b0
github.com/pulumi/pulumi/sdk/v2/go/common/resource/plugin.UnmarshalProperties(0xc00188e6f0, 0xc000499540, 0x50, 0x100010100000100, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/resource/plugin/rpc.go:243 +0x267
github.com/pulumi/pulumi/sdk/v2/go/common/resource/plugin.UnmarshalPropertyValue(0xc001890280, 0xc000499540, 0x50, 0x100010100000100, 0x0, 0xc00173f970, 0x0, 0x0)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/resource/plugin/rpc.go:307 +0x44f
github.com/pulumi/pulumi/sdk/v2/go/common/resource/plugin.UnmarshalProperties(0xc00188e690, 0xc000499540, 0x50, 0x100010100000100, 0x0, 0x58ca030, 0x5555555555555555, 0x38)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/resource/plugin/rpc.go:243 +0x267
github.com/pulumi/pulumi/sdk/v2/go/common/resource/plugin.UnmarshalPropertyValue(0xc001890200, 0xc000499540, 0x50, 0x100010100000100, 0x0, 0xc001736200, 0x4, 0x8)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/resource/plugin/rpc.go:307 +0x44f
github.com/pulumi/pulumi/sdk/v2/go/common/resource/plugin.UnmarshalProperties(0xc00188e630, 0xc000499540, 0x50, 0x100010100000100, 0x0, 0xc001758260, 0x1, 0x2)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/resource/plugin/rpc.go:243 +0x267
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*resmon).RegisterResource(0xc000d233b0, 0x5c17ae0, 0xc00188e8a0, 0xc001888c60, 0xc000d233b0, 0x5631601, 0xc0018906c0)
	/private/tmp/pulumi-20210204-32106-fnbw58/pkg/resource/deploy/source_eval.go:805 +0x4d4
github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceMonitor_RegisterResource_Handler.func1(0x5c17ae0, 0xc00188e8a0, 0x588b660, 0xc001888c60, 0x582f080, 0x6844e40, 0x5c17ae0, 0xc00188e8a0)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/proto/go/resource.pb.go:1070 +0x89
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x5c17ae0, 0xc00188e600, 0x588b660, 0xc001888c60, 0xc00188c680, 0xc00188c6a0, 0x0, 0x0, 0x5be1720, 0xc00007ed80)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f6
github.com/pulumi/pulumi/sdk/v2/go/common/util/rpcutil.OpenTracingServerInterceptor.func1(0x5c17ae0, 0xc00188e600, 0x588b660, 0xc001888c60, 0xc00188c680, 0xc00188c6a0, 0xc000b9bba0, 0x4123be6, 0x57b15a0, 0xc00188e600)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/go/common/util/rpcutil/interceptor.go:81 +0x144
github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceMonitor_RegisterResource_Handler(0x578da40, 0xc000d233b0, 0x5c17ae0, 0xc00188e600, 0xc00107d860, 0xc000d08840, 0x5c17ae0, 0xc00188e600, 0xc0000e7400, 0x38f)
	/private/tmp/pulumi-20210204-32106-fnbw58/sdk/proto/go/resource.pb.go:1072 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000d5e340, 0x5c2bb00, 0xc00026b980, 0xc0013bfa00, 0xc000d0b2c0, 0x67fa1c8, 0x0, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000d5e340, 0x5c2bb00, 0xc00026b980, 0xc0013bfa00, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xcc5
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0005d0220, 0xc000d5e340, 0x5c2bb00, 0xc00026b980, 0xc0013bfa00)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5
```

## Steps to Reproduce
1. Start a new aws/typescript project
2. Paste the offending code into index.js
3. Run `pulumi preview`

## Context (Environment)
running v2.20.0 on MacOS Big Sur

**Comment by Zaid-Ajaj** [comment]
Hi @rofr using latest Pulumi CLI v3.86.0 I can no longer reproduce a panic, instead we get a proper error coming from AWS `InvalidParameterValueException: Uploaded file must be a non-empty zip`. Here is the full error:

```
  aws:lambda:Function (myFunction):
    error: 1 error occurred:
        * creating Lambda Function (myFunction-94f1602): operation error Lambda: CreateFunction, https response error StatusCode: 400, RequestID: 1e361573-a557-457a-9d24-91850560bbc7, InvalidParameterValueException: Uploaded file must be a non-empty zip
```

I used the following program to reproduce the issue:
```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const dotNetApplicationPublishFolder = "";

const lambdaRole = new aws.iam.Role("lambdaRole", {
    assumeRolePolicy: JSON.stringify({
        "Version": "2012-10-17",
        "Statement": [{
            "Action": "sts:AssumeRole",
            "Principal": {
                "Service": "lambda.amazonaws.com",
            },
            "Effect": "Allow",
            "Sid": "",
        }],
    })
})

const policyAttachment = new aws.iam.RolePolicyAttachment("lambdaRoleAttachment", {
    role: lambdaRole,
    policyArn: aws.iam.ManagedPolicies.AWSLambdaBasicExecutionRole,
});

const myFunction = new aws.lambda.Function("myFunction", {
    role: lambdaRole.arn,
    handler : "MyApi::MyApi.LambdaEntryPoint::FunctionHandlerAsync",
    runtime : "dotnet6",
    code: new pulumi.asset.AssetArchive({
        ".": new pulumi.asset.FileArchive(dotNetApplicationPublishFolder),
    })
});

export const name = myFunction.name;
```
I will go ahead and close the issue as _fixed_. Please consider reopening if you are still seeing such hard crashes.
