### ISSUE TITLE
Pulumi not registering changes to workflow source code

### ISSUE THREAD

**Issue by austinrivas** [pulumi/pulumi#6285]
It seems like pulumi is not registering changes to workflows since last night.

## Expected Behavior

I am making arbitrary changes (adding logging statements for example) and not seeing them reflected when running pulumi commands (up, destroy, refresh).

using Typescript / node as my execution environment

## Current Behavior

add a change, for example `console.log("hello pulumi")`  expect to see that change reflected on my next run.

It is not.

## Context (Environment)

Currently blocking releases to production

Perhaps this is related to the recent GH outtage?

**Comment by austinrivas** [comment]
after a little more investigation this seems to only affect destroy

**Comment by austinrivas** [comment]
created a new stack with the same config and everything seems to be working.

my hunch tells me that it has something to do with ts serialization

**Comment by austinrivas** [comment]
actually nevermind, it seems to be happening on that stack too.

The resulting symptom is that a Dynamic Resource Provider is error'ing when attempting to destroy a resource and none of the fixes I am applying are getting through.

**Comment by leezen** [comment]
This is by design as we don't read/run the program during destroy. You'll need to update first to update the dynamic provider, then run destroy.

**Comment by austinrivas** [comment]
thanks for the response @leezen 

I tried doing pulumi up several times and still saw the same problem, however I will try again and report back if it is not resolved.

**Comment by austinrivas** [comment]
@leezen this still seems to be an ongoing issue for me, I have updated successfully several times now, but when attempting to refresh or destroy I am seeing outdated logs coming from my dynamic provider.

I have been attempting to debug this on my end, but it truly seems like pulumi is not updating.

For reference here is the provider i am having problems with

```typescript
export const NetlifySiteProvider: ResourceProvider = {
  async check(
    olds: NetlifySiteInputs,
    news: NetlifySiteInputs
  ): Promise<CheckResult> {
    try {
      const failures: CheckFailure[] = [];
      if (failures.length > 0) {
        return { failures };
      }
      return { inputs: news };
    } catch (error) {
      console.error(`${provider}:check:error`, error);
      throw error;
    }
  },

  async create(props: ProviderInputs): Promise<CreateResult> {
    try {
      const client: NetlifyAPI = new Netlify(props.accessToken);
      // eslint-disable-next-line @typescript-eslint/naming-convention
      const { name, custom_domain, secondsToWaitAfter } = props;

      const body: CreateSiteRequest = {
        name,
        custom_domain,
        ssl: true,
      };

      const { id, ...outs } = await client.createSite({ body });

      if (typeof secondsToWaitAfter === "number" && secondsToWaitAfter > 0) {
        await sleep(secondsToWaitAfter);
      }

      return { id, outs };
    } catch (error) {
      console.error(`${provider}:create:error`, error?.json?.errors);
      throw error;
    }
  },

  async diff(
    id: string,
    olds: ProviderInputs,
    news: ProviderInputs
  ): Promise<DiffResult> {
    const replaces: string[] = [];
    let changes = false;

    if (!shallowCompare(olds, news)) {
      changes = true;
      // replaces.push(...Object.keys(news).filter(filterValidKeys));
    }

    return { changes, replaces };
  },

  async update(
    id: string,
    olds: ProviderInputs,
    news: ProviderInputs
  ): Promise<UpdateResult> {
    try {
      // eslint-disable-next-line @typescript-eslint/naming-convention
      const { name, custom_domain, secondsToWaitAfter, accessToken } = news;
      const client: NetlifyAPI = new Netlify(accessToken);

      const body: UpdateSiteRequest = {
        name,
        custom_domain,
      };

      const { id: sameId, ...outs } = await client.updateSite({
        site_id: id,
        body,
      });

      if (typeof secondsToWaitAfter === "number" && secondsToWaitAfter > 0) {
        await sleep(secondsToWaitAfter);
      }

      return { outs };
    } catch (error) {
      console.error(`${provider}:update:error`, error?.json?.errors);
      throw error;
    }
  },

  async delete(id: string, props: ProviderInputs) {
    try {
      const { accessToken } = props;
      const client: NetlifyAPI = new Netlify(accessToken);
      await client.deleteSite({
        site_id: id,
      });
    } catch (error) {
      console.error(`${provider}:delete:error`, error.message);
      throw error;
    }
  },

  async read(id: string, props: ProviderInputs): Promise<ReadResult> {
    try {
      const { accessToken } = props;
      console.log("props", props);
      const client: NetlifyAPI = new Netlify(accessToken);
      const response = await client.getSite({ site_id: id });
      return { id: response.id, props: { ...props, ...response } };
    } catch (error) {
      console.error(`${provider}:read:error`, error);
      throw error;
    }
  },
};
```

For whatever reason I am seeing

```
    netlify-site-provider:read:error TextHTTPError: Unauthorized
        at parseResponse (/home/austin/Workspace/Sophia/platform/node_modules/netlify/src/methods/response.js:13:11)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at callMethod (/home/austin/Workspace/Sophia/platform/node_modules/netlify/src/methods/index.js:33:26) {
      status: 401,
      data: ''
    }
```

In the logs only on read / delete / update operations and not create operations.

Attempts to further debug fail due to being unable to log additional information about the context even after successfully running pulumi up again.

**Comment by austinrivas** [comment]
Ok, got it worked out.

As with most things, it was mostly user error. My provider outs were not persisting the access token, which was the root of my authentication errors. This was honestly expected.

What made this difficult though was that there is definitely a bug in the js serializer for the provider. I was able to solve the issue by triggering re-serialization for the provider by making changes to code outside of the Provider object itself. Namely the array of filterable keys.

Once I did that pulumi was able to register a diff in the provider and my debug code started providing relevant info that helped me identify how utterly wrong my provider implementation was.

Overall it was a good learning experience, however I would take a look at the serializer as there seems to be some issues there.

I'll provide the working code below in case you would like to reproduce this.

**Comment by austinrivas** [comment]
```typescript
import * as pulumi from "@pulumi/pulumi";
import {
  CheckFailure,
  CheckResult,
  CreateResult,
  DiffResult,
  ReadResult,
  ResourceProvider,
} from "@pulumi/pulumi/dynamic";
import { UpdateResult } from "@pulumi/pulumi/provider";

import NetlifyAPI, { CreateSiteRequest, UpdateSiteRequest } from "../types";

// eslint-disable-next-line @typescript-eslint/no-var-requires
const Netlify = require("netlify"); // netlify api is not typed...

export type NetlifySiteInputs = {
  accessToken: string | pulumi.Input<string>;
  name: string;
  custom_domain: string;
};

export type ProviderInputs = {
  accessToken: string;
  name: string;
  custom_domain: string;
};

// eslint-disable-next-line unicorn/prefer-set-has
const validKeys = ["name", "custom_domain", "accessToken"]; <------ ADDING AND ELEMENT TO THIS ARRAY TRIGGERED THE SERIALIZER DIFF
function filterValidKeys(key: string): key is keyof ProviderInputs {
  return validKeys.includes(key);
}

function shallowCompare(obj1: ProviderInputs, obj2: ProviderInputs) {
  const obj1Keys: Array<keyof ProviderInputs> = Object.keys(obj1).filter(
    filterValidKeys
  );
  const obj2Keys: Array<keyof ProviderInputs> = Object.keys(obj2).filter(
    filterValidKeys
  );
  return (
    obj1Keys.length === obj2Keys.length &&
    obj1Keys.every(function compare(key: keyof ProviderInputs) {
      return obj1[key] === obj2[key];
    })
  );
}

const provider = "netlify-site-provider";
export const NetlifySiteProvider: ResourceProvider = {
  async check(
    olds: NetlifySiteInputs,
    news: NetlifySiteInputs
  ): Promise<CheckResult> {
    try {
      const failures: CheckFailure[] = [];
      if (failures.length > 0) {
        return { failures };
      }
      return { inputs: news };
    } catch (error) {
      console.error(`${provider}:check:error`, error);
      throw error;
    }
  },

  async create(props: ProviderInputs): Promise<CreateResult> {
    try {
      // eslint-disable-next-line @typescript-eslint/naming-convention
      const { name, custom_domain, accessToken } = props;
      const client: NetlifyAPI = new Netlify(accessToken);

      const body: CreateSiteRequest = {
        name,
        custom_domain,
        ssl: true,
      };

      const { id, ...outs } = await client.createSite({ body });

      return {
        id,
        outs: {
          ...props,
          ...outs,
        },
      };
    } catch (error) {
      console.error(`${provider}:create:error`, error?.json?.errors);
      throw error;
    }
  },

  async diff(
    id: string,
    olds: ProviderInputs,
    news: ProviderInputs
  ): Promise<DiffResult> {
    const replaces: string[] = [];
    let changes = false;
    if (!shallowCompare(olds, news)) {
      changes = true;
      // replaces.push(...Object.keys(news).filter(filterValidKeys));
    }

    return { changes, replaces };
  },

  async update(
    id: string,
    olds: ProviderInputs,
    news: ProviderInputs
  ): Promise<UpdateResult> {
    try {
      // eslint-disable-next-line @typescript-eslint/naming-convention
      const { name, custom_domain, accessToken } = news;
      const client: NetlifyAPI = new Netlify(accessToken);

      const body: UpdateSiteRequest = {
        name,
        custom_domain,
      };

      const { id: sameId, ...outs } = await client.updateSite({
        site_id: id,
        body,
      });

      return {
        outs: {
          ...olds,
          ...news,
          ...outs,
        },
      };
    } catch (error) {
      console.error(`${provider}:update:error`, error?.json?.errors);
      throw error;
    }
  },

  async delete(id: string, props: ProviderInputs) {
    try {
      const { accessToken } = props;
      const client: NetlifyAPI = new Netlify(accessToken);
      await client.deleteSite({
        site_id: id,
      });
    } catch (error) {
      console.error(`${provider}:delete:error`, error.message);
      throw error;
    }
  },

  async read(id: string, props: ProviderInputs): Promise<ReadResult> {
    try {
      const { accessToken } = props;
      const client: NetlifyAPI = new Netlify(accessToken);
      const response = await client.getSite({ site_id: id });
      return { id: response.id, props: { ...props, ...response } };
    } catch (error) {
      console.error(`${provider}:read:error`, error);
      throw error;
    }
  },
};
```
