### ISSUE TITLE
cannot complete a resource 'XXXX' whose registration isn't pending

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi#6423]
Register outputs results in a failed assertion

## Expected behavior
It should complete successfully

## Current behavior
> panic: fatal: An assertion has failed: cannot complete a resource 'XXXX' whose registration isn't pending

<details>
<title>Stack Trace</title>

> panic: fatal: An assertion has failed: cannot complete a resource 'urn:pulumi:dev::register-output-issue::pulumi:pulumi:Stack::register-output-issue-dev' whose registration isn't pending
> 
> goroutine 72 [running]:
> github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
> github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0xc000b9ca00, 0x1f5c58e, 0x40, 0xc0006ed928, 0x1, 0x1)
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:33 +0x1ad
> github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).ExecuteRegisterResourceOutputs(0xc0014e0d00, 0x17b71e1f8b0, 0xc000a554a0)
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:154 +0x165
> github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).handleSingleEvent(0xc000091ba0, 0x2216bc0, 0xc000a554a0, 0x0, 0x1)
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:378 +0x32d
> github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).Execute.func3(0xc00140d020, 0xc000091ba0, 0xc0005cbc10, 0x224a920, 0xc000527d40, 0x0, 0x0, 0x224a9e0, 0xc000949f20, 0x0, ...)
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:242 +0x229
> github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*deploymentExecutor).Execute(0xc000091ba0, 0x224a9e0, 0xc000949f20, 0x17b720d8aa8, 0xc00062dcc0, 0x7fffffff, 0x0, 0x2e8cde0, 0x0, 0x0, ...)
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:258 +0x7de
> github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*Deployment).Execute(...)
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/resource/deploy/deployment.go:405
> github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run.func1(0x2255960, 0xc00062dcc0, 0xc000970640, 0x224a9e0, 0xc000949f20, 0xc000949f01, 0xc000594870, 0xc00003e8a0)
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/engine/deployment.go:252 +0x2a7
> created by github.com/pulumi/pulumi/pkg/v2/engine.(*deployment).run
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/engine/deployment.go:237 +0x314
 
</details>

## Steps to reproduce

Deploy this stack

```csharp
using Pulumi;
using System.Collections.Generic;
using System.Threading.Tasks;

class MyStack : Stack
{
    public MyStack()
    {
        Output<bool> packageCreated = Output.Create(true).Apply(async n => await SomethingAsync());
        Output<IDictionary<string, object?>> outputs = packageCreated.Apply(p =>
        {
            return (IDictionary<string, object?>)new Dictionary<string, object?>
            {
                { "package", p },
            };
        });
        RegisterOutputs(outputs);  // Commenting this out removes the error
    }

    private async Task<bool> SomethingAsync()
    {
        return true;
    }
}
```

## Context (Environment)
Pulumi v2.20.0
I'm trying to run an async function and need to make sure it completes before the stack exits.

## Workaround

Output some value.

```csharp
[Output] public Output<bool> Junk { get; set; }
```

**Comment by viveklak** [comment]
My understanding is that RegisterOutputs is only relevant for component resources but a panic is nonetheless an unfriendly response to this. Does this fit in the context of https://github.com/pulumi/pulumi/issues/5941 @leezen?

**Comment by leezen** [comment]
@viveklak I don't think exactly. #5941 is meant to track how the behavior of calling `registerOutputs` varies from language runtime to language runtime. This feels like a separate issue of just making it clear that `registerOutputs` isn't really meant for use at the stack level.

**Comment by MisinformedDNA** [comment]
Is my workaround the correct way to go?

**Comment by viveklak** [comment]
> Is my workaround the correct way to go?

Yes that looks right.
