### ISSUE TITLE
Bug when trying to import github resource

### ISSUE THREAD

**Issue by RoiSightfull** [pulumi/pulumi#6434]
When importing github resoure encountered this trace:

```shell
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v2.21.2
Go Version:       go1.16
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: An assertion has failed: Module member token 'github:index/ActionsOrganizationSecret' missing module member delimiter

goroutine 1 [running]:
runtime/debug.Stack(0xc001c8d248, 0x55250e0, 0xc0006179e0)
        /usr/local/Cellar/go/1.16/libexec/src/runtime/debug/stack.go:24 +0x9f
main.panicHandler()
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/cmd/pulumi/main.go:29 +0x76
panic(0x55250e0, 0xc0006179e0)
        /usr/local/Cellar/go/1.16/libexec/src/runtime/panic.go:965 +0x1b9
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0x7ffeefbff800, 0x58cbf69, 0x38, 0xc001c8d498, 0x1, 0x1)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/sdk/go/common/util/contract/assert.go:33 +0x1a5
github.com/pulumi/pulumi/sdk/v2/go/common/tokens.ModuleMember.Module(0x7ffeefbff816, 0x26, 0xc000db5350, 0x0)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/sdk/go/common/tokens/tokens.go:192 +0xd2
github.com/pulumi/pulumi/sdk/v2/go/common/tokens.ModuleMember.Package(0x7ffeefbff816, 0x26, 0x5b67620, 0x1)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/sdk/go/common/tokens/tokens.go:187 +0x35
github.com/pulumi/pulumi/sdk/v2/go/common/tokens.Type.Package(0x7ffeefbff816, 0x26, 0x2c, 0x586db9c)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/sdk/go/common/tokens/tokens.go:227 +0x70
github.com/pulumi/pulumi/pkg/v2/engine.newDeployment(0xc000a20380, 0xc0006b80a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/engine/deployment.go:177 +0x470
github.com/pulumi/pulumi/pkg/v2/engine.update(0xc000a20380, 0xc0006b80a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/engine/update.go:439 +0x4e7
github.com/pulumi/pulumi/pkg/v2/engine.Import(0x5bc24f8, 0xc0008c6120, 0xc000a20380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, ...)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/engine/import.go:43 +0x56e
github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudBackend).runEngineAction(0xc000a376e0, 0x5bcef28, 0xc000130008, 0x5882dff, 0xf, 0x5bb9cf0, 0xc000e267c0, 0xc0009fea00, 0xc000907280, 0x2c, ...)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/backend/httpstate/backend.go:1043 +0xce5
github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudBackend).apply(0xc000a376e0, 0x5bcef28, 0xc000130008, 0x5882dff, 0xf, 0x5beab70, 0xc000e00500, 0xc0009fea00, 0xc000907280, 0x2c, ...)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/backend/httpstate/backend.go:949 +0x2ba
github.com/pulumi/pulumi/pkg/v2/backend.PreviewThenPrompt(0x5bcef28, 0xc000130008, 0x5882dff, 0xf, 0x5beab70, 0xc000e00500, 0xc0009fea00, 0xc000907280, 0x2c, 0xc0005ed860, ...)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/backend/apply.go:115 +0x133
github.com/pulumi/pulumi/pkg/v2/backend.PreviewThenPromptThenExecute(0x5bcef28, 0xc000130008, 0x5882dff, 0xf, 0x5beab70, 0xc000e00500, 0xc0009fea00, 0xc000907280, 0x2c, 0xc0005ed860, ...)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/backend/apply.go:200 +0x1a8
github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudBackend).Import(0xc000a376e0, 0x5bcef28, 0xc000130008, 0x5beab70, 0xc000e00500, 0xc0009fea00, 0xc000907280, 0x2c, 0xc0005ed860, 0x1, ...)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/backend/httpstate/backend.go:842 +0x109
github.com/pulumi/pulumi/pkg/v2/backend.ImportStack(0x5bcef28, 0xc000130008, 0x5beab70, 0xc000e00500, 0xc0009fea00, 0xc000907280, 0x2c, 0x0, 0x0, 0x0, ...)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/backend/stack.go:91 +0xe5
github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudStack).Import(0xc000e00500, 0x5bcef28, 0xc000130008, 0xc0009fea00, 0xc000907280, 0x2c, 0x0, 0x0, 0x0, 0xc000e1ced0, ...)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/backend/httpstate/stack.go:153 +0xc8
main.newImportCmd.func1(0xc000a39b80, 0xc000a36d50, 0x3, 0x3, 0x0, 0x0)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/cmd/pulumi/import.go:461 +0xcc5
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc000a39b80, 0xc000a36d50, 0x3, 0x3)
        /private/tmp/pulumi-20210224-15895-1jgsfq7/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000a39b80, 0xc000a36d20, 0x3, 0x3, 0xc000a39b80, 0xc000a36d20)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000882000, 0xc000068740, 0x4070d88, 0xc000000180)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /private/tmp/pulumi-20210224-15895-1jgsfq7/pkg/cmd/pulumi/main.go:48 +0x4d
```

## Steps to reproduce
pulumi import github:index/ActionsOrganizationSecret keyID org/keyId

**Comment by leezen** [comment]
Sorry you're running into this. Could you please retry with `github:index/actionsSecret:ActionsSecret` -- that is the correct type token for this resource.

**Comment by RoiSightfull** [comment]
appears to be working thanks, I guess maybe a better exception handling would suffice :)

**Comment by leezen** [comment]
Thanks for confirming. Agree the error messaging could be better here!
