### ISSUE TITLE
Unit test with Mock fails

### ISSUE THREAD

**Issue by robin-wittler** [pulumi/pulumi#6465]
I followed the Unittest example - but with a GCP Bucket - and it always Fails with a Runtime Error. The message is: RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_2'.

## Current behavior
python -m unittest fails with an exception

```
python -m unittest

E
======================================================================
ERROR: test_storage_bucket (test_main.TestingWithMocks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/mocks.py", line 37, in wrapper
    _sync_await(run_pulumi_func(lambda: _sync_await(Output.from_input(fn(*args, **kwargs)).future())))
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/sync_await.py", line 62, in _sync_await
    return loop.run_until_complete(fut)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
    await RPC_MANAGER.rpcs.pop()
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/output.py", line 157, in run
    value = await self._future
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/output.py", line 382, in gather_futures
    return await asyncio.gather(*value_futures_list)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/output.py", line 116, in get_value
    val = await self._future
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/output.py", line 157, in run
    value = await self._future
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/output.py", line 155, in run
    is_known = await self._is_known
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
    result = await rpc
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
    return await is_known and not contains_unknowns(await future)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
    return await is_known and not contains_unknowns(await future)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
    return await is_known and not contains_unknowns(await future)
  [Previous line repeated 16 more times]
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 441, in do_register
    resp = await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 437, in do_rpc_call
    return monitor.RegisterResource(req)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/mocks.py", line 130, in RegisterResource
    inputs = rpc.deserialize_properties(request.object)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 288, in deserialize_properties
    value = deserialize_property(v, keep_unknowns)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 380, in deserialize_property
    props = deserialize_properties(value, keep_unknowns)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 272, in deserialize_properties
    return deserialize_resource(props_struct, keep_unknowns)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 318, in deserialize_resource
    return cast('Resource', resource_module.construct(urn_name, typ, urn))
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi_gcp/storage/__init__.py", line 41, in construct
    return Bucket(name, pulumi.ResourceOptions(urn=urn))
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi_gcp/storage/bucket.py", line 182, in __init__
    opts)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/resource.py", line 837, in __init__
    Resource.__init__(self, t, name, True, props, opts, False, dependency)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/resource.py", line 734, in __init__
    get_resource(self, props, custom, opts.urn)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 170, in get_resource
    (resolve_urn, res.__dict__["urn"]) = resource_output(res)
  File "/home/testuser/pulumi-test/venv/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 144, in resource_output
    value_future: asyncio.Future[Any] = asyncio.Future()
  File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_2'.

----------------------------------------------------------------------
Ran 1 test in 0.017s

FAILED (errors=1)
```

## Steps to reproduce
I've a folder structure like this:
```
pulumi-test
├── demo_bucket.py
├── __main__.py
├── Pulumi.dev.yaml
├── Pulumi.yaml
├── requirements.txt
├── site
│   └── index.html
├── test_main.py
```

### content of demo_bucket.py
```
"""A Google Cloud Python Pulumi program"""

import pulumi
from pulumi_gcp import storage


config = pulumi.Config()

bucket_name = config.get('bucket_name') or 'my-bucket'

bucket = storage.Bucket(
    bucket_name,
    website=storage.BucketWebsiteArgs(
        main_page_suffix='index.html',
    ),
    uniform_bucket_level_access=True,
)

bucketIAMBinding = storage.BucketIAMBinding(
    'my-bucket-IAMBinding',
    bucket=bucket,
    role='roles/storage.objectViewer',
    members=['allUsers']
)

bucketObject = storage.BucketObject(
    'index.html',
    bucket=bucket,
    content_type='text/html',
    content_encoding='utf8',
    content=open('site/index.html').read(),
)

pulumi.export(
    'bucket_endpoint',
    pulumi.Output.concat(
        'http://storage.googleapis.com/',
        bucket.id,
        "/",
        bucketObject.name
    )
)
```

### content of test_main.py

```
import pulumi
import unittest

class MockedResources(pulumi.runtime.Mocks):
    def new_resource(self, type_, name, inputs, provider, id_):
        return [name + '_id', inputs]
    def call(self, token, args, provider):
        return {}

pulumi.runtime.set_mocks(MockedResources())

import demo_bucket

class TestingWithMocks(unittest.TestCase):
    @pulumi.runtime.test
    def test_storage_bucket(self):
        def check_website(args):
            valid_dict = {'mainPageSuffix': 'index.html'}
            urn, website = args
            self.assertDictEqual(
                website,
                valid_dict,
                msg='The resulting website dict is not equal with the validation dict'
            )

        return pulumi.Output.all(
            demo_bucket.bucket.urn, 
            demo_bucket.bucket.website
        ).apply(check_website)

```

**Comment by justinvp** [comment]
This is happening when deserializing a resource reference. Still working on a fix, but in the meantime, a workaround is to pass `bucket.id` rather than `bucket` in `demo_bucket.py`:

```diff
"""A Google Cloud Python Pulumi program"""

import pulumi
from pulumi_gcp import storage


config = pulumi.Config()

bucket_name = config.get('bucket_name') or 'my-bucket'

bucket = storage.Bucket(
    bucket_name,
    website=storage.BucketWebsiteArgs(
        main_page_suffix='index.html',
    ),
    uniform_bucket_level_access=True,
)

bucketIAMBinding = storage.BucketIAMBinding(
    'my-bucket-IAMBinding',
-   bucket=bucket,
+   bucket=bucket.id,
    role='roles/storage.objectViewer',
    members=['allUsers']
)

bucketObject = storage.BucketObject(
    'index.html',
-   bucket=bucket,
+   bucket=bucket.id,
    content_type='text/html',
    content_encoding='utf8',
    content=open('site/index.html').read(),
)

pulumi.export(
    'bucket_endpoint',
    pulumi.Output.concat(
        'http://storage.googleapis.com/',
        bucket.id,
        "/",
        bucketObject.name
    )
)
```

**Comment by robin-wittler** [comment]
@justinvp Thx for the Tip with "bucket.id" The mocking unittests are now working. Funny that it is simply working when calling "pulumi up" ... I've expected that this would run almost the same codepath as the mocked unittests. :)

Thx for your immediate help - I will continue now my journey with pulumi! :)
