### ISSUE TITLE
[cli] Investigate Standard Error hygiene

### ISSUE THREAD

**Issue by vipentti** [pulumi/pulumi#6515]
Currently Pulumi CLI seems to write everything into Standard Output, including errors.

## Expected behavior

Standard error should be utilized.

## Current behavior

Everything is written into standard output.

## Steps to reproduce

1. Run `pulumi new typescript`
2. Add the following to the `index.ts`

```typescript
import * as pulumi from "@pulumi/pulumi";

pulumi.log.info("info");
pulumi.log.warn("warn");
console.info("console.info");
console.error("console.error");
console.warn("console.warn");
```

3. Run `pulumi preview --non-interactive > stdout` to redirect Standard Output to a file
4. Everything is written into the file, including `console.error` and `console.warn`, which when used normally would write to the standard error

**Comment by vipentti** [comment]
Continued investigating the current behaviour, this time using C#.

I have the following Pulumi program using C# with .NET 5

```csharp
using Pulumi;

return await Deployment.RunAsync<MyStack>();

class MyStack : Stack
{
    public MyStack()
    {
        throw new System.Exception("TestFail"); // <- removing this semicolon
    }
}
```

Running the following command:

```bash
> pulumi preview --non-interactive > stdout
```

Everything ends up being written into the stdout file, including errors due to the exception being thrown.

<details>
<summary><strong>Contents of stdout file</strong></summary>

```text
> cat stdout
Previewing update (StackName)

View Live: https://app.pulumi.com/Org/ProjectName/StackName/previews/<id>

    pulumi:pulumi:Stack ProjectName-StackName  running 'dotnet build -nologo .'
    pulumi:pulumi:Stack ProjectName-StackName    Determining projects to restore...
    pulumi:pulumi:Stack ProjectName-StackName    All projects are up-to-date for restore.
    pulumi:pulumi:Stack ProjectName-StackName    ProjectName -> <path>\bin\Debug\net5.0\ProjectName.dll
    pulumi:pulumi:Stack ProjectName-StackName
    pulumi:pulumi:Stack ProjectName-StackName  Build succeeded.
    pulumi:pulumi:Stack ProjectName-StackName  'dotnet build -nologo .' completed successfully

 +  pulumi:pulumi:Stack ProjectName-StackName create 'dotnet build -nologo .' completed successfully
 +  pulumi:pulumi:Stack ProjectName-StackName create error: Running program '<path>\bin\Debug\net5.0\ProjectName.dll' failed with an unhandled exception:
 +  pulumi:pulumi:Stack ProjectName-StackName create 1 error

Diagnostics:
  pulumi:pulumi:Stack (ProjectName-StackName):
    error: Running program '<path>\bin\Debug\net5.0\ProjectName.dll' failed with an unhandled exception:
    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
     ---> System.Exception: TestFail
       at MyStack..ctor() in <path>\Program.cs:line 9
       --- End of inner exception stack trace ---
       at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
       at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
       at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
       at System.Activator.CreateInstance[T]()
       at Pulumi.Deployment.Runner.<>c__4`1.<RunAsync>b__4_0()
       at Pulumi.Deployment.Runner.RunAsync[TStack](Func`1 stackFactory)
```

</details>

If I introduce a syntax error, for example by removing a semicolon and then run the same command

```bash
> pulumi preview --non-interactive > stdout
error: failed to discover plugin requirements: 'dotnet build -nologo .' exited with non-zero exit code: 1
```

**NOTE:** We get some output via standard error regarding the plugin requirements, but none of the actual errors.
Rest of the details is still in the stdout file.

<details>
<summary><strong>Contents of stdout file with syntax errors</strong></summary>

```text
> cat stdout
Previewing update (StackName)

View Live: https://app.pulumi.com/Org/ProjectName/StackName/previews/<id>

    pulumi:pulumi:Stack ProjectName-StackName  running 'dotnet build -nologo .'
    pulumi:pulumi:Stack ProjectName-StackName    Determining projects to restore...
    pulumi:pulumi:Stack ProjectName-StackName    All projects are up-to-date for restore.
    pulumi:pulumi:Stack ProjectName-StackName  <Path>\ProjectName\Program.cs(9,47): error CS1002: ; expected [<Path>\ProjectName\ProjectName.csproj]
    pulumi:pulumi:Stack ProjectName-StackName
    pulumi:pulumi:Stack ProjectName-StackName  Build FAILED.
    pulumi:pulumi:Stack ProjectName-StackName    Determining projects to restore...
    pulumi:pulumi:Stack ProjectName-StackName    All projects are up-to-date for restore.
    pulumi:pulumi:Stack ProjectName-StackName  <Path>\ProjectName\Program.cs(9,47): error CS1002: ; expected [<Path>\ProjectName\ProjectName.csproj]
    pulumi:pulumi:Stack ProjectName-StackName  Build FAILED.
    pulumi:pulumi:Stack ProjectName-StackName  <Path>\ProjectName\Program.cs(9,47): error CS1002: ; expected [<Path>\ProjectName\ProjectName.csproj]
    pulumi:pulumi:Stack ProjectName-StackName      0 Warning(s)
    pulumi:pulumi:Stack ProjectName-StackName      1 Error(s)
    pulumi:pulumi:Stack ProjectName-StackName  Time Elapsed 00:00:01.60
    pulumi:pulumi:Stack ProjectName-StackName  8 messages

Diagnostics:
  pulumi:pulumi:Stack (ProjectName-StackName):
      Determining projects to restore...
      All projects are up-to-date for restore.
    <Path>\ProjectName\Program.cs(9,47): error CS1002: ; expected [<Path>\ProjectName\ProjectName.csproj]
    Build FAILED.
    <Path>\ProjectName\Program.cs(9,47): error CS1002: ; expected [<Path>\ProjectName\ProjectName.csproj]
        0 Warning(s)
        1 Error(s)
    Time Elapsed 00:00:01.60
```

</details>

**Comment by dixler** [comment]
A user in community slack reports that:
> This is something we've hit that has made us decide to explore alternatives to Pulumi.

[source](https://pulumi-community.slack.com/archives/C84L4E3N1/p1662570614300799)

**Comment by RobbieMcKinstry** [comment]
To give a little clarity into what I was thinking, I suppose I imagine a world in which all messages above INFO get sent to STDERR, while INFO and below are send to STDOUT. I'm not sure what the best practices are in this area. I could be way off base here.

**Comment by Frassle** [comment]
> To give a little clarity into what I was thinking, I suppose I imagine a world in which all messages above INFO get sent to STDERR, while INFO and below are send to STDOUT. I'm not sure what the best practices are in this area. I could be way off base here.

I would find that surprising. Most tools I've used _all_ logs go to stderr (or a proper log sink) while stdout is for the main output of the program.
