### ISSUE TITLE
Flakey python test errors with "Task attached to a different loop"

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#6561]
The TestingWithMocks.test_component test intermittently errors with a `Task attached to a different loop` error: https://github.com/pulumi/pulumi/runs/2098866118#step:18:1754

## Expected behavior
The test should pass every time.

## Current behavior

```
=================================== FAILURES ===================================
_______________________ TestingWithMocks.test_component ________________________

args = (<test_with_mocks.test_testing_with_mocks.TestingWithMocks testMethod=test_component>,)
kwargs = {}

    def wrapper(*args, **kwargs):
        from .. import Output  # pylint: disable=import-outside-toplevel
>       _sync_await(run_pulumi_func(lambda: _sync_await(Output.from_input(fn(*args, **kwargs)).future())))

../pulumi/runtime/mocks.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Error: ../pulumi/runtime/sync_await.py:54: in _sync_await
    return loop.run_until_complete(fut)
Error: /opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/asyncio/base_events.py:642: in run_until_complete
    return future.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

func = <function test.<locals>.wrapper.<locals>.<lambda> at 0x7f68c09c2940>

    async def run_pulumi_func(func: Callable):
        try:
            func()
        finally:
            log.debug("Waiting for outstanding RPCs to complete")
    
            # Pump the event loop, giving all of the RPCs that we just queued up time to fully execute.
            # The asyncio scheduler does not expose a "yield" primitive, so this will have to do.
            #
            # Note that "asyncio.sleep(0)" is the blessed way to do this:
            # python/asyncio/issues/284#issuecomment-154180935
            #
            # We await each RPC in turn so that this loop will actually block rather than busy-wait.
            while True:
                await asyncio.sleep(0)
                rpcs_remaining = len(RPC_MANAGER.rpcs)
                if rpcs_remaining == 0:
                    break
                log.debug(f"waiting for quiescence; {rpcs_remaining} RPCs outstanding")
>               await RPC_MANAGER.rpcs.pop()
E               RuntimeError: Task <Task pending name='Task-70' coro=<run_pulumi_func() running at /home/runner/work/pulumi/pulumi/sdk/python/lib/pulumi/runtime/stack.py:51> cb=[_run_until_complete_cb() at /opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/asyncio/base_events.py:184]> got Future <Task pending name='Task-349' coro=<get_resource.<locals>.do_get() running at /home/runner/work/pulumi/pulumi/sdk/python/lib/pulumi/runtime/resource.py:194> wait_for=<Future finished result=return {
E                 fi..."
E                   }
E                 }
E               }
E               > cb=[<TaskWakeupMethWrapper object at 0x7f68bdc7ef40>()]> attached to a different loop

Error: ../pulumi/runtime/stack.py:51: RuntimeError
```

## Steps to reproduce

This is a tricky one to reproduce. I have seen this in automation API as well, but been unable to reproduce it consistently. The thing in common between mocks and automation API is that they are both operating within threads where an event loop may not yet exist and therefore need to be created: https://github.com/pulumi/pulumi/pull/6479/files#diff-7940e0adbdbe429f8fbb220a99ee2c6dac0436a1e01abfd8a4dcb5ec6b4e8235R92-R97

**Comment by amitjattan** [comment]
Facing same issues while running pulumi automation tasks via APIs. Resources are created successfully though.

code: 255 stdout: Updating (itsd-devtest-RajanSQLTestRgD01-azrpmsqld009-SQLTesting01): + pulumi:pulumi:Stack itsd-devtest-itsd-devtest-RajanSQLTestRgD01-azrpmsqld009-SQLTesting01 creating + azure:mssql:Database SQLTesting01 creating + azure:mssql:Database SQLTesting01 created + pulumi:pulumi:Stack itsd-devtest-itsd-devtest-RajanSQLTestRgD01-azrpmsqld009-SQLTesting01 creating error: python inline source runtime error: Task <Task pending name='Task-871' coro=<run_in_stack() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py:83> cb=[_run_until_complete_cb() at /usr/local/lib/python3.9/asyncio/base_events.py:184]> got Future <Task pending name='Task-783' coro=<register_resource.<locals>.do_register() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/resource.py:358> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f4037cafaf0>(), <2 more>, <TaskWakeupMethWrapper object at 0x7f4037caf370>()]> cb=[<TaskWakeupMethWrapper object at 0x7f4037af3df0>()]> attached to a different loop + pulumi:pulumi:Stack itsd-devtest-itsd-devtest-RajanSQLTestRgD01-azrpmsqld009-SQLTesting01 creating error: an unhandled error occurred: python inline source runtime error: Task <Task pending name='Task-871' coro=<run_in_stack() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py:83> cb=[_run_until_complete_cb() at /usr/local/lib/python3.9/asyncio/base_events.py:184]> got Future <Task pending name='Task-783' coro=<register_resource.<locals>.do_register() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/resource.py:358> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f4037cafaf0>(), <2 more>, <TaskWakeupMethWrapper object at 0x7f4037caf370>()]> cb=[<TaskWakeupMethWrapper object at 0x7f4037af3df0>()]> attached to a different loop + pulumi:pulumi:Stack itsd-devtest-itsd-devtest-RajanSQLTestRgD01-azrpmsqld009-SQLTesting01 **creating failed** 2 errors Diagnostics: pulumi:pulumi:Stack (itsd-devtest-itsd-devtest-RajanSQLTestRgD01-azrpmsqld009-SQLTesting01): error: python inline source runtime error: Task <Task pending name='Task-871' coro=<run_in_stack() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py:83> cb=[_run_until_complete_cb() at /usr/local/lib/python3.9/asyncio/base_events.py:184]> got Future <Task pending name='Task-783' coro=<register_resource.<locals>.do_register() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/resource.py:358> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f4037cafaf0>(), <2 more>, <TaskWakeupMethWrapper object at 0x7f4037caf370>()]> cb=[<TaskWakeupMethWrapper object at 0x7f4037af3df0>()]> attached to a different loop Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/pulumi/x/automation/_server.py", line 64, in Run loop.run_until_complete(run_in_stack(self.program)) File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete return future.result() File "/usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack await run_pulumi_func(lambda: Stack(func)) File "/usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func await RPC_MANAGER.rpcs.pop() RuntimeError: Task <Task pending name='Task-871' coro=<run_in_stack() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py:83> cb=[_run_until_complete_cb() at /usr/local/lib/python3.9/asyncio/base_events.py:184]> got Future <Task pending name='Task-783' coro=<register_resource.<locals>.do_register() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/resource.py:358> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f4037cafaf0>(), <2 more>, <TaskWakeupMethWrapper object at 0x7f4037caf370>()]> cb=[<TaskWakeupMethWrapper object at 0x7f4037af3df0>()]> attached to a different loop error: an unhandled error occurred: python inline source runtime error: Task <Task pending name='Task-871' coro=<run_in_stack() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py:83> cb=[_run_until_complete_cb() at /usr/local/lib/python3.9/asyncio/base_events.py:184]> got Future <Task pending name='Task-783' coro=<register_resource.<locals>.do_register() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/resource.py:358> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f4037cafaf0>(), <2 more>, <TaskWakeupMethWrapper object at 0x7f4037caf370>()]> cb=[<TaskWakeupMethWrapper object at 0x7f4037af3df0>()]> attached to a different loop Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/pulumi/x/automation/_server.py", line 64, in Run loop.run_until_complete(run_in_stack(self.program)) File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete return future.result() File "/usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack await run_pulumi_func(lambda: Stack(func)) File "/usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func await RPC_MANAGER.rpcs.pop() RuntimeError: Task <Task pending name='Task-871' coro=<run_in_stack() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py:83> cb=[_run_until_complete_cb() at /usr/local/lib/python3.9/asyncio/base_events.py:184]> got Future <Task pending name='Task-783' coro=<register_resource.<locals>.do_register() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/resource.py:358> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f4037cafaf0>(), <2 more>, <TaskWakeupMethWrapper object at 0x7f4037caf370>()]> cb=[<TaskWakeupMethWrapper object at 0x7f4037af3df0>()]> attached to a different loop Resources: + 2 created Duration: 1m47s stderr:

**Comment by komalali** [comment]
@amitjattan is this something you've been able to reproduce reliably? If so, could you please share some code to reproduce the error? I've been trying to track this down and it's been tough to get a reliable repro.

**Comment by amitjattan** [comment]
So my code base is like below
`        logging.info("Pulumi logged in for Provisioning")
            stack = auto.create_or_select_stack(
                stack_name=stack_name, project_name=subscription, program=pulumi_program
            )
    logging.info("Stack Info: %s", stack.info())
        logging.info("Provisioning stack info: %s", stack.info())
        # deploy the stack, tailing the logs to stdout
        up_res = stack.up(on_output=print)
        logging.info("Stack Response: %s", up_res)`

As you can see in above logs I shared, it has successfully created the resources, but in the end it failed due to asyncio error. When I look at cloud, I can see the resources are there as well. And de-provision of same works fine.

**Comment by amitjattan** [comment]
@komalali to answer your question whether it's continuous error or not. I would say it happens in between of running APIs, and then I restart the API, the error is gone. Not sure, but I suspect it happens when API is being called by multiple clients at same time.

**Comment by amitjattan** [comment]
This issue is still occurring on our environment, we have upgraded pulumi with v2.23.1. Any idea when it will be fixed.

**Comment by komalali** [comment]
Hey @amitjattan I have a theory on what might be causing this issue but unfortunately, I've been unable to reproduce the error reliably making it very difficult to test my fix. If you have code that consistently reproduces the error, please let me know. Otherwise, this is dependent on me figuring out a reliable repro, so it's difficult to give an exact estimate.

Can you tell me what impact this has on your program? That could help us prioritize.

**Comment by amitjattan** [comment]
Sure @komalali , here is more on my scenario

**below is pip list**
pulumi==2.24.1
pulumi-azure==3.53.0
azure-functions
azure-functions-durable

Below are the import in one of my python class
**import pulumi_azure as azure
from pulumi.x import automation as auto**

Functionality achieved from Pulumi

- Creation of Azure SQL Server
- Creations of Azure SQL DB


Below are the errors while my functions APIs are getting multiple requests same time.

`Raj923 database creation has been failed due to :
code: 255
stdout: Updating (ites-prod-SQL2008_Rgp01-azrmpsqlp078-Raj923):

+ pulumi:pulumi:Stack ites-prod-ites-prod-SQL2008_Rgp01-azrmpsqlp078-Raj923 creating
+ azure:mssql:Server azrmpsqlp078 creating
+ azure:mssql:Server azrmpsqlp078 created
+ azure:sql:FirewallRule Default_IP_1 creating
+ azure:mssql:Database Raj923 creating
+ azure:sql:FirewallRule Default_IP_2 creating
+ azure:sql:FirewallRule Default_IP_3 creating
+ azure:sql:FirewallRule Azure_Access creating
+ azure:sql:FirewallRule Default_IP_2 created
+ azure:sql:FirewallRule Azure_Access created
+ azure:sql:FirewallRule Default_IP_1 created
+ azure:sql:FirewallRule Default_IP_3 created
+ azure:mssql:Database Raj923 created
+ pulumi:pulumi:Stack ites-prod-ites-prod-SQL2008_Rgp01-azrmpsqlp078-Raj923 creating error: an unhandled error occurred: python inline source runtime error: Task <Task pending name='Task-1185' coro=<run_in_stack() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py:83> cb=[_run_until_complete_cb() at /usr/local/lib/python3.9/asyncio/base_events.py:184]> got Future <Task pending name='Task-1791' coro=<register_resource.<locals>.do_register() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/resource.py:358> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb40ede5880>(), <2 more>, <TaskWakeupMethWrapper object at 0x7fb40ee7d9a0>()]> cb=[<TaskWakeupMethWrapper object at 0x7fb40ee7d400>()]> attached to a different loop
+ pulumi:pulumi:Stack ites-prod-ites-prod-SQL2008_Rgp01-azrmpsqlp078-Raj923 **creating failed** 1 error

Diagnostics:
pulumi:pulumi:Stack (ites-prod-ites-prod-SQL2008_Rgp01-azrmpsqlp078-Raj923):
error: an unhandled error occurred: python inline source runtime error: Task <Task pending name='Task-1185' coro=<run_in_stack() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py:83> cb=[_run_until_complete_cb() at /usr/local/lib/python3.9/asyncio/base_events.py:184]> got Future <Task pending name='Task-1791' coro=<register_resource.<locals>.do_register() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/resource.py:358> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb40ede5880>(), <2 more>, <TaskWakeupMethWrapper object at 0x7fb40ee7d9a0>()]> cb=[<TaskWakeupMethWrapper object at 0x7fb40ee7d400>()]> attached to a different loop
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pulumi/x/automation/_server.py", line 64, in Run
loop.run_until_complete(run_in_stack(self.program))
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "/usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
await run_pulumi_func(lambda: Stack(func))
File "/usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
await RPC_MANAGER.rpcs.pop()
RuntimeError: Task <Task pending name='Task-1185' coro=<run_in_stack() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/stack.py:83> cb=[_run_until_complete_cb() at /usr/local/lib/python3.9/asyncio/base_events.py:184]> got Future <Task pending name='Task-1791' coro=<register_resource.<locals>.do_register() running at /usr/local/lib/python3.9/site-packages/pulumi/runtime/resource.py:358> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb40ede5880>(), <2 more>, <TaskWakeupMethWrapper object at 0x7fb40ee7d9a0>()]> cb=[<TaskWakeupMethWrapper object at 0x7fb40ee7d400>()]> attached to a different loop

Resources:
+ 7 created

Duration: 4m43s

 stderr: warning: A new version of Pulumi is available. To upgrade from version '2.23.1' to '2.24.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.`

**Comment by komalali** [comment]
I did some research on the cause of this error, and while I haven't gotten down to the bottom of why it only happens intermittently, I thought I'd write out what I've found already.

My theory is that this is related to the `ThreadPoolExecutor` that we create for the grpc servers in [automation API](https://github.com/pulumi/pulumi/blob/55ecf7a81ebd95f3085cbf611b12567f855320f9/sdk/python/lib/pulumi/x/automation/_stack.py#L339-L340) and for the [mock resource monitor](https://github.com/pulumi/pulumi/blob/cedab0003bda3b4cbb767d1a8875a620c34ba9da/sdk/python/lib/test/langhost/util.py#L303). When using a `ThreadPoolExecutor`, according to the [asyncio docs](https://docs.python.org/3/library/asyncio-eventloop.html#executing-code-in-thread-or-process-pools), it should either be set as the default executor or passed in as the first argument to `loop.run_in_executor()`. However, we don't do that - all of our [calls](https://github.com/pulumi/pulumi/blob/cedab0003bda3b4cbb767d1a8875a620c34ba9da/sdk/python/lib/pulumi/runtime/resource.py#L246) to `run_in_executor` pass in `None` as the executor to use, and we never set the ThreadPoolExecutor we create as the default.

**Comment by komalali** [comment]
@amitjattan I am still investigating this, but I have a few other things that are taking priority right now. Hoping I'll be able to get to it in the next few weeks.

**Comment by t0yv0** [comment]
I can reproduce this pretty consistently `pytest -ss test_with_mocks/test_testing_with_mocks.py` - every 10 runs or so it happens.

**Comment by t0yv0** [comment]
Just poking around the codebase, I wonder how much of a refactoring it would be to:

1. remove `_ensure_event_loop` completely
2. remove `def _sync_await(awaitable: Awaitable[Any]) -> Any:` completely, switching call sites to async
3. perhaps this means moving some gRPC servers to AIO

**Comment by komalali** [comment]
@t0yv0 might be worth touching base with @pgavlin about this. 

I would expect if we did (3) we would also have to find a better solution for https://github.com/pulumi/pulumi/issues/6762

**Comment by komalali** [comment]
@t0yv0 @justinvp any thoughts on whether we should skip this test for now? Wondering where we're at with our confidence in being able to fix this anytime soon.

**Comment by t0yv0** [comment]
Sounds great, skip the test! Provided we're tracking the underlying issue somewhere, would you like me to create a ticket for it? The test is more of a symptom, the underlying issue is we sometimes run more than one asyncio loop and collide futures from both loops.

**Comment by komalali** [comment]
> would you like me to create a ticket for it? 

Yes please! 🙏

**Comment by t0yv0** [comment]
Reopening the issue - the merged in PR has worked around the issue so the test passes every time, however customer code attempting to use Mocks may still be affected by this. The suggested way forward is to eliminate threading then undo the workaround so the test works as before.
