### ISSUE TITLE
Refresh fails with "slice bounds out of range" panic

### ISSUE THREAD

**Issue by austinbutler** [pulumi/pulumi#6583]
While `pulumi up` and `pulumi preview` work just fine, `pulumi refresh` fails with the following error. This is happening on both of my stacks, production and staging. I managed to temporarily fix it on my staging stack by importing an earlier checkpoint file (which required the use of [a script a user created](https://github.com/pulumi/pulumi/issues/6060)), but for some reason it's back again today on the staging stack, too.

```
  pulumi:pulumi:Stack (production):
    panic: runtime error: slice bounds out of range [:42] with capacity 2
    goroutine 150 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.extractInputs(0x5729620, 0xc002f88b40, 0x5729620, 0xc001d756c8, 0x7957cb8, 0xc000f29680, 0x0, 0x0, 0x
7957cb8, 0xc000f29680, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/schema.go:1019 +0xe30
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.extractInputs(0x6af74c0, 0xc002f8dad0, 0x6af74c0, 0xc0032ba540, 0x7957c00, 0xc002047080, 0x0, 0x0, 0x
6af74c0, 0xc002f8da70, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/schema.go:1049 +0x639
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.extractInputs(0x5729620, 0xc002f88c30, 0x5729620, 0xc001d75758, 0x7957cb8, 0xc000f2a280, 0xc0018211e0
, 0x0, 0x7957cb8, 0xc000f2a280, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/schema.go:1014 +0x1c9
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.extractInputs(0x6af74c0, 0xc002f8da10, 0x6af74c0, 0xc0032ba480, 0x7957c00, 0xc002046fd0, 0xc002fd9540
, 0x0, 0x57e1e80, 0xb, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/schema.go:1049 +0x639
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.extractInputsFromOutputs(0xc002f8da10, 0xc0032ba480, 0x793e7c0, 0xc000ee3530, 0xc00180ea50, 0xc0032ba
a01, 0x0, 0x0, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/schema.go:1135 +0x145
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Read(0xc00000ab40, 0x7922e28, 0xc0021aa570, 0xc002198280, 0xc00000ab40, 0x5fed101, 0xc002
1b11c0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/provider.go:897 +0x8bb
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Read_Handler.func1(0x7922e28, 0xc0021aa570, 0x6b71140, 0xc002198280, 0x6bcd4c0, 0xbadbf28, 0x7922e28
, 0xc0021aa570)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.22.1-0.20210310211618-1f16423ede4c/proto/go/provider.pb.go:2287 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x7922e28, 0xc0021aa120, 0x6b71140, 0xc002198280, 0xc002117820, 0xc0021
9a210, 0x0, 0x0, 0x78538c0, 0xc0003bca90)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Read_Handler(0x6cd0920, 0xc00000ab40, 0x7922e28, 0xc0021aa120, 0xc00216aa20, 0xc00176bc40, 0x7922e28
, 0xc0021aa120, 0xc002185900, 0x10c1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.22.1-0.20210310211618-1f16423ede4c/proto/go/provider.pb.go:2289 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006b7500, 0x7944718, 0xc0017a0780, 0xc002172800, 0xc0018c01b0, 0xba996e0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1210 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc0006b7500, 0x7944718, 0xc0017a0780, 0xc002172800, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1533 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001835b10, 0xc0006b7500, 0x7944718, 0xc0017a0780, 0xc002172800)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:869 +0x1fd

    error: preview failed
```

## Expected behavior

`pulumi refresh` does not panic, or it's easier to ascertain what's causing the panic.

## Current behavior

`pulumi refresh` panics so cannot be used.

## Steps to reproduce

This is a rather large project and there's no indication as to what bit of the project is the issue, so at the moment not sure what to put here.

## Context (Environment)

I don't _think_ this was an issue prior to 2.23 and adding `PULUMI_SELF_MANAGED_STATE_LOCKING`, but I could be wrong.

**Comment by stack72** [comment]
Hi @austinbutler 

There is a fix underway for this - https://github.com/pulumi/pulumi-terraform-bridge/pull/336

Sorry this caused some pain

Paul

**Comment by austinbutler** [comment]
Thanks @stack72, I see that has been merged now. Can we close this issue once it's available in a release?

**Comment by stack72** [comment]
Hey @austinbutler whatbprovider are you using that caused this?

**Comment by austinbutler** [comment]
Probably AWS?

**Comment by stack72** [comment]
Sorry I should have been more clear - but yes AWS will be causing it for sure

I opened a PR to that provider with the fix as well

**Comment by austinbutler** [comment]
https://github.com/pulumi/pulumi-aws/pull/1412 I assume.

**Comment by stack72** [comment]
Hey @austinbutler 

I believe this is going to be fixed for you in Pulumi-aws v3.34.1

Let me know if there are any issues with it

Paul

**Comment by DStoyanoff** [comment]
Hello guys,
I am experiencing a similar issue with GCP:

```
panic: runtime error: slice bounds out of range [:10] with capacity 5
    goroutine 43 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.extractInputs(0x36f8f00, 0xc000691db8, 0x36f8f00, 0xc0010bff38, 0x43ec1d8, 0xc000c3f2c0, 0x0, 0x0, 0x43ec1d8, 0xc000c3f2c0, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/schema.go:1019 +0xe30
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.extractInputs(0x3c72580, 0xc001315c50, 0x3c72580, 0xc001175050, 0x43ec1d8, 0xc000c3f400, 0x0, 0x0, 0x43ec1d8, 0xc000c3f400, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/schema.go:1049 +0x639
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.extractInputs(0x3c72580, 0xc001315c20, 0x3c72580, 0xc001175020, 0x43ec1d8, 0xc000c3f900, 0x0, 0x0, 0x43ec1d8, 0xc000c3f900, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/schema.go:1049 +0x639
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.extractInputs(0x3c72580, 0xc001315bf0, 0x3c72580, 0xc001174ff0, 0x43ec120, 0xc00104ea50, 0x0, 0x0, 0x3c72580, 0xc0013159e0, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/schema.go:1049 +0x639
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.extractInputs(0x36f8f00, 0xc000691f38, 0x36f8f00, 0xc0010bff50, 0x43ec1d8, 0xc000c3fcc0, 0x0, 0x0, 0x43ec1d8, 0xc000c3fcc0, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/schema.go:1014 +0x1c9
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.extractInputs(0x3c72580, 0xc0013155f0, 0x3c72580, 0xc001174e10, 0x43ec120, 0xc00104e9a0, 0xc0012b1540, 0x0, 0x373b840, 0x7, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/schema.go:1049 +0x639
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.extractInputsFromOutputs(0xc0013155f0, 0xc001174e10, 0x43cf250, 0xc000c13500, 0xc0007900f0, 0xc001175601, 0x0, 0x0, 0x1)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/schema.go:1135 +0x145
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Read(0xc00000a1e0, 0x439b980, 0xc001315560, 0xc00131e690, 0xc00000a1e0, 0x394fc01, 0xc00134aa80)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.21.0/pkg/tfbridge/provider.go:897 +0x8bb
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Read_Handler.func1(0x439b980, 0xc001315560, 0x3cd4b80, 0xc00131e690, 0x3d29680, 0x5a92350, 0x439b980, 0xc001315560)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.22.1-0.20210310211618-1f16423ede4c/proto/go/provider.pb.go:2287 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x439b980, 0xc001314b70, 0x3cd4b80, 0xc00131e690, 0xc001322360, 0xc000691530, 0x0, 0x0, 0x4367120, 0xc0002ac8f0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Read_Handler(0x3db25a0, 0xc00000a1e0, 0x439b980, 0xc001314b70, 0xc0013106c0, 0xc00003a680, 0x439b980, 0xc001314b70, 0xc0003d4800, 0xbd3)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.22.1-0.20210310211618-1f16423ede4c/proto/go/provider.pb.go:2289 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032d880, 0x43d7e38, 0xc000082900, 0xc001344100, 0xc000790690, 0x5a4f4a0, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.1/server.go:1210 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc00032d880, 0x43d7e38, 0xc000082900, 0xc001344100, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.1/server.go:1533 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000413bb0, 0xc00032d880, 0x43d7e38, 0xc000082900, 0xc001344100)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.1/server.go:871 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.1/server.go:869 +0x1fd
```


It started appearing without a logical reason and the problematic resource was not updated for a while. I've upgraded to the latest available GCP package ("@pulumi/gcp": "^4.16.1"), but this is still appearing. Please let me know what information would be useful to investigate this.

**Comment by stack72** [comment]
Hi @DStoyanoff 

What error are you getting when you upgrade to v4.16.1 of Pulumi GCP? I can see the error above is specific to a version of the provider pre then

Paul

**Comment by DStoyanoff** [comment]
Hm, weird. This was the log after the upgrade. I've tried again now, but it's no longer reproducible. Perhaps something happened and I was still using the old one. Thanks for your input and sorry if I wasted your time checking this.

**Comment by stack72** [comment]
@DStoyanoff no waste of time at all :) I am glad it's working for you! I was ready to help debug

thanks for letting us know
