### ISSUE TITLE
panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update on imported GKE cluster

### ISSUE THREAD

**Issue by nielsdemoen** [pulumi/pulumi#6619]
When trying to update an imported cluster, it fails with:
 panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update of urn:pulumi:stack::project::gcp:container/cluster:Cluster::mycompany-cluster-staging

In this instance we're updating masterAuthorizedNetworksConfig however updating anything else in the cluster has the same affect.  The stack has two clusters, both exhibit the issue.

## Expected behavior
The object should be updated without an unexpected replacement, at minimum the diff should log what's different that would require a replacement and not an update.

## Current behavior
Panics on updates of the cluster.

## Steps to reproduce
1. Import a GKE cluster
2. Attempt an update.

We have other GKE clusters in another stack which don't have this issue, so the issue is specific to this stack.

**Comment by logston** [comment]
Similar, if not the same issue, except my cluster is not imported. The preview prior to `pulumi up` works fine but then the application of the updates fails with the following trace:

```
  pulumi:pulumi:Stack (gke-....):                                                                                                                                                                   
    panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update of urn:pulumi:...::gke::gcp:container/cluster:Cluster::crdb                          
    goroutine 57 [running]:                                                                                                                                                                                          
    github.com/pulumi/pulumi/sdk/go/common/util/contract.failfast(...)                                                                                                                                               
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk@v1.13.1/go/common/util/contract/failfast.go:23                                                                                                      
    github.com/pulumi/pulumi/sdk/go/common/util/contract.Assertf(0xc000880000, 0x363a5df, 0x48, 0xc00088b728, 0x1, 0x1)                                                                                              
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk@v1.13.1/go/common/util/contract/assert.go:33 +0x197                                                                                                 
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.(*Provider).Update(0xc0004f2780, 0x3aebca0, 0xc0009dad80, 0xc00087c000, 0xc0004f2780, 0x3131f01, 0xc0007a2600)                                            
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.8.4/pkg/tfbridge/provider.go:825 +0x81d                                                                                             
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler.func1(0x3aebca0, 0xc0009dad80, 0x34dfc20, 0xc00087c000, 0x34de820, 0x4f7be80, 0x3aebca0, 0xc0009dad80)                                    
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk@v1.13.1/proto/go/provider.pb.go:1920 +0x89                                                                                                          
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3aebca0, 0xc000953b60, 0x34dfc20, 0xc00087c000, 0xc0009a8200, 0xc0009a8220, 0x0, 0x0, 0x3ab25a0, 0xc000433070)         
        /home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f9                                                                      
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler(0x354ad60, 0xc0004f2780, 0x3aebca0, 0xc000953b60, 0xc00053a000, 0xc0004a2420, 0x3aebca0, 0xc000953b60, 0xc00087a000, 0x1dd4)              
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk@v1.13.1/proto/go/provider.pb.go:1922 +0x14b                                                                                                         
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006a2340, 0x3b269a0, 0xc000558900, 0xc0004f4000, 0xc0006c0e70, 0x4f4d5d8, 0x0, 0x0, 0x0)                                                                    
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1082 +0x4fd                                                                                                                             
    google.golang.org/grpc.(*Server).handleStream(0xc0006a2340, 0x3b269a0, 0xc000558900, 0xc0004f4000, 0x0)                                                                                                          
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1405 +0xd23                                                                                                                             
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000d8080, 0xc0006a2340, 0x3b269a0, 0xc000558900, 0xc0004f4000)                                                                                         
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:746 +0xbb                                                                                                                               
    created by google.golang.org/grpc.(*Server).serveStreams.func1                                                                                                                                                   
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:744 +0xa1 
```
