### ISSUE TITLE
[sdk/python] Output.from_input() does not unwrap Inputs in tuples

### ISSUE THREAD

**Issue by hnicke** [pulumi/pulumi#6635]
`Output.from_input()` does not unwrap inputs which are contained in tuples.

## Expected behavior

Inputs in tuples should be unwrapped correctly.

## Current behavior

```
my_input: Input[T]
nested_input = ('test', my_input) # tuple containing an input
lifted_input = Output.from_input(nested_input) # unwrap nested input
assert nested_input == lifted_input # evaluates to True
# lifted_input still contains the nested input
```

## Context (Environment)

I had a bug in my code where i declared an input like this:
```
my_input = RandomPassword(...),
```
instead of 
```
my_input = RandomPassword(...)
```
After executing the code, pulumi crashed with following error log:
```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 479, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 78, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 199, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 185, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/output.py", line 116, in get_value
        val = await self._future
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/output.py", line 188, in run
        return await transformed.future(with_unknowns=True)
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/output.py", line 116, in get_value
        val = await self._future
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/output.py", line 157, in run
        value = await self._future
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/output.py", line 157, in run
        value = await self._future
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi/output.py", line 178, in run
        transformed: Input[U] = func(value)
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi_kubernetes/helm/v3/helm.py", line 422, in <lambda>
        lambda x: json.dumps(x, default=lambda o: {k: v for (k, v) in o.__dict__.items() if v is not None}))
      File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
        return cls(
      File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
      File "/home/heiko/dev/flip/devops/infra/venv/lib/python3.9/site-packages/pulumi_kubernetes/helm/v3/helm.py", line 422, in <lambda>
        lambda x: json.dumps(x, default=lambda o: {k: v for (k, v) in o.__dict__.items() if v is not None}))
    AttributeError: '_asyncio.Future' object has no attribute '__dict__'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Even if the whole python sdk never uses tuples, it would make it much easier if the trailing comma bug wouldn't be masked by this behaviour.

**Comment by justinvp** [comment]
See also repro from #8321

**Comment by Frassle** [comment]
Oh no never mind, that was for RPC serialization this is for from_input. Probably a simple fix though.
