### ISSUE TITLE
dynamic provider resource exhaustion

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#6645]
Gist with repro: https://gist.github.com/EvanBoyle/ac4d50a5cf9c66ce5302e0c325a18e8b

It appears that creating lots of dynamic resources creates resource exhaustion at some layer (investigation ongoing). 

This was getting masked by https://github.com/pulumi/pulumi/issues/6643, but with a fix for that in, I can now see the following output:

```
error: Running program '/Users/evanboyle/go/src/dynprov' failed with an unhandled exception:
Error: failed to register new resource foo [lotsofdynamics]: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted
    at Object.registerResource (/opt/pulumi/node_modules/@pulumi/pulumi/runtime/resource.js:218:27)
    at new Resource (/opt/pulumi/node_modules/@pulumi/pulumi/resource.js:215:24)
    at new ComponentResource (/opt/pulumi/node_modules/@pulumi/pulumi/resource.js:386:9)
    at new Component (/Users/evanboyle/go/src/dynprov/index.ts:36:9)
    at /Users/evanboyle/go/src/dynprov/index.ts:48:9
    at Array.forEach (<anonymous>)
    at /Users/evanboyle/go/src/dynprov/index.ts:47:20
    at Generator.next (<anonymous>)
    at /Users/evanboyle/go/src/dynprov/index.ts:8:71
    at new Promise (<anonymous>)

```

I need to do another pass to figure out at exactly what layer the exhaustion is occurring. This error is coming from the resource monitor, but it is unclear if it originates there or from the dynamic provider. 

It does seem to be related to dynamic providers specifically, as I was not able to get the same behavior when creating a similar number of custom resources (`randomId`). 

Update:

I've made a few improvements in this area to both dynamic provider performance and error logging: 

- Made a perf improvement provider side via #6657 
- Program side perf improvement via #6673 
- Surfacing swallowed errors via #6644

I opened https://github.com/pulumi/pulumi/issues/6675 to track porting these improvements to python. 

There is still somewhat of a logging hole. The error message returned, and the debug logs in the engine do not make it clear that this message originates in the dynamic provider. Theoretically, the resource monitor or some other gRPC service in the call chain could be returning with this error. We should consider adding better instrumentation here. What we currently get back:

```
    error: Running program '/Users/evanboyle/go/src/dynprov' failed with an unhandled exception:
    Error: failed to register new resource foo12 [pulumi-nodejs:dynamic:Resource]: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
        at Object.registerResource (/opt/pulumi/node_modules/@pulumi/pulumi/runtime/resource.js:218:27)
        at new Resource (/opt/pulumi/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/opt/pulumi/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new Resource (/opt/pulumi/node_modules/@pulumi/pulumi/dynamic/index.js:55:9)
        at new MyResource (/Users/evanboyle/go/src/dynprov/index.ts:30:9)
        at /Users/evanboyle/go/src/dynprov/index.ts:40:13
        at Array.forEach (<anonymous>)
        at new Component (/Users/evanboyle/go/src/dynprov/index.ts:39:13)
        at /Users/evanboyle/go/src/dynprov/index.ts:48:9
        at Array.forEach (<anonymous>)
    error: Running program '/Users/evanboyle/go/src/dynprov' failed with an unhandled exception:
    Error: failed to register new resource foo53 [pulumi-nodejs:dynamic:Resource]: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted
        at Object.registerResource (/opt/pulumi/node_modules/@pulumi/pulumi/runtime/resource.js:218:27)
        at new Resource (/opt/pulumi/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/opt/pulumi/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new Resource (/opt/pulumi/node_modules/@pulumi/pulumi/dynamic/index.js:55:9)
        at new MyResource (/Users/evanboyle/go/src/dynprov/index.ts:30:9)
        at /Users/evanboyle/go/src/dynprov/index.ts:40:13
        at Array.forEach (<anonymous>)
        at new Component (/Users/evanboyle/go/src/dynprov/index.ts:39:13)
        at /Users/evanboyle/go/src/dynprov/index.ts:48:9
        at Array.forEach (<anonymous>)
```

**Comment by EvanBoyle** [comment]
fixed via #6673 and #6657

#6675 tracks making these improvements in python
