### ISSUE TITLE
pulumi refresh causes an "Invalid asset" error with StringAsset

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi#6691]
## Expected behavior

`pulumi refresh` has no impact on StringAsset

## Current behavior

`pulumi refresh` causes an "Invalid asset" error with StringAsset

## Steps to reproduce

1. Create an Azure blob with StringAsset
    ```ts
    import * as pulumi from "@pulumi/pulumi";
    import * as resources from "@pulumi/azure-native/resources";
    import * as storage from "@pulumi/azure-native/storage";
    
    // Create an Azure Resource Group
    const resourceGroup = new resources.ResourceGroup("resourceGroup");
    // Create an Azure resource (Storage Account)
    const storageAccount = new storage.StorageAccount("sa", {
        resourceGroupName: resourceGroup.name,
        sku: {
            name: storage.SkuName.Standard_LRS,
        },
        kind: storage.Kind.StorageV2,
    })
    const blobContainer = new storage.BlobContainer("blobContainer", {
        accountName: storageAccount.name,
        resourceGroupName: resourceGroup.name,
        containerName: "assets",
        publicAccess: storage.PublicAccess.Blob,
    })
    
    const file = new storage.Blob('mon-fichier.txt', {
        accountName: storageAccount.name,
        resourceGroupName: resourceGroup.name,
        containerName: blobContainer.name,
        blobName: 'mon-fichier.txt',
        source: new pulumi.asset.StringAsset('lab azure')
    })
    ```
2. do `pulumi up` to deploy it
3. a second `pulumi up` works as expected (no changes) 
3. perform a refresh with `pulumi refresh`
4. now `pulumi preview` fails with following error:
    ```bash
    $ pulumi preview
    
    Previewing update (dev)
    
    View Live: https://app.pulumi.com/MAIF/lab-storage/dev/previews/b6ac5a78-3cc4-41ef-9905-1ddefd2f416d
    
         Type                                   Name             Plan       Info
         pulumi:pulumi:Stack                    lab-storage-dev             1 error; 24 messages
     ~   └─ azure-native:storage:BlobContainer  blobContainer    update     [diff: -defaultEncryptionScope,denyEncryptionScopeOverride]
    
    Diagnostics:
      pulumi:pulumi:Stack (lab-storage-dev):
        unhandled rejection: CONTEXT(375): monitor.registerResource(resource:mon-fichier.txt[azure-native:storage:Blob])-initial
        STACK_TRACE:
        Error:
            at Object.debuggablePromise (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
            at runAsyncResourceOp (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:634:75)
            at Object.<anonymous> (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:257:9)
            at Generator.next (<anonymous>)
            at /private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
            at new Promise (<anonymous>)
            at __awaiter (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
            at /private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:219:63
            at processTicksAndRejections (node:internal/process/task_queues:94:5)
        unhandled rejection: CONTEXT(375): monitor.registerResource(resource:mon-fichier.txt[azure-native:storage:Blob])-initial
        STACK_TRACE:
        Error:
            at Object.debuggablePromise (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/debuggable.js:69:75)
            at runAsyncResourceOp (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:634:75)
            at Object.<anonymous> (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:257:9)
            at Generator.next (<anonymous>)
            at /private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
            at new Promise (<anonymous>)
            at __awaiter (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
            at /private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:219:63
            at processTicksAndRejections (node:internal/process/task_queues:94:5)
    
        error: Running program '/private/tmp/lab-storage' failed with an unhandled exception:
        Error: Invalid asset encountered when unmarshaling resource property
            at deserializeProperty (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/rpc.js:437:31)
            at deserializeProperty (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/rpc.js:506:23)
            at deserializeProperty (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/rpc.js:463:32)
            at Object.deserializeProperties (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/rpc.js:126:24)
            at /private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:524:43
            at Generator.next (<anonymous>)
            at /private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
            at new Promise (<anonymous>)
            at __awaiter (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
            at resolveOutputs (/private/tmp/lab-storage/node_modules/@pulumi/pulumi/runtime/resource.js:519:12)
    ```

## Analysis

If I compare state before and after `pulumi refresh`, I saw that `text` property has been removed.

- Before:
  ```json
  {
        "urn": "urn:pulumi:dev::lab-storage::azure-native:storage:Blob::mon-fichier.txt",
        "type": "azure-native:storage:Blob",
        "inputs": {
            "accountName": "saae3692d4",
            "blobName": "mon-fichier.txt",
            "containerName": "assets",
            "resourceGroupName": "rg-trainee-manuel.boillod",
            "source": {
                "4dabf18193072939515e22adb298388d": "c44067f5952c0a294b673a41bacd8c17",
                "hash": "678e7adc27d2686c9451d307fa0dc71ccae7a8e040c552ef1bacd453ad9e3bc9",
                "text": "lab azure"
            },
            "type": "Block"
        }
   }
  ```
- After : 
  ```json
  {
        "urn": "urn:pulumi:dev::lab-storage::azure-native:storage:Blob::mon-fichier.txt",
        "type": "azure-native:storage:Blob",
        "inputs": {
            "accountName": "saae3692d4",
            "blobName": "mon-fichier.txt",
            "containerName": "assets",
            "resourceGroupName": "rg-trainee-manuel.boillod",
            "source": {
                "4dabf18193072939515e22adb298388d": "c44067f5952c0a294b673a41bacd8c17",
                "hash": "678e7adc27d2686c9451d307fa0dc71ccae7a8e040c552ef1bacd453ad9e3bc9"
            },
            "type": "Block"
        }
   }
  ```

## Context (Environment)

- pulumi: v2.24.0
- npm:
  ```
  ├── @pulumi/azure-native@0.7.1
  ├── @pulumi/pulumi@2.23.2
  └── @types/node@10.17.56
  ```

## Affected feature

- `pulumi.asset.StringAsset`

**Comment by boillodmanuel** [comment]
similar error message in #3018

**Comment by cnunciato** [comment]
Hitting this myself but with a `FileAsset`, and it's not clear how to get out of it.

**Comment by chrisjohnson00** [comment]
This can be simply reproduced by doing:

```
pulumi new serverless-azure-python -y
pulumi up -y
pulumi refresh -y
pulumi up -y
```

Results in 

```
(venv) chris@r10-ubuntu:/tmp/foobar$ pulumi new serverless-azure-python -y
Created project 'foobar'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
Created stack 'dev'

Saved config

Installing dependencies...

Creating virtual environment...
Finished creating virtual environment
Updating pip, setuptools, and wheel in virtual environment...
Requirement already satisfied: pip in ./venv/lib/python3.10/site-packages (22.2)
Collecting pip
  Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
Requirement already satisfied: setuptools in ./venv/lib/python3.10/site-packages (59.6.0)
Collecting setuptools
  Using cached setuptools-67.7.2-py3-none-any.whl (1.1 MB)
Collecting wheel
  Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Uninstalling setuptools-59.6.0:
      Successfully uninstalled setuptools-59.6.0
  Attempting uninstall: pip
    Found existing installation: pip 22.2
    Uninstalling pip-22.2:
      Successfully uninstalled pip-22.2
Successfully installed pip-23.1.2 setuptools-67.7.2 wheel-0.40.0
Finished updating
Installing dependencies in virtual environment...
Collecting pulumi<4.0.0,>=3.0.0 (from -r requirements.txt (line 1))
  Using cached pulumi-3.65.1-py3-none-any.whl (180 kB)
Collecting pulumi-azure-native<2.0.0,>=1.0.0 (from -r requirements.txt (line 2))
  Using cached pulumi_azure_native-1.101.0-py3-none-any.whl
Collecting pulumi-synced-folder<1.0.0,>=0.0.0 (from -r requirements.txt (line 3))
  Using cached pulumi_synced_folder-0.10.2-py3-none-any.whl
Collecting protobuf~=4.21 (from pulumi<4.0.0,>=3.0.0->-r requirements.txt (line 1))
  Using cached protobuf-4.22.3-cp37-abi3-manylinux2014_x86_64.whl (302 kB)
Collecting grpcio==1.51.3 (from pulumi<4.0.0,>=3.0.0->-r requirements.txt (line 1))
  Using cached grpcio-1.51.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
Collecting dill~=0.3 (from pulumi<4.0.0,>=3.0.0->-r requirements.txt (line 1))
  Using cached dill-0.3.6-py3-none-any.whl (110 kB)
Collecting six~=1.12 (from pulumi<4.0.0,>=3.0.0->-r requirements.txt (line 1))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting semver~=2.13 (from pulumi<4.0.0,>=3.0.0->-r requirements.txt (line 1))
  Using cached semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting pyyaml~=6.0 (from pulumi<4.0.0,>=3.0.0->-r requirements.txt (line 1))
  Using cached PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
Collecting parver>=0.2.1 (from pulumi-azure-native<2.0.0,>=1.0.0->-r requirements.txt (line 2))
  Using cached parver-0.4-py3-none-any.whl (15 kB)
Collecting arpeggio>=1.7 (from parver>=0.2.1->pulumi-azure-native<2.0.0,>=1.0.0->-r requirements.txt (line 2))
  Using cached Arpeggio-2.0.0-py2.py3-none-any.whl (54 kB)
Collecting attrs>=19.2 (from parver>=0.2.1->pulumi-azure-native<2.0.0,>=1.0.0->-r requirements.txt (line 2))
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Installing collected packages: arpeggio, six, semver, pyyaml, protobuf, grpcio, dill, attrs, pulumi, parver, pulumi-synced-folder, pulumi-azure-native
Successfully installed arpeggio-2.0.0 attrs-23.1.0 dill-0.3.6 grpcio-1.51.3 parver-0.4 protobuf-4.22.3 pulumi-3.65.1 pulumi-azure-native-1.101.0 pulumi-synced-folder-0.10.2 pyyaml-6.0 semver-2.13.0 six-1.16.0
Finished installing dependencies
Finished installing dependencies

Your new project is ready to go! 

To perform an initial deployment, run `pulumi up`

(venv) chris@r10-ubuntu:/tmp/foobar$ pulumi up -y
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/chrisjohnson00/foobar/dev/previews/f57d73c2-f370-4e67-a742-1791c5e4abdf

     Type                                                 Name                      Plan       
 +   pulumi:pulumi:Stack                                  foobar-dev                create     
 +   ├─ azure-native:resources:ResourceGroup              resource-group            create     
 +   ├─ azure-native:web:AppServicePlan                   plan                      create     
 +   ├─ azure-native:storage:StorageAccount               account                   create     
 +   ├─ azure-native:storage:StorageAccountStaticWebsite  website                   create     
 +   ├─ azure-native:storage:BlobContainer                app-container             create     
 +   ├─ azure-native:storage:Blob                         app-blob                  create     
 +   ├─ azure-native:web:WebApp                           app                       create     
 +   ├─ azure-native:storage:Blob                         config.json               create     
 +   └─ synced-folder:index:AzureBlobFolder               synced-folder             create     
 +      ├─ azure-native:storage:Blob                      synced-folder-error.html  create     
 +      └─ azure-native:storage:Blob                      synced-folder-index.html  create     


Outputs:
    apiURL : output<string>
    siteURL: output<string>

Resources:
    + 12 to create

Updating (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/chrisjohnson00/foobar/dev/updates/1

     Type                                                 Name                      Status              
 +   pulumi:pulumi:Stack                                  foobar-dev                created (55s)       
 +   ├─ azure-native:resources:ResourceGroup              resource-group            created (1.00s)     
 +   ├─ azure-native:web:AppServicePlan                   plan                      created (7s)        
 +   ├─ azure-native:storage:StorageAccount               account                   created (21s)       
 +   ├─ azure-native:storage:StorageAccountStaticWebsite  website                   created (1s)        
 +   ├─ azure-native:storage:BlobContainer                app-container             created (0.55s)     
 +   ├─ azure-native:storage:Blob                         app-blob                  created (0.68s)     
 +   ├─ azure-native:web:WebApp                           app                       created (29s)       
 +   ├─ synced-folder:index:AzureBlobFolder               synced-folder             created (0.56s)     
 +   │  ├─ azure-native:storage:Blob                      synced-folder-error.html  created (0.63s)     
 +   │  └─ azure-native:storage:Blob                      synced-folder-index.html  created (0.65s)     
 +   └─ azure-native:storage:Blob                         config.json               created (0.81s)     


Outputs:
    apiURL : "https://appe1283816.azurewebsites.net/api"
    siteURL: "https://account8e13103a.z22.web.core.windows.net/"

Resources:
    + 12 created

Duration: 58s

(venv) chris@r10-ubuntu:/tmp/foobar$ pulumi refresh -y
Previewing refresh (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/chrisjohnson00/foobar/dev/previews/33cc2b83-68d3-4c61-9995-7b02e627e372

     Type                                                 Name                      Plan       Info
     pulumi:pulumi:Stack                                  foobar-dev                           
     ├─ azure-native:resources:ResourceGroup              resource-group                       
     ├─ azure-native:storage:StorageAccount               account                              
 ~   ├─ azure-native:web:AppServicePlan                   plan                      update     [diff: ~numberOfSites]
 ~   ├─ azure-native:storage:BlobContainer                app-container             update     [diff: +defaultEncryptionScope,denyEncryptionScopeOverride,etag,lastModifiedTime,leaseState,leaseStatus,legalHold]
     ├─ synced-folder:index:AzureBlobFolder               synced-folder                        
     │  ├─ azure-native:storage:Blob                      synced-folder-error.html             
     │  └─ azure-native:storage:Blob                      synced-folder-index.html             
     ├─ azure-native:storage:Blob                         app-blob                             
     ├─ azure-native:storage:StorageAccountStaticWebsite  website                              
     ├─ azure-native:storage:Blob                         config.json                          
     └─ azure-native:web:WebApp                           app                                  


Resources:
    ~ 2 to update
    10 unchanged

Refreshing (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/chrisjohnson00/foobar/dev/updates/2

     Type                                                 Name                      Status              Info
     pulumi:pulumi:Stack                                  foobar-dev                                    
     ├─ azure-native:resources:ResourceGroup              resource-group                                
 ~   ├─ azure-native:web:AppServicePlan                   plan                      updated (0.31s)     [diff: ~numberOfSites]
 ~   ├─ azure-native:storage:BlobContainer                app-container             updated (0.17s)     [diff: +defaultEncryptionScope,denyEncryptionScopeOverride,etag,lastModifiedTime,leaseState,leaseStatus,legalHold]
     ├─ azure-native:storage:StorageAccount               account                                       
     ├─ azure-native:storage:StorageAccountStaticWebsite  website                                       
     ├─ synced-folder:index:AzureBlobFolder               synced-folder                                 
     │  ├─ azure-native:storage:Blob                      synced-folder-error.html                      
     │  └─ azure-native:storage:Blob                      synced-folder-index.html                      
     ├─ azure-native:storage:Blob                         app-blob                                      
     ├─ azure-native:storage:Blob                         config.json                                   
     └─ azure-native:web:WebApp                           app                                           


Outputs:
    apiURL : "https://appe1283816.azurewebsites.net/api"
    siteURL: "https://account8e13103a.z22.web.core.windows.net/"

Resources:
    ~ 2 updated
    10 unchanged

Duration: 2s

(venv) chris@r10-ubuntu:/tmp/foobar$ pulumi up -y
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/chrisjohnson00/foobar/dev/previews/1a8d9470-7bd5-4f79-9edf-cc8b3f109844

     Type                                   Name           Plan       Info
     pulumi:pulumi:Stack                    foobar-dev                3 errors; 11 messages
 ~   └─ azure-native:storage:BlobContainer  app-container  update     [diff: -defaultEncryptionScope,denyEncryptionScopeOverride]


Diagnostics:
  pulumi:pulumi:Stack (foobar-dev):
    error: Error: Invalid asset encountered when unmarshaling resource property
        at deserializeProperty (/snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/rpc.js:524:31)
        at deserializeProperty (/snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/rpc.js:605:23)
        at deserializeProperty (/snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/rpc.js:550:32)
        at Object.deserializeProperties (/snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/rpc.js:164:24)
        at /snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/resource.js:681:43
        at Generator.next (<anonymous>)
        at /snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
        at resolveOutputs (/snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/resource.js:676:12)
    error: Error: Invalid asset encountered when unmarshaling resource property
        at deserializeProperty (/snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/rpc.js:524:31)
        at deserializeProperty (/snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/rpc.js:605:23)
        at deserializeProperty (/snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/rpc.js:550:32)
        at Object.deserializeProperties (/snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/rpc.js:164:24)
        at /snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/resource.js:681:43
        at Generator.next (<anonymous>)
        at /snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
        at resolveOutputs (/snapshot/pulumi-resource-synced-folder/node_modules/@pulumi/pulumi/runtime/resource.js:676:12)
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/tmp/foobar/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 916, in do_rpc_call
        return monitor.RegisterResource(req)
      File "/tmp/foobar/venv/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
        return _end_unary_response_blocking(state, call, False, None)
      File "/tmp/foobar/venv/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
        raise _InactiveRpcError(state)
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Invalid asset encountered when unmarshaling resource property"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:44513 {created_time:"2023-04-27T11:05:36.201998699-07:00", grpc_status:2, grpc_message:"Invalid asset encountered when unmarshaling resource property"}"
    >
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/chris/.pulumi/bin/pulumi-language-python-exec", line 197, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
        return future.result()
      File "/tmp/foobar/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 136, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/tmp/foobar/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/tmp/foobar/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 120, in wait_for_rpcs
        raise exception
      File "/tmp/foobar/venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
      File "/tmp/foobar/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 921, in do_register
        resp = await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/tmp/foobar/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 918, in do_rpc_call
        handle_grpc_error(exn)
      File "/tmp/foobar/venv/lib/python3.10/site-packages/pulumi/runtime/settings.py", line 273, in handle_grpc_error
        raise grpc_error_to_exception(exn)
    Exception: Invalid asset encountered when unmarshaling resource property

    exception calling callback for <Future at 0x7f83e0301330 state=finished returned tuple>
    Traceback (most recent call last):
      File "/usr/lib/python3.10/concurrent/futures/_base.py", line 342, in _invoke_callbacks
        callback(self)
      File "/usr/lib/python3.10/asyncio/futures.py", line 399, in _call_set_state
        dest_loop.call_soon_threadsafe(_set_state, destination, source)
      File "/usr/lib/python3.10/asyncio/base_events.py", line 795, in call_soon_threadsafe
        self._check_closed()
      File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed
```

**Comment by chrisjohnson00** [comment]
I will note, the exact same sequence works perfectly on AWS using the `serverless-aws-python` template.

**Comment by Frassle** [comment]
Doesn't look like `serverless-aws-python` uses StringAssets at all, so probably not a fair comparison of azure vs aws there, but I do still suspect this might be an azure provider issue given how refresh works.

**Comment by chrisjohnson00** [comment]
> Doesn't look like `serverless-aws-python` uses StringAssets at all, so probably not a fair comparison of azure vs aws there, but I do still suspect this might be an azure provider issue given how refresh works.

@Frassle - Is there a better ticket to track for Azure provider updates related to refresh?

For example, if I deploy the serverless python template for Azure, then some idiot manually changes/removes something, I have no simple/easy way to get things back in sync.  Doing the same test (manually delete something) in AWS, followed by a refresh and update works beautifully.

**Comment by Tungsten78** [comment]
Would it make sense to move this bug to azure-native?

**Comment by Zaid-Ajaj** [comment]
> Would it make sense to move this bug to azure-native?

Hi @Tungsten78 I am currently working on this issue. I believe it to be an engine specific bug since the azure-native provider doesn't do anything with the assets during `pulumi refresh`

**Comment by Zaid-Ajaj** [comment]
This has been fixed as of Pulumi CLI v3.87.0 🎉

**Comment by mausch** [comment]
I just got this in v3.94.0 after a `pulumi refresh`.
Are there any workarounds?

**Comment by aleclarson** [comment]
Is there guidance on how to escape this issue?

- Pulumi CLI v3.153.1
