### ISSUE TITLE
[sdk/python] Exception raised when serializing an output type that has "items" as one of the properties

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi#6697]
I was trying to export the `trusted_signers` output property of the `Distribution` resource when I hit this error. Note that this same problem exists when registering outputs in component resources via [`self.register_outputs()`](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/resource.py#L482) as well when we [serialize properties](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/rpc.py#L222-L227) there.

Although I hit this problem while exporting a CFN `Distribution` resource property, I believe this affects any resource that uses an output type with a property called `items`. To test the theory I made a local patch to the output serialization for [stack outputs](For https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/stack.py#L172-L175) using this:

```python
for key in attr:
    # ignore private keys
    if not key.startswith("_"):
        result[key] = massage(attr[key], seen)
```

which then correctly produces:

```
Outputs:
    trusted_signers: [
        [0]: {
            enabled: true
            items  : [
                [0]: {
                    awsAccountNumber: "self"
                }
            ]
        }
    ]
```

## Expected behavior

Output is exported without any errors.

## Current behavior

```
Diagnostics:
  pulumi:pulumi:Stack (aws-cloudfront-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/Users/praneetloke/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
        return future.result()
      File "/Users/praneetloke/temp-pulumi-stacks/aws-cloudfront/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 104, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/praneetloke/temp-pulumi-stacks/aws-cloudfront/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 85, in run_pulumi_func
        raise exception
      File "/Users/praneetloke/temp-pulumi-stacks/aws-cloudfront/venv/lib/python3.8/site-packages/pulumi/output.py", line 178, in run
        transformed: Input[U] = func(value)
      File "/Users/praneetloke/temp-pulumi-stacks/aws-cloudfront/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 180, in <lambda>
        return attr.apply(lambda v: massage(v, seen))
      File "/Users/praneetloke/temp-pulumi-stacks/aws-cloudfront/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 201, in massage
        return [massage(a, seen) for a in attr]
      File "/Users/praneetloke/temp-pulumi-stacks/aws-cloudfront/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 201, in <listcomp>
        return [massage(a, seen) for a in attr]
      File "/Users/praneetloke/temp-pulumi-stacks/aws-cloudfront/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 172, in massage
        for key, value in attr.items():
    TypeError: 'list' object is not callable
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

## Steps to reproduce

I just ran the example from https://www.pulumi.com/docs/reference/pkg/aws/cloudfront/distribution/.

```python
"""An AWS Python Pulumi program"""

import pulumi
import pulumi_aws as aws

bucket = aws.s3.Bucket("bucket",
    acl="private",
    tags={
        "Name": "My bucket",
    })
s3_origin_id = "myS3Origin"
s3_distribution = aws.cloudfront.Distribution("s3Distribution",
    origins=[aws.cloudfront.DistributionOriginArgs(
        domain_name=bucket.bucket_regional_domain_name,
        origin_id=s3_origin_id,
    )],
    enabled=True,
    is_ipv6_enabled=True,
    comment="Some comment",
    default_root_object="index.html",
    default_cache_behavior=aws.cloudfront.DistributionDefaultCacheBehaviorArgs(
        allowed_methods=[
            "DELETE",
            "GET",
            "HEAD",
            "OPTIONS",
            "PATCH",
            "POST",
            "PUT",
        ],
        cached_methods=[
            "GET",
            "HEAD",
        ],
        trusted_signers=[ "self" ],
        target_origin_id=s3_origin_id,
        forwarded_values=aws.cloudfront.DistributionDefaultCacheBehaviorForwardedValuesArgs(
            query_string=False,
            cookies=aws.cloudfront.DistributionDefaultCacheBehaviorForwardedValuesCookiesArgs(
                forward="none",
            ),
        ),
        viewer_protocol_policy="allow-all",
        min_ttl=0,
        default_ttl=3600,
        max_ttl=86400,
    ),
    ordered_cache_behaviors=[
        aws.cloudfront.DistributionOrderedCacheBehaviorArgs(
            path_pattern="/content/immutable/*",
            allowed_methods=[
                "GET",
                "HEAD",
                "OPTIONS",
            ],
            cached_methods=[
                "GET",
                "HEAD",
                "OPTIONS",
            ],
            target_origin_id=s3_origin_id,
            forwarded_values=aws.cloudfront.DistributionOrderedCacheBehaviorForwardedValuesArgs(
                query_string=False,
                headers=["Origin"],
                cookies=aws.cloudfront.DistributionOrderedCacheBehaviorForwardedValuesCookiesArgs(
                    forward="none",
                ),
            ),
            min_ttl=0,
            default_ttl=86400,
            max_ttl=31536000,
            compress=True,
            viewer_protocol_policy="redirect-to-https",
        ),
        aws.cloudfront.DistributionOrderedCacheBehaviorArgs(
            path_pattern="/content/*",
            allowed_methods=[
                "GET",
                "HEAD",
                "OPTIONS",
            ],
            cached_methods=[
                "GET",
                "HEAD",
            ],
            target_origin_id=s3_origin_id,
            forwarded_values=aws.cloudfront.DistributionOrderedCacheBehaviorForwardedValuesArgs(
                query_string=False,
                cookies=aws.cloudfront.DistributionOrderedCacheBehaviorForwardedValuesCookiesArgs(
                    forward="none",
                ),
            ),
            min_ttl=0,
            default_ttl=3600,
            max_ttl=86400,
            compress=True,
            viewer_protocol_policy="redirect-to-https",
        ),
    ],
    price_class="PriceClass_200",
    restrictions=aws.cloudfront.DistributionRestrictionsArgs(
        geo_restriction=aws.cloudfront.DistributionRestrictionsGeoRestrictionArgs(
            restriction_type="whitelist",
            locations=[
                "US",
                "CA",
                "GB",
                "DE",
            ],
        ),
    ),
    tags={
        "Environment": "production",
    },
    viewer_certificate=aws.cloudfront.DistributionViewerCertificateArgs(
        cloudfront_default_certificate=True,
    ))

pulumi.export("trusted_signers", s3_distribution.trusted_signers)
```

## Context (Environment)

Here's my `pip list` for `pulumi` packages:

```
❯ pip list
Package    Version
---------- -------
pulumi     2.24.1
pulumi-aws 3.35.0
```

**Comment by praneetloke** [comment]
@komalali thank you for fixing the issue! I was thinking that the same fix would be needed for https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/rpc.py#L222-L227 since output serialization during `register_outputs` seems to be following a different code path than for stack output serialization.

**Comment by komalali** [comment]
Ah yup, good call. Thanks @praneetloke!

**Comment by praneetloke** [comment]
Whoa! That's blazing fast, @komalali! Thank you! 🙏
