### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by followben** [pulumi/pulumi#6717]
With Python 3.10 [in developer preview and due for beta release next month](https://pythoninsider.blogspot.com/2021/04/python-3100a7-is-now-available-for.html), would love to see a roadmap of what needs to be be done on both the core pulumi Python SDK as well as the provider-specific SDKs to support it.

There's some great improvements incl. support for structural pattern matching and enhanced typing which might improve both the internal implementation of Pulumi's own codebase as well as that of your customers.

I understand there may be dependencies that do not or cannot immediately support 3.10.x, but it'd nice to have visibility of them as well as any required internal changes.

## Affected feature

Support for Python 3.10

**Comment by komalali** [comment]
@followben I imagine we probably won't be able to update the pulumi codebase itself since we need to remain compatible with python 3.6+, but on the surface there's nothing that stands out to me that would be incompatible with users using python 3.10. 

You can see our support issue for the [update to 3.9](https://github.com/pulumi/pulumi/issues/5662) that mentioned that we needed grpc and protobuf updates, but I think with the changes we made there we might not need any internal fixes to support 3.10.

All of that to say that you should try it out with 3.10 if you want to and let us know what you find!

**Comment by tksrc** [comment]
I have started seeing this "warning" message after migrating to 3.10. The exact same setup using 3.9 does not generate such message.

![image](https://user-images.githubusercontent.com/52125950/142618368-7576ae82-db2f-409d-b28c-d5a54387fd84.png)

--- adding the message in text in case other people search for this too
`Failed to resolve python version command: fork/exec bin/python: no such file or directory`

**Comment by nimbinatus** [comment]
When trying to run a `pulumi up` with version 3.10.3, I got this traceback in case it helps:

```
  pulumi:pulumi:Stack (infra-dev):
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 14, in <module>
        import pulumi
      File "/Users/nimbinatus/.local/share/virtualenvs/stand-back-talk-EGEXhFrC/lib/python3.10/site-packages/pulumi/__init__.py", line 33, in <module>
        from .config import (
      File "/Users/nimbinatus/.local/share/virtualenvs/stand-back-talk-EGEXhFrC/lib/python3.10/site-packages/pulumi/config.py", line 22, in <module>
        from . import log
      File "/Users/nimbinatus/.local/share/virtualenvs/stand-back-talk-EGEXhFrC/lib/python3.10/site-packages/pulumi/log.py", line 22, in <module>
        from .runtime.settings import get_engine
      File "/Users/nimbinatus/.local/share/virtualenvs/stand-back-talk-EGEXhFrC/lib/python3.10/site-packages/pulumi/runtime/__init__.py", line 29, in <module>
        from .mocks import (
      File "/Users/nimbinatus/.local/share/virtualenvs/stand-back-talk-EGEXhFrC/lib/python3.10/site-packages/pulumi/runtime/mocks.py", line 24, in <module>
        from . import rpc, rpc_manager
      File "/Users/nimbinatus/.local/share/virtualenvs/stand-back-talk-EGEXhFrC/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 40, in <module>
        from . import known_types, settings
      File "/Users/nimbinatus/.local/share/virtualenvs/stand-back-talk-EGEXhFrC/lib/python3.10/site-packages/pulumi/runtime/settings.py", line 22, in <module>
        import grpc
      File "/Users/nimbinatus/.local/share/virtualenvs/stand-back-talk-EGEXhFrC/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
        from grpc import _compression
      File "/Users/nimbinatus/.local/share/virtualenvs/stand-back-talk-EGEXhFrC/lib/python3.10/site-packages/grpc/_compression.py", line 15, in <module>
        from grpc._cython import cygrpc
    ImportError: dlopen(/Users/nimbinatus/.local/share/virtualenvs/stand-back-talk-EGEXhFrC/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 2): no suitable image found.  Did find:
        /Users/nimbinatus/.local/share/virtualenvs/stand-back-talk-EGEXhFrC/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so: mach-o, but wrong architecture
        /Users/nimbinatus/.local/share/virtualenvs/stand-back-talk-EGEXhFrC/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so: mach-o, but wrong architecture
    It looks like the Pulumi SDK has not been installed. Have you run pip install?
    If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
 
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Details:
- Python 3.10.3 via pyenv and a shim.
- pipenv as a virtual environment (same thing happened with the built-in, though)
- Brand new project and stack

**Comment by Frassle** [comment]
This is due to a change in python 3.10 which has broken the grpc wheel package: https://github.com/grpc/grpc/issues/28387

**Comment by lukehoban** [comment]
Adding a little more here.

As @Frassle notes - this appears to be due to https://github.com/grpc/grpc/issues/28387. It looks like the Python gRPC library has a significant problem on Python 3.10 on M1 Macs. We'll have to look into whether we can somehow pin a specific version without this problem, though it looks like it's been a problem for a long time, and that possibly there is no available Python gRPC library without this bug on Python 3.10 and M1 Macs.

There is a workaround at https://github.com/grpc/grpc/issues/28387#issuecomment-1016166913, as well as the option to use Python 3.9 instead of 3.10 which avoids this problem if that can work in your environment.
