### ISSUE TITLE
[sdk/python] - Improve await of outstanding tasks

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#6762]
Currently, we [collect all remaining async tasks](https://github.com/pulumi/pulumi/blob/0c4e1a33e058a5b129ba009c5a58793200c09fff/sdk/python/lib/pulumi/runtime/stack.py#L65-L87) in the event loop and await them prior to exit. We introduced this via https://github.com/pulumi/pulumi/pull/6606. This is not great, because there may be async tasks from the user that have nothing to do with Pulumi and we'll end up waiting maybe forever.

A better solution would collect the outstanding tasks that we would like to await (mostly `Output`/`apply`-related tasks) and *only* await those. 

## Expected behavior

The expected behavior is for `pulumi preview` to succeed quickly in presence of unrelated long-running tasks.

## Current behavior

Current behavior is for `pulumi preview`, and indeed driver program execution, hangs until unrelated long-running tasks complete.

## Steps to reproduce

Simple program to repro:

```
"""An AWS Python Pulumi program"""

import asyncio
import pulumi
from pulumi_aws import s3

async def t():
    print('start')
    await asyncio.sleep(10000)
    print('end')

loop = asyncio.get_running_loop()
loop.create_task(t())

# Create an AWS resource (S3 Bucket)
bucket = s3.Bucket('my-bucket')

# Export the name of the bucket
pulumi.export('bucket_name', bucket.id)
```

The more interesting reproduction case involves Automation API. Starting from inline_program example:

https://github.com/pulumi/automation-api-examples/tree/main/python/inline_program

If we inject the `create_task` into main.py, `def pulumi_program`, then we can reproduce the issue. Interestingly if we inject create_task at top-level, the issue does not happen. This seems to be affecting only the scope of inline program, which may have its own event loop (and/or process or thread).

## Context (Environment)

This has affected @t0yv0  when working on multi-lang features, in the context of a provider running gRPC AIO server. The Python primitives we use to await RPC calls inadvertently grab tasks pertaining to the gRPC server loop, which never complete by design. Specifically this primitive is responsible:

```
# pulumi/runtime/stack.py
async def run_pulumi_func(func: Callable):
  ...
```

This can be traced down to using ```_all_tasks = asyncio.Task.all_tasks``` and awaiting them; that is, the code references the thread-level event loop and inspects all running tasks.

It seems to be invoked in at least LanguageServer.

For mutli-lang component purposes we might have a workaround.

## Affected feature

The logic can be traced back to the PR 6606 that introduced awaiting outstanding apply calls and Output chain resolution before exiting, which is a nice feature for Pulumi CLI. The original design decision of awaiting all tasks is even somewhat justified in the CLI program context, as we expect the typical program to not run any long AIO tasks.

However, these assumptions now break down as we reuse the SDK code in other contexts, such as multi-lang servers or Automation API. In the latter case especially, we cannot assume that our SDK owns the event loop, we might accidentally lock up on some user tasks.

**Comment by komalali** [comment]
> If we inject the create_task into main.py, def pulumi_program, then we can reproduce the issue. Interestingly if we inject create_task at top-level, the issue does not happen. This seems to be affecting only the scope of inline program, which may have its own event loop (and/or process or thread).

Yes, inline programs run in their own thread because we are using the [thread-based grpc server](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/x/automation/_stack.py#L251-L252). So this will only bite us in automation API if there are long-running async tasks within the pulumi program itself, which is somewhat unlikely. That being said, if we migrate to asyncio-based grpc API as we are using in the multi-lang server, this will indeed bite us.

I only mention this as a "this is not immediately terrible for automation API" note.

**Comment by t0yv0** [comment]
Great. So then we do not have a credible scenario of this affecting users yet, that's good to know. It may be less important than originally appeared then. Ty.

**Comment by manojlds** [comment]
Seeing issues running automation api in Celery workers that could be related to this:

```
[2021-06-24 19:00:35,818: WARNING/ForkPoolWorker-1] +  pulumi:pulumi:Stack notebook creating error: python inline source runtime error:
[2021-06-24 19:00:35,818: WARNING/ForkPoolWorker-1] +  pulumi:pulumi:Stack notebook creating error: an unhandled error occurred: python inline source runtime error:
[2021-06-24 19:00:36,677: WARNING/ForkPoolWorker-1] +  pulumi:pulumi:Stack notebook **creating failed** 2 errors
[2021-06-24 19:00:36,677: WARNING/ForkPoolWorker-1] Diagnostics:
[2021-06-24 19:00:36,677: WARNING/ForkPoolWorker-1] pulumi:pulumi:Stack (notebook):
[2021-06-24 19:00:36,677: WARNING/ForkPoolWorker-1] error: python inline source runtime error:
[2021-06-24 19:00:36,677: WARNING/ForkPoolWorker-1] Traceback (most recent call last):
[2021-06-24 19:00:36,677: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/site-packages/pulumi/automation/_server.py", line 65, in Run
[2021-06-24 19:00:36,677: WARNING/ForkPoolWorker-1] loop.run_until_complete(run_in_stack(self.program))
[2021-06-24 19:00:36,677: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
[2021-06-24 19:00:36,678: WARNING/ForkPoolWorker-1] return future.result()
[2021-06-24 19:00:36,678: WARNING/ForkPoolWorker-1] concurrent.futures._base.CancelledError
[2021-06-24 19:00:36,678: WARNING/ForkPoolWorker-1] error: an unhandled error occurred: python inline source runtime error:
[2021-06-24 19:00:36,678: WARNING/ForkPoolWorker-1] Traceback (most recent call last):
[2021-06-24 19:00:36,678: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/site-packages/pulumi/automation/_server.py", line 65, in Run
[2021-06-24 19:00:36,678: WARNING/ForkPoolWorker-1] loop.run_until_complete(run_in_stack(self.program))
[2021-06-24 19:00:36,678: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
[2021-06-24 19:00:36,678: WARNING/ForkPoolWorker-1] return future.result()
[2021-06-24 19:00:36,678: WARNING/ForkPoolWorker-1] concurrent.futures._base.CancelledError
```

**Comment by komalali** [comment]
@manojlds is that the entire stack trace? It doesn't look complete. Or if it is there's something different going on here. Can you please describe your setup in more detail? What is running in the celery tasks? When do you see these errors? Is this actually the entire error?

**Comment by sy-bee** [comment]
We are seeing this error in our application which is built using FastAPI and Pulumi Automations API. We also run our FastAPI uvicorn application with New Relic agent via `newrelic-admin`. Apparently New Relic agent maintains it's event loop as well which sometimes causes an issue with the exception like this (apologies for the wrapped text):
```
    pulumi:pulumi:Stack some_pulumi_stack running error: an unhandled error occurred: python inline source runtime error: Task <Task pending name='Task-645543' coro=<run_in_stack() running at /usr/local/lib/python3.10/site-packages/pulumi/runtime/stack.py:126> cb=[remove_from_cache() at /usr/local/lib/python3.10/site-packages/newrelic/hooks/coroutines_asyncio.py:20, _run_until_complete_cb() at /usr/local/lib/python3.10/asyncio/base_events.py:184]> got Future <Task pending name='Task-645248' coro=<invoke.<locals>.do_invoke() running at /usr/local/lib/python3.10/site-packages/pulumi/runtime/invoke.py:85> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[remove_from_cache() at /usr/local/lib/python3.10/site-packages/newrelic/hooks/coroutines_asyncio.py:20, Task.task_wakeup()]> attached to a different loop
```

**Comment by t0yv0** [comment]
🚢
