### ISSUE TITLE
Unable to mock StackReference in tests

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#6861]
It seems something changed in 3.0 that breaks when attempting to mock `StackReference` in a test.

## Current behavior

Tests fail with this error:

```
DEBUG    root:mocks.py:227 exception when preparing or executing rpc: Traceback (most recent call last):
  File "/home/user1/.local/share/virtualenvs/my-app/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 376, in do_read
    resp = await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user1/.local/share/virtualenvs/my-app/python3.9/site-packages/pulumi/runtime/resource.py", line 371, in do_rpc_call
    return monitor.ReadResource(req)
  File "/home/user1/.local/share/virtualenvs/my-app/python3.9/site-packages/pulumi/runtime/mocks.py", line 174, in ReadResource
    custom=request.custom or False)
AttributeError: custom
```

## Steps to reproduce

TBD

**Comment by stack72** [comment]
Do you have any code that worked before that we can trace here?

**Comment by komalali** [comment]
@stack72 the user provided an example in slack which I have used as a test case in the resolving PR: https://github.com/pulumi/pulumi/pull/6863
