### ISSUE TITLE
Function serialization seems to execute code unexpectedly

### ISSUE THREAD

**Issue by kfirba** [pulumi/pulumi#6908]
Hey,

I'm trying to serialize a function that refers to a TypeORM entity that uses the TypeORM Active Record pattern.
For some reason, Pulumi just fails to serialize such an entity. It looks like Pulumi attempts to run some code behind the scenes for that entity which triggers an attempt to retrieve a connection to the database.

The code I have is very simple and easy to reproduce:

 ```ts
import * as pulumi from '@pulumi/pulumi';
import { BaseEntity } from 'typeorm';

(async () => {
  const val = await pulumi.runtime.serializeFunction(foo);
  console.log(val);
})();

class FooEntity extends BaseEntity {
  readonly id: string;
}

function foo() {
  const a = FooEntity;
}
```

When trying to execute this code the returned error message is:

>    error: Running program '/Users/kfir/code/integrations/features/xxx' failed with an unhandled exception:
    ConnectionNotFoundError: Connection "default" was not found.
        at new ConnectionNotFoundError (/Users/kfir/code/integrations/src/error/ConnectionNotFoundError.ts:8:9)
        at ConnectionManager.get (/Users/kfir/code/integrations/src/connection/ConnectionManager.ts:40:19)
        at Object.getConnection (/Users/kfir/code/integrations/src/index.ts:252:35)
        at Function.BaseEntity.getRepository (/Users/kfir/code/integrations/src/repository/BaseEntity.ts:99:72)
        at Function.get (/Users/kfir/code/integrations/src/repository/BaseEntity.ts:109:21)
        at /Users/kfir/code/integrations/features/xxx/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:1086:19
        at Generator.next (<anonymous>)
        at /Users/kfir/code/integrations/features/xxx/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/kfir/code/integrations/features/xxx/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:17:12)

## Expected behavior

Pulumi should just “copy-paste” the code without trying to execute any of it.

## Current behavior

Pulumi somehow triggers some code under the hood that attempts to retrieve a connection and fails.

## Steps to reproduce

1. Create a new aws-typescript project (or really any typescript project)
2. Install NPM dependencies: `npm install typeorm`
3. Place the following code inside your `index.ts` file and try to execute it with `pulumi up`:
```ts
import * as pulumi from '@pulumi/pulumi';
import { BaseEntity } from 'typeorm';

(async () => {
  const val = await pulumi.runtime.serializeFunction(foo);
  console.log(val);
})();

class FooEntity extends BaseEntity {
  readonly id: string;
}

function foo() {
  const a = FooEntity;
}
```
## Affected Feature
https://www.pulumi.com/docs/intro/concepts/function-serialization/#function-serialization

**Comment by kfirba** [comment]
I have completely updated this issue with a much more minimal reproduction of the issue.
