### ISSUE TITLE
panic: fatal: An assertion has failed

### ISSUE THREAD

**Issue by pquerna** [pulumi/pulumi#6934]
## Expected behavior
Ran `pulumi up` with no pending changes, a panic occurs.

## Current behavior

```
$ pulumi up
Please choose a stack, or create a new one: redacted
Previewing update (redacted)

View Live: https://app.pulumi.com/redacted

     Type                 Name                          Plan
     pulumi:pulumi:Stack  redacted-dev

Resources:
    19 unchanged

Do you want to perform this update? yes
Updating (redacted/dev)

View Live: https://app.pulumi.com/redacted

     Type                 Name                          Status
     pulumi:pulumi:Stack  redacted-dev

panic: fatal: An assertion has failed

goroutine 249 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20210422-70582-1bpvlru/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
	/private/tmp/pulumi-20210422-70582-1bpvlru/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v3/engine.printPropertyValue(0xc0005d41b0, 0x57cce00, 0xc001da9050, 0x0, 0x1, 0x5932853, 0x4, 0x0)
	/private/tmp/pulumi-20210422-70582-1bpvlru/pkg/engine/diff.go:511 +0x1485
github.com/pulumi/pulumi/pkg/v3/engine.GetResourceOutputsPropertiesString(0x5932853, 0x4, 0xc0005bd1a0, 0x5b, 0xc000c37488, 0x13, 0xc001dae000, 0xc001dae090, 0xc001dae120, 0x0, ...)
	/private/tmp/pulumi-20210422-70582-1bpvlru/pkg/engine/diff.go:408 +0x4c6
github.com/pulumi/pulumi/pkg/v3/backend/display.(*ProgressDisplay).printOutputs(0xc001622780)
	/private/tmp/pulumi-20210422-70582-1bpvlru/pkg/backend/display/progress.go:901 +0x146
github.com/pulumi/pulumi/pkg/v3/backend/display.(*ProgressDisplay).processEndSteps(0xc001622780)
	/private/tmp/pulumi-20210422-70582-1bpvlru/pkg/backend/display/progress.go:739 +0x32e
github.com/pulumi/pulumi/pkg/v3/backend/display.(*ProgressDisplay).processEvents(0xc001622780, 0xc0015efae0, 0xc0009cb260)
	/private/tmp/pulumi-20210422-70582-1bpvlru/pkg/backend/display/progress.go:1199 +0x11f
github.com/pulumi/pulumi/pkg/v3/backend/display.ShowProgressEvents.func1(0xc001622780, 0xc0015efae0, 0xc0009cb260, 0xc0009cb3e0)
	/private/tmp/pulumi-20210422-70582-1bpvlru/pkg/backend/display/progress.go:343 +0x3f
created by github.com/pulumi/pulumi/pkg/v3/backend/display.ShowProgressEvents
	/private/tmp/pulumi-20210422-70582-1bpvlru/pkg/backend/display/progress.go:342 +0x529
```
## Steps to reproduce

Maybe related to https://github.com/pulumi/pulumi/issues/6816 but has different call stack after printPropertyValue

**Comment by stack72** [comment]
Hi @pquerna 

Please can you tell us what version of Pulumi and any associated providers are included with the stack and what backend you are using?

Thanks

Paul

**Comment by pquerna** [comment]
- writing go
- only provider in the stack is AWS - I'm just creating a VPC, RouteTable, InternetGateway, Subnet, etc.
- backend is pulumi.com

**Comment by pquerna** [comment]
This also affects the ability to run `pulumi destroy` - it panics before I can destroy :(

**Comment by pquerna** [comment]
Found out after some looking, I stored a whole object instead of an ID in my output of this stack:
```
{
  "c1:route_table_public_id": {
    "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
    "id": "rtb-0af55d33456fa1dda",
    "packageVersion": "",
    "urn": "urn:pulumi:dev::c1-demo-02-managed-infra::aws:ec2/routeTable:RouteTable::route-table-public"
  },
  "c1:subnet_private_a": "subnet-00c86a6bcef6240e2",
  "c1:subnet_private_b": "subnet-070db5c2998797fb5",
  "c1:subnet_public_a": "subnet-0dc7aa9e855c126e6",
  "c1:subnet_public_b": "subnet-0281efe209631bbd9",
  "c1:vpc_id": "vpc-0271db1385e1dc802"
}
```

In my code I was exporting the route table object, instead of its ID.  Changing to the ID "fixed" my stack:
```
 func exportRouteTablePublic(ctx *pulumi.Context, rt *ec2.RouteTable) {
-       ctx.Export(exportRouteTablePublicID, rt)
+       ctx.Export(exportRouteTablePublicID, rt.ID())
 }
 ```

However I had to full destroy + up -- I didn't see a way to edit just the output easily to work around that.

**Comment by lukehoban** [comment]
@pquerna great that you figured out how to workaround - thanks for those additional details. There is still a bug here though - the original code should work as you expected.
