### ISSUE TITLE
Tests fail to run from source due to external integration dependencies

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi#6952]
I'm working through https://github.com/pulumi/pulumi/issues/4963#issuecomment-827312020 and at the point where I can build everything but some tests fail to run due to external integration dependencies.

## Expected behavior
All tests should pass out of the box, given environment specific configuration if required.

## Current behavior
```
make ensure
...
make only_build
...
make
...
  480 passing (4m)
  1 failing
  1) LocalWorkspace nested_config:
     CommandError: code: 255
 stdout: 
 stderr: error: could not create stack: [404] Not Found: Organization 'pulumi-test' not found
 err?: 
      at Object.createCommandError (bin/automation/errors.js:71:17)
      at ChildProcess.<anonymous> (bin/automation/cmd.js:63:40)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
Makefile:45: recipe for target 'istanbul_tests' failed
make[1]: *** [istanbul_tests] Error 1
make[1]: Leaving directory '/workspaces/pulumi/sdk/nodejs'
build/common.mk:206: recipe for target 'sdk/nodejs_default' failed
make: *** [sdk/nodejs_default] Error 2
```

## Steps to reproduce

1. from linux distro (ubuntu 20.04) in wsl2 via window terminal
2. `git clone https://github.com/pulumi/pulumi.git`
2. `cd pulumi`
3. `code .`
4. add `.devcontainer` folder from issue comment above
5. re-open in remote container
6. `make ensure` ... succeeds
7. `make only_build` ... succeeds
8. `make` ... fails as above

**Comment by EvanBoyle** [comment]
The test org should be controlled via the environment variable `PULUMI_TEST_ORG`. Looks like this change was missed in the python and nodejs automation api implementations. 

https://github.com/pulumi/pulumi/blob/c3dc2d54abf85da811de0fbaa5e98f22b0f054c8/sdk/go/auto/local_workspace_test.go#L1772

**Comment by EvanBoyle** [comment]
Also, the test org appears to be used inconsistently in node for some tests.

**Comment by gitfool** [comment]
@EvanBoyle I pulled your latest changes and added the `PULUMI_TEST_ORG` env var to `.devcontainer/devcontainer.json` but the nodejs tests now fail with:
```
...
480 passing (4m)
  1 failing

  1) LocalWorkspace nested_config:
     CommandError: code: 255
 stdout: 
 stderr: error: could not decrypt configuration value: [400] Message authentication failed

 err?: 

      at Object.createCommandError (bin/automation/errors.js:71:17)
      at ChildProcess.<anonymous> (bin/automation/cmd.js:63:40)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

**Comment by gitfool** [comment]
@komalali I pulled your latest changes and the build gets further but fails building the python sdk:
```
LINT:
MYPYPATH=./stubs pipenv run mypy ./lib/pulumi --config-file=mypy.ini
lib/pulumi/output.py:329: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
Found 1 error in 1 file (checked 63 source files)
Makefile:30: recipe for target 'lint' failed
```
<details>
  <summary>log extract</summary>

```
make[1]: Entering directory '/workspaces/pulumi/sdk/python'
=================
Pulumi Python SDK
=================
BUILD:
rm -rf ./env/src && cp -R ./lib/. ./env/src/
sed -i.bak "s/\${VERSION}/3.2.0a1620747681/g" ./env/src/setup.py && rm ./env/src/setup.py.bak
cp ../../README.md ./env/src
cd ./env/src && pipenv run python setup.py build bdist_wheel --universal
running build
running build_py
creating build
creating build/lib
creating build/lib/pulumi
copying pulumi/stack_reference.py -> build/lib/pulumi
copying pulumi/log.py -> build/lib/pulumi
copying pulumi/errors.py -> build/lib/pulumi
copying pulumi/resource.py -> build/lib/pulumi
copying pulumi/config.py -> build/lib/pulumi
copying pulumi/_async.py -> build/lib/pulumi
copying pulumi/_types.py -> build/lib/pulumi
copying pulumi/output.py -> build/lib/pulumi
copying pulumi/_utils.py -> build/lib/pulumi
copying pulumi/asset.py -> build/lib/pulumi
copying pulumi/invoke.py -> build/lib/pulumi
copying pulumi/__init__.py -> build/lib/pulumi
copying pulumi/metadata.py -> build/lib/pulumi
creating build/lib/pulumi/automation
copying pulumi/automation/_stack_settings.py -> build/lib/pulumi/automation
copying pulumi/automation/_local_workspace.py -> build/lib/pulumi/automation
copying pulumi/automation/_workspace.py -> build/lib/pulumi/automation
copying pulumi/automation/errors.py -> build/lib/pulumi/automation
copying pulumi/automation/_server.py -> build/lib/pulumi/automation
copying pulumi/automation/events.py -> build/lib/pulumi/automation
copying pulumi/automation/_minimum_version.py -> build/lib/pulumi/automation
copying pulumi/automation/_cmd.py -> build/lib/pulumi/automation
copying pulumi/automation/_stack.py -> build/lib/pulumi/automation
copying pulumi/automation/_config.py -> build/lib/pulumi/automation
copying pulumi/automation/_output.py -> build/lib/pulumi/automation
copying pulumi/automation/__init__.py -> build/lib/pulumi/automation
copying pulumi/automation/_project_settings.py -> build/lib/pulumi/automation
creating build/lib/pulumi/dynamic
copying pulumi/dynamic/__main__.py -> build/lib/pulumi/dynamic
copying pulumi/dynamic/dynamic.py -> build/lib/pulumi/dynamic
copying pulumi/dynamic/__init__.py -> build/lib/pulumi/dynamic
creating build/lib/pulumi/policy
copying pulumi/policy/__main__.py -> build/lib/pulumi/policy
copying pulumi/policy/__init__.py -> build/lib/pulumi/policy
creating build/lib/pulumi/provider
copying pulumi/provider/provider.py -> build/lib/pulumi/provider
copying pulumi/provider/__init__.py -> build/lib/pulumi/provider
copying pulumi/provider/server.py -> build/lib/pulumi/provider
creating build/lib/pulumi/runtime
copying pulumi/runtime/sync_await.py -> build/lib/pulumi/runtime
copying pulumi/runtime/stack.py -> build/lib/pulumi/runtime
copying pulumi/runtime/resource.py -> build/lib/pulumi/runtime
copying pulumi/runtime/config.py -> build/lib/pulumi/runtime
copying pulumi/runtime/rpc_manager.py -> build/lib/pulumi/runtime
copying pulumi/runtime/known_types.py -> build/lib/pulumi/runtime
copying pulumi/runtime/mocks.py -> build/lib/pulumi/runtime
copying pulumi/runtime/settings.py -> build/lib/pulumi/runtime
copying pulumi/runtime/invoke.py -> build/lib/pulumi/runtime
copying pulumi/runtime/rpc.py -> build/lib/pulumi/runtime
copying pulumi/runtime/__init__.py -> build/lib/pulumi/runtime
copying pulumi/runtime/_json.py -> build/lib/pulumi/runtime
creating build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/engine_pb2.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/resource_pb2_grpc.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/status_pb2_grpc.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/provider_pb2_grpc.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/analyzer_pb2_grpc.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/plugin_pb2.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/errors_pb2.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/language_pb2.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/provider_pb2.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/status_pb2.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/analyzer_pb2.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/language_pb2_grpc.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/plugin_pb2_grpc.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/errors_pb2_grpc.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/resource_pb2.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/engine_pb2_grpc.py -> build/lib/pulumi/runtime/proto
copying pulumi/runtime/proto/__init__.py -> build/lib/pulumi/runtime/proto
copying pulumi/py.typed -> build/lib/pulumi
warning: build_py: byte-compiling is disabled, skipping.

running bdist_wheel
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/pulumi
copying build/lib/pulumi/stack_reference.py -> build/bdist.linux-x86_64/wheel/pulumi
creating build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/_stack_settings.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/_local_workspace.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/_workspace.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/errors.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/_server.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/events.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/_minimum_version.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/_cmd.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/_stack.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/_config.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/_output.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/__init__.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/automation/_project_settings.py -> build/bdist.linux-x86_64/wheel/pulumi/automation
copying build/lib/pulumi/log.py -> build/bdist.linux-x86_64/wheel/pulumi
copying build/lib/pulumi/errors.py -> build/bdist.linux-x86_64/wheel/pulumi
copying build/lib/pulumi/resource.py -> build/bdist.linux-x86_64/wheel/pulumi
copying build/lib/pulumi/config.py -> build/bdist.linux-x86_64/wheel/pulumi
copying build/lib/pulumi/_async.py -> build/bdist.linux-x86_64/wheel/pulumi
copying build/lib/pulumi/_types.py -> build/bdist.linux-x86_64/wheel/pulumi
creating build/bdist.linux-x86_64/wheel/pulumi/dynamic
copying build/lib/pulumi/dynamic/__main__.py -> build/bdist.linux-x86_64/wheel/pulumi/dynamic
copying build/lib/pulumi/dynamic/dynamic.py -> build/bdist.linux-x86_64/wheel/pulumi/dynamic
copying build/lib/pulumi/dynamic/__init__.py -> build/bdist.linux-x86_64/wheel/pulumi/dynamic
creating build/bdist.linux-x86_64/wheel/pulumi/policy
copying build/lib/pulumi/policy/__main__.py -> build/bdist.linux-x86_64/wheel/pulumi/policy
copying build/lib/pulumi/policy/__init__.py -> build/bdist.linux-x86_64/wheel/pulumi/policy
copying build/lib/pulumi/output.py -> build/bdist.linux-x86_64/wheel/pulumi
copying build/lib/pulumi/_utils.py -> build/bdist.linux-x86_64/wheel/pulumi
copying build/lib/pulumi/asset.py -> build/bdist.linux-x86_64/wheel/pulumi
copying build/lib/pulumi/invoke.py -> build/bdist.linux-x86_64/wheel/pulumi
creating build/bdist.linux-x86_64/wheel/pulumi/provider
copying build/lib/pulumi/provider/provider.py -> build/bdist.linux-x86_64/wheel/pulumi/provider
copying build/lib/pulumi/provider/__init__.py -> build/bdist.linux-x86_64/wheel/pulumi/provider
copying build/lib/pulumi/provider/server.py -> build/bdist.linux-x86_64/wheel/pulumi/provider
creating build/bdist.linux-x86_64/wheel/pulumi/runtime
copying build/lib/pulumi/runtime/sync_await.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime
copying build/lib/pulumi/runtime/stack.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime
copying build/lib/pulumi/runtime/resource.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime
copying build/lib/pulumi/runtime/config.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime
copying build/lib/pulumi/runtime/rpc_manager.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime
copying build/lib/pulumi/runtime/known_types.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime
creating build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/engine_pb2.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/resource_pb2_grpc.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/status_pb2_grpc.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/provider_pb2_grpc.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/analyzer_pb2_grpc.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/plugin_pb2.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/errors_pb2.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/language_pb2.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/provider_pb2.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/status_pb2.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/analyzer_pb2.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/language_pb2_grpc.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/plugin_pb2_grpc.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/errors_pb2_grpc.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/resource_pb2.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/engine_pb2_grpc.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/proto/__init__.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime/proto
copying build/lib/pulumi/runtime/mocks.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime
copying build/lib/pulumi/runtime/settings.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime
copying build/lib/pulumi/runtime/invoke.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime
copying build/lib/pulumi/runtime/rpc.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime
copying build/lib/pulumi/runtime/__init__.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime
copying build/lib/pulumi/runtime/_json.py -> build/bdist.linux-x86_64/wheel/pulumi/runtime
copying build/lib/pulumi/__init__.py -> build/bdist.linux-x86_64/wheel/pulumi
copying build/lib/pulumi/py.typed -> build/bdist.linux-x86_64/wheel/pulumi
copying build/lib/pulumi/metadata.py -> build/bdist.linux-x86_64/wheel/pulumi
warning: install_lib: byte-compiling is disabled, skipping.

running install_egg_info
running egg_info
creating pulumi.egg-info
writing pulumi.egg-info/PKG-INFO
writing dependency_links to pulumi.egg-info/dependency_links.txt
writing requirements to pulumi.egg-info/requires.txt
writing top-level names to pulumi.egg-info/top_level.txt
writing manifest file 'pulumi.egg-info/SOURCES.txt'
reading manifest file 'pulumi.egg-info/SOURCES.txt'
writing manifest file 'pulumi.egg-info/SOURCES.txt'
Copying pulumi.egg-info to build/bdist.linux-x86_64/wheel/pulumi-3.2.0a1620747681-py3.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/pulumi-3.2.0a1620747681.dist-info/WHEEL
creating 'dist/pulumi-3.2.0a1620747681-py2.py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'pulumi/__init__.py'
adding 'pulumi/_async.py'
adding 'pulumi/_types.py'
adding 'pulumi/_utils.py'
adding 'pulumi/asset.py'
adding 'pulumi/config.py'
adding 'pulumi/errors.py'
adding 'pulumi/invoke.py'
adding 'pulumi/log.py'
adding 'pulumi/metadata.py'
adding 'pulumi/output.py'
adding 'pulumi/py.typed'
adding 'pulumi/resource.py'
adding 'pulumi/stack_reference.py'
adding 'pulumi/automation/__init__.py'
adding 'pulumi/automation/_cmd.py'
adding 'pulumi/automation/_config.py'
adding 'pulumi/automation/_local_workspace.py'
adding 'pulumi/automation/_minimum_version.py'
adding 'pulumi/automation/_output.py'
adding 'pulumi/automation/_project_settings.py'
adding 'pulumi/automation/_server.py'
adding 'pulumi/automation/_stack.py'
adding 'pulumi/automation/_stack_settings.py'
adding 'pulumi/automation/_workspace.py'
adding 'pulumi/automation/errors.py'
adding 'pulumi/automation/events.py'
adding 'pulumi/dynamic/__init__.py'
adding 'pulumi/dynamic/__main__.py'
adding 'pulumi/dynamic/dynamic.py'
adding 'pulumi/policy/__init__.py'
adding 'pulumi/policy/__main__.py'
adding 'pulumi/provider/__init__.py'
adding 'pulumi/provider/provider.py'
adding 'pulumi/provider/server.py'
adding 'pulumi/runtime/__init__.py'
adding 'pulumi/runtime/_json.py'
adding 'pulumi/runtime/config.py'
adding 'pulumi/runtime/invoke.py'
adding 'pulumi/runtime/known_types.py'
adding 'pulumi/runtime/mocks.py'
adding 'pulumi/runtime/resource.py'
adding 'pulumi/runtime/rpc.py'
adding 'pulumi/runtime/rpc_manager.py'
adding 'pulumi/runtime/settings.py'
adding 'pulumi/runtime/stack.py'
adding 'pulumi/runtime/sync_await.py'
adding 'pulumi/runtime/proto/__init__.py'
adding 'pulumi/runtime/proto/analyzer_pb2.py'
adding 'pulumi/runtime/proto/analyzer_pb2_grpc.py'
adding 'pulumi/runtime/proto/engine_pb2.py'
adding 'pulumi/runtime/proto/engine_pb2_grpc.py'
adding 'pulumi/runtime/proto/errors_pb2.py'
adding 'pulumi/runtime/proto/errors_pb2_grpc.py'
adding 'pulumi/runtime/proto/language_pb2.py'
adding 'pulumi/runtime/proto/language_pb2_grpc.py'
adding 'pulumi/runtime/proto/plugin_pb2.py'
adding 'pulumi/runtime/proto/plugin_pb2_grpc.py'
adding 'pulumi/runtime/proto/provider_pb2.py'
adding 'pulumi/runtime/proto/provider_pb2_grpc.py'
adding 'pulumi/runtime/proto/resource_pb2.py'
adding 'pulumi/runtime/proto/resource_pb2_grpc.py'
adding 'pulumi/runtime/proto/status_pb2.py'
adding 'pulumi/runtime/proto/status_pb2_grpc.py'
adding 'pulumi-3.2.0a1620747681.dist-info/METADATA'
adding 'pulumi-3.2.0a1620747681.dist-info/WHEEL'
adding 'pulumi-3.2.0a1620747681.dist-info/top_level.txt'
adding 'pulumi-3.2.0a1620747681.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
go install -ldflags "-X github.com/pulumi/pulumi/sdk/v3/go/common/version.Version=3.2.0-alpha.1620747681+3ef2648f" github.com/pulumi/pulumi/sdk/v3/python/cmd/pulumi-language-python
INSTALL:
cp ./cmd/pulumi-language-python-exec "/opt/pulumi/bin"
cp ./dist/pulumi-resource-pulumi-python "/opt/pulumi/bin"
cp ./dist/pulumi-analyzer-policy-python "/opt/pulumi/bin"
GOBIN=/opt/pulumi/bin go install \
          -ldflags "-X github.com/pulumi/pulumi/sdk/v3/go/common/version.Version=3.2.0-alpha.1620747681+3ef2648f" github.com/pulumi/pulumi/sdk/v3/python/cmd/pulumi-language-python
LINT:
MYPYPATH=./stubs pipenv run mypy ./lib/pulumi --config-file=mypy.ini
lib/pulumi/output.py:329: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
Found 1 error in 1 file (checked 63 source files)
Makefile:30: recipe for target 'lint' failed
make[1]: *** [lint] Error 1
make[1]: Leaving directory '/workspaces/pulumi/sdk/python'
build/common.mk:206: recipe for target 'sdk/python_default' failed
make: *** [sdk/python_default] Error 2
```
</details>

**Comment by komalali** [comment]
@gitfool hmm that's super weird. This is what I see:

```
LINT:
MYPYPATH=./stubs pipenv run mypy ./lib/pulumi --config-file=mypy.ini
Success: no issues found in 63 source files
pipenv run pylint ./lib/pulumi --rcfile=.pylintrc

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

It's also odd that it's pointing to line 329, because that's a [comment](https://github.com/pulumi/pulumi/blob/55ecf7a81ebd95f3085cbf611b12567f855320f9/sdk/python/lib/pulumi/output.py#L329) and the line it's actually pointing to is 331 and [already has an ignore](https://github.com/pulumi/pulumi/blob/55ecf7a81ebd95f3085cbf611b12567f855320f9/sdk/python/lib/pulumi/output.py#L331)

**Comment by gitfool** [comment]
@komalali you should be able to duplicate this by using my `.devcontainer` in vs code. Perhaps I'm missing something else?

**Comment by gitfool** [comment]
@komalali I'm getting much further now, but the build fails in the the pulumi sdk:
```
==========
Pulumi SDK
==========
BUILD:
GENERATE:
echo "Generate static assets bundle for docs generator"
Generate static assets bundle for docs generator
cd pkg && go generate ./codegen/docs/gen.go
cd pkg && go install -ldflags "-X github.com/pulumi/pulumi/pkg/v3/version.Version=3.2.0-alpha.1620844228+be818318.dirty" github.com/pulumi/pulumi/pkg/v3/cmd/pulumi
INSTALL:
cd pkg && GOBIN=/opt/pulumi/bin go install -ldflags "-X github.com/pulumi/pulumi/pkg/v3/version.Version=3.2.0-alpha.1620844228+be818318.dirty" github.com/pulumi/pulumi/pkg/v3/cmd/pulumi
LINT:
for DIR in "pkg" "sdk" "tests" ; do \
        pushd $DIR ; golangci-lint run -c ../.golangci.yml --timeout 5m ; popd ; \
done
/workspaces/pulumi/pkg /workspaces/pulumi
/workspaces/pulumi
/workspaces/pulumi/sdk /workspaces/pulumi
/workspaces/pulumi
/workspaces/pulumi/tests /workspaces/pulumi
/workspaces/pulumi
TEST FAST:
cd pkg && PATH="/opt/pulumi/bin:/opt/pulumi:/opt/pulumi/bin:/go/bin:/usr/local/go/bin:/go/bin:/usr/local/go/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" go test -short -count=1 -cover -tags=all -timeout 1h -parallel 10 github.com/pulumi/pulumi/pkg/v3/backend github.com/pulumi/pulumi/pkg/v3/backend/display github.com/pulumi/pulumi/pkg/v3/backend/filestate github.com/pulumi/pulumi/pkg/v3/backend/httpstate github.com/pulumi/pulumi/pkg/v3/backend/httpstate/client github.com/pulumi/pulumi/pkg/v3/backend/state github.com/pulumi/pulumi/pkg/v3/cmd/pulumi github.com/pulumi/pulumi/pkg/v3/codegen github.com/pulumi/pulumi/pkg/v3/codegen/docs github.com/pulumi/pulumi/pkg/v3/codegen/dotnet github.com/pulumi/pulumi/pkg/v3/codegen/go github.com/pulumi/pulumi/pkg/v3/codegen/hcl2 github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/model/format github.com/pulumi/pulumi/pkg/v3/codegen/hcl2/syntax github.com/pulumi/pulumi/pkg/v3/codegen/importer github.com/pulumi/pulumi/pkg/v3/codegen/internal/test github.com/pulumi/pulumi/pkg/v3/codegen/nodejs github.com/pulumi/pulumi/pkg/v3/codegen/python github.com/pulumi/pulumi/pkg/v3/codegen/schema github.com/pulumi/pulumi/pkg/v3/engine github.com/pulumi/pulumi/pkg/v3/engine/lifeycletest github.com/pulumi/pulumi/pkg/v3/graph github.com/pulumi/pulumi/pkg/v3/graph/dotconv github.com/pulumi/pulumi/pkg/v3/operations github.com/pulumi/pulumi/pkg/v3/resource/analyzer github.com/pulumi/pulumi/pkg/v3/resource/deploy github.com/pulumi/pulumi/pkg/v3/resource/deploy/deploytest github.com/pulumi/pulumi/pkg/v3/resource/deploy/providers github.com/pulumi/pulumi/pkg/v3/resource/edit github.com/pulumi/pulumi/pkg/v3/resource/graph github.com/pulumi/pulumi/pkg/v3/resource/provider github.com/pulumi/pulumi/pkg/v3/resource/stack github.com/pulumi/pulumi/pkg/v3/secrets github.com/pulumi/pulumi/pkg/v3/secrets/b64 github.com/pulumi/pulumi/pkg/v3/secrets/cloud github.com/pulumi/pulumi/pkg/v3/secrets/passphrase github.com/pulumi/pulumi/pkg/v3/secrets/service github.com/pulumi/pulumi/pkg/v3/testing/integration github.com/pulumi/pulumi/pkg/v3/util/cancel github.com/pulumi/pulumi/pkg/v3/util/testutil github.com/pulumi/pulumi/pkg/v3/util/tracing github.com/pulumi/pulumi/pkg/v3/util/validation github.com/pulumi/pulumi/pkg/v3/version
ok      github.com/pulumi/pulumi/pkg/v3/backend 0.104s  coverage: 33.4% of statements
ok      github.com/pulumi/pulumi/pkg/v3/backend/display 0.164s  coverage: 4.3% of statements
ok      github.com/pulumi/pulumi/pkg/v3/backend/filestate       0.112s  coverage: 2.6% of statements
ok      github.com/pulumi/pulumi/pkg/v3/backend/httpstate       0.064s  coverage: 1.0% of statements
?       github.com/pulumi/pulumi/pkg/v3/backend/httpstate/client        [no test files]
?       github.com/pulumi/pulumi/pkg/v3/backend/state   [no test files]
ok      github.com/pulumi/pulumi/pkg/v3/cmd/pulumi      0.904s  coverage: 2.9% of statements
ok      github.com/pulumi/pulumi/pkg/v3/codegen 0.073s  coverage: 38.1% of statements
--- FAIL: TestGeneratePackage (339.25s)
    --- FAIL: TestGeneratePackage/External_resource_schema (339.17s)
        gen_test.go:553: 
                Error Trace:    gen_test.go:553
                Error:          Received unexpected error:
                                stream error: stream ID 3; PROTOCOL_ERROR
                                untarring file /home/user/.pulumi/plugins/resource-kubernetes-v2.6.3/pulumi-resource-kubernetes
...
```
(Use my latest `.devcontainer`)

**Comment by komalali** [comment]
Hey @gitfool, I'm not sure this is the same issue anymore. This issue was specifically about the external dependencies on the integration tests, and we have fixed those. 

That's awesome that you wanna contribute a devcontainer, but I think you're going to have to do the debugging to make it work. Thanks!

**Comment by gitfool** [comment]
@komalali indeed, this is now a more general "how do I build pulumi successfully" issue.

I guess I'll have to abandon the effort at this point in time as I don't exactly have the time to debug a build I know little about and that should just work out of the box. 😞

**Comment by jaxxstorm** [comment]
@gitfool if you just want to build Pulumi, `make install` should work without running the integration tests

**Comment by gitfool** [comment]
@jaxxstorm okay, thanks; although I was hoping to create a `devcontainer` for anyone to use that could `make` everything, including tests for obvious reasons. They take too long to run all the time but are useful to catch issues, especially before sending a PR.

I'd expect any tests in the default target to work at least, but maybe that's not valid due to undocumented repo assumptions around integration requirements that are internal to pulumi only. It's hard to know if that's why a test is failing without digging into it, which usually requires domain knowledge, whether it be for a build system, particular language and tooling, something environmental or beyond. This is an awesome project but it has a complicated "build".

A curated `devcontainer` provides a newbie friendly sandbox from which to experiment by encoding all the requirements without needing to mess with your own environment. That's a great entry point and should not be under valued.

**Comment by komalali** [comment]
Interestingly, I can't replicate this error at all in the `devcontainer`. My tests all pass.
<img width="1162" alt="Screen Shot 2021-05-13 at 10 21 48 AM" src="https://user-images.githubusercontent.com/24326455/118161945-09dfcd00-b3d5-11eb-8aaf-14a8bca70407.png">

**Comment by gitfool** [comment]
@komalali third time lucky, with a `git clean` thrown in for good measure, seemed to do the trick and it completed for me too! 🎉
