### ISSUE TITLE
Can't read pulumi resource plugin

### ISSUE THREAD

**Issue by fsodano** [pulumi/pulumi#7014]
When I run pulumi up I get a panic, see below:

If I run it again, then I get a different error:
```
  pulumi:providers:azure (default_4_1_0):
    error: could not read plugin [C:\Users\FabricioSodano\.pulumi\plugins\resource-azure-v4.1.0\pulumi-resource-azure.exe] stdout: EOF
```
The plugin is there.
pulumi plugin install doesn't do anything.
pulumi plugin rm and then installing them again produces the same error.

```
'dotnet build -nologo .' completed successfully
 
Exception 0xc0000005 0x0 0x7ffd826b0fff 0x232cf5e0000
 
PC=0x232cf5e0000
 
syscall.loadsystemlibrary(0xc00004e1c8, 0xc000048980, 0xc000048980, 0x20)
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/syscall_windows.go:278 +0xe7
 
syscall.LoadDLL(0x6940fa4, 0xb, 0xc00007e000, 0xc000060000, 0xc0005bf370)
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/syscall/dll_windows.go:83 +0x16a
 
syscall.(*LazyDLL).Load(0xc00008c140, 0x0, 0x0)
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/syscall/dll_windows.go:247 +0xc8
 
syscall.(*LazyProc).Find(0xc00005b7d0, 0x0, 0x0)
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/syscall/dll_windows.go:302 +0xbf
 
syscall.(*LazyProc).mustFind(...)
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/syscall/dll_windows.go:320
 
syscall.(*LazyProc).Addr(...)
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/syscall/dll_windows.go:329
 
syscall.GetUserProfileDirectory(0x1d0, 0xc0007164e0, 0xc0005bf450, 0xc0007164e0, 0x232a9ec9f20)
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/syscall/zsyscall_windows.go:1218 +0x3e
 
syscall.Token.GetUserProfileDirectory(0x1d0, 0xc000048940, 0x34, 0x0, 0x0)
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/syscall/security_windows.go:368 +0x8f
 
os/user.current(0x0, 0x0, 0x0)
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/os/user/lookup_windows.go:217 +0x1cf
 
os/user.Current.func1()
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/os/user/lookup.go:15 +0x29
 
sync.(*Once).doSlow(0xad6e300, 0x6b52348)
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/sync/once.go:68 +0xf7
 
sync.(*Once).Do(...)
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/sync/once.go:59
 
os/user.Current(0xc000236190, 0x8, 0x692dbec)
 
	/opt/hostedtoolcache/go/1.16.3/x64/src/os/user/lookup.go:15 +0x105
 
github.com/golang/glog.init.1()
 
	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog_file.go:63 +0x4b
 
goroutine 6 [select]:
 
go.opencensus.io/stats/view.(*worker).start(0xc00012ab00)
 
	/home/runner/go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:276 +0xd4
 
created by go.opencensus.io/stats/view.init.0
 
	/home/runner/go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:34 +0x72
 
goroutine 13 [chan receive]:
 
github.com/golang/glog.(*loggingT).flushDaemon(0xad6efa0)
 
	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x92
 
created by github.com/golang/glog.init.0
 
	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x27a
 
rax     0x7ffd7fb15894
 
rbx     0x7ffd7fb15892
 
rcx     0x41
 
rdi     0xffffffffffbadd11
 
rsi     0x0
 
rbp     0x0
 
rsp     0x3b591fef30
 
r8      0x0
 
r9      0x0
 
r10     0x0
 
r11     0x97c
 
r12     0xc000007a
 
r13     0x0
 
r14     0x7ffd7fb15894
 
r15     0x7ffd824b0000
 
rip     0x232cf5e0000
 
rflags  0x10202
 
cs      0x33
 
fs      0x53
 
gs      0x2b
 
default_4_0_1 (pulumi:providers:azure)
error: could not read plugin [C:\Users\FabricioSodano\.pulumi\plugins\resource-azure-v4.0.1\pulumi-resource-azure.exe] stdout: EOF
```

**Comment by fsodano** [comment]
The problem is webroot, the antivirus. Thank you @viveklak .
