### ISSUE TITLE
Pulumi C# v3.2.1 is running Output.Apply in preview

### ISSUE THREAD

**Issue by darnmason** [pulumi/pulumi#7030]
When running `pulumi up` with Azure Native I'm getting a `ResourceNotFound` error, but it's just a preview so shouldn't be executing the code that's causing the error.

## Expected behavior
I expect for a preview that the Output.Apply code block is not executed, [as per the documentation](https://www.pulumi.com/docs/intro/concepts/inputs-outputs/#apply).

## Current behavior
The Apply code block is being executed.

## Steps to reproduce
```
var functionApp = new WebApp("functionsApp", new WebAppArgs
  {
      ResourceGroupName = resGroup.Name,
      Name = "fn-uat",
      ServerFarmId = plan.Id,
      Kind = "functionapp",
  });

this.FunctionAppKey = Output.Tuple(functionApp.Name, resGroup.Name, Output.CreateSecret("")).Apply(
    t => ListWebAppHostKeys.InvokeAsync(new ListWebAppHostKeysArgs
    {
        Name = t.Item1,
        ResourceGroupName = t.Item2,
    })).Apply(result => result.MasterKey);
```

## Context (Environment)
This only reared it's head as I'm deploying a new environment for the first time. Here's the redacted log.

```
Previewing update (uat)

View Live: https://app.pulumi.com/...

     Type                                                   Name                      Plan       Info
     pulumi:pulumi:Stack                                    integrations-uat      1 error; 1 message
 ~   ├─ azure-native:web:AppServicePlan                     plan                      update     [diff: ~sku]
 +   ├─ azure-native:apimanagement:ApiManagementService     apiService                create     
 +   ├─ azure-native:sql:FirewallRule                       sqlDbFirewallAllowAzure   create     
 +   ├─ azure-native:sql:Database                           sqlDb                     create     
 +   ├─ azure-native:servicebus:Queue                       emailQueue                create     
 +   ├─ azure-native:servicebus:NamespaceAuthorizationRule  busRuleSendListen         create     
 +   ├─ azure-native:apimanagement:NamedValue               partnerPortalAppIdValue   create     
 +   ├─ azure-native:apimanagement:NamedValue               openIdConfigUrlValue      create     
 +   ├─ azure-native:apimanagement:ApiVersionSet            partnerVersionSet         create     
 +   ├─ azure-native:apimanagement:User                     partnerUser               create     
 +   ├─ azure-native:apimanagement:Logger                   apiLogger                 create     
 +   ├─ azure-native:apimanagement:Product                  partnerProduct            create     
 +   ├─ azure-native:apimanagement:Subscription             subscription              create     
 +   ├─ azure-native:web:WebApp                             functionsApp              create     
 +   ├─ azure-native:apimanagement:Api                      partnerApi                create     
 +   ├─ azure-native:apimanagement:ProductApi               partnerProductApi         create     
 +   └─ azure-native:web:WebApp                             partnerPortalApp          create     
 
Diagnostics:
  pulumi:pulumi:Stack (integrations-uat):
    project: ... | location: AustraliaEast | stack: uat | env: uat | consumption: False | production: False | (preview)
    error: Running program '/Users/.../bin/Debug/netcoreapp3.1/Infrastructure.dll' failed with an unhandled exception:
    Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="invocation of azure-native:web:listWebAppHostKeys returned an error: request failed /subscriptions/.../resourceGroups/res-uat/providers/Microsoft.Web/sites/fn-uat/host/default/listkeys: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Web/sites/fn-uat' under resource group 'res-uat' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1620789602.902369000","description":"Error received from peer ipv4:127.0.0.1:64203","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"invocation of azure-native:web:listWebAppHostKeys returned an error: request failed /subscriptions/.../resourceGroups/res-uat/providers/Microsoft.Web/sites/fn-uat/host/default/listkeys: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Web/sites/fn-uat' under resource group 'res-uat' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"","grpc_status":2}")
       at Pulumi.GrpcMonitor.InvokeAsync(InvokeRequest request)
       at Pulumi.Deployment.InvokeRawAsync(String token, InvokeArgs args, InvokeOptions options)
       at Pulumi.Deployment.InvokeAsync[T](String token, InvokeArgs args, InvokeOptions options, Boolean convertResult)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey, Boolean keepResources)
       at Pulumi.Deployment.PrepareResourceAsync(String label, Resource res, Boolean custom, Boolean remote, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args, Boolean keepResources)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.RegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Output`1.GetValueAsync()
       at Pulumi.Deployment.Logger.TryGetResourceUrnAsync(Resource resource)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.<TupleHelperAsync>g__GetData|20_0[T1,T2,T3,T4,T5,T6,T7,T8,X](Input`1 input)
       at Pulumi.Output`1.TupleHelperAsync[T1,T2,T3,T4,T5,T6,T7,T8](Input`1 item1, Input`1 item2, Input`1 item3, Input`1 item4, Input`1 item5, Input`1 item6, Input`1 item7, Input`1 item8)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeDictionaryAsync(String ctx, IDictionary dictionary, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeInputArgsAsync(String ctx, InputArgs args, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey, Boolean keepResources)
       at Pulumi.Deployment.PrepareResourceAsync(String label, Resource res, Boolean custom, Boolean remote, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.RegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Output`1.GetValueAsync()
       at Pulumi.Deployment.Logger.TryGetResourceUrnAsync(Resource resource)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop, Boolean keepResources)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey, Boolean keepResources)
       at Pulumi.Deployment.PrepareResourceAsync(String label, Resource res, Boolean custom, Boolean remote, ResourceArgs args, ResourceOptions options)
```

## Affected feature
pulumi up preview

**Comment by darnmason** [comment]
A workaround is to skip the preview.
`pulumi up -f`

**Comment by leezen** [comment]
I don't think this is a bug. In general, an `apply` will run if the value is known. I think the wording in the documentation could be improved, but the intent of the text "For example, it won’t run during a preview, when resource output values may be unknown" should emphasize the "may be unknown" part.

**Comment by darnmason** [comment]
What would be the recommended approach then to call a function like `ListWebAppHostKeys`?

The function app is not yet deployed, Pulumi by default does a preview run, the preview will always fail with my current approach.

**Comment by leezen** [comment]
You could rely on an output value that is only known after the resource exists such as `Id` which should only be known after the resource is created. Note that the code will still execute in your `preview` in subsequent updates since at that point, the property is known.

**Comment by darnmason** [comment]
I'm already passing in an unnecessary Output to the Tuple to get a side effect - which is to make the resulting Output a secret.

Maybe for this one it'd be better to just wrap it all in an `if (!Deployment.Instance.IsDryRun)`, but having these scattered throughout the code isn't nice either. I feel Pulumi should have a way to handle this naturally.

**Comment by D3-LucaPiombino** [comment]
We have encountered the same issue a lot.
Would be nice to have a way to avoid needing to piggyback on other outputs or use `Deployment.Instance.IsDryRun`.

**Comment by Frassle** [comment]
So the example in the first post I think could be written like this today:
```
this.FunctionAppKey = Output.CreateSecret(functionApp.Id).Apply(_ => // ignore the ID just use it for lifecycle control
    ListWebAppHostKeys.Invoke(new ListWebAppHostKeysInvokeArgs 
    {
        Name = functionApp.Name,
        ResourceGroupName =resGroup.Name,
    })).Apply(result => result.MasterKey);
```
Which is a little nicer but still odd having to use ID like that.

It's hard to suggest better approaches for doing this more generally without more examples.

Outputs need to run at preview time for known inputs so that you can preview resources that are created inside Applys. This is even more important when using update plans. So we can't change that behavior, although as Lee said we could probably make that a bit more clear in the docs.

**Comment by Frassle** [comment]
I wonder if this is because ID gets returned to us before the function app is _actually_ created. This probably then becomes https://github.com/pulumi/pulumi/issues/3364 to give a way to handle the not found and retry.
