### ISSUE TITLE
Uncaught error in MockMonitor.registerResourceOutputs

### ISSUE THREAD

**Issue by tenwit** [pulumi/pulumi#7042]
I am creating aws:cloudwatch:EventRuleEventSubscription resources in my ComponentResource and they cause my unit tests to abort with this error:

```
     Uncaught Error: unknown resource urn:pulumi:core::project::aws:lambda/function:Function$aws:cloudwatch:EventRuleEventSubscription::nonfiltering-ec2-start
      at MockMonitor.registerResourceOutputs (node_modules/@pulumi/pulumi/runtime/mocks.js:125:23)
      at /pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:615:91
      at new Promise (<anonymous>)
      at Object.<anonymous> (node_modules/@pulumi/pulumi/runtime/resource.js:615:50)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/@pulumi/pulumi/runtime/resource.js:18:58)
```

This happens asynchronously, so the test that creates these resources seems to pass, and a later test errors out.

## Expected behavior
EventRuleEventSubscription resources should not be considered unknown by the MockMonitor.

## Steps to reproduce

Add this mocha test to an existing suite of tests, in a file called AAA.spec.ts (or similar). It has to run before a few other tests, as the issue doesn't manifest for a few milliseconds.

```
import "mocha";
import { expect, use as chaiWillUse } from "chai";
import * as chaiAsPromised from "chai-as-promised";
chaiWillUse(chaiAsPromised);

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";


declare module "@pulumi/pulumi" {
  export interface OutputInstance<T> {
    promise(withUnknowns?: boolean): Promise<T>;
  }
}

describe("AAA", function AAA() {
  before(function prepareState() {
    pulumi.runtime.setMocks({
      newResource: (args: pulumi.runtime.MockResourceArgs): { id: string, state: Record<string, any> } => {
        let state = {
          ...args.inputs,
          id: `${args.inputs.name ?? args.name}_id`,
          name: args.inputs.name ?? args.name,
        };

        return {
          id: state.id,
          state: state,
        };
      },
      call: (args: pulumi.runtime.MockCallArgs): Record<string, any> => {
        return args.inputs;
      },
    });
  });


  it("should pass", async function pass() {
    const name = "thisShouldPass";
    const role = new aws.iam.Role(name, {
      assumeRolePolicy: {
        Version: "2012-10-17",
        Statement: [{
          Effect: "Allow",
          Action: "sts:AssumeRole",
          Principal: { Service: "lambda.amazonaws.com" }
        }]
      } as aws.iam.PolicyDocument
    });
    const rule = new aws.cloudwatch.EventRule(name, {
    });
    const handler = new aws.lambda.CallbackFunction<aws.cloudwatch.EventRuleEvent, void>(name, {
      role: role,
      callback: (_: aws.cloudwatch.EventRuleEvent) => {}
    }, { parent: rule });
    const startSchedule = new aws.cloudwatch.EventRuleEventSubscription(name, rule, handler, {}, { parent: handler });

    expect(startSchedule.eventRule.name.promise()).to.eventually.eql(name);
  });
});
```

The error is:

>      Uncaught Error: unknown resource urn:pulumi:stack::project::aws:lambda/function:Function$aws:cloudwatch:EventRuleEventSubscription::thisShouldPass
>       at MockMonitor.registerResourceOutputs (node_modules/@pulumi/pulumi/runtime/mocks.js:125:23)
>       at /pulumi/projects/node_modules/@pulumi/pulumi/runtime/resource.js:615:91
>       at new Promise (<anonymous>)
>       at Object.<anonymous> (node_modules/@pulumi/pulumi/runtime/resource.js:615:50)
>       at Generator.next (<anonymous>)
>       at fulfilled (node_modules/@pulumi/pulumi/runtime/resource.js:18:58)

If you remove the `, { parent: handler }` parameter at the end of the EventRuleEventSubscription constructor, this error goes away. I think this is because there are only two levels of parent/child relationships with this change, and the getUrn and changeUrn logic produce the same output in this case. (The error is replaced by another error, which may be related; I think it has something to do with the aliases opt, and how it is used in generating URNs.)

## Analysis

I note that the code that produces this URN (https://github.com/pulumi/pulumi/blob/bd183840387d49d48a7877571acafa70d757860b/sdk/nodejs/runtime/mocks.ts#L105) has different logic to this function: https://github.com/pulumi/pulumi/blob/bd183840387d49d48a7877571acafa70d757860b/sdk/nodejs/resource.ts#L29. Specifically, newUrn considers only a resource's type and its parent's type when creating a URN, but createUrn uses all the ancestors' types. I don't know that createUrn is used in the tests, since I haven't encountered this before, but perhaps it is used specifically in EventRuleEventSubscription, or mixins?

## Affected feature

Unit tests / "mocks".

**Comment by tenwit** [comment]
It looks like createUrn is used in this case because EventRuleEventSubscription sets the aliases opt, which I've never done in a test object before. That causes the function `inheritedChildAlias` in _resource.ts_ to be called, which is what calls createUrn. Then later when the MockMonitor looks up the resource by calling `this.resources.get(req.getUrn())`, it can't find it because the getUrn and createUrn logics are different.

**Comment by tenwit** [comment]
(Aside: is the alias still necessary? I can't re-parent my EventRuleEventSubscriptions because the new version has the same alias as the old version.. I can work around this via commenting-out or transforms, but I think the alias just isn't needed any more.)

**Comment by komalali** [comment]
Thanks @tenwit for doing a lot of the digging here! As you noticed, this appears to be throwing due to the fact that an `EventRuleEventSubscription` is already parented by the `EventRule` in its definition, and when you pass in a specific parent, i.e. `{ parent: handler }`, the parent you pass in is assigned as an alias. These changes were introduced in https://github.com/pulumi/pulumi-aws/pull/623 and https://github.com/pulumi/pulumi-aws/pull/625, and it's unclear if this is the correct behavior if an explicit parent is provided.

In any case, since `MockMonitor.newUrn()` doesn't take the alias into consideration, it results in a mismatch of urns, resulting in the error you saw. 

@tenwit I'm curious why you have explicitly set the handler function as the parent for the `EventRuleEventSubscription` when it is already parented by the `EventRule`.

More generally, though, this seems like a corner case affecting how the MockMonitor handles (or fails to handle) aliases, which are used internally by `pulumi-aws` mixins. This issue appears to have existed since early 2020 when the MockMonitor was first introduced for Nodejs.
