### ISSUE TITLE
Panic importing gitlab:index/groupMembership

### ISSUE THREAD

**Issue by alexbowers** [pulumi/pulumi#7054]
```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.2.1
Go Version:       go1.16.3
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: An assertion has failed: Module member token 'gitlab:index/groupMembership' missing module member delimiter

goroutine 1 [running]:
runtime/debug.Stack(0xc001633240, 0x55d0720, 0xc00055a570)
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/debug/stack.go:24 +0x9f
main.panicHandler()
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/cmd/pulumi/main.go:29 +0x76
panic(0x55d0720, 0xc00055a570)
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/panic.go:965 +0x1b9
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20210506-93883-penxzb/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x7ffeefbff400, 0x5993f4d, 0x38, 0xc001633490, 0x1, 0x1)
	/private/tmp/pulumi-20210506-93883-penxzb/sdk/go/common/util/contract/assert.go:33 +0x1a5
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.ModuleMember.Module(0x7ffeefbff476, 0x1c, 0xc000416cc0, 0x0)
	/private/tmp/pulumi-20210506-93883-penxzb/sdk/go/common/tokens/tokens.go:192 +0xd2
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.ModuleMember.Package(0x7ffeefbff476, 0x1c, 0x5c5d288, 0x1)
	/private/tmp/pulumi-20210506-93883-penxzb/sdk/go/common/tokens/tokens.go:187 +0x35
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.Type.Package(0x7ffeefbff476, 0x1c, 0x38, 0x5932ded)
	/private/tmp/pulumi-20210506-93883-penxzb/sdk/go/common/tokens/tokens.go:227 +0x70
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(0xc0009044c0, 0xc000900520, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/engine/deployment.go:177 +0x470
github.com/pulumi/pulumi/pkg/v3/engine.update(0xc0009044c0, 0xc000900520, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/engine/update.go:439 +0x4e7
github.com/pulumi/pulumi/pkg/v3/engine.Import(0x5cbab28, 0xc000552b40, 0xc0009044c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, ...)
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/engine/import.go:43 +0x56e
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(0xc000aa53e0, 0x5cc7108, 0xc000198008, 0x59484db, 0xf, 0x5cb1da8, 0xc0009040c0, 0xc00020f200, 0xc0000435e0, 0x38, ...)
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/backend/httpstate/backend.go:1043 +0xce5
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(0xc000aa53e0, 0x5cc7108, 0xc000198008, 0x59484db, 0xf, 0x5ce3630, 0xc00020f800, 0xc00020f200, 0xc0000435e0, 0x38, ...)
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/backend/httpstate/backend.go:949 +0x2ba
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt(0x5cc7108, 0xc000198008, 0x59484db, 0xf, 0x5ce3630, 0xc00020f800, 0xc00020f200, 0xc0000435e0, 0x38, 0xc0005fb5c0, ...)
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/backend/apply.go:115 +0x133
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute(0x5cc7108, 0xc000198008, 0x59484db, 0xf, 0x5ce3630, 0xc00020f800, 0xc00020f200, 0xc0000435e0, 0x38, 0xc0005fb5c0, ...)
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/backend/apply.go:200 +0x1a8
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Import(0xc000aa53e0, 0x5cc7108, 0xc000198008, 0x5ce3630, 0xc00020f800, 0xc00020f200, 0xc0000435e0, 0x38, 0xc0005fb5c0, 0x1, ...)
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/backend/httpstate/backend.go:842 +0x109
github.com/pulumi/pulumi/pkg/v3/backend.ImportStack(0x5cc7108, 0xc000198008, 0x5ce3630, 0xc00020f800, 0xc00020f200, 0xc0000435e0, 0x38, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/backend/stack.go:91 +0xe5
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Import(0xc00020f800, 0x5cc7108, 0xc000198008, 0xc00020f200, 0xc0000435e0, 0x38, 0x0, 0x0, 0x0, 0xc000191548, ...)
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/backend/httpstate/stack.go:153 +0xc8
main.newImportCmd.func1(0xc000aa78c0, 0xc000aa4cc0, 0x3, 0x3, 0x0, 0x0)
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/cmd/pulumi/import.go:462 +0xd05
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000aa78c0, 0xc000aa4cc0, 0x3, 0x3)
	/private/tmp/pulumi-20210506-93883-penxzb/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000aa78c0, 0xc000aa4c90, 0x3, 0x3, 0xc000aa78c0, 0xc000aa4c90)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c02c0, 0xc000072740, 0x406fda8, 0xc000000180)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/private/tmp/pulumi-20210506-93883-penxzb/pkg/cmd/pulumi/main.go:48 +0x4d
```

**Comment by stack72** [comment]
Hi @alexbowers 

Apologies for this, the module name is `gitlab:index/groupMembership:GroupMembership`

We should make sure that doesn't panic and gives the user a better message

Paul

**Comment by alexbowers** [comment]
Ah that makes sense. Thanks

**Comment by stack72** [comment]
I will keep this open so we can track the panics here

Paul

**Comment by lukehoban** [comment]
This issue is also being tracked in #6990 so closing this one out to track there.
