### ISSUE TITLE
Cannot run pulumi up with resoure AWS

### ISSUE THREAD

**Issue by vanbasten17** [pulumi/pulumi#7085]
## Expected behavior
* Should run `pulumi up` as expected.

## Current behavior
After doing a clean install of pulumi with brew (MacOS 10.15.7) and logged in (as `pulumi login --local`) cannot deploy my stack of the project anymore.
Also tried after a clean install of: https://github.com/pulumi/examples/tree/master/aws-ts-static-website with same results.

## Steps to reproduce

1. Clone https://github.com/pulumi/examples/tree/master/aws-ts-static-website
2. `npm install`
3. `pulumi login --local`
4. Config the stack with `config set` command:
```
encryptionsalt: XXX
config:
  aws:profile: myprofile-super-admin
  static-website:pathToWebsiteContents: www
  static-website:targetDomain: test.mydomain.com
```
5. `pulumi up`: which produces the following output:

```
Previewing update (dev):
     Type                 Name                       Plan       Info
 +   pulumi:pulumi:Stack  aws-ts-static-website-dev  create...          /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.0. +   pulumi:pulumi:Stack  aws-ts-static-website-dev  create...          /home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:4173 +0x52e1     Type                     Name                       Plan       Info +   pulumi:pulumi:Stack      aws-ts-static-website-dev  create...      /home/runner/work/pulumi-aws/pulumi-aws/provider/cmd/pulumi-resource-aws/m +   pulumi:pulumi:Stack      aws-ts-static-website-dev  create     9 messages
     └─ pulumi:providers:aws  default_4_5_0                         1 error
 
Diagnostics:
  pulumi:providers:aws (default_4_5_0):
    error: could not read plugin [/Users/me/.pulumi/plugins/resource-aws-v4.5.0/pulumi-resource-aws] stdout: EOF
 
  pulumi:pulumi:Stack (aws-ts-static-website-dev):
    panic: strconv.ParseUint: parsing "": invalid syntax
    goroutine 1 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.GetModuleMajorVersion(0x0, 0x0, 0xc0013bf5b0, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.0.0/pkg/tfbridge/info.go:730 +0x1dc
    github.com/pulumi/pulumi-aws/provider/v4.Provider(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/pulumi-aws/pulumi-aws/provider/resources.go:4173 +0x52e1b
    main.main()
        /home/runner/work/pulumi-aws/pulumi-aws/provider/cmd/pulumi-resource-aws/main.go:26 +0x37
 
    Syncing contents from local disk at /Users/me/Desktop/examples/aws-ts-static-website/www
```

I have the project up and running just yesterday, and I have tried to uninstall and reinstall pulumi binary with no results. Any clue on this?

**Comment by pierskarsenbarg** [comment]
Hi @vanbasten17 we released v4.5.0 this morning that had a bug in it. We're in the middle of releasing 4.5.1 with a fix in, or you can go back to the previous version (v4.4.1) and this should work again.
