### ISSUE TITLE
`stack.cancel()` of automation API doesn't work. 

### ISSUE THREAD

**Issue by taoluo** [pulumi/pulumi#7096]
`stack.cancel()` doesn't work.

## Expected behavior
`stack.cancel()` should cancel an updating stack.
## Current behavior
```
refreshing stack...
Refreshing (dev)

Traceback (most recent call last):
  File "./setup_ec2_vms.py", line 155, in <module>
    stack.refresh(on_output=print)
  File "/home/tao2/miniconda3/envs/ops/lib/python3.7/site-packages/pulumi/automation/_stack.py", line 391, in refresh
    refresh_result = self._run_pulumi_cmd_sync(args, on_output)
  File "/home/tao2/miniconda3/envs/ops/lib/python3.7/site-packages/pulumi/automation/_stack.py", line 591, in _run_pulumi_cmd_sync
    result = _run_pulumi_cmd(args, self.workspace.work_dir, envs, on_output)
  File "/home/tao2/miniconda3/envs/ops/lib/python3.7/site-packages/pulumi/automation/_cmd.py", line 75, in _run_pulumi_cmd
    raise create_command_error(result)
pulumi.automation.errors.ConcurrentUpdateError:
 code: 255
 stdout: Refreshing (dev)

 stderr: error: [409] Conflict: Another update is currently in progress.
To learn more about possible reasons and resolution, visit https://www.pulumi.com/docs/troubleshooting/#conflict
```

## Steps to reproduce
//

## Context (Environment)
python SDK in Linux

**Comment by ttaoluo** [comment]
Also, while troubleshooting by myself, I cannot find any unittest/example about `cancel()` of python API in current repo.

**Comment by emiliza** [comment]
Hi @taoluo - currently looking into this. Can you tell me what backend you're using?

`stack.cancel()` is only supported right now on the Pulumi service backend and won't work for other backends (see doc string note here: https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/automation/_stack.py#L558)

**Comment by emiliza** [comment]
@taoluo closing due to inactivity. Please create a new issues and provide the additional information requested if this is still an issue - thanks!
