### ISSUE TITLE
Error on BranchProtection resource

### ISSUE THREAD

**Issue by kateetrant** [pulumi/pulumi#7112]
## Expected behavior
pulumi imports BranchProtection resource after retrieval without error

## Current behavior
Errors on import. Subsequent import fails on preview as it is already imported

## Steps to reproduce

1. run ` pulumi import github:index/branchProtection:BranchProtection repo.repo repo.repo:development`
2. agree to import

*Stack Trace and relevant info*
```
Pulumi Version:   v3.3.0
Go Version:       go1.16.3
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            invalid Go source code:

package main

import (

"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
"github.com/pulumi/pulumi-github/sdk/v4/go/github"
)
func main() {
pulumi.Run(func(ctx *pulumi.Context) error {
_, err := github.NewBranchProtection(ctx, "repo_repo", &github.BranchProtectionArgs{
AllowsDeletions: pulumi.Bool(false),
AllowsForcePushes: pulumi.Bool(false),
EnforceAdmins: pulumi.Bool(false),
Pattern: pulumi.String("development"),
PushRestrictions: interface{}{
nil,
nil,
pulumi.String("MDQ6VGVhbTQwMjg0ODk="),
},
RepositoryId: pulumi.String("MDEwOlJlcG9zaXRvcnkyMTg4MzY5NDY="),
RequireSignedCommits: pulumi.Bool(false),
}, pulumi.Protect(true))
if err != nil {
return err
}
return nil
})
}


goroutine 1 [running]:
runtime/debug.Stack(0xc002212a88, 0x56d7840, 0xc000d0bd28)
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/debug/stack.go:24 +0x9f
main.panicHandler()
	/private/tmp/pulumi-20210520-6659-1j9ek9d/pkg/cmd/pulumi/main.go:29 +0x76
panic(0x56d7840, 0xc000d0bd28)
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/panic.go:965 +0x1b9
github.com/pulumi/pulumi/pkg/v3/codegen/go.GenerateProgram(0xc000ec1800, 0x691f620, 0xc001125ce0, 0x53a15c0, 0xc002cbada0, 0x1, 0x1)
	/private/tmp/pulumi-20210520-6659-1j9ek9d/pkg/codegen/go/gen_program.go:92 +0x91f
main.generateImportedDefinitions.func1(0x5c956c0, 0xc0008aad20, 0xc000ec1800, 0xc002212e00, 0x2)
	/private/tmp/pulumi-20210520-6659-1j9ek9d/pkg/cmd/pulumi/import.go:238 +0x44
github.com/pulumi/pulumi/pkg/v3/codegen/importer.GenerateLanguageDefinitions(0x5c956c0, 0xc0008aad20, 0x5c98020, 0xc000d56330, 0xc002213048, 0xc000722350, 0x1, 0x1, 0xc0008aad50, 0x27, ...)
	/private/tmp/pulumi-20210520-6659-1j9ek9d/pkg/codegen/importer/language.go:107 +0x5e9
main.generateImportedDefinitions(0x5c956c0, 0xc0008aad20, 0xc0005417a0, 0x6, 0xc000541010, 0x6, 0xc001af2f30, 0x59e2058, 0xc0008aad50, 0xc000537860, ...)
	/private/tmp/pulumi-20210520-6659-1j9ek9d/pkg/cmd/pulumi/import.go:237 +0x5a5
main.newImportCmd.func1(0xc0008adb80, 0xc0008aacc0, 0x3, 0x3, 0x0, 0x0)
	/private/tmp/pulumi-20210520-6659-1j9ek9d/pkg/cmd/pulumi/import.go:477 +0xed2
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc0008adb80, 0xc0008aacc0, 0x3, 0x3)
	/private/tmp/pulumi-20210520-6659-1j9ek9d/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc0008adb80, 0xc0008aac90, 0x3, 0x3, 0xc0008adb80, 0xc0008aac90)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a8000, 0xc00007c740, 0x406ddc8, 0xc000000180)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/private/tmp/pulumi-20210520-6659-1j9ek9d/pkg/cmd/pulumi/main.go:48 +0x4d
```

**Comment by lukehoban** [comment]
This part doesn't look like legal Go code - so there is definitely something wrong in the Go codegen here:

```go
PushRestrictions: interface{}{
nil,
nil,
pulumi.String("MDQ6VGVhbTQwMjg0ODk="),
},
```

We should understand whether this impacts only a corner case of `pulumi import` for Go, or impacts a common case.

**Comment by komalali** [comment]
@kateetrant could you do a `pulumi stack export` and tell me what your inputs look like for this resource? I'm mostly curious about the `pushRestrictions` property.

But yeah, I can at least make the fix of not panicking and providing a more useful error.

**Comment by komalali** [comment]
I've fixed the panic to provide a better error, but the underlying error in import remains. Removing the p1 label and we can come back to this (or someone with the right github access can maybe get a repro so we can track down the underlying issue).

**Comment by emiliza** [comment]
@kateetrant closing this due to inactivity. We've gone ahead and fixed the panic to get a better error but still need repro steps to understand the underlying `import` issue.  If this is still a problem please create a new issue and include the information requested by Komal.  Thanks!

**Comment by kateetrant** [comment]
Hey sorry I didn't see this earlier. I'm not sure the export would be of any use now. We deleted all the previous resources and now have the `branchProtectionV3` resources.
