### ISSUE TITLE
pulumi up crashes with generic error message "transport is closing"

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#7132]
When calling `pulumi up`, the command crashes and returns the following error
`Exception: invoke of aws:iam/getPolicyDocument:getPolicyDocument failed: invocation of aws:iam/getPolicyDocument:getPolicyDocument returned an error: transport is closing`

## Expected behavior

The CLI shouldn't crash and a more specific error message should be displayed.

## Current behavior

the command `pulumi up` crashes, dumps some debug information along with other error messages.

```
Previewing update (crash)

View Live: https://app.pulumi.com/aureq/aws-py-wireguard-server-transport-closing/crash/previews/a39490fe-3c1a-4315-bbad-8c8ea88baa8c

     Type                                    Name                                             Plan       Info
 +   pulumi:pulumi:Stack                     aws-py-wireguard-server-transport-closing-crash  create     3 errors; 34 messages
 +   └─ aws:secretsmanager:Secret            wireguard-vpn-secret                             create     
 +      └─ aws:secretsmanager:SecretVersion  wireguard-vpn-secret                             create     
 
Diagnostics:
  pulumi:pulumi:Stack (aws-py-wireguard-server-transport-closing-crash):
    panic: fatal: A failure has occurred: Unrecognized structpb value kind in RPC[tf.Provider[aws].Invoke(aws:iam/getPolicyDocument:getPolicyDocument).args]: <nil>
    goroutine 99 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf(0x72dbe51, 0x2f, 0xc001c96a00, 0x2, 0x2)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/common/util/contract/fail.go:30 +0x18d
    github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.UnmarshalPropertyValue(0xc002194200, 0xc001cb39f0, 0x49, 0x101, 0x0, 0xc002198170, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/common/resource/plugin/rpc.go:427 +0x3b9
    github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.UnmarshalPropertyValue(0xc002194180, 0xc001cb39f0, 0x49, 0x101, 0x0, 0xc002198190, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/common/resource/plugin/rpc.go:292 +0x19c9
    github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.UnmarshalProperties(0xc002182d80, 0xc001cb39f0, 0x49, 0x101, 0x0, 0xc001c96f98, 0x4665ff, 0x64241e0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/common/resource/plugin/rpc.go:243 +0x267
    github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.UnmarshalPropertyValue(0xc002194080, 0xc001cb39f0, 0x49, 0x101, 0x0, 0xc001c97230, 0xc001c97450, 0x4f402c)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/common/resource/plugin/rpc.go:307 +0x43a
    github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.UnmarshalPropertyValue(0xc0014d5fc0, 0xc001cb39f0, 0x49, 0x101, 0x0, 0xc002198120, 0x0, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/common/resource/plugin/rpc.go:292 +0x19c9
    github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.UnmarshalProperties(0xc002182ba0, 0xc001cb39f0, 0x49, 0x101, 0x0, 0xc001cb39f0, 0x49, 0x7365598)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/go/common/resource/plugin/rpc.go:243 +0x267
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Invoke(0xc00000ad20, 0x7d887c8, 0xc002182de0, 0xc0018a1860, 0xc00000ad20, 0x6367001, 0xc002194240)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.0.0/pkg/tfbridge/provider.go:1128 +0x3e5
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler.func1(0x7d887c8, 0xc002182de0, 0x6f63e60, 0xc0018a1860, 0x6faed00, 0xc221868, 0x7d887c8, 0xc002182de0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/proto/go/provider.pb.go:2194 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x7d887c8, 0xc002182930, 0x6f63e60, 0xc0018a1860, 0xc001cdc820, 0xc00214b6b0, 0x0, 0x0, 0x7cb2ca0, 0xc000434c50)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler(0x70c7da0, 0xc00000ad20, 0x7d887c8, 0xc002182930, 0xc0018a1800, 0xc001b461a0, 0x7d887c8, 0xc002182930, 0xc001c305a0, 0x88)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.0.0/proto/go/provider.pb.go:2196 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000fd4e00, 0x7dac798, 0xc00017e000, 0xc00215e900, 0xc001b3ced0, 0xc1de800, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1210 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc000fd4e00, 0x7dac798, 0xc00017e000, 0xc00215e900, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1533 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000160050, 0xc000fd4e00, 0x7dac798, 0xc00017e000, 0xc00215e900)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:869 +0x1fd
 
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/redacted/.pulumi/bin/pulumi-language-python-exec", line 92, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/redacted/work/aws-py-wireguard-server/demos/aws-py-wireguard-server-crash-transport-closing/deployment/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 110, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/redacted/work/aws-py-wireguard-server/demos/aws-py-wireguard-server-crash-transport-closing/deployment/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 43, in run_pulumi_func
        func()
      File "/redacted/work/aws-py-wireguard-server/demos/aws-py-wireguard-server-crash-transport-closing/deployment/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 110, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/redacted/work/aws-py-wireguard-server/demos/aws-py-wireguard-server-crash-transport-closing/deployment/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 133, in __init__
        func()
      File "/redacted/.pulumi/bin/pulumi-language-python-exec", line 91, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/local/lib/python3.9/runpy.py", line 285, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 37, in <module>
        role_policy = iam.get_policy_document(
      File "/redacted/work/aws-py-wireguard-server/demos/aws-py-wireguard-server-crash-transport-closing/deployment/venv/lib/python3.9/site-packages/pulumi_aws/iam/get_policy_document.py", line 185, in get_policy_document
        __ret__ = pulumi.runtime.invoke('aws:iam/getPolicyDocument:getPolicyDocument', __args__, opts=opts, typ=GetPolicyDocumentResult).value
      File "/redacted/work/aws-py-wireguard-server/demos/aws-py-wireguard-server-crash-transport-closing/deployment/venv/lib/python3.9/site-packages/pulumi/runtime/invoke.py", line 144, in invoke
        raise invoke_error
    Exception: invoke of aws:iam/getPolicyDocument:getPolicyDocument failed: invocation of aws:iam/getPolicyDocument:getPolicyDocument returned an error: transport is closing
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

## Steps to reproduce

1. create a new python pulumi app
2. select your preferred AWS region
3. run the app using the code provided
4. wait until the code crashes

## Source
```python
"""
An AWS Python Pulumi program to securely deploy a Wireguard VPN server
"""
import json
import pulumi
from pulumi_aws import iam, secretsmanager

config = pulumi.Config()
service_name = f'wireguard-vpn'
secret_name = f'{service_name}-secret'
role_name = f'{service_name}-ec2-role'
wg0_conf = "some secure string using: config.require_secret('wg0_conf')"

"""
Store the wireguard configuration into AWS Secrets Manager.
"""
secret = secretsmanager.Secret(
    resource_name=secret_name,
    tags={
        'Name': secret_name
    }
)

secretsmanager.SecretVersion(secret_name,
    secret_id=secret.id,
    secret_string=wg0_conf,
    opts=pulumi.ResourceOptions(parent=secret)
)

"""
Create an EC2 instance role to grant EC2 instances access to this secret
"""
# ##########################################################
# the use of `secret.arn.apply` is incorrect and that's the reason of the crash
# ##########################################################
role_name = service_name+'-ec2-role'
role_policy = iam.get_policy_document(
    statements=[
        iam.GetPolicyDocumentStatementArgs(
            actions=["secretsmanager:GetSecretValue"],
            resources=[
                secret.arn.apply(lambda arg: f"{arg}")
            ],
        )
    ]
)

# ##########################################################
# this is the correct code
# ##########################################################
# role_name = self._name+'-ec2-role'
# role_policy = self.secret.arn.apply(
#     lambda secret_arn:
#     iam.get_policy_document(
#         statements=[
#             iam.GetPolicyDocumentStatementArgs(
#                 actions=["secretsmanager:GetSecretValue"],
#                 resources=[
#                     secret_arn
#                 ],
#             )
#         ]
#     )
# )

ec2_role = iam.Role(role_name,
    assume_role_policy=json.dumps({
        "Version": "2012-10-17",
        "Statement": [{
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Sid": "",
            "Principal": {
                "Service": "ec2.amazonaws.com",
            },
        }],
    }),
    inline_policies=[
        iam.RoleInlinePolicyArgs(
            name=role_name+'-policy',
            policy=role_policy.json,
        )
    ],
    opts=pulumi.ResourceOptions(parent=secret)
)

instance_profile = iam.InstanceProfile(service_name+'-instance-profile',
    role=ec2_role.name,
    opts=pulumi.ResourceOptions(parent=ec2_role)
)

```

**Comment by t0yv0** [comment]
The solution put forward in #7214 fixes a low-level bug in MarshalProperties treatment of unknown values. With the fix, I can no longer reproduce a panic (or an error) on the given example, it previews and updates as expected. Closing based on this result.
