### ISSUE TITLE
Assertion failed during import of azure-native ContainerGroup

### ISSUE THREAD

**Issue by bbh** [pulumi/pulumi#7176]
I was trying to import an azure container instance but the only output is

```
fatal: An assertion has failed: Module member token 'azure-native:containerinstance.ContainerGroup' missing module member delimiter
```

## Expected behavior
to import the resource

## Current behavior
Getting a fatal error

## Steps to reproduce
Create an azure container instance and try to import such resource

```
pulumi import -s <STACK_NAME> azure-native:containerinstance.ContainerGroup <RESOURCE_NAME> /subscriptions/<SUBSCRIPTION_ID>/resourceGroups/<RESOURCE_GROUP_NAME>/providers/Microsoft.ContainerInstance/containerGroups/<CONTAINER_GROUP_NAME>
```

## Context (Environment)
Pulumi Version:   v3.3.1
Go Version:       go1.16.4
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            fatal: An assertion has failed: Module member token 'azure-native:containerinstance.ContainerGroup' missing module member delimiter

```
goroutine 1 [running]:
runtime/debug.Stack(0xc0001e3490, 0x19c88e0, 0xc000670ed0)
	/Users/runner/hostedtoolcache/go/1.16.4/x64/src/runtime/debug/stack.go:24 +0x9f
main.panicHandler()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x76
panic(0x19c88e0, 0xc000670ed0)
	/Users/runner/hostedtoolcache/go/1.16.4/x64/src/runtime/panic.go:965 +0x1b9
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x7ffc26e93500, 0x1d8aae2, 0x38, 0xc0001e36e0, 0x1, 0x1)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:33 +0x1a5
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.ModuleMember.Module(0x7ffc26e935b7, 0x2d, 0xc000f886c0, 0x208dcc0)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/tokens/tokens.go:192 +0xd2
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.ModuleMember.Package(0x7ffc26e935b7, 0x2d, 0x2053110, 0x1)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/tokens/tokens.go:187 +0x35
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.Type.Package(0x7ffc26e935b7, 0x2d, 0x30, 0x1d2968d)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/tokens/tokens.go:227 +0x70
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(0xc0013f4540, 0xc001012600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
	/Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:177 +0x470
github.com/pulumi/pulumi/pkg/v3/engine.update(0xc0013f4540, 0xc001012600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
	/Users/runner/work/pulumi/pulumi/pkg/engine/update.go:439 +0x4e7
github.com/pulumi/pulumi/pkg/v3/engine.Import(0x20b0130, 0xc0013d69c0, 0xc0013f4540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, ...)
	/Users/runner/work/pulumi/pulumi/pkg/engine/import.go:43 +0x56e
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).apply(0xc000180300, 0x20bc768, 0xc000110000, 0x1d3efed, 0xf, 0x20d8a28, 0xc000dd60c0, 0xc00054c980, 0xc00055f140, 0x30, ...)
	/Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:609 +0x1385
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt(0x20bc768, 0xc000110000, 0x1d3efed, 0xf, 0x20d8a28, 0xc000dd60c0, 0xc00054c980, 0xc00055f140, 0x30, 0xc000dbea20, ...)
	/Users/runner/work/pulumi/pulumi/pkg/backend/apply.go:115 +0x133
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute(0x20bc768, 0xc000110000, 0x1d3efed, 0xf, 0x20d8a28, 0xc000dd60c0, 0xc00054c980, 0xc00055f140, 0x30, 0xc000dbea20, ...)
	/Users/runner/work/pulumi/pulumi/pkg/backend/apply.go:200 +0x1a8
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).Import(0xc000180300, 0x20bc768, 0xc000110000, 0x20d8a28, 0xc000dd60c0, 0xc00054c980, 0xc00055f140, 0x30, 0xc000dbea20, 0x1, ...)
	/Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:502 +0x193
github.com/pulumi/pulumi/pkg/v3/backend.ImportStack(0x20bc768, 0xc000110000, 0x20d8a28, 0xc000dd60c0, 0xc00054c980, 0xc00055f140, 0x30, 0x0, 0x0, 0x0, ...)
	/Users/runner/work/pulumi/pulumi/pkg/backend/stack.go:91 +0xe5
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localStack).Import(0xc000dd60c0, 0x20bc768, 0xc000110000, 0xc00054c980, 0xc00055f140, 0x30, 0x0, 0x0, 0x0, 0xc000b7b1b8, ...)
	/Users/runner/work/pulumi/pulumi/pkg/backend/filestate/stack.go:77 +0xc8
main.newImportCmd.func1(0xc000dcadc0, 0xc0001849b0, 0x3, 0x5, 0x0, 0x0)
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/import.go:462 +0xd05
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000dcadc0, 0xc0001849b0, 0x3, 0x5)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000dcadc0, 0xc000184960, 0x5, 0x5, 0xc000dcadc0, 0xc000184960)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001422c0, 0xc00004a060, 0xc00006a748, 0x2cd60c0)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x4d
```

**Comment by lukehoban** [comment]
The format of the type token should be `azure-native:containerinstance:ContainerGroup`. 

We are tracking the fact that this crashes instead of reporting a useful error at https://github.com/pulumi/pulumi/issues/7054 and #6990.
