### ISSUE TITLE
Better errors for multi-language components

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#7197]
When I have an error in my multi-language component implementation (in Go), and try to construct an instance from Node.js, I see the following:

```
Diagnostics:
  pulumi:pulumi:Stack (serverless-simple-test):
    error: Error: failed to register new resource svc [serverless:index:Service]: 2 UNKNOWN: creating component: invalid value for required argument 'AssumeRolePolicy'
        at Object.registerResource (/Users/lukehoban/go/src/github.com/lukehoban/pulumi-package-serverless/sdk/nodejs/node_modules/@pulumi/pulumi/runtime/resource.js:219:27)
        at new Resource (/Users/lukehoban/go/src/github.com/lukehoban/pulumi-package-serverless/sdk/nodejs/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new ComponentResource (/Users/lukehoban/go/src/github.com/lukehoban/pulumi-package-serverless/sdk/nodejs/node_modules/@pulumi/pulumi/resource.js:386:9)
        at new Service (/Users/lukehoban/go/src/github.com/lukehoban/pulumi-package-serverless/sdk/nodejs/service.ts:62:9)
        at Object.<anonymous> (/Users/lukehoban/go/src/github.com/lukehoban/pulumi-package-serverless/examples/simple/index.ts:6:13)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Module.m._compile (/Users/lukehoban/go/src/github.com/lukehoban/pulumi-package-serverless/examples/simple/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/lukehoban/go/src/github.com/lukehoban/pulumi-package-serverless/examples/simple/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:928:32)
```

The only part of this that is relevant to my problem is `invalid value for required argument 'AssumeRolePolicy'`.  However, that's not a ton of information to go on to figure out what the issue was.  In fact, it doesn't even mention that the required argument was for a an `aws.iam.Role` and specifically a call to `iam.NewRole`.  There is also a bit of gRPC stuff bleeding through here which doesn't seem ideal. 

It turns out, the issue was on this line in my Go code:

```go
executionRole, err := iam.NewRole(ctx, "role", &iam.RoleArgs{}, pulumi.Parent(component))
```

**Comment by lunaris** [comment]
I think this has been addressed by #17306 and its various follow-ups; closing but we can reopen if I'm wrong.
