### ISSUE TITLE
Issue with the work for waiting async tasks in Go SDK

### ISSUE THREAD

**Issue by emiliza** [pulumi/pulumi#7275]
Experienced by @stack72 - seeing this on the pulumi-docker repo after upgrading to Pulumi v3.4.0 when using a pulumi-docker go program
```
Diagnostics:
  pulumi:pulumi:Stack (dockerfile-go-p-it-fv-az290-4-dockerfile-d29d3b03):
    panic: sync: WaitGroup is reused before previous Wait has returned
    goroutine 1 [running]:
    sync.(*WaitGroup).Wait(0xc00039c9d8)
    	/opt/hostedtoolcache/go/1.16.4/x64/src/sync/waitgroup.go:132 +0xae
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).wait(0xc00039c8c0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/pulumi/context.go:156 +0x50
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc00039c8c0, 0xe32308, 0xc00003824f, 0xd)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/pulumi/run.go:112 +0x2a6
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunErr(0xe32308, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/pulumi/run.go:84 +0x23f
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.Run(0xe32308, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/pulumi/run.go:41 +0x59
    main.main()
    	/home/runner/go/src/stackName-1623065997245879475/main.go:9 +0x3e
    exit status 2
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

Possibly related to:  https://github.com/pulumi/pulumi/pull/6983

**Comment by scottslowe** [comment]
Also experiencing this error using Pulumi v3.5.1 with the AWS resource provider:

```
Diagnostics:
  pulumi:pulumi:Stack (aws-infra-go-us-west-2):
    panic: sync: WaitGroup is reused before previous Wait has returned
    goroutine 1 [running]:
    sync.(*WaitGroup).Wait(0xc000146258)
    	/usr/local/go/src/sync/waitgroup.go:132 +0xae
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).wait(0xc000146140, 0x0, 0x0)
    	/Users/slowe/Code/Go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.0/go/pulumi/context.go:156 +0x50
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc000146140, 0x1c40808, 0xc0000440ef, 0xc)
    	/Users/slowe/Code/Go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.0/go/pulumi/run.go:112 +0x2a6
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunErr(0x1c40808, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/Users/slowe/Code/Go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.0/go/pulumi/run.go:84 +0x23f
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.Run(0x1c40808, 0x0, 0x0, 0x0)
    	/Users/slowe/Code/Go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.0/go/pulumi/run.go:41 +0x59
    main.main()
    	/Users/slowe/Code/Repos/lab/infra/aws-infra-go/main.go:14 +0x3e
    exit status 2

    error: an unhandled error occurred: program exited with non-zero exit code: 1
```
This is using Go 1.16.4 on an ARM64 (M1-based Mac) system. For me, the error is intermittent and I have not yet found a way to reliably reproduce it.

**Comment by t0yv0** [comment]
Note to self. According to Go docs this is caused by the following:

```
package main

import (
	"fmt"
	"sync"
	"time"
)

// Note that calls with a positive delta that occur when the counter is zero must happen before a Wait.

func main() {
	wg := &sync.WaitGroup{}
	wg.Add(1)

	go func() {
		fmt.Printf("Adding\n")
		wg.Add(-1)
		wg.Add(1)
		fmt.Printf("Added\n")
	}()

	wg.Wait()
	time.Sleep(10)
}
```

Now digging in to understand how it happens in Pulumi.

**Comment by t0yv0** [comment]
@stack72 you wanted to try this out ~ original issue was on a basic pulumi-docker example, I think it's working for me now, but please confirm. Unfortunately the bug is in the language SDK and it did not make it into 3.9.0 but will be in the next release.
