### ISSUE TITLE
[python] azure_native.containerservice.ManagedCluster fails for multiple values for argument 'resource_name' 

### ISSUE THREAD

**Issue by matteocalabro-tomtom** [pulumi/pulumi#7303]
Newly created project.
I import a managed cluster and `up` without any change: the command fails with unhandled exception.

I also tried with TypeScript and it works as expected, so the issue must be in the Python provider (import in go is also broken, it produces malformed code. panic-ing)

## Affected versions

* pulumi v3.3.1, v3.4.0
* pulumi-azure-native v1.9.0, v1.12.0

## Steps to reproduce
1. `pulumi new azure-python -g -n my-project`
2. ...recommended commands for python env
3. `pulumi stack init test`
4. `pulumi import azure-native:containerservice:ManagedCluster managedCluster /subscriptions/***/resourcegroups/***/providers/Microsoft.ContainerService/managedClusters/my-cluster -o __main__.py`
5. `pulumi up`

Expected: exit code 0, nothing to do
Actual:
```sh
Diagnostics:
  pulumi:pulumi:Stack (test):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 92, in <module>
        loop.run_until_complete(coro)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/path/to/my-repo/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 110, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/path/to/my-repo/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 43, in run_pulumi_func
        func()
      File "/path/to/my-repo/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 110, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/path/to/my-repo/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 133, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 91, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 280, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 4, in <module>
        managed_cluster = azure_native.containerservice.ManagedCluster("managedCluster",
    TypeError: __init__() got multiple values for argument 'resource_name'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by matteocalabro-tomtom** [comment]
Oh, I was reading the code but I didn't notice the trailing underscore 🤦🏻‍♂️

Thanks @mikhailshilkov
