### ISSUE TITLE
StackReference getOutput with empty value causes fatal error

### ISSUE THREAD

**Issue by ng-valentijn** [pulumi/pulumi#7440]
It seems that trying to get a empty variable from a stackreference is causing a fatal error.

## Steps to reproduce

1. Have a exported variable with empty value
2. Create a stackreference with a getOutput to this exported variable

**Expected:** Have a nil or undefined value
**Actual:** 

```
panic: fatal: An assertion has failed

goroutine 206 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*provider).Read(0xc0005e53e0, 0xc00074c5f0, 0x45, 0x0, 0x0, 0x0, 0xc0008f0b40, 0xe87b4d, 0x7f0d00000004, 0x0, ...)
	/Users/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/provider_plugin.go:784 +0x1025
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*ReadStep).Apply(0xc000949260, 0x1, 0x1da7803, 0x23, 0xc0014cfe30, 0x3)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step.go:623 +0x103
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeStep(0xc00057e600, 0x5, 0x211d6e0, 0xc000949260, 0x0, 0x100000000000000)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:271 +0x209
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc00057e600, 0x5, 0xc0016ace30, 0x1, 0x1)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:221 +0xef
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1(0xc00057e600, 0x5, 0xc0016ace30, 0x1, 0x1, 0xc0016c6e40)
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:377 +0xc5
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:374 +0x2c8
```

**Comment by emiliza** [comment]
Hi @ng-valentijn thanks for reporting! Attempting to repro this myself - can you provide more info on what language and versions you're using?

**Comment by ng-valentijn** [comment]
@emiliza  We are using typescript and running pulumi version 3.6.0

**Comment by emiliza** [comment]
I've tried the following and can't get the panic to result:
1. Create typescript stack (ts1) with [0,null,"",undefined] output vars
2. Create new typescript stack (ts2) referencing those output vars

In both ts1&ts2 `undefined` ends up not being created as an output, with no panic. And for null,0, "" the StackReference getOutput in ts2 works as anticipated and the panics don't arise.

@ng-valentijn can you provide more info on how you were able to reproduce this?  Thanks!

**Comment by emiliza** [comment]
Closing due to inactivity - please create a new issue with more repro steps if this is still a problem, thanks!
