### ISSUE TITLE
[auto/dotnet] - Flakey Automation API tests for C#

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#7492]
Since the PR to [Fix swallowed nested exceptions in inline programs](https://github.com/pulumi/pulumi/pull/7323), we have been seeing increased [flakey tests](https://github.com/pulumi/pulumi/runs/3049702475#step:17:97) for the dotnet automation API tests. The stack trace is below:

```
  Failed Pulumi.Automation.Tests.LocalWorkspaceTests.StackLifecycleInlineProgram [5 s]
  Error Message:
   System.Collections.Generic.KeyNotFoundException : The given key 'System.Threading.Tasks.UnwrapPromise`1[System.Threading.Tasks.VoidTaskResult]' was not present in the dictionary.
  Stack Trace:
     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Pulumi.Deployment.Runner.<>c__DisplayClass13_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext() in /_/sdk/dotnet/Pulumi/Deployment/Deployment.Runner.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at Pulumi.Deployment.Runner.WhileRunningAsync() in /_/sdk/dotnet/Pulumi/Deployment/Deployment.Runner.cs:line 181
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at Pulumi.Deployment.<>c__DisplayClass63_0.<<RunInlineAsync>b__1>d.MoveNext() in /_/sdk/dotnet/Pulumi/Deployment/Deployment_Inline.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at Pulumi.Automation.WorkspaceStack.PreviewAsync(PreviewOptions options, CancellationToken cancellationToken) in /_/sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs:line 422
   at Pulumi.Automation.WorkspaceStack.PreviewAsync(PreviewOptions options, CancellationToken cancellationToken) in /_/sdk/dotnet/Pulumi.Automation/WorkspaceStack.cs:line 445
   at Pulumi.Automation.Tests.LocalWorkspaceTests.StackLifecycleInlineProgram() in /Users/runner/work/pulumi/pulumi/sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs:line 482
   at Pulumi.Automation.Tests.LocalWorkspaceTests.StackLifecycleInlineProgram() in /Users/runner/work/pulumi/pulumi/sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs:line 499
```

**Comment by komalali** [comment]
From @orionstudt:
>I think this is because the existing Runner class that is doing all of that task tracking is not very resilient so the automation api now depending on that class has exposed the issues with it. There's probably a race condition in that class with the way that it is throwing tasks into the dictionary and then checking for them later. So that class needs a refactor I think. I talked about this with Anton in that PR

**Comment by orionstudt** [comment]
Hey @t0yv0 I think this is related to [our discussion here.](https://github.com/pulumi/pulumi/pull/7323#issuecomment-865149288) I guess that refactor is needed sooner rather than later. I suspect that now that Automation API SDK is correctly tracking all of it's tasks in the Runner class we have exposed the resiliency issues with it - as evidenced by these race conditions we are seeing.

I think short of a full refactor a good/quick solution would be to add some locking around access to [this dictionary](https://github.com/pulumi/pulumi/blob/30278f8e4c08cae561b2ab3078a1a14d4ccabafa/sdk/dotnet/Pulumi/Deployment/Deployment.Runner.cs#L32), or maybe consider using a `ConcurrentDictionary` instead.

**Comment by t0yv0** [comment]
Looking at this "real soon now" ™️
