### ISSUE TITLE
Pulumi Dynamic Providers don't support importing resources

### ISSUE THREAD

**Issue by pbzdyl** [pulumi/pulumi#7534]
Pulumi native providers support [`pulumi import`](https://www.pulumi.com/docs/reference/cli/pulumi_import/). Thus workarounds must be used that make the dynamic provider implementation awkward.

Current workaround that I currently use:
- specify additional boolean input property, e.g. `import: boolean`
- if the flag is set, in the dynamic provider `check` and `create` verify that the declared inputs match the state of the existing resource; if they do, pass `check` without failures and in the `create` just return success without actually creating remote reource

**Comment by flovilmart** [comment]
Got an issue as well trying to mark dynamic provider resources with `import: 'external-id'` 

```
Error: code must be a string, not undefined: Error: code must be a string, not undefined
        at requireFromString (node_modules/.pnpm/require-from-string@2.0.2/node_modules/require-from-string/index.js:19:9)
        at getProvider (node_modules/.pnpm/@pulumi+pulumi@3.33.2/node_modules/@pulumi/cmd/dynamic-provider/index.ts:92:14)
        at Object.<anonymous> (node_modules/.pnpm/@pulumi+pulumi@3.33.2/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:247:24)
        at Generator.next (<anonymous>)
        at node_modules/.pnpm/@pulumi+pulumi@3.33.2/node_modules/@pulumi/cmd/dynamic-provider/index.ts:43:35
        at new Promise (<anonymous>)
        at __awaiter (node_modules/.pnpm/@pulumi+pulumi@3.33.2/node_modules/@pulumi/cmd/dynamic-provider/index.ts:18:1)
        at Object.readRPC [as read] (node_modules/.pnpm/@pulumi+pulumi@3.33.2/node_modules/@pulumi/cmd/dynamic-provider/index.ts:251:7)
        at handleUnary (node_modules/.pnpm/@grpc+grpc-js@1.3.8/node_modules/@grpc/grpc-js/src/server.ts:667:11)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by Frassle** [comment]
Duplicate of https://github.com/pulumi/pulumi/issues/3550
