### ISSUE TITLE
Eliminate threading from the Python SDK

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#7663]
Please consider eliminating threading use from the Python SDK in favor of heavily leaning on asynchronous IO.

Fix outline:

1. switch to AIO-based gRPC clients for the engine and monitor, making those async - see https://grpclib.readthedocs.io/en/latest/

```
python -m grpc_tools.protoc -I./ --python_out="$TEMP_DIR" --grpclib_python_out="$TEMP_DIR" *.proto
```

2. switch mocks to async IO

3. search for all instances of code similar to the following `await asyncio.get_event_loop().run_in_executor(None, do_invoke)` and replace with forking AIO coroutines; currently `run_in_executor` uses default ThreadPoolExecutor, we essentially jump threads on every Invoke, RegisterResource, and so on, to make sure gRPC calls are non-blocking

4. Search for ThreadPoolExecutor and replace the callsites, which appear to be gRPC *server* instances, with AIO-based servers

We could break this up as appropriate.

If this becomes a breaking change, we could build out a parallel set of classes such as AIOMonitorClient and gradually transition code, with env vars to back out.

## Affected feature

As an immediate benefit this will remove issues related to several AIO loops on different threads https://github.com/pulumi/pulumi/issues/6561

Indirectly, this will also contribute to scalability and stability of the SDK. Python AIO loops should be capable of cheaper context switches than threading. Note that Python programs using threading still enter the Global Interpreter Lock when entering Python code and thus only speed things up for the situation of waiting on IO in native code.

**Comment by t0yv0** [comment]
CC @emiliza logging this for later as discussed.

**Comment by t0yv0** [comment]
AS @komalali rightly points out we also need to tackle e #6762  before or concurrently with this, since putting more things onto the shared AIO loop on the main thread will introduce accidental waits unless #6762 can distinguish pulumi tasks from non-pulumi tasks (such as internal tasks of the gRPC servers and clients).

**Comment by ahmed-wajid** [comment]
This keeps raising sometimes with flaky Pytests. But meanwhile, it raises pretty often when we run Automation API, with celery for async tasks. 

```
Resources:
    + 6 created
    17 unchanged

Duration: 1m57s
 stderr: error: python inline source runtime error: Task <Task pending name='Task-27816' coro=<run_in_stack() running at /usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py:136> cb=[_run_until_complete_cb() at /usr/local/lib/python3.10/asyncio/base_events.py:184]> got Future <Task pending name='Task-26658' coro=<register_resource.<locals>.do_register() running at /usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py:811> wait_for=<Task pending name='Task-25021' coro=<Output.__init__.<locals>.is_value_known() running at /usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/output.py:103> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup(), <2 more>, Task.task_wakeup()]> cb=[Task.task_wakeup()]> attached to a different loop
Traceback (most recent call last):
  File "/usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/automation/_server.py", line 81, in Run
    loop.run_until_complete(run_in_stack(self.program))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 136, in run_in_stack
    await run_pulumi_func(lambda: Stack(func))
  File "/usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
    await wait_for_rpcs()
  File "/usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 74, in wait_for_rpcs
    await RPC_MANAGER.rpcs.pop()
RuntimeError: Task <Task pending name='Task-27816' coro=<run_in_stack() running at /usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py:136> cb=[_run_until_complete_cb() at /usr/local/lib/python3.10/asyncio/base_events.py:184]> got Future <Task pending name='Task-26658' coro=<register_resource.<locals>.do_register() running at /usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py:811> wait_for=<Task pending name='Task-25021' coro=<Output.__init__.<locals>.is_value_known() running at /usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/output.py:103> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup(), <2 more>, Task.task_wakeup()]> cb=[Task.task_wakeup()]> attached to a different loop

error: an unhandled error occurred: python inline source runtime error: Task <Task pending name='Task-27816' coro=<run_in_stack() running at /usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py:136> cb=[_run_until_complete_cb() at /usr/local/lib/python3.10/asyncio/base_events.py:184]> got Future <Task pending name='Task-26658' coro=<register_resource.<locals>.do_register() running at /usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py:811> wait_for=<Task pending name='Task-25021' coro=<Output.__init__.<locals>.is_value_known() running at /usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/output.py:103> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup(), <2 more>, Task.task_wakeup()]> cb=[Task.task_wakeup()]> attached to a different loop
Traceback (most recent call last):
  File "/usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/automation/_server.py", line 81, in Run
    loop.run_until_complete(run_in_stack(self.program))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 136, in run_in_stack
    await run_pulumi_func(lambda: Stack(func))
  File "/usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
    await wait_for_rpcs()
  File "/usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 74, in wait_for_rpcs
    await RPC_MANAGER.rpcs.pop()
RuntimeError: Task <Task pending name='Task-27816' coro=<run_in_stack() running at /usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py:136> cb=[_run_until_complete_cb() at /usr/local/lib/python3.10/asyncio/base_events.py:184]> got Future <Task pending name='Task-26658' coro=<register_resource.<locals>.do_register() running at /usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py:811> wait_for=<Task pending name='Task-25021' coro=<Output.__init__.<locals>.is_value_known() running at /usr/src/extollo/.venv/lib/python3.10/site-packages/pulumi/output.py:103> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[Task.task_wakeup(), <2 more>, Task.task_wakeup()]> cb=[Task.task_wakeup()]> attached to a different loop

```

We are running celery with prefork workers in Azure Kubernetes environment. This happens sporadically and hence we are also not able to reproduce this in a consistent manner. One thing we could say is that it happens when there are many tasks in the queue, and many queued tasks fail at the same time with this error, or some tasks randomly fail with this. Could you please suggest a workaround for this? Or prio this issue?

**Comment by jaketbouma** [comment]
In the early stages of a dummy python project to try out Component Resources, I hit **flaky pytests** that sometimes ran fine and sometimes hung infinitely. ([tests and environment](https://github.com/jaketbouma/demo-components/blob/c4781d1dd238f2b8af5da6cd54cceda643836016/mycomponents/tests/test_pulumi.py), [analysis](https://github.com/jaketbouma/demo-components/issues/1))

Found my way here, and dropping this code in to my own tests did the trick. https://github.com/pulumi/pulumi/blob/da70a80fcfd37b8b32fc736a167ca15173bbb00d/sdk/python/lib/test_with_mocks/test_testing_with_mocks.py#L27

I'm surprised I'm the only one hitting on this 😅
