### ISSUE TITLE
Ability to upgrade provider versions for existing resources

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi#7702]
Currently when provider versions are upgraded in a stack, existing resources still try to use the provider version used to create the stack. In order to update existing resources, these will need to be recreated. It is desirable to update existing resources to at least newer minor revisions of the provider. 

Currently the workarounds here are unsavory:
1. Place the updated provider in $PATH
2. Statefile editing
3. Set PULUMI_ENABLE_LEGACY_PLUGIN_SEARCH=true

**Comment by viveklak** [comment]
See https://github.com/pulumi/pulumi/issues/5641

**Comment by pgavlin** [comment]
@viveklak updating the SDK used by the Pulumi program should update the provider versions as well without recreating the resources. Is that not happening?

**Comment by LucasBrazi06** [comment]
Same problem here, new fix has been provided in plugin 'kubernetes' V3.21.1 but it still uses the V3.20.2 when doing 'pulumi up'!!!
pulumi/pulumi-kubernetes#2249

**Comment by chapmanjacobd** [comment]
yeah this is pretty annoying

```
Diagnostics:
  pulumi:pulumi:Stack (jacob):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "pulumi/__main__.py", line 14, in <module>
        schedule_cloud_batch(
      File "pulumi/utils.py", line 212, in schedule_cloud_batch
        cr.JobIamMember(
        ^^^^^^^^^^^^^^^
    AttributeError: module 'pulumi_gcp.cloudrunv2' has no attribute 'JobIamMember'
```

```
$ pulumi plugin rm resource gcp
This will remove 2 plugins from the cache:
    resource gcp-6.47.0
    resource gcp-6.50.0
Please confirm that this is what you'd like to do by typing `yes`: yes

$ pulumi plugin install resource gcp --reinstall
[resource plugin gcp-6.50.0] installing
```

Then when doing pulumi refresh or pulumi up, even though I only have gcp-6.50.0 installed, it chooses to try the old version.

```
Downloading plugin gcp v6.47.0: 46.59 MiB / 46.59 MiB [=============] 100.00% 1s
```

**Comment by jamest-pin** [comment]
Just ran into this issue. I was not in production so I could destroy my stack and recreate it. What if this was a production environment?

**Comment by raphaelauv** [comment]
this issue is still present ? thanks

**Comment by Frassle** [comment]
I think `pulumi refresh --run-program` should help with this now, that will re-register the resources with the version of the provider declared by the program.
