### ISSUE TITLE
example：aws ec2 get_network_interfaces 

### ISSUE THREAD

**Issue by Rick6652** [pulumi/pulumi#7729]
## Affected feature
I need an example:how to use this module.
I want to get all the network interface IDS, but my operation is wrong.

network_interfaces = aws.ec2.get_network_interfaces()
pulumi.export("network_interfaces", network_interfaces.ids)

Diagnostics:
  pulumi:pulumi:Stack (aws-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "D:\soft\Pulumi\bin\pulumi-language-python-exec", line 92, in <module>
        loop.run_until_complete(coro)
      File "D:\soft\Python 3.9\lib\asyncio\base_events.py", line 642, in run_until_complete
        return future.result()
      File "D:\aws\venv\lib\site-packages\pulumi\runtime\stack.py", line 110, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "D:\aws\venv\lib\site-packages\pulumi\runtime\stack.py", line 43, in run_pulumi_func
        func()
      File "D:\aws\venv\lib\site-packages\pulumi\runtime\stack.py", line 110, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "D:\aws\venv\lib\site-packages\pulumi\runtime\stack.py", line 133, in __init__
        func()
      File "D:\soft\Pulumi\bin\pulumi-language-python-exec", line 91, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "D:\soft\Python 3.9\lib\runpy.py", line 285, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "D:\soft\Python 3.9\lib\runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File ".\__main__.py", line 14, in <module>
        security_groups = aws.ec2.get_security_groups()
      File "D:\aws\venv\lib\site-packages\pulumi_aws\ec2\get_security_groups.py", line 119, in get_security_groups
        __ret__ = pulumi.runtime.invoke('aws:ec2/getSecurityGroups:getSecurityGroups', __args__, opts=opts, typ=GetSecurityGroupsResult).value
      File "D:\aws\venv\lib\site-packages\pulumi\runtime\invoke.py", line 146, in invoke
        raise invoke_error
    Exception: invoke of aws:ec2/getSecurityGroups:getSecurityGroups failed: invocation of aws:ec2/getSecurityGroups:getSecurityGroups returned an error: invoking aws:ec2/getSecurityGroups:getSecurityGroups: 1 error occurred:
        * One of filters or tags must be assigned
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

**Comment by emiliza** [comment]
Hey @Rick6652 - here's an example for using `aws.ec2.get_network_interfaces()` : https://github.com/pulumi/pulumi-aws/blob/master/sdk/python/pulumi_aws/ec2/get_network_interfaces.py#L81-L116

Actually looks like your error is when trying to call `security_groups = aws.ec2.get_security_groups()` - it's asking for at least one of tags or filters to be passed, check the example here: https://github.com/pulumi/pulumi-aws/blob/master/sdk/python/pulumi_aws/ec2/get_security_groups.py#L108-L134
