### ISSUE TITLE
Remove pulumi-test dependency when running make test_all

### ISSUE THREAD

**Issue by emiliza** [pulumi/pulumi#7776]
We want external developers to be able to run these tests, but sadly `make test_all` fails due to:

```
 1) LocalWorkspace create/select/remove LocalWorkspace stack:
     CommandError: code: 255
 stdout: 
 stderr: error: could not create stack: [404] Not Found: Organization 'pulumi-test' not found

 err?: 

      at Object.createCommandError (bin/automation/errors.js:71:17)
      at ChildProcess.<anonymous> (bin/automation/cmd.js:63:40)
      at ChildProcess.emit (node:events:394:28)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

We could consider flagging these off by default and then have people opt-in to running them

Current workaround:
Set the `PULUMI_TEST_ORG` to your pulumi username (likely your github name) and that should allow you to run all the automation API tests under your user org

**Comment by t0yv0** [comment]
There is also `pulumi whoami` that can help with defaulting but we probably need to ask the users' permission explicitly first before deploying test stacks into their account.

**Comment by tgummerer** [comment]
Marking this as `kind/engineering`, since it's not a bug in the product. We also started making some progress towards this with https://github.com/pulumi/pulumi/pull/17393 (and more is still to come, slowly)
