### ISSUE TITLE
[sdk/python] Error when a resource args class is passed to a resource that's been imported differently

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#7818]
This program which passes `BucketArgs` to `s3.Bucket`:

```python
from pulumi import ResourceOptions
from pulumi_aws import s3
from pulumi_aws.s3.bucket import BucketArgs
bucket = s3.Bucket('my-bucket', BucketArgs(), opts=ResourceOptions())
```

And this program which passes `s3.BucketArgs` to `Bucket`:

```python
from pulumi import ResourceOptions
from pulumi_aws import s3
from pulumi_aws.s3.bucket import Bucket
bucket = Bucket('my-bucket', s3.BucketArgs(), opts=ResourceOptions())
```

Both result in the following error when running `pulumi up`:

```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/opt/pulumi/bin/pulumi-language-python-exec", line 92, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/Users/user/Desktop/bucketargs/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 110, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/user/Desktop/bucketargs/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 43, in run_pulumi_func
        func()
      File "/Users/user/Desktop/bucketargs/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 110, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/user/Desktop/bucketargs/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 133, in __init__
        func()
      File "/opt/pulumi/bin/pulumi-language-python-exec", line 91, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 285, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/Users/user/Desktop/bucketargs/./__main__.py", line 4, in <module>
        bucket = s3.Bucket('my-bucket', BucketArgs(), opts=ResourceOptions())
      File "/Users/user/Desktop/bucketargs/venv/lib/python3.9/site-packages/pulumi_aws/s3/bucket.py", line 1420, in __init__
        __self__._internal_init(resource_name, *args, **kwargs)
    TypeError: _internal_init() got multiple values for argument 'opts'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

However, this program which uses consistent imports for both the resource and resource args works correctly without error:

```python
from pulumi import ResourceOptions
from pulumi_aws import s3
bucket = s3.Bucket('my-bucket', s3.BucketArgs(), opts=ResourceOptions())
```

Apparently, when the types are imported in these different ways, they don't work correctly with `isinstance`:

```python
from pulumi_aws import s3
from pulumi_aws.s3.bucket import BucketArgs
args = BucketArgs()
print(f"A: {isinstance(args, BucketArgs)}")
print(f"B: {isinstance(args, s3.BucketArgs)}")
```

Output:

```
A: True
B: False
```

Which is tripping up this check in the generated Python SDK for a provider:

https://github.com/pulumi/pulumi/blob/da2bd2ab043f2588b3a136846da1b97505326f25/pkg/codegen/python/gen.go#L2781-L2791

Which is used by generated resource classes like [Bucket](https://github.com/pulumi/pulumi-aws/blob/9ecc0872df7cd61bb39e0a3cb1edb49dcb0cfcad/sdk/python/pulumi_aws/s3/bucket.py#L1415-L1420):

```python
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(BucketArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)
```

| Package | Version |
|---|---|
| pulumi | 3.10.3 |
| pulumi-aws | 4.17.0 |

**Comment by justinvp** [comment]
I'm wondering if this is a double import type of issue (like https://bugs.python.org/issue467267), or if it's due to how we lazily load submodules.

**Comment by julienp** [comment]
I This is due to the lazy import mechanism we have. When I change the import in `aws/__init__.py` for S3 to a normal import instead of the lazy import, it works.
