### ISSUE TITLE
TestEngineEventPerf inconsistent failure

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi#7883]
See https://github.com/pulumi/pulumi/pull/7877/checks?check_run_id=3469114554
Rerun succeeded. Recording the error here for posterity.

```
 --- FAIL: TestEngineEventPerf (36.99s)
Error:              program.go:1553: sample: ee_perf
Error:              program.go:1558: pulumi: D:\Pulumi\bin\pulumi.exe
Error:              command.go:34: **** Invoke 'C:\npm\prefix\yarn.cmd install' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945'
Error:              command.go:97: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945\command-output\yarn-install.20210831-045801.49c3c.log
Error:              command.go:34: **** Invoke 'C:\npm\prefix\yarn.cmd link @pulumi/pulumi' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945'
Error:              command.go:97: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945\command-output\yarn-link.20210831-045809.1d1df.log
Error:              program.go:1621: projdir: C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945
Error:              program.go:1082: Initializing project (dir C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945; stack p-it-fv-az177-9-ee_perf-13bf6c3b)
Error:              command.go:34: **** Invoke 'D:\Pulumi\bin\pulumi.exe login' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945'
Error:              command.go:97: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945\command-output\pulumi-login.20210831-045810.c7adf.log
Error:              command.go:34: **** Invoke 'D:\Pulumi\bin\pulumi.exe stack init moolumi/p-it-fv-az177-9-ee_perf-13bf6c3b' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945'
Error:              command.go:97: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945\command-output\pulumi-stack-init.20210831-045810.62da6.log
Error:              program.go:1175: Performing primary preview and update
Error:              command.go:34: **** Invoke 'D:\Pulumi\bin\pulumi.exe up --non-interactive --yes --skip-preview --event-log C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-events.json' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945'
Error:              integration_test.go:54: Test step "pulumi-update-initial" took longer than expected. 8.61s vs. max 8.00s
Error:              command.go:97: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945\command-output\pulumi-update-initial.20210831-045819.c1e42.log
Error:              command.go:34: **** Invoke 'D:\Pulumi\bin\pulumi.exe refresh --non-interactive --yes --skip-preview --expect-no-changes' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945'
Error:              command.go:97: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945\command-output\pulumi-refresh.20210831-045821.fcb1c.log
Error:              program.go:1150: Destroying stack
Error:              command.go:34: **** Invoke 'D:\Pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945'
Error:              command.go:97: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az177-9-ee_perf-13bf6c3b-943523945\command-output\pulumi-destroy.20210831-045822.568df.log
Error:              program.go:1160: Test failed, retaining stack 'moolumi/p-it-fv-az177-9-ee_perf-13bf6c3b'
         Deployment: &{{2021-08-31 05:14:14.7033708 +0000 UTC 6a0f72e8c09606c30b217032e38bf17a49fe8076a62d4ea827eed0f0e558d0b8 v3.12.0-alpha.1630384196+3efe4d30.dirty []} 0xc000924240 [{urn:pulumi:p-it-fv-az177-9-python-3aae90c4::stack_outputs_py::pulumi:pulumi:Stack::stack_outputs_py-p-it-fv-az177-9-python-3aae90c4 false false  pulumi:pulumi:Stack map[] map[foo:42 xyz:ABC]  false false [] []  map[] false [] [] <nil> }] []}Updating (moolumi/p-it-fv-az177-9-python-bro-536892a2)
         
         View Live: https://app.pulumi.com/moolumi/dynamic_broken_py/p-it-fv-az177-9-python-bro-536892a2/updates/1
         
         
          +  pulumi:pulumi:Stack dynamic_broken_py-p-it-fv-az177-9-python-bro-536892a2 creating 
          +  pulumi-python:dynamic:Resource my_x creating 
          +  pulumi-python:dynamic:Resource my_x created 
          +  pulumi:pulumi:Stack dynamic_broken_py-p-it-fv-az177-9-python-bro-536892a2 creating error: Program failed with an unhandled exception:
          +  pulumi:pulumi:Stack dynamic_broken_py-p-it-fv-az177-9-python-bro-536892a2 creating error: Traceback (most recent call last):
          +  pulumi:pulumi:Stack dynamic_broken_py-p-it-fv-az177-9-python-bro-536892a2 creating error: an unhandled error occurred: Program exited with non-zero exit code: 1
          +  pulumi:pulumi:Stack dynamic_broken_py-p-it-fv-az177-9-python-bro-536892a2 **creating failed** 3 errors
          
         Diagnostics:
           pulumi:pulumi:Stack (dynamic_broken_py-p-it-fv-az177-9-python-bro-536892a2):
     1>EXEC : error : Program failed with an unhandled exception: [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
     1>EXEC : error : Traceback (most recent call last): [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
               File "D:\Pulumi\bin\pulumi-language-python-exec", line 92, in <module>
                 loop.run_until_complete(coro)
               File "C:\hostedtoolcache\windows\Python\3.9.6\x64\lib\asyncio\base_events.py", line 642, in run_until_complete
                 return future.result()
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\runtime\stack.py", line 110, in run_in_stack
                 await run_pulumi_func(lambda: Stack(func))
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\runtime\stack.py", line 45, in run_pulumi_func
                 await wait_for_rpcs()
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\runtime\stack.py", line 94, in wait_for_rpcs
                 raise exception
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\output.py", line 158, in run
                 is_known = await self._is_known
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\runtime\rpc_manager.py", line 65, in rpc_wrapper
                 result = await rpc
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\output.py", line 94, in is_value_known
                 return await is_known and not contains_unknowns(await future)
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\output.py", line 94, in is_value_known
                 return await is_known and not contains_unknowns(await future)
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\runtime\resource.py", line 564, in do_register
                 rpc.resolve_outputs(res, resolver.serialized_props, resp.object, deps, resolvers, transform_using_type_metadata)
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\runtime\rpc.py", line 765, in resolve_outputs
                 translated_value = translate_output_properties(value, translate_to_pass, types.get(key),
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\runtime\rpc.py", line 652, in translate_output_properties
                 return {
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\runtime\rpc.py", line 654, in <dictcomp>
                 translate_output_properties(v,
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\runtime\rpc.py", line 648, in translate_output_properties
                 raise AssertionError((f"Unexpected type; expected a value of type `{typ}`"
             AssertionError: Unexpected type; expected a value of type `<class 'str'>` but got a value of type `<class 'dict'>` at resource `my_x`, property `x.my_key_1`: {'extra_buggy_key': 'my_value_1!'}
     1>error : an unhandled error occurred: Program exited with non-zero exit code: 1 [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
          
         Resources:
             + 2 created
         
         Duration: 5s
         
         
         Logging in using access token from PULUMI_ACCESS_TOKEN
         Logging in using access token from PULUMI_ACCESS_TOKEN
     1>EXEC : warning : you are now using 76516 of 0 stacks - manage stack limits for your organization at https://app.pulumi.com/moolumi/settings/subscription [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
     1>EXEC : warning : you are now using 76519 of 0 stacks - manage stack limits for your organization at https://app.pulumi.com/moolumi/settings/subscription [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         Deployment: &{{2021-08-31 05:15:54.9991486 +0000 UTC 6a0f72e8c09606c30b217032e38bf17a49fe8076a62d4ea827eed0f0e558d0b8 v3.12.0-alpha.1630384196+3efe4d30.dirty []} 0xc000663ec0 [{urn:pulumi:p-it-fv-az177-9-nodejs-e396ffcf::stack_outputs::pulumi:pulumi:Stack::stack_outputs-p-it-fv-az177-9-nodejs-e396ffcf false false  pulumi:pulumi:Stack map[] map[foo:42 xyz:ABC]  false false [] []  map[] false [] [] <nil> }] []}Deployment: &{{2021-08-31 05:17:49.5168101 +0000 UTC 6a0f72e8c09606c30b217032e38bf17a49fe8076a62d4ea827eed0f0e558d0b8 v3.12.0-alpha.1630384196+3efe4d30.dirty []} 0xc000953830 [{urn:pulumi:p-it-fv-az177-9-dotnet_ser-9b885983::dotnet_service_provider::pulumi:pulumi:Stack::dotnet_service_provider-p-it-fv-az177-9-dotnet_ser-9b885983 false false  pulumi:pulumi:Stack map[] map[Foo:42 abc:ABC]  false false [] []  map[] false [] [] <nil> }] []}Deployment: &{{2021-08-31 05:17:59.1663347 +0000 UTC 6a0f72e8c09606c30b217032e38bf17a49fe8076a62d4ea827eed0f0e558d0b8 v3.12.0-alpha.1630384196+3efe4d30.dirty []} 0xc0008231a0 [{urn:pulumi:p-it-fv-az177-9-dotnet-4e4a6f03::stack_compoennt::pulumi:pulumi:Stack::stack_compoennt-p-it-fv-az177-9-dotnet-4e4a6f03 false false  pulumi:pulumi:Stack map[] map[Foo:42 abc:ABC]  false false [] []  map[] false [] [] <nil> }] []}Deployment: &{{2021-08-31 05:18:06.1234402 +0000 UTC 6a0f72e8c09606c30b217032e38bf17a49fe8076a62d4ea827eed0f0e558d0b8 v3.12.0-alpha.1630384196+3efe4d30.dirty []} 0xc0008b04b0 [{urn:pulumi:p-it-fv-az177-9-dotnet-b48d4469::stack_outputs::pulumi:pulumi:Stack::stack_outputs-p-it-fv-az177-9-dotnet-b48d4469 false false  pulumi:pulumi:Stack map[] map[foo:42 xyz:ABC]  false false [] []  map[] false [] [] <nil> }] []}FAIL
         coverage: [no statements]
         FAIL	github.com/pulumi/pulumi/tests/integration	1867.806s
         FAIL
         The command "go test -timeout 1h -cover -parallel 20 -tags=all .\integration" exited with code 1.
       Done executing task "Exec".
       Using "Error" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
       Task "Error"
     1>D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj(362,5): error : integration tests (.\tests\integration) failed
       Done executing task "Error" -- FAILED.
     1>Done building target "Tests" in project "build.proj" -- FAILED.
     1>Done Building Project "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target(s)) -- FAILED.

Build FAILED.

       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
       (TestDependencies target) -> 
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         EXEC : warning pulumi-resource-testcomponent: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         EXEC : warning pulumi-resource-testcomponent: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         EXEC : warning pulumi-resource-testcomponent: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         EXEC : warning pulumi-resource-testcomponent: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         EXEC : warning pulumi-resource-testcomponent: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         EXEC : warning pulumi-resource-testcomponent: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         EXEC : warning pulumi-resource-testcomponent: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         EXEC : warning pulumi-resource-testcomponent: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         EXEC : warning pulumi-resource-testcomponent: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
       (TestBuild target) -> 
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
       (Tests target) -> 
         EXEC : warning : you are now using 76516 of 0 stacks - manage stack limits for your organization at https://app.pulumi.com/moolumi/settings/subscription [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         EXEC : warning : you are now using 76519 of 0 stacks - manage stack limits for your organization at https://app.pulumi.com/moolumi/settings/subscription [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
       (Tests target) -> 
         EXEC : error : Program failed with an unhandled exception: [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         EXEC : error : Traceback (most recent call last): [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         error : an unhandled error occurred: Program exited with non-zero exit code: 1 [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


       "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target) (1) ->
         D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj(362,5): error : integration tests (.\tests\integration) failed

    38 Warning(s)
```

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi/pull/7899/checks?check_run_id=3702752010

   --- FAIL: TestEngineEventPerf (53.94s) (?)

Repeat occurrence.

 https://github.com/pulumi/pulumi/pull/7899
