### ISSUE TITLE
Panic when using `iam.RoleArrayOutput.Index` in Go

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#7897]
Hitting an issue with cluster.InstanceRoles.Index in Go against pulumi-eks and pulumi-aws. I suspect this might be a codegen or SDK related issue so filling here:

## Steps to reproduce

```go

package main

import (
	"github.com/pulumi/pulumi-eks/sdk/go/eks"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		cluster, err := eks.NewCluster(ctx, "example", &eks.ClusterArgs{})
		if err != nil {
			return err
		}
		cluster.InstanceRoles.Index(pulumi.Int(0))
		return nil
	})
}
```

```
    panic: interface conversion: pulumi.Output is pulumi.AnyOutput, not iam.RoleOutput
    goroutine 1 [running]:
    github.com/pulumi/pulumi-aws/sdk/v4/go/aws/iam.RoleArrayOutput.Index(0xc0003d44d0, 0x20c4080, 0x2077960, 0xc0005ea300)
    	/Users/anton/go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.18.0/go/aws/iam/role.go:665 +0x1a6
    main.main.func1(0xc0004aa140, 0x1f6d936, 0x13)
    	/Users/anton/tmp/repro-7862/go1/main.go:21 +0xc5
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc0004aa140, 0x1fa7b60, 0xc000042087, 0x2)
    	/Users/anton/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.11.0/go/pulumi/run.go:103 +0x206
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunErr(0x1fa7b60, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/Users/anton/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.11.0/go/pulumi/run.go:84 +0x23f
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.Run(0x1fa7b60, 0x0, 0x0, 0x0)
    	/Users/anton/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.11.0/go/pulumi/run.go:41 +0x59
    main.main()
    	/Users/anton/tmp/repro-7862/go1/main.go:11 +0x3e
    exit status 2
 
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

go.mod:

```
module go1

go 1.16

require (
	github.com/pulumi/pulumi-aws/sdk/v4 v4.18.0
	github.com/pulumi/pulumi-eks/sdk v0.33.0 // indirect
	github.com/pulumi/pulumi/sdk/v3 v3.11.0
)
```

```
pulumi version
v3.11.0
```

Expected: non-compiling program, or runtime error
Actual: panic

**Comment by emiliza** [comment]
@pgavlin please document the workaround, thanks!

**Comment by t0yv0** [comment]
Generally `.Index` is a helper to find nth element of the array so the workaround here is not use it but use the full Apply forms.

From https://github.com/pulumi/pulumi/issues/7890

```go
NodeRoleArn: cluster.InstanceRoles.
					ApplyT(func(roles *[]iam.Role) pulumi.StringOutput {
						return (*roles)[0].Arn
					}).
					ApplyT(func(x interface{}) string {
						return x.(string)
					}).(pulumi.StringOutput),
```

If Int is not known but is an Input then it can be paired in with All.

**Comment by pgavlin** [comment]
...what @t0yv0 said!

**Comment by Zaid-Ajaj** [comment]
Will be closing this issue as _fixed_. Consider re-opening if this or similar issue occurs
