### ISSUE TITLE
Panic after recovering from a Pulumi CLI interruption

### ISSUE THREAD

**Issue by dmelo** [pulumi/pulumi#7908]
I have forced interruption on `pulumi up`. When I tried to issue a new command, it guided me to check manually the creation state of a resource. I did so, imported back the update state into the stack.

From that point on, `pulumi up`, `pulumi update`, `pulumi destroy`, they all give me the same panic message.

## Steps to reproduce

1. copy `__main__.py` file from https://github.com/pulumi/examples/tree/master/aws-py-fargate
2. `pulumi up` and approve plan
3. kill pulumi before it ends
4. pulumi stack export, fix states of pending resources, pulumi stack import

Expected: Resume pulumi usage, so I can update and/or destroy the stack...
Actual: Pulumi stops with a panic message:

```
goroutine 76 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*provider).Diff(0xc001241c80, 0xc001477b30, 0x48, 0x0, 0x0, 0xc0011e19e0, 0xc00193fd70, 0x1, 0x0, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/provider_plugin.go:611 +0x15f7
github.com/pulumi/pulumi/pkg/v3/resource/deploy.diffResource(0xc001477b30, 0x48, 0x0, 0x0, 0xc0011e19b0, 0xc0011e19e0, 0xc00193fd70, 0x2195ef8, 0xc001241c80, 0xc0012dcb01, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1088 +0x13a
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).diff(0xc0015345a0, 0xc001477b30, 0x48, 0xc00148d9e0, 0xc001a56fc0, 0xc0011e19b0, 0xc0011e19e0, 0xc00193fd70, 0x2195ef8, 0xc001241c80, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:1076 +0x277
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).generateStepsFromDiff(0xc0015345a0, 0x7f752a306598, 0xc00192b3c0, 0xc001477b30, 0x48, 0xc00148d9e0, 0xc001a56fc0, 0xc0011e19b0, 0xc0011e19e0, 0xc00193fd70, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:514 +0x125
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).generateSteps(0xc0015345a0, 0x7f752a306598, 0xc00192b3c0, 0x1, 0xc001009c80, 0xc0018a59f8, 0x44a937, 0xc000991200)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:447 +0x101b
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).GenerateSteps(0xc0015345a0, 0x7f752a306598, 0xc00192b3c0, 0x7f752a306598, 0xc00192b3c0, 0x1, 0x2, 0x469460)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:152 +0x5a
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).handleSingleEvent(0xc00098e9a8, 0x21443e0, 0xc00192b3c0, 0x0, 0x2)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:372 +0x13f
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute.func3(0xc000991200, 0xc00098e9a8, 0xc0015383c0, 0x21737b0, 0xc0008e9340, 0x0, 0x0, 0x2173858, 0xc001536120, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:242 +0x20c
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute(0xc00098e9a8, 0x2173858, 0xc001536120, 0x7f7529f83670, 0xc0014a2000, 0x7fffffff, 0x0, 0x2df4630, 0x0, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:258 +0x7e5
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Deployment).Execute(...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:409
github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run.func1(0x217df28, 0xc0014a2000, 0xc0009b0dc0, 0x2173858, 0xc001536120, 0xc001536101, 0xc001538330, 0xc000990d20)
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:260 +0x287
created by github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:245 +0x308
```

**Comment by emiliza** [comment]
I'm unable to reproduce this - can you provide more information on which version of Pulumi you're using? And perhaps some insights on what you did for fixing the pending resources states?  When attempting to repro -  I just nuked the pending operations, re-imported, and `pulumi up` worked without panic
