### ISSUE TITLE
Running pulumi about results in panic -- "interface {} is nil, not string"

### ISSUE THREAD

**Issue by tdorianh** [pulumi/pulumi#7942]
Just upgraded to Pulumi v3.12.0, and now running `pulumi about` always results in a panic.

## Steps to reproduce

1.  run `pulumi about`

Expected:  normal output
Actual: . go panic

Here is the output from running the command:

```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.12.0
Go Version:       go1.17
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            interface conversion: interface {} is nil, not string

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/Cellar/go/1.17/libexec/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/private/tmp/pulumi-20210909-33633-18beiyj/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x5443820, 0xc00023af90})
	/usr/local/Cellar/go/1.17/libexec/src/runtime/panic.go:1038 +0x215
main.getNodeProgramDependencies({0xc00017ed70, 0x37}, 0x0)
	/private/tmp/pulumi-20210909-33633-18beiyj/pkg/cmd/pulumi/about.go:705 +0x1be5
main.getProgramDependenciesAbout(0xc000915828, {0xc00017ed70, 0x2000}, 0x0)
	/private/tmp/pulumi-20210909-33633-18beiyj/pkg/cmd/pulumi/about.go:766 +0x8c
main.getSummaryAbout(0x12)
	/private/tmp/pulumi-20210909-33633-18beiyj/pkg/cmd/pulumi/about.go:148 +0x4e5
main.newAboutCmd.func1(0x0, {0x7020106, 0x0, 0xc000915d78})
	/private/tmp/pulumi-20210909-33633-18beiyj/pkg/cmd/pulumi/about.go:77 +0x45
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunFunc.func1(0xd, {0x682bb28, 0xc000915d90, 0x41eacf3})
	/private/tmp/pulumi-20210909-33633-18beiyj/sdk/go/common/util/cmdutil/exit.go:96 +0x26
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc00096b8c0, {0x682bb28, 0x0, 0x0})
	/private/tmp/pulumi-20210909-33633-18beiyj/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc00096b8c0, {0x682bb28, 0x0, 0x0})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003eb340)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/private/tmp/pulumi-20210909-33633-18beiyj/pkg/cmd/pulumi/main.go:48 +0x45
```

**Comment by tdorianh** [comment]
Got this error repeatedly, but now when I run `pulumi about` in the same situation, I am no longer able to reproduce the issue. Not sure cause/fix on this one
