### ISSUE TITLE
"pulumi stack ls" failed to decrypt value

### ISSUE THREAD

**Issue by momoliu-msft** [pulumi/pulumi#7991]
"pulumi stack ls" gives me the following result:

================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v2.9.0
Go Version:       go1.14.3
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            attempt to decrypt value

goroutine 1 [running]:
runtime/debug.Stack(0xc0007fac70, 0x1588560, 0x1c2e930)
        C:/go/src/runtime/debug/stack.go:24 +0xa4
main.panicHandler()
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x75
panic(0x1588560, 0x1c2e930)
        C:/go/src/runtime/panic.go:969 +0x174
github.com/pulumi/pulumi/sdk/v2/go/common/resource/config.panicCrypter.DecryptValue(...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/go/common/resource/config/crypt.go:123
github.com/pulumi/pulumi/pkg/v2/resource/stack.DeserializePropertyValue(0x1631200, 0xc000efa660, 0x2987f310, 0x2966c28, 0x2987f330, 0x2966c28, 0x1588560, 0xc000efe820, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:523 +0x83a
github.com/pulumi/pulumi/pkg/v2/resource/stack.DeserializeProperties(0xc000efa630, 0x2987f310, 0x2966c28, 0x2987f330, 0x2966c28, 0xc000efa8a0, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:450 +0x10a
github.com/pulumi/pulumi/pkg/v2/resource/stack.DeserializeResource(0xc000bcab40, 0x5e, 0x1, 0xc000b4b710, 0x8f, 0xc00169ecf0, 0x28, 0xc000efa5d0, 0xc000efa630, 0xc000bcac00, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:424 +0xe3
github.com/pulumi/pulumi/pkg/v2/resource/stack.DeserializeDeploymentV3(0x2698b8d8, 0xed7e3cce1, 0xc0000cf860, 0xc0018068c0, 0x40, 0xc000af2af0, 0x7, 0x0, 0x0, 0x0, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:237 +0x4ac
github.com/pulumi/pulumi/pkg/v2/resource/stack.DeserializeCheckpoint(0xc000cdf580, 0xc00059fc2f, 0x4, 0xc000cdf580)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/stack/checkpoint.go:114 +0xf0
github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).getStack(0xc0002041e0, 0xc00059fc2f, 0x4, 0x5, 0xc00005a868, 0xc000f36801, 0x4, 0x8)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/filestate/state.go:138 +0x165
github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).getLocalStacks(0xc0002041e0, 0x0, 0xc000546360, 0xc00003d6c0, 0x0, 0xc00025fb48)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/filestate/backend.go:732 +0x1ae
github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).ListStacks(0xc0002041e0, 0x1c91a60, 0xc0000360f0, 0x0, 0xc0008ae540, 0x0, 0x0, 0x0, 0x1cb9980, 0xc0002041e0, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/filestate/backend.go:316 +0x47
main.newStackLsCmd.func1(0xc000920000, 0x2966c28, 0x0, 0x0, 0x11, 0x11)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/stack_ls.go:105 +0x24c
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunFunc.func1(0xc000920000, 0x2966c28, 0x0, 0x0, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:96 +0x58
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc000920000, 0x2966c28, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x72
github.com/spf13/cobra.(*Command).execute(0xc000920000, 0x2966c28, 0x0, 0x0, 0xc000920000, 0x2966c28)
        C:/Users/appveyor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2a4
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004e0000, 0x15, 0x0, 0x0)
        C:/Users/appveyor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/appveyor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x54

Expected: a list of stacks

**Comment by emiliza** [comment]
Thanks for filing @momoliu-msft! 

Can you give more context on what your stack contains? Perhaps a repro?  I'd also be curious if this error persists on a newer version of the pulumi cli

**Comment by momoliu-msft** [comment]
Hi, emiliza, I have two services deployed there. This command worked at first and then stopped working for some reason. I do not really know what happened and why it suddenly stopped working. Btw, I've moved to version 2.22.0 and the ls command still does not work.

**Comment by emiliza** [comment]
Can you try moving to a 3.x version? https://www.pulumi.com/docs/get-started/install/versions/

There were some related secret provider panics that were addressed in the late 2.x versions that may have solved this

**Comment by momoliu-msft** [comment]
Thanks for the suggestion. Our service has the restriction which does not support me to move to 3.x version. Is there any other solution?

**Comment by clstokes** [comment]
@momoliu-msft we can discuss some options with you. Can you reach out to us at https://support.pulumi.com/ ?
