### ISSUE TITLE
LocalWorkspace supports stack outputs flaky

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#8061]
```
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

https://github.com/pulumi/pulumi/pull/8051

## Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:

**Comment by komalali** [comment]
Not the same exact failure, but similar in that it's automation api nodejs test failing with a timeout: https://github.com/pulumi/pulumi/runs/3738395273

This is super weird! Has there been a regression in this area? These tests have worked reliably with no flakes for the past year-ish.
