### ISSUE TITLE
Error serialising dynamic provider

### ISSUE THREAD

**Issue by abiro** [pulumi/pulumi#8090]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Error serialising dynamic typescript provider with node v16.9.1 and pulumi 3.13.0. The error is due to this line in the provider:

```
import fs from 'fs/promises'

...

// ERROR here
const files = await fs.readdir('.')
```

The error can be worked around by using the sync version of readdir. Full stack trace:

```
error: Error: Error serializing '() => provider': index.js(28,47)

'() => provider': index.js(28,47): captured
  variable 'provider' which indirectly referenced
    function 'DynamicResourceProvider': dynamic-resource.ts(25,15): which referenced
      function 'create': dynamic-resource.ts(28,10): which captured
        variable 'promises_1' which indirectly referenced
          function 'readdir': which referenced
            function 'getOptions': which captured
              'ERR_INVALID_ARG_TYPE', a function defined at
                function 'NodeError': which referenced
                  function 'isErrorStackTraceLimitWritable': which captured
                    'ObjectGetOwnPropertyDescriptor', a function defined at
                      function 'getOwnPropertyDescriptor': which could not be serialized because
                        it was a native code function.

Function code:
  function getOwnPropertyDescriptor() { [native code] }

    at throwSerializationError (/pulumi-bug/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:465:11)
    at /pulumi-bug/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:215:21
    at Generator.next (<anonymous>)
    at /pulumi-bug/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/pulumi-bug/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:17:12)
    at serializeWorkerAsync (/pulumi-bug/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:203:20)
    at /pulumi-bug/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:181:30
    at Generator.next (<anonymous>)
    at fulfilled (/pulumi-bug/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:18:58)
```

### Steps to reproduce

1. Check out https://github.com/abiro/pulumi-bug
2. `npm i`
3. `pulumi preview`
4. create new stack

Expected: The preview should succeed after creating the new stack.
Actual: The preview command fails with the above stack trace.

**Comment by abiro** [comment]
Also happens with `Map` methods.

**Comment by emiliza** [comment]
Looks like a similar issue to https://github.com/pulumi/pulumi/issues/6987 - can you try the workaround indicated in that issue and see if it fixes this situation for you?

**Comment by davidNHK** [comment]
workaround in #6997 didn't help

Here is code i copy from official example.

```
import * as pulumi from '@pulumi/pulumi';
import * as crypto from 'crypto';

const randomprovider: pulumi.dynamic.ResourceProvider = {
  async create(inputs) {
    return {
      id: await pulumi.runtime.serializeFunction(() =>
        crypto.randomBytes(16).toString('hex'),
      ),
      outs: {},
    };
  },
};

export class GithubActionWorkflowDeploymentEnvironmentVariablesResource extends pulumi
  .dynamic.Resource {
  constructor(name: string, opts?: pulumi.CustomResourceOptions) {
    super(randomprovider, name, {}, opts);
  }
}
```

**Comment by lionello** [comment]
Other workaround that worked for me is to stick to importing `"fs"` and dereference the `promises` member:
```
import * as fs from "fs";

async function test() {
  await fs.promises.readFile(…);
}
```

**Comment by awoimbee** [comment]
> workaround in https://github.com/pulumi/pulumi/issues/6997 didn't help

Same issue, I'm using using ESM and tsx, not sure if related:
```yaml
runtime:
  name: nodejs
  options:
    nodeargs: "--import tsx"
```
The example from the docs (what @neviaumi posted) doesn't work:
```
    '() => provider': index.js(50,43): captured
      variable 'provider' which indirectly referenced
        function 'create': provider_multirotate.ts(1,629): which captured
          variable 'crypto' which indirectly referenced
            function 'randomBytes': which referenced
              function 'assertSize': which captured
                'validateNumber', a function defined at
                  function 'wrappedFn': which captured
                    'fn', a function defined at
                      '(value, name, min = undefined, max)  ...': which captured
                        'ERR_INVALID_ARG_TYPE', a function defined at
                          function 'HideStackFramesError': which referenced
                            function 'isErrorStackTraceLimitWritable': which captured
                              'ObjectPrototypeHasOwnProperty', a function defined at
                                function 'bound call': which could not be serialized because
                                  it was a native code function.
```
Replacing `crypto.randomBytes(16).toString('hex')` by `id: Date.now().toString()` works but isn't really safe.
