### ISSUE TITLE
Flaky Node JS LocalWorkspace tests

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#8220]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

```
    python3 /home/runner/work/pulumi/pulumi/scripts/run-testsuite.py auto-nodejs ./node_modules/.bin/istanbul test --print none _mocha -- --timeout 120000 'bin/tests/automation/**/*.spec.js'


  LocalWorkspace
    ✓ projectSettings from yaml/yml/json (291ms)
    ✓ stackSettings from yaml/yml/json (285ms)
    ✓ adds/removes/lists plugins successfully (1901ms)
    ✓ create/select/remove LocalWorkspace stack (1698ms)
    ✓ create/select/createOrSelect Stack (2584ms)
    ✓ Config (5375ms)
    ✓ nested_config (2580ms)
    ✓ can list stacks and currently selected stack (4641ms)
    ✓ stack status methods (2382ms)
    1) runs through the stack lifecycle with a local program
    ✓ runs through the stack lifecycle with an inline program (13242ms)
    ✓ handles events (14909ms)
    - has secret config warnings
    ✓ imports and exports stacks (10618ms)
    ✓ supports stack outputs (12554ms)
    ✓ runs an inline program that rejects a promise and exits gracefully (5542ms)
    ✓ detects inline programs with side by side pulumi and throws an error (5373ms)
    ✓ sets pulumi version (98ms)
    ✓ respects existing project settings (1179ms)
    ✓ correctly sets config on multiple stacks concurrently (15242ms)

  checkVersionIsValid
    ✓ validates 100.0.0
    ✓ validates 1.0.0
    ✓ validates v2.22.0
    ✓ validates v2.1.0
    ✓ validates v2.21.2
    ✓ validates v2.21.1
    ✓ validates v2.21.0
    ✓ validates v2.21.1-alpha.1234
    ✓ validates v2.20.0
    ✓ validates v2.22.0


  28 passing (2m)
  1 pending
  1 failing

  1) LocalWorkspace runs through the stack lifecycle with a local program:
     StackAlreadyExistsError: code: 255
 stdout:
 stderr: error: stack 'pulumi-test/testproj/int_test298669' already exists

 err?:

      at Object.createCommandError (bin/automation/errors.js:69:43)
      at ChildProcess.<anonymous> (bin/automation/cmd.js:63:40)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)



Traceback (most recent call last):
TESTSUITE auto-nodejs completed in 2.3829989004298113e-06
```

### Steps to reproduce

https://github.com/pulumi/pulumi/runs/3897545227

**Comment by Frassle** [comment]
I've also seen "LocalWorkspace correctly sets config on multiple stacks concurrently" fail like this:
```
  1) LocalWorkspace correctly sets config on multiple stacks concurrently:
     StackAlreadyExistsError: code: 255
 stdout: 
 stderr: error: stack 'dev' already exists

 err?: 

      at Object.createCommandError (bin/automation/errors.js:69:43)
      at ChildProcess.<anonymous> (bin/automation/cmd.js:63:40)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
```

**Comment by tgummerer** [comment]
This seems to have happened again [here](https://github.com/pulumi/pulumi/actions/runs/7178890043/job/19548146303)

```
  1) LocalWorkspace
       successfully initializes multiple stacks:
     StackAlreadyExistsError: code: -2
 stdout: 
 stderr: Command failed with exit code 255: pulumi stack init moolumi/inline_node/int_test352501 --non-interactive
error: stack 'moolumi/inline_node/int_test352501' already exists
 err?: Error: Command failed with exit code 255: pulumi stack init moolumi/inline_node/int_test352501 --non-interactive
error: stack 'moolumi/inline_node/int_test352501' already exists

      at Object.createCommandError (automation/errors.ts:23:53)
      at Object.<anonymous> (bin/automation/cmd.js:17:1414)
      at Generator.throw (<anonymous>)
      at rejected (bin/automation/cmd.js:15:1011)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
