### ISSUE TITLE
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#8222]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The issue arose in master branch verifications on Windows.

   https://github.com/pulumi/pulumi/runs/3897859667?check_suite_focus=true

```
   --- FAIL: TestConstructPlainDotnet (66.86s)
   --- FAIL: TestConstructPlainDotnet/testcomponent-python (13.89s)


      Diagnostics:
           pulumi:pulumi:Stack (construct_component_unknown_dotnet-p-it-fv-az177-1-dotnet-af352bee):
             Traceback (most recent call last):
               File "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\tests\integration\construct_component_unknown\testcomponent-python\testcomponent.py", line 53, in <module>
                 provider.main(Provider(), sys.argv[1:])
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\provider\server.py", line 301, in main
                 loop.run_until_complete(serve())
               File "C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\asyncio\base_events.py", line 641, in run_until_complete
                 return future.result()
               File "d:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\sdk\python\env\src\pulumi\provider\server.py", line 289, in serve
                 server = grpc.aio.server(options=_GRPC_CHANNEL_OPTIONS)
               File "C:\Users\runneradmin\.virtualenvs\python-FORTJMCV\lib\site-packages\grpc\aio\_server.py", line 207, in server
                 return Server(migration_thread_pool, () if handlers is None else handlers,
               File "C:\Users\runneradmin\.virtualenvs\python-FORTJMCV\lib\site-packages\grpc\aio\_server.py", line 54, in __init__
                 self._server = cygrpc.AioServer(
               File "src\python\grpcio\grpc\_cython\_cygrpc/aio/server.pyx.pxi", line 857, in grpc._cython.cygrpc.AioServer.__init__
               File "C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\asyncio\locks.py", line 77, in __init__
                 super().__init__(loop=loop)
               File "C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\asyncio\mixins.py", line 17, in __init__
                 raise TypeError(
             TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary

           pulumi:providers:testcomponent (default):
     1>EXEC : error : could not read plugin [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\tests\integration\construct_component_unknown\testcomponent-python\pulumi-resource-testcomponent.cmd]
     stdout: EOF [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]


    --- FAIL: TestConstructUnknownDotnet (41.33s)
    --- FAIL: TestConstructUnknownDotnet/testcomponent-python (13.26s)

    Similar

```

**Comment by justinvp** [comment]
Closing as stale
