### ISSUE TITLE
Flaky Automation API LocalWorkspaceTests for C# 

### ISSUE THREAD

**Issue by emiliza** [pulumi/pulumi#8228]
This test looks like an intermittent flake, corrected itself on retry - please 👍 if it happens again 

```
[xUnit.net 00:01:35.20]     Pulumi.Automation.Tests.LocalWorkspaceTests.InlineProgramExceptionPropagatesToCallerWithServiceProvider [FAIL]
  X Pulumi.Automation.Tests.LocalWorkspaceTests.InlineProgramExceptionPropagatesToCallerWithServiceProvider [5s 289ms]
  Error Message:
   Assert.Throws() Failure
Expected: typeof(System.IO.FileNotFoundException)
Actual:   (No exception was thrown)
  Stack Trace:
     at Pulumi.Automation.Tests.LocalWorkspaceTests.InlineProgramExceptionPropagatesToCallerWithServiceProvider() in /home/runner/work/pulumi/pulumi/sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs:line 1292
   at Pulumi.Automation.Tests.LocalWorkspaceTests.InlineProgramExceptionPropagatesToCallerWithServiceProvider() in /home/runner/work/pulumi/pulumi/sdk/dotnet/Pulumi.Automation.Tests/LocalWorkspaceTests.cs:line 1296
--- End of stack trace from previous location where exception was thrown ---

```

https://github.com/pulumi/pulumi/runs/3864329148?check_suite_focus=true

**Comment by justinvp** [comment]
Closing old issue.
