### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: The given key 'System.Threading.Tasks.UnwrapPromise`1[System.Threading.Tasks.VoidTaskResult]' was not present in the dictionary.

### ISSUE THREAD

**Issue by andrewdmoreno** [pulumi/pulumi#8355]
Could you open a new issue @andrewdmoreno with your dependency versions? Much appreciated.

_Originally posted by @t0yv0 in https://github.com/pulumi/pulumi/issues/6377#issuecomment-961222292_

-------------------------------------------------------
I have encountered this issue from 2 separate projects.

````
2021-11-04T15:20:23.3936747Z     System.Collections.Generic.KeyNotFoundException: The given key 'System.Threading.Tasks.UnwrapPromise`1[System.Threading.Tasks.VoidTaskResult]' was not present in the dictionary.
2021-11-04T15:20:23.3937843Z        at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
2021-11-04T15:20:23.3938997Z        at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
2021-11-04T15:20:23.3940130Z     --- End of stack trace from previous location where exception was thrown ---
2021-11-04T15:20:23.3940634Z        at Pulumi.Deployment.Runner.WhileRunningAsync()
````

Project 1:
![image](https://user-images.githubusercontent.com/2897853/140403040-069adfbb-35da-4e82-9c70-d14da271cb45.png)

Project 2:
![image](https://user-images.githubusercontent.com/2897853/140402936-74b232d5-3733-45e7-8a85-817656dece17.png)

**Comment by emiliza** [comment]
Hi @andrewdmoreno thanks for providing your versions!  

Can you try upgrading Pulumi to at least v3.8.0? This is the version that has the fix for #6377 via PR #7529 per [changelog](https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md#380-2021-07-22).  

Let me know if this is still an issue after upgrading - thanks!

**Comment by andrewdmoreno** [comment]
Thanks for confirming. I will try that!

**Comment by t0yv0** [comment]
3.17.0 is recommended if possible since it also includes a fix that may be related https://github.com/pulumi/pulumi/pull/8294

**Comment by andrewdmoreno** [comment]
Thanks all. We'll make sure to reference 3.17.0. We're creating the PRs to our projects now and hopefully we'll be good to go. I appreciate the prompt response!

**Comment by andrewdmoreno** [comment]
We have not had the issue pop up since updating the version. Optimistically closing the issue. 😄
