### ISSUE TITLE
ES6/import with JavaScript template?

### ISSUE THREAD

**Issue by leviwolfe** [pulumi/pulumi#8357]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Is it possible to use ES6/import with JavaScript (not TypeScript)? I have a sample repo using the following steps: https://github.com/leviwolfe/import-pulumi

### Steps to reproduce

1. Create a skeleton using `pulumi new javascript`
2. Change `const pulumi = require("@pulumi/pulumi");` into `import pulumi from "@pulumi/pulumi";`
3. Add `"type": "module"` to package.json

Expected: The `pulumi preview` command to display a preview.
Actual: The `pulumi preview` command displays the following error:
```
   error: Running program 'c:\code\import-pulumi' failed with an unhandled exception:
    Error [ERR_REQUIRE_ESM]: require() of ES Module c:\code\import-pulumi\index.js from c:\code\import-pulumi\node_modules\@pulumi\pulumi\cmd\run\run.js not supported.
    Instead change the require of index.js in c:\code\import-pulumi\node_modules\@pulumi\pulumi\cmd\run\run.js to a dynamic import() which is available in all CommonJS modules.
        at Object.<anonymous> (c:\code\import-pulumi\node_modules\@pulumi\pulumi\cmd\run\run.js:219:31)
        at Generator.next (<anonymous>)
        at c:\code\import-pulumi\node_modules\@pulumi\pulumi\cmd\run\run.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (c:\code\import-pulumi\node_modules\@pulumi\pulumi\cmd\run\run.js:17:12)
        at Object.runProgram [as init] (c:\code\import-pulumi\node_modules\@pulumi\pulumi\cmd\run\run.js:205:30)
        at Stack.<anonymous> (c:\code\import-pulumi\node_modules\@pulumi\pulumi\runtime\stack.js:86:43)
        at Generator.next (<anonymous>)
        at fulfilled (c:\code\import-pulumi\node_modules\@pulumi\pulumi\runtime\stack.js:18:58)

```

**Comment by emiliza** [comment]
Hi @leviwolfe - unfortunately this isn't something supported today. 

We've captured the greater request of ECMAScript  support for js projects in https://github.com/pulumi/pulumi/issues/4130 - please take a moment to upvote and use this for tracking - thanks!
