### ISSUE TITLE
Throwing error in output not working when combined with log function

### ISSUE THREAD

**Issue by jsaunderson** [pulumi/pulumi#8438]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm trying to throw an error inside an `pulumi.output(x).apply(fn)`.

This works and an error is shown, however if I also use `pulumi.log.info(msg, resource)` then it shows no error and appears successful.

### Steps to reproduce

The following code that works:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

// Create an AWS resource (S3 Bucket)
const bucket = new aws.s3.Bucket("my-bucket", {
    accelerationStatus: pulumi.output("test").apply(() => {
        throw new Error('oops')
    })
});

// Export the name of the bucket
export const bucketName = bucket.id;
```

Results in the following output:
```
joseph@Josephs-MBP pulumitest % pulumi preview
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember): 
Previewing update (dev):
     Type                 Name            Plan       Info
 +   pulumi:pulumi:Stack  pulumitest-dev  create     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (pulumitest-dev):
    error: Running program '/Users/joseph/tmp/pulumitest' failed with an unhandled exception:
    Error: oops
        at /Users/joseph/tmp/pulumitest/index.ts:8:15
        at /Users/joseph/tmp/pulumitest/node_modules/@pulumi/pulumi/output.js:250:35
        at Generator.next (<anonymous>)
        at /Users/joseph/tmp/pulumitest/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/joseph/tmp/pulumitest/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/Users/joseph/tmp/pulumitest/node_modules/@pulumi/pulumi/output.js:229:12)
        at /Users/joseph/tmp/pulumitest/node_modules/@pulumi/pulumi/output.js:183:65
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

However adding a log line which references the bucket:
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

// Create an AWS resource (S3 Bucket)
const bucket = new aws.s3.Bucket("my-bucket", {
    accelerationStatus: pulumi.output("test").apply(() => {
        throw new Error('oops')
    })
});
pulumi.log.info('testmsg', bucket)

// Export the name of the bucket
export const bucketName = bucket.id;
```

Results in the following output (neither the log or error is shown):
```
joseph@Josephs-MBP pulumitest % pulumi preview                   
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember): 
Previewing update (dev):
     Type                 Name            Plan       
 +   pulumi:pulumi:Stack  pulumitest-dev  create     
 
Resources:
    + 1 to create
```

Expected: Error message from apply function is shown, and `pulumi preview` shows an error instead of success
Actual: `pulumi preview` shows output as if there is no error

**Comment by emiliza** [comment]
Thanks for filing @jsaunderson, can confirm this is an issue - and that the `preview` is returning an error status even if it's not displaying the actual error.
