### ISSUE TITLE
Can't create aws.budgets.Budget resource

### ISSUE THREAD

**Issue by abiro** [pulumi/pulumi#8540]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Can't create aws.budgets.Budget resource.

### Source

__main__.py
```py
import pulumi
import pulumi_aws as aws

config = pulumi.Config()
monthly_usd_limit = config.require("monthly-usd-limit")
assert isinstance(monthly_usd_limit, str)
email_notifications = config.require_object("email-notifications")
assert isinstance(email_notifications, list)

aws.budgets.Budget(
    "account-budget",
    budget_type="COST",
    limit_amount=monthly_usd_limit,
    limit_unit="USD",
    notifications=[
        aws.budgets.BudgetNotificationArgs(
            comparison_operator="GREATER_THAN",
            notification_type="FORECASTED",
            subscriber_email_addresses=email_notifications,
            threshold=100,
            threshold_type="PERCENTAGE",
        )
    ],
    time_period_end="2087-06-15_00:00",
    time_period_start="2021-01-01_00:00",
    time_unit="MONTHLY",
)
```

Pulumi.yaml
```yaml
name: budget
runtime:
  name: python
  options:
    virtualenv: venv
description: Budget alert
```

Pulumi.default.yaml
```yaml
config:
  aws:region: eu-west-1
  analytics-budget:monthly-usd-limit: 1000
  analytics-budget:email-notifications:
    - "example@example.com"
```

requirements.txt
```
Arpeggio==1.10.2
attrs==21.2.0
dill==0.3.4
grpcio==1.41.1
parver==0.3.1
protobuf==3.19.1
pulumi==3.19.0
pulumi-aws==4.30.0
PyYAML==6.0
semver==2.13.0
six==1.16.0
```

### Steps to reproduce

1. `pulumi stack init --stack default`
2. `pulumi preview --stack default`

Expected: The preview command outputs the resources to be created.
Actual: The preview command fails with the error below.

### Error

```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/Users/archilogic/homebrew/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/Users/archilogic/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/Users/archilogic/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 110, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/archilogic/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 45, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/archilogic/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 94, in wait_for_rpcs
        raise exception
      File "/Users/archilogic/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/Users/archilogic/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/archilogic/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/archilogic/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 10 more times]
      File "/Users/archilogic/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 568, in do_register
        rpc.resolve_outputs(res, resolver.serialized_props, resp.object, deps, resolvers, transform_using_type_metadata)
      File "/Users/archilogic/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 850, in resolve_outputs
        translated_value = translate_output_properties(value, translate_to_pass, types.get(key),
      File "/Users/archilogic/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 748, in translate_output_properties
        element_type = _get_list_element_type(typ)
      File "/Users/archilogic/repos/analytics/budget/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 107, in _get_list_element_type
        raise AssertionError(f"Unexpected type. Expected 'list' got '{typ}'")
    AssertionError: Unexpected type. Expected 'list' got 'typing.Mapping[str, str]'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

```

**Comment by emiliza** [comment]
I'm having trouble reproducing this with the code and versions you provided.

Reading the error it sounds like `email_notifications` just isn't deserialized properly - have you tried just passing the email as a list (not specified in config)?

**Comment by abiro** [comment]
Hi @emiliza, thanks for looking into it! Turns out my reproduction steps were incomplete. Creating a new stack from scratch (without any history) works for me too, but then if I change the `analytics-budget:monthly-usd-limit` config to a different number and I run `pulumi up`, I get the above error.

Btw in the meantime I've upgraded to pulumi CLI v3.19.0 and my requirements.txt is now:

```
Arpeggio==1.10.2
attrs==21.2.0
dill==0.3.4
grpcio==1.41.1
parver==0.3.1
protobuf==3.19.1
pulumi==3.19.0
pulumi-aws==4.31.0
PyYAML==6.0
semver==2.13.0
six==1.16.0

```
