### ISSUE TITLE
[sdk/go] Regression in provider handling of enum types

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#8588]
It appears that https://github.com/pulumi/pulumi/pull/7975 introduced a regression in handling enums in providers.  I don't have a repro yet, but have this trace.

```
         [stdout]          panic: reflect.Set: value of type pulumi.String is not assignable to type eks.EbsVolumeTypeInput
         [stdout]          
         [stdout]          goroutine 43 [running]:
         [stdout]          
         [stdout]          reflect.Value.assignTo({0x1d5de20, 0xc0004f6f30, 0x7f6af8cab5b8}, {0x2189214, 0xb}, 0x1d2a620, 0xc0002718e0)
         [stdout]          
         [stdout]          	/usr/local/src/reflect/value.go:2797 +0x2ad
         [stdout]          
         [stdout]          reflect.Value.Set({0x1d2a620, 0xc0002718e0, 0x1d2a620}, {0x1d5de20, 0xc0004f6f30, 0xc000305f28})
         [stdout]          
         [stdout]          	/usr/local/src/reflect/value.go:1905 +0xec
         [stdout]          
         [stdout]          github.com/pulumi/pulumi/sdk/v3/go/pulumi.copyInputTo(0x1e661c0, {{0x1ab7420, 0xc0004f6bf0}}, {0x1d2a620, 0xc0002718e0, 0x1d2a620})
         [stdout]          
         [stdout]          	/root/go/pkg/mod/acmecorp/cloud/pulumi-sdk/sdk/v3@v3.0.0-20211209203206-950decc1a806/go/pulumi/provider.go:362 +0x179f
```

**Comment by joeduffy** [comment]
Let’s also make sure we improve test coverage as part of this. If there are other adjacent areas we know we are deficient on, let’s also improve or, worst case, file issues to follow up on.

**Comment by lukehoban** [comment]
Some details:

The struct that is being copied is this:

```go
type AWSEKSControlPlaneArgs struct {
   // some things
   StorageClasses map[string]acmecorp.StorageClassInput `pulumi:"storageClasses"`
}
```

Where the nested `StorageClassInput` is this:

```go
type StorageClass struct {
	// Denotes whether volume expansion is allowed.
	AllowVolumeExpansion *bool `pulumi:"allowVolumeExpansion"`
	// Denotes whether the storage class is a default or not.
	Default *bool `pulumi:"default"`
	// The number of IOPS per GB of volume size to provision for IO1 volumes.
	IopsPerGb *int `pulumi:"iopsPerGb"`
	// The ARN of a KMS Key to use for volume encryption.
	KmsKeyArn *string `pulumi:"kmsKeyArn"`
	// Additional metadata to apply to the Kubernetes StorageClass resource.
	Metadata *metav1.ObjectMeta `pulumi:"metadata"`
	// Mount options for volumes.
	MountOptions []string `pulumi:"mountOptions"`
	// The reclaim policy for volumes.
	ReclaimPolicy *ReclaimPolicy `pulumi:"reclaimPolicy"`
	// The volume binding mode for volumes.
	VolumeBindingMode *VolumeBindingMode `pulumi:"volumeBindingMode"`
	// An enumeration of EBS Volume types which can be used for StorageClasses. Note that this only includes classes supported by the in-tree EBS storage provisioner [1]. [1]: https://kubernetes.io/docs/concepts/storage/volumes/#awselasticblockstore
	VolumeType EbsVolumeType `pulumi:"volumeType"`
	// The availability zone names in which volumes are provisioned.
	Zones []string `pulumi:"zones"`
}
​
// StorageClassInput is an input type that accepts StorageClassArgs and StorageClassOutput values.
// You can construct a concrete instance of `StorageClassInput` via:
//
//          StorageClassArgs{...}
type StorageClassInput interface {
	pulumi.Input
​
	ToStorageClassOutput() StorageClassOutput
	ToStorageClassOutputWithContext(context.Context) StorageClassOutput
}
​
type StorageClassArgs struct {
	// Denotes whether volume expansion is allowed.
	AllowVolumeExpansion pulumi.BoolPtrInput `pulumi:"allowVolumeExpansion"`
	// Denotes whether the storage class is a default or not.
	Default pulumi.BoolPtrInput `pulumi:"default"`
	// The number of IOPS per GB of volume size to provision for IO1 volumes.
	IopsPerGb pulumi.IntPtrInput `pulumi:"iopsPerGb"`
	// The ARN of a KMS Key to use for volume encryption.
	KmsKeyArn pulumi.StringPtrInput `pulumi:"kmsKeyArn"`
	// Additional metadata to apply to the Kubernetes StorageClass resource.
	Metadata metav1.ObjectMetaPtrInput `pulumi:"metadata"`
	// Mount options for volumes.
	MountOptions pulumi.StringArrayInput `pulumi:"mountOptions"`
	// The reclaim policy for volumes.
	ReclaimPolicy ReclaimPolicyPtrInput `pulumi:"reclaimPolicy"`
	// The volume binding mode for volumes.
	VolumeBindingMode VolumeBindingModePtrInput `pulumi:"volumeBindingMode"`
	// An enumeration of EBS Volume types which can be used for StorageClasses. Note that this only includes classes supported by the in-tree EBS storage provisioner [1]. [1]: https://kubernetes.io/docs/concepts/storage/volumes/#awselasticblockstore
	VolumeType EbsVolumeTypeInput `pulumi:"volumeType"`
	// The availability zone names in which volumes are provisioned.
	Zones pulumi.StringArrayInput `pulumi:"zones"`
}
```

Definition of `EbsVolumeType` in the schema:

```json
        "acmecorp:aws/eks:EbsVolumeType": {
            "type": "string",
            "enum": [
                {
                    "name": "gp2",
                    "value": "gp2"
                },
                {
                    "name": "io1",
                    "value": "io1"
                },
                {
                    "name": "sc1",
                    "value": "sc1"
                },
                {
                    "name": "st1",
                    "value": "st1"
                }
            ]
        },
```
