### ISSUE TITLE
Importing from state file results in assertion failure

### ISSUE THREAD

**Issue by elsbrock** [pulumi/pulumi#8611]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

```sh
$ pulumi version
v3.19.0
```

Trying to import state from a Terraform state JSON file. State only contains Cloudflare resources. Nametable has been added manually; in addition, types were converted into typeTokens.

### Steps to reproduce

```sh
$ pulumi import -f ../state.json
Previewing import (live):
panic: fatal: An assertion has failed

goroutine 50 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v3/resource/deploy.newImportDeploymentStep(0x0, 0xc000c264b0)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step.go:839 +0x259
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*importer).importResources(0xc000b53b28, {0x1e79f90, 0xc0008f61c0})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/import.go:337 +0x655
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).importResources(0xc000a98cc0, {0x1e7a038, 0xc000f16bd0}, {{0x7f31bab86568, 0xc000d9e280}, 0x7fffffff, 0x0, 0x0, {0x0, 0x0, ...}, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:450 +0x132
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute(0xc000a98cc0, {0x1e7a038, 0xc000f16bd0}, {{0x7f31bab86568, 0xc000d9e280}, 0x7fffffff, 0x0, 0x0, {0x0, 0x0, ...}, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:138 +0x1030
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Deployment).Execute(...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:410
github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run.func1()
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:262 +0x2b0
created by github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:246 +0x325
```

Minimal, redacted `state.json`:

```json
{
    "version": 4,
    "terraform_version": "1.0.11",
    "serial": 568,
    "lineage": "7ef0bfc3-0522-568d-d9ce-5fb2602cc7d1",
    "nameTable": {
      "cloudflare": "urn:pulumi:live::example-domains::pulumi:providers:cloudflare::default_4_0_0::04da6b53-80e4-46f7-96ec-b56ff0331ba9"
  },
    "resources": [
      {
        "mode": "managed",
        "type": "cloudflare:index/pageRule:PageRule",
        "name": "partner",
        "provider": "cloudflare",
        "instances": [
          {
            "schema_version": 0,
            "attributes": {
              "actions": [
                {
                  "always_online": "",
                  "always_use_https": false,
                  "automatic_https_rewrites": "",
                  "browser_cache_ttl": "",
                  "browser_check": "",
                  "bypass_cache_on_cookie": "",
                  "cache_by_device_type": "",
                  "cache_deception_armor": "",
                  "cache_key_fields": [],
                  "cache_level": "",
                  "cache_on_cookie": "",
                  "cache_ttl_by_status": [],
                  "disable_apps": false,
                  "disable_performance": false,
                  "disable_railgun": false,
                  "disable_security": false,
                  "edge_cache_ttl": 0,
                  "email_obfuscation": "",
                  "explicit_cache_control": "",
                  "forwarding_url": [
                    {
                      "status_code": 302,
                      "url": "https://example.com/foobar"
                    }
                  ],
                  "host_header_override": "",
                  "ip_geolocation": "",
                  "minify": [],
                  "mirage": "",
                  "opportunistic_encryption": "",
                  "origin_error_page_pass_thru": "",
                  "polish": "",
                  "resolve_override": "",
                  "respect_strong_etag": "",
                  "response_buffering": "",
                  "rocket_loader": "",
                  "security_level": "",
                  "server_side_exclude": "",
                  "sort_query_string_for_cache": "",
                  "ssl": "",
                  "true_client_ip_header": "",
                  "waf": ""
                }
              ],
              "id": "eca7dc8c6bad50cca7122319631a3739",
              "priority": 2,
              "status": "active",
              "target": "example.com/",
              "zone_id": "ece31c937a3f74166d108db1d1932ba5"
            },
            "sensitive_attributes": [],
            "dependencies": [
              "cloudflare:index/zone:Zone.foobar_com"
            ]
          }
        ]
      }
    ]
  }
```

**Comment by elsbrock** [comment]
It seems to be related to a missing `id` property on the resources. The file was exported from Terraform using `terraform state pull > state.json`.

**Comment by leezen** [comment]
Pulumi doesn't currently support directly importing Terraform state. If you're trying to import a single resource, the easiest path is like to just use `import` https://www.pulumi.com/docs/guides/adopting/import/

You may also want to refer to https://www.pulumi.com/docs/guides/adopting/from_terraform/ for other ways to adopt existing Terraform-based resources into Pulumi.
