### ISSUE TITLE
Failure to run pulumi up on M1 Mac

### ISSUE THREAD

**Issue by ggeer8** [pulumi/pulumi#8674]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When trying to run `pulumi up` on an M1 Max Macbook Pro I'm getting an error:

`ImportError: dlopen(/Users/<username>/pulumiTest/venv/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'
It looks like the Pulumi SDK has not been installed. Have you run pip install?
If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
error: an unhandled error occurred: Program exited with non-zero exit code: 1`

### Steps to reproduce

MUST USE PYTHON 3.9+

1. Install pulumi with python 3.9 via brew
2. pulumi new
3. pip3 install -r requirements.txt
Output 
![image](https://user-images.githubusercontent.com/16470051/147890576-79da80d4-500d-41c8-a324-f3d8ba9d9b56.png)

4. pulumi up

Expected: 
pulumi up to build with the base __main__.py - comes with an s3.bucket i nit
Actual: 

Get the below error:

![image](https://user-images.githubusercontent.com/16470051/147890592-ddefb3f1-ce84-49b7-8e18-4a046b0b6036.png)

If anyone wants to reach out to troubleshoot, I can be reached on the Pulumi Slack - Greg Geer

**Comment by leezen** [comment]
Given Pulumi's dependency on grpc, I think you may need to follow the steps outlined in https://github.com/grpc/grpc/issues/25082 prior to `pip install`

**Comment by scrottty** [comment]
@ggeer8 - Iv tried all of the answers on https://github.com/grpc/grpc/issues/25082, in a bunch of different configurations (condo, venv, py3.8, py3.9, etc.) to no avail. 

Do you have a specific solution that worked for you? Thanks in advance for any help!

**Comment by ggeer8** [comment]
> 

Hit me up on the Pulumi Slack, will be happy to try to help out!

**Comment by scrottty** [comment]
Ok I got this working. Putting what I did up here for any future stuck people!

The issue seems to be if you use conda. It gets in the way of the installations. So I did the following:
1. Uninstalled pulumi - `brew uninstall pulumi`
2. Made sure my console was outside of any conda env including the base env, so typing `conda deactivate` a bunch of times
3. installed the version of python I wanted with brew `brew install python@3.8`
4. Linked the python install with brew `brew unlink python` & `brew link --force python@3.8`
5. set the env variables as per https://github.com/grpc/grpc/issues/25082
```
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
```
6. Run through the pulumi demo
7. If you get `libssl.1.1.dylib' (no such file)` errors then you need to set up some symulinks. This worked for me. There is probably a much tidier way of doing this so if you know if please feel free to comment!
```
sudo ln -s /opt/homebrew/Cellar/openssl@1.1/1.1.1m/lib/libcrypto.1.1.dylib /usr/local/lib/    
sudo ln -s /opt/homebrew/Cellar/openssl@1.1/1.1.1m/lib/libssl.1.1.dylib /usr/local/lib/
```

**Comment by palladius** [comment]
I have the same issue.

Tried:

```
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1

sudo ln -sf /opt/homebrew/Cellar/openssl\@1.1/1.1.1q/lib/libcrypto.1.1.dylib  /usr/local/lib
sudo ln -sf /opt/homebrew/Cellar/openssl\@1.1/1.1.1q/lib/libssl.1.1.dylib     /usr/local/lib/

```

nit still fails:

```
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 14, in <module>
        import pulumi
      File "/Users/ricc/git/gprojects/pulumi/palladius-pulumi-public/examples/gcp-kms-gcs-hello/venv/lib/python3.8/site-packages/pulumi/__init__.py", line 33, in <module>
        from .config import (
      File "/Users/ricc/git/gprojects/pulumi/palladius-pulumi-public/examples/gcp-kms-gcs-hello/venv/lib/python3.8/site-packages/pulumi/config.py", line 22, in <module>
        from . import log
      File "/Users/ricc/git/gprojects/pulumi/palladius-pulumi-public/examples/gcp-kms-gcs-hello/venv/lib/python3.8/site-packages/pulumi/log.py", line 22, in <module>
        from .runtime.settings import get_engine
      File "/Users/ricc/git/gprojects/pulumi/palladius-pulumi-public/examples/gcp-kms-gcs-hello/venv/lib/python3.8/site-packages/pulumi/runtime/__init__.py", line 29, in <module>
        from .mocks import (
      File "/Users/ricc/git/gprojects/pulumi/palladius-pulumi-public/examples/gcp-kms-gcs-hello/venv/lib/python3.8/site-packages/pulumi/runtime/mocks.py", line 23, in <module>
        from . import rpc, rpc_manager
      File "/Users/ricc/git/gprojects/pulumi/palladius-pulumi-public/examples/gcp-kms-gcs-hello/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 40, in <module>
        from . import known_types, settings
      File "/Users/ricc/git/gprojects/pulumi/palladius-pulumi-public/examples/gcp-kms-gcs-hello/venv/lib/python3.8/site-packages/pulumi/runtime/settings.py", line 25, in <module>
        import grpc
      File "/Users/ricc/git/gprojects/pulumi/palladius-pulumi-public/examples/gcp-kms-gcs-hello/venv/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
        from grpc import _compression
      File "/Users/ricc/git/gprojects/pulumi/palladius-pulumi-public/examples/gcp-kms-gcs-hello/venv/lib/python3.8/site-packages/grpc/_compression.py", line 15, in <module>
        from grpc._cython import cygrpc
    ImportError: dlopen(/Users/ricc/git/gprojects/pulumi/palladius-pulumi-public/examples/gcp-kms-gcs-hello/venv/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace (_CFRelease)
    It looks like the Pulumi SDK has not been installed. Have you run pip install?
    If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.
 
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
 ```
