### ISSUE TITLE
RuntimeError "Set changed size during iteration" when using InvokeOptions with parent ComponentResource

### ISSUE THREAD

**Issue by tdaniely-dn** [pulumi/pulumi#8880]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Getting error when using various aws getXYZ with `InvokeOptions(parent=self)` inside `ComponentResource.__init__`
Having trouble tracking exactly when it happens.
It might work once or twice, and then start getting the error.
Sometimes destroying the component fixes it, sometimes not.
Removing the opts from the calls fixes it, but that disables provider inheritance.

### Steps to reproduce

pulumi 3.23.2 (cli & package)
pulumi-aws 4.36.0

python 3.10.1 & poetry

aws cli using sso profiles, not sure if relevant.

<details><summary>sample</summary>

```python
from typing import Optional, Sequence

from pulumi import ComponentResource, Input, InvokeOptions, ResourceOptions
from pulumi_aws import ec2, ssm

class NodeGroup(ComponentResource):
    def __init__(
        self,
        name: str,
        opts: Optional[ResourceOptions] = None,
        *,
        cluster_name: Input[str],
        k8s_version: Input[str],
        subnets: Input[Sequence[Input[str]]],
        instance_types: Input[Sequence[Input[str]]],
    ):
        super().__init__("foo:NodeGroup", name, opts=opts)

        # role ....

        ami_id = ssm.get_parameter(
            f"/aws/service/eks/optimized-ami/{k8s_version}/amazon-linux-2/recommended/image_id",
            opts=InvokeOptions(parent=self),
        ).value

        ami = ec2.get_ami(
            owners=["amazon"],
            filters=[ec2.GetAmiFilterArgs(name="image-id", values=[ami_id])],
            opts=InvokeOptions(parent=self),
        )

        template = ec2.LaunchTemplate(
            f"{name}-launchtemplate",
            ResourceOptions(parent=self),
            image_id=ami_id,
            block_device_mappings=[
                ec2.LaunchTemplateBlockDeviceMappingArgs(
                    device_name=dev.device_name,
                    ebs=ec2.LaunchTemplateBlockDeviceMappingEbsArgs(
                        delete_on_termination=True,
                        encrypted=True,
                        volume_type="gp3",
                        volume_size=100,
                        snapshot_id=dev.ebs["snapshot_id"],
                    ),
                )
                for dev in ami.block_device_mappings
            ],
            metadata_options=ec2.LaunchTemplateMetadataOptionsArgs(
                http_endpoint="enabled",
                http_tokens="optional",
                http_put_response_hop_limit=2,
            ),
        )

        # node group ....

        self.register_outputs({})
```

</details>

Expected: InvokeOptions works with `parent=self` in ComponentResource 
<details><summary>Actual: Fails with error</summary>

```
Updating (infra):
     Type                 Name          Status         Info
     pulumi:pulumi:Stack  infra         **failed**     3 errors

Diagnostics:
  pulumi:pulumi:Stack (infra):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
        return future.result()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 110, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 45, in run_pulumi_func
        await wait_for_rpcs()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 65, in wait_for_rpcs
        await RPC_MANAGER.rpcs.pop()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 34 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 34 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 34 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 3 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 105, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, translate, typ,
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 150, in serialize_properties
        result = await serialize_property(v, deps, input_transformer, get_type(k), keep_output_values)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 292, in serialize_property
        value = await serialize_property(output.future(), promise_deps, input_transformer, typ, keep_output_values=False)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 277, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 105, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, translate, typ,
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 150, in serialize_properties
        result = await serialize_property(v, deps, input_transformer, get_type(k), keep_output_values)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 292, in serialize_property
        value = await serialize_property(output.future(), promise_deps, input_transformer, typ, keep_output_values=False)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 277, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 105, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, translate, typ,
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 150, in serialize_properties
        result = await serialize_property(v, deps, input_transformer, get_type(k), keep_output_values)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 292, in serialize_property
        value = await serialize_property(output.future(), promise_deps, input_transformer, typ, keep_output_values=False)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 277, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 92, in prepare_resource
        explicit_urn_dependencies = await _resolve_depends_on_urns(opts, from_resource=res)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 748, in _resolve_depends_on_urns
        return await _expand_dependencies(all_deps, from_resource)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 721, in _expand_dependencies
        await _add_dependency(urns, d, from_resource)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 709, in _add_dependency
        urn = await res.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 32 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 34 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 105, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, translate, typ,
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 150, in serialize_properties
        result = await serialize_property(v, deps, input_transformer, get_type(k), keep_output_values)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 292, in serialize_property
        value = await serialize_property(output.future(), promise_deps, input_transformer, typ, keep_output_values=False)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 277, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 105, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, translate, typ,
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 150, in serialize_properties
        result = await serialize_property(v, deps, input_transformer, get_type(k), keep_output_values)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 292, in serialize_property
        value = await serialize_property(output.future(), promise_deps, input_transformer, typ, keep_output_values=False)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 277, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 159, in run
        is_known = await self._is_known
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 159, in run
        is_known = await self._is_known
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 159, in run
        is_known = await self._is_known
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 14 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 14 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 14 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 111, in prepare_resource
        parent_urn = await opts.parent.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 111, in prepare_resource
        parent_urn = await opts.parent.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 111, in prepare_resource
        parent_urn = await opts.parent.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 159, in run
        is_known = await self._is_known
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 159, in run
        is_known = await self._is_known
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 14 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 14 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 111, in prepare_resource
        parent_urn = await opts.parent.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 111, in prepare_resource
        parent_urn = await opts.parent.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 9 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 111, in prepare_resource
        parent_urn = await opts.parent.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 192, in run
        return await transformed.future(with_unknowns=True)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 161, in run
        value = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 419, in gather_futures
        return await asyncio.gather(*value_futures_list)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 593, in do_register_resource_outputs
        urn = await res.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 161, in run
        value = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      [Previous line repeated 1 more time]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 92, in prepare_resource
        explicit_urn_dependencies = await _resolve_depends_on_urns(opts, from_resource=res)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 748, in _resolve_depends_on_urns
        return await _expand_dependencies(all_deps, from_resource)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 721, in _expand_dependencies
        await _add_dependency(urns, d, from_resource)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 709, in _add_dependency
        urn = await res.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 593, in do_register_resource_outputs
        urn = await res.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 593, in do_register_resource_outputs
        urn = await res.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 159, in run
        is_known = await self._is_known
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 593, in do_register_resource_outputs
        urn = await res.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 593, in do_register_resource_outputs
        urn = await res.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 32 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 34 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 593, in do_register_resource_outputs
        urn = await res.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 111, in prepare_resource
        parent_urn = await opts.parent.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 111, in prepare_resource
        parent_urn = await opts.parent.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 111, in prepare_resource
        parent_urn = await opts.parent.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 111, in prepare_resource
        parent_urn = await opts.parent.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 111, in prepare_resource
        parent_urn = await opts.parent.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 111, in prepare_resource
        parent_urn = await opts.parent.urn.future()
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 65, in rpc_wrapper
        result = await rpc
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 94, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/output.py", line 119, in get_value
        val = await self._future
      [Previous line repeated 4 more times]
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 448, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 92, in prepare_resource
        explicit_urn_dependencies = await _resolve_depends_on_urns(opts, from_resource=res)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 748, in _resolve_depends_on_urns
        return await _expand_dependencies(all_deps, from_resource)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 721, in _expand_dependencies
        await _add_dependency(urns, d, from_resource)
      File "/redacted-path/.venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 702, in _add_dependency
        for child in res._childResources:
    RuntimeError: Set changed size during iteration
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

</details>

**Comment by tdaniely-dn** [comment]
misdiagnosed the error, probably has to do with dependencie between ComponentResource
