### ISSUE TITLE
pulumi python pulumi-gcp : panic: fatal

### ISSUE THREAD

**Issue by raphaelauv** [pulumi/pulumi#9002]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

```log
(venv) XXXXXXXXX@XXXXXX:~/REPO/XXXXXX/data-iac/src/XXXXXX$ pulumi up
Previewing update (XXXXXXXXXX-prod):
     Type                           Name                                                                                        Plan        Info
     pulumi:pulumi:Stack            XXXXXXXXXX-XXXXXXXXXX-prod                                                                                      
     └─ gcp:component:all_resource  all_resource                                                                                            
 +-     ├─ gcp:projects:IAMMember   iam_member_storage.objectCreator_XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com  replace     [diff: ~condition]
 +-     └─ gcp:projects:IAMMember   iam_member_storage.objectViewer_XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com   replace     [diff: ~condition]
 
Resources:
    +-2 to replace
    337 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::pulumi:pulumi:Stack::XXXXXXXXXX-XXXXXXXXXX-prod]
        ++gcp:projects/iAMMember:IAMMember: (create-replacement) 🔓
            [id=XXXXXXXXXX-261214/roles/storage.objectCreator/serviceAccount:XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com/RW-gcs-composer-bucket//resource.name == "europe-west1-airflow-XXXXXXXXXX-bucket" ||
resource.name == "europe-west1-airflow-XXXXXXXXXX-bucket"]
            [urn=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::gcp:component:all_resource$gcp:projects/iAMMember:IAMMember::iam_member_storage.objectCreator_XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com]
            [provider=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::pulumi:providers:gcp::default_gcp::XXXX-XXXXX-XXXXXX-XXXXXX-XXXXXXXXXX]
          ~ condition: {
              ~ expression: "resource.name == \"europe-west1-airflow-XXXXXXXXXX-bucket\" ||\nresource.name == \"europe-west1-airflow-XXXXXXXXXX-bucket\"" => "resource.name.startsWith(\"europe-west1-airflow-XXXXXXXXXX-bucket\") ||\nresource.name.startsWith(\"europe-west1-airflow-XXXXXXXXXX-bucket\")"
            }
        +-gcp:projects/iAMMember:IAMMember: (replace) 🔓
            [id=XXXXXXXXXX-261214/roles/storage.objectCreator/serviceAccount:XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com/RW-gcs-composer-bucket//resource.name == "europe-west1-airflow-XXXXXXXXXX-bucket" ||
resource.name == "europe-west1-airflow-XXXXXXXXXX-bucket"]
            [urn=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::gcp:component:all_resource$gcp:projects/iAMMember:IAMMember::iam_member_storage.objectCreator_XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com]
            [provider=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::pulumi:providers:gcp::default_gcp::XXXX-XXXXX-XXXXXX-XXXXXX-XXXXXXXXXX]
          ~ condition: {
              ~ expression: "resource.name == \"europe-west1-airflow-XXXXXXXXXX-bucket\" ||\nresource.name == \"europe-west1-airflow-XXXXXXXXXX-bucket\"" => "resource.name.startsWith(\"europe-west1-airflow-XXXXXXXXXX-bucket\") ||\nresource.name.startsWith(\"europe-west1-airflow-XXXXXXXXXX-bucket\")"
            }
        ++gcp:projects/iAMMember:IAMMember: (create-replacement) 🔓
            [id=XXXXXXXXXX-261214/roles/storage.objectViewer/serviceAccount:XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com/LIST-gcs-composer-bucket//resource.name == "europe-west1-airflow-XXXXXXXXXX-bucket" ||
resource.name == "europe-west1-airflow-XXXXXXXXXX-bucket"]
            [urn=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::gcp:component:all_resource$gcp:projects/iAMMember:IAMMember::iam_member_storage.objectViewer_XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com]
            [provider=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::pulumi:providers:gcp::default_gcp::XXXX-XXXXX-XXXXXX-XXXXXX-XXXXXXXXXX]
          ~ condition: {
              ~ expression: "resource.name == \"europe-west1-airflow-XXXXXXXXXX-bucket\" ||\nresource.name == \"europe-west1-airflow-XXXXXXXXXX-bucket\"" => "resource.name.startsWith(\"europe-west1-airflow-XXXXXXXXXX-bucket\") ||\nresource.name.startsWith(\"europe-west1-airflow-XXXXXXXXXX-bucket\")"
            }
        +-gcp:projects/iAMMember:IAMMember: (replace) 🔓
            [id=XXXXXXXXXX-261214/roles/storage.objectViewer/serviceAccount:XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com/LIST-gcs-composer-bucket//resource.name == "europe-west1-airflow-XXXXXXXXXX-bucket" ||
resource.name == "europe-west1-airflow-XXXXXXXXXX-bucket"]
            [urn=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::gcp:component:all_resource$gcp:projects/iAMMember:IAMMember::iam_member_storage.objectViewer_XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com]
            [provider=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::pulumi:providers:gcp::default_gcp::XXXX-XXXXX-XXXXXX-XXXXXX-XXXXXXXXXX]
          ~ condition: {
              ~ expression: "resource.name == \"europe-west1-airflow-XXXXXXXXXX-bucket\" ||\nresource.name == \"europe-west1-airflow-XXXXXXXXXX-bucket\"" => "resource.name.startsWith(\"europe-west1-airflow-XXXXXXXXXX-bucket\") ||\nresource.name.startsWith(\"europe-west1-airflow-XXXXXXXXXX-bucket\")"
            }
        --gcp:projects/iAMMember:IAMMember: (delete-replaced) 🔒
            [id=XXXXXXXXXX-261214/roles/storage.objectCreator/serviceAccount:XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com/RW-gcs-composer-bucket//resource.name == "europe-west1-airflow-XXXXXXXXXX-bucket" ||
resource.name == "europe-west1-airflow-XXXXXXXXXX-bucket"]
            [urn=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::gcp:component:all_resource$gcp:projects/iAMMember:IAMMember::iam_member_storage.objectCreator_XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com]
            [provider=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::pulumi:providers:gcp::default_gcp::XXXX-XXXXX-XXXXXX-XXXXXX-XXXXXXXXXX]
        --gcp:projects/iAMMember:IAMMember: (delete-replaced) 🔒
            [id=XXXXXXXXXX-261214/roles/storage.objectViewer/serviceAccount:XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com/LIST-gcs-composer-bucket//resource.name == "europe-west1-airflow-XXXXXXXXXX-bucket" ||
resource.name == "europe-west1-airflow-XXXXXXXXXX-bucket"]
            [urn=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::gcp:component:all_resource$gcp:projects/iAMMember:IAMMember::iam_member_storage.objectViewer_XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com]
            [provider=urn:pulumi:XXXXXXXXXX-prod::XXXXXXXXXX::pulumi:providers:gcp::default_gcp::XXXX-XXXXX-XXXXXX-XXXXXX-XXXXXXXXXX]

Do you want to perform this update? yes
Updating (XXXXXXXXXX-prod):
     Type                           Name                                                                                        Status                Info
     pulumi:pulumi:Stack            XXXXXXXXXX-XXXXXXXXXX-prod                                                                          running.              
     └─ gcp:component:all_resource  all_resource                                                                                                      
 --     ├─ gcp:projects:IAMMember   iam_member_storage.objectCreator_XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com  deleting original...  [diff: ~condition]
 --     └─ gcp:projects:IAMMember   iam_member_storage.objectViewer_XXXXXXXXXXX@XXXXXXXXXXXXX.iam.gserviceaccount.com   deleting original...  [diff: ~condition]
panic: fatal: An assertion has failed

goroutine 2345 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v3/backend.(*deleteSnapshotMutation).End.func1()
        /Users/runner/work/pulumi/pulumi/pkg/backend/snapshot.go:394 +0x11a
github.com/pulumi/pulumi/pkg/v3/backend.NewSnapshotManager.func1()
        /Users/runner/work/pulumi/pulumi/pkg/backend/snapshot.go:649 +0x109
created by github.com/pulumi/pulumi/pkg/v3/backend.NewSnapshotManager
        /Users/runner/work/pulumi/pulumi/pkg/backend/snapshot.go:639 +0x1dd


```
### Steps to reproduce

pulumi: 3.24.1
pulumi-gcp : 6.10.0
pulumi up , to update a condition on a IAM member

Expected: pulumi do not fail
Actual: pulumi fail

**Comment by mikhailshilkov** [comment]
@Frassle any idea what could be causing this panic? It seems to be on this line https://github.com/pulumi/pulumi/blob/272c4643b20d40113689475fd2f9fe3134e6d431/pkg/backend/snapshot.go#L394

**Comment by Frassle** [comment]
Ah that assert should be changed. We now allow replacement deletes as long as either old or new protect is false. I guess they unprotected the resource, tried to replace it but the old one that was being deleted still had the protect bit set.

You can work around this by unsetting the protect bit with [`pulumi state unprotect`](https://www.pulumi.com/docs/reference/cli/pulumi_state_unprotect/) but we should fix that assert! I'll do that now, we might want to patch release it.
