### ISSUE TITLE
pulumi up panics with Go sdk - panic: fatal: An assertion has failed

### ISSUE THREAD

**Issue by VRanga000** [pulumi/pulumi#9008]
## Issue details

Creating an EKS cluster using pulumi Go sdk results in panic.

```
Resources:
    + 26 to create
    2 unchanged

Do you want to perform this update? yes
Updating (eks-test):
     Type                 Name             Status         Info
     pulumi:pulumi:Stack  eks_go-eks-test  **failed**     1 error; 23 messages

Diagnostics:
  pulumi:pulumi:Stack (eks_go-eks-test):
    error: an unhandled error occurred: program exited with non-zero exit code: 1

    panic: fatal: An assertion has failed
    goroutine 98 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/vikas/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
        /home/vikas/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/go/common/util/contract/assert.go:26
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputImpl({0x14e7120, 0xc0004ec140}, {0x1781850, 0x14e7120}, 0x1, 0x0)
        /home/vikas/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/go/pulumi/rpc.go:353 +0x263b
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputImpl({0x1468920, 0xc0005875e0}, {0x1781850, 0x14e7120}, 0x1, 0x0)
        /home/vikas/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/go/pulumi/rpc.go:273 +0xc5d
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(...)
        /home/vikas/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/go/pulumi/rpc.go:217
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputs.func1({0x10cecaf, 0xc}, {0x1468920, 0xc0005875e0}, {0x1781850, 0x14e7120})
        /home/vikas/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/go/pulumi/rpc.go:134 +0x8b
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputs({0x172b280, 0xc0000d8000})
        /home/vikas/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/go/pulumi/rpc.go:187 +0x878
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).prepareResourceInputs(0xc0004ec000, {0x177a9a8, 0xc00014a200}, {0x172b280, 0xc0000d8000}, {0x1591684, 0x11}, 0xc00014d200, 0xc0004ac300, 0x1)
        /home/vikas/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/go/pulumi/context.go:1213 +0x1a5
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).registerResource.func1()
        /home/vikas/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/go/pulumi/context.go:794 +0x27f
    created by github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).registerResource
        /home/vikas/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/go/pulumi/context.go:781 +0x7a8
    exit status 2

Resources:
    2 unchanged

Duration: 3s
```

### Steps to reproduce

Relevant code:

```
func NewEksCluster(ctx *pulumi.Context, cfg *config.Config) (*eks.Cluster, error) {
	awsRegion := cfg.Require("aws_region")
	awsProviderName := cfg.Require("aws_provider_name")
	awsProfile := cfg.Require("aws_profile")

	awsProvider, err := aws.NewProvider(ctx, awsProviderName, &aws.ProviderArgs{
		Region:  pulumi.StringPtr(awsRegion),
		Profile: pulumi.StringPtr(awsProfile),
	})
	if err != nil {
		return nil, fmt.Errorf("Failed to create aws provider: %w", err)
	}

	instanceRoleName := cfg.Require("aws_instance_role")
	serviceRoleName := cfg.Require("aws_service_role")

	instanceRole, err := getRole(ctx, instanceRoleName, awsProvider)
	if err != nil {
		return nil, err
	}
	serviceRole, err := getRole(ctx, serviceRoleName, awsProvider)
	if err != nil {
		return nil, err
	}

	clusterName := cfg.Require("clusterName")
	var subnetIds []string
	cfg.RequireObject("subnetIds", &subnetIds)

	cluster, err := eks.NewCluster(ctx, clusterName, &eks.ClusterArgs{
		Name:                  pulumi.StringPtr(clusterName),
		Version:               pulumi.StringPtr(cfg.Require("masterVersion")),
		MinSize:               pulumi.IntPtr(cfg.RequireInt("minNodes")),
		MaxSize:               pulumi.IntPtr(cfg.RequireInt("maxNodes")),
		InstanceType:          pulumi.StringPtr(cfg.Require("instanceType")),
		NodeAmiId:             pulumi.StringPtr(cfg.Get("nodeAmiId")),
		VpcId:                 pulumi.StringPtr(cfg.Require("vpcId")),
		SubnetIds:             pulumi.ToStringArray(subnetIds),
		InstanceRole:          instanceRole.ToRoleOutput(),
		ServiceRole:           serviceRole.ToRoleOutput(),
		InstanceProfileName:   pulumi.StringPtr(cfg.Require("instanceProfileName")),
		EndpointPublicAccess:  pulumi.BoolPtr(cfg.RequireBool("endpointPublicAccess")),
		EndpointPrivateAccess: pulumi.BoolPtr(cfg.RequireBool("endpointPrivateAccess")),
		UseDefaultVpcCni:      pulumi.BoolPtr(true),
		RoleMappings:          eks.RoleMappingArray{},
		ProviderCredentialOpts: &eks.KubeconfigOptionsArgs{
			ProfileName: pulumi.StringPtr(awsProfile),
		},
	},
		pulumi.Provider(awsProvider),
	)

	if err != nil {
		return nil, fmt.Errorf("Failed to create eks cluster: %w", err)
	}

	if err := addNodeGroups(ctx, cluster, cfg, awsProvider); err != nil {
		return cluster, fmt.Errorf("Failed to create nodegroups: %w", err)
	}

	return cluster, nil

}
```

There seem to have been a [fix](https://github.com/pulumi/pulumi/pull/6962) that addresses a [similar issue](https://github.com/pulumi/pulumi/issues/6934).
My suspicion is that it has to do with the resource references to the IAM roles.

## Environment details

```
✗ pulumi version
v3.24.1

✗ pulumi plugin ls
NAME        KIND      VERSION  SIZE    INSTALLED  LAST USED
aws         resource  4.37.4   350 MB  n/a        14 minutes ago
aws         resource  4.34.0   358 MB  n/a        14 minutes ago
aws         resource  4.27.2   344 MB  n/a        14 minutes ago
aws         resource  4.27.0   344 MB  n/a        14 minutes ago
docker      resource  3.1.0    40 MB   n/a        14 minutes ago
eks         resource  0.37.1   174 MB  n/a        11 minutes ago
eks         resource  0.35.0   174 MB  n/a        14 minutes ago
kubernetes  resource  3.16.0   77 MB   n/a        11 minutes ago
kubernetes  resource  3.15.2   77 MB   n/a        14 minutes ago
kubernetes  resource  3.14.0   77 MB   n/a        14 minutes ago
kubernetes  resource  3.10.0   77 MB   n/a        14 minutes ago
kubernetes  resource  3.9.0    77 MB   n/a        14 minutes ago

```

**Comment by mikhailshilkov** [comment]
@iwahbe Could you please take a look if you can repro this (and why this happens)?

**Comment by VRanga000** [comment]
> I'm unable to repro. I don't know what either `getRole` or `addNodeGroups` does. If I leave as default all the unknown function fields (and config values I don't know how to manually setup), I have removed whatever bug causes the assert failure.
> 
> With regards to the root cause of the bug, the error is from:
> 
> https://github.com/pulumi/pulumi/blob/12accf6a8e1f8b657300a176e99667ff467ddac1/sdk/go/pulumi/rpc.go#L346-L366

Thank you! Here is the getRole function:

```
func getRole(ctx *pulumi.Context, roleName string, awsProvider pulumi.ProviderResource) (*iam.Role, error) {
	role, err := iam.GetRole(ctx, roleName, pulumi.ID(roleName), &iam.RoleState{Name: pulumi.StringPtr(roleName)}, pulumi.Provider(awsProvider))
	if err != nil {
		return nil, fmt.Errorf("Failed to lookup role %s: %w", roleName, err)
	}

	return role, nil

}
```

The addNodes function does not seem to matter, I get the error even when that's commented out.

**Comment by VRanga000** [comment]
Some more info. According to the docs, the `iam.LookupRole` function is what should be used, not the `GetRole` function. I don't really understand why, because the GetRole function signature seems to match the corresponding Typescript function (getRole) rather than `LookupRole`. Also, there does not seem to be a way to convert a `LookupRoleResult` into ` Role`.

**Comment by mikhailshilkov** [comment]
`LookupRole` in Go is like `getRole` in Typescript, `GetRole` in Go is like `Role.get` in Typescript. They differ in arguments and return type indeed.

@iwahbe Have you tried the `getRole` Go function defined above?

**Comment by VRanga000** [comment]
Even more info: the stack works ok if I give up on GetRole / LookupRole and use NewRole to create fresh roles. This does not satisfy all use cases tho.

**Comment by justinvp** [comment]
The stack of the panic looks to be the same as #7517

**Comment by iwahbe** [comment]
I have a repro. I think the workaround is no calling `.ToRoleOutput()`.
