### ISSUE TITLE
Inline Program fails with Pulumi engine unavailable

### ISSUE THREAD

**Issue by liamawhite** [pulumi/pulumi#9078]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Running the automation API results in:

```
/Users/liamwhite/src/github.com/tetrateio/tetrate/cloud/node_modules/@pulumi/pulumi/runtime/settings.js:123
        throw new Error("Program run without the Pulumi engine available; re-run using the `pulumi` CLI");
              ^
Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
    at requireTestModeEnabled (/Users/liamwhite/src/github.com/tetrateio/tetrate/cloud/node_modules/@pulumi/pulumi/runtime/settings.js:123:15)
    at Object.getProject (/Users/liamwhite/src/github.com/tetrateio/tetrate/cloud/node_modules/@pulumi/pulumi/runtime/settings.js:161:5)
    at Object.getProject (/Users/liamwhite/src/github.com/tetrateio/tetrate/cloud/node_modules/@pulumi/pulumi/metadata.js:22:20)
    at Object.<anonymous> (/Users/liamwhite/src/github.com/tetrateio/tetrate/cloud/components/optionsv2/aws.ts:28:50)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module.m._compile (/Users/liamwhite/src/github.com/tetrateio/tetrate/cloud/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/liamwhite/src/github.com/tetrateio/tetrate/cloud/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
```

### Steps to reproduce

I've narrowed it down to the following line, which is imported from another package:

```ts
const opts = { ...options.Azure('azure'), region: stack.region, resourceGroupName }
```

The function definition:
```ts
export function Azure(
    name: string,
    opts?: CustomResourceOptions,
    providerOptions?: ProviderOptions,
): AzureOptions {
    const cfg = new pulumi.Config('azure')
    const subscriptionId = cfg.require('subscriptionId')
    const provider = new azure.Provider(
        name,
        {
            tenantId,
            subscriptionId,
            clientId: cfg.require('clientId'),
            clientSecret: cfg.requireSecret('clientSecret'),
        },
        providerOptions,
    )
    return {
        subscriptionId,
        provider,
        ...opts,
    }
}
```

Both packages import the following versions:

```
    "@pulumi/azure-native": "1.45.0",
    "@pulumi/pulumi": "3.14.0",
```

Expected: Stack to up
Actual: see above error ^^

**Comment by liamawhite** [comment]
> Can you provide any additional details on what you mean by this? How is that line related to the error you are seeing here?

When I comment out this line the stack select works, when I comment it out it works.

> It appears that you are somehow running in a context that does not have a project configured. What context are you calling getProject in here, and can you report what you see for the PULUMI_NODEJS_PROJECT env var at this point?

Ths only `PULUMI_` env vars set are my access token and `PULUMI_NODEJS_SXS_FLAG: '0.48217873268474487'`.

Here is the wider code:

```ts
import * as options from '@tetrateio-components/optionsv2'
...
const aks: PulumiFn = async () => {

    // Load in the stack config
    const cfg = new pulumi.Config('controlplane')
    const stack = cfg.requireObject<Config>('stack')

    // The maximum length of the node resource group name is 80
    const resourceGroupName = `hosted-cp-${pulumi.getStack()}`

    const platform = new core.StackReference()
    const opts = { ...options.Azure('azure'), region: stack.region, resourceGroupName }
}

const stack = await LocalWorkspace.createOrSelectStack({
    stackName: `tetrate/${instance.cloudProvider}.${instance.id}.${cp.name}`,
    projectName: `hosted-controlplanes-aks`,
    program: aks,
})
```

**Comment by liamawhite** [comment]
Ah, worked out what I was doing wrong. In a different file in the package I had `export const foo = `pulumi-automation-${pulumi.getProject()}-${pulumi.getStack()}` that was not being called inside of a function.
