### ISSUE TITLE
ts-node top level await fails with code in subdirectory

### ISSUE THREAD

**Issue by rawkode** [pulumi/pulumi#9153]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Trying to use `ts-node` with the loader for top level async-await seems to fail if the Pulumi code is inside a `src` directory, a rather common pattern for Pulumi users.

### Steps to reproduce

1. Move code to `./src`
2. Update `Pulumi.yaml` with `main: src/index.ts`
3. Update `tsconfig.json` with `files: ["src/index.ts"]`

Expected: Pulumi program should still work
Actual:

```
    error: Running program '/Users/rawkode/Code/src/github.com/pulumi/pulumi/tests/integration/nodejs/esm-srcdir-ts/src/index.ts' failed with an unhandled exception:
    Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/rawkode/Code/src/github.com/pulumi/pulumi/tests/integration/nodejs/esm-srcdir-ts/src/index.ts
    require() of ES modules is not supported.
    require() of /Users/rawkode/Code/src/github.com/pulumi/pulumi/tests/integration/nodejs/esm-srcdir-ts/src/index.ts from /Users/rawkode/Code/src/github.com/pulumi/pulumi/tests/integration/nodejs/esm-srcdir-ts/node_modules/@pulumi/pulumi/cmd/run/run.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
    Instead change the requiring code to use import(), or remove "type": "module" from /Users/rawkode/Code/src/github.com/pulumi/pulumi/tests/integration/nodejs/esm-srcdir-ts/package.json.

        at createErrRequireEsm (/Users/rawkode/Code/src/github.com/pulumi/pulumi/tests/integration/nodejs/esm-srcdir-ts/node_modules/ts-node/dist-raw/node-cjs-loader-utils.js:97:15)
        at assertScriptCanLoadAsCJSImpl (/Users/rawkode/Code/src/github.com/pulumi/pulumi/tests/integration/nodejs/esm-srcdir-ts/node_modules/ts-node/dist-raw/node-cjs-loader-utils.js:30:11)
        at require.extensions.<computed> (/Users/rawkode/Code/src/github.com/pulumi/pulumi/tests/integration/nodejs/esm-srcdir-ts/node_modules/ts-node/src/index.ts:1451:5)
        at Object.require.extensions.<computed> [as .ts] (/Users/rawkode/Code/src/github.com/pulumi/pulumi/tests/integration/nodejs/esm-srcdir-ts/node_modules/@pulumi/pulumi/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:975:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:999:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.<anonymous> (/Users/rawkode/Code/src/github.com/pulumi/pulumi/tests/integration/nodejs/esm-srcdir-ts/node_modules/@pulumi/cmd/run/run.ts:290:33)
        at Generator.next (<anonymous>)
```

**Comment by liubog2008** [comment]
I have same problem about this... any progress?

**Comment by Frassle** [comment]
Me and rawkode talked about this the other day, I've got a suspicion our handling of the Pwd and Program arguments in the node plugin aren't consistent.

**Comment by liubog2008** [comment]
How about this problem?

**Comment by alvis** [comment]
Sounds like it's related to #10459?
