### ISSUE TITLE
Node.js closure serialization doesn't capture method bodies

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi#9168]
Our closure serialization doesn't seem to be fully capturing referenced instance methods -- at least not those called from other instance methods. In the following program, for example, `handler` gets called, and `someMethod` gets called from there, but the call fails because `someMethod` doesn't exist:

```typescript
import * as aws from "@pulumi/aws";

class MyClass {
    bucket: aws.s3.Bucket;

    constructor() {
        this.bucket = new aws.s3.Bucket("my-bucket");
        this.bucket.onObjectCreated("handler", this.handler);
    }

    handler() {
        this.someMethod();
    }

    someMethod() {
        console.log("hello from someMethod");
    }
}

const b = new MyClass();
export const bucketName = b.bucket.id;
```

```
ERROR   Invoke Error    {"errorType":"TypeError","errorMessage":"this.someMethod is not a function","stack":["TypeError: this.someMethod is not a function","    at Runtime.<anonymous> (/var/task/__index.js:8:14)","    at Runtime.__f0 [as handler] (/var/task/__index.js:12:34)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
```

Is this expected? If so, should we add something to the docs that better explains it? (Seems possible this runs afoul of something mentioned in https://www.pulumi.com/docs/intro/concepts/function-serialization, but nothing jumped out at me.) Feels like an easy thing to hit, too, especially when working in the context of a component-resource class.

**Comment by dixler** [comment]
Not that it adds much, but I checked that v3.24.1 before #8710 also has this issue.

**Comment by dixler** [comment]
@cnunciato I see that changing
```typescript
        this.bucket.onObjectCreated("handler", () => this.handler());
```
throws this error
```
Diagnostics:
  pulumi:pulumi:Stack (9168.pulumi-dev):
    error: Error serializing function '<anonymous>'
    
    function '<anonymous>': which could not be serialized because
      arrow function captured 'this'. Assign 'this' to another name outside function and capture that.
    
    Function code:
      () => this.handler()
 

warning: A new version of Pulumi is available. To upgrade from version '3.24.0' to '3.26.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```
I followed this
```typescript
        const that =  this;
        this.bucket.onObjectCreated("handler", () => that.handler());
```
It then serialized pulumi requires into the lambda object since it seems the serialization captures the constructor that has the bucket constructor.

**Comment by skyrpex** [comment]
I also find this issue when extending a class, ie:

```ts
class BaseCommand {
    constructor(private readonly text: string) {}

    hi() {
        return this.text;
    }
}

class Command extends BaseCommand {
    constructor(text: string) {
        super(text);
    }
}
```

Command's inherited `hi` method doesn't exist in runtime.

**Comment by lalitkapoor** [comment]
am experiencing this issue in a lambda callbackFunction.

I am using a logging library (pino) and I instantiate it in a file titled `utils.ts`. I import that instantiated logger and attempt to call the logger in the `callbackFactory` and I get the following error:

```
error: Error serializing function 'callbackFactory': dynamoDBPutHandler.ts(45,34)

    function 'callbackFactory': dynamoDBPutHandler.ts(45,34): captured
      module './src/utils.ts' which indirectly referenced
        function '<anonymous>': index.js(127,17): which could not be serialized because
          arrow function captured 'this'. Assign 'this' to another name outside function and capture that.

    Function code:
      (err, n) => {
          if (err) {
            if (err.code === 'EAGAIN' && this.retryEAGAIN(err, this._writingBuf.length, this._len - this._writingBuf.length)) {
              if (this.sync) {
                // This error code should not happen in sync mode, because it is
      ...

    Capturing modules can sometimes cause problems.
    Consider using import('./src/utils.ts') or require('./src/utils.ts') inside function 'callbackFactory': dynamoDBPutHandler.ts(45,34)
```

I tried the recommendation of doing dynamic imports, but it errors after successfully deploying with can't find utils.ts
