### ISSUE TITLE
pulumi up , high upload network needs (remote backend -> GCS)

### ISSUE THREAD

**Issue by raphaelauv** [pulumi/pulumi#9190]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

with pulumi v3.26.1

pulumi-gcp 6.15.1

gcs backend

I want create a new resource , but after waiting 10 minutes I hit CTRL+C , wait 1 minute then hit a second time CTRL+C

```
Previewing update (TOTO-prod):
     Type                           Name                                                          Plan       
     pulumi:pulumi:Stack            TOTO-TOTO-prod                                                       
     └─ gcp:component:all_resource  all_resource                                                             
 +      ├─ gcp:projects:IAMMember   iam_member_composer.user_XXXXXXXXX@YYYYYYYYYYYYYYYYYYY.com    create     
  
 
Resources:
    + 1 to create
    382 unchanged

Do you want to perform this update? yes
Updating (TOTO-prod):
     Type                 Name                Status     
     pulumi:pulumi:Stack  TOTO-TOTO-prod             
 C
Outputs:
    result: "DONE"

Resources:
    133 unchanged

Duration: 12m43s

panic: send on closed channel

goroutine 4935 [running]:
github.com/pulumi/pulumi/pkg/v3/engine.diagEvent(0xc00358c600, 0xc001efe090, {0xc0009e9800, 0x1c}, {0xc001c18000, 0x51}, {0x1ae12e5, 0x5}, 0x0)
        /Users/runner/work/pulumi/pulumi/pkg/engine/events.go:578 +0x1c9
github.com/pulumi/pulumi/pkg/v3/engine.(*eventEmitter).diagErrorEvent(...)
        /Users/runner/work/pulumi/pulumi/pkg/engine/events.go:602
github.com/pulumi/pulumi/pkg/v3/engine.(*eventSink).Errorf(0xc00358c600, 0x8f, {0x0, 0x2d, 0xc000fd5f18})
        /Users/runner/work/pulumi/pulumi/pkg/engine/eventsink.go:88 +0x12b
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc00218a500, 0x0, {0xc0031d2780, 0x1, 0x0})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:262 +0x2e4
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1()
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:414 +0xd9
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:411 +0x2cf
panic: send on closed channel

goroutine 4941 [running]:
github.com/pulumi/pulumi/pkg/v3/engine.diagEvent(0xc00358c600, 0xc000b6f770, {0xc001ae23c0, 0x1c}, {0xc00250c1e0, 0x51}, {0x1ae12e5, 0x5}, 0x0)
        /Users/runner/work/pulumi/pulumi/pkg/engine/events.go:578 +0x1c9
github.com/pulumi/pulumi/pkg/v3/engine.(*eventEmitter).diagErrorEvent(...)
        /Users/runner/work/pulumi/pulumi/pkg/engine/events.go:602
github.com/pulumi/pulumi/pkg/v3/engine.(*eventSink).Errorf(0xc00358c600, 0x8a, {0x0, 0x2d, 0xc000793f18})
        /Users/runner/work/pulumi/pulumi/pkg/engine/eventsink.go:88 +0x12b
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc00218a500, 0xc0004d6778, {0xc003401ba0, 0x1, 0x0})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:262 +0x2e4
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1()
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:414 +0xd9
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:411 +0x2cf

```

### Steps to reproduce

Expected: pulumi create the new resource
Actual: nothing happen

**Comment by mikhailshilkov** [comment]
@raphaelauv Does it happen every time, or just happened once? On one particular stack, or all updates? Any program that I could run to reproduce?

**Comment by raphaelauv** [comment]
Okay I got it , my UPLOAD internet speed was very low ( less than 256 KIB/s ) , but why pulumi need so much bandwidth for a so small change ?

**Comment by Frassle** [comment]
Pulumi currently writes the entire stack state across the network for every change, so bandwidth is proportional to total resources in the stack, not changes made. This is simple but highly inefficient! 

We have other issues such as https://github.com/pulumi/pulumi/issues/6074 and https://github.com/pulumi/pulumi/issues/5469 tracking this.

**Comment by raphaelauv** [comment]
okay , so I can close that issue, thanks for your answer
