### ISSUE TITLE
[sdk/go] Panic using StringPtr as input to pulumi.All

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#9192]
The following program panics.

```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var defaulted = "<defaulted>"

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		aStringOutput := pulumi.String("Test").ToStringOutput()
		aStringPtrInput := pulumi.StringPtr("Hello World")

		derived := pulumi.All(aStringOutput, aStringPtrInput).ApplyT(func(vs []interface{}) string {
			first := vs[0].(string)
			second := vs[1].(*string)

			if second == nil {
				second = &defaulted
			}

			return fmt.Sprintf("%s %s", first, *second)
		}).(pulumi.StringOutput)

		ctx.Export("result", derived)
		return nil
	})
}
```

```
  pulumi:pulumi:Stack (repro-string-ptr-dev):
    panic: reflect: Elem of invalid type interface {}
    goroutine 25 [running]:
    reflect.(*rtype).Elem(0x1719900)
    	/opt/brew/Cellar/go/1.17.8/libexec/src/reflect/type.go:954 +0x134
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.awaitInputs({0x19314f8, 0xc00003c150}, {0x17514e0, 0xc0005b4590, 0x0}, {0x1719900, 0xc00068e080, 0x194})
    	/Users/James/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.26.1/go/pulumi/types.go:723 +0xbfe
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.awaitInputs({0x19314f8, 0xc00003c150}, {0x1719900, 0xc000528090, 0xc00051c000}, {0x1719900, 0xc00068e080, 0x194})
    	/Users/James/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.26.1/go/pulumi/types.go:742 +0x1125
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.awaitInputs({0x19314f8, 0xc00003c150}, {0x16e1160, 0xc0001820c0, 0x0}, {0x16e1160, 0xc0001820d8, 0x197})
    	/Users/James/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.26.1/go/pulumi/types.go:778 +0x1985
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.toOutputTWithContext.func3()
    	/Users/James/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.26.1/go/pulumi/types.go:849 +0x131
    created by github.com/pulumi/pulumi/sdk/v3/go/pulumi.toOutputTWithContext
    	/Users/James/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.26.1/go/pulumi/types.go:841 +0x365
    exit status 2

    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

**Comment by lukehoban** [comment]
This might be the same root cause as https://github.com/pulumi/pulumi/issues/7706?
