### ISSUE TITLE
StackReference Cannot be Mocked from a Unit Test

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#9212]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

As a developer, I want to be able to mock `StackReferences` in my code, so that I can detach external data sources and solely test my local code without external dependencies. Currently, instead of invoking the `newResource` method of the Pulumi `mock` unit test framework, Pulumi attempts to read the external `StackReference`, which results in an error.

### Steps to reproduce

1. Create two Pulumi programs.
2. One which creates a resource and exports something relevant, like a S3 bucket and bucket ID. The second reads in the bucket ID via `StackReference` and utilizes the value in some way.
3. Create a unit test in program 2 that attempts to mock the `StackRefernce`.
4. Execute the unit test
5. View the error.

### Code
**Program 1**
```typescript
import * as aws from "@pulumi/aws";

// Create an AWS resource (S3 Bucket)
const bucket = new aws.s3.Bucket("my-bucket");

// Export the name of the bucket to be used by consumer stack
export const stackBucket = bucket.id;
```

**Program 2**
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const myStackRef = new pulumi.StackReference("phillipedwards/stackref-test-bucket/dev")
const val = myStackRef.requireOutput("stackBucket");

// Create an AWS resource (S3 Bucket)
const bucket = new aws.s3.Bucket("my-bucket");

// Export the name of the bucket
export const stackBucket = val;
```
**Unit Test**
```typescript
import * as pulumi from '@pulumi/pulumi';
import 'mocha';

pulumi.runtime.setMocks({
    /* eslint-disable @typescript-eslint/no-explicit-any */
    newResource: function (args: pulumi.runtime.MockResourceArgs): { id: string, state: any } {
        /* eslint-enable @typescript-eslint/no-explicit-any */
        
        console.log(args);
        switch (true) {
            case /aws:/.test(args.type): {
                console.log("hitting aws case for newResource()");
                return {
                    id: args.name + '_id',
                    state: { name: `${args.name}-0000000`, arn: `arn:${args.name}-0000000`, ...args.inputs },
                }
            }
            default:
                console.log("hitting default case for newResource()");
                return {
                    id: args.name + '_id',
                    state: { name: `${args.name}-0000000`, ...args.inputs },
                };

        }

    },
    call: function (args: pulumi.runtime.MockCallArgs) {
        console.log("hi call");
        console.log(args);
        return args.inputs;
    },
});


describe("Infrastructure", function () {
    let infra: typeof import("./index")
    before(async function () {
        infra = await import('./index')
    })
    it("testStackReferenceWithMocks", function () {
        try {
            const something = infra.stackBucket
            console.log(something);
        } catch (e) {
            console.error(e)
        }
    })
})
```

Expected:  `StackReferences` are captured by the `default` case and "mocked".
Actual:  `StackReference` produces an error:
```
Promise {
  <rejected> <ref *1> Error: failed to read resource #phillipedwards/stackref-test-bucket/dev 'phillipedwards/stackref-test-bucket/dev' [pulumi:pulumi:StackReference]: req.getCustom is not a function
      at Object.readResource (/Users/pedwards/repos/stackref-test/node_modules/@pulumi/runtime/resource.ts:206:27)
      at new Resource (/Users/pedwards/repos/stackref-test/node_modules/@pulumi/resource.ts:387:13)
      at new CustomResource (/Users/pedwards/repos/stackref-test/node_modules/@pulumi/resource.ts:768:9)
      at new StackReference (/Users/pedwards/repos/stackref-test/node_modules/@pulumi/stackReference.ts:52:9)
      at Object.<anonymous> (/Users/pedwards/repos/stackref-test/index.ts:5:20)
      at Module._compile (internal/modules/cjs/loader.js:1072:14)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
      at Module.load (internal/modules/cjs/loader.js:937:32)
      at Function.Module._load (internal/modules/cjs/loader.js:778:12)
      at Module.require (internal/modules/cjs/loader.js:961:19)
      at require (internal/modules/cjs/helpers.js:92:18)
      at /Users/pedwards/repos/stackref-test/test.ts:39:17 {
    promise: Promise { <rejected> [Circular *1] }
  }
```

**Comment by zbuchheit** [comment]
I had this issue and as a workaround I used sinon to stub requireOutput while waiting for this issue/feature to be implemented.

Example:
sinon.stub(pulumi.StackReference.prototype, ‘requireOutput’).callsFake( () => pulumi.output(“Fake”));

**Comment by dblair-cet** [comment]
I'm running into this issue with the .Net API too. Doesn't need to be complicated just need `StackReference` to implement an interface that I can mock.

**Comment by StevenDenman** [comment]
I too am facing this issue where one stack relies on outputs from an earlier stack and cant get it. I tried to set the outputs for the stack reference in NewResourceAsync, but unfortunately that doesn't work (presumably as the stack reference doesn't have the properties with the output attribute)

**Comment by tgummerer** [comment]
I believe this issue has been fixed in https://github.com/pulumi/pulumi/pull/12072.  I gave the original reproduction a try with the latest version of pulumi, and the tests pass successfully now.  I'm going to close this issue out, but let us know if it's still not working.

**Comment by jasond-s** [comment]
> I believe this issue has been fixed in #12072. I gave the original reproduction a try with the latest version of pulumi, and the tests pass successfully now. I'm going to close this issue out, but let us know if it's still not working.

We are still seeing this in the .NET testing package. 

```public class TestStack : Stack
{
    public TestStack()
    {
        var stackRef = new StackReference("stack-ref");
        var output = stackRef.GetOutput("test-output");
    }
}```

This is the minimal failing test stack that I can create.
