### ISSUE TITLE
Function serialization fails to capture variable in closure

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#9318]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Appears that nodejs function serialization fails to serialize a function that declares a variable without `var`/`let`/`const` keyword. Was running into an issue with capturing a closure in some code that I imported.

index.ts
```typescript
import * as aws from "@pulumi/aws";
const {wew} = require("./wack");

new aws.lambda.CallbackFunction("myfun", {
  callback: (event) => {
    wew();
  }
})

```

wew.js
```javascript
module.exports = {
  wew: function() {
    foo = 1; // variable declaration
    return foo;
  }
}
```

```
255 kdixler@kdixler-20xw004aus ~/Documents/unify (git)-[master] % pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/kyle/unify/dev/previews/57555a1c-a3f7-4b7d-a8e4-b42bb697d5b4

     Type                             Name            Plan       Info
     pulumi:pulumi:Stack              unify-dev                  1 error
 +   ├─ aws:s3:Bucket                 myResource      create     
 +   ├─ aws:iam:RolePolicyAttachment  myfun-a1de8170  create     
 +   ├─ aws:iam:RolePolicyAttachment  myfun-e1a3786d  create     
 +   ├─ aws:iam:RolePolicyAttachment  myfun-1b4caae3  create     
 +   ├─ aws:iam:RolePolicyAttachment  myfun-4aaabb8e  create     
 +   ├─ aws:iam:RolePolicyAttachment  myfun-b5aeb6b6  create     
 +   ├─ aws:iam:RolePolicyAttachment  myfun-7cd09230  create     
 +   ├─ aws:iam:RolePolicyAttachment  myfun-6c156834  create     
 +   ├─ aws:iam:RolePolicyAttachment  myfun-74d12784  create     
 +   └─ aws:iam:RolePolicyAttachment  myfun-019020e7  create     
 
Diagnostics:
  pulumi:pulumi:Stack (unify-dev):
    error: Error: Error serializing '(event) => { wew(); ...': index.ts(32,14)
    
    '(event) => { wew(); ...': index.ts(32,14): referenced
      function 'wew': wack.js(2,15): which could not be serialized because
        Unexpected missing variable in closure environment: foo
    
    Function code:
      function() {
          foo = 1;
          return foo;
        }
    
        at throwSerializationError (/home/kdixler/Documents/unify/node_modules/@pulumi/runtime/closure/createClosure.ts:712:11)
        at /home/kdixler/Documents/unify/node_modules/@pulumi/runtime/closure/createClosure.ts:537:21
        at Generator.throw (<anonymous>)
        at rejected (/home/kdixler/Documents/unify/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:19:65)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to reproduce

1.
2.
3.
4.

Expected: Function serialization to serialize the function.
Actual: Throws an error.

**Comment by dixler** [comment]
@mikhailshilkov for some context, I ran into this issue when closure serialization managed to serialize a method from the aws-sdk which had a declaration like that in a function body.
