### ISSUE TITLE
Every AWS data source call results in a panic after upgrading provider from v4.33 to v4.38

### ISSUE THREAD

**Issue by iridian-ks** [pulumi/pulumi#9319]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Calls to what seems to be _any_ AWS data source results in a panic. This is happening after upgrading the provider from v4.33 to v4.38. Unsure how to proceed with upgrading.

### Steps to reproduce

1. Create AWS resources such as: EKS clusters, NodeGroups, IAM policies, etc
2. Use version v4.33
3. Upgrade to latest
4. Panic

Expected: Data sources should work as normal after upgrading
Actual: Panics

```
panic: fatal: An assertion has failed
                                                                                                                                                            goroutine 237 [running]:                                                                                                                                    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)                                                                                                 /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v3/resource/deploy.NewDeleteReplacementStep(0xc0051d0b00, 0xc002336360, 0xe0)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step.go:306 +0x16c
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).generateStepsFromDiff(0xc0052950e0, {0x7f5473a53a20, 0xc00257b340}, {0xc004b78780, 0x0}, 0xc0022d9e60, 0xc003bc7200, 0xc003ed87b0, 0xc004206120, 0xc0041f72f0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:820 +0x1445
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).generateSteps(0xc0052950e0, {0x7f5473a53a20, 0xc00257b340})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:607 +0x1c72
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).GenerateSteps(0xc0052950e0, {0x7f5473a53a20, 0xc00257b340})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:190 +0x46
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).handleSingleEvent(0xc0027b4180, {0x1e84980, 0xc00257b340})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:413 +0xe5
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute.func3(0xc005af49c0, 0xc0027b4180, 0xc004c2b9c0, {0x1eb6890, 0xc00581e040}, 0x0, 0x0, {0x1eb6938, 0xc00305aab0})                                                                                                                                   /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:250 +0x273
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute(0xc0027b4180, {0x1eb6938, 0xc00305aab0}, {{0x7f5473ef0a98, 0xc00124c160}, 0x7fffffff, 0x0, 0x0, {0x2cc8a18, 0x0, ...}, ...}, ...)                                                                                                                 /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:266 +0x95f
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Deployment).Execute(0xc0051d0b00, {0x1eb6938, 0xc00305aab0}, {{0x7f5473ef0a98, 0xc00124c160}, 0x7fffffff, 0x0, 0x0, {0x2cc8a18, 0x0, ...}, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:447 +0xd0
github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run.func1()
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:269 +0x250
created by github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:252 +0x371
```

Data sources I was using (Python):

- pulumi_aws.iam.get_user
- pulumi_aws.iam.get_role
- pulumi_aws.route53.get_zone

I was able to definitely get it to the data source by littering the code with `pulumi.warn("tickX")` and the very last debug line shows up in the Pulumi status field (`-d` not working). Every time a data source was hit it did a panic.

When setting up a brand new stack this didn't happen. When the `aws-provider` resource I was creating had a change in the version number then this happened.

I'm sure this isn't enough information to figure out what's going on, but IDK what else to provide. I tested on Pulumi v3.26.1 and I saw some panic bugs fixed in v3.27.0, but got the exact same behavior. The resources were originally created with Pulumi v3.19.0.

Disclaimer: Apologies if this should be under the `pulumi-aws` project but the stacktrace is in Pulumi proper so thought this was appropriate.

**Comment by iridian-ks** [comment]
The stack trace is overlapping with the output so I can't tell which resource in particular is being problematic

```
goroutine 296 [running]::aws          aws-provider                                 update                 [diff: ~profile,version]
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)              replace
 +-  └─ /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23create replacement     [diff: ~name]
```

Hard to see but note both the `replace` and `create replacement` lines. They are on the same lines as the stack trace.

**Comment by iridian-ks** [comment]
Here's an example piece of code:

```
        pulumi.warn("tick12")
        zone = aws.route53.get_zone(
            name=f"{self.zone}.",
            private_zone=True,
            opts=self.aws_invoke,
        )
        pulumi.warn("tick13")
```

Some Pulumi output

```
     Type                             Name                                         Plan        Info
     pulumi:pulumi:Stack              core-inf-develop-pci                         running     warning: tick12
```

Followed by the same stacktrace as above.

I'm going to downgrade the provider and get the stack clean then try upgrading again and see if it helps.

**Comment by mikhailshilkov** [comment]
If you don't feel like sharing the logs publicly due to potentially sensitive data, you can also email them to mikhail@pulumi.com. (Or, feel free to mask any private data of course).
