### ISSUE TITLE
serializeFunction throws when serializing async generators

### ISSUE THREAD

**Issue by skyrpex** [pulumi/pulumi#9344]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Serializing a callback that uses an async generator crashes with the following error:

```
Error: Remote object was not 'function': {"type":"object","className":"AsyncGeneratorFunction","description":"AsyncGeneratorFunction","objectId":"7622203698069076896.2.78"}
```

### Steps to reproduce

1. Create the following `index.js` file:

```js
import { runtime } from "@pulumi/pulumi"

async function* run() {
  // Sleep for 100ms, see: https://masteringjs.io/tutorials/fundamentals/sleep
  await new Promise((resolve) => setTimeout(resolve, 100))
  yield "Hello"
  console.log("World")
}

runtime.serializeFunction(() => {
  // `run()` returns an async iterator.
  const asyncIterator = run()

  // The function doesn't start running until you call `next()`
  asyncIterator
    .next()
    .then((object) => console.log(object.value)) // Prints "Hello"
    .then(() => asyncIterator.next()) // Prints "World"
})
```

2. Run it:

```sh
node index.js
```

Expected:  The function gets serialized along with the async generator.

Actual:  It throws an error.

```
/Code/my-app/node_modules/.pnpm/@pulumi+pulumi@3.28.0/node_modules/@pulumi/pulumi/runtime/closure/v8_v11andHigher.js:18
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
                                                         ^
Error: Remote object was not 'function': {"type":"object","className":"AsyncGeneratorFunction","description":"AsyncGeneratorFunction","objectId":"7622203698069076896.2.78"}
    at /Code/my-app/node_modules/.pnpm/@pulumi+pulumi@3.28.0/node_modules/@pulumi/runtime/closure/v8_v11andHigher.ts:181:19
    at Generator.next (<anonymous>)
    at fulfilled (/Code/my-app/node_modules/.pnpm/@pulumi+pulumi@3.28.0/node_modules/@pulumi/pulumi/runtime/closure/v8_v11andHigher.js:18:58)
```

As a workaround, defining the async generator inside the callback works:

```js
import { runtime } from "@pulumi/pulumi"

runtime.serializeFunction(() => {
  async function* run() {
    // Sleep for 100ms, see: https://masteringjs.io/tutorials/fundamentals/sleep
    await new Promise((resolve) => setTimeout(resolve, 100))
    yield "Hello"
    console.log("World")
  }

  // `run()` returns an async iterator.
  const asyncIterator = run()

  // The function doesn't start running until you call `next()`
  asyncIterator
    .next()
    .then((object) => console.log(object.value)) // Prints "Hello"
    .then(() => asyncIterator.next()) // Prints "World"
})
```

**Comment by andreujuanc** [comment]
Because I transpile first to JS, I had the issue but found that if I target ES2016 it works fine. 
So that one is a second workaround :)
