### ISSUE TITLE
Ubuntu 20.04 LTS ships node 10, and while its unsupported the error message is less than desirable. 

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#9521]
### What happened?

#6760 made nodejs < 11 deprecated.

```
Error: 
pulumi:pulumi:Stack (quickstart-ts-dev):
    error: Running program '/home/rshade/pulumi_projects/quickstart' failed with an unhandled exception:
    Error: Should not call getSessionAsync unless on Node11 or above.
        at Object.<anonymous> (/home/rshade/pulumi_projects/quickstart/node_modules/@pulumi/runtime/closure/v8Hooks.ts:64:15)
        at Generator.next (<anonymous>)
        at /home/rshade/pulumi_projects/quickstart/node_modules/@pulumi/pulumi/runtime/closure/v8Hooks.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/home/rshade/pulumi_projects/quickstart/node_modules/@pulumi/pulumi/runtime/closure/v8Hooks.js:17:12)
        at Object.getSessionAsync (/home/rshade/pulumi_projects/quickstart/node_modules/@pulumi/pulumi/runtime/closure/v8Hooks.js:65:12)
        at /home/rshade/pulumi_projects/quickstart/node_modules/@pulumi/runtime/closure/v8_v11andHigher.ts:132:51
        at Generator.next (<anonymous>)
        at /home/rshade/pulumi_projects/quickstart/node_modules/@pulumi/pulumi/runtime/closure/v8_v11andHigher.js:21:71
        at new Promise (<anonymous>)


rshade@LAPTOP-8F1BDL67:~/pulumi_projects/quickstart$ node --version
v10.19.0
```
### Steps to reproduce

Using WSL - Ubuntu 20.04 for development

1. sudo apt-get install nodejs  npm -y
2. run thru quickstart

### Expected Behavior

Catch the exception and report a better error message. 

`NodeJS > 11 Supported, please upgrade: https://nodejs.org/en/download/package-manager/`

### Actual Behavior

It throws the unhandled exception above.

### Versions used

CLI          
Version      3.31.0
Go Version   go1.17.9
Go Compiler  gc

Host     
OS       ubuntu
Version  20.04
Arch     x86_6

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
@rshade why is this completed?

**Comment by rshade** [comment]
It looks like all that code is gone in v8hooks.ts? https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/runtime/closure/v8Hooks.ts
