### ISSUE TITLE
LogException using Pulumi.Automation in C#

### ISSUE THREAD

**Issue by ffMathy** [pulumi/pulumi#9582]
### What happened?

```
Pulumi.LogException: Error occurred during logging

Pulumi.LogException
Error occurred during logging
   at Pulumi.Deployment.EngineLogger.LogAsync(LogSeverity severity, String message, Resource resource, Nullable`1 streamId, Nullable`1 ephemeral)
   at Pulumi.Deployment.Runner.LogExceptionToErrorStream(Exception exception)
   at Pulumi.Deployment.Runner.HandleExceptionsAsync(IEnumerable`1 exceptions)
   at Pulumi.Deployment.<>c__DisplayClass71_0.<<RunInlineAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Pulumi.Automation.WorkspaceStack.UpAsync(UpOptions options, CancellationToken cancellationToken)
   at Pulumi.Automation.WorkspaceStack.UpAsync(UpOptions options, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
--- End of stack trace from previous location ---
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)

Grpc.Core.RpcException
Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: Connection refused (127.0.0.1:52034) SocketException: Connection refused", DebugException="System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:52034)
 ---> System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at Pulumi.GrpcEngine.LogAsync(LogRequest request)
   at Pulumi.Deployment.EngineLogger.LogAsync(LogSeverity severity, String message, Resource resource, Nullable`1 streamId, Nullable`1 ephemeral)
```

### Steps to reproduce

Run Pulumi up via Pulumi automation. Not sure what is causing it to happen.

### Expected Behavior

That the command didn't fail.

### Actual Behavior

It failed (see above error).

### Versions used

```
CLI          
Version      3.32.1
Go Version   go1.18.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.4.0
dotnet  unknown
tls     4.4.0

Host     
OS       darwin
Version  12.3.1
Arch     arm64

This project is written in dotnet (/usr/local/share/dotnet/dotnet v6.0.200)

Backend        
URL            file://~
Organizations  

NAME             VERSION
Newtonsoft.Json  13.0.1
Pulumi           3.32.1
Pulumi.Aws       5.4.0
Pulumi.Tls       4.4.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ffMathy** [comment]
Downgrading Pulumi installation to 3.31.1 fixed the issue.

**Comment by Frassle** [comment]
Is this reproducible? Nothing changed in the dotnet sdk between 3.31.1 and 3.32.1, was this just bad luck that it failed once on 3.32 and then happened to work when you wound back to 3.31?

**Comment by ffMathy** [comment]
It might have been.

It seems that the downgrade did indeed not have anything to do with it. It just happens 90% of the time. I've just done around 10 runs, and only one of them succeeded.

All others failed with the above error, and it's not very self-explanatory.

**Comment by Frassle** [comment]
`Connection refused` looks like the engine shutdown. Can you hook onto the `OnStandardOutput` and `OnStandardError` options of `UpOptions` and see if the engine is printing anything to those?

**Comment by ffMathy** [comment]
> `Connection refused` looks like the engine shutdown. Can you hook onto the `OnStandardOutput` and `OnStandardError` options of `UpOptions` and see if the engine is printing anything to those?

Hmmm I've been digging deeper into this. It seems that it happens within a retry mechanism.

I use Polly to retry setting up the whole stack again if there is an exception. The first exception is indeed showing my problem (in this case a resource couldn't be updated), but then when everything is tried again, this exception is thrown instead.

Any clue what is going on?

**Comment by ffMathy** [comment]
Still relevant. I'm the one that didn't hear from you, not the other way around.

**Comment by Frassle** [comment]
Yup sorry about that, we need to manually clear those labels. Clearing the labels now and I'll have a look into this during the work week.

**Comment by Frassle** [comment]
> Run Pulumi up via Pulumi automation.

Is this "up" for an inline program or a folder deployment? I suspect given the bug this was an inline program?

**Comment by ffMathy** [comment]
Yes, it was an inline deployment. The working directory was also modified.

**Comment by ffMathy** [comment]
Also, typically this would happen if the whole thing failed and I had a try/catch which would retry again.

Perhaps because the directory was the same, something there would fail?

**Comment by Frassle** [comment]
I've been trying to repro this by running UpAsync in a loop with it sometimes throwing an exception, and with it always throwing an exception and I can't get any errors to trigger.

Do you have any more logs/output/code you can share to try and repro and track this down? I can't see any obvious reason in the code how this could get hit (well unless there's a grpc bug, but lets hope its not that).

**Comment by ffMathy** [comment]
Did you set the working directory of the stack to the same in automation?

I think that could be needed for it to trigger.

I suspect that's when it happens.

**Comment by ffMathy** [comment]
And did you also dispose it between runs?

**Comment by ffMathy** [comment]
M1 😊

**Comment by Frassle** [comment]
Ah they have been a source of various grpc issues. I'm probably not going to be able to repro this on my intel mac. Will ping this internally to see if any engineers with M1 have capacity to pick it up.

**Comment by ffMathy** [comment]
Oh wow. Would have never thought M1 and grpc would be relatable in any way 😅

That sounds like a debugging nightmare for you 😅

**Comment by Zaid-Ajaj** [comment]
Hi there @ffMathy, I am looking at the issue here and I see that you are using dotnet SDK v6.0.200 which is good but what is the _target framework_ of your C# project? I've seen this error pop up in C# projects targeting v3.1.0 on M1 machines and being built and ran from the latest dotnet SDK v6.

Updating the target framework of the project to `net6.0` stabilized the issue when I encountered it, can you please give that another try? In the meantime, I will to repro the issue at hand and let you know how it goes

**Comment by ffMathy** [comment]
The target framework is dotnet6.

The issue still occurs, and I just tried upgrading all my Pulumi plugins and NuGet packages to the latest version, prior to this.

**Comment by ffMathy** [comment]
@Frassle and/or @Zaid-Ajaj can we re-open this?

**Comment by ffMathy** [comment]
Hmmm, ironically, if I delete the `stacks`, `locks` and `pulumi` folder (from current directory) when that error happens, it seems it fixes the issue. For a while.

However, not on the later versions it seems.

Is there any form of logging I can enable to help you all resolve this?

**Comment by ffMathy** [comment]
Also, it seems like the above only helps Pulumi get a little further. It still crashes half way through the process.

**Comment by ffMathy** [comment]
Here are my project settings:

```xml
    <PropertyGroup>
        <RootNamespace>xxx</RootNamespace>
        <AssemblyName>xxx</AssemblyName>
        <TargetFramework>net6.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
        <LangVersion>default</LangVersion>
    </PropertyGroup>
```

**Comment by ffMathy** [comment]
According to this, it could perhaps be a company network issue? I am doing this from a work computer, which is via a VPN.
https://stackoverflow.com/questions/66500195/net-5-grpc-client-call-throws-exception-requesting-http-version-2-0-with-versi

However, I don't have the given environment variables set.

I'm on an M1 MacBook Pro.

**Comment by ffMathy** [comment]
Okay, interesting. Look at the second answer of this post:
https://stackoverflow.com/a/69553548/553609

I just set the `no_proxy` environment variable to `"localhost,127.0.0.1"`, and it seems like it hasn't crashed yet. Will run a bit more with it to see if that's the permanent solution.

Then it must have something to do with my company's VPN. I wonder why this happens - it should never proxy localhost I suppose?

What would the fix for this be? I feel like it should maybe be fixed in GRPC, or perhaps in Pulumi by default setting that variable to not proxy on localhost.

**Comment by Frassle** [comment]
Bit late here and I've got to run, but normally running through the CLI I'd say to run with `-v10 --logtostderr`. I think there's an automation api option to turn that on as well somewhere in the UpdateSettings. It _might_ give some more information.

**Comment by ffMathy** [comment]
The `no_proxy` thing seems to stabilize things (haven't seen the crash yet), but as soon as I update to the latest version, even with `no_proxy`, I encounter the issue after a while.

Will try with those arguments soon.

**Comment by ffMathy** [comment]
Argh, enabling those arguments appear to have stabilized things quite a bit. I haven't gotten the exception now for a while, but it might be coincidence.

I am genuinely sorry that my reports are inconsistent and left-and-right, and based on hunches. It's like Shröedingers Bug or something. When I want to measure it, it disappears.

**Comment by ffMathy** [comment]
The error just happened again. I tried changing my code so I don't manually also run `pulumi` commands from the commandline aside from via the automation API.

Before, I was doing things like running `pulumi cancel` automatically in my integration tests, which is not supported by Automation API, so I was invoking it programmatically with `Process.Start`.

**Comment by ffMathy** [comment]
Ooooh, interesting. I don't know when this happened, but now the InnerException is actually different.

Here's the full exception now. Running latest Pulumi and latest of all plugins.

```
Pulumi.LogException: Error occurred during logging
 ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake.", DebugException="System.Net.Http.HttpRequestException: An HTTP/2 connection could not be established because the server did not complete the HTTP/2 handshake.
   at System.Net.Http.HttpConnectionPool.ReturnHttp2Connection(Http2Connection connection, Boolean isNewConnection)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at Pulumi.GrpcEngine.LogAsync(LogRequest request)
   at Pulumi.Deployment.EngineLogger.LogAsync(LogSeverity severity, String message, Resource resource, Nullable`1 streamId, Nullable`1 ephemeral)
   --- End of inner exception stack trace ---
   at Pulumi.Deployment.EngineLogger.LogAsync(LogSeverity severity, String message, Resource resource, Nullable`1 streamId, Nullable`1 ephemeral)
   at Pulumi.Deployment.<>c__DisplayClass75_0.<<RunInlineAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
```

**Comment by ffMathy** [comment]
Okay, hooking into stderr as you requested yields something interesting. Looking at the process monitor, I can also indeed confirm that the update starts running through a bit (because I can see a lot of AWS-native and AWS processes starting up for a while).

Then it throws this on the standard error output:

```
[19:54:45 INF] Updating (xxx):
[19:54:56 ERR] I1104 19:54:40.510985   35239 update.go:190] *** Starting Update(preview=false) ***
[19:55:01 ERR] I1104 19:54:40.511262   35239 plugins.go:120] gatherPluginsFromProgram(): gathering plugins from language host
[19:55:01 INF] @ updating....
[19:55:08 INF] 
[19:55:08 ERR] I1104 19:54:40.511271   35239 langruntime_plugin.go:111] langhost[client].GetRequiredPlugins(proj=iac,pwd=xxx,program=.) executing
[19:55:14 ERR] I1104 19:55:00.510662   35239 langruntime_plugin.go:120] langhost[client].GetRequiredPlugins(proj=iac,pwd=xxx,program=.) failed: err=failed to receive server preface within timeout
[19:55:14 ERR] I1104 19:55:00.510864   35239 update.go:193] *** Update(preview=false) complete ***
[19:55:14 ERR] I1104 19:55:03.150508   35239 sink.go:153] defaultSink::Error(error: failed to discover plugin requirements: failed to receive server preface within timeout
[19:55:14 ERR] github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.GetRequiredPlugins
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:569
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/engine.gatherPluginsFromProgram
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/engine/plugins.go:122
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/engine.installPlugins
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/engine/update.go:225
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/engine/update.go:376
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/engine.newDeployment
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:161
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/engine.update
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/engine/update.go:451
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/engine.Update
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/engine/update.go:193
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).apply
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:622
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/backend/apply.go:238
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).Update
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:505
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/backend/stack.go:91
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localStack).Update
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/stack.go:77
[19:55:14 ERR] main.newUpCmd.func1
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:181
[19:55:14 ERR] main.newUpCmd.func3
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:494
[19:55:14 ERR] github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112
[19:55:14 ERR] github.com/spf13/cobra.(*Command).execute
[19:55:14 ERR]  /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876
[19:55:14 ERR] github.com/spf13/cobra.(*Command).ExecuteC
[19:55:14 ERR]  /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990
[19:55:14 ERR] github.com/spf13/cobra.(*Command).Execute
[19:55:14 ERR]  /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
[19:55:14 ERR] main.main
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48
[19:55:14 ERR] runtime.main
[19:55:14 ERR]  /Users/runner/hostedtoolcache/go/1.19.2/x64/src/runtime/proc.go:250
[19:55:14 ERR] runtime.goexit
[19:55:14 ERR]  /Users/runner/hostedtoolcache/go/1.19.2/x64/src/runtime/asm_arm64.s:1172
[19:55:14 ERR] )
[19:55:14 ERR] error: failed to discover plugin requirements: failed to receive server preface within timeout
[19:55:14 ERR] github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.GetRequiredPlugins
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:569
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/engine.gatherPluginsFromProgram
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/engine/plugins.go:122
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/engine.installPlugins
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/engine/update.go:225
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/engine/update.go:376
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/engine.newDeployment
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:161
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/engine.update
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/engine/update.go:451
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/engine.Update
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/engine/update.go:193
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).apply
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:622
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/backend/apply.go:238
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).Update
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:505
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/backend/stack.go:91
[19:55:14 ERR] github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localStack).Update
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/stack.go:77
[19:55:14 ERR] main.newUpCmd.func1
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:181
[19:55:14 ERR] main.newUpCmd.func3
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:494
[19:55:14 ERR] github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112
[19:55:14 ERR] github.com/spf13/cobra.(*Command).execute
[19:55:14 ERR]  /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876
[19:55:14 ERR] github.com/spf13/cobra.(*Command).ExecuteC
[19:55:14 ERR]  /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990
[19:55:14 ERR] github.com/spf13/cobra.(*Command).Execute
[19:55:14 ERR]  /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
[19:55:14 ERR] main.main
[19:55:14 ERR]  /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48
[19:55:14 ERR] runtime.main
[19:55:14 ERR]  /Users/runner/hostedtoolcache/go/1.19.2/x64/src/runtime/proc.go:250
[19:55:14 ERR] runtime.goexit
[19:55:14 ERR]  /Users/runner/hostedtoolcache/go/1.19.2/x64/src/runtime/asm_arm64.s:1172
[19:55:14 ERR] 
```

**Comment by ffMathy** [comment]
@Frassle does this help reveal anything to you of what went wrong?

**Comment by ffMathy** [comment]
I also tried both with VPN on, and VPN off.

**Comment by ffMathy** [comment]
I am using the following code to install plugins via Pulumi Automation:

```csharp
private async Task InstallPulumiPlugins(WorkspaceStack stack, CancellationToken cancellationToken)
{
    const string pulumiPluginPrefix = "Pulumi.";
    var pulumiPluginAssemblies = typeof(InfrastructureStack).Assembly
        .GetReferencedAssemblies()
        .Where(assemblyName => assemblyName.FullName.StartsWith(pulumiPluginPrefix))
        .ToImmutableArray();

    foreach (var plugin in pulumiPluginAssemblies)
    {
        if (plugin.Name == null)
            throw new InvalidOperationException("Could not find plugin name.");

        if (plugin.Version == null)
            throw new InvalidOperationException("Could not find plugin version.");

        var pluginName = plugin.Name
            .Substring(pulumiPluginPrefix.Length)
            .ToKebabCase();

        _logger.Information("Installing plugin {PluginName} v{PluginVersion}", pluginName, plugin.Version);
        await stack.Workspace.InstallPluginAsync(
            pluginName,
            plugin.Version.ToString(3),
            PluginKind.Resource,
            new PluginInstallOptions()
            {
                ExactVersion = true
            },
            cancellationToken);
    }
}
```

Maybe this is what messes things up?

Also, while I am using Pulumi Automation, I am actually creating it via a *real* stack that I initialized. The reason for this is that I use `pulumi stack init my-local-stack --non-interactive --copy-config-from real-stack` to make sure my values from my own stack get copied over.

I use it when debugging locally, or running tests. Essentially I create a "clone" of all my resources, but with a specific name suffix given by an environment variable. So "-tests" for tests, and "-debug" for debug environment.

**Comment by ffMathy** [comment]
I tried commenting out the plugin installation code. The issue remains the same.

**Comment by ffMathy** [comment]
Hmmmm! New interesting discovery!

If I forward standard out, and then when it crashes, I hit a breakpoint and look at the logs, I can see that (at least the last 10 times I've tried running it), whenever I get the LogException, it actually shows that it succesfully performed the operation!

I can see X amount of resources updated etc, and I can also tell that it works.

If this is true, the issue could be as simple as being more resilient in case the `pulumi` process shuts down on success? Perhaps it's closing its connection too soon?

cc @Frassle

**Comment by ffMathy** [comment]
And by "successfully performed", in this case, I actually have an error 400 from AWS for 2 resources, but at least the command runs all the way through.

**Comment by ffMathy** [comment]
Aha @Frassle! I can now confirm that the LogException only occurs if the `up` operation actually fails in AWS, and gives an error 400!

If the operation is succesful, it doesn't throw a LogException.

In addition, *when* it throws a LogException, the stdout reveals that it also did indeed complete successfully!

Can you repro with this information? More specifically, the 400 that happened was due to making a Lambda function via AWS native which did not have a proper S3 Bucket key set (pointing to some resource that didn't exist).

But I suspect it may happen on any failure.

**Comment by Frassle** [comment]
> Can you repro with this information?

Oh maybe, sounds like the parsing is getting tripped up somewhere.

**Comment by ffMathy** [comment]
I see @Zaid-Ajaj is assigned to this.

Anyway, so just to recap the whole contents of this issue:

- It seems to be happening only if Pulumi actually fails, not during success.
- It seems to be terminating early somehow in those scenarios, throwing a connection exception due to the process exiting too soon and not gracefully disconnecting on shutdown.
- It is not related to VPN or proxying or anything like that.

CC @Frassle.
