### ISSUE TITLE
FileAsset unable to get zip files

### ISSUE THREAD

**Issue by SeamusY** [pulumi/pulumi#9585]
### What happened?

While attempting to follow the guide on this : https://www.pulumi.com/docs/intro/concepts/assets-archives/

I attempted to read a zip file that was in a separate folder, but I couldn't figure the path. In the documentation, it seems that the path was "Relative" but when running pulumi it was "Absolute path" was required. I was confused.

While looking around on google, I finally came upon this: 
https://medium.com/swlh/migrating-serverless-to-pulumi-project-7ce798103505

In this article, I only copied the function "relativeRootPath" and used it to find the zip file path, to pass to the parameter "Code" without the "FileAsset".

I'd like to know if something is wrong with the documentation or am I missing something? 

### Steps to reproduce

1. Copy the code below:
```
export function createLambda(name: string, file: string, policy: aws.iam.Policy) {
        let zipFile = new pulumi.asset.FileArchive("./Handler.zip")
        let roles = createRole(`lambda-roles`, lambda_roles, {"primary_roles": "Enable Lambda function"});
        new aws.iam.RolePolicyAttachment("basic_lambda", {
            role: roles.name,
            policyArn: cloud_trail_policy.arn
        })
        console.log(zipFile);
        new aws.lambda.Function(name, {
            code: zipFile,
            role: roles.arn,
            handler: "index.handler",
            runtime: "nodejs14.x",
            timeout: 300
        });
    }
```

2. Create a simple Handler.zip, with an Index.js inside. 
3. Pulumi up and watch

### Expected Behavior

pulumi up to create the lambda and run accordingly without error.

### Actual Behavior

While using FileArchive:
```

Diagnostics:
  pulumi:pulumi:Stack (data_ingestion_project-dev):
    /Users/User/Documents/Folder/Testing/Lambda/Function/Handler.zip
 
    error: Error: failed to register new resource Handler [aws:lambda/function:Function]: 2 UNKNOWN: failed to compute archive hash for "code": open /Users/User/Documents/Folder/Testing/Lambda/Function/Handler.zip: no such file or directory
        at Object.registerResource (/Users/User/Folder/Github/Testing/aws_infrastructure/node_modules/@pulumi/runtime/resource.ts:295:27)
        at new Resource (/Users/Seamus/Documents/Github/Data-Ingestion-Project/aws_infrastructure/node_modules/@pulumi/resource.ts:393:13)
        at new CustomResource...
```

While using Medium Walkthrough above (Which Worked):
```
function relativeRootPath(path: string) {
    return join(process.cwd(), "..", path)
  }

export function createLambda(name: string, file: string, cloud_trail_policy: aws.iam.Policy) {
        let zipFile = relativeRootPath(file) // E.g Absolute Path from Project Root
        let roles = createRole(`lambda-roles`, lambda_roles, {"primary_roles": "Enable Lambda function"});
        new aws.iam.RolePolicyAttachment("basic_lambda", {
            role: roles.name,
            policyArn: cloud_trail_policy.arn
        })
        console.log(zipFile);
        new aws.lambda.Function(name, {
            code: zipFile,
            role: roles.arn,
            handler: "index.handler",
            runtime: "nodejs14.x",
            timeout: 300
        });
    }
```

### Versions used

CLI          
Version      3.32.1
Go Version   go1.18.1
Go Compiler  gc

Plugins
NAME            VERSION
aws             5.4.0
aws             4.38.1
aws-apigateway  0.0.6
docker          3.2.0
nodejs          unknown

Host     
OS       darwin
Version  12.3.1
Arch     arm64

This project is written in nodejs (/usr/local/bin/node v14.18.3)

NAME                    VERSION
@pulumi/aws             5.4.0
@pulumi/aws-apigateway  0.0.6
@pulumi/awsx            0.40.0
@pulumi/pulumi          3.32.1
@types/node             14.18.16

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @SeamusY I'm trying to reproduce the problem but it seems to be working fine for me. The program that you shared isn't entirely complete (it's just a function and misses a few pieces), so I came up with this straightforward repro:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

let zipFile = new pulumi.asset.FileArchive("./Handler.zip")
const bucket = new aws.s3.Bucket("s3-bucket");

const siteObject = new aws.s3.BucketObject("s3-object", {
    bucket: bucket,
    source: zipFile,
});

```

I have a `Handler.zip` file in my application folder. `pulumi up` actually works and deploys the Bucket Object successfully. Could you run the same program and let me know if it fails for you?
