### ISSUE TITLE
Panic in waiting for Kuberentes Service Update

### ISSUE THREAD

**Issue by pquerna** [pulumi/pulumi#9655]
### What happened?

Panic while waiting for a Kubernetes Service to come up?

```
    ~ kubernetes:core/v1:Service: (update)
        [id=default/edge]
        [urn=urn:pulumi:sandbox-usw2a::app-60-60-app-zonal-services::kubernetes:core/v1:Service::edge-service]
        [provider=urn:pulumi:sandbox-usw2a::app-60-60-app-zonal-services::pulumi:providers:kubernetes::k8s::1eb4625c-f6ec-4f58-9d41-3963c0189712]
      ~ spec: {
          + externalTrafficPolicy: "local"
        }

Do you want to perform this update? yes
Updating (*****/sandbox-usw2a)

View Live: https://app.pulumi.com/*****/app-60-60-app-zonal-services/sandbox-usw2a/updates/6

     Type                           Name                                        Status                  Info
     pulumi:pulumi:Stack            app-60-60-app-zonal-services-sandbox-usw2a  **failed**              1 error; 25 messages
 ~   └─ kubernetes:core/v1:Service  edge-service                                **updating failed**     [diff: ~spec]; 1 error

Diagnostics:
  kubernetes:core/v1:Service (edge-service):
    error: transport is closing

  pulumi:pulumi:Stack (app-60-60-app-zonal-services-sandbox-usw2a):
    error: update failed

    panic: runtime error: [secret] memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2ad55c0]
    goroutine 129 [running]:
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/await.makeServiceInitAwaiter(0xc0009a6558, 0x3495fa0, 0xc0009a18c0, 0xc002314a80, 0x60, 0xc0024a9e9c, 0x2, 0xc0026373c0, 0xc00073cae0, 0xc0023252e8, ...)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/await/service.go:84 +0x60
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/await.awaitServiceUpdate(0xc0009a6558, 0x3495fa0, 0xc0009a18c0, 0xc002314a80, 0x60, 0xc0024a9e9c, 0x2, 0xc0026373c0, 0xc00073cae0, 0xc0023252e8, ...)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/await/service.go:112 +0x3d
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/await.Update(0x3495fa0, 0xc0009a18c0, 0xc0009a6558, 0xc002314a80, 0x60, 0xc0024a9e9c, 0x2, 0x0, 0x0, 0xc00073cae0, ...)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/await/await.go:430 +0xb35
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.(*kubeProvider).Update(0xc000582600, 0x3496048, 0xc00262b380, 0xc002624280, 0xc000582600, 0x2dccf01, 0xc002636b40)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:2166 +0xfc5
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1(0x3496048, 0xc00262b380, 0x2fed860, 0xc002624280, 0x2fd9900, 0x46b6dc8, 0x3496048, 0xc00262b380)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/proto/go/provider.pb.go:2638 +0x8b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3496048, 0xc00262a0c0, 0x2fed860, 0xc002624280, 0xc00262c0c0, 0xc002628228, 0x0, 0x0, 0x344ba20, 0xc0003a2d60)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler(0x307cb40, 0xc000582600, 0x3496048, 0xc00262a0c0, 0xc0024e99e0, 0xc0009a58a0, 0x3496048, 0xc00262a0c0, 0xc002610a80, 0xa4e)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/proto/go/provider.pb.go:2640 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00021f340, 0x34b2f78, 0xc000502000, 0xc002626d80, 0xc0009f6360, 0x4653730, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc00021f340, 0x34b2f78, 0xc000502000, 0xc002626d80, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000274040, 0xc00021f340, 0x34b2f78, 0xc000502000, 0xc002626d80)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:932 +0x1fd
```

### Steps to reproduce

Attempted to modify an existing NodePort service, adding `ExternalTrafficPolicy=local` to the Spec.

### Expected Behavior

Service is updated without a panic

### Actual Behavior

Panic.

### Versions used

❯ pulumi version
v3.30.0

❯ grep pulumi/pulumi-kubernetes vendor/modules.txt
github.com/pulumi/pulumi-kubernetes/sdk/v3 v3.12.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pquerna** [comment]
Upgrading pulumi-kubernetes, caused the error to:
```
    	* the Kubernetes API server reported that "default/edge" failed to fully initialize or become live: Service "edge" is [secret]: spec.externalTrafficPolicy: Invalid value: "local": ExternalTrafficPolicy must be empty, Cluster or Local
 ```

instead of a panic.

fixing the `local` -> `Local` and was able to up.
