### ISSUE TITLE
Panic: concurrent write to map in tests with trunk Pulumi

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#9667]
Updating the Pulumi pkg dependency to latest in Pulumi YAML results in concurrent map writes. A workaround is included in pulumi/pulumi-yaml#195 as it depends on recently merged codegen improvements to add mutexes, but these should be considered temporary.

Output:

```
$ make test_short
go test --timeout 30m -short -count 1 -parallel 10 ./pkg/...
ok      github.com/pulumi/pulumi-yaml/pkg/pulumiyaml    1.694s
ok      github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/ast        0.010s
fatal error: concurrent map writes

goroutine 68 [running]:
runtime.throw({0x1abe26b?, 0x18?})
        /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0027a2778 sp=0xc0027a2748 pc=0x437f51
runtime.mapassign_faststr(0xc00cc71b00?, 0xc00e865645?, {0xc00e865645, 0x4e})
        /usr/local/go/src/runtime/map_faststr.go:212 +0x39c fp=0xc0027a27e0 sp=0xc0027a2778 pc=0x4153bc
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindResourceTypeDef(0xc00cc71b00, {0xc00e865645, 0x4e})
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:693 +0x105 fp=0xc0027a2838 sp=0xc0027a27e0 pc=0xdbd6c5
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).finishResources(0xc00cc71b00, {0xc00d64c000, 0xd6, 0x7ff1845d6fff?})
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:1431 +0x2ff fp=0xc0027a2970 sp=0xc0027a2838 pc=0xdc707f
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*PartialPackage).Definition(0xc00d60c6c0)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/package_reference.go:390 +0xa5 fp=0xc0027a2a68 sp=0xc0027a2970 pc=0xdcaa25
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*pluginLoader).LoadPackage(0x1aa03f6?, {0xc00df80480?, 0x0?}, 0xc00e6aaff0?)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/loader.go:140 +0x42 fp=0xc0027a2a98 sp=0xc0027a2a68 pc=0xdc9262
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.testPackageLoader.LoadPackage({0xc00df80480?}, {0xc00df80480?, 0x1aa03f6?})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen/gen_program_test.go:58 +0x5c fp=0xc0027a2ac8 sp=0xc0027a2a98 pc=0x164707c
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.loadPackage({0x1e55430, 0xc00031d1e0}, {0xc00df80480, 0x1d})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/packages.go:214 +0xb8 fp=0xc0027a2b58 sp=0xc0027a2ac8 pc=0xeb6978
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.ResolveResource({0x1e55430, 0xc00031d1e0}, {0xc00df80480, 0x1d})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/packages.go:248 +0xaa fp=0xc0027a2bd0 sp=0xc0027a2b58 pc=0xeb6b8a
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*typeCache).typeResource(0xc00ab03fa0, 0xc00ab32580, {{{0x1e4d7c0, 0xc00e6ac580}, 0xc00ab01880, {0x1e53068, 0xc00e6aa3c0}}, 0xc00e6acae0, 0xc0006f40f0})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/analyser.go:24 +0x17b fp=0xc0027a3320 sp=0xc0027a2bd0 pc=0xeb201b
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*typeCache).typeResource-fm(0x0?, {{{0x1e4d7c0, 0xc00e6ac580}, 0xc00ab01880, {0x1e53068, 0xc00e6aa3c0}}, 0xc00e6acae0, 0xc0006f40f0})
        <autogenerated>:1 +0x89 fp=0xc0027a3378 sp=0xc0027a3320 pc=0xec84e9
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.walker.EvalResource({0x0, 0x0, 0x0, 0xc00ab03fb0, 0xc00ab03fc0}, 0xc00ab32580, {{{0x1e4d7c0, 0xc00e6ac580}, 0xc00ab01880, {0x1e53068, ...}}, ...})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/analyser.go:295 +0xa8 fp=0xc0027a35b0 sp=0xc0027a3378 pc=0xeb4f88
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*walker).EvalResource(0x1ac5881?, 0xc00dfb62d0?, {{{0x1e4d7c0, 0xc00e6ac580}, 0xc00ab01880, {0x1e53068, 0xc00e6aa3c0}}, 0xc00e6acae0, 0xc0006f40f0})
        <autogenerated>:1 +0xee fp=0xc0027a3650 sp=0xc0027a35b0 pc=0xec89ae
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*runner).Run(0xc00ab32580, {0x1e5b3d0, 0xc00e6aaf60})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/run.go:528 +0x36e fp=0xc0027a37f0 sp=0xc0027a3650 pc=0xebbc2e
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.TypeCheck(0xc00e6aadb0?)
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/analyser.go:184 +0x12f fp=0xc0027a3850 sp=0xc0027a37f0 pc=0xeb40af
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.RunTemplate(0xc00070e780, 0xc00dfb04e0, {0x1e55430?, 0xc00031d1e0})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/run.go:181 +0x16f fp=0xc0027a38f8 sp=0xc0027a3850 pc=0xeb93af
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.TestGenerateProgram.func2.1(0x1aa2300?)
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen/gen_program_test.go:218 +0x28 fp=0xc0027a3928 sp=0xc0027a38f8 pc=0x16481e8
github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc00070e780, 0xc000569ca0)
        /home/friel/go/src/github.com/pulumi/pulumi/sdk/go/pulumi/run.go:103 +0x199 fp=0xc0027a3a78 sp=0xc0027a3928 pc=0xe72819
github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunErr(0x1e4c5c0?, {0xc000569c88, 0x1, 0x1aa0451?})
        /home/friel/go/src/github.com/pulumi/pulumi/sdk/go/pulumi/run.go:84 +0x310 fp=0xc0027a3c08 sp=0xc0027a3a78 pc=0xe724d0
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.TestGenerateProgram.func2(0xc00031d1e0, {0xc0001261e0, 0x4b}, 0xa?)
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen/gen_program_test.go:217 +0x271 fp=0xc0027a3d00 sp=0xc0027a3c08 pc=0x1648151
github.com/pulumi/pulumi/pkg/v3/codegen/testing/test.TestProgramCodegen.func1(0xc00031d1e0)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/testing/test/program_driver.go:295 +0xc74 fp=0xc0027a3f70 sp=0xc0027a3d00 pc=0x162b214
testing.tRunner(0xc00031d1e0, 0xc0002a0e60)
        /usr/local/go/src/testing/testing.go:1439 +0x102 fp=0xc0027a3fc0 sp=0xc0027a3f70 pc=0x51d2a2
testing.(*T).Run.func1()
        /usr/local/go/src/testing/testing.go:1486 +0x2a fp=0xc0027a3fe0 sp=0xc0027a3fc0 pc=0x51e14a
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0027a3fe8 sp=0xc0027a3fe0 pc=0x46b0c1
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1486 +0x35f

goroutine 61 [runnable]:
reflect.mapassign(0x17fd720, 0xc00f01e210?, 0xc00db0811a?, 0x1ac6a2e?)
        /usr/local/go/src/runtime/map.go:1351 +0x25
reflect.Value.SetMapIndex({0x17fd720?, 0xc00f01a360?, 0x1df2?}, {0x1756d40, 0xc00efe2e70, 0x198}, {0x1a29b80, 0xc00f01e210, 0x199})
        /usr/local/go/src/reflect/value.go:2253 +0x3a8
github.com/segmentio/encoding/json.decoder.decodeMap({0x23?}, {0xc00db06538, 0x398b, 0x172aea}, 0xc00efec690, {0x1e674c0?, 0x17fd720}, {0x1e674c0, 0x1756d40}, {0x1e674c0, ...}, ...)
        /home/friel/go/pkg/mod/github.com/segmentio/encoding@v0.3.5/json/decode.go:719 +0x36e
github.com/segmentio/encoding/json.constructMapDecodeFunc.func1({0x3a3080?}, {0xc00db06538?, 0x80?, 0xc00db0652b?}, 0xa?)
        /home/friel/go/pkg/mod/github.com/segmentio/encoding@v0.3.5/json/codec.go:460 +0x108
github.com/segmentio/encoding/json.decoder.decodeStruct({0x20305c?}, {0xc00db064e7, 0x39dc, 0x172b3b}, 0xc00efec680, 0xc000b22120)
        /home/friel/go/pkg/mod/github.com/segmentio/encoding@v0.3.5/json/decode.go:1212 +0x426
github.com/segmentio/encoding/json.constructStructDecodeFunc.func1({0xdb064e7?}, {0xc00db064e7?, 0x18c49e0?, 0x80?}, 0x0?)
        /home/friel/go/pkg/mod/github.com/segmentio/encoding@v0.3.5/json/codec.go:522 +0x25
github.com/segmentio/encoding/json.Parse({0xc00db064e7, 0x39dc, 0x172b3b}, {0x17079c0, 0xc00efec680}, 0x1c)
        /home/friel/go/pkg/mod/github.com/segmentio/encoding@v0.3.5/json/json.go:329 +0x203
github.com/pulumi/pulumi/pkg/v3/codegen/schema.parseJSONPropertyValue(...)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/package_reference.go:620
github.com/pulumi/pulumi/pkg/v3/codegen/schema.partialPackageSpecSource.GetTypeDefSpec({0xc00e986000?}, {0xc00db0c531?, 0xc00efebc20?})
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:365 +0xb9
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindTypeDef(0xc00e990000, {0xc00db0c531, 0x1a})
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:648 +0xb9
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindTypeSpecRef(0xc00e990000, {0xc00def7ac0?, 0xc00e9c40d8?}, {{0x0, 0x0}, {0xc00db0c529, 0x22}, 0x0, 0x0, {0x0, ...}, ...}, ...)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:756 +0xa48
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindTypeSpec(0x17fd780?, {0xc00def7ac0?, 0x79?}, {{0x0, 0x0}, {0xc00db0c529, 0x22}, 0x0, 0x0, {0x0, ...}, ...}, ...)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:854 +0x117a
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindProperties(0xc00e990000, {0xc00def7a00, 0x37}, 0x1000000000076?, {0xc00def7a40, 0x35}, {0x0, 0x0, 0x40f434?}, 0x0)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:1028 +0x20e
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindObjectTypeDetails(0xc00e990000, {0xc000677bf0, 0x2c}, 0xc00f0136c0, {0xc00da7a4d4, 0x22}, {{0xc00db0c39f, 0x51}, 0xc00f01a2a0, {0xc00db0c62c, ...}, ...})
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:1091 +0x1b0
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindTypeDef(0xc00e990000, {0xc00da7a4d4, 0x22})
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:667 +0x325
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindTypeSpecRef(0xc00e990000, {0xc00def79c0?, 0xc00e9c4d88?}, {{0x0, 0x0}, {0xc00da7a4cc, 0x2a}, 0x0, 0x0, {0x0, ...}, ...}, ...)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:756 +0xa48
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindTypeSpec(0xc00e990000?, {0xc00def79c0?, 0x4a?}, {{0x0, 0x0}, {0xc00da7a4cc, 0x2a}, 0x0, 0x0, {0x0, ...}, ...}, ...)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:854 +0x117a
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindProperties(0xc00e990000, {0xc00def7900, 0x35}, 0x1000000000076?, {0xc00def7940, 0x33}, {0xc00efc6e60, 0x2, 0x40f434?}, 0x0)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:1028 +0x20e
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindObjectTypeDetails(0xc00e990000, {0xc000677b90, 0x2a}, 0xc00f013490, {0xc00dbbf951, 0x20}, {{0xc00da7a0ae, 0x33}, 0xc00f01a180, {0xc00da7a748, ...}, ...})
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:1091 +0x1b0
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindTypeDef(0xc00e990000, {0xc00dbbf951, 0x20})
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:667 +0x325
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindTypeSpecRef(0xc00e990000, {0xc00def7880?, 0x2d?}, {{0x0, 0x0}, {0xc00dbbf949, 0x28}, 0x0, 0x0, {0x0, ...}, ...}, ...)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:756 +0xa48
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindTypeSpec(0xc00e990000?, {0xc00def7880?, 0x3a?}, {{0x0, 0x0}, {0xc00dbbf949, 0x28}, 0x0, 0x0, {0x0, ...}, ...}, ...)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:854 +0x117a
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindProperties(0xc00e990000, {0xc00def76c0, 0x35}, 0x172dfe0?, {0xc00def7700, 0x33}, {0x0, 0x0, 0xc00dbc0253?}, 0x0)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:1028 +0x20e
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindResourceDetails(0xc00e990000, {0xc000677b30, _}, {_, _}, {{{0xc00dbbf4a8, 0x37}, 0xc00f01a030, {0xc00dbbfbb2, 0x6}, ...}, ...}, ...)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:1320 +0x2bf
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindResourceDef(0xc00e990000, {0xc00dbbf471, 0x1c})
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:1301 +0x23f
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindResourceTypeDef(0xc00e990000, {0xc00dbbf471, 0x1c})
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:685 +0x65
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).finishResources(0xc00e990000, {0xc000728880, 0xd6, 0x99?})
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/bind.go:1431 +0x2ff
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*PartialPackage).Definition(0xc00e992000)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/package_reference.go:390 +0xa5
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*pluginLoader).LoadPackage(0x1aa03f6?, {0xc00050f300?, 0x0?}, 0xc00d7fa240?)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/schema/loader.go:140 +0x42
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.testPackageLoader.LoadPackage({0xc00050f300?}, {0xc00050f300?, 0x1aa03f6?})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen/gen_program_test.go:58 +0x5c
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.loadPackage({0x1e55430, 0xc0000c8b60}, {0xc00050f300, 0x1d})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/packages.go:214 +0xb8
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.ResolveResource({0x1e55430, 0xc0000c8b60}, {0xc00050f300, 0x1d})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/packages.go:248 +0xaa
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*typeCache).typeResource(0xc00d7ed110, 0xc000814700, {{{0x1e4d7c0, 0xc00d7f8340}, 0xc00ce4f6e0, {0x1e53068, 0xc00d7f15f0}}, 0xc00d7f8780, 0xc000225860})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/analyser.go:24 +0x17b
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.walker.EvalResource({0x0, 0x0, 0x0, 0xc00d7ed120, 0xc00d7ed130}, 0xc000814700, {{{0x1e4d7c0, 0xc00d7f8340}, 0xc00ce4f6e0, {0x1e53068, ...}}, ...})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/analyser.go:295 +0xa8
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.(*runner).Run(0xc000814700, {0x1e5b3d0, 0xc00d7fa1b0})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/run.go:528 +0x36e
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.TypeCheck(0xc00d7fa000?)
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/analyser.go:184 +0x12f
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml.RunTemplate(0xc00072f540, 0xc00081c820, {0x1e55430?, 0xc0000c8b60})
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/run.go:181 +0x16f
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.TestGenerateProgram.func2.1(0x1aa2300?)
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen/gen_program_test.go:218 +0x28
github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc00072f540, 0xc0009ebca0)
        /home/friel/go/src/github.com/pulumi/pulumi/sdk/go/pulumi/run.go:103 +0x199
github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunErr(0x1e4c5c0?, {0xc0009ebc88, 0x1, 0x1aa0451?})
        /home/friel/go/src/github.com/pulumi/pulumi/sdk/go/pulumi/run.go:84 +0x310
github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen.TestGenerateProgram.func2(0xc0000c8b60, {0xc00004b900, 0x4d}, 0xa?)
        /home/friel/go/src/github.com/pulumi/pulumi-yaml/pkg/pulumiyaml/codegen/gen_program_test.go:217 +0x271
github.com/pulumi/pulumi/pkg/v3/codegen/testing/test.TestProgramCodegen.func1(0xc0000c8b60)
        /home/friel/go/src/github.com/pulumi/pulumi/pkg/codegen/testing/test/program_driver.go:295 +0xc74
testing.tRunner(0xc0000c8b60, 0xc000733b80)
        /usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1486 +0x35f
```

**Comment by AaronFriel** [comment]
We likely just to acquire the lock on the receiver around the call to `Definition` here:
https://github.com/pulumi/pulumi/blob/36cbf572f45790f6859a8da3f8d67f6b32620fca/pkg/codegen/schema/loader.go#L135-L141

Or we could add mutex(es) to the `PartialPackage` type and implement it to prevent concurrent writes to the `types` property.

**Comment by AaronFriel** [comment]
Reduced severity as our next release is on 6/1.
