### ISSUE TITLE
panic: reflect: NumField of non-struct type pulumi.Output

### ISSUE THREAD

**Issue by rodrigobrim** [pulumi/pulumi#9682]
### What happened?

After upgrading github.com/pulumi/pulumi-eks/sdk from v0.35.0 to v0.40.0, the following error appears:

 
    panic: reflect: NumField of non-struct type pulumi.Output
    goroutine 1 [running]:
    reflect.(*rtype).NumField(0x506fec0)
        /usr/local/go/src/reflect/type.go:1015 +0x66
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.newOutput(0x506fe40, {0x2bad3f0, 0x225dc00}, {0xc0003b1430, 0x1, 0x1})
        /tmp/my-project/vendor/github.com/pulumi/pulumi/sdk/v3/go/pulumi/types.go:299 +0x2d9
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*OutputState).ApplyTWithContext(0xc0002cdf80, {0x2b37dd8, 0xc000076130}, {0xc0005971a0, 0xc0005ab140})
        /tmp/my-project/vendor/github.com/pulumi/pulumi/sdk/v3/go/pulumi/types.go:472 +0x199
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*OutputState).ApplyT(0xc0002cdf80, {0x1f40660, 0xc000597140})
        /tmp/my-project/vendor/github.com/pulumi/pulumi/sdk/v3/go/pulumi/types.go:430 +0x79
    aws-package-manager/src/projects/rspm/configs/cluster.serviceAccountAssumeRole(0xc00065b500, {0x28172eb, 0x16}, {{0xc000148380, 0x360}, {0x280abc8, 0x7}, 0xc0005ae9c0, 0xc00053e000, {0xc0002cdf80}})
        /tmp/my-project/src/projects/rspm/configs/cluster/cluster.go:604 +0x125
    aws-package-manager/src/projects/rspm/configs/cluster.installAlb(0xc00012e140, {{0xc000148380, 0x360}, {0x280abc8, 0x7}, 0xc0005ae9c0, 0xc00053e000, {0xc0002cdf80}})
        /tmp/my-project/src/projects/rspm/configs/cluster/cluster.go:436 +0x1c5
    aws-package-manager/src/projects/rspm/configs/cluster.Configure(0x2107080, {{0xc000148380, 0x360}, {0x280abc8, 0x7}, 0xc0005ae9c0, 0xc00053e000, {0xc0002cdf80}})
        /tmp/my-project/src/projects/rspm/configs/cluster/cluster.go:233 +0x165
    aws-package-manager/src/projects/rspm.Create(0xc00012e140, 0xc00013c0c0)
        /tmp/my-project/src/projects/rspm/main.go:102 +0x7c5
    main.main.func1(0xc00012e140)
        /tmp/my-project/main.go:32 +0x166
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc00012e140, 0x287ffd0)
        /tmp/my-project/vendor/github.com/pulumi/pulumi/sdk/v3/go/pulumi/run.go:103 +0x199
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunErr(0x43f225, {0x0, 0x0, 0xc0000001a0})
        /tmp/my-project/vendor/github.com/pulumi/pulumi/sdk/v3/go/pulumi/run.go:84 +0x310
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.Run(0x0, {0x0, 0x1eb6ce0, 0xc0000001a0})
        /tmp/my-project/vendor/github.com/pulumi/pulumi/sdk/v3/go/pulumi/run.go:41 +0x25
    main.main()
        /tmp/my-project/main.go:19 +0x27
    exit status 2

### Steps to reproduce

Running the following ApplyT function:

```
func serviceAccountAssumeRole(ctx *pulumi.Context, saName string, settings ConfigureSettings) pulumi.Output {

	awsCallerId, err := aws.GetCallerIdentity(ctx, nil, nil)
	if err != nil {
		return nil
	}
	return settings.OidcProvider.ApplyT(
		func(oidc *iam.OpenIdConnectProvider) pulumi.Output {
			if oidc != nil {
				r := oidc.Url.ApplyT(func(i interface{}) pulumi.String {
					url := ""
					if i != nil {
						url = fmt.Sprint(i)
					}
					json, err := json.Marshal(map[string]interface{}{
						"Version": "2012-10-17",
						"Statement": []map[string]interface{}{
							map[string]interface{}{
								"Action": "sts:AssumeRoleWithWebIdentity",
								"Effect": "Allow",
								"Principal": map[string]interface{}{
									"Federated": strings.Join([]string{"arn:aws:iam::", awsCallerId.AccountId, ":oidc-provider/", url}, ""),
								},
								"Condition": map[string]interface{}{
									"StringEquals": map[string]interface{}{
										strings.Join([]string{url, ":sub"}, ""): strings.Join([]string{"system:serviceaccount:", settings.Namespace, ":", saName}, ""),
										strings.Join([]string{url, ":aud"}, ""): "sts.amazonaws.com",
									},
								},
							},
						},
					})
					if err != nil {
						panic(err)
					}
					return pulumi.String(string(json))
				})
				return r
			} else {
				return pulumi.String("").ToStringOutput()
			}
		})
}
```

### Expected Behavior

Success.

### Actual Behavior

error: an unhandled error occurred: program exited with non-zero exit code: 1

### Versions used

$ pulumi about
CLI          
Version      3.32.1
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.4.0
aws         4.38.1
eks         0.40.0
go          unknown
kubernetes  3.19.1

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in go (/usr/local/go/bin/go v1.17.6 linux/amd64)

Current Stack: staging

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:staging::my-project::pulumi:pulumi:Stack::my-project-staging
pulumi:providers:aws                                 urn:pulumi:staging::my-project::pulumi:providers:aws::default
aws:ec2/eip:Eip                                      urn:pulumi:staging::my-project::aws:ec2/eip:Eip::pubSubnet3
aws:ec2/eip:Eip                                      urn:pulumi:staging::my-project::aws:ec2/eip:Eip::pubSubnet1
aws:ec2/eip:Eip                                      urn:pulumi:staging::my-project::aws:ec2/eip:Eip::pubSubnet2
aws:ec2/vpc:Vpc                                      urn:pulumi:staging::my-project::aws:ec2/vpc:Vpc::my-project
aws:iam/role:Role                                    urn:pulumi:staging::my-project::aws:iam/role:Role::my-project-team-account
aws:iam/role:Role                                    urn:pulumi:staging::my-project::aws:iam/role:Role::my-project-eks-cluster
aws:iam/role:Role                                    urn:pulumi:staging::my-project::aws:iam/role:Role::my-project-eks-nodes
aws:acm/certificate:Certificate                      urn:pulumi:staging::my-project::aws:acm/certificate:Certificate::*.staging.myname.com
aws:iam/openIdConnectProvider:OpenIdConnectProvider  urn:pulumi:staging::my-project::aws:iam/openIdConnectProvider:OpenIdConnectProvider::github-actions
aws:s3/bucket:Bucket                                 urn:pulumi:staging::my-project::aws:s3/bucket:Bucket::helm-my-project-staging

Found no pending operations associated with staging

Backend        
Name           xps9300
URL            s3://my-project-stacks
User           rodrigo
Organizations  

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's plugins: Failed to get modules: exit status 1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already). 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
@rodrigobrim could you tell me what version of `pulumi/sdk/v3` is in the go.mod and if it's less than 3.33, could you try updating it to our latest 3.33.1 and try again?

**Comment by rodrigobrim** [comment]
@AaronFriel, I'm already using the github.com/pulumi/pulumi/sdk/v3/go/pulumi@v3.33.1, which seems to be the cause of the error.

If I return to v3.27.0, the error is gone.

**Comment by AaronFriel** [comment]
Hey @rodrigobrim, could you try the changes below with your program?

I think this is due to us relaxing the rules on what we allow in ApplyT, to allow nested Outputs, but we may need to warn or error when an abstract `Output` is the return type. We use Go's reflection capabilities to get the return type of the function passed to ApplyT. 

```go
	return settings.OidcProvider.ApplyT(
                // 🆕 change this to require a concrete output type
		func(oidc *iam.OpenIdConnectProvider) pulumi.StringOutput {
			if oidc != nil {
				r := oidc.Url.ApplyT(func(i interface{}) pulumi.String {
					url := ""
					if i != nil {
						url = fmt.Sprint(i)
					}
					json, err := json.Marshal(map[string]interface{}{
						"Version": "2012-10-17",
						"Statement": []map[string]interface{}{
							map[string]interface{}{
								"Action": "sts:AssumeRoleWithWebIdentity",
								"Effect": "Allow",
								"Principal": map[string]interface{}{
									"Federated": strings.Join([]string{"arn:aws:iam::", awsCallerId.AccountId, ":oidc-provider/", url}, ""),
								},
								"Condition": map[string]interface{}{
									"StringEquals": map[string]interface{}{
										strings.Join([]string{url, ":sub"}, ""): strings.Join([]string{"system:serviceaccount:", settings.Namespace, ":", saName}, ""),
										strings.Join([]string{url, ":aud"}, ""): "sts.amazonaws.com",
									},
								},
							},
						},
					})
					if err != nil {
						panic(err)
					}
					return pulumi.String(string(json))
                                // 🆕 change this to cast to StringOutput
				}).(pulumi.StringOutput)
				return r
			} else {
				return pulumi.String("").ToStringOutput()
			}
		})
```

**Comment by rodrigobrim** [comment]
The suggested changes throw the following error:

```
    panic: interface conversion: pulumi.Output is pulumi.AnyOutput, not pulumi.StringOutput
    goroutine 168 [running]:
```

But worked with the following changes:

`func(oidc *iam.OpenIdConnectProvider) pulumi.AnyOutput {`
`}).(pulumi.AnyOutput)`

Thank you!
