### ISSUE TITLE
The Pulumi CLI encountered a fatal error. This is a bug! pulumi <<differen options>> doesn't work anymore

### ISSUE THREAD

**Issue by Daldor** [pulumi/pulumi#9714]
### What happened?

The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.24.1
Go Version:       go1.17.6
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            attempt to decrypt value

goroutine 1 [running]:
runtime/debug.Stack()
        /Users/runner/hostedtoolcache/go/1.17.6/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x17aa1a0, 0x1e45220})
        /Users/runner/hostedtoolcache/go/1.17.6/x64/src/runtime/panic.go:1038 +0x215
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.panicCrypter.DecryptValue(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/resource/config/crypt.go:222
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializePropertyValue({0x18512e0, 0xc00044b3e0}, {0x7f3cef11ece0, 0x2ca9680}, {0x7f3cef11ed08, 0x2ca9680})
        /Users/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:606 +0x3b5
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeProperties(0xc00044b4d0, {0x7f3cef11ece0, 0x2ca9680}, {0x7f3cef11ed08, 0x2ca9680})
        /Users/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:533 +0xeb
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeResource({{0xc0006a6720, 0x5f}, 0x1, 0x0, {0xc0006a6780, 0x59}, {0xc000b17c20, 0x24}, 0xc00044b380, 0xc00044b3b0, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:495 +0xa5
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeDeploymentV3({{{0x2ac43e3f, 0xeda22c2ee, 0x2c78d80}, {0xc000374b00, 0x40}, {0xc0007a5380, 0x7}, {0x0, 0x0, 0x0}}, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:263 +0x748
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeCheckpoint(0xc00043cde0)
        /Users/runner/work/pulumi/pulumi/pkg/resource/stack/checkpoint.go:111 +0xd8
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).getStack(0xc0004d18f0, {0xc0007a4640, 0xc000cf1ad0})
        /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/state.go:140 +0xcf
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).GetStack(0xc0006cfe00, {0xc0007a4640, 0x0}, {0x1e8d440, 0xc0004d18f0})
        /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:321 +0x45
github.com/pulumi/pulumi/pkg/v3/backend/state.CurrentStack({0x1ea2548, 0xc00003e078}, {0x1ef0570, 0xc0006cfe00})
        /Users/runner/work/pulumi/pulumi/pkg/backend/state/stacks.go:41 +0x93
main.runStackLS({0x0, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}})
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/stack_ls.go:136 +0x2fc
main.newStackLsCmd.func1(0x2, {0x5020105, 0x2, 0xc000cf1d78})
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/stack_ls.go:64 +0xb3
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunFunc.func1(0x11, {0x2ca9680, 0xc000cf1d90, 0x5e56d3})
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:96 +0x26
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc0006d98c0, {0x2ca9680, 0x0, 0x0})
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc0006d98c0, {0x2ca9680, 0x0, 0x0})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000b1cb00)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()

### Steps to reproduce

- Set passphrase to ""
- updated stack
- pulumi up didn't work -> `PULUMI_CONFIG_PASSPHRASE` or `PULUMI_CONFIG_PASSPHRASE_FILE` not found/set
- removed secrets_part from stack.json, as I did before

### Expected Behavior

Update stack

### Actual Behavior

bug message

### Additional context

after moving faulty stack.json everything works fine again -> My problem is solved
passphrase stuff pretty annoying
commands related to stack (pulumi inventory -> sth i'd guess didn't  work anymore)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Daldor** [comment]
after moving faulty stack.json everything works fine again -> My problem is solved
passphrase stuff pretty annoying
commands related to stack (pulumi inventory -> sth i'd guess didn't  work anymore)

**Comment by Daldor** [comment]
after moving faulty stack.json everything works fine again -> My problem is solved
passphrase stuff pretty annoying
commands related to stack (pulumi inventory -> sth i'd guess didn't  work anymore)
