### ISSUE TITLE
Error: Should not have seen an older plugin if sorting is correct!

### ISSUE THREAD

**Issue by ianaya89** [pulumi/pulumi#9759]
### What happened?

Getting a panic error when trying to run `pulumi up` with the Checkly provider I built. 

```
Pulumi Version:   v3.33.2
Go Version:       go1.18.2
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: A failure has occurred: Should not have seen an older plugin if sorting is correct!
  checkly/pulumi-0.0.1-alpha.10
  checkly/pulumi-0.0.1-alpha.10+dirty -

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/Cellar/go/1.18.2/libexec/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x5618840, 0xc000dc0ff0})
	/usr/local/Cellar/go/1.18.2/libexec/src/runtime/panic.go:838 +0x207
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20220527-4545-6ymlri/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf({0x5a53f5c?, 0x14?}, {0xc000f42b10?, 0xc000db2640?, 0x2?})
	/private/tmp/pulumi-20220527-4545-6ymlri/sdk/go/common/util/contract/fail.go:30 +0xcd
github.com/pulumi/pulumi/pkg/v3/engine.computeDefaultProviderPlugins(0xc000d91110, 0xc000dbe840)
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/engine/plugins.go:284 +0xec5
github.com/pulumi/pulumi/pkg/v3/engine.installPlugins(0x0?, {0xc0004c91c0?, 0x4a2f889?}, {0x59cda0d?, 0x31?}, 0xc0004c91c0?, 0x31?, 0x0)
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/engine/update.go:255 +0x197
github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource({_, _}, {{{0x6c893b8, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/engine/update.go:377 +0x7b
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x6c893b8, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/engine/deployment.go:159 +0x259
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x6c893b8, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/engine/update.go:451 +0x391
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x5e17568, 0xc000f662d0}, 0xc000165d40, {{0x6c893b8, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, ...}, ...)
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/engine/update.go:195 +0x670
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc0005f01b0, {0xc0004c91c0, 0x31}, ...}, ...)
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/backend/httpstate/backend.go:1075 +0x93b
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc0005f01b0, {0xc0004c91c0, 0x31}, ...}, ...)
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/backend/httpstate/backend.go:982 +0x418
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt({_, _}, {_, _}, {_, _}, {0xc0005f01b0, {0xc0004c91c0, 0x31}, {0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/backend/apply.go:115 +0x17a
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc0005f01b0, {0xc0004c91c0, 0x31}, {0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/backend/apply.go:209 +0x125
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Update(_, {_, _}, {_, _}, {0xc0005f01b0, {0xc0004c91c0, 0x31}, {0x0, 0x0, ...}, ...})
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/backend/httpstate/backend.go:869 +0xb8
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc0005f01b0, {0xc0004c91c0, 0x31}, {0x0, 0x0, 0x0}, ...})
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/backend/stack.go:87 +0xbb
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Update(_, {_, _}, {0xc0005f01b0, {0xc0004c91c0, 0x31}, {0x0, 0x0, 0x0}, 0xc000112c90, ...})
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/backend/httpstate/stack.go:151 +0x68
main.newUpCmd.func1({{{0x6c893b8, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, 0x0, {0x6c893b8, ...}, ...}, ...})
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/cmd/pulumi/up.go:179 +0xcec
main.newUpCmd.func3(0x29?, {0x6c893b8, 0x0, 0x41fffa5?})
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/cmd/pulumi/up.go:453 +0x595
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000bfaf00?, {0x6c893b8, 0x0, 0x0})
	/private/tmp/pulumi-20220527-4545-6ymlri/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000bfaf00, {0x6c893b8, 0x0, 0x0})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000bfaa00)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/private/tmp/pulumi-20220527-4545-6ymlri/pkg/cmd/pulumi/main.go:48 +0x45
````

### Steps to reproduce

1. Create a JS file with some Checkly resources
2. Install nodejs checkly provider: `npm i -S @checkly/pulumi`
3. Run `pulumi up`

Here a project sample 👇
[demo.zip](https://github.com/pulumi/pulumi/files/8819038/demo.zip)

### Expected Behavior

Apply Checkly resources successfully after running `up` command.

### Actual Behavior

Not able to apply any change and getting a GO panic message when trying to run `up` command.

### Versions used

```
CLI
Version      3.33.2
Go Version   go1.18.2
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  12.3.1
Arch     x86_64

This project is written in nodejs (/Users/ianaya89/.nvm/versions/node/v14.17.3/bin/node v14.17.3)

Current Stack: local

Found no resources associated with local

Found no pending operations associated with local

Backend
Name           pulumi.com
URL            https://app.pulumi.com/ianaya89
User           ianaya89
Organizations  ianaya89

Pulumi locates its logs in /var/folders/t1/s8kvbsd913q1qy9fqp058g6r0000gn/T/ by default
warning: Failed to get information about the Pulumi program's plugins: Failed to run "/Users/ianaya89/.nvm/versions/node/v14.17.3/bin/npm ls --json --depth=0": exit status 1
```

### Additional context

- Checkly Provider repository https://github.com/checkly/pulumi-checkly
- Checkly Provider npm package https://www.npmjs.com/package/@checkly/pulumi

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ianaya89** [comment]
@iwahbe Thanks for the quick response!
