### ISSUE TITLE
consider allowing users to run `pulumi up` via i.e. `python __main__.py` `go run main.go` `ts-node index.ts`

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#9772]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
I was trying to use pulumi and I ran `python __main__.py` and it threw an error
```bash
kdixler@kdixler-20xw004aus ~/Documents/aws-python % python __main__.py
Traceback (most recent call last):
  File "/home/kdixler/Documents/aws-python/__main__.py", line 7, in <module>
    bucket = s3.Bucket('my-bucket')
  File "/home/kdixler/Documents/aws-python/venv/lib/python3.10/site-packages/pulumi_aws/s3/bucket.py", line 1444, in __init__
    __self__._internal_init(resource_name, *args, **kwargs)
  File "/home/kdixler/Documents/aws-python/venv/lib/python3.10/site-packages/pulumi_aws/s3/bucket.py", line 1507, in _internal_init
    super(Bucket, __self__).__init__(
  File "/home/kdixler/Documents/aws-python/venv/lib/python3.10/site-packages/pulumi/resource.py", line 1081, in __init__
    Resource.__init__(self, t, name, True, props, opts, False, dependency)
  File "/home/kdixler/Documents/aws-python/venv/lib/python3.10/site-packages/pulumi/resource.py", line 941, in __init__
    register_resource(
  File "/home/kdixler/Documents/aws-python/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 489, in register_resource
    monitor = settings.get_monitor()
  File "/home/kdixler/Documents/aws-python/venv/lib/python3.10/site-packages/pulumi/runtime/settings.py", line 194, in get_monitor
    require_test_mode_enabled()
  File "/home/kdixler/Documents/aws-python/venv/lib/python3.10/site-packages/pulumi/runtime/settings.py", line 139, in require_test_mode_enabled
    raise RunError(
pulumi.errors.RunError: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
```

couldn't the Pulumi SDK figure out how to run my program using automation API and then do error recovery and drop me into the flow of `pulumi up`?

relates to:
#3901

**Comment by dixler** [comment]
duplicate of #5538
