### ISSUE TITLE
Fatal error in Pulumi CLI when destroying stacks with Automation API (3.34.0)

### ISSUE THREAD

**Issue by gustavclausen** [pulumi/pulumi#9815]
### What happened?

We encounter a fatal error with version 3.34.0 when destroying Pulumi stacks using the Automation API and Pulumi CLI.
We're using the Node.js SDK.

### Steps to reproduce

Call `Stack.destroy` with the Automation API (Node.js SDK).

### Expected Behavior

Stack is destroyed without any errors.

### Actual Behavior

A fatal error is thrown from the Pulumi CLI:
```
CommandError: code: 1
 stdout: 
 stderr: ================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.34.0
Go Version:       go1.17.11
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.17.11/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x1aef7e0, 0x3169060})
	/opt/hostedtoolcache/go/1.17.11/x64/src/runtime/panic.go:1038 +0x215
main.newDestroyCmd.func1(0x20, {0xc00020e5a0, 0xc00083fd90, 0x5f27c5})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/destroy.go:152 +0x8ef
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000879680, {0xc0008989a0, 0x0, 0x7})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc00087[968](<GITHUB ACTIONS RUN MASKED>)0, {0xc000898930, 0x7, 0x7})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000878c80)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
 err?: 
      at Object.createCommandError (node_modules/@pulumi/automation/errors.ts:73:21)
      at ChildProcess.<anonymous> (node_modules/@pulumi/automation/cmd.ts:80:31)
      at ChildProcess.emit (node:events:527:28)
      at ChildProcess.emit (node:domain:475:12)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

### Versions used

Pulumi CLI: `3.34.0`.
Pulumi Node.js SDK (@pulumi/pulumi): `3.34.0`.

### Additional context

The error doesn't occur with version 3.33.2 (both Pulumi CLI and Node.js SDK).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Looks like this was a mistake made in https://github.com/pulumi/pulumi/pull/9613 which changed how we loaded the secrets provider based on state and config.

**Comment by t0yv0** [comment]
Reproducible in pulumi/pulumi-java by `make test_example.minimal` at the destroy phase.

**Comment by t0yv0** [comment]
Reverting https://github.com/pulumi/pulumi/pull/9613 makes the test pass for me again. 👍
