### ISSUE TITLE
`pulumi convert` crashes due to unknown package version

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#9897]
If I try to convert a program that uses the [Pulumi Command](https://www.pulumi.com/registry/packages/command) package:

```
name: yamyam
runtime: yaml
resources:
  echo:
    type: command:local:Command
    properties:
      create: echo ''
```

It crashes:

```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   3.35.0-alpha.1655483272+2a07ed75.dirty
Go Version:       go1.17.4
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x56fa1e0, 0x6d6d9a0})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/pulumi/pulumi/pkg/v3/codegen/python.GenerateProject({0x7ff7bfeff765, 0x4}, {{0xc0003f66f0, 0x18}, {{0x59d22ca, 0x6}, 0x0}, {0x0, 0x0}, 0xc00027da70, ...}, ...)
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/codegen/python/gen_program.go:110 +0x278
main.newConvertCmd.func1(0xf, {0xc000b1cd00, 0xc000761d90, 0x41f0105})
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/convert.go:86 +0x39d
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000768780, {0xc00072d3c0, 0x0, 0x4})
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000768780, {0xc00072d380, 0x4, 0x4})
	/Users/joeduffy/dev/code/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000b27680)
	/Users/joeduffy/dev/code/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/joeduffy/dev/code/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/Users/joeduffy/dev/code/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
```

This is because, for some reason, `p.Version` is `nil` on this line:

https://github.com/pulumi/pulumi/blob/2a07ed754f9320a1761d5a8d94f647303b6ad816/pkg/codegen/python/gen_program.go#L110

**Comment by mikhailshilkov** [comment]
@joeduffy thank you for filing these issues. May I ask you to either use one of the existing issues templates, or mark your new issues with the `needs-triage` label? Unlabelled issues from Pulumians aren't currently highlighted in our triage queue. Thank you!

**Comment by AaronFriel** [comment]
Moving this to the `pulumi-command` repo. `Version` is a required field in the package schema spec. Fixing this panic internally is a much thornier problem, unfortunately.
